/** Alemão — verbos de ampliação. Nenhum repete o lote de `verbs.ts`. */

import type { ByLevel } from './entry';

export const DE: ByLevel = {
  A1: [
    ['kommen', '', 'vir', 'ich:komme|er:kommt|Perfekt:ist gekommen', 'Komm mit mir.', 'Venha comigo.', 'Perfeito com "sein": verbo de movimento.'],
    ['sehen', '', 'ver', 'ich:sehe|er:sieht|Perfekt:hat gesehen', 'Ich sehe den Bus.', 'Vejo o ônibus.', 'Muda a vogal na 2ª e 3ª pessoa: e → ie.'],
    ['wissen', '', 'saber', 'ich:weiß|er:weiß|Perfekt:hat gewusst', 'Ich weiß die Antwort.', 'Sei a resposta.', '"Wissen" é fato; "kennen" é pessoa ou lugar.'],
    ['kennen', '', 'conhecer', 'ich:kenne|er:kennt|Perfekt:hat gekannt', 'Ich kenne Berlin gut.', 'Conheço bem Berlim.', ''],
    ['sagen', '', 'dizer', 'ich:sage|er:sagt|Perfekt:hat gesagt', 'Er hat nein gesagt.', 'Ele disse não.', ''],
    ['essen', '', 'comer', 'ich:esse|er:isst|Perfekt:hat gegessen', 'Wir essen um zwölf.', 'A gente come ao meio-dia.', ''],
    ['trinken', '', 'beber', 'ich:trinke|er:trinkt|Perfekt:hat getrunken', 'Ich trinke Wasser.', 'Bebo água.', ''],
    ['wohnen', '', 'morar', 'ich:wohne|er:wohnt|Perfekt:hat gewohnt', 'Sie wohnen in Porto.', 'Eles moram no Porto.', '"Wohnen" é morar; "leben" é viver.'],
    ['arbeiten', '', 'trabalhar', 'ich:arbeite|er:arbeitet|Perfekt:hat gearbeitet', 'Ich arbeite zu Hause.', 'Trabalho em casa.', ''],
    ['lernen', '', 'aprender / estudar', 'ich:lerne|er:lernt|Perfekt:hat gelernt', 'Ich lerne jeden Abend.', 'Estudo toda noite.', 'Cobre "aprender" e "estudar" — o alemão não separa como o português.'],
    ['helfen', '', 'ajudar', 'ich:helfe|er:hilft|Perfekt:hat geholfen', 'Kannst du mir helfen?', 'Você pode me ajudar?', 'Pede dativo: "mir", não "mich".'],
    ['nehmen', '', 'pegar / tomar', 'ich:nehme|er:nimmt|Perfekt:hat genommen', 'Ich nehme einen Kaffee.', 'Vou tomar um café.', ''],
  ],
  A2: [
    ['schicken', '', 'enviar', 'ich:schicke|er:schickt|Perfekt:hat geschickt', 'Ich habe die Datei geschickt.', 'Enviei o arquivo.', ''],
    ['treffen', '', 'encontrar', 'ich:treffe|er:trifft|Perfekt:hat getroffen', 'Wir haben uns gestern getroffen.', 'A gente se encontrou ontem.', ''],
    ['vergessen', '', 'esquecer', 'ich:vergesse|er:vergisst|Perfekt:hat vergessen', 'Ich habe die Schlüssel vergessen.', 'Esqueci as chaves.', 'Particípio sem "ge-": o prefixo "ver-" é inseparável.'],
    ['sich erinnern', '', 'lembrar', 'ich:erinnere mich|er:erinnert sich|Perfekt:hat sich erinnert', 'Erinnere dich daran, sie anzurufen.', 'Lembre de ligar para ela.', 'Pede "an" + acusativo.'],
    ['wählen', '', 'escolher', 'ich:wähle|er:wählt|Perfekt:hat gewählt', 'Wähl eine Option.', 'Escolha uma opção.', 'Também é "votar" e "discar".'],
    ['antworten', '', 'responder', 'ich:antworte|er:antwortet|Perfekt:hat geantwortet', 'Er hat nie geantwortet.', 'Ele nunca respondeu.', 'Pede dativo de pessoa e "auf" para a pergunta.'],
    ['öffnen', '', 'abrir', 'ich:öffne|er:öffnet|Perfekt:hat geöffnet', 'Der Laden öffnet um neun.', 'A loja abre às nove.', ''],
    ['schließen', '', 'fechar', 'ich:schließe|er:schließt|Perfekt:hat geschlossen', 'Schließ das Fenster.', 'Feche a janela.', ''],
    ['reisen', '', 'viajar', 'ich:reise|er:reist|Perfekt:ist gereist', 'Ich reise beruflich.', 'Viajo a trabalho.', 'Perfeito com "sein".'],
    ['buchen', '', 'reservar', 'ich:buche|er:bucht|Perfekt:hat gebucht', 'Ich habe einen Tisch gebucht.', 'Reservei uma mesa.', ''],
    ['kochen', '', 'cozinhar', 'ich:koche|er:kocht|Perfekt:hat gekocht', 'Er kocht sonntags.', 'Ele cozinha aos domingos.', ''],
    ['verstehen', '', 'entender', 'ich:verstehe|er:versteht|Perfekt:hat verstanden', 'Ich habe alles verstanden.', 'Entendi tudo.', ''],
  ],
  B1: [
    ['leihen', '', 'emprestar / pegar emprestado', 'ich:leihe|er:leiht|Perfekt:hat geliehen', 'Sie hat mir das Buch geliehen.', 'Ela me emprestou o livro.', 'Com "sich" passa a ser pegar emprestado: "ich leihe mir".'],
    ['sich bewerben', '', 'candidatar-se', 'ich:bewerbe mich|er:bewirbt sich|Perfekt:hat sich beworben', 'Ich habe mich um die Stelle beworben.', 'Me candidatei à vaga.', 'Pede "um" + acusativo.'],
    ['einstellen', '', 'contratar', 'ich:stelle ein|er:stellt ein|Perfekt:hat eingestellt', 'Sie haben zwei Designer eingestellt.', 'Contrataram dois designers.', 'Verbo separável: o prefixo vai para o fim da frase.'],
    ['liefern', '', 'entregar', 'ich:liefere|er:liefert|Perfekt:hat geliefert', 'Wir haben pünktlich geliefert.', 'Entregamos no prazo.', ''],
    ['teilnehmen', '', 'participar', 'ich:nehme teil|er:nimmt teil|Perfekt:hat teilgenommen', 'Ich habe an der Sitzung teilgenommen.', 'Participei da reunião.', 'Separável, pede "an" + dativo.'],
    ['bemerken', '', 'reparar', 'ich:bemerke|er:bemerkt|Perfekt:hat bemerkt', 'Niemand hat die Änderung bemerkt.', 'Ninguém reparou na mudança.', ''],
    ['zugeben', '', 'admitir', 'ich:gebe zu|er:gibt zu|Perfekt:hat zugegeben', 'Er hat den Fehler zugegeben.', 'Ele admitiu o erro.', 'Separável.'],
    ['ablehnen', '', 'recusar', 'ich:lehne ab|er:lehnt ab|Perfekt:hat abgelehnt', 'Sie hat das Angebot abgelehnt.', 'Ela recusou a oferta.', 'Separável.'],
    ['verschieben', '', 'adiar', 'ich:verschiebe|er:verschiebt|Perfekt:hat verschoben', 'Wir haben den Start verschoben.', 'Adiamos o lançamento.', ''],
    ['abmachen', '', 'combinar', 'ich:mache ab|er:macht ab|Perfekt:hat abgemacht', 'Wir haben einen Termin abgemacht.', 'Combinamos um horário.', 'Separável, registro coloquial.'],
    ['schulden', '', 'dever (dinheiro)', 'ich:schulde|er:schuldet|Perfekt:hat geschuldet', 'Du schuldest mir nichts.', 'Você não me deve nada.', 'Diferente de "sollen", que é dever de obrigação.'],
    ['erledigen', '', 'resolver / dar conta de', 'ich:erledige|er:erledigt|Perfekt:hat erledigt', 'Ich habe alles erledigt.', 'Resolvi tudo.', ''],
  ],
  B2: [
    ['zuweisen', '', 'destinar / alocar', 'ich:weise zu|er:weist zu|Perfekt:hat zugewiesen', 'Wir haben mehr Budget zugewiesen.', 'Destinamos mais orçamento.', 'Separável.'],
    ['offenlegen', '', 'divulgar / revelar', 'ich:lege offen|er:legt offen|Perfekt:hat offengelegt', 'Sie haben die Bedingungen offengelegt.', 'Divulgaram as condições.', ''],
    ['verwerten', '', 'aproveitar / reaproveitar', 'ich:verwerte|er:verwertet|Perfekt:hat verwertet', 'Wir haben vorhandene Daten verwertet.', 'Reaproveitamos os dados existentes.', ''],
    ['vereinfachen', '', 'simplificar', 'ich:vereinfache|er:vereinfacht|Perfekt:hat vereinfacht', 'Sie haben den Prozess vereinfacht.', 'Simplificaram o processo.', ''],
    ['beaufsichtigen', '', 'supervisionar', 'ich:beaufsichtige|er:beaufsichtigt|Perfekt:hat beaufsichtigt', 'Sie beaufsichtigt drei Teams.', 'Ela supervisiona três equipes.', ''],
    ['auslösen', '', 'provocar / desencadear', 'er:löst aus|Perfekt:hat ausgelöst', 'Der Bericht hat eine Prüfung ausgelöst.', 'O relatório desencadeou uma auditoria.', 'Separável.'],
    ['aufrechterhalten', '', 'sustentar / manter', 'er:erhält aufrecht|Perfekt:hat aufrechterhalten', 'Sie haben das Wachstum aufrechterhalten.', 'Sustentaram o crescimento.', ''],
    ['zurückhalten', '', 'reter', 'ich:halte zurück|er:hält zurück|Perfekt:hat zurückgehalten', 'Er hat die Daten zurückgehalten.', 'Ele reteve os dados.', 'Separável.'],
    ['priorisieren', '', 'priorizar', 'ich:priorisiere|er:priorisiert|Perfekt:hat priorisiert', 'Wir haben Sicherheit priorisiert.', 'Priorizamos a segurança.', ''],
    ['eintreten für', '', 'defender (uma causa)', 'ich:trete ein für|er:tritt ein für|Perfekt:ist eingetreten für', 'Sie tritt für die Reform ein.', 'Ela defende a reforma.', 'Separável, perfeito com "sein".'],
    ['behaupten', '', 'alegar / afirmar', 'ich:behaupte|er:behauptet|Perfekt:hat behauptet', 'Der Bericht behauptet Betrug.', 'O relatório alega fraude.', ''],
    ['befürworten', '', 'endossar / apoiar', 'ich:befürworte|er:befürwortet|Perfekt:hat befürwortet', 'Zwei Gremien befürworteten den Plan.', 'Dois conselhos apoiaram o plano.', ''],
  ],
  C1: [
    ['erhärten', '', 'corroborar', 'er:erhärtet|Perfekt:hat erhärtet', 'Zwei Quellen erhärten den Verdacht.', 'Duas fontes corroboram a suspeita.', ''],
    ['abgrenzen', '', 'delimitar', 'er:grenzt ab|Perfekt:hat abgegrenzt', 'Der Aufsatz grenzt das Thema ab.', 'O artigo delimita o tema.', 'Separável.'],
    ['festlegen', '', 'estipular / fixar', 'ich:lege fest|er:legt fest|Perfekt:hat festgelegt', 'Der Vertrag legt eine Frist fest.', 'O contrato estipula um prazo.', 'Separável.'],
    ['lindern', '', 'aliviar', 'er:lindert|Perfekt:hat gelindert', 'Die Maßnahme lindert den Druck.', 'A medida alivia a pressão.', ''],
    ['konsolidieren', '', 'consolidar', 'ich:konsolidiere|er:konsolidiert|Perfekt:hat konsolidiert', 'Sie haben die Ergebnisse konsolidiert.', 'Consolidaram os resultados.', ''],
    ['zuschreiben', '', 'atribuir', 'ich:schreibe zu|er:schreibt zu|Perfekt:hat zugeschrieben', 'Er schreibt es dem Glück zu.', 'Ele atribui isso à sorte.', 'Separável, pede dativo.'],
    ['darstellen', '', 'constituir / representar', 'er:stellt dar|Perfekt:hat dargestellt', 'Das stellt einen Verstoß dar.', 'Isso constitui uma violação.', 'Separável.'],
    ['unternehmen', '', 'empreender', 'ich:unternehme|er:unternimmt|Perfekt:hat unternommen', 'Wir haben eine Prüfung unternommen.', 'Empreendemos uma auditoria.', ''],
    ['umfassen', '', 'abranger', 'er:umfasst|Perfekt:hat umfasst', 'Die Studie umfasst zehn Jahre.', 'O estudo abrange dez anos.', 'Inseparável, apesar do prefixo "um-".'],
    ['machen zu', '', 'tornar', 'er:macht zu|Perfekt:hat gemacht zu', 'Die Verzögerung machte es nutzlos.', 'O atraso o tornou inútil.', ''],
    ['erbringen', '', 'render / produzir', 'er:erbringt|Perfekt:hat erbracht', 'Die Methode erbringt bessere Daten.', 'O método rende dados melhores.', ''],
    ['einschränken', '', 'restringir', 'ich:schränke ein|er:schränkt ein|Perfekt:hat eingeschränkt', 'Sie haben die Ausgaben eingeschränkt.', 'Restringiram os gastos.', 'Separável.'],
  ],
  C2: [
    ['verschleiern', '', 'obscurecer', 'er:verschleiert|Perfekt:hat verschleiert', 'Die Formulierung verschleiert das Risiko.', 'A redação obscurece o risco.', ''],
    ['extrapolieren', '', 'extrapolar', 'ich:extrapoliere|er:extrapoliert|Perfekt:hat extrapoliert', 'Man kann nicht von einem Fall extrapolieren.', 'Não dá para extrapolar de um caso só.', ''],
    ['umgehen', '', 'contornar (uma regra)', 'er:umgeht|Perfekt:hat umgangen', 'Das Modell umgeht die Vorschrift.', 'O modelo contorna a norma.', 'Inseparável neste sentido; separável significa "lidar com".'],
    ['ablösen', '', 'substituir / suplantar', 'er:löst ab|Perfekt:hat abgelöst', 'Diese Fassung löst die vorige ab.', 'Esta versão substitui a anterior.', 'Separável.'],
    ['bestätigen', '', 'confirmar / dar razão a', 'er:bestätigt|Perfekt:hat bestätigt', 'Das Ergebnis bestätigte ihr Vorgehen.', 'O resultado confirmou a conduta dela.', ''],
    ['verbannen', '', 'relegar / banir', 'er:verbannt|Perfekt:hat verbannt', 'Sie haben es in eine Fußnote verbannt.', 'Relegaram isso a uma nota de rodapé.', ''],
    ['herabwürdigen', '', 'depreciar', 'er:würdigt herab|Perfekt:hat herabgewürdigt', 'Er hat den Vorschlag herabgewürdigt.', 'Ele depreciou a proposta.', 'Separável.'],
    ['unterstreichen', '', 'sublinhar / reforçar', 'er:unterstreicht|Perfekt:hat unterstrichen', 'Die Daten unterstreichen den Trend.', 'Os dados reforçam a tendência.', ''],
    ['hervorrufen', '', 'suscitar', 'er:ruft hervor|Perfekt:hat hervorgerufen', 'Die Frage rief Schweigen hervor.', 'A pergunta suscitou silêncio.', 'Separável.'],
    ['zuvorkommen', '', 'antecipar-se a', 'er:kommt zuvor|Perfekt:ist zuvorgekommen', 'Der Schritt kam einem Streik zuvor.', 'A medida antecipou-se a uma greve.', 'Separável, pede dativo, perfeito com "sein".'],
    ['verankern', '', 'consagrar (em lei)', 'er:verankert|Perfekt:hat verankert', 'Das Recht ist im Gesetz verankert.', 'O direito está consagrado na lei.', ''],
    ['heraufbeschwören', '', 'desencadear / provocar', 'er:beschwört herauf|Perfekt:hat heraufbeschworen', 'Das Urteil beschwor eine Krise herauf.', 'A decisão desencadeou uma crise.', 'Separável.'],
  ],
};
