/** Inglês — verbos de ampliação. Nenhum repete o lote de `verbs.ts`. */

import type { ByLevel } from './entry';

export const EN: ByLevel = {
  A1: [
    ['to come', '', 'vir', 'eu:come|ele:comes|passado:came', 'Come with me.', 'Venha comigo.', ''],
    ['to see', '', 'ver', 'eu:see|ele:sees|passado:saw', 'I see the bus.', 'Eu vejo o ônibus.', ''],
    ['to get', '', 'pegar / receber / ficar', 'eu:get|ele:gets|passado:got', 'I get home at six.', 'Chego em casa às seis.', 'O verbo mais polissêmico do inglês: aprenda por expressão, não por tradução.'],
    ['to make', '', 'fazer (produzir)', 'eu:make|ele:makes|passado:made', 'She makes good coffee.', 'Ela faz um bom café.', '"Make" cria algo; "do" executa uma ação. O português usa "fazer" para os dois.'],
    ['to know', '', 'saber / conhecer', 'eu:know|ele:knows|passado:knew', 'I know the answer.', 'Eu sei a resposta.', ''],
    ['to say', '', 'dizer', 'eu:say|ele:says|passado:said', 'She said no.', 'Ela disse não.', '"Say" não leva objeto de pessoa: diz-se "tell me", nunca "say me".'],
    ['to eat', '', 'comer', 'eu:eat|ele:eats|passado:ate', 'We eat at noon.', 'A gente come ao meio-dia.', ''],
    ['to drink', '', 'beber', 'eu:drink|ele:drinks|passado:drank', 'I drink water.', 'Eu bebo água.', ''],
    ['to live', '', 'morar / viver', 'eu:live|ele:lives|passado:lived', 'They live in Porto.', 'Eles moram no Porto.', ''],
    ['to work', '', 'trabalhar / funcionar', 'eu:work|ele:works|passado:worked', 'The lift works now.', 'O elevador funciona agora.', 'Serve para pessoa e para máquina, como em português.'],
    ['to study', '', 'estudar', 'eu:study|ele:studies|passado:studied', 'I study every night.', 'Eu estudo toda noite.', ''],
    ['to help', '', 'ajudar', 'eu:help|ele:helps|passado:helped', 'Can you help me?', 'Você pode me ajudar?', ''],
  ],
  A2: [
    ['to send', '', 'enviar', 'eu:send|ele:sends|passado:sent', 'I sent the file.', 'Enviei o arquivo.', ''],
    ['to meet', '', 'encontrar / conhecer', 'eu:meet|ele:meets|passado:met', 'We met last year.', 'A gente se conheceu ano passado.', 'No primeiro encontro significa "conhecer"; depois, "encontrar".'],
    ['to forget', '', 'esquecer', 'eu:forget|ele:forgets|passado:forgot', 'I forgot the keys.', 'Esqueci as chaves.', ''],
    ['to remember', '', 'lembrar', 'eu:remember|ele:remembers|passado:remembered', 'Remember to call her.', 'Lembre de ligar para ela.', '"Remember to do" é lembrar de fazer; "remember doing" é lembrar de ter feito.'],
    ['to choose', '', 'escolher', 'eu:choose|ele:chooses|passado:chose', 'Choose one option.', 'Escolha uma opção.', ''],
    ['to answer', '', 'responder', 'eu:answer|ele:answers|passado:answered', 'He never answered.', 'Ele nunca respondeu.', 'Sem preposição: "answer the question", não "answer to".'],
    ['to open', '', 'abrir', 'eu:open|ele:opens|passado:opened', 'The shop opens at nine.', 'A loja abre às nove.', ''],
    ['to close', '', 'fechar', 'eu:close|ele:closes|passado:closed', 'Close the window, please.', 'Feche a janela, por favor.', ''],
    ['to travel', '', 'viajar', 'eu:travel|ele:travels|passado:travelled', 'I travel for work.', 'Eu viajo a trabalho.', ''],
    ['to book', '', 'reservar', 'eu:book|ele:books|passado:booked', 'I booked a table.', 'Reservei uma mesa.', 'Em inglês britânico é o verbo padrão para reserva; nos EUA usa-se muito "to reserve".'],
    ['to cook', '', 'cozinhar', 'eu:cook|ele:cooks|passado:cooked', 'He cooks on Sundays.', 'Ele cozinha aos domingos.', ''],
    ['to learn', '', 'aprender', 'eu:learn|ele:learns|passado:learned', 'She learned fast.', 'Ela aprendeu rápido.', ''],
  ],
  B1: [
    ['to borrow', '', 'pegar emprestado', 'eu:borrow|ele:borrows|passado:borrowed', 'Can I borrow your pen?', 'Posso pegar sua caneta emprestada?', 'Quem pega é "borrow"; quem empresta é "lend". O português usa "emprestar" para os dois — é o erro mais comum.'],
    ['to lend', '', 'emprestar (dar)', 'eu:lend|ele:lends|passado:lent', 'She lent me the book.', 'Ela me emprestou o livro.', ''],
    ['to apply', '', 'candidatar-se / aplicar', 'eu:apply|ele:applies|passado:applied', 'I applied for the job.', 'Me candidatei à vaga.', 'Para vaga usa-se "apply for"; para universidade, "apply to".'],
    ['to hire', '', 'contratar', 'eu:hire|ele:hires|passado:hired', 'They hired two designers.', 'Contrataram dois designers.', ''],
    ['to deliver', '', 'entregar', 'eu:deliver|ele:delivers|passado:delivered', 'We delivered on time.', 'Entregamos no prazo.', ''],
    ['to attend', '', 'comparecer a', 'eu:attend|ele:attends|passado:attended', 'I attended the meeting.', 'Compareci à reunião.', 'Falso amigo: não é "atender". Atender ao telefone é "answer".'],
    ['to notice', '', 'reparar / notar', 'eu:notice|ele:notices|passado:noticed', 'Nobody noticed the change.', 'Ninguém reparou na mudança.', ''],
    ['to admit', '', 'admitir', 'eu:admit|ele:admits|passado:admitted', 'He admitted the mistake.', 'Ele admitiu o erro.', ''],
    ['to refuse', '', 'recusar', 'eu:refuse|ele:refuses|passado:refused', 'She refused the offer.', 'Ela recusou a oferta.', ''],
    ['to postpone', '', 'adiar', 'eu:postpone|ele:postpones|passado:postponed', 'We postponed the launch.', 'Adiamos o lançamento.', ''],
    ['to arrange', '', 'combinar / organizar', 'eu:arrange|ele:arranges|passado:arranged', 'I arranged a call.', 'Combinei uma ligação.', ''],
    ['to owe', '', 'dever (dinheiro)', 'eu:owe|ele:owes|passado:owed', 'You owe me nothing.', 'Você não me deve nada.', 'Não confundir com "must", que é dever de obrigação.'],
  ],
  B2: [
    ['to allocate', '', 'alocar / destinar', 'eu:allocate|ele:allocates|passado:allocated', 'We allocated more budget.', 'Destinamos mais orçamento.', ''],
    ['to disclose', '', 'divulgar / revelar', 'eu:disclose|ele:discloses|passado:disclosed', 'They disclosed the terms.', 'Divulgaram os termos.', 'Registro jurídico e corporativo.'],
    ['to leverage', '', 'alavancar / aproveitar', 'eu:leverage|ele:leverages|passado:leveraged', 'We leveraged existing data.', 'Aproveitamos os dados existentes.', ''],
    ['to streamline', '', 'simplificar / enxugar', 'eu:streamline|ele:streamlines|passado:streamlined', 'They streamlined the process.', 'Enxugaram o processo.', ''],
    ['to oversee', '', 'supervisionar', 'eu:oversee|ele:oversees|passado:oversaw', 'She oversees three teams.', 'Ela supervisiona três equipes.', 'Não confundir com "overlook", que é deixar passar.'],
    ['to prompt', '', 'levar a / provocar', 'ele:prompts|passado:prompted', 'The report prompted a review.', 'O relatório provocou uma revisão.', ''],
    ['to sustain', '', 'sustentar / manter', 'eu:sustain|ele:sustains|passado:sustained', 'They sustained the growth.', 'Sustentaram o crescimento.', ''],
    ['to withhold', '', 'reter / sonegar', 'eu:withhold|ele:withholds|passado:withheld', 'He withheld the data.', 'Ele reteve os dados.', ''],
    ['to prioritise', '', 'priorizar', 'eu:prioritise|ele:prioritises|passado:prioritised', 'We prioritised safety.', 'Priorizamos a segurança.', 'Grafia britânica; nos EUA, "prioritize".'],
    ['to advocate', '', 'defender (uma causa)', 'eu:advocate|ele:advocates|passado:advocated', 'She advocates for reform.', 'Ela defende a reforma.', ''],
    ['to allege', '', 'alegar', 'ele:alleges|passado:alleged', 'The report alleges fraud.', 'O relatório alega fraude.', 'Marca que a afirmação não está provada — é a palavra da imprensa.'],
    ['to endorse', '', 'endossar / apoiar', 'eu:endorse|ele:endorses|passado:endorsed', 'Two boards endorsed the plan.', 'Dois conselhos endossaram o plano.', ''],
  ],
  C1: [
    ['to corroborate', '', 'corroborar', 'ele:corroborates|passado:corroborated', 'Two sources corroborate it.', 'Duas fontes corroboram isso.', ''],
    ['to delineate', '', 'delimitar / traçar', 'ele:delineates|passado:delineated', 'The paper delineates the scope.', 'O artigo delimita o escopo.', ''],
    ['to stipulate', '', 'estipular', 'ele:stipulates|passado:stipulated', 'The contract stipulates a deadline.', 'O contrato estipula um prazo.', ''],
    ['to alleviate', '', 'aliviar', 'ele:alleviates|passado:alleviated', 'The measure alleviates pressure.', 'A medida alivia a pressão.', ''],
    ['to consolidate', '', 'consolidar', 'eu:consolidate|ele:consolidates|passado:consolidated', 'They consolidated the results.', 'Consolidaram os resultados.', ''],
    ['to attribute', '', 'atribuir', 'eu:attribute|ele:attributes|passado:attributed', 'He attributes it to luck.', 'Ele atribui isso à sorte.', 'Substantivo e verbo têm acentuação diferente na fala.'],
    ['to constitute', '', 'constituir / configurar', 'ele:constitutes|passado:constituted', 'That constitutes a breach.', 'Isso configura uma violação.', ''],
    ['to undertake', '', 'empreender / assumir', 'eu:undertake|ele:undertakes|passado:undertook', 'We undertook a full audit.', 'Empreendemos uma auditoria completa.', ''],
    ['to encompass', '', 'abranger', 'ele:encompasses|passado:encompassed', 'The study encompasses ten years.', 'O estudo abrange dez anos.', ''],
    ['to render', '', 'tornar / deixar', 'ele:renders|passado:rendered', 'The delay rendered it useless.', 'O atraso o tornou inútil.', '"Render + adjetivo" é a forma culta de "make + adjetivo".'],
    ['to yield', '', 'render / ceder', 'ele:yields|passado:yielded', 'The method yields better data.', 'O método rende dados melhores.', 'Dois sentidos distantes: produzir resultado e ceder passagem.'],
    ['to curtail', '', 'restringir / cortar', 'ele:curtails|passado:curtailed', 'They curtailed spending.', 'Restringiram os gastos.', ''],
  ],
  C2: [
    ['to obfuscate', '', 'obscurecer de propósito', 'ele:obfuscates|passado:obfuscated', 'The wording obfuscates the risk.', 'A redação obscurece o risco.', ''],
    ['to extrapolate', '', 'extrapolar', 'eu:extrapolate|ele:extrapolates|passado:extrapolated', 'You cannot extrapolate from one case.', 'Não dá para extrapolar de um caso só.', ''],
    ['to circumvent', '', 'contornar (uma regra)', 'ele:circumvents|passado:circumvented', 'The scheme circumvents the rule.', 'O esquema contorna a regra.', ''],
    ['to supersede', '', 'substituir / suplantar', 'ele:supersedes|passado:superseded', 'This version supersedes the last.', 'Esta versão substitui a anterior.', 'Registro normativo: aparece em contratos e normas.'],
    ['to vindicate', '', 'dar razão a', 'ele:vindicates|passado:vindicated', 'The result vindicated her.', 'O resultado deu razão a ela.', 'Falso amigo: não é "vingar".'],
    ['to relegate', '', 'relegar / rebaixar', 'ele:relegates|passado:relegated', 'They relegated it to a footnote.', 'Relegaram isso a uma nota de rodapé.', ''],
    ['to disparage', '', 'depreciar', 'ele:disparages|passado:disparaged', 'He disparaged the proposal.', 'Ele depreciou a proposta.', ''],
    ['to underscore', '', 'sublinhar / reforçar', 'ele:underscores|passado:underscored', 'The data underscores the trend.', 'Os dados reforçam a tendência.', ''],
    ['to elicit', '', 'suscitar / obter', 'ele:elicits|passado:elicited', 'The question elicited silence.', 'A pergunta suscitou silêncio.', 'Não confundir com "illicit", que é ilícito e se pronuncia igual.'],
    ['to forestall', '', 'prevenir / antecipar-se a', 'ele:forestalls|passado:forestalled', 'The move forestalled a strike.', 'A medida preveniu uma greve.', ''],
    ['to enshrine', '', 'consagrar (em lei)', 'ele:enshrines|passado:enshrined', 'The right is enshrined in law.', 'O direito está consagrado em lei.', ''],
    ['to precipitate', '', 'precipitar / desencadear', 'ele:precipitates|passado:precipitated', 'The ruling precipitated a crisis.', 'A decisão desencadeou uma crise.', ''],
  ],
};
