/** Espanhol — verbos de ampliação. Nenhum repete o lote de `verbs.ts`. */

import type { ByLevel } from './entry';

export const ES: ByLevel = {
  A1: [
    ['venir', '', 'vir', 'yo:vengo|él:viene|pretérito:vino', '¿Vienes conmigo?', 'Você vem comigo?', 'O imperativo é irregular e curto: «ven».'],
    ['ver', '', 'ver', 'yo:veo|él:ve|pretérito:vio', 'Veo el autobús.', 'Vejo o ônibus.', ''],
    ['saber', '', 'saber', 'yo:sé|él:sabe|pretérito:supo', 'Sé la respuesta.', 'Sei a resposta.', '"Saber" é fato; "conocer" é pessoa ou lugar.'],
    ['conocer', '', 'conhecer', 'yo:conozco|él:conoce|pretérito:conoció', 'Conozco bien Madrid.', 'Conheço bem Madri.', ''],
    ['decir', '', 'dizer', 'yo:digo|él:dice|pretérito:dijo', 'Dijo que no.', 'Ele disse não.', ''],
    ['comer', '', 'comer', 'yo:como|él:come|pretérito:comió', 'Comemos a mediodía.', 'A gente come ao meio-dia.', ''],
    ['beber', '', 'beber', 'yo:bebo|él:bebe|pretérito:bebió', 'Bebo agua.', 'Bebo água.', ''],
    ['vivir', '', 'morar / viver', 'yo:vivo|él:vive|pretérito:vivió', 'Viven en Oporto.', 'Eles moram no Porto.', ''],
    ['trabajar', '', 'trabalhar', 'yo:trabajo|él:trabaja|pretérito:trabajó', 'Trabajo desde casa.', 'Trabalho de casa.', ''],
    ['estudiar', '', 'estudar', 'yo:estudio|él:estudia|pretérito:estudió', 'Estudio cada noche.', 'Estudo toda noite.', ''],
    ['ayudar', '', 'ajudar', 'yo:ayudo|él:ayuda|pretérito:ayudó', '¿Me puedes ayudar?', 'Você pode me ajudar?', ''],
    ['tomar', '', 'tomar / pegar', 'yo:tomo|él:toma|pretérito:tomó', 'Tomo un café.', 'Vou tomar um café.', 'Na Espanha, "coger" é comum; na América Latina, evite — tem sentido vulgar.'],
  ],
  A2: [
    ['enviar', '', 'enviar', 'yo:envío|él:envía|pretérito:envió', 'Envié el archivo.', 'Enviei o arquivo.', 'Leva acento em quase todas as formas do presente.'],
    ['encontrar', '', 'encontrar', 'yo:encuentro|él:encuentra|pretérito:encontró', 'Nos encontramos ayer.', 'A gente se encontrou ontem.', 'Verbo de ditongo: e → ie.'],
    ['olvidar', '', 'esquecer', 'yo:olvido|él:olvida|pretérito:olvidó', 'Olvidé las llaves.', 'Esqueci as chaves.', ''],
    ['recordar', '', 'lembrar', 'yo:recuerdo|él:recuerda|pretérito:recordó', 'Recuerda llamarla.', 'Lembre de ligar para ela.', 'Ditongo o → ue.'],
    ['elegir', '', 'escolher', 'yo:elijo|él:elige|pretérito:eligió', 'Elige una opción.', 'Escolha uma opção.', ''],
    ['responder', '', 'responder', 'yo:respondo|él:responde|pretérito:respondió', 'Nunca respondió.', 'Ele nunca respondeu.', ''],
    ['abrir', '', 'abrir', 'yo:abro|él:abre|participio:abierto', 'La tienda abre a las nueve.', 'A loja abre às nove.', 'Particípio irregular.'],
    ['cerrar', '', 'fechar', 'yo:cierro|él:cierra|pretérito:cerró', 'Cierra la ventana.', 'Feche a janela.', ''],
    ['viajar', '', 'viajar', 'yo:viajo|él:viaja|pretérito:viajó', 'Viajo por trabajo.', 'Viajo a trabalho.', ''],
    ['reservar', '', 'reservar', 'yo:reservo|él:reserva|pretérito:reservó', 'Reservé una mesa.', 'Reservei uma mesa.', ''],
    ['cocinar', '', 'cozinhar', 'yo:cocino|él:cocina|pretérito:cocinó', 'Cocina los domingos.', 'Ele cozinha aos domingos.', ''],
    ['aprender', '', 'aprender', 'yo:aprendo|él:aprende|pretérito:aprendió', 'Aprendió rápido.', 'Ela aprendeu rápido.', 'Pede "a" antes de infinitivo.'],
  ],
  B1: [
    ['prestar', '', 'emprestar (dar)', 'yo:presto|él:presta|pretérito:prestó', 'Me prestó el libro.', 'Ela me emprestou o livro.', ''],
    ['pedir prestado', '', 'pegar emprestado', 'yo:pido prestado|pretérito:pidió prestado', '¿Puedo pedir prestado el bolígrafo?', 'Posso pegar a caneta emprestada?', 'O espanhol distingue quem dá de quem pega.'],
    ['postularse', '', 'candidatar-se', 'yo:me postulo|él:se postula|pretérito:se postuló', 'Me postulé al puesto.', 'Me candidatei à vaga.', 'Na Espanha diz-se mais "presentarse a".'],
    ['contratar', '', 'contratar', 'yo:contrato|él:contrata|pretérito:contrató', 'Contrataron a dos diseñadores.', 'Contrataram dois designers.', 'Pessoa como objeto pede "a".'],
    ['entregar', '', 'entregar', 'yo:entrego|él:entrega|pretérito:entregó', 'Entregamos a tiempo.', 'Entregamos no prazo.', ''],
    ['asistir', '', 'comparecer a', 'yo:asisto|él:asiste|pretérito:asistió', 'Asistí a la reunión.', 'Compareci à reunião.', 'Falso amigo: não é "assistir a um filme" — isso é "ver".'],
    ['notar', '', 'reparar', 'yo:noto|él:nota|pretérito:notó', 'Nadie notó el cambio.', 'Ninguém reparou na mudança.', ''],
    ['admitir', '', 'admitir', 'yo:admito|él:admite|pretérito:admitió', 'Admitió el error.', 'Ele admitiu o erro.', ''],
    ['rechazar', '', 'recusar', 'yo:rechazo|él:rechaza|pretérito:rechazó', 'Rechazó la oferta.', 'Ela recusou a oferta.', ''],
    ['aplazar', '', 'adiar', 'yo:aplazo|él:aplaza|pretérito:aplazó', 'Aplazamos el lanzamiento.', 'Adiamos o lançamento.', ''],
    ['organizar', '', 'organizar / combinar', 'yo:organizo|él:organiza|pretérito:organizó', 'Organicé una llamada.', 'Combinei uma ligação.', ''],
    ['deber', '', 'dever', 'yo:debo|él:debe|pretérito:debió', 'No me debes nada.', 'Você não me deve nada.', 'Serve para dívida e obrigação.'],
  ],
  B2: [
    ['destinar', '', 'destinar / alocar', 'yo:destino|él:destina|pretérito:destinó', 'Destinamos más presupuesto.', 'Destinamos mais orçamento.', ''],
    ['divulgar', '', 'divulgar', 'yo:divulgo|él:divulga|pretérito:divulgó', 'Divulgaron los términos.', 'Divulgaram os termos.', ''],
    ['capitalizar', '', 'capitalizar / tirar proveito de', 'yo:capitalizo|él:capitaliza|pretérito:capitalizó', 'Capitalizaron el aprendizaje del error.', 'Capitalizaram o aprendizado do erro.', ''],
    ['simplificar', '', 'simplificar', 'yo:simplifico|él:simplifica|pretérito:simplificó', 'Simplificaron el proceso.', 'Simplificaram o processo.', ''],
    ['supervisar', '', 'supervisionar', 'yo:superviso|él:supervisa|pretérito:supervisó', 'Supervisa tres equipos.', 'Ela supervisiona três equipes.', ''],
    ['provocar', '', 'provocar / causar', 'él:provoca|pretérito:provocó', 'El informe provocó una revisión.', 'O relatório provocou uma revisão.', ''],
    ['sostener', '', 'sustentar', 'yo:sostengo|él:sostiene|pretérito:sostuvo', 'Sostuvieron el crecimiento.', 'Sustentaram o crescimento.', ''],
    ['retener', '', 'reter', 'yo:retengo|él:retiene|pretérito:retuvo', 'Retuvo los datos.', 'Ele reteve os dados.', ''],
    ['priorizar', '', 'priorizar', 'yo:priorizo|él:prioriza|pretérito:priorizó', 'Priorizamos la seguridad.', 'Priorizamos a segurança.', ''],
    ['abogar', '', 'defender (uma causa)', 'yo:abogo|él:aboga|pretérito:abogó', 'Aboga por la reforma.', 'Ela defende a reforma.', 'Pede "por".'],
    ['alegar', '', 'alegar', 'él:alega|pretérito:alegó', 'El informe alega fraude.', 'O relatório alega fraude.', ''],
    ['respaldar', '', 'endossar / apoiar', 'yo:respaldo|él:respalda|pretérito:respaldó', 'Dos consejos respaldaron el plan.', 'Dois conselhos apoiaram o plano.', ''],
  ],
  C1: [
    ['corroborar', '', 'corroborar', 'él:corrobora|pretérito:corroboró', 'Dos fuentes lo corroboran.', 'Duas fontes corroboram isso.', ''],
    ['delimitar', '', 'delimitar', 'él:delimita|pretérito:delimitó', 'El artículo delimita el alcance.', 'O artigo delimita o escopo.', ''],
    ['estipular', '', 'estipular', 'él:estipula|pretérito:estipuló', 'El contrato estipula un plazo.', 'O contrato estipula um prazo.', ''],
    ['aliviar', '', 'aliviar', 'él:alivia|pretérito:alivió', 'La medida alivia la presión.', 'A medida alivia a pressão.', ''],
    ['consolidar', '', 'consolidar', 'yo:consolido|él:consolida|pretérito:consolidó', 'Consolidaron los resultados.', 'Consolidaram os resultados.', ''],
    ['atribuir', '', 'atribuir', 'yo:atribuyo|él:atribuye|pretérito:atribuyó', 'Lo atribuye a la suerte.', 'Ele atribui isso à sorte.', 'Insere "y" nas formas do presente.'],
    ['configurar', '', 'configurar / constituir', 'él:configura|pretérito:configuró', 'Eso configura una infracción.', 'Isso configura uma infração.', ''],
    ['emprender', '', 'empreender', 'yo:emprendo|él:emprende|pretérito:emprendió', 'Emprendimos una auditoría.', 'Empreendemos uma auditoria.', ''],
    ['abarcar', '', 'abranger', 'él:abarca|pretérito:abarcó', 'El estudio abarca diez años.', 'O estudo abrange dez anos.', ''],
    ['tornar', '', 'tornar', 'él:torna|pretérito:tornó', 'El retraso lo tornó inútil.', 'O atraso o tornou inútil.', 'Mais comum: "volver + adjetivo".'],
    ['rendir', '', 'render', 'él:rinde|pretérito:rindió', 'El método rinde mejores datos.', 'O método rende dados melhores.', ''],
    ['restringir', '', 'restringir', 'yo:restrinjo|él:restringe|pretérito:restringió', 'Restringieron el gasto.', 'Restringiram os gastos.', ''],
  ],
  C2: [
    ['ofuscar', '', 'obscurecer', 'él:ofusca|pretérito:ofuscó', 'La redacción ofusca el riesgo.', 'A redação obscurece o risco.', ''],
    ['extrapolar', '', 'extrapolar', 'yo:extrapolo|él:extrapola|pretérito:extrapoló', 'No se puede extrapolar de un caso.', 'Não dá para extrapolar de um caso só.', ''],
    ['eludir', '', 'contornar / iludir', 'yo:eludo|él:elude|pretérito:eludió', 'El esquema elude la norma.', 'O esquema contorna a norma.', ''],
    ['suplantar', '', 'suplantar', 'él:suplanta|pretérito:suplantó', 'Esta versión suplanta la anterior.', 'Esta versão suplanta a anterior.', ''],
    ['reivindicar', '', 'reivindicar / dar razão a', 'él:reivindica|pretérito:reivindicó', 'El resultado la reivindicó.', 'O resultado deu razão a ela.', ''],
    ['relegar', '', 'relegar', 'él:relega|pretérito:relegó', 'Lo relegaron a una nota.', 'Relegaram isso a uma nota.', ''],
    ['denigrar', '', 'depreciar', 'él:denigra|pretérito:denigró', 'Denigró la propuesta.', 'Ele depreciou a proposta.', ''],
    ['subrayar', '', 'sublinhar / reforçar', 'él:subraya|pretérito:subrayó', 'Los datos subrayan la tendencia.', 'Os dados reforçam a tendência.', ''],
    ['suscitar', '', 'suscitar', 'él:suscita|pretérito:suscitó', 'La pregunta suscitó silencio.', 'A pergunta suscitou silêncio.', ''],
    ['prevenir', '', 'prevenir', 'yo:prevengo|él:previene|pretérito:previno', 'La medida previno una huelga.', 'A medida preveniu uma greve.', ''],
    ['consagrar', '', 'consagrar (em lei)', 'él:consagra|pretérito:consagró', 'El derecho está consagrado en la ley.', 'O direito está consagrado na lei.', ''],
    ['desencadenar', '', 'desencadear', 'él:desencadena|pretérito:desencadenó', 'El fallo desencadenó una crisis.', 'A decisão desencadeou uma crise.', ''],
  ],
};
