/** Francês — verbos de ampliação. Nenhum repete o lote de `verbs.ts`. */

import type { ByLevel } from './entry';

export const FR: ByLevel = {
  A1: [
    ['venir', '', 'vir', 'je:viens|il:vient|passé:est venu', 'Viens avec moi.', 'Venha comigo.', 'Passado com "être": o particípio concorda.'],
    ['voir', '', 'ver', 'je:vois|il:voit|passé:a vu', 'Je vois le bus.', 'Vejo o ônibus.', ''],
    ['savoir', '', 'saber', 'je:sais|il:sait|passé:a su', 'Je sais la réponse.', 'Sei a resposta.', '"Savoir" é fato; "connaître" é pessoa ou lugar.'],
    ['connaître', '', 'conhecer', 'je:connais|il:connaît|passé:a connu', 'Je connais bien Lyon.', 'Conheço bem Lyon.', ''],
    ['dire', '', 'dizer', 'je:dis|il:dit|passé:a dit', 'Il a dit non.', 'Ele disse não.', ''],
    ['manger', '', 'comer', 'je:mange|il:mange|passé:a mangé', 'On mange à midi.', 'A gente come ao meio-dia.', ''],
    ['boire', '', 'beber', 'je:bois|il:boit|passé:a bu', 'Je bois de l’eau.', 'Bebo água.', ''],
    ['habiter', '', 'morar', 'je:habite|il:habite|passé:a habité', 'Ils habitent à Porto.', 'Eles moram no Porto.', ''],
    ['travailler', '', 'trabalhar', 'je:travaille|il:travaille|passé:a travaillé', 'Je travaille chez moi.', 'Trabalho em casa.', ''],
    ['étudier', '', 'estudar', 'je:étudie|il:étudie|passé:a étudié', 'J’étudie chaque soir.', 'Estudo toda noite.', ''],
    ['aider', '', 'ajudar', 'je:aide|il:aide|passé:a aidé', 'Tu peux m’aider ?', 'Você pode me ajudar?', ''],
    ['prendre', '', 'pegar / tomar', 'je:prends|il:prend|passé:a pris', 'Je prends un café.', 'Vou tomar um café.', 'Cobre transporte, bebida e objeto.'],
  ],
  A2: [
    ['envoyer', '', 'enviar', 'je:envoie|il:envoie|passé:a envoyé', 'J’ai envoyé le fichier.', 'Enviei o arquivo.', ''],
    ['rencontrer', '', 'encontrar / conhecer', 'je:rencontre|il:rencontre|passé:a rencontré', 'On s’est rencontrés hier.', 'A gente se conheceu ontem.', ''],
    ['oublier', '', 'esquecer', 'je:oublie|il:oublie|passé:a oublié', 'J’ai oublié les clés.', 'Esqueci as chaves.', ''],
    ['se souvenir', '', 'lembrar', 'je:me souviens|il:se souvient|passé:s’est souvenu', 'Souviens-toi de l’appeler.', 'Lembre de ligar para ela.', 'Pede "de". Alternativa: "se rappeler", que é direto.'],
    ['choisir', '', 'escolher', 'je:choisis|il:choisit|passé:a choisi', 'Choisis une option.', 'Escolha uma opção.', ''],
    ['répondre', '', 'responder', 'je:réponds|il:répond|passé:a répondu', 'Il n’a jamais répondu.', 'Ele nunca respondeu.', 'Pede "à": "répondre à la question".'],
    ['ouvrir', '', 'abrir', 'je:ouvre|il:ouvre|passé:a ouvert', 'Le magasin ouvre à neuf heures.', 'A loja abre às nove.', ''],
    ['fermer', '', 'fechar', 'je:ferme|il:ferme|passé:a fermé', 'Ferme la fenêtre.', 'Feche a janela.', ''],
    ['voyager', '', 'viajar', 'je:voyage|il:voyage|passé:a voyagé', 'Je voyage pour le travail.', 'Viajo a trabalho.', ''],
    ['réserver', '', 'reservar', 'je:réserve|il:réserve|passé:a réservé', 'J’ai réservé une table.', 'Reservei uma mesa.', ''],
    ['cuisiner', '', 'cozinhar', 'je:cuisine|il:cuisine|passé:a cuisiné', 'Il cuisine le dimanche.', 'Ele cozinha aos domingos.', ''],
    ['apprendre', '', 'aprender', 'je:apprends|il:apprend|passé:a appris', 'Elle a appris vite.', 'Ela aprendeu rápido.', 'Pede "à" antes de infinitivo.'],
  ],
  B1: [
    ['prêter', '', 'emprestar (dar)', 'je:prête|il:prête|passé:a prêté', 'Elle m’a prêté le livre.', 'Ela me emprestou o livro.', ''],
    ['emprunter', '', 'pegar emprestado', 'je:emprunte|il:emprunte|passé:a emprunté', 'Je peux emprunter ton stylo ?', 'Posso pegar sua caneta emprestada?', 'O francês distingue quem dá de quem pega.'],
    ['postuler', '', 'candidatar-se', 'je:postule|il:postule|passé:a postulé', 'J’ai postulé au poste.', 'Me candidatei à vaga.', ''],
    ['embaucher', '', 'contratar', 'je:embauche|il:embauche|passé:a embauché', 'Ils ont embauché deux designers.', 'Contrataram dois designers.', ''],
    ['livrer', '', 'entregar', 'je:livre|il:livre|passé:a livré', 'Nous avons livré à temps.', 'Entregamos no prazo.', ''],
    ['assister', '', 'comparecer a', 'je:assiste|il:assiste|passé:a assisté', 'J’ai assisté à la réunion.', 'Compareci à reunião.', 'Pede "à". Sem preposição significa "socorrer".'],
    ['remarquer', '', 'reparar', 'je:remarque|il:remarque|passé:a remarqué', 'Personne n’a remarqué le changement.', 'Ninguém reparou na mudança.', ''],
    ['admettre', '', 'admitir', 'je:admets|il:admet|passé:a admis', 'Il a admis son erreur.', 'Ele admitiu o erro.', ''],
    ['refuser', '', 'recusar', 'je:refuse|il:refuse|passé:a refusé', 'Elle a refusé l’offre.', 'Ela recusou a oferta.', ''],
    ['reporter', '', 'adiar', 'je:reporte|il:reporte|passé:a reporté', 'Nous avons reporté le lancement.', 'Adiamos o lançamento.', ''],
    ['organiser', '', 'organizar / combinar', 'je:organise|il:organise|passé:a organisé', 'J’ai organisé un appel.', 'Combinei uma ligação.', ''],
    ['devoir', '', 'dever', 'je:dois|il:doit|passé:a dû', 'Tu ne me dois rien.', 'Você não me deve nada.', 'Serve para dívida e para obrigação.'],
  ],
  B2: [
    ['affecter', '', 'destinar / afetar', 'je:affecte|il:affecte|passé:a affecté', 'Nous avons affecté plus de budget.', 'Destinamos mais orçamento.', 'Dois sentidos: alocar recurso e causar efeito.'],
    ['divulguer', '', 'divulgar', 'je:divulgue|il:divulgue|passé:a divulgué', 'Ils ont divulgué les termes.', 'Divulgaram os termos.', ''],
    ['exploiter', '', 'aproveitar / explorar', 'je:exploite|il:exploite|passé:a exploité', 'Nous avons exploité les données existantes.', 'Aproveitamos os dados existentes.', 'Carga negativa quando o objeto é pessoa.'],
    ['simplifier', '', 'simplificar', 'je:simplifie|il:simplifie|passé:a simplifié', 'Ils ont simplifié le processus.', 'Simplificaram o processo.', ''],
    ['superviser', '', 'supervisionar', 'je:supervise|il:supervise|passé:a supervisé', 'Elle supervise trois équipes.', 'Ela supervisiona três equipes.', ''],
    ['susciter', '', 'provocar / suscitar', 'il:suscite|passé:a suscité', 'Le rapport a suscité une révision.', 'O relatório provocou uma revisão.', ''],
    ['soutenir', '', 'sustentar / apoiar', 'je:soutiens|il:soutient|passé:a soutenu', 'Ils ont soutenu la croissance.', 'Sustentaram o crescimento.', ''],
    ['retenir', '', 'reter', 'je:retiens|il:retient|passé:a retenu', 'Il a retenu les données.', 'Ele reteve os dados.', ''],
    ['prioriser', '', 'priorizar', 'je:priorise|il:priorise|passé:a priorisé', 'Nous avons priorisé la sécurité.', 'Priorizamos a segurança.', ''],
    ['plaider', '', 'defender (uma causa)', 'je:plaide|il:plaide|passé:a plaidé', 'Elle plaide pour la réforme.', 'Ela defende a reforma.', 'Pede "pour" ou "en faveur de".'],
    ['alléguer', '', 'alegar', 'il:allègue|passé:a allégué', 'Le rapport allègue une fraude.', 'O relatório alega fraude.', ''],
    ['approuver', '', 'aprovar / endossar', 'je:approuve|il:approuve|passé:a approuvé', 'Deux conseils ont approuvé le plan.', 'Dois conselhos aprovaram o plano.', ''],
  ],
  C1: [
    ['corroborer', '', 'corroborar', 'il:corrobore|passé:a corroboré', 'Deux sources le corroborent.', 'Duas fontes corroboram isso.', ''],
    ['délimiter', '', 'delimitar', 'il:délimite|passé:a délimité', 'L’article délimite le champ.', 'O artigo delimita o escopo.', ''],
    ['stipuler', '', 'estipular', 'il:stipule|passé:a stipulé', 'Le contrat stipule un délai.', 'O contrato estipula um prazo.', ''],
    ['soulager', '', 'aliviar', 'il:soulage|passé:a soulagé', 'La mesure soulage la pression.', 'A medida alivia a pressão.', ''],
    ['consolider', '', 'consolidar', 'je:consolide|il:consolide|passé:a consolidé', 'Ils ont consolidé les résultats.', 'Consolidaram os resultados.', ''],
    ['attribuer', '', 'atribuir', 'je:attribue|il:attribue|passé:a attribué', 'Il l’attribue à la chance.', 'Ele atribui isso à sorte.', ''],
    ['constituer', '', 'constituir / configurar', 'il:constitue|passé:a constitué', 'Cela constitue une infraction.', 'Isso configura uma infração.', ''],
    ['entreprendre', '', 'empreender', 'je:entreprends|il:entreprend|passé:a entrepris', 'Nous avons entrepris un audit.', 'Empreendemos uma auditoria.', ''],
    ['englober', '', 'abranger', 'il:englobe|passé:a englobé', 'L’étude englobe dix ans.', 'O estudo abrange dez anos.', ''],
    ['rendre', '', 'tornar', 'il:rend|passé:a rendu', 'Le retard l’a rendu inutile.', 'O atraso o tornou inútil.', '"Rendre + adjetivo" é a forma culta.'],
    ['produire', '', 'render / produzir', 'il:produit|passé:a produit', 'La méthode produit de meilleures données.', 'O método rende dados melhores.', ''],
    ['restreindre', '', 'restringir', 'je:restreins|il:restreint|passé:a restreint', 'Ils ont restreint les dépenses.', 'Restringiram os gastos.', ''],
  ],
  C2: [
    ['obscurcir', '', 'obscurecer', 'il:obscurcit|passé:a obscurci', 'La formulation obscurcit le risque.', 'A redação obscurece o risco.', ''],
    ['extrapoler', '', 'extrapolar', 'je:extrapole|il:extrapole|passé:a extrapolé', 'On ne peut pas extrapoler d’un seul cas.', 'Não dá para extrapolar de um caso só.', ''],
    ['contourner', '', 'contornar (uma regra)', 'il:contourne|passé:a contourné', 'Le montage contourne la règle.', 'O esquema contorna a regra.', ''],
    ['supplanter', '', 'suplantar', 'il:supplante|passé:a supplanté', 'Cette version supplante la précédente.', 'Esta versão suplanta a anterior.', ''],
    ['donner raison à', '', 'dar razão a', 'il:donne raison à|passé:a donné raison à', 'Le résultat lui a donné raison.', 'O resultado deu razão a ela.', ''],
    ['reléguer', '', 'relegar', 'il:relègue|passé:a relégué', 'Ils l’ont relégué à une note.', 'Relegaram isso a uma nota.', ''],
    ['dénigrer', '', 'depreciar', 'il:dénigre|passé:a dénigré', 'Il a dénigré la proposition.', 'Ele depreciou a proposta.', ''],
    ['souligner', '', 'sublinhar / reforçar', 'il:souligne|passé:a souligné', 'Les données soulignent la tendance.', 'Os dados reforçam a tendência.', ''],
    ['provoquer', '', 'provocar', 'il:provoque|passé:a provoqué', 'La question a provoqué un silence.', 'A pergunta provocou um silêncio.', ''],
    ['prévenir', '', 'prevenir', 'je:préviens|il:prévient|passé:a prévenu', 'La mesure a prévenu une grève.', 'A medida preveniu uma greve.', ''],
    ['consacrer', '', 'consagrar (em lei)', 'il:consacre|passé:a consacré', 'Le droit est consacré par la loi.', 'O direito é consagrado pela lei.', ''],
    ['déclencher', '', 'desencadear', 'il:déclenche|passé:a déclenché', 'La décision a déclenché une crise.', 'A decisão desencadeou uma crise.', ''],
  ],
};
