/** Italiano — verbos de ampliação. Nenhum repete o lote de `verbs.ts`. */

import type { ByLevel } from './entry';

export const IT: ByLevel = {
  A1: [
    ['venire', '', 'vir', 'io:vengo|lui:viene|passato:è venuto', 'Vieni con me.', 'Venha comigo.', 'Passado com "essere": concorda com o sujeito.'],
    ['vedere', '', 'ver', 'io:vedo|lui:vede|passato:ho visto', 'Vedo l’autobus.', 'Vejo o ônibus.', ''],
    ['sapere', '', 'saber', 'io:so|lui:sa|passato:ho saputo', 'So la risposta.', 'Sei a resposta.', '"Sapere" é saber um fato; "conoscere" é conhecer pessoa ou lugar.'],
    ['conoscere', '', 'conhecer', 'io:conosco|lui:conosce|passato:ho conosciuto', 'Conosco Roma bene.', 'Conheço bem Roma.', ''],
    ['dire', '', 'dizer', 'io:dico|lui:dice|passato:ho detto', 'Ha detto di no.', 'Ele disse não.', ''],
    ['mangiare', '', 'comer', 'io:mangio|lui:mangia|passato:ho mangiato', 'Mangiamo a mezzogiorno.', 'A gente come ao meio-dia.', ''],
    ['bere', '', 'beber', 'io:bevo|lui:beve|passato:ho bevuto', 'Bevo acqua.', 'Bebo água.', 'Irregular: o radical vira "bev-".'],
    ['abitare', '', 'morar', 'io:abito|lui:abita|passato:ho abitato', 'Abitano a Porto.', 'Eles moram no Porto.', ''],
    ['lavorare', '', 'trabalhar', 'io:lavoro|lui:lavora|passato:ho lavorato', 'Lavoro da casa.', 'Trabalho de casa.', ''],
    ['studiare', '', 'estudar', 'io:studio|lui:studia|passato:ho studiato', 'Studio ogni sera.', 'Estudo toda noite.', ''],
    ['aiutare', '', 'ajudar', 'io:aiuto|lui:aiuta|passato:ho aiutato', 'Mi puoi aiutare?', 'Você pode me ajudar?', ''],
    ['prendere', '', 'pegar / tomar', 'io:prendo|lui:prende|passato:ho preso', 'Prendo un caffè.', 'Vou tomar um café.', 'Serve para transporte, bebida e objeto — cobre boa parte do dia.'],
  ],
  A2: [
    ['mandare', '', 'enviar', 'io:mando|lui:manda|passato:ho mandato', 'Ho mandato il file.', 'Enviei o arquivo.', ''],
    ['incontrare', '', 'encontrar', 'io:incontro|lui:incontra|passato:ho incontrato', 'Ci siamo incontrati ieri.', 'A gente se encontrou ontem.', ''],
    ['dimenticare', '', 'esquecer', 'io:dimentico|lui:dimentica|passato:ho dimenticato', 'Ho dimenticato le chiavi.', 'Esqueci as chaves.', ''],
    ['ricordare', '', 'lembrar', 'io:ricordo|lui:ricorda|passato:ho ricordato', 'Ricordati di chiamarla.', 'Lembre de ligar para ela.', 'Na forma reflexiva, pede "di" antes do infinitivo.'],
    ['scegliere', '', 'escolher', 'io:scelgo|lui:sceglie|passato:ho scelto', 'Scegli un’opzione.', 'Escolha uma opção.', ''],
    ['rispondere', '', 'responder', 'io:rispondo|lui:risponde|passato:ho risposto', 'Non ha mai risposto.', 'Ele nunca respondeu.', 'Pede "a": "rispondere alla domanda".'],
    ['aprire', '', 'abrir', 'io:apro|lui:apre|passato:ho aperto', 'Il negozio apre alle nove.', 'A loja abre às nove.', ''],
    ['chiudere', '', 'fechar', 'io:chiudo|lui:chiude|passato:ho chiuso', 'Chiudi la finestra.', 'Feche a janela.', ''],
    ['viaggiare', '', 'viajar', 'io:viaggio|lui:viaggia|passato:ho viaggiato', 'Viaggio per lavoro.', 'Viajo a trabalho.', ''],
    ['prenotare', '', 'reservar', 'io:prenoto|lui:prenota|passato:ho prenotato', 'Ho prenotato un tavolo.', 'Reservei uma mesa.', ''],
    ['cucinare', '', 'cozinhar', 'io:cucino|lui:cucina|passato:ho cucinato', 'Cucina la domenica.', 'Ele cozinha aos domingos.', ''],
    ['imparare', '', 'aprender', 'io:imparo|lui:impara|passato:ho imparato', 'Ha imparato in fretta.', 'Ela aprendeu rápido.', 'Pede "a" antes de infinitivo: "imparare a nuotare".'],
  ],
  B1: [
    ['prestare', '', 'emprestar (dar)', 'io:presto|lui:presta|passato:ho prestato', 'Mi ha prestato il libro.', 'Ela me emprestou o livro.', ''],
    ['prendere in prestito', '', 'pegar emprestado', 'io:prendo in prestito|passato:ho preso in prestito', 'Posso prendere in prestito la penna?', 'Posso pegar a caneta emprestada?', 'O italiano distingue quem dá de quem pega, como o inglês.'],
    ['candidarsi', '', 'candidatar-se', 'io:mi candido|lui:si candida|passato:mi sono candidato', 'Mi sono candidato al posto.', 'Me candidatei à vaga.', ''],
    ['assumere', '', 'contratar', 'io:assumo|lui:assume|passato:ho assunto', 'Hanno assunto due designer.', 'Contrataram dois designers.', 'Também significa assumir uma postura ou um risco.'],
    ['consegnare', '', 'entregar', 'io:consegno|lui:consegna|passato:ho consegnato', 'Abbiamo consegnato in tempo.', 'Entregamos no prazo.', ''],
    ['partecipare', '', 'participar / comparecer', 'io:partecipo|lui:partecipa|passato:ho partecipato', 'Ho partecipato alla riunione.', 'Participei da reunião.', 'Pede "a".'],
    ['notare', '', 'reparar', 'io:noto|lui:nota|passato:ho notato', 'Nessuno ha notato il cambiamento.', 'Ninguém reparou na mudança.', ''],
    ['ammettere', '', 'admitir', 'io:ammetto|lui:ammette|passato:ho ammesso', 'Ha ammesso l’errore.', 'Ele admitiu o erro.', ''],
    ['rifiutare', '', 'recusar', 'io:rifiuto|lui:rifiuta|passato:ho rifiutato', 'Ha rifiutato l’offerta.', 'Ela recusou a oferta.', ''],
    ['rimandare', '', 'adiar', 'io:rimando|lui:rimanda|passato:ho rimandato', 'Abbiamo rimandato il lancio.', 'Adiamos o lançamento.', ''],
    ['organizzare', '', 'organizar / combinar', 'io:organizzo|lui:organizza|passato:ho organizzato', 'Ho organizzato una call.', 'Combinei uma ligação.', ''],
    ['dovere', '', 'dever', 'io:devo|lui:deve|passato:ho dovuto', 'Non mi devi niente.', 'Você não me deve nada.', 'Serve para dívida e para obrigação, como em português.'],
  ],
  B2: [
    ['destinare', '', 'destinar / alocar', 'io:destino|lui:destina|passato:ho destinato', 'Abbiamo destinato più budget.', 'Destinamos mais orçamento.', ''],
    ['divulgare', '', 'divulgar', 'io:divulgo|lui:divulga|passato:ho divulgato', 'Hanno divulgato i termini.', 'Divulgaram os termos.', ''],
    ['valorizzare', '', 'valorizar / dar valor a', 'io:valorizzo|lui:valorizza|passato:ho valorizzato', 'Hanno valorizzato i dati esistenti.', 'Valorizaram os dados existentes.', ''],
    ['semplificare', '', 'simplificar', 'io:semplifico|lui:semplifica|passato:ho semplificato', 'Hanno semplificato il processo.', 'Simplificaram o processo.', ''],
    ['supervisionare', '', 'supervisionar', 'io:supervisiono|lui:supervisiona|passato:ho supervisionato', 'Supervisiona tre squadre.', 'Ela supervisiona três equipes.', ''],
    ['provocare', '', 'provocar / causar', 'lui:provoca|passato:ha provocato', 'Il rapporto ha provocato una revisione.', 'O relatório provocou uma revisão.', ''],
    ['sostenere', '', 'sustentar / apoiar', 'io:sostengo|lui:sostiene|passato:ho sostenuto', 'Hanno sostenuto la crescita.', 'Sustentaram o crescimento.', 'Também é "prestar" uma prova: "sostenere un esame".'],
    ['trattenere', '', 'reter / segurar', 'io:trattengo|lui:trattiene|passato:ho trattenuto', 'Ha trattenuto i dati.', 'Ele reteve os dados.', ''],
    ['dare priorità', '', 'priorizar', 'io:do priorità|passato:ho dato priorità', 'Abbiamo dato priorità alla sicurezza.', 'Priorizamos a segurança.', 'O italiano prefere a locução ao verbo derivado.'],
    ['perorare', '', 'defender (uma causa)', 'lui:perora|passato:ha perorato', 'Ha perorato la riforma.', 'Ela defendeu a reforma.', 'Registro alto; no dia a dia usa-se "battersi per".'],
    ['sostenere che', '', 'alegar que', 'lui:sostiene che|passato:ha sostenuto che', 'Il rapporto sostiene che ci sia frode.', 'O relatório alega que há fraude.', 'Pede subjuntivo depois de "che".'],
    ['approvare', '', 'aprovar / endossar', 'io:approvo|lui:approva|passato:ho approvato', 'Due consigli hanno approvato il piano.', 'Dois conselhos aprovaram o plano.', ''],
  ],
  C1: [
    ['corroborare', '', 'corroborar', 'lui:corrobora|passato:ha corroborato', 'Due fonti corroborano la tesi.', 'Duas fontes corroboram a tese.', ''],
    ['delineare', '', 'delinear / traçar', 'lui:delinea|passato:ha delineato', 'L’articolo delinea l’ambito.', 'O artigo delineia o escopo.', ''],
    ['stipulare', '', 'estipular', 'lui:stipula|passato:ha stipulato', 'Il contratto stipula una scadenza.', 'O contrato estipula um prazo.', ''],
    ['alleviare', '', 'aliviar', 'lui:allevia|passato:ha alleviato', 'La misura allevia la pressione.', 'A medida alivia a pressão.', ''],
    ['consolidare', '', 'consolidar', 'io:consolido|lui:consolida|passato:ho consolidato', 'Hanno consolidato i risultati.', 'Consolidaram os resultados.', ''],
    ['attribuire', '', 'atribuir', 'io:attribuisco|lui:attribuisce|passato:ho attribuito', 'Lo attribuisce alla fortuna.', 'Ele atribui isso à sorte.', 'Verbo em -isc-.'],
    ['configurare', '', 'configurar / constituir', 'lui:configura|passato:ha configurato', 'Questo configura una violazione.', 'Isso configura uma violação.', ''],
    ['intraprendere', '', 'empreender', 'io:intraprendo|lui:intraprende|passato:ho intrapreso', 'Abbiamo intrapreso una revisione.', 'Empreendemos uma revisão.', ''],
    ['abbracciare', '', 'abranger', 'lui:abbraccia|passato:ha abbracciato', 'Lo studio abbraccia dieci anni.', 'O estudo abrange dez anos.', 'Fora do sentido físico de abraçar.'],
    ['rendere', '', 'tornar', 'lui:rende|passato:ha reso', 'Il ritardo lo ha reso inutile.', 'O atraso o tornou inútil.', '"Rendere + adjetivo" é a forma culta de "fare diventare".'],
    ['fruttare', '', 'render', 'lui:frutta|passato:ha fruttato', 'Il metodo frutta dati migliori.', 'O método rende dados melhores.', ''],
    ['limitare', '', 'restringir', 'io:limito|lui:limita|passato:ho limitato', 'Hanno limitato le spese.', 'Restringiram os gastos.', ''],
  ],
  C2: [
    ['offuscare', '', 'obscurecer', 'lui:offusca|passato:ha offuscato', 'La formulazione offusca il rischio.', 'A redação obscurece o risco.', ''],
    ['estrapolare', '', 'extrapolar', 'io:estrapolo|lui:estrapola|passato:ho estrapolato', 'Non si può estrapolare da un caso solo.', 'Não dá para extrapolar de um caso só.', ''],
    ['aggirare', '', 'contornar (uma regra)', 'lui:aggira|passato:ha aggirato', 'Lo schema aggira la norma.', 'O esquema contorna a norma.', ''],
    ['soppiantare', '', 'suplantar', 'lui:soppianta|passato:ha soppiantato', 'Questa versione soppianta la precedente.', 'Esta versão suplanta a anterior.', ''],
    ['dare ragione a', '', 'dar razão a', 'lui:dà ragione a|passato:ha dato ragione a', 'Il risultato le ha dato ragione.', 'O resultado deu razão a ela.', ''],
    ['relegare', '', 'relegar', 'lui:relega|passato:ha relegato', 'Lo hanno relegato a una nota.', 'Relegaram isso a uma nota.', ''],
    ['denigrare', '', 'depreciar', 'lui:denigra|passato:ha denigrato', 'Ha denigrato la proposta.', 'Ele depreciou a proposta.', ''],
    ['sottolineare', '', 'sublinhar / reforçar', 'lui:sottolinea|passato:ha sottolineato', 'I dati sottolineano la tendenza.', 'Os dados reforçam a tendência.', ''],
    ['suscitare', '', 'suscitar', 'lui:suscita|passato:ha suscitato', 'La domanda ha suscitato silenzio.', 'A pergunta suscitou silêncio.', ''],
    ['prevenire', '', 'prevenir / antecipar-se a', 'lui:previene|passato:ha prevenuto', 'La mossa ha prevenuto uno sciopero.', 'A medida preveniu uma greve.', ''],
    ['sancire', '', 'consagrar (em lei)', 'lui:sancisce|passato:ha sancito', 'Il diritto è sancito dalla legge.', 'O direito é consagrado pela lei.', 'Verbo em -isc-, registro jurídico.'],
    ['innescare', '', 'desencadear', 'lui:innesca|passato:ha innescato', 'La sentenza ha innescato una crisi.', 'A decisão desencadeou uma crise.', ''],
  ],
};
