/** Japonês — verbos de ampliação. Romanização obrigatória. */

import type { ByLevel } from './entry';

export const JA: ByLevel = {
  A1: [
    ['来る', 'kuru', 'vir', 'presente:来ます (kimasu)|passado:来ました (kimashita)', '一緒に来てください。', 'Venha comigo, por favor.', 'Irregular: só existem dois no japonês, e este é um deles.'],
    ['見る', 'miru', 'ver / assistir', 'presente:見ます (mimasu)|passado:見ました (mimashita)', 'バスが見えます。', 'Dá para ver o ônibus.', ''],
    ['知る', 'shiru', 'saber / conhecer', 'presente:知っています (shitte imasu)|negativo:知りません (shirimasen)', '答えを知っています。', 'Sei a resposta.', 'No afirmativo usa-se sempre a forma contínua 知っています; a forma simples soa errada.'],
    ['言う', 'iu', 'dizer', 'presente:言います (iimasu)|passado:言いました (iimashita)', '彼はだめだと言いました。', 'Ele disse que não.', 'Pronuncia-se "yuu", não "iu".'],
    ['食べる', 'taberu', 'comer', 'presente:食べます (tabemasu)|passado:食べました (tabemashita)', '十二時に食べます。', 'A gente come ao meio-dia.', 'Verbo do grupo ichidan: perde o 「る」 e recebe a terminação.'],
    ['飲む', 'nomu', 'beber', 'presente:飲みます (nomimasu)|passado:飲みました (nomimashita)', '水を飲みます。', 'Bebo água.', 'Também é o verbo para tomar remédio.'],
    ['住む', 'sumu', 'morar', 'presente:住んでいます (sunde imasu)|passado:住んでいました', 'ポルトに住んでいます。', 'Moro no Porto.', 'Usa-se na forma contínua para estado atual.'],
    ['働く', 'hataraku', 'trabalhar', 'presente:働きます (hatarakimasu)|passado:働きました', '家で働いています。', 'Trabalho em casa.', ''],
    ['勉強する', 'benkyou suru', 'estudar', 'presente:勉強します|passado:勉強しました', '毎晩勉強します。', 'Estudo toda noite.', 'Verbo com する: forma-se a partir de um substantivo.'],
    ['手伝う', 'tetsudau', 'ajudar', 'presente:手伝います (tetsudaimasu)|passado:手伝いました', '手伝ってくれますか。', 'Você pode me ajudar?', ''],
    ['買う', 'kau', 'comprar', 'presente:買います (kaimasu)|passado:買いました', 'パンを買います。', 'Vou comprar pão.', ''],
    ['帰る', 'kaeru', 'voltar (para casa)', 'presente:帰ります (kaerimasu)|passado:帰りました', '六時に帰ります。', 'Volto às seis.', 'Parece ichidan pela terminação, mas é godan — exceção clássica.'],
  ],
  A2: [
    ['送る', 'okuru', 'enviar', 'presente:送ります (okurimasu)|passado:送りました', 'ファイルを送りました。', 'Enviei o arquivo.', 'Também é acompanhar alguém até a saída.'],
    ['会う', 'au', 'encontrar (pessoa)', 'presente:会います (aimasu)|passado:会いました', '昨日友だちに会いました。', 'Ontem encontrei um amigo.', 'Pede a partícula に, não を.'],
    ['忘れる', 'wasureru', 'esquecer', 'presente:忘れます (wasuremasu)|passado:忘れました', '鍵を忘れました。', 'Esqueci as chaves.', ''],
    ['覚える', 'oboeru', 'lembrar / memorizar', 'presente:覚えます (oboemasu)|passado:覚えました', '名前を覚えました。', 'Memorizei o nome.', 'É guardar na memória; 思い出す é trazer de volta à lembrança.'],
    ['選ぶ', 'erabu', 'escolher', 'presente:選びます (erabimasu)|passado:選びました', '一つ選んでください。', 'Escolha uma, por favor.', ''],
    ['答える', 'kotaeru', 'responder', 'presente:答えます (kotaemasu)|passado:答えました', '彼は答えませんでした。', 'Ele não respondeu.', 'Pede に para a pergunta.'],
    ['開ける', 'akeru', 'abrir', 'presente:開けます (akemasu)|passado:開けました', '窓を開けます。', 'Vou abrir a janela.', 'Transitivo. O intransitivo é 開く (aku).'],
    ['閉める', 'shimeru', 'fechar', 'presente:閉めます (shimemasu)|passado:閉めました', 'ドアを閉めてください。', 'Feche a porta, por favor.', 'Transitivo, par de 閉まる (shimaru).'],
    ['旅行する', 'ryokou suru', 'viajar', 'presente:旅行します|passado:旅行しました', '仕事で旅行します。', 'Viajo a trabalho.', ''],
    ['予約する', 'yoyaku suru', 'reservar', 'presente:予約します|passado:予約しました', 'テーブルを予約しました。', 'Reservei uma mesa.', ''],
    ['作る', 'tsukuru', 'fazer / preparar', 'presente:作ります (tsukurimasu)|passado:作りました', '日曜日に料理を作ります。', 'No domingo eu cozinho.', ''],
    ['習う', 'narau', 'aprender (com alguém)', 'presente:習います (naraimasu)|passado:習いました', '先生に日本語を習いました。', 'Aprendi japonês com um professor.', 'Implica um professor; 学ぶ é aprender de forma mais ampla.'],
  ],
  B1: [
    ['貸す', 'kasu', 'emprestar (dar)', 'presente:貸します (kashimasu)|passado:貸しました', '本を貸してくれました。', 'Ele me emprestou o livro.', 'Par com 借りる: o japonês distingue quem dá de quem pega.'],
    ['借りる', 'kariru', 'pegar emprestado', 'presente:借ります (karimasu)|passado:借りました', 'ペンを借りてもいいですか。', 'Posso pegar a caneta emprestada?', ''],
    ['応募する', 'oubo suru', 'candidatar-se', 'presente:応募します|passado:応募しました', 'その仕事に応募しました。', 'Me candidatei àquela vaga.', ''],
    ['雇う', 'yatou', 'contratar', 'presente:雇います (yatoimasu)|passado:雇いました', 'デザイナーを二人雇いました。', 'Contrataram dois designers.', ''],
    ['届ける', 'todokeru', 'entregar', 'presente:届けます (todokemasu)|passado:届けました', '時間どおりに届けました。', 'Entregamos no horário.', ''],
    ['参加する', 'sanka suru', 'participar', 'presente:参加します|passado:参加しました', '会議に参加しました。', 'Participei da reunião.', 'Pede に.'],
    ['気づく', 'kizuku', 'reparar / dar-se conta', 'presente:気づきます|passado:気づきました', '誰も変化に気づきませんでした。', 'Ninguém reparou na mudança.', 'Pede に.'],
    ['認める', 'mitomeru', 'admitir / reconhecer', 'presente:認めます|passado:認めました', '彼はミスを認めました。', 'Ele admitiu o erro.', ''],
    ['断る', 'kotowaru', 'recusar', 'presente:断ります (kotowarimasu)|passado:断りました', '申し出を断りました。', 'Recusou a oferta.', 'Também significa avisar antes de fazer algo.'],
    ['延期する', 'enki suru', 'adiar', 'presente:延期します|passado:延期しました', '発売を延期しました。', 'Adiamos o lançamento.', ''],
    ['決める', 'kimeru', 'decidir', 'presente:決めます (kimemasu)|passado:決めました', '日程を決めましょう。', 'Vamos decidir a data.', 'Transitivo; o intransitivo é 決まる.'],
    ['調べる', 'shiraberu', 'pesquisar / verificar', 'presente:調べます|passado:調べました', '原因を調べています。', 'Estou verificando a causa.', ''],
  ],
  B2: [
    ['割り当てる', 'wariateru', 'destinar / alocar', 'presente:割り当てます|passado:割り当てました', '予算を多く割り当てました。', 'Destinamos mais orçamento.', ''],
    ['公開する', 'koukai suru', 'divulgar / tornar público', 'presente:公開します|passado:公開しました', '条件を公開しました。', 'Divulgaram as condições.', ''],
    ['活用する', 'katsuyou suru', 'aproveitar / utilizar', 'presente:活用します|passado:活用しました', '既存のデータを活用しました。', 'Aproveitamos os dados existentes.', ''],
    ['簡略化する', 'kanryakuka suru', 'simplificar', 'presente:簡略化します|passado:簡略化しました', '手順を簡略化しました。', 'Simplificaram o procedimento.', ''],
    ['統括する', 'toukatsu suru', 'supervisionar', 'presente:統括します|passado:統括しました', '三つのチームを統括しています。', 'Ela supervisiona três equipes.', ''],
    ['引き起こす', 'hikiokosu', 'provocar / causar', 'presente:引き起こします|passado:引き起こしました', '報告書が見直しを引き起こしました。', 'O relatório provocou uma revisão.', ''],
    ['維持する', 'iji suru', 'manter / sustentar', 'presente:維持します|passado:維持しました', '成長を維持しました。', 'Sustentaram o crescimento.', ''],
    ['保留する', 'horyuu suru', 'reter / deixar pendente', 'presente:保留します|passado:保留しました', 'データを保留しました。', 'Retiveram os dados.', ''],
    ['優先する', 'yuusen suru', 'priorizar', 'presente:優先します|passado:優先しました', '安全を優先しました。', 'Priorizamos a segurança.', ''],
    ['主張する', 'shuchou suru', 'alegar / sustentar (uma tese)', 'presente:主張します|passado:主張しました', '報告書は不正を主張しています。', 'O relatório alega fraude.', ''],
    ['支持する', 'shiji suru', 'apoiar / endossar', 'presente:支持します|passado:支持しました', '二つの委員会が計画を支持しました。', 'Dois comitês apoiaram o plano.', ''],
    ['見直す', 'minaosu', 'revisar / reavaliar', 'presente:見直します|passado:見直しました', '方針を見直しています。', 'Estamos revisando a política.', ''],
  ],
  C1: [
    ['裏付ける', 'urazukeru', 'corroborar', 'presente:裏付けます|passado:裏付けました', '二つの資料が裏付けています。', 'Duas fontes corroboram.', ''],
    ['画定する', 'kakutei suru', 'delimitar', 'presente:画定します|passado:画定しました', '範囲を画定します。', 'Delimita-se o escopo.', ''],
    ['規定する', 'kitei suru', 'estipular', 'presente:規定します|passado:規定しました', '契約が期限を規定しています。', 'O contrato estipula um prazo.', ''],
    ['緩和する', 'kanwa suru', 'aliviar / flexibilizar', 'presente:緩和します|passado:緩和しました', 'その措置は圧力を緩和します。', 'A medida alivia a pressão.', ''],
    ['統合する', 'tougou suru', 'consolidar / integrar', 'presente:統合します|passado:統合しました', '結果を統合しました。', 'Consolidaram os resultados.', ''],
    ['帰する', 'ki suru', 'atribuir', 'presente:帰します|passado:帰しました', '原因を運に帰しています。', 'Atribui a causa à sorte.', 'Registro escrito; na fala usa-se ～のせいにする.'],
    ['該当する', 'gaitou suru', 'configurar / enquadrar-se', 'presente:該当します|passado:該当しました', 'それは違反に該当します。', 'Isso configura uma violação.', 'Pede に.'],
    ['着手する', 'chakushu suru', 'empreender / iniciar', 'presente:着手します|passado:着手しました', '監査に着手しました。', 'Iniciamos a auditoria.', 'Pede に.'],
    ['網羅する', 'moura suru', 'abranger', 'presente:網羅します|passado:網羅しました', 'この研究は十年を網羅しています。', 'Este estudo abrange dez anos.', ''],
    ['もたらす', 'motarasu', 'trazer / render', 'presente:もたらします|passado:もたらしました', 'その方法はよい結果をもたらします。', 'Aquele método traz bons resultados.', ''],
    ['制限する', 'seigen suru', 'restringir', 'presente:制限します|passado:制限しました', '支出を制限しました。', 'Restringiram os gastos.', ''],
    ['把握する', 'haaku suru', 'compreender / ter domínio de', 'presente:把握します|passado:把握しました', '状況を把握しています。', 'Tenho domínio da situação.', ''],
  ],
  C2: [
    ['曖昧にする', 'aimai ni suru', 'obscurecer / tornar ambíguo', 'presente:曖昧にします|passado:曖昧にしました', '表現がリスクを曖昧にしています。', 'A redação torna o risco ambíguo.', ''],
    ['敷衍する', 'fuen suru', 'extrapolar / estender', 'presente:敷衍します|passado:敷衍しました', '一例から敷衍はできません。', 'Não se pode extrapolar de um exemplo só.', 'Registro muito literário.'],
    ['回避する', 'kaihi suru', 'contornar / evitar', 'presente:回避します|passado:回避しました', 'その仕組みは規則を回避しています。', 'Aquele mecanismo contorna a regra.', ''],
    ['取って代わる', 'totte kawaru', 'suplantar / substituir', 'presente:取って代わります|passado:取って代わりました', '新版が旧版に取って代わります。', 'A nova versão substitui a antiga.', 'Pede に.'],
    ['正当化する', 'seitouka suru', 'justificar', 'presente:正当化します|passado:正当化しました', '結果が判断を正当化しました。', 'O resultado justificou a decisão.', ''],
    ['格下げする', 'kakusage suru', 'rebaixar / relegar', 'presente:格下げします|passado:格下げしました', '注記に格下げしました。', 'Relegaram a uma nota.', ''],
    ['貶める', 'otoshimeru', 'depreciar', 'presente:貶めます|passado:貶めました', '提案を貶めました。', 'Depreciou a proposta.', ''],
    ['強調する', 'kyouchou suru', 'enfatizar / reforçar', 'presente:強調します|passado:強調しました', 'データが傾向を強調しています。', 'Os dados reforçam a tendência.', ''],
    ['喚起する', 'kanki suru', 'suscitar / despertar', 'presente:喚起します|passado:喚起しました', 'その問いは沈黙を喚起しました。', 'A pergunta suscitou silêncio.', ''],
    ['未然に防ぐ', 'mizen ni fusegu', 'prevenir antes que aconteça', 'presente:未然に防ぎます|passado:未然に防ぎました', 'ストライキを未然に防ぎました。', 'Preveniram a greve antes que ocorresse.', ''],
    ['明記する', 'meiki suru', 'consignar / consagrar por escrito', 'presente:明記します|passado:明記しました', 'その権利は法律に明記されています。', 'Aquele direito está consignado na lei.', ''],
    ['誘発する', 'yuuhatsu suru', 'desencadear', 'presente:誘発します|passado:誘発しました', '判決が危機を誘発しました。', 'A decisão desencadeou uma crise.', ''],
  ],
};
