/** Coreano — verbos de ampliação. Romanização obrigatória. */

import type { ByLevel } from './entry';

export const KO: ByLevel = {
  A1: [
    ['오다', 'oda', 'vir', 'presente:와요 (wayo)|passado:왔어요 (wasseoyo)', '저랑 같이 와요.', 'Venha comigo.', ''],
    ['보다', 'boda', 'ver / assistir', 'presente:봐요 (bwayo)|passado:봤어요 (bwasseoyo)', '버스가 보여요.', 'Dá para ver o ônibus.', ''],
    ['모르다', 'moreuda', 'não saber', 'presente:몰라요 (mollayo)|passado:몰랐어요', '답을 몰라요.', 'Não sei a resposta.', 'Irregular em 르. O coreano tem um verbo próprio para a negação de saber.'],
    ['묻다', 'mutda', 'perguntar', 'presente:물어요 (mureoyo)|passado:물었어요', '길을 물었어요.', 'Perguntei o caminho.', 'Irregular em ㄷ: 묻 + 어요 vira 물어요.'],
    ['만들다', 'mandeulda', 'fazer / preparar', 'presente:만들어요|passado:만들었어요', '저녁을 만들어요.', 'Estou preparando o jantar.', ''],
    ['마시다', 'masida', 'beber', 'presente:마셔요 (masyeoyo)|passado:마셨어요', '물을 마셔요.', 'Bebo água.', ''],
    ['살다', 'salda', 'morar / viver', 'presente:살아요 (sarayo)|passado:살았어요', '포르투에 살아요.', 'Moro no Porto.', ''],
    ['일하다', 'ilhada', 'trabalhar', 'presente:일해요 (ilhaeyo)|passado:일했어요', '집에서 일해요.', 'Trabalho em casa.', ''],
    ['공부하다', 'gongbuhada', 'estudar', 'presente:공부해요|passado:공부했어요', '매일 밤 공부해요.', 'Estudo toda noite.', ''],
    ['돕다', 'dopda', 'ajudar', 'presente:도와요 (dowayo)|passado:도왔어요', '좀 도와주세요.', 'Me ajude, por favor.', 'Verbo irregular em ㅂ: 돕 + 아요 → 도와요.'],
    ['사다', 'sada', 'comprar', 'presente:사요 (sayo)|passado:샀어요', '빵을 사요.', 'Vou comprar pão.', ''],
    ['앉다', 'anda', 'sentar-se', 'presente:앉아요 (anjayo)|passado:앉았어요', '여기 앉으세요.', 'Sente-se aqui.', ''],
  ],
  A2: [
    ['보내다', 'bonaeda', 'enviar', 'presente:보내요|passado:보냈어요', '파일을 보냈어요.', 'Enviei o arquivo.', 'Também é "passar" o tempo.'],
    ['만나다', 'mannada', 'encontrar (pessoa)', 'presente:만나요|passado:만났어요', '어제 친구를 만났어요.', 'Ontem encontrei um amigo.', 'Usa 를/을, diferente do japonês.'],
    ['잊다', 'itda', 'esquecer', 'presente:잊어요|passado:잊었어요', '열쇠를 잊었어요.', 'Esqueci as chaves.', ''],
    ['기억하다', 'gieokada', 'lembrar', 'presente:기억해요|passado:기억했어요', '이름을 기억해요.', 'Lembro o nome.', ''],
    ['고르다', 'goreuda', 'escolher', 'presente:골라요 (gollayo)|passado:골랐어요', '하나 고르세요.', 'Escolha uma.', 'Irregular em 르: 고르 + 아요 → 골라요.'],
    ['대답하다', 'daedapada', 'responder', 'presente:대답해요|passado:대답했어요', '그는 대답하지 않았어요.', 'Ele não respondeu.', ''],
    ['열다', 'yeolda', 'abrir', 'presente:열어요|passado:열었어요', '가게는 아홉 시에 열어요.', 'A loja abre às nove.', ''],
    ['닫다', 'datda', 'fechar', 'presente:닫아요|passado:닫았어요', '문을 닫아 주세요.', 'Feche a porta, por favor.', ''],
    ['여행하다', 'yeohaenghada', 'viajar', 'presente:여행해요|passado:여행했어요', '일 때문에 여행해요.', 'Viajo a trabalho.', ''],
    ['예약하다', 'yeyakada', 'reservar', 'presente:예약해요|passado:예약했어요', '자리를 예약했어요.', 'Reservei um lugar.', ''],
    ['요리하다', 'yorihada', 'cozinhar', 'presente:요리해요|passado:요리했어요', '일요일에 요리해요.', 'Cozinho aos domingos.', ''],
    ['배우다', 'baeuda', 'aprender', 'presente:배워요|passado:배웠어요', '한국어를 배워요.', 'Estou aprendendo coreano.', ''],
  ],
  B1: [
    ['빌려주다', 'billyeojuda', 'emprestar (dar)', 'presente:빌려줘요|passado:빌려줬어요', '책을 빌려줬어요.', 'Ele me emprestou o livro.', 'Par com 빌리다: o coreano distingue quem dá de quem pega.'],
    ['빌리다', 'billida', 'pegar emprestado', 'presente:빌려요|passado:빌렸어요', '펜을 빌릴 수 있어요?', 'Posso pegar a caneta emprestada?', ''],
    ['지원하다', 'jiwonhada', 'candidatar-se / apoiar', 'presente:지원해요|passado:지원했어요', '그 자리에 지원했어요.', 'Me candidatei àquela vaga.', 'Dois sentidos: candidatar-se e dar suporte.'],
    ['채용하다', 'chaeyonghada', 'contratar', 'presente:채용해요|passado:채용했어요', '디자이너 두 명을 채용했어요.', 'Contrataram dois designers.', ''],
    ['전달하다', 'jeondalhada', 'entregar / transmitir', 'presente:전달해요|passado:전달했어요', '제시간에 전달했어요.', 'Entregamos no horário.', ''],
    ['참석하다', 'chamseokada', 'comparecer', 'presente:참석해요|passado:참석했어요', '회의에 참석했어요.', 'Compareci à reunião.', 'Pede 에.'],
    ['알아차리다', 'alachalida', 'reparar / dar-se conta', 'presente:알아차려요|passado:알아차렸어요', '아무도 변화를 알아차리지 못했어요.', 'Ninguém percebeu a mudança.', ''],
    ['시인하다', 'siinhada', 'admitir (uma falta)', 'presente:시인해요|passado:시인했어요', '실수를 시인했어요.', 'Ele admitiu o erro.', 'Registro mais formal que 인정하다.'],
    ['거절하다', 'geojeolhada', 'recusar', 'presente:거절해요|passado:거절했어요', '제안을 거절했어요.', 'Recusou a proposta.', ''],
    ['연기하다', 'yeongihada', 'adiar', 'presente:연기해요|passado:연기했어요', '출시를 연기했어요.', 'Adiamos o lançamento.', 'Homônimo de "atuação" e "fumaça" — o contexto resolve.'],
    ['정하다', 'jeonghada', 'definir / marcar', 'presente:정해요|passado:정했어요', '날짜를 정합시다.', 'Vamos marcar a data.', ''],
    ['알아보다', 'alaboda', 'verificar / pesquisar', 'presente:알아봐요|passado:알아봤어요', '원인을 알아보고 있어요.', 'Estou verificando a causa.', ''],
  ],
  B2: [
    ['배정하다', 'baejeonghada', 'alocar / destinar', 'presente:배정해요|passado:배정했어요', '예산을 더 배정했어요.', 'Destinamos mais orçamento.', ''],
    ['공개하다', 'gonggaehada', 'divulgar', 'presente:공개해요|passado:공개했어요', '조건을 공개했어요.', 'Divulgaram as condições.', ''],
    ['응용하다', 'eungyonghada', 'aplicar (na prática)', 'presente:응용해요|passado:응용했어요', '이론을 현장에 응용했어요.', 'Aplicamos a teoria no campo.', ''],
    ['간소화하다', 'gansohwahada', 'simplificar', 'presente:간소화해요|passado:간소화했어요', '절차를 간소화했어요.', 'Simplificaram o procedimento.', ''],
    ['총괄하다', 'chonggwalhada', 'supervisionar', 'presente:총괄해요|passado:총괄했어요', '세 팀을 총괄해요.', 'Ela supervisiona três equipes.', ''],
    ['초래하다', 'choraehada', 'provocar / acarretar', 'presente:초래해요|passado:초래했어요', '보고서가 재검토를 초래했어요.', 'O relatório acarretou uma revisão.', 'Quase sempre com consequência negativa.'],
    ['유지하다', 'yujihada', 'manter / sustentar', 'presente:유지해요|passado:유지했어요', '성장을 유지했어요.', 'Sustentaram o crescimento.', ''],
    ['보류하다', 'boryuhada', 'reter / suspender', 'presente:보류해요|passado:보류했어요', '자료를 보류했어요.', 'Retiveram o material.', ''],
    ['배려하다', 'baeryeohada', 'considerar / ter consideração por', 'presente:배려해요|passado:배려했어요', '상대를 배려했어요.', 'Tive consideração pelo outro.', ''],
    ['주장하다', 'jujanghada', 'alegar / sustentar', 'presente:주장해요|passado:주장했어요', '보고서는 부정을 주장해요.', 'O relatório alega irregularidade.', ''],
    ['지지하다', 'jijihada', 'apoiar / endossar', 'presente:지지해요|passado:지지했어요', '두 위원회가 계획을 지지했어요.', 'Dois comitês apoiaram o plano.', ''],
    ['검토하다', 'geomtohada', 'analisar / revisar', 'presente:검토해요|passado:검토했어요', '방침을 검토하고 있어요.', 'Estamos revisando a política.', ''],
  ],
  C1: [
    ['방증하다', 'bangjeunghada', 'evidenciar indiretamente', 'presente:방증해요|passado:방증했어요', '이 수치가 문제를 방증해요.', 'Esses números evidenciam o problema.', 'Prova indireta: aponta para a conclusão sem demonstrá-la.'],
    ['획정하다', 'hoekjeonghada', 'delimitar', 'presente:획정해요|passado:획정했어요', '범위를 획정합니다.', 'Delimita-se o escopo.', ''],
    ['규정하다', 'gyujeonghada', 'estipular', 'presente:규정해요|passado:규정했어요', '계약이 기한을 규정해요.', 'O contrato estipula um prazo.', ''],
    ['경감하다', 'gyeonggamhada', 'reduzir / atenuar', 'presente:경감해요|passado:경감했어요', '그 조치는 부담을 경감해요.', 'A medida reduz o encargo.', ''],
    ['통합하다', 'tonghapada', 'consolidar / integrar', 'presente:통합해요|passado:통합했어요', '결과를 통합했어요.', 'Consolidaram os resultados.', ''],
    ['돌리다', 'dollida', 'atribuir / devolver', 'presente:돌려요|passado:돌렸어요', '원인을 운으로 돌려요.', 'Atribui a causa à sorte.', 'Com 으로 significa atribuir.'],
    ['해당하다', 'haedanghada', 'enquadrar-se / configurar', 'presente:해당해요|passado:해당했어요', '그것은 위반에 해당해요.', 'Isso configura uma violação.', 'Pede 에.'],
    ['착수하다', 'chaksuhada', 'iniciar / empreender', 'presente:착수해요|passado:착수했어요', '감사에 착수했어요.', 'Iniciamos a auditoria.', 'Pede 에.'],
    ['망라하다', 'mangnahada', 'abranger', 'presente:망라해요|passado:망라했어요', '이 연구는 십 년을 망라해요.', 'Este estudo abrange dez anos.', ''],
    ['도출하다', 'dochulhada', 'derivar / obter (resultado)', 'presente:도출해요|passado:도출했어요', '그 방법은 더 나은 결과를 도출해요.', 'Aquele método obtém melhores resultados.', ''],
    ['제한하다', 'jehanhada', 'restringir', 'presente:제한해요|passado:제한했어요', '지출을 제한했어요.', 'Restringiram os gastos.', ''],
    ['파악하다', 'paakada', 'compreender / ter domínio de', 'presente:파악해요|passado:파악했어요', '상황을 파악하고 있어요.', 'Tenho domínio da situação.', ''],
  ],
  C2: [
    ['왜곡하다', 'waegokada', 'distorcer', 'presente:왜곡해요|passado:왜곡했어요', '표현이 사실을 왜곡해요.', 'A redação distorce os fatos.', ''],
    ['유추하다', 'yuchuhada', 'inferir / extrapolar', 'presente:유추해요|passado:유추했어요', '한 사례로 유추할 수 없어요.', 'Não se pode extrapolar de um caso só.', ''],
    ['회피하다', 'hoepihada', 'contornar / esquivar-se', 'presente:회피해요|passado:회피했어요', '그 구조는 규정을 회피해요.', 'Aquela estrutura contorna a norma.', ''],
    ['대체하다', 'daechehada', 'substituir', 'presente:대체해요|passado:대체했어요', '새 판이 이전 판을 대체해요.', 'A nova versão substitui a anterior.', ''],
    ['합리화하다', 'hallihwahada', 'racionalizar / arranjar justificativa', 'presente:합리화해요|passado:합리화했어요', '실패를 합리화했어요.', 'Arranjou justificativa para o fracasso.', 'Tem carga negativa: é justificar o injustificável.'],
    ['격하하다', 'gyeokahada', 'rebaixar / relegar', 'presente:격하해요|passado:격하했어요', '각주로 격하했어요.', 'Relegaram a uma nota.', ''],
    ['폄하하다', 'pyeomhahada', 'depreciar', 'presente:폄하해요|passado:폄하했어요', '제안을 폄하했어요.', 'Depreciou a proposta.', ''],
    ['강조하다', 'gangjohada', 'enfatizar / reforçar', 'presente:강조해요|passado:강조했어요', '자료가 추세를 강조해요.', 'Os dados reforçam a tendência.', ''],
    ['불러일으키다', 'bulleoireukida', 'suscitar / despertar', 'presente:불러일으켜요|passado:불러일으켰어요', '그 질문이 침묵을 불러일으켰어요.', 'Aquela pergunta suscitou silêncio.', ''],
    ['미연에 방지하다', 'miyeone bangjihada', 'prevenir antes que ocorra', 'presente:미연에 방지해요|passado:미연에 방지했어요', '파업을 미연에 방지했어요.', 'Preveniram a greve antes que ocorresse.', ''],
    ['명시하다', 'myeongsihada', 'consignar / explicitar', 'presente:명시해요|passado:명시했어요', '그 권리는 법에 명시돼 있어요.', 'Aquele direito está explicitado na lei.', ''],
    ['촉발하다', 'chokbalhada', 'desencadear', 'presente:촉발해요|passado:촉발했어요', '판결이 위기를 촉발했어요.', 'A decisão desencadeou uma crise.', ''],
  ],
};
