/** Mandarim — verbos de ampliação. Pinyin obrigatório. */

import type { ByLevel } from './entry';

export const ZH: ByLevel = {
  A1: [
    ['来', 'lái', 'vir', 'presente:来|passado:来了 (lái le)', '跟我来。', 'Venha comigo.', 'O chinês não conjuga: o tempo vem de partículas como 了.'],
    ['看', 'kàn', 'ver / olher / ler', 'presente:看|passado:看了 (kàn le)', '我看见公共汽车了。', 'Eu vi o ônibus.', 'Cobre ver, assistir e ler — o contexto decide.'],
    ['知道', 'zhīdào', 'saber', 'presente:知道|negativo:不知道', '我知道答案。', 'Sei a resposta.', '知道 é saber um fato; 认识 é conhecer pessoa.'],
    ['认识', 'rènshi', 'conhecer (pessoa/lugar)', 'presente:认识|passado:认识了', '我认识她。', 'Eu a conheço.', ''],
    ['问', 'wèn', 'perguntar', 'presente:问|passado:问了 (wèn le)', '我问了路。', 'Perguntei o caminho.', ''],
    ['吃', 'chī', 'comer', 'presente:吃|passado:吃了 (chī le)', '我们十二点吃饭。', 'A gente come ao meio-dia.', 'Comer refeição é 吃饭 — o objeto genérico é obrigatório.'],
    ['喝', 'hē', 'beber', 'presente:喝|passado:喝了 (hē le)', '我喝水。', 'Bebo água.', ''],
    ['住', 'zhù', 'morar', 'presente:住|passado:住过 (zhù guo)', '他们住在波尔图。', 'Eles moram no Porto.', 'Pede 在 antes do lugar.'],
    ['工作', 'gōngzuò', 'trabalhar', 'presente:工作|passado:工作了', '我在家工作。', 'Trabalho em casa.', 'Também é substantivo: "trabalho".'],
    ['学习', 'xuéxí', 'estudar / aprender', 'presente:学习|passado:学习了', '我每天晚上学习。', 'Estudo toda noite.', ''],
    ['帮助', 'bāngzhù', 'ajudar', 'presente:帮助|passado:帮助了', '你能帮助我吗？', 'Você pode me ajudar?', 'Na fala usa-se mais 帮忙 ou só 帮.'],
    ['买', 'mǎi', 'comprar', 'presente:买|passado:买了 (mǎi le)', '我买面包。', 'Vou comprar pão.', 'Cuidado com o tom: 买 (mǎi) é comprar, 卖 (mài) é vender.'],
  ],
  A2: [
    ['发送', 'fāsòng', 'enviar', 'presente:发送|passado:发送了', '我发送了文件。', 'Enviei o arquivo.', 'Na fala cotidiana usa-se só 发.'],
    ['见面', 'jiànmiàn', 'encontrar-se', 'presente:见面|passado:见面了', '我们昨天见面了。', 'A gente se encontrou ontem.', 'Verbo separável: "见你的面", nunca "见面你".'],
    ['忘记', 'wàngjì', 'esquecer', 'presente:忘记|passado:忘记了', '我忘记带钥匙了。', 'Esqueci de trazer as chaves.', ''],
    ['记得', 'jìde', 'lembrar', 'presente:记得|negativo:不记得', '记得给她打电话。', 'Lembre de ligar para ela.', ''],
    ['选择', 'xuǎnzé', 'escolher', 'presente:选择|passado:选择了', '请选择一个。', 'Escolha uma, por favor.', ''],
    ['回答', 'huídá', 'responder', 'presente:回答|passado:回答了', '他没有回答。', 'Ele não respondeu.', ''],
    ['开', 'kāi', 'abrir / ligar / dirigir', 'presente:开|passado:开了', '商店九点开门。', 'A loja abre às nove.', 'Cobre abrir, ligar aparelho e dirigir carro.'],
    ['关', 'guān', 'fechar / desligar', 'presente:关|passado:关了', '请关窗户。', 'Feche a janela, por favor.', ''],
    ['旅行', 'lǚxíng', 'viajar', 'presente:旅行|passado:旅行了', '我因为工作旅行。', 'Viajo a trabalho.', ''],
    ['预订', 'yùdìng', 'reservar', 'presente:预订|passado:预订了', '我预订了一张桌子。', 'Reservei uma mesa.', ''],
    ['做饭', 'zuòfàn', 'cozinhar', 'presente:做饭|passado:做饭了', '他星期天做饭。', 'Ele cozinha aos domingos.', 'Separável: "做了饭".'],
    ['懂', 'dǒng', 'entender', 'presente:懂|negativo:不懂', '我懂了。', 'Entendi.', 'Estado, não ação: não leva 在.'],
  ],
  B1: [
    ['借给', 'jiè gěi', 'emprestar (dar)', 'presente:借给|passado:借给了', '她借给我一本书。', 'Ela me emprestou um livro.', '借 sozinho serve para dar e para pegar; 给 desfaz a ambiguidade.'],
    ['借', 'jiè', 'pegar emprestado', 'presente:借|passado:借了', '我可以借你的笔吗？', 'Posso pegar sua caneta emprestada?', ''],
    ['申请', 'shēnqǐng', 'candidatar-se / solicitar', 'presente:申请|passado:申请了', '我申请了那个职位。', 'Me candidatei àquela vaga.', ''],
    ['聘用', 'pìnyòng', 'contratar', 'presente:聘用|passado:聘用了', '他们聘用了两名设计师。', 'Contrataram dois designers.', 'Na fala usa-se mais 招 ou 请.'],
    ['交付', 'jiāofù', 'entregar', 'presente:交付|passado:交付了', '我们按时交付了。', 'Entregamos no prazo.', ''],
    ['参加', 'cānjiā', 'participar', 'presente:参加|passado:参加了', '我参加了会议。', 'Participei da reunião.', ''],
    ['注意到', 'zhùyì dào', 'reparar', 'presente:注意到|passado:注意到了', '没人注意到变化。', 'Ninguém reparou na mudança.', '到 marca que a percepção se completou.'],
    ['坦白', 'tǎnbái', 'confessar / abrir o jogo', 'presente:坦白|passado:坦白了', '他坦白了实情。', 'Ele confessou a verdade.', ''],
    ['拒绝', 'jùjué', 'recusar', 'presente:拒绝|passado:拒绝了', '她拒绝了这个提议。', 'Ela recusou a proposta.', ''],
    ['推迟', 'tuīchí', 'adiar', 'presente:推迟|passado:推迟了', '我们推迟了发布。', 'Adiamos o lançamento.', ''],
    ['安排', 'ānpái', 'organizar / marcar', 'presente:安排|passado:安排了', '我安排了一次通话。', 'Marquei uma ligação.', ''],
    ['欠', 'qiàn', 'dever (dinheiro)', 'presente:欠|passado:欠了', '你不欠我什么。', 'Você não me deve nada.', 'Diferente de 应该, que é dever de obrigação.'],
  ],
  B2: [
    ['分配', 'fēnpèi', 'alocar / distribuir', 'presente:分配|passado:分配了', '我们分配了更多预算。', 'Alocamos mais orçamento.', ''],
    ['披露', 'pīlù', 'divulgar / revelar', 'presente:披露|passado:披露了', '他们披露了条款。', 'Divulgaram as cláusulas.', 'Registro jornalístico e corporativo.'],
    ['借助', 'jièzhù', 'apoiar-se em / valer-se de', 'presente:借助|passado:借助了', '我们借助现有数据完成了分析。', 'Concluímos a análise valendo-nos dos dados existentes.', ''],
    ['简化', 'jiǎnhuà', 'simplificar', 'presente:简化|passado:简化了', '他们简化了流程。', 'Simplificaram o processo.', ''],
    ['监督', 'jiāndū', 'supervisionar', 'presente:监督|passado:监督了', '她监督三个团队。', 'Ela supervisiona três equipes.', ''],
    ['引发', 'yǐnfā', 'provocar / desencadear', 'presente:引发|passado:引发了', '报告引发了一次复核。', 'O relatório provocou uma revisão.', ''],
    ['维持', 'wéichí', 'manter / sustentar', 'presente:维持|passado:维持了', '他们维持了增长。', 'Sustentaram o crescimento.', ''],
    ['扣留', 'kòuliú', 'reter', 'presente:扣留|passado:扣留了', '他扣留了数据。', 'Ele reteve os dados.', ''],
    ['侧重', 'cèzhòng', 'dar ênfase a', 'presente:侧重|passado:侧重了', '这份报告侧重成本。', 'Esse relatório dá ênfase ao custo.', ''],
    ['主张', 'zhǔzhāng', 'defender / alegar', 'presente:主张|passado:主张了', '报告主张存在欺诈。', 'O relatório alega que há fraude.', ''],
    ['支持', 'zhīchí', 'apoiar / endossar', 'presente:支持|passado:支持了', '两个委员会支持该计划。', 'Dois comitês apoiaram o plano.', ''],
    ['审视', 'shěnshì', 'examinar / revisar', 'presente:审视|passado:审视了', '我们在审视这项政策。', 'Estamos revisando essa política.', ''],
  ],
  C1: [
    ['佐证', 'zuǒzhèng', 'corroborar', 'presente:佐证|passado:佐证了', '两份材料佐证了这一点。', 'Duas fontes corroboram isso.', ''],
    ['界定', 'jièdìng', 'delimitar / definir', 'presente:界定|passado:界定了', '文章界定了范围。', 'O artigo delimita o escopo.', ''],
    ['规定', 'guīdìng', 'estipular', 'presente:规定|passado:规定了', '合同规定了期限。', 'O contrato estipula um prazo.', ''],
    ['减轻', 'jiǎnqīng', 'reduzir / atenuar', 'presente:减轻|passado:减轻了', '这项措施减轻了负担。', 'Essa medida reduziu o encargo.', ''],
    ['整合', 'zhěnghé', 'consolidar / integrar', 'presente:整合|passado:整合了', '他们整合了结果。', 'Consolidaram os resultados.', ''],
    ['归因于', 'guīyīn yú', 'atribuir a', 'presente:归因于|passado:归因于了', '他把结果归因于运气。', 'Ele atribui o resultado à sorte.', 'Registro escrito; na fala, 是因为.'],
    ['构成', 'gòuchéng', 'constituir / configurar', 'presente:构成|passado:构成了', '这构成违规。', 'Isso configura uma irregularidade.', ''],
    ['着手', 'zhuóshǒu', 'iniciar / empreender', 'presente:着手|passado:着手了', '我们着手进行审计。', 'Iniciamos a auditoria.', ''],
    ['涵盖', 'hángài', 'abranger', 'presente:涵盖|passado:涵盖了', '研究涵盖十年。', 'O estudo abrange dez anos.', ''],
    ['使', 'shǐ', 'tornar / fazer com que', 'presente:使|passado:使得', '延误使它失去意义。', 'O atraso o tornou sem sentido.', 'Estrutura causativa culta.'],
    ['产生', 'chǎnshēng', 'produzir / gerar', 'presente:产生|passado:产生了', '这个方法产生更好的数据。', 'Esse método gera dados melhores.', ''],
    ['限制', 'xiànzhì', 'restringir', 'presente:限制|passado:限制了', '他们限制了开支。', 'Restringiram os gastos.', ''],
  ],
  C2: [
    ['掩盖', 'yǎngài', 'encobrir / obscurecer', 'presente:掩盖|passado:掩盖了', '措辞掩盖了风险。', 'A redação encobre o risco.', ''],
    ['推演', 'tuīyǎn', 'extrapolar / deduzir', 'presente:推演|passado:推演了', '不能从单一案例推演。', 'Não se pode extrapolar de um caso só.', ''],
    ['规避', 'guībì', 'contornar (uma regra)', 'presente:规避|passado:规避了', '该安排规避了规定。', 'Aquele arranjo contorna a norma.', ''],
    ['取代', 'qǔdài', 'substituir / suplantar', 'presente:取代|passado:取代了', '新版取代旧版。', 'A nova versão substitui a antiga.', ''],
    ['证明', 'zhèngmíng', 'provar / dar razão a', 'presente:证明|passado:证明了', '结果证明她是对的。', 'O resultado provou que ela tinha razão.', ''],
    ['贬为', 'biǎn wéi', 'rebaixar a / relegar a', 'presente:贬为|passado:贬为了', '他们把它贬为一条注释。', 'Relegaram isso a uma nota.', ''],
    ['贬低', 'biǎndī', 'depreciar', 'presente:贬低|passado:贬低了', '他贬低了这个提案。', 'Ele depreciou a proposta.', ''],
    ['凸显', 'tūxiǎn', 'evidenciar / reforçar', 'presente:凸显|passado:凸显了', '数据凸显了这一趋势。', 'Os dados evidenciam essa tendência.', ''],
    ['引起', 'yǐnqǐ', 'suscitar / causar', 'presente:引起|passado:引起了', '这个问题引起了沉默。', 'Aquela pergunta suscitou silêncio.', ''],
    ['防患于未然', 'fánghuàn yú wèirán', 'prevenir antes que aconteça', 'presente:防患于未然|passado:防患于未然了', '这项举措防患于未然。', 'Essa iniciativa preveniu o problema antes.', 'Expressão de quatro caracteres usada como verbo.'],
    ['载明', 'zǎimíng', 'consignar (em documento)', 'presente:载明|passado:载明了', '该权利已载明于法律。', 'Aquele direito já está consignado em lei.', 'Registro jurídico.'],
    ['触发', 'chùfā', 'desencadear', 'presente:触发|passado:触发了', '判决触发了一场危机。', 'A decisão desencadeou uma crise.', ''],
  ],
};
