/** Alemão — terceiro lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const DE_THEMATIC3: LatinByLevel = {
  A1: [
    ['der Sohn', 'filho', 'substantivo', 'Mein Sohn ist fünf.', 'Meu filho tem cinco anos.', 'Família e pessoas'],
    ['die Tochter', 'filha', 'substantivo', 'Ihre Tochter studiert hier.', 'A filha dela estuda aqui.', 'Família e pessoas'],
    ['die Großmutter', 'avó', 'substantivo', 'Meine Großmutter kocht gut.', 'Minha avó cozinha bem.', 'Família e pessoas'],
    ['der Großvater', 'avô', 'substantivo', 'Mein Großvater erzählt Geschichten.', 'Meu avô conta histórias.', 'Família e pessoas'],
    ['der Onkel', 'tio', 'substantivo', 'Mein Onkel wohnt weit weg.', 'Meu tio mora longe.', 'Família e pessoas'],
    ['die Tante', 'tia', 'substantivo', 'Meine Tante ist Krankenschwester.', 'Minha tia é enfermeira.', 'Família e pessoas'],
    ['der Cousin', 'primo', 'substantivo', 'Mein Cousin ist so alt wie ich.', 'Meu primo tem a minha idade.', 'Família e pessoas'],
    ['die Ehefrau', 'esposa', 'substantivo', 'Seine Ehefrau arbeitet in der Stadt.', 'A esposa dele trabalha na cidade.', 'Família e pessoas'],
    ['der Ehemann', 'marido', 'substantivo', 'Ihr Ehemann ist Lehrer.', 'O marido dela é professor.', 'Família e pessoas'],
    ['der Freund', 'amigo', 'substantivo', 'Er ist mein bester Freund.', 'Ele é meu melhor amigo.', 'Família e pessoas'],
    ['das Zimmer', 'quarto / cômodo', 'substantivo', 'Dieses Zimmer ist ruhig.', 'Este quarto é silencioso.', 'Casa e cômodos'],
    ['das Wohnzimmer', 'sala de estar', 'substantivo', 'Wir sehen im Wohnzimmer fern.', 'Assistimos TV na sala de estar.', 'Casa e cômodos'],
    ['das Schlafzimmer', 'dormitório', 'substantivo', 'Das Schlafzimmer ist oben.', 'O dormitório fica em cima.', 'Casa e cômodos'],
    ['der Garten', 'jardim', 'substantivo', 'Der Garten braucht Wasser.', 'O jardim precisa de água.', 'Casa e cômodos'],
    ['die Wand', 'parede', 'substantivo', 'Die Wand ist schmutzig.', 'A parede está suja.', 'Casa e cômodos'],
    ['der Boden', 'chão', 'substantivo', 'Der Boden ist nass.', 'O chão está molhado.', 'Casa e cômodos'],
    ['die Treppe', 'escada', 'substantivo', 'Die Treppe ist steil.', 'A escada é íngreme.', 'Casa e cômodos'],
    ['der Schlüssel', 'chave', 'substantivo', 'Ich habe meinen Schlüssel verloren.', 'Perdi minha chave.', 'Casa e cômodos'],
    ['die Lampe', 'luminária', 'substantivo', 'Mach die Lampe an.', 'Acenda a luminária.', 'Casa e cômodos'],
    ['die Garage', 'garagem', 'substantivo', 'Das Auto steht in der Garage.', 'O carro está na garagem.', 'Casa e cômodos'],
  ],
  A2: [
    ['der Gürtel', 'cinto', 'substantivo', 'Dieser Gürtel ist zu lang.', 'Este cinto é comprido demais.', 'Vestuário e aparência'],
    ['der Schal', 'cachecol', 'substantivo', 'Nimm einen Schal, es ist kalt.', 'Leve um cachecol, está frio.', 'Vestuário e aparência'],
    ['der Handschuh', 'luva', 'substantivo', 'Ich habe einen Handschuh verloren.', 'Perdi uma luva.', 'Vestuário e aparência'],
    ['der Stiefel', 'bota', 'substantivo', 'Diese Stiefel sind schwer.', 'Estas botas são pesadas.', 'Vestuário e aparência'],
    ['der Ärmel', 'manga (de roupa)', 'substantivo', 'Der Ärmel ist zerrissen.', 'A manga está rasgada.', 'Vestuário e aparência'],
    ['die Tasche', 'bolso', 'substantivo', 'Es ist in meiner Tasche.', 'Está no meu bolso.', 'Vestuário e aparência'],
    ['der Knopf', 'botão', 'substantivo', 'Ein Knopf ist abgefallen.', 'Caiu um botão.', 'Vestuário e aparência'],
    ['der Reißverschluss', 'zíper', 'substantivo', 'Der Reißverschluss klemmt.', 'O zíper está emperrado.', 'Vestuário e aparência'],
    ['der Bart', 'barba', 'substantivo', 'Er hat sich einen Bart wachsen lassen.', 'Ele deixou a barba crescer.', 'Vestuário e aparência'],
    ['das Make-up', 'maquiagem', 'substantivo', 'Sie trägt wenig Make-up.', 'Ela usa pouca maquiagem.', 'Vestuário e aparência'],
    ['der Geburtstag', 'aniversário', 'substantivo', 'Heute ist mein Geburtstag.', 'Hoje é meu aniversário.', 'Datas e festas'],
    ['der Feiertag', 'feriado', 'substantivo', 'Montag ist ein Feiertag.', 'Segunda é feriado.', 'Datas e festas'],
    ['die Hochzeit', 'casamento', 'substantivo', 'Die Hochzeit ist im Juni.', 'O casamento é em junho.', 'Datas e festas'],
    ['das Geschenk', 'presente', 'substantivo', 'Danke für das Geschenk.', 'Obrigado pelo presente.', 'Datas e festas'],
    ['die Party', 'festa', 'substantivo', 'Die Party beginnt um neun.', 'A festa começa às nove.', 'Datas e festas'],
    ['die Kerze', 'vela', 'substantivo', 'Zünde die Kerzen an.', 'Acenda as velas.', 'Datas e festas'],
    ['die Einladung', 'convite', 'substantivo', 'Ich habe die Einladung bekommen.', 'Recebi o convite.', 'Datas e festas'],
    ['der Jahrestag', 'data comemorativa', 'substantivo', 'Es ist unser zehnter Jahrestag.', 'É nosso décimo aniversário.', 'Datas e festas'],
    ['feiern', 'comemorar', 'verbo', 'Wir feiern am Samstag.', 'Comemoramos no sábado.', 'Datas e festas'],
    ['der Gast', 'convidado', 'substantivo', 'Zwanzig Gäste kommen.', 'Vêm vinte convidados.', 'Datas e festas'],
  ],
  B1: [
    ['der Abschluss', 'diploma / conclusão de curso', 'substantivo', 'Sie hat einen juristischen Abschluss.', 'Ela tem diploma em direito.', 'Educação superior'],
    ['die Doktorarbeit', 'tese de doutorado', 'substantivo', 'Er schreibt seine Doktorarbeit.', 'Ele está escrevendo a tese.', 'Educação superior'],
    ['die Vorlesung', 'aula expositiva', 'substantivo', 'Die Vorlesung dauerte zwei Stunden.', 'A aula expositiva durou duas horas.', 'Educação superior'],
    ['der Dozent', 'docente universitário', 'substantivo', 'Der Dozent hat ein Buch veröffentlicht.', 'O docente publicou um livro.', 'Educação superior'],
    ['der Campus', 'campus', 'substantivo', 'Der Campus ist riesig.', 'O campus é enorme.', 'Educação superior'],
    ['das Semester', 'semestre', 'substantivo', 'Das Semester endet im Juli.', 'O semestre acaba em julho.', 'Educação superior'],
    ['sich einschreiben', 'matricular-se', 'verbo', 'Ich schreibe mich nächsten Monat ein.', 'Vou me matricular mês que vem.', 'Educação superior'],
    ['das Studentenwohnheim', 'moradia estudantil', 'substantivo', 'Sie wohnt im Studentenwohnheim.', 'Ela mora na moradia estudantil.', 'Educação superior'],
    ['den Abschluss machen', 'formar-se', 'verbo', 'Sie machen im Dezember den Abschluss.', 'Eles se formam em dezembro.', 'Educação superior'],
    ['das Seminar', 'seminário', 'substantivo', 'Das Seminar war klein.', 'O seminário era pequeno.', 'Educação superior'],
    ['die Jugendherberge', 'albergue', 'substantivo', 'Wir haben in einer Jugendherberge geschlafen.', 'Dormimos num albergue.', 'Viagem e hospedagem'],
    ['die Hotelbuchung', 'reserva de hotel', 'substantivo', 'Meine Hotelbuchung wurde storniert.', 'Minha reserva de hotel foi cancelada.', 'Viagem e hospedagem'],
    ['das Einchecken', 'check-in', 'substantivo', 'Das Einchecken beginnt um vierzehn Uhr.', 'O check-in começa às duas.', 'Viagem e hospedagem'],
    ['der Rezeptionist', 'recepcionista', 'substantivo', 'Frag den Rezeptionisten.', 'Pergunte ao recepcionista.', 'Viagem e hospedagem'],
    ['die Lobby', 'saguão', 'substantivo', 'Warte in der Lobby auf mich.', 'Me espere no saguão.', 'Viagem e hospedagem'],
    ['das Wahrzeichen', 'marco / ponto turístico', 'substantivo', 'Der Turm ist ein Wahrzeichen.', 'A torre é um marco da cidade.', 'Viagem e hospedagem'],
    ['das Reiseandenken', 'lembrança de viagem', 'substantivo', 'Ich habe ein Reiseandenken gekauft.', 'Comprei uma lembrança de viagem.', 'Viagem e hospedagem'],
    ['der Reiseführer', 'guia de viagem', 'substantivo', 'Der Reiseführer ist veraltet.', 'O guia de viagem está desatualizado.', 'Viagem e hospedagem'],
    ['das Visum', 'visto', 'substantivo', 'Ich brauche ein Visum.', 'Preciso de visto.', 'Viagem e hospedagem'],
    ['der Tourist', 'turista', 'substantivo', 'Die Stadt ist voller Touristen.', 'A cidade está cheia de turistas.', 'Viagem e hospedagem'],
  ],
  B2: [
    ['der Algorithmus', 'algoritmo', 'substantivo', 'Der Algorithmus sortiert die Treffer.', 'O algoritmo ordena os resultados.', 'Tecnologia avançada'],
    ['die Verschlüsselung', 'criptografia', 'substantivo', 'Die Verschlüsselung schützt die Daten.', 'A criptografia protege os dados.', 'Tecnologia avançada'],
    ['die Bandbreite', 'largura de banda', 'substantivo', 'Uns ging die Bandbreite aus.', 'Ficamos sem largura de banda.', 'Tecnologia avançada'],
    ['der Server', 'servidor', 'substantivo', 'Der Server ist ausgefallen.', 'O servidor caiu.', 'Tecnologia avançada'],
    ['die Datenbank', 'banco de dados', 'substantivo', 'Sichere die Datenbank.', 'Faça backup do banco de dados.', 'Tecnologia avançada'],
    ['die Schnittstelle', 'interface', 'substantivo', 'Die Schnittstelle ist verwirrend.', 'A interface é confusa.', 'Tecnologia avançada'],
    ['die Automatisierung', 'automação', 'substantivo', 'Die Automatisierung senkte die Kosten.', 'A automação baixou os custos.', 'Tecnologia avançada'],
    ['die Firewall', 'firewall', 'substantivo', 'Die Firewall hat es blockiert.', 'O firewall bloqueou.', 'Tecnologia avançada'],
    ['der Prototyp', 'protótipo', 'substantivo', 'Wir haben einen Prototyp gebaut.', 'Construímos um protótipo.', 'Tecnologia avançada'],
    ['die Latenz', 'latência', 'substantivo', 'Latenz ruiniert das Erlebnis.', 'A latência arruína a experiência.', 'Tecnologia avançada'],
    ['die Werbung', 'publicidade', 'substantivo', 'Die Werbung trieb den Absatz.', 'A publicidade impulsionou as vendas.', 'Consumo e marketing'],
    ['der Verbraucher', 'consumidor', 'substantivo', 'Der Verbraucher entscheidet.', 'O consumidor decide.', 'Consumo e marketing'],
    ['der Einzelhandel', 'varejo', 'substantivo', 'Die Margen im Einzelhandel sind dünn.', 'As margens do varejo são apertadas.', 'Consumo e marketing'],
    ['der Großhandel', 'atacado', 'substantivo', 'Sie kaufen im Großhandel.', 'Eles compram no atacado.', 'Consumo e marketing'],
    ['die Verpackung', 'embalagem', 'substantivo', 'Die Verpackung ist Verschwendung.', 'A embalagem é desperdício.', 'Consumo e marketing'],
    ['das Logo', 'logotipo', 'substantivo', 'Das Logo wurde neu gestaltet.', 'O logotipo foi redesenhado.', 'Consumo e marketing'],
    ['der Werbespruch', 'slogan', 'substantivo', 'Der Werbespruch blieb hängen.', 'O slogan pegou.', 'Consumo e marketing'],
    ['die Zielgruppe', 'público-alvo', 'substantivo', 'Definiere zuerst die Zielgruppe.', 'Defina o público-alvo primeiro.', 'Consumo e marketing'],
    ['die Werbepartnerschaft', 'parceria publicitária', 'substantivo', 'Die Werbepartnerschaft kostete ein Vermögen.', 'A parceria publicitária custou uma fortuna.', 'Consumo e marketing'],
    ['der Aufschlag', 'margem de lucro', 'substantivo', 'Der Aufschlag ist zu hoch.', 'A margem de lucro é alta demais.', 'Consumo e marketing'],
  ],
  C1: [
    ['der Vermögenswert', 'ativo (patrimônio)', 'substantivo', 'Der Vermögenswert verlor an Wert.', 'O ativo perdeu valor.', 'Finanças'],
    ['das Eigenkapital', 'patrimônio líquido', 'substantivo', 'Das Eigenkapital schrumpfte.', 'O patrimônio líquido encolheu.', 'Finanças'],
    ['die Dividende', 'dividendo', 'substantivo', 'Sie kürzten die Dividende.', 'Cortaram o dividendo.', 'Finanças'],
    ['das Portfolio', 'carteira de investimentos', 'substantivo', 'Streue das Portfolio breiter.', 'Diversifique a carteira.', 'Finanças'],
    ['die Absicherung', 'proteção contra risco', 'substantivo', 'Gold dient als Absicherung.', 'O ouro serve de proteção.', 'Finanças'],
    ['die Bewertung', 'avaliação de valor', 'substantivo', 'Die Bewertung wirkt überhöht.', 'A avaliação parece inflada.', 'Finanças'],
    ['die Abschreibung', 'amortização', 'substantivo', 'Die Abschreibung verteilt die Kosten.', 'A amortização dilui os custos.', 'Finanças'],
    ['die Sicherheit', 'garantia real', 'substantivo', 'Das Haus diente als Sicherheit.', 'A casa serviu de garantia.', 'Finanças'],
    ['die Rendite', 'rendimento', 'substantivo', 'Die Rendite fiel unter die Inflation.', 'O rendimento ficou abaixo da inflação.', 'Finanças'],
    ['die Zahlungsfähigkeit', 'solvência', 'substantivo', 'Zahlungsfähigkeit ist nicht Liquidität.', 'Solvência não é liquidez.', 'Finanças'],
    ['das Drehmoment', 'torque', 'substantivo', 'Prüfe das Drehmoment der Schrauben.', 'Confira o torque dos parafusos.', 'Engenharia'],
    ['die Legierung', 'liga metálica', 'substantivo', 'Die Legierung widersteht Korrosion.', 'A liga resiste à corrosão.', 'Engenharia'],
    ['der Stromkreis', 'circuito elétrico', 'substantivo', 'Der Stromkreis überhitzte.', 'O circuito superaqueceu.', 'Engenharia'],
    ['die Fertigungstoleranz', 'tolerância de fabricação', 'substantivo', 'Die Fertigungstoleranz beträgt einen Millimeter.', 'A tolerância é de um milímetro.', 'Engenharia'],
    ['die Kalibrierung', 'calibração', 'substantivo', 'Die Kalibrierung ist verrutscht.', 'A calibração se desviou.', 'Engenharia'],
    ['die Reibung', 'atrito', 'substantivo', 'Die Reibung nutzt das Teil ab.', 'O atrito desgasta a peça.', 'Engenharia'],
    ['thermisch', 'térmico', 'adjetivo', 'Thermische Ausdehnung hat es gerissen.', 'A dilatação térmica trincou a peça.', 'Engenharia'],
    ['hydraulisch', 'hidráulico', 'adjetivo', 'Das hydraulische System versagte.', 'O sistema hidráulico falhou.', 'Engenharia'],
    ['das Schweißen', 'solda', 'substantivo', 'Das Schweißen hat gehalten.', 'A solda aguentou.', 'Engenharia'],
    ['die Traglast', 'carga estrutural', 'substantivo', 'Der Träger nimmt die Traglast auf.', 'A viga recebe a carga.', 'Engenharia'],
  ],
  C2: [
    ['die Hegemonie', 'hegemonia', 'substantivo', 'Ihre Hegemonie blieb unangefochten.', 'A hegemonia deles ficou incontestada.', 'Filosofia política'],
    ['die Legitimität', 'legitimidade', 'substantivo', 'Die Wahl stellte die Legitimität wieder her.', 'A eleição restaurou a legitimidade.', 'Filosofia política'],
    ['der Populismus', 'populismo', 'substantivo', 'Populismus lebt vom Groll.', 'O populismo vive do ressentimento.', 'Filosofia política'],
    ['die Meritokratie', 'meritocracia', 'substantivo', 'Meritokratie setzt einen fairen Start voraus.', 'A meritocracia pressupõe largada justa.', 'Filosofia política'],
    ['egalitär', 'igualitário', 'adjetivo', 'Es ist ein egalitärer Vorschlag.', 'É uma proposta igualitária.', 'Filosofia política'],
    ['autoritär', 'autoritário', 'adjetivo', 'Die Wende war autoritär.', 'A guinada foi autoritária.', 'Filosofia política'],
    ['der Pluralismus', 'pluralismo', 'substantivo', 'Pluralismus braucht echten Widerspruch.', 'O pluralismo precisa de dissenso real.', 'Filosofia política'],
    ['die Subsidiarität', 'subsidiariedade', 'substantivo', 'Subsidiarität verlagert Entscheidungen nach unten.', 'A subsidiariedade desloca decisões para baixo.', 'Filosofia política'],
    ['die Technokratie', 'tecnocracia', 'substantivo', 'Technokratie drängt den Wähler an den Rand.', 'A tecnocracia empurra o eleitor para a margem.', 'Filosofia política'],
    ['die Staatskunst', 'arte de governar', 'substantivo', 'Das war gekonnte Staatskunst.', 'Aquilo foi arte de governar com maestria.', 'Filosofia política'],
    ['die Kadenz', 'cadência', 'substantivo', 'Die Kadenz löst die Phrase auf.', 'A cadência resolve a frase.', 'Música e som'],
    ['die Klangfarbe', 'timbre', 'substantivo', 'Die Klangfarbe ist unverwechselbar.', 'O timbre é inconfundível.', 'Música e som'],
    ['die Dissonanz', 'dissonância', 'substantivo', 'Die Dissonanz ist gewollt.', 'A dissonância é proposital.', 'Música e som'],
    ['das Crescendo', 'crescendo', 'substantivo', 'Das Crescendo baut sich langsam auf.', 'O crescendo se constrói devagar.', 'Música e som'],
    ['der Kontrapunkt', 'contraponto', 'substantivo', 'Der Kontrapunkt ist verschachtelt.', 'O contraponto é intrincado.', 'Música e som'],
    ['die Resonanz', 'ressonância', 'substantivo', 'Der Saal hat warme Resonanz.', 'A sala tem ressonância quente.', 'Música e som'],
    ['das Staccato', 'staccato', 'substantivo', 'Die Staccato-Stelle ist heikel.', 'O trecho em staccato é delicado.', 'Música e som'],
    ['der Refrain', 'refrão', 'substantivo', 'Der Refrain kehrt viermal wieder.', 'O refrão volta quatro vezes.', 'Música e som'],
    ['das Tempo', 'andamento', 'substantivo', 'Hier schleppt das Tempo.', 'Aqui o andamento se arrasta.', 'Música e som'],
    ['die Harmonie', 'harmonia', 'substantivo', 'Die Harmonie wechselt abrupt.', 'A harmonia muda abruptamente.', 'Música e som'],
  ],
};
