/** Inglês — terceiro lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const EN_THEMATIC3: LatinByLevel = {
  A1: [
    ['son', 'filho', 'substantivo', 'My son is five.', 'Meu filho tem cinco anos.', 'Família e pessoas'],
    ['daughter', 'filha', 'substantivo', 'Her daughter studies here.', 'A filha dela estuda aqui.', 'Família e pessoas'],
    ['grandmother', 'avó', 'substantivo', 'My grandmother cooks well.', 'Minha avó cozinha bem.', 'Família e pessoas'],
    ['grandfather', 'avô', 'substantivo', 'My grandfather tells stories.', 'Meu avô conta histórias.', 'Família e pessoas'],
    ['uncle', 'tio', 'substantivo', 'My uncle lives far away.', 'Meu tio mora longe.', 'Família e pessoas'],
    ['aunt', 'tia', 'substantivo', 'My aunt is a nurse.', 'Minha tia é enfermeira.', 'Família e pessoas'],
    ['cousin', 'primo', 'substantivo', 'My cousin is my age.', 'Meu primo tem a minha idade.', 'Família e pessoas'],
    ['wife', 'esposa', 'substantivo', 'His wife works downtown.', 'A esposa dele trabalha no centro.', 'Família e pessoas'],
    ['husband', 'marido', 'substantivo', 'Her husband is a teacher.', 'O marido dela é professor.', 'Família e pessoas'],
    ['friend', 'amigo', 'substantivo', 'She is my best friend.', 'Ela é minha melhor amiga.', 'Família e pessoas'],
    ['room', 'quarto / cômodo', 'substantivo', 'This room is quiet.', 'Este quarto é silencioso.', 'Casa e cômodos'],
    ['living room', 'sala de estar', 'substantivo', 'We watch TV in the living room.', 'Assistimos TV na sala de estar.', 'Casa e cômodos'],
    ['bedroom', 'dormitório', 'substantivo', 'The bedroom is upstairs.', 'O dormitório fica lá em cima.', 'Casa e cômodos'],
    ['garden', 'jardim', 'substantivo', 'The garden needs water.', 'O jardim precisa de água.', 'Casa e cômodos'],
    ['wall', 'parede', 'substantivo', 'The wall is dirty.', 'A parede está suja.', 'Casa e cômodos'],
    ['floor', 'chão / piso', 'substantivo', 'The floor is wet.', 'O chão está molhado.', 'Casa e cômodos'],
    ['stairs', 'escada', 'substantivo', 'The stairs are steep.', 'A escada é íngreme.', 'Casa e cômodos'],
    ['key', 'chave', 'substantivo', 'I lost my key.', 'Perdi minha chave.', 'Casa e cômodos'],
    ['lamp', 'luminária', 'substantivo', 'Turn on the lamp.', 'Acenda a luminária.', 'Casa e cômodos'],
    ['garage', 'garagem', 'substantivo', 'The car is in the garage.', 'O carro está na garagem.', 'Casa e cômodos'],
  ],
  A2: [
    ['belt', 'cinto', 'substantivo', 'This belt is too long.', 'Este cinto é comprido demais.', 'Vestuário e aparência'],
    ['scarf', 'cachecol', 'substantivo', 'Wear a scarf, it is cold.', 'Use um cachecol, está frio.', 'Vestuário e aparência'],
    ['glove', 'luva', 'substantivo', 'I lost one glove.', 'Perdi uma luva.', 'Vestuário e aparência'],
    ['boot', 'bota', 'substantivo', 'These boots are heavy.', 'Estas botas são pesadas.', 'Vestuário e aparência'],
    ['sleeve', 'manga (de roupa)', 'substantivo', 'The sleeve is torn.', 'A manga está rasgada.', 'Vestuário e aparência'],
    ['pocket', 'bolso', 'substantivo', 'It is in my pocket.', 'Está no meu bolso.', 'Vestuário e aparência'],
    ['button', 'botão', 'substantivo', 'A button fell off.', 'Caiu um botão.', 'Vestuário e aparência'],
    ['zipper', 'zíper', 'substantivo', 'The zipper is broken.', 'O zíper está quebrado.', 'Vestuário e aparência'],
    ['beard', 'barba', 'substantivo', 'He grew a beard.', 'Ele deixou a barba crescer.', 'Vestuário e aparência'],
    ['makeup', 'maquiagem', 'substantivo', 'She wears little makeup.', 'Ela usa pouca maquiagem.', 'Vestuário e aparência'],
    ['birthday', 'aniversário', 'substantivo', 'Today is my birthday.', 'Hoje é meu aniversário.', 'Datas e festas'],
    ['holiday', 'feriado', 'substantivo', 'Monday is a holiday.', 'Segunda é feriado.', 'Datas e festas'],
    ['wedding', 'casamento', 'substantivo', 'The wedding is in June.', 'O casamento é em junho.', 'Datas e festas'],
    ['gift', 'presente', 'substantivo', 'Thank you for the gift.', 'Obrigado pelo presente.', 'Datas e festas'],
    ['party', 'festa', 'substantivo', 'The party starts at nine.', 'A festa começa às nove.', 'Datas e festas'],
    ['candle', 'vela', 'substantivo', 'Light the candles.', 'Acenda as velas.', 'Datas e festas'],
    ['invitation', 'convite', 'substantivo', 'I got the invitation.', 'Recebi o convite.', 'Datas e festas'],
    ['anniversary', 'data comemorativa', 'substantivo', 'It is our tenth anniversary.', 'É nosso décimo aniversário de casamento.', 'Datas e festas'],
    ['celebrate', 'comemorar', 'verbo', 'We celebrate on Saturday.', 'Nós comemoramos no sábado.', 'Datas e festas'],
    ['guest', 'convidado', 'substantivo', 'Twenty guests are coming.', 'Vinte convidados vêm.', 'Datas e festas'],
  ],
  B1: [
    ['degree', 'diploma / graduação', 'substantivo', 'She has a law degree.', 'Ela tem diploma de direito.', 'Educação superior'],
    ['thesis', 'tese', 'substantivo', 'He is writing his thesis.', 'Ele está escrevendo a tese.', 'Educação superior'],
    ['lecture', 'palestra / aula expositiva', 'substantivo', 'The lecture lasted two hours.', 'A aula expositiva durou duas horas.', 'Educação superior'],
    ['professor', 'professor universitário', 'substantivo', 'The professor published a book.', 'O professor publicou um livro.', 'Educação superior'],
    ['campus', 'campus', 'substantivo', 'The campus is huge.', 'O campus é enorme.', 'Educação superior'],
    ['semester', 'semestre', 'substantivo', 'The semester ends in July.', 'O semestre acaba em julho.', 'Educação superior'],
    ['enrol', 'matricular-se', 'verbo', 'I will enrol next month.', 'Vou me matricular mês que vem.', 'Educação superior'],
    ['dormitory', 'alojamento estudantil', 'substantivo', 'She lives in a dormitory.', 'Ela mora num alojamento estudantil.', 'Educação superior'],
    ['graduate', 'formar-se', 'verbo', 'They graduate in December.', 'Eles se formam em dezembro.', 'Educação superior'],
    ['seminar', 'seminário', 'substantivo', 'The seminar was small.', 'O seminário era pequeno.', 'Educação superior'],
    ['hostel', 'albergue', 'substantivo', 'We stayed in a hostel.', 'Ficamos num albergue.', 'Viagem e hospedagem'],
    ['booking', 'reserva (de hospedagem)', 'substantivo', 'My booking was cancelled.', 'Minha reserva foi cancelada.', 'Viagem e hospedagem'],
    ['check-in', 'check-in', 'substantivo', 'Check-in starts at two.', 'O check-in começa às duas.', 'Viagem e hospedagem'],
    ['receptionist', 'recepcionista', 'substantivo', 'Ask the receptionist.', 'Pergunte ao recepcionista.', 'Viagem e hospedagem'],
    ['lobby', 'saguão', 'substantivo', 'Wait for me in the lobby.', 'Me espere no saguão.', 'Viagem e hospedagem'],
    ['landmark', 'ponto turístico', 'substantivo', 'That tower is a landmark.', 'Aquela torre é um ponto turístico.', 'Viagem e hospedagem'],
    ['souvenir', 'lembrança de viagem', 'substantivo', 'I bought a souvenir.', 'Comprei uma lembrança de viagem.', 'Viagem e hospedagem'],
    ['guidebook', 'guia de viagem', 'substantivo', 'The guidebook is outdated.', 'O guia de viagem está desatualizado.', 'Viagem e hospedagem'],
    ['visa', 'visto', 'substantivo', 'I need a visa.', 'Preciso de visto.', 'Viagem e hospedagem'],
    ['tourist', 'turista', 'substantivo', 'The city is full of tourists.', 'A cidade está cheia de turistas.', 'Viagem e hospedagem'],
  ],
  B2: [
    ['algorithm', 'algoritmo', 'substantivo', 'The algorithm ranks the results.', 'O algoritmo ordena os resultados.', 'Tecnologia avançada'],
    ['encryption', 'criptografia', 'substantivo', 'Encryption protects the data.', 'A criptografia protege os dados.', 'Tecnologia avançada'],
    ['bandwidth', 'largura de banda', 'substantivo', 'We ran out of bandwidth.', 'Ficamos sem largura de banda.', 'Tecnologia avançada'],
    ['server', 'servidor', 'substantivo', 'The server went down.', 'O servidor caiu.', 'Tecnologia avançada'],
    ['database', 'banco de dados', 'substantivo', 'Back up the database.', 'Faça backup do banco de dados.', 'Tecnologia avançada'],
    ['interface', 'interface', 'substantivo', 'The interface is confusing.', 'A interface é confusa.', 'Tecnologia avançada'],
    ['automation', 'automação', 'substantivo', 'Automation cut the costs.', 'A automação cortou os custos.', 'Tecnologia avançada'],
    ['firewall', 'firewall', 'substantivo', 'The firewall blocked it.', 'O firewall bloqueou.', 'Tecnologia avançada'],
    ['prototype', 'protótipo', 'substantivo', 'We built a prototype.', 'Construímos um protótipo.', 'Tecnologia avançada'],
    ['latency', 'latência', 'substantivo', 'Latency ruins the experience.', 'A latência estraga a experiência.', 'Tecnologia avançada'],
    ['advertising', 'publicidade', 'substantivo', 'Advertising drove the sales.', 'A publicidade impulsionou as vendas.', 'Consumo e marketing'],
    ['consumer', 'consumidor', 'substantivo', 'The consumer decides.', 'O consumidor decide.', 'Consumo e marketing'],
    ['retail', 'varejo', 'substantivo', 'Retail margins are thin.', 'As margens do varejo são apertadas.', 'Consumo e marketing'],
    ['wholesale', 'atacado', 'substantivo', 'They buy at wholesale.', 'Eles compram no atacado.', 'Consumo e marketing'],
    ['packaging', 'embalagem', 'substantivo', 'The packaging is wasteful.', 'A embalagem é um desperdício.', 'Consumo e marketing'],
    ['logo', 'logotipo', 'substantivo', 'The logo was redesigned.', 'O logotipo foi redesenhado.', 'Consumo e marketing'],
    ['slogan', 'slogan', 'substantivo', 'The slogan stuck.', 'O slogan pegou.', 'Consumo e marketing'],
    ['target audience', 'público-alvo', 'substantivo', 'Define the target audience first.', 'Defina o público-alvo primeiro.', 'Consumo e marketing'],
    ['endorsement', 'aval / recomendação paga', 'substantivo', 'The endorsement cost a fortune.', 'O aval custou uma fortuna.', 'Consumo e marketing'],
    ['markup', 'margem de lucro', 'substantivo', 'The markup is too high.', 'A margem de lucro é alta demais.', 'Consumo e marketing'],
  ],
  C1: [
    ['asset', 'ativo (patrimônio)', 'substantivo', 'The asset lost value.', 'O ativo perdeu valor.', 'Finanças'],
    ['equity', 'participação acionária', 'substantivo', 'She holds equity in the firm.', 'Ela tem participação acionária na empresa.', 'Finanças'],
    ['dividend', 'dividendo', 'substantivo', 'They cut the dividend.', 'Cortaram o dividendo.', 'Finanças'],
    ['portfolio', 'carteira de investimentos', 'substantivo', 'Diversify the portfolio.', 'Diversifique a carteira.', 'Finanças'],
    ['hedge', 'proteção contra risco', 'substantivo', 'Gold works as a hedge.', 'O ouro serve de proteção contra risco.', 'Finanças'],
    ['valuation', 'avaliação de valor', 'substantivo', 'The valuation seems inflated.', 'A avaliação parece inflada.', 'Finanças'],
    ['amortization', 'amortização', 'substantivo', 'Amortization spreads the cost.', 'A amortização dilui o custo.', 'Finanças'],
    ['collateral', 'garantia real', 'substantivo', 'The house served as collateral.', 'A casa serviu de garantia.', 'Finanças'],
    ['yield', 'rendimento', 'substantivo', 'The yield fell below inflation.', 'O rendimento ficou abaixo da inflação.', 'Finanças'],
    ['solvency', 'solvência', 'substantivo', 'Solvency is not liquidity.', 'Solvência não é liquidez.', 'Finanças'],
    ['torque', 'torque', 'substantivo', 'Check the torque on the bolts.', 'Confira o torque dos parafusos.', 'Engenharia'],
    ['alloy', 'liga metálica', 'substantivo', 'The alloy resists corrosion.', 'A liga resiste à corrosão.', 'Engenharia'],
    ['circuit', 'circuito', 'substantivo', 'The circuit overheated.', 'O circuito superaqueceu.', 'Engenharia'],
    ['tolerance', 'tolerância dimensional', 'substantivo', 'The tolerance is one millimetre.', 'A tolerância é de um milímetro.', 'Engenharia'],
    ['calibration', 'calibração', 'substantivo', 'The calibration drifted.', 'A calibração se desviou.', 'Engenharia'],
    ['friction', 'atrito', 'substantivo', 'Friction wears the part down.', 'O atrito desgasta a peça.', 'Engenharia'],
    ['thermal', 'térmico', 'adjetivo', 'Thermal expansion cracked it.', 'A dilatação térmica trincou a peça.', 'Engenharia'],
    ['hydraulic', 'hidráulico', 'adjetivo', 'The hydraulic system failed.', 'O sistema hidráulico falhou.', 'Engenharia'],
    ['welding', 'solda', 'substantivo', 'The welding held.', 'A solda aguentou.', 'Engenharia'],
    ['load', 'carga (estrutural)', 'substantivo', 'The beam takes the load.', 'A viga recebe a carga.', 'Engenharia'],
  ],
  C2: [
    ['hegemony', 'hegemonia', 'substantivo', 'Their hegemony went unchallenged.', 'A hegemonia deles não foi contestada.', 'Filosofia política'],
    ['legitimacy', 'legitimidade', 'substantivo', 'The vote restored legitimacy.', 'A votação restaurou a legitimidade.', 'Filosofia política'],
    ['populism', 'populismo', 'substantivo', 'Populism thrives on grievance.', 'O populismo se alimenta do ressentimento.', 'Filosofia política'],
    ['meritocracy', 'meritocracia', 'substantivo', 'Meritocracy assumes a fair start.', 'A meritocracia pressupõe largada justa.', 'Filosofia política'],
    ['egalitarian', 'igualitário', 'adjetivo', 'It is an egalitarian proposal.', 'É uma proposta igualitária.', 'Filosofia política'],
    ['authoritarian', 'autoritário', 'adjetivo', 'The turn was authoritarian.', 'A guinada foi autoritária.', 'Filosofia política'],
    ['pluralism', 'pluralismo', 'substantivo', 'Pluralism needs real dissent.', 'O pluralismo exige dissenso real.', 'Filosofia política'],
    ['subsidiarity', 'subsidiariedade', 'substantivo', 'Subsidiarity pushes decisions downward.', 'A subsidiariedade empurra decisões para baixo.', 'Filosofia política'],
    ['technocracy', 'tecnocracia', 'substantivo', 'Technocracy sidelines the voter.', 'A tecnocracia marginaliza o eleitor.', 'Filosofia política'],
    ['statecraft', 'arte de governar', 'substantivo', 'That was skilled statecraft.', 'Aquilo foi arte de governar com habilidade.', 'Filosofia política'],
    ['cadence', 'cadência', 'substantivo', 'The cadence resolves the phrase.', 'A cadência resolve a frase.', 'Música e som'],
    ['timbre', 'timbre', 'substantivo', 'The timbre is unmistakable.', 'O timbre é inconfundível.', 'Música e som'],
    ['dissonance', 'dissonância', 'substantivo', 'The dissonance is deliberate.', 'A dissonância é proposital.', 'Música e som'],
    ['crescendo', 'crescendo', 'substantivo', 'The crescendo builds slowly.', 'O crescendo se constrói devagar.', 'Música e som'],
    ['counterpoint', 'contraponto', 'substantivo', 'The counterpoint is intricate.', 'O contraponto é intrincado.', 'Música e som'],
    ['resonance', 'ressonância', 'substantivo', 'The hall has warm resonance.', 'A sala tem ressonância quente.', 'Música e som'],
    ['staccato', 'staccato', 'adjetivo', 'The staccato passage is tricky.', 'A passagem em staccato é difícil.', 'Música e som'],
    ['refrain', 'refrão', 'substantivo', 'The refrain repeats four times.', 'O refrão repete quatro vezes.', 'Música e som'],
    ['tempo', 'andamento', 'substantivo', 'The tempo drags here.', 'O andamento se arrasta aqui.', 'Música e som'],
    ['harmony', 'harmonia', 'substantivo', 'The harmony shifts abruptly.', 'A harmonia muda de repente.', 'Música e som'],
  ],
};
