/** Espanhol — terceiro lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const ES_THEMATIC3: LatinByLevel = {
  A1: [
    ['el hijo', 'filho', 'substantivo', 'Mi hijo tiene cinco años.', 'Meu filho tem cinco anos.', 'Família e pessoas'],
    ['la hija', 'filha', 'substantivo', 'Su hija estudia aquí.', 'A filha dela estuda aqui.', 'Família e pessoas'],
    ['la abuela', 'avó', 'substantivo', 'Mi abuela cocina bien.', 'Minha avó cozinha bem.', 'Família e pessoas'],
    ['el abuelo', 'avô', 'substantivo', 'Mi abuelo cuenta historias.', 'Meu avô conta histórias.', 'Família e pessoas'],
    ['el tío', 'tio', 'substantivo', 'Mi tío vive lejos.', 'Meu tio mora longe.', 'Família e pessoas'],
    ['la tía', 'tia', 'substantivo', 'Mi tía es enfermera.', 'Minha tia é enfermeira.', 'Família e pessoas'],
    ['el primo', 'primo', 'substantivo', 'Mi primo tiene mi edad.', 'Meu primo tem a minha idade.', 'Família e pessoas'],
    ['la esposa', 'esposa', 'substantivo', 'Su esposa trabaja en el centro.', 'A esposa dele trabalha no centro.', 'Família e pessoas'],
    ['el marido', 'marido', 'substantivo', 'Su marido es profesor.', 'O marido dela é professor.', 'Família e pessoas'],
    ['el amigo', 'amigo', 'substantivo', 'Es mi mejor amigo.', 'Ele é meu melhor amigo.', 'Família e pessoas'],
    ['la habitación', 'quarto / cômodo', 'substantivo', 'Esta habitación es tranquila.', 'Este quarto é tranquilo.', 'Casa e cômodos'],
    ['el salón', 'sala de estar', 'substantivo', 'Vemos la tele en el salón.', 'Assistimos TV na sala de estar.', 'Casa e cômodos'],
    ['el dormitorio', 'dormitório', 'substantivo', 'El dormitorio está arriba.', 'O dormitório fica lá em cima.', 'Casa e cômodos'],
    ['el jardín', 'jardim', 'substantivo', 'El jardín necesita agua.', 'O jardim precisa de água.', 'Casa e cômodos'],
    ['la pared', 'parede', 'substantivo', 'La pared está sucia.', 'A parede está suja.', 'Casa e cômodos'],
    ['el suelo', 'chão', 'substantivo', 'El suelo está mojado.', 'O chão está molhado.', 'Casa e cômodos'],
    ['la escalera', 'escada', 'substantivo', 'La escalera es empinada.', 'A escada é íngreme.', 'Casa e cômodos'],
    ['la llave', 'chave', 'substantivo', 'Perdí la llave.', 'Perdi a chave.', 'Casa e cômodos'],
    ['la lámpara', 'luminária', 'substantivo', 'Enciende la lámpara.', 'Acenda a luminária.', 'Casa e cômodos'],
    ['el garaje', 'garagem', 'substantivo', 'El coche está en el garaje.', 'O carro está na garagem.', 'Casa e cômodos'],
  ],
  A2: [
    ['el cinturón', 'cinto', 'substantivo', 'Este cinturón es muy largo.', 'Este cinto é comprido demais.', 'Vestuário e aparência'],
    ['la bufanda', 'cachecol', 'substantivo', 'Ponte la bufanda, hace frío.', 'Use o cachecol, está frio.', 'Vestuário e aparência'],
    ['el guante', 'luva', 'substantivo', 'Perdí un guante.', 'Perdi uma luva.', 'Vestuário e aparência'],
    ['la bota', 'bota', 'substantivo', 'Estas botas pesan mucho.', 'Estas botas são muito pesadas.', 'Vestuário e aparência'],
    ['la manga', 'manga (de roupa)', 'substantivo', 'La manga está rota.', 'A manga está rasgada.', 'Vestuário e aparência'],
    ['el bolsillo', 'bolso', 'substantivo', 'Está en mi bolsillo.', 'Está no meu bolso.', 'Vestuário e aparência'],
    ['el botón', 'botão', 'substantivo', 'Se cayó un botón.', 'Caiu um botão.', 'Vestuário e aparência'],
    ['la cremallera', 'zíper', 'substantivo', 'La cremallera está rota.', 'O zíper está quebrado.', 'Vestuário e aparência'],
    ['la barba', 'barba', 'substantivo', 'Se dejó la barba.', 'Ele deixou a barba crescer.', 'Vestuário e aparência'],
    ['el maquillaje', 'maquiagem', 'substantivo', 'Usa poco maquillaje.', 'Ela usa pouca maquiagem.', 'Vestuário e aparência'],
    ['el cumpleaños', 'aniversário', 'substantivo', 'Hoy es mi cumpleaños.', 'Hoje é meu aniversário.', 'Datas e festas'],
    ['el día festivo', 'feriado', 'substantivo', 'El lunes es día festivo.', 'Segunda é feriado.', 'Datas e festas'],
    ['la boda', 'casamento', 'substantivo', 'La boda es en junio.', 'O casamento é em junho.', 'Datas e festas'],
    ['el regalo', 'presente', 'substantivo', 'Gracias por el regalo.', 'Obrigado pelo presente.', 'Datas e festas'],
    ['la fiesta', 'festa', 'substantivo', 'La fiesta empieza a las nueve.', 'A festa começa às nove.', 'Datas e festas'],
    ['la vela', 'vela', 'substantivo', 'Enciende las velas.', 'Acenda as velas.', 'Datas e festas'],
    ['la invitación', 'convite', 'substantivo', 'Recibí la invitación.', 'Recebi o convite.', 'Datas e festas'],
    ['el aniversario', 'data comemorativa', 'substantivo', 'Es nuestro décimo aniversario.', 'É nosso décimo aniversário.', 'Datas e festas'],
    ['celebrar', 'comemorar', 'verbo', 'Celebramos el sábado.', 'Comemoramos no sábado.', 'Datas e festas'],
    ['el invitado', 'convidado', 'substantivo', 'Vienen veinte invitados.', 'Vêm vinte convidados.', 'Datas e festas'],
  ],
  B1: [
    ['la carrera', 'curso superior', 'substantivo', 'Terminó la carrera de derecho.', 'Ela terminou o curso de direito.', 'Educação superior'],
    ['la tesis', 'tese', 'substantivo', 'Está escribiendo la tesis.', 'Ele está escrevendo a tese.', 'Educação superior'],
    ['la conferencia', 'palestra', 'substantivo', 'La conferencia duró dos horas.', 'A palestra durou duas horas.', 'Educação superior'],
    ['el catedrático', 'professor titular', 'substantivo', 'El catedrático publicó un libro.', 'O professor titular publicou um livro.', 'Educação superior'],
    ['el campus', 'campus', 'substantivo', 'El campus es enorme.', 'O campus é enorme.', 'Educação superior'],
    ['el semestre', 'semestre', 'substantivo', 'El semestre acaba en julio.', 'O semestre acaba em julho.', 'Educação superior'],
    ['matricularse', 'matricular-se', 'verbo', 'Me matriculo el mes que viene.', 'Vou me matricular mês que vem.', 'Educação superior'],
    ['la residencia estudiantil', 'alojamento estudantil', 'substantivo', 'Vive en una residencia estudiantil.', 'Ela mora num alojamento estudantil.', 'Educação superior'],
    ['graduarse', 'formar-se', 'verbo', 'Se gradúan en diciembre.', 'Eles se formam em dezembro.', 'Educação superior'],
    ['el seminario', 'seminário', 'substantivo', 'El seminario era pequeño.', 'O seminário era pequeno.', 'Educação superior'],
    ['el albergue', 'albergue', 'substantivo', 'Nos quedamos en un albergue.', 'Ficamos num albergue.', 'Viagem e hospedagem'],
    ['la reserva de hotel', 'reserva de hotel', 'substantivo', 'Cancelaron mi reserva de hotel.', 'Cancelaram minha reserva de hotel.', 'Viagem e hospedagem'],
    ['la entrada al hotel', 'check-in', 'substantivo', 'La entrada al hotel es a las dos.', 'O check-in é às duas.', 'Viagem e hospedagem'],
    ['el recepcionista', 'recepcionista', 'substantivo', 'Pregunta al recepcionista.', 'Pergunte ao recepcionista.', 'Viagem e hospedagem'],
    ['el vestíbulo', 'saguão', 'substantivo', 'Espérame en el vestíbulo.', 'Me espere no saguão.', 'Viagem e hospedagem'],
    ['el punto de referencia', 'ponto de referência', 'substantivo', 'Esa torre es un punto de referencia.', 'Aquela torre é um ponto de referência.', 'Viagem e hospedagem'],
    ['el recuerdo de viaje', 'lembrança de viagem', 'substantivo', 'Compré un recuerdo de viaje.', 'Comprei uma lembrança de viagem.', 'Viagem e hospedagem'],
    ['la guía turística', 'guia de viagem', 'substantivo', 'La guía turística está desfasada.', 'O guia de viagem está desatualizado.', 'Viagem e hospedagem'],
    ['el visado', 'visto', 'substantivo', 'Necesito un visado.', 'Preciso de visto.', 'Viagem e hospedagem'],
    ['el turista', 'turista', 'substantivo', 'La ciudad está llena de turistas.', 'A cidade está cheia de turistas.', 'Viagem e hospedagem'],
  ],
  B2: [
    ['el algoritmo', 'algoritmo', 'substantivo', 'El algoritmo ordena los resultados.', 'O algoritmo ordena os resultados.', 'Tecnologia avançada'],
    ['el cifrado', 'criptografia', 'substantivo', 'El cifrado protege los datos.', 'A criptografia protege os dados.', 'Tecnologia avançada'],
    ['el ancho de banda', 'largura de banda', 'substantivo', 'Nos quedamos sin ancho de banda.', 'Ficamos sem largura de banda.', 'Tecnologia avançada'],
    ['el servidor', 'servidor', 'substantivo', 'El servidor se cayó.', 'O servidor caiu.', 'Tecnologia avançada'],
    ['la base de datos', 'banco de dados', 'substantivo', 'Haz copia de la base de datos.', 'Faça backup do banco de dados.', 'Tecnologia avançada'],
    ['la interfaz', 'interface', 'substantivo', 'La interfaz es confusa.', 'A interface é confusa.', 'Tecnologia avançada'],
    ['la automatización', 'automação', 'substantivo', 'La automatización redujo costes.', 'A automação reduziu custos.', 'Tecnologia avançada'],
    ['el cortafuegos', 'firewall', 'substantivo', 'El cortafuegos lo bloqueó.', 'O firewall bloqueou.', 'Tecnologia avançada'],
    ['el prototipo', 'protótipo', 'substantivo', 'Construimos un prototipo.', 'Construímos um protótipo.', 'Tecnologia avançada'],
    ['la latencia', 'latência', 'substantivo', 'La latencia arruina la experiencia.', 'A latência estraga a experiência.', 'Tecnologia avançada'],
    ['la publicidad', 'publicidade', 'substantivo', 'La publicidad impulsó las ventas.', 'A publicidade impulsionou as vendas.', 'Consumo e marketing'],
    ['el consumidor', 'consumidor', 'substantivo', 'El consumidor decide.', 'O consumidor decide.', 'Consumo e marketing'],
    ['el comercio minorista', 'varejo', 'substantivo', 'Los márgenes del comercio minorista son estrechos.', 'As margens do varejo são apertadas.', 'Consumo e marketing'],
    ['el comercio mayorista', 'atacado', 'substantivo', 'Compran en el comercio mayorista.', 'Eles compram no atacado.', 'Consumo e marketing'],
    ['el envase', 'embalagem', 'substantivo', 'El envase es un desperdicio.', 'A embalagem é um desperdício.', 'Consumo e marketing'],
    ['el logotipo', 'logotipo', 'substantivo', 'Rediseñaron el logotipo.', 'Redesenharam o logotipo.', 'Consumo e marketing'],
    ['el eslogan', 'slogan', 'substantivo', 'El eslogan caló.', 'O slogan pegou.', 'Consumo e marketing'],
    ['el público objetivo', 'público-alvo', 'substantivo', 'Define primero el público objetivo.', 'Defina o público-alvo primeiro.', 'Consumo e marketing'],
    ['el respaldo publicitario', 'aval publicitário', 'substantivo', 'El respaldo publicitario costó una fortuna.', 'O aval publicitário custou uma fortuna.', 'Consumo e marketing'],
    ['el margen comercial', 'margem de lucro', 'substantivo', 'El margen comercial es alto.', 'A margem de lucro é alta.', 'Consumo e marketing'],
  ],
  C1: [
    ['el activo', 'ativo (patrimônio)', 'substantivo', 'El activo perdió valor.', 'O ativo perdeu valor.', 'Finanças'],
    ['la participación accionarial', 'participação acionária', 'substantivo', 'Tiene participación accionarial en la empresa.', 'Ela tem participação acionária na empresa.', 'Finanças'],
    ['el dividendo', 'dividendo', 'substantivo', 'Recortaron el dividendo.', 'Cortaram o dividendo.', 'Finanças'],
    ['la cartera de inversión', 'carteira de investimentos', 'substantivo', 'Diversifica la cartera de inversión.', 'Diversifique a carteira.', 'Finanças'],
    ['la cobertura de riesgo', 'proteção contra risco', 'substantivo', 'El oro sirve de cobertura de riesgo.', 'O ouro serve de proteção contra risco.', 'Finanças'],
    ['la valoración', 'avaliação de valor', 'substantivo', 'La valoración parece inflada.', 'A avaliação parece inflada.', 'Finanças'],
    ['la amortización', 'amortização', 'substantivo', 'La amortización reparte el coste.', 'A amortização dilui o custo.', 'Finanças'],
    ['la garantía real', 'garantia real', 'substantivo', 'La casa sirvió de garantía real.', 'A casa serviu de garantia real.', 'Finanças'],
    ['el rendimiento financiero', 'rendimento financeiro', 'substantivo', 'El rendimiento financiero quedó bajo la inflación.', 'O rendimento ficou abaixo da inflação.', 'Finanças'],
    ['la solvencia', 'solvência', 'substantivo', 'La solvencia no es liquidez.', 'Solvência não é liquidez.', 'Finanças'],
    ['el par de apriete', 'torque', 'substantivo', 'Comprueba el par de apriete.', 'Confira o torque.', 'Engenharia'],
    ['la aleación', 'liga metálica', 'substantivo', 'La aleación resiste la corrosión.', 'A liga resiste à corrosão.', 'Engenharia'],
    ['el circuito', 'circuito', 'substantivo', 'El circuito se sobrecalentó.', 'O circuito superaqueceu.', 'Engenharia'],
    ['la tolerancia dimensional', 'tolerância dimensional', 'substantivo', 'La tolerancia dimensional es de un milímetro.', 'A tolerância dimensional é de um milímetro.', 'Engenharia'],
    ['la calibración', 'calibração', 'substantivo', 'La calibración se desvió.', 'A calibração se desviou.', 'Engenharia'],
    ['la fricción', 'atrito', 'substantivo', 'La fricción desgasta la pieza.', 'O atrito desgasta a peça.', 'Engenharia'],
    ['térmico', 'térmico', 'adjetivo', 'La dilatación térmica la agrietó.', 'A dilatação térmica trincou a peça.', 'Engenharia'],
    ['hidráulico', 'hidráulico', 'adjetivo', 'El sistema hidráulico falló.', 'O sistema hidráulico falhou.', 'Engenharia'],
    ['la soldadura', 'solda', 'substantivo', 'La soldadura aguantó.', 'A solda aguentou.', 'Engenharia'],
    ['la carga estructural', 'carga estrutural', 'substantivo', 'La viga soporta la carga estructural.', 'A viga suporta a carga estrutural.', 'Engenharia'],
  ],
  C2: [
    ['la hegemonía', 'hegemonia', 'substantivo', 'Su hegemonía no fue disputada.', 'A hegemonia deles não foi disputada.', 'Filosofia política'],
    ['la legitimidad', 'legitimidade', 'substantivo', 'La votación restauró la legitimidad.', 'A votação restaurou a legitimidade.', 'Filosofia política'],
    ['el populismo', 'populismo', 'substantivo', 'El populismo se nutre del agravio.', 'O populismo se nutre do agravo.', 'Filosofia política'],
    ['la meritocracia', 'meritocracia', 'substantivo', 'La meritocracia supone una salida justa.', 'A meritocracia pressupõe largada justa.', 'Filosofia política'],
    ['igualitario', 'igualitário', 'adjetivo', 'Es una propuesta igualitaria.', 'É uma proposta igualitária.', 'Filosofia política'],
    ['autoritario', 'autoritário', 'adjetivo', 'El giro fue autoritario.', 'A guinada foi autoritária.', 'Filosofia política'],
    ['el pluralismo', 'pluralismo', 'substantivo', 'El pluralismo exige disenso real.', 'O pluralismo exige dissenso real.', 'Filosofia política'],
    ['la subsidiariedad', 'subsidiariedade', 'substantivo', 'La subsidiariedad baja las decisiones.', 'A subsidiariedade desce as decisões.', 'Filosofia política'],
    ['la tecnocracia', 'tecnocracia', 'substantivo', 'La tecnocracia arrincona al votante.', 'A tecnocracia marginaliza o eleitor.', 'Filosofia política'],
    ['el arte de gobernar', 'arte de governar', 'substantivo', 'Aquello fue arte de gobernar.', 'Aquilo foi arte de governar.', 'Filosofia política'],
    ['la cadencia', 'cadência', 'substantivo', 'La cadencia resuelve la frase.', 'A cadência resolve a frase.', 'Música e som'],
    ['el timbre musical', 'timbre', 'substantivo', 'El timbre musical es inconfundible.', 'O timbre é inconfundível.', 'Música e som'],
    ['la disonancia', 'dissonância', 'substantivo', 'La disonancia es deliberada.', 'A dissonância é proposital.', 'Música e som'],
    ['el crescendo', 'crescendo', 'substantivo', 'El crescendo se construye despacio.', 'O crescendo se constrói devagar.', 'Música e som'],
    ['el contrapunto', 'contraponto', 'substantivo', 'El contrapunto es intrincado.', 'O contraponto é intrincado.', 'Música e som'],
    ['la resonancia', 'ressonância', 'substantivo', 'La sala tiene resonancia cálida.', 'A sala tem ressonância quente.', 'Música e som'],
    ['el staccato', 'staccato', 'substantivo', 'El pasaje en staccato es difícil.', 'A passagem em staccato é difícil.', 'Música e som'],
    ['el estribillo', 'refrão', 'substantivo', 'El estribillo se repite cuatro veces.', 'O refrão repete quatro vezes.', 'Música e som'],
    ['el tempo', 'andamento', 'substantivo', 'Aquí el tempo se arrastra.', 'Aqui o andamento se arrasta.', 'Música e som'],
    ['la armonía', 'harmonia', 'substantivo', 'La armonía cambia de golpe.', 'A harmonia muda de repente.', 'Música e som'],
  ],
};
