/** Francês — terceiro lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const FR_THEMATIC3: LatinByLevel = {
  A1: [
    ['le fils', 'filho', 'substantivo', 'Mon fils a cinq ans.', 'Meu filho tem cinco anos.', 'Família e pessoas'],
    ['la fille', 'filha', 'substantivo', 'Sa fille étudie ici.', 'A filha dela estuda aqui.', 'Família e pessoas'],
    ['la grand-mère', 'avó', 'substantivo', 'Ma grand-mère cuisine bien.', 'Minha avó cozinha bem.', 'Família e pessoas'],
    ['le grand-père', 'avô', 'substantivo', 'Mon grand-père raconte des histoires.', 'Meu avô conta histórias.', 'Família e pessoas'],
    ['l’oncle', 'tio', 'substantivo', 'Mon oncle habite loin.', 'Meu tio mora longe.', 'Família e pessoas'],
    ['la tante', 'tia', 'substantivo', 'Ma tante est infirmière.', 'Minha tia é enfermeira.', 'Família e pessoas'],
    ['le cousin', 'primo', 'substantivo', 'Mon cousin a mon âge.', 'Meu primo tem a minha idade.', 'Família e pessoas'],
    ['l’épouse', 'esposa', 'substantivo', 'Son épouse travaille en ville.', 'A esposa dele trabalha na cidade.', 'Família e pessoas'],
    ['le mari', 'marido', 'substantivo', 'Son mari est professeur.', 'O marido dela é professor.', 'Família e pessoas'],
    ['l’ami', 'amigo', 'substantivo', "C'est mon meilleur ami.", 'Ele é meu melhor amigo.', 'Família e pessoas'],
    ['la pièce', 'cômodo', 'substantivo', 'Cette pièce est calme.', 'Este cômodo é tranquilo.', 'Casa e cômodos'],
    ['le salon', 'sala de estar', 'substantivo', 'On regarde la télé au salon.', 'Assistimos TV na sala de estar.', 'Casa e cômodos'],
    ['la chambre', 'quarto', 'substantivo', 'La chambre est à l’étage.', 'O quarto fica no andar de cima.', 'Casa e cômodos'],
    ['le jardin', 'jardim', 'substantivo', 'Le jardin a besoin d’eau.', 'O jardim precisa de água.', 'Casa e cômodos'],
    ['le mur', 'parede', 'substantivo', 'Le mur est sale.', 'A parede está suja.', 'Casa e cômodos'],
    ['le sol', 'chão', 'substantivo', 'Le sol est mouillé.', 'O chão está molhado.', 'Casa e cômodos'],
    ['l’escalier', 'escada', 'substantivo', "L'escalier est raide.", 'A escada é íngreme.', 'Casa e cômodos'],
    ['la clé', 'chave', 'substantivo', "J'ai perdu ma clé.", 'Perdi minha chave.', 'Casa e cômodos'],
    ['la lampe', 'luminária', 'substantivo', 'Allume la lampe.', 'Acenda a luminária.', 'Casa e cômodos'],
    ['le garage', 'garagem', 'substantivo', 'La voiture est au garage.', 'O carro está na garagem.', 'Casa e cômodos'],
  ],
  A2: [
    ['la ceinture', 'cinto', 'substantivo', 'Cette ceinture est trop longue.', 'Este cinto é comprido demais.', 'Vestuário e aparência'],
    ['l’écharpe', 'cachecol', 'substantivo', 'Mets une écharpe, il fait froid.', 'Use um cachecol, está frio.', 'Vestuário e aparência'],
    ['le gant', 'luva', 'substantivo', "J'ai perdu un gant.", 'Perdi uma luva.', 'Vestuário e aparência'],
    ['la botte', 'bota', 'substantivo', 'Ces bottes sont lourdes.', 'Estas botas são pesadas.', 'Vestuário e aparência'],
    ['la manche', 'manga (de roupa)', 'substantivo', 'La manche est déchirée.', 'A manga está rasgada.', 'Vestuário e aparência'],
    ['la poche', 'bolso', 'substantivo', "C'est dans ma poche.", 'Está no meu bolso.', 'Vestuário e aparência'],
    ['le bouton', 'botão', 'substantivo', 'Un bouton est tombé.', 'Caiu um botão.', 'Vestuário e aparência'],
    ['la fermeture éclair', 'zíper', 'substantivo', 'La fermeture éclair est cassée.', 'O zíper está quebrado.', 'Vestuário e aparência'],
    ['la barbe', 'barba', 'substantivo', "Il s'est laissé pousser la barbe.", 'Ele deixou a barba crescer.', 'Vestuário e aparência'],
    ['le maquillage', 'maquiagem', 'substantivo', 'Elle porte peu de maquillage.', 'Ela usa pouca maquiagem.', 'Vestuário e aparência'],
    ['l’anniversaire', 'aniversário', 'substantivo', "Aujourd'hui, c'est mon anniversaire.", 'Hoje é meu aniversário.', 'Datas e festas'],
    ['le jour férié', 'feriado', 'substantivo', 'Lundi est un jour férié.', 'Segunda é feriado.', 'Datas e festas'],
    ['le mariage', 'casamento', 'substantivo', 'Le mariage est en juin.', 'O casamento é em junho.', 'Datas e festas'],
    ['le cadeau', 'presente', 'substantivo', 'Merci pour le cadeau.', 'Obrigado pelo presente.', 'Datas e festas'],
    ['la fête', 'festa', 'substantivo', 'La fête commence à neuf heures.', 'A festa começa às nove.', 'Datas e festas'],
    ['la bougie', 'vela', 'substantivo', 'Allume les bougies.', 'Acenda as velas.', 'Datas e festas'],
    ['l’invitation', 'convite', 'substantivo', "J'ai reçu l'invitation.", 'Recebi o convite.', 'Datas e festas'],
    ['les noces', 'bodas', 'substantivo', 'Ce sont nos noces d’étain.', 'São nossas bodas de estanho.', 'Datas e festas'],
    ['fêter', 'comemorar', 'verbo', 'On fête ça samedi.', 'Comemoramos no sábado.', 'Datas e festas'],
    ['l’invité', 'convidado', 'substantivo', 'Vingt invités viennent.', 'Vinte convidados vêm.', 'Datas e festas'],
  ],
  B1: [
    ['le diplôme', 'diploma', 'substantivo', 'Elle a un diplôme de droit.', 'Ela tem diploma de direito.', 'Educação superior'],
    ['la thèse', 'tese', 'substantivo', 'Il rédige sa thèse.', 'Ele está escrevendo a tese.', 'Educação superior'],
    ['le cours magistral', 'aula expositiva', 'substantivo', 'Le cours magistral a duré deux heures.', 'A aula expositiva durou duas horas.', 'Educação superior'],
    ['l’enseignant-chercheur', 'professor pesquisador', 'substantivo', "L'enseignant-chercheur a publié un livre.", 'O professor pesquisador publicou um livro.', 'Educação superior'],
    ['le campus', 'campus', 'substantivo', 'Le campus est immense.', 'O campus é imenso.', 'Educação superior'],
    ['le semestre', 'semestre', 'substantivo', 'Le semestre finit en juillet.', 'O semestre acaba em julho.', 'Educação superior'],
    ['s’inscrire', 'matricular-se', 'verbo', 'Je m’inscris le mois prochain.', 'Vou me matricular mês que vem.', 'Educação superior'],
    ['la cité universitaire', 'moradia estudantil', 'substantivo', 'Elle vit en cité universitaire.', 'Ela mora na moradia estudantil.', 'Educação superior'],
    ['obtenir son diplôme', 'formar-se', 'verbo', 'Ils obtiennent leur diplôme en décembre.', 'Eles se formam em dezembro.', 'Educação superior'],
    ['le séminaire', 'seminário', 'substantivo', 'Le séminaire était restreint.', 'O seminário era restrito.', 'Educação superior'],
    ['l’auberge de jeunesse', 'albergue', 'substantivo', 'Nous avons dormi en auberge de jeunesse.', 'Dormimos num albergue.', 'Viagem e hospedagem'],
    ['la réservation d’hôtel', 'reserva de hotel', 'substantivo', 'Ma réservation d’hôtel a été annulée.', 'Minha reserva de hotel foi cancelada.', 'Viagem e hospedagem'],
    ['l’arrivée à l’hôtel', 'check-in', 'substantivo', "L'arrivée à l'hôtel est à quatorze heures.", 'O check-in é às duas.', 'Viagem e hospedagem'],
    ['le réceptionniste', 'recepcionista', 'substantivo', 'Demande au réceptionniste.', 'Pergunte ao recepcionista.', 'Viagem e hospedagem'],
    ['le hall', 'saguão', 'substantivo', 'Attends-moi dans le hall.', 'Me espere no saguão.', 'Viagem e hospedagem'],
    ['le point de repère', 'ponto de referência', 'substantivo', 'Cette tour est un point de repère.', 'Aquela torre é um ponto de referência.', 'Viagem e hospedagem'],
    ['le souvenir de voyage', 'lembrança de viagem', 'substantivo', "J'ai acheté un souvenir de voyage.", 'Comprei uma lembrança de viagem.', 'Viagem e hospedagem'],
    ['le guide touristique', 'guia de viagem', 'substantivo', 'Le guide touristique est périmé.', 'O guia de viagem está desatualizado.', 'Viagem e hospedagem'],
    ['le visa', 'visto', 'substantivo', "J'ai besoin d'un visa.", 'Preciso de visto.', 'Viagem e hospedagem'],
    ['le touriste', 'turista', 'substantivo', 'La ville est pleine de touristes.', 'A cidade está cheia de turistas.', 'Viagem e hospedagem'],
  ],
  B2: [
    ['l’algorithme', 'algoritmo', 'substantivo', "L'algorithme classe les résultats.", 'O algoritmo ordena os resultados.', 'Tecnologia avançada'],
    ['le chiffrement', 'criptografia', 'substantivo', 'Le chiffrement protège les données.', 'A criptografia protege os dados.', 'Tecnologia avançada'],
    ['la bande passante', 'largura de banda', 'substantivo', 'Nous manquons de bande passante.', 'Estamos sem largura de banda.', 'Tecnologia avançada'],
    ['le serveur informatique', 'servidor (máquina)', 'substantivo', 'Le serveur informatique est tombé.', 'O servidor caiu.', 'Tecnologia avançada'],
    ['la base de données', 'banco de dados', 'substantivo', 'Sauvegarde la base de données.', 'Faça backup do banco de dados.', 'Tecnologia avançada'],
    ['l’interface', 'interface', 'substantivo', "L'interface est déroutante.", 'A interface é confusa.', 'Tecnologia avançada'],
    ['l’automatisation', 'automação', 'substantivo', "L'automatisation a réduit les coûts.", 'A automação reduziu custos.', 'Tecnologia avançada'],
    ['le pare-feu', 'firewall', 'substantivo', 'Le pare-feu a bloqué la requête.', 'O firewall bloqueou a requisição.', 'Tecnologia avançada'],
    ['le prototype', 'protótipo', 'substantivo', 'Nous avons construit un prototype.', 'Construímos um protótipo.', 'Tecnologia avançada'],
    ['la latence', 'latência', 'substantivo', "La latence gâche l'expérience.", 'A latência estraga a experiência.', 'Tecnologia avançada'],
    ['la publicité', 'publicidade', 'substantivo', 'La publicité a dopé les ventes.', 'A publicidade impulsionou as vendas.', 'Consumo e marketing'],
    ['le consommateur', 'consumidor', 'substantivo', 'Le consommateur décide.', 'O consumidor decide.', 'Consumo e marketing'],
    ['le commerce de détail', 'varejo', 'substantivo', 'Les marges du commerce de détail sont faibles.', 'As margens do varejo são baixas.', 'Consumo e marketing'],
    ['le commerce de gros', 'atacado', 'substantivo', 'Ils achètent au commerce de gros.', 'Eles compram no atacado.', 'Consumo e marketing'],
    ['l’emballage', 'embalagem', 'substantivo', "L'emballage est du gaspillage.", 'A embalagem é desperdício.', 'Consumo e marketing'],
    ['le logo', 'logotipo', 'substantivo', 'Le logo a été refait.', 'O logotipo foi refeito.', 'Consumo e marketing'],
    ['le slogan', 'slogan', 'substantivo', 'Le slogan a marqué.', 'O slogan marcou.', 'Consumo e marketing'],
    ['la cible', 'público-alvo', 'substantivo', "Définis d'abord la cible.", 'Defina o público-alvo primeiro.', 'Consumo e marketing'],
    ['le parrainage', 'patrocínio / aval', 'substantivo', 'Le parrainage a coûté une fortune.', 'O patrocínio custou uma fortuna.', 'Consumo e marketing'],
    ['la marge commerciale', 'margem de lucro', 'substantivo', 'La marge commerciale est trop élevée.', 'A margem de lucro é alta demais.', 'Consumo e marketing'],
  ],
  C1: [
    ['l’actif', 'ativo (patrimônio)', 'substantivo', "L'actif a perdu de la valeur.", 'O ativo perdeu valor.', 'Finanças'],
    ['les capitaux propres', 'patrimônio líquido', 'substantivo', 'Les capitaux propres ont fondu.', 'O patrimônio líquido encolheu.', 'Finanças'],
    ['le dividende', 'dividendo', 'substantivo', 'Ils ont réduit le dividende.', 'Cortaram o dividendo.', 'Finanças'],
    ['le portefeuille d’investissement', 'carteira de investimentos', 'substantivo', 'Diversifie le portefeuille d’investissement.', 'Diversifique a carteira de investimentos.', 'Finanças'],
    ['la couverture de risque', 'proteção contra risco', 'substantivo', "L'or sert de couverture de risque.", 'O ouro serve de proteção contra risco.', 'Finanças'],
    ['la valorisation', 'avaliação de valor', 'substantivo', 'La valorisation paraît gonflée.', 'A avaliação parece inflada.', 'Finanças'],
    ['l’amortissement', 'amortização', 'substantivo', "L'amortissement étale le coût.", 'A amortização dilui o custo.', 'Finanças'],
    ['le nantissement', 'garantia real', 'substantivo', 'La maison a servi de nantissement.', 'A casa serviu de garantia real.', 'Finanças'],
    ['le rendement', 'rendimento', 'substantivo', "Le rendement est passé sous l'inflation.", 'O rendimento ficou abaixo da inflação.', 'Finanças'],
    ['la solvabilité', 'solvência', 'substantivo', "La solvabilité n'est pas la liquidité.", 'Solvência não é liquidez.', 'Finanças'],
    ['le couple de serrage', 'torque', 'substantivo', 'Vérifie le couple de serrage.', 'Confira o torque.', 'Engenharia'],
    ['l’alliage', 'liga metálica', 'substantivo', "L'alliage résiste à la corrosion.", 'A liga resiste à corrosão.', 'Engenharia'],
    ['le circuit électrique', 'circuito elétrico', 'substantivo', 'Le circuit électrique a surchauffé.', 'O circuito elétrico superaqueceu.', 'Engenharia'],
    ['la tolérance dimensionnelle', 'tolerância dimensional', 'substantivo', 'La tolérance dimensionnelle est d’un millimètre.', 'A tolerância dimensional é de um milímetro.', 'Engenharia'],
    ['l’étalonnage', 'calibração', 'substantivo', "L'étalonnage a dérivé.", 'A calibração se desviou.', 'Engenharia'],
    ['le frottement', 'atrito', 'substantivo', 'Le frottement use la pièce.', 'O atrito desgasta a peça.', 'Engenharia'],
    ['thermique', 'térmico', 'adjetivo', 'La dilatation thermique l’a fissurée.', 'A dilatação térmica a trincou.', 'Engenharia'],
    ['hydraulique', 'hidráulico', 'adjetivo', 'Le système hydraulique a lâché.', 'O sistema hidráulico falhou.', 'Engenharia'],
    ['la soudure', 'solda', 'substantivo', 'La soudure a tenu.', 'A solda aguentou.', 'Engenharia'],
    ['la charge structurelle', 'carga estrutural', 'substantivo', 'La poutre reprend la charge structurelle.', 'A viga recebe a carga estrutural.', 'Engenharia'],
  ],
  C2: [
    ['l’hégémonie', 'hegemonia', 'substantivo', 'Leur hégémonie n’a pas été contestée.', 'A hegemonia deles não foi contestada.', 'Filosofia política'],
    ['la légitimité', 'legitimidade', 'substantivo', 'Le vote a rétabli la légitimité.', 'A votação restabeleceu a legitimidade.', 'Filosofia política'],
    ['le populisme', 'populismo', 'substantivo', 'Le populisme prospère sur la rancœur.', 'O populismo prospera no ressentimento.', 'Filosofia política'],
    ['la méritocratie', 'meritocracia', 'substantivo', 'La méritocratie suppose un départ juste.', 'A meritocracia pressupõe largada justa.', 'Filosofia política'],
    ['égalitaire', 'igualitário', 'adjetivo', "C'est une proposition égalitaire.", 'É uma proposta igualitária.', 'Filosofia política'],
    ['autoritaire', 'autoritário', 'adjetivo', 'Le tournant fut autoritaire.', 'A guinada foi autoritária.', 'Filosofia política'],
    ['le pluralisme', 'pluralismo', 'substantivo', 'Le pluralisme exige un vrai désaccord.', 'O pluralismo exige dissenso real.', 'Filosofia política'],
    ['la subsidiarité', 'subsidiariedade', 'substantivo', 'La subsidiarité descend les décisions.', 'A subsidiariedade desce as decisões.', 'Filosofia política'],
    ['la technocratie', 'tecnocracia', 'substantivo', "La technocratie écarte l'électeur.", 'A tecnocracia afasta o eleitor.', 'Filosofia política'],
    ['l’art de gouverner', 'arte de governar', 'substantivo', "C'était de l'art de gouverner.", 'Aquilo foi arte de governar.', 'Filosofia política'],
    ['la cadence', 'cadência', 'substantivo', 'La cadence résout la phrase.', 'A cadência resolve a frase.', 'Música e som'],
    ['le timbre', 'timbre', 'substantivo', 'Le timbre est reconnaissable.', 'O timbre é reconhecível.', 'Música e som'],
    ['la dissonance', 'dissonância', 'substantivo', 'La dissonance est voulue.', 'A dissonância é proposital.', 'Música e som'],
    ['le crescendo', 'crescendo', 'substantivo', 'Le crescendo monte lentement.', 'O crescendo sobe lentamente.', 'Música e som'],
    ['le contrepoint', 'contraponto', 'substantivo', 'Le contrepoint est complexe.', 'O contraponto é complexo.', 'Música e som'],
    ['la résonance', 'ressonância', 'substantivo', 'La salle a une résonance chaude.', 'A sala tem ressonância quente.', 'Música e som'],
    ['le staccato', 'staccato', 'substantivo', 'Le passage en staccato est délicat.', 'A passagem em staccato é delicada.', 'Música e som'],
    ['le refrain', 'refrão', 'substantivo', 'Le refrain revient quatre fois.', 'O refrão volta quatro vezes.', 'Música e som'],
    ['le tempo', 'andamento', 'substantivo', 'Le tempo traîne ici.', 'O andamento se arrasta aqui.', 'Música e som'],
    ['l’harmonie', 'harmonia', 'substantivo', "L'harmonie change brusquement.", 'A harmonia muda bruscamente.', 'Música e som'],
  ],
};
