/** Italiano — terceiro lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const IT_THEMATIC3: LatinByLevel = {
  A1: [
    ['il figlio', 'filho', 'substantivo', 'Mio figlio ha cinque anni.', 'Meu filho tem cinco anos.', 'Família e pessoas'],
    ['la figlia', 'filha', 'substantivo', 'Sua figlia studia qui.', 'A filha dela estuda aqui.', 'Família e pessoas'],
    ['la nonna', 'avó', 'substantivo', 'Mia nonna cucina bene.', 'Minha avó cozinha bem.', 'Família e pessoas'],
    ['il nonno', 'avô', 'substantivo', 'Mio nonno racconta storie.', 'Meu avô conta histórias.', 'Família e pessoas'],
    ['lo zio', 'tio', 'substantivo', 'Mio zio abita lontano.', 'Meu tio mora longe.', 'Família e pessoas'],
    ['la zia', 'tia', 'substantivo', 'Mia zia è infermiera.', 'Minha tia é enfermeira.', 'Família e pessoas'],
    ['il cugino', 'primo', 'substantivo', 'Mio cugino ha la mia età.', 'Meu primo tem a minha idade.', 'Família e pessoas'],
    ['la moglie', 'esposa', 'substantivo', 'Sua moglie lavora in centro.', 'A esposa dele trabalha no centro.', 'Família e pessoas'],
    ['il marito', 'marido', 'substantivo', 'Suo marito è insegnante.', 'O marido dela é professor.', 'Família e pessoas'],
    ['l’amico', 'amigo', 'substantivo', 'È il mio migliore amico.', 'Ele é meu melhor amigo.', 'Família e pessoas'],
    ['la stanza', 'cômodo', 'substantivo', 'Questa stanza è tranquilla.', 'Este cômodo é tranquilo.', 'Casa e cômodos'],
    ['il soggiorno', 'sala de estar', 'substantivo', 'Guardiamo la TV in soggiorno.', 'Assistimos TV na sala de estar.', 'Casa e cômodos'],
    ['la camera da letto', 'quarto', 'substantivo', 'La camera da letto è al piano di sopra.', 'O quarto fica no andar de cima.', 'Casa e cômodos'],
    ['il giardino', 'jardim', 'substantivo', 'Il giardino ha bisogno d’acqua.', 'O jardim precisa de água.', 'Casa e cômodos'],
    ['il muro', 'parede', 'substantivo', 'Il muro è sporco.', 'A parede está suja.', 'Casa e cômodos'],
    ['il pavimento', 'chão / piso', 'substantivo', 'Il pavimento è bagnato.', 'O chão está molhado.', 'Casa e cômodos'],
    ['le scale', 'escada', 'substantivo', 'Le scale sono ripide.', 'A escada é íngreme.', 'Casa e cômodos'],
    ['la chiave', 'chave', 'substantivo', 'Ho perso la chiave.', 'Perdi a chave.', 'Casa e cômodos'],
    ['la lampada', 'luminária', 'substantivo', 'Accendi la lampada.', 'Acenda a luminária.', 'Casa e cômodos'],
    ['il garage', 'garagem', 'substantivo', 'La macchina è in garage.', 'O carro está na garagem.', 'Casa e cômodos'],
  ],
  A2: [
    ['la cintura', 'cinto', 'substantivo', 'Questa cintura è troppo lunga.', 'Este cinto é comprido demais.', 'Vestuário e aparência'],
    ['la sciarpa', 'cachecol', 'substantivo', 'Metti la sciarpa, fa freddo.', 'Use o cachecol, está frio.', 'Vestuário e aparência'],
    ['il guanto', 'luva', 'substantivo', 'Ho perso un guanto.', 'Perdi uma luva.', 'Vestuário e aparência'],
    ['lo stivale', 'bota', 'substantivo', 'Questi stivali sono pesanti.', 'Estas botas são pesadas.', 'Vestuário e aparência'],
    ['la manica', 'manga (de roupa)', 'substantivo', 'La manica è strappata.', 'A manga está rasgada.', 'Vestuário e aparência'],
    ['la tasca', 'bolso', 'substantivo', 'È nella mia tasca.', 'Está no meu bolso.', 'Vestuário e aparência'],
    ['il bottone', 'botão', 'substantivo', 'È caduto un bottone.', 'Caiu um botão.', 'Vestuário e aparência'],
    ['la cerniera', 'zíper', 'substantivo', 'La cerniera è rotta.', 'O zíper está quebrado.', 'Vestuário e aparência'],
    ['la barba', 'barba', 'substantivo', 'Si è fatto crescere la barba.', 'Ele deixou a barba crescer.', 'Vestuário e aparência'],
    ['il trucco', 'maquiagem', 'substantivo', 'Usa poco trucco.', 'Ela usa pouca maquiagem.', 'Vestuário e aparência'],
    ['il compleanno', 'aniversário', 'substantivo', 'Oggi è il mio compleanno.', 'Hoje é meu aniversário.', 'Datas e festas'],
    ['il giorno festivo', 'feriado', 'substantivo', 'Lunedì è giorno festivo.', 'Segunda é feriado.', 'Datas e festas'],
    ['il matrimonio', 'casamento', 'substantivo', 'Il matrimonio è a giugno.', 'O casamento é em junho.', 'Datas e festas'],
    ['il regalo', 'presente', 'substantivo', 'Grazie per il regalo.', 'Obrigado pelo presente.', 'Datas e festas'],
    ['la festa', 'festa', 'substantivo', 'La festa comincia alle nove.', 'A festa começa às nove.', 'Datas e festas'],
    ['la candela', 'vela', 'substantivo', 'Accendi le candele.', 'Acenda as velas.', 'Datas e festas'],
    ['l’invito', 'convite', 'substantivo', 'Ho ricevuto l’invito.', 'Recebi o convite.', 'Datas e festas'],
    ['l’anniversario', 'data comemorativa', 'substantivo', 'È il nostro decimo anniversario.', 'É nosso décimo aniversário.', 'Datas e festas'],
    ['festeggiare', 'comemorar', 'verbo', 'Festeggiamo sabato.', 'Comemoramos no sábado.', 'Datas e festas'],
    ['l’ospite', 'convidado', 'substantivo', 'Vengono venti ospiti.', 'Vêm vinte convidados.', 'Datas e festas'],
  ],
  B1: [
    ['la laurea', 'diploma / graduação', 'substantivo', 'Ha una laurea in giurisprudenza.', 'Ela tem diploma em direito.', 'Educação superior'],
    ['la tesi', 'tese', 'substantivo', 'Sta scrivendo la tesi.', 'Ele está escrevendo a tese.', 'Educação superior'],
    ['la lezione universitaria', 'aula universitária', 'substantivo', 'La lezione universitaria è durata due ore.', 'A aula universitária durou duas horas.', 'Educação superior'],
    ['il docente', 'docente', 'substantivo', 'Il docente ha pubblicato un libro.', 'O docente publicou um livro.', 'Educação superior'],
    ['il campus', 'campus', 'substantivo', 'Il campus è enorme.', 'O campus é enorme.', 'Educação superior'],
    ['il semestre', 'semestre', 'substantivo', 'Il semestre finisce a luglio.', 'O semestre acaba em julho.', 'Educação superior'],
    ['iscriversi', 'matricular-se', 'verbo', 'Mi iscrivo il mese prossimo.', 'Vou me matricular mês que vem.', 'Educação superior'],
    ['la casa dello studente', 'moradia estudantil', 'substantivo', 'Vive nella casa dello studente.', 'Ela mora na moradia estudantil.', 'Educação superior'],
    ['laurearsi', 'formar-se', 'verbo', 'Si laureano a dicembre.', 'Eles se formam em dezembro.', 'Educação superior'],
    ['il seminario universitario', 'seminário', 'substantivo', 'Il seminario universitario era piccolo.', 'O seminário era pequeno.', 'Educação superior'],
    ['l’ostello', 'albergue', 'substantivo', 'Abbiamo dormito in ostello.', 'Dormimos num albergue.', 'Viagem e hospedagem'],
    ['la prenotazione alberghiera', 'reserva de hotel', 'substantivo', 'La prenotazione alberghiera è stata annullata.', 'A reserva de hotel foi cancelada.', 'Viagem e hospedagem'],
    ['il check-in', 'check-in', 'substantivo', 'Il check-in è dalle due.', 'O check-in é a partir das duas.', 'Viagem e hospedagem'],
    ['il receptionist', 'recepcionista', 'substantivo', 'Chiedi al receptionist.', 'Pergunte ao recepcionista.', 'Viagem e hospedagem'],
    ['la hall', 'saguão', 'substantivo', 'Aspettami nella hall.', 'Me espere no saguão.', 'Viagem e hospedagem'],
    ['il punto di riferimento', 'ponto de referência', 'substantivo', 'Quella torre è un punto di riferimento.', 'Aquela torre é um ponto de referência.', 'Viagem e hospedagem'],
    ['il souvenir', 'lembrança de viagem', 'substantivo', 'Ho comprato un souvenir.', 'Comprei uma lembrança.', 'Viagem e hospedagem'],
    ['la guida turistica', 'guia de viagem', 'substantivo', 'La guida turistica è superata.', 'O guia de viagem está desatualizado.', 'Viagem e hospedagem'],
    ['il visto', 'visto', 'substantivo', 'Mi serve un visto.', 'Preciso de visto.', 'Viagem e hospedagem'],
    ['il turista', 'turista', 'substantivo', 'La città è piena di turisti.', 'A cidade está cheia de turistas.', 'Viagem e hospedagem'],
  ],
  B2: [
    ['l’algoritmo', 'algoritmo', 'substantivo', "L'algoritmo ordina i risultati.", 'O algoritmo ordena os resultados.', 'Tecnologia avançada'],
    ['la cifratura', 'criptografia', 'substantivo', 'La cifratura protegge i dati.', 'A criptografia protege os dados.', 'Tecnologia avançada'],
    ['la larghezza di banda', 'largura de banda', 'substantivo', 'Abbiamo finito la larghezza di banda.', 'Ficamos sem largura de banda.', 'Tecnologia avançada'],
    ['il server', 'servidor', 'substantivo', 'Il server è caduto.', 'O servidor caiu.', 'Tecnologia avançada'],
    ['il database', 'banco de dados', 'substantivo', 'Fai il backup del database.', 'Faça backup do banco de dados.', 'Tecnologia avançada'],
    ['l’interfaccia', 'interface', 'substantivo', "L'interfaccia è confusa.", 'A interface é confusa.', 'Tecnologia avançada'],
    ['l’automazione', 'automação', 'substantivo', "L'automazione ha tagliato i costi.", 'A automação cortou os custos.', 'Tecnologia avançada'],
    ['il firewall', 'firewall', 'substantivo', 'Il firewall lo ha bloccato.', 'O firewall bloqueou.', 'Tecnologia avançada'],
    ['il prototipo', 'protótipo', 'substantivo', 'Abbiamo costruito un prototipo.', 'Construímos um protótipo.', 'Tecnologia avançada'],
    ['la latenza', 'latência', 'substantivo', "La latenza rovina l'esperienza.", 'A latência estraga a experiência.', 'Tecnologia avançada'],
    ['la pubblicità', 'publicidade', 'substantivo', 'La pubblicità ha spinto le vendite.', 'A publicidade impulsionou as vendas.', 'Consumo e marketing'],
    ['il consumatore', 'consumidor', 'substantivo', 'Il consumatore decide.', 'O consumidor decide.', 'Consumo e marketing'],
    ['il commercio al dettaglio', 'varejo', 'substantivo', 'I margini del commercio al dettaglio sono bassi.', 'As margens do varejo são baixas.', 'Consumo e marketing'],
    ['il commercio all’ingrosso', 'atacado', 'substantivo', 'Comprano nel commercio all’ingrosso.', 'Eles compram no atacado.', 'Consumo e marketing'],
    ['la confezione', 'embalagem', 'substantivo', 'La confezione è uno spreco.', 'A embalagem é um desperdício.', 'Consumo e marketing'],
    ['il logo', 'logotipo', 'substantivo', 'Hanno rifatto il logo.', 'Refizeram o logotipo.', 'Consumo e marketing'],
    ['lo slogan', 'slogan', 'substantivo', 'Lo slogan ha funzionato.', 'O slogan funcionou.', 'Consumo e marketing'],
    ['il pubblico di riferimento', 'público-alvo', 'substantivo', 'Definisci prima il pubblico di riferimento.', 'Defina o público-alvo primeiro.', 'Consumo e marketing'],
    ['la sponsorizzazione', 'patrocínio', 'substantivo', 'La sponsorizzazione è costata molto.', 'O patrocínio custou muito.', 'Consumo e marketing'],
    ['il ricarico', 'margem de lucro', 'substantivo', 'Il ricarico è troppo alto.', 'A margem de lucro é alta demais.', 'Consumo e marketing'],
  ],
  C1: [
    ['l’attivo patrimoniale', 'ativo patrimonial', 'substantivo', "L'attivo patrimoniale ha perso valore.", 'O ativo patrimonial perdeu valor.', 'Finanças'],
    ['il patrimonio netto', 'patrimônio líquido', 'substantivo', 'Il patrimonio netto si è ridotto.', 'O patrimônio líquido encolheu.', 'Finanças'],
    ['il dividendo', 'dividendo', 'substantivo', 'Hanno tagliato il dividendo.', 'Cortaram o dividendo.', 'Finanças'],
    ['il portafoglio titoli', 'carteira de investimentos', 'substantivo', 'Diversifica il portafoglio titoli.', 'Diversifique a carteira.', 'Finanças'],
    ['la copertura del rischio', 'proteção contra risco', 'substantivo', "L'oro funge da copertura del rischio.", 'O ouro serve de proteção contra risco.', 'Finanças'],
    ['la valutazione aziendale', 'avaliação de valor', 'substantivo', 'La valutazione aziendale sembra gonfiata.', 'A avaliação parece inflada.', 'Finanças'],
    ['l’ammortamento', 'amortização', 'substantivo', "L'ammortamento distribuisce il costo.", 'A amortização dilui o custo.', 'Finanças'],
    ['la garanzia reale', 'garantia real', 'substantivo', 'La casa è servita da garanzia reale.', 'A casa serviu de garantia real.', 'Finanças'],
    ['il rendimento finanziario', 'rendimento financeiro', 'substantivo', "Il rendimento finanziario è sceso sotto l'inflazione.", 'O rendimento ficou abaixo da inflação.', 'Finanças'],
    ['la solvibilità', 'solvência', 'substantivo', 'La solvibilità non è liquidità.', 'Solvência não é liquidez.', 'Finanças'],
    ['la coppia di serraggio', 'torque', 'substantivo', 'Controlla la coppia di serraggio.', 'Confira o torque.', 'Engenharia'],
    ['la lega metallica', 'liga metálica', 'substantivo', 'La lega metallica resiste alla corrosione.', 'A liga resiste à corrosão.', 'Engenharia'],
    ['il circuito elettrico', 'circuito elétrico', 'substantivo', 'Il circuito elettrico si è surriscaldato.', 'O circuito elétrico superaqueceu.', 'Engenharia'],
    ['la tolleranza dimensionale', 'tolerância dimensional', 'substantivo', 'La tolleranza dimensionale è di un millimetro.', 'A tolerância dimensional é de um milímetro.', 'Engenharia'],
    ['la taratura', 'calibração', 'substantivo', 'La taratura è andata fuori registro.', 'A calibração se desviou.', 'Engenharia'],
    ['l’attrito', 'atrito', 'substantivo', "L'attrito consuma il pezzo.", 'O atrito desgasta a peça.', 'Engenharia'],
    ['termico', 'térmico', 'adjetivo', 'La dilatazione termica lo ha incrinato.', 'A dilatação térmica o trincou.', 'Engenharia'],
    ['idraulico', 'hidráulico', 'adjetivo', 'Il sistema idraulico ha ceduto.', 'O sistema hidráulico falhou.', 'Engenharia'],
    ['la saldatura', 'solda', 'substantivo', 'La saldatura ha tenuto.', 'A solda aguentou.', 'Engenharia'],
    ['il carico strutturale', 'carga estrutural', 'substantivo', 'La trave regge il carico strutturale.', 'A viga suporta a carga estrutural.', 'Engenharia'],
  ],
  C2: [
    ['l’egemonia', 'hegemonia', 'substantivo', 'La loro egemonia non fu contestata.', 'A hegemonia deles não foi contestada.', 'Filosofia política'],
    ['la legittimità', 'legitimidade', 'substantivo', 'Il voto ha restituito legittimità.', 'A votação restituiu legitimidade.', 'Filosofia política'],
    ['il populismo', 'populismo', 'substantivo', 'Il populismo prospera sul rancore.', 'O populismo prospera no rancor.', 'Filosofia política'],
    ['la meritocrazia', 'meritocracia', 'substantivo', 'La meritocrazia presuppone una partenza equa.', 'A meritocracia pressupõe largada justa.', 'Filosofia política'],
    ['egualitario', 'igualitário', 'adjetivo', 'È una proposta egualitaria.', 'É uma proposta igualitária.', 'Filosofia política'],
    ['autoritario', 'autoritário', 'adjetivo', 'La svolta fu autoritaria.', 'A guinada foi autoritária.', 'Filosofia política'],
    ['il pluralismo', 'pluralismo', 'substantivo', 'Il pluralismo richiede dissenso vero.', 'O pluralismo exige dissenso verdadeiro.', 'Filosofia política'],
    ['la sussidiarietà', 'subsidiariedade', 'substantivo', 'La sussidiarietà abbassa le decisioni.', 'A subsidiariedade desce as decisões.', 'Filosofia política'],
    ['la tecnocrazia', 'tecnocracia', 'substantivo', "La tecnocrazia mette l'elettore ai margini.", 'A tecnocracia marginaliza o eleitor.', 'Filosofia política'],
    ['l’arte di governare', 'arte de governar', 'substantivo', 'Quella fu arte di governare.', 'Aquilo foi arte de governar.', 'Filosofia política'],
    ['la cadenza', 'cadência', 'substantivo', 'La cadenza risolve la frase.', 'A cadência resolve a frase.', 'Música e som'],
    ['il timbro', 'timbre', 'substantivo', 'Il timbro è inconfondibile.', 'O timbre é inconfundível.', 'Música e som'],
    ['la dissonanza', 'dissonância', 'substantivo', 'La dissonanza è voluta.', 'A dissonância é proposital.', 'Música e som'],
    ['il crescendo', 'crescendo', 'substantivo', 'Il crescendo sale lentamente.', 'O crescendo sobe lentamente.', 'Música e som'],
    ['il contrappunto', 'contraponto', 'substantivo', 'Il contrappunto è intricato.', 'O contraponto é intrincado.', 'Música e som'],
    ['la risonanza', 'ressonância', 'substantivo', 'La sala ha una risonanza calda.', 'A sala tem ressonância quente.', 'Música e som'],
    ['lo staccato', 'staccato', 'substantivo', 'Il passaggio in staccato è insidioso.', 'A passagem em staccato é traiçoeira.', 'Música e som'],
    ['il ritornello', 'refrão', 'substantivo', 'Il ritornello torna quattro volte.', 'O refrão volta quatro vezes.', 'Música e som'],
    ['il tempo musicale', 'andamento', 'substantivo', 'Qui il tempo musicale si trascina.', 'Aqui o andamento se arrasta.', 'Música e som'],
    ['l’armonia', 'harmonia', 'substantivo', "L'armonia cambia di colpo.", 'A harmonia muda de repente.', 'Música e som'],
  ],
};
