/** Japonês — terceiro lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { AsianByLevel } from '../entry';

export const JA_THEMATIC3: AsianByLevel = {
  A1: [
    ['息子', 'musuko', 'filho', 'substantivo', '息子は五歳です。', 'Musuko wa gosai desu.', 'Meu filho tem cinco anos.', 'Família e pessoas'],
    ['娘', 'musume', 'filha', 'substantivo', '娘はここで勉強しています。', 'Musume wa koko de benkyō shite imasu.', 'Minha filha estuda aqui.', 'Família e pessoas'],
    ['祖母', 'sobo', 'avó', 'substantivo', '祖母は料理が上手です。', 'Sobo wa ryōri ga jōzu desu.', 'Minha avó cozinha bem.', 'Família e pessoas'],
    ['祖父', 'sofu', 'avô', 'substantivo', '祖父は話が面白いです。', 'Sofu wa hanashi ga omoshiroi desu.', 'Meu avô conta boas histórias.', 'Família e pessoas'],
    ['おじ', 'oji', 'tio', 'substantivo', 'おじは遠くに住んでいます。', 'Oji wa tōku ni sunde imasu.', 'Meu tio mora longe.', 'Família e pessoas'],
    ['おば', 'oba', 'tia', 'substantivo', 'おばは看護師です。', 'Oba wa kangoshi desu.', 'Minha tia é enfermeira.', 'Família e pessoas'],
    ['いとこ', 'itoko', 'primo', 'substantivo', 'いとこは同い年です。', 'Itoko wa onaidoshi desu.', 'Meu primo tem a minha idade.', 'Família e pessoas'],
    ['妻', 'tsuma', 'esposa', 'substantivo', '妻は町で働いています。', 'Tsuma wa machi de hataraite imasu.', 'Minha esposa trabalha na cidade.', 'Família e pessoas'],
    ['夫', 'otto', 'marido', 'substantivo', '夫は先生です。', 'Otto wa sensei desu.', 'Meu marido é professor.', 'Família e pessoas'],
    ['友達', 'tomodachi', 'amigo', 'substantivo', '彼女は一番の友達です。', 'Kanojo wa ichiban no tomodachi desu.', 'Ela é minha melhor amiga.', 'Família e pessoas'],
    ['部屋', 'heya', 'quarto / cômodo', 'substantivo', 'この部屋は静かです。', 'Kono heya wa shizuka desu.', 'Este quarto é silencioso.', 'Casa e cômodos'],
    ['居間', 'ima', 'sala de estar', 'substantivo', '居間でテレビを見ます。', 'Ima de terebi o mimasu.', 'Assistimos TV na sala de estar.', 'Casa e cômodos'],
    ['寝室', 'shinshitsu', 'dormitório', 'substantivo', '寝室は二階です。', 'Shinshitsu wa nikai desu.', 'O dormitório fica no segundo andar.', 'Casa e cômodos'],
    ['庭', 'niwa', 'jardim / quintal', 'substantivo', '庭に水をやってください。', 'Niwa ni mizu o yatte kudasai.', 'Regue o jardim.', 'Casa e cômodos'],
    ['壁', 'kabe', 'parede', 'substantivo', '壁が汚れています。', 'Kabe ga yogorete imasu.', 'A parede está suja.', 'Casa e cômodos'],
    ['床', 'yuka', 'chão / piso', 'substantivo', '床がぬれています。', 'Yuka ga nurete imasu.', 'O chão está molhado.', 'Casa e cômodos'],
    ['階段', 'kaidan', 'escada', 'substantivo', 'この階段は急です。', 'Kono kaidan wa kyū desu.', 'Esta escada é íngreme.', 'Casa e cômodos'],
    ['鍵', 'kagi', 'chave', 'substantivo', '鍵をなくしました。', 'Kagi o nakushimashita.', 'Perdi a chave.', 'Casa e cômodos'],
    ['電気スタンド', 'denki sutando', 'luminária', 'substantivo', '電気スタンドをつけてください。', 'Denki sutando o tsukete kudasai.', 'Acenda a luminária.', 'Casa e cômodos'],
    ['車庫', 'shako', 'garagem', 'substantivo', '車は車庫にあります。', 'Kuruma wa shako ni arimasu.', 'O carro está na garagem.', 'Casa e cômodos'],
  ],
  A2: [
    ['ベルト', 'beruto', 'cinto', 'substantivo', 'このベルトは長すぎます。', 'Kono beruto wa nagasugimasu.', 'Este cinto é comprido demais.', 'Vestuário e aparência'],
    ['マフラー', 'mafuraa', 'cachecol', 'substantivo', '寒いのでマフラーをしてください。', 'Samui node mafurā o shite kudasai.', 'Está frio, use um cachecol.', 'Vestuário e aparência'],
    ['手袋', 'tebukuro', 'luva', 'substantivo', '手袋を片方なくしました。', 'Tebukuro o katahō nakushimashita.', 'Perdi uma das luvas.', 'Vestuário e aparência'],
    ['ブーツ', 'buutsu', 'bota', 'substantivo', 'このブーツは重いです。', 'Kono būtsu wa omoi desu.', 'Estas botas são pesadas.', 'Vestuário e aparência'],
    ['袖', 'sode', 'manga (de roupa)', 'substantivo', '袖が破れています。', 'Sode ga yaburete imasu.', 'A manga está rasgada.', 'Vestuário e aparência'],
    ['ポケット', 'poketto', 'bolso', 'substantivo', 'ポケットの中にあります。', 'Poketto no naka ni arimasu.', 'Está no bolso.', 'Vestuário e aparência'],
    ['ボタン', 'botan', 'botão', 'substantivo', 'ボタンが取れました。', 'Botan ga toremashita.', 'Caiu um botão.', 'Vestuário e aparência'],
    ['ファスナー', 'fasunaa', 'zíper', 'substantivo', 'ファスナーが壊れています。', 'Fasunā ga kowarete imasu.', 'O zíper está quebrado.', 'Vestuário e aparência'],
    ['ひげ', 'hige', 'barba', 'substantivo', 'ひげを伸ばしました。', 'Hige o nobashimashita.', 'Ele deixou a barba crescer.', 'Vestuário e aparência'],
    ['化粧', 'keshou', 'maquiagem', 'substantivo', '化粧は薄めです。', 'Keshō wa usume desu.', 'A maquiagem é leve.', 'Vestuário e aparência'],
    ['誕生日', 'tanjoubi', 'aniversário', 'substantivo', '今日は誕生日です。', 'Kyō wa tanjōbi desu.', 'Hoje é meu aniversário.', 'Datas e festas'],
    ['祝日', 'shukujitsu', 'feriado', 'substantivo', '月曜日は祝日です。', 'Getsuyōbi wa shukujitsu desu.', 'Segunda é feriado.', 'Datas e festas'],
    ['結婚式', 'kekkonshiki', 'casamento (cerimônia)', 'substantivo', '結婚式は六月です。', 'Kekkonshiki wa rokugatsu desu.', 'O casamento é em junho.', 'Datas e festas'],
    ['贈り物', 'okurimono', 'presente', 'substantivo', '贈り物をありがとうございます。', 'Okurimono o arigatō gozaimasu.', 'Obrigado pelo presente.', 'Datas e festas'],
    ['パーティー', 'paatii', 'festa', 'substantivo', 'パーティーは九時からです。', 'Pātī wa kuji kara desu.', 'A festa começa às nove.', 'Datas e festas'],
    ['ろうそく', 'rousoku', 'vela', 'substantivo', 'ろうそくに火をつけてください。', 'Rōsoku ni hi o tsukete kudasai.', 'Acenda as velas.', 'Datas e festas'],
    ['招待状', 'shoutaijou', 'convite', 'substantivo', '招待状が届きました。', 'Shōtaijō ga todokimashita.', 'O convite chegou.', 'Datas e festas'],
    ['記念日', 'kinenbi', 'data comemorativa', 'substantivo', '十回目の記念日です。', 'Jūkaime no kinenbi desu.', 'É o décimo aniversário.', 'Datas e festas'],
    ['祝う', 'iwau', 'comemorar', 'verbo', '土曜日に祝います。', 'Doyōbi ni iwaimasu.', 'Comemoramos no sábado.', 'Datas e festas'],
    ['招待客', 'shoutaikyaku', 'convidado', 'substantivo', '招待客は二十人です。', 'Shōtaikyaku wa nijūnin desu.', 'São vinte convidados.', 'Datas e festas'],
  ],
  B1: [
    ['学位', 'gakui', 'diploma / título', 'substantivo', '彼女は法学の学位があります。', 'Kanojo wa hōgaku no gakui ga arimasu.', 'Ela tem diploma em direito.', 'Educação superior'],
    ['論文', 'ronbun', 'tese / artigo acadêmico', 'substantivo', '論文を書いています。', 'Ronbun o kaite imasu.', 'Ele está escrevendo a tese.', 'Educação superior'],
    ['講義', 'kougi', 'aula expositiva', 'substantivo', '講義は二時間続きました。', 'Kōgi wa nijikan tsuzukimashita.', 'A aula durou duas horas.', 'Educação superior'],
    ['教授', 'kyouju', 'professor titular', 'substantivo', '教授が本を出版しました。', 'Kyōju ga hon o shuppan shimashita.', 'O professor publicou um livro.', 'Educação superior'],
    ['キャンパス', 'kyanpasu', 'campus', 'substantivo', 'キャンパスは広いです。', 'Kyanpasu wa hiroi desu.', 'O campus é grande.', 'Educação superior'],
    ['学期', 'gakki', 'semestre', 'substantivo', '学期は七月に終わります。', 'Gakki wa shichigatsu ni owarimasu.', 'O semestre acaba em julho.', 'Educação superior'],
    ['入学する', 'nyuugaku suru', 'matricular-se', 'verbo', '来月入学します。', 'Raigetsu nyūgaku shimasu.', 'Vou me matricular mês que vem.', 'Educação superior'],
    ['学生寮', 'gakuseiryou', 'alojamento estudantil', 'substantivo', '学生寮に住んでいます。', 'Gakuseiryō ni sunde imasu.', 'Ela mora no alojamento estudantil.', 'Educação superior'],
    ['卒業する', 'sotsugyou suru', 'formar-se', 'verbo', '十二月に卒業します。', 'Jūnigatsu ni sotsugyō shimasu.', 'Eles se formam em dezembro.', 'Educação superior'],
    ['ゼミ', 'zemi', 'seminário', 'substantivo', 'ゼミは少人数でした。', 'Zemi wa shōninzū deshita.', 'O seminário era pequeno.', 'Educação superior'],
    ['ゲストハウス', 'gesutohausu', 'albergue', 'substantivo', 'ゲストハウスに泊まりました。', 'Gesutohausu ni tomarimashita.', 'Ficamos num albergue.', 'Viagem e hospedagem'],
    ['宿の予約', 'yado no yoyaku', 'reserva de hospedagem', 'substantivo', '宿の予約が取り消されました。', 'Yado no yoyaku ga torikesaremashita.', 'A reserva foi cancelada.', 'Viagem e hospedagem'],
    ['チェックイン', 'chekkuin', 'check-in', 'substantivo', 'チェックインは二時からです。', 'Chekkuin wa niji kara desu.', 'O check-in é a partir das duas.', 'Viagem e hospedagem'],
    ['受付係', 'uketsukegakari', 'recepcionista', 'substantivo', '受付係に聞いてください。', 'Uketsukegakari ni kiite kudasai.', 'Pergunte ao recepcionista.', 'Viagem e hospedagem'],
    ['ロビー', 'robii', 'saguão', 'substantivo', 'ロビーで待っていてください。', 'Robī de matte ite kudasai.', 'Me espere no saguão.', 'Viagem e hospedagem'],
    ['名所', 'meisho', 'ponto turístico', 'substantivo', 'あの塔は名所です。', 'Ano tō wa meisho desu.', 'Aquela torre é um ponto turístico.', 'Viagem e hospedagem'],
    ['土産', 'miyage', 'lembrança de viagem', 'substantivo', '土産を買いました。', 'Miyage o kaimashita.', 'Comprei uma lembrança.', 'Viagem e hospedagem'],
    ['旅行案内書', 'ryokou annaisho', 'guia de viagem', 'substantivo', '旅行案内書が古いです。', 'Ryokō annaisho ga furui desu.', 'O guia de viagem está velho.', 'Viagem e hospedagem'],
    ['ビザ', 'biza', 'visto', 'substantivo', 'ビザが必要です。', 'Biza ga hitsuyō desu.', 'Preciso de visto.', 'Viagem e hospedagem'],
    ['観光客', 'kankoukyaku', 'turista', 'substantivo', '街は観光客でいっぱいです。', 'Machi wa kankōkyaku de ippai desu.', 'A cidade está cheia de turistas.', 'Viagem e hospedagem'],
  ],
  B2: [
    ['アルゴリズム', 'arugorizumu', 'algoritmo', 'substantivo', 'アルゴリズムが結果を並べます。', 'Arugorizumu ga kekka o narabemasu.', 'O algoritmo ordena os resultados.', 'Tecnologia avançada'],
    ['暗号化', 'angouka', 'criptografia', 'substantivo', '暗号化がデータを守ります。', 'Angōka ga dēta o mamorimasu.', 'A criptografia protege os dados.', 'Tecnologia avançada'],
    ['帯域幅', 'taiikihaba', 'largura de banda', 'substantivo', '帯域幅が足りません。', 'Taiikihaba ga tarimasen.', 'A largura de banda não basta.', 'Tecnologia avançada'],
    ['サーバー', 'saabaa', 'servidor', 'substantivo', 'サーバーが落ちました。', 'Sābā ga ochimashita.', 'O servidor caiu.', 'Tecnologia avançada'],
    ['データベース', 'deetabeesu', 'banco de dados', 'substantivo', 'データベースを保存してください。', 'Dētabēsu o hozon shite kudasai.', 'Faça backup do banco de dados.', 'Tecnologia avançada'],
    ['インターフェース', 'intaafeesu', 'interface', 'substantivo', 'インターフェースが分かりにくいです。', 'Intāfēsu ga wakarinikui desu.', 'A interface é confusa.', 'Tecnologia avançada'],
    ['自動化', 'jidouka', 'automação', 'substantivo', '自動化でコストが下がりました。', 'Jidōka de kosuto ga sagarimashita.', 'A automação baixou os custos.', 'Tecnologia avançada'],
    ['ファイアウォール', 'faiawooru', 'firewall', 'substantivo', 'ファイアウォールが遮断しました。', 'Faiawōru ga shadan shimashita.', 'O firewall bloqueou.', 'Tecnologia avançada'],
    ['試作品', 'shisakuhin', 'protótipo', 'substantivo', '試作品を作りました。', 'Shisakuhin o tsukurimashita.', 'Construímos um protótipo.', 'Tecnologia avançada'],
    ['遅延時間', 'chien jikan', 'latência', 'substantivo', '遅延時間が体験を損ないます。', 'Chien jikan ga taiken o sokonaimasu.', 'A latência estraga a experiência.', 'Tecnologia avançada'],
    ['広告', 'koukoku', 'publicidade', 'substantivo', '広告が売上を押し上げました。', 'Kōkoku ga uriage o oshiagemashita.', 'A publicidade impulsionou as vendas.', 'Consumo e marketing'],
    ['消費者', 'shouhisha', 'consumidor', 'substantivo', '決めるのは消費者です。', 'Kimeru no wa shōhisha desu.', 'Quem decide é o consumidor.', 'Consumo e marketing'],
    ['小売業', 'kourigyou', 'setor varejista', 'substantivo', '小売業の利幅は薄いです。', 'Kourigyō no rihaba wa usui desu.', 'A margem do varejo é fina.', 'Consumo e marketing'],
    ['卸売', 'oroshiuri', 'atacado', 'substantivo', '卸売で仕入れています。', 'Oroshiuri de shiirete imasu.', 'Eles compram no atacado.', 'Consumo e marketing'],
    ['包装', 'housou', 'embalagem', 'substantivo', '包装が過剰です。', 'Hōsō ga kajō desu.', 'A embalagem é excessiva.', 'Consumo e marketing'],
    ['ロゴ', 'rogo', 'logotipo', 'substantivo', 'ロゴを作り直しました。', 'Rogo o tsukurinaoshimashita.', 'Refizeram o logotipo.', 'Consumo e marketing'],
    ['キャッチコピー', 'kyacchikopii', 'slogan', 'substantivo', 'キャッチコピーが浸透しました。', 'Kyacchikopī ga shintō shimashita.', 'O slogan pegou.', 'Consumo e marketing'],
    ['対象顧客', 'taishou kokyaku', 'público-alvo', 'substantivo', 'まず対象顧客を決めてください。', 'Mazu taishō kokyaku o kimete kudasai.', 'Defina o público-alvo primeiro.', 'Consumo e marketing'],
    ['推奨広告', 'suishou koukoku', 'publicidade com aval', 'substantivo', '推奨広告に大金がかかりました。', 'Suishō kōkoku ni taikin ga kakarimashita.', 'A publicidade com aval custou caro.', 'Consumo e marketing'],
    ['利益率', 'ekiritsu', 'margem de lucro', 'substantivo', '利益率が高すぎます。', 'Ekiritsu ga takasugimasu.', 'A margem de lucro é alta demais.', 'Consumo e marketing'],
  ],
  C1: [
    ['資産', 'shisan', 'ativo (patrimônio)', 'substantivo', '資産の価値が下がりました。', 'Shisan no kachi ga sagarimashita.', 'O ativo perdeu valor.', 'Finanças'],
    ['自己資本', 'jikoshihon', 'patrimônio líquido', 'substantivo', '自己資本が目減りしました。', 'Jikoshihon ga meberi shimashita.', 'O patrimônio líquido encolheu.', 'Finanças'],
    ['配当', 'haitou', 'dividendo', 'substantivo', '配当が減らされました。', 'Haitō ga herasaremashita.', 'O dividendo foi cortado.', 'Finanças'],
    ['運用資産', 'un’you shisan', 'carteira de investimentos', 'substantivo', '運用資産を分散してください。', 'Un’yō shisan o bunsan shite kudasai.', 'Diversifique a carteira.', 'Finanças'],
    ['リスク回避', 'risuku kaihi', 'proteção contra risco', 'substantivo', '金はリスク回避に使われます。', 'Kin wa risuku kaihi ni tsukawaremasu.', 'O ouro serve de proteção contra risco.', 'Finanças'],
    ['企業価値評価', 'kigyou kachi hyouka', 'avaliação de valor', 'substantivo', '企業価値評価が過大です。', 'Kigyō kachi hyōka ga kadai desu.', 'A avaliação está inflada.', 'Finanças'],
    ['償却', 'shoukyaku', 'amortização', 'substantivo', '償却で費用を平準化します。', 'Shōkyaku de hiyō o heijunka shimasu.', 'A amortização dilui o custo.', 'Finanças'],
    ['担保', 'tanpo', 'garantia real', 'substantivo', '家を担保にしました。', 'Ie o tanpo ni shimashita.', 'A casa serviu de garantia.', 'Finanças'],
    ['利回り', 'rimawari', 'rendimento', 'substantivo', '利回りがインフレを下回りました。', 'Rimawari ga infure o shitamawarimashita.', 'O rendimento ficou abaixo da inflação.', 'Finanças'],
    ['支払能力', 'shiharai nouryoku', 'solvência', 'substantivo', '支払能力と流動性は別です。', 'Shiharai nōryoku to ryūdōsei wa betsu desu.', 'Solvência e liquidez são coisas distintas.', 'Finanças'],
    ['締め付けトルク', 'shimetsuke toruku', 'torque de aperto', 'substantivo', '締め付けトルクを確認してください。', 'Shimetsuke toruku o kakunin shite kudasai.', 'Confira o torque de aperto.', 'Engenharia'],
    ['合金', 'goukin', 'liga metálica', 'substantivo', 'この合金は腐食に強いです。', 'Kono gōkin wa fushoku ni tsuyoi desu.', 'Esta liga resiste à corrosão.', 'Engenharia'],
    ['回路', 'kairo', 'circuito', 'substantivo', '回路が過熱しました。', 'Kairo ga kanetsu shimashita.', 'O circuito superaqueceu.', 'Engenharia'],
    ['寸法公差', 'sunpou kousa', 'tolerância dimensional', 'substantivo', '寸法公差は一ミリです。', 'Sunpō kōsa wa ichimiri desu.', 'A tolerância dimensional é de um milímetro.', 'Engenharia'],
    ['校正', 'kousei', 'calibração', 'substantivo', '校正がずれました。', 'Kōsei ga zuremashita.', 'A calibração se desviou.', 'Engenharia'],
    ['摩擦', 'masatsu', 'atrito', 'substantivo', '摩擦で部品がすり減ります。', 'Masatsu de buhin ga suriherimasu.', 'O atrito desgasta a peça.', 'Engenharia'],
    ['熱の', 'netsu no', 'térmico', 'adjetivo', '熱の膨張でひびが入りました。', 'Netsu no bōchō de hibi ga hairimashita.', 'A dilatação térmica trincou a peça.', 'Engenharia'],
    ['油圧の', 'yuatsu no', 'hidráulico', 'adjetivo', '油圧の系統が故障しました。', 'Yuatsu no keitō ga koshō shimashita.', 'O sistema hidráulico falhou.', 'Engenharia'],
    ['溶接', 'yousetsu', 'solda', 'substantivo', '溶接は持ちこたえました。', 'Yōsetsu wa mochikotaemashita.', 'A solda aguentou.', 'Engenharia'],
    ['荷重', 'kajuu', 'carga estrutural', 'substantivo', '梁が荷重を受けます。', 'Hari ga kajū o ukemasu.', 'A viga recebe a carga.', 'Engenharia'],
  ],
  C2: [
    ['覇権', 'haken', 'hegemonia', 'substantivo', 'その覇権は誰にも挑まれませんでした。', 'Sono haken wa dare ni mo idomaremasen deshita.', 'Aquela hegemonia não foi contestada.', 'Filosofia política'],
    ['正統性', 'seitousei', 'legitimidade', 'substantivo', '投票が正統性を取り戻しました。', 'Tōhyō ga seitōsei o torimodoshimashita.', 'A votação recuperou a legitimidade.', 'Filosofia política'],
    ['大衆迎合主義', 'taishuu geigou shugi', 'populismo', 'substantivo', '大衆迎合主義は不満を糧にします。', 'Taishū geigō shugi wa fuman o kate ni shimasu.', 'O populismo se alimenta do descontentamento.', 'Filosofia política'],
    ['能力主義', 'nouryoku shugi', 'meritocracia', 'substantivo', '能力主義は公平な出発を前提とします。', 'Nōryoku shugi wa kōhei na shuppatsu o zentei to shimasu.', 'A meritocracia pressupõe largada justa.', 'Filosofia política'],
    ['平等主義の', 'byoudou shugi no', 'igualitário', 'adjetivo', '平等主義の提案です。', 'Byōdō shugi no teian desu.', 'É uma proposta igualitária.', 'Filosofia política'],
    ['権威主義の', 'ken’i shugi no', 'autoritário', 'adjetivo', '権威主義の転換でした。', 'Ken’i shugi no tenkan deshita.', 'Foi uma guinada autoritária.', 'Filosofia política'],
    ['多元主義', 'tagen shugi', 'pluralismo', 'substantivo', '多元主義には本物の異論が要ります。', 'Tagen shugi ni wa honmono no iron ga irimasu.', 'O pluralismo exige dissenso real.', 'Filosofia política'],
    ['補完性原理', 'hokansei genri', 'princípio da subsidiariedade', 'substantivo', '補完性原理は決定を現場に近づけます。', 'Hokansei genri wa kettei o genba ni chikazukemasu.', 'A subsidiariedade aproxima a decisão da ponta.', 'Filosofia política'],
    ['技術官僚支配', 'gijutsu kanryou shihai', 'tecnocracia', 'substantivo', '技術官僚支配は有権者を遠ざけます。', 'Gijutsu kanryō shihai wa yūkensha o tōzakemasu.', 'A tecnocracia afasta o eleitor.', 'Filosofia política'],
    ['統治術', 'touchijutsu', 'arte de governar', 'substantivo', 'それは見事な統治術でした。', 'Sore wa migoto na tōchijutsu deshita.', 'Aquilo foi arte de governar com maestria.', 'Filosofia política'],
    ['終止形', 'shuushikei', 'cadência (música)', 'substantivo', '終止形が楽句を締めます。', 'Shūshikei ga gakku o shimemasu.', 'A cadência fecha a frase musical.', 'Música e som'],
    ['音色', 'neiro', 'timbre', 'substantivo', 'その音色は聞けば分かります。', 'Sono neiro wa kikeba wakarimasu.', 'Esse timbre se reconhece de ouvido.', 'Música e som'],
    ['不協和音', 'fukyouwaon', 'dissonância', 'substantivo', '不協和音は意図的です。', 'Fukyōwaon wa itoteki desu.', 'A dissonância é proposital.', 'Música e som'],
    ['クレッシェンド', 'kuresshendo', 'crescendo', 'substantivo', 'クレッシェンドがゆっくり高まります。', 'Kuresshendo ga yukkuri takamarimasu.', 'O crescendo sobe devagar.', 'Música e som'],
    ['対位法', 'taiihou', 'contraponto', 'substantivo', '対位法が緻密です。', 'Taiihō ga chimitsu desu.', 'O contraponto é minucioso.', 'Música e som'],
    ['残響', 'zankyou', 'ressonância / reverberação', 'substantivo', 'このホールは残響が豊かです。', 'Kono hōru wa zankyō ga yutaka desu.', 'Esta sala tem reverberação rica.', 'Música e som'],
    ['スタッカート', 'sutakkaato', 'staccato', 'substantivo', 'スタッカートの部分が難しいです。', 'Sutakkāto no bubun ga muzukashii desu.', 'O trecho em staccato é difícil.', 'Música e som'],
    ['リフレイン', 'rifurein', 'refrão', 'substantivo', 'リフレインが四回繰り返されます。', 'Rifurein ga yonkai kurikaesaremasu.', 'O refrão se repete quatro vezes.', 'Música e som'],
    ['テンポ', 'tenpo', 'andamento', 'substantivo', 'ここでテンポが重くなります。', 'Koko de tenpo ga omoku narimasu.', 'Aqui o andamento fica pesado.', 'Música e som'],
    ['和声', 'wasei', 'harmonia', 'substantivo', '和声が急に変わります。', 'Wasei ga kyū ni kawarimasu.', 'A harmonia muda de repente.', 'Música e som'],
  ],
};
