/** Coreano — terceiro lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { AsianByLevel } from '../entry';

export const KO_THEMATIC3: AsianByLevel = {
  A1: [
    ['아들', 'adeul', 'filho', 'substantivo', '아들이 다섯 살이에요.', 'Adeuri daseot sarieyo.', 'Meu filho tem cinco anos.', 'Família e pessoas'],
    ['딸', 'ttal', 'filha', 'substantivo', '딸이 여기서 공부해요.', 'Ttari yeogiseo gongbuhaeyo.', 'Minha filha estuda aqui.', 'Família e pessoas'],
    ['할머니', 'halmeoni', 'avó', 'substantivo', '할머니는 요리를 잘하세요.', 'Halmeonineun yorireul jalhaseyo.', 'Minha avó cozinha bem.', 'Família e pessoas'],
    ['할아버지', 'harabeoji', 'avô', 'substantivo', '할아버지는 이야기를 잘하세요.', 'Harabeojineun iyagireul jalhaseyo.', 'Meu avô conta boas histórias.', 'Família e pessoas'],
    ['삼촌', 'samchon', 'tio', 'substantivo', '삼촌은 멀리 살아요.', 'Samchoneun meolli sarayo.', 'Meu tio mora longe.', 'Família e pessoas'],
    ['이모', 'imo', 'tia (materna)', 'substantivo', '이모는 간호사예요.', 'Imoneun ganhosayeyo.', 'Minha tia é enfermeira.', 'Família e pessoas'],
    ['사촌', 'sachon', 'primo', 'substantivo', '사촌은 저와 동갑이에요.', 'Sachoneun jeowa donggabieyo.', 'Meu primo tem a minha idade.', 'Família e pessoas'],
    ['아내', 'anae', 'esposa', 'substantivo', '아내는 시내에서 일해요.', 'Anaeneun sinaeeseo ilhaeyo.', 'Minha esposa trabalha no centro.', 'Família e pessoas'],
    ['남편', 'nampyeon', 'marido', 'substantivo', '남편은 선생님이에요.', 'Nampyeoneun seonsaengnimieyo.', 'Meu marido é professor.', 'Família e pessoas'],
    ['친구', 'chingu', 'amigo', 'substantivo', '그녀는 제일 친한 친구예요.', 'Geunyeoneun jeil chinhan chinguyeyo.', 'Ela é minha melhor amiga.', 'Família e pessoas'],
    ['방', 'bang', 'quarto / cômodo', 'substantivo', '이 방은 조용해요.', 'I bangeun joyonghaeyo.', 'Este quarto é silencioso.', 'Casa e cômodos'],
    ['거실', 'geosil', 'sala de estar', 'substantivo', '거실에서 텔레비전을 봐요.', 'Geosireseo tellebijeoneul bwayo.', 'Assistimos TV na sala de estar.', 'Casa e cômodos'],
    ['침실', 'chimsil', 'dormitório', 'substantivo', '침실은 위층이에요.', 'Chimsireun wicheungieyo.', 'O dormitório fica no andar de cima.', 'Casa e cômodos'],
    ['정원', 'jeongwon', 'jardim', 'substantivo', '정원에 물을 줘야 해요.', 'Jeongwone mureul jwoya haeyo.', 'O jardim precisa de água.', 'Casa e cômodos'],
    ['벽', 'byeok', 'parede', 'substantivo', '벽이 더러워요.', 'Byeogi deoreowoyo.', 'A parede está suja.', 'Casa e cômodos'],
    ['바닥', 'badak', 'chão', 'substantivo', '바닥이 젖었어요.', 'Badagi jeojeosseoyo.', 'O chão está molhado.', 'Casa e cômodos'],
    ['계단', 'gyedan', 'escada', 'substantivo', '계단이 가팔라요.', 'Gyedani gapallayo.', 'A escada é íngreme.', 'Casa e cômodos'],
    ['열쇠', 'yeolsoe', 'chave', 'substantivo', '열쇠를 잃어버렸어요.', 'Yeolsoereul ireobeoryeosseoyo.', 'Perdi a chave.', 'Casa e cômodos'],
    ['전등', 'jeondeung', 'luminária', 'substantivo', '전등을 켜 주세요.', 'Jeondeungeul kyeo juseyo.', 'Acenda a luminária.', 'Casa e cômodos'],
    ['차고', 'chago', 'garagem', 'substantivo', '차는 차고에 있어요.', 'Chaneun chagoe isseoyo.', 'O carro está na garagem.', 'Casa e cômodos'],
  ],
  A2: [
    ['허리띠', 'heoritti', 'cinto', 'substantivo', '이 허리띠는 너무 길어요.', 'I heorittineun neomu gireoyo.', 'Este cinto é comprido demais.', 'Vestuário e aparência'],
    ['목도리', 'mokdori', 'cachecol', 'substantivo', '추우니까 목도리를 하세요.', 'Chuunikka mokdorireul haseyo.', 'Está frio, use um cachecol.', 'Vestuário e aparência'],
    ['장갑', 'janggap', 'luva', 'substantivo', '장갑 한 짝을 잃어버렸어요.', 'Janggap han jjageul ireobeoryeosseoyo.', 'Perdi uma das luvas.', 'Vestuário e aparência'],
    ['부츠', 'bucheu', 'bota', 'substantivo', '이 부츠는 무거워요.', 'I bucheuneun mugeowoyo.', 'Estas botas são pesadas.', 'Vestuário e aparência'],
    ['소매', 'somae', 'manga (de roupa)', 'substantivo', '소매가 찢어졌어요.', 'Somaega jjijeojyeosseoyo.', 'A manga está rasgada.', 'Vestuário e aparência'],
    ['주머니', 'jumeoni', 'bolso', 'substantivo', '주머니 안에 있어요.', 'Jumeoni ane isseoyo.', 'Está no bolso.', 'Vestuário e aparência'],
    ['단추', 'danchu', 'botão', 'substantivo', '단추가 떨어졌어요.', 'Danchuga tteoreojyeosseoyo.', 'Caiu um botão.', 'Vestuário e aparência'],
    ['지퍼', 'jipeo', 'zíper', 'substantivo', '지퍼가 고장 났어요.', 'Jipeoga gojang nasseoyo.', 'O zíper quebrou.', 'Vestuário e aparência'],
    ['수염', 'suyeom', 'barba', 'substantivo', '수염을 길렀어요.', 'Suyeomeul gilleosseoyo.', 'Ele deixou a barba crescer.', 'Vestuário e aparência'],
    ['화장', 'hwajang', 'maquiagem', 'substantivo', '화장을 옅게 해요.', 'Hwajangeul yeotge haeyo.', 'Ela usa maquiagem leve.', 'Vestuário e aparência'],
    ['생일', 'saengil', 'aniversário', 'substantivo', '오늘은 제 생일이에요.', 'Oneureun je saengirieyo.', 'Hoje é meu aniversário.', 'Datas e festas'],
    ['공휴일', 'gonghyuil', 'feriado', 'substantivo', '월요일은 공휴일이에요.', 'Woryoireun gonghyuirieyo.', 'Segunda é feriado.', 'Datas e festas'],
    ['결혼식', 'gyeolhonsik', 'casamento (cerimônia)', 'substantivo', '결혼식은 유월이에요.', 'Gyeolhonsigeun yuworieyo.', 'O casamento é em junho.', 'Datas e festas'],
    ['선물', 'seonmul', 'presente', 'substantivo', '선물 고맙습니다.', 'Seonmul gomapseumnida.', 'Obrigado pelo presente.', 'Datas e festas'],
    ['파티', 'pati', 'festa', 'substantivo', '파티는 아홉 시에 시작해요.', 'Patineun ahop sie sijakaeyo.', 'A festa começa às nove.', 'Datas e festas'],
    ['양초', 'yangcho', 'vela', 'substantivo', '양초에 불을 켜세요.', 'Yangchoe bureul kyeoseyo.', 'Acenda as velas.', 'Datas e festas'],
    ['초대장', 'chodaejang', 'convite', 'substantivo', '초대장을 받았어요.', 'Chodaejangeul badasseoyo.', 'Recebi o convite.', 'Datas e festas'],
    ['기념일', 'ginyeomil', 'data comemorativa', 'substantivo', '열 번째 기념일이에요.', 'Yeol beonjjae ginyeomirieyo.', 'É o décimo aniversário.', 'Datas e festas'],
    ['축하하다', 'chukhahada', 'comemorar / parabenizar', 'verbo', '토요일에 축하해요.', 'Toyoire chukhahaeyo.', 'Comemoramos no sábado.', 'Datas e festas'],
    ['하객', 'hagaek', 'convidado (de cerimônia)', 'substantivo', '하객이 스무 명 와요.', 'Hagaegi seumu myeong wayo.', 'Vêm vinte convidados.', 'Datas e festas'],
  ],
  B1: [
    ['학위', 'hagwi', 'diploma / título', 'substantivo', '그녀는 법학 학위가 있어요.', 'Geunyeoneun beophak hagwiga isseoyo.', 'Ela tem diploma em direito.', 'Educação superior'],
    ['논문', 'nonmun', 'tese / artigo acadêmico', 'substantivo', '논문을 쓰고 있어요.', 'Nonmuneul sseugo isseoyo.', 'Ele está escrevendo a tese.', 'Educação superior'],
    ['강의', 'gangui', 'aula expositiva', 'substantivo', '강의가 두 시간 걸렸어요.', 'Ganguiga du sigan geollyeosseoyo.', 'A aula durou duas horas.', 'Educação superior'],
    ['교수', 'gyosu', 'professor universitário', 'substantivo', '교수가 책을 냈어요.', 'Gyosuga chaegeul naesseoyo.', 'O professor publicou um livro.', 'Educação superior'],
    ['캠퍼스', 'kaempeoseu', 'campus', 'substantivo', '캠퍼스가 아주 넓어요.', 'Kaempeoseuga aju neolbeoyo.', 'O campus é muito grande.', 'Educação superior'],
    ['학기', 'hakgi', 'semestre', 'substantivo', '학기는 칠월에 끝나요.', 'Hakgineun chirwore kkeutnayo.', 'O semestre acaba em julho.', 'Educação superior'],
    ['등록하다', 'deungnokhada', 'matricular-se', 'verbo', '다음 달에 등록해요.', 'Daeum dare deungnokaeyo.', 'Vou me matricular mês que vem.', 'Educação superior'],
    ['기숙사', 'gisuksa', 'alojamento estudantil', 'substantivo', '기숙사에 살아요.', 'Gisuksae sarayo.', 'Ela mora no alojamento.', 'Educação superior'],
    ['졸업하다', 'joreophada', 'formar-se', 'verbo', '십이월에 졸업해요.', 'Sibiwore joreophaeyo.', 'Eles se formam em dezembro.', 'Educação superior'],
    ['세미나', 'semina', 'seminário', 'substantivo', '세미나는 소규모였어요.', 'Seminaneun sogyumoyeosseoyo.', 'O seminário era pequeno.', 'Educação superior'],
    ['게스트하우스', 'geseuteuhauseu', 'albergue', 'substantivo', '게스트하우스에 묵었어요.', 'Geseuteuhauseue mugeosseoyo.', 'Ficamos num albergue.', 'Viagem e hospedagem'],
    ['숙소 예약', 'sukso yeyak', 'reserva de hospedagem', 'substantivo', '숙소 예약이 취소됐어요.', 'Sukso yeyagi chwisodwaesseoyo.', 'A reserva foi cancelada.', 'Viagem e hospedagem'],
    ['체크인', 'chekeuin', 'check-in', 'substantivo', '체크인은 두 시부터예요.', 'Chekeuineun du sibuteoyeyo.', 'O check-in é a partir das duas.', 'Viagem e hospedagem'],
    ['접수원', 'jeopsuwon', 'recepcionista', 'substantivo', '접수원에게 물어보세요.', 'Jeopsuwonege mureoboseyo.', 'Pergunte ao recepcionista.', 'Viagem e hospedagem'],
    ['호텔 로비', 'hotel robi', 'saguão do hotel', 'substantivo', '호텔 로비에서 기다려 주세요.', 'Hotel robieseo gidaryeo juseyo.', 'Me espere no saguão do hotel.', 'Viagem e hospedagem'],
    ['명소', 'myeongso', 'ponto turístico', 'substantivo', '저 탑은 명소예요.', 'Jeo tabeun myeongsoyeyo.', 'Aquela torre é um ponto turístico.', 'Viagem e hospedagem'],
    ['기념품', 'ginyeompum', 'lembrança de viagem', 'substantivo', '기념품을 샀어요.', 'Ginyeompumeul sasseoyo.', 'Comprei uma lembrança.', 'Viagem e hospedagem'],
    ['여행 안내서', 'yeohaeng annaeseo', 'guia de viagem', 'substantivo', '여행 안내서가 오래됐어요.', 'Yeohaeng annaeseoga oraedwaesseoyo.', 'O guia de viagem está velho.', 'Viagem e hospedagem'],
    ['비자', 'bija', 'visto', 'substantivo', '비자가 필요해요.', 'Bijaga piryohaeyo.', 'Preciso de visto.', 'Viagem e hospedagem'],
    ['관광객', 'gwangwanggaek', 'turista', 'substantivo', '도시가 관광객으로 붐벼요.', 'Dosiga gwangwanggaegeuro bumbyeoyo.', 'A cidade está cheia de turistas.', 'Viagem e hospedagem'],
  ],
  B2: [
    ['알고리즘', 'algorijeum', 'algoritmo', 'substantivo', '알고리즘이 결과를 정렬해요.', 'Algorijeumi gyeolgwareul jeongnyeolhaeyo.', 'O algoritmo ordena os resultados.', 'Tecnologia avançada'],
    ['암호화', 'amhohwa', 'criptografia', 'substantivo', '암호화가 자료를 보호해요.', 'Amhohwaga jaryoreul bohohaeyo.', 'A criptografia protege os dados.', 'Tecnologia avançada'],
    ['대역폭', 'daeyeokpok', 'largura de banda', 'substantivo', '대역폭이 부족해요.', 'Daeyeokpogi bujokaeyo.', 'A largura de banda é insuficiente.', 'Tecnologia avançada'],
    ['서버', 'seobeo', 'servidor', 'substantivo', '서버가 다운됐어요.', 'Seobeoga daundwaesseoyo.', 'O servidor caiu.', 'Tecnologia avançada'],
    ['데이터베이스', 'deiteobeiseu', 'banco de dados', 'substantivo', '데이터베이스를 백업하세요.', 'Deiteobeiseureul baegeophaseyo.', 'Faça backup do banco de dados.', 'Tecnologia avançada'],
    ['인터페이스', 'inteopeiseu', 'interface', 'substantivo', '인터페이스가 헷갈려요.', 'Inteopeiseuga hetgallyeoyo.', 'A interface é confusa.', 'Tecnologia avançada'],
    ['자동화', 'jadonghwa', 'automação', 'substantivo', '자동화로 비용이 줄었어요.', 'Jadonghwaro biyongi jureosseoyo.', 'A automação reduziu custos.', 'Tecnologia avançada'],
    ['방화벽', 'banghwabyeok', 'firewall', 'substantivo', '방화벽이 차단했어요.', 'Banghwabyeogi chadanhaesseoyo.', 'O firewall bloqueou.', 'Tecnologia avançada'],
    ['시제품', 'sijepum', 'protótipo', 'substantivo', '시제품을 만들었어요.', 'Sijepumeul mandeureosseoyo.', 'Construímos um protótipo.', 'Tecnologia avançada'],
    ['지연 시간', 'jiyeon sigan', 'latência', 'substantivo', '지연 시간이 경험을 망쳐요.', 'Jiyeon sigani gyeongheomeul mangchyeoyo.', 'A latência estraga a experiência.', 'Tecnologia avançada'],
    ['광고', 'gwanggo', 'publicidade', 'substantivo', '광고가 매출을 끌어올렸어요.', 'Gwanggoga maechureul kkeureoollyeosseoyo.', 'A publicidade impulsionou as vendas.', 'Consumo e marketing'],
    ['소비자', 'sobija', 'consumidor', 'substantivo', '결정은 소비자가 해요.', 'Gyeoljeongeun sobijaga haeyo.', 'Quem decide é o consumidor.', 'Consumo e marketing'],
    ['소매업', 'somaeeop', 'varejo', 'substantivo', '소매업 마진이 얇아요.', 'Somaeeop majini yalbayo.', 'A margem do varejo é fina.', 'Consumo e marketing'],
    ['도매업', 'domaeeop', 'atacado', 'substantivo', '도매업에서 사들여요.', 'Domaeeobeseo sadeuryeoyo.', 'Eles compram no atacado.', 'Consumo e marketing'],
    ['포장', 'pojang', 'embalagem', 'substantivo', '포장이 과해요.', 'Pojangi gwahaeyo.', 'A embalagem é excessiva.', 'Consumo e marketing'],
    ['로고', 'rogo', 'logotipo', 'substantivo', '로고를 새로 만들었어요.', 'Rogoreul saero mandeureosseoyo.', 'Refizeram o logotipo.', 'Consumo e marketing'],
    ['광고 문구', 'gwanggo mungu', 'slogan', 'substantivo', '광고 문구가 잘 먹혔어요.', 'Gwanggo munguga jal meokyeosseoyo.', 'O slogan funcionou bem.', 'Consumo e marketing'],
    ['목표 고객', 'mokpyo gogaek', 'público-alvo', 'substantivo', '먼저 목표 고객을 정하세요.', 'Meonjeo mokpyo gogaegeul jeonghaseyo.', 'Defina o público-alvo primeiro.', 'Consumo e marketing'],
    ['광고 협찬', 'gwanggo hyeopchan', 'patrocínio publicitário', 'substantivo', '광고 협찬에 큰돈이 들었어요.', 'Gwanggo hyeopchane keundoni deureosseoyo.', 'O patrocínio custou caro.', 'Consumo e marketing'],
    ['이윤율', 'iyunyul', 'margem de lucro', 'substantivo', '이윤율이 너무 높아요.', 'Iyunyuri neomu nopayo.', 'A margem de lucro é alta demais.', 'Consumo e marketing'],
  ],
  C1: [
    ['자산', 'jasan', 'ativo (patrimônio)', 'substantivo', '자산 가치가 떨어졌어요.', 'Jasan gachiga tteoreojyeosseoyo.', 'O ativo perdeu valor.', 'Finanças'],
    ['자기자본', 'jagijabon', 'patrimônio líquido', 'substantivo', '자기자본이 줄었어요.', 'Jagijaboni jureosseoyo.', 'O patrimônio líquido encolheu.', 'Finanças'],
    ['배당금', 'baedanggeum', 'dividendo', 'substantivo', '배당금을 줄였어요.', 'Baedanggeumeul juryeosseoyo.', 'Cortaram o dividendo.', 'Finanças'],
    ['투자 포트폴리오', 'tuja poteupollio', 'carteira de investimentos', 'substantivo', '투자 포트폴리오를 분산하세요.', 'Tuja poteupollioreul bunsanhaseyo.', 'Diversifique a carteira.', 'Finanças'],
    ['위험 회피', 'wiheom hoepi', 'proteção contra risco', 'substantivo', '금은 위험 회피 수단이에요.', 'Geumeun wiheom hoepi sudanieyo.', 'O ouro é instrumento de proteção contra risco.', 'Finanças'],
    ['기업 가치 평가', 'gieop gachi pyeongga', 'avaliação de valor', 'substantivo', '기업 가치 평가가 부풀려졌어요.', 'Gieop gachi pyeonggaga bupullyeojyeosseoyo.', 'A avaliação está inflada.', 'Finanças'],
    ['상각', 'sanggak', 'amortização', 'substantivo', '상각으로 비용을 분산해요.', 'Sanggageuro biyongeul bunsanhaeyo.', 'A amortização dilui o custo.', 'Finanças'],
    ['담보', 'dambo', 'garantia real', 'substantivo', '집을 담보로 잡았어요.', 'Jibeul damboro jabasseoyo.', 'A casa serviu de garantia.', 'Finanças'],
    ['수익률', 'suingnyul', 'rentabilidade', 'substantivo', '수익률이 물가 상승률보다 낮아요.', 'Suingnyuri mulga sangseungnyulboda najayo.', 'A rentabilidade está abaixo da inflação.', 'Finanças'],
    ['지급 능력', 'jigeup neungnyeok', 'solvência', 'substantivo', '지급 능력과 유동성은 달라요.', 'Jigeup neungnyeokgwa yudongseongeun dallayo.', 'Solvência e liquidez são coisas distintas.', 'Finanças'],
    ['조임 토크', 'joim tokeu', 'torque de aperto', 'substantivo', '조임 토크를 확인하세요.', 'Joim tokeureul hwaginhaseyo.', 'Confira o torque de aperto.', 'Engenharia'],
    ['합금', 'hapgeum', 'liga metálica', 'substantivo', '이 합금은 부식에 강해요.', 'I hapgeumeun busige ganghaeyo.', 'Esta liga resiste à corrosão.', 'Engenharia'],
    ['회로', 'hoero', 'circuito', 'substantivo', '회로가 과열됐어요.', 'Hoeroga gwayeoldwaesseoyo.', 'O circuito superaqueceu.', 'Engenharia'],
    ['치수 공차', 'chisu gongcha', 'tolerância dimensional', 'substantivo', '치수 공차는 일 밀리미터예요.', 'Chisu gongchaneun il millimiteoyeyo.', 'A tolerância dimensional é de um milímetro.', 'Engenharia'],
    ['교정', 'gyojeong', 'calibração', 'substantivo', '교정이 어긋났어요.', 'Gyojeongi eogeutnasseoyo.', 'A calibração se desviou.', 'Engenharia'],
    ['마찰', 'machal', 'atrito', 'substantivo', '마찰로 부품이 닳아요.', 'Machallo bupumi dalayo.', 'O atrito desgasta a peça.', 'Engenharia'],
    ['열의', 'yeorui', 'térmico', 'adjetivo', '열의 팽창으로 금이 갔어요.', 'Yeorui paengchangeuro geumi gasseoyo.', 'A dilatação térmica trincou a peça.', 'Engenharia'],
    ['유압의', 'yuabui', 'hidráulico', 'adjetivo', '유압의 계통이 고장 났어요.', 'Yuabui gyetongi gojang nasseoyo.', 'O sistema hidráulico falhou.', 'Engenharia'],
    ['용접', 'yongjeop', 'solda', 'substantivo', '용접이 버텼어요.', 'Yongjeobi beotyeosseoyo.', 'A solda aguentou.', 'Engenharia'],
    ['하중', 'hajung', 'carga estrutural', 'substantivo', '들보가 하중을 받아요.', 'Deulboga hajungeul badayo.', 'A viga recebe a carga.', 'Engenharia'],
  ],
  C2: [
    ['패권', 'paegwon', 'hegemonia', 'substantivo', '그들의 패권은 도전받지 않았어요.', 'Geudeurui paegwoneun dojeonbatji anasseoyo.', 'A hegemonia deles não foi contestada.', 'Filosofia política'],
    ['정당성', 'jeongdangseong', 'legitimidade', 'substantivo', '투표가 정당성을 회복시켰어요.', 'Tupyoga jeongdangseongeul hoebokssikyeosseoyo.', 'A votação restaurou a legitimidade.', 'Filosofia política'],
    ['포퓰리즘', 'popyullijeum', 'populismo', 'substantivo', '포퓰리즘은 불만을 먹고 자라요.', 'Popyullijeumeun bulmaneul meokgo jarayo.', 'O populismo se alimenta do descontentamento.', 'Filosofia política'],
    ['능력주의', 'neungnyeokjuui', 'meritocracia', 'substantivo', '능력주의는 공정한 출발을 전제해요.', 'Neungnyeokjuuineun gongjeonghan chulbareul jeonjehaeyo.', 'A meritocracia pressupõe largada justa.', 'Filosofia política'],
    ['평등주의의', 'pyeongdeungjuuiui', 'igualitário', 'adjetivo', '평등주의의 제안이에요.', 'Pyeongdeungjuuiui jeanieyo.', 'É uma proposta igualitária.', 'Filosofia política'],
    ['권위주의의', 'gwonwijuuiui', 'autoritário', 'adjetivo', '권위주의의 전환이었어요.', 'Gwonwijuuiui jeonhwanieosseoyo.', 'Foi uma guinada autoritária.', 'Filosofia política'],
    ['다원주의', 'dawonjuui', 'pluralismo', 'substantivo', '다원주의는 진짜 이견이 필요해요.', 'Dawonjuuineun jinjja igyeoni piryohaeyo.', 'O pluralismo exige dissenso real.', 'Filosofia política'],
    ['보충성 원칙', 'bochungseong wonchik', 'princípio da subsidiariedade', 'substantivo', '보충성 원칙은 결정을 아래로 내려요.', 'Bochungseong wonchigeun gyeoljeongeul araero naeryeoyo.', 'A subsidiariedade desce as decisões.', 'Filosofia política'],
    ['기술관료주의', 'gisulgwallyojuui', 'tecnocracia', 'substantivo', '기술관료주의는 유권자를 밀어내요.', 'Gisulgwallyojuuineun yugwonjareul mireonaeyo.', 'A tecnocracia afasta o eleitor.', 'Filosofia política'],
    ['통치술', 'tongchisul', 'arte de governar', 'substantivo', '그것은 뛰어난 통치술이었어요.', 'Geugeoseun ttwieonan tongchisurieosseoyo.', 'Aquilo foi arte de governar com maestria.', 'Filosofia política'],
    ['종지형', 'jongjihyeong', 'cadência (música)', 'substantivo', '종지형이 악구를 마무리해요.', 'Jongjihyeongi akgureul mamurihaeyo.', 'A cadência fecha a frase musical.', 'Música e som'],
    ['음색', 'eumsaek', 'timbre', 'substantivo', '그 음색은 단번에 알아요.', 'Geu eumsaegeun danbeone arayo.', 'Esse timbre se reconhece na hora.', 'Música e som'],
    ['불협화음', 'bulhyeophwaeum', 'dissonância', 'substantivo', '불협화음은 의도된 거예요.', 'Bulhyeophwaeumeun uidodoen geoyeyo.', 'A dissonância é proposital.', 'Música e som'],
    ['크레셴도', 'keuresyendo', 'crescendo', 'substantivo', '크레셴도가 천천히 쌓여요.', 'Keuresyendoga cheoncheonhi ssayeoyo.', 'O crescendo se constrói devagar.', 'Música e som'],
    ['대위법', 'daewibeop', 'contraponto', 'substantivo', '대위법이 정교해요.', 'Daewibeobi jeonggyohaeyo.', 'O contraponto é elaborado.', 'Música e som'],
    ['잔향', 'janhyang', 'reverberação', 'substantivo', '이 홀은 잔향이 풍부해요.', 'I horeun janhyangi pungbuhaeyo.', 'Esta sala tem reverberação rica.', 'Música e som'],
    ['스타카토', 'seutakato', 'staccato', 'substantivo', '스타카토 부분이 까다로워요.', 'Seutakato bubuni kkadarowoyo.', 'O trecho em staccato é difícil.', 'Música e som'],
    ['후렴', 'huryeom', 'refrão', 'substantivo', '후렴이 네 번 반복돼요.', 'Huryeomi ne beon banbokdwaeyo.', 'O refrão se repete quatro vezes.', 'Música e som'],
    ['빠르기', 'ppareugi', 'andamento', 'substantivo', '여기서 빠르기가 늘어져요.', 'Yeogiseo ppareugiga neureojyeoyo.', 'Aqui o andamento se arrasta.', 'Música e som'],
    ['화성', 'hwaseong', 'harmonia', 'substantivo', '화성이 갑자기 바뀌어요.', 'Hwaseongi gapjagi bakkwieoyo.', 'A harmonia muda de repente.', 'Música e som'],
  ],
};
