/** Mandarim — terceiro lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { AsianByLevel } from '../entry';

export const ZH_THEMATIC3: AsianByLevel = {
  A1: [
    ['儿子', 'érzi', 'filho', 'substantivo', '我儿子五岁。', 'Wǒ érzi wǔ suì.', 'Meu filho tem cinco anos.', 'Família e pessoas'],
    ['女儿', 'nǚ’ér', 'filha', 'substantivo', '她女儿在这里读书。', 'Tā nǚ’ér zài zhèlǐ dúshū.', 'A filha dela estuda aqui.', 'Família e pessoas'],
    ['奶奶', 'nǎinai', 'avó', 'substantivo', '我奶奶做饭很好吃。', 'Wǒ nǎinai zuò fàn hěn hǎochī.', 'Minha avó cozinha muito bem.', 'Família e pessoas'],
    ['爷爷', 'yéye', 'avô', 'substantivo', '我爷爷会讲故事。', 'Wǒ yéye huì jiǎng gùshi.', 'Meu avô sabe contar histórias.', 'Família e pessoas'],
    ['叔叔', 'shūshu', 'tio', 'substantivo', '我叔叔住得很远。', 'Wǒ shūshu zhù de hěn yuǎn.', 'Meu tio mora longe.', 'Família e pessoas'],
    ['阿姨', 'āyí', 'tia', 'substantivo', '我阿姨是护士。', 'Wǒ āyí shì hùshi.', 'Minha tia é enfermeira.', 'Família e pessoas'],
    ['表哥', 'biǎogē', 'primo (mais velho)', 'substantivo', '我表哥和我同岁。', 'Wǒ biǎogē hé wǒ tóngsuì.', 'Meu primo tem a minha idade.', 'Família e pessoas'],
    ['妻子', 'qīzi', 'esposa', 'substantivo', '他妻子在市区工作。', 'Tā qīzi zài shìqū gōngzuò.', 'A esposa dele trabalha no centro.', 'Família e pessoas'],
    ['丈夫', 'zhàngfu', 'marido', 'substantivo', '她丈夫是老师。', 'Tā zhàngfu shì lǎoshī.', 'O marido dela é professor.', 'Família e pessoas'],
    ['朋友', 'péngyou', 'amigo', 'substantivo', '她是我最好的朋友。', 'Tā shì wǒ zuì hǎo de péngyou.', 'Ela é minha melhor amiga.', 'Família e pessoas'],
    ['房间', 'fángjiān', 'quarto / cômodo', 'substantivo', '这个房间很安静。', 'Zhège fángjiān hěn ānjìng.', 'Este quarto é silencioso.', 'Casa e cômodos'],
    ['客厅', 'kètīng', 'sala de estar', 'substantivo', '我们在客厅看电视。', 'Wǒmen zài kètīng kàn diànshì.', 'Assistimos TV na sala de estar.', 'Casa e cômodos'],
    ['卧室', 'wòshì', 'dormitório', 'substantivo', '卧室在楼上。', 'Wòshì zài lóushàng.', 'O dormitório fica no andar de cima.', 'Casa e cômodos'],
    ['花园', 'huāyuán', 'jardim', 'substantivo', '花园需要浇水。', 'Huāyuán xūyào jiāo shuǐ.', 'O jardim precisa de água.', 'Casa e cômodos'],
    ['墙', 'qiáng', 'parede', 'substantivo', '墙很脏。', 'Qiáng hěn zāng.', 'A parede está suja.', 'Casa e cômodos'],
    ['地板', 'dìbǎn', 'chão / piso', 'substantivo', '地板是湿的。', 'Dìbǎn shì shī de.', 'O chão está molhado.', 'Casa e cômodos'],
    ['楼梯', 'lóutī', 'escada', 'substantivo', '楼梯很陡。', 'Lóutī hěn dǒu.', 'A escada é íngreme.', 'Casa e cômodos'],
    ['钥匙', 'yàoshi', 'chave', 'substantivo', '我把钥匙弄丢了。', 'Wǒ bǎ yàoshi nòngdiū le.', 'Perdi a chave.', 'Casa e cômodos'],
    ['台灯', 'táidēng', 'luminária de mesa', 'substantivo', '请打开台灯。', 'Qǐng dǎkāi táidēng.', 'Acenda a luminária.', 'Casa e cômodos'],
    ['车库', 'chēkù', 'garagem', 'substantivo', '车在车库里。', 'Chē zài chēkù lǐ.', 'O carro está na garagem.', 'Casa e cômodos'],
  ],
  A2: [
    ['腰带', 'yāodài', 'cinto', 'substantivo', '这条腰带太长了。', 'Zhè tiáo yāodài tài cháng le.', 'Este cinto é comprido demais.', 'Vestuário e aparência'],
    ['围巾', 'wéijīn', 'cachecol', 'substantivo', '天冷，戴条围巾吧。', 'Tiān lěng, dài tiáo wéijīn ba.', 'Está frio, use um cachecol.', 'Vestuário e aparência'],
    ['手套', 'shǒutào', 'luva', 'substantivo', '我丢了一只手套。', 'Wǒ diū le yì zhī shǒutào.', 'Perdi uma luva.', 'Vestuário e aparência'],
    ['靴子', 'xuēzi', 'bota', 'substantivo', '这双靴子很重。', 'Zhè shuāng xuēzi hěn zhòng.', 'Estas botas são pesadas.', 'Vestuário e aparência'],
    ['袖子', 'xiùzi', 'manga (de roupa)', 'substantivo', '袖子破了。', 'Xiùzi pò le.', 'A manga rasgou.', 'Vestuário e aparência'],
    ['口袋', 'kǒudài', 'bolso', 'substantivo', '在我口袋里。', 'Zài wǒ kǒudài lǐ.', 'Está no meu bolso.', 'Vestuário e aparência'],
    ['扣子', 'kòuzi', 'botão', 'substantivo', '掉了一颗扣子。', 'Diào le yì kē kòuzi.', 'Caiu um botão.', 'Vestuário e aparência'],
    ['拉链', 'lāliàn', 'zíper', 'substantivo', '拉链坏了。', 'Lāliàn huài le.', 'O zíper quebrou.', 'Vestuário e aparência'],
    ['胡子', 'húzi', 'barba', 'substantivo', '他留了胡子。', 'Tā liú le húzi.', 'Ele deixou a barba crescer.', 'Vestuário e aparência'],
    ['化妆', 'huàzhuāng', 'maquiagem', 'substantivo', '她化妆很淡。', 'Tā huàzhuāng hěn dàn.', 'A maquiagem dela é leve.', 'Vestuário e aparência'],
    ['生日', 'shēngrì', 'aniversário', 'substantivo', '今天是我的生日。', 'Jīntiān shì wǒ de shēngrì.', 'Hoje é meu aniversário.', 'Datas e festas'],
    ['假日', 'jiàrì', 'feriado', 'substantivo', '星期一是假日。', 'Xīngqīyī shì jiàrì.', 'Segunda é feriado.', 'Datas e festas'],
    ['婚礼', 'hūnlǐ', 'casamento (cerimônia)', 'substantivo', '婚礼在六月。', 'Hūnlǐ zài liùyuè.', 'O casamento é em junho.', 'Datas e festas'],
    ['礼物', 'lǐwù', 'presente', 'substantivo', '谢谢你的礼物。', 'Xièxie nǐ de lǐwù.', 'Obrigado pelo presente.', 'Datas e festas'],
    ['聚会', 'jùhuì', 'festa / reunião', 'substantivo', '聚会九点开始。', 'Jùhuì jiǔ diǎn kāishǐ.', 'A festa começa às nove.', 'Datas e festas'],
    ['蜡烛', 'làzhú', 'vela', 'substantivo', '把蜡烛点上。', 'Bǎ làzhú diǎn shàng.', 'Acenda as velas.', 'Datas e festas'],
    ['请柬', 'qǐngjiǎn', 'convite', 'substantivo', '我收到请柬了。', 'Wǒ shōudào qǐngjiǎn le.', 'Recebi o convite.', 'Datas e festas'],
    ['纪念日', 'jìniànrì', 'data comemorativa', 'substantivo', '这是我们第十个纪念日。', 'Zhè shì wǒmen dì shí gè jìniànrì.', 'É nosso décimo aniversário.', 'Datas e festas'],
    ['庆祝', 'qìngzhù', 'comemorar', 'verbo', '我们星期六庆祝。', 'Wǒmen xīngqīliù qìngzhù.', 'Comemoramos no sábado.', 'Datas e festas'],
    ['宾客', 'bīnkè', 'convidado', 'substantivo', '来了二十位宾客。', 'Lái le èrshí wèi bīnkè.', 'Vieram vinte convidados.', 'Datas e festas'],
  ],
  B1: [
    ['学位', 'xuéwèi', 'diploma / título', 'substantivo', '她有法学学位。', 'Tā yǒu fǎxué xuéwèi.', 'Ela tem diploma em direito.', 'Educação superior'],
    ['论文', 'lùnwén', 'tese / artigo acadêmico', 'substantivo', '他在写论文。', 'Tā zài xiě lùnwén.', 'Ele está escrevendo a tese.', 'Educação superior'],
    ['讲座', 'jiǎngzuò', 'palestra', 'substantivo', '讲座持续了两个小时。', 'Jiǎngzuò chíxù le liǎng gè xiǎoshí.', 'A palestra durou duas horas.', 'Educação superior'],
    ['教授', 'jiàoshòu', 'professor universitário', 'substantivo', '教授出版了一本书。', 'Jiàoshòu chūbǎn le yì běn shū.', 'O professor publicou um livro.', 'Educação superior'],
    ['校园', 'xiàoyuán', 'campus', 'substantivo', '校园非常大。', 'Xiàoyuán fēicháng dà.', 'O campus é enorme.', 'Educação superior'],
    ['学期', 'xuéqī', 'semestre', 'substantivo', '学期七月结束。', 'Xuéqī qīyuè jiéshù.', 'O semestre acaba em julho.', 'Educação superior'],
    ['注册', 'zhùcè', 'matricular-se', 'verbo', '我下个月注册。', 'Wǒ xià gè yuè zhùcè.', 'Vou me matricular mês que vem.', 'Educação superior'],
    ['宿舍', 'sùshè', 'alojamento estudantil', 'substantivo', '她住在宿舍。', 'Tā zhù zài sùshè.', 'Ela mora no alojamento.', 'Educação superior'],
    ['毕业', 'bìyè', 'formar-se', 'verbo', '他们十二月毕业。', 'Tāmen shí’èr yuè bìyè.', 'Eles se formam em dezembro.', 'Educação superior'],
    ['研讨课', 'yántǎokè', 'seminário', 'substantivo', '研讨课人很少。', 'Yántǎokè rén hěn shǎo.', 'O seminário tinha poucas pessoas.', 'Educação superior'],
    ['青年旅舍', 'qīngnián lǚshè', 'albergue', 'substantivo', '我们住在青年旅舍。', 'Wǒmen zhù zài qīngnián lǚshè.', 'Ficamos num albergue.', 'Viagem e hospedagem'],
    ['住宿预订', 'zhùsù yùdìng', 'reserva de hospedagem', 'substantivo', '住宿预订被取消了。', 'Zhùsù yùdìng bèi qǔxiāo le.', 'A reserva foi cancelada.', 'Viagem e hospedagem'],
    ['入住', 'rùzhù', 'fazer check-in', 'verbo', '两点开始入住。', 'Liǎng diǎn kāishǐ rùzhù.', 'O check-in começa às duas.', 'Viagem e hospedagem'],
    ['接待员', 'jiēdàiyuán', 'recepcionista', 'substantivo', '问一下接待员。', 'Wèn yíxià jiēdàiyuán.', 'Pergunte ao recepcionista.', 'Viagem e hospedagem'],
    ['大堂', 'dàtáng', 'saguão', 'substantivo', '在大堂等我。', 'Zài dàtáng děng wǒ.', 'Me espere no saguão.', 'Viagem e hospedagem'],
    ['地标', 'dìbiāo', 'marco / ponto turístico', 'substantivo', '那座塔是地标。', 'Nà zuò tǎ shì dìbiāo.', 'Aquela torre é um marco.', 'Viagem e hospedagem'],
    ['纪念品', 'jìniànpǐn', 'lembrança de viagem', 'substantivo', '我买了纪念品。', 'Wǒ mǎi le jìniànpǐn.', 'Comprei uma lembrança.', 'Viagem e hospedagem'],
    ['旅游指南', 'lǚyóu zhǐnán', 'guia de viagem', 'substantivo', '旅游指南过时了。', 'Lǚyóu zhǐnán guòshí le.', 'O guia de viagem está desatualizado.', 'Viagem e hospedagem'],
    ['签证', 'qiānzhèng', 'visto', 'substantivo', '我需要签证。', 'Wǒ xūyào qiānzhèng.', 'Preciso de visto.', 'Viagem e hospedagem'],
    ['游客', 'yóukè', 'turista', 'substantivo', '城里满是游客。', 'Chéng lǐ mǎn shì yóukè.', 'A cidade está cheia de turistas.', 'Viagem e hospedagem'],
  ],
  B2: [
    ['算法', 'suànfǎ', 'algoritmo', 'substantivo', '算法给结果排序。', 'Suànfǎ gěi jiéguǒ páixù.', 'O algoritmo ordena os resultados.', 'Tecnologia avançada'],
    ['加密', 'jiāmì', 'criptografia', 'substantivo', '加密保护数据。', 'Jiāmì bǎohù shùjù.', 'A criptografia protege os dados.', 'Tecnologia avançada'],
    ['带宽', 'dàikuān', 'largura de banda', 'substantivo', '带宽不够了。', 'Dàikuān búgòu le.', 'A largura de banda acabou.', 'Tecnologia avançada'],
    ['服务器', 'fúwùqì', 'servidor', 'substantivo', '服务器宕机了。', 'Fúwùqì dàngjī le.', 'O servidor caiu.', 'Tecnologia avançada'],
    ['数据库', 'shùjùkù', 'banco de dados', 'substantivo', '请备份数据库。', 'Qǐng bèifèn shùjùkù.', 'Faça backup do banco de dados.', 'Tecnologia avançada'],
    ['界面', 'jièmiàn', 'interface', 'substantivo', '界面让人困惑。', 'Jièmiàn ràng rén kùnhuò.', 'A interface confunde.', 'Tecnologia avançada'],
    ['自动化', 'zìdònghuà', 'automação', 'substantivo', '自动化降低了成本。', 'Zìdònghuà jiàngdī le chéngběn.', 'A automação baixou os custos.', 'Tecnologia avançada'],
    ['防火墙', 'fánghuǒqiáng', 'firewall', 'substantivo', '防火墙拦住了它。', 'Fánghuǒqiáng lánzhù le tā.', 'O firewall bloqueou.', 'Tecnologia avançada'],
    ['样机', 'yàngjī', 'protótipo', 'substantivo', '我们做了一台样机。', 'Wǒmen zuò le yì tái yàngjī.', 'Fizemos um protótipo.', 'Tecnologia avançada'],
    ['延迟', 'yánchí', 'latência', 'substantivo', '延迟毁了体验。', 'Yánchí huǐ le tǐyàn.', 'A latência arruinou a experiência.', 'Tecnologia avançada'],
    ['广告宣传', 'guǎnggào xuānchuán', 'publicidade', 'substantivo', '广告宣传拉动了销量。', 'Guǎnggào xuānchuán lādòng le xiāoliàng.', 'A publicidade impulsionou as vendas.', 'Consumo e marketing'],
    ['消费者', 'xiāofèizhě', 'consumidor', 'substantivo', '决定权在消费者。', 'Juédìngquán zài xiāofèizhě.', 'A decisão é do consumidor.', 'Consumo e marketing'],
    ['零售', 'língshòu', 'varejo', 'substantivo', '零售利润很薄。', 'Língshòu lìrùn hěn bó.', 'O lucro do varejo é fino.', 'Consumo e marketing'],
    ['批发', 'pīfā', 'atacado', 'substantivo', '他们从批发进货。', 'Tāmen cóng pīfā jìnhuò.', 'Eles compram no atacado.', 'Consumo e marketing'],
    ['包装', 'bāozhuāng', 'embalagem', 'substantivo', '包装太浪费了。', 'Bāozhuāng tài làngfèi le.', 'A embalagem é um desperdício.', 'Consumo e marketing'],
    ['标识', 'biāozhì', 'logotipo / identificação visual', 'substantivo', '标识重新设计了。', 'Biāozhì chóngxīn shèjì le.', 'O logotipo foi redesenhado.', 'Consumo e marketing'],
    ['口号', 'kǒuhào', 'slogan', 'substantivo', '这个口号很响亮。', 'Zhège kǒuhào hěn xiǎngliàng.', 'Este slogan é marcante.', 'Consumo e marketing'],
    ['目标受众', 'mùbiāo shòuzhòng', 'público-alvo', 'substantivo', '先确定目标受众。', 'Xiān quèdìng mùbiāo shòuzhòng.', 'Defina o público-alvo primeiro.', 'Consumo e marketing'],
    ['代言', 'dàiyán', 'aval publicitário', 'substantivo', '代言花了一大笔钱。', 'Dàiyán huā le yí dà bǐ qián.', 'O aval publicitário custou caro.', 'Consumo e marketing'],
    ['加价幅度', 'jiājià fúdù', 'margem de lucro', 'substantivo', '加价幅度太高了。', 'Jiājià fúdù tài gāo le.', 'A margem de lucro é alta demais.', 'Consumo e marketing'],
  ],
  C1: [
    ['资产', 'zīchǎn', 'ativo (patrimônio)', 'substantivo', '资产贬值了。', 'Zīchǎn biǎnzhí le.', 'O ativo desvalorizou.', 'Finanças'],
    ['股东权益', 'gǔdōng quányì', 'patrimônio líquido', 'substantivo', '股东权益缩水了。', 'Gǔdōng quányì suōshuǐ le.', 'O patrimônio líquido encolheu.', 'Finanças'],
    ['股息', 'gǔxī', 'dividendo', 'substantivo', '他们削减了股息。', 'Tāmen xuējiǎn le gǔxī.', 'Cortaram o dividendo.', 'Finanças'],
    ['投资组合', 'tóuzī zǔhé', 'carteira de investimentos', 'substantivo', '请分散投资组合。', 'Qǐng fēnsàn tóuzī zǔhé.', 'Diversifique a carteira.', 'Finanças'],
    ['风险对冲', 'fēngxiǎn duìchōng', 'proteção contra risco', 'substantivo', '黄金可作风险对冲。', 'Huángjīn kě zuò fēngxiǎn duìchōng.', 'O ouro serve de proteção contra risco.', 'Finanças'],
    ['估值', 'gūzhí', 'avaliação de valor', 'substantivo', '估值显得虚高。', 'Gūzhí xiǎnde xūgāo.', 'A avaliação parece inflada.', 'Finanças'],
    ['摊销', 'tānxiāo', 'amortização', 'substantivo', '摊销把成本分摊开。', 'Tānxiāo bǎ chéngběn fēntān kāi.', 'A amortização dilui o custo.', 'Finanças'],
    ['抵押物', 'dǐyāwù', 'garantia real', 'substantivo', '房子作为抵押物。', 'Fángzi zuòwéi dǐyāwù.', 'A casa serviu de garantia.', 'Finanças'],
    ['收益率', 'shōuyìlǜ', 'rentabilidade', 'substantivo', '收益率低于通胀。', 'Shōuyìlǜ dīyú tōngzhàng.', 'A rentabilidade está abaixo da inflação.', 'Finanças'],
    ['偿付能力', 'chángfù nénglì', 'solvência', 'substantivo', '偿付能力不等于流动性。', 'Chángfù nénglì bù děngyú liúdòngxìng.', 'Solvência não é liquidez.', 'Finanças'],
    ['扭矩', 'niǔjǔ', 'torque', 'substantivo', '检查螺栓的扭矩。', 'Jiǎnchá luóshuān de niǔjǔ.', 'Confira o torque dos parafusos.', 'Engenharia'],
    ['合金', 'héjīn', 'liga metálica', 'substantivo', '这种合金抗腐蚀。', 'Zhè zhǒng héjīn kàng fǔshí.', 'Esta liga resiste à corrosão.', 'Engenharia'],
    ['电路', 'diànlù', 'circuito elétrico', 'substantivo', '电路过热了。', 'Diànlù guòrè le.', 'O circuito superaqueceu.', 'Engenharia'],
    ['尺寸公差', 'chǐcùn gōngchā', 'tolerância dimensional', 'substantivo', '尺寸公差是一毫米。', 'Chǐcùn gōngchā shì yì háomǐ.', 'A tolerância dimensional é de um milímetro.', 'Engenharia'],
    ['校准', 'jiàozhǔn', 'calibração', 'substantivo', '校准出现偏移。', 'Jiàozhǔn chūxiàn piānyí.', 'A calibração se desviou.', 'Engenharia'],
    ['摩擦', 'mócā', 'atrito', 'substantivo', '摩擦会磨损零件。', 'Mócā huì mósǔn língjiàn.', 'O atrito desgasta a peça.', 'Engenharia'],
    ['热的', 'rè de', 'térmico', 'adjetivo', '热的膨胀让它开裂。', 'Rè de péngzhàng ràng tā kāiliè.', 'A dilatação térmica a trincou.', 'Engenharia'],
    ['液压的', 'yèyā de', 'hidráulico', 'adjetivo', '液压的系统失灵了。', 'Yèyā de xìtǒng shīlíng le.', 'O sistema hidráulico falhou.', 'Engenharia'],
    ['焊接', 'hànjiē', 'solda', 'substantivo', '焊接撑住了。', 'Hànjiē chēngzhù le.', 'A solda aguentou.', 'Engenharia'],
    ['荷载', 'hèzài', 'carga estrutural', 'substantivo', '梁承受荷载。', 'Liáng chéngshòu hèzài.', 'A viga suporta a carga.', 'Engenharia'],
  ],
  C2: [
    ['霸权', 'bàquán', 'hegemonia', 'substantivo', '他们的霸权无人挑战。', 'Tāmen de bàquán wú rén tiǎozhàn.', 'A hegemonia deles não foi desafiada.', 'Filosofia política'],
    ['正当性', 'zhèngdàngxìng', 'legitimidade', 'substantivo', '选举恢复了正当性。', 'Xuǎnjǔ huīfù le zhèngdàngxìng.', 'A eleição restaurou a legitimidade.', 'Filosofia política'],
    ['民粹主义', 'míncuì zhǔyì', 'populismo', 'substantivo', '民粹主义靠怨气壮大。', 'Míncuì zhǔyì kào yuànqì zhuàngdà.', 'O populismo cresce com o ressentimento.', 'Filosofia política'],
    ['精英选拔制', 'jīngyīng xuǎnbá zhì', 'meritocracia', 'substantivo', '精英选拔制预设公平起点。', 'Jīngyīng xuǎnbá zhì yùshè gōngpíng qǐdiǎn.', 'A meritocracia pressupõe largada justa.', 'Filosofia política'],
    ['平等主义的', 'píngděng zhǔyì de', 'igualitário', 'adjetivo', '这是平等主义的方案。', 'Zhè shì píngděng zhǔyì de fāng’àn.', 'É uma proposta igualitária.', 'Filosofia política'],
    ['威权的', 'wēiquán de', 'autoritário', 'adjetivo', '这次转向是威权的。', 'Zhè cì zhuǎnxiàng shì wēiquán de.', 'Esta guinada é autoritária.', 'Filosofia política'],
    ['多元主义', 'duōyuán zhǔyì', 'pluralismo', 'substantivo', '多元主义需要真实异见。', 'Duōyuán zhǔyì xūyào zhēnshí yìjiàn.', 'O pluralismo exige dissenso real.', 'Filosofia política'],
    ['辅助性原则', 'fǔzhùxìng yuánzé', 'princípio da subsidiariedade', 'substantivo', '辅助性原则把决定下放。', 'Fǔzhùxìng yuánzé bǎ juédìng xiàfàng.', 'A subsidiariedade descentraliza a decisão.', 'Filosofia política'],
    ['技术官僚统治', 'jìshù guānliáo tǒngzhì', 'tecnocracia', 'substantivo', '技术官僚统治把选民边缘化。', 'Jìshù guānliáo tǒngzhì bǎ xuǎnmín biānyuánhuà.', 'A tecnocracia marginaliza o eleitor.', 'Filosofia política'],
    ['治国方略', 'zhìguó fānglüè', 'arte de governar', 'substantivo', '那是高明的治国方略。', 'Nà shì gāomíng de zhìguó fānglüè.', 'Aquilo foi arte de governar com maestria.', 'Filosofia política'],
    ['终止式', 'zhōngzhǐshì', 'cadência (música)', 'substantivo', '终止式收束了乐句。', 'Zhōngzhǐshì shōushù le yuèjù.', 'A cadência fecha a frase musical.', 'Música e som'],
    ['音色', 'yīnsè', 'timbre', 'substantivo', '这种音色一听就认得。', 'Zhè zhǒng yīnsè yì tīng jiù rènde.', 'Esse timbre se reconhece na hora.', 'Música e som'],
    ['不协和', 'bù xiéhé', 'dissonância', 'substantivo', '不协和是刻意的。', 'Bù xiéhé shì kèyì de.', 'A dissonância é proposital.', 'Música e som'],
    ['渐强', 'jiànqiáng', 'crescendo', 'substantivo', '渐强慢慢堆积。', 'Jiànqiáng mànman duījī.', 'O crescendo se acumula devagar.', 'Música e som'],
    ['对位', 'duìwèi', 'contraponto', 'substantivo', '对位写得很精细。', 'Duìwèi xiě de hěn jīngxì.', 'O contraponto é escrito com finura.', 'Música e som'],
    ['混响', 'hùnxiǎng', 'reverberação', 'substantivo', '这个厅堂混响温暖。', 'Zhège tīngtáng hùnxiǎng wēnnuǎn.', 'Esta sala tem reverberação quente.', 'Música e som'],
    ['断奏', 'duànzòu', 'staccato', 'substantivo', '断奏段落不好弹。', 'Duànzòu duànluò bù hǎo tán.', 'O trecho em staccato é difícil de tocar.', 'Música e som'],
    ['副歌', 'fùgē', 'refrão', 'substantivo', '副歌重复四次。', 'Fùgē chóngfù sì cì.', 'O refrão repete quatro vezes.', 'Música e som'],
    ['速度记号', 'sùdù jìhào', 'andamento (marcação)', 'substantivo', '这里速度记号偏慢。', 'Zhèlǐ sùdù jìhào piān màn.', 'Aqui o andamento é lento demais.', 'Música e som'],
    ['和声', 'héshēng', 'harmonia', 'substantivo', '和声突然转变。', 'Héshēng tūrán zhuǎnbiàn.', 'A harmonia muda de repente.', 'Música e som'],
  ],
};
