/** Alemão — vocabulário de ampliação. Nenhuma palavra repete o catálogo existente. */

import type { LatinByLevel } from './entry';

export const DE: LatinByLevel = {
  A1: [
    ['der Tisch', 'mesa', 'substantivo', 'Der Tisch ist groß.', 'A mesa é grande.'],
    ['der Stuhl', 'cadeira', 'substantivo', 'Setz dich auf den Stuhl.', 'Sente-se na cadeira.'],
    ['die Tür', 'porta', 'substantivo', 'Schließ die Tür.', 'Feche a porta.'],
    ['das Fenster', 'janela', 'substantivo', 'Öffne das Fenster.', 'Abra a janela.'],
    ['das Bett', 'cama', 'substantivo', 'Ich schlafe in meinem Bett.', 'Eu durmo na minha cama.'],
    ['die Küche', 'cozinha', 'substantivo', 'Sie kocht in der Küche.', 'Ela cozinha na cozinha.'],
    ['das Badezimmer', 'banheiro', 'substantivo', 'Das Badezimmer ist oben.', 'O banheiro é lá em cima.'],
    ['der Bruder', 'irmão', 'substantivo', 'Mein Bruder ist groß.', 'Meu irmão é alto.'],
    ['die Schwester', 'irmã', 'substantivo', 'Meine Schwester ist Ärztin.', 'Minha irmã é médica.'],
    ['der Vater', 'pai', 'substantivo', 'Mein Vater arbeitet viel.', 'Meu pai trabalha muito.'],
    ['die Mutter', 'mãe', 'substantivo', 'Meine Mutter kocht gut.', 'Minha mãe cozinha bem.'],
    ['das Baby', 'bebê', 'substantivo', 'Das Baby schläft.', 'O bebê está dormindo.'],
    ['der Hund', 'cachorro', 'substantivo', 'Der Hund bellt.', 'O cachorro está latindo.'],
    ['die Katze', 'gato', 'substantivo', 'Die Katze schläft den ganzen Tag.', 'O gato dorme o dia todo.'],
    ['rot', 'vermelho', 'adjetivo', 'Das Auto ist rot.', 'O carro é vermelho.'],
    ['blau', 'azul', 'adjetivo', 'Der Himmel ist blau.', 'O céu é azul.'],
    ['hoch', 'alto', 'adjetivo', 'Das Gebäude ist hoch.', 'O prédio é alto.'],
    ['kurz', 'curto', 'adjetivo', 'Meine Haare sind kurz.', 'Meu cabelo é curto.'],
    ['heiß', 'quente', 'adjetivo', 'Die Suppe ist heiß.', 'A sopa está quente.'],
    ['kalt', 'frio', 'adjetivo', 'Das Wasser ist kalt.', 'A água está fria.'],
  ],
  A2: [
    ['die Besorgung', 'tarefa rápida (fora de casa)', 'substantivo', 'Ich habe heute ein paar Besorgungen.', 'Tenho umas tarefas para resolver hoje.'],
    ['die Rechnung', 'fatura', 'substantivo', 'Schick mir die Rechnung, bitte.', 'Me manda a fatura, por favor.'],
    ['der Nachbar', 'vizinho', 'substantivo', 'Mein Nachbar ist freundlich.', 'Meu vizinho é simpático.'],
    ['der Vermieter', 'senhorio', 'substantivo', 'Der Vermieter hat den Hahn repariert.', 'O senhorio consertou a torneira.'],
    ['die Möbel', 'móveis', 'substantivo', 'Wir haben neue Möbel gekauft.', 'Compramos móveis novos.'],
    ['die Apotheke', 'farmácia', 'substantivo', 'Die Apotheke hat lange geöffnet.', 'A farmácia abre até tarde.'],
    ['das Symptom', 'sintoma', 'substantivo', 'Beschreib deine Symptome.', 'Descreva seus sintomas.'],
    ['das Fieber', 'febre', 'substantivo', 'Sie hat Fieber.', 'Ela está com febre.'],
    ['geräumig', 'espaçoso', 'adjetivo', 'Die Wohnung ist geräumig.', 'O apartamento é espaçoso.'],
    ['erschöpft', 'exausto', 'adjetivo', 'Ich bin heute erschöpft.', 'Estou exausto hoje.'],
    ['höflich', 'educado', 'adjetivo', 'Er ist sehr höflich.', 'Ele é muito educado.'],
    ['unhöflich', 'grosseiro', 'adjetivo', 'Dieser Kommentar war unhöflich.', 'Aquele comentário foi grosseiro.'],
    ['in der Nähe', 'perto', 'advérbio', 'Es gibt einen Park in der Nähe.', 'Tem um parque por perto.'],
    ['sofort', 'imediatamente', 'advérbio', 'Ruf mich sofort an.', 'Me ligue imediatamente.'],
    ['neulich', 'ultimamente / recentemente', 'advérbio', 'Ich bin neulich hierher gezogen.', 'Recentemente eu me mudei para cá.'],
    ['der Reiseplan', 'roteiro (de viagem)', 'substantivo', 'Hier ist unser Reiseplan.', 'Aqui está nosso roteiro de viagem.'],
    ['die Rückerstattung', 'reembolso', 'substantivo', 'Ich möchte eine Rückerstattung.', 'Quero um reembolso.'],
    ['der Rabatt', 'desconto', 'substantivo', 'Gibt es einen Rabatt?', 'Tem desconto?'],
    ['die Kreuzung', 'cruzamento', 'substantivo', 'Bieg an der Kreuzung links ab.', 'Vire à esquerda no cruzamento.'],
    ['der Bürgersteig', 'calçada', 'substantivo', 'Geh auf dem Bürgersteig.', 'Ande na calçada.'],
  ],
  B1: [
    ['die Arbeitsbelastung', 'carga de trabalho', 'substantivo', 'Meine Arbeitsbelastung ist diesen Monat hoch.', 'Minha carga de trabalho está pesada este mês.'],
    ['der Kollege', 'colega de trabalho', 'substantivo', 'Er ist ein hilfsbereiter Kollege.', 'Ele é um colega prestativo.'],
    ['die Beförderung', 'promoção (cargo)', 'substantivo', 'Er hat eine Beförderung bekommen.', 'Ele conseguiu uma promoção.'],
    ['die Kündigung', 'demissão (pedido)', 'substantivo', 'Sie hat ihre Kündigung eingereicht.', 'Ela entregou o pedido de demissão.'],
    ['das Gehalt', 'salário', 'substantivo', 'Das Gehalt ist konkurrenzfähig.', 'O salário é competitivo.'],
    ['das Schulgeld', 'mensalidade escolar', 'substantivo', 'Das Schulgeld ist dieses Jahr gestiegen.', 'A mensalidade aumentou esse ano.'],
    ['das Stipendium', 'bolsa de estudos', 'substantivo', 'Sie hat ein Stipendium gewonnen.', 'Ela ganhou uma bolsa de estudos.'],
    ['flexibel', 'flexível', 'adjetivo', 'Mein Zeitplan ist flexibel.', 'Minha agenda é flexível.'],
    ['stressig', 'estressante', 'adjetivo', 'Dieser Job ist stressig.', 'Esse trabalho é estressante.'],
    ['effizient', 'eficiente', 'adjetivo', 'Das neue System ist effizient.', 'O sistema novo é eficiente.'],
    ['veraltet', 'desatualizado', 'adjetivo', 'Diese Software ist veraltet.', 'Esse software está desatualizado.'],
    ['allmählich', 'gradualmente', 'advérbio', 'Die Preise stiegen allmählich.', 'Os preços subiram gradualmente.'],
    ['letztendlich', 'no fim das contas', 'advérbio', 'Letztendlich haben wir uns geeinigt.', 'No fim das contas, chegamos a um acordo.'],
    ['das Haushaltsgerät', 'eletrodoméstico', 'substantivo', 'Die Waschmaschine ist ein Haushaltsgerät.', 'A máquina de lavar é um eletrodoméstico.'],
    ['die Garantie', 'garantia (produto)', 'substantivo', 'Die Garantie gilt zwei Jahre.', 'A garantia dura dois anos.'],
    ['das Abonnement', 'assinatura (serviço)', 'substantivo', 'Ich habe mein Abonnement gekündigt.', 'Cancelei minha assinatura.'],
    ['der Arbeitsweg', 'trajeto casa-trabalho', 'substantivo', 'Mein Arbeitsweg dauert eine Stunde.', 'Meu trajeto até o trabalho leva uma hora.'],
    ['überfordert', 'sobrecarregado', 'adjetivo', 'Ich fühle mich bei der Arbeit überfordert.', 'Me sinto sobrecarregado no trabalho.'],
    ['motiviert', 'motivado', 'adjetivo', 'Das Team ist motiviert.', 'A equipe está motivada.'],
    ['der Behördengang', 'processo burocrático', 'substantivo', 'Der Behördengang hat Wochen gedauert.', 'O processo burocrático levou semanas.'],
  ],
  B2: [
    ['die Disparität', 'disparidade', 'substantivo', 'Es gibt eine große Einkommensdisparität.', 'Há uma grande disparidade de renda.'],
    ['die Weitsicht', 'previsão / visão de futuro', 'substantivo', 'Der Plan zeigte echte Weitsicht.', 'O plano mostrou visão de futuro de verdade.'],
    ['die Nachhaltigkeit', 'sustentabilidade', 'substantivo', 'Nachhaltigkeit hat jetzt Priorität.', 'Sustentabilidade é prioridade agora.'],
    ['die Ungleichheit', 'desigualdade', 'substantivo', 'Ungleichheit bleibt ein großes Problem.', 'A desigualdade continua sendo um grande problema.'],
    ['die Kontroverse', 'controvérsia', 'substantivo', 'Die Entscheidung löste eine Kontroverse aus.', 'A decisão causou controvérsia.'],
    ['das Schlupfloch', 'brecha (na lei)', 'substantivo', 'Sie fanden ein rechtliches Schlupfloch.', 'Encontraram uma brecha legal.'],
    ['die Rechenschaftspflicht', 'responsabilização', 'substantivo', 'Wir brauchen mehr Rechenschaftspflicht.', 'Precisamos de mais responsabilização.'],
    ['die Transparenz', 'transparência', 'substantivo', 'Der Firma fehlt es an Transparenz.', 'A empresa carece de transparência.'],
    ['plausibel', 'plausível', 'adjetivo', 'Diese Erklärung klingt plausibel.', 'Aquela explicação parece plausível.'],
    ['zweideutig', 'ambíguo', 'adjetivo', 'Der Wortlaut ist zweideutig.', 'A redação é ambígua.'],
    ['widerstandsfähig', 'resiliente', 'adjetivo', 'Die Wirtschaft erwies sich als widerstandsfähig.', 'A economia se mostrou resiliente.'],
    ['volatil', 'volátil', 'adjetivo', 'Der Markt ist volatil.', 'O mercado está volátil.'],
    ['vermutlich', 'possivelmente / provavelmente', 'advérbio', 'Das ist vermutlich die beste Option.', 'Essa é, provavelmente, a melhor opção.'],
    ['unweigerlich', 'inevitavelmente', 'advérbio', 'Die Kosten werden unweigerlich steigen.', 'Os custos vão subir inevitavelmente.'],
    ['die Gegenreaktion', 'reação negativa', 'substantivo', 'Die Politik löste eine Gegenreaktion aus.', 'A política causou uma reação negativa.'],
    ['das Klischee', 'estereótipo', 'substantivo', 'Die Werbung stützt sich auf ein Klischee.', 'O anúncio se apoia num estereótipo.'],
    ['die Übergangslösung', 'solução paliativa', 'substantivo', 'Wir fanden eine Übergangslösung.', 'Encontramos uma solução paliativa.'],
    ['der Meilenstein', 'marco (conquista)', 'substantivo', 'Der Start war ein großer Meilenstein.', 'O lançamento foi um grande marco.'],
    ['die genaue Prüfung', 'escrutínio', 'substantivo', 'Der Deal steht unter genauer Prüfung.', 'O acordo está sob escrutínio.'],
    ['greifbar', 'tangível', 'adjetivo', 'Wir brauchen greifbare Ergebnisse.', 'Precisamos de resultados tangíveis.'],
  ],
  C1: [
    ['das Dilemma', 'dilema', 'substantivo', 'Das ist ein echtes Dilemma.', 'É um dilema difícil de verdade.'],
    ['das Prinzip', 'preceito / princípio', 'substantivo', 'Das ist ein zentrales Prinzip der Theorie.', 'Esse é um princípio central da teoria.'],
    ['die Auswirkung', 'repercussão', 'substantivo', 'Bedenke zuerst die Auswirkungen.', 'Considere as repercussões primeiro.'],
    ['die Feinheit', 'sutileza', 'substantivo', 'Die Übersetzung verlor eine Feinheit.', 'A tradução perdeu alguma sutileza.'],
    ['der Präzedenzfall', 'precedente', 'substantivo', 'Dieser Fall schafft einen Präzedenzfall.', 'Esse caso cria um precedente.'],
    ['pragmatisch', 'pragmático', 'adjetivo', 'Sie verfolgte einen pragmatischen Ansatz.', 'Ela adotou uma abordagem pragmática.'],
    ['redundant', 'redundante', 'adjetivo', 'Diese Klausel ist redundant.', 'Aquela cláusula é redundante.'],
    ['beispiellos', 'sem precedentes', 'adjetivo', 'Es war eine beispiellose Krise.', 'Foi uma crise sem precedentes.'],
    ['der Konsens', 'consenso', 'substantivo', 'Wir haben einen Konsens erzielt.', 'Chegamos a um consenso.'],
    ['der Notfallplan', 'plano de contingência', 'substantivo', 'Wir brauchen einen Notfallplan.', 'Precisamos de um plano de contingência.'],
    ['der Trugschluss', 'falácia', 'substantivo', 'Das ist ein häufiger Trugschluss.', 'Essa é uma falácia comum.'],
    ['das Paradox', 'paradoxo', 'substantivo', 'Es ist ein seltsames Paradox.', 'É um paradoxo estranho.'],
    ['gewissenhaft', 'escrupuloso', 'adjetivo', 'Er ist gewissenhaft bei Details.', 'Ele é escrupuloso com detalhes.'],
    ['offen', 'sincero / franco', 'adjetivo', 'Seien wir offen über die Risiken.', 'Vamos ser francos sobre os riscos.'],
    ['akribisch', 'meticuloso', 'adjetivo', 'Sie ist akribisch mit den Daten.', 'Ela é meticulosa com os dados.'],
    ['scheinbar', 'aparentemente', 'advérbio', 'Eine scheinbar einfache Aufgabe.', 'Uma tarefa aparentemente simples.'],
    ['unabhängig davon', 'independentemente de', 'advérbio', 'Wir machen weiter, unabhängig von den Risiken.', 'Seguimos em frente, independentemente dos riscos.'],
    ['vermeintlich', 'possivelmente / supostamente', 'advérbio', 'Vermeintlich könnte es funktionieren.', 'Supostamente poderia funcionar.'],
    ['die Skepsis', 'ceticismo', 'substantivo', 'Sie nahmen die Nachricht mit Skepsis auf.', 'Receberam a notícia com ceticismo.'],
    ['die Ungewissheit', 'incerteza', 'substantivo', 'Wir leben in einer Zeit der Ungewissheit.', 'Vivemos um período de incerteza.'],
  ],
  C2: [
    ['die Dringlichkeit', 'urgência premente', 'substantivo', 'Die Dringlichkeit der Lage erforderte Handeln.', 'A urgência da situação exigia ação.'],
    ['die Umschreibung', 'circunlóquio', 'substantivo', 'Vermeide Umschreibungen in Rechtstexten.', 'Evite circunlóquios em textos jurídicos.'],
    ['die Gelassenheit', 'equanimidade', 'substantivo', 'Sie nahm die Nachricht mit Gelassenheit auf.', 'Ela recebeu a notícia com equanimidade.'],
    ['die Verschleierung', 'obscurecimento proposital', 'substantivo', 'Der Bericht steckt voller Verschleierung.', 'O relatório está cheio de obscurecimento proposital.'],
    ['lustlos', 'superficial / feito por obrigação', 'adjetivo', 'Es war eine lustlose Entschuldigung.', 'Foi um pedido de desculpas superficial.'],
    ['unbeschreiblich', 'indescritível', 'adjetivo', 'Die Aussicht war unbeschreiblich.', 'A vista era indescritível.'],
    ['allgegenwärtig', 'onipresente', 'adjetivo', 'Smartphones sind heute allgegenwärtig.', 'Os smartphones são onipresentes hoje.'],
    ['eigentümlich', 'idiossincrático / peculiar', 'adjetivo', 'Sein Stil ist ziemlich eigentümlich.', 'O estilo dele é bem peculiar.'],
    ['prekär', 'precário / instável', 'adjetivo', 'Ihre Lage ist bestenfalls prekär.', 'A posição deles é, no máximo, precária.'],
    ['heimtückisch', 'insidioso', 'adjetivo', 'Es ist ein heimtückisches Problem.', 'É um problema insidioso.'],
    ['die Gegenüberstellung', 'justaposição', 'substantivo', 'Die Gegenüberstellung von Alt und Neu fällt auf.', 'A justaposição do velho com o novo impressiona.'],
    ['die Genugtuung', 'reconhecimento de razão', 'substantivo', 'Die Ergebnisse fühlten sich wie Genugtuung an.', 'Os resultados pareceram lhe dar razão.'],
    ['das stillschweigende Einverständnis', 'anuência silenciosa', 'substantivo', 'Sein Schweigen deutete auf ein stillschweigendes Einverständnis hin.', 'O silêncio dele sugeria uma anuência silenciosa.'],
    ['unveränderlich', 'imutável', 'adjetivo', 'Manche Regeln scheinen unveränderlich.', 'Algumas regras parecem imutáveis.'],
    ['vorgeblich', 'aparente (mas duvidoso)', 'adjetivo', 'Der vorgebliche Grund war der Preis.', 'A razão aparente foi o custo.'],
    ['verstohlen', 'sub-reptício / dissimulado', 'adjetivo', 'Ein verstohlener Blick auf die Notizen.', 'Um olhar dissimulado para as anotações.'],
    ['die Wechselfälle', 'vicissitude', 'substantivo', 'Die Wechselfälle des Lebens prägten sie.', 'As vicissitudes da vida a moldaram.'],
    ['schroff', 'peremptório / brusco', 'adjetivo', 'Sein Ton war schroff.', 'O tom dele foi brusco e peremptório.'],
    ['mutmaßlich', 'supostamente', 'advérbio', 'Mutmaßlich ist der Plan einfach.', 'Supostamente, o plano é simples.'],
    ['bis dato', 'até agora / até então', 'advérbio', 'Eine bis dato unbekannte Tatsache kam ans Licht.', 'Um fato até então desconhecido veio à tona.'],
  ],
};
