/** Inglês — vocabulário de ampliação. Nenhuma palavra repete o catálogo existente. */

import type { LatinByLevel } from './entry';

export const EN: LatinByLevel = {
  A1: [
    ['table', 'mesa', 'substantivo', 'The table is big.', 'A mesa é grande.'],
    ['chair', 'cadeira', 'substantivo', 'Sit on the chair.', 'Sente na cadeira.'],
    ['door', 'porta', 'substantivo', 'Close the door.', 'Feche a porta.'],
    ['window', 'janela', 'substantivo', 'Open the window.', 'Abra a janela.'],
    ['bed', 'cama', 'substantivo', 'I sleep in my bed.', 'Eu durmo na minha cama.'],
    ['kitchen', 'cozinha', 'substantivo', 'She cooks in the kitchen.', 'Ela cozinha na cozinha.'],
    ['bathroom', 'banheiro', 'substantivo', 'The bathroom is upstairs.', 'O banheiro é lá em cima.'],
    ['brother', 'irmão', 'substantivo', 'My brother is tall.', 'Meu irmão é alto.'],
    ['sister', 'irmã', 'substantivo', 'My sister is a doctor.', 'Minha irmã é médica.'],
    ['father', 'pai', 'substantivo', 'My father works a lot.', 'Meu pai trabalha muito.'],
    ['mother', 'mãe', 'substantivo', 'My mother cooks well.', 'Minha mãe cozinha bem.'],
    ['baby', 'bebê', 'substantivo', 'The baby is sleeping.', 'O bebê está dormindo.'],
    ['dog', 'cachorro', 'substantivo', 'The dog is barking.', 'O cachorro está latindo.'],
    ['cat', 'gato', 'substantivo', 'The cat sleeps all day.', 'O gato dorme o dia todo.'],
    ['red', 'vermelho', 'adjetivo', 'The car is red.', 'O carro é vermelho.'],
    ['blue', 'azul', 'adjetivo', 'The sky is blue.', 'O céu é azul.'],
    ['tall', 'alto', 'adjetivo', 'The building is tall.', 'O prédio é alto.'],
    ['short', 'baixo / curto', 'adjetivo', 'My hair is short.', 'Meu cabelo é curto.'],
    ['hot', 'quente', 'adjetivo', 'The soup is hot.', 'A sopa está quente.'],
    ['cold', 'frio', 'adjetivo', 'The water is cold.', 'A água está fria.'],
  ],
  A2: [
    ['errand', 'tarefa rápida (fora de casa)', 'substantivo', 'I have a few errands today.', 'Tenho umas tarefas para resolver hoje.'],
    ['invoice', 'fatura', 'substantivo', 'Send me the invoice, please.', 'Me manda a fatura, por favor.'],
    ['neighbor', 'vizinho', 'substantivo', 'My neighbor is friendly.', 'Meu vizinho é simpático.'],
    ['landlord', 'senhorio', 'substantivo', 'The landlord fixed the sink.', 'O senhorio consertou a pia.'],
    ['furniture', 'móveis', 'substantivo', 'We bought new furniture.', 'Compramos móveis novos.'],
    ['pharmacy', 'farmácia', 'substantivo', 'The pharmacy is open late.', 'A farmácia abre até tarde.'],
    ['symptom', 'sintoma', 'substantivo', 'Describe your symptoms.', 'Descreva seus sintomas.'],
    ['fever', 'febre', 'substantivo', 'She has a fever.', 'Ela está com febre.'],
    ['spacious', 'espaçoso', 'adjetivo', 'The apartment is spacious.', 'O apartamento é espaçoso.'],
    ['exhausted', 'exausto', 'adjetivo', 'I am exhausted today.', 'Estou exausto hoje.'],
    ['polite', 'educado', 'adjetivo', 'He is very polite.', 'Ele é muito educado.'],
    ['rude', 'grosseiro', 'adjetivo', 'That comment was rude.', 'Aquele comentário foi grosseiro.'],
    ['nearby', 'perto / próximo', 'advérbio', 'There is a park nearby.', 'Tem um parque por perto.'],
    ['immediately', 'imediatamente', 'advérbio', 'Call me immediately.', 'Me ligue imediatamente.'],
    ['recently', 'recentemente', 'advérbio', 'I recently moved here.', 'Me mudei para cá recentemente.'],
    ['itinerary', 'roteiro (de viagem)', 'substantivo', 'Here is our travel itinerary.', 'Aqui está nosso roteiro de viagem.'],
    ['refund', 'reembolso', 'substantivo', 'I want a refund.', 'Quero um reembolso.'],
    ['discount', 'desconto', 'substantivo', 'Is there a discount?', 'Tem desconto?'],
    ['crossroad', 'cruzamento', 'substantivo', 'Turn left at the crossroad.', 'Vire à esquerda no cruzamento.'],
    ['sidewalk', 'calçada', 'substantivo', 'Walk on the sidewalk.', 'Ande na calçada.'],
  ],
  B1: [
    ['workload', 'carga de trabalho', 'substantivo', 'My workload is heavy this month.', 'Minha carga de trabalho está pesada este mês.'],
    ['colleague', 'colega de trabalho', 'substantivo', 'She is a helpful colleague.', 'Ela é uma colega prestativa.'],
    ['promotion', 'promoção (cargo)', 'substantivo', 'He got a promotion.', 'Ele conseguiu uma promoção.'],
    ['resignation', 'demissão (pedido)', 'substantivo', 'She handed in her resignation.', 'Ela entregou o pedido de demissão.'],
    ['salary', 'salário', 'substantivo', 'The salary is competitive.', 'O salário é competitivo.'],
    ['tuition', 'mensalidade escolar', 'substantivo', 'Tuition increased this year.', 'A mensalidade aumentou esse ano.'],
    ['scholarship', 'bolsa de estudos', 'substantivo', 'She won a scholarship.', 'Ela ganhou uma bolsa de estudos.'],
    ['trustworthy', 'digno de confiança', 'adjetivo', 'He is a trustworthy partner.', 'Ele é um sócio digno de confiança.'],
    ['flexible', 'flexível', 'adjetivo', 'My schedule is flexible.', 'Minha agenda é flexível.'],
    ['stressful', 'estressante', 'adjetivo', 'This job is stressful.', 'Esse trabalho é estressante.'],
    ['efficient', 'eficiente', 'adjetivo', 'The new system is efficient.', 'O sistema novo é eficiente.'],
    ['outdated', 'desatualizado', 'adjetivo', 'This software is outdated.', 'Esse software está desatualizado.'],
    ['gradually', 'gradualmente', 'advérbio', 'Prices rose gradually.', 'Os preços subiram gradualmente.'],
    ['increasingly', 'cada vez mais', 'advérbio', 'It became increasingly difficult.', 'Ficou cada vez mais difícil.'],
    ['appliance', 'eletrodoméstico', 'substantivo', 'The washing machine is an appliance.', 'A máquina de lavar é um eletrodoméstico.'],
    ['warranty', 'garantia (produto)', 'substantivo', 'The warranty lasts two years.', 'A garantia dura dois anos.'],
    ['subscription', 'assinatura (serviço)', 'substantivo', 'I canceled my subscription.', 'Cancelei minha assinatura.'],
    ['commute', 'trajeto casa-trabalho', 'substantivo', 'My commute takes an hour.', 'Meu trajeto até o trabalho leva uma hora.'],
    ['overwhelmed', 'sobrecarregado', 'adjetivo', 'I feel overwhelmed at work.', 'Me sinto sobrecarregado no trabalho.'],
    ['motivated', 'motivado', 'adjetivo', 'The team is motivated.', 'A equipe está motivada.'],
  ],
  B2: [
    ['disparity', 'disparidade', 'substantivo', 'There is a wide disparity in income.', 'Há uma grande disparidade de renda.'],
    ['foresight', 'previsão / visão de futuro', 'substantivo', 'The plan showed real foresight.', 'O plano mostrou visão de futuro de verdade.'],
    ['sustainability', 'sustentabilidade', 'substantivo', 'Sustainability is a priority now.', 'Sustentabilidade é prioridade agora.'],
    ['inequality', 'desigualdade', 'substantivo', 'Inequality remains a big issue.', 'A desigualdade continua sendo um grande problema.'],
    ['controversy', 'controvérsia', 'substantivo', 'The decision caused controversy.', 'A decisão causou controvérsia.'],
    ['loophole', 'brecha (na lei)', 'substantivo', 'They found a legal loophole.', 'Encontraram uma brecha legal.'],
    ['accountability', 'responsabilização', 'substantivo', 'We need more accountability.', 'Precisamos de mais responsabilização.'],
    ['transparency', 'transparência', 'substantivo', 'The firm lacks transparency.', 'A empresa carece de transparência.'],
    ['plausible', 'plausível', 'adjetivo', 'That explanation seems plausible.', 'Aquela explicação parece plausível.'],
    ['ambiguous', 'ambíguo', 'adjetivo', 'The wording is ambiguous.', 'A redação é ambígua.'],
    ['resilient', 'resiliente', 'adjetivo', 'The economy proved resilient.', 'A economia se mostrou resiliente.'],
    ['volatile', 'volátil', 'adjetivo', 'The market is volatile.', 'O mercado está volátil.'],
    ['arguably', 'possivelmente / sem dúvida', 'advérbio', 'This is arguably the best option.', 'Essa é, sem dúvida, a melhor opção.'],
    ['inevitably', 'inevitavelmente', 'advérbio', 'Costs will inevitably rise.', 'Os custos vão subir inevitavelmente.'],
    ['backlash', 'reação negativa', 'substantivo', 'The policy caused a backlash.', 'A política causou uma reação negativa.'],
    ['stereotype', 'estereótipo', 'substantivo', 'The ad relies on a stereotype.', 'O anúncio se apoia num estereótipo.'],
    ['workaround', 'solução paliativa', 'substantivo', 'We found a temporary workaround.', 'Encontramos uma solução paliativa temporária.'],
    ['milestone', 'marco (conquista)', 'substantivo', 'Launching was a big milestone.', 'O lançamento foi um grande marco.'],
    ['scrutiny', 'escrutínio', 'substantivo', 'The deal is under scrutiny.', 'O acordo está sob escrutínio.'],
    ['tangible', 'tangível', 'adjetivo', 'We need tangible results.', 'Precisamos de resultados tangíveis.'],
  ],
  C1: [
    ['conundrum', 'dilema / charada difícil', 'substantivo', 'It is a real conundrum.', 'É um dilema difícil de verdade.'],
    ['tenet', 'princípio / preceito', 'substantivo', 'That is a core tenet of the theory.', 'Esse é um princípio central da teoria.'],
    ['repercussion', 'repercussão', 'substantivo', 'Consider the repercussions first.', 'Considere as repercussões primeiro.'],
    ['subtlety', 'sutileza', 'substantivo', 'The translation lost some subtlety.', 'A tradução perdeu alguma sutileza.'],
    ['precedent', 'precedente', 'substantivo', 'This case sets a precedent.', 'Esse caso cria um precedente.'],
    ['inherent', 'inerente', 'adjetivo', 'The risk is inherent to the job.', 'O risco é inerente ao trabalho.'],
    ['pragmatic', 'pragmático', 'adjetivo', 'She took a pragmatic approach.', 'Ela adotou uma abordagem pragmática.'],
    ['redundant', 'redundante', 'adjetivo', 'That clause is redundant.', 'Aquela cláusula é redundante.'],
    ['unprecedented', 'sem precedentes', 'adjetivo', 'It was an unprecedented crisis.', 'Foi uma crise sem precedentes.'],
    ['consensus', 'consenso', 'substantivo', 'We reached a consensus.', 'Chegamos a um consenso.'],
    ['contingency', 'contingência / plano B', 'substantivo', 'We need a contingency plan.', 'Precisamos de um plano de contingência.'],
    ['stipulation', 'estipulação', 'substantivo', 'The contract has a strict stipulation.', 'O contrato tem uma estipulação rígida.'],
    ['fallacy', 'falácia', 'substantivo', 'That is a common fallacy.', 'Essa é uma falácia comum.'],
    ['paradox', 'paradoxo', 'substantivo', 'It is a strange paradox.', 'É um paradoxo estranho.'],
    ['scrupulous', 'escrupuloso', 'adjetivo', 'He is scrupulous about details.', 'Ele é escrupuloso com detalhes.'],
    ['candid', 'sincero / franco', 'adjetivo', 'Let’s be candid about the risks.', 'Vamos ser francos sobre os riscos.'],
    ['meticulous', 'meticuloso', 'adjetivo', 'She is meticulous with data.', 'Ela é meticulosa com os dados.'],
    ['seemingly', 'aparentemente', 'advérbio', 'A seemingly simple task.', 'Uma tarefa aparentemente simples.'],
    ['irrespective', 'independentemente', 'advérbio', 'We proceed, irrespective of the risks.', 'Seguimos em frente, independentemente dos riscos.'],
    ['conceivably', 'possivelmente / é concebível que', 'advérbio', 'It could conceivably work.', 'É concebível que funcione.'],
  ],
  C2: [
    ['exigency', 'exigência premente', 'substantivo', 'The exigencies of the situation demanded action.', 'As exigências da situação demandavam ação.'],
    ['circumlocution', 'circunlóquio', 'substantivo', 'Avoid circumlocution in legal writing.', 'Evite circunlóquios na redação jurídica.'],
    ['equanimity', 'equanimidade', 'substantivo', 'She faced the news with equanimity.', 'Ela recebeu a notícia com equanimidade.'],
    ['obfuscation', 'obscurecimento proposital', 'substantivo', 'The report is full of obfuscation.', 'O relatório está cheio de obscurecimento proposital.'],
    ['perfunctory', 'superficial / feito por obrigação', 'adjetivo', 'It was a perfunctory apology.', 'Foi um pedido de desculpas superficial.'],
    ['ineffable', 'indescritível', 'adjetivo', 'The view was ineffable.', 'A vista era indescritível.'],
    ['ubiquitous', 'onipresente', 'adjetivo', 'Smartphones are ubiquitous now.', 'Os smartphones são onipresentes hoje.'],
    ['idiosyncratic', 'idiossincrático', 'adjetivo', 'His style is quite idiosyncratic.', 'O estilo dele é bem idiossincrático.'],
    ['precarious', 'precário / instável', 'adjetivo', 'Their position is precarious at best.', 'A posição deles é, no máximo, precária.'],
    ['insidious', 'insidioso', 'adjetivo', 'It is an insidious problem.', 'É um problema insidioso.'],
    ['juxtaposition', 'justaposição', 'substantivo', 'The juxtaposition of old and new is striking.', 'A justaposição do velho com o novo impressiona.'],
    ['vindication', 'reconhecimento de razão', 'substantivo', 'The results felt like vindication.', 'Os resultados pareceram lhe dar razão.'],
    ['acquiescence', 'anuência silenciosa', 'substantivo', 'His silence implied acquiescence.', 'O silêncio dele implicava anuência.'],
    ['immutable', 'imutável', 'adjetivo', 'Some rules seem immutable.', 'Algumas regras parecem imutáveis.'],
    ['ostensible', 'aparente (mas duvidoso)', 'adjetivo', 'The ostensible reason was cost.', 'A razão aparente foi o custo.'],
    ['surreptitious', 'sub-reptício / dissimulado', 'adjetivo', 'A surreptitious glance at the notes.', 'Um olhar dissimulado para as anotações.'],
    ['vicissitude', 'vicissitude', 'substantivo', 'The vicissitudes of life shaped her.', 'As vicissitudes da vida a moldaram.'],
    ['peremptory', 'peremptório', 'adjetivo', 'His tone was peremptory.', 'O tom dele foi peremptório.'],
    ['purportedly', 'supostamente', 'advérbio', 'Purportedly, the plan is simple.', 'Supostamente, o plano é simples.'],
    ['heretofore', 'até então / anteriormente', 'advérbio', 'A heretofore unknown fact emerged.', 'Um fato até então desconhecido surgiu.'],
  ],
};
