/** Espanhol — vocabulário de ampliação. Nenhuma palavra repete o catálogo existente. */

import type { LatinByLevel } from './entry';

export const ES: LatinByLevel = {
  A1: [
    ['la mesa', 'mesa', 'substantivo', 'La mesa es grande.', 'A mesa é grande.'],
    ['la silla', 'cadeira', 'substantivo', 'Siéntate en la silla.', 'Sente-se na cadeira.'],
    ['la puerta', 'porta', 'substantivo', 'Cierra la puerta.', 'Feche a porta.'],
    ['la ventana', 'janela', 'substantivo', 'Abre la ventana.', 'Abra a janela.'],
    ['la cama', 'cama', 'substantivo', 'Duermo en mi cama.', 'Eu durmo na minha cama.'],
    ['la cocina', 'cozinha', 'substantivo', 'Ella cocina en la cocina.', 'Ela cozinha na cozinha.'],
    ['el baño', 'banheiro', 'substantivo', 'El baño está arriba.', 'O banheiro é lá em cima.'],
    ['el hermano', 'irmão', 'substantivo', 'Mi hermano es alto.', 'Meu irmão é alto.'],
    ['la hermana', 'irmã', 'substantivo', 'Mi hermana es médica.', 'Minha irmã é médica.'],
    ['el padre', 'pai', 'substantivo', 'Mi padre trabaja mucho.', 'Meu pai trabalha muito.'],
    ['la madre', 'mãe', 'substantivo', 'Mi madre cocina bien.', 'Minha mãe cozinha bem.'],
    ['el bebé', 'bebê', 'substantivo', 'El bebé está durmiendo.', 'O bebê está dormindo.'],
    ['el perro', 'cachorro', 'substantivo', 'El perro está ladrando.', 'O cachorro está latindo.'],
    ['el gato', 'gato', 'substantivo', 'El gato duerme todo el día.', 'O gato dorme o dia todo.'],
    ['rojo', 'vermelho', 'adjetivo', 'El coche es rojo.', 'O carro é vermelho.'],
    ['azul', 'azul', 'adjetivo', 'El cielo es azul.', 'O céu é azul.'],
    ['alto', 'alto', 'adjetivo', 'El edificio es alto.', 'O prédio é alto.'],
    ['corto', 'curto / baixo', 'adjetivo', 'Mi pelo es corto.', 'Meu cabelo é curto.'],
    ['caliente', 'quente', 'adjetivo', 'La sopa está caliente.', 'A sopa está quente.'],
    ['frío', 'frio', 'adjetivo', 'El agua está fría.', 'A água está fria.'],
  ],
  A2: [
    ['el recado', 'tarefa rápida (fora de casa)', 'substantivo', 'Tengo unos recados hoy.', 'Tenho umas tarefas para resolver hoje.'],
    ['la factura', 'fatura', 'substantivo', 'Mándame la factura, por favor.', 'Me manda a fatura, por favor.'],
    ['el vecino', 'vizinho', 'substantivo', 'Mi vecino es amable.', 'Meu vizinho é simpático.'],
    ['el casero', 'senhorio', 'substantivo', 'El casero arregló el grifo.', 'O senhorio consertou a torneira.'],
    ['los muebles', 'móveis', 'substantivo', 'Compramos muebles nuevos.', 'Compramos móveis novos.'],
    ['la farmacia', 'farmácia', 'substantivo', 'La farmacia abre hasta tarde.', 'A farmácia abre até tarde.'],
    ['el síntoma', 'sintoma', 'substantivo', 'Describe tus síntomas.', 'Descreva seus sintomas.'],
    ['la fiebre', 'febre', 'substantivo', 'Ella tiene fiebre.', 'Ela está com febre.'],
    ['espacioso', 'espaçoso', 'adjetivo', 'El piso es espacioso.', 'O apartamento é espaçoso.'],
    ['agotado', 'exausto', 'adjetivo', 'Estoy agotado hoy.', 'Estou exausto hoje.'],
    ['educado', 'educado', 'adjetivo', 'Es muy educado.', 'Ele é muito educado.'],
    ['maleducado', 'grosseiro', 'adjetivo', 'Ese comentario fue maleducado.', 'Aquele comentário foi grosseiro.'],
    ['cerca', 'perto', 'advérbio', 'Hay un parque cerca.', 'Tem um parque por perto.'],
    ['de inmediato', 'imediatamente', 'advérbio', 'Llámame de inmediato.', 'Me ligue imediatamente.'],
    ['últimamente', 'ultimamente', 'advérbio', 'Últimamente me mudé aquí.', 'Ultimamente eu me mudei para cá.'],
    ['el itinerario', 'roteiro (de viagem)', 'substantivo', 'Aquí está nuestro itinerario.', 'Aqui está nosso roteiro de viagem.'],
    ['el reembolso', 'reembolso', 'substantivo', 'Quiero un reembolso.', 'Quero um reembolso.'],
    ['el descuento', 'desconto', 'substantivo', '¿Hay descuento?', 'Tem desconto?'],
    ['el cruce', 'cruzamento', 'substantivo', 'Gira a la izquierda en el cruce.', 'Vire à esquerda no cruzamento.'],
    ['la acera', 'calçada', 'substantivo', 'Camina por la acera.', 'Ande na calçada.'],
  ],
  B1: [
    ['la carga de trabajo', 'carga de trabalho', 'substantivo', 'Mi carga de trabajo es alta este mes.', 'Minha carga de trabalho está pesada este mês.'],
    ['el compañero', 'colega de trabalho', 'substantivo', 'Es un compañero servicial.', 'Ele é um colega prestativo.'],
    ['el ascenso', 'promoção (cargo)', 'substantivo', 'Consiguió un ascenso.', 'Ele conseguiu uma promoção.'],
    ['la dimisión', 'demissão (pedido)', 'substantivo', 'Presentó su dimisión.', 'Ela apresentou o pedido de demissão.'],
    ['el sueldo', 'salário', 'substantivo', 'El sueldo es competitivo.', 'O salário é competitivo.'],
    ['la matrícula', 'mensalidade escolar', 'substantivo', 'La matrícula subió este año.', 'A mensalidade aumentou esse ano.'],
    ['la beca', 'bolsa de estudos', 'substantivo', 'Ganó una beca.', 'Ela ganhou uma bolsa de estudos.'],
    ['flexible', 'flexível', 'adjetivo', 'Mi horario es flexible.', 'Minha agenda é flexível.'],
    ['estresante', 'estressante', 'adjetivo', 'Este trabajo es estresante.', 'Esse trabalho é estressante.'],
    ['eficiente', 'eficiente', 'adjetivo', 'El nuevo sistema es eficiente.', 'O sistema novo é eficiente.'],
    ['obsoleto', 'desatualizado', 'adjetivo', 'Este software está obsoleto.', 'Esse software está desatualizado.'],
    ['gradualmente', 'gradualmente', 'advérbio', 'Los precios subieron gradualmente.', 'Os preços subiram gradualmente.'],
    ['finalmente', 'finalmente / no fim', 'advérbio', 'Finalmente llegamos a un acuerdo.', 'No fim, chegamos a um acordo.'],
    ['el electrodoméstico', 'eletrodoméstico', 'substantivo', 'La lavadora es un electrodoméstico.', 'A máquina de lavar é um eletrodoméstico.'],
    ['la garantía', 'garantia (produto)', 'substantivo', 'La garantía dura dos años.', 'A garantia dura dois anos.'],
    ['la suscripción', 'assinatura (serviço)', 'substantivo', 'Cancelé mi suscripción.', 'Cancelei minha assinatura.'],
    ['el trayecto', 'trajeto casa-trabalho', 'substantivo', 'Mi trayecto dura una hora.', 'Meu trajeto até o trabalho leva uma hora.'],
    ['agobiado', 'sobrecarregado', 'adjetivo', 'Me siento agobiado en el trabajo.', 'Me sinto sobrecarregado no trabalho.'],
    ['motivado', 'motivado', 'adjetivo', 'El equipo está motivado.', 'A equipe está motivada.'],
    ['el trámite', 'processo burocrático', 'substantivo', 'El trámite tardó semanas.', 'O processo burocrático demorou semanas.'],
  ],
  B2: [
    ['la disparidad', 'disparidade', 'substantivo', 'Hay una gran disparidad de ingresos.', 'Há uma grande disparidade de renda.'],
    ['la previsión', 'previsão / visão de futuro', 'substantivo', 'El plan mostró verdadera previsión.', 'O plano mostrou visão de futuro de verdade.'],
    ['la sostenibilidad', 'sustentabilidade', 'substantivo', 'La sostenibilidad es una prioridad ahora.', 'Sustentabilidade é prioridade agora.'],
    ['la desigualdad', 'desigualdade', 'substantivo', 'La desigualdad sigue siendo un gran problema.', 'A desigualdade continua sendo um grande problema.'],
    ['la polémica', 'controvérsia', 'substantivo', 'La decisión causó polémica.', 'A decisão causou controvérsia.'],
    ['el resquicio', 'brecha (na lei)', 'substantivo', 'Encontraron un resquicio legal.', 'Encontraram uma brecha legal.'],
    ['la rendición de cuentas', 'responsabilização', 'substantivo', 'Necesitamos más rendición de cuentas.', 'Precisamos de mais responsabilização.'],
    ['la transparencia', 'transparência', 'substantivo', 'La empresa carece de transparencia.', 'A empresa carece de transparência.'],
    ['verosímil', 'plausível', 'adjetivo', 'Esa explicación parece verosímil.', 'Aquela explicação parece plausível.'],
    ['ambiguo', 'ambíguo', 'adjetivo', 'La redacción es ambigua.', 'A redação é ambígua.'],
    ['resiliente', 'resiliente', 'adjetivo', 'La economía resultó resiliente.', 'A economia se mostrou resiliente.'],
    ['volátil', 'volátil', 'adjetivo', 'El mercado está volátil.', 'O mercado está volátil.'],
    ['posiblemente', 'possivelmente / sem dúvida', 'advérbio', 'Esta es, posiblemente, la mejor opción.', 'Essa é, sem dúvida, a melhor opção.'],
    ['inevitablemente', 'inevitavelmente', 'advérbio', 'Los costos subirán inevitablemente.', 'Os custos vão subir inevitavelmente.'],
    ['la reacción negativa', 'reação negativa', 'substantivo', 'La política provocó una reacción negativa.', 'A política causou uma reação negativa.'],
    ['el estereotipo', 'estereótipo', 'substantivo', 'El anuncio se apoya en un estereotipo.', 'O anúncio se apoia num estereótipo.'],
    ['la solución provisional', 'solução paliativa', 'substantivo', 'Encontramos una solución provisional.', 'Encontramos uma solução paliativa temporária.'],
    ['el hito', 'marco (conquista)', 'substantivo', 'El lanzamiento fue un gran hito.', 'O lançamento foi um grande marco.'],
    ['el escrutinio', 'escrutínio', 'substantivo', 'El acuerdo está bajo escrutinio.', 'O acordo está sob escrutínio.'],
    ['tangible', 'tangível', 'adjetivo', 'Necesitamos resultados tangibles.', 'Precisamos de resultados tangíveis.'],
  ],
  C1: [
    ['el dilema', 'dilema', 'substantivo', 'Es un verdadero dilema.', 'É um dilema difícil de verdade.'],
    ['el precepto', 'preceito / princípio', 'substantivo', 'Ese es un precepto central de la teoría.', 'Esse é um princípio central da teoria.'],
    ['la repercusión', 'repercussão', 'substantivo', 'Considera primero las repercusiones.', 'Considere as repercussões primeiro.'],
    ['la sutileza', 'sutileza', 'substantivo', 'La traducción perdió alguna sutileza.', 'A tradução perdeu alguma sutileza.'],
    ['el precedente', 'precedente', 'substantivo', 'Este caso sienta un precedente.', 'Esse caso cria um precedente.'],
    ['pragmático', 'pragmático', 'adjetivo', 'Adoptó un enfoque pragmático.', 'Ela adotou uma abordagem pragmática.'],
    ['redundante', 'redundante', 'adjetivo', 'Esa cláusula es redundante.', 'Aquela cláusula é redundante.'],
    ['sin precedentes', 'sem precedentes', 'adjetivo', 'Fue una crisis sin precedentes.', 'Foi uma crise sem precedentes.'],
    ['el consenso', 'consenso', 'substantivo', 'Llegamos a un consenso.', 'Chegamos a um consenso.'],
    ['el plan de contingencia', 'plano de contingência', 'substantivo', 'Necesitamos un plan de contingencia.', 'Precisamos de um plano de contingência.'],
    ['la falacia', 'falácia', 'substantivo', 'Esa es una falacia común.', 'Essa é uma falácia comum.'],
    ['la paradoja', 'paradoxo', 'substantivo', 'Es una paradoja extraña.', 'É um paradoxo estranho.'],
    ['escrupuloso', 'escrupuloso', 'adjetivo', 'Es escrupuloso con los detalles.', 'Ele é escrupuloso com detalhes.'],
    ['franco', 'sincero / franco', 'adjetivo', 'Seamos francos sobre los riesgos.', 'Vamos ser francos sobre os riscos.'],
    ['meticuloso', 'meticuloso', 'adjetivo', 'Es meticulosa con los datos.', 'Ela é meticulosa com os dados.'],
    ['aparentemente', 'aparentemente', 'advérbio', 'Es una tarea aparentemente simple.', 'É uma tarefa aparentemente simples.'],
    ['independientemente', 'independentemente', 'advérbio', 'Seguimos adelante, independientemente de los riesgos.', 'Seguimos em frente, independentemente dos riscos.'],
    ['presumiblemente', 'possivelmente / é presumível que', 'advérbio', 'Presumiblemente podría funcionar.', 'É presumível que possa funcionar.'],
    ['el escepticismo', 'ceticismo', 'substantivo', 'Recibieron la noticia con escepticismo.', 'Receberam a notícia com ceticismo.'],
    ['la incertidumbre', 'incerteza', 'substantivo', 'Vivimos en tiempos de incertidumbre.', 'Vivemos em tempos de incerteza.'],
  ],
  C2: [
    ['la premura', 'urgência / pressa premente', 'substantivo', 'La premura de la situación exigía acción.', 'A urgência da situação exigia ação.'],
    ['el circunloquio', 'circunlóquio', 'substantivo', 'Evita el circunloquio en textos legales.', 'Evite circunlóquios em textos jurídicos.'],
    ['la ecuanimidad', 'equanimidade', 'substantivo', 'Recibió la noticia con ecuanimidad.', 'Ela recebeu a notícia com equanimidade.'],
    ['la ofuscación', 'obscurecimento proposital', 'substantivo', 'El informe está lleno de ofuscación.', 'O relatório está cheio de obscurecimento proposital.'],
    ['somero', 'superficial / feito por obrigação', 'adjetivo', 'Fue una disculpa somera.', 'Foi um pedido de desculpas superficial.'],
    ['inefable', 'indescritível', 'adjetivo', 'La vista era inefable.', 'A vista era indescritível.'],
    ['omnipresente', 'onipresente', 'adjetivo', 'Los móviles son omnipresentes ahora.', 'Os celulares são onipresentes hoje.'],
    ['idiosincrático', 'idiossincrático', 'adjetivo', 'Su estilo es bastante idiosincrático.', 'O estilo dele é bem idiossincrático.'],
    ['precario', 'precário / instável', 'adjetivo', 'Su posición es, en el mejor de los casos, precaria.', 'A posição deles é, no máximo, precária.'],
    ['insidioso', 'insidioso', 'adjetivo', 'Es un problema insidioso.', 'É um problema insidioso.'],
    ['la yuxtaposición', 'justaposição', 'substantivo', 'La yuxtaposición de lo viejo y lo nuevo impresiona.', 'A justaposição do velho com o novo impressiona.'],
    ['la reivindicación', 'reconhecimento de razão', 'substantivo', 'Los resultados se sintieron como una reivindicación.', 'Os resultados pareceram lhe dar razão.'],
    ['la anuencia', 'anuência silenciosa', 'substantivo', 'Su silencio implicaba anuencia.', 'O silêncio dele implicava anuência.'],
    ['inmutable', 'imutável', 'adjetivo', 'Algunas reglas parecen inmutables.', 'Algumas regras parecem imutáveis.'],
    ['presunto', 'aparente (mas duvidoso)', 'adjetivo', 'La presunta razón fue el costo.', 'A razão aparente foi o custo.'],
    ['subrepticio', 'sub-reptício / dissimulado', 'adjetivo', 'Una mirada subrepticia a las notas.', 'Um olhar dissimulado para as anotações.'],
    ['la vicisitud', 'vicissitude', 'substantivo', 'Las vicisitudes de la vida la formaron.', 'As vicissitudes da vida a moldaram.'],
    ['perentorio', 'peremptório', 'adjetivo', 'Su tono fue perentorio.', 'O tom dele foi peremptório.'],
    ['al parecer', 'ao que parece / supostamente', 'advérbio', 'Al parecer, el plan es simple.', 'Ao que parece, o plano é simples.'],
    ['hasta la fecha', 'até agora / até então', 'advérbio', 'Surgió un hecho desconocido hasta la fecha.', 'Surgiu um fato desconhecido até então.'],
  ],
};
