/** Francês — vocabulário de ampliação. Nenhuma palavra repete o catálogo existente. */

import type { LatinByLevel } from './entry';

export const FR: LatinByLevel = {
  A1: [
    ['la table', 'mesa', 'substantivo', 'La table est grande.', 'A mesa é grande.'],
    ['la chaise', 'cadeira', 'substantivo', 'Assieds-toi sur la chaise.', 'Sente-se na cadeira.'],
    ['la porte', 'porta', 'substantivo', 'Ferme la porte.', 'Feche a porta.'],
    ['la fenêtre', 'janela', 'substantivo', 'Ouvre la fenêtre.', 'Abra a janela.'],
    ['le lit', 'cama', 'substantivo', 'Je dors dans mon lit.', 'Eu durmo na minha cama.'],
    ['la cuisine', 'cozinha', 'substantivo', 'Elle cuisine dans la cuisine.', 'Ela cozinha na cozinha.'],
    ['la salle de bain', 'banheiro', 'substantivo', 'La salle de bain est à l’étage.', 'O banheiro é lá em cima.'],
    ['le frère', 'irmão', 'substantivo', 'Mon frère est grand.', 'Meu irmão é alto.'],
    ['la sœur', 'irmã', 'substantivo', 'Ma sœur est médecin.', 'Minha irmã é médica.'],
    ['le père', 'pai', 'substantivo', 'Mon père travaille beaucoup.', 'Meu pai trabalha muito.'],
    ['la mère', 'mãe', 'substantivo', 'Ma mère cuisine bien.', 'Minha mãe cozinha bem.'],
    ['le bébé', 'bebê', 'substantivo', 'Le bébé dort.', 'O bebê está dormindo.'],
    ['le chien', 'cachorro', 'substantivo', 'Le chien aboie.', 'O cachorro está latindo.'],
    ['le chat', 'gato', 'substantivo', 'Le chat dort toute la journée.', 'O gato dorme o dia todo.'],
    ['rouge', 'vermelho', 'adjetivo', 'La voiture est rouge.', 'O carro é vermelho.'],
    ['bleu', 'azul', 'adjetivo', 'Le ciel est bleu.', 'O céu é azul.'],
    ['haut', 'alto', 'adjetivo', 'L’immeuble est haut.', 'O prédio é alto.'],
    ['court', 'curto', 'adjetivo', 'Mes cheveux sont courts.', 'Meu cabelo é curto.'],
    ['chaud', 'quente', 'adjetivo', 'La soupe est chaude.', 'A sopa está quente.'],
    ['froid', 'frio', 'adjetivo', 'L’eau est froide.', 'A água está fria.'],
  ],
  A2: [
    ['la course', 'tarefa rápida (fora de casa)', 'substantivo', 'J’ai quelques courses à faire.', 'Tenho umas tarefas para resolver hoje.'],
    ['la facture', 'fatura', 'substantivo', 'Envoie-moi la facture, s’il te plaît.', 'Me manda a fatura, por favor.'],
    ['le voisin', 'vizinho', 'substantivo', 'Mon voisin est sympathique.', 'Meu vizinho é simpático.'],
    ['le propriétaire', 'senhorio', 'substantivo', 'Le propriétaire a réparé le robinet.', 'O senhorio consertou a torneira.'],
    ['les meubles', 'móveis', 'substantivo', 'Nous avons acheté de nouveaux meubles.', 'Compramos móveis novos.'],
    ['la pharmacie', 'farmácia', 'substantivo', 'La pharmacie ouvre tard.', 'A farmácia abre até tarde.'],
    ['le symptôme', 'sintoma', 'substantivo', 'Décris tes symptômes.', 'Descreva seus sintomas.'],
    ['la fièvre', 'febre', 'substantivo', 'Elle a de la fièvre.', 'Ela está com febre.'],
    ['spacieux', 'espaçoso', 'adjetivo', 'L’appartement est spacieux.', 'O apartamento é espaçoso.'],
    ['épuisé', 'exausto', 'adjetivo', 'Je suis épuisé aujourd’hui.', 'Estou exausto hoje.'],
    ['poli', 'educado', 'adjetivo', 'Il est très poli.', 'Ele é muito educado.'],
    ['impoli', 'grosseiro', 'adjetivo', 'Ce commentaire était impoli.', 'Aquele comentário foi grosseiro.'],
    ['tout près', 'perto', 'advérbio', 'Il y a un parc tout près.', 'Tem um parque por perto.'],
    ['immédiatement', 'imediatamente', 'advérbio', 'Appelle-moi immédiatement.', 'Me ligue imediatamente.'],
    ['dernièrement', 'ultimamente', 'advérbio', 'Je me suis installé ici dernièrement.', 'Ultimamente eu me mudei para cá.'],
    ['l’itinéraire', 'roteiro (de viagem)', 'substantivo', 'Voici notre itinéraire.', 'Aqui está nosso roteiro de viagem.'],
    ['le remboursement', 'reembolso', 'substantivo', 'Je veux un remboursement.', 'Quero um reembolso.'],
    ['la réduction', 'desconto', 'substantivo', 'Il y a une réduction ?', 'Tem desconto?'],
    ['le carrefour', 'cruzamento', 'substantivo', 'Tourne à gauche au carrefour.', 'Vire à esquerda no cruzamento.'],
    ['le trottoir', 'calçada', 'substantivo', 'Marche sur le trottoir.', 'Ande na calçada.'],
  ],
  B1: [
    ['la charge de travail', 'carga de trabalho', 'substantivo', 'Ma charge de travail est lourde ce mois-ci.', 'Minha carga de trabalho está pesada este mês.'],
    ['le collègue', 'colega de trabalho', 'substantivo', 'C’est un collègue serviable.', 'Ele é um colega prestativo.'],
    ['la promotion', 'promoção (cargo)', 'substantivo', 'Il a eu une promotion.', 'Ele conseguiu uma promoção.'],
    ['la démission', 'demissão (pedido)', 'substantivo', 'Elle a remis sa démission.', 'Ela entregou o pedido de demissão.'],
    ['le salaire', 'salário', 'substantivo', 'Le salaire est compétitif.', 'O salário é competitivo.'],
    ['les frais de scolarité', 'mensalidade escolar', 'substantivo', 'Les frais de scolarité ont augmenté.', 'A mensalidade aumentou esse ano.'],
    ['la bourse', 'bolsa de estudos', 'substantivo', 'Elle a obtenu une bourse.', 'Ela ganhou uma bolsa de estudos.'],
    ['flexible', 'flexível', 'adjetivo', 'Mon emploi du temps est flexible.', 'Minha agenda é flexível.'],
    ['stressant', 'estressante', 'adjetivo', 'Ce travail est stressant.', 'Esse trabalho é estressante.'],
    ['efficace', 'eficiente', 'adjetivo', 'Le nouveau système est efficace.', 'O sistema novo é eficiente.'],
    ['obsolète', 'desatualizado', 'adjetivo', 'Ce logiciel est obsolète.', 'Esse software está desatualizado.'],
    ['graduellement', 'gradualmente', 'advérbio', 'Les prix ont augmenté graduellement.', 'Os preços subiram gradualmente.'],
    ['au bout du compte', 'no fim das contas', 'advérbio', 'Au bout du compte, nous sommes tombés d’accord.', 'No fim das contas, chegamos a um acordo.'],
    ['l’électroménager', 'eletrodoméstico', 'substantivo', 'Le lave-linge est un électroménager.', 'A máquina de lavar é um eletrodoméstico.'],
    ['la garantie', 'garantia (produto)', 'substantivo', 'La garantie dure deux ans.', 'A garantia dura dois anos.'],
    ['l’abonnement', 'assinatura (serviço)', 'substantivo', 'J’ai annulé mon abonnement.', 'Cancelei minha assinatura.'],
    ['le trajet', 'trajeto casa-trabalho', 'substantivo', 'Mon trajet dure une heure.', 'Meu trajeto até o trabalho leva uma hora.'],
    ['débordé', 'sobrecarregado', 'adjetivo', 'Je me sens débordé au travail.', 'Me sinto sobrecarregado no trabalho.'],
    ['motivé', 'motivado', 'adjetivo', 'L’équipe est motivée.', 'A equipe está motivada.'],
    ['la démarche', 'processo burocrático', 'substantivo', 'La démarche a pris des semaines.', 'O processo burocrático levou semanas.'],
  ],
  B2: [
    ['la disparité', 'disparidade', 'substantivo', 'Il y a une grande disparité de revenus.', 'Há uma grande disparidade de renda.'],
    ['la prévoyance', 'previsão / visão de futuro', 'substantivo', 'Le plan a montré une vraie prévoyance.', 'O plano mostrou visão de futuro de verdade.'],
    ['la durabilité', 'sustentabilidade', 'substantivo', 'La durabilité est une priorité maintenant.', 'Sustentabilidade é prioridade agora.'],
    ['l’inégalité', 'desigualdade', 'substantivo', 'L’inégalité reste un problème majeur.', 'A desigualdade continua sendo um grande problema.'],
    ['la polémique', 'controvérsia', 'substantivo', 'La décision a suscité une polémique.', 'A decisão causou controvérsia.'],
    ['la faille', 'brecha (na lei)', 'substantivo', 'Ils ont trouvé une faille juridique.', 'Encontraram uma brecha legal.'],
    ['la redevabilité', 'responsabilização', 'substantivo', 'Nous avons besoin de plus de redevabilité.', 'Precisamos de mais responsabilização.'],
    ['la transparence', 'transparência', 'substantivo', 'L’entreprise manque de transparence.', 'A empresa carece de transparência.'],
    ['vraisemblable', 'plausível', 'adjetivo', 'Cette explication semble vraisemblable.', 'Aquela explicação parece plausível.'],
    ['ambigu', 'ambíguo', 'adjetivo', 'La formulation est ambiguë.', 'A redação é ambígua.'],
    ['résilient', 'resiliente', 'adjetivo', 'L’économie s’est montrée résiliente.', 'A economia se mostrou resiliente.'],
    ['volatil', 'volátil', 'adjetivo', 'Le marché est volatil.', 'O mercado está volátil.'],
    ['sans doute', 'sem dúvida / possivelmente', 'advérbio', 'C’est sans doute la meilleure option.', 'Essa é, sem dúvida, a melhor opção.'],
    ['inévitablement', 'inevitavelmente', 'advérbio', 'Les coûts vont inévitablement augmenter.', 'Os custos vão subir inevitavelmente.'],
    ['la réaction négative', 'reação negativa', 'substantivo', 'La politique a provoqué une réaction négative.', 'A política causou uma reação negativa.'],
    ['le stéréotype', 'estereótipo', 'substantivo', 'La publicité s’appuie sur un stéréotype.', 'O anúncio se apoia num estereótipo.'],
    ['la solution provisoire', 'solução paliativa', 'substantivo', 'Nous avons trouvé une solution provisoire.', 'Encontramos uma solução paliativa temporária.'],
    ['le jalon', 'marco (conquista)', 'substantivo', 'Le lancement a été un jalon important.', 'O lançamento foi um marco importante.'],
    ['l’examen minutieux', 'escrutínio', 'substantivo', 'L’accord fait l’objet d’un examen minutieux.', 'O acordo está sob escrutínio.'],
    ['tangible', 'tangível', 'adjetivo', 'Nous avons besoin de résultats tangibles.', 'Precisamos de resultados tangíveis.'],
  ],
  C1: [
    ['le dilemme', 'dilema', 'substantivo', 'C’est un vrai dilemme.', 'É um dilema difícil de verdade.'],
    ['le précepte', 'preceito / princípio', 'substantivo', 'C’est un précepte central de la théorie.', 'Esse é um princípio central da teoria.'],
    ['la répercussion', 'repercussão', 'substantivo', 'Considère d’abord les répercussions.', 'Considere as repercussões primeiro.'],
    ['la subtilité', 'sutileza', 'substantivo', 'La traduction a perdu une part de subtilité.', 'A tradução perdeu alguma sutileza.'],
    ['le précédent', 'precedente', 'substantivo', 'Cette affaire crée un précédent.', 'Esse caso cria um precedente.'],
    ['pragmatique', 'pragmático', 'adjetivo', 'Elle a adopté une approche pragmatique.', 'Ela adotou uma abordagem pragmática.'],
    ['redondant', 'redundante', 'adjetivo', 'Cette clause est redondante.', 'Aquela cláusula é redundante.'],
    ['sans précédent', 'sem precedentes', 'adjetivo', 'C’était une crise sans précédent.', 'Foi uma crise sem precedentes.'],
    ['le consensus', 'consenso', 'substantivo', 'Nous sommes parvenus à un consensus.', 'Chegamos a um consenso.'],
    ['le plan de secours', 'plano de contingência', 'substantivo', 'Il nous faut un plan de secours.', 'Precisamos de um plano de contingência.'],
    ['le sophisme', 'falácia', 'substantivo', 'C’est un sophisme courant.', 'Essa é uma falácia comum.'],
    ['le paradoxe', 'paradoxo', 'substantivo', 'C’est un étrange paradoxe.', 'É um paradoxo estranho.'],
    ['scrupuleux', 'escrupuloso', 'adjetivo', 'Il est scrupuleux sur les détails.', 'Ele é escrupuloso com detalhes.'],
    ['franc', 'sincero / franco', 'adjetivo', 'Soyons francs sur les risques.', 'Vamos ser francos sobre os riscos.'],
    ['méticuleux', 'meticuloso', 'adjetivo', 'Elle est méticuleuse avec les données.', 'Ela é meticulosa com os dados.'],
    ['apparemment', 'aparentemente', 'advérbio', 'C’est une tâche apparemment simple.', 'É uma tarefa aparentemente simples.'],
    ['quels que soient', 'independentemente de', 'advérbio', 'Nous continuons, quels que soient les risques.', 'Seguimos em frente, independentemente dos riscos.'],
    ['vraisemblablement', 'possivelmente / é provável que', 'advérbio', 'Cela pourrait vraisemblablement fonctionner.', 'É provável que funcione.'],
    ['le scepticisme', 'ceticismo', 'substantivo', 'Ils ont accueilli la nouvelle avec scepticisme.', 'Receberam a notícia com ceticismo.'],
    ['l’incertitude', 'incerteza', 'substantivo', 'Nous vivons une période d’incertitude.', 'Vivemos um período de incerteza.'],
  ],
  C2: [
    ['l’urgence', 'urgência premente', 'substantivo', 'L’urgence de la situation exigeait une action.', 'A urgência da situação exigia ação.'],
    ['la circonlocution', 'circunlóquio', 'substantivo', 'Évite la circonlocution dans les textes juridiques.', 'Evite circunlóquios em textos jurídicos.'],
    ['l’équanimité', 'equanimidade', 'substantivo', 'Elle a accueilli la nouvelle avec équanimité.', 'Ela recebeu a notícia com equanimidade.'],
    ['l’obscurcissement', 'obscurecimento proposital', 'substantivo', 'Le rapport est plein d’obscurcissement.', 'O relatório está cheio de obscurecimento proposital.'],
    ['sommaire', 'superficial / feito por obrigação', 'adjetivo', 'C’était des excuses sommaires.', 'Foi um pedido de desculpas superficial.'],
    ['ineffable', 'indescritível', 'adjetivo', 'La vue était ineffable.', 'A vista era indescritível.'],
    ['omniprésent', 'onipresente', 'adjetivo', 'Les smartphones sont omniprésents aujourd’hui.', 'Os smartphones são onipresentes hoje.'],
    ['idiosyncrasique', 'idiossincrático', 'adjetivo', 'Son style est assez idiosyncrasique.', 'O estilo dele é bem idiossincrático.'],
    ['précaire', 'precário / instável', 'adjetivo', 'Leur position est, au mieux, précaire.', 'A posição deles é, no máximo, precária.'],
    ['insidieux', 'insidioso', 'adjetivo', 'C’est un problème insidieux.', 'É um problema insidioso.'],
    ['la juxtaposition', 'justaposição', 'substantivo', 'La juxtaposition de l’ancien et du nouveau frappe.', 'A justaposição do velho com o novo impressiona.'],
    ['la vindicte', 'reconhecimento de razão (vingativo)', 'substantivo', 'Les résultats ressemblaient à une vindicte.', 'Os resultados pareceram uma vingança justificada.'],
    ['l’acquiescement', 'anuência silenciosa', 'substantivo', 'Son silence impliquait un acquiescement.', 'O silêncio dele implicava anuência.'],
    ['immuable', 'imutável', 'adjetivo', 'Certaines règles semblent immuables.', 'Algumas regras parecem imutáveis.'],
    ['ostensible', 'aparente (mas duvidoso)', 'adjetivo', 'La raison ostensible était le coût.', 'A razão aparente foi o custo.'],
    ['subreptice', 'sub-reptício / dissimulado', 'adjetivo', 'Un regard subreptice vers les notes.', 'Um olhar dissimulado para as anotações.'],
    ['la vicissitude', 'vicissitude', 'substantivo', 'Les vicissitudes de la vie l’ont façonnée.', 'As vicissitudes da vida a moldaram.'],
    ['péremptoire', 'peremptório', 'adjetivo', 'Son ton était péremptoire.', 'O tom dele foi peremptório.'],
    ['soi-disant', 'supostamente', 'advérbio', 'Soi-disant, le plan est simple.', 'Supostamente, o plano é simples.'],
    ['jusqu’à ce jour', 'até hoje / até então', 'advérbio', 'Un fait resté inconnu jusqu’à ce jour a émergé.', 'Um fato até então desconhecido surgiu.'],
  ],
};
