/** Italiano — vocabulário de ampliação. Nenhuma palavra repete o catálogo existente. */

import type { LatinByLevel } from './entry';

export const IT: LatinByLevel = {
  A1: [
    ['il tavolo', 'mesa', 'substantivo', 'Il tavolo è grande.', 'A mesa é grande.'],
    ['la sedia', 'cadeira', 'substantivo', 'Siediti sulla sedia.', 'Sente-se na cadeira.'],
    ['la porta', 'porta', 'substantivo', 'Chiudi la porta.', 'Feche a porta.'],
    ['la finestra', 'janela', 'substantivo', 'Apri la finestra.', 'Abra a janela.'],
    ['il letto', 'cama', 'substantivo', 'Dormo nel mio letto.', 'Eu durmo na minha cama.'],
    ['la cucina', 'cozinha', 'substantivo', 'Lei cucina in cucina.', 'Ela cozinha na cozinha.'],
    ['il bagno', 'banheiro', 'substantivo', 'Il bagno è di sopra.', 'O banheiro é lá em cima.'],
    ['il fratello', 'irmão', 'substantivo', 'Mio fratello è alto.', 'Meu irmão é alto.'],
    ['la sorella', 'irmã', 'substantivo', 'Mia sorella è medica.', 'Minha irmã é médica.'],
    ['il padre', 'pai', 'substantivo', 'Mio padre lavora molto.', 'Meu pai trabalha muito.'],
    ['la madre', 'mãe', 'substantivo', 'Mia madre cucina bene.', 'Minha mãe cozinha bem.'],
    ['il bambino', 'bebê / criança', 'substantivo', 'Il bambino dorme.', 'O bebê está dormindo.'],
    ['il cane', 'cachorro', 'substantivo', 'Il cane abbaia.', 'O cachorro está latindo.'],
    ['il gatto', 'gato', 'substantivo', 'Il gatto dorme tutto il giorno.', 'O gato dorme o dia todo.'],
    ['rosso', 'vermelho', 'adjetivo', 'L’auto è rossa.', 'O carro é vermelho.'],
    ['blu', 'azul', 'adjetivo', 'Il cielo è blu.', 'O céu é azul.'],
    ['alto', 'alto', 'adjetivo', 'L’edificio è alto.', 'O prédio é alto.'],
    ['corto', 'curto', 'adjetivo', 'I miei capelli sono corti.', 'Meu cabelo é curto.'],
    ['caldo', 'quente', 'adjetivo', 'La zuppa è calda.', 'A sopa está quente.'],
    ['freddo', 'frio', 'adjetivo', 'L’acqua è fredda.', 'A água está fria.'],
  ],
  A2: [
    ['la commissione', 'tarefa rápida (fora de casa)', 'substantivo', 'Ho delle commissioni da fare oggi.', 'Tenho umas tarefas para resolver hoje.'],
    ['la fattura', 'fatura', 'substantivo', 'Mandami la fattura, per favore.', 'Me manda a fatura, por favor.'],
    ['il vicino', 'vizinho', 'substantivo', 'Il mio vicino è simpatico.', 'Meu vizinho é simpático.'],
    ['il padrone di casa', 'senhorio', 'substantivo', 'Il padrone di casa ha riparato il rubinetto.', 'O senhorio consertou a torneira.'],
    ['i mobili', 'móveis', 'substantivo', 'Abbiamo comprato mobili nuovi.', 'Compramos móveis novos.'],
    ['la farmacia', 'farmácia', 'substantivo', 'La farmacia apre fino a tardi.', 'A farmácia abre até tarde.'],
    ['il sintomo', 'sintoma', 'substantivo', 'Descrivi i tuoi sintomi.', 'Descreva seus sintomas.'],
    ['la febbre', 'febre', 'substantivo', 'Ha la febbre.', 'Ela está com febre.'],
    ['spazioso', 'espaçoso', 'adjetivo', 'L’appartamento è spazioso.', 'O apartamento é espaçoso.'],
    ['esausto', 'exausto', 'adjetivo', 'Sono esausto oggi.', 'Estou exausto hoje.'],
    ['educato', 'educado', 'adjetivo', 'È molto educato.', 'Ele é muito educado.'],
    ['maleducato', 'grosseiro', 'adjetivo', 'Quel commento è stato maleducato.', 'Aquele comentário foi grosseiro.'],
    ['qui vicino', 'perto', 'advérbio', 'C’è un parco qui vicino.', 'Tem um parque por perto.'],
    ['subito', 'imediatamente', 'advérbio', 'Chiamami subito.', 'Me ligue imediatamente.'],
    ['ultimamente', 'ultimamente', 'advérbio', 'Mi sono trasferito qui ultimamente.', 'Ultimamente eu me mudei para cá.'],
    ['l’itinerario', 'roteiro (de viagem)', 'substantivo', 'Ecco il nostro itinerario.', 'Aqui está nosso roteiro de viagem.'],
    ['il rimborso', 'reembolso', 'substantivo', 'Voglio un rimborso.', 'Quero um reembolso.'],
    ['lo sconto', 'desconto', 'substantivo', 'C’è uno sconto?', 'Tem desconto?'],
    ['l’incrocio', 'cruzamento', 'substantivo', 'Gira a sinistra all’incrocio.', 'Vire à esquerda no cruzamento.'],
    ['il marciapiede', 'calçada', 'substantivo', 'Cammina sul marciapiede.', 'Ande na calçada.'],
  ],
  B1: [
    ['il carico di lavoro', 'carga de trabalho', 'substantivo', 'Il mio carico di lavoro è pesante questo mese.', 'Minha carga de trabalho está pesada este mês.'],
    ['il collega', 'colega de trabalho', 'substantivo', 'È un collega disponibile.', 'Ele é um colega prestativo.'],
    ['la promozione', 'promoção (cargo)', 'substantivo', 'Ha ottenuto una promozione.', 'Ele conseguiu uma promoção.'],
    ['le dimissioni', 'demissão (pedido)', 'substantivo', 'Ha presentato le dimissioni.', 'Ela apresentou o pedido de demissão.'],
    ['lo stipendio', 'salário', 'substantivo', 'Lo stipendio è competitivo.', 'O salário é competitivo.'],
    ['la retta scolastica', 'mensalidade escolar', 'substantivo', 'La retta scolastica è aumentata quest’anno.', 'A mensalidade aumentou esse ano.'],
    ['la borsa di studio', 'bolsa de estudos', 'substantivo', 'Ha vinto una borsa di studio.', 'Ela ganhou uma bolsa de estudos.'],
    ['flessibile', 'flexível', 'adjetivo', 'Il mio orario è flessibile.', 'Minha agenda é flexível.'],
    ['stressante', 'estressante', 'adjetivo', 'Questo lavoro è stressante.', 'Esse trabalho é estressante.'],
    ['efficiente', 'eficiente', 'adjetivo', 'Il nuovo sistema è efficiente.', 'O sistema novo é eficiente.'],
    ['obsoleto', 'desatualizado', 'adjetivo', 'Questo software è obsoleto.', 'Esse software está desatualizado.'],
    ['gradualmente', 'gradualmente', 'advérbio', 'I prezzi sono saliti gradualmente.', 'Os preços subiram gradualmente.'],
    ['alla fine dei conti', 'no fim das contas', 'advérbio', 'Alla fine dei conti abbiamo trovato un accordo.', 'No fim das contas, chegamos a um acordo.'],
    ['l’elettrodomestico', 'eletrodoméstico', 'substantivo', 'La lavatrice è un elettrodomestico.', 'A máquina de lavar é um eletrodoméstico.'],
    ['la garanzia', 'garantia (produto)', 'substantivo', 'La garanzia dura due anni.', 'A garantia dura dois anos.'],
    ['l’abbonamento', 'assinatura (serviço)', 'substantivo', 'Ho disdetto l’abbonamento.', 'Cancelei minha assinatura.'],
    ['il tragitto', 'trajeto casa-trabalho', 'substantivo', 'Il mio tragitto dura un’ora.', 'Meu trajeto até o trabalho leva uma hora.'],
    ['sopraffatto', 'sobrecarregado', 'adjetivo', 'Mi sento sopraffatto al lavoro.', 'Me sinto sobrecarregado no trabalho.'],
    ['motivato', 'motivado', 'adjetivo', 'La squadra è motivata.', 'A equipe está motivada.'],
    ['la pratica burocratica', 'processo burocrático', 'substantivo', 'La pratica ha richiesto settimane.', 'O processo burocrático levou semanas.'],
  ],
  B2: [
    ['la disparità', 'disparidade', 'substantivo', 'C’è una grande disparità di reddito.', 'Há uma grande disparidade de renda.'],
    ['la lungimiranza', 'previsão / visão de futuro', 'substantivo', 'Il piano ha mostrato vera lungimiranza.', 'O plano mostrou visão de futuro de verdade.'],
    ['la sostenibilità', 'sustentabilidade', 'substantivo', 'La sostenibilità è una priorità adesso.', 'Sustentabilidade é prioridade agora.'],
    ['la disuguaglianza', 'desigualdade', 'substantivo', 'La disuguaglianza resta un grosso problema.', 'A desigualdade continua sendo um grande problema.'],
    ['la polemica', 'controvérsia', 'substantivo', 'La decisione ha causato polemica.', 'A decisão causou controvérsia.'],
    ['la scappatoia', 'brecha (na lei)', 'substantivo', 'Hanno trovato una scappatoia legale.', 'Encontraram uma brecha legal.'],
    ['la responsabilizzazione', 'responsabilização', 'substantivo', 'Serve più responsabilizzazione.', 'Precisamos de mais responsabilização.'],
    ['la trasparenza', 'transparência', 'substantivo', 'L’azienda manca di trasparenza.', 'A empresa carece de transparência.'],
    ['verosimile', 'plausível', 'adjetivo', 'Quella spiegazione sembra verosimile.', 'Aquela explicação parece plausível.'],
    ['ambiguo', 'ambíguo', 'adjetivo', 'Il testo è ambiguo.', 'A redação é ambígua.'],
    ['resiliente', 'resiliente', 'adjetivo', 'L’economia si è dimostrata resiliente.', 'A economia se mostrou resiliente.'],
    ['volatile', 'volátil', 'adjetivo', 'Il mercato è volatile.', 'O mercado está volátil.'],
    ['probabilmente', 'possivelmente / provavelmente', 'advérbio', 'Questa è probabilmente la scelta migliore.', 'Essa é, provavelmente, a melhor opção.'],
    ['inevitabilmente', 'inevitavelmente', 'advérbio', 'I costi aumenteranno inevitabilmente.', 'Os custos vão subir inevitavelmente.'],
    ['la reazione negativa', 'reação negativa', 'substantivo', 'La politica ha causato una reazione negativa.', 'A política causou uma reação negativa.'],
    ['lo stereotipo', 'estereótipo', 'substantivo', 'La pubblicità si basa su uno stereotipo.', 'O anúncio se apoia num estereótipo.'],
    ['la soluzione provvisoria', 'solução paliativa', 'substantivo', 'Abbiamo trovato una soluzione provvisoria.', 'Encontramos uma solução paliativa.'],
    ['il traguardo raggiunto', 'marco (conquista)', 'substantivo', 'Il lancio è stato un grande traguardo.', 'O lançamento foi um grande marco.'],
    ['l’esame accurato', 'escrutínio', 'substantivo', 'L’accordo è sotto esame accurato.', 'O acordo está sob escrutínio.'],
    ['tangibile', 'tangível', 'adjetivo', 'Ci servono risultati tangibili.', 'Precisamos de resultados tangíveis.'],
  ],
  C1: [
    ['il dilemma', 'dilema', 'substantivo', 'È un vero dilemma.', 'É um dilema difícil de verdade.'],
    ['il precetto', 'preceito / princípio', 'substantivo', 'È un precetto centrale della teoria.', 'Esse é um princípio central da teoria.'],
    ['la ripercussione', 'repercussão', 'substantivo', 'Considera prima le ripercussioni.', 'Considere as repercussões primeiro.'],
    ['la sottigliezza', 'sutileza', 'substantivo', 'La traduzione ha perso qualche sottigliezza.', 'A tradução perdeu alguma sutileza.'],
    ['il precedente', 'precedente', 'substantivo', 'Questo caso crea un precedente.', 'Esse caso cria um precedente.'],
    ['pragmatico', 'pragmático', 'adjetivo', 'Ha adottato un approccio pragmatico.', 'Ela adotou uma abordagem pragmática.'],
    ['ridondante', 'redundante', 'adjetivo', 'Quella clausola è ridondante.', 'Aquela cláusula é redundante.'],
    ['senza precedenti', 'sem precedentes', 'adjetivo', 'È stata una crisi senza precedenti.', 'Foi uma crise sem precedentes.'],
    ['il consenso', 'consenso', 'substantivo', 'Siamo arrivati a un consenso.', 'Chegamos a um consenso.'],
    ['il piano di riserva', 'plano de contingência', 'substantivo', 'Ci serve un piano di riserva.', 'Precisamos de um plano de contingência.'],
    ['il sofisma', 'falácia', 'substantivo', 'È un sofisma comune.', 'Essa é uma falácia comum.'],
    ['il paradosso', 'paradoxo', 'substantivo', 'È uno strano paradosso.', 'É um paradoxo estranho.'],
    ['scrupoloso', 'escrupuloso', 'adjetivo', 'È scrupoloso con i dettagli.', 'Ele é escrupuloso com detalhes.'],
    ['franco', 'sincero / franco', 'adjetivo', 'Siamo franchi sui rischi.', 'Vamos ser francos sobre os riscos.'],
    ['meticoloso', 'meticuloso', 'adjetivo', 'È meticolosa con i dati.', 'Ela é meticulosa com os dados.'],
    ['apparentemente semplice', 'aparentemente simples', 'adjetivo', 'È un compito apparentemente semplice.', 'É uma tarefa aparentemente simples.'],
    ['a prescindere da', 'independentemente de', 'advérbio', 'Andiamo avanti, a prescindere dai rischi.', 'Seguimos em frente, independentemente dos riscos.'],
    ['presumibilmente', 'possivelmente / é presumível que', 'advérbio', 'Presumibilmente potrebbe funzionare.', 'É presumível que possa funcionar.'],
    ['lo scetticismo', 'ceticismo', 'substantivo', 'Hanno accolto la notizia con scetticismo.', 'Receberam a notícia com ceticismo.'],
    ['l’incertezza', 'incerteza', 'substantivo', 'Viviamo un periodo di incertezza.', 'Vivemos um período de incerteza.'],
  ],
  C2: [
    ['l’urgenza pressante', 'urgência premente', 'substantivo', 'L’urgenza della situazione richiedeva azione.', 'A urgência da situação exigia ação.'],
    ['la circonlocuzione', 'circunlóquio', 'substantivo', 'Evita la circonlocuzione nei testi legali.', 'Evite circunlóquios em textos jurídicos.'],
    ['l’equanimità', 'equanimidade', 'substantivo', 'Ha accolto la notizia con equanimità.', 'Ela recebeu a notícia com equanimidade.'],
    ['l’offuscamento', 'obscurecimento proposital', 'substantivo', 'Il rapporto è pieno di offuscamento.', 'O relatório está cheio de obscurecimento proposital.'],
    ['sbrigativo', 'superficial / feito por obrigação', 'adjetivo', 'È stata una scusa sbrigativa.', 'Foi um pedido de desculpas superficial.'],
    ['ineffabile', 'indescritível', 'adjetivo', 'La vista era ineffabile.', 'A vista era indescritível.'],
    ['onnipresente', 'onipresente', 'adjetivo', 'Gli smartphone sono onnipresenti ormai.', 'Os smartphones são onipresentes hoje.'],
    ['idiosincratico', 'idiossincrático', 'adjetivo', 'Il suo stile è piuttosto idiosincratico.', 'O estilo dele é bem idiossincrático.'],
    ['precario', 'precário / instável', 'adjetivo', 'La loro posizione è, nel migliore dei casi, precaria.', 'A posição deles é, no máximo, precária.'],
    ['insidioso', 'insidioso', 'adjetivo', 'È un problema insidioso.', 'É um problema insidioso.'],
    ['la giustapposizione', 'justaposição', 'substantivo', 'La giustapposizione tra vecchio e nuovo colpisce.', 'A justaposição do velho com o novo impressiona.'],
    ['la rivalsa', 'reconhecimento de razão (vingativo)', 'substantivo', 'I risultati sembravano una rivalsa.', 'Os resultados pareceram uma vingança justificada.'],
    ['l’acquiescenza', 'anuência silenciosa', 'substantivo', 'Il suo silenzio implicava acquiescenza.', 'O silêncio dele implicava anuência.'],
    ['immutabile', 'imutável', 'adjetivo', 'Alcune regole sembrano immutabili.', 'Algumas regras parecem imutáveis.'],
    ['presunto', 'aparente (mas duvidoso)', 'adjetivo', 'La presunta ragione era il costo.', 'A razão aparente foi o custo.'],
    ['furtivo', 'sub-reptício / dissimulado', 'adjetivo', 'Uno sguardo furtivo agli appunti.', 'Um olhar dissimulado para as anotações.'],
    ['la vicissitudine', 'vicissitude', 'substantivo', 'Le vicissitudini della vita l’hanno plasmata.', 'As vicissitudes da vida a moldaram.'],
    ['perentorio', 'peremptório', 'adjetivo', 'Il suo tono era perentorio.', 'O tom dele foi peremptório.'],
    ['a quanto pare', 'supostamente / ao que parece', 'advérbio', 'A quanto pare, il piano è semplice.', 'Ao que parece, o plano é simples.'],
    ['finora', 'até agora / até então', 'advérbio', 'È emerso un fatto sconosciuto finora.', 'Surgiu um fato até então desconhecido.'],
  ],
};
