/**
 * Japonês — vocabulário de ampliação.
 *
 * Nenhuma palavra repete o catálogo existente. Romanização obrigatória.
 */

import type { AsianByLevel } from './entry';

export const JA: AsianByLevel = {
  A1: [
    ['机', 'tsukue', 'mesa', 'substantivo', '机が大きいです。', 'Tsukue ga ookii desu.', 'A mesa é grande.'],
    ['椅子', 'isu', 'cadeira', 'substantivo', '椅子に座ってください。', 'Isu ni suwatte kudasai.', 'Sente-se na cadeira, por favor.'],
    ['ドア', 'doa', 'porta', 'substantivo', 'ドアを閉めてください。', 'Doa wo shimete kudasai.', 'Feche a porta, por favor.'],
    ['窓', 'mado', 'janela', 'substantivo', '窓を開けます。', 'Mado wo akemasu.', 'Vou abrir a janela.'],
    ['ベッド', 'beddo', 'cama', 'substantivo', '自分のベッドで寝ます。', 'Jibun no beddo de nemasu.', 'Eu durmo na minha cama.'],
    ['台所', 'daidokoro', 'cozinha', 'substantivo', '台所で料理します。', 'Daidokoro de ryouri shimasu.', 'Cozinho na cozinha.'],
    ['お風呂', 'ofuro', 'banheiro / banho', 'substantivo', 'お風呂は二階です。', 'Ofuro wa nikai desu.', 'O banheiro é no segundo andar.'],
    ['兄', 'ani', 'irmão mais velho', 'substantivo', '兄は背が高いです。', 'Ani wa se ga takai desu.', 'Meu irmão mais velho é alto.'],
    ['姉', 'ane', 'irmã mais velha', 'substantivo', '姉は医者です。', 'Ane wa isha desu.', 'Minha irmã mais velha é médica.'],
    ['父', 'chichi', 'pai', 'substantivo', '父はよく働きます。', 'Chichi wa yoku hatarakimasu.', 'Meu pai trabalha muito.'],
    ['母', 'haha', 'mãe', 'substantivo', '母は料理が上手です。', 'Haha wa ryouri ga jouzu desu.', 'Minha mãe cozinha bem.'],
    ['赤ちゃん', 'akachan', 'bebê', 'substantivo', '赤ちゃんが寝ています。', 'Akachan ga nete imasu.', 'O bebê está dormindo.'],
    ['犬', 'inu', 'cachorro', 'substantivo', '犬が吠えています。', 'Inu ga hoete imasu.', 'O cachorro está latindo.'],
    ['猫', 'neko', 'gato', 'substantivo', '猫は一日中寝ます。', 'Neko wa ichinichijuu nemasu.', 'O gato dorme o dia todo.'],
    ['赤い', 'akai', 'vermelho', 'adjetivo', '車が赤いです。', 'Kuruma ga akai desu.', 'O carro é vermelho.'],
    ['青い', 'aoi', 'azul', 'adjetivo', '空が青いです。', 'Sora ga aoi desu.', 'O céu é azul.'],
    ['高い', 'takai', 'alto', 'adjetivo', 'あの建物は高いです。', 'Ano tatemono wa takai desu.', 'Aquele prédio é alto.'],
    ['短い', 'mijikai', 'curto', 'adjetivo', '髪が短いです。', 'Kami ga mijikai desu.', 'Meu cabelo é curto.'],
    ['熱い', 'atsui', 'quente (ao toque)', 'adjetivo', 'スープが熱いです。', 'Suupu ga atsui desu.', 'A sopa está quente.'],
    ['冷たい', 'tsumetai', 'frio (ao toque)', 'adjetivo', '水が冷たいです。', 'Mizu ga tsumetai desu.', 'A água está fria.'],
  ],
  A2: [
    ['用事', 'youji', 'tarefa rápida (fora de casa)', 'substantivo', '今日は用事があります。', 'Kyou wa youji ga arimasu.', 'Tenho umas tarefas hoje.'],
    ['請求書', 'seikyuusho', 'fatura', 'substantivo', '請求書を送ってください。', 'Seikyuusho wo okutte kudasai.', 'Me manda a fatura, por favor.'],
    ['隣人', 'rinjin', 'vizinho', 'substantivo', '隣人は親切です。', 'Rinjin wa shinsetsu desu.', 'Meu vizinho é gentil.'],
    ['大家', 'ooya', 'senhorio', 'substantivo', '大家が蛇口を直しました。', 'Ooya ga jaguchi wo naoshimashita.', 'O senhorio consertou a torneira.'],
    ['家具', 'kagu', 'móveis', 'substantivo', '新しい家具を買いました。', 'Atarashii kagu wo kaimashita.', 'Compramos móveis novos.'],
    ['薬局', 'yakkyoku', 'farmácia', 'substantivo', '薬局は遅くまで開いています。', 'Yakkyoku wa osoku made aite imasu.', 'A farmácia abre até tarde.'],
    ['症状', 'shoujou', 'sintoma', 'substantivo', '症状を説明してください。', 'Shoujou wo setsumei shite kudasai.', 'Descreva seus sintomas, por favor.'],
    ['熱', 'netsu', 'febre', 'substantivo', '彼女は熱があります。', 'Kanojo wa netsu ga arimasu.', 'Ela está com febre.'],
    ['広々とした', 'hirobiro to shita', 'espaçoso', 'adjetivo', 'アパートは広々としています。', 'Apaato wa hirobiro to shite imasu.', 'O apartamento é espaçoso.'],
    ['疲れ切った', 'tsukarekitta', 'exausto', 'adjetivo', '今日は疲れ切っています。', 'Kyou wa tsukarekitte imasu.', 'Estou exausto hoje.'],
    ['丁寧な', 'teinei na', 'educado / cortês', 'adjetivo', '彼はとても丁寧です。', 'Kare wa totemo teinei desu.', 'Ele é muito educado.'],
    ['失礼な', 'shitsurei na', 'grosseiro / rude', 'adjetivo', 'あのコメントは失礼でした。', 'Ano komento wa shitsurei deshita.', 'Aquele comentário foi rude.'],
    ['近くに', 'chikaku ni', 'perto', 'advérbio', '近くに公園があります。', 'Chikaku ni kouen ga arimasu.', 'Tem um parque por perto.'],
    ['すぐに', 'sugu ni', 'imediatamente', 'advérbio', 'すぐに電話してください。', 'Sugu ni denwa shite kudasai.', 'Me ligue imediatamente.'],
    ['最近', 'saikin', 'recentemente / ultimamente', 'advérbio', '最近ここに引っ越しました。', 'Saikin koko ni hikkoshimashita.', 'Recentemente eu me mudei para cá.'],
    ['旅程', 'ryotei', 'roteiro (de viagem)', 'substantivo', 'これが私たちの旅程です。', 'Kore ga watashitachi no ryotei desu.', 'Aqui está nosso roteiro de viagem.'],
    ['払い戻し', 'haraimodoshi', 'reembolso', 'substantivo', '払い戻しをお願いします。', 'Haraimodoshi wo onegaishimasu.', 'Quero um reembolso, por favor.'],
    ['割引', 'waribiki', 'desconto', 'substantivo', '割引はありますか。', 'Waribiki wa arimasu ka.', 'Tem desconto?'],
    ['交差点', 'kousaten', 'cruzamento', 'substantivo', '交差点で左に曲がってください。', 'Kousaten de hidari ni magatte kudasai.', 'Vire à esquerda no cruzamento.'],
    ['歩道', 'hodou', 'calçada', 'substantivo', '歩道を歩いてください。', 'Hodou wo aruite kudasai.', 'Ande na calçada, por favor.'],
  ],
  B1: [
    ['業務量', 'gyoumuryou', 'carga de trabalho', 'substantivo', '今月は業務量が多いです。', 'Kongetsu wa gyoumuryou ga ooi desu.', 'Minha carga de trabalho está pesada este mês.'],
    ['同僚', 'douryou', 'colega de trabalho', 'substantivo', '彼は頼りになる同僚です。', 'Kare wa tayori ni naru douryou desu.', 'Ele é um colega em quem se pode confiar.'],
    ['昇進', 'shoushin', 'promoção (cargo)', 'substantivo', '彼は昇進しました。', 'Kare wa shoushin shimashita.', 'Ele foi promovido.'],
    ['退職届', 'taishokutodoke', 'pedido de demissão', 'substantivo', '彼女は退職届を出しました。', 'Kanojo wa taishokutodoke wo dashimashita.', 'Ela entregou o pedido de demissão.'],
    ['給料', 'kyuuryou', 'salário', 'substantivo', '給料は良いです。', 'Kyuuryou wa ii desu.', 'O salário é bom.'],
    ['学費', 'gakuhi', 'mensalidade escolar', 'substantivo', '学費が今年上がりました。', 'Gakuhi ga kotoshi agarimashita.', 'A mensalidade subiu este ano.'],
    ['奨学金', 'shougakukin', 'bolsa de estudos', 'substantivo', '彼女は奨学金をもらいました。', 'Kanojo wa shougakukin wo moraimashita.', 'Ela ganhou uma bolsa de estudos.'],
    ['柔軟な', 'juunan na', 'flexível', 'adjetivo', '私のスケジュールは柔軟です。', 'Watashi no sukejuuru wa juunan desu.', 'Minha agenda é flexível.'],
    ['ストレスが多い', 'sutoresu ga ooi', 'estressante', 'adjetivo', 'この仕事はストレスが多いです。', 'Kono shigoto wa sutoresu ga ooi desu.', 'Esse trabalho é estressante.'],
    ['効率的な', 'kouritsuteki na', 'eficiente', 'adjetivo', '新しいシステムは効率的です。', 'Atarashii shisutemu wa kouritsuteki desu.', 'O sistema novo é eficiente.'],
    ['時代遅れの', 'jidaiokure no', 'desatualizado', 'adjetivo', 'このソフトは時代遅れです。', 'Kono sofuto wa jidaiokure desu.', 'Esse software está desatualizado.'],
    ['徐々に', 'jojo ni', 'gradualmente', 'advérbio', '価格は徐々に上がりました。', 'Kakaku wa jojo ni agarimashita.', 'Os preços subiram gradualmente.'],
    ['結局のところ', 'kekkyoku no tokoro', 'no fim das contas', 'advérbio', '結局のところ、合意しました。', 'Kekkyoku no tokoro, goui shimashita.', 'No fim das contas, chegamos a um acordo.'],
    ['家電', 'kaden', 'eletrodoméstico', 'substantivo', '洗濯機は家電です。', 'Sentakuki wa kaden desu.', 'A máquina de lavar é um eletrodoméstico.'],
    ['保証', 'hoshou', 'garantia (produto)', 'substantivo', '保証は二年間です。', 'Hoshou wa ninenkan desu.', 'A garantia dura dois anos.'],
    ['定期購読', 'teikikoudoku', 'assinatura (serviço)', 'substantivo', '定期購読を解約しました。', 'Teikikoudoku wo kaiyaku shimashita.', 'Cancelei minha assinatura.'],
    ['通勤', 'tsuukin', 'trajeto casa-trabalho', 'substantivo', '通勤に一時間かかります。', 'Tsuukin ni ichijikan kakarimasu.', 'Meu trajeto até o trabalho leva uma hora.'],
    ['圧倒された', 'attou sareta', 'sobrecarregado', 'adjetivo', '仕事で圧倒されています。', 'Shigoto de attou sarete imasu.', 'Me sinto sobrecarregado no trabalho.'],
    ['やる気がある', 'yaruki ga aru', 'motivado', 'adjetivo', 'チームはやる気があります。', 'Chiimu wa yaruki ga arimasu.', 'A equipe está motivada.'],
    ['手続き', 'tetsuzuki', 'processo burocrático', 'substantivo', '手続きに数週間かかりました。', 'Tetsuzuki ni suushuukan kakarimashita.', 'O processo burocrático levou semanas.'],
  ],
  B2: [
    ['格差', 'kakusa', 'disparidade', 'substantivo', '所得に大きな格差があります。', 'Shotoku ni ookina kakusa ga arimasu.', 'Há uma grande disparidade de renda.'],
    ['先見の明', 'senken no mei', 'previsão / visão de futuro', 'substantivo', '計画は先見の明を示しました。', 'Keikaku wa senken no mei wo shimeshimashita.', 'O plano mostrou visão de futuro de verdade.'],
    ['持続可能性', 'jizoku kanousei', 'sustentabilidade', 'substantivo', '持続可能性が今は優先です。', 'Jizoku kanousei ga ima wa yuusen desu.', 'Sustentabilidade é prioridade agora.'],
    ['不平等', 'fubyoudou', 'desigualdade', 'substantivo', '不平等は依然として大きな問題です。', 'Fubyoudou wa izen toshite ookina mondai desu.', 'A desigualdade continua sendo um grande problema.'],
    ['論争', 'ronsou', 'controvérsia', 'substantivo', 'その決定は論争を招きました。', 'Sono kettei wa ronsou wo manekimashita.', 'A decisão causou controvérsia.'],
    ['抜け穴', 'nukeana', 'brecha (na lei)', 'substantivo', '彼らは法律の抜け穴を見つけました。', 'Karera wa houritsu no nukeana wo mitsukemashita.', 'Encontraram uma brecha legal.'],
    ['説明責任', 'setsumei sekinin', 'responsabilização', 'substantivo', 'もっと説明責任が必要です。', 'Motto setsumei sekinin ga hitsuyou desu.', 'Precisamos de mais responsabilização.'],
    ['透明性', 'toumeisei', 'transparência', 'substantivo', 'その会社は透明性に欠けています。', 'Sono kaisha wa toumeisei ni kakete imasu.', 'A empresa carece de transparência.'],
    ['もっともらしい', 'mottomorashii', 'plausível', 'adjetivo', 'その説明はもっともらしいです。', 'Sono setsumei wa mottomorashii desu.', 'Aquela explicação parece plausível.'],
    ['曖昧な', 'aimai na', 'ambíguo', 'adjetivo', '文言が曖昧です。', 'Mongon ga aimai desu.', 'A redação é ambígua.'],
    ['回復力のある', 'kaifukuryoku no aru', 'resiliente', 'adjetivo', '経済は回復力があると証明されました。', 'Keizai wa kaifukuryoku ga aru to shoumei saremashita.', 'A economia se mostrou resiliente.'],
    ['不安定な', 'fuantei na', 'volátil', 'adjetivo', '市場は不安定です。', 'Shijou wa fuantei desu.', 'O mercado está volátil.'],
    ['たぶん', 'tabun', 'possivelmente / provavelmente', 'advérbio', 'これがたぶん最善の選択肢です。', 'Kore ga tabun saizen no sentakushi desu.', 'Essa é, provavelmente, a melhor opção.'],
    ['避けられず', 'sakerarezu', 'inevitavelmente', 'advérbio', 'コストは避けられず上がります。', 'Kosuto wa sakerarezu agarimasu.', 'Os custos vão subir inevitavelmente.'],
    ['反発', 'hanpatsu', 'reação negativa', 'substantivo', 'その政策は反発を招きました。', 'Sono seisaku wa hanpatsu wo manekimashita.', 'A política causou uma reação negativa.'],
    ['固定観念', 'kotei kannen', 'estereótipo', 'substantivo', 'その広告は固定観念に頼っています。', 'Sono koukoku wa kotei kannen ni tayotte imasu.', 'O anúncio se apoia num estereótipo.'],
    ['暫定的な解決策', 'zantei teki na kaiketsusaku', 'solução paliativa', 'substantivo', '暫定的な解決策を見つけました。', 'Zantei teki na kaiketsusaku wo mitsukemashita.', 'Encontramos uma solução paliativa.'],
    ['節目', 'fushime', 'marco (conquista)', 'substantivo', 'ローンチは大きな節目でした。', 'Rounchi wa ookina fushime deshita.', 'O lançamento foi um grande marco.'],
    ['精査', 'seisa', 'escrutínio', 'substantivo', 'その取引は精査を受けています。', 'Sono torihiki wa seisa wo ukete imasu.', 'O acordo está sob escrutínio.'],
    ['具体的な', 'gutaiteki na', 'tangível / concreto', 'adjetivo', '具体的な結果が必要です。', 'Gutaiteki na kekka ga hitsuyou desu.', 'Precisamos de resultados concretos.'],
  ],
  C1: [
    ['ジレンマ', 'jirenma', 'dilema', 'substantivo', 'それは本当のジレンマです。', 'Sore wa hontou no jirenma desu.', 'É um dilema difícil de verdade.'],
    ['信条', 'shinjou', 'preceito / princípio', 'substantivo', 'それは理論の中心的な信条です。', 'Sore wa riron no chuushinteki na shinjou desu.', 'Esse é um princípio central da teoria.'],
    ['波及効果', 'hakyuu kouka', 'repercussão', 'substantivo', 'まず波及効果を考えてください。', 'Mazu hakyuu kouka wo kangaete kudasai.', 'Considere as repercussões primeiro.'],
    ['機微', 'kibi', 'sutileza / nuance delicada', 'substantivo', '翻訳で機微が失われました。', 'Honyaku de kibi ga ushinawaremashita.', 'A tradução perdeu alguma sutileza.'],
    ['先例', 'senrei', 'precedente', 'substantivo', 'この事例は先例を作ります。', 'Kono jirei wa senrei wo tsukurimasu.', 'Esse caso cria um precedente.'],
    ['実利的な', 'jitsuriteki na', 'pragmático', 'adjetivo', '彼女は実利的な手法を取りました。', 'Kanojo wa jitsuriteki na shuhou wo torimashita.', 'Ela adotou uma abordagem pragmática.'],
    ['冗長な', 'jouchou na', 'redundante', 'adjetivo', 'その条項は冗長です。', 'Sono joukou wa jouchou desu.', 'Aquela cláusula é redundante.'],
    ['前例のない', 'zenrei no nai', 'sem precedentes', 'adjetivo', '前例のない危機でした。', 'Zenrei no nai kiki deshita.', 'Foi uma crise sem precedentes.'],
    ['総意', 'souI', 'consenso', 'substantivo', '私たちは総意に達しました。', 'Watashitachi wa souI ni tasshimashita.', 'Chegamos a um consenso.'],
    ['緊急時対応計画', 'kinkyuuji taiou keikaku', 'plano de contingência', 'substantivo', '緊急時対応計画が必要です。', 'Kinkyuuji taiou keikaku ga hitsuyou desu.', 'Precisamos de um plano de contingência.'],
    ['詭弁', 'kiben', 'falácia / sofisma', 'substantivo', 'それはよくある詭弁です。', 'Sore wa yoku aru kiben desu.', 'Essa é uma falácia comum.'],
    ['逆説', 'gyakusetsu', 'paradoxo', 'substantivo', '奇妙な逆説です。', 'Kimyou na gyakusetsu desu.', 'É um paradoxo estranho.'],
    ['几帳面な', 'kichoumen na', 'escrupuloso / meticuloso', 'adjetivo', '彼は細部に几帳面です。', 'Kare wa saibu ni kichoumen desu.', 'Ele é escrupuloso com detalhes.'],
    ['率直な', 'sotchoku na', 'sincero / franco', 'adjetivo', 'リスクについて率直に話しましょう。', 'Risuku ni tsuite sotchoku ni hanashimashou.', 'Vamos ser francos sobre os riscos.'],
    ['入念な', 'nyuunen na', 'meticuloso', 'adjetivo', '彼女はデータに入念です。', 'Kanojo wa deeta ni nyuunen desu.', 'Ela é meticulosa com os dados.'],
    ['一見', 'ikken', 'aparentemente', 'advérbio', '一見単純な作業です。', 'Ikken tanjun na sagyou desu.', 'É uma tarefa aparentemente simples.'],
    ['～にかかわらず', 'ni kakawarazu', 'independentemente de', 'advérbio', 'リスクにかかわらず、続けます。', 'Risuku ni kakawarazu, tsuzukemasu.', 'Seguimos em frente, independentemente dos riscos.'],
    ['ひょっとして', 'hyottoshite', 'possivelmente (por acaso)', 'advérbio', 'ひょっとしてうまくいくかもしれません。', 'Hyottoshite umaku iku kamoshiremasen.', 'Possivelmente vai dar certo.'],
    ['懐疑', 'kaigi', 'ceticismo', 'substantivo', '彼らは懐疑的にその知らせを受け止めました。', 'Karera wa kaigiteki ni sono shirase wo uketomemashita.', 'Receberam a notícia com ceticismo.'],
    ['不確実性', 'fukakujitsusei', 'incerteza', 'substantivo', '私たちは不確実性の時代に生きています。', 'Watashitachi wa fukakujitsusei no jidai ni ikite imasu.', 'Vivemos um período de incerteza.'],
  ],
  C2: [
    ['切迫感', 'seppakukan', 'urgência premente', 'substantivo', '状況の切迫感が行動を求めました。', 'Joukyou no seppakukan ga koudou wo motomemashita.', 'A urgência da situação exigia ação.'],
    ['回りくどい表現', 'mawarikudoi hyougen', 'circunlóquio', 'substantivo', '法律文書では回りくどい表現を避けましょう。', 'Houritsu bunsho de wa mawarikudoi hyougen wo sakemashou.', 'Evite circunlóquios em textos jurídicos.'],
    ['平静', 'heisei', 'equanimidade', 'substantivo', '彼女はその知らせを平静に受け止めました。', 'Kanojo wa sono shirase wo heisei ni uketomemashita.', 'Ela recebeu a notícia com equanimidade.'],
    ['ごまかし', 'gomakashi', 'obscurecimento proposital', 'substantivo', 'その報告書はごまかしだらけです。', 'Sono houkokusho wa gomakashi darake desu.', 'O relatório está cheio de obscurecimento proposital.'],
    ['おざなりな', 'ozanari na', 'superficial / feito por obrigação', 'adjetivo', 'おざなりな謝罪でした。', 'Ozanari na shazai deshita.', 'Foi um pedido de desculpas superficial.'],
    ['言葉にできない', 'kotoba ni dekinai', 'indescritível', 'adjetivo', '眺めは言葉にできないほどでした。', 'Nagame wa kotoba ni dekinai hodo deshita.', 'A vista era indescritível.'],
    ['遍在する', 'henzai suru', 'onipresente', 'adjetivo', 'スマートフォンは今や遍在しています。', 'Sumaatofon wa ima ya henzai shite imasu.', 'Os smartphones são onipresentes hoje.'],
    ['独特な', 'dokutoku na', 'idiossincrático / peculiar', 'adjetivo', '彼のスタイルはかなり独特です。', 'Kare no sutairu wa kanari dokutoku desu.', 'O estilo dele é bem peculiar.'],
    ['不安定な立場', 'fuantei na tachiba', 'posição precária', 'substantivo', '彼らの立場はせいぜい不安定です。', 'Karera no tachiba wa seizei fuantei desu.', 'A posição deles é, no máximo, precária.'],
    ['陰湿な', 'inshitsu na', 'insidioso', 'adjetivo', 'それは陰湿な問題です。', 'Sore wa inshitsu na mondai desu.', 'É um problema insidioso.'],
    ['対比', 'taihi', 'justaposição / contraste', 'substantivo', '新旧の対比が際立っています。', 'Shinkyuu no taihi ga kiwadatte imasu.', 'A justaposição do velho com o novo impressiona.'],
    ['正当性の証明', 'seitousei no shoumei', 'reconhecimento de razão', 'substantivo', 'その結果は正当性の証明のようでした。', 'Sono kekka wa seitousei no shoumei no you deshita.', 'Os resultados pareceram lhe dar razão.'],
    ['暗黙の了承', 'anmoku no ryoushou', 'anuência silenciosa', 'substantivo', '彼の沈黙は暗黙の了承を意味しました。', 'Kare no chinmoku wa anmoku no ryoushou wo imi shimashita.', 'O silêncio dele implicava anuência.'],
    ['不変の', 'fuhen no', 'imutável', 'adjetivo', 'いくつかの規則は不変に見えます。', 'Ikutsuka no kisoku wa fuhen ni miemasu.', 'Algumas regras parecem imutáveis.'],
    ['表向きの', 'omotemuki no', 'aparente (mas duvidoso)', 'adjetivo', '表向きの理由はコストでした。', 'Omotemuki no riyuu wa kosuto deshita.', 'A razão aparente foi o custo.'],
    ['こっそりとした', 'kossori to shita', 'sub-reptício / dissimulado', 'adjetivo', 'メモへのこっそりとした一瞥。', 'Memo e no kossori to shita ichibetsu.', 'Um olhar dissimulado para as anotações.'],
    ['浮き沈み', 'ukishizumi', 'vicissitude', 'substantivo', '人生の浮き沈みが彼女を形作りました。', 'Jinsei no ukishizumi ga kanojo wo katachizukurimashita.', 'As vicissitudes da vida a moldaram.'],
    ['断固とした', 'danko to shita', 'peremptório', 'adjetivo', '彼の口調は断固としていました。', 'Kare no kuchou wa danko to shite imashita.', 'O tom dele foi peremptório.'],
    ['伝えられるところでは', 'tsutaerareru tokoro dewa', 'supostamente', 'advérbio', '伝えられるところでは、計画は単純です。', 'Tsutaerareru tokoro dewa, keikaku wa tanjun desu.', 'Supostamente, o plano é simples.'],
    ['これまでのところ', 'kore made no tokoro', 'até agora / até então', 'advérbio', 'これまでのところ知られていなかった事実が浮上しました。', 'Kore made no tokoro shirarete inakatta jijitsu ga fujou shimashita.', 'Um fato até então desconhecido veio à tona.'],
  ],
};
