/**
 * Coreano — vocabulário de ampliação.
 *
 * Nenhuma palavra repete o catálogo existente. Romanização obrigatória.
 */

import type { AsianByLevel } from './entry';

export const KO: AsianByLevel = {
  A1: [
    ['책상', 'chaeksang', 'mesa', 'substantivo', '책상이 커요.', 'Chaeksangi keoyo.', 'A mesa é grande.'],
    ['의자', 'uija', 'cadeira', 'substantivo', '의자에 앉으세요.', 'Uija-e anjeuseyo.', 'Sente-se na cadeira.'],
    ['문', 'mun', 'porta', 'substantivo', '문을 닫아 주세요.', 'Muneul dada juseyo.', 'Feche a porta, por favor.'],
    ['창문', 'changmun', 'janela', 'substantivo', '창문을 열게요.', 'Changmuneul yeolgeyo.', 'Vou abrir a janela.'],
    ['침대', 'chimdae', 'cama', 'substantivo', '제 침대에서 자요.', 'Je chimdae-eseo jayo.', 'Eu durmo na minha cama.'],
    ['부엌', 'bueok', 'cozinha', 'substantivo', '부엌에서 요리해요.', 'Bueok-eseo yorihaeyo.', 'Cozinho na cozinha.'],
    ['욕실', 'yoksil', 'banheiro', 'substantivo', '욕실은 이층에 있어요.', 'Yoksireun icheung-e isseoyo.', 'O banheiro fica no segundo andar.'],
    ['형', 'hyeong', 'irmão mais velho (falado por homem)', 'substantivo', '형은 키가 커요.', 'Hyeongeun kiga keoyo.', 'Meu irmão mais velho é alto.'],
    ['누나', 'nuna', 'irmã mais velha (falado por homem)', 'substantivo', '누나는 의사예요.', 'Nunaneun uisayeyo.', 'Minha irmã mais velha é médica.'],
    ['아버지', 'abeoji', 'pai', 'substantivo', '아버지는 일을 많이 해요.', 'Abeojineun ireul mani haeyo.', 'Meu pai trabalha muito.'],
    ['어머니', 'eomeoni', 'mãe', 'substantivo', '어머니는 요리를 잘해요.', 'Eomeonineun yorireul jalhaeyo.', 'Minha mãe cozinha bem.'],
    ['아기', 'agi', 'bebê', 'substantivo', '아기가 자고 있어요.', 'Agiga jago isseoyo.', 'O bebê está dormindo.'],
    ['개', 'gae', 'cachorro', 'substantivo', '개가 짖고 있어요.', 'Gaega jitgo isseoyo.', 'O cachorro está latindo.'],
    ['고양이', 'goyangi', 'gato', 'substantivo', '고양이는 하루 종일 자요.', 'Goyangineun haru jongil jayo.', 'O gato dorme o dia todo.'],
    ['빨간색', 'ppalgansaek', 'vermelho', 'adjetivo', '차가 빨간색이에요.', 'Chaga ppalgansaegieyo.', 'O carro é vermelho.'],
    ['파란색', 'paransaek', 'azul', 'adjetivo', '하늘이 파란색이에요.', 'Haneuri paransaegieyo.', 'O céu é azul.'],
    ['높다', 'nopda', 'alto', 'adjetivo', '건물이 높아요.', 'Geonmuri nopayo.', 'O prédio é alto.'],
    ['짧다', 'jjalda', 'curto', 'adjetivo', '제 머리가 짧아요.', 'Je meoriga jjalbayo.', 'Meu cabelo é curto.'],
    ['뜨겁다', 'tteugeopda', 'quente (ao toque)', 'adjetivo', '수프가 뜨거워요.', 'Supeuga tteugeowoyo.', 'A sopa está quente.'],
    ['차갑다', 'chagapda', 'frio (ao toque)', 'adjetivo', '물이 차가워요.', 'Muri chagawoyo.', 'A água está fria.'],
  ],
  A2: [
    ['볼일', 'boril', 'tarefa rápida (fora de casa)', 'substantivo', '오늘 볼일이 있어요.', 'Oneul borili isseoyo.', 'Tenho umas tarefas hoje.'],
    ['청구서', 'cheongguseo', 'fatura', 'substantivo', '청구서를 보내 주세요.', 'Cheongguseoreul bonae juseyo.', 'Me manda a fatura, por favor.'],
    ['이웃', 'iut', 'vizinho', 'substantivo', '이웃이 친절해요.', 'Iusi chinjeolhaeyo.', 'Meu vizinho é gentil.'],
    ['집주인', 'jipjuin', 'senhorio', 'substantivo', '집주인이 수도꼭지를 고쳤어요.', 'Jipjuini sudokkokjireul gochyeosseoyo.', 'O senhorio consertou a torneira.'],
    ['가구', 'gagu', 'móveis', 'substantivo', '새 가구를 샀어요.', 'Sae gagureul sasseoyo.', 'Compramos móveis novos.'],
    ['약국', 'yakguk', 'farmácia', 'substantivo', '약국은 늦게까지 열어요.', 'Yakgugeun neutgekkaji yeoreoyo.', 'A farmácia abre até tarde.'],
    ['증상', 'jeungsang', 'sintoma', 'substantivo', '증상을 설명해 주세요.', 'Jeungsangeul seolmyeonghae juseyo.', 'Descreva seus sintomas, por favor.'],
    ['열', 'yeol', 'febre', 'substantivo', '그녀는 열이 있어요.', 'Geunyeoneun yeori isseoyo.', 'Ela está com febre.'],
    ['넓다', 'neolda', 'espaçoso', 'adjetivo', '아파트가 넓어요.', 'Apateuga neolbeoyo.', 'O apartamento é espaçoso.'],
    ['지친', 'jichin', 'exausto', 'adjetivo', '오늘 정말 지쳤어요.', 'Oneul jeongmal jichyeosseoyo.', 'Estou exausto hoje.'],
    ['공손한', 'gongsonhan', 'educado', 'adjetivo', '그는 아주 공손해요.', 'Geuneun aju gongsonhaeyo.', 'Ele é muito educado.'],
    ['무례한', 'muryehan', 'grosseiro', 'adjetivo', '그 말은 무례했어요.', 'Geu mareun muryehaesseoyo.', 'Aquele comentário foi grosseiro.'],
    ['근처에', 'geuncheo-e', 'perto', 'advérbio', '근처에 공원이 있어요.', 'Geuncheo-e gongwoni isseoyo.', 'Tem um parque por perto.'],
    ['즉시', 'jeuksi', 'imediatamente', 'advérbio', '즉시 전화해 주세요.', 'Jeuksi jeonhwahae juseyo.', 'Me ligue imediatamente.'],
    ['최근에', 'choegeune', 'recentemente / ultimamente', 'advérbio', '최근에 여기로 이사했어요.', 'Choegeune yeogiro isahaesseoyo.', 'Recentemente eu me mudei para cá.'],
    ['여행 일정', 'yeohaeng iljeong', 'roteiro (de viagem)', 'substantivo', '이것이 우리 여행 일정이에요.', 'Igeosi uri yeohaeng iljeong-ieyo.', 'Aqui está nosso roteiro de viagem.'],
    ['환불', 'hwanbul', 'reembolso', 'substantivo', '환불을 원해요.', 'Hwanbureul wonhaeyo.', 'Quero um reembolso.'],
    ['할인', 'harin', 'desconto', 'substantivo', '할인이 있어요?', 'Harini isseoyo?', 'Tem desconto?'],
    ['교차로', 'gyocharo', 'cruzamento', 'substantivo', '교차로에서 왼쪽으로 도세요.', 'Gyocharo-eseo oenjjogeuro doseyo.', 'Vire à esquerda no cruzamento.'],
    ['인도', 'indo', 'calçada', 'substantivo', '인도로 걸으세요.', 'Indoro georeuseyo.', 'Ande na calçada.'],
  ],
  B1: [
    ['업무량', 'eommuryang', 'carga de trabalho', 'substantivo', '이번 달은 업무량이 많아요.', 'Ibeon dareun eommuryangi manayo.', 'Minha carga de trabalho está pesada este mês.'],
    ['동료', 'dongryo', 'colega de trabalho', 'substantivo', '그는 도움이 되는 동료예요.', 'Geuneun doumi doeneun dongryoyeyo.', 'Ele é um colega prestativo.'],
    ['승진', 'seungjin', 'promoção (cargo)', 'substantivo', '그는 승진했어요.', 'Geuneun seungjinhaesseoyo.', 'Ele foi promovido.'],
    ['사직서', 'sajikseo', 'pedido de demissão', 'substantivo', '그녀는 사직서를 냈어요.', 'Geunyeoneun sajikseoreul naesseoyo.', 'Ela entregou o pedido de demissão.'],
    ['월급', 'wolgeup', 'salário', 'substantivo', '월급이 좋아요.', 'Wolgeubi joayo.', 'O salário é bom.'],
    ['등록금', 'deungnokgeum', 'mensalidade escolar', 'substantivo', '등록금이 올해 올랐어요.', 'Deungnokgeumi olhae ollasseoyo.', 'A mensalidade subiu este ano.'],
    ['장학금', 'janghakgeum', 'bolsa de estudos', 'substantivo', '그녀는 장학금을 받았어요.', 'Geunyeoneun janghakgeumeul badasseoyo.', 'Ela ganhou uma bolsa de estudos.'],
    ['유연한', 'yuyeonhan', 'flexível', 'adjetivo', '제 일정은 유연해요.', 'Je iljeongeun yuyeonhaeyo.', 'Minha agenda é flexível.'],
    ['스트레스가 많은', 'seuteureseuga maneun', 'estressante', 'adjetivo', '이 일은 스트레스가 많아요.', 'I ireun seuteureseuga manayo.', 'Esse trabalho é estressante.'],
    ['효율적인', 'hyoyuljeogin', 'eficiente', 'adjetivo', '새 시스템은 효율적이에요.', 'Sae siseutemeun hyoyuljeogieyo.', 'O sistema novo é eficiente.'],
    ['구식인', 'gusigin', 'desatualizado', 'adjetivo', '이 소프트웨어는 구식이에요.', 'I sopeuteuweeoneun gusigieyo.', 'Esse software está desatualizado.'],
    ['점차', 'jeomcha', 'gradualmente', 'advérbio', '가격이 점차 올랐어요.', 'Gagyeogi jeomcha ollasseoyo.', 'Os preços subiram gradualmente.'],
    ['결국에는', 'gyeolguk-eneun', 'no fim das contas', 'advérbio', '결국에는 합의했어요.', 'Gyeolguk-eneun habuihaesseoyo.', 'No fim das contas, chegamos a um acordo.'],
    ['가전제품', 'gajeonjepum', 'eletrodoméstico', 'substantivo', '세탁기는 가전제품이에요.', 'Setakgineun gajeonjepumieyo.', 'A máquina de lavar é um eletrodoméstico.'],
    ['보증', 'bojeung', 'garantia (produto)', 'substantivo', '보증은 이 년이에요.', 'Bojeungeun i nyeonieyo.', 'A garantia dura dois anos.'],
    ['구독', 'gudok', 'assinatura (serviço)', 'substantivo', '구독을 취소했어요.', 'Gudogeul chwisohaesseoyo.', 'Cancelei minha assinatura.'],
    ['통근', 'tonggeun', 'trajeto casa-trabalho', 'substantivo', '통근에 한 시간 걸려요.', 'Tonggeune han sigan geollyeoyo.', 'Meu trajeto até o trabalho leva uma hora.'],
    ['압도된', 'apdodoen', 'sobrecarregado', 'adjetivo', '일 때문에 압도된 느낌이에요.', 'Il ttaemune apdodoen neukkim-ieyo.', 'Me sinto sobrecarregado no trabalho.'],
    ['의욕적인', 'uiyokjeogin', 'motivado', 'adjetivo', '팀이 의욕적이에요.', 'Timi uiyokjeogieyo.', 'A equipe está motivada.'],
    ['행정 절차', 'haengjeong jeolcha', 'processo burocrático', 'substantivo', '행정 절차가 몇 주 걸렸어요.', 'Haengjeong jeolchaga myeot ju geollyeosseoyo.', 'O processo burocrático levou semanas.'],
  ],
  B2: [
    ['격차', 'gyeokcha', 'disparidade', 'substantivo', '소득에 큰 격차가 있어요.', 'Sodeuge keun gyeokchaga isseoyo.', 'Há uma grande disparidade de renda.'],
    ['선견지명', 'seongyeonjimyeong', 'previsão / visão de futuro', 'substantivo', '계획은 진정한 선견지명을 보였어요.', 'Gyehoegeun jinjeonghan seongyeonjimyeongeul boyeosseoyo.', 'O plano mostrou visão de futuro de verdade.'],
    ['지속 가능성', 'jisok ganeungseong', 'sustentabilidade', 'substantivo', '지속 가능성이 이제 우선순위예요.', 'Jisok ganeungseongi ije useonsunwiyeyo.', 'Sustentabilidade é prioridade agora.'],
    ['불평등', 'bulpyeongdeung', 'desigualdade', 'substantivo', '불평등은 여전히 큰 문제예요.', 'Bulpyeongdeungeun yeojeonhi keun munjeyeyo.', 'A desigualdade continua sendo um grande problema.'],
    ['논란', 'nollan', 'controvérsia', 'substantivo', '그 결정은 논란을 일으켰어요.', 'Geu gyeoljeongeun nollaneul ireukyeosseoyo.', 'A decisão causou controvérsia.'],
    ['허점', 'heojeom', 'brecha (na lei)', 'substantivo', '그들은 법적 허점을 찾았어요.', 'Geudeureun beopjeok heojeomeul chajasseoyo.', 'Encontraram uma brecha legal.'],
    ['책임성', 'chaegimseong', 'responsabilização', 'substantivo', '더 많은 책임성이 필요해요.', 'Deo maneun chaegimseongi piryohaeyo.', 'Precisamos de mais responsabilização.'],
    ['투명성', 'tumyeongseong', 'transparência', 'substantivo', '그 회사는 투명성이 부족해요.', 'Geu hoesaneun tumyeongseongi bujokhaeyo.', 'A empresa carece de transparência.'],
    ['그럴듯한', 'geureoldeutan', 'plausível', 'adjetivo', '그 설명은 그럴듯해요.', 'Geu seolmyeongeun geureoldeutaeyo.', 'Aquela explicação parece plausível.'],
    ['모호한', 'mohohan', 'ambíguo', 'adjetivo', '문구가 모호해요.', 'Mungu-ga mohohaeyo.', 'A redação é ambígua.'],
    ['회복력이 있는', 'hoebongnyeogi inneun', 'resiliente', 'adjetivo', '경제는 회복력이 있음을 증명했어요.', 'Gyeongjeneun hoebongnyeogi isseumeul jeungmyeonghaesseoyo.', 'A economia se mostrou resiliente.'],
    ['불안정한', 'buranjeonghan', 'volátil', 'adjetivo', '시장이 불안정해요.', 'Sijangi buranjeonghaeyo.', 'O mercado está volátil.'],
    ['아마', 'ama', 'possivelmente / provavelmente', 'advérbio', '이것이 아마 최선의 선택일 거예요.', 'Igeosi ama choeseonui seontaegil geoyeyo.', 'Essa é, provavelmente, a melhor opção.'],
    ['불가피하게', 'bulgapihage', 'inevitavelmente', 'advérbio', '비용이 불가피하게 오를 거예요.', 'Biyongi bulgapihage oreul geoyeyo.', 'Os custos vão subir inevitavelmente.'],
    ['반발', 'banbal', 'reação negativa', 'substantivo', '그 정책은 반발을 불렀어요.', 'Geu jeongchaegeun banbareul bulleosseoyo.', 'A política causou uma reação negativa.'],
    ['고정관념', 'gojeonggwannyeom', 'estereótipo', 'substantivo', '그 광고는 고정관념에 의존해요.', 'Geu gwanggoneun gojeonggwannyeome uijonhaeyo.', 'O anúncio se apoia num estereótipo.'],
    ['임시 해결책', 'imsi haegyeolchaek', 'solução paliativa', 'substantivo', '임시 해결책을 찾았어요.', 'Imsi haegyeolchaegeul chajasseoyo.', 'Encontramos uma solução paliativa.'],
    ['이정표', 'ijeongpyo', 'marco (conquista)', 'substantivo', '출시는 큰 이정표였어요.', 'Chulsineun keun ijeongpyoyeosseoyo.', 'O lançamento foi um grande marco.'],
    ['면밀한 조사', 'myeonmilhan josa', 'escrutínio', 'substantivo', '그 거래는 면밀한 조사를 받고 있어요.', 'Geu georaeneun myeonmilhan josareul batgo isseoyo.', 'O acordo está sob escrutínio.'],
    ['구체적인', 'guchejeogin', 'tangível / concreto', 'adjetivo', '구체적인 결과가 필요해요.', 'Guchejeogin gyeolgwaga piryohaeyo.', 'Precisamos de resultados concretos.'],
  ],
  C1: [
    ['딜레마', 'dillema', 'dilema', 'substantivo', '그것은 진짜 딜레마예요.', 'Geugeoseun jinjja dillemayeyo.', 'É um dilema difícil de verdade.'],
    ['신조', 'sinjo', 'preceito / princípio', 'substantivo', '그것은 이론의 핵심 신조예요.', 'Geugeoseun ironui haeksim sinjoyeyo.', 'Esse é um princípio central da teoria.'],
    ['파급 효과', 'pageup hyogwa', 'repercussão', 'substantivo', '먼저 파급 효과를 생각하세요.', 'Meonjeo pageup hyogwareul saenggakaseyo.', 'Considere as repercussões primeiro.'],
    ['미묘함', 'mimyohan', 'sutileza / nuance delicada', 'substantivo', '번역에서 미묘함이 사라졌어요.', 'Beonyeogeseo mimyohami sarajyeosseoyo.', 'A tradução perdeu alguma sutileza.'],
    ['선례', 'seollye', 'precedente', 'substantivo', '이 사건은 선례를 만들어요.', 'I sageoneun seollyereul mandeureoyo.', 'Esse caso cria um precedente.'],
    ['실용적인', 'silyongjeogin', 'pragmático', 'adjetivo', '그녀는 실용적인 접근을 택했어요.', 'Geunyeoneun silyongjeogin jeopgeuneul taekaesseoyo.', 'Ela adotou uma abordagem pragmática.'],
    ['중복된', 'jungbokdoen', 'redundante', 'adjetivo', '그 조항은 중복돼요.', 'Geu johangeun jungbokdwaeyo.', 'Aquela cláusula é redundante.'],
    ['전례 없는', 'jeollye eomneun', 'sem precedentes', 'adjetivo', '전례 없는 위기였어요.', 'Jeollye eomneun wigiyeosseoyo.', 'Foi uma crise sem precedentes.'],
    ['합의', 'habui', 'consenso', 'substantivo', '우리는 합의에 도달했어요.', 'Urineun habuie dodalhaesseoyo.', 'Chegamos a um consenso.'],
    ['비상 대책', 'bisang daechaek', 'plano de contingência', 'substantivo', '비상 대책이 필요해요.', 'Bisang daechaegi piryohaeyo.', 'Precisamos de um plano de contingência.'],
    ['궤변', 'gwebyeon', 'falácia / sofisma', 'substantivo', '그것은 흔한 궤변이에요.', 'Geugeoseun heunhan gwebyeon-ieyo.', 'Essa é uma falácia comum.'],
    ['역설', 'yeokseol', 'paradoxo', 'substantivo', '이상한 역설이에요.', 'Isanghan yeokseor-ieyo.', 'É um paradoxo estranho.'],
    ['꼼꼼한', 'kkomkkomhan', 'escrupuloso / meticuloso', 'adjetivo', '그는 세부 사항에 꼼꼼해요.', 'Geuneun sebu sahange kkomkkomhaeyo.', 'Ele é escrupuloso com detalhes.'],
    ['솔직한', 'soljikhan', 'sincero / franco', 'adjetivo', '위험에 대해 솔직해집시다.', 'Wiheome daehae soljikaejipsida.', 'Vamos ser francos sobre os riscos.'],
    ['치밀한', 'chimilhan', 'meticuloso', 'adjetivo', '그녀는 데이터에 치밀해요.', 'Geunyeoneun deiteoe chimilhaeyo.', 'Ela é meticulosa com os dados.'],
    ['얼핏 보기에', 'eolpit bogie', 'aparentemente', 'advérbio', '얼핏 보기에 단순한 작업이에요.', 'Eolpit bogie dansunhan jageobieyo.', 'É uma tarefa aparentemente simples.'],
    ['상관없이', 'sanggwaneopsi', 'independentemente de', 'advérbio', '위험과 상관없이 계속해요.', 'Wiheomgwa sanggwaneopsi gyesokaeyo.', 'Seguimos em frente, independentemente dos riscos.'],
    ['어쩌면', 'eojjeomyeon', 'possivelmente', 'advérbio', '어쩌면 효과가 있을 거예요.', 'Eojjeomyeon hyogwaga isseul geoyeyo.', 'Possivelmente vai dar certo.'],
    ['회의론', 'hoeuiron', 'ceticismo', 'substantivo', '그들은 회의적으로 그 소식을 받아들였어요.', 'Geudeureun hoeuijeogeuro geu sosigeul badadeuryeosseoyo.', 'Receberam a notícia com ceticismo.'],
    ['불확실성', 'bulhwaksilseong', 'incerteza', 'substantivo', '우리는 불확실성의 시대에 살고 있어요.', 'Urineun bulhwaksilseongui sidae-e salgo isseoyo.', 'Vivemos um período de incerteza.'],
  ],
  C2: [
    ['긴박감', 'ginbakgam', 'urgência premente', 'substantivo', '상황의 긴박감이 행동을 요구했어요.', 'Sanghwangui ginbakgami haengdongeul yogutaesseoyo.', 'A urgência da situação exigia ação.'],
    ['에두른 표현', 'edureun pyohyeon', 'circunlóquio', 'substantivo', '법률 문서에서는 에두른 표현을 피하세요.', 'Beomnyul munseoeseoneun edureun pyohyeoneul pihaseyo.', 'Evite circunlóquios em textos jurídicos.'],
    ['평정심', 'pyeongjeongsim', 'equanimidade', 'substantivo', '그녀는 평정심으로 그 소식을 받아들였어요.', 'Geunyeoneun pyeongjeongsimeuro geu sosigeul badadeuryeosseoyo.', 'Ela recebeu a notícia com equanimidade.'],
    ['눈속임', 'nunsogim', 'obscurecimento proposital', 'substantivo', '그 보고서는 눈속임투성이예요.', 'Geu bogoseoneun nunsogimtuseongiyeyo.', 'O relatório está cheio de obscurecimento proposital.'],
    ['형식적인', 'hyeongsikjeogin', 'superficial / feito por obrigação', 'adjetivo', '형식적인 사과였어요.', 'Hyeongsikjeogin sagwayeosseoyo.', 'Foi um pedido de desculpas superficial.'],
    ['형언할 수 없는', 'hyeoneonhal su eomneun', 'indescritível', 'adjetivo', '경치는 형언할 수 없었어요.', 'Gyeongchineun hyeoneonhal su eopseosseoyo.', 'A vista era indescritível.'],
    ['어디에나 있는', 'eodiena inneun', 'onipresente', 'adjetivo', '스마트폰은 이제 어디에나 있어요.', 'Seumateuponeun ije eodiena isseoyo.', 'Os smartphones são onipresentes hoje.'],
    ['특이한', 'teugihan', 'idiossincrático / peculiar', 'adjetivo', '그의 스타일은 꽤 특이해요.', 'Geuui seutaireun kkwae teugihaeyo.', 'O estilo dele é bem peculiar.'],
    ['불안정한 입지', 'buranjeonghan ipji', 'posição precária', 'substantivo', '그들의 입지는 기껏해야 불안정해요.', 'Geudeurui ipjineun gikkeotaeya buranjeonghaeyo.', 'A posição deles é, no máximo, precária.'],
    ['음흉한', 'eumhyunghan', 'insidioso', 'adjetivo', '그것은 음흉한 문제예요.', 'Geugeoseun eumhyunghan munjeyeyo.', 'É um problema insidioso.'],
    ['병치', 'byeongchi', 'justaposição', 'substantivo', '신구의 병치가 눈에 띄어요.', 'Singuui byeongchiga nune ttwieoyo.', 'A justaposição do velho com o novo impressiona.'],
    ['명예 회복', 'myeongye hoebok', 'reconhecimento de razão', 'substantivo', '그 결과는 명예 회복처럼 느껴졌어요.', 'Geu gyeolgwaneun myeongye hoebokcheoreom neukkyeojyeosseoyo.', 'Os resultados pareceram uma reabilitação para ela.'],
    ['묵인', 'mugin', 'anuência silenciosa', 'substantivo', '그의 침묵은 묵인을 의미했어요.', 'Geuui chimmugeun mugineul uimihaesseoyo.', 'O silêncio dele implicava anuência.'],
    ['불변하는', 'bulbyeonhaneun', 'imutável', 'adjetivo', '어떤 규칙은 불변해 보여요.', 'Eotteon gyuchigeun bulbyeonhae boyeoyo.', 'Algumas regras parecem imutáveis.'],
    ['표면상의', 'pyomyeonsangui', 'aparente (mas duvidoso)', 'adjetivo', '표면상의 이유는 비용이었어요.', 'Pyomyeonsangui iyuneun biyongieosseoyo.', 'A razão aparente foi o custo.'],
    ['은밀한', 'eunmilhan', 'sub-reptício / dissimulado', 'adjetivo', '메모를 향한 은밀한 시선.', 'Memoreul hyanghan eunmilhan siseon.', 'Um olhar dissimulado para as anotações.'],
    ['부침', 'bujim', 'vicissitude / altos e baixos', 'substantivo', '인생의 부침이 그녀를 만들었어요.', 'Insaengui bujimi geunyeoreul mandeureosseoyo.', 'As vicissitudes da vida a moldaram.'],
    ['단호한', 'danhohan', 'peremptório', 'adjetivo', '그의 어조는 단호했어요.', 'Geuui eojoneun danhohaesseoyo.', 'O tom dele foi peremptório.'],
    ['전해지는 바로는', 'jeonhaejineun baroneun', 'supostamente', 'advérbio', '전해지는 바로는 계획은 단순해요.', 'Jeonhaejineun baroneun gyehoegeun dansunhaeyo.', 'Supostamente, o plano é simples.'],
    ['지금까지', 'jigeumkkaji', 'até agora / até então', 'advérbio', '지금까지 알려지지 않은 사실이 드러났어요.', 'Jigeumkkaji allyeojiji aneun sasiri deureonasseoyo.', 'Um fato até então desconhecido veio à tona.'],
  ],
};
