/**
 * Mandarim — vocabulário de ampliação.
 *
 * Nenhuma palavra repete o catálogo existente. Pinyin obrigatório.
 */

import type { AsianByLevel } from './entry';

export const ZH: AsianByLevel = {
  A1: [
    ['桌子', 'zhuōzi', 'mesa', 'substantivo', '桌子很大。', 'Zhuōzi hěn dà.', 'A mesa é grande.'],
    ['椅子', 'yǐzi', 'cadeira', 'substantivo', '请坐在椅子上。', 'Qǐng zuò zài yǐzi shàng.', 'Sente-se na cadeira, por favor.'],
    ['门', 'mén', 'porta', 'substantivo', '请关门。', 'Qǐng guān mén.', 'Feche a porta, por favor.'],
    ['窗户', 'chuānghu', 'janela', 'substantivo', '我要开窗户。', 'Wǒ yào kāi chuānghu.', 'Vou abrir a janela.'],
    ['床', 'chuáng', 'cama', 'substantivo', '我在自己的床上睡觉。', 'Wǒ zài zìjǐ de chuáng shàng shuìjiào.', 'Eu durmo na minha cama.'],
    ['厨房', 'chúfáng', 'cozinha', 'substantivo', '我在厨房做饭。', 'Wǒ zài chúfáng zuòfàn.', 'Cozinho na cozinha.'],
    ['浴室', 'yùshì', 'banheiro', 'substantivo', '浴室在楼上。', 'Yùshì zài lóushàng.', 'O banheiro é lá em cima.'],
    ['哥哥', 'gēge', 'irmão mais velho', 'substantivo', '我哥哥很高。', 'Wǒ gēge hěn gāo.', 'Meu irmão mais velho é alto.'],
    ['姐姐', 'jiějie', 'irmã mais velha', 'substantivo', '我姐姐是医生。', 'Wǒ jiějie shì yīshēng.', 'Minha irmã mais velha é médica.'],
    ['爸爸', 'bàba', 'pai', 'substantivo', '我爸爸工作很多。', 'Wǒ bàba gōngzuò hěn duō.', 'Meu pai trabalha muito.'],
    ['妈妈', 'māma', 'mãe', 'substantivo', '我妈妈做饭很好吃。', 'Wǒ māma zuòfàn hěn hǎochī.', 'Minha mãe cozinha muito bem.'],
    ['婴儿', 'yīng’ér', 'bebê', 'substantivo', '婴儿在睡觉。', 'Yīng’ér zài shuìjiào.', 'O bebê está dormindo.'],
    ['狗', 'gǒu', 'cachorro', 'substantivo', '狗在叫。', 'Gǒu zài jiào.', 'O cachorro está latindo.'],
    ['猫', 'māo', 'gato', 'substantivo', '猫整天睡觉。', 'Māo zhěngtiān shuìjiào.', 'O gato dorme o dia todo.'],
    ['红色', 'hóngsè', 'vermelho', 'adjetivo', '车是红色的。', 'Chē shì hóngsè de.', 'O carro é vermelho.'],
    ['蓝色', 'lánsè', 'azul', 'adjetivo', '天空是蓝色的。', 'Tiānkōng shì lánsè de.', 'O céu é azul.'],
    ['高', 'gāo', 'alto', 'adjetivo', '那栋楼很高。', 'Nà dòng lóu hěn gāo.', 'Aquele prédio é alto.'],
    ['短', 'duǎn', 'curto', 'adjetivo', '我的头发很短。', 'Wǒ de tóufa hěn duǎn.', 'Meu cabelo é curto.'],
    ['烫', 'tàng', 'quente (ao toque)', 'adjetivo', '汤很烫。', 'Tāng hěn tàng.', 'A sopa está bem quente.'],
    ['凉', 'liáng', 'frio (temperatura amena)', 'adjetivo', '水很凉。', 'Shuǐ hěn liáng.', 'A água está fria.'],
  ],
  A2: [
    ['差事', 'chāishi', 'tarefa rápida (fora de casa)', 'substantivo', '我今天有点差事要办。', 'Wǒ jīntiān yǒudiǎn chāishi yào bàn.', 'Tenho umas tarefas para resolver hoje.'],
    ['账单', 'zhàngdān', 'fatura', 'substantivo', '请把账单发给我。', 'Qǐng bǎ zhàngdān fā gěi wǒ.', 'Me manda a fatura, por favor.'],
    ['邻居', 'línjū', 'vizinho', 'substantivo', '我的邻居很友好。', 'Wǒ de línjū hěn yǒuhǎo.', 'Meu vizinho é gentil.'],
    ['房东', 'fángdōng', 'senhorio', 'substantivo', '房东修好了水龙头。', 'Fángdōng xiūhǎole shuǐlóngtóu.', 'O senhorio consertou a torneira.'],
    ['家具', 'jiājù', 'móveis', 'substantivo', '我们买了新家具。', 'Wǒmen mǎile xīn jiājù.', 'Compramos móveis novos.'],
    ['药店', 'yàodiàn', 'farmácia', 'substantivo', '药店开到很晚。', 'Yàodiàn kāi dào hěn wǎn.', 'A farmácia abre até tarde.'],
    ['症状', 'zhèngzhuàng', 'sintoma', 'substantivo', '请描述你的症状。', 'Qǐng miáoshù nǐ de zhèngzhuàng.', 'Descreva seus sintomas, por favor.'],
    ['发烧', 'fāshāo', 'febre', 'substantivo', '她在发烧。', 'Tā zài fāshāo.', 'Ela está com febre.'],
    ['宽敞', 'kuānchang', 'espaçoso', 'adjetivo', '公寓很宽敞。', 'Gōngyù hěn kuānchang.', 'O apartamento é espaçoso.'],
    ['筋疲力尽', 'jīnpílìjìn', 'exausto', 'adjetivo', '我今天筋疲力尽。', 'Wǒ jīntiān jīnpílìjìn.', 'Estou exausto hoje.'],
    ['有礼貌', 'yǒu lǐmào', 'educado', 'adjetivo', '他很有礼貌。', 'Tā hěn yǒu lǐmào.', 'Ele é muito educado.'],
    ['粗鲁', 'cūlǔ', 'grosseiro', 'adjetivo', '那句话很粗鲁。', 'Nà jù huà hěn cūlǔ.', 'Aquele comentário foi grosseiro.'],
    ['附近', 'fùjìn', 'perto / por perto', 'advérbio', '附近有一个公园。', 'Fùjìn yǒu yīgè gōngyuán.', 'Tem um parque por perto.'],
    ['马上', 'mǎshàng', 'imediatamente', 'advérbio', '请马上给我打电话。', 'Qǐng mǎshàng gěi wǒ dǎ diànhuà.', 'Me ligue imediatamente.'],
    ['最近', 'zuìjìn', 'recentemente / ultimamente', 'advérbio', '我最近搬到这里。', 'Wǒ zuìjìn bān dào zhèlǐ.', 'Recentemente eu me mudei para cá.'],
    ['行程', 'xíngchéng', 'roteiro (de viagem)', 'substantivo', '这是我们的行程。', 'Zhè shì wǒmen de xíngchéng.', 'Aqui está nosso roteiro de viagem.'],
    ['退款', 'tuìkuǎn', 'reembolso', 'substantivo', '我想要退款。', 'Wǒ xiǎng yào tuìkuǎn.', 'Quero um reembolso.'],
    ['折扣', 'zhékòu', 'desconto', 'substantivo', '有折扣吗？', 'Yǒu zhékòu ma?', 'Tem desconto?'],
    ['十字路口', 'shízì lùkǒu', 'cruzamento', 'substantivo', '在十字路口左转。', 'Zài shízì lùkǒu zuǒ zhuǎn.', 'Vire à esquerda no cruzamento.'],
    ['人行道', 'rénxíngdào', 'calçada', 'substantivo', '请走人行道。', 'Qǐng zǒu rénxíngdào.', 'Ande na calçada, por favor.'],
  ],
  B1: [
    ['工作量', 'gōngzuòliàng', 'carga de trabalho', 'substantivo', '这个月我的工作量很大。', 'Zhège yuè wǒ de gōngzuòliàng hěn dà.', 'Minha carga de trabalho está pesada este mês.'],
    ['同事', 'tóngshì', 'colega de trabalho', 'substantivo', '他是一个乐于助人的同事。', 'Tā shì yīgè lèyú zhùrén de tóngshì.', 'Ele é um colega prestativo.'],
    ['升职', 'shēngzhí', 'promoção (cargo)', 'substantivo', '他升职了。', 'Tā shēngzhí le.', 'Ele foi promovido.'],
    ['辞职信', 'cízhíxìn', 'carta de demissão', 'substantivo', '她交了辞职信。', 'Tā jiāole cízhíxìn.', 'Ela entregou a carta de demissão.'],
    ['工资', 'gōngzī', 'salário', 'substantivo', '工资很有竞争力。', 'Gōngzī hěn yǒu jìngzhēnglì.', 'O salário é competitivo.'],
    ['学费', 'xuéfèi', 'mensalidade escolar', 'substantivo', '今年学费涨了。', 'Jīnnián xuéfèi zhǎngle.', 'A mensalidade subiu este ano.'],
    ['奖学金', 'jiǎngxuéjīn', 'bolsa de estudos', 'substantivo', '她获得了奖学金。', 'Tā huòdéle jiǎngxuéjīn.', 'Ela ganhou uma bolsa de estudos.'],
    ['灵活', 'línghuó', 'flexível', 'adjetivo', '我的日程很灵活。', 'Wǒ de rìchéng hěn línghuó.', 'Minha agenda é flexível.'],
    ['有压力', 'yǒu yālì', 'estressante', 'adjetivo', '这份工作很有压力。', 'Zhè fèn gōngzuò hěn yǒu yālì.', 'Esse trabalho é estressante.'],
    ['高效', 'gāoxiào', 'eficiente', 'adjetivo', '新系统很高效。', 'Xīn xìtǒng hěn gāoxiào.', 'O sistema novo é eficiente.'],
    ['过时', 'guòshí', 'desatualizado', 'adjetivo', '这个软件过时了。', 'Zhège ruǎnjiàn guòshí le.', 'Esse software está desatualizado.'],
    ['逐渐', 'zhújiàn', 'gradualmente', 'advérbio', '价格逐渐上涨了。', 'Jiàgé zhújiàn shàngzhǎngle.', 'Os preços subiram gradualmente.'],
    ['最终', 'zuìzhōng', 'no fim das contas', 'advérbio', '我们最终达成了协议。', 'Wǒmen zuìzhōng dáchéngle xiéyì.', 'No fim das contas, chegamos a um acordo.'],
    ['家电', 'jiādiàn', 'eletrodoméstico', 'substantivo', '洗衣机是一种家电。', 'Xǐyījī shì yī zhǒng jiādiàn.', 'A máquina de lavar é um eletrodoméstico.'],
    ['保修', 'bǎoxiū', 'garantia (produto)', 'substantivo', '保修期是两年。', 'Bǎoxiū qī shì liǎng nián.', 'A garantia dura dois anos.'],
    ['订阅', 'dìngyuè', 'assinatura (serviço)', 'substantivo', '我取消了订阅。', 'Wǒ qǔxiāole dìngyuè.', 'Cancelei minha assinatura.'],
    ['通勤', 'tōngqín', 'trajeto casa-trabalho', 'substantivo', '我的通勤要一个小时。', 'Wǒ de tōngqín yào yīgè xiǎoshí.', 'Meu trajeto até o trabalho leva uma hora.'],
    ['不堪重负', 'bùkān zhòngfù', 'sobrecarregado', 'adjetivo', '我在工作上感到不堪重负。', 'Wǒ zài gōngzuò shàng gǎndào bùkān zhòngfù.', 'Me sinto sobrecarregado no trabalho.'],
    ['积极性高', 'jījíxìng gāo', 'motivado', 'adjetivo', '团队积极性很高。', 'Tuánduì jījíxìng hěn gāo.', 'A equipe está muito motivada.'],
    ['手续', 'shǒuxù', 'processo burocrático', 'substantivo', '手续花了好几周。', 'Shǒuxù huāle hǎojǐ zhōu.', 'O processo burocrático levou semanas.'],
  ],
  B2: [
    ['差距', 'chājù', 'disparidade', 'substantivo', '收入差距很大。', 'Shōurù chājù hěn dà.', 'Há uma grande disparidade de renda.'],
    ['远见', 'yuǎnjiàn', 'previsão / visão de futuro', 'substantivo', '这个计划展示了真正的远见。', 'Zhège jìhuà zhǎnshìle zhēnzhèng de yuǎnjiàn.', 'O plano mostrou visão de futuro de verdade.'],
    ['可持续性', 'kěchíxùxìng', 'sustentabilidade', 'substantivo', '可持续性现在是优先事项。', 'Kěchíxùxìng xiànzài shì yōuxiān shìxiàng.', 'Sustentabilidade é prioridade agora.'],
    ['不平等', 'bùpíngděng', 'desigualdade', 'substantivo', '不平等仍然是个大问题。', 'Bùpíngděng réngrán shì gè dà wèntí.', 'A desigualdade continua sendo um grande problema.'],
    ['争议', 'zhēngyì', 'controvérsia', 'substantivo', '这个决定引起了争议。', 'Zhège juédìng yǐnqǐle zhēngyì.', 'A decisão causou controvérsia.'],
    ['漏洞', 'lòudòng', 'brecha (na lei)', 'substantivo', '他们找到了一个法律漏洞。', 'Tāmen zhǎodàole yīgè fǎlǜ lòudòng.', 'Encontraram uma brecha legal.'],
    ['问责制', 'wènzé zhì', 'responsabilização', 'substantivo', '我们需要更多问责制。', 'Wǒmen xūyào gèng duō wènzé zhì.', 'Precisamos de mais responsabilização.'],
    ['透明度', 'tòumíngdù', 'transparência', 'substantivo', '这家公司缺乏透明度。', 'Zhè jiā gōngsī quēfá tòumíngdù.', 'A empresa carece de transparência.'],
    ['貌似合理', 'màosì hélǐ', 'plausível', 'adjetivo', '那个解释貌似合理。', 'Nàge jiěshì màosì hélǐ.', 'Aquela explicação parece plausível.'],
    ['含糊', 'hánhu', 'ambíguo', 'adjetivo', '措辞很含糊。', 'Cuòcí hěn hánhu.', 'A redação é ambígua.'],
    ['有韧性', 'yǒu rènxìng', 'resiliente', 'adjetivo', '经济证明了自己是有韧性的。', 'Jīngjì zhèngmíngle zìjǐ shì yǒu rènxìng de.', 'A economia se mostrou resiliente.'],
    ['不稳定', 'bù wěndìng', 'volátil', 'adjetivo', '市场不稳定。', 'Shìchǎng bù wěndìng.', 'O mercado está volátil.'],
    ['大概', 'dàgài', 'possivelmente / provavelmente', 'advérbio', '这大概是最好的选择。', 'Zhè dàgài shì zuì hǎo de xuǎnzé.', 'Essa é, provavelmente, a melhor opção.'],
    ['不可避免地', 'bùkě bìmiǎn de', 'inevitavelmente', 'advérbio', '成本将不可避免地上涨。', 'Chéngběn jiāng bùkě bìmiǎn de shàngzhǎng.', 'Os custos vão subir inevitavelmente.'],
    ['强烈反对', 'qiángliè fǎnduì', 'reação negativa', 'substantivo', '这项政策引发了强烈反对。', 'Zhè xiàng zhèngcè yǐnfāle qiángliè fǎnduì.', 'A política causou uma forte reação negativa.'],
    ['刻板印象', 'kèbǎn yìnxiàng', 'estereótipo', 'substantivo', '这个广告依赖刻板印象。', 'Zhège guǎnggào yīlài kèbǎn yìnxiàng.', 'O anúncio se apoia num estereótipo.'],
    ['临时解决方案', 'línshí jiějué fāng’àn', 'solução paliativa', 'substantivo', '我们找到了一个临时解决方案。', 'Wǒmen zhǎodàole yīgè línshí jiějué fāng’àn.', 'Encontramos uma solução paliativa.'],
    ['里程碑', 'lǐchéngbēi', 'marco (conquista)', 'substantivo', '发布是一个重要的里程碑。', 'Fābù shì yīgè zhòngyào de lǐchéngbēi.', 'O lançamento foi um marco importante.'],
    ['严格审查', 'yángé shěnchá', 'escrutínio', 'substantivo', '这笔交易正在接受严格审查。', 'Zhè bǐ jiāoyì zhèngzài jiēshòu yángé shěnchá.', 'O acordo está sob escrutínio.'],
    ['切实的', 'qièshí de', 'tangível / concreto', 'adjetivo', '我们需要切实的结果。', 'Wǒmen xūyào qièshí de jiéguǒ.', 'Precisamos de resultados concretos.'],
  ],
  C1: [
    ['难题', 'nántí', 'dilema', 'substantivo', '这是一个真正的难题。', 'Zhè shì yīgè zhēnzhèng de nántí.', 'É um dilema difícil de verdade.'],
    ['信条', 'xìntiáo', 'preceito / princípio', 'substantivo', '这是该理论的核心信条。', 'Zhè shì gāi lǐlùn de héxīn xìntiáo.', 'Esse é um princípio central da teoria.'],
    ['影响', 'yǐngxiǎng', 'repercussão', 'substantivo', '先考虑一下影响。', 'Xiān kǎolǜ yīxià yǐngxiǎng.', 'Considere as repercussões primeiro.'],
    ['微妙之处', 'wēimiào zhī chù', 'sutileza / nuance delicada', 'substantivo', '翻译丢失了一些微妙之处。', 'Fānyì diūshīle yīxiē wēimiào zhī chù.', 'A tradução perdeu alguma sutileza.'],
    ['先例', 'xiānlì', 'precedente', 'substantivo', '这个案子开创了先例。', 'Zhège ànzi kāichuàngle xiānlì.', 'Esse caso cria um precedente.'],
    ['务实', 'wùshí', 'pragmático', 'adjetivo', '她采取了务实的方法。', 'Tā cǎiqǔle wùshí de fāngfǎ.', 'Ela adotou uma abordagem pragmática.'],
    ['多余', 'duōyú', 'redundante', 'adjetivo', '那条款是多余的。', 'Nà tiáokuǎn shì duōyú de.', 'Aquela cláusula é redundante.'],
    ['史无前例', 'shǐwúqiánlì', 'sem precedentes', 'adjetivo', '这是一场史无前例的危机。', 'Zhè shì yī chǎng shǐwúqiánlì de wéijī.', 'Foi uma crise sem precedentes.'],
    ['共识', 'gòngshí', 'consenso', 'substantivo', '我们达成了共识。', 'Wǒmen dáchéngle gòngshí.', 'Chegamos a um consenso.'],
    ['应急计划', 'yìngjí jìhuà', 'plano de contingência', 'substantivo', '我们需要一个应急计划。', 'Wǒmen xūyào yīgè yìngjí jìhuà.', 'Precisamos de um plano de contingência.'],
    ['谬论', 'miùlùn', 'falácia / sofisma', 'substantivo', '这是一个常见的谬论。', 'Zhè shì yīgè chángjiàn de miùlùn.', 'Essa é uma falácia comum.'],
    ['悖论', 'bèilùn', 'paradoxo', 'substantivo', '这是一个奇怪的悖论。', 'Zhè shì yīgè qíguài de bèilùn.', 'É um paradoxo estranho.'],
    ['一丝不苟', 'yīsībùgǒu', 'escrupuloso / meticuloso', 'adjetivo', '他对细节一丝不苟。', 'Tā duì xìjié yīsībùgǒu.', 'Ele é escrupuloso com detalhes.'],
    ['坦率', 'tǎnshuài', 'sincero / franco', 'adjetivo', '让我们坦率地谈谈风险。', 'Ràng wǒmen tǎnshuài de tántán fēngxiǎn.', 'Vamos ser francos sobre os riscos.'],
    ['细致', 'xìzhì', 'meticuloso', 'adjetivo', '她对数据非常细致。', 'Tā duì shùjù fēicháng xìzhì.', 'Ela é meticulosa com os dados.'],
    ['表面看来', 'biǎomiàn kànlái', 'aparentemente', 'advérbio', '这是一个表面看来简单的任务。', 'Zhè shì yīgè biǎomiàn kànlái jiǎndān de rènwù.', 'É uma tarefa aparentemente simples.'],
    ['不论', 'bùlùn', 'independentemente de', 'advérbio', '不论风险如何，我们继续前进。', 'Bùlùn fēngxiǎn rúhé, wǒmen jìxù qiánjìn.', 'Independentemente dos riscos, seguimos em frente.'],
    ['或许', 'huòxǔ', 'possivelmente', 'advérbio', '或许这行得通。', 'Huòxǔ zhè xíngdetōng.', 'Possivelmente vai dar certo.'],
    ['怀疑态度', 'huáiyí tàidù', 'ceticismo', 'substantivo', '他们以怀疑态度接受了这个消息。', 'Tāmen yǐ huáiyí tàidù jiēshòule zhège xiāoxi.', 'Receberam a notícia com ceticismo.'],
    ['不确定性', 'bù quèdìngxìng', 'incerteza', 'substantivo', '我们生活在一个充满不确定性的时代。', 'Wǒmen shēnghuó zài yīgè chōngmǎn bù quèdìngxìng de shídài.', 'Vivemos um período de incerteza.'],
  ],
  C2: [
    ['紧迫感', 'jǐnpògǎn', 'urgência premente', 'substantivo', '局势的紧迫感要求采取行动。', 'Júshì de jǐnpògǎn yāoqiú cǎiqǔ xíngdòng.', 'A urgência da situação exigia ação.'],
    ['迂回的表达', 'yūhuí de biǎodá', 'circunlóquio', 'substantivo', '在法律文书中要避免迂回的表达。', 'Zài fǎlǜ wénshū zhōng yào bìmiǎn yūhuí de biǎodá.', 'Evite circunlóquios em textos jurídicos.'],
    ['泰然自若', 'tàiránzìruò', 'equanimidade', 'substantivo', '她泰然自若地接受了这个消息。', 'Tā tàiránzìruò de jiēshòule zhège xiāoxi.', 'Ela recebeu a notícia com equanimidade.'],
    ['蒙蔽', 'méngbì', 'obscurecimento proposital', 'substantivo', '这份报告充满了蒙蔽。', 'Zhè fèn bàogào chōngmǎnle méngbì.', 'O relatório está cheio de obscurecimento proposital.'],
    ['敷衍了事的', 'fūyǎn liǎoshì de', 'superficial / feito por obrigação', 'adjetivo', '那是一次敷衍了事的道歉。', 'Nà shì yī cì fūyǎn liǎoshì de dàoqiàn.', 'Foi um pedido de desculpas superficial.'],
    ['难以言表', 'nányǐyánbiǎo', 'indescritível', 'adjetivo', '那景色难以言表。', 'Nà jǐngsè nányǐyánbiǎo.', 'A vista era indescritível.'],
    ['无处不在', 'wúchùbùzài', 'onipresente', 'adjetivo', '智能手机现在无处不在。', 'Zhìnéng shǒujī xiànzài wúchùbùzài.', 'Os smartphones são onipresentes hoje.'],
    ['独特的', 'dútè de', 'idiossincrático / peculiar', 'adjetivo', '他的风格相当独特。', 'Tā de fēnggé xiāngdāng dútè.', 'O estilo dele é bem peculiar.'],
    ['岌岌可危的处境', 'jíjíkěwēi de chǔjìng', 'posição precária', 'substantivo', '他们的处境充其量是岌岌可危的。', 'Tāmen de chǔjìng chōngqíliàng shì jíjíkěwēi de.', 'A posição deles é, no máximo, precária.'],
    ['阴险', 'yīnxiǎn', 'insidioso', 'adjetivo', '这是一个阴险的问题。', 'Zhè shì yīgè yīnxiǎn de wèntí.', 'É um problema insidioso.'],
    ['并置', 'bìngzhì', 'justaposição', 'substantivo', '新旧的并置很引人注目。', 'Xīnjiù de bìngzhì hěn yǐnrén zhùmù.', 'A justaposição do velho com o novo impressiona.'],
    ['平反', 'píngfǎn', 'reconhecimento de razão', 'substantivo', '这个结果感觉像是一种平反。', 'Zhège jiéguǒ gǎnjué xiàng shì yī zhǒng píngfǎn.', 'Os resultados pareceram uma reabilitação para ela.'],
    ['默许', 'mòxǔ', 'anuência silenciosa', 'substantivo', '他的沉默意味着默许。', 'Tā de chénmò yìwèizhe mòxǔ.', 'O silêncio dele implicava anuência.'],
    ['不可改变的', 'bùkě gǎibiàn de', 'imutável', 'adjetivo', '有些规则看起来不可改变。', 'Yǒuxiē guīzé kàn qǐlái bùkě gǎibiàn.', 'Algumas regras parecem imutáveis.'],
    ['表面上的', 'biǎomiàn shàng de', 'aparente (mas duvidoso)', 'adjetivo', '表面上的原因是成本。', 'Biǎomiàn shàng de yuányīn shì chéngběn.', 'A razão aparente foi o custo.'],
    ['偷偷摸摸的', 'tōutōu mōmō de', 'sub-reptício / dissimulado', 'adjetivo', '偷偷摸摸地瞥了一眼笔记。', 'Tōutōu mōmō de piēle yīyǎn bǐjì.', 'Um olhar dissimulado para as anotações.'],
    ['沧桑', 'cāngsāng', 'vicissitude / altos e baixos da vida', 'substantivo', '人生的沧桑塑造了她。', 'Rénshēng de cāngsāng sùzàole tā.', 'As vicissitudes da vida a moldaram.'],
    ['专断的', 'zhuānduàn de', 'peremptório', 'adjetivo', '他的语气很专断。', 'Tā de yǔqì hěn zhuānduàn.', 'O tom dele foi peremptório.'],
    ['据称', 'jùchēng', 'supostamente', 'advérbio', '据称，这个计划很简单。', 'Jùchēng, zhège jìhuà hěn jiǎndān.', 'Supostamente, o plano é simples.'],
    ['迄今为止', 'qìjīnwéizhǐ', 'até agora / até então', 'advérbio', '一个迄今为止未知的事实浮出水面。', 'Yīgè qìjīnwéizhǐ wèizhī de shìshí fúchūshuǐmiàn.', 'Um fato até então desconhecido veio à tona.'],
  ],
};
