/**
 * Alemão — expressões por nível.
 *
 * Nenhuma expressão aqui repete o lote curado de `idioms.ts`.
 */

import type { ByLevel } from './entry';

export const DE: ByLevel = {
  A2: [
    ['na klar', '', 'ora claro', 'Claro que sim.', 'Claro', '', 'Kommst du mit? — Na klar!', 'Você vem junto? — Claro!', 'informal', 5],
    ['keine Ahnung', '', 'nenhuma noção', 'Não faço ideia.', 'Sei lá', '', 'Wo ist der Schlüssel? — Keine Ahnung.', 'Cadê a chave? — Sei lá.', 'informal', 5],
    ['macht nichts', '', 'faz nada', 'Não tem problema.', 'Sem problema', '', 'Du bist spät? Macht nichts.', 'Você atrasou? Sem problema.', 'informal', 5],
    ['auf jeden Fall', '', 'em cada caso', 'Com certeza, de todo jeito.', 'Com certeza', '', 'Ich komme auf jeden Fall.', 'Eu vou com certeza.', 'neutral', 5],
    ['alles klar', '', 'tudo claro', 'Tudo certo; entendido.', 'Tudo certo', '', 'Alles klar, bis morgen.', 'Tudo certo, até amanhã.', 'informal', 5],
    ['kein Problem', '', 'nenhum problema', 'Sem problema algum.', 'Sem problema', '', 'Kein Problem, ich helfe dir.', 'Sem problema, eu te ajudo.', 'neutral', 5],
    ['bis später', '', 'até mais tarde', 'Até logo, ainda hoje.', 'Até mais', '', 'Bis später im Büro.', 'Até mais no escritório.', 'informal', 5],
    ['viel Glück', '', 'muita sorte', 'Boa sorte.', 'Boa sorte', '', 'Viel Glück bei der Prüfung!', 'Boa sorte na prova!', 'neutral', 5],
    ['wie schade', '', 'que pena', 'Que pena.', 'Que pena', '', 'Wie schade, dass du nicht kommst.', 'Que pena que você não vem.', 'neutral', 4],
    ['genau', '', 'exato', 'Exatamente; é isso.', 'Exatamente', '', 'Genau, das meine ich.', 'Exatamente, é isso que quero dizer.', 'neutral', 5],
    ['ein bisschen', '', 'um pouquinho', 'Um pouco.', 'Um pouco', '', 'Ich spreche ein bisschen Deutsch.', 'Eu falo um pouco de alemão.', 'neutral', 5],
    ['auf keinen Fall', '', 'em nenhum caso', 'De jeito nenhum.', 'De jeito nenhum', '', 'Auf keinen Fall mache ich das.', 'De jeito nenhum eu faço isso.', 'neutral', 4],
    ['Lust haben auf', '', 'ter vontade em', 'Estar com vontade de algo.', 'Estar a fim de', '', 'Ich habe Lust auf Kaffee.', 'Estou a fim de um café.', 'informal', 5],
    ['es geht', '', 'isso vai', 'Mais ou menos; dá para levar.', 'Vai indo', '', 'Wie geht’s? — Es geht.', 'Como vai? — Vai indo.', 'informal', 5],
    ['kein Wunder', '', 'nenhum milagre', 'Não é de espantar.', 'Não é à toa', '', 'Kein Wunder, dass er müde ist.', 'Não é à toa que ele está cansado.', 'neutral', 4],
    ['mach’s gut', '', 'faça-o bem', 'Se cuida — despedida.', 'Se cuida', '', 'Mach’s gut, wir sehen uns.', 'Se cuida, a gente se vê.', 'informal', 4],
    ['es tut mir leid', '', 'isso me faz pena', 'Sinto muito.', 'Sinto muito', '', 'Es tut mir leid für gestern.', 'Sinto muito por ontem.', 'neutral', 5],
    ['Bescheid sagen', '', 'dizer informação', 'Avisar alguém.', 'Dar um toque', '', 'Sag mir Bescheid, wenn du da bist.', 'Me dá um toque quando chegar.', 'neutral', 5],
    ['zum Beispiel', '', 'para exemplo', 'Por exemplo.', 'Por exemplo', '', 'Nimm zum Beispiel diesen Fall.', 'Pegue por exemplo este caso.', 'neutral', 5],
    ['immer wieder', '', 'sempre de novo', 'Repetidamente.', 'Toda hora', '', 'Er fragt immer wieder dasselbe.', 'Ele pergunta a mesma coisa toda hora.', 'neutral', 4],
    ['ab und zu', '', 'de e para', 'De vez em quando.', 'De vez em quando', '', 'Ab und zu gehe ich schwimmen.', 'De vez em quando eu vou nadar.', 'neutral', 4],
    ['gar nicht', '', 'de todo não', 'Nem um pouco.', 'Nem um pouco', '', 'Das stört mich gar nicht.', 'Isso não me incomoda nem um pouco.', 'neutral', 5],
    ['Spaß machen', '', 'fazer diversão', 'Ser divertido; brincar.', 'Ser divertido', '', 'Das Spiel macht Spaß.', 'O jogo é divertido.', 'informal', 5],
    ['recht haben', '', 'ter direito', 'Estar certo.', 'Ter razão', '', 'Du hast recht damit.', 'Você tem razão nisso.', 'neutral', 5],
    ['keine Zeit haben', '', 'não ter tempo', 'Estar sem tempo.', 'Estar sem tempo', '', 'Ich habe heute keine Zeit.', 'Hoje eu não tenho tempo.', 'neutral', 5],
  ],
  B1: [
    ['unter vier Augen', '', 'sob quatro olhos', 'A sós, sem mais ninguém ouvindo.', 'A sós', '', 'Können wir das unter vier Augen besprechen?', 'Podemos conversar isso a sós?', 'neutral', 4],
    ['das ist mir Wurst', '', 'isso me é salsicha', 'Tanto faz para mim.', 'Tanto faz', '', 'Wo wir essen, ist mir Wurst.', 'Onde a gente come, tanto faz.', 'informal', 4],
    ['ich verstehe nur Bahnhof', '', 'eu entendo só estação de trem', 'Não estou entendendo nada.', 'Para mim é grego', 'Soldados da Primeira Guerra só ouviam "estação" — a viagem de volta para casa.', 'Bei diesem Thema verstehe ich nur Bahnhof.', 'Nesse assunto, para mim é grego.', 'informal', 4],
    ['auf die Nerven gehen', '', 'ir nos nervos', 'Irritar alguém.', 'Dar nos nervos', '', 'Der Lärm geht mir auf die Nerven.', 'O barulho me dá nos nervos.', 'informal', 5],
    ['den Faden verlieren', '', 'perder o fio', 'Perder a linha de raciocínio.', 'Perder o fio da meada', 'Do fio de Ariadne, no labirinto.', 'Entschuldigung, ich habe den Faden verloren.', 'Desculpe, perdi o fio da meada.', 'neutral', 4],
    ['ins Schwarze treffen', '', 'acertar no preto', 'Acertar exatamente o ponto.', 'Acertar na mosca', 'Do centro preto do alvo.', 'Mit dieser Analyse hast du ins Schwarze getroffen.', 'Com essa análise você acertou na mosca.', 'neutral', 3],
    ['auf dem Laufenden sein', '', 'estar no corrente', 'Estar atualizado sobre algo.', 'Estar por dentro', '', 'Ich halte dich auf dem Laufenden.', 'Vou te manter por dentro.', 'neutral', 4],
    ['auf die lange Bank schieben', '', 'empurrar para o banco longo', 'Adiar indefinidamente.', 'Empurrar com a barriga', 'Do banco longo dos tribunais medievais onde os processos ficavam parados.', 'Schieb das nicht auf die lange Bank.', 'Não empurre isso com a barriga.', 'neutral', 3],
    ['die Kurve kriegen', '', 'pegar a curva', 'Conseguir se ajeitar na hora certa.', 'Se ajeitar a tempo', '', 'Er hat gerade noch die Kurve gekriegt.', 'Ele conseguiu se ajeitar bem na hora.', 'informal', 3],
    ['Hals über Kopf', '', 'pescoço sobre cabeça', 'Às pressas, sem pensar.', 'Às pressas', '', 'Sie sind Hals über Kopf umgezogen.', 'Eles se mudaram às pressas.', 'informal', 3],
    ['das Herz auf der Zunge tragen', '', 'carregar o coração na língua', 'Dizer tudo o que sente na hora.', 'Ter o coração na boca', '', 'Sie trägt das Herz auf der Zunge.', 'Ela diz tudo o que sente.', 'neutral', 3],
    ['blau machen', '', 'fazer azul', 'Faltar ao trabalho sem justificativa.', 'Matar o trabalho', 'Da tinturaria: o dia em que o tecido azul secava e ninguém trabalhava.', 'Er hat gestern blau gemacht.', 'Ele matou o trabalho ontem.', 'informal', 3],
    ['Schlange stehen', '', 'ficar de cobra', 'Ficar na fila.', 'Pegar fila', '', 'Wir mussten eine Stunde Schlange stehen.', 'Tivemos de pegar fila por uma hora.', 'neutral', 4],
    ['die Ohren spitzen', '', 'apontar as orelhas', 'Prestar muita atenção.', 'Ficar de ouvido em pé', '', 'Bei dem Namen spitzte er die Ohren.', 'Ao ouvir o nome, ele ficou de ouvido em pé.', 'informal', 3],
    ['eine lange Leitung haben', '', 'ter um cabo longo', 'Demorar a entender.', 'Ter o pavio longo para entender', 'Da telefonia: quanto mais longo o cabo, maior o atraso.', 'Ich habe heute eine lange Leitung.', 'Hoje estou demorando para entender.', 'informal', 3],
    ['auf dem Schlauch stehen', '', 'estar em cima da mangueira', 'Travar sem entender o óbvio.', 'Dar branco', 'Quem pisa na mangueira não entende por que a água não sai.', 'Ich stehe gerade völlig auf dem Schlauch.', 'Deu um branco total agora.', 'informal', 3],
    ['sich ins Zeug legen', '', 'deitar-se no material', 'Empenhar-se de verdade.', 'Meter a cara', '', 'Sie hat sich richtig ins Zeug gelegt.', 'Ela realmente meteu a cara.', 'neutral', 3],
    ['kalte Füße bekommen', '', 'ficar com pés frios', 'Perder a coragem na hora H.', 'Amarelar', '', 'Er hat kalte Füße bekommen.', 'Ele amarelou.', 'informal', 3],
    ['aus dem Häuschen sein', '', 'estar fora da casinha', 'Estar eufórico.', 'Estar fora de si de alegria', '', 'Die Kinder waren völlig aus dem Häuschen.', 'As crianças estavam eufóricas.', 'informal', 3],
    ['eine Nachteule sein', '', 'ser uma coruja noturna', 'Ser pessoa da noite.', 'Ser notívago', '', 'Ich bin eine Nachteule.', 'Eu sou notívago.', 'informal', 3],
    ['das kannst du vergessen', '', 'isso você pode esquecer', 'Isso não vai acontecer.', 'Pode tirar o cavalo da chuva', '', 'Heute noch? Das kannst du vergessen.', 'Ainda hoje? Pode tirar o cavalo da chuva.', 'informal', 4],
    ['über den Weg laufen', '', 'correr pelo caminho', 'Encontrar alguém por acaso.', 'Dar de cara com', '', 'Gestern ist mir Anna über den Weg gelaufen.', 'Ontem dei de cara com a Anna.', 'informal', 3],
    ['jemandem den Kopf verdrehen', '', 'virar a cabeça de alguém', 'Deixar alguém apaixonado.', 'Virar a cabeça de alguém', '', 'Sie hat ihm den Kopf verdreht.', 'Ela virou a cabeça dele.', 'informal', 3],
    ['die Nase vorn haben', '', 'ter o nariz à frente', 'Estar na dianteira.', 'Estar na frente', 'Das corridas de cavalo.', 'Unser Team hat die Nase vorn.', 'Nosso time está na frente.', 'neutral', 3],
    ['sich etwas hinter die Ohren schreiben', '', 'escrever algo atrás das orelhas', 'Guardar bem um aviso.', 'Anotar atrás da orelha', 'Costume medieval de puxar a orelha de testemunhas jovens para fixar a memória.', 'Das solltest du dir hinter die Ohren schreiben.', 'Isso você devia guardar bem.', 'informal', 3],
  ],
  B2: [
    ['ins Fettnäpfchen treten', '', 'pisar no potinho de gordura', 'Cometer uma gafe.', 'Dar uma mancada', 'Do pote de graxa de sapato que ficava na entrada das casas.', 'Da bin ich ordentlich ins Fettnäpfchen getreten.', 'Aí eu dei uma bela mancada.', 'informal', 3],
    ['die Katze aus dem Sack lassen', '', 'deixar o gato sair do saco', 'Revelar o segredo.', 'Dar com a língua nos dentes', 'Das feiras medievais: vendia-se gato no saco no lugar de leitão.', 'Jetzt lass endlich die Katze aus dem Sack.', 'Agora conta logo o segredo.', 'informal', 3],
    ['ein Dorn im Auge sein', '', 'ser um espinho no olho', 'Ser algo que incomoda profundamente alguém.', 'Ser uma pedra no sapato', '', 'Diese Regel ist ihm ein Dorn im Auge.', 'Essa regra é uma pedra no sapato dele.', 'neutral', 3],
    ['wie ein Elefant im Porzellanladen', '', 'como um elefante na loja de porcelana', 'Agir sem nenhum tato numa situação delicada.', 'Como um elefante numa loja de cristais', '', 'Er verhandelt wie ein Elefant im Porzellanladen.', 'Ele negocia como um elefante numa loja de cristais.', 'neutral', 3],
    ['jemandem etwas in die Schuhe schieben', '', 'empurrar algo para dentro dos sapatos de alguém', 'Botar a culpa em outra pessoa.', 'Jogar a culpa em cima de alguém', 'De albergues medievais, onde o ladrão escondia o furto no sapato de outro hóspede.', 'Sie wollten mir den Fehler in die Schuhe schieben.', 'Queriam jogar o erro em cima de mim.', 'neutral', 3],
    ['den Kopf in den Sand stecken', '', 'enfiar a cabeça na areia', 'Recusar-se a encarar o problema.', 'Enterrar a cabeça na areia', '', 'Steck nicht den Kopf in den Sand.', 'Não enterre a cabeça na areia.', 'neutral', 4],
    ['das Blaue vom Himmel versprechen', '', 'prometer o azul do céu', 'Prometer o impossível.', 'Prometer mundos e fundos', '', 'Der Anbieter verspricht das Blaue vom Himmel.', 'O fornecedor promete mundos e fundos.', 'neutral', 3],
    ['alles in Butter', '', 'tudo em manteiga', 'Está tudo em ordem.', 'Tudo nos conformes', 'Louças eram transportadas dentro de manteiga para não quebrar.', 'Keine Sorge, alles in Butter.', 'Sem preocupação, está tudo nos conformes.', 'informal', 3],
    ['die Flinte ins Korn werfen', '', 'jogar a espingarda no trigo', 'Desistir precipitadamente.', 'Jogar a toalha', 'Do soldado que largava a arma e fugia pelo trigal.', 'Wirf die Flinte nicht ins Korn.', 'Não jogue a toalha.', 'neutral', 3],
    ['jemandem auf den Zahn fühlen', '', 'apalpar o dente de alguém', 'Sondar alguém para saber o que sabe.', 'Puxar pela língua', 'Do exame do dentista.', 'Der Journalist fühlte ihm auf den Zahn.', 'O jornalista puxou pela língua dele.', 'neutral', 3],
    ['aus einer Mücke einen Elefanten machen', '', 'fazer de um mosquito um elefante', 'Exagerar desmedidamente.', 'Fazer tempestade em copo d’água', '', 'Mach aus einer Mücke keinen Elefanten.', 'Não faça tempestade em copo d’água.', 'informal', 3],
    ['Bauklötze staunen', '', 'espantar-se em blocos de montar', 'Ficar de queixo caído.', 'Ficar de queixo caído', '', 'Da wirst du Bauklötze staunen.', 'Você vai ficar de queixo caído.', 'informal', 2],
    ['jemanden auf die Palme bringen', '', 'levar alguém para a palmeira', 'Deixar alguém furioso.', 'Tirar do sério', '', 'Diese Ausrede bringt mich auf die Palme.', 'Essa desculpa me tira do sério.', 'informal', 3],
    ['in den sauren Apfel beißen', '', 'morder a maçã azeda', 'Aceitar algo desagradável e inevitável.', 'Engolir o sapo', '', 'Wir müssen in den sauren Apfel beißen.', 'Temos de engolir o sapo.', 'neutral', 3],
    ['jemandem einen Bären aufbinden', '', 'amarrar um urso em alguém', 'Contar uma mentira absurda a alguém.', 'Contar uma lorota', '', 'Da hat er dir einen Bären aufgebunden.', 'Aí ele te contou uma lorota.', 'informal', 3],
    ['mit dem Kopf durch die Wand wollen', '', 'querer atravessar a parede com a cabeça', 'Insistir por força bruta onde não cabe.', 'Bater com a cabeça na parede', '', 'Du willst immer mit dem Kopf durch die Wand.', 'Você sempre quer bater com a cabeça na parede.', 'neutral', 3],
    ['Schwamm drüber', '', 'esponja por cima', 'Vamos esquecer isso.', 'Bola pra frente', 'Da esponja que apaga o quadro-negro.', 'Schwamm drüber, das ist vorbei.', 'Bola pra frente, isso já passou.', 'informal', 3],
    ['jemandem die Stirn bieten', '', 'oferecer a testa a alguém', 'Enfrentar alguém abertamente.', 'Peitar', '', 'Sie bot dem Vorstand die Stirn.', 'Ela peitou a diretoria.', 'formal', 3],
    ['sich aus dem Staub machen', '', 'fazer-se para fora da poeira', 'Sumir discretamente.', 'Dar no pé', 'Do cavaleiro que escapava na poeira do campo de batalha.', 'Er hat sich aus dem Staub gemacht.', 'Ele deu no pé.', 'informal', 3],
    ['auf großem Fuß leben', '', 'viver em pé grande', 'Viver com luxo acima do razoável.', 'Viver como rei', '', 'Sie leben auf großem Fuß.', 'Eles vivem como reis.', 'neutral', 3],
    ['ein Auge zudrücken', '', 'fechar um olho', 'Deixar passar uma falha de propósito.', 'Fazer vista grossa', '', 'Diesmal drücke ich ein Auge zu.', 'Desta vez eu faço vista grossa.', 'neutral', 4],
    ['Pi mal Daumen', '', 'pi vezes polegar', 'Por alto, no chute.', 'No olhômetro', '', 'Pi mal Daumen sind das dreißig Stück.', 'No olhômetro, são umas trinta peças.', 'informal', 3],
    ['jemandem das Wasser reichen können', '', 'poder alcançar a água a alguém', 'Chegar aos pés de alguém — quase sempre na negativa.', 'Chegar aos pés de', 'Dos criados que serviam a água aos senhores à mesa.', 'Niemand kann ihr das Wasser reichen.', 'Ninguém chega aos pés dela.', 'formal', 3],
    ['etwas unter den Teppich kehren', '', 'varrer algo para debaixo do tapete', 'Esconder um problema em vez de resolvê-lo.', 'Varrer para debaixo do tapete', '', 'Der Bericht wurde unter den Teppich gekehrt.', 'O relatório foi varrido para debaixo do tapete.', 'neutral', 3],
    ['die Nase rümpfen', '', 'torcer o nariz', 'Demonstrar desprezo.', 'Torcer o nariz', '', 'Sie rümpfte die Nase über den Vorschlag.', 'Ela torceu o nariz para a proposta.', 'neutral', 3],
  ],
  C1: [
    ['den Nagel auf den Kopf treffen', '', 'acertar o prego na cabeça', 'Dizer exatamente a coisa certa.', 'Acertar na mosca', 'Da carpintaria.', 'Mit dieser Bemerkung hast du den Nagel auf den Kopf getroffen.', 'Com esse comentário você acertou na mosca.', 'neutral', 4],
    ['das Handtuch werfen', '', 'jogar a toalha', 'Desistir depois de muito resistir.', 'Jogar a toalha', 'Do boxe.', 'Nach drei Jahren warf er das Handtuch.', 'Depois de três anos, ele jogou a toalha.', 'neutral', 3],
    ['Öl ins Feuer gießen', '', 'derramar óleo no fogo', 'Agravar um conflito de propósito.', 'Botar lenha na fogueira', '', 'Diese Aussage gießt Öl ins Feuer.', 'Essa declaração bota lenha na fogueira.', 'neutral', 3],
    ['auf dem Holzweg sein', '', 'estar no caminho de madeira', 'Estar completamente enganado.', 'Estar no caminho errado', 'Trilhas de madeireiros terminavam no meio do bosque, sem levar a lugar nenhum.', 'Wer das glaubt, ist auf dem Holzweg.', 'Quem acredita nisso está no caminho errado.', 'neutral', 3],
    ['jemandem reinen Wein einschenken', '', 'servir vinho puro a alguém', 'Contar a verdade sem suavizar.', 'Abrir o jogo', 'Vinho batizado com água era o costume; servir puro era ser honesto.', 'Ich schenke dir reinen Wein ein.', 'Vou abrir o jogo com você.', 'formal', 3],
    ['gute Miene zum bösen Spiel machen', '', 'fazer boa cara para o jogo ruim', 'Disfarçar o desagrado e seguir em frente.', 'Fazer boa cara para o mau tempo', '', 'Er machte gute Miene zum bösen Spiel.', 'Ele fez boa cara para o mau tempo.', 'formal', 3],
    ['Tacheles reden', '', 'falar Tacheles', 'Falar francamente, sem rodeios.', 'Falar na lata', 'Do iídiche "tachlis": o essencial.', 'Lass uns Tacheles reden.', 'Vamos falar na lata.', 'informal', 3],
    ['Butter bei die Fische', '', 'manteiga junto dos peixes', 'Vamos ao que interessa.', 'Vamos ao que interessa', 'Do norte da Alemanha: o prato só ficava pronto com a manteiga.', 'Also, Butter bei die Fische: was kostet es?', 'Então, vamos ao que interessa: quanto custa?', 'informal', 3],
    ['den Ball flach halten', '', 'manter a bola baixa', 'Não exagerar; manter a discrição.', 'Segurar a onda', 'Do futebol.', 'Halten wir vorerst den Ball flach.', 'Vamos segurar a onda por enquanto.', 'informal', 3],
    ['jemandem Paroli bieten', '', 'oferecer paroli a alguém', 'Fazer frente a alguém de igual para igual.', 'Bater de frente', 'Do faraó, jogo de cartas: dobrar a aposta.', 'Der kleine Anbieter bietet dem Konzern Paroli.', 'O pequeno fornecedor bate de frente com o grupo.', 'formal', 2],
    ['die Weichen stellen', '', 'ajustar os desvios de trilho', 'Definir agora o rumo do que vem depois.', 'Definir os rumos', 'Da ferrovia.', 'Heute stellen wir die Weichen für das nächste Jahr.', 'Hoje definimos os rumos do ano que vem.', 'formal', 3],
    ['im Trüben fischen', '', 'pescar na água turva', 'Agir sem clareza, ou aproveitar-se da confusão.', 'Pescar em águas turvas', '', 'Die Ermittler fischen noch im Trüben.', 'Os investigadores ainda pescam em águas turvas.', 'formal', 3],
    ['den Kürzeren ziehen', '', 'puxar o mais curto', 'Sair perdendo numa disputa.', 'Levar a pior', 'Do sorteio por palitos de tamanhos diferentes.', 'Im Streit zog er den Kürzeren.', 'Na disputa ele levou a pior.', 'neutral', 3],
    ['das Zünglein an der Waage sein', '', 'ser a linguetinha da balança', 'Ser o fator que decide um equilíbrio.', 'Ser o fiel da balança', '', 'Diese Stimme war das Zünglein an der Waage.', 'Aquele voto foi o fiel da balança.', 'formal', 2],
    ['jemandem den Wind aus den Segeln nehmen', '', 'tirar o vento das velas de alguém', 'Desarmar o argumento do outro antes que ele o use.', 'Tirar o chão de alguém', 'Da navegação à vela.', 'Mit dieser Zahl nahm sie ihm den Wind aus den Segeln.', 'Com esse número ela tirou o chão dele.', 'formal', 3],
    ['den Stier bei den Hörnern packen', '', 'agarrar o touro pelos chifres', 'Enfrentar o problema de frente.', 'Pegar o touro à unha', '', 'Packen wir den Stier bei den Hörnern.', 'Vamos pegar o touro à unha.', 'neutral', 3],
    ['zwischen Baum und Borke stecken', '', 'estar entre a árvore e a casca', 'Estar preso entre duas opções ruins.', 'Estar entre a cruz e a espada', '', 'Der Vermittler steckt zwischen Baum und Borke.', 'O mediador está entre a cruz e a espada.', 'formal', 2],
    ['sich etwas auf die Fahne schreiben', '', 'escrever algo na própria bandeira', 'Assumir algo como bandeira pública.', 'Levantar a bandeira de', '', 'Die Partei hat sich das auf die Fahne geschrieben.', 'O partido levantou essa bandeira.', 'formal', 2],
    ['mit allen Wassern gewaschen sein', '', 'estar lavado com todas as águas', 'Ser experiente e cheio de recursos.', 'Ter calo na profissão', 'Do marinheiro que já navegou todos os mares.', 'Der Anwalt ist mit allen Wassern gewaschen.', 'O advogado tem calo na profissão.', 'formal', 2],
    ['das Ruder herumreißen', '', 'virar o leme', 'Reverter uma situação já perdida.', 'Virar o jogo', 'Da navegação.', 'Im letzten Quartal haben sie das Ruder herumgerissen.', 'No último trimestre eles viraram o jogo.', 'formal', 3],
    ['Klartext reden', '', 'falar texto claro', 'Falar sem eufemismo.', 'Falar claro', '', 'Reden wir Klartext über die Kosten.', 'Vamos falar claro sobre os custos.', 'neutral', 3],
    ['die Kirche im Dorf lassen', '', 'deixar a igreja na aldeia', 'Não exagerar; manter a proporção.', 'Não passar do ponto', 'Procissões que davam voltas exageradas pela cidade.', 'Lassen wir die Kirche im Dorf.', 'Vamos manter a proporção.', 'informal', 2],
    ['jemandem auf den Leim gehen', '', 'ir na cola de alguém', 'Cair no golpe de alguém.', 'Cair no conto do vigário', 'Da cola usada para capturar pássaros.', 'Wir sind ihm auf den Leim gegangen.', 'Caímos no conto do vigário dele.', 'neutral', 3],
    ['etwas ins Rollen bringen', '', 'pôr algo a rolar', 'Deflagrar um processo.', 'Botar para andar', '', 'Der Artikel brachte die Sache ins Rollen.', 'O artigo botou a coisa para andar.', 'formal', 3],
    ['aus dem Ruder laufen', '', 'sair do leme', 'Sair do controle.', 'Fugir ao controle', 'Da navegação.', 'Die Kosten laufen aus dem Ruder.', 'Os custos estão fugindo ao controle.', 'formal', 3],
  ],
  C2: [
    ['der Sündenbock sein', '', 'ser o bode dos pecados', 'Levar a culpa de todos.', 'Ser o bode expiatório', 'Do rito hebraico do Yom Kipur.', 'Er war der Sündenbock der Affäre.', 'Ele foi o bode expiatório do caso.', 'formal', 3],
    ['die Spitze des Eisbergs', '', 'a ponta do iceberg', 'A fração visível de um problema muito maior.', 'A ponta do iceberg', '', 'Diese Fälle sind nur die Spitze des Eisbergs.', 'Esses casos são só a ponta do iceberg.', 'formal', 3],
    ['ein Pyrrhussieg', '', 'uma vitória de Pirro', 'Vitória que custa mais do que vale.', 'Vitória de Pirro', 'Do rei Pirro do Epiro, 279 a.C.', 'Das Urteil war ein Pyrrhussieg.', 'A sentença foi uma vitória de Pirro.', 'formal', 2],
    ['zwischen den Zeilen lesen', '', 'ler entre as linhas', 'Captar o que ficou implícito.', 'Ler nas entrelinhas', '', 'Man muss zwischen den Zeilen lesen.', 'É preciso ler nas entrelinhas.', 'formal', 3],
    ['die Achillesferse', '', 'o calcanhar de Aquiles', 'O ponto fraco decisivo.', 'Calcanhar de Aquiles', 'Da Ilíada.', 'Die Lieferkette ist ihre Achillesferse.', 'A cadeia de suprimentos é o calcanhar de Aquiles deles.', 'formal', 3],
    ['ein Damoklesschwert', '', 'uma espada de Dâmocles', 'Ameaça permanente suspensa sobre alguém.', 'Espada de Dâmocles', 'Da corte de Dionísio de Siracusa.', 'Die Klage ist ein Damoklesschwert.', 'O processo é uma espada de Dâmocles.', 'formal', 2],
    ['den Rubikon überschreiten', '', 'atravessar o Rubicão', 'Dar o passo sem volta.', 'Cruzar o Rubicão', 'César, em 49 a.C.', 'Mit der Unterschrift überschritten sie den Rubikon.', 'Com a assinatura, cruzaram o Rubicão.', 'formal', 2],
    ['ein trojanisches Pferd', '', 'um cavalo de Troia', 'Ameaça que entra disfarçada de presente.', 'Cavalo de Troia', 'Da Eneida.', 'Diese Klausel ist ein trojanisches Pferd.', 'Aquela cláusula é um cavalo de Troia.', 'formal', 3],
    ['das Kind mit dem Bade ausschütten', '', 'jogar fora a criança com a água do banho', 'Descartar o bom junto com o ruim.', 'Jogar fora o bom com o ruim', 'Registrada por Thomas Murner em 1512.', 'Damit schütten wir das Kind mit dem Bade aus.', 'Com isso jogamos fora o bom com o ruim.', 'formal', 2],
    ['Perlen vor die Säue werfen', '', 'jogar pérolas aos porcos', 'Oferecer o valioso a quem não reconhece.', 'Dar pérolas aos porcos', 'Do Evangelho de Mateus.', 'Das ist, als würfe man Perlen vor die Säue.', 'Isso é como dar pérolas aos porcos.', 'formal', 2],
    ['in der Wüste predigen', '', 'pregar no deserto', 'Falar sem que ninguém escute.', 'Pregar no deserto', 'De João Batista.', 'Ich predige seit Jahren in der Wüste.', 'Prego no deserto há anos.', 'formal', 2],
    ['ein Kartenhaus', '', 'um castelo de cartas', 'Estrutura que desaba ao primeiro abalo.', 'Castelo de cartas', '', 'Das Konstrukt war ein Kartenhaus.', 'A montagem era um castelo de cartas.', 'formal', 3],
    ['ein Sturm im Wasserglas', '', 'uma tempestade num copo d’água', 'Alvoroço enorme por algo mínimo.', 'Tempestade em copo d’água', '', 'Die Debatte war ein Sturm im Wasserglas.', 'O debate foi tempestade em copo d’água.', 'formal', 3],
    ['die Gans schlachten, die goldene Eier legt', '', 'abater o ganso que põe ovos de ouro', 'Destruir a própria fonte de ganho.', 'Matar a galinha dos ovos de ouro', 'De Esopo.', 'Solche Gebühren schlachten die Gans, die goldene Eier legt.', 'Taxas assim matam a galinha dos ovos de ouro.', 'formal', 2],
    ['den gordischen Knoten durchschlagen', '', 'cortar o nó górdio', 'Resolver um impasse com um golpe decisivo.', 'Cortar o nó górdio', 'Alexandre, o Grande.', 'Der Vorstand durchschlug den gordischen Knoten.', 'A diretoria cortou o nó górdio.', 'formal', 2],
    ['Kleider machen Leute', '', 'roupas fazem pessoas', 'A aparência determina como você é tratado.', 'Quem vê cara não vê coração — pelo avesso', 'Título de uma novela de Gottfried Keller.', 'Kleider machen Leute, leider.', 'A aparência define o tratamento, infelizmente.', 'formal', 2],
    ['es ist nicht alles Gold, was glänzt', '', 'nem tudo que brilha é ouro', 'Nem toda aparência boa corresponde à realidade.', 'Nem tudo que reluz é ouro', '', 'Es ist nicht alles Gold, was glänzt.', 'Nem tudo que reluz é ouro.', 'neutral', 3],
    ['der Teufel steckt im Detail', '', 'o diabo está no detalhe', 'O problema está nos pormenores.', 'O diabo mora nos detalhes', '', 'Prüf den Vertrag: der Teufel steckt im Detail.', 'Confira o contrato: o diabo mora nos detalhes.', 'formal', 3],
    ['Eulen nach Athen tragen', '', 'levar corujas para Atenas', 'Fazer algo redundante, levar o que já sobra.', 'Vender geladeira a esquimó', 'Atenas tinha a coruja como símbolo e ela estava em toda parte.', 'Ihm Ratschläge zu geben, heißt Eulen nach Athen tragen.', 'Dar conselhos a ele é chover no molhado.', 'formal', 2],
    ['den Teufel mit dem Beelzebub austreiben', '', 'expulsar o diabo com Belzebu', 'Trocar um problema por outro pior.', 'Trocar seis por meia dúzia — para pior', 'Dos Evangelhos.', 'Diese Lösung treibt den Teufel mit dem Beelzebub aus.', 'Essa solução troca um problema por outro pior.', 'formal', 2],
    ['auf Sand gebaut', '', 'construído sobre areia', 'Baseado em fundamento frágil.', 'Construído sobre areia', 'Da parábola das duas casas, no Evangelho de Mateus.', 'Diese Prognose ist auf Sand gebaut.', 'Essa previsão foi construída sobre areia.', 'formal', 2],
    ['Schall und Rauch', '', 'som e fumaça', 'Palavras vazias, sem substância.', 'Conversa fiada', 'Do Fausto, de Goethe.', 'Solche Versprechen sind Schall und Rauch.', 'Promessas assim são conversa fiada.', 'formal', 2],
    ['ein Wolf im Schafspelz', '', 'um lobo em pele de ovelha', 'Ameaça disfarçada de coisa inofensiva.', 'Lobo em pele de cordeiro', 'Do Evangelho de Mateus.', 'Der Investor war ein Wolf im Schafspelz.', 'O investidor era um lobo em pele de cordeiro.', 'formal', 3],
    ['die Büchse der Pandora öffnen', '', 'abrir a caixa de Pandora', 'Desencadear males incontroláveis.', 'Abrir a caixa de Pandora', 'Da mitologia grega.', 'Diese Entscheidung öffnet die Büchse der Pandora.', 'Essa decisão abre a caixa de Pandora.', 'formal', 2],
    ['Wasser predigen und Wein trinken', '', 'pregar água e beber vinho', 'Exigir dos outros o que não se cumpre.', 'Fazer o que eu digo, não o que eu faço', 'Popularizada por Heinrich Heine.', 'Sie predigen Wasser und trinken Wein.', 'Eles fazem o que dizem que ninguém deve fazer.', 'formal', 2],
  ],
};
