/**
 * Espanhol — expressões por nível.
 *
 * Nenhuma expressão aqui repete o lote curado de `idioms.ts`.
 */

import type { ByLevel } from './entry';

export const ES: ByLevel = {
  A2: [
    ['ni modo', '', 'nem modo', 'Não tem jeito; fazer o quê.', 'Fazer o quê', 'Muito frequente no espanhol do México.', 'No hay entradas, ni modo.', 'Não tem ingresso, fazer o quê.', 'informal', 5],
    ['vale', '', 'vale', 'Ok, combinado — a confirmação mais comum na Espanha.', 'Beleza', '', 'Nos vemos a las ocho. — Vale.', 'A gente se vê às oito. — Beleza.', 'informal', 5],
    ['dar igual', '', 'dar igual', 'Tanto faz; não faz diferença.', 'Tanto faz', '', 'Me da igual el color.', 'Tanto faz a cor para mim.', 'informal', 5],
    ['un montón', '', 'um monte', 'Muitíssimo; uma quantidade enorme.', 'Um montão', '', 'Tengo un montón de trabajo.', 'Tenho um montão de trabalho.', 'informal', 5],
    ['qué va', '', 'que vai', 'Que nada; de jeito nenhum.', 'Que nada', '', '¿Estás enfadado? — ¡Qué va!', 'Você está bravo? — Que nada!', 'informal', 4],
    ['por supuesto', '', 'por suposto', 'Claro; sem dúvida.', 'Claro', '', 'Por supuesto que puedes venir.', 'Claro que você pode vir.', 'neutral', 5],
    ['¡ojo!', '', 'olho!', 'Atenção; cuidado com isso.', 'Olha o perigo!', '', '¡Ojo con el escalón!', 'Cuidado com o degrau!', 'informal', 4],
    ['ahora mismo', '', 'agora mesmo', 'Neste exato momento.', 'Agora mesmo', '', 'Lo hago ahora mismo.', 'Faço agora mesmo.', 'neutral', 5],
    ['poco a poco', '', 'pouco a pouco', 'Devagar, aos poucos.', 'Aos poucos', '', 'Poco a poco vas mejorando.', 'Aos poucos você vai melhorando.', 'neutral', 4],
    ['de repente', '', 'de repente', 'Subitamente, sem aviso.', 'De repente', '', 'De repente empezó a llover.', 'De repente começou a chover.', 'neutral', 4],
    ['tener ganas de', '', 'ter vontades de', 'Estar com vontade de fazer algo.', 'Estar a fim de', '', 'Tengo ganas de salir.', 'Estou a fim de sair.', 'informal', 5],
    ['dar un paseo', '', 'dar um passeio', 'Sair para caminhar sem pressa.', 'Dar uma volta', '', 'Vamos a dar un paseo.', 'Vamos dar uma volta.', 'neutral', 4],
    ['hacer caso', '', 'fazer caso', 'Dar atenção ao que alguém diz.', 'Dar ouvidos', '', 'No le hagas caso.', 'Não dê ouvidos a ele.', 'informal', 5],
    ['en seguida', '', 'em seguida', 'Já, num instante.', 'Num instante', '', 'Vuelvo en seguida.', 'Volto num instante.', 'neutral', 4],
    ['por si acaso', '', 'por se acaso', 'Por precaução.', 'Por via das dúvidas', '', 'Lleva paraguas por si acaso.', 'Leve guarda-chuva por via das dúvidas.', 'neutral', 4],
    ['tener prisa', '', 'ter pressa', 'Estar com pressa.', 'Estar com pressa', '', 'Perdona, tengo prisa.', 'Desculpa, estou com pressa.', 'neutral', 5],
    ['a lo mejor', '', 'ao melhor', 'Talvez; pode ser que.', 'Vai que', '', 'A lo mejor viene mañana.', 'Talvez ele venha amanhã.', 'informal', 4],
    ['ya está', '', 'já está', 'Pronto, acabou.', 'Pronto', '', 'Ya está, terminamos.', 'Pronto, terminamos.', 'informal', 5],
    ['qué tal', '', 'que tal', 'E aí? — cumprimento e pergunta sobre algo.', 'E aí', '', '¿Qué tal el examen?', 'E aí, como foi a prova?', 'informal', 5],
    ['sin falta', '', 'sem falta', 'Com certeza, sem exceção.', 'Sem falta', '', 'Te llamo mañana sin falta.', 'Te ligo amanhã sem falta.', 'neutral', 4],
    ['de vez en cuando', '', 'de vez em quando', 'Ocasionalmente.', 'De vez em quando', '', 'Voy al cine de vez en cuando.', 'Vou ao cinema de vez em quando.', 'neutral', 4],
    ['hacer falta', '', 'fazer falta', 'Ser necessário.', 'Ser preciso', '', 'Hace falta más tiempo.', 'É preciso mais tempo.', 'neutral', 5],
    ['valer la pena', '', 'valer a pena', 'Compensar o esforço.', 'Valer a pena', '', 'Vale la pena intentarlo.', 'Vale a pena tentar.', 'neutral', 5],
    ['estar de acuerdo', '', 'estar de acordo', 'Concordar com alguém.', 'Concordar', '', 'Estoy de acuerdo contigo.', 'Concordo com você.', 'neutral', 5],
    ['dar las gracias', '', 'dar as graças', 'Agradecer formalmente.', 'Agradecer', '', 'Quiero dar las gracias a todos.', 'Quero agradecer a todos.', 'neutral', 4],
  ],
  B1: [
    ['estar hecho polvo', '', 'estar feito pó', 'Estar exausto, acabado.', 'Estar acabado', '', 'Llegué a casa hecho polvo.', 'Cheguei em casa acabado.', 'informal', 4],
    ['ponerse las pilas', '', 'colocar as pilhas', 'Começar a se esforçar de verdade.', 'Botar pilha; se ligar', '', 'Ponte las pilas, el examen es el lunes.', 'Se liga, a prova é segunda.', 'informal', 4],
    ['no pegar ojo', '', 'não pregar olho', 'Não conseguir dormir nada.', 'Não pregar o olho', '', 'No consigo pegar ojo por las noches.', 'Não consigo pregar o olho à noite.', 'informal', 4],
    ['quedarse en blanco', '', 'ficar em branco', 'Esquecer tudo na hora decisiva.', 'Dar branco', '', 'Me quedé en blanco en la entrevista.', 'Deu branco na entrevista.', 'informal', 4],
    ['ser uña y carne', '', 'ser unha e carne', 'Ser inseparáveis.', 'Ser unha e carne', '', 'Esos dos son uña y carne.', 'Aqueles dois são unha e carne.', 'informal', 3],
    ['echar de menos', '', 'jogar de menos', 'Sentir falta de alguém ou algo.', 'Sentir falta', '', 'Echo de menos a mi familia.', 'Sinto falta da minha família.', 'neutral', 5],
    ['tener buena pinta', '', 'ter boa pinta', 'Parecer bom, ter boa aparência.', 'Ter uma cara boa', '', 'Ese plato tiene buena pinta.', 'Esse prato está com uma cara boa.', 'informal', 4],
    ['dar la lata', '', 'dar a lata', 'Importunar insistentemente.', 'Encher o saco', '', 'Deja de dar la lata.', 'Para de encher o saco.', 'informal', 4],
    ['meter la pata', '', 'meter a pata', 'Cometer uma gafe.', 'Dar mancada', '', 'Metí la pata delante de todos.', 'Dei uma mancada na frente de todos.', 'informal', 4],
    ['ser un rollo', '', 'ser um rolo', 'Ser muito chato e demorado.', 'Ser um saco', '', 'La reunión fue un rollo.', 'A reunião foi um saco.', 'informal', 4],
    ['ir al grano', '', 'ir ao grão', 'Ir direto ao ponto.', 'Ir direto ao ponto', '', 'Vamos al grano, por favor.', 'Vamos direto ao ponto, por favor.', 'neutral', 4],
    ['hacer novillos', '', 'fazer novilhos', 'Faltar à aula sem justificativa.', 'Matar aula', 'De quando os estudantes fugiam para ver touros jovens.', 'Hizo novillos toda la semana.', 'Matou aula a semana inteira.', 'informal', 3],
    ['no tener ni idea', '', 'não ter nem ideia', 'Não saber absolutamente nada sobre algo.', 'Não fazer ideia', '', 'No tengo ni idea de dónde está.', 'Não faço ideia de onde ele está.', 'informal', 5],
    ['pasarlo bomba', '', 'passá-lo bomba', 'Divertir-se muitíssimo.', 'Se divertir à beça', '', 'Lo pasamos bomba en la fiesta.', 'A gente se divertiu à beça na festa.', 'informal', 3],
    ['estar de bajón', '', 'estar de baixão', 'Estar para baixo, desanimado.', 'Estar na fossa', '', 'Estoy de bajón esta semana.', 'Estou na fossa esta semana.', 'informal', 3],
    ['ser la leche', '', 'ser o leite', 'Ser incrível — ou inacreditável, conforme o tom.', 'Ser demais', '', 'Este café es la leche.', 'Esse café é demais.', 'informal', 3],
    ['matar dos pájaros de un tiro', '', 'matar dois pássaros de um tiro', 'Resolver duas coisas com um só esforço.', 'Matar dois coelhos com uma cajadada', '', 'Así matamos dos pájaros de un tiro.', 'Assim matamos dois coelhos com uma cajadada.', 'neutral', 4],
    ['hablar por los codos', '', 'falar pelos cotovelos', 'Falar sem parar.', 'Falar pelos cotovelos', '', 'Mi tía habla por los codos.', 'Minha tia fala pelos cotovelos.', 'informal', 4],
    ['estar como pez en el agua', '', 'estar como peixe na água', 'Sentir-se completamente à vontade.', 'Estar como peixe na água', '', 'En el escenario está como pez en el agua.', 'No palco ele está como peixe na água.', 'neutral', 3],
    ['sacar de quicio', '', 'tirar do batente', 'Irritar profundamente alguém.', 'Tirar do sério', 'Quicio é o batente da porta: tirar a porta do lugar.', 'Ese ruido me saca de quicio.', 'Esse barulho me tira do sério.', 'informal', 4],
    ['quedarse frito', '', 'ficar frito', 'Apagar de sono.', 'Apagar', '', 'Se quedó frito en el sofá.', 'Ele apagou no sofá.', 'informal', 3],
    ['tener mala pata', '', 'ter má pata', 'Ter azar.', 'Ter azar', '', '¡Qué mala pata, otra vez llueve!', 'Que azar, chovendo de novo!', 'informal', 3],
    ['estar sin blanca', '', 'estar sem branca', 'Estar sem dinheiro nenhum.', 'Estar duro', 'Blanca era uma moeda medieval de pouco valor.', 'Este mes estoy sin blanca.', 'Este mês estou duro.', 'informal', 3],
    ['ser un manitas', '', 'ser um mãozinhas', 'Ter jeito para consertar tudo.', 'Ser bom de mão', '', 'Mi padre es un manitas.', 'Meu pai é bom de mão.', 'informal', 3],
    ['tener el día tonto', '', 'ter o dia bobo', 'Estar num dia em que tudo sai errado.', 'Estar com o dia atravessado', '', 'Hoy tengo el día tonto.', 'Hoje meu dia está atravessado.', 'informal', 3],
  ],
  B2: [
    ['irse por las ramas', '', 'ir-se pelos galhos', 'Fugir do assunto principal.', 'Enrolar; fazer rodeios', '', 'No te vayas por las ramas.', 'Não faça rodeios.', 'neutral', 4],
    ['hacer la vista gorda', '', 'fazer a vista gorda', 'Fingir que não viu algo errado.', 'Fazer vista grossa', '', 'El jefe hizo la vista gorda.', 'O chefe fez vista grossa.', 'neutral', 4],
    ['estar de mala leche', '', 'estar de leite ruim', 'Estar de péssimo humor.', 'Estar de mau humor', '', 'Hoy está de mala leche.', 'Hoje ele está de mau humor.', 'informal', 4],
    ['tirar la casa por la ventana', '', 'jogar a casa pela janela', 'Gastar sem limite numa ocasião.', 'Botar a casa abaixo', 'Costume espanhol de jogar móveis velhos fora ao ganhar na loteria.', 'Tiraron la casa por la ventana en la boda.', 'Gastaram sem limite no casamento.', 'informal', 3],
    ['echar leña al fuego', '', 'jogar lenha no fogo', 'Piorar um conflito de propósito.', 'Botar lenha na fogueira', '', 'No eches leña al fuego ahora.', 'Não bote lenha na fogueira agora.', 'neutral', 4],
    ['ir viento en popa', '', 'ir vento em popa', 'Progredir muito bem.', 'Ir de vento em popa', 'Da navegação à vela: vento vindo por trás.', 'El negocio va viento en popa.', 'O negócio vai de vento em popa.', 'neutral', 3],
    ['dar gato por liebre', '', 'dar gato por lebre', 'Enganar entregando coisa pior que a prometida.', 'Vender gato por lebre', 'Das estalagens medievais.', 'Nos dieron gato por liebre con ese coche.', 'Nos venderam gato por lebre naquele carro.', 'informal', 3],
    ['estar en el ajo', '', 'estar no alho', 'Estar por dentro de um assunto reservado.', 'Estar por dentro', '', 'Ella parece estar en el ajo desde el principio.', 'Ela parece estar por dentro desde o começo.', 'informal', 3],
    ['ponerse las botas', '', 'colocar as botas', 'Aproveitar ao máximo, sobretudo comendo.', 'Se empanturrar', 'Antigamente só os ricos tinham botas.', 'Nos pusimos las botas en el buffet.', 'Nos empanturramos no bufê.', 'informal', 3],
    ['no dar el brazo a torcer', '', 'não dar o braço a torcer', 'Não ceder de jeito nenhum.', 'Não dar o braço a torcer', '', 'Nunca da el brazo a torcer.', 'Ele nunca dá o braço a torcer.', 'neutral', 4],
    ['tener la sartén por el mango', '', 'ter a frigideira pelo cabo', 'Estar em posição de mando na negociação.', 'Estar com a faca e o queijo na mão', '', 'Ahora ellos tienen la sartén por el mango.', 'Agora eles estão com a faca e o queijo na mão.', 'neutral', 3],
    ['estar entre la espada y la pared', '', 'estar entre a espada e a parede', 'Estar sem alternativa boa.', 'Estar entre a cruz e a espada', '', 'Me dejaron entre la espada y la pared.', 'Me deixaram entre a cruz e a espada.', 'neutral', 4],
    ['ser el ojo derecho de alguien', '', 'ser o olho direito de alguém', 'Ser o preferido de alguém com poder.', 'Ser o queridinho', '', 'Es el ojo derecho del director.', 'Ele é o queridinho do diretor.', 'informal', 3],
    ['salirse con la suya', '', 'sair-se com a sua', 'Conseguir o que queria apesar da oposição.', 'Fazer o que bem entende', '', 'Al final se salió con la suya.', 'No fim, ele fez o que bem entendeu.', 'neutral', 4],
    ['quedarse de piedra', '', 'ficar de pedra', 'Ficar completamente atônito.', 'Ficar de queixo caído', '', 'Me quedé de piedra al verlo.', 'Fiquei de queixo caído ao ver aquilo.', 'informal', 4],
    ['no dar pie con bola', '', 'não dar pé com bola', 'Errar tudo, não acertar nada.', 'Não acertar uma', '', 'Hoy no doy pie con bola.', 'Hoje não acerto uma.', 'informal', 3],
    ['ser un chollo', '', 'ser uma pechincha', 'Ser uma oportunidade muito vantajosa.', 'Ser uma pechincha', '', 'Ese piso es un chollo.', 'Aquele apartamento é uma pechincha.', 'informal', 3],
    ['estar hasta las narices', '', 'estar até os narizes', 'Estar completamente farto.', 'Estar de saco cheio', '', 'Estoy hasta las narices de esperar.', 'Estou de saco cheio de esperar.', 'informal', 4],
    ['montar un pollo', '', 'montar um frango', 'Fazer um escândalo em público.', 'Dar um chilique', '', 'Montó un pollo en la tienda.', 'Deu um chilique na loja.', 'informal', 3],
    ['cortar por lo sano', '', 'cortar pelo são', 'Encerrar de forma drástica para não piorar.', 'Cortar o mal pela raiz', 'Da cirurgia: cortar na parte ainda saudável.', 'Cortamos por lo sano y cerramos el trato.', 'Cortamos o mal pela raiz e encerramos o acordo.', 'neutral', 3],
    ['dar plantón', '', 'dar plantão', 'Deixar alguém esperando e não aparecer.', 'Dar bolo', '', 'Me dio plantón otra vez.', 'Ele me deu bolo de novo.', 'informal', 3],
    ['poner el grito en el cielo', '', 'pôr o grito no céu', 'Reagir com indignação escandalosa.', 'Pôr a boca no trombone', '', 'Pusieron el grito en el cielo por el precio.', 'Puseram a boca no trombone por causa do preço.', 'neutral', 3],
    ['tener enchufe', '', 'ter tomada', 'Conseguir algo por conhecer alguém.', 'Ter QI; ter pistolão', '', 'Consiguió el puesto porque tiene enchufe.', 'Conseguiu a vaga porque tem pistolão.', 'informal', 3],
    ['llevarse el gato al agua', '', 'levar o gato à água', 'Vencer uma disputa difícil.', 'Levar a melhor', '', 'Al final se llevó el gato al agua.', 'No fim, ele levou a melhor.', 'informal', 3],
    ['estar en las últimas', '', 'estar nas últimas', 'Estar no fim das forças ou dos recursos.', 'Estar nas últimas', '', 'La batería está en las últimas.', 'A bateria está nas últimas.', 'informal', 3],
  ],
  C1: [
    ['poner el dedo en la llaga', '', 'pôr o dedo na ferida', 'Tocar exatamente no ponto doloroso.', 'Pôr o dedo na ferida', '', 'Pusiste el dedo en la llaga con esa pregunta.', 'Você pôs o dedo na ferida com essa pergunta.', 'neutral', 4],
    ['tirar la toalla', '', 'jogar a toalha', 'Desistir depois de muito tentar.', 'Jogar a toalha', 'Do boxe: o córner joga a toalha para encerrar a luta.', 'No tires la toalla todavía.', 'Não jogue a toalha ainda.', 'neutral', 4],
    ['a buenas horas', '', 'a boas horas', 'Tarde demais — dito com ironia.', 'Agora é tarde', '', '¡A buenas horas avisas!', 'Agora é tarde para avisar!', 'informal', 3],
    ['buscarle tres pies al gato', '', 'procurar três pés no gato', 'Complicar o que é simples.', 'Procurar pelo em ovo', '', 'No le busques tres pies al gato.', 'Não procure pelo em ovo.', 'informal', 3],
    ['hacer el agosto', '', 'fazer o agosto', 'Lucrar muito numa oportunidade breve.', 'Fazer a festa', 'Da colheita de agosto na Espanha.', 'Los hoteles hicieron el agosto.', 'Os hotéis fizeram a festa.', 'neutral', 3],
    ['dar la vuelta a la tortilla', '', 'virar a omelete', 'Inverter completamente a situação.', 'Virar o jogo', '', 'En el segundo tiempo dieron la vuelta a la tortilla.', 'No segundo tempo viraram o jogo.', 'informal', 3],
    ['andar con pies de plomo', '', 'andar com pés de chumbo', 'Agir com extrema cautela.', 'Pisar em ovos', '', 'Con ese cliente hay que andar con pies de plomo.', 'Com aquele cliente é preciso pisar em ovos.', 'neutral', 3],
    ['arrimar el ascua a su sardina', '', 'aproximar a brasa da sua sardinha', 'Puxar tudo para o próprio interesse.', 'Puxar a brasa para a sua sardinha', '', 'Cada uno arrima el ascua a su sardina.', 'Cada um puxa a brasa para a sua sardinha.', 'neutral', 2],
    ['estar en el candelero', '', 'estar no candelabro', 'Estar em evidência pública no momento.', 'Estar em evidência', '', 'Ese tema está en el candelero.', 'Esse tema está em evidência.', 'formal', 2],
    ['curarse en salud', '', 'curar-se em saúde', 'Prevenir-se antes que o problema apareça.', 'Prevenir-se', '', 'Aclaré todo por curarme en salud.', 'Esclareci tudo por precaução.', 'formal', 2],
    ['atar cabos', '', 'amarrar cabos', 'Juntar indícios até entender o quadro.', 'Ligar os pontos', 'Da marinharia.', 'Até cabos y entendí lo que pasaba.', 'Liguei os pontos e entendi o que acontecia.', 'neutral', 3],
    ['echar balones fuera', '', 'chutar as bolas para fora', 'Desviar da pergunta para não se comprometer.', 'Jogar para a plateia', 'Do futebol: chutar a bola para fora para ganhar tempo.', 'El ministro echó balones fuera.', 'O ministro desviou da pergunta.', 'formal', 3],
    ['sacar los trapos sucios', '', 'tirar os trapos sujos', 'Expor publicamente as falhas alheias.', 'Lavar roupa suja em público', '', 'Empezaron a sacar los trapos sucios.', 'Começaram a lavar roupa suja em público.', 'informal', 3],
    ['hacer de tripas corazón', '', 'fazer das tripas coração', 'Reunir coragem para o que dá medo ou nojo.', 'Fazer das tripas coração', '', 'Hice de tripas corazón y hablé.', 'Fiz das tripas coração e falei.', 'neutral', 3],
    ['pasar por el aro', '', 'passar pelo arco', 'Ceder e aceitar a condição imposta.', 'Entrar na linha', 'Do circo: o animal que salta pelo arco.', 'Al final tuvo que pasar por el aro.', 'No fim teve de entrar na linha.', 'informal', 3],
    ['tener madera de algo', '', 'ter madeira de algo', 'Ter talento natural para algo.', 'Ter talento de nascença', '', 'Tiene madera de líder.', 'Ele tem talento nato de líder.', 'neutral', 3],
    ['poner toda la carne en el asador', '', 'pôr toda a carne no assador', 'Apostar todos os recursos numa única tentativa.', 'Botar todas as fichas', '', 'Pusieron toda la carne en el asador.', 'Botaram todas as fichas.', 'neutral', 3],
    ['no ver más allá de sus narices', '', 'não ver além do próprio nariz', 'Ter visão muito curta.', 'Não enxergar um palmo à frente', '', 'No ve más allá de sus narices.', 'Ele não enxerga um palmo à frente.', 'neutral', 3],
    ['dar carta blanca', '', 'dar carta branca', 'Conceder liberdade total de decisão.', 'Dar carta branca', '', 'Le dieron carta blanca para reorganizar el equipo.', 'Deram carta branca a ele para reorganizar a equipe.', 'formal', 3],
    ['leer entre líneas', '', 'ler entre linhas', 'Captar o que ficou implícito.', 'Ler nas entrelinhas', '', 'Hay que leer entre líneas ese informe.', 'É preciso ler nas entrelinhas aquele relatório.', 'formal', 4],
    ['subirse a las barbas', '', 'subir nas barbas', 'Perder o respeito por quem tem autoridade.', 'Passar por cima', '', 'No dejes que se te suban a las barbas.', 'Não deixe que passem por cima de você.', 'informal', 2],
    ['llover a cántaros', '', 'chover a cântaros', 'Chover muito forte.', 'Chover canivete', '', 'Está lloviendo a cántaros.', 'Está chovendo canivete.', 'informal', 4],
    ['ser agua pasada', '', 'ser água passada', 'Ser assunto encerrado, sem importância agora.', 'Ser água passada', '', 'Eso ya es agua pasada.', 'Isso já é água passada.', 'neutral', 3],
    ['tener los pies en la tierra', '', 'ter os pés na terra', 'Ser realista.', 'Ter os pés no chão', '', 'Ella siempre tiene los pies en la tierra.', 'Ela sempre tem os pés no chão.', 'neutral', 4],
    ['jugar con fuego', '', 'brincar com fogo', 'Assumir um risco que pode explodir.', 'Brincar com fogo', '', 'Estás jugando con fuego con ese contrato.', 'Você está brincando com fogo nesse contrato.', 'neutral', 3],
  ],
  C2: [
    ['ser el chivo expiatorio', '', 'ser o bode expiatório', 'Levar a culpa por todos.', 'Ser o bode expiatório', 'Do rito hebraico do Yom Kipur.', 'Lo hicieron el chivo expiatorio del desastre.', 'Fizeram dele o bode expiatório do desastre.', 'formal', 3],
    ['dorar la píldora', '', 'dourar a pílula', 'Adoçar uma notícia ruim.', 'Dourar a pílula', 'Da farmácia: revestir a pílula amarga.', 'No me dores la píldora, dime la verdad.', 'Não doure a pílula, me diga a verdade.', 'neutral', 3],
    ['llover sobre mojado', '', 'chover sobre molhado', 'Problema novo caindo sobre um antigo.', 'Desgraça pouca é bobagem', '', 'Con esta multa, llueve sobre mojado.', 'Com essa multa, desgraça pouca é bobagem.', 'neutral', 3],
    ['el quid de la cuestión', '', 'o quid da questão', 'O ponto essencial de um assunto.', 'O xis da questão', 'Do latim escolástico "quid".', 'Ese es el quid de la cuestión.', 'Esse é o xis da questão.', 'formal', 3],
    ['la punta del iceberg', '', 'a ponta do iceberg', 'A parte visível de um problema muito maior.', 'A ponta do iceberg', '', 'Estos casos son la punta del iceberg.', 'Esses casos são a ponta do iceberg.', 'formal', 3],
    ['predicar en el desierto', '', 'pregar no deserto', 'Falar sem que ninguém escute.', 'Pregar no deserto', 'De João Batista, nos Evangelhos.', 'Llevo años predicando en el desierto.', 'Faz anos que prego no deserto.', 'formal', 2],
    ['echar margaritas a los cerdos', '', 'jogar margaridas aos porcos', 'Oferecer algo valioso a quem não sabe valorizar.', 'Dar pérolas aos porcos', 'Do Evangelho de Mateus.', 'Regalarle ese vino es echar margaritas a los cerdos.', 'Dar esse vinho a ele é dar pérolas aos porcos.', 'formal', 2],
    ['la gota que colma el vaso', '', 'a gota que enche o copo', 'O último detalhe que faz tudo transbordar.', 'A gota d’água', '', 'Esa respuesta fue la gota que colmó el vaso.', 'Aquela resposta foi a gota d’água.', 'formal', 3],
    ['cortar el nudo gordiano', '', 'cortar o nó górdio', 'Resolver um impasse com um golpe decisivo.', 'Cortar o nó górdio', 'Alexandre, o Grande, cortando o nó em Górdio.', 'Hubo que cortar el nudo gordiano y decidir.', 'Foi preciso cortar o nó górdio e decidir.', 'formal', 2],
    ['cruzar el Rubicón', '', 'cruzar o Rubicão', 'Dar um passo sem volta.', 'Cruzar o Rubicão', 'César atravessando o rio Rubicão em 49 a.C.', 'Al firmar, cruzaron el Rubicón.', 'Ao assinar, cruzaram o Rubicão.', 'formal', 2],
    ['un canto de sirena', '', 'um canto de sereia', 'Promessa sedutora que leva à ruína.', 'Canto de sereia', 'Da Odisseia.', 'Esa oferta es un canto de sirena.', 'Aquela oferta é um canto de sereia.', 'formal', 2],
    ['el talón de Aquiles', '', 'o calcanhar de Aquiles', 'O ponto fraco decisivo.', 'Calcanhar de Aquiles', 'Da Ilíada.', 'La logística es su talón de Aquiles.', 'A logística é o calcanhar de Aquiles deles.', 'formal', 3],
    ['la espada de Damocles', '', 'a espada de Dâmocles', 'Ameaça permanente pairando sobre alguém.', 'Espada de Dâmocles', 'Da corte de Dionísio de Siracusa.', 'La deuda es una espada de Damocles.', 'A dívida é uma espada de Dâmocles.', 'formal', 2],
    ['matar la gallina de los huevos de oro', '', 'matar a galinha dos ovos de ouro', 'Destruir a fonte do próprio lucro.', 'Matar a galinha dos ovos de ouro', 'De Esopo.', 'Subir tanto el precio es matar la gallina de los huevos de oro.', 'Subir tanto o preço é matar a galinha dos ovos de ouro.', 'formal', 3],
    ['hacer leña del árbol caído', '', 'fazer lenha da árvore caída', 'Aproveitar-se de quem já está derrotado.', 'Chutar cachorro morto', '', 'No hagas leña del árbol caído.', 'Não chute cachorro morto.', 'neutral', 2],
    ['no dejar títere con cabeza', '', 'não deixar boneco com cabeça', 'Criticar todo mundo sem poupar ninguém.', 'Não deixar pedra sobre pedra', 'Do Dom Quixote, no teatro de fantoches.', 'En el artículo no dejó títere con cabeza.', 'No artigo ele não poupou ninguém.', 'formal', 2],
    ['poner los puntos sobre las íes', '', 'pôr os pontos nos is', 'Esclarecer tudo com precisão, sem ambiguidade.', 'Pôr os pingos nos is', '', 'Vamos a poner los puntos sobre las íes.', 'Vamos pôr os pingos nos is.', 'neutral', 3],
    ['tener vela en este entierro', '', 'ter vela neste enterro', 'Ter alguma razão para se meter no assunto.', 'Ter vela nesse enterro', '', '¿Quién te dio vela en este entierro?', 'Quem te deu vela nesse enterro?', 'informal', 2],
    ['ser harina de otro costal', '', 'ser farinha de outro saco', 'Ser um assunto completamente diferente.', 'Ser outra história', '', 'Eso ya es harina de otro costal.', 'Isso já é outra história.', 'neutral', 3],
    ['a río revuelto, ganancia de pescadores', '', 'em rio revolto, ganho de pescadores', 'Na confusão, alguém sempre lucra.', 'Em rio revolto, ganho de pescador', '', 'A río revuelto, ganancia de pescadores: alguien se benefició.', 'Em rio revolto, ganho de pescador: alguém se beneficiou.', 'formal', 2],
    ['quien mucho abarca poco aprieta', '', 'quem muito abarca pouco aperta', 'Quem quer tudo ao mesmo tempo não faz nada bem.', 'Quem muito quer, nada tem', '', 'Enfócate: quien mucho abarca poco aprieta.', 'Foque: quem muito quer, nada tem.', 'neutral', 2],
    ['de perdidos, al río', '', 'de perdidos, ao rio', 'Já que está tudo perdido, vamos ao risco total.', 'Já que é para morrer, que seja afogado', '', 'De perdidos, al río: presentamos la propuesta.', 'Já que é assim, mandamos a proposta mesmo.', 'informal', 2],
    ['el hábito no hace al monje', '', 'o hábito não faz o monge', 'A aparência não define o que a pessoa é.', 'O hábito não faz o monge', '', 'Recuerda que el hábito no hace al monje.', 'Lembre que o hábito não faz o monge.', 'formal', 2],
    ['aunque la mona se vista de seda, mona se queda', '', 'ainda que a macaca se vista de seda, macaca continua', 'Enfeitar não muda a essência.', 'Macaco de seda continua macaco', 'Fábula difundida por Félix Lope de Vega.', 'Aunque la mona se vista de seda, mona se queda.', 'Por mais que se enfeite, a essência não muda.', 'informal', 2],
    ['no está el horno para bollos', '', 'o forno não está para pãezinhos', 'Não é hora de pedir nada nem de brincar.', 'Não está para brincadeira', '', 'Hoy no está el horno para bollos.', 'Hoje não está para brincadeira.', 'informal', 2],
  ],
};
