/**
 * Francês — expressões por nível.
 *
 * Nenhuma expressão aqui repete o lote curado de `idioms.ts`.
 */

import type { ByLevel } from './entry';

export const FR: ByLevel = {
  A2: [
    ['ça marche', '', 'isso anda', 'Combinado; funciona para mim.', 'Fechado', '', 'On se voit à midi ? — Ça marche.', 'A gente se vê ao meio-dia? — Fechado.', 'informal', 5],
    ['bof', '', 'bof', 'Sem entusiasmo nenhum; mais ou menos.', 'Ah, sei lá', '', 'Le film ? Bof.', 'O filme? Ah, sei lá.', 'informal', 4],
    ['ça y est', '', 'isso aí está', 'Pronto; aconteceu.', 'Pronto', '', 'Ça y est, j’ai fini.', 'Pronto, terminei.', 'informal', 5],
    ['tant pis', '', 'tanto pior', 'Paciência; fazer o quê.', 'Paciência', '', 'Tant pis, on ira demain.', 'Paciência, a gente vai amanhã.', 'informal', 5],
    ['tant mieux', '', 'tanto melhor', 'Que bom; melhor assim.', 'Melhor assim', '', 'Il a accepté ? Tant mieux.', 'Ele aceitou? Melhor assim.', 'informal', 4],
    ['ça dépend', '', 'isso depende', 'Depende das circunstâncias.', 'Depende', '', 'Tu viens ? — Ça dépend de l’heure.', 'Você vem? — Depende do horário.', 'neutral', 5],
    ['pas grave', '', 'não grave', 'Não tem problema.', 'Sem problema', '', 'Tu es en retard ? Pas grave.', 'Você atrasou? Sem problema.', 'informal', 5],
    ['bien sûr', '', 'bem seguro', 'Claro, evidentemente.', 'Claro', '', 'Bien sûr que tu peux venir.', 'Claro que você pode vir.', 'neutral', 5],
    ['tout de suite', '', 'todo de seguida', 'Imediatamente.', 'Agora mesmo', '', 'J’arrive tout de suite.', 'Já vou agora mesmo.', 'neutral', 5],
    ['de temps en temps', '', 'de tempo em tempo', 'De vez em quando.', 'De vez em quando', '', 'Je cuisine de temps en temps.', 'Eu cozinho de vez em quando.', 'neutral', 4],
    ['avoir envie de', '', 'ter vontade de', 'Estar com vontade de algo.', 'Estar a fim de', '', 'J’ai envie de sortir ce soir.', 'Estou a fim de sair hoje à noite.', 'neutral', 5],
    ['avoir besoin de', '', 'ter necessidade de', 'Precisar de algo.', 'Precisar de', '', 'J’ai besoin d’aide.', 'Preciso de ajuda.', 'neutral', 5],
    ['faire attention', '', 'fazer atenção', 'Prestar atenção; tomar cuidado.', 'Prestar atenção', '', 'Fais attention à la marche.', 'Cuidado com o degrau.', 'neutral', 5],
    ['ça suffit', '', 'isso basta', 'Já chega.', 'Chega', '', 'Ça suffit, arrête maintenant.', 'Chega, para agora.', 'informal', 4],
    ['n’importe quoi', '', 'não importa o quê', 'Bobagem; qualquer coisa sem sentido.', 'Besteira', '', 'Tu racontes n’importe quoi.', 'Você está falando besteira.', 'informal', 4],
    ['à tout à l’heure', '', 'a toda a hora', 'Até logo, ainda hoje.', 'Até já', '', 'À tout à l’heure, je reviens.', 'Até já, eu volto.', 'informal', 5],
    ['quand même', '', 'quando mesmo', 'Mesmo assim; convenhamos.', 'Mesmo assim', '', 'Il est venu quand même.', 'Ele veio mesmo assim.', 'informal', 5],
    ['peu à peu', '', 'pouco a pouco', 'Gradualmente.', 'Aos poucos', '', 'Peu à peu, il progresse.', 'Aos poucos ele progride.', 'neutral', 4],
    ['avoir raison', '', 'ter razão', 'Estar certo.', 'Ter razão', '', 'Tu as raison sur ce point.', 'Você tem razão nesse ponto.', 'neutral', 5],
    ['avoir tort', '', 'ter erro', 'Estar errado.', 'Estar errado', '', 'J’avais tort, désolé.', 'Eu estava errado, desculpa.', 'neutral', 4],
    ['faire la queue', '', 'fazer a cauda', 'Ficar na fila.', 'Pegar fila', '', 'On a fait la queue une heure.', 'Ficamos uma hora na fila.', 'neutral', 4],
    ['avoir mal à', '', 'ter mal a', 'Sentir dor em alguma parte do corpo.', 'Estar com dor em', '', 'J’ai mal à la tête.', 'Estou com dor de cabeça.', 'neutral', 5],
    ['s’il te plaît', '', 'se te agrada', 'Por favor, no tratamento informal.', 'Por favor', '', 'Passe-moi le sel, s’il te plaît.', 'Me passa o sal, por favor.', 'informal', 5],
    ['pas du tout', '', 'nada do todo', 'De maneira nenhuma.', 'De jeito nenhum', '', 'Ça ne me dérange pas du tout.', 'Não me incomoda de jeito nenhum.', 'neutral', 5],
    ['ça vaut le coup', '', 'isso vale o golpe', 'Vale a pena.', 'Vale a pena', '', 'Le détour vaut le coup.', 'O desvio vale a pena.', 'informal', 4],
  ],
  B1: [
    ['donner un coup de main', '', 'dar um golpe de mão', 'Ajudar alguém numa tarefa.', 'Dar uma mão', '', 'Tu peux me donner un coup de main ?', 'Você pode me dar uma mão?', 'informal', 5],
    ['avoir un coup de foudre', '', 'ter um golpe de raio', 'Apaixonar-se instantaneamente.', 'Amor à primeira vista', '', 'Ça a été un coup de foudre immédiat.', 'Foi amor à primeira vista.', 'neutral', 3],
    ['en avoir marre', '', 'ter disso demais', 'Estar farto de algo.', 'Estar de saco cheio', '', 'J’en ai marre d’attendre.', 'Estou de saco cheio de esperar.', 'informal', 5],
    ['être crevé', '', 'estar furado', 'Estar exausto.', 'Estar acabado', 'Do pneu furado.', 'Je suis crevé après cette journée.', 'Estou acabado depois desse dia.', 'informal', 4],
    ['avoir la flemme', '', 'ter a preguiça', 'Estar sem a menor vontade de fazer algo.', 'Estar com preguiça', '', 'J’ai la flemme de cuisiner.', 'Estou com preguiça de cozinhar.', 'informal', 4],
    ['tomber à l’eau', '', 'cair na água', 'Plano que fracassa antes de acontecer.', 'Ir por água abaixo', '', 'Le projet est tombé à l’eau.', 'O projeto foi por água abaixo.', 'neutral', 4],
    ['être dans la lune', '', 'estar na lua', 'Estar distraído, pensando em outra coisa.', 'Estar no mundo da lua', '', 'Tu es dans la lune aujourd’hui.', 'Você está no mundo da lua hoje.', 'informal', 4],
    ['avoir du pain sur la planche', '', 'ter pão sobre a tábua', 'Ter muito trabalho pela frente.', 'Ter muita lenha para queimar', 'Antigamente, a reserva de pão na tábua era o trabalho já garantido.', 'On a du pain sur la planche cette semaine.', 'Temos muito trabalho esta semana.', 'neutral', 4],
    ['mettre son grain de sel', '', 'pôr o seu grão de sal', 'Dar palpite sem que ninguém tenha pedido.', 'Dar pitaco', '', 'Il met toujours son grain de sel.', 'Ele sempre dá um pitaco.', 'informal', 3],
    ['casser les pieds à quelqu’un', '', 'quebrar os pés de alguém', 'Importunar alguém sem parar.', 'Encher o saco', '', 'Tu me casses les pieds avec ça.', 'Você está enchendo meu saco com isso.', 'informal', 4],
    ['être au courant', '', 'estar na corrente', 'Estar informado sobre algo.', 'Estar por dentro', 'Da corrente elétrica e da corrente de informação.', 'Tu es au courant de la nouvelle ?', 'Você está por dentro da novidade?', 'neutral', 5],
    ['faire la grasse matinée', '', 'fazer a manhã gorda', 'Dormir até tarde.', 'Dormir até tarde', '', 'Le dimanche, je fais la grasse matinée.', 'No domingo eu durmo até tarde.', 'informal', 3],
    ['prendre son courage à deux mains', '', 'pegar sua coragem com as duas mãos', 'Reunir coragem para algo difícil.', 'Criar coragem', '', 'J’ai pris mon courage à deux mains et j’ai parlé.', 'Criei coragem e falei.', 'neutral', 3],
    ['être sur la même longueur d’onde', '', 'estar no mesmo comprimento de onda', 'Entender-se sem esforço.', 'Estar na mesma sintonia', 'Do rádio.', 'On est sur la même longueur d’onde.', 'Estamos na mesma sintonia.', 'neutral', 4],
    ['avoir la tête ailleurs', '', 'ter a cabeça em outro lugar', 'Estar com o pensamento longe.', 'Estar com a cabeça longe', '', 'Il a la tête ailleurs depuis lundi.', 'Ele está com a cabeça longe desde segunda.', 'neutral', 4],
    ['être à côté de la plaque', '', 'estar ao lado da placa', 'Estar completamente equivocado.', 'Estar viajando', 'Do tiro ao alvo: acertar fora da placa.', 'Ta réponse est à côté de la plaque.', 'Sua resposta está totalmente equivocada.', 'informal', 3],
    ['rater le coche', '', 'perder a diligência', 'Perder a oportunidade certa.', 'Perder o bonde', 'Coche era a diligência puxada a cavalos.', 'On a raté le coche sur ce marché.', 'Perdemos o bonde nesse mercado.', 'neutral', 3],
    ['être bien dans sa peau', '', 'estar bem na própria pele', 'Sentir-se bem consigo mesmo.', 'Estar bem consigo mesmo', '', 'Elle est bien dans sa peau maintenant.', 'Ela está bem consigo mesma agora.', 'neutral', 3],
    ['faire le pont', '', 'fazer a ponte', 'Emendar o feriado com o fim de semana.', 'Emendar o feriado', '', 'On fait le pont jeudi et vendredi.', 'Vamos emendar o feriado quinta e sexta.', 'informal', 3],
    ['avoir un trou de mémoire', '', 'ter um buraco de memória', 'Esquecer algo momentaneamente.', 'Dar um branco', '', 'J’ai eu un trou de mémoire en pleine réunion.', 'Deu um branco em plena reunião.', 'neutral', 4],
    ['se prendre la tête', '', 'pegar-se a cabeça', 'Ficar remoendo ou brigando por bobagem.', 'Esquentar a cabeça', '', 'Ne te prends pas la tête avec ça.', 'Não esquente a cabeça com isso.', 'informal', 4],
    ['avoir des fourmis dans les jambes', '', 'ter formigas nas pernas', 'Sentir formigamento; não parar quieto.', 'Estar com formigamento', '', 'J’ai des fourmis dans les jambes.', 'Minhas pernas estão formigando.', 'informal', 3],
    ['tomber à pic', '', 'cair a pique', 'Chegar exatamente na hora certa.', 'Chegar em boa hora', '', 'Ton appel tombe à pic.', 'Sua ligação chegou em boa hora.', 'informal', 3],
    ['avoir le moral à zéro', '', 'ter o moral a zero', 'Estar completamente desanimado.', 'Estar na fossa', '', 'Il a le moral à zéro depuis l’examen.', 'Ele está na fossa desde a prova.', 'informal', 3],
    ['ne pas être dans son assiette', '', 'não estar no seu prato', 'Não estar se sentindo bem.', 'Não estar num bom dia', '"Assiette" já significou postura, não prato.', 'Je ne suis pas dans mon assiette aujourd’hui.', 'Não estou num bom dia hoje.', 'informal', 3],
  ],
  B2: [
    ['avoir un poil dans la main', '', 'ter um pelo na mão', 'Ser extremamente preguiçoso.', 'Ter preguiça crônica', 'A imagem é a de quem não usa a mão há tanto tempo que nasceu pelo nela.', 'Il a un poil dans la main, celui-là.', 'Esse aí tem preguiça crônica.', 'informal', 3],
    ['mettre les pieds dans le plat', '', 'pôr os pés no prato', 'Falar sem tato exatamente do assunto delicado.', 'Dar uma mancada', '', 'Il a mis les pieds dans le plat devant tout le monde.', 'Ele deu uma mancada na frente de todo mundo.', 'informal', 4],
    ['faire la sourde oreille', '', 'fazer o ouvido surdo', 'Fingir que não ouviu.', 'Fazer ouvidos moucos', '', 'La direction fait la sourde oreille.', 'A direção faz ouvidos moucos.', 'neutral', 4],
    ['en faire tout un fromage', '', 'fazer disso todo um queijo', 'Transformar bobagem em drama.', 'Fazer tempestade em copo d’água', 'Do trabalho que dá transformar leite em queijo.', 'N’en fais pas tout un fromage.', 'Não faça tempestade em copo d’água.', 'informal', 3],
    ['tourner autour du pot', '', 'girar ao redor do pote', 'Enrolar em vez de dizer o essencial.', 'Fazer rodeios', '', 'Arrête de tourner autour du pot.', 'Pare de fazer rodeios.', 'informal', 4],
    ['avoir d’autres chats à fouetter', '', 'ter outros gatos para chicotear', 'Ter coisas mais importantes a fazer.', 'Ter mais o que fazer', '', 'J’ai d’autres chats à fouetter aujourd’hui.', 'Tenho mais o que fazer hoje.', 'informal', 3],
    ['appuyer sur le champignon', '', 'apertar o cogumelo', 'Acelerar bastante.', 'Pisar fundo', 'O antigo acelerador tinha formato de cogumelo.', 'Appuie sur le champignon, on est en retard.', 'Pisa fundo, estamos atrasados.', 'informal', 3],
    ['arriver comme un cheveu sur la soupe', '', 'chegar como um cabelo na sopa', 'Chegar ou ser dito na pior hora possível.', 'Chegar como uma mosca na sopa', '', 'Sa remarque est arrivée comme un cheveu sur la soupe.', 'O comentário dele caiu como uma mosca na sopa.', 'informal', 3],
    ['ne pas y aller de main morte', '', 'não ir com a mão morta', 'Agir ou criticar com força total.', 'Não pegar leve', '', 'Le critique n’y est pas allé de main morte.', 'O crítico não pegou leve.', 'informal', 3],
    ['tirer son épingle du jeu', '', 'tirar seu alfinete do jogo', 'Sair bem de uma situação complicada.', 'Se dar bem apesar de tudo', 'De um jogo infantil com alfinetes.', 'Elle a tiré son épingle du jeu.', 'Ela se saiu bem apesar de tudo.', 'neutral', 3],
    ['mettre la main à la pâte', '', 'pôr a mão na massa', 'Participar do trabalho concreto.', 'Pôr a mão na massa', '', 'Le patron met la main à la pâte.', 'O chefe põe a mão na massa.', 'neutral', 4],
    ['avoir le cœur sur la main', '', 'ter o coração na mão', 'Ser muito generoso.', 'Ter um coração enorme', '', 'Elle a le cœur sur la main.', 'Ela tem um coração enorme.', 'neutral', 3],
    ['sauter du coq à l’âne', '', 'pular do galo ao burro', 'Mudar de assunto sem nexo.', 'Sair pela tangente', 'Expressão registrada desde o século XIV.', 'Il saute du coq à l’âne sans arrêt.', 'Ele muda de assunto sem nexo o tempo todo.', 'informal', 3],
    ['se mettre en quatre', '', 'colocar-se em quatro', 'Fazer todo o esforço possível por alguém.', 'Se desdobrar', '', 'Elle s’est mise en quatre pour nous aider.', 'Ela se desdobrou para nos ajudar.', 'neutral', 3],
    ['avoir un verre dans le nez', '', 'ter um copo no nariz', 'Estar alcoolizado.', 'Estar alto', '', 'Il avait un verre dans le nez hier soir.', 'Ele estava alto ontem à noite.', 'informal', 3],
    ['prendre la mouche', '', 'pegar a mosca', 'Ofender-se por muito pouco.', 'Ficar de nariz em pé', '', 'Ne prends pas la mouche, c’était une blague.', 'Não fique ofendido, era brincadeira.', 'informal', 3],
    ['filer à l’anglaise', '', 'escapar à inglesa', 'Ir embora sem se despedir.', 'Sair à francesa', 'Curiosidade: em inglês diz-se "to take French leave" — cada idioma culpa o outro.', 'Il a filé à l’anglaise avant le dessert.', 'Ele saiu à francesa antes da sobremesa.', 'informal', 3],
    ['avoir la puce à l’oreille', '', 'ter a pulga na orelha', 'Desconfiar que há algo errado.', 'Ficar com a pulga atrás da orelha', '', 'Ce détail m’a mis la puce à l’oreille.', 'Esse detalhe me deixou com a pulga atrás da orelha.', 'neutral', 3],
    ['mettre les bouchées doubles', '', 'dar garfadas dobradas', 'Acelerar o ritmo do trabalho.', 'Dobrar o ritmo', '', 'On met les bouchées doubles pour livrer vendredi.', 'Estamos dobrando o ritmo para entregar sexta.', 'neutral', 3],
    ['être dans le pétrin', '', 'estar na masseira', 'Estar em apuros sérios.', 'Estar numa enrascada', 'Pétrin é o tanque onde se sova a massa.', 'On est dans le pétrin jusqu’au cou.', 'Estamos numa enrascada até o pescoço.', 'informal', 3],
    ['faire d’une pierre deux coups', '', 'fazer de uma pedra dois golpes', 'Resolver duas coisas de uma vez.', 'Matar dois coelhos com uma cajadada', '', 'On fait d’une pierre deux coups.', 'Matamos dois coelhos com uma cajadada.', 'neutral', 4],
    ['avoir la gueule de bois', '', 'ter a boca de madeira', 'Estar de ressaca.', 'Estar de ressaca', '', 'J’ai la gueule de bois ce matin.', 'Estou de ressaca hoje de manhã.', 'informal', 3],
    ['rouler quelqu’un dans la farine', '', 'rolar alguém na farinha', 'Enganar alguém com lábia.', 'Passar a perna', 'Do teatro: os atores se cobriam de farinha para se disfarçar.', 'Ils nous ont roulés dans la farine.', 'Eles passaram a perna na gente.', 'informal', 3],
    ['casser du sucre sur le dos de quelqu’un', '', 'quebrar açúcar nas costas de alguém', 'Falar mal de alguém ausente.', 'Falar pelas costas', '', 'Ils cassent du sucre sur son dos depuis des mois.', 'Eles falam pelas costas dele há meses.', 'informal', 3],
    ['être au bout du rouleau', '', 'estar no fim do rolo', 'Estar sem forças nem recursos.', 'Estar no limite', 'Do rolo de pergaminho que chega ao fim.', 'Elle est au bout du rouleau.', 'Ela está no limite.', 'neutral', 3],
  ],
  C1: [
    ['jeter l’éponge', '', 'jogar a esponja', 'Desistir depois de resistir muito.', 'Jogar a toalha', 'Do boxe.', 'Après trois recours, il a jeté l’éponge.', 'Depois de três recursos, ele jogou a toalha.', 'neutral', 4],
    ['couper les cheveux en quatre', '', 'cortar os cabelos em quatro', 'Complicar com distinções inúteis.', 'Procurar pelo em ovo', '', 'Arrête de couper les cheveux en quatre.', 'Pare de procurar pelo em ovo.', 'neutral', 3],
    ['mettre la charrue avant les bœufs', '', 'pôr o arado antes dos bois', 'Inverter a ordem das etapas.', 'Pôr o carro na frente dos bois', '', 'Signer avant l’audit, c’est mettre la charrue avant les bœufs.', 'Assinar antes da auditoria é pôr o carro na frente dos bois.', 'formal', 3],
    ['avoir le bras long', '', 'ter o braço longo', 'Ter influência e contatos poderosos.', 'Ter costas quentes', '', 'Son avocat a le bras long.', 'O advogado dele tem costas quentes.', 'neutral', 3],
    ['mettre les points sur les i', '', 'pôr os pontos nos is', 'Deixar tudo explícito, sem margem para dúvida.', 'Pôr os pingos nos is', '', 'Il est temps de mettre les points sur les i.', 'É hora de pôr os pingos nos is.', 'neutral', 3],
    ['avoir voix au chapitre', '', 'ter voz no capítulo', 'Ter direito de opinar numa decisão.', 'Ter voz ativa', 'Do capítulo de monges, onde só alguns votavam.', 'Les salariés n’ont pas voix au chapitre.', 'Os funcionários não têm voz ativa.', 'formal', 2],
    ['battre le fer pendant qu’il est chaud', '', 'bater o ferro enquanto está quente', 'Agir enquanto a oportunidade dura.', 'Malhar o ferro enquanto está quente', 'Da forja.', 'Battons le fer pendant qu’il est chaud.', 'Vamos malhar o ferro enquanto está quente.', 'neutral', 3],
    ['ménager la chèvre et le chou', '', 'poupar a cabra e a couve', 'Tentar agradar dois lados opostos.', 'Agradar a gregos e troianos', '', 'Le maire ménage la chèvre et le chou.', 'O prefeito tenta agradar a gregos e troianos.', 'formal', 2],
    ['jeter de l’huile sur le feu', '', 'jogar óleo no fogo', 'Agravar um conflito de propósito.', 'Botar lenha na fogueira', '', 'Ce communiqué jette de l’huile sur le feu.', 'Esse comunicado bota lenha na fogueira.', 'neutral', 3],
    ['faire chou blanc', '', 'fazer couve branca', 'Voltar de mãos vazias.', 'Dar com os burros n’água', 'De um antigo jogo de bolas em que "coup blanc" era o golpe nulo.', 'La perquisition a fait chou blanc.', 'A busca deu com os burros n’água.', 'formal', 2],
    ['donner sa langue au chat', '', 'dar sua língua ao gato', 'Desistir de adivinhar e pedir a resposta.', 'Entregar os pontos', '', 'Je donne ma langue au chat, dis-moi.', 'Entrego os pontos, me diga.', 'informal', 3],
    ['être au pied du mur', '', 'estar ao pé do muro', 'Estar sem saída, obrigado a decidir.', 'Estar contra a parede', '', 'Nous sommes au pied du mur.', 'Estamos contra a parede.', 'neutral', 3],
    ['reculer pour mieux sauter', '', 'recuar para melhor saltar', 'Adiar apenas para enfrentar o mesmo depois.', 'Só adiar o inevitável', '', 'Reporter la réunion, c’est reculer pour mieux sauter.', 'Adiar a reunião é só adiar o inevitável.', 'neutral', 2],
    ['avoir plusieurs cordes à son arc', '', 'ter várias cordas no seu arco', 'Ter mais de uma competência ou alternativa.', 'Ter mais de uma carta na manga', '', 'Elle a plusieurs cordes à son arc.', 'Ela tem mais de uma carta na manga.', 'neutral', 3],
    ['remettre les pendules à l’heure', '', 'acertar os relógios', 'Restabelecer os fatos e as regras.', 'Botar as coisas nos eixos', '', 'Le directeur a remis les pendules à l’heure.', 'O diretor botou as coisas nos eixos.', 'neutral', 3],
    ['ne pas être sorti de l’auberge', '', 'não ter saído da estalagem', 'Ainda estar longe de resolver o problema.', 'A briga ainda é longa', '', 'Avec ce bug, on n’est pas sorti de l’auberge.', 'Com esse bug, a briga ainda é longa.', 'informal', 3],
    ['tirer les ficelles', '', 'puxar os cordéis', 'Comandar nos bastidores.', 'Puxar os cordões', 'Do teatro de marionetes.', 'On sait qui tire les ficelles.', 'Sabemos quem puxa os cordões.', 'neutral', 3],
    ['faire l’autruche', '', 'fazer o avestruz', 'Fingir que o problema não existe.', 'Enterrar a cabeça na areia', '', 'La direction fait l’autruche depuis un an.', 'A direção enterra a cabeça na areia há um ano.', 'neutral', 3],
    ['brûler la chandelle par les deux bouts', '', 'queimar a vela pelas duas pontas', 'Gastar-se além do sustentável.', 'Queimar a vela pelas duas pontas', '', 'Il brûle la chandelle par les deux bouts.', 'Ele se consome pelas duas pontas.', 'formal', 2],
    ['avoir l’esprit d’escalier', '', 'ter o espírito de escada', 'Só pensar na resposta certa depois que já saiu.', 'Só pensar na resposta depois', 'Cunhada por Diderot.', 'J’ai l’esprit d’escalier, comme toujours.', 'Só penso na resposta depois, como sempre.', 'formal', 2],
    ['mettre de l’eau dans son vin', '', 'pôr água no seu vinho', 'Moderar as próprias exigências.', 'Baixar a bola', '', 'Il a fini par mettre de l’eau dans son vin.', 'Ele acabou baixando a bola.', 'neutral', 3],
    ['prendre des vessies pour des lanternes', '', 'tomar bexigas por lanternas', 'Confundir grosseiramente uma coisa com outra.', 'Confundir alhos com bugalhos', 'Bexigas de animal já foram usadas como lampiões improvisados.', 'Il prend des vessies pour des lanternes.', 'Ele confunde alhos com bugalhos.', 'formal', 2],
    ['lire entre les lignes', '', 'ler entre as linhas', 'Compreender o que ficou implícito.', 'Ler nas entrelinhas', '', 'Il faut lire entre les lignes de ce rapport.', 'É preciso ler nas entrelinhas desse relatório.', 'formal', 4],
    ['tenir le haut du pavé', '', 'ocupar a parte alta da calçada', 'Ocupar posição de destaque.', 'Estar no topo', 'No passado, a parte alta da rua era a limpa, reservada aos nobres.', 'Cette marque tient le haut du pavé.', 'Essa marca está no topo.', 'formal', 2],
    ['avoir maille à partir avec', '', 'ter moeda a dividir com', 'Ter um desentendimento com alguém.', 'Ter contas a acertar', 'Maille era a menor moeda medieval, indivisível — daí a briga.', 'Il a eu maille à partir avec le fisc.', 'Ele teve contas a acertar com o fisco.', 'formal', 2],
  ],
  C2: [
    ['être un pavé dans la mare', '', 'ser uma pedra no lago', 'Declaração que abala o consenso.', 'Jogar uma bomba', '', 'Son rapport est un pavé dans la mare.', 'O relatório dele foi uma bomba.', 'formal', 2],
    ['prêcher le faux pour savoir le vrai', '', 'pregar o falso para saber o verdadeiro', 'Afirmar algo errado de propósito para arrancar a verdade.', 'Jogar verde para colher maduro', '', 'Il prêche le faux pour savoir le vrai.', 'Ele joga verde para colher maduro.', 'formal', 2],
    ['la goutte d’eau qui fait déborder le vase', '', 'a gota d’água que faz transbordar o vaso', 'O detalhe final que esgota a paciência.', 'A gota d’água', '', 'Ce refus a été la goutte d’eau qui fait déborder le vase.', 'Aquela recusa foi a gota d’água.', 'formal', 3],
    ['appeler un chat un chat', '', 'chamar um gato de gato', 'Dizer as coisas pelo nome, sem eufemismo.', 'Dar nome aos bois', 'Atribuída a Boileau.', 'Appelons un chat un chat : c’est une fraude.', 'Vamos dar nome aos bois: isso é fraude.', 'formal', 3],
    ['le talon d’Achille', '', 'o calcanhar de Aquiles', 'O ponto vulnerável decisivo.', 'Calcanhar de Aquiles', 'Da Ilíada.', 'La trésorerie est leur talon d’Achille.', 'O caixa é o calcanhar de Aquiles deles.', 'formal', 3],
    ['une épée de Damoclès', '', 'uma espada de Dâmocles', 'Ameaça constante suspensa sobre alguém.', 'Espada de Dâmocles', 'Da corte de Dionísio de Siracusa.', 'Ce procès est une épée de Damoclès.', 'Esse processo é uma espada de Dâmocles.', 'formal', 2],
    ['franchir le Rubicon', '', 'atravessar o Rubicão', 'Dar o passo irreversível.', 'Cruzar o Rubicão', 'César, em 49 a.C.', 'En signant, ils ont franchi le Rubicon.', 'Ao assinar, cruzaram o Rubicão.', 'formal', 2],
    ['un cadeau empoisonné', '', 'um presente envenenado', 'Presente que traz mais problema que benefício.', 'Presente de grego', '', 'Cette promotion est un cadeau empoisonné.', 'Essa promoção é um presente de grego.', 'formal', 3],
    ['jeter le bébé avec l’eau du bain', '', 'jogar o bebê com a água do banho', 'Descartar o bom junto com o ruim.', 'Jogar fora o bom com o ruim', 'Provérbio de origem alemã.', 'Supprimer tout le programme, c’est jeter le bébé avec l’eau du bain.', 'Eliminar o programa inteiro é jogar fora o bom com o ruim.', 'formal', 2],
    ['la partie émergée de l’iceberg', '', 'a parte emersa do iceberg', 'A fração visível de um problema muito maior.', 'A ponta do iceberg', '', 'Ces plaintes sont la partie émergée de l’iceberg.', 'Essas queixas são a ponta do iceberg.', 'formal', 3],
    ['prêcher dans le désert', '', 'pregar no deserto', 'Falar sem que ninguém escute.', 'Pregar no deserto', 'De João Batista.', 'Je prêche dans le désert depuis des années.', 'Prego no deserto há anos.', 'formal', 2],
    ['un cheval de Troie', '', 'um cavalo de Troia', 'Ameaça que entra disfarçada de presente.', 'Cavalo de Troia', 'Da Eneida.', 'Cette clause est un cheval de Troie.', 'Aquela cláusula é um cavalo de Troia.', 'formal', 3],
    ['un chant des sirènes', '', 'um canto das sereias', 'Promessa sedutora e perigosa.', 'Canto de sereia', 'Da Odisseia.', 'Ne cède pas au chant des sirènes.', 'Não ceda ao canto de sereia.', 'formal', 2],
    ['tuer la poule aux œufs d’or', '', 'matar a galinha dos ovos de ouro', 'Destruir a fonte do próprio ganho.', 'Matar a galinha dos ovos de ouro', 'De Esopo, retomada por La Fontaine.', 'Augmenter les frais, c’est tuer la poule aux œufs d’or.', 'Aumentar as taxas é matar a galinha dos ovos de ouro.', 'formal', 3],
    ['trancher le nœud gordien', '', 'cortar o nó górdio', 'Resolver um impasse com um golpe decisivo.', 'Cortar o nó górdio', 'Alexandre, o Grande.', 'Il a fallu trancher le nœud gordien.', 'Foi preciso cortar o nó górdio.', 'formal', 2],
    ['un château de cartes', '', 'um castelo de cartas', 'Estrutura que desaba ao primeiro abalo.', 'Castelo de cartas', '', 'Le montage financier était un château de cartes.', 'A montagem financeira era um castelo de cartas.', 'formal', 3],
    ['une tempête dans un verre d’eau', '', 'uma tempestade num copo d’água', 'Alvoroço enorme por algo mínimo.', 'Tempestade em copo d’água', '', 'Toute cette polémique est une tempête dans un verre d’eau.', 'Toda essa polêmica é tempestade em copo d’água.', 'formal', 3],
    ['jeter des perles aux pourceaux', '', 'jogar pérolas aos porcos', 'Oferecer o valioso a quem não sabe reconhecer.', 'Dar pérolas aos porcos', 'Do Evangelho de Mateus.', 'Lui offrir ce livre, c’est jeter des perles aux pourceaux.', 'Dar esse livro a ele é dar pérolas aos porcos.', 'formal', 2],
    ['faire d’une mouche un éléphant', '', 'fazer de uma mosca um elefante', 'Exagerar desmedidamente um detalhe.', 'Fazer de um grão de areia uma montanha', '', 'Tu fais d’une mouche un éléphant.', 'Você está exagerando desmedidamente.', 'formal', 2],
    ['le bouc émissaire', '', 'o bode expiatório', 'Quem leva a culpa de todos.', 'Bode expiatório', 'Do rito hebraico do Yom Kipur.', 'Il a servi de bouc émissaire.', 'Ele serviu de bode expiatório.', 'formal', 3],
    ['il n’y a pas de fumée sans feu', '', 'não há fumaça sem fogo', 'Todo boato costuma ter alguma base.', 'Onde há fumaça, há fogo', '', 'Il n’y a pas de fumée sans feu, dit-on.', 'Onde há fumaça, há fogo, dizem.', 'neutral', 3],
    ['l’habit ne fait pas le moine', '', 'o hábito não faz o monge', 'A aparência não define a pessoa.', 'O hábito não faz o monge', '', 'L’habit ne fait pas le moine, méfie-toi.', 'O hábito não faz o monge, cuidado.', 'formal', 3],
    ['qui trop embrasse mal étreint', '', 'quem abraça demais aperta mal', 'Quem tenta tudo ao mesmo tempo não faz nada bem.', 'Quem muito quer, nada tem', '', 'Concentre-toi : qui trop embrasse mal étreint.', 'Concentre-se: quem muito quer, nada tem.', 'formal', 2],
    ['la nuit porte conseil', '', 'a noite traz conselho', 'Decidir no dia seguinte é decidir melhor.', 'A noite é boa conselheira', '', 'Attends demain, la nuit porte conseil.', 'Espere amanhã, a noite é boa conselheira.', 'neutral', 3],
    ['découvrir le pot aux roses', '', 'descobrir o pote das rosas', 'Descobrir o segredo por trás da fachada.', 'Descobrir o pulo do gato', '', 'La presse a découvert le pot aux roses.', 'A imprensa descobriu o que havia por trás.', 'formal', 2],
  ],
};
