/**
 * Italiano — expressões por nível.
 *
 * Nenhuma expressão aqui repete o lote curado de `idioms.ts`.
 */

import type { ByLevel } from './entry';

export const IT: ByLevel = {
  A2: [
    ['magari', '', 'quem dera', 'Tomara; quem dera fosse assim.', 'Quem dera', '', 'Vinci la borsa? — Magari!', 'Você ganhou a bolsa? — Quem dera!', 'informal', 5],
    ['dai', '', 'dá', 'Vai; anda logo — incentivo ou impaciência.', 'Vai lá', '', 'Dai, andiamo!', 'Vai, vamos!', 'informal', 5],
    ['boh', '', 'boh', 'Sei lá; não faço ideia.', 'Sei lá', '', 'Dov’è il treno? — Boh.', 'Cadê o trem? — Sei lá.', 'informal', 4],
    ['va bene', '', 'vai bem', 'Está certo; combinado.', 'Beleza', '', 'Ci vediamo alle otto, va bene?', 'A gente se vê às oito, beleza?', 'neutral', 5],
    ['meno male', '', 'menos mal', 'Ainda bem.', 'Ainda bem', '', 'Meno male che sei arrivato.', 'Ainda bem que você chegou.', 'informal', 5],
    ['che peccato', '', 'que pecado', 'Que pena.', 'Que pena', '', 'Non puoi venire? Che peccato.', 'Você não pode vir? Que pena.', 'neutral', 4],
    ['mi raccomando', '', 'me recomendo', 'Não esqueça; conto com você.', 'Olha lá, hein', '', 'Chiamami, mi raccomando.', 'Me liga, hein.', 'informal', 4],
    ['sul serio', '', 'no sério', 'A sério, de verdade.', 'Sério mesmo', '', 'Parli sul serio?', 'Você está falando sério?', 'informal', 4],
    ['per caso', '', 'por caso', 'Por acaso.', 'Por acaso', '', 'Hai per caso visto le chiavi?', 'Por acaso você viu as chaves?', 'neutral', 4],
    ['tutto a posto', '', 'tudo no lugar', 'Está tudo certo.', 'Tudo certo', '', 'È tutto a posto, non preoccuparti.', 'Está tudo certo, não se preocupe.', 'informal', 5],
    ['a dopo', '', 'a depois', 'Até mais tarde.', 'Até mais', '', 'A dopo, ci sentiamo.', 'Até mais, a gente se fala.', 'informal', 4],
    ['più o meno', '', 'mais ou menos', 'Aproximadamente.', 'Mais ou menos', '', 'Sono più o meno venti.', 'São mais ou menos vinte.', 'neutral', 5],
    ['poco a poco', '', 'pouco a pouco', 'Gradualmente.', 'Aos poucos', '', 'Poco a poco impari.', 'Aos poucos você aprende.', 'neutral', 4],
    ['di solito', '', 'de sólito', 'Normalmente, em geral.', 'Normalmente', '', 'Di solito lavoro da casa.', 'Normalmente trabalho de casa.', 'neutral', 5],
    ['avere voglia di', '', 'ter vontade de', 'Estar com vontade de algo.', 'Estar a fim de', '', 'Ho voglia di un caffè.', 'Estou a fim de um café.', 'neutral', 5],
    ['avere fretta', '', 'ter pressa', 'Estar com pressa.', 'Estar com pressa', '', 'Scusa, ho fretta.', 'Desculpa, estou com pressa.', 'neutral', 5],
    ['stare attento', '', 'estar atento', 'Prestar atenção; tomar cuidado.', 'Ficar atento', '', 'Stai attento al gradino.', 'Cuidado com o degrau.', 'neutral', 5],
    ['in fretta', '', 'em pressa', 'Depressa, correndo.', 'Correndo', '', 'Ho mangiato in fretta.', 'Comi correndo.', 'neutral', 4],
    ['che ne dici', '', 'que disso dizes', 'O que você acha?', 'O que você acha', '', 'Andiamo al mare, che ne dici?', 'Vamos à praia, o que você acha?', 'informal', 4],
    ['non fa niente', '', 'não faz nada', 'Não tem problema.', 'Não tem problema', '', 'Hai rotto il bicchiere? Non fa niente.', 'Quebrou o copo? Não tem problema.', 'neutral', 4],
    ['a presto', '', 'a cedo', 'Até breve.', 'Até breve', '', 'Grazie di tutto, a presto!', 'Obrigado por tudo, até breve!', 'neutral', 4],
    ['certo che sì', '', 'certo que sim', 'Com toda a certeza.', 'Claro que sim', '', 'Vieni? — Certo che sì.', 'Você vem? — Claro que sim.', 'informal', 4],
    ['essere in gamba', '', 'estar em perna', 'Ser competente e confiável.', 'Ser gente boa e capaz', '', 'Il nuovo collega è in gamba.', 'O colega novo é muito capaz.', 'informal', 4],
    ['fare due passi', '', 'dar dois passos', 'Sair para uma caminhada curta.', 'Dar uma volta', '', 'Andiamo a fare due passi.', 'Vamos dar uma volta.', 'informal', 4],
    ['vale la pena', '', 'vale a pena', 'Compensa o esforço.', 'Vale a pena', '', 'Vale la pena provare.', 'Vale a pena tentar.', 'neutral', 5],
  ],
  B1: [
    ['avere le mani bucate', '', 'ter as mãos furadas', 'Gastar dinheiro sem controle.', 'Ter a mão furada', '', 'Mio fratello ha le mani bucate.', 'Meu irmão tem a mão furada.', 'informal', 3],
    ['essere giù di corda', '', 'estar embaixo da corda', 'Estar desanimado.', 'Estar para baixo', 'Do relógio de corda que perde a tensão.', 'Sei giù di corda oggi?', 'Você está para baixo hoje?', 'informal', 3],
    ['fare una figuraccia', '', 'fazer uma figuraça', 'Pagar um mico em público.', 'Pagar mico', '', 'Ho fatto una figuraccia alla riunione.', 'Paguei um mico na reunião.', 'informal', 4],
    ['prendere in giro', '', 'levar em volta', 'Zoar; enganar de brincadeira.', 'Tirar sarro', '', 'Mi stai prendendo in giro?', 'Você está tirando sarro de mim?', 'informal', 5],
    ['avere la testa tra le nuvole', '', 'ter a cabeça entre as nuvens', 'Estar distraído.', 'Estar no mundo da lua', '', 'Hai la testa tra le nuvole oggi.', 'Você está no mundo da lua hoje.', 'informal', 4],
    ['non avere peli sulla lingua', '', 'não ter pelos na língua', 'Falar sem rodeios, mesmo o que incomoda.', 'Não ter papas na língua', '', 'Lei non ha peli sulla lingua.', 'Ela não tem papas na língua.', 'neutral', 4],
    ['dare una mano', '', 'dar uma mão', 'Ajudar alguém.', 'Dar uma mão', '', 'Mi dai una mano con questo?', 'Me dá uma mão com isso?', 'informal', 5],
    ['essere al settimo cielo', '', 'estar no sétimo céu', 'Estar felicíssimo.', 'Estar nas nuvens', 'Da cosmologia medieval dos sete céus.', 'Era al settimo cielo per la notizia.', 'Ele estava nas nuvens com a notícia.', 'neutral', 3],
    ['avere un diavolo per capello', '', 'ter um diabo por cabelo', 'Estar furioso.', 'Estar uma fera', '', 'Oggi ha un diavolo per capello.', 'Hoje ele está uma fera.', 'informal', 3],
    ['andare a genio', '', 'ir ao gênio', 'Agradar; cair bem para alguém.', 'Agradar', '', 'Quel tipo non mi va a genio.', 'Aquele cara não me agrada.', 'informal', 3],
    ['attaccare bottone', '', 'pregar botão', 'Puxar conversa e não largar mais.', 'Puxar assunto', 'Do vendedor que segurava o botão do casaco do cliente.', 'Mi ha attaccato bottone per un’ora.', 'Ele me segurou numa conversa por uma hora.', 'informal', 3],
    ['avere le mani legate', '', 'ter as mãos amarradas', 'Não poder agir por impedimento externo.', 'Estar de mãos atadas', '', 'Mi dispiace, ho le mani legate.', 'Sinto muito, estou de mãos atadas.', 'neutral', 4],
    ['saltare agli occhi', '', 'saltar aos olhos', 'Ser evidente demais.', 'Saltar aos olhos', '', 'L’errore salta agli occhi.', 'O erro salta aos olhos.', 'neutral', 3],
    ['non chiudere occhio', '', 'não fechar olho', 'Não conseguir dormir.', 'Não pregar o olho', '', 'Non ho chiuso occhio stanotte.', 'Não preguei o olho esta noite.', 'informal', 4],
    ['essere una frana', '', 'ser um desmoronamento', 'Ser péssimo em alguma coisa.', 'Ser uma negação', '', 'In cucina sono una frana.', 'Na cozinha eu sou uma negação.', 'informal', 3],
    ['fare quattro chiacchiere', '', 'fazer quatro conversas', 'Bater um papo rápido.', 'Bater um papo', '', 'Facciamo quattro chiacchiere al bar.', 'Vamos bater um papo no bar.', 'informal', 4],
    ['perdere la testa', '', 'perder a cabeça', 'Perder o controle emocional.', 'Perder a cabeça', '', 'Ha perso la testa per una sciocchezza.', 'Ele perdeu a cabeça por uma bobagem.', 'neutral', 4],
    ['avere una fame da lupi', '', 'ter uma fome de lobos', 'Estar com muita fome.', 'Estar com uma fome de leão', '', 'Ho una fame da lupi.', 'Estou com uma fome de leão.', 'informal', 3],
    ['tirare avanti', '', 'puxar adiante', 'Ir levando, sobrevivendo.', 'Ir levando', '', 'Con questo stipendio tiriamo avanti.', 'Com esse salário a gente vai levando.', 'informal', 4],
    ['andare a ruba', '', 'ir a roubo', 'Vender-se num instante.', 'Voar da prateleira', '', 'I biglietti sono andati a ruba.', 'Os ingressos voaram.', 'neutral', 3],
    ['essere sulle spine', '', 'estar sobre os espinhos', 'Estar ansioso esperando notícia.', 'Estar numa agonia', '', 'Sono sulle spine da ieri.', 'Estou numa agonia desde ontem.', 'neutral', 3],
    ['cascare dal sonno', '', 'cair do sono', 'Estar caindo de sono.', 'Estar caindo de sono', '', 'Vado a letto, casco dal sonno.', 'Vou dormir, estou caindo de sono.', 'informal', 3],
    ['rompere le scatole', '', 'quebrar as caixas', 'Encher a paciência de alguém.', 'Encher o saco', '', 'Smettila di rompere le scatole.', 'Para de encher o saco.', 'informal', 4],
    ['costare uno sproposito', '', 'custar um despropósito', 'Ser caríssimo.', 'Custar uma fortuna', '', 'Quella borsa costa uno sproposito.', 'Aquela bolsa custa uma fortuna.', 'informal', 3],
    ['prendere una cotta', '', 'pegar uma queimadura', 'Apaixonar-se rapidamente.', 'Se amarrar em alguém', '', 'Ha preso una cotta per lei.', 'Ele se amarrou nela.', 'informal', 3],
  ],
  B2: [
    ['fare orecchie da mercante', '', 'fazer orelhas de mercador', 'Fingir que não ouviu.', 'Fazer ouvidos moucos', 'Do comerciante que só ouvia o que lhe convinha.', 'Il comune fa orecchie da mercante.', 'A prefeitura faz ouvidos moucos.', 'neutral', 3],
    ['essere fuori come un balcone', '', 'estar para fora como uma sacada', 'Estar completamente maluco.', 'Estar pirado', '', 'Quel tipo è fuori come un balcone.', 'Aquele cara é totalmente pirado.', 'informal', 3],
    ['menare il can per l’aia', '', 'levar o cão pelo terreiro', 'Enrolar para não chegar ao ponto.', 'Enrolar', '', 'Non menare il can per l’aia, rispondi.', 'Não enrole, responda.', 'informal', 3],
    ['togliersi un peso dallo stomaco', '', 'tirar um peso do estômago', 'Dizer o que estava entalado.', 'Tirar um peso das costas', '', 'Mi sono tolto un peso dallo stomaco.', 'Tirei um peso das costas.', 'neutral', 3],
    ['mettere il carro davanti ai buoi', '', 'pôr o carro na frente dos bois', 'Inverter a ordem correta das etapas.', 'Pôr o carro na frente dos bois', '', 'Firmare adesso è mettere il carro davanti ai buoi.', 'Assinar agora é pôr o carro na frente dos bois.', 'neutral', 3],
    ['avere la coda di paglia', '', 'ter o rabo de palha', 'Reagir na defensiva por ter culpa no cartório.', 'Ter rabo preso', 'De uma fábula: a raposa com rabo de palha teme o fogo.', 'Si offende subito: ha la coda di paglia.', 'Se ofende na hora: tem rabo preso.', 'informal', 3],
    ['fare il passo più lungo della gamba', '', 'dar o passo maior que a perna', 'Assumir mais do que se aguenta.', 'Dar um passo maior que a perna', '', 'Hanno fatto il passo più lungo della gamba.', 'Deram um passo maior que a perna.', 'neutral', 3],
    ['essere il fanalino di coda', '', 'ser a lanterninha', 'Ser o último da fila, o pior colocado.', 'Ser lanterninha', 'Do farol traseiro do último vagão.', 'Siamo il fanalino di coda del settore.', 'Somos a lanterninha do setor.', 'neutral', 3],
    ['non stare né in cielo né in terra', '', 'não estar nem no céu nem na terra', 'Não ter cabimento algum.', 'Não ter pé nem cabeça', '', 'Questa scusa non sta né in cielo né in terra.', 'Essa desculpa não tem pé nem cabeça.', 'neutral', 3],
    ['dormire sugli allori', '', 'dormir sobre os louros', 'Acomodar-se depois de um sucesso.', 'Dormir sobre os louros', 'Da coroa de louros dos vencedores romanos.', 'Non dormire sugli allori.', 'Não durma sobre os louros.', 'formal', 3],
    ['essere una mosca bianca', '', 'ser uma mosca branca', 'Ser raríssimo no meio em que está.', 'Ser uma raridade', '', 'Un dirigente così è una mosca bianca.', 'Um gestor assim é uma raridade.', 'neutral', 3],
    ['avere un asso nella manica', '', 'ter um ás na manga', 'Guardar um recurso decisivo escondido.', 'Ter uma carta na manga', '', 'Il legale ha un asso nella manica.', 'O advogado tem uma carta na manga.', 'neutral', 3],
    ['cercare il pelo nell’uovo', '', 'procurar o pelo no ovo', 'Implicar com detalhes mínimos.', 'Procurar pelo em ovo', '', 'Smetti di cercare il pelo nell’uovo.', 'Pare de procurar pelo em ovo.', 'informal', 3],
    ['essere culo e camicia', '', 'ser bunda e camisa', 'Ser inseparáveis, quase cúmplices.', 'Ser unha e carne', '', 'Quei due sono culo e camicia.', 'Aqueles dois são unha e carne.', 'informal', 3],
    ['parlare fuori dai denti', '', 'falar fora dos dentes', 'Dizer o que pensa, sem filtro.', 'Falar na lata', '', 'Parliamo fuori dai denti: non funziona.', 'Vamos falar na lata: não funciona.', 'informal', 3],
    ['tagliare la corda', '', 'cortar a corda', 'Escapar discretamente.', 'Dar no pé', 'Da marinha: cortar a amarra e fugir.', 'Ha tagliato la corda prima del conto.', 'Ele deu no pé antes da conta.', 'informal', 3],
    ['fare un buco nell’acqua', '', 'fazer um buraco na água', 'Tentar e não conseguir absolutamente nada.', 'Dar em nada', '', 'La campagna ha fatto un buco nell’acqua.', 'A campanha deu em nada.', 'neutral', 3],
    ['avere le carte in regola', '', 'ter as cartas em ordem', 'Preencher todos os requisitos.', 'Estar com tudo em dia', '', 'Il candidato ha le carte in regola.', 'O candidato está com tudo em dia.', 'formal', 3],
    ['mettere una pulce nell’orecchio', '', 'pôr uma pulga no ouvido', 'Semear uma desconfiança.', 'Deixar a pulga atrás da orelha', '', 'Quella frase mi ha messo una pulce nell’orecchio.', 'Aquela frase deixou a pulga atrás da minha orelha.', 'neutral', 3],
    ['avere la puzza sotto il naso', '', 'ter o cheiro ruim sob o nariz', 'Ser esnobe.', 'Ser metido', '', 'Ha sempre la puzza sotto il naso.', 'Ele é sempre metido.', 'informal', 3],
    ['prendere il toro per le corna', '', 'pegar o touro pelos chifres', 'Enfrentar o problema de frente.', 'Pegar o touro à unha', '', 'Prendiamo il toro per le corna.', 'Vamos pegar o touro à unha.', 'neutral', 3],
    ['far girare le scatole', '', 'fazer girar as caixas', 'Irritar profundamente.', 'Tirar do sério', '', 'Questa storia mi fa girare le scatole.', 'Essa história me tira do sério.', 'informal', 3],
    ['calare le braghe', '', 'baixar as calças', 'Ceder humilhantemente.', 'Baixar a cabeça', '', 'Alla prima difficoltà hanno calato le braghe.', 'Na primeira dificuldade eles baixaram a cabeça.', 'informal', 2],
    ['essere con l’acqua alla gola', '', 'estar com a água na garganta', 'Estar em apuros e sem tempo.', 'Estar com a corda no pescoço', '', 'Siamo con l’acqua alla gola per la consegna.', 'Estamos com a corda no pescoço para entregar.', 'neutral', 3],
    ['tirare la corda', '', 'puxar a corda', 'Forçar a situação até quase romper.', 'Esticar a corda', '', 'Non tirare troppo la corda.', 'Não estique demais a corda.', 'neutral', 3],
  ],
  C1: [
    ['mettere il dito nella piaga', '', 'pôr o dedo na chaga', 'Tocar exatamente no ponto doloroso.', 'Pôr o dedo na ferida', '', 'Hai messo il dito nella piaga.', 'Você pôs o dedo na ferida.', 'neutral', 3],
    ['gettare la spugna', '', 'jogar a esponja', 'Desistir depois de muito resistir.', 'Jogar a toalha', 'Do boxe.', 'Dopo due anni ha gettato la spugna.', 'Depois de dois anos ele jogou a toalha.', 'neutral', 3],
    ['cadere dalle nuvole', '', 'cair das nuvens', 'Ficar espantado por não saber de nada.', 'Cair das nuvens', '', 'Quando l’ho saputo sono caduto dalle nuvole.', 'Quando soube, caí das nuvens.', 'neutral', 3],
    ['avere la botte piena e la moglie ubriaca', '', 'ter o barril cheio e a esposa bêbada', 'Querer duas vantagens incompatíveis.', 'Querer ter o bolo e comer o bolo', '', 'Non puoi avere la botte piena e la moglie ubriaca.', 'Você não pode ter o bolo e comer o bolo.', 'informal', 3],
    ['prendere lucciole per lanterne', '', 'tomar vaga-lumes por lanternas', 'Confundir grosseiramente uma coisa com outra.', 'Confundir alhos com bugalhos', '', 'Hai preso lucciole per lanterne.', 'Você confundiu alhos com bugalhos.', 'formal', 2],
    ['tirare l’acqua al proprio mulino', '', 'puxar a água para o próprio moinho', 'Conduzir tudo para o próprio interesse.', 'Puxar a sardinha para o seu lado', '', 'Ognuno tira l’acqua al proprio mulino.', 'Cada um puxa a sardinha para o seu lado.', 'neutral', 3],
    ['avere il coltello dalla parte del manico', '', 'ter a faca pelo lado do cabo', 'Estar em posição de força.', 'Estar com a faca e o queijo na mão', '', 'In questa trattativa hanno il coltello dalla parte del manico.', 'Nessa negociação eles estão com a faca e o queijo na mão.', 'neutral', 3],
    ['fare di tutta l’erba un fascio', '', 'fazer de toda a erva um feixe', 'Generalizar sem distinguir os casos.', 'Meter tudo no mesmo saco', '', 'Non facciamo di tutta l’erba un fascio.', 'Não vamos meter tudo no mesmo saco.', 'formal', 3],
    ['mettere le mani avanti', '', 'pôr as mãos à frente', 'Antecipar desculpas para se proteger.', 'Se precaver', '', 'Mette sempre le mani avanti.', 'Ele sempre se precavê antes.', 'neutral', 3],
    ['navigare a vista', '', 'navegar à vista', 'Conduzir sem plano, decidindo na hora.', 'Ir levando conforme der', 'Da navegação sem instrumentos.', 'L’azienda naviga a vista da mesi.', 'A empresa navega sem rumo há meses.', 'formal', 3],
    ['stare con le mani in mano', '', 'ficar com as mãos na mão', 'Ficar parado sem fazer nada.', 'Ficar de braços cruzados', '', 'Non stare con le mani in mano.', 'Não fique de braços cruzados.', 'informal', 3],
    ['battere il ferro finché è caldo', '', 'bater o ferro enquanto está quente', 'Aproveitar a oportunidade no momento certo.', 'Malhar o ferro enquanto está quente', '', 'Battiamo il ferro finché è caldo.', 'Vamos malhar o ferro enquanto está quente.', 'neutral', 3],
    ['mettere i puntini sulle i', '', 'pôr os pontinhos nos is', 'Esclarecer tudo com precisão.', 'Pôr os pingos nos is', '', 'È ora di mettere i puntini sulle i.', 'É hora de pôr os pingos nos is.', 'neutral', 3],
    ['leggere tra le righe', '', 'ler entre as linhas', 'Captar o que ficou implícito.', 'Ler nas entrelinhas', '', 'Bisogna leggere tra le righe.', 'É preciso ler nas entrelinhas.', 'formal', 4],
    ['chiudere un occhio', '', 'fechar um olho', 'Deixar passar uma falha de propósito.', 'Fazer vista grossa', '', 'Per questa volta chiudo un occhio.', 'Por esta vez eu faço vista grossa.', 'neutral', 4],
    ['essere di manica larga', '', 'ser de manga larga', 'Ser tolerante demais ao avaliar.', 'Ser mão aberta na nota', 'Das mangas largas dos hábitos religiosos, onde se escondiam coisas.', 'Quel professore è di manica larga.', 'Aquele professor é bem tolerante.', 'informal', 2],
    ['giocare a carte scoperte', '', 'jogar com cartas descobertas', 'Agir com transparência total.', 'Jogar com as cartas na mesa', '', 'Giochiamo a carte scoperte.', 'Vamos jogar com as cartas na mesa.', 'formal', 3],
    ['alzare l’asticella', '', 'levantar a barra', 'Elevar o nível exigido.', 'Elevar o nível', 'Do salto em altura.', 'Il concorrente ha alzato l’asticella.', 'O concorrente elevou o nível.', 'neutral', 3],
    ['rimandare alle calende greche', '', 'adiar para as calendas gregas', 'Adiar para uma data que nunca chega.', 'Adiar para o dia de São Nunca', 'Os gregos não tinham calendas — a data não existia.', 'La riforma è rimandata alle calende greche.', 'A reforma foi adiada para o dia de São Nunca.', 'formal', 2],
    ['prendere fischi per fiaschi', '', 'tomar assobios por garrafas', 'Entender uma coisa por outra.', 'Entender tudo errado', '', 'Hai preso fischi per fiaschi.', 'Você entendeu tudo errado.', 'informal', 2],
    ['buttare fumo negli occhi', '', 'jogar fumaça nos olhos', 'Iludir com aparências.', 'Jogar areia nos olhos', '', 'Quel discorso butta fumo negli occhi.', 'Aquele discurso joga areia nos olhos.', 'formal', 3],
    ['avere le spalle coperte', '', 'ter as costas cobertas', 'Estar protegido por quem tem poder.', 'Ter costas quentes', '', 'Non teme nulla: ha le spalle coperte.', 'Ele não teme nada: tem costas quentes.', 'neutral', 3],
    ['andare controcorrente', '', 'ir contra a corrente', 'Agir contra a opinião dominante.', 'Remar contra a maré', '', 'La sua tesi va controcorrente.', 'A tese dele rema contra a maré.', 'formal', 3],
    ['tenere il piede in due scarpe', '', 'ter o pé em dois sapatos', 'Jogar dos dois lados ao mesmo tempo.', 'Jogar nos dois times', '', 'Tiene il piede in due scarpe da mesi.', 'Ele joga nos dois times há meses.', 'neutral', 3],
    ['passare il testimone', '', 'passar o bastão', 'Transferir a responsabilidade a quem vem depois.', 'Passar o bastão', 'Do revezamento no atletismo.', 'È ora di passare il testimone.', 'É hora de passar o bastão.', 'formal', 3],
  ],
  C2: [
    ['fare le nozze coi fichi secchi', '', 'fazer o casamento com figos secos', 'Tentar algo grande com recursos ridículos.', 'Fazer festa com pão e água', '', 'Con questo budget facciamo le nozze coi fichi secchi.', 'Com esse orçamento é festa com pão e água.', 'formal', 2],
    ['essere il capro espiatorio', '', 'ser o bode expiatório', 'Levar a culpa de todos.', 'Ser o bode expiatório', 'Do rito hebraico do Yom Kipur.', 'È stato il capro espiatorio della crisi.', 'Ele foi o bode expiatório da crise.', 'formal', 3],
    ['la punta dell’iceberg', '', 'a ponta do iceberg', 'A parte visível de um problema muito maior.', 'A ponta do iceberg', '', 'Questi casi sono la punta dell’iceberg.', 'Esses casos são a ponta do iceberg.', 'formal', 3],
    ['il dado è tratto', '', 'o dado está lançado', 'A decisão irreversível já foi tomada.', 'A sorte está lançada', 'Frase atribuída a Júlio César ao cruzar o Rubicão.', 'Abbiamo firmato: il dado è tratto.', 'Assinamos: a sorte está lançada.', 'formal', 2],
    ['il tallone d’Achille', '', 'o calcanhar de Aquiles', 'O ponto fraco decisivo.', 'Calcanhar de Aquiles', 'Da Ilíada.', 'La logistica è il loro tallone d’Achille.', 'A logística é o calcanhar de Aquiles deles.', 'formal', 3],
    ['una spada di Damocle', '', 'uma espada de Dâmocles', 'Ameaça permanente pairando sobre alguém.', 'Espada de Dâmocles', 'Da corte de Dionísio de Siracusa.', 'Il debito è una spada di Damocle.', 'A dívida é uma espada de Dâmocles.', 'formal', 2],
    ['varcare il Rubicone', '', 'atravessar o Rubicão', 'Dar o passo sem volta.', 'Cruzar o Rubicão', 'César, em 49 a.C.', 'Firmando, hanno varcato il Rubicone.', 'Ao assinar, cruzaram o Rubicão.', 'formal', 2],
    ['un cavallo di Troia', '', 'um cavalo de Troia', 'Ameaça que entra disfarçada de presente.', 'Cavalo de Troia', 'Da Eneida.', 'Quella clausola è un cavallo di Troia.', 'Aquela cláusula é um cavalo de Troia.', 'formal', 3],
    ['il canto delle sirene', '', 'o canto das sereias', 'Promessa sedutora que leva à ruína.', 'Canto de sereia', 'Da Odisseia.', 'Non cedere al canto delle sirene.', 'Não ceda ao canto de sereia.', 'formal', 2],
    ['uccidere la gallina dalle uova d’oro', '', 'matar a galinha dos ovos de ouro', 'Destruir a própria fonte de ganho.', 'Matar a galinha dos ovos de ouro', 'De Esopo.', 'Alzare così i prezzi è uccidere la gallina dalle uova d’oro.', 'Subir tanto os preços é matar a galinha dos ovos de ouro.', 'formal', 3],
    ['tagliare il nodo gordiano', '', 'cortar o nó górdio', 'Resolver um impasse com um golpe decisivo.', 'Cortar o nó górdio', 'Alexandre, o Grande.', 'Bisognava tagliare il nodo gordiano.', 'Era preciso cortar o nó górdio.', 'formal', 2],
    ['un castello di carte', '', 'um castelo de cartas', 'Estrutura que desaba ao primeiro abalo.', 'Castelo de cartas', '', 'Il piano era un castello di carte.', 'O plano era um castelo de cartas.', 'formal', 3],
    ['una tempesta in un bicchier d’acqua', '', 'uma tempestade num copo d’água', 'Alvoroço enorme por algo mínimo.', 'Tempestade em copo d’água', '', 'È una tempesta in un bicchier d’acqua.', 'É tempestade em copo d’água.', 'formal', 3],
    ['gettare le perle ai porci', '', 'jogar as pérolas aos porcos', 'Oferecer o valioso a quem não reconhece.', 'Dar pérolas aos porcos', 'Do Evangelho de Mateus.', 'Regalargli quel vino è gettare le perle ai porci.', 'Dar aquele vinho a ele é dar pérolas aos porcos.', 'formal', 2],
    ['predicare nel deserto', '', 'pregar no deserto', 'Falar sem que ninguém escute.', 'Pregar no deserto', 'De João Batista.', 'Predico nel deserto da anni.', 'Prego no deserto há anos.', 'formal', 2],
    ['l’abito non fa il monaco', '', 'o hábito não faz o monge', 'A aparência não define a pessoa.', 'O hábito não faz o monge', '', 'Ricorda che l’abito non fa il monaco.', 'Lembre que o hábito não faz o monge.', 'formal', 3],
    ['non è tutto oro quel che luccica', '', 'nem tudo que reluz é ouro', 'Nem toda aparência boa corresponde à realidade.', 'Nem tudo que reluz é ouro', 'Difundida por Shakespeare em "O Mercador de Veneza".', 'Attento: non è tutto oro quel che luccica.', 'Cuidado: nem tudo que reluz é ouro.', 'neutral', 3],
    ['chi troppo vuole nulla stringe', '', 'quem quer demais nada agarra', 'Quem tenta tudo ao mesmo tempo não obtém nada.', 'Quem muito quer, nada tem', '', 'Concentrati: chi troppo vuole nulla stringe.', 'Concentre-se: quem muito quer, nada tem.', 'formal', 2],
    ['il lupo perde il pelo ma non il vizio', '', 'o lobo perde o pelo mas não o vício', 'O caráter não muda com o tempo.', 'Pau que nasce torto morre torto', '', 'Il lupo perde il pelo ma non il vizio.', 'Pau que nasce torto morre torto.', 'neutral', 3],
    ['tra il dire e il fare c’è di mezzo il mare', '', 'entre o dizer e o fazer há o mar no meio', 'Entre prometer e cumprir há uma distância enorme.', 'Falar é fácil, difícil é fazer', '', 'Tra il dire e il fare c’è di mezzo il mare.', 'Entre falar e fazer há uma distância enorme.', 'neutral', 3],
    ['ogni morte di papa', '', 'a cada morte de papa', 'Raríssimo, quase nunca.', 'A cada morte de bispo', '', 'Ci vediamo ogni morte di papa.', 'A gente se vê a cada morte de bispo.', 'informal', 3],
    ['essere l’ago della bilancia', '', 'ser a agulha da balança', 'Ser quem decide um equilíbrio disputado.', 'Ser o fiel da balança', '', 'Quel partito è l’ago della bilancia.', 'Aquele partido é o fiel da balança.', 'formal', 3],
    ['vuotare il sacco', '', 'esvaziar o saco', 'Contar tudo o que se sabia e calava.', 'Abrir o jogo', '', 'Alla fine ha vuotato il sacco.', 'No fim ele abriu o jogo.', 'informal', 3],
    ['essere il vaso di coccio tra vasi di ferro', '', 'ser o vaso de barro entre vasos de ferro', 'Ser o mais frágil num ambiente de fortes.', 'Ser o elo mais fraco', 'De "Os Noivos", de Manzoni.', 'In quel consiglio è il vaso di coccio tra vasi di ferro.', 'Naquele conselho ele é o elo mais fraco.', 'formal', 2],
    ['trovare il bandolo della matassa', '', 'achar a ponta do novelo', 'Encontrar o fio que desata o problema.', 'Achar a ponta do novelo', '', 'Finalmente abbiamo trovato il bandolo della matassa.', 'Finalmente achamos a ponta do novelo.', 'formal', 2],
  ],
};
