/**
 * Japonês — expressões por nível.
 *
 * Nenhuma expressão aqui repete o lote curado de `idioms.ts`. Toda entrada
 * traz romanização: sem ela, o aluno vê um bloco de kanji e não consegue nem
 * pronunciar o que está estudando.
 */

import type { ByLevel } from './entry';

export const JA: ByLevel = {
  A2: [
    ['よろしく', 'yoroshiku', 'favoravelmente', 'Fórmula de apresentação e de pedido de colaboração.', 'Prazer; conto com você', 'Abreviação de 「よろしくお願いします」.', '田中です。よろしく。', 'Sou o Tanaka. Prazer.', 'informal', 5],
    ['しょうがない', 'shou ga nai', 'não há jeito', 'Não tem o que fazer; é o que é.', 'Fazer o quê', '', '雨だから、しょうがないね。', 'Está chovendo, fazer o quê.', 'informal', 5],
    ['久しぶり', 'hisashiburi', 'depois de muito tempo', 'Quanto tempo! — a quem não se via há muito.', 'Quanto tempo', '', '久しぶり、元気だった？', 'Quanto tempo! Tudo bem?', 'informal', 5],
    ['大丈夫', 'daijoubu', 'grande homem robusto', 'Está tudo bem; tudo certo.', 'Tudo bem', 'O sentido original era "sólido, seguro".', '大丈夫、心配しないで。', 'Tudo bem, não se preocupe.', 'neutral', 5],
    ['気を付けて', 'ki wo tsukete', 'prenda o ânimo', 'Cuide-se; vá com cuidado.', 'Se cuida', '', '道が暗いから気を付けて。', 'A rua está escura, se cuida.', 'neutral', 5],
    ['いただきます', 'itadakimasu', 'eu recebo humildemente', 'Dito antes de comer, agradecendo a quem produziu.', 'Sem equivalente direto', 'Vem do budismo: gratidão pela vida que sustenta a refeição.', 'では、いただきます。', 'Então, vamos comer.', 'neutral', 5],
    ['ごちそうさま', 'gochisousama', 'foi um banquete', 'Dito ao terminar de comer, agradecendo.', 'Sem equivalente direto', '', 'ごちそうさま、おいしかった。', 'Obrigado pela refeição, estava ótima.', 'neutral', 5],
    ['お邪魔します', 'ojama shimasu', 'vou atrapalhar', 'Dito ao entrar na casa de alguém.', 'Com licença', '', 'お邪魔します、失礼します。', 'Com licença, entro então.', 'formal', 4],
    ['おかげさまで', 'okagesama de', 'graças à sua sombra', 'Graças a você; usado mesmo com estranhos.', 'Graças a Deus', 'A "sombra" é a proteção invisível recebida dos outros.', 'おかげさまで元気です。', 'Graças a você, estou bem.', 'formal', 4],
    ['とんでもない', 'tondemonai', 'inaceitável', 'Imagina! — recusa modesta de um elogio.', 'Imagina', '', 'とんでもない、私は何もしていません。', 'Imagina, eu não fiz nada.', 'formal', 4],
    ['なるほど', 'naruhodo', 'até o ponto de se tornar', 'Ah, entendi; faz sentido.', 'Entendi', '', 'なるほど、そういうことか。', 'Entendi, então é isso.', 'neutral', 5],
    ['まあまあ', 'maamaa', 'mais ou menos', 'Nem bom nem ruim.', 'Mais ou menos', '', '味はまあまあだった。', 'O sabor estava mais ou menos.', 'informal', 4],
    ['やっぱり', 'yappari', 'como esperado', 'Eu sabia; no fim das contas.', 'Eu sabia', '', 'やっぱり彼は来なかった。', 'Eu sabia que ele não viria.', 'informal', 5],
    ['どういたしまして', 'dou itashimashite', 'como eu faria', 'De nada.', 'De nada', '', 'ありがとう。— どういたしまして。', 'Obrigado. — De nada.', 'neutral', 4],
    ['ちょっと待って', 'chotto matte', 'espere um pouco', 'Espera aí.', 'Peraí', '', 'ちょっと待って、鍵を探す。', 'Espera aí, vou procurar a chave.', 'informal', 5],
    ['がんばって', 'ganbatte', 'esforce-se', 'Boa sorte; força aí.', 'Força', '', '試験、がんばって！', 'Boa sorte na prova!', 'informal', 5],
    ['お先に失礼します', 'osaki ni shitsurei shimasu', 'sou grosseiro por ir antes', 'Dito ao sair do trabalho antes dos colegas.', 'Sem equivalente direto', 'Reflete a etiqueta de não deixar o grupo sem se desculpar.', 'お先に失礼します。', 'Com licença, vou indo antes.', 'formal', 4],
    ['まさか', 'masaka', 'não pode ser', 'Não acredito; jamais.', 'Não acredito', '', 'まさか、彼が？', 'Não acredito, ele?', 'informal', 4],
    ['ぜんぜん', 'zenzen', 'de todo', 'Nem um pouco — com verbo na negativa.', 'Nem um pouco', '', 'ぜんぜん分からない。', 'Não entendo nem um pouco.', 'informal', 5],
    ['もちろん', 'mochiron', 'naturalmente', 'Claro; sem dúvida.', 'Claro', '', 'もちろん行きます。', 'Claro que eu vou.', 'neutral', 5],
    ['ただいま', 'tadaima', 'agora mesmo', 'Cheguei — dito ao entrar em casa.', 'Cheguei', 'Abreviação de 「ただいま帰りました」.', 'ただいま、遅くなった。', 'Cheguei, me atrasei.', 'informal', 5],
    ['おかえり', 'okaeri', 'bem-vindo de volta', 'Resposta a quem chega em casa.', 'Bem-vindo', '', 'おかえり、ご飯できてるよ。', 'Bem-vindo, a comida está pronta.', 'informal', 5],
    ['いってきます', 'ittekimasu', 'vou e volto', 'Dito ao sair de casa.', 'Já volto', 'A promessa embutida de retorno é parte do sentido.', 'いってきます、六時に帰る。', 'Estou saindo, volto às seis.', 'informal', 5],
    ['いってらっしゃい', 'itterasshai', 'vá e volte', 'Resposta a quem sai de casa.', 'Vá com Deus', '', 'いってらっしゃい、気を付けて。', 'Até logo, se cuida.', 'informal', 5],
    ['せっかく', 'sekkaku', 'com esforço deliberado', 'Já que se fez o esforço; aproveitando a ocasião.', 'Já que', '', 'せっかく来たのに休みだった。', 'Vim até aqui e estava fechado.', 'neutral', 4],
  ],
  B1: [
    ['空気を読む', 'kuuki wo yomu', 'ler o ar', 'Perceber o clima do grupo e agir conforme.', 'Ler o ambiente', 'Competência social central no Japão; quem não a tem é chamado de 「KY」.', '会議では空気を読む必要がある。', 'Na reunião é preciso ler o ambiente.', 'neutral', 5],
    ['気が合う', 'ki ga au', 'os ânimos combinam', 'Ter afinidade natural com alguém.', 'Ter afinidade', '', '彼とは気が合う。', 'Eu tenho afinidade com ele.', 'informal', 4],
    ['手を貸す', 'te wo kasu', 'emprestar a mão', 'Ajudar alguém.', 'Dar uma mão', '', 'ちょっと手を貸してくれる？', 'Pode me dar uma mão?', 'informal', 4],
    ['耳が痛い', 'mimi ga itai', 'a orelha dói', 'Ouvir uma crítica que acerta em cheio.', 'Doer nos ouvidos', '', 'その指摘は耳が痛い。', 'Essa crítica dói de tão certa.', 'neutral', 4],
    ['目が高い', 'me ga takai', 'o olho é alto', 'Ter bom olho para qualidade.', 'Ter bom gosto', '', 'お目が高いですね。', 'O senhor tem bom olho.', 'formal', 3],
    ['頭が下がる', 'atama ga sagaru', 'a cabeça abaixa', 'Sentir profunda admiração por alguém.', 'Tirar o chapéu', '', '彼の努力には頭が下がる。', 'Tiro o chapéu para o esforço dele.', 'formal', 3],
    ['口が堅い', 'kuchi ga katai', 'a boca é dura', 'Ser discreto, guardar segredo.', 'Ser um túmulo', 'Oposto exato de 口が軽い.', '彼女は口が堅いから安心だ。', 'Ela é um túmulo, pode ficar tranquilo.', 'neutral', 4],
    ['気が重い', 'ki ga omoi', 'o ânimo é pesado', 'Estar desanimado diante de algo que precisa fazer.', 'Estar sem ânimo', '', '明日の面談は気が重い。', 'Estou sem ânimo para a conversa de amanhã.', 'neutral', 3],
    ['顔を出す', 'kao wo dasu', 'mostrar o rosto', 'Dar as caras num evento.', 'Dar as caras', '', '少しだけ顔を出すつもりだ。', 'Pretendo só dar as caras.', 'informal', 4],
    ['骨が折れる', 'hone ga oreru', 'o osso quebra', 'Ser trabalhoso e cansativo.', 'Ser osso duro', '', 'この作業は骨が折れる。', 'Esse trabalho é osso duro.', 'neutral', 3],
    ['気が利く', 'ki ga kiku', 'o ânimo funciona', 'Ser atencioso, antecipar o que o outro precisa.', 'Ser atencioso', '', '彼はよく気が利く。', 'Ele é muito atencioso.', 'neutral', 4],
    ['手が空く', 'te ga aku', 'a mão esvazia', 'Ficar livre de tarefas.', 'Ficar livre', '', '手が空いたら手伝うよ。', 'Quando eu ficar livre, eu ajudo.', 'informal', 4],
    ['目を通す', 'me wo toosu', 'passar o olho', 'Dar uma lida rápida.', 'Dar uma passada de olho', '', '資料に目を通しておく。', 'Vou dar uma passada de olho no material.', 'neutral', 4],
    ['気にする', 'ki ni suru', 'fazer disso um ânimo', 'Se importar; ficar remoendo.', 'Ligar para', '', 'そんなに気にしないで。', 'Não ligue tanto para isso.', 'informal', 5],
    ['気になる', 'ki ni naru', 'virar ânimo', 'Ficar curioso ou preocupado com algo.', 'Ficar na cabeça', 'Diferença sutil com 気にする: aqui o sentimento vem sozinho.', '結果が気になる。', 'O resultado fica na minha cabeça.', 'informal', 5],
    ['手間がかかる', 'tema ga kakaru', 'toma mão e tempo', 'Dar trabalho, exigir muitos passos.', 'Dar trabalho', '', 'この料理は手間がかかる。', 'Esse prato dá trabalho.', 'neutral', 4],
    ['腰が重い', 'koshi ga omoi', 'o quadril é pesado', 'Custar a começar algo.', 'Ser mole para começar', '', '彼は腰が重いタイプだ。', 'Ele custa a começar as coisas.', 'informal', 3],
    ['顔色が悪い', 'kaoiro ga warui', 'a cor do rosto é ruim', 'Estar com aparência abatida.', 'Estar com cara ruim', '', '顔色が悪いけど大丈夫？', 'Você está com cara ruim, tudo bem?', 'neutral', 3],
    ['話にならない', 'hanashi ni naranai', 'não vira conversa', 'Ser tão ruim que nem vale discutir.', 'Nem se discute', '', 'この品質では話にならない。', 'Com essa qualidade nem se discute.', 'neutral', 3],
    ['道草を食う', 'michikusa wo kuu', 'comer capim do caminho', 'Enrolar no caminho, se distrair.', 'Enrolar no caminho', 'Dos cavalos que paravam para comer capim.', '帰りに道草を食ってしまった。', 'Acabei enrolando na volta.', 'informal', 3],
    ['熱が冷める', 'netsu ga sameru', 'a febre esfria', 'Perder o entusiasmo inicial.', 'Esfriar o ânimo', '', 'ブームの熱が冷めてきた。', 'O entusiasmo com a moda esfriou.', 'neutral', 3],
    ['目が回る', 'me ga mawaru', 'os olhos giram', 'Estar tonto de tão ocupado.', 'Estar de cabeça rodando', '', '忙しくて目が回る。', 'Estou tão ocupado que minha cabeça roda.', 'informal', 3],
    ['手を抜く', 'te wo nuku', 'tirar a mão', 'Fazer com menos cuidado do que devia.', 'Fazer nas coxas', '', 'この工程で手を抜いてはいけない。', 'Nessa etapa não dá para fazer nas coxas.', 'neutral', 4],
    ['気が済む', 'ki ga sumu', 'o ânimo se completa', 'Ficar satisfeito depois de fazer o que queria.', 'Ficar satisfeito', '', '言いたいことを言って気が済んだ。', 'Falei o que queria e fiquei satisfeito.', 'informal', 3],
    ['息を抜く', 'iki wo nuku', 'tirar o fôlego', 'Dar uma pausa para respirar.', 'Dar um respiro', '', 'たまには息を抜こう。', 'De vez em quando, vamos dar um respiro.', 'informal', 3],
  ],
  B2: [
    ['一期一会', 'ichigo ichie', 'uma vida, um encontro', 'Cada encontro é único e não se repete.', 'Sem equivalente direto', 'Do cerimonial do chá, formulado por Sen no Rikyū.', '一期一会の気持ちで接する。', 'Trato cada encontro como único.', 'formal', 3],
    ['七転び八起き', 'nanakorobi yaoki', 'sete quedas, oito levantadas', 'Levantar sempre uma vez a mais do que se cai.', 'Cair sete vezes, levantar oito', 'Ligada ao daruma, o boneco que sempre volta a ficar de pé.', '七転び八起きでやってきた。', 'Cheguei aqui caindo e levantando.', 'neutral', 3],
    ['猿も木から落ちる', 'saru mo ki kara ochiru', 'até o macaco cai da árvore', 'Até o especialista erra.', 'Até o macaco cai da árvore', '', '猿も木から落ちる、気にするな。', 'Até o macaco cai da árvore, não se preocupe.', 'neutral', 3],
    ['花より団子', 'hana yori dango', 'bolinho em vez de flor', 'Preferir o proveito prático ao estético.', 'Antes o útil que o belo', 'Das festas de contemplação das cerejeiras, onde muitos só iam pela comida.', '花より団子で、屋台に直行した。', 'Fui direto às barracas: antes o útil que o belo.', 'informal', 3],
    ['石の上にも三年', 'ishi no ue ni mo sannen', 'três anos mesmo sobre a pedra', 'A persistência acaba aquecendo até a pedra.', 'Água mole em pedra dura', '', '石の上にも三年、続けてみよう。', 'Água mole em pedra dura: vamos continuar.', 'formal', 3],
    ['出る杭は打たれる', 'derukui wa utareru', 'a estaca que se destaca leva martelada', 'Quem se destaca demais é podado pelo grupo.', 'Cabeça que se levanta é cortada', 'Retrato direto da pressão de conformidade social.', '出る杭は打たれる文化がある。', 'Existe uma cultura de podar quem se destaca.', 'neutral', 3],
    ['二階から目薬', 'nikai kara megusuri', 'colírio do segundo andar', 'Método totalmente ineficaz para o problema.', 'Enxugar gelo', '', 'その対策は二階から目薬だ。', 'Essa medida é enxugar gelo.', 'formal', 2],
    ['濡れ手で粟', 'nurete de awa', 'painço com a mão molhada', 'Lucro grande sem esforço nenhum.', 'Dinheiro fácil', 'Grãos de painço grudam na mão molhada.', '濡れ手で粟のような話は疑うべきだ。', 'Histórias de dinheiro fácil merecem desconfiança.', 'formal', 2],
    ['転ばぬ先の杖', 'korobanu saki no tsue', 'a bengala antes da queda', 'Prevenir antes que o problema aconteça.', 'Melhor prevenir que remediar', '', '転ばぬ先の杖として保険に入った。', 'Fiz seguro: melhor prevenir que remediar.', 'formal', 3],
    ['絵に描いた餅', 'e ni kaita mochi', 'bolinho pintado num quadro', 'Plano bonito e inútil.', 'Castelo no ar', '', 'その計画は絵に描いた餅だ。', 'Aquele plano é castelo no ar.', 'formal', 3],
    ['馬の耳に念仏', 'uma no mimi ni nenbutsu', 'sutra no ouvido do cavalo', 'Conselho dado a quem não vai ouvir.', 'Falar com a parede', '', '彼に言っても馬の耳に念仏だ。', 'Falar com ele é falar com a parede.', 'neutral', 3],
    ['首を長くする', 'kubi wo nagaku suru', 'esticar o pescoço', 'Esperar ansiosamente.', 'Contar os dias', '', '返事を首を長くして待っている。', 'Estou contando os dias pela resposta.', 'neutral', 3],
    ['火に油を注ぐ', 'hi ni abura wo sosogu', 'derramar óleo no fogo', 'Piorar um conflito de propósito.', 'Botar lenha na fogueira', '', 'その発言は火に油を注いだ。', 'Aquela fala botou lenha na fogueira.', 'neutral', 3],
    ['大目に見る', 'oome ni miru', 'olhar com olho grande', 'Relevar uma falha.', 'Fazer vista grossa', '', '今回は大目に見よう。', 'Desta vez vamos fazer vista grossa.', 'neutral', 3],
    ['腹を割って話す', 'hara wo watte hanasu', 'falar abrindo a barriga', 'Conversar com total franqueza.', 'Abrir o jogo', 'No Japão, a barriga é a sede da intenção verdadeira.', '一度腹を割って話そう。', 'Vamos abrir o jogo uma vez.', 'informal', 3],
    ['手も足も出ない', 'te mo ashi mo denai', 'nem mão nem pé saem', 'Não ter absolutamente o que fazer.', 'Ficar de mãos atadas', '', 'この問題には手も足も出ない。', 'Nesse problema fico de mãos atadas.', 'neutral', 3],
    ['目から鱗が落ちる', 'me kara uroko ga ochiru', 'as escamas caem dos olhos', 'Compreender de repente o que estava óbvio.', 'Cair a ficha', 'Dos Atos dos Apóstolos, na conversão de Paulo.', 'その説明で目から鱗が落ちた。', 'Com aquela explicação a ficha caiu.', 'neutral', 3],
    ['足を引っ張る', 'ashi wo hipparu', 'puxar a perna', 'Atrapalhar o progresso do grupo.', 'Puxar para trás', '', 'チームの足を引っ張りたくない。', 'Não quero puxar o time para trás.', 'neutral', 4],
    ['顔から火が出る', 'kao kara hi ga deru', 'sai fogo do rosto', 'Morrer de vergonha.', 'Ficar vermelho de vergonha', '', '思い出すと顔から火が出る。', 'Quando lembro, morro de vergonha.', 'informal', 3],
    ['口を挟む', 'kuchi wo hasamu', 'enfiar a boca', 'Interromper a conversa alheia.', 'Meter a colher', '', '横から口を挟まないで。', 'Não meta a colher no meio.', 'informal', 3],
    ['気が置けない', 'ki ga okenai', 'não é preciso pôr o ânimo', 'Com quem se pode relaxar totalmente.', 'De confiança total', 'Frequentemente mal-entendida até por nativos: o sentido é positivo.', '気が置けない友人と過ごした。', 'Passei o tempo com amigos de total confiança.', 'formal', 2],
    ['板挟みになる', 'itabasami ni naru', 'ficar prensado entre tábuas', 'Ficar entre dois lados que se opõem.', 'Estar entre a cruz e a espada', '', '上司と部下の板挟みになる。', 'Fico entre a cruz e a espada, entre chefe e equipe.', 'neutral', 3],
    ['泥を塗る', 'doro wo nuru', 'passar lama', 'Manchar a reputação de alguém.', 'Sujar o nome', '', '会社の顔に泥を塗った。', 'Sujou o nome da empresa.', 'formal', 3],
    ['肩を持つ', 'kata wo motsu', 'segurar o ombro', 'Tomar o partido de alguém.', 'Puxar a sardinha para o lado de alguém', '', 'なぜ彼の肩を持つの？', 'Por que você fica do lado dele?', 'informal', 3],
    ['水に流す', 'mizu ni nagasu', 'deixar correr na água', 'Esquecer uma desavença passada.', 'Deixar para lá', '', 'その件は水に流そう。', 'Vamos deixar aquele assunto para lá.', 'neutral', 3],
  ],
  C1: [
    ['棚に上げる', 'tana ni ageru', 'pôr na prateleira', 'Ignorar o próprio defeito ao criticar o alheio.', 'Ver o cisco no olho alheio', '', '自分のことは棚に上げて批判する。', 'Critica os outros ignorando os próprios defeitos.', 'neutral', 3],
    ['縁の下の力持ち', 'en no shita no chikaramochi', 'o forte debaixo do assoalho', 'Quem sustenta tudo sem aparecer.', 'Herói anônimo', 'A viga sob o assoalho, invisível e essencial.', '彼は縁の下の力持ちだ。', 'Ele é o herói anônimo do time.', 'formal', 3],
    ['二の足を踏む', 'ni no ashi wo fumu', 'pisar o segundo pé no lugar', 'Hesitar diante do passo decisivo.', 'Pisar em ovos', '', '価格を見て二の足を踏んだ。', 'Vi o preço e hesitei.', 'formal', 3],
    ['覆水盆に返らず', 'fukusui bon ni kaerazu', 'a água derramada não volta à bacia', 'O que foi feito não se desfaz.', 'Água derramada não se recolhe', 'De uma história chinesa sobre Jiang Ziya e sua esposa.', '覆水盆に返らず、前を向こう。', 'O que passou, passou: vamos em frente.', 'formal', 2],
    ['井の中の蛙大海を知らず', 'i no naka no kawazu taikai wo shirazu', 'a rã do poço não conhece o oceano', 'Quem só viu o próprio meio julga que ele é tudo.', 'Sapo de poço', 'Do Zhuangzi chinês.', '井の中の蛙大海を知らず、外を見よう。', 'Não sejamos sapos de poço: vamos olhar para fora.', 'formal', 2],
    ['急がば回れ', 'isogaba maware', 'se tem pressa, dê a volta', 'O caminho seguro é mais rápido que o atalho.', 'Devagar se vai ao longe', '', '急がば回れ、確認してから進もう。', 'Devagar se vai ao longe: vamos conferir antes.', 'formal', 3],
    ['情けは人の為ならず', 'nasake wa hito no tame narazu', 'a compaixão não é só pelo outro', 'A bondade acaba voltando para quem a pratica.', 'Faça o bem sem olhar a quem', 'Muito confundida até por nativos com "ajudar estraga o outro".', '情けは人の為ならずと言うからね。', 'Como se diz, o bem que se faz sempre volta.', 'formal', 2],
    ['弘法にも筆の誤り', 'koubou ni mo fude no ayamari', 'até Kōbō erra o pincel', 'Até o maior mestre comete deslizes.', 'Até o melhor escorrega', 'Kōbō Daishi, o mais célebre calígrafo do Japão.', '弘法にも筆の誤り、誰でも間違える。', 'Até o mestre erra; qualquer um erra.', 'formal', 2],
    ['骨折り損のくたびれ儲け', 'honeorizon no kutabiremouke', 'prejuízo de osso quebrado, lucro de cansaço', 'Esforço enorme que não rendeu nada.', 'Trabalho perdido', '', '結局、骨折り損のくたびれ儲けだった。', 'No fim, foi trabalho perdido.', 'formal', 2],
    ['背に腹は代えられぬ', 'se ni hara wa kaerarenu', 'não se troca a barriga pelas costas', 'Diante do essencial, sacrifica-se o resto.', 'Antes perder o anel que o dedo', '', '背に腹は代えられぬ、支店を閉じる。', 'Antes perder o anel que o dedo: vamos fechar a filial.', 'formal', 2],
    ['藪から棒', 'yabu kara bou', 'um bastão saindo do mato', 'De supetão, sem qualquer preparação.', 'Do nada', '', '藪から棒に何の話？', 'Do nada, que conversa é essa?', 'informal', 3],
    ['白羽の矢が立つ', 'shiraha no ya ga tatsu', 'a flecha de plumas brancas se finca', 'Ser escolhido entre todos para uma missão.', 'Ser o escolhido', 'De lendas em que a flecha marcava a casa do sacrifício.', '新事業の責任者として白羽の矢が立った。', 'Foi o escolhido para chefiar o novo negócio.', 'formal', 2],
    ['一目置く', 'ichimoku oku', 'colocar uma pedra de vantagem', 'Reconhecer a superioridade de alguém.', 'Reconhecer o valor de alguém', 'Do go: o jogador mais fraco começa com uma pedra a mais.', '同業者も彼には一目置く。', 'Até os concorrentes reconhecem o valor dele.', 'formal', 3],
    ['太鼓判を押す', 'taikoban wo osu', 'carimbar com o selo do tambor', 'Garantir a qualidade de algo sem reservas.', 'Botar a mão no fogo', '', '品質には太鼓判を押す。', 'Boto a mão no fogo pela qualidade.', 'formal', 2],
    ['折り紙付き', 'origamitsuki', 'com certificado dobrado', 'De qualidade comprovada e atestada.', 'Com selo de garantia', 'Do certificado dobrado que acompanhava obras de arte.', '彼の腕は折り紙付きだ。', 'A competência dele tem selo de garantia.', 'formal', 2],
    ['釘を刺す', 'kugi wo sasu', 'cravar um prego', 'Avisar antes para que não haja deslize.', 'Deixar avisado', '', '遅刻しないよう釘を刺した。', 'Deixei avisado para não se atrasar.', 'neutral', 3],
    ['腰を据える', 'koshi wo sueru', 'assentar o quadril', 'Instalar-se para um trabalho longo e sério.', 'Sentar e encarar', '', '腰を据えて取り組む。', 'Vou sentar e encarar de verdade.', 'formal', 3],
    ['舵を切る', 'kaji wo kiru', 'girar o leme', 'Mudar o rumo estratégico.', 'Mudar o rumo', 'Da navegação.', '会社は海外へ舵を切った。', 'A empresa mudou o rumo para o exterior.', 'formal', 3],
    ['水を差す', 'mizu wo sasu', 'derramar água', 'Estragar o clima ou o entusiasmo.', 'Jogar um balde de água fria', '', 'いい雰囲気に水を差したくない。', 'Não quero jogar água fria no clima bom.', 'neutral', 3],
    ['一線を画す', 'issen wo kakusu', 'traçar uma linha', 'Marcar uma diferença clara em relação a algo.', 'Marcar distância', '', '他社とは一線を画す品質だ。', 'É uma qualidade que marca distância das concorrentes.', 'formal', 3],
    ['手綱を締める', 'tazuna wo shimeru', 'apertar as rédeas', 'Endurecer o controle.', 'Apertar as rédeas', 'Da equitação.', '現場の手綱を締める必要がある。', 'É preciso apertar as rédeas na operação.', 'formal', 2],
    ['尻に火が付く', 'shiri ni hi ga tsuku', 'o traseiro pega fogo', 'O prazo apertar a ponto de forçar a ação.', 'Estar com a corda no pescoço', '', '締切前で尻に火が付いた。', 'Com o prazo chegando, estou com a corda no pescoço.', 'informal', 3],
    ['一枚岩', 'ichimaiiwa', 'uma única rocha', 'Grupo perfeitamente unido.', 'Bloco monolítico', '', '党内は一枚岩ではない。', 'O partido não é um bloco monolítico.', 'formal', 2],
    ['風向きが変わる', 'kazamuki ga kawaru', 'a direção do vento muda', 'A situação vira a favor ou contra.', 'O vento virou', '', '交渉の風向きが変わった。', 'O vento da negociação virou.', 'formal', 3],
    ['目星をつける', 'meboshi wo tsukeru', 'marcar a estrela do olho', 'Ter uma hipótese ou alvo provável.', 'Ter um palpite', '', '原因に目星をつけた。', 'Já tenho um palpite sobre a causa.', 'formal', 2],
  ],
  C2: [
    ['他山の石', 'tazan no ishi', 'a pedra da outra montanha', 'O erro alheio serve de lição para você.', 'Aprender no erro dos outros', 'Do Livro das Odes chinês.', 'この失敗を他山の石としたい。', 'Quero aprender com esse erro alheio.', 'formal', 2],
    ['塞翁が馬', 'saiou ga uma', 'o cavalo do velho da fronteira', 'Não se sabe se a sorte é boa ou má até o fim.', 'Há males que vêm para bem', 'Parábola chinesa do Huainanzi.', '人間万事塞翁が馬だ。', 'Na vida, nunca se sabe o que é sorte ou azar.', 'formal', 2],
    ['言わぬが花', 'iwanu ga hana', 'não dizer é a flor', 'Certas coisas ficam melhores não ditas.', 'O silêncio é de ouro', '', 'それは言わぬが花だろう。', 'Isso é melhor não dizer.', 'formal', 2],
    ['蛇足', 'dasoku', 'pés de cobra', 'Acréscimo desnecessário que estraga o conjunto.', 'Sobra que atrapalha', 'De uma disputa chinesa em que o vencedor pintou pés na cobra e perdeu.', 'この段落は蛇足だ。', 'Esse parágrafo é sobra que atrapalha.', 'formal', 2],
    ['五十歩百歩', 'gojippo hyappo', 'cinquenta passos, cem passos', 'Diferença que não é diferença nenhuma.', 'Farinha do mesmo saco', 'De Mêncio: o soldado que fugiu cinquenta passos zomba do que fugiu cem.', 'どちらも五十歩百歩だ。', 'Os dois são farinha do mesmo saco.', 'formal', 2],
    ['呉越同舟', 'goetsu doushuu', 'Wu e Yue no mesmo barco', 'Inimigos obrigados a cooperar pela circunstância.', 'Inimigos no mesmo barco', 'De Sun Tzu, sobre dois reinos rivais.', '今回は呉越同舟で進める。', 'Desta vez seguimos como inimigos no mesmo barco.', 'formal', 2],
    ['画竜点睛を欠く', 'garyou tensei wo kaku', 'falta pintar a pupila do dragão', 'Falta o toque final que dá vida à obra.', 'Falta o toque final', 'Do pintor chinês cujo dragão voou quando ganhou pupilas.', 'この企画は画竜点睛を欠く。', 'Falta o toque final a esse projeto.', 'formal', 2],
    ['羊頭狗肉', 'youtou kuniku', 'cabeça de carneiro, carne de cachorro', 'Anunciar uma coisa e entregar outra pior.', 'Propaganda enganosa', 'Da China antiga: a placa mostrava carneiro, vendia-se cão.', 'あの広告は羊頭狗肉だった。', 'Aquela propaganda era enganosa.', 'formal', 2],
    ['温故知新', 'onko chishin', 'aquecer o velho, conhecer o novo', 'Estudar o passado para entender o presente.', 'Aprender com o passado', 'De Confúcio.', '温故知新の姿勢で資料を読む。', 'Leio os documentos aprendendo com o passado.', 'formal', 2],
    ['臥薪嘗胆', 'gashin shoutan', 'deitar em lenha, provar fel', 'Suportar sofrimento longo por um objetivo.', 'Sofrer calado pelo objetivo', 'Do rei Goujian, que dormia sobre lenha para não esquecer a derrota.', '臥薪嘗胆の十年だった。', 'Foram dez anos de sacrifício calado.', 'formal', 2],
    ['四面楚歌', 'shimen soka', 'canções de Chu nos quatro lados', 'Estar cercado de inimigos, sem nenhum aliado.', 'Cercado por todos os lados', 'Do cerco final ao general Xiang Yu.', '彼は社内で四面楚歌だ。', 'Ele está cercado por todos os lados na empresa.', 'formal', 2],
    ['杞憂', 'kiyuu', 'a preocupação do homem de Qi', 'Preocupação com algo que jamais vai acontecer.', 'Preocupação à toa', 'Do homem de Qi que temia que o céu caísse.', 'それは杞憂に終わった。', 'Aquilo acabou sendo preocupação à toa.', 'formal', 2],
    ['朝三暮四', 'chousan boshi', 'três de manhã, quatro à noite', 'Enganar alguém trocando a forma sem mudar o total.', 'Trocar seis por meia dúzia', 'Do tratador que enganou os macacos com a mesma ração.', 'その提案は朝三暮四にすぎない。', 'Aquela proposta é trocar seis por meia dúzia.', 'formal', 2],
    ['虎の威を借る狐', 'tora no i wo karu kitsune', 'a raposa que toma emprestada a força do tigre', 'Quem se impõe com a autoridade de outro.', 'Quem manda com poder emprestado', 'Fábula chinesa das Estratégias dos Reinos Combatentes.', '彼は虎の威を借る狐だ。', 'Ele manda com poder emprestado.', 'formal', 2],
    ['木を見て森を見ず', 'ki wo mite mori wo mizu', 'ver a árvore e não ver a floresta', 'Perder-se no detalhe e não ver o conjunto.', 'Ver a árvore e não a floresta', '', '木を見て森を見ずにならないように。', 'Cuidado para não ver só a árvore e perder a floresta.', 'formal', 3],
    ['玉石混淆', 'gyokuseki konkou', 'joias e pedras misturadas', 'Bom e ruim misturados sem distinção.', 'Tudo no mesmo balaio', '', 'ネットの情報は玉石混淆だ。', 'A informação na internet vem tudo no mesmo balaio.', 'formal', 2],
    ['換骨奪胎', 'kankotsu dattai', 'trocar os ossos, tomar o útero', 'Reaproveitar a obra alheia dando forma nova.', 'Reinventar a partir do alheio', 'Da crítica literária chinesa.', '古典を換骨奪胎した作品だ。', 'É uma obra que reinventa o clássico.', 'formal', 2],
    ['泣いて馬謖を斬る', 'naite bashoku wo kiru', 'chorar e executar Ma Su', 'Punir quem se ama para preservar a regra.', 'Sem equivalente direto', 'De Zhuge Liang, que executou seu general preferido.', '泣いて馬謖を斬る決断だった。', 'Foi uma decisão dolorosa em nome da regra.', 'formal', 2],
    ['背水の陣', 'haisui no jin', 'formação de costas para a água', 'Colocar-se numa situação sem retirada possível.', 'Queimar as pontes atrás de si', 'Da tática do general Han Xin.', '背水の陣で臨む。', 'Vou encarar sem possibilidade de recuo.', 'formal', 2],
    ['捲土重来', 'kendo chourai', 'levantar poeira e voltar', 'Voltar com força total depois da derrota.', 'Voltar por cima', '', '捲土重来を期す。', 'Pretendo voltar por cima.', 'formal', 2],
    ['面従腹背', 'menjuu fukuhai', 'obedecer na cara, trair na barriga', 'Concordar na frente e sabotar por trás.', 'Sorrir na frente, morder por trás', '', '組織に面従腹背が広がっている。', 'Espalhou-se na organização o hábito de concordar e sabotar.', 'formal', 2],
    ['一石を投じる', 'isseki wo toujiru', 'lançar uma pedra', 'Provocar um debate com uma intervenção.', 'Jogar uma pedra no lago', '', 'その論文は業界に一石を投じた。', 'Aquele artigo jogou uma pedra no lago do setor.', 'formal', 2],
    ['枚挙にいとまがない', 'maikyo ni itoma ga nai', 'não há tempo para enumerar', 'São exemplos demais para listar.', 'Não dá nem para contar', '', '例は枚挙にいとまがない。', 'Os exemplos não dá nem para contar.', 'formal', 2],
    ['破竹の勢い', 'hachiku no ikioi', 'o ímpeto do bambu partido', 'Avanço que nada consegue deter.', 'A todo vapor', 'Uma vez rachado, o bambu se abre inteiro.', '破竹の勢いで市場を広げた。', 'Ampliou o mercado a todo vapor.', 'formal', 2],
    ['不倶戴天', 'fugutaiten', 'não dividir o mesmo céu', 'Inimizade absoluta e irreconciliável.', 'Inimigo mortal', 'Do Livro dos Ritos chinês.', '両社は不倶戴天の関係だ。', 'As duas empresas são inimigas mortais.', 'formal', 2],
  ],
};
