/**
 * Coreano — expressões por nível.
 *
 * Nenhuma expressão aqui repete o lote curado de `idioms.ts`. Toda entrada
 * traz romanização revisada: sem ela, o aluno não consegue pronunciar o que
 * está estudando.
 */

import type { ByLevel } from './entry';

export const KO: ByLevel = {
  A2: [
    ['수고하셨습니다', 'sugohasyeotseumnida', 'o senhor se esforçou', 'Agradecimento formal pelo trabalho de alguém.', 'Obrigado pelo trabalho', 'Dito ao fim do expediente ou de uma tarefa conjunta.', '오늘도 수고하셨습니다.', 'Obrigado pelo trabalho de hoje também.', 'formal', 5],
    ['괜찮아요', 'gwaenchanayo', 'está tudo bem', 'Está tudo bem; não precisa.', 'Tudo bem', '', '괜찮아요, 걱정하지 마세요.', 'Tudo bem, não se preocupe.', 'neutral', 5],
    ['어쩔 수 없다', 'eojjeol su eopda', 'não há o que fazer', 'Não tem jeito.', 'Fazer o quê', '', '비가 와서 어쩔 수 없어요.', 'Está chovendo, não tem jeito.', 'neutral', 5],
    ['오랜만이야', 'oraenmaniya', 'faz muito tempo', 'Quanto tempo!', 'Quanto tempo', '', '오랜만이야, 잘 지냈어?', 'Quanto tempo! Como você está?', 'informal', 5],
    ['잘 부탁드립니다', 'jal butakdeurimnida', 'peço que cuide bem', 'Fórmula de apresentação e pedido de colaboração.', 'Conto com você', '', '앞으로 잘 부탁드립니다.', 'Daqui em diante, conto com o senhor.', 'formal', 5],
    ['맛있게 드세요', 'masitge deuseyo', 'coma saborosamente', 'Bom apetite.', 'Bom apetite', '', '맛있게 드세요!', 'Bom apetite!', 'neutral', 4],
    ['잘 먹겠습니다', 'jal meokgetseumnida', 'vou comer bem', 'Dito antes de comer, agradecendo.', 'Sem equivalente direto', '', '잘 먹겠습니다!', 'Obrigado pela comida!', 'neutral', 5],
    ['잘 먹었습니다', 'jal meogeotseumnida', 'comi bem', 'Dito ao terminar a refeição.', 'Sem equivalente direto', '', '잘 먹었습니다, 정말 맛있었어요.', 'Obrigado pela refeição, estava ótima.', 'neutral', 5],
    ['다녀오겠습니다', 'danyeoogetseumnida', 'vou e volto', 'Dito ao sair de casa.', 'Já volto', '', '다녀오겠습니다!', 'Estou saindo!', 'neutral', 4],
    ['다녀왔습니다', 'danyeowatseumnida', 'fui e voltei', 'Cheguei — dito ao voltar para casa.', 'Cheguei', '', '다녀왔습니다, 늦었어요.', 'Cheguei, me atrasei.', 'neutral', 4],
    ['안녕히 계세요', 'annyeonghi gyeseyo', 'fique em paz', 'Tchau, dito por quem vai embora.', 'Até logo', 'A escolha entre 계세요 e 가세요 depende de quem sai.', '안녕히 계세요, 내일 봬요.', 'Até logo, vejo o senhor amanhã.', 'formal', 5],
    ['안녕히 가세요', 'annyeonghi gaseyo', 'vá em paz', 'Tchau, dito a quem vai embora.', 'Até logo', '', '안녕히 가세요, 조심히 가세요.', 'Até logo, vá com cuidado.', 'formal', 5],
    ['천만에요', 'cheonmaneyo', 'dez milhões de vezes não', 'De nada.', 'De nada', '', '고마워요. — 천만에요.', 'Obrigado. — De nada.', 'formal', 4],
    ['물론이죠', 'mulloniyo', 'é claro', 'Claro que sim.', 'Claro', '', '물론이죠, 도와드릴게요.', 'Claro, eu ajudo.', 'neutral', 4],
    ['잠깐만요', 'jamkkanmanyo', 'só um instante', 'Espera um pouquinho.', 'Só um minuto', '', '잠깐만요, 확인해 볼게요.', 'Só um minuto, vou verificar.', 'neutral', 5],
    ['조심하세요', 'josimhaseyo', 'tenha cuidado', 'Cuidado; se cuide.', 'Se cuida', '', '길이 미끄러우니 조심하세요.', 'A rua está escorregadia, cuidado.', 'neutral', 5],
    ['별말씀을요', 'byeolmalsseumeuryo', 'que palavras estranhas', 'Imagina; não foi nada.', 'Imagina', '', '별말씀을요, 당연한 일인데요.', 'Imagina, era o mínimo.', 'formal', 3],
    ['그럼요', 'geureomyo', 'pois então', 'Claro; sem dúvida.', 'Claro', '', '그럼요, 가능합니다.', 'Claro, é possível.', 'neutral', 4],
    ['아무래도', 'amuraedo', 'de qualquer modo', 'Parece que; de todo jeito.', 'Pelo jeito', '', '아무래도 오늘은 어려울 것 같아요.', 'Pelo jeito hoje vai ser difícil.', 'neutral', 4],
    ['혹시', 'hoksi', 'por acaso', 'Por acaso; será que.', 'Por acaso', 'Abre pedidos educados sem soar invasivo.', '혹시 시간 있으세요?', 'Por acaso o senhor tem tempo?', 'neutral', 5],
    ['진짜', 'jinjja', 'de verdade', 'Sério; de verdade.', 'Sério', '', '진짜 맛있어요!', 'É sério, está delicioso!', 'informal', 5],
    ['대박', 'daebak', 'grande jarro', 'Que incrível; sucesso enorme.', 'Arrasou', 'Originalmente "grande fortuna"; virou interjeição juvenil.', '대박, 진짜 붙었어?', 'Que incrível, você passou mesmo?', 'informal', 4],
    ['글쎄요', 'geulsseyo', 'pois é', 'Não sei bem; hesitação educada.', 'Sei lá', 'Serve de recusa suave sem dizer não.', '글쎄요, 생각해 볼게요.', 'Não sei bem, vou pensar.', 'neutral', 4],
    ['그냥', 'geunyang', 'simplesmente', 'Sem motivo especial; assim mesmo.', 'Sem mais', '', '왜 왔어? — 그냥.', 'Por que você veio? — Sem motivo.', 'informal', 5],
    ['어서 오세요', 'eoseo oseyo', 'venha depressa', 'Bem-vindo — saudação de loja.', 'Seja bem-vindo', '', '어서 오세요, 몇 분이세요?', 'Bem-vindos, quantas pessoas?', 'neutral', 5],
  ],
  B1: [
    ['눈치가 빠르다', 'nunchiga ppareuda', 'a percepção é rápida', 'Captar rápido o clima e a intenção alheia.', 'Ser esperto socialmente', '눈치 é competência social central na Coreia.', '그 친구는 눈치가 빠르다.', 'Aquele amigo capta tudo rápido.', 'neutral', 4],
    ['손이 크다', 'soni keuda', 'a mão é grande', 'Ser generoso, servir e dar em excesso.', 'Ter a mão aberta', '', '어머니는 손이 크세요.', 'Minha mãe tem a mão bem aberta.', 'informal', 3],
    ['속이 타다', 'sogi tada', 'o interior queima', 'Estar aflito por dentro.', 'Estar com o coração na mão', '', '연락이 없어서 속이 탄다.', 'Sem notícia, estou com o coração na mão.', 'informal', 3],
    ['입이 무겁다', 'ibi mugeopda', 'a boca é pesada', 'Ser discreto, guardar segredo.', 'Ser um túmulo', '', '그 사람은 입이 무겁다.', 'Aquela pessoa é um túmulo.', 'neutral', 3],
    ['입이 가볍다', 'ibi gabyeopda', 'a boca é leve', 'Não segurar segredo.', 'Ter a língua solta', '', '입이 가벼운 사람에게는 말하지 마.', 'Não conte a quem tem a língua solta.', 'informal', 3],
    ['귀가 얇다', 'gwiga yalpda', 'a orelha é fina', 'Acreditar em tudo que ouve.', 'Ser influenciável', '', '그는 귀가 얇아서 쉽게 속는다.', 'Ele é influenciável e cai fácil.', 'informal', 3],
    ['발이 묶이다', 'bari mukkida', 'os pés ficam amarrados', 'Ficar impedido de sair ou avançar.', 'Ficar preso', '', '폭설로 공항에 발이 묶였다.', 'Fiquei preso no aeroporto pela nevasca.', 'neutral', 3],
    ['낯이 익다', 'nachi ikda', 'o rosto é familiar', 'Achar alguém conhecido de algum lugar.', 'Ter cara de conhecido', '', '어디서 봤는지 낯이 익어요.', 'Tenho a impressão de já ter visto essa pessoa.', 'neutral', 3],
    ['마음이 놓이다', 'maeumi noida', 'o coração se assenta', 'Sentir alívio.', 'Ficar aliviado', '', '무사하다니 마음이 놓인다.', 'Fico aliviado de saber que está bem.', 'neutral', 4],
    ['정신이 없다', 'jeongsini eopda', 'não há espírito', 'Estar atarefado a ponto de não pensar direito.', 'Estar a mil', '', '요즘 정신이 없어요.', 'Ando a mil ultimamente.', 'informal', 4],
    ['한숨 돌리다', 'hansum dollida', 'devolver um suspiro', 'Dar uma pausa para respirar.', 'Dar um respiro', '', '이제야 한숨 돌렸다.', 'Só agora consegui respirar.', 'informal', 3],
    ['애를 쓰다', 'aereul sseuda', 'gastar as entranhas', 'Esforçar-se muito.', 'Se esforçar bastante', '', '많이 애를 쓰셨네요.', 'O senhor se esforçou bastante.', 'neutral', 4],
    ['눈에 띄다', 'nune ttuida', 'saltar aos olhos', 'Chamar atenção; destacar-se.', 'Saltar aos olhos', '', '그 색이 눈에 띈다.', 'Aquela cor salta aos olhos.', 'neutral', 4],
    ['시간 가는 줄 모르다', 'sigan ganeun jul moreuda', 'não perceber o tempo indo', 'Perder a noção do tempo.', 'Perder a noção do tempo', '', '이야기하다 보니 시간 가는 줄 몰랐다.', 'Conversando, perdi a noção do tempo.', 'neutral', 3],
    ['마음에 들다', 'maeume deulda', 'entrar no coração', 'Agradar; gostar de algo.', 'Cair no gosto', '', '이 옷이 마음에 들어요.', 'Gostei desta roupa.', 'neutral', 5],
    ['김이 새다', 'gimi saeda', 'o vapor escapa', 'Perder a graça ou o entusiasmo.', 'Perder a graça', 'Do vapor que escapa da panela e estraga o cozimento.', '결말을 알아서 김이 샜다.', 'Soube do final e perdeu a graça.', 'informal', 3],
    ['얼굴이 두껍다', 'eolguri dukkeopda', 'o rosto é grosso', 'Não ter vergonha na cara.', 'Ter a cara de pau', '', '얼굴이 두꺼운 사람이다.', 'É uma pessoa de cara de pau.', 'informal', 3],
    ['목이 빠지게 기다리다', 'mogi ppajige gidarida', 'esperar até o pescoço cair', 'Esperar ansiosamente por muito tempo.', 'Esperar até não aguentar', '', '연락을 목이 빠지게 기다렸다.', 'Esperei o contato até não aguentar mais.', 'informal', 3],
    ['발 벗고 나서다', 'bal beotgo naseoda', 'sair descalço', 'Ajudar de corpo e alma, sem reservas.', 'Entrar de cabeça para ajudar', '', '동네일에 발 벗고 나섰다.', 'Entrou de cabeça para ajudar o bairro.', 'neutral', 3],
    ['골치가 아프다', 'golchiga apeuda', 'o miolo dói', 'Ser um problema que dá dor de cabeça.', 'Dar dor de cabeça', '', '이 문제는 정말 골치가 아프다.', 'Esse problema dá muita dor de cabeça.', 'informal', 4],
    ['진땀을 흘리다', 'jinttameul heullida', 'derramar suor grosso', 'Suar frio numa situação difícil.', 'Suar frio', '', '면접에서 진땀을 흘렸다.', 'Suei frio na entrevista.', 'informal', 3],
    ['손발이 맞다', 'sonbari matda', 'mãos e pés combinam', 'Trabalhar em perfeita sintonia.', 'Estar entrosado', '', '우리는 손발이 잘 맞는다.', 'A gente é bem entrosado.', 'neutral', 3],
    ['어깨가 무겁다', 'eokkaega mugeopda', 'os ombros são pesados', 'Sentir o peso da responsabilidade.', 'Carregar um peso nas costas', '', '책임이 커서 어깨가 무겁다.', 'A responsabilidade é grande e pesa nas costas.', 'formal', 3],
    ['코가 높다', 'koga nopda', 'o nariz é alto', 'Ser orgulhoso e exigente.', 'Ser nariz empinado', '', '그 사람은 코가 높다.', 'Aquela pessoa é nariz empinado.', 'informal', 3],
    ['물 만난 고기', 'mul mannan gogi', 'peixe que encontrou água', 'Alguém no ambiente onde brilha.', 'Peixe na água', '', '무대에서는 물 만난 고기 같다.', 'No palco ele é peixe na água.', 'informal', 3],
  ],
  B2: [
    ['바가지를 쓰다', 'bagajireul sseuda', 'usar a cabaça', 'Pagar muito mais do que a coisa vale.', 'Levar uma facada', 'De um antigo jogo de azar com cabaças.', '관광지에서 바가지를 썼다.', 'Levei uma facada no ponto turístico.', 'informal', 4],
    ['눈코 뜰 새 없다', 'nunko tteul sae eopda', 'sem tempo de abrir olhos e nariz', 'Estar ocupadíssimo.', 'Não ter tempo nem de respirar', '', '요즘 눈코 뜰 새 없이 바쁘다.', 'Ando sem tempo nem de respirar.', 'informal', 4],
    ['손을 씻다', 'soneul ssitda', 'lavar as mãos', 'Abandonar de vez uma atividade ilícita.', 'Lavar as mãos', '', '그는 그 일에서 손을 씻었다.', 'Ele lavou as mãos daquele ramo.', 'neutral', 3],
    ['발등에 불이 떨어지다', 'baldeunge buri tteoreojida', 'o fogo cai no peito do pé', 'O prazo apertar de vez.', 'Estar com a corda no pescoço', '', '발등에 불이 떨어져서야 시작했다.', 'Só comecei com a corda no pescoço.', 'informal', 3],
    ['미역국을 먹다', 'miyeokgugeul meokda', 'comer sopa de alga', 'Ser reprovado num exame.', 'Rodar na prova', 'A alga é escorregadia — mau presságio para quem vai prestar prova.', '시험에서 미역국을 먹었다.', 'Rodei na prova.', 'informal', 3],
    ['국수를 먹다', 'guksureul meokda', 'comer macarrão', 'Casar — pelo prato servido nos casamentos.', 'Subir ao altar', '', '언제 국수를 먹여 줄 거야?', 'Quando você vai casar?', 'informal', 3],
    ['뒷북을 치다', 'dwitbugeul chida', 'bater o tambor atrasado', 'Reagir quando já não adianta.', 'Chegar atrasado na notícia', '', '이제 와서 뒷북을 치네.', 'Agora é que você vem reagir, tarde demais.', 'informal', 3],
    ['시치미를 떼다', 'sichimireul tteda', 'arrancar a etiqueta do falcão', 'Fingir que não sabe de nada.', 'Fazer-se de desentendido', 'Da falcoaria: retirar a plaqueta de identificação da ave.', '알면서 시치미를 뗀다.', 'Sabe de tudo e se faz de desentendido.', 'neutral', 3],
    ['하늘의 별 따기', 'haneurui byeol ttagi', 'colher estrela do céu', 'Algo praticamente impossível de conseguir.', 'Tirar leite de pedra', '', '그 자리는 하늘의 별 따기다.', 'Aquela vaga é tirar leite de pedra.', 'neutral', 3],
    ['도토리 키 재기', 'dotori ki jaegi', 'medir a altura de bolotas', 'Comparar coisas igualmente insignificantes.', 'Farinha do mesmo saco', '', '둘 다 도토리 키 재기다.', 'Os dois são farinha do mesmo saco.', 'informal', 3],
    ['누워서 떡 먹기', 'nuwoseo tteok meokgi', 'comer bolinho deitado', 'Muito fácil de fazer.', 'Mamão com açúcar', '', '그 정도는 누워서 떡 먹기야.', 'Isso é mamão com açúcar.', 'informal', 3],
    ['티끌 모아 태산', 'tikkeul moa taesan', 'juntando poeira, uma montanha', 'Pouquinho a pouquinho se junta muito.', 'De grão em grão a galinha enche o papo', '', '티끌 모아 태산이라고 하잖아.', 'De grão em grão a galinha enche o papo.', 'neutral', 3],
    ['가재는 게 편', 'gajaeneun ge pyeon', 'o lagostim fica do lado do caranguejo', 'Semelhante defende semelhante.', 'Farinha do mesmo saco se protege', '', '가재는 게 편이라더니.', 'Como se diz, um puxa a brasa para o outro.', 'informal', 3],
    ['밑 빠진 독에 물 붓기', 'mit ppajin doge mul butgi', 'derramar água em pote sem fundo', 'Esforço que nunca preenche nada.', 'Enxugar gelo', '', '이건 밑 빠진 독에 물 붓기다.', 'Isso é enxugar gelo.', 'neutral', 3],
    ['소문난 잔치에 먹을 것 없다', 'somunnan janchie meogeul geot eopda', 'na festa famosa não há o que comer', 'O que tem muita fama entrega pouco.', 'Muito barulho por nada', '', '소문난 잔치에 먹을 것 없더라.', 'Muita fama e pouca entrega.', 'neutral', 2],
    ['발 없는 말이 천 리 간다', 'bal eomneun mari cheon ri ganda', 'palavra sem pés anda mil li', 'Boato viaja depressa e longe.', 'Notícia ruim corre rápido', 'Trocadilho: 말 é tanto "palavra" quanto "cavalo".', '발 없는 말이 천 리 간다고 하잖아.', 'Como se diz, boato corre rápido.', 'neutral', 3],
    ['아는 게 병', 'aneun ge byeong', 'saber é doença', 'Às vezes saber demais só traz aflição.', 'A ignorância é uma bênção', '', '아는 게 병이라더니 정말이네.', 'Saber demais só traz aflição mesmo.', 'neutral', 2],
    ['등을 돌리다', 'deungeul dollida', 'virar as costas', 'Romper com alguém, retirar o apoio.', 'Virar as costas', '', '지지자들이 등을 돌렸다.', 'Os apoiadores viraram as costas.', 'formal', 3],
    ['코가 납작해지다', 'koga napjakaejida', 'o nariz fica achatado', 'Ter o orgulho derrubado.', 'Levar uma lição de humildade', '', '결과를 보고 코가 납작해졌다.', 'Vendo o resultado, levou uma lição de humildade.', 'informal', 3],
    ['입에 침이 마르다', 'ibe chimi mareuda', 'a saliva seca na boca', 'Elogiar sem parar.', 'Não parar de elogiar', '', '입에 침이 마르게 칭찬한다.', 'Ele elogia sem parar.', 'informal', 3],
    ['파리 날리다', 'pari nallida', 'espantar moscas', 'Estabelecimento vazio, sem clientes.', 'Sem mover uma mosca', '', '요즘 가게가 파리 날린다.', 'A loja anda vazia.', 'informal', 3],
    ['찬물을 끼얹다', 'chanmureul kkieonda', 'jogar água fria', 'Estragar o clima ou o ânimo.', 'Jogar um balde de água fria', '', '분위기에 찬물을 끼얹었다.', 'Jogou um balde de água fria no clima.', 'neutral', 3],
    ['뚜껑이 열리다', 'ttukkeongi yeollida', 'a tampa abre', 'Explodir de raiva.', 'Perder a cabeça', '', '그 말을 듣고 뚜껑이 열렸다.', 'Ouvi aquilo e perdi a cabeça.', 'informal', 3],
    ['김칫국부터 마시다', 'gimchitgukbuteo masida', 'beber o caldo do kimchi antes', 'Comemorar antes de a coisa acontecer.', 'Contar com o ovo dentro da galinha', 'O caldo acompanha o bolinho que ainda nem chegou.', '김칫국부터 마시지 마.', 'Não conte com o ovo dentro da galinha.', 'informal', 3],
    ['손에 땀을 쥐다', 'sone ttameul jwida', 'segurar suor na mão', 'Assistir a algo com muita tensão.', 'De roer as unhas', '', '손에 땀을 쥐는 경기였다.', 'Foi um jogo de roer as unhas.', 'neutral', 3],
  ],
  C1: [
    ['우물 안 개구리', 'umul an gaeguri', 'a rã dentro do poço', 'Quem só conhece o próprio meio e o julga o mundo.', 'Sapo de poço', 'Do Zhuangzi chinês.', '우물 안 개구리가 되지 말자.', 'Não vamos virar sapos de poço.', 'formal', 3],
    ['배가 아프다', 'baega apeuda', 'a barriga dói', 'Sentir inveja do sucesso alheio.', 'Ficar com inveja', 'Ditado: "quando o primo compra terra, a barriga dói".', '친구가 잘되니 배가 아프다.', 'O amigo se deu bem e deu inveja.', 'informal', 3],
    ['등잔 밑이 어둡다', 'deungjan michi eodupda', 'sob a lamparina é escuro', 'O que está mais perto é o que não se enxerga.', 'O escuro fica embaixo da lâmpada', '', '등잔 밑이 어둡다고, 답은 여기 있었다.', 'O escuro fica embaixo da lâmpada: a resposta estava aqui.', 'formal', 3],
    ['소 잃고 외양간 고친다', 'so ilko oeyanggan gochinda', 'consertar o estábulo depois de perder o boi', 'Tomar providência tarde demais.', 'Trancar o cofre depois do roubo', '', '소 잃고 외양간 고치는 격이다.', 'É trancar o cofre depois do roubo.', 'formal', 3],
    ['개구리 올챙이 적 생각 못한다', 'gaeguri olchaengi jeok saenggak motanda', 'a rã não lembra de quando era girino', 'Esquecer as próprias origens humildes.', 'Esquecer de onde veio', '', '개구리 올챙이 적 생각 못한다더니.', 'Esqueceu de onde veio.', 'informal', 3],
    ['원숭이도 나무에서 떨어진다', 'wonsungido namueseo tteoreojinda', 'até o macaco cai da árvore', 'Até o especialista erra.', 'Até o macaco cai da árvore', '', '원숭이도 나무에서 떨어진다잖아.', 'Até o macaco cai da árvore.', 'neutral', 3],
    ['낫 놓고 기역 자도 모른다', 'nat noko giyeok jado moreunda', 'com a foice à frente, não sabe a letra ㄱ', 'Ser completamente analfabeto no assunto.', 'Não saber o beabá', 'A foice tem exatamente o formato da letra ㄱ.', '낫 놓고 기역 자도 모르는 수준이다.', 'Não sabe nem o beabá do assunto.', 'informal', 2],
    ['백지장도 맞들면 낫다', 'baekjijangdo matdeulmyeon natda', 'até uma folha de papel é melhor erguer a dois', 'Qualquer tarefa fica melhor com ajuda.', 'Duas cabeças pensam melhor que uma', '', '백지장도 맞들면 낫다고 하잖아.', 'Duas cabeças pensam melhor que uma.', 'neutral', 3],
    ['고래 싸움에 새우 등 터진다', 'gorae ssaume saeu deung teojinda', 'na briga de baleias, as costas do camarão estouram', 'O fraco é quem paga a briga dos poderosos.', 'Briga de cachorro grande', '', '고래 싸움에 새우 등 터지는 격이다.', 'É briga de cachorro grande e quem paga é o pequeno.', 'formal', 3],
    ['호랑이도 제 말 하면 온다', 'horangido je mal hamyeon onda', 'até o tigre aparece quando falam dele', 'Falou da pessoa, ela chega.', 'Falando no diabo', '', '호랑이도 제 말 하면 온다더니!', 'Falando no diabo, ele apareceu!', 'informal', 3],
    ['세 살 버릇 여든까지 간다', 'se sal beoreut yeodeunkkaji ganda', 'o hábito dos três anos vai até os oitenta', 'O que se aprende cedo dura a vida toda.', 'Pau que nasce torto morre torto', '', '세 살 버릇 여든까지 간다더라.', 'Pau que nasce torto morre torto.', 'neutral', 3],
    ['가는 말이 고와야 오는 말이 곱다', 'ganeun mari gowaya oneun mari gopda', 'a palavra que vai bonita faz voltar bonita', 'O tratamento que você dá é o que recebe.', 'Cada um colhe o que planta', '', '가는 말이 고와야 오는 말이 곱다.', 'O tratamento que você dá é o que volta.', 'neutral', 3],
    ['남의 떡이 커 보인다', 'namui tteogi keo boinda', 'o bolinho do outro parece maior', 'O que é dos outros sempre parece melhor.', 'A grama do vizinho é mais verde', '', '남의 떡이 커 보이는 법이다.', 'A grama do vizinho sempre parece mais verde.', 'neutral', 3],
    ['열 번 찍어 안 넘어가는 나무 없다', 'yeol beon jjigeo an neomeoganeun namu eopda', 'não há árvore que resista a dez machadadas', 'A insistência acaba vencendo.', 'Água mole em pedra dura', '', '열 번 찍어 안 넘어가는 나무 없다잖아.', 'Água mole em pedra dura tanto bate até que fura.', 'neutral', 3],
    ['서당 개 삼 년이면 풍월을 읊는다', 'seodang gae sam nyeonimyeon pungworeul eumneunda', 'o cão da escola recita poesia em três anos', 'A convivência prolongada ensina sozinha.', 'Quem com ferro fere', '', '서당 개 삼 년이면 풍월을 읊는다고 하죠.', 'A convivência acaba ensinando.', 'formal', 2],
    ['우물을 파도 한 우물을 파라', 'umureul pado han umureul para', 'se for cavar poço, cave um só', 'Concentre o esforço em uma coisa só.', 'Quem muito quer, nada tem', '', '우물을 파도 한 우물을 파라는 말이 있다.', 'Diz-se: cave um poço só.', 'formal', 2],
    ['하늘이 무너져도 솟아날 구멍이 있다', 'haneuri muneojyeodo sosanal gumeongi itda', 'mesmo se o céu cair, há um buraco por onde sair', 'Sempre há uma saída, por pior que pareça.', 'Deus aperta mas não sufoca', '', '하늘이 무너져도 솟아날 구멍이 있다.', 'Deus aperta mas não sufoca.', 'neutral', 3],
    ['되로 주고 말로 받는다', 'doero jugo mallo batneunda', 'dar uma medida pequena e receber uma grande', 'O pequeno mal que se faz volta multiplicado.', 'Colher tempestade', 'Do e 말 eram medidas de grão de tamanhos muito diferentes.', '되로 주고 말로 받은 셈이다.', 'Fez pouco mal e colheu tempestade.', 'formal', 2],
    ['빈 수레가 요란하다', 'bin surega yoranhada', 'a carroça vazia faz mais barulho', 'Quem menos sabe é quem mais fala.', 'Quem sabe menos fala mais alto', '', '빈 수레가 요란하다더니.', 'Quem menos sabe é quem mais fala.', 'neutral', 3],
    ['뛰는 놈 위에 나는 놈 있다', 'ttwineun nom wie naneun nom itda', 'acima de quem corre há quem voa', 'Sempre existe alguém melhor.', 'Sempre tem um melhor', '', '뛰는 놈 위에 나는 놈 있다.', 'Sempre existe alguém melhor.', 'informal', 3],
    ['급할수록 돌아가라', 'geuphalsurok doraga', 'quanto mais pressa, mais dê a volta', 'O caminho seguro é mais rápido que o atalho.', 'Devagar se vai ao longe', '', '급할수록 돌아가라는 말이 맞다.', 'Devagar se vai ao longe.', 'formal', 3],
    ['시작이 반이다', 'sijagi banida', 'começar já é a metade', 'O mais difícil é começar.', 'Começar já é meio caminho andado', '', '시작이 반이다, 일단 해 보자.', 'Começar já é meio caminho: vamos tentar.', 'neutral', 4],
    ['첫술에 배부르랴', 'cheotsure baebureurya', 'a primeira colherada já enche a barriga?', 'Não se espera resultado logo na primeira tentativa.', 'Ninguém nasce sabendo', '', '첫술에 배부르랴, 천천히 하자.', 'Ninguém acerta de primeira, vamos devagar.', 'formal', 2],
    ['윗물이 맑아야 아랫물이 맑다', 'winmuri malgaya araetmuri makda', 'se a água de cima é limpa, a de baixo também', 'O exemplo vem de cima.', 'O exemplo vem de cima', '', '윗물이 맑아야 아랫물이 맑다.', 'O exemplo tem de vir de cima.', 'formal', 3],
    ['못 먹는 감 찔러나 본다', 'mot meokneun gam jjilleona bonda', 'espeta o caqui que não pode comer', 'Estragar o que não se pode ter.', 'Cachorro do hortelão', '', '못 먹는 감 찔러나 보는 심보다.', 'É o espírito do cachorro do hortelão.', 'informal', 2],
  ],
  C2: [
    ['새옹지마', 'saeongjima', 'o cavalo do velho da fronteira', 'Não se sabe se a sorte é boa ou má até o fim.', 'Há males que vêm para bem', 'Parábola chinesa do Huainanzi.', '인생은 새옹지마다.', 'A vida é assim: nunca se sabe.', 'formal', 3],
    ['어불성설', 'eobulseongseol', 'palavra que não forma discurso', 'Argumento que não se sustenta.', 'Não tem pé nem cabeça', '', '그 주장은 어불성설이다.', 'Aquela alegação não tem pé nem cabeça.', 'formal', 2],
    ['빙산의 일각', 'bingsanui ilgak', 'um canto do iceberg', 'A parte visível de um problema muito maior.', 'A ponta do iceberg', '', '이건 빙산의 일각에 불과하다.', 'Isso é só a ponta do iceberg.', 'formal', 3],
    ['희생양', 'huisaengyang', 'cordeiro do sacrifício', 'Quem leva a culpa de todos.', 'Bode expiatório', '', '그가 희생양이 되었다.', 'Ele virou o bode expiatório.', 'formal', 3],
    ['청출어람', 'cheongchuloeram', 'o azul nasce do índigo', 'O discípulo supera o mestre.', 'O aluno superou o professor', 'De Xunzi.', '청출어람이라는 말이 딱 맞다.', 'É o caso do aluno que superou o mestre.', 'formal', 2],
    ['괄목상대', 'gwalmoksangdae', 'esfregar os olhos e olhar de novo', 'Progresso tão grande que espanta.', 'Progredir de forma impressionante', 'Do Registro dos Três Reinos.', '실력이 괄목상대할 정도다.', 'A competência dele progrediu de forma impressionante.', 'formal', 2],
    ['대기만성', 'daegimanseong', 'o grande vaso demora a ficar pronto', 'Quem tem grande talento amadurece devagar.', 'Grande talento demora a florescer', 'Do Dao De Jing.', '대기만성형 선수다.', 'É um atleta que amadurece devagar.', 'formal', 2],
    ['사면초가', 'samyeonchoga', 'canções de Chu nos quatro lados', 'Estar cercado de adversários, sem aliado.', 'Cercado por todos os lados', 'Do cerco ao general Xiang Yu.', '지금은 사면초가 상황이다.', 'Agora estamos cercados por todos os lados.', 'formal', 2],
    ['오리무중', 'orimujung', 'no meio de cinco li de névoa', 'Situação totalmente obscura, sem pistas.', 'No escuro', '', '사건은 오리무중이다.', 'O caso está totalmente no escuro.', 'formal', 2],
    ['자가당착', 'jagadangchak', 'colidir consigo mesmo', 'Contradizer-se dentro do próprio argumento.', 'Se contradizer', '', '그 논리는 자가당착이다.', 'Aquela lógica se contradiz.', 'formal', 2],
    ['좌불안석', 'jwaburanseok', 'sentar sem assento tranquilo', 'Não conseguir ficar quieto de tanta inquietação.', 'Sentar em brasa', '', '결과를 기다리며 좌불안석이었다.', 'Esperei o resultado como quem senta em brasa.', 'formal', 2],
    ['촌철살인', 'choncheolsarin', 'matar com uma polegada de ferro', 'Frase curta que atinge em cheio.', 'Certeiro como uma flecha', '', '그의 지적은 촌철살인이었다.', 'A observação dele foi certeira.', 'formal', 2],
    ['견물생심', 'gyeonmulsaengsim', 'ver a coisa gera o desejo', 'A cobiça nasce de ver o objeto.', 'Os olhos comem primeiro', '', '견물생심이라 지갑을 열었다.', 'Vi e não resisti: abri a carteira.', 'formal', 2],
    ['결자해지', 'gyeoljahaeji', 'quem amarrou é quem desata', 'Quem criou o problema deve resolvê-lo.', 'Quem sujou que limpe', '', '결자해지의 자세가 필요하다.', 'É preciso que quem criou o problema o resolva.', 'formal', 2],
    ['과유불급', 'gwayubulgeup', 'o excesso é como a falta', 'Exagerar é tão ruim quanto faltar.', 'Tudo em excesso faz mal', 'De Confúcio.', '과유불급이니 적당히 하자.', 'Tudo em excesso faz mal: vamos com equilíbrio.', 'formal', 2],
    ['근묵자흑', 'geunmukjaheuk', 'quem se aproxima da tinta fica preto', 'A companhia influencia o caráter.', 'Diga-me com quem andas', '', '근묵자흑이라는 말을 기억해라.', 'Lembre: diga-me com quem andas.', 'formal', 2],
    ['낭중지추', 'nangjungjichu', 'a agulha dentro do saco', 'O talento acaba furando o pano e aparecendo.', 'Talento não se esconde', '', '낭중지추라 결국 알려졌다.', 'Talento não se esconde: acabou aparecendo.', 'formal', 2],
    ['다다익선', 'dadaikseon', 'quanto mais, melhor', 'Quanto maior a quantidade, melhor.', 'Quanto mais, melhor', 'Do general Han Xin, falando do próprio exército.', '자료는 다다익선이다.', 'Quanto mais material, melhor.', 'formal', 2],
    ['동병상련', 'dongbyeongsangnyeon', 'os doentes da mesma doença se compadecem', 'Quem sofre igual entende de verdade.', 'Quem já passou pelo mesmo entende', '', '동병상련의 마음으로 도왔다.', 'Ajudei por já ter passado pelo mesmo.', 'formal', 2],
    ['마이동풍', 'maidongpung', 'vento leste na orelha do cavalo', 'Conselho que entra por um ouvido e sai pelo outro.', 'Entrar por um ouvido e sair pelo outro', 'De um poema de Li Bai.', '아무리 말해도 마이동풍이다.', 'Por mais que eu fale, entra por um ouvido e sai pelo outro.', 'formal', 2],
    ['명불허전', 'myeongbulheojeon', 'a fama não é transmitida em vão', 'A reputação é merecida.', 'A fama é merecida', '', '명불허전이라는 말이 실감난다.', 'Dá para sentir que a fama é merecida.', 'formal', 2],
    ['배수의 진', 'baesuui jin', 'formação de costas para a água', 'Colocar-se numa posição sem retirada.', 'Queimar as pontes atrás de si', 'Da tática do general Han Xin.', '배수의 진을 치고 임했다.', 'Encarei sem possibilidade de recuo.', 'formal', 2],
    ['사필귀정', 'sapilgwijeong', 'tudo retorna ao correto', 'No fim, a justiça prevalece.', 'A justiça tarda mas não falha', '', '사필귀정이라 믿는다.', 'Acredito que a justiça tarda mas não falha.', 'formal', 2],
    ['아전인수', 'ajeoninsu', 'puxar a água para o próprio campo', 'Interpretar tudo em proveito próprio.', 'Puxar a sardinha para o seu lado', '', '아전인수식 해석이다.', 'É uma interpretação que puxa a sardinha para o próprio lado.', 'formal', 2],
    ['오월동주', 'owoldongju', 'Wu e Yue no mesmo barco', 'Rivais obrigados a cooperar.', 'Inimigos no mesmo barco', 'De Sun Tzu.', '오월동주의 상황이 되었다.', 'Viramos inimigos no mesmo barco.', 'formal', 2],
  ],
};
