/**
 * Mandarim — expressões por nível.
 *
 * Nenhuma expressão aqui repete o lote curado de `idioms.ts`. Toda entrada
 * traz pinyin: sem ele, o aluno vê um bloco de caracteres e não consegue nem
 * pronunciar o que está estudando.
 */

import type { ByLevel } from './entry';

export const ZH: ByLevel = {
  A2: [
    ['不好意思', 'bù hǎo yìsi', 'não é bom o sentido', 'Desculpe; que vergonha — para pedidos e deslizes leves.', 'Desculpa', 'Mais leve que 对不起: serve para incomodar alguém.', '不好意思，请问一下。', 'Com licença, uma pergunta.', 'neutral', 5],
    ['随便', 'suíbiàn', 'conforme a conveniência', 'Tanto faz; como preferir.', 'Tanto faz', '', '吃什么？— 随便。', 'O que a gente come? — Tanto faz.', 'informal', 5],
    ['好久不见', 'hǎo jiǔ bú jiàn', 'muito tempo sem ver', 'Quanto tempo!', 'Quanto tempo', 'Deu origem ao inglês "long time no see".', '好久不见，你好吗？', 'Quanto tempo! Como você está?', 'neutral', 5],
    ['没事', 'méi shì', 'não há assunto', 'Não foi nada; tudo bem.', 'Não foi nada', '', '没事，我来处理。', 'Não foi nada, eu resolvo.', 'informal', 5],
    ['太好了', 'tài hǎo le', 'bom demais', 'Que ótimo!', 'Que ótimo', '', '太好了，我们成功了！', 'Que ótimo, conseguimos!', 'informal', 5],
    ['差不多', 'chàbuduō', 'diferença não muita', 'Mais ou menos; quase igual.', 'Mais ou menos', '', '两个价格差不多。', 'Os dois preços são mais ou menos iguais.', 'neutral', 5],
    ['当然', 'dāngrán', 'evidentemente', 'Claro; naturalmente.', 'Claro', '', '当然可以。', 'Claro que pode.', 'neutral', 5],
    ['慢慢来', 'mànman lái', 'venha devagar', 'Vá com calma.', 'Vai com calma', '', '别急，慢慢来。', 'Sem pressa, vai com calma.', 'informal', 5],
    ['不客气', 'bú kèqi', 'não seja cerimonioso', 'De nada.', 'De nada', '', '谢谢！— 不客气。', 'Obrigado! — De nada.', 'neutral', 5],
    ['请问', 'qǐngwèn', 'peço para perguntar', 'Com licença, posso perguntar?', 'Por favor, uma pergunta', '', '请问，地铁站在哪儿？', 'Com licença, onde fica o metrô?', 'neutral', 5],
    ['辛苦了', 'xīnkǔ le', 'foi trabalhoso', 'Obrigado pelo esforço.', 'Valeu pelo trabalho', '', '大家辛苦了。', 'Obrigado pelo esforço de todos.', 'neutral', 5],
    ['一会儿见', 'yíhuìr jiàn', 'ver daqui a pouco', 'Até daqui a pouco.', 'Até já', '', '一会儿见，我先走了。', 'Até já, vou indo.', 'informal', 4],
    ['有点儿', 'yǒudiǎnr', 'tem um pouco', 'Um pouco — quase sempre para algo negativo.', 'Meio', 'Diferente de 一点儿, que vem depois do adjetivo.', '今天有点儿冷。', 'Hoje está meio frio.', 'neutral', 5],
    ['真的吗', 'zhēn de ma', 'é verdade?', 'Sério? — pedido de confirmação.', 'Sério mesmo', '', '真的吗？我不敢相信。', 'Sério? Não acredito.', 'informal', 5],
    ['算了', 'suàn le', 'já contou', 'Deixa pra lá.', 'Deixa pra lá', '', '算了，别说了。', 'Deixa pra lá, para de falar.', 'informal', 5],
    ['看情况', 'kàn qíngkuàng', 'olhar a situação', 'Depende das circunstâncias.', 'Depende', '', '去不去？— 看情况。', 'Você vai? — Depende.', 'neutral', 4],
    ['没问题', 'méi wèntí', 'não há problema', 'Sem problema.', 'Sem problema', '', '没问题，交给我。', 'Sem problema, deixa comigo.', 'neutral', 5],
    ['拜托', 'bàituō', 'confiar com reverência', 'Por favor, conto com você — ou "faça-me o favor".', 'Faz esse favor', 'O tom decide se é pedido sincero ou impaciência.', '拜托你帮我看一下。', 'Por favor, dá uma olhada para mim.', 'informal', 4],
    ['麻烦你了', 'máfan nǐ le', 'te dei trabalho', 'Desculpe o incômodo; obrigado pelo trabalho.', 'Desculpa o incômodo', '', '麻烦你了，谢谢。', 'Desculpa o incômodo, obrigado.', 'neutral', 4],
    ['说不定', 'shuōbudìng', 'não dá para dizer com certeza', 'Talvez; vai que.', 'Vai que', '', '说不定他已经到了。', 'Vai que ele já chegou.', 'informal', 4],
    ['好像', 'hǎoxiàng', 'parece semelhante', 'Parece que.', 'Parece que', '', '好像要下雨了。', 'Parece que vai chover.', 'neutral', 5],
    ['反正', 'fǎnzhèng', 'ao contrário e ao certo', 'De qualquer jeito; afinal.', 'De qualquer jeito', '', '反正我今天没事。', 'De qualquer jeito, hoje estou livre.', 'informal', 4],
    ['顺便', 'shùnbiàn', 'aproveitando a conveniência', 'De passagem; já que está indo.', 'Já que', '', '你出去顺便买牛奶。', 'Já que vai sair, compra leite.', 'neutral', 4],
    ['尽量', 'jǐnliàng', 'até o limite da medida', 'Fazer o máximo possível.', 'Dentro do possível', '', '我尽量早点到。', 'Vou chegar cedo dentro do possível.', 'neutral', 4],
    ['特别', 'tèbié', 'especialmente distinto', 'Especialmente; muito.', 'Especialmente', '', '今天特别忙。', 'Hoje estou especialmente ocupado.', 'neutral', 5],
  ],
  B1: [
    ['面子', 'miànzi', 'a face', 'A honra social de alguém diante do grupo.', 'A imagem que se tem perante os outros', 'Conceito central: fazer alguém perder 面子 em público é uma ofensa séria.', '要给他留点面子。', 'É preciso preservar um pouco a imagem dele.', 'neutral', 5],
    ['走后门', 'zǒu hòumén', 'entrar pela porta dos fundos', 'Conseguir algo por contato pessoal, fora das regras.', 'Entrar pela porta dos fundos', '', '他是走后门进去的。', 'Ele entrou pela porta dos fundos.', 'informal', 4],
    ['吃苦', 'chīkǔ', 'comer amargura', 'Aguentar dificuldade sem reclamar.', 'Ralar', 'Suportar sofrimento é valor cultural explícito.', '年轻时要能吃苦。', 'Quando jovem é preciso saber ralar.', 'neutral', 4],
    ['吃醋', 'chīcù', 'comer vinagre', 'Sentir ciúme.', 'Ter ciúme', 'De uma anedota da corte Tang sobre uma esposa que preferiu beber veneno — que era vinagre.', '他有点吃醋了。', 'Ele ficou meio com ciúme.', 'informal', 4],
    ['拍马屁', 'pāi mǎpì', 'dar tapinha na garupa do cavalo', 'Bajular quem tem poder.', 'Puxar o saco', 'Da estepe: elogiar o cavalo do chefe era elogiar o chefe.', '别拍马屁了。', 'Pare de puxar o saco.', 'informal', 4],
    ['打交道', 'dǎ jiāodào', 'bater no cruzamento', 'Lidar com alguém regularmente.', 'Lidar com', '', '我常跟供应商打交道。', 'Eu lido com fornecedores com frequência.', 'neutral', 4],
    ['开夜车', 'kāi yèchē', 'dirigir o carro noturno', 'Virar a noite estudando ou trabalhando.', 'Virar a noite', '', '昨晚我开夜车写报告。', 'Ontem virei a noite escrevendo o relatório.', 'informal', 3],
    ['泼冷水', 'pō lěngshuǐ', 'jogar água fria', 'Desanimar alguém.', 'Jogar um balde de água fria', '', '别给他泼冷水。', 'Não jogue água fria nele.', 'informal', 3],
    ['大手大脚', 'dà shǒu dà jiǎo', 'mãos grandes, pés grandes', 'Gastar sem controle.', 'Ter a mão furada', '', '他花钱大手大脚。', 'Ele gasta sem controle.', 'informal', 3],
    ['铁公鸡', 'tiě gōngjī', 'galo de ferro', 'Pessoa muito avarenta.', 'Pão-duro', 'Um galo de ferro não solta nem uma pena.', '他是个铁公鸡。', 'Ele é um pão-duro.', 'informal', 3],
    ['露一手', 'lòu yìshǒu', 'mostrar uma mão', 'Exibir uma habilidade.', 'Mostrar do que é capaz', '', '今天我给你们露一手。', 'Hoje eu mostro do que sou capaz.', 'informal', 3],
    ['掉链子', 'diào liànzi', 'a corrente cair', 'Falhar bem na hora decisiva.', 'Falhar na hora H', 'Da corrente da bicicleta que sai no meio da subida.', '关键时刻别掉链子。', 'Na hora decisiva, não falhe.', 'informal', 3],
    ['抬杠', 'táigàng', 'levantar a vara', 'Discutir por discutir.', 'Discutir por esporte', '', '他就爱跟人抬杠。', 'Ele adora discutir por esporte.', 'informal', 3],
    ['没谱', 'méipǔ', 'sem partitura', 'Não ter ideia nem plano.', 'Não ter noção', 'Da música: tocar sem partitura.', '这件事我还没谱。', 'Nesse assunto ainda não tenho noção.', 'informal', 3],
    ['有两下子', 'yǒu liǎngxiàzi', 'ter dois golpes', 'Ter mesmo competência.', 'Ter talento de verdade', '', '你还真有两下子。', 'Você tem talento de verdade.', 'informal', 3],
    ['靠谱', 'kàopǔ', 'apoiado na partitura', 'Confiável; que faz sentido.', 'Confiável', '', '这个方案挺靠谱。', 'Esse plano é bem confiável.', 'informal', 4],
    ['摸不着头脑', 'mō bu zháo tóunǎo', 'não consigo apalpar a cabeça', 'Não entender nada da situação.', 'Não entender bulhufas', '', '我完全摸不着头脑。', 'Não entendi bulhufas.', 'informal', 3],
    ['一言难尽', 'yì yán nán jìn', 'uma palavra não esgota', 'É uma longa história.', 'É uma longa história', '', '这事一言难尽。', 'Essa história é longa.', 'neutral', 3],
    ['心里有数', 'xīnlǐ yǒu shù', 'ter o número no coração', 'Saber exatamente como as coisas estão.', 'Saber bem o que está fazendo', '', '你放心，我心里有数。', 'Fica tranquilo, eu sei bem o que estou fazendo.', 'neutral', 4],
    ['一头雾水', 'yì tóu wù shuǐ', 'a cabeça inteira em névoa', 'Ficar completamente confuso.', 'Boiando', '', '听完我一头雾水。', 'Depois de ouvir, fiquei boiando.', 'informal', 3],
    ['打退堂鼓', 'dǎ tuìtánggǔ', 'bater o tambor de retirada', 'Recuar antes de terminar.', 'Dar para trás', 'Do tambor que anunciava o fim da audiência no tribunal imperial.', '他中途打退堂鼓了。', 'Ele deu para trás no meio do caminho.', 'neutral', 3],
    ['唱反调', 'chàng fǎndiào', 'cantar na tonalidade oposta', 'Contrariar sistematicamente.', 'Ir na contramão', '', '他总是唱反调。', 'Ele sempre vai na contramão.', 'neutral', 3],
    ['碰钉子', 'pèng dīngzi', 'esbarrar num prego', 'Levar uma recusa seca.', 'Levar um não na cara', '', '我去申请，结果碰钉子了。', 'Fui pedir e acabei levando um não na cara.', 'informal', 3],
    ['吃闭门羹', 'chī bìmén gēng', 'comer a sopa da porta fechada', 'Chegar e encontrar a porta fechada.', 'Levar um pé na porta', 'De uma cortesã Tang que servia sopa a quem não queria receber.', '我们去了，结果吃闭门羹。', 'Fomos até lá e levamos um pé na porta.', 'informal', 2],
    ['抢手', 'qiǎngshǒu', 'arrancar da mão', 'Muito disputado, que vende num instante.', 'Disputadíssimo', '', '这款手机很抢手。', 'Esse celular é disputadíssimo.', 'neutral', 3],
  ],
  B2: [
    ['对牛弹琴', 'duì niú tán qín', 'tocar cítara para o boi', 'Falar algo refinado a quem não pode entender.', 'Falar com a parede', 'Do filósofo Gongming Yi, que tocou para um boi.', '跟他讲这些是对牛弹琴。', 'Falar isso com ele é falar com a parede.', 'neutral', 3],
    ['说曹操曹操到', 'shuō Cáo Cāo Cáo Cāo dào', 'fala de Cao Cao e Cao Cao chega', 'Falou da pessoa, ela apareceu.', 'Falando no diabo', 'Do Romance dos Três Reinos.', '说曹操曹操到，他来了！', 'Falando no diabo, ele chegou!', 'informal', 3],
    ['隔墙有耳', 'gé qiáng yǒu ěr', 'atrás do muro há ouvidos', 'Cuidado, alguém pode estar ouvindo.', 'As paredes têm ouvidos', '', '小声点，隔墙有耳。', 'Fala baixo, as paredes têm ouvidos.', 'neutral', 3],
    ['三心二意', 'sān xīn èr yì', 'três corações, duas intenções', 'Fazer as coisas sem se decidir nem se concentrar.', 'Fazer de qualquer jeito, sem foco', '', '别三心二意的。', 'Não fique sem foco assim.', 'neutral', 3],
    ['半斤八两', 'bàn jīn bā liǎng', 'meio jin e oito liang', 'Os dois são exatamente iguais.', 'Farinha do mesmo saco', 'Na balança antiga, meio jin equivalia a oito liang.', '两家公司半斤八两。', 'As duas empresas são farinha do mesmo saco.', 'informal', 3],
    ['无风不起浪', 'wú fēng bù qǐ làng', 'sem vento não há onda', 'Todo boato tem alguma base.', 'Onde há fumaça há fogo', '', '无风不起浪，一定有原因。', 'Onde há fumaça há fogo: deve ter um motivo.', 'neutral', 3],
    ['一箭双雕', 'yí jiàn shuāng diāo', 'uma flecha, duas águias', 'Resolver duas coisas de uma só vez.', 'Matar dois coelhos com uma cajadada', 'De um arqueiro da dinastia Sui que acertou duas águias.', '这样做一箭双雕。', 'Fazendo assim, matamos dois coelhos.', 'formal', 3],
    ['打草惊蛇', 'dǎ cǎo jīng shé', 'bater no capim e espantar a cobra', 'Agir cedo demais e alertar o adversário.', 'Dar bandeira', '', '别打草惊蛇，先观察。', 'Não dê bandeira, observe primeiro.', 'formal', 3],
    ['顺其自然', 'shùn qí zìrán', 'seguir o próprio natural', 'Deixar as coisas seguirem seu curso.', 'Deixar rolar', 'Do pensamento taoista.', '别强求，顺其自然吧。', 'Não force, deixa rolar.', 'neutral', 4],
    ['各有千秋', 'gè yǒu qiān qiū', 'cada um tem mil outonos', 'Cada um tem seus próprios méritos.', 'Cada um tem seu valor', '', '两个方案各有千秋。', 'Os dois planos têm seus próprios méritos.', 'formal', 3],
    ['名副其实', 'míng fù qí shí', 'o nome corresponde à realidade', 'A fama corresponde ao que a coisa é.', 'Faz jus ao nome', '', '他是名副其实的专家。', 'Ele é um especialista que faz jus ao nome.', 'formal', 3],
    ['得寸进尺', 'dé cùn jìn chǐ', 'ganhar uma polegada e avançar um pé', 'Receber uma concessão e exigir mais.', 'Dar a mão e querer o braço', '', '他总是得寸进尺。', 'Você dá a mão e ele quer o braço.', 'neutral', 3],
    ['自作自受', 'zì zuò zì shòu', 'fez sozinho, sofre sozinho', 'Colher o que se plantou.', 'Colher o que plantou', '', '这是自作自受。', 'Ele está colhendo o que plantou.', 'neutral', 3],
    ['一分耕耘一分收获', 'yì fēn gēngyún yì fēn shōuhuò', 'uma parte de lavoura, uma parte de colheita', 'A colheita é proporcional ao trabalho.', 'Quem planta colhe', '', '一分耕耘一分收获，别急。', 'Quem planta colhe: sem pressa.', 'formal', 3],
    ['火上浇油', 'huǒ shàng jiāo yóu', 'derramar óleo no fogo', 'Agravar o conflito.', 'Botar lenha na fogueira', '', '这句话是火上浇油。', 'Essa frase é botar lenha na fogueira.', 'neutral', 3],
    ['雪上加霜', 'xuě shàng jiā shuāng', 'geada sobre a neve', 'Desgraça nova sobre desgraça antiga.', 'Desgraça pouca é bobagem', '', '这次罚款真是雪上加霜。', 'Essa multa foi desgraça sobre desgraça.', 'formal', 3],
    ['事半功倍', 'shì bàn gōng bèi', 'metade do trabalho, o dobro do efeito', 'Obter muito resultado com pouco esforço.', 'Render o dobro', 'De Mêncio.', '用对方法就能事半功倍。', 'Com o método certo, rende o dobro.', 'formal', 3],
    ['事倍功半', 'shì bèi gōng bàn', 'o dobro do trabalho, metade do efeito', 'Muito esforço para pouco resultado.', 'Muito esforço para pouco resultado', '', '方法不对就会事倍功半。', 'Com o método errado, muito esforço rende pouco.', 'formal', 3],
    ['举一反三', 'jǔ yī fǎn sān', 'levantar um e devolver três', 'Aprender um caso e deduzir os outros.', 'Puxar o resto pelo exemplo', 'De Confúcio, sobre o bom aluno.', '好学生能举一反三。', 'Um bom aluno deduz o resto pelo exemplo.', 'formal', 3],
    ['因小失大', 'yīn xiǎo shī dà', 'por causa do pequeno, perder o grande', 'Perder o essencial por prender-se ao detalhe.', 'Perder o filé pelo osso', '', '别因小失大。', 'Não perca o essencial por causa do detalhe.', 'formal', 3],
    ['熟能生巧', 'shú néng shēng qiǎo', 'a familiaridade gera a habilidade', 'A prática gera a destreza.', 'A prática leva à perfeição', '', '熟能生巧，多练习吧。', 'A prática leva à perfeição: pratique mais.', 'formal', 4],
    ['三思而后行', 'sān sī ér hòu xíng', 'pensar três vezes antes de agir', 'Refletir bem antes de decidir.', 'Pensar duas vezes', 'De Confúcio.', '这么大的事要三思而后行。', 'Uma coisa dessas exige pensar bem antes.', 'formal', 3],
    ['眼高手低', 'yǎn gāo shǒu dī', 'olho alto, mão baixa', 'Ter padrão exigente e execução fraca.', 'Falar bonito e fazer mal', '', '他有点眼高手低。', 'Ele fala bonito e executa mal.', 'neutral', 3],
    ['隔行如隔山', 'gé háng rú gé shān', 'mudar de ramo é como atravessar uma montanha', 'Cada profissão é um mundo à parte.', 'Cada macaco no seu galho', '', '隔行如隔山，我不懂医学。', 'Cada macaco no seu galho: não entendo de medicina.', 'neutral', 3],
    ['一手遮天', 'yì shǒu zhē tiān', 'com uma mão tapar o céu', 'Exercer poder absoluto e esconder tudo.', 'Mandar sozinho e abafar tudo', '', '在那家公司他一手遮天。', 'Naquela empresa ele manda sozinho e abafa tudo.', 'formal', 3],
  ],
  C1: [
    ['井底之蛙', 'jǐng dǐ zhī wā', 'a rã no fundo do poço', 'Quem só conhece o próprio meio e o toma pelo mundo.', 'Sapo de poço', 'Do Zhuangzi.', '别做井底之蛙。', 'Não seja um sapo de poço.', 'formal', 3],
    ['亡羊补牢', 'wáng yáng bǔ láo', 'consertar o curral depois de perder a ovelha', 'Corrigir depois do prejuízo — ainda vale a pena.', 'Antes tarde do que nunca', 'Das Estratégias dos Reinos Combatentes.', '亡羊补牢，为时未晚。', 'Antes tarde do que nunca.', 'formal', 3],
    ['临时抱佛脚', 'línshí bào fójiǎo', 'abraçar os pés de Buda na última hora', 'Estudar só na véspera.', 'Estudar na véspera', '', '他又在临时抱佛脚。', 'Ele está de novo estudando na véspera.', 'informal', 3],
    ['背黑锅', 'bēi hēiguō', 'carregar a panela preta', 'Levar a culpa de outro.', 'Pagar o pato', '', '这次我不想背黑锅。', 'Desta vez não quero pagar o pato.', 'informal', 3],
    ['骑虎难下', 'qí hǔ nán xià', 'montado no tigre, difícil descer', 'Estar num impasse em que parar é tão ruim quanto seguir.', 'Estar num beco sem saída', '', '现在骑虎难下了。', 'Agora estamos num beco sem saída.', 'formal', 3],
    ['车到山前必有路', 'chē dào shān qián bì yǒu lù', 'chegando o carro à montanha, haverá caminho', 'Na hora, aparece uma solução.', 'Na hora a gente dá um jeito', '', '别担心，车到山前必有路。', 'Não se preocupe, na hora a gente dá um jeito.', 'neutral', 3],
    ['一鸣惊人', 'yì míng jīng rén', 'um canto e espanta todos', 'Ficar em silêncio e então surpreender todo mundo.', 'Estourar de uma vez', 'Do rei Zhuang de Chu, que fingiu ociosidade por três anos.', '这部作品让他一鸣惊人。', 'Essa obra fez dele um nome da noite para o dia.', 'formal', 2],
    ['破釜沉舟', 'pò fǔ chén zhōu', 'quebrar os caldeirões e afundar os barcos', 'Eliminar toda possibilidade de recuo.', 'Queimar as pontes atrás de si', 'Do general Xiang Yu, em 207 a.C.', '我们破釜沉舟，只能成功。', 'Queimamos as pontes: só nos resta vencer.', 'formal', 2],
    ['胸有成竹', 'xiōng yǒu chéng zhú', 'ter o bambu pronto no peito', 'Ter o plano inteiro claro antes de começar.', 'Ter tudo na cabeça', 'Do pintor Wen Tong, que via o bambu pronto antes de pintar.', '他做事胸有成竹。', 'Ele age com tudo já claro na cabeça.', 'formal', 2],
    ['因材施教', 'yīn cái shī jiào', 'ensinar conforme o material', 'Adaptar o ensino a cada aluno.', 'Ensinar conforme o aluno', 'Princípio pedagógico de Confúcio.', '好老师懂得因材施教。', 'Um bom professor sabe ensinar conforme o aluno.', 'formal', 2],
    ['望梅止渴', 'wàng méi zhǐ kě', 'olhar ameixas para matar a sede', 'Consolar-se com o que é só imaginação.', 'Matar a fome com o cheiro', 'Cao Cao prometeu ameixas ao exército sedento.', '这只是望梅止渴。', 'Isso é só matar a fome com o cheiro.', 'formal', 2],
    ['守株待兔', 'shǒu zhū dài tù', 'guardar o toco esperando a lebre', 'Esperar que a sorte se repita sem fazer nada.', 'Esperar sentado', 'Do camponês de Han Fei que viu uma lebre morrer contra um toco.', '这样等于守株待兔。', 'Isso é o mesmo que esperar sentado.', 'formal', 2],
    ['刻舟求剑', 'kè zhōu qiú jiàn', 'marcar o barco para achar a espada', 'Aplicar método antigo a uma situação que mudou.', 'Insistir no método velho', 'Do homem que marcou a borda do barco onde a espada caiu.', '这种做法是刻舟求剑。', 'Esse jeito é insistir num método que já não serve.', 'formal', 2],
    ['掩耳盗铃', 'yǎn ěr dào líng', 'tapar os ouvidos para roubar o sino', 'Enganar apenas a si mesmo.', 'Enganar a si próprio', 'Do ladrão que tapou os próprios ouvidos ao roubar um sino.', '这是掩耳盗铃罢了。', 'Isso é apenas se enganar.', 'formal', 2],
    ['拔苗助长', 'bá miáo zhù zhǎng', 'puxar o broto para ajudá-lo a crescer', 'Forçar o processo e estragar tudo.', 'Forçar a barra e estragar', 'De Mêncio: o camponês que puxou os brotos e matou a plantação.', '这样training是拔苗助长。', 'Um treino assim é forçar a barra e estragar.', 'formal', 2],
    ['南辕北辙', 'nán yuán běi zhé', 'a carruagem para o sul, os sulcos para o norte', 'Agir na direção oposta ao próprio objetivo.', 'Fazer o contrário do que se quer', '', '这项政策南辕北辙。', 'Essa política vai na direção contrária ao objetivo.', 'formal', 2],
    ['班门弄斧', 'bān mén nòng fǔ', 'brandir o machado à porta de Lu Ban', 'Exibir-se diante de quem é muito melhor.', 'Ensinar o padre a rezar missa', 'Lu Ban é o mestre carpinteiro lendário.', '在您面前谈这个是班门弄斧。', 'Falar disso diante do senhor é ensinar o padre a rezar missa.', 'formal', 2],
    ['滥竽充数', 'làn yú chōng shù', 'flauta ruim para completar o número', 'Estar num grupo só para preencher vaga, sem competência.', 'Estar de enfeite', 'Do músico que fingia tocar numa orquestra de trezentos.', '我只是滥竽充数罢了。', 'Eu só estou ali de enfeite.', 'formal', 2],
    ['买椟还珠', 'mǎi dú huán zhū', 'comprar a caixa e devolver a pérola', 'Escolher o enfeite e descartar o que valia.', 'Ficar com a embalagem e jogar o presente', '', '这种选择是买椟还珠。', 'Essa escolha é ficar com a embalagem e jogar o presente.', 'formal', 2],
    ['邯郸学步', 'Hándān xué bù', 'aprender a andar em Handan', 'Imitar o outro e perder até o que já sabia.', 'Perder o próprio jeito imitando', 'Do jovem que foi imitar o andar elegante de Handan e esqueceu o seu.', '盲目模仿会邯郸学步。', 'Imitar cegamente faz perder o próprio jeito.', 'formal', 2],
    ['讳疾忌医', 'huì jí jì yī', 'esconder a doença e evitar o médico', 'Negar o problema até ele ficar incurável.', 'Esconder o problema até não ter cura', 'Do rei Huan de Cai e o médico Bian Que.', '讳疾忌医只会更糟。', 'Esconder o problema só piora.', 'formal', 2],
    ['曲突徙薪', 'qū tū xǐ xīn', 'entortar a chaminé e afastar a lenha', 'Prevenir o desastre antes que ele aconteça.', 'Melhor prevenir que remediar', '', '曲突徙薪胜过救火。', 'Prevenir vale mais que apagar incêndio.', 'formal', 2],
    ['三顾茅庐', 'sān gù máolú', 'três visitas à cabana de palha', 'Insistir com humildade para conquistar alguém.', 'Ir buscar de joelhos', 'Liu Bei visitou Zhuge Liang três vezes.', '公司三顾茅庐才请到他。', 'A empresa insistiu três vezes até contratá-lo.', 'formal', 2],
    ['后来居上', 'hòu lái jū shàng', 'quem chega depois fica por cima', 'O retardatário ultrapassa os pioneiros.', 'Chegar depois e passar na frente', '', '这家公司后来居上。', 'Essa empresa chegou depois e passou na frente.', 'formal', 2],
    ['水滴石穿', 'shuǐ dī shí chuān', 'a gota d’água fura a pedra', 'A persistência vence o obstáculo.', 'Água mole em pedra dura', '', '水滴石穿，坚持下去。', 'Água mole em pedra dura: continue.', 'formal', 3],
  ],
  C2: [
    ['塞翁失马', 'sài wēng shī mǎ', 'o velho da fronteira perdeu o cavalo', 'Não se sabe se a sorte é boa ou má até o fim.', 'Há males que vêm para bem', 'Parábola do Huainanzi.', '塞翁失马，焉知非福。', 'Há males que vêm para bem.', 'formal', 3],
    ['冰山一角', 'bīngshān yì jiǎo', 'um canto do iceberg', 'A parte visível de um problema muito maior.', 'A ponta do iceberg', '', '这只是冰山一角。', 'Isso é só a ponta do iceberg.', 'formal', 3],
    ['杯水车薪', 'bēi shuǐ chē xīn', 'um copo d’água para uma carroça de lenha em chamas', 'Recurso ridiculamente insuficiente.', 'Enxugar gelo', 'De Mêncio.', '这点预算是杯水车薪。', 'Esse orçamento é enxugar gelo.', 'formal', 2],
    ['言外之意', 'yán wài zhī yì', 'o sentido fora da palavra', 'O que ficou implícito na fala.', 'Nas entrelinhas', '', '他的言外之意很清楚。', 'O que ele disse nas entrelinhas está claro.', 'formal', 3],
    ['唇亡齿寒', 'chún wáng chǐ hán', 'sem lábios, os dentes sentem frio', 'A queda do vizinho expõe você em seguida.', 'Hoje ele, amanhã você', 'Do Comentário de Zuo.', '唇亡齿寒，我们必须帮忙。', 'Hoje ele, amanhã nós: temos de ajudar.', 'formal', 2],
    ['螳螂捕蝉', 'tángláng bǔ chán', 'o louva-a-deus caça a cigarra', 'Concentrado na presa, não vê o predador atrás.', 'Caçador virando caça', 'Completa-se com 黄雀在后: "e o pardal está atrás".', '螳螂捕蝉，黄雀在后。', 'O caçador vira caça sem perceber.', 'formal', 2],
    ['城门失火殃及池鱼', 'chéngmén shī huǒ yāng jí chí yú', 'o portão pega fogo e os peixes do fosso pagam', 'Quem nada tinha a ver acaba prejudicado.', 'Sobrar para quem não tem nada a ver', '', '城门失火殃及池鱼，我们也受影响。', 'Sobrou para quem não tinha nada a ver: nós também fomos afetados.', 'formal', 2],
    ['未雨绸缪', 'wèi yǔ chóumóu', 'reparar o telhado antes da chuva', 'Preparar-se antes de o problema chegar.', 'Melhor prevenir que remediar', 'Do Livro das Odes.', '公司应该未雨绸缪。', 'A empresa devia se preparar antes.', 'formal', 2],
    ['一叶障目', 'yí yè zhàng mù', 'uma folha tapa os olhos', 'Um detalhe impede de ver o conjunto.', 'Ver a árvore e não a floresta', 'Completa-se com 不见泰山: "e não se vê o monte Tai".', '一叶障目，不见泰山。', 'Um detalhe impede de ver o todo.', 'formal', 2],
    ['树大招风', 'shù dà zhāo fēng', 'árvore grande atrai vento', 'Quem cresce demais atrai ataques.', 'Quanto maior, mais alvo', '', '树大招风，低调一点。', 'Quanto maior, mais alvo: seja discreto.', 'formal', 2],
    ['覆水难收', 'fù shuǐ nán shōu', 'água derramada é difícil de recolher', 'O que foi feito não se desfaz.', 'Água derramada não se recolhe', '', '覆水难收，向前看吧。', 'O que passou, passou: olhe para a frente.', 'formal', 2],
    ['功亏一篑', 'gōng kuī yí kuì', 'a obra falha por um cesto de terra', 'Fracassar bem no último passo.', 'Perder no último minuto', 'Do Livro dos Documentos: o monte que faltou um cesto para terminar.', '别功亏一篑。', 'Não vá perder tudo no último passo.', 'formal', 2],
    ['削足适履', 'xuē zú shì lǚ', 'cortar o pé para caber no sapato', 'Distorcer o essencial para caber na forma.', 'Adaptar ao contrário', '', '这样改是削足适履。', 'Mudar assim é cortar o pé para caber no sapato.', 'formal', 2],
    ['杀鸡取卵', 'shā jī qǔ luǎn', 'matar a galinha para tirar os ovos', 'Destruir a fonte do próprio ganho.', 'Matar a galinha dos ovos de ouro', '', '涨价太多是杀鸡取卵。', 'Aumentar demais o preço é matar a galinha dos ovos de ouro.', 'formal', 3],
    ['舍本逐末', 'shě běn zhú mò', 'abandonar a raiz e perseguir a ponta', 'Cuidar do acessório e largar o essencial.', 'Cuidar do detalhe e largar o principal', '', '这是舍本逐末的做法。', 'Essa é uma forma de largar o principal pelo detalhe.', 'formal', 2],
    ['掉以轻心', 'diào yǐ qīng xīn', 'tratar com coração leve', 'Subestimar um risco.', 'Bobear', '', '这件事不能掉以轻心。', 'Nesse assunto não dá para bobear.', 'formal', 2],
    ['养虎为患', 'yǎng hǔ wéi huàn', 'criar um tigre e virar problema', 'Tolerar uma ameaça até que ela cresça.', 'Criar cobra no peito', '', '姑息就是养虎为患。', 'Ser leniente é criar cobra no peito.', 'formal', 2],
    ['众口铄金', 'zhòng kǒu shuò jīn', 'muitas bocas derretem o metal', 'A repetição coletiva impõe uma versão.', 'Mentira repetida vira verdade', '', '众口铄金，谣言很危险。', 'Mentira repetida vira verdade: boato é perigoso.', 'formal', 2],
    ['明修栈道暗度陈仓', 'míng xiū zhàndào àn dù Chéncāng', 'consertar a passarela à vista e cruzar Chencang às escondidas', 'Fingir um movimento para executar outro.', 'Fazer manobra de diversão', 'Da estratégia de Han Xin.', '这是明修栈道暗度陈仓。', 'Isso é uma manobra de diversão.', 'formal', 2],
    ['图穷匕见', 'tú qióng bǐ xiàn', 'desenrolado o mapa, aparece a adaga', 'A verdadeira intenção se revela no fim.', 'Cair a máscara', 'Do atentado de Jing Ke contra o rei de Qin.', '谈到最后图穷匕见。', 'No fim da conversa, caiu a máscara.', 'formal', 2],
    ['洛阳纸贵', 'Luòyáng zhǐ guì', 'o papel encareceu em Luoyang', 'Obra tão copiada que faltou papel na cidade.', 'Sucesso arrebatador', 'Da "Rapsódia das Três Capitais", de Zuo Si.', '这本书一时洛阳纸贵。', 'Aquele livro foi um sucesso arrebatador.', 'formal', 2],
    ['沧海一粟', 'cānghǎi yí sù', 'um grão de painço no mar', 'Algo minúsculo diante da imensidão.', 'Uma gota no oceano', 'De Su Shi.', '个人之力不过沧海一粟。', 'A força de um indivíduo é uma gota no oceano.', 'formal', 2],
    ['高山流水', 'gāo shān liú shuǐ', 'montanha alta, água corrente', 'Amizade entre quem se entende profundamente.', 'Alma gêmea', 'De Bo Ya e Zhong Ziqi, o músico e seu único ouvinte verdadeiro.', '他们是高山流水的知己。', 'Eles são almas gêmeas de verdade.', 'formal', 2],
    ['曲高和寡', 'qǔ gāo hè guǎ', 'melodia elevada, poucos acompanham', 'Obra refinada demais para ter público.', 'Erudito demais para o gosto geral', '', '这部电影曲高和寡。', 'Esse filme é refinado demais para o gosto geral.', 'formal', 2],
    ['大智若愚', 'dà zhì ruò yú', 'a grande sabedoria parece tolice', 'O verdadeiro sábio não se exibe.', 'Sábio que se faz de bobo', 'Do Dao De Jing.', '他大智若愚，别小看他。', 'Ele parece bobo mas é sábio; não o subestime.', 'formal', 2],
  ],
};
