/**
 * Catálogo de verbos por nível
 * =============================
 *
 * ## Por que verbo merece catálogo próprio
 *
 * Verbo não é "mais uma palavra". Numa frase, ele é a peça que carrega tempo,
 * pessoa, modo e — em metade dos idiomas daqui — regência. Um aluno que sabe
 * 500 substantivos e 20 verbos **não fala**; um que sabe 100 substantivos e
 * 80 verbos conversa. É por isso que este arquivo existe separado do
 * vocabulário geral e aparece em seção própria na apostila.
 *
 * ## O que cada verbete carrega, e por quê
 *
 *  - `infinitive` — a forma de dicionário.
 *  - `romanization` — obrigatória em ja/ko/zh: sem ela o aluno não consegue
 *    nem repetir o verbo em voz alta.
 *  - `meaning` — o sentido em português, com as acepções que importam.
 *  - `forms` — as três formas que mais aparecem na fala real. Não é a
 *    conjugação completa de propósito: uma tabela de 6 pessoas × 8 tempos é
 *    material de consulta, não de aprendizado, e afoga o iniciante. Aqui vão
 *    as formas que ele vai **usar hoje**.
 *  - `example` / `exampleTranslation` — o verbo em contexto. Verbo isolado não
 *    se fixa: o que a memória guarda é a frase.
 *  - `note` — a armadilha de uso, quando existe. É onde mora a diferença entre
 *    conhecer o verbo e usá-lo certo.
 *
 * ## Progressão
 *
 * Os verbos mudam a cada nível e nunca se repetem — há teste garantindo. A1
 * traz os auxiliares e os de altíssima frequência; C1/C2 trazem os de registro
 * formal e os que exigem escolha entre sinônimos próximos.
 */

import type { CefrLevel, LanguageCode } from '@/domain/types';

export type VerbEntry = {
  infinitive: string;
  romanization: string | null;
  meaning: string;
  /** Formas de uso mais frequente, rotuladas. */
  forms: { person: string; form: string }[];
  example: string;
  exampleTranslation: string;
  note: string | null;
};

/** Formato compacto: [infinitivo, romanização, sentido, formas, exemplo, tradução, nota] */
type Raw = [string, string, string, string, string, string, string];

/**
 * Expande `"eu:am|ele:is|passado:was"` na lista de formas.
 * Compacto porque é dado, não código — escrever objeto quadruplicaria o arquivo.
 */
function parseForms(spec: string): { person: string; form: string }[] {
  return spec
    .split('|')
    .filter(Boolean)
    .map((pair) => {
      const [person = '', form = ''] = pair.split(':');
      return { person: person.trim(), form: form.trim() };
    });
}

function expand(raw: Raw[]): VerbEntry[] {
  return raw.map(([infinitive, romanization, meaning, forms, example, translation, note]) => ({
    infinitive,
    romanization: romanization || null,
    meaning,
    forms: parseForms(forms),
    example,
    exampleTranslation: translation,
    note: note || null,
  }));
}

type VerbMap = Partial<Record<CefrLevel, Raw[]>>;

/* ================================================================== *
 * Inglês
 * ================================================================== */

const EN: VerbMap = {
  A1: [
    [
      'to be',
      '',
      'ser / estar',
      'eu:am|ele/ela:is|nós/eles:are|passado:was / were',
      'I am a student. She is tired.',
      'Eu sou estudante. Ela está cansada.',
      'Cobre "ser" e "estar" ao mesmo tempo — o contexto decide qual é.',
    ],
    [
      'to have',
      '',
      'ter / possuir',
      'eu:have|ele/ela:has|passado:had',
      'They have two children.',
      'Eles têm dois filhos.',
      'Não se usa para idade: "I am 25", nunca "I have 25".',
    ],
    [
      'to go',
      '',
      'ir',
      'eu:go|ele/ela:goes|passado:went|particípio:gone',
      'We go to the beach on Sundays.',
      'Vamos à praia aos domingos.',
      '"Go to" com lugar, mas "go home" sem preposição.',
    ],
    [
      'to do',
      '',
      'fazer',
      'eu:do|ele/ela:does|passado:did|particípio:done',
      'What do you do for work?',
      'O que você faz da vida?',
      'Também é o auxiliar de perguntas e negativas.',
    ],
    [
      'to want',
      '',
      'querer',
      'eu:want|ele/ela:wants|passado:wanted',
      'I want to learn English.',
      'Quero aprender inglês.',
      'Sempre seguido de infinitivo com "to".',
    ],
    [
      'to like',
      '',
      'gostar de',
      'eu:like|ele/ela:likes|passado:liked',
      'She likes cooking.',
      'Ela gosta de cozinhar.',
      'Sem preposição depois: "like coffee", não "like of coffee".',
    ],
    [
      'to need',
      '',
      'precisar de',
      'eu:need|ele/ela:needs|passado:needed',
      'I need help.',
      'Preciso de ajuda.',
      'Não leva preposição: "need help", não "need of help".',
    ],
    [
      'to speak',
      '',
      'falar',
      'eu:speak|ele/ela:speaks|passado:spoke|particípio:spoken',
      'Do you speak Portuguese?',
      'Você fala português?',
      '"Speak" para idiomas; "talk" para conversar com alguém.',
    ],
  ],
  A2: [
    [
      'to bring',
      '',
      'trazer',
      'presente:bring|passado:brought|particípio:brought',
      'Bring your documents tomorrow.',
      'Traga seus documentos amanhã.',
      '"Bring" é trazer para cá; "take" é levar para lá.',
    ],
    [
      'to leave',
      '',
      'sair / deixar',
      'presente:leave|passado:left|particípio:left',
      'I left my keys at home.',
      'Deixei minhas chaves em casa.',
      'Dois sentidos bem diferentes no mesmo verbo.',
    ],
    [
      'to buy',
      '',
      'comprar',
      'presente:buy|passado:bought|particípio:bought',
      'She bought a new phone.',
      'Ela comprou um celular novo.',
      '',
    ],
    [
      'to pay',
      '',
      'pagar',
      'presente:pay|passado:paid|particípio:paid',
      'I paid by card.',
      'Paguei com cartão.',
      'Paga-se "for" a coisa: "pay for the meal".',
    ],
    [
      'to wait',
      '',
      'esperar (aguardar)',
      'presente:wait|passado:waited',
      'We waited for an hour.',
      'Esperamos por uma hora.',
      'Sempre "wait for", nunca "wait" sozinho com objeto.',
    ],
    [
      'to feel',
      '',
      'sentir / sentir-se',
      'presente:feel|passado:felt|particípio:felt',
      'I feel much better today.',
      'Me sinto bem melhor hoje.',
      'Não leva pronome reflexivo: "I feel", não "I feel myself".',
    ],
    [
      'to happen',
      '',
      'acontecer',
      'presente:happens|passado:happened',
      'What happened yesterday?',
      'O que aconteceu ontem?',
      'Nunca tem sujeito pessoal.',
    ],
    [
      'to try',
      '',
      'tentar / experimentar',
      'presente:try|passado:tried|particípio:tried',
      'Try to arrive early.',
      'Tente chegar cedo.',
      '"Try to do" é tentar; "try doing" é experimentar.',
    ],
  ],
  B1: [
    [
      'to manage',
      '',
      'conseguir / administrar',
      'presente:manage|passado:managed',
      'She managed to finish on time.',
      'Ela conseguiu terminar a tempo.',
      '"Manage to" implica esforço e sucesso.',
    ],
    [
      'to afford',
      '',
      'ter condições de pagar',
      'presente:afford|passado:afforded',
      "I can't afford it right now.",
      'Não tenho condições agora.',
      'Quase sempre com "can" ou "could".',
    ],
    [
      'to suggest',
      '',
      'sugerir',
      'presente:suggest|passado:suggested',
      'He suggested meeting on Friday.',
      'Ele sugeriu nos encontrarmos na sexta.',
      'Seguido de gerúndio, não de infinitivo.',
    ],
    [
      'to avoid',
      '',
      'evitar',
      'presente:avoid|passado:avoided',
      'Avoid using long sentences.',
      'Evite usar frases longas.',
      'Sempre com gerúndio depois.',
    ],
    [
      'to complain',
      '',
      'reclamar',
      'presente:complain|passado:complained',
      'They complained about the noise.',
      'Eles reclamaram do barulho.',
      'Reclama-se "about" algo.',
    ],
    [
      'to realize',
      '',
      'perceber / dar-se conta',
      'presente:realize|passado:realized',
      'I realized I was wrong.',
      'Percebi que estava errado.',
      'Falso amigo: não é "realizar" no sentido de executar.',
    ],
    [
      'to expect',
      '',
      'esperar (prever)',
      'presente:expect|passado:expected',
      'We expect a reply by Friday.',
      'Esperamos resposta até sexta.',
      'Diferente de "wait": aqui é prever, não aguardar.',
    ],
    [
      'to improve',
      '',
      'melhorar',
      'presente:improve|passado:improved',
      'My writing improved a lot.',
      'Minha escrita melhorou muito.',
      'Serve como transitivo e intransitivo.',
    ],
  ],
  B2: [
    [
      'to acknowledge',
      '',
      'reconhecer / admitir',
      'presente:acknowledge|passado:acknowledged',
      'He acknowledged the mistake.',
      'Ele reconheceu o erro.',
      'Registro mais formal que "admit".',
    ],
    [
      'to undermine',
      '',
      'minar / enfraquecer',
      'presente:undermine|passado:undermined',
      'The delay undermined our credibility.',
      'O atraso minou nossa credibilidade.',
      '',
    ],
    [
      'to overlook',
      '',
      'deixar passar / ignorar',
      'presente:overlook|passado:overlooked',
      'We overlooked one detail.',
      'Deixamos passar um detalhe.',
      'Também significa "ter vista para".',
    ],
    [
      'to enhance',
      '',
      'aprimorar / realçar',
      'presente:enhance|passado:enhanced',
      'The changes enhanced performance.',
      'As mudanças aprimoraram o desempenho.',
      'Mais forte e mais formal que "improve".',
    ],
    [
      'to address',
      '',
      'abordar / tratar de',
      'presente:address|passado:addressed',
      'The report addresses three risks.',
      'O relatório aborda três riscos.',
      'Nada a ver com endereço, aqui.',
    ],
    [
      'to entail',
      '',
      'implicar / acarretar',
      'presente:entails|passado:entailed',
      'This entails extra costs.',
      'Isso acarreta custos extras.',
      '',
    ],
    [
      'to comply',
      '',
      'cumprir / estar em conformidade',
      'presente:comply|passado:complied',
      'We must comply with the rules.',
      'Precisamos cumprir as regras.',
      'Sempre "comply with".',
    ],
    [
      'to outweigh',
      '',
      'superar (em peso/importância)',
      'presente:outweigh|passado:outweighed',
      'The benefits outweigh the risks.',
      'Os benefícios superam os riscos.',
      '',
    ],
  ],
  C1: [
    [
      'to substantiate',
      '',
      'comprovar / fundamentar',
      'presente:substantiate|passado:substantiated',
      'He failed to substantiate the claim.',
      'Ele não conseguiu comprovar a alegação.',
      'Registro jurídico e acadêmico.',
    ],
    [
      'to reconcile',
      '',
      'conciliar',
      'presente:reconcile|passado:reconciled',
      'It is hard to reconcile both accounts.',
      'É difícil conciliar os dois relatos.',
      '',
    ],
    [
      'to preclude',
      '',
      'inviabilizar / impedir',
      'presente:precludes|passado:precluded',
      'Budget cuts preclude further testing.',
      'Cortes inviabilizam mais testes.',
      'Mais formal que "prevent".',
    ],
    [
      'to mitigate',
      '',
      'mitigar / atenuar',
      'presente:mitigate|passado:mitigated',
      'These measures mitigate the risk.',
      'Essas medidas mitigam o risco.',
      '',
    ],
    [
      'to prevail',
      '',
      'prevalecer',
      'presente:prevail|passado:prevailed',
      'Common sense eventually prevailed.',
      'O bom senso acabou prevalecendo.',
      '',
    ],
    [
      'to warrant',
      '',
      'justificar / merecer',
      'presente:warrants|passado:warranted',
      'The issue warrants further study.',
      'A questão merece mais estudo.',
      'Nada a ver com garantia, neste uso.',
    ],
    [
      'to underpin',
      '',
      'sustentar / embasar',
      'presente:underpins|passado:underpinned',
      'Three principles underpin the model.',
      'Três princípios sustentam o modelo.',
      '',
    ],
    [
      'to reconcile oneself',
      '',
      'conformar-se',
      'presente:reconcile myself|passado:reconciled myself',
      'She reconciled herself to the outcome.',
      'Ela se conformou com o resultado.',
      '',
    ],
  ],
  C2: [
    [
      'to belie',
      '',
      'desmentir / contradizer',
      'presente:belies|passado:belied',
      'His calm tone belied his anger.',
      'O tom calmo dele desmentia sua raiva.',
      'Sempre indica contradição entre aparência e realidade.',
    ],
    [
      'to equivocate',
      '',
      'usar de evasivas',
      'presente:equivocate|passado:equivocated',
      'The minister equivocated for an hour.',
      'O ministro usou de evasivas por uma hora.',
      '',
    ],
    [
      'to eschew',
      '',
      'evitar deliberadamente',
      'presente:eschew|passado:eschewed',
      'The author eschews jargon.',
      'O autor evita jargão.',
      'Registro literário; raro na fala.',
    ],
    [
      'to obviate',
      '',
      'tornar desnecessário',
      'presente:obviates|passado:obviated',
      'This obviates the need for a second review.',
      'Isso torna desnecessária uma segunda revisão.',
      '',
    ],
    [
      'to countenance',
      '',
      'tolerar / admitir',
      'presente:countenance|passado:countenanced',
      'They would not countenance delay.',
      'Eles não admitiriam atraso.',
      '',
    ],
    [
      'to inure',
      '',
      'habituar (a algo penoso)',
      'presente:inured|passado:inured',
      'He became inured to criticism.',
      'Ele se habituou às críticas.',
      'Quase sempre na voz passiva.',
    ],
    [
      'to gloss over',
      '',
      'passar por cima de',
      'presente:glosses over|passado:glossed over',
      'The report glosses over the failures.',
      'O relatório passa por cima dos fracassos.',
      '',
    ],
    [
      'to hedge',
      '',
      'atenuar / não se comprometer',
      'presente:hedges|passado:hedged',
      'The study hedges its conclusions.',
      'O estudo atenua suas conclusões.',
      'Essencial no registro acadêmico inglês.',
    ],
  ],
};

/* ================================================================== *
 * Espanhol
 * ================================================================== */

const ES: VerbMap = {
  A1: [
    [
      'ser',
      '',
      'ser (característica, identidade)',
      'yo:soy|él/ella:es|nosotros:somos|pasado:fui',
      'Soy brasileño.',
      'Sou brasileiro.',
      'Para característica permanente; estado usa "estar".',
    ],
    [
      'estar',
      '',
      'estar (estado, lugar)',
      'yo:estoy|él/ella:está|nosotros:estamos|pasado:estuve',
      'Estoy cansado.',
      'Estou cansado.',
      '"Estoy casado" — casado é estado em espanhol.',
    ],
    [
      'tener',
      '',
      'ter',
      'yo:tengo|él/ella:tiene|nosotros:tenemos|pasado:tuve',
      'Tengo veinticinco años.',
      'Tenho vinte e cinco anos.',
      'Usa-se para idade, como em português.',
    ],
    [
      'hacer',
      '',
      'fazer',
      'yo:hago|él/ella:hace|pasado:hice',
      '¿Qué haces los domingos?',
      'O que você faz aos domingos?',
      '',
    ],
    [
      'ir',
      '',
      'ir',
      'yo:voy|él/ella:va|nosotros:vamos|pasado:fui',
      'Voy al trabajo en metro.',
      'Vou ao trabalho de metrô.',
      '"Ir a" + infinitivo forma o futuro próximo.',
    ],
    [
      'querer',
      '',
      'querer / amar',
      'yo:quiero|él/ella:quiere|pasado:quise',
      'Quiero aprender español.',
      'Quero aprender espanhol.',
      'Com pessoa, também significa amar.',
    ],
    [
      'gustar',
      '',
      'agradar (gostar)',
      'me:gusta|me:gustan|pasado:gustó',
      'Me gustan los libros.',
      'Gosto de livros.',
      'Estrutura invertida: quem gosta é objeto indireto.',
    ],
    [
      'hablar',
      '',
      'falar',
      'yo:hablo|él/ella:habla|pasado:hablé',
      '¿Hablas portugués?',
      'Você fala português?',
      '',
    ],
  ],
  A2: [
    [
      'traer',
      '',
      'trazer',
      'yo:traigo|él/ella:trae|pasado:traje',
      'Trae los documentos mañana.',
      'Traga os documentos amanhã.',
      'Irregular na primeira pessoa.',
    ],
    [
      'salir',
      '',
      'sair',
      'yo:salgo|él/ella:sale|pasado:salí',
      'Salgo de casa a las ocho.',
      'Saio de casa às oito.',
      'Irregular na primeira pessoa.',
    ],
    [
      'pagar',
      '',
      'pagar',
      'yo:pago|él/ella:paga|pasado:pagué',
      'Pagué con tarjeta.',
      'Paguei com cartão.',
      'No pretérito, o "g" vira "gu".',
    ],
    [
      'esperar',
      '',
      'esperar (aguardar e ter esperança)',
      'yo:espero|pasado:esperé',
      'Espera un rato, por favor.',
      'Espere um momento, por favor.',
      'Com subjuntivo, significa ter esperança.',
    ],
    [
      'sentirse',
      '',
      'sentir-se',
      'yo:me siento|él:se siente|pasado:me sentí',
      'Hoy me siento mucho mejor.',
      'Hoje me sinto bem melhor.',
      'Reflexivo, ao contrário do inglês.',
    ],
    [
      'pasar',
      '',
      'passar / acontecer',
      'presente:pasa|pasado:pasó',
      '¿Qué pasó ayer?',
      'O que aconteceu ontem?',
      'Um dos verbos mais polissêmicos do espanhol.',
    ],
    [
      'intentar',
      '',
      'tentar',
      'yo:intento|pasado:intenté',
      'Intenta llegar temprano.',
      'Tente chegar cedo.',
      '',
    ],
    [
      'quedar',
      '',
      'ficar / combinar',
      'yo:quedo|pasado:quedé',
      'Quedamos a las siete.',
      'Combinamos às sete.',
      '"Quedarse" é permanecer; "quedar" é combinar.',
    ],
  ],
  B1: [
    [
      'lograr',
      '',
      'conseguir',
      'yo:logro|pasado:logré',
      'Logró terminar a tiempo.',
      'Ele conseguiu terminar a tempo.',
      'Implica esforço e êxito.',
    ],
    [
      'permitirse',
      '',
      'ter condições de',
      'yo:me permito|pasado:me permití',
      'No puedo permitirme ese viaje.',
      'Não tenho condições dessa viagem.',
      '',
    ],
    [
      'sugerir',
      '',
      'sugerir',
      'yo:sugiero|pasado:sugerí',
      'Sugiero que vengas temprano.',
      'Sugiro que você venha cedo.',
      'Exige subjuntivo na oração seguinte.',
    ],
    [
      'evitar',
      '',
      'evitar',
      'yo:evito|pasado:evité',
      'Evita usar frases largas.',
      'Evite usar frases longas.',
      '',
    ],
    [
      'quejarse',
      '',
      'reclamar',
      'yo:me quejo|pasado:me quejé',
      'Se quejaron del ruido.',
      'Reclamaram do barulho.',
      'Reclama-se "de" algo.',
    ],
    [
      'darse cuenta',
      '',
      'perceber',
      'yo:me doy cuenta|pasado:me di cuenta',
      'Me di cuenta de que estaba mal.',
      'Percebi que estava errado.',
      'Sempre com "de que".',
    ],
    [
      'soler',
      '',
      'costumar',
      'yo:suelo|él:suele|pasado:solía',
      'Suelo estudiar por la noche.',
      'Costumo estudar à noite.',
      'Não existe em inglês; muito frequente.',
    ],
    [
      'mejorar',
      '',
      'melhorar',
      'yo:mejoro|pasado:mejoré',
      'Mi escritura mejoró mucho.',
      'Minha escrita melhorou muito.',
      '',
    ],
  ],
  B2: [
    [
      'reconocer',
      '',
      'reconhecer / admitir',
      'yo:reconozco|pasado:reconocí',
      'Reconoció su error.',
      'Ele reconheceu o erro.',
      'Irregular na primeira pessoa.',
    ],
    [
      'socavar',
      '',
      'minar',
      'presente:socava|pasado:socavó',
      'El retraso socavó la confianza.',
      'O atraso minou a confiança.',
      '',
    ],
    [
      'pasar por alto',
      '',
      'deixar passar',
      'presente:paso por alto|pasado:pasé por alto',
      'Pasamos por alto un detalle.',
      'Deixamos passar um detalhe.',
      '',
    ],
    [
      'abordar',
      '',
      'abordar / tratar de',
      'yo:abordo|pasado:abordé',
      'El informe aborda tres riesgos.',
      'O relatório aborda três riscos.',
      '',
    ],
    [
      'implicar',
      '',
      'implicar / acarretar',
      'presente:implica|pasado:implicó',
      'Esto implica costes extra.',
      'Isso acarreta custos extras.',
      '',
    ],
    [
      'cumplir',
      '',
      'cumprir',
      'yo:cumplo|pasado:cumplí',
      'Debemos cumplir con las normas.',
      'Devemos cumprir as normas.',
      'Também se usa para idade: "cumplir años".',
    ],
    [
      'superar',
      '',
      'superar',
      'yo:supero|pasado:superé',
      'Los beneficios superan los riesgos.',
      'Os benefícios superam os riscos.',
      '',
    ],
    [
      'aprovechar',
      '',
      'aproveitar',
      'yo:aprovecho|pasado:aproveché',
      'Aprovecharon el conocimiento local.',
      'Aproveitaram o conhecimento local.',
      '',
    ],
  ],
  C1: [
    [
      'fundamentar',
      '',
      'fundamentar',
      'yo:fundamento|pasado:fundamenté',
      'No pudo fundamentar la acusación.',
      'Não conseguiu fundamentar a acusação.',
      '',
    ],
    [
      'conciliar',
      '',
      'conciliar',
      'yo:concilio|pasado:concilié',
      'Cuesta conciliar ambas versiones.',
      'Custa conciliar as duas versões.',
      '',
    ],
    [
      'impedir',
      '',
      'impedir',
      'yo:impido|pasado:impedí',
      'Los recortes impiden nuevas pruebas.',
      'Os cortes impedem novos testes.',
      'Exige subjuntivo depois.',
    ],
    [
      'mitigar',
      '',
      'mitigar',
      'presente:mitiga|pasado:mitigó',
      'Estas medidas mitigan el riesgo.',
      'Essas medidas mitigam o risco.',
      '',
    ],
    [
      'imperar',
      '',
      'imperar / prevalecer',
      'presente:impera|pasado:imperó',
      'Al final imperó el sentido común.',
      'No fim, imperou o bom senso.',
      '',
    ],
    [
      'ameritar',
      '',
      'merecer / justificar',
      'presente:amerita|pasado:ameritó',
      'El caso amerita más estudio.',
      'O caso merece mais estudo.',
      'Mais comum na América Latina.',
    ],
    [
      'sustentar',
      '',
      'sustentar / embasar',
      'yo:sustento|pasado:sustenté',
      'Tres principios sustentan el modelo.',
      'Três princípios sustentam o modelo.',
      '',
    ],
    [
      'resignarse',
      '',
      'conformar-se',
      'yo:me resigno|pasado:me resigné',
      'Se resignó al resultado.',
      'Conformou-se com o resultado.',
      '',
    ],
  ],
  C2: [
    [
      'desmentir',
      '',
      'desmentir',
      'presente:desmiente|pasado:desmintió',
      'Su calma desmentía su enfado.',
      'Sua calma desmentia sua irritação.',
      '',
    ],
    [
      'soslayar',
      '',
      'contornar / driblar',
      'yo:soslayo|pasado:soslayé',
      'El informe soslaya los fracasos.',
      'O relatório contorna os fracassos.',
      '',
    ],
    [
      'rehuir',
      '',
      'esquivar-se de',
      'yo:rehúyo|pasado:rehuí',
      'Rehúye el debate.',
      'Esquiva-se do debate.',
      'Acentuação irregular.',
    ],
    [
      'obviar',
      '',
      'dispensar / evitar',
      'presente:obvia|pasado:obvió',
      'Esto obvia una segunda revisión.',
      'Isso dispensa uma segunda revisão.',
      '',
    ],
    [
      'consentir',
      '',
      'consentir / tolerar',
      'yo:consiento|pasado:consentí',
      'No consentirían el retraso.',
      'Não consentiriam o atraso.',
      '',
    ],
    [
      'curtirse',
      '',
      'endurecer-se (com a experiência)',
      'yo:me curto|pasado:me curtí',
      'Se curtió con las críticas.',
      'Endureceu com as críticas.',
      '',
    ],
    [
      'matizar',
      '',
      'matizar / nuançar',
      'yo:matizo|pasado:maticé',
      'Conviene matizar esa afirmación.',
      'Convém matizar essa afirmação.',
      'Central no discurso acadêmico.',
    ],
    [
      'aducir',
      '',
      'alegar / aduzir',
      'yo:aduzco|pasado:aduje',
      'Adujo razones de salud.',
      'Alegou motivos de saúde.',
      'Registro jurídico e formal.',
    ],
  ],
};

/* ================================================================== *
 * Francês, italiano, alemão, japonês, coreano e mandarim
 * ================================================================== */

const FR: VerbMap = {
  A1: [
    [
      'être',
      '',
      'ser / estar',
      'je:suis|il/elle:est|nous:sommes|passé:étais',
      'Je suis étudiant.',
      'Sou estudante.',
      'Auxiliar de vários verbos no passado composto.',
    ],
    [
      'avoir',
      '',
      'ter',
      "j':ai|il/elle:a|nous:avons|passé:avais",
      "J'ai vingt-cinq ans.",
      'Tenho vinte e cinco anos.',
      'Usa-se para idade, como em português.',
    ],
    [
      'aller',
      '',
      'ir',
      'je:vais|il/elle:va|nous:allons|passé:allais',
      'Je vais au travail en métro.',
      'Vou ao trabalho de metrô.',
      '"Aller" + infinitivo forma o futuro próximo.',
    ],
    [
      'faire',
      '',
      'fazer',
      'je:fais|il/elle:fait|nous:faisons|passé:faisais',
      'Que fais-tu le dimanche ?',
      'O que você faz aos domingos?',
      '',
    ],
    [
      'vouloir',
      '',
      'querer',
      'je:veux|il/elle:veut|nous:voulons|passé:voulais',
      'Je veux apprendre le français.',
      'Quero aprender francês.',
      '"Je voudrais" é a forma educada.',
    ],
    [
      'pouvoir',
      '',
      'poder',
      'je:peux|il/elle:peut|nous:pouvons|passé:pouvais',
      'Tu peux répéter ?',
      'Você pode repetir?',
      '',
    ],
    [
      'parler',
      '',
      'falar',
      'je:parle|il/elle:parle|nous:parlons|passé:parlais',
      'Parlez-vous portugais ?',
      'Você fala português?',
      '',
    ],
    [
      'aimer',
      '',
      'gostar de / amar',
      'je:aime|il/elle:aime|passé:aimais',
      "J'aime le café.",
      'Gosto de café.',
      'Com pessoa, significa amar.',
    ],
  ],
  A2: [
    [
      'apporter',
      '',
      'trazer',
      "j':apporte|passé composé:ai apporté",
      'Apporte tes documents demain.',
      'Traga seus documentos amanhã.',
      '"Apporter" coisas; "amener" pessoas.',
    ],
    [
      'partir',
      '',
      'partir / ir embora',
      'je:pars|il:part|passé composé:suis parti',
      'Je pars à huit heures.',
      'Saio às oito.',
      'Passado composto com "être".',
    ],
    [
      'payer',
      '',
      'pagar',
      'je:paie|passé composé:ai payé',
      "J'ai payé par carte.",
      'Paguei com cartão.',
      '',
    ],
    [
      'attendre',
      '',
      'esperar (aguardar)',
      "j':attends|passé composé:ai attendu",
      "J'attends le bus.",
      'Espero o ônibus.',
      'Falso amigo: não é "atender".',
    ],
    [
      'se sentir',
      '',
      'sentir-se',
      'je:me sens|passé composé:me suis senti',
      'Je me sens mieux.',
      'Me sinto melhor.',
      'Reflexivo, com "être" no passado.',
    ],
    [
      'arriver',
      '',
      'chegar / acontecer',
      'il:arrive|passé composé:est arrivé',
      "Qu'est-ce qui est arrivé ?",
      'O que aconteceu?',
      'Dois sentidos; passado com "être".',
    ],
    [
      'essayer',
      '',
      'tentar',
      "j':essaie|passé composé:ai essayé",
      "Essaie d'arriver tôt.",
      'Tente chegar cedo.',
      'Seguido de "de" + infinitivo.',
    ],
    [
      'rester',
      '',
      'ficar / permanecer',
      'je:reste|passé composé:suis resté',
      'Je reste à la maison.',
      'Fico em casa.',
      'Falso amigo: não é "restar".',
    ],
  ],
  B1: [
    [
      'réussir',
      '',
      'conseguir / ter êxito',
      'je:réussis|passé composé:ai réussi',
      'Elle a réussi à finir.',
      'Ela conseguiu terminar.',
      'Seguido de "à" + infinitivo.',
    ],
    [
      'se permettre',
      '',
      'ter condições de',
      'je:me permets|passé:me suis permis',
      'Je ne peux pas me permettre ce voyage.',
      'Não tenho condições dessa viagem.',
      '',
    ],
    [
      'suggérer',
      '',
      'sugerir',
      'je:suggère|passé composé:ai suggéré',
      'Il a suggéré de se voir vendredi.',
      'Ele sugeriu se verem na sexta.',
      '',
    ],
    [
      'éviter',
      '',
      'evitar',
      "j':évite|passé composé:ai évité",
      "Évite d'utiliser des phrases longues.",
      'Evite usar frases longas.',
      '',
    ],
    [
      'se plaindre',
      '',
      'reclamar',
      'je:me plains|passé:me suis plaint',
      'Ils se sont plaints du bruit.',
      'Reclamaram do barulho.',
      'Reclama-se "de" algo.',
    ],
    [
      'se rendre compte',
      '',
      'dar-se conta',
      'je:me rends compte|passé:me suis rendu compte',
      "Je me suis rendu compte de l'erreur.",
      'Dei-me conta do erro.',
      '',
    ],
    [
      'avoir du mal',
      '',
      'ter dificuldade',
      "j':ai du mal|passé:avais du mal",
      "J'ai du mal à comprendre.",
      'Tenho dificuldade em entender.',
      'Locução, não verbo simples.',
    ],
    [
      'améliorer',
      '',
      'melhorar',
      "j':améliore|passé composé:ai amélioré",
      "J'ai amélioré mon écriture.",
      'Melhorei minha escrita.',
      '',
    ],
  ],
  B2: [
    [
      'reconnaître',
      '',
      'reconhecer / admitir',
      'je:reconnais|passé composé:ai reconnu',
      "Il a reconnu qu'il avait tort.",
      'Ele reconheceu que estava errado.',
      '',
    ],
    [
      'saper',
      '',
      'minar',
      'il:sape|passé composé:a sapé',
      'Les retards ont sapé la confiance.',
      'Os atrasos minaram a confiança.',
      '',
    ],
    [
      'négliger',
      '',
      'negligenciar',
      'je:néglige|passé composé:ai négligé',
      'Nous avons négligé un détail.',
      'Negligenciamos um detalhe.',
      '',
    ],
    [
      'aborder',
      '',
      'abordar',
      "j':aborde|passé composé:ai abordé",
      'Le rapport aborde trois risques.',
      'O relatório aborda três riscos.',
      '',
    ],
    [
      'entraîner',
      '',
      'acarretar / treinar',
      'il:entraîne|passé composé:a entraîné',
      'Cela entraîne des coûts.',
      'Isso acarreta custos.',
      'Dois sentidos distantes.',
    ],
    [
      'respecter',
      '',
      'cumprir / respeitar',
      'je:respecte|passé composé:ai respecté',
      'Il faut respecter les règles.',
      'É preciso cumprir as regras.',
      '',
    ],
    [
      "l'emporter sur",
      '',
      'superar / prevalecer sobre',
      "il:l'emporte|passé:l'a emporté",
      "Les avantages l'emportent sur les risques.",
      'As vantagens superam os riscos.',
      '',
    ],
    [
      'tirer parti de',
      '',
      'tirar proveito de',
      'je:tire parti|passé:ai tiré parti',
      'Ils ont tiré parti de leur expérience.',
      'Tiraram proveito da experiência.',
      '',
    ],
  ],
  C1: [
    [
      'étayer',
      '',
      'fundamentar',
      "j':étaie|passé composé:ai étayé",
      "Il n'a pas étayé ses accusations.",
      'Não fundamentou as acusações.',
      '',
    ],
    [
      'concilier',
      '',
      'conciliar',
      'je:concilie|passé composé:ai concilié',
      'Difficile de concilier les deux.',
      'Difícil conciliar os dois.',
      '',
    ],
    [
      'empêcher',
      '',
      'impedir',
      "j':empêche|passé composé:ai empêché",
      'Les coupes empêchent les essais.',
      'Os cortes impedem os testes.',
      'Seguido de "de" + infinitivo.',
    ],
    [
      'atténuer',
      '',
      'atenuar / mitigar',
      "j':atténue|passé composé:ai atténué",
      'Ces mesures atténuent le risque.',
      'Essas medidas atenuam o risco.',
      '',
    ],
    [
      'prévaloir',
      '',
      'prevalecer',
      'il:prévaut|passé composé:a prévalu',
      'Le bon sens a prévalu.',
      'O bom senso prevaleceu.',
      'Conjugação irregular rara.',
    ],
    [
      'justifier',
      '',
      'justificar',
      'je:justifie|passé composé:ai justifié',
      'Le cas justifie une étude.',
      'O caso justifica um estudo.',
      '',
    ],
    [
      'sous-tendre',
      '',
      'sustentar / subjazer',
      'il:sous-tend|passé composé:a sous-tendu',
      'Trois principes sous-tendent le modèle.',
      'Três princípios sustentam o modelo.',
      '',
    ],
    [
      'se résigner',
      '',
      'conformar-se',
      'je:me résigne|passé:me suis résigné',
      "Elle s'est résignée au résultat.",
      'Conformou-se com o resultado.',
      '',
    ],
  ],
  C2: [
    [
      'démentir',
      '',
      'desmentir',
      'il:dément|passé composé:a démenti',
      'Son calme démentait sa colère.',
      'Sua calma desmentia sua raiva.',
      '',
    ],
    [
      'tergiverser',
      '',
      'usar de evasivas',
      'il:tergiverse|passé composé:a tergiversé',
      'Le ministre a tergiversé.',
      'O ministro usou de evasivas.',
      '',
    ],
    [
      'escamoter',
      '',
      'escamotear',
      "j':escamote|passé composé:ai escamoté",
      'Le rapport escamote les échecs.',
      'O relatório escamoteia os fracassos.',
      '',
    ],
    [
      'obvier à',
      '',
      'obviar / remediar',
      'il:obvie|passé composé:a obvié',
      'Cela obvie à une seconde revue.',
      'Isso dispensa uma segunda revisão.',
      'Registro muito formal.',
    ],
    [
      'souscrire à',
      '',
      'subscrever / concordar com',
      'je:souscris|passé composé:ai souscrit',
      'Je ne souscris pas à cette thèse.',
      'Não subscrevo essa tese.',
      '',
    ],
    [
      "s'aguerrir",
      '',
      'endurecer-se',
      "je:m'aguerris|passé:me suis aguerri",
      "Il s'est aguerri aux critiques.",
      'Endureceu com as críticas.',
      '',
    ],
    [
      'nuancer',
      '',
      'matizar',
      'je:nuance|passé composé:ai nuancé',
      'Il convient de nuancer ce propos.',
      'Convém matizar essa afirmação.',
      'Central na dissertação francesa.',
    ],
    [
      'invoquer',
      '',
      'alegar / invocar',
      "j':invoque|passé composé:ai invoqué",
      'Il a invoqué des raisons de santé.',
      'Alegou motivos de saúde.',
      '',
    ],
  ],
};

const IT: VerbMap = {
  A1: [
    [
      'essere',
      '',
      'ser / estar',
      'io:sono|lui/lei:è|noi:siamo|passato:ero',
      'Sono brasiliano.',
      'Sou brasileiro.',
      'Auxiliar de muitos verbos no passado.',
    ],
    [
      'avere',
      '',
      'ter',
      'io:ho|lui/lei:ha|noi:abbiamo|passato:avevo',
      'Ho venticinque anni.',
      'Tenho vinte e cinco anos.',
      'Usa-se para idade.',
    ],
    [
      'andare',
      '',
      'ir',
      'io:vado|lui/lei:va|noi:andiamo|passato:andavo',
      'Vado al lavoro in metro.',
      'Vou ao trabalho de metrô.',
      'Passado com "essere".',
    ],
    [
      'fare',
      '',
      'fazer',
      'io:faccio|lui/lei:fa|noi:facciamo|passato:facevo',
      'Cosa fai la domenica?',
      'O que você faz aos domingos?',
      '',
    ],
    [
      'volere',
      '',
      'querer',
      'io:voglio|lui/lei:vuole|noi:vogliamo|passato:volevo',
      "Voglio imparare l'italiano.",
      'Quero aprender italiano.',
      '"Vorrei" é a forma educada.',
    ],
    [
      'potere',
      '',
      'poder',
      'io:posso|lui/lei:può|noi:possiamo|passato:potevo',
      'Puoi ripetere?',
      'Você pode repetir?',
      '',
    ],
    [
      'parlare',
      '',
      'falar',
      'io:parlo|lui/lei:parla|passato:parlavo',
      'Parli portoghese?',
      'Você fala português?',
      '',
    ],
    [
      'piacere',
      '',
      'agradar (gostar)',
      'mi:piace|mi:piacciono|passato:piaceva',
      'Mi piacciono i libri.',
      'Gosto de livros.',
      'Estrutura invertida, como o espanhol.',
    ],
  ],
  A2: [
    [
      'portare',
      '',
      'trazer / levar',
      'io:porto|passato prossimo:ho portato',
      'Porta i documenti domani.',
      'Traga os documentos amanhã.',
      'Serve para trazer e levar.',
    ],
    [
      'uscire',
      '',
      'sair',
      'io:esco|lui:esce|passato prossimo:sono uscito',
      'Esco alle otto.',
      'Saio às oito.',
      'Passado com "essere".',
    ],
    [
      'pagare',
      '',
      'pagar',
      'io:pago|passato prossimo:ho pagato',
      'Ho pagato con la carta.',
      'Paguei com cartão.',
      '',
    ],
    [
      'aspettare',
      '',
      'esperar (aguardar)',
      'io:aspetto|passato prossimo:ho aspettato',
      'Aspetta un attimo.',
      'Espere um instante.',
      'Sem preposição depois.',
    ],
    [
      'sentirsi',
      '',
      'sentir-se',
      'io:mi sento|passato:mi sono sentito',
      'Oggi mi sento meglio.',
      'Hoje me sinto melhor.',
      'Reflexivo, com "essere".',
    ],
    [
      'succedere',
      '',
      'acontecer',
      'lui:succede|passato prossimo:è successo',
      'Cosa è successo ieri?',
      'O que aconteceu ontem?',
      '',
    ],
    [
      'provare',
      '',
      'tentar / experimentar',
      'io:provo|passato prossimo:ho provato',
      'Prova ad arrivare presto.',
      'Tente chegar cedo.',
      'Seguido de "a" + infinitivo.',
    ],
    [
      'rimanere',
      '',
      'ficar / permanecer',
      'io:rimango|passato prossimo:sono rimasto',
      'Rimango a casa.',
      'Fico em casa.',
      '',
    ],
  ],
  B1: [
    [
      'riuscire',
      '',
      'conseguir',
      'io:riesco|passato prossimo:sono riuscito',
      'È riuscita a finire.',
      'Ela conseguiu terminar.',
      'Seguido de "a"; passado com "essere".',
    ],
    [
      'permettersi',
      '',
      'ter condições de',
      'io:mi permetto|passato:mi sono permesso',
      'Non posso permettermi quel viaggio.',
      'Não tenho condições dessa viagem.',
      '',
    ],
    [
      'suggerire',
      '',
      'sugerir',
      'io:suggerisco|passato prossimo:ho suggerito',
      'Ha suggerito di vederci venerdì.',
      'Sugeriu nos vermos na sexta.',
      'Verbo em -isc-.',
    ],
    [
      'evitare',
      '',
      'evitar',
      'io:evito|passato prossimo:ho evitato',
      'Evita di usare frasi lunghe.',
      'Evite usar frases longas.',
      '',
    ],
    [
      'lamentarsi',
      '',
      'reclamar',
      'io:mi lamento|passato:mi sono lamentato',
      'Si sono lamentati del rumore.',
      'Reclamaram do barulho.',
      '',
    ],
    [
      'accorgersi',
      '',
      'dar-se conta',
      'io:mi accorgo|passato:mi sono accorto',
      "Mi sono accorto dell'errore.",
      'Dei-me conta do erro.',
      'Seguido de "di".',
    ],
    [
      'faticare',
      '',
      'ter dificuldade',
      'io:fatico|passato prossimo:ho faticato',
      'Ho faticato a capire.',
      'Tive dificuldade em entender.',
      '',
    ],
    [
      'migliorare',
      '',
      'melhorar',
      'io:miglioro|passato prossimo:ho migliorato',
      'Ho migliorato la scrittura.',
      'Melhorei a escrita.',
      '',
    ],
  ],
  B2: [
    [
      'riconoscere',
      '',
      'reconhecer',
      'io:riconosco|passato prossimo:ho riconosciuto',
      'Ha riconosciuto di aver sbagliato.',
      'Reconheceu que errou.',
      '',
    ],
    [
      'minare',
      '',
      'minar',
      'lui:mina|passato prossimo:ha minato',
      'I ritardi hanno minato la fiducia.',
      'Os atrasos minaram a confiança.',
      '',
    ],
    [
      'trascurare',
      '',
      'negligenciar',
      'io:trascuro|passato prossimo:ho trascurato',
      'Abbiamo trascurato un dettaglio.',
      'Negligenciamos um detalhe.',
      '',
    ],
    [
      'affrontare',
      '',
      'enfrentar / abordar',
      'io:affronto|passato prossimo:ho affrontato',
      'Il rapporto affronta tre rischi.',
      'O relatório aborda três riscos.',
      '',
    ],
    [
      'comportare',
      '',
      'acarretar',
      'lui:comporta|passato prossimo:ha comportato',
      'Questo comporta costi extra.',
      'Isso acarreta custos extras.',
      '',
    ],
    [
      'rispettare',
      '',
      'cumprir / respeitar',
      'io:rispetto|passato prossimo:ho rispettato',
      'Bisogna rispettare le regole.',
      'É preciso cumprir as regras.',
      '',
    ],
    [
      'superare',
      '',
      'superar',
      'io:supero|passato prossimo:ho superato',
      'I benefici superano i rischi.',
      'Os benefícios superam os riscos.',
      '',
    ],
    [
      'sfruttare',
      '',
      'aproveitar',
      'io:sfrutto|passato prossimo:ho sfruttato',
      'Hanno sfruttato la conoscenza locale.',
      'Aproveitaram o conhecimento local.',
      '',
    ],
  ],
  C1: [
    [
      'comprovare',
      '',
      'comprovar',
      'io:comprovo|passato prossimo:ho comprovato',
      "Non ha comprovato l'accusa.",
      'Não comprovou a acusação.',
      '',
    ],
    [
      'conciliare',
      '',
      'conciliar',
      'io:concilio|passato prossimo:ho conciliato',
      'È difficile conciliare le versioni.',
      'É difícil conciliar as versões.',
      '',
    ],
    [
      'precludere',
      '',
      'inviabilizar',
      'lui:preclude|passato prossimo:ha precluso',
      'I tagli precludono nuovi test.',
      'Os cortes inviabilizam novos testes.',
      '',
    ],
    [
      'mitigare',
      '',
      'mitigar',
      'lui:mitiga|passato prossimo:ha mitigato',
      'Queste misure mitigano il rischio.',
      'Essas medidas mitigam o risco.',
      '',
    ],
    [
      'prevalere',
      '',
      'prevalecer',
      'lui:prevale|passato prossimo:è prevalso',
      'È prevalso il buon senso.',
      'Prevaleceu o bom senso.',
      'Passado com "essere".',
    ],
    [
      'giustificare',
      '',
      'justificar',
      'io:giustifico|passato prossimo:ho giustificato',
      'Il caso giustifica uno studio.',
      'O caso justifica um estudo.',
      '',
    ],
    [
      'sorreggere',
      '',
      'sustentar',
      'lui:sorregge|passato prossimo:ha sorretto',
      'Tre principi sorreggono il modello.',
      'Três princípios sustentam o modelo.',
      '',
    ],
    [
      'rassegnarsi',
      '',
      'conformar-se',
      'io:mi rassegno|passato:mi sono rassegnato',
      'Si è rassegnata al risultato.',
      'Conformou-se com o resultado.',
      '',
    ],
  ],
  C2: [
    [
      'smentire',
      '',
      'desmentir',
      'lui:smentisce|passato prossimo:ha smentito',
      'Il tono calmo smentiva la rabbia.',
      'O tom calmo desmentia a raiva.',
      '',
    ],
    [
      'tergiversare',
      '',
      'usar de evasivas',
      'lui:tergiversa|passato prossimo:ha tergiversato',
      'Il ministro ha tergiversato.',
      'O ministro usou de evasivas.',
      '',
    ],
    [
      'sorvolare',
      '',
      'passar por cima',
      'lui:sorvola|passato prossimo:ha sorvolato',
      'Il rapporto sorvola sui fallimenti.',
      'O relatório passa por cima dos fracassos.',
      '',
    ],
    [
      'ovviare',
      '',
      'obviar / remediar',
      'lui:ovvia|passato prossimo:ha ovviato',
      'Questo ovvia a una seconda revisione.',
      'Isso dispensa uma segunda revisão.',
      '',
    ],
    [
      'tollerare',
      '',
      'tolerar',
      'io:tollero|passato prossimo:ho tollerato',
      'Non tollererebbero il ritardo.',
      'Não tolerariam o atraso.',
      '',
    ],
    [
      'agguerrirsi',
      '',
      'endurecer-se',
      'io:mi agguerrisco|passato:mi sono agguerrito',
      'Si è agguerrito alle critiche.',
      'Endureceu com as críticas.',
      '',
    ],
    [
      'sfumare',
      '',
      'matizar / esvair-se',
      'lui:sfuma|passato prossimo:ha sfumato',
      'Conviene sfumare questa affermazione.',
      'Convém matizar essa afirmação.',
      '',
    ],
    [
      'addurre',
      '',
      'alegar / aduzir',
      'lui:adduce|passato prossimo:ha addotto',
      'Ha addotto motivi di salute.',
      'Alegou motivos de saúde.',
      'Registro formal.',
    ],
  ],
};

const DE: VerbMap = {
  A1: [
    [
      'sein',
      '',
      'ser / estar',
      'ich:bin|er/sie:ist|wir:sind|Präteritum:war',
      'Ich bin Student.',
      'Sou estudante.',
      'Auxiliar de verbos de movimento no Perfekt.',
    ],
    [
      'haben',
      '',
      'ter',
      'ich:habe|er/sie:hat|wir:haben|Präteritum:hatte',
      'Ich habe zwei Brüder.',
      'Tenho dois irmãos.',
      'Idade usa "sein": "Ich bin 25".',
    ],
    [
      'gehen',
      '',
      'ir (a pé)',
      'ich:gehe|er/sie:geht|Perfekt:bin gegangen',
      'Ich gehe zur Arbeit.',
      'Vou ao trabalho.',
      'Perfekt com "sein".',
    ],
    [
      'machen',
      '',
      'fazer',
      'ich:mache|er/sie:macht|Perfekt:habe gemacht',
      'Was machst du am Sonntag?',
      'O que você faz no domingo?',
      '',
    ],
    [
      'wollen',
      '',
      'querer',
      'ich:will|er/sie:will|wir:wollen|Präteritum:wollte',
      'Ich will Deutsch lernen.',
      'Quero aprender alemão.',
      'Verbo modal; o principal vai ao fim.',
    ],
    [
      'können',
      '',
      'poder / saber',
      'ich:kann|er/sie:kann|wir:können|Präteritum:konnte',
      'Kannst du das wiederholen?',
      'Você pode repetir isso?',
      'Também significa saber fazer algo.',
    ],
    [
      'sprechen',
      '',
      'falar',
      'ich:spreche|er/sie:spricht|Perfekt:habe gesprochen',
      'Sprichst du Portugiesisch?',
      'Você fala português?',
      'Muda a vogal na 2ª e 3ª pessoa.',
    ],
    [
      'mögen',
      '',
      'gostar de',
      'ich:mag|er/sie:mag|wir:mögen|Präteritum:mochte',
      'Ich mag Kaffee.',
      'Gosto de café.',
      '"Ich möchte" é "eu gostaria".',
    ],
  ],
  A2: [
    [
      'bringen',
      '',
      'trazer',
      'ich:bringe|Perfekt:habe gebracht',
      'Bring morgen deine Unterlagen mit.',
      'Traga seus documentos amanhã.',
      'Falso amigo do inglês "bring/become".',
    ],
    [
      'verlassen',
      '',
      'deixar / sair de',
      'ich:verlasse|Perfekt:habe verlassen',
      'Ich verlasse das Haus um acht.',
      'Saio de casa às oito.',
      '',
    ],
    [
      'bezahlen',
      '',
      'pagar',
      'ich:bezahle|Perfekt:habe bezahlt',
      'Ich habe mit Karte bezahlt.',
      'Paguei com cartão.',
      '',
    ],
    [
      'warten',
      '',
      'esperar (aguardar)',
      'ich:warte|Perfekt:habe gewartet',
      'Ich warte auf den Bus.',
      'Espero o ônibus.',
      'Sempre "warten auf" + acusativo.',
    ],
    [
      'sich fühlen',
      '',
      'sentir-se',
      'ich:fühle mich|Perfekt:habe mich gefühlt',
      'Ich fühle mich besser.',
      'Me sinto melhor.',
      'Reflexivo obrigatório.',
    ],
    [
      'passieren',
      '',
      'acontecer',
      'es:passiert|Perfekt:ist passiert',
      'Was ist gestern passiert?',
      'O que aconteceu ontem?',
      'Perfekt com "sein".',
    ],
    [
      'versuchen',
      '',
      'tentar',
      'ich:versuche|Perfekt:habe versucht',
      'Versuch früh anzukommen.',
      'Tente chegar cedo.',
      'Com "zu" + infinitivo.',
    ],
    [
      'bleiben',
      '',
      'ficar / permanecer',
      'ich:bleibe|Perfekt:bin geblieben',
      'Ich bleibe zu Hause.',
      'Fico em casa.',
      'Perfekt com "sein".',
    ],
  ],
  B1: [
    [
      'schaffen',
      '',
      'conseguir / criar',
      'ich:schaffe|Perfekt:habe geschafft',
      'Sie hat es rechtzeitig geschafft.',
      'Ela conseguiu a tempo.',
      'Dois sentidos com particípios diferentes.',
    ],
    [
      'sich leisten',
      '',
      'ter condições de',
      'ich:leiste mir|Perfekt:habe mir geleistet',
      'Ich kann mir die Reise nicht leisten.',
      'Não tenho condições da viagem.',
      'Sempre reflexivo com dativo.',
    ],
    [
      'vorschlagen',
      '',
      'sugerir',
      'ich:schlage vor|Perfekt:habe vorgeschlagen',
      'Er schlug Freitag vor.',
      'Ele sugeriu sexta.',
      'Verbo separável.',
    ],
    [
      'vermeiden',
      '',
      'evitar',
      'ich:vermeide|Perfekt:habe vermieden',
      'Vermeide lange Sätze.',
      'Evite frases longas.',
      '',
    ],
    [
      'sich beschweren',
      '',
      'reclamar',
      'ich:beschwere mich|Perfekt:habe mich beschwert',
      'Sie beschwerten sich über den Lärm.',
      'Reclamaram do barulho.',
      'Reclama-se "über" + acusativo.',
    ],
    [
      'merken',
      '',
      'perceber / notar',
      'ich:merke|Perfekt:habe gemerkt',
      'Ich habe gemerkt, dass ich falsch lag.',
      'Percebi que estava errado.',
      '"Sich merken" é memorizar — outro sentido.',
    ],
    [
      'erwarten',
      '',
      'esperar (prever)',
      'ich:erwarte|Perfekt:habe erwartet',
      'Wir erwarten eine Antwort.',
      'Esperamos uma resposta.',
      'Diferente de "warten".',
    ],
    [
      'verbessern',
      '',
      'melhorar',
      'ich:verbessere|Perfekt:habe verbessert',
      'Mein Schreiben hat sich verbessert.',
      'Minha escrita melhorou.',
      '',
    ],
  ],
  B2: [
    [
      'einräumen',
      '',
      'admitir / conceder',
      'ich:räume ein|Perfekt:habe eingeräumt',
      'Er räumte den Fehler ein.',
      'Ele admitiu o erro.',
      'Verbo separável.',
    ],
    [
      'untergraben',
      '',
      'minar',
      'es:untergräbt|Perfekt:hat untergraben',
      'Die Verzögerung untergrub das Vertrauen.',
      'O atraso minou a confiança.',
      '',
    ],
    [
      'übersehen',
      '',
      'deixar passar',
      'ich:übersehe|Perfekt:habe übersehen',
      'Wir haben ein Detail übersehen.',
      'Deixamos passar um detalhe.',
      'Inseparável, apesar do prefixo.',
    ],
    [
      'behandeln',
      '',
      'tratar de / abordar',
      'ich:behandle|Perfekt:habe behandelt',
      'Der Bericht behandelt drei Risiken.',
      'O relatório aborda três riscos.',
      '',
    ],
    [
      'mit sich bringen',
      '',
      'acarretar',
      'es:bringt mit sich|Perfekt:hat mit sich gebracht',
      'Das bringt Mehrkosten mit sich.',
      'Isso acarreta custos extras.',
      'Locução fixa.',
    ],
    [
      'einhalten',
      '',
      'cumprir',
      'ich:halte ein|Perfekt:habe eingehalten',
      'Wir müssen die Regeln einhalten.',
      'Precisamos cumprir as regras.',
      'Separável.',
    ],
    [
      'überwiegen',
      '',
      'superar / predominar',
      'es:überwiegt|Perfekt:hat überwogen',
      'Die Vorteile überwiegen die Risiken.',
      'As vantagens superam os riscos.',
      '',
    ],
    [
      'nutzen',
      '',
      'aproveitar / usar',
      'ich:nutze|Perfekt:habe genutzt',
      'Sie nutzten ihre Ortskenntnis.',
      'Aproveitaram o conhecimento local.',
      '',
    ],
  ],
  C1: [
    [
      'belegen',
      '',
      'comprovar',
      'ich:belege|Perfekt:habe belegt',
      'Er konnte den Vorwurf nicht belegen.',
      'Não conseguiu comprovar a acusação.',
      '',
    ],
    [
      'vereinbaren',
      '',
      'conciliar / combinar',
      'ich:vereinbare|Perfekt:habe vereinbart',
      'Beides ist schwer zu vereinbaren.',
      'É difícil conciliar os dois.',
      'Também significa marcar um compromisso.',
    ],
    [
      'ausschließen',
      '',
      'excluir / inviabilizar',
      'ich:schließe aus|Perfekt:habe ausgeschlossen',
      'Kürzungen schließen Tests aus.',
      'Cortes inviabilizam testes.',
      'Separável.',
    ],
    [
      'abmildern',
      '',
      'mitigar',
      'ich:mildere ab|Perfekt:habe abgemildert',
      'Die Maßnahmen mildern das Risiko ab.',
      'As medidas mitigam o risco.',
      'Separável.',
    ],
    [
      'sich durchsetzen',
      '',
      'prevalecer / impor-se',
      'ich:setze mich durch|Perfekt:habe mich durchgesetzt',
      'Der Menschenverstand setzte sich durch.',
      'O bom senso prevaleceu.',
      '',
    ],
    [
      'rechtfertigen',
      '',
      'justificar',
      'ich:rechtfertige|Perfekt:habe gerechtfertigt',
      'Der Fall rechtfertigt eine Studie.',
      'O caso justifica um estudo.',
      '',
    ],
    [
      'zugrunde liegen',
      '',
      'subjazer / embasar',
      'es:liegt zugrunde|Perfekt:hat zugrunde gelegen',
      'Drei Prinzipien liegen dem Modell zugrunde.',
      'Três princípios embasam o modelo.',
      '',
    ],
    [
      'sich abfinden',
      '',
      'conformar-se',
      'ich:finde mich ab|Perfekt:habe mich abgefunden',
      'Sie fand sich mit dem Ergebnis ab.',
      'Conformou-se com o resultado.',
      'Com "mit" + dativo.',
    ],
  ],
  C2: [
    [
      'Lügen strafen',
      '',
      'desmentir',
      'es:straft Lügen|Perfekt:hat Lügen gestraft',
      'Sein Ton strafte seinen Zorn Lügen.',
      'Seu tom desmentia sua raiva.',
      'Locução literária.',
    ],
    [
      'ausweichen',
      '',
      'esquivar-se',
      'ich:weiche aus|Perfekt:bin ausgewichen',
      'Der Minister wich aus.',
      'O ministro se esquivou.',
      'Perfekt com "sein".',
    ],
    [
      'beschönigen',
      '',
      'maquiar / dourar a pílula',
      'ich:beschönige|Perfekt:habe beschönigt',
      'Der Bericht beschönigt die Fehler.',
      'O relatório maquia os erros.',
      '',
    ],
    [
      'erübrigen',
      '',
      'tornar desnecessário',
      'es:erübrigt sich|Perfekt:hat sich erübrigt',
      'Eine zweite Prüfung erübrigt sich.',
      'Uma segunda revisão é dispensável.',
      'Reflexivo.',
    ],
    [
      'dulden',
      '',
      'tolerar',
      'ich:dulde|Perfekt:habe geduldet',
      'Sie würden keine Verzögerung dulden.',
      'Não tolerariam atraso.',
      '',
    ],
    [
      'abstumpfen',
      '',
      'insensibilizar-se',
      'ich:stumpfe ab|Perfekt:bin abgestumpft',
      'Er ist gegen Kritik abgestumpft.',
      'Ele se insensibilizou às críticas.',
      '',
    ],
    [
      'relativieren',
      '',
      'relativizar / matizar',
      'ich:relativiere|Perfekt:habe relativiert',
      'Diese Aussage ist zu relativieren.',
      'Essa afirmação deve ser matizada.',
      '',
    ],
    [
      'anführen',
      '',
      'alegar / citar',
      'ich:führe an|Perfekt:habe angeführt',
      'Er führte Gesundheitsgründe an.',
      'Alegou motivos de saúde.',
      'Separável.',
    ],
  ],
};

const JA: VerbMap = {
  A1: [
    [
      'です / だ',
      'desu / da',
      'ser / estar (cópula)',
      'polido:です|casual:だ|passado:でした',
      '私は学生です。',
      'Eu sou estudante.',
      'Não é verbo pleno: é cópula, e não se conjuga como os outros.',
    ],
    [
      'あります',
      'arimasu',
      'haver / existir (coisas)',
      'presente:あります|negativo:ありません|passado:ありました',
      '本があります。',
      'Há um livro.',
      'Para objetos; seres vivos usam います.',
    ],
    [
      'います',
      'imasu',
      'haver / estar (seres vivos)',
      'presente:います|negativo:いません|passado:いました',
      '猫がいます。',
      'Há um gato.',
      'A distinção com あります é obrigatória.',
    ],
    [
      '行きます',
      'ikimasu',
      'ir',
      'polido:行きます|dicionário:行く|passado:行きました',
      '毎日会社に行きます。',
      'Vou à empresa todo dia.',
      'O destino leva に ou へ.',
    ],
    [
      '食べます',
      'tabemasu',
      'comer',
      'polido:食べます|dicionário:食べる|て:食べて',
      '朝ごはんを食べます。',
      'Como o café da manhã.',
      'Verbo do grupo 2 (ichidan).',
    ],
    [
      'します',
      'shimasu',
      'fazer',
      'polido:します|dicionário:する|passado:しました',
      '宿題をします。',
      'Faço a lição de casa.',
      'Combina com substantivos: 勉強します.',
    ],
    [
      '話します',
      'hanashimasu',
      'falar',
      'polido:話します|dicionário:話す|て:話して',
      '日本語を話します。',
      'Falo japonês.',
      '',
    ],
    [
      '分かります',
      'wakarimasu',
      'entender',
      'polido:分かります|negativo:分かりません',
      '意味が分かりません。',
      'Não entendo o sentido.',
      'O objeto leva が, não を.',
    ],
  ],
  A2: [
    [
      '持ってきます',
      'motte kimasu',
      'trazer',
      'polido:持ってきます|passado:持ってきました',
      '明日書類を持ってきます。',
      'Trago os documentos amanhã.',
      'Composto de 持つ + くる.',
    ],
    [
      '出ます',
      'demasu',
      'sair',
      'polido:出ます|dicionário:出る|て:出て',
      '八時に家を出ます。',
      'Saio de casa às oito.',
      'O lugar de onde se sai leva を.',
    ],
    [
      '払います',
      'haraimasu',
      'pagar',
      'polido:払います|dicionário:払う|て:払って',
      'カードで払います。',
      'Pago com cartão.',
      '',
    ],
    [
      '待ちます',
      'machimasu',
      'esperar',
      'polido:待ちます|dicionário:待つ|て:待って',
      'ちょっと待ってください。',
      'Espere um pouco, por favor.',
      '',
    ],
    [
      '感じます',
      'kanjimasu',
      'sentir',
      'polido:感じます|dicionário:感じる',
      '今日は調子がいいと感じます。',
      'Sinto que estou bem hoje.',
      '',
    ],
    [
      'なります',
      'narimasu',
      'tornar-se',
      'polido:なります|dicionário:なる|passado:なりました',
      '医者になりました。',
      'Tornei-me médico.',
      'Com substantivo, exige に.',
    ],
    [
      'やってみます',
      'yatte mimasu',
      'tentar / experimentar',
      'polido:やってみます|passado:やってみました',
      '早く来てみます。',
      'Vou tentar vir cedo.',
      'A forma て + みる significa "experimentar".',
    ],
    [
      '決めます',
      'kimemasu',
      'decidir',
      'polido:決めます|dicionário:決める|て:決めて',
      '来週決めます。',
      'Decido na semana que vem.',
      '',
    ],
  ],
  B1: [
    [
      'できます',
      'dekimasu',
      'conseguir / poder',
      'polido:できます|negativo:できません',
      '時間内に終わることができました。',
      'Consegui terminar no prazo.',
      'Forma potencial; o objeto leva が.',
    ],
    [
      '指摘します',
      'shiteki shimasu',
      'apontar',
      'polido:指摘します|passado:指摘しました',
      '間違いを指摘しました。',
      'Apontou o erro.',
      'Substantivo + します.',
    ],
    [
      '避けます',
      'sakemasu',
      'evitar',
      'polido:避けます|dicionário:避ける',
      '長い文を避けてください。',
      'Evite frases longas.',
      '',
    ],
    [
      '文句を言います',
      'monku o iimasu',
      'reclamar',
      'polido:言います|passado:言いました',
      '騒音に文句を言いました。',
      'Reclamou do barulho.',
      '',
    ],
    [
      '気づきます',
      'kizukimasu',
      'perceber / dar-se conta',
      'polido:気づきます|dicionário:気づく',
      '間違いに気づきました。',
      'Percebi o erro.',
      'O objeto leva に.',
    ],
    [
      '期待します',
      'kitai shimasu',
      'esperar (prever)',
      'polido:期待します|passado:期待しました',
      '返事を期待しています。',
      'Estou esperando resposta.',
      '',
    ],
    [
      '改善します',
      'kaizen shimasu',
      'melhorar',
      'polido:改善します|passado:改善しました',
      '文章が改善しました。',
      'O texto melhorou.',
      'Palavra famosa fora do Japão.',
    ],
    [
      '苦労します',
      'kurō shimasu',
      'ter dificuldade',
      'polido:苦労します|passado:苦労しました',
      '文法に苦労しました。',
      'Tive dificuldade com a gramática.',
      '',
    ],
  ],
  B2: [
    [
      '認めます',
      'mitomemasu',
      'reconhecer / admitir',
      'polido:認めます|dicionário:認める',
      '間違いを認めました。',
      'Admitiu o erro.',
      '',
    ],
    [
      '損ないます',
      'sokonaimasu',
      'prejudicar / minar',
      'polido:損ないます|dicionário:損なう',
      '信頼を損ないました。',
      'Minou a confiança.',
      '',
    ],
    [
      '見落とします',
      'miotoshimasu',
      'deixar passar',
      'polido:見落とします|dicionário:見落とす',
      '重要な点を見落としました。',
      'Deixou passar um ponto importante.',
      '',
    ],
    [
      '扱います',
      'atsukaimasu',
      'tratar de / lidar com',
      'polido:扱います|dicionário:扱う',
      '三つのリスクを扱います。',
      'Trata de três riscos.',
      '',
    ],
    [
      '伴います',
      'tomonaimasu',
      'acarretar / acompanhar',
      'polido:伴います|dicionário:伴う',
      '追加費用を伴います。',
      'Acarreta custos extras.',
      '',
    ],
    [
      '守ります',
      'mamorimasu',
      'cumprir / proteger',
      'polido:守ります|dicionário:守る',
      '規則を守ります。',
      'Cumpro as regras.',
      'Dois sentidos próximos.',
    ],
    [
      '上回ります',
      'uwamawarimasu',
      'superar',
      'polido:上回ります|dicionário:上回る',
      '利点がリスクを上回ります。',
      'Os benefícios superam os riscos.',
      '',
    ],
    [
      '活用します',
      'katsuyō shimasu',
      'aproveitar',
      'polido:活用します|passado:活用しました',
      '地元の知識を活用しました。',
      'Aproveitou o conhecimento local.',
      '',
    ],
  ],
  C1: [
    [
      '裏付けます',
      'urazukemasu',
      'comprovar',
      'polido:裏付けます|dicionário:裏付ける',
      '主張を裏付ける証拠がない。',
      'Não há prova que comprove a alegação.',
      '',
    ],
    [
      '両立します',
      'ryōritsu shimasu',
      'conciliar',
      'polido:両立します|passado:両立しました',
      '両者を両立させるのは難しい。',
      'É difícil conciliar os dois.',
      '',
    ],
    [
      '妨げます',
      'samatagemasu',
      'impedir',
      'polido:妨げます|dicionário:妨げる',
      '予算削減が試験を妨げます。',
      'Cortes impedem os testes.',
      '',
    ],
    [
      '緩和します',
      'kanwa shimasu',
      'mitigar',
      'polido:緩和します|passado:緩和しました',
      'リスクを緩和します。',
      'Mitiga o risco.',
      '',
    ],
    [
      '優先します',
      'yūsen shimasu',
      'priorizar',
      'polido:優先します|passado:優先しました',
      '安全を優先します。',
      'Prioriza a segurança.',
      '',
    ],
    [
      '正当化します',
      'seitōka shimasu',
      'justificar',
      'polido:正当化します|passado:正当化しました',
      'その判断を正当化できない。',
      'Não dá para justificar essa decisão.',
      '',
    ],
    [
      '支えます',
      'sasaemasu',
      'sustentar',
      'polido:支えます|dicionário:支える',
      '三つの原則が支えています。',
      'Três princípios sustentam.',
      '',
    ],
    [
      '諦めます',
      'akiramemasu',
      'desistir / conformar-se',
      'polido:諦めます|dicionário:諦める',
      '結果を諦めました。',
      'Conformou-se com o resultado.',
      '',
    ],
  ],
  C2: [
    [
      '覆します',
      'kutsugaeshimasu',
      'reverter / desmentir',
      'polido:覆します|dicionário:覆す',
      '通説を覆す発見。',
      'Uma descoberta que reverte o consenso.',
      '',
    ],
    [
      '言葉を濁します',
      'kotoba o nigoshimasu',
      'usar de evasivas',
      'polido:濁します|passado:濁しました',
      '大臣は言葉を濁しました。',
      'O ministro usou de evasivas.',
      'Locução idiomática.',
    ],
    [
      '取り繕います',
      'toritsukuroimasu',
      'disfarçar / maquiar',
      'polido:取り繕います|dicionário:取り繕う',
      '失敗を取り繕う。',
      'Disfarça o fracasso.',
      '',
    ],
    [
      '省きます',
      'habukimasu',
      'dispensar / omitir',
      'polido:省きます|dicionário:省く',
      '手間を省きます。',
      'Dispensa o trabalho.',
      '',
    ],
    [
      '容認します',
      'yōnin shimasu',
      'tolerar / admitir',
      'polido:容認します|passado:容認しました',
      '遅延を容認しない。',
      'Não tolera atraso.',
      '',
    ],
    [
      '慣れます',
      'naremasu',
      'habituar-se',
      'polido:慣れます|dicionário:慣れる',
      '批判に慣れました。',
      'Habituou-se às críticas.',
      'O objeto leva に.',
    ],
    [
      '和らげます',
      'yawaragemasu',
      'suavizar / matizar',
      'polido:和らげます|dicionário:和らげる',
      '表現を和らげます。',
      'Suaviza a expressão.',
      '',
    ],
    [
      '挙げます',
      'agemasu',
      'apontar / citar',
      'polido:挙げます|dicionário:挙げる',
      '健康上の理由を挙げました。',
      'Citou motivos de saúde.',
      '',
    ],
  ],
};

const KO: VerbMap = {
  A1: [
    [
      '이다',
      'ida',
      'ser (cópula)',
      'polido:이에요/예요|passado:이었어요|formal:입니다',
      '저는 학생이에요.',
      'Eu sou estudante.',
      'Cola no substantivo, sem espaço.',
    ],
    [
      '있다',
      'itda',
      'haver / ter / estar',
      'polido:있어요|negativo:없어요|passado:있었어요',
      '시간이 있어요?',
      'Você tem tempo?',
      'Cobre existir, ter e estar em lugar.',
    ],
    [
      '가다',
      'gada',
      'ir',
      'polido:가요|passado:갔어요|futuro:갈 거예요',
      '회사에 가요.',
      'Vou à empresa.',
      'O destino leva 에.',
    ],
    [
      '하다',
      'hada',
      'fazer',
      'polido:해요|passado:했어요|futuro:할 거예요',
      '숙제를 해요.',
      'Faço a lição.',
      'Combina com milhares de substantivos.',
    ],
    [
      '먹다',
      'meokda',
      'comer',
      'polido:먹어요|passado:먹었어요',
      '아침을 먹어요.',
      'Como o café da manhã.',
      '',
    ],
    [
      '말하다',
      'malhada',
      'falar',
      'polido:말해요|passado:말했어요',
      '한국어를 말해요.',
      'Falo coreano.',
      '',
    ],
    [
      '좋아하다',
      'joahada',
      'gostar de',
      'polido:좋아해요|passado:좋아했어요',
      '커피를 좋아해요.',
      'Gosto de café.',
      'O objeto leva 을/를, ao contrário do espanhol.',
    ],
    [
      '알다',
      'alda',
      'saber / conhecer',
      'polido:알아요|negativo:몰라요',
      '답을 알아요.',
      'Sei a resposta.',
      'O negativo é um verbo diferente: 모르다.',
    ],
  ],
  A2: [
    [
      '가져오다',
      'gajyeooda',
      'trazer',
      'polido:가져와요|passado:가져왔어요',
      '내일 서류를 가져오세요.',
      'Traga os documentos amanhã.',
      '',
    ],
    [
      '나가다',
      'nagada',
      'sair',
      'polido:나가요|passado:나갔어요',
      '여덟 시에 집에서 나가요.',
      'Saio de casa às oito.',
      'O lugar de origem leva 에서.',
    ],
    [
      '지불하다',
      'jibulhada',
      'pagar',
      'polido:지불해요|passado:지불했어요',
      '카드로 지불해요.',
      'Pago com cartão.',
      '',
    ],
    [
      '기다리다',
      'gidarida',
      'esperar',
      'polido:기다려요|passado:기다렸어요',
      '잠깐 기다려 주세요.',
      'Espere um pouco, por favor.',
      '',
    ],
    [
      '느끼다',
      'neukkida',
      'sentir',
      'polido:느껴요|passado:느꼈어요',
      '오늘은 좋게 느껴요.',
      'Hoje me sinto bem.',
      '',
    ],
    [
      '되다',
      'doeda',
      'tornar-se / dar certo',
      'polido:돼요|passado:됐어요',
      '의사가 됐어요.',
      'Tornou-se médico.',
      'O complemento leva 이/가.',
    ],
    [
      '해 보다',
      'hae boda',
      'experimentar / tentar',
      'polido:해 봐요|passado:해 봤어요',
      '일찍 와 볼게요.',
      'Vou tentar vir cedo.',
      'Forma -아/어 보다.',
    ],
    [
      '결정하다',
      'gyeoljeonghada',
      'decidir',
      'polido:결정해요|passado:결정했어요',
      '다음 주에 결정해요.',
      'Decido semana que vem.',
      '',
    ],
  ],
  B1: [
    [
      '할 수 있다',
      'hal su itda',
      'conseguir / poder',
      'polido:할 수 있어요|negativo:할 수 없어요',
      '제시간에 끝낼 수 있었어요.',
      'Consegui terminar no prazo.',
      'Estrutura -(으)ㄹ 수 있다.',
    ],
    [
      '지적하다',
      'jijeokhada',
      'apontar',
      'polido:지적해요|passado:지적했어요',
      '실수를 지적했어요.',
      'Apontou o erro.',
      '',
    ],
    [
      '피하다',
      'pihada',
      'evitar',
      'polido:피해요|passado:피했어요',
      '긴 문장을 피하세요.',
      'Evite frases longas.',
      '',
    ],
    [
      '불평하다',
      'bulpyeonghada',
      'reclamar',
      'polido:불평해요|passado:불평했어요',
      '소음에 불평했어요.',
      'Reclamou do barulho.',
      '',
    ],
    [
      '깨닫다',
      'kkaedatda',
      'perceber / dar-se conta',
      'polido:깨달아요|passado:깨달았어요',
      '실수를 깨달았어요.',
      'Percebi o erro.',
      'Irregular em ㄷ.',
    ],
    [
      '기대하다',
      'gidaehada',
      'esperar (prever)',
      'polido:기대해요|passado:기대했어요',
      '답장을 기대해요.',
      'Espero resposta.',
      '',
    ],
    [
      '향상되다',
      'hyangsangdoeda',
      'melhorar',
      'polido:향상돼요|passado:향상됐어요',
      '글쓰기가 향상됐어요.',
      'A escrita melhorou.',
      '',
    ],
    [
      '어려워하다',
      'eoryeowohada',
      'ter dificuldade',
      'polido:어려워해요|passado:어려워했어요',
      '문법을 어려워했어요.',
      'Teve dificuldade com a gramática.',
      '',
    ],
  ],
  B2: [
    [
      '인정하다',
      'injeonghada',
      'reconhecer / admitir',
      'polido:인정해요|passado:인정했어요',
      '잘못을 인정했어요.',
      'Admitiu o erro.',
      '',
    ],
    [
      '훼손하다',
      'hwesonhada',
      'minar / danificar',
      'polido:훼손해요|passado:훼손했어요',
      '신뢰를 훼손했어요.',
      'Minou a confiança.',
      '',
    ],
    [
      '간과하다',
      'gangwahada',
      'deixar passar',
      'polido:간과해요|passado:간과했어요',
      '중요한 점을 간과했어요.',
      'Deixou passar um ponto importante.',
      '',
    ],
    [
      '다루다',
      'darutda',
      'tratar de / lidar com',
      'polido:다뤄요|passado:다뤘어요',
      '세 가지 위험을 다뤄요.',
      'Trata de três riscos.',
      '',
    ],
    [
      '수반하다',
      'subanhada',
      'acarretar',
      'polido:수반해요|passado:수반했어요',
      '추가 비용을 수반해요.',
      'Acarreta custos extras.',
      '',
    ],
    [
      '준수하다',
      'junsuhada',
      'cumprir',
      'polido:준수해요|passado:준수했어요',
      '규칙을 준수해요.',
      'Cumpre as regras.',
      'Registro formal.',
    ],
    [
      '능가하다',
      'neunggahada',
      'superar',
      'polido:능가해요|passado:능가했어요',
      '이점이 위험을 능가해요.',
      'Os benefícios superam os riscos.',
      '',
    ],
    [
      '활용하다',
      'hwaryonghada',
      'aproveitar',
      'polido:활용해요|passado:활용했어요',
      '현지 지식을 활용했어요.',
      'Aproveitou o conhecimento local.',
      '',
    ],
  ],
  C1: [
    [
      '입증하다',
      'ipjeunghada',
      'comprovar',
      'polido:입증해요|passado:입증했어요',
      '주장을 입증하지 못했어요.',
      'Não comprovou a alegação.',
      '',
    ],
    [
      '조화시키다',
      'johwasikida',
      'conciliar',
      'polido:조화시켜요|passado:조화시켰어요',
      '두 입장을 조화시켜요.',
      'Concilia as duas posições.',
      '',
    ],
    [
      '저해하다',
      'jeohaehada',
      'impedir',
      'polido:저해해요|passado:저해했어요',
      '예산 삭감이 시험을 저해해요.',
      'Cortes impedem os testes.',
      '',
    ],
    [
      '완화하다',
      'wanhwahada',
      'mitigar',
      'polido:완화해요|passado:완화했어요',
      '위험을 완화해요.',
      'Mitiga o risco.',
      '',
    ],
    [
      '우선하다',
      'useonhada',
      'priorizar',
      'polido:우선해요|passado:우선했어요',
      '안전을 우선해요.',
      'Prioriza a segurança.',
      '',
    ],
    [
      '정당화하다',
      'jeongdanghwahada',
      'justificar',
      'polido:정당화해요|passado:정당화했어요',
      '그 결정을 정당화할 수 없어요.',
      'Não dá para justificar essa decisão.',
      '',
    ],
    [
      '뒷받침하다',
      'dwitbatchimhada',
      'sustentar / embasar',
      'polido:뒷받침해요|passado:뒷받침했어요',
      '세 원칙이 뒷받침해요.',
      'Três princípios sustentam.',
      '',
    ],
    [
      '체념하다',
      'chenyeomhada',
      'conformar-se',
      'polido:체념해요|passado:체념했어요',
      '결과에 체념했어요.',
      'Conformou-se com o resultado.',
      '',
    ],
  ],
  C2: [
    [
      '뒤집다',
      'dwijipda',
      'reverter / desmentir',
      'polido:뒤집어요|passado:뒤집었어요',
      '통설을 뒤집는 발견.',
      'Uma descoberta que reverte o consenso.',
      '',
    ],
    [
      '얼버무리다',
      'eolbeomurida',
      'usar de evasivas',
      'polido:얼버무려요|passado:얼버무렸어요',
      '장관은 얼버무렸어요.',
      'O ministro usou de evasivas.',
      '',
    ],
    [
      '호도하다',
      'hodohada',
      'iludir / maquiar',
      'polido:호도해요|passado:호도했어요',
      '실패를 호도해요.',
      'Maquia o fracasso.',
      '',
    ],
    [
      '생략하다',
      'saengnyakhada',
      'omitir / dispensar',
      'polido:생략해요|passado:생략했어요',
      '절차를 생략해요.',
      'Dispensa o procedimento.',
      '',
    ],
    [
      '용인하다',
      'yonginhada',
      'tolerar',
      'polido:용인해요|passado:용인했어요',
      '지연을 용인하지 않아요.',
      'Não tolera atraso.',
      '',
    ],
    [
      '익숙해지다',
      'iksukhaejida',
      'habituar-se',
      'polido:익숙해져요|passado:익숙해졌어요',
      '비판에 익숙해졌어요.',
      'Habituou-se às críticas.',
      '',
    ],
    [
      '누그러뜨리다',
      'nugureotteurida',
      'suavizar',
      'polido:누그러뜨려요|passado:누그러뜨렸어요',
      '표현을 누그러뜨려요.',
      'Suaviza a expressão.',
      '',
    ],
    [
      '내세우다',
      'naeseuda',
      'alegar / apresentar',
      'polido:내세워요|passado:내세웠어요',
      '건강상의 이유를 내세웠어요.',
      'Alegou motivos de saúde.',
      '',
    ],
  ],
};

const ZH: VerbMap = {
  A1: [
    [
      '是',
      'shì',
      'ser',
      'presente:是|negativo:不是|passado:é invariável',
      '我是学生。',
      'Eu sou estudante.',
      'Não se usa com adjetivo: "我很高", não "我是高".',
    ],
    [
      '有',
      'yǒu',
      'ter / haver',
      'presente:有|negativo:没有',
      '我有两个孩子。',
      'Tenho dois filhos.',
      'A negação é 没有, nunca 不有.',
    ],
    [
      '去',
      'qù',
      'ir',
      'presente:去|passado:去了|negativo:不去',
      '我去公司。',
      'Vou à empresa.',
      '',
    ],
    [
      '做',
      'zuò',
      'fazer',
      'presente:做|passado:做了',
      '你星期天做什么？',
      'O que você faz no domingo?',
      '',
    ],
    [
      '要',
      'yào',
      'querer / precisar',
      'presente:要|negativo:不要',
      '我要学中文。',
      'Quero aprender chinês.',
      'Também indica futuro próximo.',
    ],
    [
      '能',
      'néng',
      'poder / conseguir',
      'presente:能|negativo:不能',
      '你能再说一遍吗？',
      'Você pode repetir?',
      'Capacidade; permissão usa 可以.',
    ],
    [
      '说',
      'shuō',
      'falar / dizer',
      'presente:说|passado:说了',
      '你说葡萄牙语吗？',
      'Você fala português?',
      '',
    ],
    [
      '喜欢',
      'xǐhuān',
      'gostar de',
      'presente:喜欢|negativo:不喜欢',
      '我喜欢咖啡。',
      'Gosto de café.',
      'Sem preposição depois.',
    ],
  ],
  A2: [
    [
      '带',
      'dài',
      'trazer / levar',
      'presente:带|passado:带了',
      '明天带上文件。',
      'Traga os documentos amanhã.',
      '',
    ],
    [
      '出去',
      'chūqù',
      'sair',
      'presente:出去|passado:出去了',
      '我八点出门。',
      'Saio às oito.',
      'Complemento direcional.',
    ],
    ['付', 'fù', 'pagar', 'presente:付|passado:付了', '我用卡付。', 'Pago com cartão.', ''],
    [
      '等',
      'děng',
      'esperar',
      'presente:等|passado:等了',
      '请等一下。',
      'Espere um pouco, por favor.',
      '',
    ],
    [
      '觉得',
      'juéde',
      'achar / sentir',
      'presente:觉得|negativo:不觉得',
      '我觉得今天好多了。',
      'Acho que hoje está bem melhor.',
      'Introduz opinião.',
    ],
    [
      '变成',
      'biànchéng',
      'tornar-se',
      'presente:变成|passado:变成了',
      '他变成了医生。',
      'Ele se tornou médico.',
      '',
    ],
    [
      '试',
      'shì',
      'tentar / experimentar',
      'presente:试|passado:试了',
      '试着早点来。',
      'Tente vir cedo.',
      '试着 + verbo.',
    ],
    [
      '决定',
      'juédìng',
      'decidir',
      'presente:决定|passado:决定了',
      '下周决定。',
      'Decido semana que vem.',
      '',
    ],
  ],
  B1: [
    [
      '能够',
      'nénggòu',
      'conseguir',
      'presente:能够|negativo:不能够',
      '她能够按时完成。',
      'Ela conseguiu terminar no prazo.',
      'Mais formal que 能.',
    ],
    [
      '指出',
      'zhǐchū',
      'apontar',
      'presente:指出|passado:指出了',
      '他指出了一个错误。',
      'Ele apontou um erro.',
      '',
    ],
    [
      '避免',
      'bìmiǎn',
      'evitar',
      'presente:避免|negativo:不避免',
      '避免使用长句。',
      'Evite usar frases longas.',
      '',
    ],
    [
      '抱怨',
      'bàoyuàn',
      'reclamar',
      'presente:抱怨|passado:抱怨了',
      '他们抱怨噪音。',
      'Reclamaram do barulho.',
      '',
    ],
    [
      '意识到',
      'yìshí dào',
      'dar-se conta',
      'presente:意识到|passado:意识到了',
      '我意识到我错了。',
      'Percebi que errei.',
      'Complemento de resultado 到.',
    ],
    [
      '期待',
      'qīdài',
      'esperar (prever)',
      'presente:期待|passado:期待了',
      '我们期待回复。',
      'Esperamos resposta.',
      '',
    ],
    [
      '提高',
      'tígāo',
      'melhorar / elevar',
      'presente:提高|passado:提高了',
      '我的写作提高了。',
      'Minha escrita melhorou.',
      '',
    ],
    [
      '难以',
      'nányǐ',
      'ter dificuldade em',
      'presente:难以|uso:难以 + verbo',
      '难以理解语法。',
      'É difícil entender a gramática.',
      'Registro escrito.',
    ],
  ],
  B2: [
    [
      '承认',
      'chéngrèn',
      'reconhecer / admitir',
      'presente:承认|passado:承认了',
      '他承认了错误。',
      'Ele admitiu o erro.',
      '',
    ],
    [
      '削弱',
      'xuēruò',
      'minar',
      'presente:削弱|passado:削弱了',
      '延误削弱了信任。',
      'O atraso minou a confiança.',
      '',
    ],
    [
      '忽略',
      'hūlüè',
      'deixar passar',
      'presente:忽略|passado:忽略了',
      '我们忽略了一个细节。',
      'Deixamos passar um detalhe.',
      '',
    ],
    [
      '涉及',
      'shèjí',
      'abordar / envolver',
      'presente:涉及|passado:涉及了',
      '报告涉及三个风险。',
      'O relatório aborda três riscos.',
      '',
    ],
    [
      '导致',
      'dǎozhì',
      'acarretar / levar a',
      'presente:导致|passado:导致了',
      '这会导致额外成本。',
      'Isso acarreta custos extras.',
      'Quase sempre com consequência negativa.',
    ],
    [
      '遵守',
      'zūnshǒu',
      'cumprir',
      'presente:遵守|passado:遵守了',
      '我们必须遵守规则。',
      'Precisamos cumprir as regras.',
      '',
    ],
    [
      '超过',
      'chāoguò',
      'superar',
      'presente:超过|passado:超过了',
      '好处超过风险。',
      'Os benefícios superam os riscos.',
      '',
    ],
    [
      '利用',
      'lìyòng',
      'aproveitar',
      'presente:利用|passado:利用了',
      '他们利用了本地知识。',
      'Aproveitaram o conhecimento local.',
      '',
    ],
  ],
  C1: [
    [
      '证实',
      'zhèngshí',
      'comprovar',
      'presente:证实|passado:证实了',
      '他无法证实这一说法。',
      'Não conseguiu comprovar a alegação.',
      '',
    ],
    [
      '调和',
      'tiáohé',
      'conciliar',
      'presente:调和|passado:调和了',
      '很难调和两种说法。',
      'É difícil conciliar as duas versões.',
      '',
    ],
    [
      '阻碍',
      'zǔ’ài',
      'impedir',
      'presente:阻碍|passado:阻碍了',
      '削减阻碍了测试。',
      'Cortes impediram os testes.',
      '',
    ],
    [
      '缓解',
      'huǎnjiě',
      'mitigar',
      'presente:缓解|passado:缓解了',
      '这些措施缓解了风险。',
      'Essas medidas mitigaram o risco.',
      '',
    ],
    [
      '优先',
      'yōuxiān',
      'priorizar',
      'presente:优先|uso:优先考虑',
      '优先考虑安全。',
      'Prioriza a segurança.',
      '',
    ],
    [
      '论证',
      'lùnzhèng',
      'argumentar / demonstrar',
      'presente:论证|passado:论证了',
      '论证这个决定。',
      'Argumenta essa decisão.',
      '',
    ],
    [
      '支撑',
      'zhīchēng',
      'sustentar',
      'presente:支撑|passado:支撑了',
      '三个原则支撑这个模型。',
      'Três princípios sustentam o modelo.',
      '',
    ],
    [
      '妥协',
      'tuǒxié',
      'conformar-se / ceder',
      'presente:妥协|passado:妥协了',
      '他向结果妥协了。',
      'Cedeu ao resultado.',
      '',
    ],
  ],
  C2: [
    [
      '推翻',
      'tuīfān',
      'derrubar / reverter',
      'presente:推翻|passado:推翻了',
      '推翻了传统观点。',
      'Derrubou a visão tradicional.',
      '',
    ],
    [
      '含糊其辞',
      'hánhú qící',
      'usar de evasivas',
      'uso:成语|função:predicado',
      '部长含糊其辞。',
      'O ministro usou de evasivas.',
      'Chengyu de quatro caracteres.',
    ],
    [
      '粉饰',
      'fěnshì',
      'maquiar / dourar',
      'presente:粉饰|passado:粉饰了',
      '粉饰失败。',
      'Maquia o fracasso.',
      '',
    ],
    [
      '省去',
      'shěngqù',
      'dispensar / poupar',
      'presente:省去|passado:省去了',
      '省去一道手续。',
      'Dispensa um procedimento.',
      '',
    ],
    [
      '容忍',
      'róngrěn',
      'tolerar',
      'presente:容忍|negativo:不容忍',
      '不容忍延误。',
      'Não tolera atraso.',
      '',
    ],
    [
      '习惯于',
      'xíguàn yú',
      'habituar-se a',
      'presente:习惯于|passado:习惯了',
      '他习惯了批评。',
      'Habituou-se às críticas.',
      '',
    ],
    [
      '淡化',
      'dànhuà',
      'atenuar / diluir',
      'presente:淡化|passado:淡化了',
      '淡化这个说法。',
      'Atenua essa afirmação.',
      '',
    ],
    [
      '援引',
      'yuányǐn',
      'invocar / citar',
      'presente:援引|passado:援引了',
      '援引健康原因。',
      'Invocou motivos de saúde.',
      '',
    ],
  ],
};

/* ================================================================== *
 * Registro
 * ================================================================== */

const VERB_CATALOG: Record<LanguageCode, VerbMap> = {
  en: EN,
  es: ES,
  fr: FR,
  it: IT,
  de: DE,
  ja: JA,
  ko: KO,
  zh: ZH,
};

/** Verbos de um idioma num nível, já expandidos. */
export function levelVerbs(language: LanguageCode, level: CefrLevel): VerbEntry[] {
  const raw = VERB_CATALOG[language]?.[level];
  return raw ? expand(raw) : [];
}

/** Todos os verbos de um idioma, do A1 ao C2. */
export function allVerbs(language: LanguageCode): VerbEntry[] {
  const levels: CefrLevel[] = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];
  return levels.flatMap((level) => levelVerbs(language, level));
}

/** Total catalogado — usado em documentação e testes. */
export function verbCount(): number {
  const levels: CefrLevel[] = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];
  return Object.keys(VERB_CATALOG).reduce(
    (total, language) =>
      total +
      levels.reduce(
        (sum, level) => sum + levelVerbs(language as LanguageCode, level).length,
        0,
      ),
    0,
  );
}
