/**
 * Catálogo de verbos por nível
 * =============================
 *
 * ## Por que verbo merece catálogo próprio
 *
 * Verbo não é "mais uma palavra". Numa frase, ele é a peça que carrega tempo,
 * pessoa, modo e — em metade dos idiomas daqui — regência. Um aluno que sabe
 * 500 substantivos e 20 verbos **não fala**; um que sabe 100 substantivos e
 * 80 verbos conversa. É por isso que este arquivo existe separado do
 * vocabulário geral e aparece em seção própria na apostila.
 *
 * ## O que cada verbete carrega, e por quê
 *
 *  - `infinitive` — a forma de dicionário.
 *  - `romanization` — obrigatória em ja/ko/zh: sem ela o aluno não consegue
 *    nem repetir o verbo em voz alta.
 *  - `meaning` — o sentido em português, com as acepções que importam.
 *  - `forms` — as três formas que mais aparecem na fala real. Não é a
 *    conjugação completa de propósito: uma tabela de 6 pessoas × 8 tempos é
 *    material de consulta, não de aprendizado, e afoga o iniciante. Aqui vão
 *    as formas que ele vai **usar hoje**.
 *  - `example` / `exampleTranslation` — o verbo em contexto. Verbo isolado não
 *    se fixa: o que a memória guarda é a frase.
 *  - `note` — a armadilha de uso, quando existe. É onde mora a diferença entre
 *    conhecer o verbo e usá-lo certo.
 *
 * ## Progressão
 *
 * Os verbos mudam a cada nível e nunca se repetem — há teste garantindo. A1
 * traz os auxiliares e os de altíssima frequência; C1/C2 trazem os de registro
 * formal e os que exigem escolha entre sinônimos próximos.
 */

import type { CefrLevel, LanguageCode } from '@/domain/types';
import { extraVerbsRaw } from './verbs-extra';

export type VerbEntry = {
  infinitive: string;
  romanization: string | null;
  meaning: string;
  /** Formas de uso mais frequente, rotuladas. */
  forms: { person: string; form: string }[];
  example: string;
  exampleTranslation: string;
  note: string | null;
};

/** Formato compacto: [infinitivo, romanização, sentido, formas, exemplo, tradução, nota] */
type Raw = [string, string, string, string, string, string, string];

/**
 * Expande `"eu:am|ele:is|passado:was"` na lista de formas.
 * Compacto porque é dado, não código — escrever objeto quadruplicaria o arquivo.
 */
function parseForms(spec: string): { person: string; form: string }[] {
  return spec
    .split('|')
    .filter(Boolean)
    .map((pair) => {
      const [person = '', form = ''] = pair.split(':');
      return { person: person.trim(), form: form.trim() };
    });
}

function expand(raw: Raw[]): VerbEntry[] {
  return raw.map(([infinitive, romanization, meaning, forms, example, translation, note]) => ({
    infinitive,
    romanization: romanization || null,
    meaning,
    forms: parseForms(forms),
    example,
    exampleTranslation: translation,
    note: note || null,
  }));
}

type VerbMap = Partial<Record<CefrLevel, Raw[]>>;

/* ================================================================== *
 * Inglês
 * ================================================================== */

const EN: VerbMap = {
  A1: [
    [
      'to be',
      '',
      'ser / estar',
      'eu:am|ele/ela:is|nós/eles:are|passado:was / were',
      'I am a student. She is tired.',
      'Eu sou estudante. Ela está cansada.',
      'Cobre "ser" e "estar" ao mesmo tempo — o contexto decide qual é.',
    ],
    [
      'to have',
      '',
      'ter / possuir',
      'eu:have|ele/ela:has|passado:had',
      'They have two children.',
      'Eles têm dois filhos.',
      'Não se usa para idade: "I am 25", nunca "I have 25".',
    ],
    [
      'to go',
      '',
      'ir',
      'eu:go|ele/ela:goes|passado:went|particípio:gone',
      'We go to the beach on Sundays.',
      'Vamos à praia aos domingos.',
      '"Go to" com lugar, mas "go home" sem preposição.',
    ],
    [
      'to do',
      '',
      'fazer',
      'eu:do|ele/ela:does|passado:did|particípio:done',
      'What do you do for work?',
      'O que você faz da vida?',
      'Também é o auxiliar de perguntas e negativas.',
    ],
    [
      'to want',
      '',
      'querer',
      'eu:want|ele/ela:wants|passado:wanted',
      'I want to learn English.',
      'Quero aprender inglês.',
      'Sempre seguido de infinitivo com "to".',
    ],
    [
      'to like',
      '',
      'gostar de',
      'eu:like|ele/ela:likes|passado:liked',
      'She likes cooking.',
      'Ela gosta de cozinhar.',
      'Sem preposição depois: "like coffee", não "like of coffee".',
    ],
    [
      'to need',
      '',
      'precisar de',
      'eu:need|ele/ela:needs|passado:needed',
      'I need help.',
      'Preciso de ajuda.',
      'Não leva preposição: "need help", não "need of help".',
    ],
    [
      'to speak',
      '',
      'falar',
      'eu:speak|ele/ela:speaks|passado:spoke|particípio:spoken',
      'Do you speak Portuguese?',
      'Você fala português?',
      '"Speak" para idiomas; "talk" para conversar com alguém.',
    ],
  ],
  A2: [
    [
      'to bring',
      '',
      'trazer',
      'presente:bring|passado:brought|particípio:brought',
      'Bring your documents tomorrow.',
      'Traga seus documentos amanhã.',
      '"Bring" é trazer para cá; "take" é levar para lá.',
    ],
    [
      'to leave',
      '',
      'sair / deixar',
      'presente:leave|passado:left|particípio:left',
      'I left my keys at home.',
      'Deixei minhas chaves em casa.',
      'Dois sentidos bem diferentes no mesmo verbo.',
    ],
    [
      'to buy',
      '',
      'comprar',
      'presente:buy|passado:bought|particípio:bought',
      'She bought a new phone.',
      'Ela comprou um celular novo.',
      '',
    ],
    [
      'to pay',
      '',
      'pagar',
      'presente:pay|passado:paid|particípio:paid',
      'I paid by card.',
      'Paguei com cartão.',
      'Paga-se "for" a coisa: "pay for the meal".',
    ],
    [
      'to wait',
      '',
      'esperar (aguardar)',
      'presente:wait|passado:waited',
      'We waited for an hour.',
      'Esperamos por uma hora.',
      'Sempre "wait for", nunca "wait" sozinho com objeto.',
    ],
    [
      'to feel',
      '',
      'sentir / sentir-se',
      'presente:feel|passado:felt|particípio:felt',
      'I feel much better today.',
      'Me sinto bem melhor hoje.',
      'Não leva pronome reflexivo: "I feel", não "I feel myself".',
    ],
    [
      'to happen',
      '',
      'acontecer',
      'presente:happens|passado:happened',
      'What happened yesterday?',
      'O que aconteceu ontem?',
      'Nunca tem sujeito pessoal.',
    ],
    [
      'to try',
      '',
      'tentar / experimentar',
      'presente:try|passado:tried|particípio:tried',
      'Try to arrive early.',
      'Tente chegar cedo.',
      '"Try to do" é tentar; "try doing" é experimentar.',
    ],
  ],
  B1: [
    [
      'to manage',
      '',
      'conseguir / administrar',
      'presente:manage|passado:managed',
      'She managed to finish on time.',
      'Ela conseguiu terminar a tempo.',
      '"Manage to" implica esforço e sucesso.',
    ],
    [
      'to afford',
      '',
      'ter condições de pagar',
      'presente:afford|passado:afforded',
      "I can't afford it right now.",
      'Não tenho condições agora.',
      'Quase sempre com "can" ou "could".',
    ],
    [
      'to suggest',
      '',
      'sugerir',
      'presente:suggest|passado:suggested',
      'He suggested meeting on Friday.',
      'Ele sugeriu nos encontrarmos na sexta.',
      'Seguido de gerúndio, não de infinitivo.',
    ],
    [
      'to avoid',
      '',
      'evitar',
      'presente:avoid|passado:avoided',
      'Avoid using long sentences.',
      'Evite usar frases longas.',
      'Sempre com gerúndio depois.',
    ],
    [
      'to complain',
      '',
      'reclamar',
      'presente:complain|passado:complained',
      'They complained about the noise.',
      'Eles reclamaram do barulho.',
      'Reclama-se "about" algo.',
    ],
    [
      'to realize',
      '',
      'perceber / dar-se conta',
      'presente:realize|passado:realized',
      'I realized I was wrong.',
      'Percebi que estava errado.',
      'Falso amigo: não é "realizar" no sentido de executar.',
    ],
    [
      'to expect',
      '',
      'esperar (prever)',
      'presente:expect|passado:expected',
      'We expect a reply by Friday.',
      'Esperamos resposta até sexta.',
      'Diferente de "wait": aqui é prever, não aguardar.',
    ],
    [
      'to improve',
      '',
      'melhorar',
      'presente:improve|passado:improved',
      'My writing improved a lot.',
      'Minha escrita melhorou muito.',
      'Serve como transitivo e intransitivo.',
    ],
  ],
  B2: [
    [
      'to acknowledge',
      '',
      'reconhecer / admitir',
      'presente:acknowledge|passado:acknowledged',
      'He acknowledged the mistake.',
      'Ele reconheceu o erro.',
      'Registro mais formal que "admit".',
    ],
    [
      'to undermine',
      '',
      'minar / enfraquecer',
      'presente:undermine|passado:undermined',
      'The delay undermined our credibility.',
      'O atraso minou nossa credibilidade.',
      '',
    ],
    [
      'to overlook',
      '',
      'deixar passar / ignorar',
      'presente:overlook|passado:overlooked',
      'We overlooked one detail.',
      'Deixamos passar um detalhe.',
      'Também significa "ter vista para".',
    ],
    [
      'to enhance',
      '',
      'aprimorar / realçar',
      'presente:enhance|passado:enhanced',
      'The changes enhanced performance.',
      'As mudanças aprimoraram o desempenho.',
      'Mais forte e mais formal que "improve".',
    ],
    [
      'to address',
      '',
      'abordar / tratar de',
      'presente:address|passado:addressed',
      'The report addresses three risks.',
      'O relatório aborda três riscos.',
      'Nada a ver com endereço, aqui.',
    ],
    [
      'to entail',
      '',
      'implicar / acarretar',
      'presente:entails|passado:entailed',
      'This entails extra costs.',
      'Isso acarreta custos extras.',
      '',
    ],
    [
      'to comply',
      '',
      'cumprir / estar em conformidade',
      'presente:comply|passado:complied',
      'We must comply with the rules.',
      'Precisamos cumprir as regras.',
      'Sempre "comply with".',
    ],
    [
      'to outweigh',
      '',
      'superar (em peso/importância)',
      'presente:outweigh|passado:outweighed',
      'The benefits outweigh the risks.',
      'Os benefícios superam os riscos.',
      '',
    ],
  ],
  C1: [
    [
      'to substantiate',
      '',
      'comprovar / fundamentar',
      'presente:substantiate|passado:substantiated',
      'He failed to substantiate the claim.',
      'Ele não conseguiu comprovar a alegação.',
      'Registro jurídico e acadêmico.',
    ],
    [
      'to reconcile',
      '',
      'conciliar',
      'presente:reconcile|passado:reconciled',
      'It is hard to reconcile both accounts.',
      'É difícil conciliar os dois relatos.',
      '',
    ],
    [
      'to preclude',
      '',
      'inviabilizar / impedir',
      'presente:precludes|passado:precluded',
      'Budget cuts preclude further testing.',
      'Cortes inviabilizam mais testes.',
      'Mais formal que "prevent".',
    ],
    [
      'to mitigate',
      '',
      'mitigar / atenuar',
      'presente:mitigate|passado:mitigated',
      'These measures mitigate the risk.',
      'Essas medidas mitigam o risco.',
      '',
    ],
    [
      'to prevail',
      '',
      'prevalecer',
      'presente:prevail|passado:prevailed',
      'Common sense eventually prevailed.',
      'O bom senso acabou prevalecendo.',
      '',
    ],
    [
      'to warrant',
      '',
      'justificar / merecer',
      'presente:warrants|passado:warranted',
      'The issue warrants further study.',
      'A questão merece mais estudo.',
      'Nada a ver com garantia, neste uso.',
    ],
    [
      'to underpin',
      '',
      'sustentar / embasar',
      'presente:underpins|passado:underpinned',
      'Three principles underpin the model.',
      'Três princípios sustentam o modelo.',
      '',
    ],
    [
      'to reconcile oneself',
      '',
      'conformar-se',
      'presente:reconcile myself|passado:reconciled myself',
      'She reconciled herself to the outcome.',
      'Ela se conformou com o resultado.',
      '',
    ],
  ],
  C2: [
    [
      'to belie',
      '',
      'desmentir / contradizer',
      'presente:belies|passado:belied',
      'His calm tone belied his anger.',
      'O tom calmo dele desmentia sua raiva.',
      'Sempre indica contradição entre aparência e realidade.',
    ],
    [
      'to equivocate',
      '',
      'usar de evasivas',
      'presente:equivocate|passado:equivocated',
      'The minister equivocated for an hour.',
      'O ministro usou de evasivas por uma hora.',
      '',
    ],
    [
      'to eschew',
      '',
      'evitar deliberadamente',
      'presente:eschew|passado:eschewed',
      'The author eschews jargon.',
      'O autor evita jargão.',
      'Registro literário; raro na fala.',
    ],
    [
      'to obviate',
      '',
      'tornar desnecessário',
      'presente:obviates|passado:obviated',
      'This obviates the need for a second review.',
      'Isso torna desnecessária uma segunda revisão.',
      '',
    ],
    [
      'to countenance',
      '',
      'tolerar / admitir',
      'presente:countenance|passado:countenanced',
      'They would not countenance delay.',
      'Eles não admitiriam atraso.',
      '',
    ],
    [
      'to inure',
      '',
      'habituar (a algo penoso)',
      'presente:inured|passado:inured',
      'He became inured to criticism.',
      'Ele se habituou às críticas.',
      'Quase sempre na voz passiva.',
    ],
    [
      'to gloss over',
      '',
      'passar por cima de',
      'presente:glosses over|passado:glossed over',
      'The report glosses over the failures.',
      'O relatório passa por cima dos fracassos.',
      '',
    ],
    [
      'to hedge',
      '',
      'atenuar / não se comprometer',
      'presente:hedges|passado:hedged',
      'The study hedges its conclusions.',
      'O estudo atenua suas conclusões.',
      'Essencial no registro acadêmico inglês.',
    ],
  ],
};

/* ================================================================== *
 * Espanhol
 * ================================================================== */

const ES: VerbMap = {
  A1: [
    [
      'ser',
      '',
      'ser (característica, identidade)',
      'yo:soy|él/ella:es|nosotros:somos|pasado:fui',
      'Soy brasileño.',
      'Sou brasileiro.',
      'Para característica permanente; estado usa "estar".',
    ],
    [
      'estar',
      '',
      'estar (estado, lugar)',
      'yo:estoy|él/ella:está|nosotros:estamos|pasado:estuve',
      'Estoy cansado.',
      'Estou cansado.',
      '"Estoy casado" — casado é estado em espanhol.',
    ],
    [
      'tener',
      '',
      'ter',
      'yo:tengo|él/ella:tiene|nosotros:tenemos|pasado:tuve',
      'Tengo veinticinco años.',
      'Tenho vinte e cinco anos.',
      'Usa-se para idade, como em português.',
    ],
    [
      'hacer',
      '',
      'fazer',
      'yo:hago|él/ella:hace|pasado:hice',
      '¿Qué haces los domingos?',
      'O que você faz aos domingos?',
      '',
    ],
    [
      'ir',
      '',
      'ir',
      'yo:voy|él/ella:va|nosotros:vamos|pasado:fui',
      'Voy al trabajo en metro.',
      'Vou ao trabalho de metrô.',
      '"Ir a" + infinitivo forma o futuro próximo.',
    ],
    [
      'querer',
      '',
      'querer / amar',
      'yo:quiero|él/ella:quiere|pasado:quise',
      'Quiero aprender español.',
      'Quero aprender espanhol.',
      'Com pessoa, também significa amar.',
    ],
    [
      'gustar',
      '',
      'agradar (gostar)',
      'me:gusta|me:gustan|pasado:gustó',
      'Me gustan los libros.',
      'Gosto de livros.',
      'Estrutura invertida: quem gosta é objeto indireto.',
    ],
    [
      'hablar',
      '',
      'falar',
      'yo:hablo|él/ella:habla|pasado:hablé',
      '¿Hablas portugués?',
      'Você fala português?',
      '',
    ],
  ],
  A2: [
    [
      'traer',
      '',
      'trazer',
      'yo:traigo|él/ella:trae|pasado:traje',
      'Trae los documentos mañana.',
      'Traga os documentos amanhã.',
      'Irregular na primeira pessoa.',
    ],
    [
      'salir',
      '',
      'sair',
      'yo:salgo|él/ella:sale|pasado:salí',
      'Salgo de casa a las ocho.',
      'Saio de casa às oito.',
      'Irregular na primeira pessoa.',
    ],
    [
      'pagar',
      '',
      'pagar',
      'yo:pago|él/ella:paga|pasado:pagué',
      'Pagué con tarjeta.',
      'Paguei com cartão.',
      'No pretérito, o "g" vira "gu".',
    ],
    [
      'esperar',
      '',
      'esperar (aguardar e ter esperança)',
      'yo:espero|pasado:esperé',
      'Espera un rato, por favor.',
      'Espere um momento, por favor.',
      'Com subjuntivo, significa ter esperança.',
    ],
    [
      'sentirse',
      '',
      'sentir-se',
      'yo:me siento|él:se siente|pasado:me sentí',
      'Hoy me siento mucho mejor.',
      'Hoje me sinto bem melhor.',
      'Reflexivo, ao contrário do inglês.',
    ],
    [
      'pasar',
      '',
      'passar / acontecer',
      'presente:pasa|pasado:pasó',
      '¿Qué pasó ayer?',
      'O que aconteceu ontem?',
      'Um dos verbos mais polissêmicos do espanhol.',
    ],
    [
      'intentar',
      '',
      'tentar',
      'yo:intento|pasado:intenté',
      'Intenta llegar temprano.',
      'Tente chegar cedo.',
      '',
    ],
    [
      'quedar',
      '',
      'ficar / combinar',
      'yo:quedo|pasado:quedé',
      'Quedamos a las siete.',
      'Combinamos às sete.',
      '"Quedarse" é permanecer; "quedar" é combinar.',
    ],
  ],
  B1: [
    [
      'lograr',
      '',
      'conseguir',
      'yo:logro|pasado:logré',
      'Logró terminar a tiempo.',
      'Ele conseguiu terminar a tempo.',
      'Implica esforço e êxito.',
    ],
    [
      'permitirse',
      '',
      'ter condições de',
      'yo:me permito|pasado:me permití',
      'No puedo permitirme ese viaje.',
      'Não tenho condições dessa viagem.',
      '',
    ],
    [
      'sugerir',
      '',
      'sugerir',
      'yo:sugiero|pasado:sugerí',
      'Sugiero que vengas temprano.',
      'Sugiro que você venha cedo.',
      'Exige subjuntivo na oração seguinte.',
    ],
    [
      'evitar',
      '',
      'evitar',
      'yo:evito|pasado:evité',
      'Evita usar frases largas.',
      'Evite usar frases longas.',
      '',
    ],
    [
      'quejarse',
      '',
      'reclamar',
      'yo:me quejo|pasado:me quejé',
      'Se quejaron del ruido.',
      'Reclamaram do barulho.',
      'Reclama-se "de" algo.',
    ],
    [
      'darse cuenta',
      '',
      'perceber',
      'yo:me doy cuenta|pasado:me di cuenta',
      'Me di cuenta de que estaba mal.',
      'Percebi que estava errado.',
      'Sempre com "de que".',
    ],
    [
      'soler',
      '',
      'costumar',
      'yo:suelo|él:suele|pasado:solía',
      'Suelo estudiar por la noche.',
      'Costumo estudar à noite.',
      'Não existe em inglês; muito frequente.',
    ],
    [
      'mejorar',
      '',
      'melhorar',
      'yo:mejoro|pasado:mejoré',
      'Mi escritura mejoró mucho.',
      'Minha escrita melhorou muito.',
      '',
    ],
  ],
  B2: [
    [
      'reconocer',
      '',
      'reconhecer / admitir',
      'yo:reconozco|pasado:reconocí',
      'Reconoció su error.',
      'Ele reconheceu o erro.',
      'Irregular na primeira pessoa.',
    ],
    [
      'socavar',
      '',
      'minar',
      'presente:socava|pasado:socavó',
      'El retraso socavó la confianza.',
      'O atraso minou a confiança.',
      '',
    ],
    [
      'pasar por alto',
      '',
      'deixar passar',
      'presente:paso por alto|pasado:pasé por alto',
      'Pasamos por alto un detalle.',
      'Deixamos passar um detalhe.',
      '',
    ],
    [
      'abordar',
      '',
      'abordar / tratar de',
      'yo:abordo|pasado:abordé',
      'El informe aborda tres riesgos.',
      'O relatório aborda três riscos.',
      '',
    ],
    [
      'implicar',
      '',
      'implicar / acarretar',
      'presente:implica|pasado:implicó',
      'Esto implica costes extra.',
      'Isso acarreta custos extras.',
      '',
    ],
    [
      'cumplir',
      '',
      'cumprir',
      'yo:cumplo|pasado:cumplí',
      'Debemos cumplir con las normas.',
      'Devemos cumprir as normas.',
      'Também se usa para idade: "cumplir años".',
    ],
    [
      'superar',
      '',
      'superar',
      'yo:supero|pasado:superé',
      'Los beneficios superan los riesgos.',
      'Os benefícios superam os riscos.',
      '',
    ],
    [
      'aprovechar',
      '',
      'aproveitar',
      'yo:aprovecho|pasado:aproveché',
      'Aprovecharon el conocimiento local.',
      'Aproveitaram o conhecimento local.',
      '',
    ],
  ],
  C1: [
    [
      'fundamentar',
      '',
      'fundamentar',
      'yo:fundamento|pasado:fundamenté',
      'No pudo fundamentar la acusación.',
      'Não conseguiu fundamentar a acusação.',
      '',
    ],
    [
      'conciliar',
      '',
      'conciliar',
      'yo:concilio|pasado:concilié',
      'Cuesta conciliar ambas versiones.',
      'Custa conciliar as duas versões.',
      '',
    ],
    [
      'impedir',
      '',
      'impedir',
      'yo:impido|pasado:impedí',
      'Los recortes impiden nuevas pruebas.',
      'Os cortes impedem novos testes.',
      'Exige subjuntivo depois.',
    ],
    [
      'mitigar',
      '',
      'mitigar',
      'presente:mitiga|pasado:mitigó',
      'Estas medidas mitigan el riesgo.',
      'Essas medidas mitigam o risco.',
      '',
    ],
    [
      'imperar',
      '',
      'imperar / prevalecer',
      'presente:impera|pasado:imperó',
      'Al final imperó el sentido común.',
      'No fim, imperou o bom senso.',
      '',
    ],
    [
      'ameritar',
      '',
      'merecer / justificar',
      'presente:amerita|pasado:ameritó',
      'El caso amerita más estudio.',
      'O caso merece mais estudo.',
      'Mais comum na América Latina.',
    ],
    [
      'sustentar',
      '',
      'sustentar / embasar',
      'yo:sustento|pasado:sustenté',
      'Tres principios sustentan el modelo.',
      'Três princípios sustentam o modelo.',
      '',
    ],
    [
      'resignarse',
      '',
      'conformar-se',
      'yo:me resigno|pasado:me resigné',
      'Se resignó al resultado.',
      'Conformou-se com o resultado.',
      '',
    ],
  ],
  C2: [
    [
      'desmentir',
      '',
      'desmentir',
      'presente:desmiente|pasado:desmintió',
      'Su calma desmentía su enfado.',
      'Sua calma desmentia sua irritação.',
      '',
    ],
    [
      'soslayar',
      '',
      'contornar / driblar',
      'yo:soslayo|pasado:soslayé',
      'El informe soslaya los fracasos.',
      'O relatório contorna os fracassos.',
      '',
    ],
    [
      'rehuir',
      '',
      'esquivar-se de',
      'yo:rehúyo|pasado:rehuí',
      'Rehúye el debate.',
      'Esquiva-se do debate.',
      'Acentuação irregular.',
    ],
    [
      'obviar',
      '',
      'dispensar / evitar',
      'presente:obvia|pasado:obvió',
      'Esto obvia una segunda revisión.',
      'Isso dispensa uma segunda revisão.',
      '',
    ],
    [
      'consentir',
      '',
      'consentir / tolerar',
      'yo:consiento|pasado:consentí',
      'No consentirían el retraso.',
      'Não consentiriam o atraso.',
      '',
    ],
    [
      'curtirse',
      '',
      'endurecer-se (com a experiência)',
      'yo:me curto|pasado:me curtí',
      'Se curtió con las críticas.',
      'Endureceu com as críticas.',
      '',
    ],
    [
      'matizar',
      '',
      'matizar / nuançar',
      'yo:matizo|pasado:maticé',
      'Conviene matizar esa afirmación.',
      'Convém matizar essa afirmação.',
      'Central no discurso acadêmico.',
    ],
    [
      'aducir',
      '',
      'alegar / aduzir',
      'yo:aduzco|pasado:aduje',
      'Adujo razones de salud.',
      'Alegou motivos de saúde.',
      'Registro jurídico e formal.',
    ],
  ],
};

/* ================================================================== *
 * Francês, italiano e alemão
 * ================================================================== */

const FR: VerbMap = {
  A1: [
    [
      'être',
      '',
      'ser / estar',
      'je:suis|il/elle:est|nous:sommes|passé:étais',
      'Je suis étudiant.',
      'Sou estudante.',
      'Auxiliar de vários verbos no passado composto.',
    ],
    [
      'avoir',
      '',
      'ter',
      "j':ai|il/elle:a|nous:avons|passé:avais",
      "J'ai vingt-cinq ans.",
      'Tenho vinte e cinco anos.',
      'Usa-se para idade, como em português.',
    ],
    [
      'aller',
      '',
      'ir',
      'je:vais|il/elle:va|nous:allons|passé:allais',
      'Je vais au travail en métro.',
      'Vou ao trabalho de metrô.',
      '"Aller" + infinitivo forma o futuro próximo.',
    ],
    [
      'faire',
      '',
      'fazer',
      'je:fais|il/elle:fait|nous:faisons|passé:faisais',
      'Que fais-tu le dimanche ?',
      'O que você faz aos domingos?',
      '',
    ],
    [
      'vouloir',
      '',
      'querer',
      'je:veux|il/elle:veut|nous:voulons|passé:voulais',
      'Je veux apprendre le français.',
      'Quero aprender francês.',
      '"Je voudrais" é a forma educada.',
    ],
    [
      'pouvoir',
      '',
      'poder',
      'je:peux|il/elle:peut|nous:pouvons|passé:pouvais',
      'Tu peux répéter ?',
      'Você pode repetir?',
      '',
    ],
    [
      'parler',
      '',
      'falar',
      'je:parle|il/elle:parle|nous:parlons|passé:parlais',
      'Parlez-vous portugais ?',
      'Você fala português?',
      '',
    ],
    [
      'aimer',
      '',
      'gostar de / amar',
      'je:aime|il/elle:aime|passé:aimais',
      "J'aime le café.",
      'Gosto de café.',
      'Com pessoa, significa amar.',
    ],
  ],
  A2: [
    [
      'apporter',
      '',
      'trazer',
      "j':apporte|passé composé:ai apporté",
      'Apporte tes documents demain.',
      'Traga seus documentos amanhã.',
      '"Apporter" coisas; "amener" pessoas.',
    ],
    [
      'partir',
      '',
      'partir / ir embora',
      'je:pars|il:part|passé composé:suis parti',
      'Je pars à huit heures.',
      'Saio às oito.',
      'Passado composto com "être".',
    ],
    [
      'payer',
      '',
      'pagar',
      'je:paie|passé composé:ai payé',
      "J'ai payé par carte.",
      'Paguei com cartão.',
      '',
    ],
    [
      'attendre',
      '',
      'esperar (aguardar)',
      "j':attends|passé composé:ai attendu",
      "J'attends le bus.",
      'Espero o ônibus.',
      'Falso amigo: não é "atender".',
    ],
    [
      'se sentir',
      '',
      'sentir-se',
      'je:me sens|passé composé:me suis senti',
      'Je me sens mieux.',
      'Me sinto melhor.',
      'Reflexivo, com "être" no passado.',
    ],
    [
      'arriver',
      '',
      'chegar / acontecer',
      'il:arrive|passé composé:est arrivé',
      "Qu'est-ce qui est arrivé ?",
      'O que aconteceu?',
      'Dois sentidos; passado com "être".',
    ],
    [
      'essayer',
      '',
      'tentar',
      "j':essaie|passé composé:ai essayé",
      "Essaie d'arriver tôt.",
      'Tente chegar cedo.',
      'Seguido de "de" + infinitivo.',
    ],
    [
      'rester',
      '',
      'ficar / permanecer',
      'je:reste|passé composé:suis resté',
      'Je reste à la maison.',
      'Fico em casa.',
      'Falso amigo: não é "restar".',
    ],
  ],
  B1: [
    [
      'réussir',
      '',
      'conseguir / ter êxito',
      'je:réussis|passé composé:ai réussi',
      'Elle a réussi à finir.',
      'Ela conseguiu terminar.',
      'Seguido de "à" + infinitivo.',
    ],
    [
      'se permettre',
      '',
      'ter condições de',
      'je:me permets|passé:me suis permis',
      'Je ne peux pas me permettre ce voyage.',
      'Não tenho condições dessa viagem.',
      '',
    ],
    [
      'suggérer',
      '',
      'sugerir',
      'je:suggère|passé composé:ai suggéré',
      'Il a suggéré de se voir vendredi.',
      'Ele sugeriu se verem na sexta.',
      '',
    ],
    [
      'éviter',
      '',
      'evitar',
      "j':évite|passé composé:ai évité",
      "Évite d'utiliser des phrases longues.",
      'Evite usar frases longas.',
      '',
    ],
    [
      'se plaindre',
      '',
      'reclamar',
      'je:me plains|passé:me suis plaint',
      'Ils se sont plaints du bruit.',
      'Reclamaram do barulho.',
      'Reclama-se "de" algo.',
    ],
    [
      'se rendre compte',
      '',
      'dar-se conta',
      'je:me rends compte|passé:me suis rendu compte',
      "Je me suis rendu compte de l'erreur.",
      'Dei-me conta do erro.',
      '',
    ],
    [
      'avoir du mal',
      '',
      'ter dificuldade',
      "j':ai du mal|passé:avais du mal",
      "J'ai du mal à comprendre.",
      'Tenho dificuldade em entender.',
      'Locução, não verbo simples.',
    ],
    [
      'améliorer',
      '',
      'melhorar',
      "j':améliore|passé composé:ai amélioré",
      "J'ai amélioré mon écriture.",
      'Melhorei minha escrita.',
      '',
    ],
  ],
  B2: [
    [
      'reconnaître',
      '',
      'reconhecer / admitir',
      'je:reconnais|passé composé:ai reconnu',
      "Il a reconnu qu'il avait tort.",
      'Ele reconheceu que estava errado.',
      '',
    ],
    [
      'saper',
      '',
      'minar',
      'il:sape|passé composé:a sapé',
      'Les retards ont sapé la confiance.',
      'Os atrasos minaram a confiança.',
      '',
    ],
    [
      'négliger',
      '',
      'negligenciar',
      'je:néglige|passé composé:ai négligé',
      'Nous avons négligé un détail.',
      'Negligenciamos um detalhe.',
      '',
    ],
    [
      'aborder',
      '',
      'abordar',
      "j':aborde|passé composé:ai abordé",
      'Le rapport aborde trois risques.',
      'O relatório aborda três riscos.',
      '',
    ],
    [
      'entraîner',
      '',
      'acarretar / treinar',
      'il:entraîne|passé composé:a entraîné',
      'Cela entraîne des coûts.',
      'Isso acarreta custos.',
      'Dois sentidos distantes.',
    ],
    [
      'respecter',
      '',
      'cumprir / respeitar',
      'je:respecte|passé composé:ai respecté',
      'Il faut respecter les règles.',
      'É preciso cumprir as regras.',
      '',
    ],
    [
      "l'emporter sur",
      '',
      'superar / prevalecer sobre',
      "il:l'emporte|passé:l'a emporté",
      "Les avantages l'emportent sur les risques.",
      'As vantagens superam os riscos.',
      '',
    ],
    [
      'tirer parti de',
      '',
      'tirar proveito de',
      'je:tire parti|passé:ai tiré parti',
      'Ils ont tiré parti de leur expérience.',
      'Tiraram proveito da experiência.',
      '',
    ],
  ],
  C1: [
    [
      'étayer',
      '',
      'fundamentar',
      "j':étaie|passé composé:ai étayé",
      "Il n'a pas étayé ses accusations.",
      'Não fundamentou as acusações.',
      '',
    ],
    [
      'concilier',
      '',
      'conciliar',
      'je:concilie|passé composé:ai concilié',
      'Difficile de concilier les deux.',
      'Difícil conciliar os dois.',
      '',
    ],
    [
      'empêcher',
      '',
      'impedir',
      "j':empêche|passé composé:ai empêché",
      'Les coupes empêchent les essais.',
      'Os cortes impedem os testes.',
      'Seguido de "de" + infinitivo.',
    ],
    [
      'atténuer',
      '',
      'atenuar / mitigar',
      "j':atténue|passé composé:ai atténué",
      'Ces mesures atténuent le risque.',
      'Essas medidas atenuam o risco.',
      '',
    ],
    [
      'prévaloir',
      '',
      'prevalecer',
      'il:prévaut|passé composé:a prévalu',
      'Le bon sens a prévalu.',
      'O bom senso prevaleceu.',
      'Conjugação irregular rara.',
    ],
    [
      'justifier',
      '',
      'justificar',
      'je:justifie|passé composé:ai justifié',
      'Le cas justifie une étude.',
      'O caso justifica um estudo.',
      '',
    ],
    [
      'sous-tendre',
      '',
      'sustentar / subjazer',
      'il:sous-tend|passé composé:a sous-tendu',
      'Trois principes sous-tendent le modèle.',
      'Três princípios sustentam o modelo.',
      '',
    ],
    [
      'se résigner',
      '',
      'conformar-se',
      'je:me résigne|passé:me suis résigné',
      "Elle s'est résignée au résultat.",
      'Conformou-se com o resultado.',
      '',
    ],
  ],
  C2: [
    [
      'démentir',
      '',
      'desmentir',
      'il:dément|passé composé:a démenti',
      'Son calme démentait sa colère.',
      'Sua calma desmentia sua raiva.',
      '',
    ],
    [
      'tergiverser',
      '',
      'usar de evasivas',
      'il:tergiverse|passé composé:a tergiversé',
      'Le ministre a tergiversé.',
      'O ministro usou de evasivas.',
      '',
    ],
    [
      'escamoter',
      '',
      'escamotear',
      "j':escamote|passé composé:ai escamoté",
      'Le rapport escamote les échecs.',
      'O relatório escamoteia os fracassos.',
      '',
    ],
    [
      'obvier à',
      '',
      'obviar / remediar',
      'il:obvie|passé composé:a obvié',
      'Cela obvie à une seconde revue.',
      'Isso dispensa uma segunda revisão.',
      'Registro muito formal.',
    ],
    [
      'souscrire à',
      '',
      'subscrever / concordar com',
      'je:souscris|passé composé:ai souscrit',
      'Je ne souscris pas à cette thèse.',
      'Não subscrevo essa tese.',
      '',
    ],
    [
      "s'aguerrir",
      '',
      'endurecer-se',
      "je:m'aguerris|passé:me suis aguerri",
      "Il s'est aguerri aux critiques.",
      'Endureceu com as críticas.',
      '',
    ],
    [
      'nuancer',
      '',
      'matizar',
      'je:nuance|passé composé:ai nuancé',
      'Il convient de nuancer ce propos.',
      'Convém matizar essa afirmação.',
      'Central na dissertação francesa.',
    ],
    [
      'invoquer',
      '',
      'alegar / invocar',
      "j':invoque|passé composé:ai invoqué",
      'Il a invoqué des raisons de santé.',
      'Alegou motivos de saúde.',
      '',
    ],
  ],
};

const IT: VerbMap = {
  A1: [
    [
      'essere',
      '',
      'ser / estar',
      'io:sono|lui/lei:è|noi:siamo|passato:ero',
      'Sono brasiliano.',
      'Sou brasileiro.',
      'Auxiliar de muitos verbos no passado.',
    ],
    [
      'avere',
      '',
      'ter',
      'io:ho|lui/lei:ha|noi:abbiamo|passato:avevo',
      'Ho venticinque anni.',
      'Tenho vinte e cinco anos.',
      'Usa-se para idade.',
    ],
    [
      'andare',
      '',
      'ir',
      'io:vado|lui/lei:va|noi:andiamo|passato:andavo',
      'Vado al lavoro in metro.',
      'Vou ao trabalho de metrô.',
      'Passado com "essere".',
    ],
    [
      'fare',
      '',
      'fazer',
      'io:faccio|lui/lei:fa|noi:facciamo|passato:facevo',
      'Cosa fai la domenica?',
      'O que você faz aos domingos?',
      '',
    ],
    [
      'volere',
      '',
      'querer',
      'io:voglio|lui/lei:vuole|noi:vogliamo|passato:volevo',
      "Voglio imparare l'italiano.",
      'Quero aprender italiano.',
      '"Vorrei" é a forma educada.',
    ],
    [
      'potere',
      '',
      'poder',
      'io:posso|lui/lei:può|noi:possiamo|passato:potevo',
      'Puoi ripetere?',
      'Você pode repetir?',
      '',
    ],
    [
      'parlare',
      '',
      'falar',
      'io:parlo|lui/lei:parla|passato:parlavo',
      'Parli portoghese?',
      'Você fala português?',
      '',
    ],
    [
      'piacere',
      '',
      'agradar (gostar)',
      'mi:piace|mi:piacciono|passato:piaceva',
      'Mi piacciono i libri.',
      'Gosto de livros.',
      'Estrutura invertida, como o espanhol.',
    ],
  ],
  A2: [
    [
      'portare',
      '',
      'trazer / levar',
      'io:porto|passato prossimo:ho portato',
      'Porta i documenti domani.',
      'Traga os documentos amanhã.',
      'Serve para trazer e levar.',
    ],
    [
      'uscire',
      '',
      'sair',
      'io:esco|lui:esce|passato prossimo:sono uscito',
      'Esco alle otto.',
      'Saio às oito.',
      'Passado com "essere".',
    ],
    [
      'pagare',
      '',
      'pagar',
      'io:pago|passato prossimo:ho pagato',
      'Ho pagato con la carta.',
      'Paguei com cartão.',
      '',
    ],
    [
      'aspettare',
      '',
      'esperar (aguardar)',
      'io:aspetto|passato prossimo:ho aspettato',
      'Aspetta un attimo.',
      'Espere um instante.',
      'Sem preposição depois.',
    ],
    [
      'sentirsi',
      '',
      'sentir-se',
      'io:mi sento|passato:mi sono sentito',
      'Oggi mi sento meglio.',
      'Hoje me sinto melhor.',
      'Reflexivo, com "essere".',
    ],
    [
      'succedere',
      '',
      'acontecer',
      'lui:succede|passato prossimo:è successo',
      'Cosa è successo ieri?',
      'O que aconteceu ontem?',
      '',
    ],
    [
      'provare',
      '',
      'tentar / experimentar',
      'io:provo|passato prossimo:ho provato',
      'Prova ad arrivare presto.',
      'Tente chegar cedo.',
      'Seguido de "a" + infinitivo.',
    ],
    [
      'rimanere',
      '',
      'ficar / permanecer',
      'io:rimango|passato prossimo:sono rimasto',
      'Rimango a casa.',
      'Fico em casa.',
      '',
    ],
  ],
  B1: [
    [
      'riuscire',
      '',
      'conseguir',
      'io:riesco|passato prossimo:sono riuscito',
      'È riuscita a finire.',
      'Ela conseguiu terminar.',
      'Seguido de "a"; passado com "essere".',
    ],
    [
      'permettersi',
      '',
      'ter condições de',
      'io:mi permetto|passato:mi sono permesso',
      'Non posso permettermi quel viaggio.',
      'Não tenho condições dessa viagem.',
      '',
    ],
    [
      'suggerire',
      '',
      'sugerir',
      'io:suggerisco|passato prossimo:ho suggerito',
      'Ha suggerito di vederci venerdì.',
      'Sugeriu nos vermos na sexta.',
      'Verbo em -isc-.',
    ],
    [
      'evitare',
      '',
      'evitar',
      'io:evito|passato prossimo:ho evitato',
      'Evita di usare frasi lunghe.',
      'Evite usar frases longas.',
      '',
    ],
    [
      'lamentarsi',
      '',
      'reclamar',
      'io:mi lamento|passato:mi sono lamentato',
      'Si sono lamentati del rumore.',
      'Reclamaram do barulho.',
      '',
    ],
    [
      'accorgersi',
      '',
      'dar-se conta',
      'io:mi accorgo|passato:mi sono accorto',
      "Mi sono accorto dell'errore.",
      'Dei-me conta do erro.',
      'Seguido de "di".',
    ],
    [
      'faticare',
      '',
      'ter dificuldade',
      'io:fatico|passato prossimo:ho faticato',
      'Ho faticato a capire.',
      'Tive dificuldade em entender.',
      '',
    ],
    [
      'migliorare',
      '',
      'melhorar',
      'io:miglioro|passato prossimo:ho migliorato',
      'Ho migliorato la scrittura.',
      'Melhorei a escrita.',
      '',
    ],
  ],
  B2: [
    [
      'riconoscere',
      '',
      'reconhecer',
      'io:riconosco|passato prossimo:ho riconosciuto',
      'Ha riconosciuto di aver sbagliato.',
      'Reconheceu que errou.',
      '',
    ],
    [
      'minare',
      '',
      'minar',
      'lui:mina|passato prossimo:ha minato',
      'I ritardi hanno minato la fiducia.',
      'Os atrasos minaram a confiança.',
      '',
    ],
    [
      'trascurare',
      '',
      'negligenciar',
      'io:trascuro|passato prossimo:ho trascurato',
      'Abbiamo trascurato un dettaglio.',
      'Negligenciamos um detalhe.',
      '',
    ],
    [
      'affrontare',
      '',
      'enfrentar / abordar',
      'io:affronto|passato prossimo:ho affrontato',
      'Il rapporto affronta tre rischi.',
      'O relatório aborda três riscos.',
      '',
    ],
    [
      'comportare',
      '',
      'acarretar',
      'lui:comporta|passato prossimo:ha comportato',
      'Questo comporta costi extra.',
      'Isso acarreta custos extras.',
      '',
    ],
    [
      'rispettare',
      '',
      'cumprir / respeitar',
      'io:rispetto|passato prossimo:ho rispettato',
      'Bisogna rispettare le regole.',
      'É preciso cumprir as regras.',
      '',
    ],
    [
      'superare',
      '',
      'superar',
      'io:supero|passato prossimo:ho superato',
      'I benefici superano i rischi.',
      'Os benefícios superam os riscos.',
      '',
    ],
    [
      'sfruttare',
      '',
      'aproveitar',
      'io:sfrutto|passato prossimo:ho sfruttato',
      'Hanno sfruttato la conoscenza locale.',
      'Aproveitaram o conhecimento local.',
      '',
    ],
  ],
  C1: [
    [
      'comprovare',
      '',
      'comprovar',
      'io:comprovo|passato prossimo:ho comprovato',
      "Non ha comprovato l'accusa.",
      'Não comprovou a acusação.',
      '',
    ],
    [
      'conciliare',
      '',
      'conciliar',
      'io:concilio|passato prossimo:ho conciliato',
      'È difficile conciliare le versioni.',
      'É difícil conciliar as versões.',
      '',
    ],
    [
      'precludere',
      '',
      'inviabilizar',
      'lui:preclude|passato prossimo:ha precluso',
      'I tagli precludono nuovi test.',
      'Os cortes inviabilizam novos testes.',
      '',
    ],
    [
      'mitigare',
      '',
      'mitigar',
      'lui:mitiga|passato prossimo:ha mitigato',
      'Queste misure mitigano il rischio.',
      'Essas medidas mitigam o risco.',
      '',
    ],
    [
      'prevalere',
      '',
      'prevalecer',
      'lui:prevale|passato prossimo:è prevalso',
      'È prevalso il buon senso.',
      'Prevaleceu o bom senso.',
      'Passado com "essere".',
    ],
    [
      'giustificare',
      '',
      'justificar',
      'io:giustifico|passato prossimo:ho giustificato',
      'Il caso giustifica uno studio.',
      'O caso justifica um estudo.',
      '',
    ],
    [
      'sorreggere',
      '',
      'sustentar',
      'lui:sorregge|passato prossimo:ha sorretto',
      'Tre principi sorreggono il modello.',
      'Três princípios sustentam o modelo.',
      '',
    ],
    [
      'rassegnarsi',
      '',
      'conformar-se',
      'io:mi rassegno|passato:mi sono rassegnato',
      'Si è rassegnata al risultato.',
      'Conformou-se com o resultado.',
      '',
    ],
  ],
  C2: [
    [
      'smentire',
      '',
      'desmentir',
      'lui:smentisce|passato prossimo:ha smentito',
      'Il tono calmo smentiva la rabbia.',
      'O tom calmo desmentia a raiva.',
      '',
    ],
    [
      'tergiversare',
      '',
      'usar de evasivas',
      'lui:tergiversa|passato prossimo:ha tergiversato',
      'Il ministro ha tergiversato.',
      'O ministro usou de evasivas.',
      '',
    ],
    [
      'sorvolare',
      '',
      'passar por cima',
      'lui:sorvola|passato prossimo:ha sorvolato',
      'Il rapporto sorvola sui fallimenti.',
      'O relatório passa por cima dos fracassos.',
      '',
    ],
    [
      'ovviare',
      '',
      'obviar / remediar',
      'lui:ovvia|passato prossimo:ha ovviato',
      'Questo ovvia a una seconda revisione.',
      'Isso dispensa uma segunda revisão.',
      '',
    ],
    [
      'tollerare',
      '',
      'tolerar',
      'io:tollero|passato prossimo:ho tollerato',
      'Non tollererebbero il ritardo.',
      'Não tolerariam o atraso.',
      '',
    ],
    [
      'agguerrirsi',
      '',
      'endurecer-se',
      'io:mi agguerrisco|passato:mi sono agguerrito',
      'Si è agguerrito alle critiche.',
      'Endureceu com as críticas.',
      '',
    ],
    [
      'sfumare',
      '',
      'matizar / esvair-se',
      'lui:sfuma|passato prossimo:ha sfumato',
      'Conviene sfumare questa affermazione.',
      'Convém matizar essa afirmação.',
      '',
    ],
    [
      'addurre',
      '',
      'alegar / aduzir',
      'lui:adduce|passato prossimo:ha addotto',
      'Ha addotto motivi di salute.',
      'Alegou motivos de saúde.',
      'Registro formal.',
    ],
  ],
};

const DE: VerbMap = {
  A1: [
    [
      'sein',
      '',
      'ser / estar',
      'ich:bin|er/sie:ist|wir:sind|Präteritum:war',
      'Ich bin Student.',
      'Sou estudante.',
      'Auxiliar de verbos de movimento no Perfekt.',
    ],
    [
      'haben',
      '',
      'ter',
      'ich:habe|er/sie:hat|wir:haben|Präteritum:hatte',
      'Ich habe zwei Brüder.',
      'Tenho dois irmãos.',
      'Idade usa "sein": "Ich bin 25".',
    ],
    [
      'gehen',
      '',
      'ir (a pé)',
      'ich:gehe|er/sie:geht|Perfekt:bin gegangen',
      'Ich gehe zur Arbeit.',
      'Vou ao trabalho.',
      'Perfekt com "sein".',
    ],
    [
      'machen',
      '',
      'fazer',
      'ich:mache|er/sie:macht|Perfekt:habe gemacht',
      'Was machst du am Sonntag?',
      'O que você faz no domingo?',
      '',
    ],
    [
      'wollen',
      '',
      'querer',
      'ich:will|er/sie:will|wir:wollen|Präteritum:wollte',
      'Ich will Deutsch lernen.',
      'Quero aprender alemão.',
      'Verbo modal; o principal vai ao fim.',
    ],
    [
      'können',
      '',
      'poder / saber',
      'ich:kann|er/sie:kann|wir:können|Präteritum:konnte',
      'Kannst du das wiederholen?',
      'Você pode repetir isso?',
      'Também significa saber fazer algo.',
    ],
    [
      'sprechen',
      '',
      'falar',
      'ich:spreche|er/sie:spricht|Perfekt:habe gesprochen',
      'Sprichst du Portugiesisch?',
      'Você fala português?',
      'Muda a vogal na 2ª e 3ª pessoa.',
    ],
    [
      'mögen',
      '',
      'gostar de',
      'ich:mag|er/sie:mag|wir:mögen|Präteritum:mochte',
      'Ich mag Kaffee.',
      'Gosto de café.',
      '"Ich möchte" é "eu gostaria".',
    ],
  ],
  A2: [
    [
      'bringen',
      '',
      'trazer',
      'ich:bringe|Perfekt:habe gebracht',
      'Bring morgen deine Unterlagen mit.',
      'Traga seus documentos amanhã.',
      'Falso amigo do inglês "bring/become".',
    ],
    [
      'verlassen',
      '',
      'deixar / sair de',
      'ich:verlasse|Perfekt:habe verlassen',
      'Ich verlasse das Haus um acht.',
      'Saio de casa às oito.',
      '',
    ],
    [
      'bezahlen',
      '',
      'pagar',
      'ich:bezahle|Perfekt:habe bezahlt',
      'Ich habe mit Karte bezahlt.',
      'Paguei com cartão.',
      '',
    ],
    [
      'warten',
      '',
      'esperar (aguardar)',
      'ich:warte|Perfekt:habe gewartet',
      'Ich warte auf den Bus.',
      'Espero o ônibus.',
      'Sempre "warten auf" + acusativo.',
    ],
    [
      'sich fühlen',
      '',
      'sentir-se',
      'ich:fühle mich|Perfekt:habe mich gefühlt',
      'Ich fühle mich besser.',
      'Me sinto melhor.',
      'Reflexivo obrigatório.',
    ],
    [
      'passieren',
      '',
      'acontecer',
      'es:passiert|Perfekt:ist passiert',
      'Was ist gestern passiert?',
      'O que aconteceu ontem?',
      'Perfekt com "sein".',
    ],
    [
      'versuchen',
      '',
      'tentar',
      'ich:versuche|Perfekt:habe versucht',
      'Versuch früh anzukommen.',
      'Tente chegar cedo.',
      'Com "zu" + infinitivo.',
    ],
    [
      'bleiben',
      '',
      'ficar / permanecer',
      'ich:bleibe|Perfekt:bin geblieben',
      'Ich bleibe zu Hause.',
      'Fico em casa.',
      'Perfekt com "sein".',
    ],
  ],
  B1: [
    [
      'schaffen',
      '',
      'conseguir / criar',
      'ich:schaffe|Perfekt:habe geschafft',
      'Sie hat es rechtzeitig geschafft.',
      'Ela conseguiu a tempo.',
      'Dois sentidos com particípios diferentes.',
    ],
    [
      'sich leisten',
      '',
      'ter condições de',
      'ich:leiste mir|Perfekt:habe mir geleistet',
      'Ich kann mir die Reise nicht leisten.',
      'Não tenho condições da viagem.',
      'Sempre reflexivo com dativo.',
    ],
    [
      'vorschlagen',
      '',
      'sugerir',
      'ich:schlage vor|Perfekt:habe vorgeschlagen',
      'Er schlug Freitag vor.',
      'Ele sugeriu sexta.',
      'Verbo separável.',
    ],
    [
      'vermeiden',
      '',
      'evitar',
      'ich:vermeide|Perfekt:habe vermieden',
      'Vermeide lange Sätze.',
      'Evite frases longas.',
      '',
    ],
    [
      'sich beschweren',
      '',
      'reclamar',
      'ich:beschwere mich|Perfekt:habe mich beschwert',
      'Sie beschwerten sich über den Lärm.',
      'Reclamaram do barulho.',
      'Reclama-se "über" + acusativo.',
    ],
    [
      'merken',
      '',
      'perceber / notar',
      'ich:merke|Perfekt:habe gemerkt',
      'Ich habe gemerkt, dass ich falsch lag.',
      'Percebi que estava errado.',
      '"Sich merken" é memorizar — outro sentido.',
    ],
    [
      'erwarten',
      '',
      'esperar (prever)',
      'ich:erwarte|Perfekt:habe erwartet',
      'Wir erwarten eine Antwort.',
      'Esperamos uma resposta.',
      'Diferente de "warten".',
    ],
    [
      'verbessern',
      '',
      'melhorar',
      'ich:verbessere|Perfekt:habe verbessert',
      'Mein Schreiben hat sich verbessert.',
      'Minha escrita melhorou.',
      '',
    ],
  ],
  B2: [
    [
      'einräumen',
      '',
      'admitir / conceder',
      'ich:räume ein|Perfekt:habe eingeräumt',
      'Er räumte den Fehler ein.',
      'Ele admitiu o erro.',
      'Verbo separável.',
    ],
    [
      'untergraben',
      '',
      'minar',
      'es:untergräbt|Perfekt:hat untergraben',
      'Die Verzögerung untergrub das Vertrauen.',
      'O atraso minou a confiança.',
      '',
    ],
    [
      'übersehen',
      '',
      'deixar passar',
      'ich:übersehe|Perfekt:habe übersehen',
      'Wir haben ein Detail übersehen.',
      'Deixamos passar um detalhe.',
      'Inseparável, apesar do prefixo.',
    ],
    [
      'behandeln',
      '',
      'tratar de / abordar',
      'ich:behandle|Perfekt:habe behandelt',
      'Der Bericht behandelt drei Risiken.',
      'O relatório aborda três riscos.',
      '',
    ],
    [
      'mit sich bringen',
      '',
      'acarretar',
      'es:bringt mit sich|Perfekt:hat mit sich gebracht',
      'Das bringt Mehrkosten mit sich.',
      'Isso acarreta custos extras.',
      'Locução fixa.',
    ],
    [
      'einhalten',
      '',
      'cumprir',
      'ich:halte ein|Perfekt:habe eingehalten',
      'Wir müssen die Regeln einhalten.',
      'Precisamos cumprir as regras.',
      'Separável.',
    ],
    [
      'überwiegen',
      '',
      'superar / predominar',
      'es:überwiegt|Perfekt:hat überwogen',
      'Die Vorteile überwiegen die Risiken.',
      'As vantagens superam os riscos.',
      '',
    ],
    [
      'nutzen',
      '',
      'aproveitar / usar',
      'ich:nutze|Perfekt:habe genutzt',
      'Sie nutzten ihre Ortskenntnis.',
      'Aproveitaram o conhecimento local.',
      '',
    ],
  ],
  C1: [
    [
      'belegen',
      '',
      'comprovar',
      'ich:belege|Perfekt:habe belegt',
      'Er konnte den Vorwurf nicht belegen.',
      'Não conseguiu comprovar a acusação.',
      '',
    ],
    [
      'vereinbaren',
      '',
      'conciliar / combinar',
      'ich:vereinbare|Perfekt:habe vereinbart',
      'Beides ist schwer zu vereinbaren.',
      'É difícil conciliar os dois.',
      'Também significa marcar um compromisso.',
    ],
    [
      'ausschließen',
      '',
      'excluir / inviabilizar',
      'ich:schließe aus|Perfekt:habe ausgeschlossen',
      'Kürzungen schließen Tests aus.',
      'Cortes inviabilizam testes.',
      'Separável.',
    ],
    [
      'abmildern',
      '',
      'mitigar',
      'ich:mildere ab|Perfekt:habe abgemildert',
      'Die Maßnahmen mildern das Risiko ab.',
      'As medidas mitigam o risco.',
      'Separável.',
    ],
    [
      'sich durchsetzen',
      '',
      'prevalecer / impor-se',
      'ich:setze mich durch|Perfekt:habe mich durchgesetzt',
      'Der Menschenverstand setzte sich durch.',
      'O bom senso prevaleceu.',
      '',
    ],
    [
      'rechtfertigen',
      '',
      'justificar',
      'ich:rechtfertige|Perfekt:habe gerechtfertigt',
      'Der Fall rechtfertigt eine Studie.',
      'O caso justifica um estudo.',
      '',
    ],
    [
      'zugrunde liegen',
      '',
      'subjazer / embasar',
      'es:liegt zugrunde|Perfekt:hat zugrunde gelegen',
      'Drei Prinzipien liegen dem Modell zugrunde.',
      'Três princípios embasam o modelo.',
      '',
    ],
    [
      'sich abfinden',
      '',
      'conformar-se',
      'ich:finde mich ab|Perfekt:habe mich abgefunden',
      'Sie fand sich mit dem Ergebnis ab.',
      'Conformou-se com o resultado.',
      'Com "mit" + dativo.',
    ],
  ],
  C2: [
    [
      'Lügen strafen',
      '',
      'desmentir',
      'es:straft Lügen|Perfekt:hat Lügen gestraft',
      'Sein Ton strafte seinen Zorn Lügen.',
      'Seu tom desmentia sua raiva.',
      'Locução literária.',
    ],
    [
      'ausweichen',
      '',
      'esquivar-se',
      'ich:weiche aus|Perfekt:bin ausgewichen',
      'Der Minister wich aus.',
      'O ministro se esquivou.',
      'Perfekt com "sein".',
    ],
    [
      'beschönigen',
      '',
      'maquiar / dourar a pílula',
      'ich:beschönige|Perfekt:habe beschönigt',
      'Der Bericht beschönigt die Fehler.',
      'O relatório maquia os erros.',
      '',
    ],
    [
      'erübrigen',
      '',
      'tornar desnecessário',
      'es:erübrigt sich|Perfekt:hat sich erübrigt',
      'Eine zweite Prüfung erübrigt sich.',
      'Uma segunda revisão é dispensável.',
      'Reflexivo.',
    ],
    [
      'dulden',
      '',
      'tolerar',
      'ich:dulde|Perfekt:habe geduldet',
      'Sie würden keine Verzögerung dulden.',
      'Não tolerariam atraso.',
      '',
    ],
    [
      'abstumpfen',
      '',
      'insensibilizar-se',
      'ich:stumpfe ab|Perfekt:bin abgestumpft',
      'Er ist gegen Kritik abgestumpft.',
      'Ele se insensibilizou às críticas.',
      '',
    ],
    [
      'relativieren',
      '',
      'relativizar / matizar',
      'ich:relativiere|Perfekt:habe relativiert',
      'Diese Aussage ist zu relativieren.',
      'Essa afirmação deve ser matizada.',
      '',
    ],
    [
      'anführen',
      '',
      'alegar / citar',
      'ich:führe an|Perfekt:habe angeführt',
      'Er führte Gesundheitsgründe an.',
      'Alegou motivos de saúde.',
      'Separável.',
    ],
  ],
};

/* ================================================================== *
 * Registro
 * ================================================================== */

const VERB_CATALOG: Record<LanguageCode, VerbMap> = {
  en: EN,
  es: ES,
  fr: FR,
  it: IT,
  de: DE,
};

/**
 * Verbos de um idioma num nível, já expandidos.
 *
 * Junta os dois lotes — o curado deste arquivo e o de ampliação de
 * `verbs-extra/` — num único ponto, para que apostila, trilha e contagem
 * enxerguem sempre o mesmo conjunto. Se cada consumidor tivesse de lembrar de
 * somar os dois, algum esqueceria.
 */
export function levelVerbs(language: LanguageCode, level: CefrLevel): VerbEntry[] {
  const curated = VERB_CATALOG[language]?.[level] ?? [];
  return expand([...curated, ...extraVerbsRaw(language, level)]);
}

/** Todos os verbos de um idioma, do A1 ao C2. */
export function allVerbs(language: LanguageCode): VerbEntry[] {
  const levels: CefrLevel[] = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];
  return levels.flatMap((level) => levelVerbs(language, level));
}

/** Total catalogado — usado em documentação e testes. */
export function verbCount(): number {
  const levels: CefrLevel[] = ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'];
  return Object.keys(VERB_CATALOG).reduce(
    (total, language) =>
      total +
      levels.reduce(
        (sum, level) => sum + levelVerbs(language as LanguageCode, level).length,
        0,
      ),
    0,
  );
}
