/**
 * Vocabulário por nível CEFR — japonês, coreano e mandarim
 * =========================================================
 *
 * Separado dos idiomas latinos por uma razão concreta: aqui **todo verbete
 * carrega romanização**, e enfiar um campo opcional na tupla dos outros
 * idiomas deixaria 400 posições vazias só para acomodar 200 preenchidas.
 *
 * ## A romanização não é enfeite
 *
 * Para um falante de português, a barreira inicial em japonês, coreano e
 * mandarim não é gramática — é **não conseguir nem pronunciar o que vê**. Sem
 * romanização ao lado, o aluno de A2 olha para 締め切り e não tem nenhum ponto
 * de apoio: não consegue repetir, não consegue procurar, não consegue guardar.
 * Ela aparece sempre junto do texto nativo, nunca no lugar dele — o objetivo é
 * a escrita nativa se tornar legível, não ser substituída.
 *
 * ## Progressão de escrita, não só de vocabulário
 *
 * A escolha dos verbetes acompanha a carga de escrita, que é uma dificuldade
 * própria destes idiomas:
 *
 *  - **A2** — palavras do cotidiano, kanji/hanzi de traço simples e alto uso.
 *  - **B1** — opinião e narrativa; compostos de dois caracteres.
 *  - **B2** — abstração; vocabulário sino-japonês e sino-coreano formal.
 *  - **C1** — registro escrito, jornalístico e corporativo.
 *  - **C2** — expressão idiomática culta: 四字熟語, 사자성어, 成语.
 *
 * Os chengyu e yojijukugo de C2 são deliberados: são exatamente o ponto em que
 * um estrangeiro fluente ainda se denuncia, porque não se deduzem das partes.
 */

import type { CefrLevel, LanguageCode } from '@/domain/types';

/** [termo, romanização, tradução PT, classe, exemplo, romanização do exemplo, tradução] */
export type AsianLevelEntry = [string, string, string, string, string, string, string];

type AsianLevelMap = Partial<Record<CefrLevel, AsianLevelEntry[]>>;

/* ================================================================== *
 * Japonês
 * ================================================================== */

const JA: AsianLevelMap = {
  A2: [
    [
      '近所',
      'kinjo',
      'vizinhança / bairro',
      'substantivo',
      '近所に住んでいます。',
      'Kinjo ni sunde imasu.',
      'Moro aqui perto.',
    ],
    [
      '予約',
      'yoyaku',
      'reserva / agendamento',
      'substantivo',
      '病院の予約があります。',
      'Byōin no yoyaku ga arimasu.',
      'Tenho consulta no hospital.',
    ],
    [
      '領収書',
      'ryōshūsho',
      'recibo',
      'substantivo',
      '領収書をください。',
      'Ryōshūsho o kudasai.',
      'Me dê o recibo, por favor.',
    ],
    [
      '貸す',
      'kasu',
      'emprestar (dar)',
      'verbo',
      '充電器を貸してくれますか。',
      'Jūdenki o kashite kuremasu ka.',
      'Você me empresta o carregador?',
    ],
    [
      '借りる',
      'kariru',
      'pegar emprestado',
      'verbo',
      '友達に車を借りました。',
      'Tomodachi ni kuruma o karimashita.',
      'Peguei o carro de um amigo emprestado.',
    ],
    [
      '込む',
      'komu',
      'ficar lotado',
      'verbo',
      '朝の電車は込みます。',
      'Asa no densha wa komimasu.',
      'O trem de manhã fica lotado.',
    ],
    [
      'なかなか',
      'nakanaka',
      'bastante / até que',
      'advérbio',
      'あの映画はなかなか良かった。',
      'Ano eiga wa nakanaka yokatta.',
      'Aquele filme foi até que bom.',
    ],
    [
      'もう',
      'mō',
      'já',
      'advérbio',
      '彼女はもう帰りました。',
      'Kanojo wa mō kaerimashita.',
      'Ela já foi embora.',
    ],
    [
      '代わりに',
      'kawari ni',
      'em vez disso',
      'locução',
      'バスの代わりに歩きます。',
      'Basu no kawari ni arukimasu.',
      'Vou a pé em vez de ônibus.',
    ],
    [
      '文句を言う',
      'monku o iu',
      'reclamar',
      'verbo',
      '騒音に文句を言いました。',
      'Sōon ni monku o iimashita.',
      'Ele reclamou do barulho.',
    ],
    [
      '直す',
      'naosu',
      'consertar',
      'verbo',
      'シャワーを直せますか。',
      'Shawā o naosemasu ka.',
      'Você consegue consertar o chuveiro?',
    ],
    [
      '払う',
      'harau',
      'pagar',
      'verbo',
      'カードで払います。',
      'Kādo de haraimasu.',
      'Vou pagar com cartão.',
    ],
  ],
  B1: [
    [
      '締め切り',
      'shimekiri',
      'prazo final',
      'substantivo',
      '締め切りは金曜日です。',
      'Shimekiri wa kin’yōbi desu.',
      'O prazo é sexta-feira.',
    ],
    [
      '成果',
      'seika',
      'resultado / conquista',
      'substantivo',
      '大きな成果が出ました。',
      'Ōkina seika ga demashita.',
      'Saiu um grande resultado.',
    ],
    [
      '課題',
      'kadai',
      'questão / desafio',
      'substantivo',
      'これは重要な課題です。',
      'Kore wa jūyō na kadai desu.',
      'Esta é uma questão importante.',
    ],
    [
      '思い込む',
      'omoikomu',
      'presumir / convencer-se',
      'verbo',
      '知っていると思い込んでいました。',
      'Shitte iru to omoikonde imashita.',
      'Eu presumi que você soubesse.',
    ],
    [
      '指摘する',
      'shiteki suru',
      'apontar',
      'verbo',
      '間違いを指摘しました。',
      'Machigai o shiteki shimashita.',
      'Ele apontou o erro.',
    ],
    [
      '信頼できる',
      'shinrai dekiru',
      'confiável',
      'adjetivo',
      '信頼できる同僚です。',
      'Shinrai dekiru dōryō desu.',
      'É um colega confiável.',
    ],
    [
      '一方',
      'ippō',
      'ao passo que',
      'conjunção',
      '彼は紅茶、一方私はコーヒーが好きだ。',
      'Kare wa kōcha, ippō watashi wa kōhī ga suki da.',
      'Ele gosta de chá, ao passo que eu prefiro café.',
    ],
    [
      '結局',
      'kekkyoku',
      'no fim das contas',
      'advérbio',
      '結局、賛成しました。',
      'Kekkyoku, sansei shimashita.',
      'No fim das contas, concordaram.',
    ],
    [
      '苦労する',
      'kurō suru',
      'ter dificuldade',
      'verbo',
      '文法に苦労しました。',
      'Bunpō ni kurō shimashita.',
      'Tive dificuldade com a gramática.',
    ],
    [
      '収入',
      'shūnyū',
      'renda',
      'substantivo',
      '収入は観光からです。',
      'Shūnyū wa kankō kara desu.',
      'A renda vem do turismo.',
    ],
    [
      '恐らく',
      'osoraku',
      'provavelmente',
      'advérbio',
      '恐らく雨は降らないでしょう。',
      'Osoraku ame wa furanai deshō.',
      'Provavelmente não vai chover.',
    ],
    [
      '機会',
      'kikai',
      'oportunidade',
      'substantivo',
      '良い機会だと思います。',
      'Yoi kikai da to omoimasu.',
      'Acho que é uma boa oportunidade.',
    ],
  ],
  B2: [
    [
      '観点',
      'kanten',
      'ponto de vista / perspectiva',
      'substantivo',
      '別の観点から見ましょう。',
      'Betsu no kanten kara mimashō.',
      'Vamos ver de outra perspectiva.',
    ],
    [
      '欠点',
      'ketten',
      'desvantagem / defeito',
      'substantivo',
      '最大の欠点は費用です。',
      'Saidai no ketten wa hiyō desu.',
      'A maior desvantagem é o custo.',
    ],
    [
      '偏り',
      'katayori',
      'viés',
      'substantivo',
      'データに偏りがあります。',
      'Dēta ni katayori ga arimasu.',
      'Há um viés nos dados.',
    ],
    [
      '認める',
      'mitomeru',
      'reconhecer / admitir',
      'verbo',
      '間違いを認めました。',
      'Machigai o mitomemashita.',
      'Ele admitiu o erro.',
    ],
    [
      '損なう',
      'sokonau',
      'prejudicar / minar',
      'verbo',
      '遅れが信頼を損ないました。',
      'Okure ga shinrai o sokonaimashita.',
      'O atraso minou a confiança.',
    ],
    [
      '見落とす',
      'miotosu',
      'deixar passar',
      'verbo',
      '重要な点を見落としました。',
      'Jūyō na ten o miotoshimashita.',
      'Deixamos passar um ponto importante.',
    ],
    [
      '徹底的',
      'tetteiteki',
      'minucioso',
      'adjetivo',
      '徹底的な分析でした。',
      'Tetteiteki na bunseki deshita.',
      'Foi uma análise minuciosa.',
    ],
    [
      '説得力',
      'settokuryoku',
      'poder de convencimento',
      'substantivo',
      '説得力のある議論です。',
      'Settokuryoku no aru giron desu.',
      'É um argumento convincente.',
    ],
    [
      'にもかかわらず',
      'nimo kakawarazu',
      'no entanto / apesar de',
      'locução',
      '雨にもかかわらず出かけた。',
      'Ame nimo kakawarazu dekaketa.',
      'Apesar da chuva, saímos.',
    ],
    [
      '活用する',
      'katsuyō suru',
      'aproveitar / utilizar',
      'verbo',
      '地元の知識を活用した。',
      'Jimoto no chishiki o katsuyō shita.',
      'Aproveitaram o conhecimento local.',
    ],
    [
      '範囲',
      'han’i',
      'escopo / alcance',
      'substantivo',
      'それは範囲外です。',
      'Sore wa han’igai desu.',
      'Isso está fora do escopo.',
    ],
    [
      '傾向',
      'keikō',
      'tendência',
      'substantivo',
      '増加の傾向があります。',
      'Zōka no keikō ga arimasu.',
      'Há uma tendência de aumento.',
    ],
  ],
  C1: [
    [
      '留意点',
      'ryūiten',
      'ressalva / ponto de atenção',
      'substantivo',
      '一つ留意点があります。',
      'Hitotsu ryūiten ga arimasu.',
      'Há uma ressalva.',
    ],
    [
      '相違',
      'sōi',
      'discrepância',
      'substantivo',
      '数値に相違があります。',
      'Sūchi ni sōi ga arimasu.',
      'Há discrepância nos números.',
    ],
    [
      '前提',
      'zentei',
      'premissa',
      'substantivo',
      '誤った前提に基づく。',
      'Ayamatta zentei ni motozuku.',
      'Baseia-se numa premissa falsa.',
    ],
    [
      '裏付ける',
      'urazukeru',
      'comprovar / fundamentar',
      'verbo',
      '主張を裏付ける証拠がない。',
      'Shuchō o urazukeru shōko ga nai.',
      'Não há prova que fundamente a alegação.',
    ],
    [
      '両立する',
      'ryōritsu suru',
      'conciliar',
      'verbo',
      '両者を両立させるのは難しい。',
      'Ryōsha o ryōritsu saseru no wa muzukashii.',
      'É difícil conciliar os dois.',
    ],
    [
      '妨げる',
      'samatageru',
      'impedir',
      'verbo',
      '予算削減が試験を妨げる。',
      'Yosan sakugen ga shiken o samatageru.',
      'Cortes impedem os testes.',
    ],
    [
      '希薄',
      'kihaku',
      'tênue / rarefeito',
      'adjetivo',
      '関連性は希薄です。',
      'Kanrensei wa kihaku desu.',
      'A relação é tênue.',
    ],
    [
      '蔓延する',
      'man’en suru',
      'alastrar-se',
      'verbo',
      '問題が業界に蔓延している。',
      'Mondai ga gyōkai ni man’en shite iru.',
      'O problema se alastrou pelo setor.',
    ],
    [
      'にもせよ',
      'nimo seyo',
      'seja como for',
      'locução',
      '遅れたにもせよ成功した。',
      'Okureta nimo seyo seikō shita.',
      'Ainda que atrasado, deu certo.',
    ],
    [
      '限りにおいて',
      'kagiri ni oite',
      'na medida em que',
      'locução',
      '結果が変わる限りにおいて重要だ。',
      'Kekka ga kawaru kagiri ni oite jūyō da.',
      'Importa na medida em que muda o resultado.',
    ],
    [
      '緩和する',
      'kanwa suru',
      'mitigar',
      'verbo',
      'リスクを緩和する措置です。',
      'Risuku o kanwa suru sochi desu.',
      'São medidas que mitigam o risco.',
    ],
    [
      '優勢',
      'yūsei',
      'predominância',
      'substantivo',
      '常識が優勢となった。',
      'Jōshiki ga yūsei to natta.',
      'O bom senso prevaleceu.',
    ],
  ],
  C2: [
    [
      '本末転倒',
      'honmatsu tentō',
      'inverter prioridades',
      'expressão',
      'それは本末転倒だ。',
      'Sore wa honmatsu tentō da.',
      'Isso é inverter as prioridades.',
    ],
    [
      '臨機応変',
      'rinki ōhen',
      'adaptar-se às circunstâncias',
      'expressão',
      '臨機応変に対応した。',
      'Rinki ōhen ni taiō shita.',
      'Ele se adaptou às circunstâncias.',
    ],
    [
      '一石二鳥',
      'isseki nichō',
      'matar dois coelhos',
      'expressão',
      'まさに一石二鳥です。',
      'Masa ni isseki nichō desu.',
      'É exatamente matar dois coelhos.',
    ],
    [
      '婉曲',
      'enkyoku',
      'eufemismo / indireto',
      'substantivo',
      '婉曲な表現を使った。',
      'Enkyoku na hyōgen o tsukatta.',
      'Ele usou uma expressão indireta.',
    ],
    [
      '言葉を濁す',
      'kotoba o nigosu',
      'usar de evasivas',
      'locução',
      '大臣は言葉を濁した。',
      'Daijin wa kotoba o nigoshita.',
      'O ministro usou de evasivas.',
    ],
    [
      'お茶を濁す',
      'ocha o nigosu',
      'enrolar / driblar o assunto',
      'locução',
      '報告書は失敗をお茶を濁した。',
      'Hōkokusho wa shippai o ocha o nigoshita.',
      'O relatório driblou os fracassos.',
    ],
    [
      '不可避',
      'fukahi',
      'inevitável',
      'adjetivo',
      '衰退は不可避だった。',
      'Suitai wa fukahi datta.',
      'O declínio foi inevitável.',
    ],
    [
      '表向き',
      'omotemuki',
      'aparentemente / oficialmente',
      'advérbio',
      '表向きは健康上の理由だ。',
      'Omotemuki wa kenkōjō no riyū da.',
      'Oficialmente, por motivos de saúde.',
    ],
    [
      '等しい',
      'hitoshii',
      'equivalente',
      'adjetivo',
      '沈黙は同意に等しい。',
      'Chinmoku wa dōi ni hitoshii.',
      'Silêncio equivale a consentimento.',
    ],
    [
      '典型的',
      'tenkeiteki',
      'típico / por excelência',
      'adjetivo',
      '典型的な東京人だ。',
      'Tenkeiteki na Tōkyōjin da.',
      'É o tóquio-ense por excelência.',
    ],
    [
      '以上',
      'ijō',
      'visto que / uma vez que',
      'conjunção',
      '合意した以上、進めよう。',
      'Gōi shita ijō, susumeyō.',
      'Visto que concordamos, sigamos.',
    ],
    [
      '従来',
      'jūrai',
      'até então / tradicionalmente',
      'advérbio',
      '従来知られていない種。',
      'Jūrai shirarete inai shu.',
      'Uma espécie até então desconhecida.',
    ],
  ],
};

/* ================================================================== *
 * Coreano
 * ================================================================== */

const KO: AsianLevelMap = {
  A2: [
    [
      '동네',
      'dongne',
      'bairro / vizinhança',
      'substantivo',
      '이 동네에서 자랐어요.',
      'I dongne-eseo jarasseoyo.',
      'Cresci neste bairro.',
    ],
    [
      '예약',
      'yeyak',
      'reserva / agendamento',
      'substantivo',
      '병원 예약이 있어요.',
      'Byeongwon yeyagi isseoyo.',
      'Tenho consulta marcada.',
    ],
    [
      '영수증',
      'yeongsujeung',
      'recibo',
      'substantivo',
      '영수증 주세요.',
      'Yeongsujeung juseyo.',
      'Me dê o recibo.',
    ],
    [
      '빌려주다',
      'billyeojuda',
      'emprestar (dar)',
      'verbo',
      '충전기 좀 빌려주세요.',
      'Chungjeongi jom billyeojuseyo.',
      'Me empreste o carregador.',
    ],
    [
      '빌리다',
      'billida',
      'pegar emprestado',
      'verbo',
      '친구 차를 빌렸어요.',
      'Chingu chareul billyeosseoyo.',
      'Peguei o carro do amigo emprestado.',
    ],
    [
      '붐비다',
      'bumbida',
      'ficar lotado',
      'verbo',
      '아침 지하철은 붐벼요.',
      'Achim jihacheoreun bumbyeoyo.',
      'O metrô de manhã fica lotado.',
    ],
    [
      '꽤',
      'kkwae',
      'bastante / até que',
      'advérbio',
      '그 영화는 꽤 좋았어요.',
      'Geu yeonghwaneun kkwae joasseoyo.',
      'Aquele filme foi até que bom.',
    ],
    [
      '벌써',
      'beolsseo',
      'já',
      'advérbio',
      '그녀는 벌써 갔어요.',
      'Geunyeoneun beolsseo gasseoyo.',
      'Ela já foi.',
    ],
    [
      '대신',
      'daesin',
      'em vez de',
      'advérbio',
      '버스 대신 걸어가요.',
      'Beoseu daesin georeogayo.',
      'Vou a pé em vez de ônibus.',
    ],
    [
      '불평하다',
      'bulpyeonghada',
      'reclamar',
      'verbo',
      '소음에 대해 불평했어요.',
      'Soeume daehae bulpyeonghaesseoyo.',
      'Ele reclamou do barulho.',
    ],
    [
      '고치다',
      'gochida',
      'consertar',
      'verbo',
      '샤워기를 고칠 수 있어요?',
      'Syawogireul gochil su isseoyo?',
      'Consegue consertar o chuveiro?',
    ],
    [
      '지불하다',
      'jibulhada',
      'pagar',
      'verbo',
      '카드로 지불할게요.',
      'Kadeuro jibulhalgeyo.',
      'Vou pagar com cartão.',
    ],
  ],
  B1: [
    [
      '마감',
      'magam',
      'prazo final',
      'substantivo',
      '마감은 금요일이에요.',
      'Magameun geumyoirieyo.',
      'O prazo é sexta.',
    ],
    [
      '성과',
      'seonggwa',
      'resultado / conquista',
      'substantivo',
      '큰 성과를 냈어요.',
      'Keun seonggwareul naesseoyo.',
      'Obtivemos um grande resultado.',
    ],
    [
      '과제',
      'gwaje',
      'tarefa / desafio',
      'substantivo',
      '이건 중요한 과제예요.',
      'Igeon jungyohan gwajeyeyo.',
      'Esta é uma tarefa importante.',
    ],
    [
      '짐작하다',
      'jimjakhada',
      'presumir',
      'verbo',
      '아는 줄 짐작했어요.',
      'Aneun jul jimjakhaesseoyo.',
      'Presumi que você soubesse.',
    ],
    [
      '지적하다',
      'jijeokhada',
      'apontar',
      'verbo',
      '실수를 지적했어요.',
      'Silsureul jijeokhaesseoyo.',
      'Ele apontou o erro.',
    ],
    [
      '믿을 만하다',
      'mideul manhada',
      'confiável',
      'adjetivo',
      '믿을 만한 동료예요.',
      'Mideul manhan dongnyoyeyo.',
      'É um colega confiável.',
    ],
    [
      '반면에',
      'banmyeone',
      'ao passo que',
      'conjunção',
      '그는 차를, 반면에 저는 커피를 좋아해요.',
      'Geuneun chareul, banmyeone jeoneun keopireul joahaeyo.',
      'Ele gosta de chá, ao passo que eu prefiro café.',
    ],
    [
      '결국',
      'gyeolguk',
      'no fim das contas',
      'advérbio',
      '결국 동의했어요.',
      'Gyeolguk donguihaesseoyo.',
      'No fim das contas, concordaram.',
    ],
    [
      '어려움을 겪다',
      'eoryeoumeul gyeokda',
      'ter dificuldade',
      'verbo',
      '문법에 어려움을 겪었어요.',
      'Munbeobe eoryeoumeul gyeokkeosseoyo.',
      'Tive dificuldade com a gramática.',
    ],
    [
      '수입',
      'suip',
      'renda',
      'substantivo',
      '수입은 관광에서 나와요.',
      'Suibeun gwangwang-eseo nawayo.',
      'A renda vem do turismo.',
    ],
    [
      '아마도',
      'amado',
      'provavelmente',
      'advérbio',
      '아마도 비가 안 올 거예요.',
      'Amado biga an ol geoyeyo.',
      'Provavelmente não vai chover.',
    ],
    [
      '기회',
      'gihoe',
      'oportunidade',
      'substantivo',
      '좋은 기회라고 생각해요.',
      'Joeun gihoerago saenggakhaeyo.',
      'Acho que é uma boa oportunidade.',
    ],
  ],
  B2: [
    [
      '관점',
      'gwanjeom',
      'ponto de vista',
      'substantivo',
      '다른 관점에서 봅시다.',
      'Dareun gwanjeomeseo bopsida.',
      'Vejamos de outro ponto de vista.',
    ],
    [
      '단점',
      'danjeom',
      'desvantagem',
      'substantivo',
      '가장 큰 단점은 비용이에요.',
      'Gajang keun danjeomeun biyongieyo.',
      'A maior desvantagem é o custo.',
    ],
    [
      '편향',
      'pyeonhyang',
      'viés',
      'substantivo',
      '데이터에 편향이 있어요.',
      'Deiteoe pyeonhyangi isseoyo.',
      'Há viés nos dados.',
    ],
    [
      '인정하다',
      'injeonghada',
      'reconhecer / admitir',
      'verbo',
      '잘못을 인정했어요.',
      'Jalmoseul injeonghaesseoyo.',
      'Ele admitiu o erro.',
    ],
    [
      '훼손하다',
      'hwesonhada',
      'danificar / minar',
      'verbo',
      '지연이 신뢰를 훼손했어요.',
      'Jiyeoni sinnoereul hwesonhaesseoyo.',
      'O atraso minou a confiança.',
    ],
    [
      '간과하다',
      'gangwahada',
      'deixar passar',
      'verbo',
      '중요한 점을 간과했어요.',
      'Jungyohan jeomeul gangwahaesseoyo.',
      'Deixamos passar um ponto importante.',
    ],
    [
      '철저하다',
      'cheoljeohada',
      'minucioso',
      'adjetivo',
      '철저한 분석이었어요.',
      'Cheoljeohan bunseogieosseoyo.',
      'Foi uma análise minuciosa.',
    ],
    [
      '설득력',
      'seoldeungnyeok',
      'poder de convencimento',
      'substantivo',
      '설득력 있는 주장이에요.',
      'Seoldeungnyeok inneun jujangieyo.',
      'É um argumento convincente.',
    ],
    [
      '그럼에도 불구하고',
      'geureomedo bulguhago',
      'não obstante',
      'locução',
      '그럼에도 불구하고 나갔어요.',
      'Geureomedo bulguhago nagasseoyo.',
      'Não obstante, saímos.',
    ],
    [
      '활용하다',
      'hwaryonghada',
      'aproveitar',
      'verbo',
      '현지 지식을 활용했어요.',
      'Hyeonji jisigeul hwaryonghaesseoyo.',
      'Aproveitaram o conhecimento local.',
    ],
    [
      '범위',
      'beomwi',
      'escopo',
      'substantivo',
      '그건 범위 밖이에요.',
      'Geugeon beomwi bakkieyo.',
      'Isso está fora do escopo.',
    ],
    [
      '경향',
      'gyeonghyang',
      'tendência',
      'substantivo',
      '증가하는 경향이 있어요.',
      'Jeunggahaneun gyeonghyangi isseoyo.',
      'Há tendência de aumento.',
    ],
  ],
  C1: [
    [
      '유의점',
      'yuuijeom',
      'ressalva',
      'substantivo',
      '한 가지 유의점이 있어요.',
      'Han gaji yuuijeomi isseoyo.',
      'Há uma ressalva.',
    ],
    [
      '불일치',
      'burilchi',
      'discrepância',
      'substantivo',
      '수치에 불일치가 있어요.',
      'Suchie burilchiga isseoyo.',
      'Há discrepância nos números.',
    ],
    [
      '전제',
      'jeonje',
      'premissa',
      'substantivo',
      '잘못된 전제에 기반해요.',
      'Jalmotdoen jeonjee gibanhaeyo.',
      'Baseia-se em premissa falsa.',
    ],
    [
      '입증하다',
      'ipjeunghada',
      'comprovar',
      'verbo',
      '주장을 입증하지 못했어요.',
      'Jujangeul ipjeunghaji mothaesseoyo.',
      'Não conseguiu comprovar a alegação.',
    ],
    [
      '조화시키다',
      'johwasikida',
      'conciliar',
      'verbo',
      '두 입장을 조화시키기 어려워요.',
      'Du ipjangeul johwasikigi eoryeowoyo.',
      'É difícil conciliar as duas posições.',
    ],
    [
      '저해하다',
      'jeohaehada',
      'impedir / prejudicar',
      'verbo',
      '예산 삭감이 시험을 저해해요.',
      'Yesan sakgami siheomeul jeohaehaeyo.',
      'Cortes impedem os testes.',
    ],
    [
      '희박하다',
      'huibakhada',
      'tênue',
      'adjetivo',
      '연관성이 희박해요.',
      'Yeongwanseongi huibakhaeyo.',
      'A relação é tênue.',
    ],
    [
      '만연하다',
      'manyeonhada',
      'alastrar-se',
      'verbo',
      '문제가 업계에 만연해요.',
      'Munjega eopgyee manyeonhaeyo.',
      'O problema se alastrou no setor.',
    ],
    [
      '에도 불구하고',
      'edo bulguhago',
      'apesar de',
      'locução',
      '지연에도 불구하고 성공했어요.',
      'Jiyeonedo bulguhago seonggonghaesseoyo.',
      'Apesar do atraso, deu certo.',
    ],
    [
      '하는 한',
      'haneun han',
      'na medida em que',
      'locução',
      '결과가 바뀌는 한 중요해요.',
      'Gyeolgwaga bakkwineun han jungyohaeyo.',
      'Importa na medida em que muda o resultado.',
    ],
    [
      '완화하다',
      'wanhwahada',
      'mitigar',
      'verbo',
      '위험을 완화하는 조치예요.',
      'Wiheomeul wanhwahaneun jochiyeyo.',
      'São medidas que mitigam o risco.',
    ],
    [
      '우세하다',
      'usehada',
      'prevalecer',
      'verbo',
      '결국 상식이 우세했어요.',
      'Gyeolguk sangsigi usehaesseoyo.',
      'No fim, o bom senso prevaleceu.',
    ],
  ],
  C2: [
    [
      '본말전도',
      'bonmaljeondo',
      'inverter prioridades',
      'expressão',
      '그건 본말전도예요.',
      'Geugeon bonmaljeondoyeyo.',
      'Isso é inverter as prioridades.',
    ],
    [
      '임기응변',
      'imgieungbyeon',
      'adaptar-se na hora',
      'expressão',
      '임기응변으로 대처했어요.',
      'Imgieungbyeoneuro daecheohaesseoyo.',
      'Ele se virou na hora.',
    ],
    [
      '일석이조',
      'ilseogijo',
      'matar dois coelhos',
      'expressão',
      '이건 일석이조예요.',
      'Igeon ilseogijoyeyo.',
      'Isso é matar dois coelhos.',
    ],
    [
      '완곡하다',
      'wangokhada',
      'ser indireto / eufemístico',
      'adjetivo',
      '완곡한 표현을 썼어요.',
      'Wangokhan pyohyeoneul sseosseoyo.',
      'Usou uma expressão indireta.',
    ],
    [
      '얼버무리다',
      'eolbeomurida',
      'usar de evasivas',
      'verbo',
      '장관은 얼버무렸어요.',
      'Janggwaneun eolbeomuryeosseoyo.',
      'O ministro usou de evasivas.',
    ],
    [
      '얼렁뚱땅',
      'eolleongttungttang',
      'de qualquer jeito / driblando',
      'advérbio',
      '보고서가 실패를 얼렁뚱땅 넘겼어요.',
      'Bogoseoga silpaereul eolleongttungttang neomgyeosseoyo.',
      'O relatório driblou os fracassos.',
    ],
    [
      '불가피하다',
      'bulgapihada',
      'inevitável',
      'adjetivo',
      '쇠퇴는 불가피했어요.',
      'Soetoeneun bulgapihaesseoyo.',
      'O declínio foi inevitável.',
    ],
    [
      '표면상',
      'pyomyeonsang',
      'aparentemente',
      'advérbio',
      '표면상 건강 문제였어요.',
      'Pyomyeonsang geongang munjeyeosseoyo.',
      'Aparentemente, foi problema de saúde.',
    ],
    [
      '다름없다',
      'dareumeopda',
      'equivaler a',
      'adjetivo',
      '침묵은 동의나 다름없어요.',
      'Chimmugeun donguina dareumeopseoyo.',
      'Silêncio equivale a consentimento.',
    ],
    [
      '전형적',
      'jeonhyeongjeok',
      'típico / por excelência',
      'adjetivo',
      '전형적인 서울 사람이에요.',
      'Jeonhyeongjeogin Seoul saramieyo.',
      'É o seulense por excelência.',
    ],
    [
      '한 이상',
      'han isang',
      'uma vez que',
      'conjunção',
      '합의한 이상 진행합시다.',
      'Habuihan isang jinhaenghapsida.',
      'Uma vez que concordamos, sigamos.',
    ],
    [
      '종래',
      'jongnae',
      'até então',
      'advérbio',
      '종래 알려지지 않은 종이에요.',
      'Jongnae allyeojiji aneun jongieyo.',
      'É uma espécie até então desconhecida.',
    ],
  ],
};

/* ================================================================== *
 * Mandarim
 * ================================================================== */

const ZH: AsianLevelMap = {
  A2: [
    [
      '小区',
      'xiǎoqū',
      'condomínio / bairro',
      'substantivo',
      '我在这个小区长大。',
      'Wǒ zài zhège xiǎoqū zhǎngdà.',
      'Cresci neste bairro.',
    ],
    [
      '预约',
      'yùyuē',
      'agendamento',
      'substantivo',
      '我有医生预约。',
      'Wǒ yǒu yīshēng yùyuē.',
      'Tenho consulta marcada.',
    ],
    [
      '发票',
      'fāpiào',
      'nota fiscal',
      'substantivo',
      '请给我发票。',
      'Qǐng gěi wǒ fāpiào.',
      'Me dê a nota fiscal, por favor.',
    ],
    [
      '借给',
      'jiè gěi',
      'emprestar (dar)',
      'verbo',
      '你能借给我充电器吗？',
      'Nǐ néng jiè gěi wǒ chōngdiànqì ma?',
      'Pode me emprestar o carregador?',
    ],
    [
      '借',
      'jiè',
      'pegar emprestado',
      'verbo',
      '我借了朋友的车。',
      'Wǒ jièle péngyǒu de chē.',
      'Peguei o carro do amigo emprestado.',
    ],
    [
      '拥挤',
      'yōngjǐ',
      'lotado',
      'adjetivo',
      '早上地铁很拥挤。',
      'Zǎoshang dìtiě hěn yōngjǐ.',
      'De manhã o metrô fica lotado.',
    ],
    [
      '挺',
      'tǐng',
      'bastante / até que',
      'advérbio',
      '那部电影挺好的。',
      'Nà bù diànyǐng tǐng hǎo de.',
      'Aquele filme foi até que bom.',
    ],
    [
      '已经',
      'yǐjīng',
      'já',
      'advérbio',
      '她已经走了。',
      'Tā yǐjīng zǒu le.',
      'Ela já foi embora.',
    ],
    [
      '而是',
      'ér shì',
      'e sim / em vez disso',
      'conjunção',
      '不坐车，而是走路。',
      'Bù zuò chē, ér shì zǒulù.',
      'Não de carro, e sim a pé.',
    ],
    [
      '抱怨',
      'bàoyuàn',
      'reclamar',
      'verbo',
      '他抱怨噪音。',
      'Tā bàoyuàn zàoyīn.',
      'Ele reclamou do barulho.',
    ],
    [
      '修',
      'xiū',
      'consertar',
      'verbo',
      '你能修淋浴吗？',
      'Nǐ néng xiū línyù ma?',
      'Consegue consertar o chuveiro?',
    ],
    [
      '付款',
      'fùkuǎn',
      'pagar',
      'verbo',
      '我用卡付款。',
      'Wǒ yòng kǎ fùkuǎn.',
      'Vou pagar com cartão.',
    ],
  ],
  B1: [
    [
      '截止日期',
      'jiézhǐ rìqī',
      'prazo final',
      'substantivo',
      '截止日期是星期五。',
      'Jiézhǐ rìqī shì xīngqīwǔ.',
      'O prazo é sexta.',
    ],
    [
      '成果',
      'chéngguǒ',
      'resultado / conquista',
      'substantivo',
      '取得了很大成果。',
      'Qǔdéle hěn dà chéngguǒ.',
      'Obtivemos um grande resultado.',
    ],
    [
      '问题',
      'wèntí',
      'questão / problema',
      'substantivo',
      '这是个重要问题。',
      'Zhè shì gè zhòngyào wèntí.',
      'Esta é uma questão importante.',
    ],
    [
      '以为',
      'yǐwéi',
      'presumir (erradamente)',
      'verbo',
      '我以为你知道。',
      'Wǒ yǐwéi nǐ zhīdào.',
      'Eu presumi que você soubesse.',
    ],
    [
      '指出',
      'zhǐchū',
      'apontar',
      'verbo',
      '他指出了一个错误。',
      'Tā zhǐchūle yīgè cuòwù.',
      'Ele apontou um erro.',
    ],
    [
      '可靠',
      'kěkào',
      'confiável',
      'adjetivo',
      '他是可靠的同事。',
      'Tā shì kěkào de tóngshì.',
      'Ele é um colega confiável.',
    ],
    [
      '而',
      'ér',
      'ao passo que',
      'conjunção',
      '他喜欢茶，而我喜欢咖啡。',
      'Tā xǐhuān chá, ér wǒ xǐhuān kāfēi.',
      'Ele gosta de chá, ao passo que eu de café.',
    ],
    [
      '结果',
      'jiéguǒ',
      'no fim / resultado',
      'advérbio',
      '结果他们同意了。',
      'Jiéguǒ tāmen tóngyì le.',
      'No fim, eles concordaram.',
    ],
    [
      '吃力',
      'chīlì',
      'custoso / difícil',
      'adjetivo',
      '我学语法很吃力。',
      'Wǒ xué yǔfǎ hěn chīlì.',
      'Aprender gramática foi difícil para mim.',
    ],
    [
      '收入',
      'shōurù',
      'renda',
      'substantivo',
      '收入来自旅游。',
      'Shōurù láizì lǚyóu.',
      'A renda vem do turismo.',
    ],
    [
      '也许',
      'yěxǔ',
      'talvez',
      'advérbio',
      '也许不会下雨。',
      'Yěxǔ bù huì xià yǔ.',
      'Talvez não chova.',
    ],
    [
      '机会',
      'jīhuì',
      'oportunidade',
      'substantivo',
      '这是个好机会。',
      'Zhè shì gè hǎo jīhuì.',
      'Esta é uma boa oportunidade.',
    ],
  ],
  B2: [
    [
      '角度',
      'jiǎodù',
      'ângulo / perspectiva',
      'substantivo',
      '换个角度看。',
      'Huàn gè jiǎodù kàn.',
      'Vejamos de outro ângulo.',
    ],
    [
      '缺点',
      'quēdiǎn',
      'desvantagem',
      'substantivo',
      '最大缺点是成本。',
      'Zuìdà quēdiǎn shì chéngběn.',
      'A maior desvantagem é o custo.',
    ],
    [
      '偏见',
      'piānjiàn',
      'viés / preconceito',
      'substantivo',
      '数据存在偏见。',
      'Shùjù cúnzài piānjiàn.',
      'Há viés nos dados.',
    ],
    [
      '承认',
      'chéngrèn',
      'reconhecer / admitir',
      'verbo',
      '他承认错了。',
      'Tā chéngrèn cuò le.',
      'Ele admitiu que errou.',
    ],
    [
      '削弱',
      'xuēruò',
      'enfraquecer / minar',
      'verbo',
      '延误削弱了信任。',
      'Yánwù xuēruòle xìnrèn.',
      'O atraso minou a confiança.',
    ],
    [
      '忽略',
      'hūlüè',
      'deixar passar',
      'verbo',
      '我们忽略了一个细节。',
      'Wǒmen hūlüèle yīgè xìjié.',
      'Deixamos passar um detalhe.',
    ],
    [
      '彻底',
      'chèdǐ',
      'minucioso / completo',
      'adjetivo',
      '这是彻底的分析。',
      'Zhè shì chèdǐ de fēnxī.',
      'Esta é uma análise minuciosa.',
    ],
    [
      '有说服力',
      'yǒu shuōfúlì',
      'convincente',
      'adjetivo',
      '这是有说服力的论点。',
      'Zhè shì yǒu shuōfúlì de lùndiǎn.',
      'É um argumento convincente.',
    ],
    [
      '然而',
      'rán’ér',
      'no entanto',
      'conjunção',
      '下雨了，然而我们还是出门了。',
      'Xià yǔ le, rán’ér wǒmen háishì chūmén le.',
      'Choveu; no entanto, saímos.',
    ],
    [
      '利用',
      'lìyòng',
      'aproveitar / utilizar',
      'verbo',
      '他们利用了本地知识。',
      'Tāmen lìyòngle běndì zhīshì.',
      'Aproveitaram o conhecimento local.',
    ],
    [
      '范围',
      'fànwéi',
      'escopo',
      'substantivo',
      '那超出了范围。',
      'Nà chāochūle fànwéi.',
      'Isso ultrapassa o escopo.',
    ],
    [
      '趋势',
      'qūshì',
      'tendência',
      'substantivo',
      '有上升趋势。',
      'Yǒu shàngshēng qūshì.',
      'Há tendência de alta.',
    ],
  ],
  C1: [
    [
      '注意事项',
      'zhùyì shìxiàng',
      'ressalva / observação',
      'substantivo',
      '有一个注意事项。',
      'Yǒu yīgè zhùyì shìxiàng.',
      'Há uma ressalva.',
    ],
    [
      '差异',
      'chāyì',
      'discrepância',
      'substantivo',
      '数字之间有差异。',
      'Shùzì zhījiān yǒu chāyì.',
      'Há discrepância entre os números.',
    ],
    [
      '前提',
      'qiántí',
      'premissa',
      'substantivo',
      '基于错误的前提。',
      'Jīyú cuòwù de qiántí.',
      'Baseia-se numa premissa falsa.',
    ],
    [
      '证实',
      'zhèngshí',
      'comprovar',
      'verbo',
      '他无法证实这一说法。',
      'Tā wúfǎ zhèngshí zhè yī shuōfǎ.',
      'Ele não conseguiu comprovar a alegação.',
    ],
    [
      '调和',
      'tiáohé',
      'conciliar',
      'verbo',
      '很难调和两种说法。',
      'Hěn nán tiáohé liǎng zhǒng shuōfǎ.',
      'É difícil conciliar as duas versões.',
    ],
    [
      '阻碍',
      'zǔ’ài',
      'impedir',
      'verbo',
      '预算削减阻碍了测试。',
      'Yùsuàn xuējiǎn zǔ’àile cèshì.',
      'Cortes impediram os testes.',
    ],
    [
      '薄弱',
      'bóruò',
      'tênue / frágil',
      'adjetivo',
      '关联很薄弱。',
      'Guānlián hěn bóruò.',
      'A relação é bem frágil.',
    ],
    [
      '普遍',
      'pǔbiàn',
      'generalizado',
      'adjetivo',
      '这个问题很普遍。',
      'Zhège wèntí hěn pǔbiàn.',
      'Esse problema é generalizado.',
    ],
    [
      '尽管如此',
      'jǐnguǎn rúcǐ',
      'não obstante',
      'locução',
      '尽管如此，仍然成功了。',
      'Jǐnguǎn rúcǐ, réngrán chénggōng le.',
      'Não obstante, deu certo.',
    ],
    [
      '就……而言',
      'jiù… ér yán',
      'no que diz respeito a',
      'locução',
      '就结果而言很重要。',
      'Jiù jiéguǒ ér yán hěn zhòngyào.',
      'No que diz respeito ao resultado, é importante.',
    ],
    [
      '缓解',
      'huǎnjiě',
      'mitigar',
      'verbo',
      '这些措施缓解了风险。',
      'Zhèxiē cuòshī huǎnjiěle fēngxiǎn.',
      'Essas medidas mitigaram o risco.',
    ],
    [
      '占上风',
      'zhàn shàngfēng',
      'prevalecer',
      'locução',
      '常识最终占了上风。',
      'Chángshí zuìzhōng zhànle shàngfēng.',
      'O bom senso acabou prevalecendo.',
    ],
  ],
  C2: [
    [
      '本末倒置',
      'běnmò dàozhì',
      'inverter prioridades',
      'expressão',
      '这是本末倒置。',
      'Zhè shì běnmò dàozhì.',
      'Isso é inverter as prioridades.',
    ],
    [
      '随机应变',
      'suíjī yìngbiàn',
      'adaptar-se às circunstâncias',
      'expressão',
      '他随机应变。',
      'Tā suíjī yìngbiàn.',
      'Ele se adaptou às circunstâncias.',
    ],
    [
      '一举两得',
      'yījǔ liǎngdé',
      'matar dois coelhos',
      'expressão',
      '这真是一举两得。',
      'Zhè zhēnshì yījǔ liǎngdé.',
      'Isso é mesmo matar dois coelhos.',
    ],
    [
      '委婉',
      'wěiwǎn',
      'eufemístico / indireto',
      'adjetivo',
      '他用了委婉的说法。',
      'Tā yòngle wěiwǎn de shuōfǎ.',
      'Ele usou uma forma indireta.',
    ],
    [
      '含糊其辞',
      'hánhú qící',
      'usar de evasivas',
      'expressão',
      '部长含糊其辞。',
      'Bùzhǎng hánhú qící.',
      'O ministro usou de evasivas.',
    ],
    [
      '避重就轻',
      'bìzhòng jiùqīng',
      'fugir do essencial',
      'expressão',
      '报告避重就轻。',
      'Bàogào bìzhòng jiùqīng.',
      'O relatório foge do essencial.',
    ],
    [
      '不可避免',
      'bùkě bìmiǎn',
      'inevitável',
      'adjetivo',
      '衰退不可避免。',
      'Shuāituì bùkě bìmiǎn.',
      'O declínio é inevitável.',
    ],
    [
      '表面上',
      'biǎomiàn shàng',
      'aparentemente',
      'advérbio',
      '表面上是健康原因。',
      'Biǎomiàn shàng shì jiànkāng yuányīn.',
      'Aparentemente, por motivos de saúde.',
    ],
    [
      '等于',
      'děngyú',
      'equivaler a',
      'verbo',
      '沉默等于同意。',
      'Chénmò děngyú tóngyì.',
      'Silêncio equivale a consentimento.',
    ],
    [
      '典型',
      'diǎnxíng',
      'típico / por excelência',
      'adjetivo',
      '他是典型的北京人。',
      'Tā shì diǎnxíng de Běijīng rén.',
      'Ele é o pequinês por excelência.',
    ],
    [
      '既然',
      'jìrán',
      'visto que',
      'conjunção',
      '既然同意了，就开始吧。',
      'Jìrán tóngyì le, jiù kāishǐ ba.',
      'Visto que concordamos, vamos começar.',
    ],
    [
      '迄今',
      'qìjīn',
      'até então / até agora',
      'advérbio',
      '迄今未知的物种。',
      'Qìjīn wèizhī de wùzhǒng.',
      'Uma espécie até agora desconhecida.',
    ],
  ],
};

/* ================================================================== *
 * Registro
 * ================================================================== */

const ASIAN_LEVEL_VOCABULARY: Partial<Record<LanguageCode, AsianLevelMap>> = {
  ja: JA,
  ko: KO,
  zh: ZH,
};

/** Verbetes asiáticos de um idioma num nível; lista vazia quando não houver. */
export function asianLevelVocabulary(
  language: LanguageCode,
  level: CefrLevel,
): AsianLevelEntry[] {
  return ASIAN_LEVEL_VOCABULARY[language]?.[level] ?? [];
}

export { ASIAN_LEVEL_VOCABULARY };
