/**
 * Vocabulário semente dos 5 idiomas iniciais.
 *
 * ## Critério de seleção
 *
 * As palavras seguem **frequência de uso real**, não ordem temática arbitrária.
 * As 1.000 palavras mais frequentes de uma língua cobrem cerca de 80% de um
 * texto corrente; as 3.000 primeiras cobrem ~95% da fala cotidiana. Ensinar na
 * ordem de frequência é a alavanca mais eficiente que existe em aquisição de
 * vocabulário — e é onde apps organizados por "temas" (cores, animais, frutas)
 * desperdiçam meses do usuário.
 *
 * Cada verbete tem exemplo em contexto, porque palavra isolada não se fixa: a
 * memória guarda a frase, não o par de tradução.
 *
 * Este arquivo é a **semente offline** embutida no binário — o que garante que
 * um usuário sem internet consiga começar a estudar no primeiro minuto. O
 * corpus completo (3.000+ termos por idioma, com áudio) chega pelos pacotes de
 * download.
 */

import type { CefrLevel, LanguageCode, VocabularyItem } from '@/domain/types';

/**
 * Formato compacto: [termo, tradução PT, classe, fonética, exemplo, tradução do exemplo, nível]
 * Compacto de propósito — é dado, não código, e escrever como objeto quadruplicaria
 * o tamanho do bundle sem ganho de legibilidade.
 */
type Entry = [string, string, string, string, string, string, CefrLevel];

const EN: Entry[] = [
  ['the', 'o / a', 'artigo', 'ðə', 'The book is on the table.', 'O livro está na mesa.', 'A1'],
  ['be', 'ser / estar', 'verbo', 'biː', 'I am happy today.', 'Estou feliz hoje.', 'A1'],
  ['have', 'ter', 'verbo', 'hæv', 'I have two brothers.', 'Eu tenho dois irmãos.', 'A1'],
  ['do', 'fazer', 'verbo', 'duː', 'What do you do?', 'O que você faz?', 'A1'],
  ['say', 'dizer', 'verbo', 'seɪ', 'What did you say?', 'O que você disse?', 'A1'],
  ['go', 'ir', 'verbo', 'ɡoʊ', 'I go to work by bus.', 'Vou para o trabalho de ônibus.', 'A1'],
  [
    'get',
    'conseguir / pegar',
    'verbo',
    'ɡet',
    'I need to get some water.',
    'Preciso pegar um pouco de água.',
    'A1',
  ],
  [
    'make',
    'fazer / criar',
    'verbo',
    'meɪk',
    'She makes great coffee.',
    'Ela faz um café ótimo.',
    'A1',
  ],
  [
    'know',
    'saber / conhecer',
    'verbo',
    'noʊ',
    'I know the answer.',
    'Eu sei a resposta.',
    'A1',
  ],
  [
    'think',
    'pensar / achar',
    'verbo',
    'θɪŋk',
    'I think you are right.',
    'Acho que você tem razão.',
    'A1',
  ],
  ['take', 'pegar / levar', 'verbo', 'teɪk', 'Take your time.', 'Vá com calma.', 'A1'],
  ['see', 'ver', 'verbo', 'siː', 'I can see the sea.', 'Consigo ver o mar.', 'A1'],
  ['come', 'vir', 'verbo', 'kʌm', 'Come here, please.', 'Venha aqui, por favor.', 'A1'],
  [
    'want',
    'querer',
    'verbo',
    'wɑːnt',
    'I want to learn English.',
    'Quero aprender inglês.',
    'A1',
  ],
  ['look', 'olhar / parecer', 'verbo', 'lʊk', 'You look tired.', 'Você parece cansado.', 'A1'],
  ['use', 'usar', 'verbo', 'juːz', 'Can I use your phone?', 'Posso usar seu telefone?', 'A1'],
  [
    'find',
    'encontrar',
    'verbo',
    'faɪnd',
    'I cannot find my keys.',
    'Não consigo encontrar minhas chaves.',
    'A1',
  ],
  ['give', 'dar', 'verbo', 'ɡɪv', 'Give me a minute.', 'Me dê um minuto.', 'A1'],
  ['tell', 'contar', 'verbo', 'tel', 'Tell me everything.', 'Me conte tudo.', 'A1'],
  [
    'work',
    'trabalhar / trabalho',
    'verbo',
    'wɜːrk',
    'I work from home.',
    'Eu trabalho de casa.',
    'A1',
  ],
  ['time', 'tempo / hora', 'substantivo', 'taɪm', 'What time is it?', 'Que horas são?', 'A1'],
  [
    'year',
    'ano',
    'substantivo',
    'jɪr',
    'Last year was hard.',
    'O ano passado foi difícil.',
    'A1',
  ],
  [
    'people',
    'pessoas',
    'substantivo',
    'ˈpiːpl',
    'Many people came.',
    'Muitas pessoas vieram.',
    'A1',
  ],
  [
    'way',
    'caminho / jeito',
    'substantivo',
    'weɪ',
    'This is the best way.',
    'Este é o melhor jeito.',
    'A1',
  ],
  ['day', 'dia', 'substantivo', 'deɪ', 'Have a nice day.', 'Tenha um bom dia.', 'A1'],
  [
    'man',
    'homem',
    'substantivo',
    'mæn',
    'The man is waiting.',
    'O homem está esperando.',
    'A1',
  ],
  [
    'woman',
    'mulher',
    'substantivo',
    'ˈwʊmən',
    'The woman is a doctor.',
    'A mulher é médica.',
    'A1',
  ],
  [
    'child',
    'criança',
    'substantivo',
    'tʃaɪld',
    'The child is sleeping.',
    'A criança está dormindo.',
    'A1',
  ],
  [
    'water',
    'água',
    'substantivo',
    'ˈwɔːtər',
    'A glass of water, please.',
    'Um copo de água, por favor.',
    'A1',
  ],
  [
    'food',
    'comida',
    'substantivo',
    'fuːd',
    'The food is delicious.',
    'A comida está deliciosa.',
    'A1',
  ],
  [
    'house',
    'casa',
    'substantivo',
    'haʊs',
    'Their house is big.',
    'A casa deles é grande.',
    'A1',
  ],
  ['good', 'bom', 'adjetivo', 'ɡʊd', 'That is a good idea.', 'Essa é uma boa ideia.', 'A1'],
  ['new', 'novo', 'adjetivo', 'nuː', 'I bought a new phone.', 'Comprei um celular novo.', 'A1'],
  [
    'first',
    'primeiro',
    'adjetivo',
    'fɜːrst',
    'This is my first time.',
    'Esta é a minha primeira vez.',
    'A1',
  ],
  [
    'big',
    'grande',
    'adjetivo',
    'bɪɡ',
    'The city is very big.',
    'A cidade é muito grande.',
    'A1',
  ],
  [
    'small',
    'pequeno',
    'adjetivo',
    'smɔːl',
    'A small coffee, please.',
    'Um café pequeno, por favor.',
    'A1',
  ],
  [
    'because',
    'porque',
    'conjunção',
    'bɪˈkɔːz',
    'I stayed because it rained.',
    'Fiquei porque choveu.',
    'A2',
  ],
  [
    'however',
    'porém',
    'advérbio',
    'haʊˈevər',
    'It is late; however, I will go.',
    'É tarde; porém, vou mesmo assim.',
    'B1',
  ],
  [
    'although',
    'embora',
    'conjunção',
    'ɔːlˈðoʊ',
    'Although it rained, we went out.',
    'Embora tenha chovido, saímos.',
    'B1',
  ],
  [
    'achieve',
    'alcançar',
    'verbo',
    'əˈtʃiːv',
    'She achieved her goal.',
    'Ela alcançou seu objetivo.',
    'B2',
  ],
];

const ES: Entry[] = [
  [
    'el / la',
    'o / a',
    'artigo',
    'el',
    'El libro está en la mesa.',
    'O livro está na mesa.',
    'A1',
  ],
  ['ser', 'ser', 'verbo', 'seɾ', 'Soy brasileño.', 'Sou brasileiro.', 'A1'],
  ['estar', 'estar', 'verbo', 'esˈtaɾ', 'Estoy cansado.', 'Estou cansado.', 'A1'],
  ['tener', 'ter', 'verbo', 'teˈneɾ', 'Tengo veinte años.', 'Tenho vinte anos.', 'A1'],
  ['hacer', 'fazer', 'verbo', 'aˈθeɾ', '¿Qué haces?', 'O que você faz?', 'A1'],
  ['ir', 'ir', 'verbo', 'iɾ', 'Voy al trabajo.', 'Vou para o trabalho.', 'A1'],
  ['poder', 'poder', 'verbo', 'poˈðeɾ', '¿Puedo ayudarte?', 'Posso te ajudar?', 'A1'],
  ['decir', 'dizer', 'verbo', 'deˈθiɾ', '¿Qué dijiste?', 'O que você disse?', 'A1'],
  [
    'querer',
    'querer',
    'verbo',
    'keˈɾeɾ',
    'Quiero aprender español.',
    'Quero aprender espanhol.',
    'A1',
  ],
  ['saber', 'saber', 'verbo', 'saˈβeɾ', 'No sé la respuesta.', 'Não sei a resposta.', 'A1'],
  ['ver', 'ver', 'verbo', 'beɾ', 'Puedo ver el mar.', 'Consigo ver o mar.', 'A1'],
  ['dar', 'dar', 'verbo', 'daɾ', 'Dame un minuto.', 'Me dê um minuto.', 'A1'],
  ['venir', 'vir', 'verbo', 'beˈniɾ', 'Ven aquí, por favor.', 'Venha aqui, por favor.', 'A1'],
  ['hablar', 'falar', 'verbo', 'aˈβlaɾ', '¿Hablas español?', 'Você fala espanhol?', 'A1'],
  ['tiempo', 'tempo', 'substantivo', 'ˈtjempo', 'No tengo tiempo.', 'Não tenho tempo.', 'A1'],
  [
    'año',
    'ano',
    'substantivo',
    'ˈaɲo',
    'El año pasado fue difícil.',
    'O ano passado foi difícil.',
    'A1',
  ],
  ['día', 'dia', 'substantivo', 'ˈdi.a', 'Que tengas buen día.', 'Tenha um bom dia.', 'A1'],
  ['casa', 'casa', 'substantivo', 'ˈkasa', 'Su casa es grande.', 'A casa dele é grande.', 'A1'],
  [
    'agua',
    'água',
    'substantivo',
    'ˈaɣwa',
    'Un vaso de agua, por favor.',
    'Um copo de água, por favor.',
    'A1',
  ],
  [
    'comida',
    'comida',
    'substantivo',
    'koˈmiða',
    'La comida está deliciosa.',
    'A comida está deliciosa.',
    'A1',
  ],
  ['gente', 'gente', 'substantivo', 'ˈxente', 'Vino mucha gente.', 'Veio muita gente.', 'A1'],
  [
    'trabajo',
    'trabalho',
    'substantivo',
    'tɾaˈβaxo',
    'Me gusta mi trabajo.',
    'Gosto do meu trabalho.',
    'A1',
  ],
  ['bueno', 'bom', 'adjetivo', 'ˈbweno', 'Es una buena idea.', 'É uma boa ideia.', 'A1'],
  [
    'nuevo',
    'novo',
    'adjetivo',
    'ˈnweβo',
    'Compré un teléfono nuevo.',
    'Comprei um telefone novo.',
    'A1',
  ],
  [
    'grande',
    'grande',
    'adjetivo',
    'ˈɡɾande',
    'La ciudad es muy grande.',
    'A cidade é muito grande.',
    'A1',
  ],
  [
    'pequeño',
    'pequeno',
    'adjetivo',
    'peˈkeɲo',
    'Un café pequeño, por favor.',
    'Um café pequeno, por favor.',
    'A1',
  ],
  [
    'porque',
    'porque',
    'conjunção',
    'poɾˈke',
    'Me quedé porque llovió.',
    'Fiquei porque choveu.',
    'A2',
  ],
  [
    'aunque',
    'embora',
    'conjunção',
    'ˈawnke',
    'Aunque llovió, salimos.',
    'Embora tenha chovido, saímos.',
    'B1',
  ],
  [
    'sin embargo',
    'no entanto',
    'locução',
    'sin emˈbaɾɣo',
    'Es tarde; sin embargo, iré.',
    'É tarde; no entanto, irei.',
    'B1',
  ],
  [
    'lograr',
    'alcançar',
    'verbo',
    'loˈɣɾaɾ',
    'Logró su objetivo.',
    'Ele alcançou seu objetivo.',
    'B2',
  ],
];

const FR: Entry[] = [
  [
    'le / la',
    'o / a',
    'artigo',
    'lə',
    'Le livre est sur la table.',
    'O livro está na mesa.',
    'A1',
  ],
  ['être', 'ser / estar', 'verbo', 'ɛtʁ', 'Je suis fatigué.', 'Estou cansado.', 'A1'],
  ['avoir', 'ter', 'verbo', 'avwaʁ', "J'ai vingt ans.", 'Tenho vinte anos.', 'A1'],
  ['faire', 'fazer', 'verbo', 'fɛʁ', 'Que fais-tu ?', 'O que você faz?', 'A1'],
  ['aller', 'ir', 'verbo', 'ale', 'Je vais au travail.', 'Vou para o trabalho.', 'A1'],
  ['pouvoir', 'poder', 'verbo', 'puvwaʁ', 'Je peux t’aider ?', 'Posso te ajudar?', 'A1'],
  ['dire', 'dizer', 'verbo', 'diʁ', "Qu'est-ce que tu as dit ?", 'O que você disse?', 'A1'],
  [
    'vouloir',
    'querer',
    'verbo',
    'vulwaʁ',
    'Je veux apprendre le français.',
    'Quero aprender francês.',
    'A1',
  ],
  ['savoir', 'saber', 'verbo', 'savwaʁ', 'Je ne sais pas.', 'Não sei.', 'A1'],
  ['voir', 'ver', 'verbo', 'vwaʁ', 'Je vois la mer.', 'Vejo o mar.', 'A1'],
  [
    'venir',
    'vir',
    'verbo',
    'v(ə)niʁ',
    'Viens ici, s’il te plaît.',
    'Venha aqui, por favor.',
    'A1',
  ],
  ['parler', 'falar', 'verbo', 'paʁle', 'Tu parles français ?', 'Você fala francês?', 'A1'],
  ['prendre', 'pegar', 'verbo', 'pʁɑ̃dʁ', 'Je prends le bus.', 'Pego o ônibus.', 'A1'],
  ['temps', 'tempo', 'substantivo', 'tɑ̃', "Je n'ai pas le temps.", 'Não tenho tempo.', 'A1'],
  [
    'année',
    'ano',
    'substantivo',
    'ane',
    "L'année dernière était dure.",
    'O ano passado foi difícil.',
    'A1',
  ],
  ['jour', 'dia', 'substantivo', 'ʒuʁ', 'Bonne journée !', 'Tenha um bom dia!', 'A1'],
  [
    'maison',
    'casa',
    'substantivo',
    'mɛzɔ̃',
    'Leur maison est grande.',
    'A casa deles é grande.',
    'A1',
  ],
  [
    'eau',
    'água',
    'substantivo',
    'o',
    "Un verre d'eau, s'il vous plaît.",
    'Um copo de água, por favor.',
    'A1',
  ],
  [
    'nourriture',
    'comida',
    'substantivo',
    'nuʁityʁ',
    'La nourriture est délicieuse.',
    'A comida está deliciosa.',
    'A1',
  ],
  [
    'gens',
    'pessoas',
    'substantivo',
    'ʒɑ̃',
    'Beaucoup de gens sont venus.',
    'Muitas pessoas vieram.',
    'A1',
  ],
  [
    'travail',
    'trabalho',
    'substantivo',
    'tʁavaj',
    "J'aime mon travail.",
    'Gosto do meu trabalho.',
    'A1',
  ],
  ['bon', 'bom', 'adjetivo', 'bɔ̃', "C'est une bonne idée.", 'É uma boa ideia.', 'A1'],
  [
    'nouveau',
    'novo',
    'adjetivo',
    'nuvo',
    "J'ai un nouveau téléphone.",
    'Tenho um telefone novo.',
    'A1',
  ],
  [
    'grand',
    'grande',
    'adjetivo',
    'ɡʁɑ̃',
    'La ville est très grande.',
    'A cidade é muito grande.',
    'A1',
  ],
  [
    'petit',
    'pequeno',
    'adjetivo',
    'p(ə)ti',
    'Un petit café, s’il vous plaît.',
    'Um café pequeno, por favor.',
    'A1',
  ],
  [
    'parce que',
    'porque',
    'conjunção',
    'paʁs kə',
    "Je suis resté parce qu'il pleuvait.",
    'Fiquei porque estava chovendo.',
    'A2',
  ],
  [
    'bien que',
    'embora',
    'conjunção',
    'bjɛ̃ kə',
    "Bien qu'il pleuve, nous sortons.",
    'Embora chova, saímos.',
    'B1',
  ],
  [
    'cependant',
    'no entanto',
    'advérbio',
    'səpɑ̃dɑ̃',
    'Il est tard ; cependant, j’irai.',
    'É tarde; no entanto, irei.',
    'B1',
  ],
  [
    'atteindre',
    'alcançar',
    'verbo',
    'atɛ̃dʁ',
    'Elle a atteint son objectif.',
    'Ela alcançou seu objetivo.',
    'B2',
  ],
];

const IT: Entry[] = [
  ['il / la', 'o / a', 'artigo', 'il', 'Il libro è sul tavolo.', 'O livro está na mesa.', 'A1'],
  ['essere', 'ser / estar', 'verbo', 'ˈɛssere', 'Sono stanco.', 'Estou cansado.', 'A1'],
  ['avere', 'ter', 'verbo', 'aˈvere', 'Ho vent’anni.', 'Tenho vinte anos.', 'A1'],
  ['fare', 'fazer', 'verbo', 'ˈfare', 'Cosa fai?', 'O que você faz?', 'A1'],
  ['andare', 'ir', 'verbo', 'anˈdare', 'Vado al lavoro.', 'Vou para o trabalho.', 'A1'],
  ['potere', 'poder', 'verbo', 'poˈtere', 'Posso aiutarti?', 'Posso te ajudar?', 'A1'],
  ['dire', 'dizer', 'verbo', 'ˈdire', 'Cosa hai detto?', 'O que você disse?', 'A1'],
  [
    'volere',
    'querer',
    'verbo',
    'voˈlere',
    'Voglio imparare l’italiano.',
    'Quero aprender italiano.',
    'A1',
  ],
  ['sapere', 'saber', 'verbo', 'saˈpere', 'Non lo so.', 'Não sei.', 'A1'],
  ['vedere', 'ver', 'verbo', 'veˈdere', 'Vedo il mare.', 'Vejo o mar.', 'A1'],
  [
    'venire',
    'vir',
    'verbo',
    'veˈnire',
    'Vieni qui, per favore.',
    'Venha aqui, por favor.',
    'A1',
  ],
  ['parlare', 'falar', 'verbo', 'parˈlare', 'Parli italiano?', 'Você fala italiano?', 'A1'],
  ['tempo', 'tempo', 'substantivo', 'ˈtɛmpo', 'Non ho tempo.', 'Não tenho tempo.', 'A1'],
  [
    'anno',
    'ano',
    'substantivo',
    'ˈanno',
    "L'anno scorso è stato difficile.",
    'O ano passado foi difícil.',
    'A1',
  ],
  ['giorno', 'dia', 'substantivo', 'ˈdʒorno', 'Buona giornata!', 'Tenha um bom dia!', 'A1'],
  [
    'casa',
    'casa',
    'substantivo',
    'ˈkasa',
    'La loro casa è grande.',
    'A casa deles é grande.',
    'A1',
  ],
  [
    'acqua',
    'água',
    'substantivo',
    'ˈakkwa',
    "Un bicchiere d'acqua, per favore.",
    'Um copo de água, por favor.',
    'A1',
  ],
  [
    'cibo',
    'comida',
    'substantivo',
    'ˈtʃibo',
    'Il cibo è delizioso.',
    'A comida está deliciosa.',
    'A1',
  ],
  [
    'gente',
    'gente',
    'substantivo',
    'ˈdʒɛnte',
    'È venuta molta gente.',
    'Veio muita gente.',
    'A1',
  ],
  [
    'lavoro',
    'trabalho',
    'substantivo',
    'laˈvoro',
    'Mi piace il mio lavoro.',
    'Gosto do meu trabalho.',
    'A1',
  ],
  ['buono', 'bom', 'adjetivo', 'ˈbwɔno', 'È una buona idea.', 'É uma boa ideia.', 'A1'],
  [
    'nuovo',
    'novo',
    'adjetivo',
    'ˈnwɔvo',
    'Ho un telefono nuovo.',
    'Tenho um telefone novo.',
    'A1',
  ],
  [
    'grande',
    'grande',
    'adjetivo',
    'ˈɡrande',
    'La città è molto grande.',
    'A cidade é muito grande.',
    'A1',
  ],
  [
    'piccolo',
    'pequeno',
    'adjetivo',
    'ˈpikkolo',
    'Un caffè piccolo, per favore.',
    'Um café pequeno, por favor.',
    'A1',
  ],
  [
    'perché',
    'porque',
    'conjunção',
    'perˈke',
    'Sono rimasto perché pioveva.',
    'Fiquei porque estava chovendo.',
    'A2',
  ],
  [
    'sebbene',
    'embora',
    'conjunção',
    'sebˈbɛne',
    'Sebbene piova, usciamo.',
    'Embora chova, saímos.',
    'B1',
  ],
  [
    'tuttavia',
    'no entanto',
    'advérbio',
    'tuttaˈvia',
    'È tardi; tuttavia, andrò.',
    'É tarde; no entanto, irei.',
    'B1',
  ],
  [
    'raggiungere',
    'alcançar',
    'verbo',
    'radˈdʒundʒere',
    'Ha raggiunto il suo obiettivo.',
    'Ele alcançou seu objetivo.',
    'B2',
  ],
];

const DE: Entry[] = [
  [
    'der / die / das',
    'o / a',
    'artigo',
    'deːɐ̯',
    'Das Buch liegt auf dem Tisch.',
    'O livro está na mesa.',
    'A1',
  ],
  ['sein', 'ser / estar', 'verbo', 'zaɪ̯n', 'Ich bin müde.', 'Estou cansado.', 'A1'],
  ['haben', 'ter', 'verbo', 'ˈhaːbn̩', 'Ich habe zwei Brüder.', 'Tenho dois irmãos.', 'A1'],
  ['machen', 'fazer', 'verbo', 'ˈmaxn̩', 'Was machst du?', 'O que você faz?', 'A1'],
  ['gehen', 'ir', 'verbo', 'ˈɡeːən', 'Ich gehe zur Arbeit.', 'Vou para o trabalho.', 'A1'],
  ['können', 'poder', 'verbo', 'ˈkœnən', 'Kann ich dir helfen?', 'Posso te ajudar?', 'A1'],
  ['sagen', 'dizer', 'verbo', 'ˈzaːɡn̩', 'Was hast du gesagt?', 'O que você disse?', 'A1'],
  [
    'wollen',
    'querer',
    'verbo',
    'ˈvɔlən',
    'Ich will Deutsch lernen.',
    'Quero aprender alemão.',
    'A1',
  ],
  ['wissen', 'saber', 'verbo', 'ˈvɪsn̩', 'Ich weiß es nicht.', 'Não sei.', 'A1'],
  ['sehen', 'ver', 'verbo', 'ˈzeːən', 'Ich sehe das Meer.', 'Vejo o mar.', 'A1'],
  ['kommen', 'vir', 'verbo', 'ˈkɔmən', 'Komm her, bitte.', 'Venha aqui, por favor.', 'A1'],
  ['sprechen', 'falar', 'verbo', 'ˈʃpʁɛçn̩', 'Sprichst du Deutsch?', 'Você fala alemão?', 'A1'],
  ['Zeit', 'tempo', 'substantivo', 'tsaɪ̯t', 'Ich habe keine Zeit.', 'Não tenho tempo.', 'A1'],
  [
    'Jahr',
    'ano',
    'substantivo',
    'jaːɐ̯',
    'Letztes Jahr war schwer.',
    'O ano passado foi difícil.',
    'A1',
  ],
  ['Tag', 'dia', 'substantivo', 'taːk', 'Schönen Tag!', 'Tenha um bom dia!', 'A1'],
  ['Haus', 'casa', 'substantivo', 'haʊ̯s', 'Ihr Haus ist groß.', 'A casa deles é grande.', 'A1'],
  [
    'Wasser',
    'água',
    'substantivo',
    'ˈvasɐ',
    'Ein Glas Wasser, bitte.',
    'Um copo de água, por favor.',
    'A1',
  ],
  [
    'Essen',
    'comida',
    'substantivo',
    'ˈɛsn̩',
    'Das Essen ist lecker.',
    'A comida está deliciosa.',
    'A1',
  ],
  [
    'Leute',
    'pessoas',
    'substantivo',
    'ˈlɔɪ̯tə',
    'Viele Leute sind gekommen.',
    'Muitas pessoas vieram.',
    'A1',
  ],
  [
    'Arbeit',
    'trabalho',
    'substantivo',
    'ˈaʁbaɪ̯t',
    'Ich mag meine Arbeit.',
    'Gosto do meu trabalho.',
    'A1',
  ],
  ['gut', 'bom', 'adjetivo', 'ɡuːt', 'Das ist eine gute Idee.', 'Essa é uma boa ideia.', 'A1'],
  [
    'neu',
    'novo',
    'adjetivo',
    'nɔɪ̯',
    'Ich habe ein neues Handy.',
    'Tenho um celular novo.',
    'A1',
  ],
  [
    'groß',
    'grande',
    'adjetivo',
    'ɡʁoːs',
    'Die Stadt ist sehr groß.',
    'A cidade é muito grande.',
    'A1',
  ],
  [
    'klein',
    'pequeno',
    'adjetivo',
    'klaɪ̯n',
    'Einen kleinen Kaffee, bitte.',
    'Um café pequeno, por favor.',
    'A1',
  ],
  [
    'weil',
    'porque',
    'conjunção',
    'vaɪ̯l',
    'Ich blieb, weil es regnete.',
    'Fiquei porque estava chovendo.',
    'A2',
  ],
  [
    'obwohl',
    'embora',
    'conjunção',
    'ɔpˈvoːl',
    'Obwohl es regnet, gehen wir raus.',
    'Embora chova, saímos.',
    'B1',
  ],
  [
    'jedoch',
    'no entanto',
    'advérbio',
    'jeˈdɔx',
    'Es ist spät; jedoch gehe ich.',
    'É tarde; no entanto, vou.',
    'B1',
  ],
  [
    'erreichen',
    'alcançar',
    'verbo',
    'ɛɐ̯ˈʁaɪ̯çn̩',
    'Sie hat ihr Ziel erreicht.',
    'Ela alcançou seu objetivo.',
    'B2',
  ],
];

const RAW: Record<LanguageCode, Entry[]> = { en: EN, es: ES, fr: FR, it: IT, de: DE };

/**
 * Expande as tuplas em `VocabularyItem`.
 *
 * O id é determinístico (`vocab:idioma:termo`) para que o mesmo verbete tenha
 * o mesmo id em qualquer dispositivo — requisito da sincronização sem conflito.
 */
export function buildVocabulary(language: LanguageCode): VocabularyItem[] {
  return (RAW[language] ?? []).map((entry, index) => {
    const [term, translation, partOfSpeech, phonetic, example, exampleTranslation, cefr] =
      entry;

    return {
      id: `vocab:${language}:${term.replace(/[^\p{L}\p{N}]/gu, '_').toLowerCase()}`,
      language,
      term,
      translation,
      partOfSpeech,
      phonetic,
      exampleSentence: example,
      exampleTranslation,
      // O índice na lista já é a ordem de frequência.
      frequencyRank: index + 1,
      cefr,
      tags: [partOfSpeech],
    };
  });
}

export function buildAllVocabulary(): VocabularyItem[] {
  return (Object.keys(RAW) as LanguageCode[]).flatMap(buildVocabulary);
}

/** Metadados de idioma para seletores e cards. */
export const LANGUAGE_META: Record<
  LanguageCode,
  { name: string; nativeName: string; flag: string; speakers: string }
> = {
  en: { name: 'Inglês', nativeName: 'English', flag: '🇺🇸', speakers: '1,5 bilhão' },
  es: { name: 'Espanhol', nativeName: 'Español', flag: '🇪🇸', speakers: '560 milhões' },
  fr: { name: 'Francês', nativeName: 'Français', flag: '🇫🇷', speakers: '310 milhões' },
  it: { name: 'Italiano', nativeName: 'Italiano', flag: '🇮🇹', speakers: '85 milhões' },
  de: { name: 'Alemão', nativeName: 'Deutsch', flag: '🇩🇪', speakers: '135 milhões' },
};
