/**
 * Vocabulário por nível CEFR — idiomas de escrita latina
 * =======================================================
 *
 * ## Por que A1 não está aqui
 *
 * A1 vem da lista de frequência em `vocabulary.ts`, e isso é uma decisão
 * pedagógica, não uma economia. No início, **frequência é o único critério que
 * importa**: as 500 palavras mais comuns cobrem a maior parte de qualquer
 * conversa banal, e são justamente artigos, verbos irregulares e preposições —
 * o esqueleto da língua. Organizar A1 por tema ("cores", "frutas") é o erro
 * clássico que faz o aluno saber dizer "abacaxi" antes de saber dizer "ainda".
 *
 * ## Por que A2 em diante está aqui
 *
 * Passado o núcleo de alta frequência, frequência para de discriminar: as
 * palavras 2.000 a 8.000 têm frequências parecidas entre si e o que muda é o
 * **domínio de uso**. A partir daí o corte certo é por situação e registro —
 * e é isso que cada nível abaixo representa:
 *
 *  - **A2** — sobrevivência ampliada: rotina, cidade, saúde, compras.
 *  - **B1** — opinião e narrativa: contar o que aconteceu, discordar, explicar.
 *  - **B2** — abstração e nuance: causa, consequência, hipótese, crítica.
 *  - **C1** — registro acadêmico e profissional, conectivos de argumentação.
 *  - **C2** — precisão idiomática, conotação, palavras que um nativo culto usa.
 *
 * ## A regra que este arquivo precisa cumprir
 *
 * **Nenhum termo se repete** — nem dentro de um nível, nem entre níveis, nem
 * contra a lista de A1. É o que garante que o aluno de C1 não receba de volta
 * a mesma pergunta que respondeu no A2. Há teste automatizado para isso em
 * `__tests__/vocabulary-levels.test.ts`; se você adicionar uma palavra que já
 * existe em outro nível, a suíte quebra de propósito.
 */

import type { CefrLevel, LanguageCode } from '@/domain/types';

/** [termo, tradução PT, classe, exemplo, tradução do exemplo] */
export type LevelEntry = [string, string, string, string, string];

/** Níveis que este arquivo cobre. A1 vem da lista de frequência. */
export const LEVELED_CEFR: CefrLevel[] = ['A2', 'B1', 'B2', 'C1', 'C2'];

type LevelMap = Partial<Record<CefrLevel, LevelEntry[]>>;

/* ================================================================== *
 * Inglês
 * ================================================================== */

const EN: LevelMap = {
  A2: [
    [
      'neighbourhood',
      'bairro',
      'substantivo',
      'I grew up in this neighbourhood.',
      'Cresci neste bairro.',
    ],
    [
      'appointment',
      'consulta / compromisso',
      'substantivo',
      'I have a doctor appointment at three.',
      'Tenho consulta médica às três.',
    ],
    [
      'receipt',
      'recibo / nota fiscal',
      'substantivo',
      'Keep the receipt in case you return it.',
      'Guarde a nota caso vá devolver.',
    ],
    [
      'borrow',
      'pegar emprestado',
      'verbo',
      'Can I borrow your charger?',
      'Posso pegar seu carregador emprestado?',
    ],
    [
      'lend',
      'emprestar (dar)',
      'verbo',
      'I lent him my bike last week.',
      'Emprestei minha bicicleta a ele semana passada.',
    ],
    [
      'afford',
      'ter condições de pagar',
      'verbo',
      "I can't afford a new phone right now.",
      'Não tenho condições de comprar um celular novo agora.',
    ],
    [
      'crowded',
      'cheio / lotado',
      'adjetivo',
      'The train is crowded in the morning.',
      'O trem fica lotado de manhã.',
    ],
    [
      'quite',
      'bastante / até que',
      'advérbio',
      'The film was quite good.',
      'O filme foi até que bom.',
    ],
    ['already', 'já', 'advérbio', 'She has already left.', 'Ela já saiu.'],
    [
      'instead',
      'em vez disso',
      'advérbio',
      "Let's take the bus instead.",
      'Vamos pegar o ônibus em vez disso.',
    ],
    [
      'complain',
      'reclamar',
      'verbo',
      'He complained about the noise.',
      'Ele reclamou do barulho.',
    ],
    [
      'fix',
      'consertar',
      'verbo',
      'Can you fix the shower?',
      'Você consegue consertar o chuveiro?',
    ],
  ],
  B1: [
    [
      'achievement',
      'conquista / realização',
      'substantivo',
      'Finishing the course was a real achievement.',
      'Terminar o curso foi uma conquista de verdade.',
    ],
    [
      'issue',
      'questão / problema',
      'substantivo',
      'We need to discuss this issue.',
      'Precisamos discutir essa questão.',
    ],
    [
      'deadline',
      'prazo final',
      'substantivo',
      'The deadline is next Friday.',
      'O prazo final é na próxima sexta.',
    ],
    [
      'assume',
      'presumir / supor',
      'verbo',
      'I assumed you knew about the meeting.',
      'Presumi que você soubesse da reunião.',
    ],
    [
      'manage',
      'conseguir / administrar',
      'verbo',
      'She managed to finish on time.',
      'Ela conseguiu terminar a tempo.',
    ],
    [
      'point out',
      'apontar / observar',
      'verbo',
      'He pointed out a mistake in the report.',
      'Ele apontou um erro no relatório.',
    ],
    [
      'reliable',
      'confiável',
      'adjetivo',
      'He is a reliable colleague.',
      'Ele é um colega confiável.',
    ],
    [
      'unlikely',
      'improvável',
      'adjetivo',
      "It's unlikely that it will rain.",
      'É improvável que chova.',
    ],
    [
      'whereas',
      'ao passo que',
      'conjunção',
      'He likes tea, whereas I prefer coffee.',
      'Ele gosta de chá, ao passo que eu prefiro café.',
    ],
    [
      'eventually',
      'por fim / no final das contas',
      'advérbio',
      'Eventually, they agreed.',
      'No final das contas, eles concordaram.',
    ],
    [
      'struggle',
      'ter dificuldade / lutar',
      'verbo',
      'I struggled with the grammar at first.',
      'Tive dificuldade com a gramática no começo.',
    ],
    [
      'income',
      'renda',
      'substantivo',
      'Their main income comes from tourism.',
      'A principal renda deles vem do turismo.',
    ],
  ],
  B2: [
    [
      'insight',
      'percepção / discernimento',
      'substantivo',
      'Her essay offers real insight into the problem.',
      'O ensaio dela traz uma percepção real do problema.',
    ],
    [
      'drawback',
      'desvantagem',
      'substantivo',
      'The main drawback is the cost.',
      'A principal desvantagem é o custo.',
    ],
    [
      'bias',
      'viés / preconceito',
      'substantivo',
      'The study corrects for sampling bias.',
      'O estudo corrige o viés de amostragem.',
    ],
    [
      'acknowledge',
      'reconhecer / admitir',
      'verbo',
      'He acknowledged that he was wrong.',
      'Ele reconheceu que estava errado.',
    ],
    [
      'undermine',
      'minar / enfraquecer',
      'verbo',
      'The delays undermined public trust.',
      'Os atrasos minaram a confiança do público.',
    ],
    [
      'overlook',
      'deixar passar / ignorar',
      'verbo',
      'We overlooked one important detail.',
      'Deixamos passar um detalhe importante.',
    ],
    [
      'thorough',
      'minucioso',
      'adjetivo',
      'She gave a thorough explanation.',
      'Ela deu uma explicação minuciosa.',
    ],
    [
      'compelling',
      'convincente',
      'adjetivo',
      'That is a compelling argument.',
      'Esse é um argumento convincente.',
    ],
    [
      'nevertheless',
      'no entanto',
      'advérbio',
      'It rained; nevertheless, we went out.',
      'Choveu; no entanto, saímos.',
    ],
    [
      'albeit',
      'embora / ainda que',
      'conjunção',
      'He agreed, albeit reluctantly.',
      'Ele concordou, embora a contragosto.',
    ],
    [
      'leverage',
      'alavancar / aproveitar',
      'verbo',
      'They leveraged their local knowledge.',
      'Eles aproveitaram o conhecimento local.',
    ],
    [
      'scope',
      'escopo / alcance',
      'substantivo',
      'That is beyond the scope of this report.',
      'Isso está fora do escopo deste relatório.',
    ],
  ],
  C1: [
    [
      'caveat',
      'ressalva',
      'substantivo',
      'One caveat: the data is three years old.',
      'Uma ressalva: os dados têm três anos.',
    ],
    [
      'discrepancy',
      'discrepância',
      'substantivo',
      'There is a discrepancy between the two figures.',
      'Há uma discrepância entre os dois números.',
    ],
    [
      'premise',
      'premissa',
      'substantivo',
      'The argument rests on a false premise.',
      'O argumento se apoia numa premissa falsa.',
    ],
    [
      'substantiate',
      'comprovar / fundamentar',
      'verbo',
      'He could not substantiate the claim.',
      'Ele não conseguiu comprovar a alegação.',
    ],
    [
      'reconcile',
      'conciliar',
      'verbo',
      'It is hard to reconcile the two accounts.',
      'É difícil conciliar os dois relatos.',
    ],
    [
      'preclude',
      'impedir / inviabilizar',
      'verbo',
      'Budget cuts preclude further testing.',
      'Cortes no orçamento inviabilizam mais testes.',
    ],
    [
      'tenuous',
      'tênue / frágil',
      'adjetivo',
      'The connection is tenuous at best.',
      'A ligação é tênue, na melhor das hipóteses.',
    ],
    [
      'pervasive',
      'generalizado / disseminado',
      'adjetivo',
      'The problem is pervasive across the sector.',
      'O problema é generalizado no setor.',
    ],
    [
      'notwithstanding',
      'não obstante',
      'preposição',
      'Notwithstanding the delay, the launch succeeded.',
      'Não obstante o atraso, o lançamento deu certo.',
    ],
    [
      'insofar as',
      'na medida em que',
      'conjunção',
      'It matters insofar as it changes the outcome.',
      'Importa na medida em que muda o resultado.',
    ],
    [
      'mitigate',
      'mitigar / atenuar',
      'verbo',
      'These measures mitigate the risk.',
      'Essas medidas mitigam o risco.',
    ],
    [
      'prevail',
      'prevalecer',
      'verbo',
      'Common sense eventually prevailed.',
      'O bom senso acabou prevalecendo.',
    ],
  ],
  C2: [
    [
      'nuance',
      'nuance / sutileza',
      'substantivo',
      'The translation loses much of the nuance.',
      'A tradução perde boa parte da nuance.',
    ],
    [
      'euphemism',
      'eufemismo',
      'substantivo',
      '"Let go" is a euphemism for "fired".',
      '"Dispensado" é um eufemismo para "demitido".',
    ],
    [
      'understatement',
      'atenuação irônica',
      'substantivo',
      'Calling it difficult is an understatement.',
      'Chamar isso de difícil é pouco.',
    ],
    [
      'belie',
      'desmentir / contradizer',
      'verbo',
      'His calm tone belied his anger.',
      'O tom calmo dele desmentia sua raiva.',
    ],
    [
      'equivocate',
      'usar de evasivas',
      'verbo',
      'The minister equivocated for twenty minutes.',
      'O ministro usou de evasivas por vinte minutos.',
    ],
    [
      'gloss over',
      'passar por cima de',
      'verbo',
      'The report glosses over the failures.',
      'O relatório passa por cima das falhas.',
    ],
    [
      'inexorable',
      'inexorável',
      'adjetivo',
      'The decline was slow but inexorable.',
      'O declínio foi lento, mas inexorável.',
    ],
    [
      'ostensibly',
      'aparentemente / sob o pretexto de',
      'advérbio',
      'He resigned, ostensibly for health reasons.',
      'Ele renunciou, aparentemente por motivos de saúde.',
    ],
    [
      'tantamount',
      'equivalente a',
      'adjetivo',
      'Silence here is tantamount to consent.',
      'Silêncio aqui equivale a consentimento.',
    ],
    [
      'quintessential',
      'por excelência',
      'adjetivo',
      'She is the quintessential New Yorker.',
      'Ela é a nova-iorquina por excelência.',
    ],
    [
      'inasmuch as',
      'visto que',
      'conjunção',
      'Inasmuch as we agree, let us proceed.',
      'Visto que concordamos, sigamos.',
    ],
    [
      'hitherto',
      'até aqui / até então',
      'advérbio',
      'A hitherto unknown species.',
      'Uma espécie até então desconhecida.',
    ],
  ],
};

/* ================================================================== *
 * Espanhol
 * ================================================================== */

const ES: LevelMap = {
  A2: [
    [
      'el barrio',
      'o bairro',
      'substantivo',
      'Vivo en este barrio desde niño.',
      'Moro neste bairro desde criança.',
    ],
    [
      'la cita',
      'a consulta / o encontro marcado',
      'substantivo',
      'Tengo cita con el médico.',
      'Tenho consulta com o médico.',
    ],
    [
      'el recibo',
      'o recibo',
      'substantivo',
      'Guarda el recibo, por favor.',
      'Guarde o recibo, por favor.',
    ],
    [
      'prestar',
      'emprestar (dar)',
      'verbo',
      '¿Me prestas tu cargador?',
      'Você me empresta seu carregador?',
    ],
    [
      'pedir prestado',
      'pegar emprestado',
      'verbo',
      'Le pedí prestado el coche.',
      'Peguei o carro dele emprestado.',
    ],
    [
      'permitirse',
      'ter condições de',
      'verbo',
      'No puedo permitirme ese viaje.',
      'Não tenho condições de fazer essa viagem.',
    ],
    [
      'lleno',
      'cheio / lotado',
      'adjetivo',
      'El metro va lleno por la mañana.',
      'O metrô vai lotado de manhã.',
    ],
    [
      'bastante',
      'bastante / até que',
      'advérbio',
      'La película fue bastante buena.',
      'O filme foi até que bom.',
    ],
    ['ya', 'já', 'advérbio', 'Ya se ha ido.', 'Ele já foi embora.'],
    [
      'en cambio',
      'em compensação / já',
      'locução',
      'Él llegó tarde; en cambio, ella llegó puntual.',
      'Ele chegou tarde; já ela chegou pontual.',
    ],
    ['quejarse', 'reclamar', 'verbo', 'Se quejó del ruido.', 'Ele reclamou do barulho.'],
    [
      'arreglar',
      'consertar',
      'verbo',
      '¿Puedes arreglar la ducha?',
      'Você consegue consertar o chuveiro?',
    ],
  ],
  B1: [
    [
      'el logro',
      'a conquista',
      'substantivo',
      'Terminar la carrera fue un gran logro.',
      'Terminar a faculdade foi uma grande conquista.',
    ],
    [
      'el plazo',
      'o prazo',
      'substantivo',
      'El plazo vence el viernes.',
      'O prazo vence na sexta.',
    ],
    [
      'el asunto',
      'o assunto / a questão',
      'substantivo',
      'Tenemos que hablar de ese asunto.',
      'Temos que falar desse assunto.',
    ],
    [
      'suponer',
      'supor / presumir',
      'verbo',
      'Supuse que ya lo sabías.',
      'Supus que você já soubesse.',
    ],
    [
      'lograr',
      'conseguir',
      'verbo',
      'Logró terminar a tiempo.',
      'Ela conseguiu terminar a tempo.',
    ],
    [
      'señalar',
      'apontar / assinalar',
      'verbo',
      'Señaló un error en el informe.',
      'Ele apontou um erro no relatório.',
    ],
    ['fiable', 'confiável', 'adjetivo', 'Es un compañero fiable.', 'É um colega confiável.'],
    [
      'poco probable',
      'pouco provável',
      'adjetivo',
      'Es poco probable que llueva.',
      'É pouco provável que chova.',
    ],
    [
      'mientras que',
      'ao passo que',
      'conjunção',
      'A él le gusta el té, mientras que yo prefiero el café.',
      'Ele gosta de chá, ao passo que eu prefiro café.',
    ],
    [
      'al final',
      'no fim das contas',
      'locução',
      'Al final aceptaron.',
      'No fim das contas, aceitaram.',
    ],
    [
      'costar trabajo',
      'custar / ter dificuldade',
      'verbo',
      'Me costó trabajo entender la gramática.',
      'Tive dificuldade em entender a gramática.',
    ],
    [
      'los ingresos',
      'a renda',
      'substantivo',
      'Sus ingresos vienen del turismo.',
      'A renda deles vem do turismo.',
    ],
  ],
  B2: [
    [
      'el enfoque',
      'a abordagem / o enfoque',
      'substantivo',
      'Propuso un enfoque distinto.',
      'Ele propôs uma abordagem diferente.',
    ],
    [
      'el inconveniente',
      'a desvantagem / o inconveniente',
      'substantivo',
      'El principal inconveniente es el precio.',
      'A principal desvantagem é o preço.',
    ],
    [
      'el sesgo',
      'o viés',
      'substantivo',
      'El estudio corrige el sesgo de la muestra.',
      'O estudo corrige o viés da amostra.',
    ],
    [
      'reconocer',
      'reconhecer / admitir',
      'verbo',
      'Reconoció que se había equivocado.',
      'Ele reconheceu que tinha errado.',
    ],
    [
      'socavar',
      'minar',
      'verbo',
      'Los retrasos socavaron la confianza.',
      'Os atrasos minaram a confiança.',
    ],
    [
      'pasar por alto',
      'deixar passar',
      'verbo',
      'Pasamos por alto un detalle importante.',
      'Deixamos passar um detalhe importante.',
    ],
    [
      'exhaustivo',
      'minucioso / exaustivo',
      'adjetivo',
      'Hizo un análisis exhaustivo.',
      'Ele fez uma análise minuciosa.',
    ],
    [
      'contundente',
      'contundente / convincente',
      'adjetivo',
      'Es un argumento contundente.',
      'É um argumento contundente.',
    ],
    [
      'sin embargo',
      'no entanto',
      'locução',
      'Llovió; sin embargo, salimos.',
      'Choveu; no entanto, saímos.',
    ],
    [
      'aunque',
      'embora',
      'conjunção',
      'Aceptó, aunque de mala gana.',
      'Ele aceitou, embora a contragosto.',
    ],
    [
      'aprovechar',
      'aproveitar',
      'verbo',
      'Aprovecharon su conocimiento local.',
      'Eles aproveitaram seu conhecimento local.',
    ],
    [
      'el ámbito',
      'o âmbito',
      'substantivo',
      'Eso queda fuera del ámbito del informe.',
      'Isso fica fora do âmbito do relatório.',
    ],
  ],
  C1: [
    [
      'la salvedad',
      'a ressalva',
      'substantivo',
      'Con la salvedad de que los datos son antiguos.',
      'Com a ressalva de que os dados são antigos.',
    ],
    [
      'la discrepancia',
      'a discrepância',
      'substantivo',
      'Hay una discrepancia entre las cifras.',
      'Há uma discrepância entre os números.',
    ],
    [
      'la premisa',
      'a premissa',
      'substantivo',
      'El argumento parte de una premisa falsa.',
      'O argumento parte de uma premissa falsa.',
    ],
    [
      'fundamentar',
      'fundamentar',
      'verbo',
      'No pudo fundamentar la acusación.',
      'Ele não conseguiu fundamentar a acusação.',
    ],
    [
      'conciliar',
      'conciliar',
      'verbo',
      'Cuesta conciliar ambas versiones.',
      'É difícil conciliar as duas versões.',
    ],
    [
      'impedir',
      'impedir',
      'verbo',
      'Los recortes impiden nuevas pruebas.',
      'Os cortes impedem novos testes.',
    ],
    ['endeble', 'frágil / tênue', 'adjetivo', 'La relación es endeble.', 'A relação é frágil.'],
    [
      'generalizado',
      'generalizado',
      'adjetivo',
      'El problema está generalizado en el sector.',
      'O problema está generalizado no setor.',
    ],
    [
      'no obstante',
      'não obstante',
      'locução',
      'No obstante el retraso, salió bien.',
      'Não obstante o atraso, deu certo.',
    ],
    [
      'en la medida en que',
      'na medida em que',
      'locução',
      'Importa en la medida en que cambia el resultado.',
      'Importa na medida em que muda o resultado.',
    ],
    [
      'mitigar',
      'mitigar',
      'verbo',
      'Estas medidas mitigan el riesgo.',
      'Essas medidas mitigam o risco.',
    ],
    [
      'imperar',
      'imperar / prevalecer',
      'verbo',
      'Al final imperó el sentido común.',
      'No fim, imperou o bom senso.',
    ],
  ],
  C2: [
    [
      'el matiz',
      'a nuance',
      'substantivo',
      'La traducción pierde el matiz.',
      'A tradução perde a nuance.',
    ],
    [
      'el eufemismo',
      'o eufemismo',
      'substantivo',
      '"Prescindir de alguien" es un eufemismo.',
      '"Prescindir de alguém" é um eufemismo.',
    ],
    [
      'la atenuación',
      'a atenuação',
      'substantivo',
      'Decir que fue difícil es una atenuación.',
      'Dizer que foi difícil é uma atenuação.',
    ],
    [
      'desmentir',
      'desmentir',
      'verbo',
      'Su tono calmado desmentía su enfado.',
      'O tom calmo dele desmentia sua irritação.',
    ],
    [
      'andarse por las ramas',
      'enrolar / usar evasivas',
      'locução',
      'Dejó de andarse por las ramas.',
      'Ele parou de enrolar.',
    ],
    [
      'soslayar',
      'contornar / driblar',
      'verbo',
      'El informe soslaya los fracasos.',
      'O relatório contorna os fracassos.',
    ],
    [
      'inexorable',
      'inexorável',
      'adjetivo',
      'El declive fue lento pero inexorable.',
      'O declínio foi lento, mas inexorável.',
    ],
    [
      'presuntamente',
      'supostamente',
      'advérbio',
      'Dimitió, presuntamente por salud.',
      'Ele renunciou, supostamente por saúde.',
    ],
    [
      'equivalente a',
      'equivalente a',
      'adjetivo',
      'Callar aquí equivale a consentir.',
      'Calar aqui equivale a consentir.',
    ],
    [
      'por antonomasia',
      'por excelência',
      'locução',
      'Es el madrileño por antonomasia.',
      'Ele é o madrilenho por excelência.',
    ],
    [
      'puesto que',
      'visto que',
      'conjunção',
      'Puesto que estamos de acuerdo, sigamos.',
      'Visto que concordamos, sigamos.',
    ],
    [
      'hasta entonces',
      'até então',
      'locução',
      'Una especie hasta entonces desconocida.',
      'Uma espécie até então desconhecida.',
    ],
  ],
};

/* ================================================================== *
 * Francês
 * ================================================================== */

const FR: LevelMap = {
  A2: [
    [
      'le quartier',
      'o bairro',
      'substantivo',
      "J'ai grandi dans ce quartier.",
      'Cresci neste bairro.',
    ],
    [
      'le rendez-vous',
      'a consulta / o compromisso',
      'substantivo',
      "J'ai rendez-vous chez le médecin.",
      'Tenho consulta com o médico.',
    ],
    [
      'le reçu',
      'o recibo',
      'substantivo',
      'Gardez le reçu, si vous voulez échanger.',
      'Guarde o recibo, caso queira trocar.',
    ],
    [
      'prêter',
      'emprestar (dar)',
      'verbo',
      'Tu peux me prêter ton chargeur ?',
      'Você me empresta seu carregador?',
    ],
    [
      'emprunter',
      'pegar emprestado',
      'verbo',
      "J'ai emprunté sa voiture.",
      'Peguei o carro dele emprestado.',
    ],
    [
      'avoir les moyens',
      'ter condições de',
      'locução',
      "Je n'ai pas les moyens pour ce voyage.",
      'Não tenho condições para essa viagem.',
    ],
    [
      'bondé',
      'lotado',
      'adjetivo',
      'Le métro est bondé le matin.',
      'O metrô fica lotado de manhã.',
    ],
    [
      'assez',
      'bastante / até que',
      'advérbio',
      'Le film était assez bon.',
      'O filme foi até que bom.',
    ],
    ['déjà', 'já', 'advérbio', 'Elle est déjà partie.', 'Ela já foi embora.'],
    [
      'plutôt',
      'em vez disso / antes',
      'advérbio',
      'Prenons plutôt le bus.',
      'Vamos pegar antes o ônibus.',
    ],
    [
      'se plaindre',
      'reclamar',
      'verbo',
      "Il s'est plaint du bruit.",
      'Ele reclamou do barulho.',
    ],
    [
      'réparer',
      'consertar',
      'verbo',
      'Tu peux réparer la douche ?',
      'Você consegue consertar o chuveiro?',
    ],
  ],
  B1: [
    [
      'la réussite',
      'a conquista / o êxito',
      'substantivo',
      'Finir ce cours a été une vraie réussite.',
      'Terminar esse curso foi um êxito de verdade.',
    ],
    ['le délai', 'o prazo', 'substantivo', 'Le délai expire vendredi.', 'O prazo vence sexta.'],
    [
      'la question',
      'a questão',
      'substantivo',
      'Il faut aborder cette question.',
      'Precisamos abordar essa questão.',
    ],
    [
      'supposer',
      'supor',
      'verbo',
      'Je supposais que tu étais au courant.',
      'Eu supunha que você soubesse.',
    ],
    [
      'parvenir à',
      'conseguir',
      'verbo',
      'Elle est parvenue à finir à temps.',
      'Ela conseguiu terminar a tempo.',
    ],
    [
      'signaler',
      'apontar / sinalizar',
      'verbo',
      'Il a signalé une erreur.',
      'Ele apontou um erro.',
    ],
    ['fiable', 'confiável', 'adjetivo', "C'est un collègue fiable.", 'É um colega confiável.'],
    [
      'peu probable',
      'pouco provável',
      'adjetivo',
      "Il est peu probable qu'il pleuve.",
      'É pouco provável que chova.',
    ],
    [
      'tandis que',
      'ao passo que',
      'conjunção',
      'Il aime le thé, tandis que je préfère le café.',
      'Ele gosta de chá, ao passo que eu prefiro café.',
    ],
    [
      'finalement',
      'no fim das contas',
      'advérbio',
      'Finalement, ils ont accepté.',
      'No fim das contas, eles aceitaram.',
    ],
    [
      'avoir du mal à',
      'ter dificuldade em',
      'locução',
      "J'ai eu du mal à comprendre la grammaire.",
      'Tive dificuldade em entender a gramática.',
    ],
    [
      'les revenus',
      'a renda',
      'substantivo',
      'Leurs revenus viennent du tourisme.',
      'A renda deles vem do turismo.',
    ],
  ],
  B2: [
    [
      "l'approche",
      'a abordagem',
      'substantivo',
      'Il a proposé une autre approche.',
      'Ele propôs outra abordagem.',
    ],
    [
      "l'inconvénient",
      'a desvantagem',
      'substantivo',
      "Le principal inconvénient, c'est le prix.",
      'A principal desvantagem é o preço.',
    ],
    [
      'le biais',
      'o viés',
      'substantivo',
      "L'étude corrige le biais d'échantillonnage.",
      'O estudo corrige o viés de amostragem.',
    ],
    [
      'reconnaître',
      'reconhecer / admitir',
      'verbo',
      "Il a reconnu qu'il avait tort.",
      'Ele reconheceu que estava errado.',
    ],
    [
      'saper',
      'minar',
      'verbo',
      'Les retards ont sapé la confiance.',
      'Os atrasos minaram a confiança.',
    ],
    [
      'négliger',
      'negligenciar / deixar passar',
      'verbo',
      'Nous avons négligé un détail important.',
      'Negligenciamos um detalhe importante.',
    ],
    [
      'approfondi',
      'minucioso / aprofundado',
      'adjetivo',
      'Elle a fait une analyse approfondie.',
      'Ela fez uma análise aprofundada.',
    ],
    [
      'convaincant',
      'convincente',
      'adjetivo',
      "C'est un argument convaincant.",
      'É um argumento convincente.',
    ],
    [
      'néanmoins',
      'no entanto',
      'advérbio',
      'Il pleuvait ; néanmoins, nous sommes sortis.',
      'Chovia; no entanto, saímos.',
    ],
    [
      'bien que',
      'embora',
      'conjunção',
      "Il a accepté, bien qu'à contrecœur.",
      'Ele aceitou, embora a contragosto.',
    ],
    [
      'tirer parti de',
      'tirar proveito de',
      'locução',
      'Ils ont tiré parti de leur expérience.',
      'Eles tiraram proveito da experiência deles.',
    ],
    [
      'le cadre',
      'o âmbito / o quadro',
      'substantivo',
      'Cela dépasse le cadre du rapport.',
      'Isso ultrapassa o âmbito do relatório.',
    ],
  ],
  C1: [
    [
      'la réserve',
      'a ressalva',
      'substantivo',
      'Avec une réserve : les données datent.',
      'Com uma ressalva: os dados são antigos.',
    ],
    [
      "l'écart",
      'a discrepância',
      'substantivo',
      'Il y a un écart entre les deux chiffres.',
      'Há uma discrepância entre os dois números.',
    ],
    [
      'la prémisse',
      'a premissa',
      'substantivo',
      "L'argument repose sur une prémisse fausse.",
      'O argumento se apoia numa premissa falsa.',
    ],
    [
      'étayer',
      'fundamentar',
      'verbo',
      "Il n'a pas pu étayer ses accusations.",
      'Ele não conseguiu fundamentar suas acusações.',
    ],
    [
      'concilier',
      'conciliar',
      'verbo',
      'Difficile de concilier les deux versions.',
      'Difícil conciliar as duas versões.',
    ],
    [
      'empêcher',
      'impedir',
      'verbo',
      'Les coupes empêchent de nouveaux essais.',
      'Os cortes impedem novos testes.',
    ],
    ['ténu', 'tênue', 'adjetivo', 'Le lien est ténu.', 'A ligação é tênue.'],
    [
      'généralisé',
      'generalizado',
      'adjetivo',
      'Le problème est généralisé.',
      'O problema é generalizado.',
    ],
    [
      'nonobstant',
      'não obstante',
      'preposição',
      'Nonobstant le retard, le lancement a réussi.',
      'Não obstante o atraso, o lançamento deu certo.',
    ],
    [
      'dans la mesure où',
      'na medida em que',
      'locução',
      'Cela compte dans la mesure où ça change tout.',
      'Isso conta na medida em que muda tudo.',
    ],
    [
      'atténuer',
      'mitigar / atenuar',
      'verbo',
      'Ces mesures atténuent le risque.',
      'Essas medidas atenuam o risco.',
    ],
    [
      "l'emporter",
      'prevalecer',
      'verbo',
      'Le bon sens a fini par l’emporter.',
      'O bom senso acabou prevalecendo.',
    ],
  ],
  C2: [
    [
      'la nuance',
      'a nuance',
      'substantivo',
      'La traduction perd la nuance.',
      'A tradução perde a nuance.',
    ],
    [
      "l'euphémisme",
      'o eufemismo',
      'substantivo',
      '« Se séparer de quelqu’un » est un euphémisme.',
      '"Dispensar alguém" é um eufemismo.',
    ],
    [
      'la litote',
      'a litote',
      'substantivo',
      '« Ce n’est pas mauvais » est une litote.',
      '"Não é ruim" é uma litote.',
    ],
    [
      'démentir',
      'desmentir',
      'verbo',
      'Son calme démentait sa colère.',
      'A calma dele desmentia sua raiva.',
    ],
    [
      'tergiverser',
      'usar de evasivas',
      'verbo',
      'Le ministre a tergiversé longtemps.',
      'O ministro usou de evasivas por muito tempo.',
    ],
    [
      'escamoter',
      'escamotear',
      'verbo',
      'Le rapport escamote les échecs.',
      'O relatório escamoteia os fracassos.',
    ],
    [
      'inexorable',
      'inexorável',
      'adjetivo',
      'Un déclin lent mais inexorable.',
      'Um declínio lento, mas inexorável.',
    ],
    [
      'ostensiblement',
      'ostensivamente',
      'advérbio',
      'Il a démissionné, ostensiblement pour raisons de santé.',
      'Ele renunciou, ostensivamente por motivos de saúde.',
    ],
    [
      'équivalant à',
      'equivalente a',
      'adjetivo',
      'Se taire ici équivaut à consentir.',
      'Calar aqui equivale a consentir.',
    ],
    [
      'par excellence',
      'por excelência',
      'locução',
      "C'est le Parisien par excellence.",
      'Ele é o parisiense por excelência.',
    ],
    [
      'dès lors que',
      'visto que / desde que',
      'conjunção',
      'Dès lors que nous sommes d’accord, avançons.',
      'Visto que concordamos, sigamos.',
    ],
    [
      'jusqu’alors',
      'até então',
      'advérbio',
      'Une espèce jusqu’alors inconnue.',
      'Uma espécie até então desconhecida.',
    ],
  ],
};

/* ================================================================== *
 * Italiano
 * ================================================================== */

const IT: LevelMap = {
  A2: [
    [
      'il quartiere',
      'o bairro',
      'substantivo',
      'Sono cresciuto in questo quartiere.',
      'Cresci neste bairro.',
    ],
    [
      "l'appuntamento",
      'o compromisso / a consulta',
      'substantivo',
      'Ho un appuntamento dal medico.',
      'Tenho consulta com o médico.',
    ],
    [
      'lo scontrino',
      'o recibo / o cupom',
      'substantivo',
      'Conserva lo scontrino.',
      'Guarde o cupom.',
    ],
    [
      'prestare',
      'emprestar (dar)',
      'verbo',
      'Mi presti il caricabatterie?',
      'Você me empresta o carregador?',
    ],
    [
      'prendere in prestito',
      'pegar emprestado',
      'verbo',
      'Ho preso in prestito la sua auto.',
      'Peguei o carro dele emprestado.',
    ],
    [
      'permettersi',
      'ter condições de',
      'verbo',
      'Non posso permettermi quel viaggio.',
      'Não tenho condições para essa viagem.',
    ],
    [
      'affollato',
      'lotado',
      'adjetivo',
      'La metro è affollata la mattina.',
      'O metrô fica lotado de manhã.',
    ],
    [
      'abbastanza',
      'bastante / até que',
      'advérbio',
      'Il film era abbastanza bello.',
      'O filme foi até que bom.',
    ],
    ['già', 'já', 'advérbio', 'È già andata via.', 'Ela já foi embora.'],
    [
      'invece',
      'em vez disso',
      'advérbio',
      'Prendiamo invece il bus.',
      'Vamos pegar o ônibus em vez disso.',
    ],
    [
      'lamentarsi',
      'reclamar',
      'verbo',
      'Si è lamentato del rumore.',
      'Ele reclamou do barulho.',
    ],
    [
      'riparare',
      'consertar',
      'verbo',
      'Puoi riparare la doccia?',
      'Você consegue consertar o chuveiro?',
    ],
  ],
  B1: [
    [
      'il traguardo',
      'a conquista / a meta atingida',
      'substantivo',
      'Finire il corso è stato un traguardo.',
      'Terminar o curso foi uma conquista.',
    ],
    ['la scadenza', 'o prazo', 'substantivo', 'La scadenza è venerdì.', 'O prazo é sexta.'],
    [
      'la questione',
      'a questão',
      'substantivo',
      'Dobbiamo affrontare questa questione.',
      'Precisamos enfrentar essa questão.',
    ],
    [
      'supporre',
      'supor',
      'verbo',
      'Supponevo che lo sapessi.',
      'Eu supunha que você soubesse.',
    ],
    [
      'riuscire a',
      'conseguir',
      'verbo',
      'È riuscita a finire in tempo.',
      'Ela conseguiu terminar a tempo.',
    ],
    [
      'segnalare',
      'apontar / sinalizar',
      'verbo',
      'Ha segnalato un errore.',
      'Ele apontou um erro.',
    ],
    [
      'affidabile',
      'confiável',
      'adjetivo',
      'È un collega affidabile.',
      'É um colega confiável.',
    ],
    [
      'poco probabile',
      'pouco provável',
      'adjetivo',
      'È poco probabile che piova.',
      'É pouco provável que chova.',
    ],
    [
      'mentre',
      'ao passo que / enquanto',
      'conjunção',
      'Lui ama il tè, mentre io preferisco il caffè.',
      'Ele adora chá, ao passo que eu prefiro café.',
    ],
    [
      'alla fine',
      'no fim das contas',
      'locução',
      'Alla fine hanno accettato.',
      'No fim das contas, aceitaram.',
    ],
    [
      'faticare a',
      'ter dificuldade em',
      'verbo',
      'Ho faticato a capire la grammatica.',
      'Tive dificuldade em entender a gramática.',
    ],
    [
      'il reddito',
      'a renda',
      'substantivo',
      'Il loro reddito viene dal turismo.',
      'A renda deles vem do turismo.',
    ],
  ],
  B2: [
    [
      "l'approccio",
      'a abordagem',
      'substantivo',
      'Ha proposto un approccio diverso.',
      'Ele propôs uma abordagem diferente.',
    ],
    [
      'lo svantaggio',
      'a desvantagem',
      'substantivo',
      'Lo svantaggio principale è il costo.',
      'A principal desvantagem é o custo.',
    ],
    [
      'il pregiudizio',
      'o viés / o preconceito',
      'substantivo',
      'Lo studio corregge il pregiudizio del campione.',
      'O estudo corrige o viés da amostra.',
    ],
    [
      'riconoscere',
      'reconhecer / admitir',
      'verbo',
      'Ha riconosciuto di aver sbagliato.',
      'Ele reconheceu que errou.',
    ],
    [
      'minare',
      'minar',
      'verbo',
      'I ritardi hanno minato la fiducia.',
      'Os atrasos minaram a confiança.',
    ],
    [
      'trascurare',
      'negligenciar',
      'verbo',
      'Abbiamo trascurato un dettaglio.',
      'Negligenciamos um detalhe.',
    ],
    [
      'approfondito',
      'aprofundado / minucioso',
      'adjetivo',
      'Ha fatto un’analisi approfondita.',
      'Ela fez uma análise aprofundada.',
    ],
    [
      'convincente',
      'convincente',
      'adjetivo',
      'È un argomento convincente.',
      'É um argumento convincente.',
    ],
    [
      'tuttavia',
      'no entanto',
      'advérbio',
      'Pioveva; tuttavia siamo usciti.',
      'Chovia; no entanto, saímos.',
    ],
    [
      'sebbene',
      'embora',
      'conjunção',
      'Ha accettato, sebbene a malincuore.',
      'Ele aceitou, embora a contragosto.',
    ],
    [
      'sfruttare',
      'aproveitar / explorar',
      'verbo',
      'Hanno sfruttato la conoscenza locale.',
      'Eles aproveitaram o conhecimento local.',
    ],
    [
      "l'ambito",
      'o âmbito',
      'substantivo',
      'Va oltre l’ambito del rapporto.',
      'Vai além do âmbito do relatório.',
    ],
  ],
  C1: [
    [
      'la riserva',
      'a ressalva',
      'substantivo',
      'Con una riserva: i dati sono vecchi.',
      'Com uma ressalva: os dados são antigos.',
    ],
    [
      'la discrepanza',
      'a discrepância',
      'substantivo',
      'C’è una discrepanza tra le due cifre.',
      'Há uma discrepância entre os dois números.',
    ],
    [
      'la premessa',
      'a premissa',
      'substantivo',
      'L’argomento parte da una premessa falsa.',
      'O argumento parte de uma premissa falsa.',
    ],
    [
      'comprovare',
      'comprovar',
      'verbo',
      'Non ha potuto comprovare l’accusa.',
      'Ele não conseguiu comprovar a acusação.',
    ],
    [
      'conciliare',
      'conciliar',
      'verbo',
      'È difficile conciliare le due versioni.',
      'É difícil conciliar as duas versões.',
    ],
    [
      'precludere',
      'inviabilizar',
      'verbo',
      'I tagli precludono nuovi test.',
      'Os cortes inviabilizam novos testes.',
    ],
    ['labile', 'tênue / frágil', 'adjetivo', 'Il legame è labile.', 'A ligação é tênue.'],
    [
      'diffuso',
      'generalizado / difundido',
      'adjetivo',
      'Il problema è diffuso nel settore.',
      'O problema é generalizado no setor.',
    ],
    [
      'nonostante',
      'não obstante',
      'preposição',
      'Nonostante il ritardo, è andata bene.',
      'Não obstante o atraso, deu certo.',
    ],
    [
      'nella misura in cui',
      'na medida em que',
      'locução',
      'Conta nella misura in cui cambia il risultato.',
      'Conta na medida em que muda o resultado.',
    ],
    [
      'mitigare',
      'mitigar',
      'verbo',
      'Queste misure mitigano il rischio.',
      'Essas medidas mitigam o risco.',
    ],
    [
      'prevalere',
      'prevalecer',
      'verbo',
      'Alla fine è prevalso il buon senso.',
      'No fim, prevaleceu o bom senso.',
    ],
  ],
  C2: [
    [
      'la sfumatura',
      'a nuance',
      'substantivo',
      'La traduzione perde la sfumatura.',
      'A tradução perde a nuance.',
    ],
    [
      "l'eufemismo",
      'o eufemismo',
      'substantivo',
      '«Lasciare andare» è un eufemismo.',
      '"Dispensar" é um eufemismo.',
    ],
    [
      "l'attenuazione",
      'a atenuação',
      'substantivo',
      'Dire difficile è un’attenuazione.',
      'Dizer difícil é uma atenuação.',
    ],
    [
      'smentire',
      'desmentir',
      'verbo',
      'Il tono calmo smentiva la rabbia.',
      'O tom calmo desmentia a raiva.',
    ],
    [
      'tergiversare',
      'usar de evasivas',
      'verbo',
      'Il ministro ha tergiversato a lungo.',
      'O ministro usou de evasivas por muito tempo.',
    ],
    [
      'sorvolare su',
      'passar por cima de',
      'verbo',
      'Il rapporto sorvola sui fallimenti.',
      'O relatório passa por cima dos fracassos.',
    ],
    [
      'inesorabile',
      'inexorável',
      'adjetivo',
      'Un declino lento ma inesorabile.',
      'Um declínio lento, mas inexorável.',
    ],
    [
      'apparentemente',
      'aparentemente',
      'advérbio',
      'Si è dimesso, apparentemente per salute.',
      'Ele renunciou, aparentemente por saúde.',
    ],
    [
      'equivalente a',
      'equivalente a',
      'adjetivo',
      'Tacere qui equivale ad acconsentire.',
      'Calar aqui equivale a consentir.',
    ],
    [
      'per antonomasia',
      'por excelência',
      'locução',
      'È il romano per antonomasia.',
      'Ele é o romano por excelência.',
    ],
    [
      'dato che',
      'visto que',
      'conjunção',
      'Dato che siamo d’accordo, procediamo.',
      'Visto que concordamos, sigamos.',
    ],
    [
      'fino ad allora',
      'até então',
      'locução',
      'Una specie fino ad allora sconosciuta.',
      'Uma espécie até então desconhecida.',
    ],
  ],
};

/* ================================================================== *
 * Alemão
 * ================================================================== */

const DE: LevelMap = {
  A2: [
    [
      'das Viertel',
      'o bairro',
      'substantivo',
      'Ich bin in diesem Viertel aufgewachsen.',
      'Cresci neste bairro.',
    ],
    [
      'der Termin',
      'o compromisso / a consulta',
      'substantivo',
      'Ich habe einen Termin beim Arzt.',
      'Tenho consulta com o médico.',
    ],
    [
      'die Quittung',
      'o recibo',
      'substantivo',
      'Heben Sie die Quittung auf.',
      'Guarde o recibo.',
    ],
    [
      'leihen',
      'emprestar (dar)',
      'verbo',
      'Leihst du mir dein Ladegerät?',
      'Você me empresta seu carregador?',
    ],
    [
      'sich leihen',
      'pegar emprestado',
      'verbo',
      'Ich habe mir sein Auto geliehen.',
      'Peguei o carro dele emprestado.',
    ],
    [
      'sich leisten',
      'ter condições de',
      'verbo',
      'Ich kann mir die Reise nicht leisten.',
      'Não tenho condições para a viagem.',
    ],
    [
      'voll',
      'cheio / lotado',
      'adjetivo',
      'Die Bahn ist morgens voll.',
      'O trem fica lotado de manhã.',
    ],
    [
      'ziemlich',
      'bastante / até que',
      'advérbio',
      'Der Film war ziemlich gut.',
      'O filme foi até que bom.',
    ],
    ['schon', 'já', 'advérbio', 'Sie ist schon gegangen.', 'Ela já foi embora.'],
    [
      'stattdessen',
      'em vez disso',
      'advérbio',
      'Nehmen wir stattdessen den Bus.',
      'Vamos pegar o ônibus em vez disso.',
    ],
    [
      'sich beschweren',
      'reclamar',
      'verbo',
      'Er hat sich über den Lärm beschwert.',
      'Ele reclamou do barulho.',
    ],
    [
      'reparieren',
      'consertar',
      'verbo',
      'Kannst du die Dusche reparieren?',
      'Você consegue consertar o chuveiro?',
    ],
  ],
  B1: [
    [
      'die Leistung',
      'a conquista / o desempenho',
      'substantivo',
      'Den Kurs zu beenden war eine Leistung.',
      'Terminar o curso foi uma conquista.',
    ],
    [
      'die Frist',
      'o prazo',
      'substantivo',
      'Die Frist läuft am Freitag ab.',
      'O prazo vence na sexta.',
    ],
    [
      'die Angelegenheit',
      'o assunto / a questão',
      'substantivo',
      'Wir müssen diese Angelegenheit klären.',
      'Precisamos esclarecer essa questão.',
    ],
    [
      'annehmen',
      'supor / presumir',
      'verbo',
      'Ich nahm an, du wüsstest Bescheid.',
      'Presumi que você soubesse.',
    ],
    [
      'schaffen',
      'conseguir',
      'verbo',
      'Sie hat es rechtzeitig geschafft.',
      'Ela conseguiu a tempo.',
    ],
    [
      'hinweisen auf',
      'apontar para',
      'verbo',
      'Er wies auf einen Fehler hin.',
      'Ele apontou um erro.',
    ],
    [
      'zuverlässig',
      'confiável',
      'adjetivo',
      'Er ist ein zuverlässiger Kollege.',
      'Ele é um colega confiável.',
    ],
    [
      'unwahrscheinlich',
      'improvável',
      'adjetivo',
      'Es ist unwahrscheinlich, dass es regnet.',
      'É improvável que chova.',
    ],
    [
      'während',
      'ao passo que / enquanto',
      'conjunção',
      'Er mag Tee, während ich Kaffee bevorzuge.',
      'Ele gosta de chá, ao passo que eu prefiro café.',
    ],
    [
      'schließlich',
      'por fim',
      'advérbio',
      'Schließlich stimmten sie zu.',
      'Por fim, eles concordaram.',
    ],
    [
      'Schwierigkeiten haben',
      'ter dificuldade',
      'locução',
      'Ich hatte Schwierigkeiten mit der Grammatik.',
      'Tive dificuldade com a gramática.',
    ],
    [
      'das Einkommen',
      'a renda',
      'substantivo',
      'Ihr Einkommen stammt aus dem Tourismus.',
      'A renda deles vem do turismo.',
    ],
  ],
  B2: [
    [
      'der Ansatz',
      'a abordagem',
      'substantivo',
      'Er schlug einen anderen Ansatz vor.',
      'Ele propôs outra abordagem.',
    ],
    [
      'der Nachteil',
      'a desvantagem',
      'substantivo',
      'Der größte Nachteil sind die Kosten.',
      'A maior desvantagem são os custos.',
    ],
    [
      'die Verzerrung',
      'o viés / a distorção',
      'substantivo',
      'Die Studie korrigiert die Verzerrung.',
      'O estudo corrige o viés.',
    ],
    [
      'einräumen',
      'reconhecer / admitir',
      'verbo',
      'Er räumte ein, dass er falsch lag.',
      'Ele admitiu que estava errado.',
    ],
    [
      'untergraben',
      'minar',
      'verbo',
      'Die Verzögerungen untergruben das Vertrauen.',
      'Os atrasos minaram a confiança.',
    ],
    [
      'übersehen',
      'deixar passar',
      'verbo',
      'Wir haben ein wichtiges Detail übersehen.',
      'Deixamos passar um detalhe importante.',
    ],
    [
      'gründlich',
      'minucioso',
      'adjetivo',
      'Sie lieferte eine gründliche Analyse.',
      'Ela entregou uma análise minuciosa.',
    ],
    [
      'überzeugend',
      'convincente',
      'adjetivo',
      'Das ist ein überzeugendes Argument.',
      'Esse é um argumento convincente.',
    ],
    [
      'dennoch',
      'no entanto',
      'advérbio',
      'Es regnete; dennoch gingen wir raus.',
      'Choveu; no entanto, saímos.',
    ],
    [
      'obwohl',
      'embora',
      'conjunção',
      'Er stimmte zu, obwohl widerwillig.',
      'Ele concordou, embora a contragosto.',
    ],
    [
      'nutzen',
      'aproveitar',
      'verbo',
      'Sie nutzten ihre Ortskenntnis.',
      'Eles aproveitaram o conhecimento local.',
    ],
    [
      'der Rahmen',
      'o âmbito / o quadro',
      'substantivo',
      'Das sprengt den Rahmen des Berichts.',
      'Isso extrapola o âmbito do relatório.',
    ],
  ],
  C1: [
    [
      'der Vorbehalt',
      'a ressalva',
      'substantivo',
      'Mit einem Vorbehalt: die Daten sind alt.',
      'Com uma ressalva: os dados são antigos.',
    ],
    [
      'die Diskrepanz',
      'a discrepância',
      'substantivo',
      'Es gibt eine Diskrepanz zwischen den Zahlen.',
      'Há uma discrepância entre os números.',
    ],
    [
      'die Prämisse',
      'a premissa',
      'substantivo',
      'Das Argument beruht auf einer falschen Prämisse.',
      'O argumento se apoia numa premissa falsa.',
    ],
    [
      'belegen',
      'comprovar',
      'verbo',
      'Er konnte den Vorwurf nicht belegen.',
      'Ele não conseguiu comprovar a acusação.',
    ],
    [
      'in Einklang bringen',
      'conciliar',
      'locução',
      'Beide Darstellungen sind schwer in Einklang zu bringen.',
      'É difícil conciliar as duas versões.',
    ],
    [
      'ausschließen',
      'excluir / inviabilizar',
      'verbo',
      'Kürzungen schließen weitere Tests aus.',
      'Cortes inviabilizam mais testes.',
    ],
    [
      'dürftig',
      'tênue / escasso',
      'adjetivo',
      'Die Beweislage ist dürftig.',
      'As provas são escassas.',
    ],
    [
      'weitverbreitet',
      'generalizado',
      'adjetivo',
      'Das Problem ist weitverbreitet.',
      'O problema é generalizado.',
    ],
    [
      'ungeachtet',
      'não obstante',
      'preposição',
      'Ungeachtet der Verzögerung war es ein Erfolg.',
      'Não obstante o atraso, foi um sucesso.',
    ],
    [
      'insofern als',
      'na medida em que',
      'conjunção',
      'Es zählt insofern, als es das Ergebnis ändert.',
      'Conta na medida em que muda o resultado.',
    ],
    [
      'abmildern',
      'mitigar',
      'verbo',
      'Diese Maßnahmen mildern das Risiko ab.',
      'Essas medidas mitigam o risco.',
    ],
    [
      'sich durchsetzen',
      'prevalecer',
      'verbo',
      'Der gesunde Menschenverstand setzte sich durch.',
      'O bom senso prevaleceu.',
    ],
  ],
  C2: [
    [
      'die Nuance',
      'a nuance',
      'substantivo',
      'Die Übersetzung verliert die Nuance.',
      'A tradução perde a nuance.',
    ],
    [
      'der Euphemismus',
      'o eufemismo',
      'substantivo',
      '„Freisetzen" ist ein Euphemismus.',
      '"Liberar" é um eufemismo.',
    ],
    [
      'die Untertreibung',
      'a atenuação irônica',
      'substantivo',
      'Das schwierig zu nennen ist eine Untertreibung.',
      'Chamar isso de difícil é pouco.',
    ],
    [
      'Lügen strafen',
      'desmentir',
      'locução',
      'Sein ruhiger Ton strafte seinen Zorn Lügen.',
      'O tom calmo dele desmentia sua raiva.',
    ],
    [
      'ausweichen',
      'esquivar-se / usar evasivas',
      'verbo',
      'Der Minister wich lange aus.',
      'O ministro usou de evasivas por muito tempo.',
    ],
    [
      'beschönigen',
      'maquiar / dourar a pílula',
      'verbo',
      'Der Bericht beschönigt die Fehler.',
      'O relatório maquia os erros.',
    ],
    [
      'unaufhaltsam',
      'inexorável',
      'adjetivo',
      'Ein langsamer, aber unaufhaltsamer Niedergang.',
      'Um declínio lento, mas inexorável.',
    ],
    [
      'angeblich',
      'supostamente',
      'advérbio',
      'Er trat zurück, angeblich aus Gesundheitsgründen.',
      'Ele renunciou, supostamente por saúde.',
    ],
    [
      'gleichbedeutend mit',
      'equivalente a',
      'adjetivo',
      'Schweigen ist hier gleichbedeutend mit Zustimmung.',
      'Silêncio aqui equivale a consentimento.',
    ],
    [
      'schlechthin',
      'por excelência',
      'advérbio',
      'Er ist der Berliner schlechthin.',
      'Ele é o berlinense por excelência.',
    ],
    [
      'zumal',
      'ainda mais que / visto que',
      'conjunção',
      'Gehen wir, zumal wir einig sind.',
      'Vamos, ainda mais que estamos de acordo.',
    ],
    [
      'bislang',
      'até então / até agora',
      'advérbio',
      'Eine bislang unbekannte Art.',
      'Uma espécie até então desconhecida.',
    ],
  ],
};

/* ================================================================== *
 * Registro
 * ================================================================== */

const LEVEL_VOCABULARY: Partial<Record<LanguageCode, LevelMap>> = {
  en: EN,
  es: ES,
  fr: FR,
  it: IT,
  de: DE,
};

/**
 * Verbetes de um idioma num nível. Devolve lista vazia (nunca `undefined`)
 * para que quem consome não precise checar — conteúdo ausente é uma lista
 * sem itens, não um caso de erro.
 */
export function levelVocabulary(language: LanguageCode, level: CefrLevel): LevelEntry[] {
  return LEVEL_VOCABULARY[language]?.[level] ?? [];
}

/** Todos os níveis que têm conteúdo próprio num idioma. */
export function levelsWithContent(language: LanguageCode): CefrLevel[] {
  const map = LEVEL_VOCABULARY[language];
  if (!map) return [];
  return LEVELED_CEFR.filter((level) => (map[level]?.length ?? 0) > 0);
}

export { LEVEL_VOCABULARY };
