/**
 * Vocabulário semente de japonês, coreano e mandarim.
 *
 * Arquivo separado do `vocabulary.ts` por uma razão prática: estes idiomas
 * carregam **romanização obrigatória**, e misturá-los com os europeus faria a
 * tupla compacta crescer para todos. Aqui a tupla tem um campo a mais.
 *
 * ## Decisão didática: romanização sempre visível
 *
 * Um brasileiro no dia 1 não lê kanji, hangul nem hanzi — e não tem teclado
 * para digitá-los. Mostrar só o script nativo tornaria o idioma inestudável;
 * mostrar só a romanização ensinaria a falar sem nunca aprender a ler.
 *
 * A solução adotada é a dos métodos sérios: **os dois juntos, sempre**, com o
 * script nativo em destaque e a romanização como apoio. A digitação nos
 * exercícios aceita romanização, o que elimina a dependência de IME.
 *
 * Coreano é a exceção parcial: o hangul é alfabético e se aprende em poucos
 * dias, então a romanização some mais cedo na progressão.
 */

import type { CefrLevel, LanguageCode, VocabularyItem } from '@/domain/types';

/**
 * [termo nativo, romanização, tradução PT, classe, exemplo, romanização do
 * exemplo, tradução do exemplo, nível]
 */
type AsianEntry = [string, string, string, string, string, string, string, CefrLevel];

const JA: AsianEntry[] = [
  [
    '私',
    'watashi',
    'eu',
    'pronome',
    '私は学生です。',
    'Watashi wa gakusei desu.',
    'Eu sou estudante.',
    'A1',
  ],
  [
    'あなた',
    'anata',
    'você',
    'pronome',
    'あなたは元気ですか。',
    'Anata wa genki desu ka.',
    'Você está bem?',
    'A1',
  ],
  [
    'です',
    'desu',
    'ser / estar (cópula)',
    'verbo',
    'これは本です。',
    'Kore wa hon desu.',
    'Isto é um livro.',
    'A1',
  ],
  [
    'ある',
    'aru',
    'haver / existir (coisas)',
    'verbo',
    '机の上に本があります。',
    'Tsukue no ue ni hon ga arimasu.',
    'Há um livro sobre a mesa.',
    'A1',
  ],
  [
    'いる',
    'iru',
    'haver / estar (seres vivos)',
    'verbo',
    '猫がいます。',
    'Neko ga imasu.',
    'Há um gato.',
    'A1',
  ],
  [
    'する',
    'suru',
    'fazer',
    'verbo',
    '宿題をします。',
    'Shukudai o shimasu.',
    'Eu faço a lição de casa.',
    'A1',
  ],
  [
    '行く',
    'iku',
    'ir',
    'verbo',
    '学校に行きます。',
    'Gakkō ni ikimasu.',
    'Eu vou para a escola.',
    'A1',
  ],
  [
    '来る',
    'kuru',
    'vir',
    'verbo',
    'ここに来てください。',
    'Koko ni kite kudasai.',
    'Venha aqui, por favor.',
    'A1',
  ],
  [
    '見る',
    'miru',
    'ver / assistir',
    'verbo',
    '映画を見ます。',
    'Eiga o mimasu.',
    'Eu assisto a um filme.',
    'A1',
  ],
  [
    '食べる',
    'taberu',
    'comer',
    'verbo',
    '朝ご飯を食べます。',
    'Asagohan o tabemasu.',
    'Eu tomo café da manhã.',
    'A1',
  ],
  [
    '飲む',
    'nomu',
    'beber',
    'verbo',
    '水を飲みます。',
    'Mizu o nomimasu.',
    'Eu bebo água.',
    'A1',
  ],
  [
    '話す',
    'hanasu',
    'falar',
    'verbo',
    '日本語を話しますか。',
    'Nihongo o hanashimasu ka.',
    'Você fala japonês?',
    'A1',
  ],
  [
    '分かる',
    'wakaru',
    'entender',
    'verbo',
    '分かりません。',
    'Wakarimasen.',
    'Não entendo.',
    'A1',
  ],
  [
    '好き',
    'suki',
    'gostar de',
    'adjetivo',
    'コーヒーが好きです。',
    'Kōhī ga suki desu.',
    'Eu gosto de café.',
    'A1',
  ],
  [
    '水',
    'mizu',
    'água',
    'substantivo',
    '水をください。',
    'Mizu o kudasai.',
    'Água, por favor.',
    'A1',
  ],
  [
    '食べ物',
    'tabemono',
    'comida',
    'substantivo',
    'この食べ物はおいしいです。',
    'Kono tabemono wa oishii desu.',
    'Esta comida está deliciosa.',
    'A1',
  ],
  [
    '家',
    'ie',
    'casa',
    'substantivo',
    '家に帰ります。',
    'Ie ni kaerimasu.',
    'Eu volto para casa.',
    'A1',
  ],
  [
    '人',
    'hito',
    'pessoa',
    'substantivo',
    'あの人は先生です。',
    'Ano hito wa sensei desu.',
    'Aquela pessoa é professora.',
    'A1',
  ],
  [
    '時間',
    'jikan',
    'tempo / hora',
    'substantivo',
    '時間がありません。',
    'Jikan ga arimasen.',
    'Não tenho tempo.',
    'A1',
  ],
  [
    '日',
    'hi',
    'dia',
    'substantivo',
    '今日はいい日です。',
    'Kyō wa ii hi desu.',
    'Hoje é um bom dia.',
    'A1',
  ],
  [
    '年',
    'toshi',
    'ano',
    'substantivo',
    '来年日本に行きます。',
    'Rainen Nihon ni ikimasu.',
    'Ano que vem vou ao Japão.',
    'A1',
  ],
  [
    '仕事',
    'shigoto',
    'trabalho',
    'substantivo',
    '仕事が好きです。',
    'Shigoto ga suki desu.',
    'Gosto do meu trabalho.',
    'A1',
  ],
  [
    'いい',
    'ii',
    'bom',
    'adjetivo',
    'それはいい考えです。',
    'Sore wa ii kangae desu.',
    'Essa é uma boa ideia.',
    'A1',
  ],
  [
    '新しい',
    'atarashii',
    'novo',
    'adjetivo',
    '新しい電話を買いました。',
    'Atarashii denwa o kaimashita.',
    'Comprei um telefone novo.',
    'A1',
  ],
  [
    '大きい',
    'ōkii',
    'grande',
    'adjetivo',
    'この町は大きいです。',
    'Kono machi wa ōkii desu.',
    'Esta cidade é grande.',
    'A1',
  ],
  [
    '小さい',
    'chiisai',
    'pequeno',
    'adjetivo',
    '小さいコーヒーをください。',
    'Chiisai kōhī o kudasai.',
    'Um café pequeno, por favor.',
    'A1',
  ],
  [
    'から',
    'kara',
    'porque / desde',
    'partícula',
    '雨だから家にいました。',
    'Ame dakara ie ni imashita.',
    'Fiquei em casa porque choveu.',
    'A2',
  ],
  [
    'でも',
    'demo',
    'mas',
    'conjunção',
    '高いです。でも買います。',
    'Takai desu. Demo kaimasu.',
    'É caro. Mas vou comprar.',
    'A2',
  ],
  [
    'しかし',
    'shikashi',
    'no entanto',
    'conjunção',
    '遅いです。しかし行きます。',
    'Osoi desu. Shikashi ikimasu.',
    'É tarde. No entanto, vou.',
    'B1',
  ],
  [
    '達成する',
    'tassei suru',
    'alcançar',
    'verbo',
    '目標を達成しました。',
    'Mokuhyō o tassei shimashita.',
    'Alcancei meu objetivo.',
    'B2',
  ],
];

const KO: AsianEntry[] = [
  [
    '저',
    'jeo',
    'eu (formal)',
    'pronome',
    '저는 학생이에요.',
    'Jeoneun haksaeng-ieyo.',
    'Eu sou estudante.',
    'A1',
  ],
  [
    '당신',
    'dangsin',
    'você',
    'pronome',
    '당신은 어때요?',
    'Dangsineun eottaeyo?',
    'Como você está?',
    'A1',
  ],
  [
    '이다',
    'ida',
    'ser',
    'verbo',
    '이것은 책이에요.',
    'Igeoseun chaeg-ieyo.',
    'Isto é um livro.',
    'A1',
  ],
  [
    '있다',
    'itda',
    'ter / existir',
    'verbo',
    '시간이 있어요.',
    'Sigani isseoyo.',
    'Tenho tempo.',
    'A1',
  ],
  [
    '없다',
    'eopda',
    'não ter / não existir',
    'verbo',
    '시간이 없어요.',
    'Sigani eopseoyo.',
    'Não tenho tempo.',
    'A1',
  ],
  [
    '하다',
    'hada',
    'fazer',
    'verbo',
    '뭐 해요?',
    'Mwo haeyo?',
    'O que você está fazendo?',
    'A1',
  ],
  ['가다', 'gada', 'ir', 'verbo', '학교에 가요.', 'Hakgyoe gayo.', 'Vou para a escola.', 'A1'],
  ['오다', 'oda', 'vir', 'verbo', '여기 오세요.', 'Yeogi oseyo.', 'Venha aqui.', 'A1'],
  [
    '보다',
    'boda',
    'ver',
    'verbo',
    '영화를 봐요.',
    'Yeonghwareul bwayo.',
    'Assisto a um filme.',
    'A1',
  ],
  [
    '먹다',
    'meokda',
    'comer',
    'verbo',
    '밥을 먹어요.',
    'Babeul meogeoyo.',
    'Eu como arroz.',
    'A1',
  ],
  [
    '마시다',
    'masida',
    'beber',
    'verbo',
    '물을 마셔요.',
    'Mureul masyeoyo.',
    'Eu bebo água.',
    'A1',
  ],
  [
    '말하다',
    'malhada',
    'falar',
    'verbo',
    '한국어를 말해요.',
    'Hangugeoreul malhaeyo.',
    'Eu falo coreano.',
    'A1',
  ],
  ['알다', 'alda', 'saber', 'verbo', '몰라요.', 'Mollayo.', 'Não sei.', 'A1'],
  [
    '좋아하다',
    'joahada',
    'gostar',
    'verbo',
    '커피를 좋아해요.',
    'Keopireul joahaeyo.',
    'Gosto de café.',
    'A1',
  ],
  ['물', 'mul', 'água', 'substantivo', '물 주세요.', 'Mul juseyo.', 'Água, por favor.', 'A1'],
  [
    '음식',
    'eumsik',
    'comida',
    'substantivo',
    '이 음식은 맛있어요.',
    'I eumsigeun masisseoyo.',
    'Esta comida está deliciosa.',
    'A1',
  ],
  ['집', 'jip', 'casa', 'substantivo', '집에 가요.', 'Jibe gayo.', 'Vou para casa.', 'A1'],
  [
    '사람',
    'saram',
    'pessoa',
    'substantivo',
    '그 사람은 선생님이에요.',
    'Geu sarameun seonsaengnim-ieyo.',
    'Aquela pessoa é professora.',
    'A1',
  ],
  [
    '시간',
    'sigan',
    'tempo / hora',
    'substantivo',
    '시간이 없어요.',
    'Sigani eopseoyo.',
    'Não tenho tempo.',
    'A1',
  ],
  [
    '날',
    'nal',
    'dia',
    'substantivo',
    '좋은 날이에요.',
    'Joeun nal-ieyo.',
    'É um bom dia.',
    'A1',
  ],
  [
    '년',
    'nyeon',
    'ano',
    'substantivo',
    '작년은 힘들었어요.',
    'Jangnyeoneun himdeureosseoyo.',
    'O ano passado foi difícil.',
    'A1',
  ],
  [
    '일',
    'il',
    'trabalho',
    'substantivo',
    '제 일을 좋아해요.',
    'Je ireul joahaeyo.',
    'Gosto do meu trabalho.',
    'A1',
  ],
  [
    '좋다',
    'jota',
    'bom',
    'adjetivo',
    '좋은 생각이에요.',
    'Joeun saenggag-ieyo.',
    'É uma boa ideia.',
    'A1',
  ],
  [
    '새롭다',
    'saeropda',
    'novo',
    'adjetivo',
    '새 휴대폰을 샀어요.',
    'Sae hyudaeponeul sasseoyo.',
    'Comprei um celular novo.',
    'A1',
  ],
  [
    '크다',
    'keuda',
    'grande',
    'adjetivo',
    '이 도시는 커요.',
    'I dosineun keoyo.',
    'Esta cidade é grande.',
    'A1',
  ],
  [
    '작다',
    'jakda',
    'pequeno',
    'adjetivo',
    '작은 커피 주세요.',
    'Jageun keopi juseyo.',
    'Um café pequeno, por favor.',
    'A1',
  ],
  [
    '그래서',
    'geuraeseo',
    'por isso',
    'conjunção',
    '비가 와서 집에 있었어요.',
    'Biga waseo jibe isseosseoyo.',
    'Choveu, por isso fiquei em casa.',
    'A2',
  ],
  [
    '하지만',
    'hajiman',
    'mas',
    'conjunção',
    '비싸요. 하지만 살 거예요.',
    'Bissayo. Hajiman sal geoyeyo.',
    'É caro. Mas vou comprar.',
    'A2',
  ],
  [
    '그러나',
    'geureona',
    'no entanto',
    'conjunção',
    '늦었어요. 그러나 갈 거예요.',
    'Neujeosseoyo. Geureona gal geoyeyo.',
    'É tarde. No entanto, vou.',
    'B1',
  ],
  [
    '달성하다',
    'dalseonghada',
    'alcançar',
    'verbo',
    '목표를 달성했어요.',
    'Mokpyoreul dalseonghaesseoyo.',
    'Alcancei meu objetivo.',
    'B2',
  ],
];

const ZH: AsianEntry[] = [
  ['我', 'wǒ', 'eu', 'pronome', '我是学生。', 'Wǒ shì xuéshēng.', 'Eu sou estudante.', 'A1'],
  ['你', 'nǐ', 'você', 'pronome', '你好吗？', 'Nǐ hǎo ma?', 'Você está bem?', 'A1'],
  ['是', 'shì', 'ser', 'verbo', '这是书。', 'Zhè shì shū.', 'Isto é um livro.', 'A1'],
  [
    '有',
    'yǒu',
    'ter / haver',
    'verbo',
    '我有时间。',
    'Wǒ yǒu shíjiān.',
    'Eu tenho tempo.',
    'A1',
  ],
  [
    '做',
    'zuò',
    'fazer',
    'verbo',
    '你在做什么？',
    'Nǐ zài zuò shénme?',
    'O que você está fazendo?',
    'A1',
  ],
  ['去', 'qù', 'ir', 'verbo', '我去学校。', 'Wǒ qù xuéxiào.', 'Eu vou para a escola.', 'A1'],
  [
    '来',
    'lái',
    'vir',
    'verbo',
    '请来这里。',
    'Qǐng lái zhèlǐ.',
    'Venha aqui, por favor.',
    'A1',
  ],
  [
    '看',
    'kàn',
    'ver / assistir',
    'verbo',
    '我看电影。',
    'Wǒ kàn diànyǐng.',
    'Eu assisto a um filme.',
    'A1',
  ],
  [
    '吃',
    'chī',
    'comer',
    'verbo',
    '我吃早饭。',
    'Wǒ chī zǎofàn.',
    'Eu tomo café da manhã.',
    'A1',
  ],
  ['喝', 'hē', 'beber', 'verbo', '我喝水。', 'Wǒ hē shuǐ.', 'Eu bebo água.', 'A1'],
  [
    '说',
    'shuō',
    'falar',
    'verbo',
    '你说中文吗？',
    'Nǐ shuō Zhōngwén ma?',
    'Você fala chinês?',
    'A1',
  ],
  ['知道', 'zhīdào', 'saber', 'verbo', '我不知道。', 'Wǒ bù zhīdào.', 'Eu não sei.', 'A1'],
  [
    '喜欢',
    'xǐhuān',
    'gostar',
    'verbo',
    '我喜欢咖啡。',
    'Wǒ xǐhuān kāfēi.',
    'Eu gosto de café.',
    'A1',
  ],
  [
    '想',
    'xiǎng',
    'querer / pensar',
    'verbo',
    '我想学中文。',
    'Wǒ xiǎng xué Zhōngwén.',
    'Quero aprender chinês.',
    'A1',
  ],
  [
    '水',
    'shuǐ',
    'água',
    'substantivo',
    '请给我水。',
    'Qǐng gěi wǒ shuǐ.',
    'Água, por favor.',
    'A1',
  ],
  [
    '食物',
    'shíwù',
    'comida',
    'substantivo',
    '这个食物很好吃。',
    'Zhège shíwù hěn hào chī.',
    'Esta comida está deliciosa.',
    'A1',
  ],
  ['家', 'jiā', 'casa', 'substantivo', '我回家。', 'Wǒ huí jiā.', 'Eu volto para casa.', 'A1'],
  [
    '人',
    'rén',
    'pessoa',
    'substantivo',
    '那个人是老师。',
    'Nàge rén shì lǎoshī.',
    'Aquela pessoa é professora.',
    'A1',
  ],
  [
    '时间',
    'shíjiān',
    'tempo',
    'substantivo',
    '我没有时间。',
    'Wǒ méiyǒu shíjiān.',
    'Não tenho tempo.',
    'A1',
  ],
  [
    '天',
    'tiān',
    'dia',
    'substantivo',
    '今天是好天。',
    'Jīntiān shì hǎo tiān.',
    'Hoje é um bom dia.',
    'A1',
  ],
  [
    '年',
    'nián',
    'ano',
    'substantivo',
    '去年很难。',
    'Qùnián hěn nán.',
    'O ano passado foi difícil.',
    'A1',
  ],
  [
    '工作',
    'gōngzuò',
    'trabalho',
    'substantivo',
    '我喜欢我的工作。',
    'Wǒ xǐhuān wǒ de gōngzuò.',
    'Gosto do meu trabalho.',
    'A1',
  ],
  [
    '好',
    'hǎo',
    'bom',
    'adjetivo',
    '这是好主意。',
    'Zhè shì hǎo zhǔyì.',
    'Essa é uma boa ideia.',
    'A1',
  ],
  [
    '新',
    'xīn',
    'novo',
    'adjetivo',
    '我买了新手机。',
    'Wǒ mǎi le xīn shǒujī.',
    'Comprei um celular novo.',
    'A1',
  ],
  [
    '大',
    'dà',
    'grande',
    'adjetivo',
    '这个城市很大。',
    'Zhège chéngshì hěn dà.',
    'Esta cidade é grande.',
    'A1',
  ],
  [
    '小',
    'xiǎo',
    'pequeno',
    'adjetivo',
    '请给我小咖啡。',
    'Qǐng gěi wǒ xiǎo kāfēi.',
    'Um café pequeno, por favor.',
    'A1',
  ],
  [
    '因为',
    'yīnwèi',
    'porque',
    'conjunção',
    '因为下雨，我在家。',
    'Yīnwèi xiàyǔ, wǒ zài jiā.',
    'Fiquei em casa porque choveu.',
    'A2',
  ],
  [
    '但是',
    'dànshì',
    'mas',
    'conjunção',
    '很贵，但是我要买。',
    'Hěn guì, dànshì wǒ yào mǎi.',
    'É caro, mas vou comprar.',
    'A2',
  ],
  [
    '然而',
    "rán'ér",
    'no entanto',
    'conjunção',
    '很晚了，然而我要去。',
    "Hěn wǎn le, rán'ér wǒ yào qù.",
    'É tarde; no entanto, vou.',
    'B1',
  ],
  [
    '实现',
    'shíxiàn',
    'alcançar / realizar',
    'verbo',
    '她实现了目标。',
    'Tā shíxiàn le mùbiāo.',
    'Ela alcançou seu objetivo.',
    'B2',
  ],
];

const RAW: Partial<Record<LanguageCode, AsianEntry[]>> = { ja: JA, ko: KO, zh: ZH };

/** Constrói os verbetes de um idioma asiático, se houver. */
export function buildAsianVocabulary(language: LanguageCode): VocabularyItem[] {
  const entries = RAW[language];
  if (!entries) return [];

  return entries.map((entry, index) => {
    const [
      term,
      romanization,
      translation,
      partOfSpeech,
      example,
      exampleRoman,
      exampleTranslation,
      cefr,
    ] = entry;

    return {
      // Id determinístico pela romanização: o script nativo não sobrevive à
      // normalização de id, e a romanização é única dentro do idioma.
      id: `vocab:${language}:${romanization.replace(/[^a-z0-9]/gi, '_').toLowerCase()}`,
      language,
      term,
      translation,
      partOfSpeech,
      phonetic: null,
      romanization,
      exampleSentence: example,
      exampleTranslation,
      exampleRomanization: exampleRoman,
      frequencyRank: index + 1,
      cefr,
      tags: [partOfSpeech],
    };
  });
}

export const ASIAN_LANGUAGES = Object.keys(RAW) as LanguageCode[];
