/** Alemão — lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const DE_THEMATIC: LatinByLevel = {
  A1: [
    ['grün', 'verde', 'adjetivo', 'Das Gras ist grün.', 'A grama é verde.', 'Cores e formas'],
    ['gelb', 'amarelo', 'adjetivo', 'Ich mag gelbe Blumen.', 'Gosto de flores amarelas.', 'Cores e formas'],
    ['schwarz', 'preto', 'adjetivo', 'Er trägt einen schwarzen Mantel.', 'Ele usa um casaco preto.', 'Cores e formas'],
    ['weiß', 'branco', 'adjetivo', 'Die Wände sind weiß.', 'As paredes são brancas.', 'Cores e formas'],
    ['orange', 'laranja', 'adjetivo', 'Sie hat eine orange Tasche.', 'Ela tem uma bolsa laranja.', 'Cores e formas'],
    ['lila', 'roxo', 'adjetivo', 'Der Himmel wurde lila.', 'O céu ficou roxo.', 'Cores e formas'],
    ['braun', 'marrom', 'adjetivo', 'Meine Schuhe sind braun.', 'Meus sapatos são marrons.', 'Cores e formas'],
    ['rosa', 'rosa', 'adjetivo', 'Das Baby hat eine rosa Decke.', 'O bebê tem um cobertor rosa.', 'Cores e formas'],
    ['der Kreis', 'círculo', 'substantivo', 'Zeichne hier einen Kreis.', 'Desenhe um círculo aqui.', 'Cores e formas'],
    ['das Quadrat', 'quadrado', 'substantivo', 'Die Schachtel ist ein Quadrat.', 'A caixa é um quadrado.', 'Cores e formas'],
    ['das Hemd', 'camisa', 'substantivo', 'Dieses Hemd ist sauber.', 'Esta camisa está limpa.', 'Roupas'],
    ['die Hose', 'calça', 'substantivo', 'Diese Hose ist neu.', 'Esta calça é nova.', 'Roupas'],
    ['die Schuhe', 'sapatos', 'substantivo', 'Meine Schuhe sind nass.', 'Meus sapatos estão molhados.', 'Roupas'],
    ['das Kleid', 'vestido', 'substantivo', 'Sie hat ein Kleid gekauft.', 'Ela comprou um vestido.', 'Roupas'],
    ['die Jacke', 'jaqueta', 'substantivo', 'Nimm deine Jacke mit.', 'Leve sua jaqueta.', 'Roupas'],
    ['der Hut', 'chapéu', 'substantivo', 'Er hat seinen Hut verloren.', 'Ele perdeu o chapéu.', 'Roupas'],
    ['die Socken', 'meias', 'substantivo', 'Ich brauche saubere Socken.', 'Preciso de meias limpas.', 'Roupas'],
    ['der Mantel', 'casaco', 'substantivo', 'Zieh heute einen Mantel an.', 'Use um casaco hoje.', 'Roupas'],
    ['der Rock', 'saia', 'substantivo', 'Dieser Rock ist lang.', 'Aquela saia é longa.', 'Roupas'],
    ['die Brille', 'óculos', 'substantivo', 'Ich habe meine Brille vergessen.', 'Esqueci meus óculos.', 'Roupas'],
    ['die Sonne', 'sol', 'substantivo', 'Die Sonne ist stark.', 'O sol está forte.', 'Clima e natureza'],
    ['der Regen', 'chuva', 'substantivo', 'Der Regen hat aufgehört.', 'A chuva parou.', 'Clima e natureza'],
    ['der Schnee', 'neve', 'substantivo', 'Der Schnee ist tief.', 'A neve está funda.', 'Clima e natureza'],
    ['der Wind', 'vento', 'substantivo', 'Der Wind ist stark.', 'O vento está forte.', 'Clima e natureza'],
    ['die Wolke', 'nuvem', 'substantivo', 'Da ist eine Wolke.', 'Há uma nuvem.', 'Clima e natureza'],
    ['der Baum', 'árvore', 'substantivo', 'Der Baum ist alt.', 'A árvore é velha.', 'Clima e natureza'],
    ['die Blume', 'flor', 'substantivo', 'Sie mag diese Blume.', 'Ela gosta desta flor.', 'Clima e natureza'],
    ['der Himmel', 'céu', 'substantivo', 'Der Himmel ist klar.', 'O céu está limpo.', 'Clima e natureza'],
    ['der Strand', 'praia', 'substantivo', 'Wir gehen an den Strand.', 'Nós vamos à praia.', 'Clima e natureza'],
    ['der Berg', 'montanha', 'substantivo', 'Der Berg ist hoch.', 'A montanha é alta.', 'Clima e natureza'],
    ['der Kopf', 'cabeça', 'substantivo', 'Mein Kopf tut weh.', 'Minha cabeça dói.', 'Corpo'],
    ['die Hand', 'mão', 'substantivo', 'Gib mir deine Hand.', 'Me dê sua mão.', 'Corpo'],
    ['der Fuß', 'pé', 'substantivo', 'Mein Fuß ist kalt.', 'Meu pé está frio.', 'Corpo'],
    ['das Auge', 'olho', 'substantivo', 'Sie hat ein grünes Auge.', 'Ela tem um olho verde.', 'Corpo'],
    ['das Ohr', 'orelha / ouvido', 'substantivo', 'Mein Ohr tut weh.', 'Meu ouvido dói.', 'Corpo'],
    ['der Mund', 'boca', 'substantivo', 'Mach den Mund auf.', 'Abra a boca.', 'Corpo'],
    ['die Nase', 'nariz', 'substantivo', 'Seine Nase ist rot.', 'O nariz dele está vermelho.', 'Corpo'],
    ['die Haare', 'cabelo', 'substantivo', 'Sie hat lange Haare.', 'O cabelo dela é longo.', 'Corpo'],
    ['der Arm', 'braço', 'substantivo', 'Er hat sich den Arm gebrochen.', 'Ele quebrou o braço.', 'Corpo'],
    ['das Bein', 'perna', 'substantivo', 'Mein Bein ist müde.', 'Minha perna está cansada.', 'Corpo'],
    ['das Brot', 'pão', 'substantivo', 'Ich esse jeden Tag Brot.', 'Eu como pão todo dia.', 'Comida e bebida'],
    ['die Milch', 'leite', 'substantivo', 'Die Milch ist kalt.', 'O leite está frio.', 'Comida e bebida'],
    ['der Kaffee', 'café', 'substantivo', 'Sie trinkt Kaffee.', 'Ela bebe café.', 'Comida e bebida'],
    ['der Reis', 'arroz', 'substantivo', 'Wir essen mittags Reis.', 'Comemos arroz no almoço.', 'Comida e bebida'],
    ['das Fleisch', 'carne', 'substantivo', 'Er isst kein Fleisch.', 'Ele não come carne.', 'Comida e bebida'],
    ['das Obst', 'fruta', 'substantivo', 'Kauf etwas Obst.', 'Compre frutas.', 'Comida e bebida'],
    ['das Ei', 'ovo', 'substantivo', 'Ich möchte ein Ei.', 'Quero um ovo.', 'Comida e bebida'],
    ['der Käse', 'queijo', 'substantivo', 'Dieser Käse ist gut.', 'Este queijo é bom.', 'Comida e bebida'],
    ['der Zucker', 'açúcar', 'substantivo', 'Ohne Zucker, bitte.', 'Sem açúcar, por favor.', 'Comida e bebida'],
    ['das Salz', 'sal', 'substantivo', 'Gib mir das Salz.', 'Me passe o sal.', 'Comida e bebida'],
    ['der Morgen', 'manhã', 'substantivo', 'Ich arbeite am Morgen.', 'Eu trabalho de manhã.', 'Tempo e rotina'],
    ['der Nachmittag', 'tarde', 'substantivo', 'Bis heute Nachmittag.', 'Até a tarde.', 'Tempo e rotina'],
    ['der Abend', 'fim de tarde / noite', 'substantivo', 'Wir essen am Abend.', 'Nós comemos à noite.', 'Tempo e rotina'],
    ['die Nacht', 'noite', 'substantivo', 'Die Nacht ist ruhig.', 'A noite está calma.', 'Tempo e rotina'],
    ['die Woche', 'semana', 'substantivo', 'Die Woche ist lang.', 'A semana é longa.', 'Tempo e rotina'],
    ['der Monat', 'mês', 'substantivo', 'Dieser Monat ist voll.', 'Este mês está cheio.', 'Tempo e rotina'],
    ['heute', 'hoje', 'advérbio', 'Ich bin heute müde.', 'Estou cansado hoje.', 'Tempo e rotina'],
    ['gestern', 'ontem', 'advérbio', 'Gestern hat es geregnet.', 'Choveu ontem.', 'Tempo e rotina'],
    ['die Stunde', 'hora', 'substantivo', 'Warte eine Stunde.', 'Espere uma hora.', 'Tempo e rotina'],
    ['das Wochenende', 'fim de semana', 'substantivo', 'Am Wochenende ruhe ich mich aus.', 'No fim de semana eu descanso.', 'Tempo e rotina'],
  ],
  A2: [
    ['der Flug', 'voo', 'substantivo', 'Unser Flug geht um sechs.', 'Nosso voo sai às seis.', 'Viagem'],
    ['der Reisepass', 'passaporte', 'substantivo', 'Zeigen Sie mir Ihren Reisepass.', 'Me mostre seu passaporte.', 'Viagem'],
    ['das Gepäck', 'bagagem', 'substantivo', 'Mein Gepäck ist schwer.', 'Minha bagagem está pesada.', 'Viagem'],
    ['die Fahrkarte', 'passagem / bilhete', 'substantivo', 'Ich habe die Fahrkarte online gekauft.', 'Comprei a passagem pela internet.', 'Viagem'],
    ['die Verspätung', 'atraso', 'substantivo', 'Es gab eine lange Verspätung.', 'Houve um atraso longo.', 'Viagem'],
    ['der Flughafen', 'aeroporto', 'substantivo', 'Der Flughafen ist weit weg.', 'O aeroporto é longe.', 'Viagem'],
    ['der Koffer', 'mala', 'substantivo', 'Pack heute Abend deinen Koffer.', 'Faça sua mala hoje à noite.', 'Viagem'],
    ['die Abfahrt', 'partida', 'substantivo', 'Prüf die Abfahrtszeit.', 'Confira o horário de partida.', 'Viagem'],
    ['die Ankunft', 'chegada', 'substantivo', 'Die Ankunft verlief reibungslos.', 'A chegada foi tranquila.', 'Viagem'],
    ['die Bordkarte', 'cartão de embarque', 'substantivo', 'Behalte deine Bordkarte.', 'Guarde seu cartão de embarque.', 'Viagem'],
    ['die Speisekarte', 'cardápio', 'substantivo', 'Kann ich die Speisekarte sehen?', 'Posso ver o cardápio?', 'Restaurante'],
    ['der Kellner', 'garçom', 'substantivo', 'Der Kellner kommt gleich.', 'O garçom está vindo.', 'Restaurante'],
    ['das Trinkgeld', 'gorjeta', 'substantivo', 'Wir haben ein gutes Trinkgeld gegeben.', 'Deixamos uma boa gorjeta.', 'Restaurante'],
    ['der Nachtisch', 'sobremesa', 'substantivo', 'Ich möchte einen Nachtisch.', 'Quero uma sobremesa.', 'Restaurante'],
    ['die Vorspeise', 'entrada (prato)', 'substantivo', 'Die Vorspeise war klein.', 'A entrada era pequena.', 'Restaurante'],
    ['die Reservierung', 'reserva', 'substantivo', 'Ich habe eine Reservierung gemacht.', 'Fiz uma reserva.', 'Restaurante'],
    ['die Serviette', 'guardanapo', 'substantivo', 'Gib mir eine Serviette.', 'Me passe um guardanapo.', 'Restaurante'],
    ['das Tablett', 'bandeja', 'substantivo', 'Stell es auf das Tablett.', 'Coloque na bandeja.', 'Restaurante'],
    ['der Geschmack', 'sabor', 'substantivo', 'Der Geschmack ist merkwürdig.', 'O sabor está estranho.', 'Restaurante'],
    ['scharf', 'picante', 'adjetivo', 'Dieses Gericht ist scharf.', 'Este prato é picante.', 'Restaurante'],
    ['das Bargeld', 'dinheiro (em espécie)', 'substantivo', 'Ich habe nur Bargeld.', 'Só tenho dinheiro em espécie.', 'Compras'],
    ['das Wechselgeld', 'troco', 'substantivo', 'Behalten Sie das Wechselgeld.', 'Fique com o troco.', 'Compras'],
    ['die Größe', 'tamanho (roupa)', 'substantivo', 'Haben Sie eine größere Größe?', 'Tem um tamanho maior?', 'Compras'],
    ['das Schnäppchen', 'pechincha', 'substantivo', 'Der Mantel war ein Schnäppchen.', 'Aquele casaco foi uma pechincha.', 'Compras'],
    ['der Kassierer', 'caixa (pessoa)', 'substantivo', 'Frag den Kassierer.', 'Pergunte ao caixa.', 'Compras'],
    ['der Gang', 'corredor (de loja)', 'substantivo', 'Die Milch ist in Gang drei.', 'O leite está no corredor três.', 'Compras'],
    ['das Regal', 'prateleira', 'substantivo', 'Das Regal ist leer.', 'A prateleira está vazia.', 'Compras'],
    ['der Ausverkauf', 'liquidação', 'substantivo', 'Die Schuhe sind im Ausverkauf.', 'Os sapatos estão em liquidação.', 'Compras'],
    ['die Geldbörse', 'carteira', 'substantivo', 'Ich habe meine Geldbörse zu Hause gelassen.', 'Deixei minha carteira em casa.', 'Compras'],
    ['die Marke', 'marca', 'substantivo', 'Ich vertraue dieser Marke.', 'Confio nesta marca.', 'Compras'],
    ['der Husten', 'tosse', 'substantivo', 'Sie hat einen schlimmen Husten.', 'Ela está com uma tosse feia.', 'Saúde'],
    ['die Kopfschmerzen', 'dor de cabeça', 'substantivo', 'Ich habe Kopfschmerzen.', 'Estou com dor de cabeça.', 'Saúde'],
    ['die Tablette', 'comprimido', 'substantivo', 'Nimm eine Tablette pro Tag.', 'Tome um comprimido por dia.', 'Saúde'],
    ['der Krankenpfleger', 'enfermeiro', 'substantivo', 'Der Krankenpfleger war nett.', 'O enfermeiro foi gentil.', 'Saúde'],
    ['die Verletzung', 'lesão', 'substantivo', 'Die Verletzung war ernst.', 'A lesão foi séria.', 'Saúde'],
    ['die Ruhe', 'descanso / sossego', 'substantivo', 'Du brauchst Ruhe.', 'Você precisa de descanso.', 'Saúde'],
    ['das Pflaster', 'curativo', 'substantivo', 'Kleb ein Pflaster drauf.', 'Coloque um curativo nisso.', 'Saúde'],
    ['schwindelig', 'tonto', 'adjetivo', 'Mir ist schwindelig.', 'Estou me sentindo tonto.', 'Saúde'],
    ['die Klinik', 'clínica', 'substantivo', 'Die Klinik öffnet um acht.', 'A clínica abre às oito.', 'Saúde'],
    ['der Schmerz', 'dor', 'substantivo', 'Ich habe Schmerzen im Rücken.', 'Tenho dor nas costas.', 'Saúde'],
    ['die Brücke', 'ponte', 'substantivo', 'Überquere die Brücke.', 'Atravesse a ponte.', 'Cidade'],
    ['der Platz', 'praça', 'substantivo', 'Wir haben uns am Platz getroffen.', 'Nos encontramos na praça.', 'Cidade'],
    ['die Ecke', 'esquina', 'substantivo', 'Bieg an der Ecke ab.', 'Vire na esquina.', 'Cidade'],
    ['der Verkehr', 'trânsito', 'substantivo', 'Der Verkehr ist furchtbar.', 'O trânsito está terrível.', 'Cidade'],
    ['die U-Bahn', 'metrô', 'substantivo', 'Nimm die U-Bahn.', 'Pegue o metrô.', 'Cidade'],
    ['die Haltestelle', 'parada (ônibus)', 'substantivo', 'Steig an der nächsten Haltestelle aus.', 'Desça na próxima parada.', 'Cidade'],
    ['die Karte', 'mapa', 'substantivo', 'Schau auf die Karte.', 'Olhe o mapa.', 'Cidade'],
    ['der Weg', 'caminho', 'substantivo', 'Folge diesem Weg.', 'Siga este caminho.', 'Cidade'],
    ['das Tor', 'portão', 'substantivo', 'Das Tor ist abgeschlossen.', 'O portão está trancado.', 'Cidade'],
    ['der Zebrastreifen', 'faixa de pedestres', 'substantivo', 'Benutze den Zebrastreifen.', 'Use a faixa de pedestres.', 'Cidade'],
    ['die Wäsche', 'roupa para lavar', 'substantivo', 'Ich mache die Wäsche am Sonntag.', 'Eu lavo a roupa no domingo.', 'Casa e tarefas'],
    ['das Geschirr', 'louça', 'substantivo', 'Er spült das Geschirr.', 'Ele lava a louça.', 'Casa e tarefas'],
    ['der Besen', 'vassoura', 'substantivo', 'Wo ist der Besen?', 'Onde está a vassoura?', 'Casa e tarefas'],
    ['der Müll', 'lixo', 'substantivo', 'Bring den Müll raus.', 'Leve o lixo para fora.', 'Casa e tarefas'],
    ['das Handtuch', 'toalha', 'substantivo', 'Das Handtuch ist nass.', 'A toalha está molhada.', 'Casa e tarefas'],
    ['die Decke', 'cobertor', 'substantivo', 'Ich brauche noch eine Decke.', 'Preciso de outro cobertor.', 'Casa e tarefas'],
    ['die Schublade', 'gaveta', 'substantivo', 'Es ist in der Schublade.', 'Está na gaveta.', 'Casa e tarefas'],
    ['der Schrank', 'armário', 'substantivo', 'Häng es in den Schrank.', 'Pendure no armário.', 'Casa e tarefas'],
    ['das Waschbecken', 'pia', 'substantivo', 'Das Waschbecken ist verstopft.', 'A pia está entupida.', 'Casa e tarefas'],
    ['der Spiegel', 'espelho', 'substantivo', 'Schau in den Spiegel.', 'Olhe no espelho.', 'Casa e tarefas'],
  ],
  B1: [
    ['das Vorstellungsgespräch', 'entrevista de emprego', 'substantivo', 'Das Vorstellungsgespräch lief gut.', 'A entrevista de emprego correu bem.', 'Trabalho'],
    ['der Lebenslauf', 'currículo', 'substantivo', 'Schick mir deinen Lebenslauf.', 'Me mande seu currículo.', 'Trabalho'],
    ['die Schicht', 'turno', 'substantivo', 'Ich arbeite die Nachtschicht.', 'Eu trabalho no turno da noite.', 'Trabalho'],
    ['die Überstunden', 'horas extras', 'substantivo', 'Sie hat wieder Überstunden gemacht.', 'Ela fez hora extra de novo.', 'Trabalho'],
    ['das Praktikum', 'estágio', 'substantivo', 'Er hat ein Praktikum bekommen.', 'Ele conseguiu um estágio.', 'Trabalho'],
    ['der Vorgesetzte', 'superior / chefe', 'substantivo', 'Sprich mit deinem Vorgesetzten.', 'Fale com seu chefe.', 'Trabalho'],
    ['die Aufgabe', 'tarefa', 'substantivo', 'Diese Aufgabe dauert zwei Stunden.', 'Esta tarefa leva duas horas.', 'Trabalho'],
    ['die Besprechung', 'reunião', 'substantivo', 'Die Besprechung wurde abgesagt.', 'A reunião foi cancelada.', 'Trabalho'],
    ['die Belegschaft', 'quadro de funcionários', 'substantivo', 'Die Belegschaft ist freundlich.', 'A equipe é simpática.', 'Trabalho'],
    ['der Vertrag', 'contrato', 'substantivo', 'Lies zuerst den Vertrag.', 'Leia o contrato primeiro.', 'Trabalho'],
    ['die Aktualisierung', 'atualização', 'substantivo', 'Installiere die Aktualisierung.', 'Instale a atualização.', 'Tecnologia'],
    ['das Passwort', 'senha', 'substantivo', 'Ich habe mein Passwort vergessen.', 'Esqueci minha senha.', 'Tecnologia'],
    ['die Sicherungskopie', 'cópia de segurança', 'substantivo', 'Mach zuerst eine Sicherungskopie.', 'Faça uma cópia de segurança antes.', 'Tecnologia'],
    ['das Gerät', 'aparelho / dispositivo', 'substantivo', 'Dieses Gerät ist schnell.', 'Este aparelho é rápido.', 'Tecnologia'],
    ['der Bildschirm', 'tela', 'substantivo', 'Der Bildschirm ist kaputt.', 'A tela está quebrada.', 'Tecnologia'],
    ['herunterladen', 'baixar', 'verbo', 'Lade die Datei jetzt herunter.', 'Baixe o arquivo agora.', 'Tecnologia'],
    ['das Netzwerk', 'rede', 'substantivo', 'Das Netzwerk ist ausgefallen.', 'A rede está fora do ar.', 'Tecnologia'],
    ['der Browser', 'navegador', 'substantivo', 'Öffne einen neuen Browser-Tab.', 'Abra uma nova aba do navegador.', 'Tecnologia'],
    ['der Ordner', 'pasta', 'substantivo', 'Speichere es in diesem Ordner.', 'Salve nesta pasta.', 'Tecnologia'],
    ['abstürzen', 'travar (programa)', 'verbo', 'Die App ist wieder abgestürzt.', 'O aplicativo travou de novo.', 'Tecnologia'],
    ['recyceln', 'reciclar', 'verbo', 'Hier recyceln wir Plastik.', 'Aqui nós reciclamos plástico.', 'Meio ambiente'],
    ['die Verschmutzung', 'poluição', 'substantivo', 'Die Verschmutzung ist schlimmer geworden.', 'A poluição piorou.', 'Meio ambiente'],
    ['der Abfall', 'resíduo', 'substantivo', 'Lebensmittelabfall ist ein Problem.', 'O resíduo alimentar é um problema.', 'Meio ambiente'],
    ['das Klima', 'clima', 'substantivo', 'Das Klima verändert sich.', 'O clima está mudando.', 'Meio ambiente'],
    ['die Energie', 'energia', 'substantivo', 'Solarenergie ist jetzt billiger.', 'A energia solar está mais barata agora.', 'Meio ambiente'],
    ['der Wald', 'floresta', 'substantivo', 'Der Wald steht unter Schutz.', 'A floresta é protegida.', 'Meio ambiente'],
    ['die Art', 'espécie', 'substantivo', 'Diese Art ist selten.', 'Esta espécie é rara.', 'Meio ambiente'],
    ['die Dürre', 'seca', 'substantivo', 'Die Dürre dauerte Monate.', 'A seca durou meses.', 'Meio ambiente'],
    ['die Überschwemmung', 'enchente', 'substantivo', 'Die Überschwemmung beschädigte die Straße.', 'A enchente danificou a estrada.', 'Meio ambiente'],
    ['das Abwasser', 'esgoto / efluente', 'substantivo', 'Das Abwasser erreichte den Fluss.', 'O efluente chegou ao rio.', 'Meio ambiente'],
    ['der Schiedsrichter', 'árbitro', 'substantivo', 'Der Schiedsrichter unterbrach das Spiel.', 'O árbitro parou o jogo.', 'Esportes'],
    ['das Turnier', 'torneio', 'substantivo', 'Sie hat das Turnier gewonnen.', 'Ela ganhou o torneio.', 'Esportes'],
    ['der Gegner', 'adversário', 'substantivo', 'Sein Gegner war schneller.', 'O adversário dele era mais rápido.', 'Esportes'],
    ['der Mannschaftskamerad', 'companheiro de equipe', 'substantivo', 'Mein Mannschaftskamerad hat getroffen.', 'Meu companheiro de equipe marcou.', 'Esportes'],
    ['der Trainer', 'treinador', 'substantivo', 'Der Trainer war wütend.', 'O treinador estava bravo.', 'Esportes'],
    ['der Spielstand', 'placar', 'substantivo', 'Wie ist der Spielstand?', 'Qual é o placar?', 'Esportes'],
    ['das Spiel', 'partida', 'substantivo', 'Das Spiel beginnt um acht.', 'A partida começa às oito.', 'Esportes'],
    ['das Training', 'treino', 'substantivo', 'Das Training ist jeden Morgen.', 'O treino é toda manhã.', 'Esportes'],
    ['die Ausdauer', 'resistência física', 'substantivo', 'Er hat viel Ausdauer.', 'Ele tem muita resistência.', 'Esportes'],
    ['die Meisterschaft', 'campeonato', 'substantivo', 'Sie haben die Meisterschaft verloren.', 'Eles perderam o campeonato.', 'Esportes'],
    ['streiten', 'brigar / discutir', 'verbo', 'Sie streiten wegen Geld.', 'Eles brigam por dinheiro.', 'Relacionamentos'],
    ['sich entschuldigen', 'pedir desculpas', 'verbo', 'Er hat sich schnell entschuldigt.', 'Ele pediu desculpas rápido.', 'Relacionamentos'],
    ['das Vertrauen', 'confiança', 'substantivo', 'Vertrauen braucht Zeit.', 'Confiança leva tempo.', 'Relacionamentos'],
    ['eifersüchtig', 'ciumento', 'adjetivo', 'Sie wird schnell eifersüchtig.', 'Ela fica com ciúmes fácil.', 'Relacionamentos'],
    ['treu', 'leal / fiel', 'adjetivo', 'Er ist ein treuer Freund.', 'Ele é um amigo leal.', 'Relacionamentos'],
    ['der Klatsch', 'fofoca', 'substantivo', 'Ich hasse Büroklatsch.', 'Odeio fofoca de escritório.', 'Relacionamentos'],
    ['der Rat', 'conselho', 'substantivo', 'Das war ein guter Rat.', 'Aquilo foi um bom conselho.', 'Relacionamentos'],
    ['der Gefallen', 'favor', 'substantivo', 'Kann ich dich um einen Gefallen bitten?', 'Posso te pedir um favor?', 'Relacionamentos'],
    ['der Zwist', 'desentendimento', 'substantivo', 'Sie hatten einen dummen Zwist.', 'Eles tiveram um desentendimento bobo.', 'Relacionamentos'],
    ['der Kompromiss', 'acordo mútuo', 'substantivo', 'Wir haben einen Kompromiss gefunden.', 'Chegamos a um acordo.', 'Relacionamentos'],
    ['das Budget', 'orçamento', 'substantivo', 'Halte dich ans Budget.', 'Siga o orçamento.', 'Dinheiro'],
    ['die Ersparnisse', 'poupança', 'substantivo', 'Sie hat ihre Ersparnisse benutzt.', 'Ela usou a poupança.', 'Dinheiro'],
    ['das Darlehen', 'empréstimo', 'substantivo', 'Er hat ein Darlehen aufgenommen.', 'Ele fez um empréstimo.', 'Dinheiro'],
    ['die Schulden', 'dívida', 'substantivo', 'Sie haben die Schulden abbezahlt.', 'Eles quitaram a dívida.', 'Dinheiro'],
    ['die Ausgabe', 'despesa', 'substantivo', 'Die Miete ist meine größte Ausgabe.', 'O aluguel é minha maior despesa.', 'Dinheiro'],
    ['die Zinsen', 'juros', 'substantivo', 'Die Zinsen sind zu hoch.', 'Os juros estão altos demais.', 'Dinheiro'],
    ['investieren', 'investir', 'verbo', 'Sie investieren in Immobilien.', 'Eles investem em imóveis.', 'Dinheiro'],
    ['die Hypothek', 'financiamento imobiliário', 'substantivo', 'Wir haben eine Hypothek.', 'Nós temos um financiamento.', 'Dinheiro'],
    ['die Versicherung', 'seguro', 'substantivo', 'Die Autoversicherung ist teuer.', 'O seguro do carro é caro.', 'Dinheiro'],
    ['der Mindestlohn', 'salário mínimo', 'substantivo', 'Der Mindestlohn ist gestiegen.', 'O salário mínimo subiu.', 'Dinheiro'],
  ],
  B2: [
    ['der Wahlkampf', 'campanha eleitoral', 'substantivo', 'Der Wahlkampf dauerte sechs Wochen.', 'A campanha eleitoral durou seis semanas.', 'Política'],
    ['die Wählerschaft', 'eleitorado', 'substantivo', 'Die Wählerschaft ist gespalten.', 'O eleitorado está dividido.', 'Política'],
    ['die Gesetzgebung', 'legislação', 'substantivo', 'Eine neue Gesetzgebung wurde verabschiedet.', 'Uma nova legislação foi aprovada.', 'Política'],
    ['die Lobbyarbeit', 'lobby', 'substantivo', 'Lobbyarbeit hat das Gesetz geprägt.', 'O lobby moldou a lei.', 'Política'],
    ['die Korruption', 'corrupção', 'substantivo', 'Korruption untergräbt das Vertrauen.', 'A corrupção corrói a confiança.', 'Política'],
    ['das Referendum', 'referendo', 'substantivo', 'Sie haben ein Referendum angesetzt.', 'Eles convocaram um referendo.', 'Política'],
    ['die Koalition', 'coalizão', 'substantivo', 'Die Koalition ist zerbrochen.', 'A coalizão desmoronou.', 'Política'],
    ['der Stimmzettel', 'cédula de votação', 'substantivo', 'Dein Stimmzettel ist geheim.', 'Seu voto é secreto.', 'Política'],
    ['der Wahlkreis', 'distrito eleitoral', 'substantivo', 'Sie besuchte ihren Wahlkreis.', 'Ela visitou seu distrito eleitoral.', 'Política'],
    ['das Mandat', 'mandato', 'substantivo', 'Sie beanspruchen ein klares Mandat.', 'Eles alegam um mandato claro.', 'Política'],
    ['die Inflation', 'inflação', 'substantivo', 'Die Inflation hat sich letzten Monat verlangsamt.', 'A inflação desacelerou no mês passado.', 'Economia'],
    ['die Rezession', 'recessão', 'substantivo', 'Das Land geriet in eine Rezession.', 'O país entrou em recessão.', 'Economia'],
    ['die Subvention', 'subsídio', 'substantivo', 'Die Subvention wurde gestrichen.', 'O subsídio foi cortado.', 'Economia'],
    ['der Zoll', 'tarifa alfandegária', 'substantivo', 'Sie haben einen Zoll erhoben.', 'Impuseram uma tarifa.', 'Economia'],
    ['der Überschuss', 'superávit', 'substantivo', 'Der Haushalt weist einen Überschuss aus.', 'O orçamento mostra um superávit.', 'Economia'],
    ['das Defizit', 'déficit', 'substantivo', 'Das Defizit wächst weiter.', 'O déficit continua crescendo.', 'Economia'],
    ['das Angebot', 'oferta', 'substantivo', 'Das Angebot deckt die Nachfrage nicht.', 'A oferta não atende à procura.', 'Economia'],
    ['die Nachfrage', 'procura', 'substantivo', 'Die Nachfrage ist stark gefallen.', 'A procura caiu bruscamente.', 'Economia'],
    ['das Monopol', 'monopólio', 'substantivo', 'Sie haben fast ein Monopol.', 'Eles têm quase um monopólio.', 'Economia'],
    ['die Sparpolitik', 'austeridade', 'substantivo', 'Die Sparpolitik traf die öffentlichen Dienste.', 'A austeridade prejudicou os serviços públicos.', 'Economia'],
    ['das Experiment', 'experimento', 'substantivo', 'Das Experiment scheiterte zweimal.', 'O experimento falhou duas vezes.', 'Ciência'],
    ['der Beweis', 'prova / evidência', 'substantivo', 'Es gibt starke Beweise.', 'Há evidências fortes.', 'Ciência'],
    ['die Stichprobe', 'amostra', 'substantivo', 'Die Stichprobe war zu klein.', 'A amostra era pequena demais.', 'Ciência'],
    ['das Labor', 'laboratório', 'substantivo', 'Sie arbeitet in einem Labor.', 'Ela trabalha num laboratório.', 'Ciência'],
    ['das Molekül', 'molécula', 'substantivo', 'Wasser ist ein einfaches Molekül.', 'A água é uma molécula simples.', 'Ciência'],
    ['das Genom', 'genoma', 'substantivo', 'Sie haben das Genom kartiert.', 'Eles mapearam o genoma.', 'Ciência'],
    ['der Impfstoff', 'vacina', 'substantivo', 'Der Impfstoff wirkt gut.', 'A vacina funciona bem.', 'Ciência'],
    ['die Mikrobe', 'micróbio', 'substantivo', 'Diese Mikrobe ist harmlos.', 'Este micróbio é inofensivo.', 'Ciência'],
    ['die Strahlung', 'radiação', 'substantivo', 'Die Strahlungswerte sind normal.', 'Os níveis de radiação estão normais.', 'Ciência'],
    ['das Teleskop', 'telescópio', 'substantivo', 'Das Teleskop fand einen Planeten.', 'O telescópio encontrou um planeta.', 'Ciência'],
    ['die Schlagzeile', 'manchete', 'substantivo', 'Die Schlagzeile war irreführend.', 'A manchete era enganosa.', 'Mídia'],
    ['die Berichterstattung', 'cobertura jornalística', 'substantivo', 'Die Berichterstattung war einseitig.', 'A cobertura foi tendenciosa.', 'Mídia'],
    ['die Zensur', 'censura', 'substantivo', 'Die Zensur nahm letztes Jahr zu.', 'A censura aumentou no ano passado.', 'Mídia'],
    ['die Propaganda', 'propaganda ideológica', 'substantivo', 'Das ist reine Propaganda.', 'Isso é pura propaganda.', 'Mídia'],
    ['die Sendung', 'transmissão / programa', 'substantivo', 'Die Sendung erreichte Millionen.', 'A transmissão alcançou milhões.', 'Mídia'],
    ['der Journalist', 'jornalista', 'substantivo', 'Die Journalistin prüfte ihre Quellen.', 'A jornalista checou suas fontes.', 'Mídia'],
    ['der Leitartikel', 'editorial', 'substantivo', 'Der Leitartikel kritisierte den Plan.', 'O editorial criticou o plano.', 'Mídia'],
    ['die Boulevardpresse', 'imprensa sensacionalista', 'substantivo', 'Trau der Boulevardpresse nicht.', 'Não confie na imprensa sensacionalista.', 'Mídia'],
    ['das Publikum', 'público', 'substantivo', 'Das Publikum war feindselig.', 'O público estava hostil.', 'Mídia'],
    ['die Quelle', 'fonte', 'substantivo', 'Nenne deine Quelle.', 'Cite sua fonte.', 'Mídia'],
    ['die Empathie', 'empatia', 'substantivo', 'Empathie lässt sich lernen.', 'A empatia pode ser aprendida.', 'Psicologia'],
    ['die Angst', 'medo / ansiedade', 'substantivo', 'Angst stört den Schlaf.', 'A ansiedade afeta o sono.', 'Psicologia'],
    ['das Trauma', 'trauma', 'substantivo', 'Das Trauma hielt Jahre an.', 'O trauma durou anos.', 'Psicologia'],
    ['die Motivation', 'motivação', 'substantivo', 'Motivation verschwindet ohne Ergebnisse.', 'A motivação some sem resultados.', 'Psicologia'],
    ['die Wahrnehmung', 'percepção', 'substantivo', 'Wahrnehmung formt die Erinnerung.', 'A percepção molda a memória.', 'Psicologia'],
    ['das Verhalten', 'comportamento', 'substantivo', 'Sein Verhalten änderte sich plötzlich.', 'O comportamento dele mudou de repente.', 'Psicologia'],
    ['der Instinkt', 'instinto', 'substantivo', 'Vertrau hier deinem Instinkt.', 'Confie no seu instinto aqui.', 'Psicologia'],
    ['die Stimmung', 'humor / estado de espírito', 'substantivo', 'Ihre Stimmung besserte sich.', 'O humor dela melhorou.', 'Psicologia'],
    ['das Selbstwertgefühl', 'autoestima', 'substantivo', 'Geringes Selbstwertgefühl ist häufig.', 'Baixa autoestima é comum.', 'Psicologia'],
    ['der Groll', 'ressentimento', 'substantivo', 'Der Groll wuchs langsam.', 'O ressentimento cresceu devagar.', 'Psicologia'],
    ['die Klage', 'processo judicial', 'substantivo', 'Sie haben Klage eingereicht.', 'Eles entraram com um processo.', 'Direito'],
    ['das Urteil', 'veredicto', 'substantivo', 'Das Urteil überraschte alle.', 'O veredicto surpreendeu todos.', 'Direito'],
    ['die Zeugenaussage', 'depoimento', 'substantivo', 'Ihre Zeugenaussage war entscheidend.', 'O depoimento dela foi decisivo.', 'Direito'],
    ['der Zeuge', 'testemunha', 'substantivo', 'Der Zeuge änderte seine Version.', 'A testemunha mudou a versão.', 'Direito'],
    ['der Angeklagte', 'réu', 'substantivo', 'Der Angeklagte schwieg.', 'O réu permaneceu calado.', 'Direito'],
    ['der Anwalt', 'advogado', 'substantivo', 'Ruf deinen Anwalt an.', 'Ligue para seu advogado.', 'Direito'],
    ['das Geständnis', 'confissão', 'substantivo', 'Er legte ein Geständnis ab.', 'Ele fez uma confissão.', 'Direito'],
    ['die Berufung', 'recurso judicial', 'substantivo', 'Sie verloren die Berufung.', 'Eles perderam o recurso.', 'Direito'],
    ['das Sorgerecht', 'guarda (de filhos)', 'substantivo', 'Sie bekam das Sorgerecht.', 'Ela ganhou a guarda.', 'Direito'],
    ['das Gesetzbuch', 'código de leis', 'substantivo', 'Das Gesetzbuch ist veraltet.', 'O código de leis está ultrapassado.', 'Direito'],
  ],
  C1: [
    ['die Hypothese', 'hipótese', 'substantivo', 'Die Hypothese hielt nicht stand.', 'A hipótese não se sustentou.', 'Pesquisa acadêmica'],
    ['die Methodik', 'metodologia', 'substantivo', 'Beschreibe deine Methodik klar.', 'Descreva sua metodologia com clareza.', 'Pesquisa acadêmica'],
    ['die Korrelation', 'correlação', 'substantivo', 'Korrelation ist keine Kausalität.', 'Correlação não é causalidade.', 'Pesquisa acadêmica'],
    ['die Variable', 'variável', 'substantivo', 'Kontrolliere diese Variable.', 'Controle essa variável.', 'Pesquisa acadêmica'],
    ['empirisch', 'empírico', 'adjetivo', 'Wir brauchen empirische Belege.', 'Precisamos de respaldo empírico.', 'Pesquisa acadêmica'],
    ['die Fachbegutachtung', 'revisão por pares', 'substantivo', 'Die Fachbegutachtung fand den Fehler.', 'A revisão por pares pegou o erro.', 'Pesquisa acadêmica'],
    ['die Längsschnittstudie', 'estudo longitudinal', 'substantivo', 'Es war eine Längsschnittstudie.', 'Foi um estudo longitudinal.', 'Pesquisa acadêmica'],
    ['die Replikation', 'replicação', 'substantivo', 'Die Replikation scheiterte zweimal.', 'A replicação falhou duas vezes.', 'Pesquisa acadêmica'],
    ['die Schlussfolgerung', 'inferência / conclusão', 'substantivo', 'Diese Schlussfolgerung ist zu weit gefasst.', 'Essa inferência é ampla demais.', 'Pesquisa acadêmica'],
    ['das Paradigma', 'paradigma', 'substantivo', 'Das Paradigma verschob sich langsam.', 'O paradigma mudou devagar.', 'Pesquisa acadêmica'],
    ['der Interessenvertreter', 'parte interessada', 'substantivo', 'Konsultiere jeden Interessenvertreter.', 'Consulte cada parte interessada.', 'Negócios'],
    ['die Übernahme', 'aquisição', 'substantivo', 'Die Übernahme wurde im Mai abgeschlossen.', 'A aquisição foi concluída em maio.', 'Negócios'],
    ['die Fusion', 'fusão', 'substantivo', 'Die Fusion stieß auf Widerstand.', 'A fusão enfrentou resistência.', 'Negócios'],
    ['der Umsatz', 'faturamento', 'substantivo', 'Der Umsatz wuchs um zwölf Prozent.', 'O faturamento cresceu doze por cento.', 'Negócios'],
    ['die Haftung', 'responsabilidade legal', 'substantivo', 'Diese Klausel begründet Haftung.', 'Aquela cláusula gera responsabilidade legal.', 'Negócios'],
    ['das Schiedsverfahren', 'arbitragem', 'substantivo', 'Sie gingen ins Schiedsverfahren.', 'Eles foram para a arbitragem.', 'Negócios'],
    ['der Richtwert', 'referência comparativa', 'substantivo', 'Setze einen realistischen Richtwert.', 'Defina uma referência realista.', 'Negócios'],
    ['die Machbarkeit', 'viabilidade', 'substantivo', 'Prüfe zuerst die Machbarkeit.', 'Estude a viabilidade primeiro.', 'Negócios'],
    ['die Diversifizierung', 'diversificação', 'substantivo', 'Die Diversifizierung senkte das Risiko.', 'A diversificação reduziu o risco.', 'Negócios'],
    ['die Beschaffung', 'compras institucionais', 'substantivo', 'Die Beschaffung dauert Monate.', 'O processo de compras leva meses.', 'Negócios'],
    ['die Ontologie', 'ontologia', 'substantivo', 'Das ist eine Frage der Ontologie.', 'Isso é uma questão de ontologia.', 'Filosofia'],
    ['die Erkenntnistheorie', 'epistemologia', 'substantivo', 'Die Erkenntnistheorie fragt, wie wir wissen.', 'A epistemologia pergunta como sabemos.', 'Filosofia'],
    ['der Determinismus', 'determinismo', 'substantivo', 'Der Determinismus verneint den freien Willen.', 'O determinismo nega o livre-arbítrio.', 'Filosofia'],
    ['die Dialektik', 'dialética', 'substantivo', 'Er argumentierte über die Dialektik.', 'Ele argumentou pela dialética.', 'Filosofia'],
    ['die Metaphysik', 'metafísica', 'substantivo', 'Die Metaphysik entzieht sich dem Beweis.', 'A metafísica resiste à comprovação.', 'Filosofia'],
    ['existenziell', 'existencial', 'adjetivo', 'Es wurde zu einer existenziellen Bedrohung.', 'Virou uma ameaça existencial.', 'Filosofia'],
    ['die Teleologie', 'teleologia', 'substantivo', 'Die Teleologie erklärt über den Zweck.', 'A teleologia explica pela finalidade.', 'Filosofia'],
    ['der Nihilismus', 'niilismo', 'substantivo', 'Der Nihilismus verneint jeden inneren Sinn.', 'O niilismo nega sentido inerente.', 'Filosofia'],
    ['das Axiom', 'axioma', 'substantivo', 'Geh von einem gemeinsamen Axiom aus.', 'Parta de um axioma comum.', 'Filosofia'],
    ['der Syllogismus', 'silogismo', 'substantivo', 'Der Syllogismus ist ungültig.', 'O silogismo é inválido.', 'Filosofia'],
    ['die Schichtung', 'estratificação', 'substantivo', 'Die soziale Schichtung besteht fort.', 'A estratificação social persiste.', 'Sociologia'],
    ['die Assimilation', 'assimilação', 'substantivo', 'Von ihnen wurde Assimilation erwartet.', 'Esperava-se deles a assimilação.', 'Sociologia'],
    ['demografisch', 'demográfico', 'adjetivo', 'Der demografische Wandel ist deutlich.', 'A mudança demográfica é clara.', 'Sociologia'],
    ['die Verstädterung', 'urbanização', 'substantivo', 'Die Verstädterung beschleunigte sich nach 1960.', 'A urbanização acelerou depois de 1960.', 'Sociologia'],
    ['die Kohorte', 'coorte / geração', 'substantivo', 'Diese Kohorte verdient weniger.', 'Essa geração ganha menos.', 'Sociologia'],
    ['die soziale Norm', 'norma social', 'substantivo', 'Die soziale Norm änderte sich unbemerkt.', 'A norma social mudou silenciosamente.', 'Sociologia'],
    ['die Abweichung', 'desvio (social)', 'substantivo', 'Abweichung wird vom Kontext bestimmt.', 'O desvio é definido pelo contexto.', 'Sociologia'],
    ['die soziale Mobilität', 'mobilidade social', 'substantivo', 'Die soziale Mobilität stagniert.', 'A mobilidade social estagnou.', 'Sociologia'],
    ['die Verwandtschaft', 'parentesco', 'substantivo', 'Verwandtschaftsbande bleiben stark.', 'Os laços de parentesco seguem fortes.', 'Sociologia'],
    ['die Säkularisierung', 'secularização', 'substantivo', 'Die Säkularisierung ist regional verschieden.', 'A secularização varia por região.', 'Sociologia'],
    ['die Prognose', 'prognóstico', 'substantivo', 'Die Prognose ist vorsichtig gut.', 'O prognóstico é cautelosamente bom.', 'Medicina'],
    ['chronisch', 'crônico', 'adjetivo', 'Es wurde eine chronische Erkrankung.', 'Virou uma doença crônica.', 'Medicina'],
    ['gutartig', 'benigno', 'adjetivo', 'Der Knoten war gutartig.', 'O nódulo era benigno.', 'Medicina'],
    ['bösartig', 'maligno', 'adjetivo', 'Der Tumor erwies sich als bösartig.', 'O tumor se revelou maligno.', 'Medicina'],
    ['die Remission', 'remissão', 'substantivo', 'Sie ist seit einem Jahr in Remission.', 'Ela está em remissão há um ano.', 'Medicina'],
    ['die Pathologie', 'patologia', 'substantivo', 'Der Pathologiebericht ist eingetroffen.', 'O laudo de patologia chegou.', 'Medicina'],
    ['die Immunität', 'imunidade', 'substantivo', 'Die Immunität lässt mit der Zeit nach.', 'A imunidade diminui com o tempo.', 'Medicina'],
    ['die Dosierung', 'dosagem', 'substantivo', 'Passe die Dosierung sorgfältig an.', 'Ajuste a dosagem com cuidado.', 'Medicina'],
    ['der Schnitt', 'incisão', 'substantivo', 'Der Schnitt ist gut verheilt.', 'A incisão cicatrizou bem.', 'Medicina'],
    ['der Rückfall', 'recaída', 'substantivo', 'Ein Rückfall bleibt möglich.', 'Uma recaída ainda é possível.', 'Medicina'],
    ['die Rhetorik', 'retórica', 'substantivo', 'Die Rhetorik überholte die Politik.', 'A retórica passou à frente da política.', 'Retórica'],
    ['die Überzeugungskraft', 'poder de persuasão', 'substantivo', 'Überzeugungskraft schlägt Zwang.', 'A persuasão vence a coerção.', 'Retórica'],
    ['die Anekdote', 'anedota', 'substantivo', 'Eine Anekdote ist kein Datum.', 'Uma anedota não é dado.', 'Retórica'],
    ['die Analogie', 'analogia', 'substantivo', 'Die Analogie versagt hier.', 'A analogia falha aqui.', 'Retórica'],
    ['die Widerlegung', 'refutação', 'substantivo', 'Seine Widerlegung war elegant.', 'A refutação dele foi elegante.', 'Retórica'],
    ['die Konnotation', 'conotação', 'substantivo', 'Dieses Wort trägt eine Konnotation.', 'Aquela palavra carrega uma conotação.', 'Retórica'],
    ['die Erwiderung', 'réplica', 'substantivo', 'Sie bereitete eine Erwiderung vor.', 'Ela preparou uma réplica.', 'Retórica'],
    ['die Redegewandtheit', 'eloquência', 'substantivo', 'Redegewandtheit verdeckt keine schwachen Belege.', 'A eloquência não esconde evidência fraca.', 'Retórica'],
    ['der öffentliche Diskurs', 'discurso público', 'substantivo', 'Der öffentliche Diskurs ist verroht.', 'O discurso público se degradou.', 'Retórica'],
    ['die Abschweifung', 'digressão', 'substantivo', 'Verzeih die Abschweifung.', 'Perdoe a digressão.', 'Retórica'],
  ],
  C2: [
    ['elegisch', 'elegíaco', 'adjetivo', 'Der Roman hat einen elegischen Ton.', 'O romance tem um tom elegíaco.', 'Registro literário'],
    ['schwermütig', 'melancólico / sombrio', 'adjetivo', 'Er sprach mit schwermütiger Stimme.', 'Ele falou com uma voz melancólica.', 'Registro literário'],
    ['idyllisch', 'idílico', 'adjetivo', 'Das waren idyllische Tage.', 'Aqueles eram dias idílicos.', 'Registro literário'],
    ['wohlklingend', 'melodioso', 'adjetivo', 'Ihr wohlklingender Vortrag fesselte den Saal.', 'A apresentação melodiosa dela prendeu a sala.', 'Registro literário'],
    ['klagend', 'lamentoso', 'adjetivo', 'Eine klagende Melodie zog herein.', 'Uma melodia lamentosa entrou no ar.', 'Registro literário'],
    ['strahlend', 'resplandecente', 'adjetivo', 'Sie kam strahlend in Weiß.', 'Ela chegou resplandecente de branco.', 'Registro literário'],
    ['streng', 'austero / severo', 'adjetivo', 'Die Prosa ist streng und genau.', 'A prosa é austera e exata.', 'Registro literário'],
    ['träge', 'lânguido / lento', 'adjetivo', 'Der Nachmittag war träge.', 'A tarde foi lânguida.', 'Registro literário'],
    ['ätherisch', 'etéreo', 'adjetivo', 'Das Licht war fast ätherisch.', 'A luz era quase etérea.', 'Registro literário'],
    ['sonor', 'sonoro', 'adjetivo', 'Sein sonores Lachen füllte den Saal.', 'A risada sonora dele encheu o salão.', 'Registro literário'],
    ['der Rechtsstreit', 'litígio', 'substantivo', 'Der Fall endete im Rechtsstreit.', 'O caso terminou em litígio.', 'Jurídico avançado'],
    ['die Gerichtsbarkeit', 'jurisdição', 'substantivo', 'Dem Gericht fehlt die Gerichtsbarkeit.', 'O tribunal não tem jurisdição.', 'Jurídico avançado'],
    ['die Anklageschrift', 'denúncia formal', 'substantivo', 'Die Anklageschrift umfasste sechzig Seiten.', 'A denúncia tinha sessenta páginas.', 'Jurídico avançado'],
    ['die Schuldfähigkeit', 'imputabilidade', 'substantivo', 'Die Schuldfähigkeit wurde nie festgestellt.', 'A imputabilidade nunca foi estabelecida.', 'Jurídico avançado'],
    ['die Vermutung', 'presunção', 'substantivo', 'Die Unschuldsvermutung gilt.', 'A presunção de inocência vale.', 'Jurídico avançado'],
    ['entlastend', 'excludente de culpa', 'adjetivo', 'Sie hielten entlastende Beweise zurück.', 'Eles ocultaram provas excludentes de culpa.', 'Jurídico avançado'],
    ['die einstweilige Verfügung', 'liminar', 'substantivo', 'Der Richter erließ eine einstweilige Verfügung.', 'O juiz concedeu uma liminar.', 'Jurídico avançado'],
    ['die eidesstattliche Aussage', 'depoimento juramentado', 'substantivo', 'Die eidesstattliche Aussage dauerte den ganzen Tag.', 'O depoimento juramentado durou o dia todo.', 'Jurídico avançado'],
    ['urteilen', 'julgar / decidir', 'verbo', 'Ein Gremium wird über den Streit urteilen.', 'Um colegiado vai julgar a disputa.', 'Jurídico avançado'],
    ['die unerlaubte Handlung', 'ilícito civil', 'substantivo', 'Das stellt eine unerlaubte Handlung dar.', 'Isso configura um ilícito civil.', 'Jurídico avançado'],
    ['gelehrt', 'erudito', 'adjetivo', 'Die Fußnoten sind gelehrt.', 'As notas de rodapé são eruditas.', 'Termos eruditos'],
    ['glasklar', 'cristalino / límpido', 'adjetivo', 'Seine glasklare Erklärung beendete die Debatte.', 'A explicação cristalina dele encerrou o debate.', 'Termos eruditos'],
    ['abstrus', 'abstruso', 'adjetivo', 'Das Argument ist unnötig abstrus.', 'O argumento é desnecessariamente abstruso.', 'Termos eruditos'],
    ['esoterisch', 'esotérico / hermético', 'adjetivo', 'Die Theorie wurde esoterisch.', 'A teoria ficou hermética.', 'Termos eruditos'],
    ['scharfsinnig', 'sagaz', 'adjetivo', 'Es war eine scharfsinnige Wahl.', 'Foi uma escolha sagaz.', 'Termos eruditos'],
    ['hellsichtig', 'perspicaz / lúcido', 'adjetivo', 'Ein hellsichtiger Leser wird es bemerken.', 'Um leitor perspicaz vai notar.', 'Termos eruditos'],
    ['lakonisch', 'lacônico', 'adjetivo', 'Seine Antwort war lakonisch.', 'A resposta dele foi lacônica.', 'Termos eruditos'],
    ['weitschweifig', 'prolixo', 'adjetivo', 'Die Einleitung ist weitschweifig.', 'A introdução é prolixa.', 'Termos eruditos'],
    ['wortkarg', 'taciturno', 'adjetivo', 'Er blieb die ganze Zeit wortkarg.', 'Ele permaneceu taciturno o tempo todo.', 'Termos eruditos'],
    ['redselig', 'tagarela / loquaz', 'adjetivo', 'Unser redseliger Gastgeber hörte nicht auf.', 'Nosso anfitrião tagarela não parava.', 'Termos eruditos'],
    ['die Ambivalenz', 'ambivalência', 'substantivo', 'Ihre Ambivalenz war offensichtlich.', 'A ambivalência dela era evidente.', 'Nuance psicológica'],
    ['der Gewissensbiss', 'escrúpulo / remorso', 'substantivo', 'Er log ohne Gewissensbiss.', 'Ele mentiu sem nenhum remorso.', 'Nuance psicológica'],
    ['die Beklommenheit', 'apreensão / aflição', 'substantivo', 'Sie öffnete es mit Beklommenheit.', 'Ela abriu com apreensão.', 'Nuance psicológica'],
    ['die Kränkung', 'ofensa / melindre', 'substantivo', 'Er nahm die Bemerkung als Kränkung.', 'Ele tomou o comentário como uma ofensa.', 'Nuance psicológica'],
    ['die Erbitterung', 'rancor / amargura', 'substantivo', 'Sie sprach ohne Erbitterung.', 'Ela falou sem rancor.', 'Nuance psicológica'],
    ['die Reue', 'contrição / arrependimento', 'substantivo', 'Seine Reue wirkte echt.', 'A contrição dele parecia genuína.', 'Nuance psicológica'],
    ['die Hybris', 'arrogância desmedida', 'substantivo', 'Die Hybris ging dem Zusammenbruch voraus.', 'A arrogância desmedida precedeu o colapso.', 'Nuance psicológica'],
    ['die Nachsicht', 'tolerância / indulgência', 'substantivo', 'Danke für Ihre Nachsicht.', 'Obrigado pela sua tolerância.', 'Nuance psicológica'],
    ['die Großmut', 'magnanimidade', 'substantivo', 'Er zeigte unerwartete Großmut.', 'Ele mostrou magnanimidade inesperada.', 'Nuance psicológica'],
    ['die Schüchternheit', 'timidez', 'substantivo', 'Ihre Schüchternheit verbarg echtes Können.', 'A timidez dela escondia talento real.', 'Nuance psicológica'],
    ['die Folgerung', 'corolário / decorrência', 'substantivo', 'Höhere Kosten sind eine Folgerung dieser Wahl.', 'Custos maiores são um corolário dessa escolha.', 'Argumentação'],
    ['axiomatisch', 'axiomático', 'adjetivo', 'In diesem Feld ist das axiomatisch.', 'É axiomático nesta área.', 'Argumentação'],
    ['unwiderlegbar', 'incontestável', 'adjetivo', 'Die Daten sind unwiderlegbar.', 'Os dados são incontestáveis.', 'Argumentação'],
    ['schlüssig', 'conclusivo / coerente', 'adjetivo', 'Sie legte einen schlüssigen Fall vor.', 'Ela apresentou um caso conclusivo.', 'Argumentação'],
    ['extrapolieren', 'extrapolar', 'verbo', 'Extrapoliere nicht aus einem Einzelfall.', 'Não extrapole a partir de um caso.', 'Argumentação'],
    ['die Spitzfindigkeit', 'sofisma / sutileza capciosa', 'substantivo', 'Diese Verteidigung ist reine Spitzfindigkeit.', 'Essa defesa é pura capciosidade.', 'Argumentação'],
    ['unaufrichtig', 'insincero / de má-fé', 'adjetivo', 'Diese Antwort ist unaufrichtig.', 'Essa resposta é insincera.', 'Argumentação'],
    ['trügerisch', 'enganoso / especioso', 'adjetivo', 'Die Argumentation ist trügerisch.', 'O raciocínio é enganoso.', 'Argumentação'],
    ['sachdienlich', 'pertinente / útil ao caso', 'adjetivo', 'Deine Bemerkung ist sachdienlich.', 'Sua observação é pertinente.', 'Argumentação'],
    ['ipso facto', 'por isso mesmo', 'advérbio', 'Daraus folgt es nicht ipso facto.', 'Não decorre disso por isso mesmo.', 'Argumentação'],
    ['die Wirklichkeitstreue', 'verossimilhança', 'substantivo', 'Dem Film fehlt Wirklichkeitstreue.', 'O filme carece de verossimilhança.', 'Crítica e estética'],
    ['das Pastiche', 'pastiche', 'substantivo', 'Das Album ist ein bewusstes Pastiche.', 'O álbum é um pastiche consciente.', 'Crítica e estética'],
    ['der Antiklimax', 'anticlímax', 'substantivo', 'Das Ende versinkt im Antiklimax.', 'O final desaba no anticlímax.', 'Crítica e estética'],
    ['die Auflösung', 'desfecho', 'substantivo', 'Die Auflösung wirkte überstürzt.', 'O desfecho pareceu apressado.', 'Crítica e estética'],
    ['die Allegorie', 'alegoria', 'substantivo', 'Das ganze Buch ist eine Allegorie.', 'O livro inteiro é uma alegoria.', 'Crítica e estética'],
    ['das Leitmotiv', 'motivo recorrente', 'substantivo', 'Wasser ist das zentrale Leitmotiv.', 'A água é o motivo recorrente central.', 'Crítica e estética'],
    ['die Übertreibung', 'hipérbole / exagero', 'substantivo', 'Das ist Übertreibung, keine Analyse.', 'Isso é exagero, não análise.', 'Crítica e estética'],
    ['das Pathos', 'pathos / comoção', 'substantivo', 'Die Szene erreicht echtes Pathos.', 'A cena alcança comoção verdadeira.', 'Crítica e estética'],
    ['die Satire', 'sátira', 'substantivo', 'Als Satire funktioniert es besser.', 'Funciona melhor como sátira.', 'Crítica e estética'],
    ['das Gesamtwerk', 'obra completa', 'substantivo', 'Das ist klein innerhalb ihres Gesamtwerks.', 'Isto é menor dentro da obra completa dela.', 'Crítica e estética'],
  ],
};
