/** Inglês — lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const EN_THEMATIC: LatinByLevel = {
  A1: [
    ['green', 'verde', 'adjetivo', 'The grass is green.', 'A grama é verde.', 'Cores e formas'],
    ['yellow', 'amarelo', 'adjetivo', 'I like yellow flowers.', 'Gosto de flores amarelas.', 'Cores e formas'],
    ['black', 'preto', 'adjetivo', 'He wears a black coat.', 'Ele usa um casaco preto.', 'Cores e formas'],
    ['white', 'branco', 'adjetivo', 'The walls are white.', 'As paredes são brancas.', 'Cores e formas'],
    ['orange', 'laranja', 'adjetivo', 'She has an orange bag.', 'Ela tem uma bolsa laranja.', 'Cores e formas'],
    ['purple', 'roxo', 'adjetivo', 'The sky turned purple.', 'O céu ficou roxo.', 'Cores e formas'],
    ['brown', 'marrom', 'adjetivo', 'My shoes are brown.', 'Meus sapatos são marrons.', 'Cores e formas'],
    ['pink', 'rosa', 'adjetivo', 'The baby has a pink blanket.', 'O bebê tem um cobertor rosa.', 'Cores e formas'],
    ['circle', 'círculo', 'substantivo', 'Draw a circle here.', 'Desenhe um círculo aqui.', 'Cores e formas'],
    ['square', 'quadrado', 'substantivo', 'The box is a square.', 'A caixa é um quadrado.', 'Cores e formas'],
    ['shirt', 'camisa', 'substantivo', 'This shirt is clean.', 'Esta camisa está limpa.', 'Roupas'],
    ['pants', 'calça', 'substantivo', 'These pants are new.', 'Esta calça é nova.', 'Roupas'],
    ['shoes', 'sapatos', 'substantivo', 'My shoes are wet.', 'Meus sapatos estão molhados.', 'Roupas'],
    ['dress', 'vestido', 'substantivo', 'She bought a dress.', 'Ela comprou um vestido.', 'Roupas'],
    ['jacket', 'jaqueta', 'substantivo', 'Take your jacket.', 'Leve sua jaqueta.', 'Roupas'],
    ['hat', 'chapéu', 'substantivo', 'He lost his hat.', 'Ele perdeu o chapéu.', 'Roupas'],
    ['socks', 'meias', 'substantivo', 'I need clean socks.', 'Preciso de meias limpas.', 'Roupas'],
    ['coat', 'casaco', 'substantivo', 'Wear a coat today.', 'Use um casaco hoje.', 'Roupas'],
    ['skirt', 'saia', 'substantivo', 'That skirt is long.', 'Aquela saia é longa.', 'Roupas'],
    ['glasses', 'óculos', 'substantivo', 'I forgot my glasses.', 'Esqueci meus óculos.', 'Roupas'],
    ['sun', 'sol', 'substantivo', 'The sun is bright.', 'O sol está forte.', 'Clima e natureza'],
    ['rain', 'chuva', 'substantivo', 'The rain stopped.', 'A chuva parou.', 'Clima e natureza'],
    ['snow', 'neve', 'substantivo', 'The snow is deep.', 'A neve está funda.', 'Clima e natureza'],
    ['wind', 'vento', 'substantivo', 'The wind is strong.', 'O vento está forte.', 'Clima e natureza'],
    ['cloud', 'nuvem', 'substantivo', 'There is one cloud.', 'Há uma nuvem.', 'Clima e natureza'],
    ['tree', 'árvore', 'substantivo', 'The tree is old.', 'A árvore é velha.', 'Clima e natureza'],
    ['flower', 'flor', 'substantivo', 'She likes this flower.', 'Ela gosta desta flor.', 'Clima e natureza'],
    ['sky', 'céu', 'substantivo', 'The sky is clear.', 'O céu está limpo.', 'Clima e natureza'],
    ['beach', 'praia', 'substantivo', 'We go to the beach.', 'Nós vamos à praia.', 'Clima e natureza'],
    ['mountain', 'montanha', 'substantivo', 'The mountain is high.', 'A montanha é alta.', 'Clima e natureza'],
    ['head', 'cabeça', 'substantivo', 'My head hurts.', 'Minha cabeça dói.', 'Corpo'],
    ['hand', 'mão', 'substantivo', 'Give me your hand.', 'Me dê sua mão.', 'Corpo'],
    ['foot', 'pé', 'substantivo', 'My foot is cold.', 'Meu pé está frio.', 'Corpo'],
    ['eye', 'olho', 'substantivo', 'She has one green eye.', 'Ela tem um olho verde.', 'Corpo'],
    ['ear', 'orelha / ouvido', 'substantivo', 'My ear hurts.', 'Meu ouvido dói.', 'Corpo'],
    ['mouth', 'boca', 'substantivo', 'Open your mouth.', 'Abra a boca.', 'Corpo'],
    ['nose', 'nariz', 'substantivo', 'His nose is red.', 'O nariz dele está vermelho.', 'Corpo'],
    ['hair', 'cabelo', 'substantivo', 'Her hair is long.', 'O cabelo dela é longo.', 'Corpo'],
    ['arm', 'braço', 'substantivo', 'He broke his arm.', 'Ele quebrou o braço.', 'Corpo'],
    ['leg', 'perna', 'substantivo', 'My leg is tired.', 'Minha perna está cansada.', 'Corpo'],
    ['bread', 'pão', 'substantivo', 'I eat bread every day.', 'Eu como pão todo dia.', 'Comida e bebida'],
    ['milk', 'leite', 'substantivo', 'The milk is cold.', 'O leite está frio.', 'Comida e bebida'],
    ['coffee', 'café', 'substantivo', 'She drinks coffee.', 'Ela bebe café.', 'Comida e bebida'],
    ['rice', 'arroz', 'substantivo', 'We eat rice at lunch.', 'Comemos arroz no almoço.', 'Comida e bebida'],
    ['meat', 'carne', 'substantivo', 'He does not eat meat.', 'Ele não come carne.', 'Comida e bebida'],
    ['fruit', 'fruta', 'substantivo', 'Buy some fruit.', 'Compre umas frutas.', 'Comida e bebida'],
    ['egg', 'ovo', 'substantivo', 'I want one egg.', 'Quero um ovo.', 'Comida e bebida'],
    ['cheese', 'queijo', 'substantivo', 'This cheese is good.', 'Este queijo é bom.', 'Comida e bebida'],
    ['sugar', 'açúcar', 'substantivo', 'No sugar, please.', 'Sem açúcar, por favor.', 'Comida e bebida'],
    ['salt', 'sal', 'substantivo', 'Pass me the salt.', 'Me passe o sal.', 'Comida e bebida'],
    ['morning', 'manhã', 'substantivo', 'I work in the morning.', 'Eu trabalho de manhã.', 'Tempo e rotina'],
    ['afternoon', 'tarde', 'substantivo', 'See you this afternoon.', 'Até a tarde.', 'Tempo e rotina'],
    ['evening', 'fim de tarde / noite', 'substantivo', 'We eat in the evening.', 'Nós comemos à noite.', 'Tempo e rotina'],
    ['night', 'noite', 'substantivo', 'The night is quiet.', 'A noite está calma.', 'Tempo e rotina'],
    ['week', 'semana', 'substantivo', 'The week is long.', 'A semana é longa.', 'Tempo e rotina'],
    ['month', 'mês', 'substantivo', 'This month is busy.', 'Este mês está cheio.', 'Tempo e rotina'],
    ['today', 'hoje', 'advérbio', 'I am tired today.', 'Estou cansado hoje.', 'Tempo e rotina'],
    ['tomorrow', 'amanhã', 'advérbio', 'We travel tomorrow.', 'Nós viajamos amanhã.', 'Tempo e rotina'],
    ['yesterday', 'ontem', 'advérbio', 'It rained yesterday.', 'Choveu ontem.', 'Tempo e rotina'],
    ['hour', 'hora', 'substantivo', 'Wait one hour.', 'Espere uma hora.', 'Tempo e rotina'],
  ],
  A2: [
    ['flight', 'voo', 'substantivo', 'Our flight leaves at six.', 'Nosso voo sai às seis.', 'Viagem'],
    ['passport', 'passaporte', 'substantivo', 'Show me your passport.', 'Me mostre seu passaporte.', 'Viagem'],
    ['luggage', 'bagagem', 'substantivo', 'My luggage is heavy.', 'Minha bagagem está pesada.', 'Viagem'],
    ['ticket', 'passagem / bilhete', 'substantivo', 'I bought the ticket online.', 'Comprei a passagem pela internet.', 'Viagem'],
    ['delay', 'atraso', 'substantivo', 'There was a long delay.', 'Houve um atraso longo.', 'Viagem'],
    ['airport', 'aeroporto', 'substantivo', 'The airport is far.', 'O aeroporto é longe.', 'Viagem'],
    ['suitcase', 'mala', 'substantivo', 'Pack your suitcase tonight.', 'Faça sua mala hoje à noite.', 'Viagem'],
    ['departure', 'partida / saída', 'substantivo', 'Check the departure time.', 'Confira o horário de partida.', 'Viagem'],
    ['arrival', 'chegada', 'substantivo', 'The arrival was smooth.', 'A chegada foi tranquila.', 'Viagem'],
    ['boarding pass', 'cartão de embarque', 'substantivo', 'Keep your boarding pass.', 'Guarde seu cartão de embarque.', 'Viagem'],
    ['menu', 'cardápio', 'substantivo', 'Can I see the menu?', 'Posso ver o cardápio?', 'Restaurante'],
    ['waiter', 'garçom', 'substantivo', 'The waiter is coming.', 'O garçom está vindo.', 'Restaurante'],
    ['tip', 'gorjeta', 'substantivo', 'We left a good tip.', 'Deixamos uma boa gorjeta.', 'Restaurante'],
    ['dessert', 'sobremesa', 'substantivo', 'I want dessert.', 'Quero sobremesa.', 'Restaurante'],
    ['starter', 'entrada (prato)', 'substantivo', 'The starter was small.', 'A entrada era pequena.', 'Restaurante'],
    ['reservation', 'reserva', 'substantivo', 'I made a reservation.', 'Fiz uma reserva.', 'Restaurante'],
    ['napkin', 'guardanapo', 'substantivo', 'Pass me a napkin.', 'Me passe um guardanapo.', 'Restaurante'],
    ['tray', 'bandeja', 'substantivo', 'Put it on the tray.', 'Coloque na bandeja.', 'Restaurante'],
    ['taste', 'sabor / provar', 'substantivo', 'The taste is strange.', 'O sabor está estranho.', 'Restaurante'],
    ['spicy', 'picante', 'adjetivo', 'This food is spicy.', 'Esta comida é picante.', 'Restaurante'],
    ['cash', 'dinheiro (em espécie)', 'substantivo', 'I only have cash.', 'Só tenho dinheiro em espécie.', 'Compras'],
    ['change', 'troco', 'substantivo', 'Keep the change.', 'Fique com o troco.', 'Compras'],
    ['size', 'tamanho', 'substantivo', 'Do you have a larger size?', 'Tem um tamanho maior?', 'Compras'],
    ['bargain', 'pechincha', 'substantivo', 'That coat was a bargain.', 'Aquele casaco foi uma pechincha.', 'Compras'],
    ['cashier', 'caixa (pessoa)', 'substantivo', 'Ask the cashier.', 'Pergunte ao caixa.', 'Compras'],
    ['aisle', 'corredor (de loja)', 'substantivo', 'The milk is in aisle three.', 'O leite está no corredor três.', 'Compras'],
    ['shelf', 'prateleira', 'substantivo', 'The shelf is empty.', 'A prateleira está vazia.', 'Compras'],
    ['sale', 'liquidação', 'substantivo', 'The shoes are on sale.', 'Os sapatos estão em liquidação.', 'Compras'],
    ['wallet', 'carteira', 'substantivo', 'I left my wallet at home.', 'Deixei minha carteira em casa.', 'Compras'],
    ['brand', 'marca', 'substantivo', 'I trust this brand.', 'Confio nesta marca.', 'Compras'],
    ['cough', 'tosse', 'substantivo', 'She has a bad cough.', 'Ela está com uma tosse feia.', 'Saúde'],
    ['headache', 'dor de cabeça', 'substantivo', 'I have a headache.', 'Estou com dor de cabeça.', 'Saúde'],
    ['pill', 'comprimido', 'substantivo', 'Take one pill a day.', 'Tome um comprimido por dia.', 'Saúde'],
    ['nurse', 'enfermeiro', 'substantivo', 'The nurse was kind.', 'O enfermeiro foi gentil.', 'Saúde'],
    ['injury', 'lesão', 'substantivo', 'The injury was serious.', 'A lesão foi séria.', 'Saúde'],
    ['rest', 'descanso', 'substantivo', 'You need rest.', 'Você precisa de descanso.', 'Saúde'],
    ['bandage', 'curativo / bandagem', 'substantivo', 'Put a bandage on it.', 'Coloque um curativo nisso.', 'Saúde'],
    ['dizzy', 'tonto', 'adjetivo', 'I feel dizzy.', 'Estou me sentindo tonto.', 'Saúde'],
    ['clinic', 'clínica', 'substantivo', 'The clinic opens at eight.', 'A clínica abre às oito.', 'Saúde'],
    ['ache', 'dor persistente', 'substantivo', 'I have an ache in my back.', 'Tenho uma dor nas costas.', 'Saúde'],
    ['bridge', 'ponte', 'substantivo', 'Cross the bridge.', 'Atravesse a ponte.', 'Cidade'],
    ['plaza', 'praça', 'substantivo', 'We met in the plaza.', 'Nos encontramos na praça.', 'Cidade'],
    ['corner', 'esquina', 'substantivo', 'Turn at the corner.', 'Vire na esquina.', 'Cidade'],
    ['traffic', 'trânsito', 'substantivo', 'The traffic is terrible.', 'O trânsito está terrível.', 'Cidade'],
    ['subway', 'metrô', 'substantivo', 'Take the subway.', 'Pegue o metrô.', 'Cidade'],
    ['stop', 'parada (ônibus)', 'substantivo', 'Get off at the next stop.', 'Desça na próxima parada.', 'Cidade'],
    ['map', 'mapa', 'substantivo', 'Look at the map.', 'Olhe o mapa.', 'Cidade'],
    ['path', 'caminho / trilha', 'substantivo', 'Follow this path.', 'Siga este caminho.', 'Cidade'],
    ['gate', 'portão', 'substantivo', 'The gate is locked.', 'O portão está trancado.', 'Cidade'],
    ['crossing', 'faixa de pedestres', 'substantivo', 'Use the crossing.', 'Use a faixa de pedestres.', 'Cidade'],
    ['laundry', 'roupa suja / lavanderia', 'substantivo', 'I do the laundry on Sunday.', 'Eu lavo a roupa no domingo.', 'Casa e tarefas'],
    ['dishes', 'louça', 'substantivo', 'He washes the dishes.', 'Ele lava a louça.', 'Casa e tarefas'],
    ['broom', 'vassoura', 'substantivo', 'Where is the broom?', 'Onde está a vassoura?', 'Casa e tarefas'],
    ['trash', 'lixo', 'substantivo', 'Take out the trash.', 'Leve o lixo para fora.', 'Casa e tarefas'],
    ['towel', 'toalha', 'substantivo', 'The towel is wet.', 'A toalha está molhada.', 'Casa e tarefas'],
    ['blanket', 'cobertor', 'substantivo', 'I need another blanket.', 'Preciso de outro cobertor.', 'Casa e tarefas'],
    ['drawer', 'gaveta', 'substantivo', 'It is in the drawer.', 'Está na gaveta.', 'Casa e tarefas'],
    ['closet', 'armário', 'substantivo', 'Hang it in the closet.', 'Pendure no armário.', 'Casa e tarefas'],
    ['sink', 'pia', 'substantivo', 'The sink is blocked.', 'A pia está entupida.', 'Casa e tarefas'],
    ['mirror', 'espelho', 'substantivo', 'Look in the mirror.', 'Olhe no espelho.', 'Casa e tarefas'],
  ],
  B1: [
    ['interview', 'entrevista', 'substantivo', 'The interview went well.', 'A entrevista correu bem.', 'Trabalho'],
    ['résumé', 'currículo', 'substantivo', 'Send me your résumé.', 'Me mande seu currículo.', 'Trabalho'],
    ['shift', 'turno', 'substantivo', 'I work the night shift.', 'Eu trabalho no turno da noite.', 'Trabalho'],
    ['overtime', 'hora extra', 'substantivo', 'She did overtime again.', 'Ela fez hora extra de novo.', 'Trabalho'],
    ['internship', 'estágio', 'substantivo', 'He got an internship.', 'Ele conseguiu um estágio.', 'Trabalho'],
    ['supervisor', 'supervisor', 'substantivo', 'Talk to your supervisor.', 'Fale com seu supervisor.', 'Trabalho'],
    ['task', 'tarefa', 'substantivo', 'This task takes two hours.', 'Esta tarefa leva duas horas.', 'Trabalho'],
    ['meeting', 'reunião', 'substantivo', 'The meeting was cancelled.', 'A reunião foi cancelada.', 'Trabalho'],
    ['staff', 'equipe / funcionários', 'substantivo', 'The staff is friendly.', 'A equipe é simpática.', 'Trabalho'],
    ['contract', 'contrato', 'substantivo', 'Read the contract first.', 'Leia o contrato primeiro.', 'Trabalho'],
    ['update', 'atualização', 'substantivo', 'Install the update.', 'Instale a atualização.', 'Tecnologia'],
    ['password', 'senha', 'substantivo', 'I forgot my password.', 'Esqueci minha senha.', 'Tecnologia'],
    ['backup', 'cópia de segurança', 'substantivo', 'Make a backup first.', 'Faça uma cópia de segurança antes.', 'Tecnologia'],
    ['device', 'dispositivo', 'substantivo', 'This device is fast.', 'Este dispositivo é rápido.', 'Tecnologia'],
    ['screen', 'tela', 'substantivo', 'The screen is broken.', 'A tela está quebrada.', 'Tecnologia'],
    ['download', 'baixar', 'verbo', 'Download the file now.', 'Baixe o arquivo agora.', 'Tecnologia'],
    ['network', 'rede', 'substantivo', 'The network is down.', 'A rede está fora do ar.', 'Tecnologia'],
    ['browser', 'navegador', 'substantivo', 'Open a new browser tab.', 'Abra uma nova aba no navegador.', 'Tecnologia'],
    ['folder', 'pasta', 'substantivo', 'Save it in this folder.', 'Salve nesta pasta.', 'Tecnologia'],
    ['crash', 'travar / falhar', 'verbo', 'The app crashed again.', 'O aplicativo travou de novo.', 'Tecnologia'],
    ['recycle', 'reciclar', 'verbo', 'We recycle plastic here.', 'Nós reciclamos plástico aqui.', 'Meio ambiente'],
    ['pollution', 'poluição', 'substantivo', 'Pollution got worse.', 'A poluição piorou.', 'Meio ambiente'],
    ['waste', 'desperdício / resíduo', 'substantivo', 'Food waste is a problem.', 'O desperdício de comida é um problema.', 'Meio ambiente'],
    ['climate', 'clima', 'substantivo', 'The climate is changing.', 'O clima está mudando.', 'Meio ambiente'],
    ['energy', 'energia', 'substantivo', 'Solar energy is cheaper now.', 'A energia solar está mais barata agora.', 'Meio ambiente'],
    ['forest', 'floresta', 'substantivo', 'The forest is protected.', 'A floresta é protegida.', 'Meio ambiente'],
    ['species', 'espécie', 'substantivo', 'This species is rare.', 'Esta espécie é rara.', 'Meio ambiente'],
    ['drought', 'seca', 'substantivo', 'The drought lasted months.', 'A seca durou meses.', 'Meio ambiente'],
    ['flood', 'enchente', 'substantivo', 'The flood damaged the road.', 'A enchente danificou a estrada.', 'Meio ambiente'],
    ['litter', 'lixo (jogado na rua)', 'substantivo', 'Do not drop litter.', 'Não jogue lixo no chão.', 'Meio ambiente'],
    ['referee', 'árbitro', 'substantivo', 'The referee stopped the game.', 'O árbitro parou o jogo.', 'Esportes'],
    ['tournament', 'torneio', 'substantivo', 'She won the tournament.', 'Ela ganhou o torneio.', 'Esportes'],
    ['opponent', 'adversário', 'substantivo', 'His opponent was faster.', 'O adversário dele era mais rápido.', 'Esportes'],
    ['teammate', 'companheiro de equipe', 'substantivo', 'My teammate scored.', 'Meu companheiro de equipe marcou.', 'Esportes'],
    ['coach', 'treinador', 'substantivo', 'The coach was angry.', 'O treinador estava bravo.', 'Esportes'],
    ['score', 'placar', 'substantivo', 'What is the score?', 'Qual é o placar?', 'Esportes'],
    ['match', 'partida', 'substantivo', 'The match starts at eight.', 'A partida começa às oito.', 'Esportes'],
    ['training', 'treino', 'substantivo', 'Training is every morning.', 'O treino é toda manhã.', 'Esportes'],
    ['stamina', 'resistência física', 'substantivo', 'He has great stamina.', 'Ele tem muita resistência.', 'Esportes'],
    ['championship', 'campeonato', 'substantivo', 'They lost the championship.', 'Eles perderam o campeonato.', 'Esportes'],
    ['argue', 'discutir', 'verbo', 'They argue about money.', 'Eles discutem por dinheiro.', 'Relacionamentos'],
    ['apologize', 'pedir desculpas', 'verbo', 'He apologized quickly.', 'Ele pediu desculpas rápido.', 'Relacionamentos'],
    ['trust', 'confiança / confiar', 'substantivo', 'Trust takes time.', 'Confiança leva tempo.', 'Relacionamentos'],
    ['jealous', 'ciumento', 'adjetivo', 'She gets jealous easily.', 'Ela fica com ciúmes fácil.', 'Relacionamentos'],
    ['loyal', 'leal', 'adjetivo', 'He is a loyal friend.', 'Ele é um amigo leal.', 'Relacionamentos'],
    ['gossip', 'fofoca', 'substantivo', 'I hate office gossip.', 'Odeio fofoca de escritório.', 'Relacionamentos'],
    ['advice', 'conselho', 'substantivo', 'That was good advice.', 'Aquilo foi um bom conselho.', 'Relacionamentos'],
    ['favor', 'favor', 'substantivo', 'Can I ask a favor?', 'Posso pedir um favor?', 'Relacionamentos'],
    ['quarrel', 'briga / desentendimento', 'substantivo', 'They had a silly quarrel.', 'Eles tiveram uma briga boba.', 'Relacionamentos'],
    ['compromise', 'acordo mútuo', 'substantivo', 'We reached a compromise.', 'Chegamos a um acordo.', 'Relacionamentos'],
    ['budget', 'orçamento', 'substantivo', 'Stick to the budget.', 'Siga o orçamento.', 'Dinheiro'],
    ['savings', 'poupança', 'substantivo', 'She used her savings.', 'Ela usou a poupança.', 'Dinheiro'],
    ['loan', 'empréstimo', 'substantivo', 'He took out a loan.', 'Ele fez um empréstimo.', 'Dinheiro'],
    ['debt', 'dívida', 'substantivo', 'They paid off the debt.', 'Eles quitaram a dívida.', 'Dinheiro'],
    ['expense', 'despesa', 'substantivo', 'Rent is my biggest expense.', 'O aluguel é minha maior despesa.', 'Dinheiro'],
    ['interest', 'juros', 'substantivo', 'The interest is too high.', 'Os juros estão altos demais.', 'Dinheiro'],
    ['invest', 'investir', 'verbo', 'They invest in property.', 'Eles investem em imóveis.', 'Dinheiro'],
    ['mortgage', 'financiamento imobiliário', 'substantivo', 'We have a mortgage.', 'Nós temos um financiamento.', 'Dinheiro'],
    ['insurance', 'seguro', 'substantivo', 'Car insurance is expensive.', 'O seguro do carro é caro.', 'Dinheiro'],
    ['wage', 'salário por hora', 'substantivo', 'The minimum wage rose.', 'O salário mínimo subiu.', 'Dinheiro'],
  ],
  B2: [
    ['campaign', 'campanha', 'substantivo', 'The campaign lasted six weeks.', 'A campanha durou seis semanas.', 'Política'],
    ['electorate', 'eleitorado', 'substantivo', 'The electorate is divided.', 'O eleitorado está dividido.', 'Política'],
    ['legislation', 'legislação', 'substantivo', 'New legislation passed.', 'Uma nova legislação foi aprovada.', 'Política'],
    ['lobbying', 'lobby', 'substantivo', 'Lobbying shaped the bill.', 'O lobby moldou o projeto de lei.', 'Política'],
    ['corruption', 'corrupção', 'substantivo', 'Corruption undermines trust.', 'A corrupção corrói a confiança.', 'Política'],
    ['referendum', 'referendo', 'substantivo', 'They called a referendum.', 'Eles convocaram um referendo.', 'Política'],
    ['coalition', 'coalizão', 'substantivo', 'The coalition collapsed.', 'A coalizão desmoronou.', 'Política'],
    ['ballot', 'cédula / votação', 'substantivo', 'Your ballot is secret.', 'Seu voto é secreto.', 'Política'],
    ['constituency', 'base eleitoral / distrito', 'substantivo', 'She visited her constituency.', 'Ela visitou sua base eleitoral.', 'Política'],
    ['mandate', 'mandato', 'substantivo', 'They claim a clear mandate.', 'Eles alegam um mandato claro.', 'Política'],
    ['inflation', 'inflação', 'substantivo', 'Inflation slowed last month.', 'A inflação desacelerou no mês passado.', 'Economia'],
    ['recession', 'recessão', 'substantivo', 'The country entered a recession.', 'O país entrou em recessão.', 'Economia'],
    ['subsidy', 'subsídio', 'substantivo', 'The subsidy was cut.', 'O subsídio foi cortado.', 'Economia'],
    ['tariff', 'tarifa alfandegária', 'substantivo', 'They imposed a tariff.', 'Impuseram uma tarifa.', 'Economia'],
    ['surplus', 'superávit', 'substantivo', 'The budget shows a surplus.', 'O orçamento mostra um superávit.', 'Economia'],
    ['deficit', 'déficit', 'substantivo', 'The deficit keeps growing.', 'O déficit continua crescendo.', 'Economia'],
    ['supply', 'oferta', 'substantivo', 'Supply cannot meet demand.', 'A oferta não atende à procura.', 'Economia'],
    ['demand', 'procura / demanda', 'substantivo', 'Demand fell sharply.', 'A procura caiu bruscamente.', 'Economia'],
    ['monopoly', 'monopólio', 'substantivo', 'They hold a near monopoly.', 'Eles têm quase um monopólio.', 'Economia'],
    ['austerity', 'austeridade', 'substantivo', 'Austerity hurt public services.', 'A austeridade prejudicou os serviços públicos.', 'Economia'],
    ['experiment', 'experimento', 'substantivo', 'The experiment failed twice.', 'O experimento falhou duas vezes.', 'Ciência'],
    ['evidence', 'evidência', 'substantivo', 'There is strong evidence.', 'Há evidências fortes.', 'Ciência'],
    ['sample', 'amostra', 'substantivo', 'The sample was too small.', 'A amostra era pequena demais.', 'Ciência'],
    ['laboratory', 'laboratório', 'substantivo', 'She works in a laboratory.', 'Ela trabalha num laboratório.', 'Ciência'],
    ['molecule', 'molécula', 'substantivo', 'Water is a simple molecule.', 'A água é uma molécula simples.', 'Ciência'],
    ['genome', 'genoma', 'substantivo', 'They mapped the genome.', 'Eles mapearam o genoma.', 'Ciência'],
    ['vaccine', 'vacina', 'substantivo', 'The vaccine works well.', 'A vacina funciona bem.', 'Ciência'],
    ['microbe', 'micróbio', 'substantivo', 'This microbe is harmless.', 'Este micróbio é inofensivo.', 'Ciência'],
    ['radiation', 'radiação', 'substantivo', 'Radiation levels are normal.', 'Os níveis de radiação estão normais.', 'Ciência'],
    ['telescope', 'telescópio', 'substantivo', 'The telescope found a planet.', 'O telescópio encontrou um planeta.', 'Ciência'],
    ['headline', 'manchete', 'substantivo', 'The headline was misleading.', 'A manchete era enganosa.', 'Mídia'],
    ['coverage', 'cobertura jornalística', 'substantivo', 'The coverage was biased.', 'A cobertura foi tendenciosa.', 'Mídia'],
    ['censorship', 'censura', 'substantivo', 'Censorship increased last year.', 'A censura aumentou no ano passado.', 'Mídia'],
    ['propaganda', 'propaganda ideológica', 'substantivo', 'This is pure propaganda.', 'Isso é pura propaganda.', 'Mídia'],
    ['broadcast', 'transmissão', 'substantivo', 'The broadcast reached millions.', 'A transmissão alcançou milhões.', 'Mídia'],
    ['journalist', 'jornalista', 'substantivo', 'The journalist checked her sources.', 'A jornalista checou suas fontes.', 'Mídia'],
    ['editorial', 'editorial', 'substantivo', 'The editorial criticised the plan.', 'O editorial criticou o plano.', 'Mídia'],
    ['tabloid', 'tabloide / imprensa sensacionalista', 'substantivo', 'Do not trust that tabloid.', 'Não confie naquele tabloide.', 'Mídia'],
    ['audience', 'público', 'substantivo', 'The audience was hostile.', 'O público estava hostil.', 'Mídia'],
    ['source', 'fonte', 'substantivo', 'Name your source.', 'Cite sua fonte.', 'Mídia'],
    ['empathy', 'empatia', 'substantivo', 'Empathy can be taught.', 'A empatia pode ser ensinada.', 'Psicologia'],
    ['anxiety', 'ansiedade', 'substantivo', 'Anxiety affects sleep.', 'A ansiedade afeta o sono.', 'Psicologia'],
    ['trauma', 'trauma', 'substantivo', 'The trauma lasted years.', 'O trauma durou anos.', 'Psicologia'],
    ['motivation', 'motivação', 'substantivo', 'Motivation fades without results.', 'A motivação some sem resultados.', 'Psicologia'],
    ['perception', 'percepção', 'substantivo', 'Perception shapes memory.', 'A percepção molda a memória.', 'Psicologia'],
    ['behaviour', 'comportamento', 'substantivo', 'His behaviour changed suddenly.', 'O comportamento dele mudou de repente.', 'Psicologia'],
    ['instinct', 'instinto', 'substantivo', 'Trust your instinct here.', 'Confie no seu instinto aqui.', 'Psicologia'],
    ['mood', 'humor / estado de espírito', 'substantivo', 'Her mood improved.', 'O humor dela melhorou.', 'Psicologia'],
    ['self-esteem', 'autoestima', 'substantivo', 'Low self-esteem is common.', 'Baixa autoestima é comum.', 'Psicologia'],
    ['resentment', 'ressentimento', 'substantivo', 'Resentment built up slowly.', 'O ressentimento cresceu devagar.', 'Psicologia'],
    ['lawsuit', 'processo judicial', 'substantivo', 'They filed a lawsuit.', 'Eles entraram com um processo.', 'Direito'],
    ['verdict', 'veredicto', 'substantivo', 'The verdict surprised everyone.', 'O veredicto surpreendeu todos.', 'Direito'],
    ['testimony', 'depoimento', 'substantivo', 'Her testimony was decisive.', 'O depoimento dela foi decisivo.', 'Direito'],
    ['witness', 'testemunha', 'substantivo', 'The witness changed his story.', 'A testemunha mudou a versão.', 'Direito'],
    ['defendant', 'réu', 'substantivo', 'The defendant stayed silent.', 'O réu permaneceu calado.', 'Direito'],
    ['attorney', 'advogado', 'substantivo', 'Call your attorney.', 'Ligue para seu advogado.', 'Direito'],
    ['plea', 'alegação / confissão', 'substantivo', 'He entered a guilty plea.', 'Ele se declarou culpado.', 'Direito'],
    ['appeal', 'recurso', 'substantivo', 'They lost the appeal.', 'Eles perderam o recurso.', 'Direito'],
    ['custody', 'custódia', 'substantivo', 'She won custody.', 'Ela ganhou a custódia.', 'Direito'],
    ['statute', 'estatuto / lei escrita', 'substantivo', 'The statute is outdated.', 'O estatuto está ultrapassado.', 'Direito'],
  ],
  C1: [
    ['hypothesis', 'hipótese', 'substantivo', 'The hypothesis was not supported.', 'A hipótese não se sustentou.', 'Pesquisa acadêmica'],
    ['methodology', 'metodologia', 'substantivo', 'Describe your methodology clearly.', 'Descreva sua metodologia com clareza.', 'Pesquisa acadêmica'],
    ['correlation', 'correlação', 'substantivo', 'Correlation is not causation.', 'Correlação não é causalidade.', 'Pesquisa acadêmica'],
    ['variable', 'variável', 'substantivo', 'Control for that variable.', 'Controle essa variável.', 'Pesquisa acadêmica'],
    ['empirical', 'empírico', 'adjetivo', 'We need empirical support.', 'Precisamos de respaldo empírico.', 'Pesquisa acadêmica'],
    ['peer review', 'revisão por pares', 'substantivo', 'Peer review caught the error.', 'A revisão por pares pegou o erro.', 'Pesquisa acadêmica'],
    ['longitudinal', 'longitudinal', 'adjetivo', 'It was a longitudinal study.', 'Foi um estudo longitudinal.', 'Pesquisa acadêmica'],
    ['replication', 'replicação', 'substantivo', 'Replication failed twice.', 'A replicação falhou duas vezes.', 'Pesquisa acadêmica'],
    ['inference', 'inferência', 'substantivo', 'That inference is too broad.', 'Essa inferência é ampla demais.', 'Pesquisa acadêmica'],
    ['paradigm', 'paradigma', 'substantivo', 'The paradigm shifted slowly.', 'O paradigma mudou devagar.', 'Pesquisa acadêmica'],
    ['stakeholder', 'parte interessada', 'substantivo', 'Consult every stakeholder.', 'Consulte cada parte interessada.', 'Negócios'],
    ['acquisition', 'aquisição', 'substantivo', 'The acquisition closed in May.', 'A aquisição foi concluída em maio.', 'Negócios'],
    ['merger', 'fusão', 'substantivo', 'The merger faced resistance.', 'A fusão enfrentou resistência.', 'Negócios'],
    ['revenue', 'receita', 'substantivo', 'Revenue grew twelve percent.', 'A receita cresceu doze por cento.', 'Negócios'],
    ['liability', 'passivo / responsabilidade legal', 'substantivo', 'That clause creates liability.', 'Aquela cláusula cria responsabilidade legal.', 'Negócios'],
    ['arbitration', 'arbitragem', 'substantivo', 'They went to arbitration.', 'Eles foram para a arbitragem.', 'Negócios'],
    ['benchmark', 'referência comparativa', 'substantivo', 'Set a realistic benchmark.', 'Defina uma referência realista.', 'Negócios'],
    ['feasibility', 'viabilidade', 'substantivo', 'Study the feasibility first.', 'Estude a viabilidade primeiro.', 'Negócios'],
    ['diversification', 'diversificação', 'substantivo', 'Diversification reduced the risk.', 'A diversificação reduziu o risco.', 'Negócios'],
    ['procurement', 'aquisição institucional / compras', 'substantivo', 'Procurement takes months.', 'O processo de compras leva meses.', 'Negócios'],
    ['ontology', 'ontologia', 'substantivo', 'That is a question of ontology.', 'Isso é uma questão de ontologia.', 'Filosofia'],
    ['epistemology', 'epistemologia', 'substantivo', 'Epistemology asks how we know.', 'A epistemologia pergunta como sabemos.', 'Filosofia'],
    ['determinism', 'determinismo', 'substantivo', 'Determinism denies free will.', 'O determinismo nega o livre-arbítrio.', 'Filosofia'],
    ['dialectic', 'dialética', 'substantivo', 'He argued through dialectic.', 'Ele argumentou pela dialética.', 'Filosofia'],
    ['metaphysics', 'metafísica', 'substantivo', 'Metaphysics resists proof.', 'A metafísica resiste à comprovação.', 'Filosofia'],
    ['existential', 'existencial', 'adjetivo', 'It became an existential threat.', 'Virou uma ameaça existencial.', 'Filosofia'],
    ['teleology', 'teleologia', 'substantivo', 'Teleology explains by purpose.', 'A teleologia explica pela finalidade.', 'Filosofia'],
    ['nihilism', 'niilismo', 'substantivo', 'Nihilism denies inherent meaning.', 'O niilismo nega sentido inerente.', 'Filosofia'],
    ['axiom', 'axioma', 'substantivo', 'Start from a shared axiom.', 'Parta de um axioma comum.', 'Filosofia'],
    ['syllogism', 'silogismo', 'substantivo', 'The syllogism is invalid.', 'O silogismo é inválido.', 'Filosofia'],
    ['stratification', 'estratificação', 'substantivo', 'Social stratification persists.', 'A estratificação social persiste.', 'Sociologia'],
    ['assimilation', 'assimilação', 'substantivo', 'Assimilation was expected of them.', 'Esperava-se deles a assimilação.', 'Sociologia'],
    ['demographic', 'demográfico', 'adjetivo', 'The demographic shift is clear.', 'A mudança demográfica é clara.', 'Sociologia'],
    ['urbanization', 'urbanização', 'substantivo', 'Urbanization accelerated after 1960.', 'A urbanização acelerou depois de 1960.', 'Sociologia'],
    ['cohort', 'coorte / geração', 'substantivo', 'That cohort earns less.', 'Essa geração ganha menos.', 'Sociologia'],
    ['norm', 'norma social', 'substantivo', 'The norm changed quietly.', 'A norma mudou silenciosamente.', 'Sociologia'],
    ['deviance', 'desvio (social)', 'substantivo', 'Deviance is defined by context.', 'O desvio é definido pelo contexto.', 'Sociologia'],
    ['mobility', 'mobilidade social', 'substantivo', 'Social mobility has stalled.', 'A mobilidade social estagnou.', 'Sociologia'],
    ['kinship', 'parentesco', 'substantivo', 'Kinship ties remain strong.', 'Os laços de parentesco seguem fortes.', 'Sociologia'],
    ['secularization', 'secularização', 'substantivo', 'Secularization varies by region.', 'A secularização varia por região.', 'Sociologia'],
    ['prognosis', 'prognóstico', 'substantivo', 'The prognosis is cautiously good.', 'O prognóstico é cautelosamente bom.', 'Medicina'],
    ['chronic', 'crônico', 'adjetivo', 'It became a chronic condition.', 'Virou uma condição crônica.', 'Medicina'],
    ['benign', 'benigno', 'adjetivo', 'The growth was benign.', 'O nódulo era benigno.', 'Medicina'],
    ['malignant', 'maligno', 'adjetivo', 'The tumour proved malignant.', 'O tumor se revelou maligno.', 'Medicina'],
    ['remission', 'remissão', 'substantivo', 'She has been in remission for a year.', 'Ela está em remissão há um ano.', 'Medicina'],
    ['pathology', 'patologia', 'substantivo', 'The pathology report arrived.', 'O laudo de patologia chegou.', 'Medicina'],
    ['immunity', 'imunidade', 'substantivo', 'Immunity fades over time.', 'A imunidade diminui com o tempo.', 'Medicina'],
    ['dosage', 'dosagem', 'substantivo', 'Adjust the dosage carefully.', 'Ajuste a dosagem com cuidado.', 'Medicina'],
    ['incision', 'incisão', 'substantivo', 'The incision healed well.', 'A incisão cicatrizou bem.', 'Medicina'],
    ['relapse', 'recaída', 'substantivo', 'A relapse is still possible.', 'Uma recaída ainda é possível.', 'Medicina'],
    ['rhetoric', 'retórica', 'substantivo', 'The rhetoric outpaced the policy.', 'A retórica passou à frente da política.', 'Retórica'],
    ['persuasion', 'persuasão', 'substantivo', 'Persuasion beats coercion.', 'A persuasão vence a coerção.', 'Retórica'],
    ['anecdote', 'anedota', 'substantivo', 'An anecdote is not data.', 'Uma anedota não é dado.', 'Retórica'],
    ['analogy', 'analogia', 'substantivo', 'The analogy breaks down here.', 'A analogia falha aqui.', 'Retórica'],
    ['refutation', 'refutação', 'substantivo', 'His refutation was elegant.', 'A refutação dele foi elegante.', 'Retórica'],
    ['connotation', 'conotação', 'substantivo', 'That word carries a connotation.', 'Aquela palavra carrega uma conotação.', 'Retórica'],
    ['rebuttal', 'réplica', 'substantivo', 'She prepared a rebuttal.', 'Ela preparou uma réplica.', 'Retórica'],
    ['eloquence', 'eloquência', 'substantivo', 'Eloquence cannot hide weak evidence.', 'A eloquência não esconde evidência fraca.', 'Retórica'],
    ['discourse', 'discurso (campo)', 'substantivo', 'Public discourse has coarsened.', 'O discurso público se degradou.', 'Retórica'],
    ['digression', 'digressão', 'substantivo', 'Forgive the digression.', 'Perdoe a digressão.', 'Retórica'],
  ],
  C2: [
    ['elegiac', 'elegíaco', 'adjetivo', 'The novel has an elegiac tone.', 'O romance tem um tom elegíaco.', 'Registro literário'],
    ['sepulchral', 'sepulcral', 'adjetivo', 'He spoke in a sepulchral voice.', 'Ele falou com uma voz sepulcral.', 'Registro literário'],
    ['halcyon', 'idílico / de bonança', 'adjetivo', 'Those were halcyon days.', 'Aqueles eram dias idílicos.', 'Registro literário'],
    ['mellifluous', 'melífluo', 'adjetivo', 'Her mellifluous delivery held the room.', 'A entrega melíflua dela prendeu a sala.', 'Registro literário'],
    ['plaintive', 'lamentoso', 'adjetivo', 'A plaintive melody drifted in.', 'Uma melodia lamentosa entrou no ar.', 'Registro literário'],
    ['resplendent', 'resplandecente', 'adjetivo', 'She arrived resplendent in white.', 'Ela chegou resplandecente de branco.', 'Registro literário'],
    ['austere', 'austero', 'adjetivo', 'The prose is austere and exact.', 'A prosa é austera e exata.', 'Registro literário'],
    ['languid', 'lânguido', 'adjetivo', 'The afternoon was languid.', 'A tarde foi lânguida.', 'Registro literário'],
    ['ethereal', 'etéreo', 'adjetivo', 'The light was almost ethereal.', 'A luz era quase etérea.', 'Registro literário'],
    ['sonorous', 'sonoro / grave', 'adjetivo', 'His sonorous laugh filled the hall.', 'A risada sonora dele encheu o salão.', 'Registro literário'],
    ['litigation', 'litígio', 'substantivo', 'The case ended in litigation.', 'O caso terminou em litígio.', 'Jurídico avançado'],
    ['jurisdiction', 'jurisdição', 'substantivo', 'The court lacks jurisdiction.', 'O tribunal não tem jurisdição.', 'Jurídico avançado'],
    ['indictment', 'denúncia formal / acusação', 'substantivo', 'The indictment ran to sixty pages.', 'A denúncia tinha sessenta páginas.', 'Jurídico avançado'],
    ['culpability', 'culpabilidade', 'substantivo', 'Culpability was never established.', 'A culpabilidade nunca foi estabelecida.', 'Jurídico avançado'],
    ['presumption', 'presunção', 'substantivo', 'The presumption of innocence holds.', 'A presunção de inocência vale.', 'Jurídico avançado'],
    ['exculpatory', 'excludente de culpa', 'adjetivo', 'They withheld exculpatory evidence.', 'Eles ocultaram provas excludentes de culpa.', 'Jurídico avançado'],
    ['injunction', 'liminar', 'substantivo', 'The judge issued an injunction.', 'O juiz concedeu uma liminar.', 'Jurídico avançado'],
    ['deposition', 'depoimento formal', 'substantivo', 'The deposition lasted all day.', 'O depoimento durou o dia todo.', 'Jurídico avançado'],
    ['adjudicate', 'julgar / decidir', 'verbo', 'A panel will adjudicate the dispute.', 'Um colegiado vai julgar a disputa.', 'Jurídico avançado'],
    ['tortious', 'ilícito civil', 'adjetivo', 'That amounts to tortious interference.', 'Isso equivale a interferência ilícita.', 'Jurídico avançado'],
    ['erudite', 'erudito', 'adjetivo', 'The footnotes are erudite.', 'As notas de rodapé são eruditas.', 'Termos eruditos'],
    ['pellucid', 'límpido / cristalino', 'adjetivo', 'His pellucid explanation settled it.', 'A explicação límpida dele resolveu a questão.', 'Termos eruditos'],
    ['recondite', 'recôndito / obscuro', 'adjetivo', 'The argument is unnecessarily recondite.', 'O argumento é desnecessariamente obscuro.', 'Termos eruditos'],
    ['abstruse', 'abstruso', 'adjetivo', 'The theory grew abstruse.', 'A teoria ficou abstrusa.', 'Termos eruditos'],
    ['sagacious', 'sagaz', 'adjetivo', 'It was a sagacious choice.', 'Foi uma escolha sagaz.', 'Termos eruditos'],
    ['perspicacious', 'perspicaz', 'adjetivo', 'A perspicacious reader will notice.', 'Um leitor perspicaz vai notar.', 'Termos eruditos'],
    ['laconic', 'lacônico', 'adjetivo', 'His reply was laconic.', 'A resposta dele foi lacônica.', 'Termos eruditos'],
    ['prolix', 'prolixo', 'adjetivo', 'The introduction is prolix.', 'A introdução é prolixa.', 'Termos eruditos'],
    ['taciturn', 'taciturno', 'adjetivo', 'He remained taciturn throughout.', 'Ele permaneceu taciturno o tempo todo.', 'Termos eruditos'],
    ['garrulous', 'tagarela', 'adjetivo', 'Our garrulous host never paused.', 'Nosso anfitrião tagarela não parava.', 'Termos eruditos'],
    ['ambivalence', 'ambivalência', 'substantivo', 'Her ambivalence was obvious.', 'A ambivalência dela era evidente.', 'Nuance psicológica'],
    ['compunction', 'escrúpulo / remorso', 'substantivo', 'He lied without compunction.', 'Ele mentiu sem nenhum escrúpulo.', 'Nuance psicológica'],
    ['trepidation', 'apreensão', 'substantivo', 'She opened it with trepidation.', 'Ela abriu com apreensão.', 'Nuance psicológica'],
    ['umbrage', 'melindre / ofensa', 'substantivo', 'He took umbrage at the remark.', 'Ele se ofendeu com o comentário.', 'Nuance psicológica'],
    ['rancour', 'rancor', 'substantivo', 'She spoke without rancour.', 'Ela falou sem rancor.', 'Nuance psicológica'],
    ['contrition', 'contrição', 'substantivo', 'His contrition seemed genuine.', 'A contrição dele parecia genuína.', 'Nuance psicológica'],
    ['hubris', 'arrogância desmedida', 'substantivo', 'Hubris preceded the collapse.', 'A arrogância precedeu o colapso.', 'Nuance psicológica'],
    ['forbearance', 'tolerância / comedimento', 'substantivo', 'Thank you for your forbearance.', 'Obrigado pela sua tolerância.', 'Nuance psicológica'],
    ['magnanimity', 'magnanimidade', 'substantivo', 'He showed unexpected magnanimity.', 'Ele mostrou magnanimidade inesperada.', 'Nuance psicológica'],
    ['diffidence', 'timidez / insegurança', 'substantivo', 'Her diffidence hid real skill.', 'A insegurança dela escondia talento real.', 'Nuance psicológica'],
    ['corollary', 'corolário', 'substantivo', 'Higher costs are a corollary of that choice.', 'Custos maiores são um corolário dessa escolha.', 'Argumentação'],
    ['axiomatic', 'axiomático', 'adjetivo', 'It is axiomatic in this field.', 'É axiomático nesta área.', 'Argumentação'],
    ['incontrovertible', 'incontestável', 'adjetivo', 'The data are incontrovertible.', 'Os dados são incontestáveis.', 'Argumentação'],
    ['cogent', 'convincente / bem fundamentado', 'adjetivo', 'She made a cogent case.', 'Ela apresentou um caso bem fundamentado.', 'Argumentação'],
    ['extrapolate', 'extrapolar', 'verbo', 'Do not extrapolate from one case.', 'Não extrapole a partir de um caso.', 'Argumentação'],
    ['sophistry', 'sofisma', 'substantivo', 'That defence is sophistry.', 'Essa defesa é sofisma.', 'Argumentação'],
    ['disingenuous', 'falsamente ingênuo / desonesto', 'adjetivo', 'That answer is disingenuous.', 'Essa resposta é desonesta.', 'Argumentação'],
    ['specious', 'especioso / aparentemente válido', 'adjetivo', 'The reasoning is specious.', 'O raciocínio é especioso.', 'Argumentação'],
    ['apropos', 'a propósito de / pertinente', 'adjetivo', 'Your point is apropos.', 'Sua observação é pertinente.', 'Argumentação'],
    ['ipso facto', 'por isso mesmo', 'advérbio', 'It does not follow ipso facto.', 'Não decorre disso por isso mesmo.', 'Argumentação'],
    ['verisimilitude', 'verossimilhança', 'substantivo', 'The film lacks verisimilitude.', 'O filme carece de verossimilhança.', 'Crítica e estética'],
    ['pastiche', 'pastiche', 'substantivo', 'The album is a knowing pastiche.', 'O álbum é um pastiche consciente.', 'Crítica e estética'],
    ['bathos', 'bathos / queda ao ridículo', 'substantivo', 'The ending collapses into bathos.', 'O final desaba no ridículo.', 'Crítica e estética'],
    ['denouement', 'desfecho', 'substantivo', 'The denouement felt rushed.', 'O desfecho pareceu apressado.', 'Crítica e estética'],
    ['allegory', 'alegoria', 'substantivo', 'The whole book is an allegory.', 'O livro inteiro é uma alegoria.', 'Crítica e estética'],
    ['motif', 'motivo recorrente', 'substantivo', 'Water is the central motif.', 'A água é o motivo central.', 'Crítica e estética'],
    ['hyperbole', 'hipérbole', 'substantivo', 'That is hyperbole, not analysis.', 'Isso é hipérbole, não análise.', 'Crítica e estética'],
    ['pathos', 'pathos / comoção', 'substantivo', 'The scene achieves real pathos.', 'A cena alcança comoção verdadeira.', 'Crítica e estética'],
    ['satire', 'sátira', 'substantivo', 'It works better as satire.', 'Funciona melhor como sátira.', 'Crítica e estética'],
    ['oeuvre', 'obra (conjunto)', 'substantivo', 'This is minor within her oeuvre.', 'Isto é menor dentro da obra dela.', 'Crítica e estética'],
  ],
};
