/** Espanhol — lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const ES_THEMATIC: LatinByLevel = {
  A1: [
    ['verde', 'verde', 'adjetivo', 'La hierba es verde.', 'A grama é verde.', 'Cores e formas'],
    ['amarillo', 'amarelo', 'adjetivo', 'Me gustan las flores amarillas.', 'Gosto de flores amarelas.', 'Cores e formas'],
    ['negro', 'preto', 'adjetivo', 'Lleva un abrigo negro.', 'Ele usa um casaco preto.', 'Cores e formas'],
    ['blanco', 'branco', 'adjetivo', 'Las paredes son blancas.', 'As paredes são brancas.', 'Cores e formas'],
    ['naranja', 'laranja', 'adjetivo', 'Tiene un bolso naranja.', 'Ela tem uma bolsa laranja.', 'Cores e formas'],
    ['morado', 'roxo', 'adjetivo', 'El cielo se puso morado.', 'O céu ficou roxo.', 'Cores e formas'],
    ['marrón', 'marrom', 'adjetivo', 'Mis zapatos son marrones.', 'Meus sapatos são marrons.', 'Cores e formas'],
    ['rosa', 'rosa', 'adjetivo', 'El bebé tiene una manta rosa.', 'O bebê tem um cobertor rosa.', 'Cores e formas'],
    ['el círculo', 'círculo', 'substantivo', 'Dibuja un círculo aquí.', 'Desenhe um círculo aqui.', 'Cores e formas'],
    ['el cuadrado', 'quadrado', 'substantivo', 'La caja es un cuadrado.', 'A caixa é um quadrado.', 'Cores e formas'],
    ['la camisa', 'camisa', 'substantivo', 'Esta camisa está limpia.', 'Esta camisa está limpa.', 'Roupas'],
    ['los pantalones', 'calça', 'substantivo', 'Estos pantalones son nuevos.', 'Esta calça é nova.', 'Roupas'],
    ['los zapatos', 'sapatos', 'substantivo', 'Mis zapatos están mojados.', 'Meus sapatos estão molhados.', 'Roupas'],
    ['el vestido', 'vestido', 'substantivo', 'Ella compró un vestido.', 'Ela comprou um vestido.', 'Roupas'],
    ['la chaqueta', 'jaqueta', 'substantivo', 'Lleva tu chaqueta.', 'Leve sua jaqueta.', 'Roupas'],
    ['el sombrero', 'chapéu', 'substantivo', 'Perdió el sombrero.', 'Ele perdeu o chapéu.', 'Roupas'],
    ['los calcetines', 'meias', 'substantivo', 'Necesito calcetines limpios.', 'Preciso de meias limpas.', 'Roupas'],
    ['el abrigo', 'casaco', 'substantivo', 'Ponte un abrigo hoy.', 'Use um casaco hoje.', 'Roupas'],
    ['la falda', 'saia', 'substantivo', 'Esa falda es larga.', 'Aquela saia é longa.', 'Roupas'],
    ['las gafas', 'óculos', 'substantivo', 'Olvidé mis gafas.', 'Esqueci meus óculos.', 'Roupas'],
    ['el sol', 'sol', 'substantivo', 'El sol está fuerte.', 'O sol está forte.', 'Clima e natureza'],
    ['la lluvia', 'chuva', 'substantivo', 'La lluvia paró.', 'A chuva parou.', 'Clima e natureza'],
    ['la nieve', 'neve', 'substantivo', 'La nieve es profunda.', 'A neve está funda.', 'Clima e natureza'],
    ['el viento', 'vento', 'substantivo', 'El viento está fuerte.', 'O vento está forte.', 'Clima e natureza'],
    ['la nube', 'nuvem', 'substantivo', 'Hay una nube.', 'Há uma nuvem.', 'Clima e natureza'],
    ['el árbol', 'árvore', 'substantivo', 'El árbol es viejo.', 'A árvore é velha.', 'Clima e natureza'],
    ['la flor', 'flor', 'substantivo', 'Le gusta esta flor.', 'Ela gosta desta flor.', 'Clima e natureza'],
    ['el cielo', 'céu', 'substantivo', 'El cielo está despejado.', 'O céu está limpo.', 'Clima e natureza'],
    ['la playa', 'praia', 'substantivo', 'Vamos a la playa.', 'Nós vamos à praia.', 'Clima e natureza'],
    ['la montaña', 'montanha', 'substantivo', 'La montaña es alta.', 'A montanha é alta.', 'Clima e natureza'],
    ['la cabeza', 'cabeça', 'substantivo', 'Me duele la cabeza.', 'Minha cabeça dói.', 'Corpo'],
    ['la mano', 'mão', 'substantivo', 'Dame la mano.', 'Me dê sua mão.', 'Corpo'],
    ['el pie', 'pé', 'substantivo', 'Tengo el pie frío.', 'Meu pé está frio.', 'Corpo'],
    ['el ojo', 'olho', 'substantivo', 'Tiene un ojo verde.', 'Ela tem um olho verde.', 'Corpo'],
    ['la oreja', 'orelha', 'substantivo', 'Me duele la oreja.', 'Minha orelha dói.', 'Corpo'],
    ['la boca', 'boca', 'substantivo', 'Abre la boca.', 'Abra a boca.', 'Corpo'],
    ['la nariz', 'nariz', 'substantivo', 'Tiene la nariz roja.', 'O nariz dele está vermelho.', 'Corpo'],
    ['el pelo', 'cabelo', 'substantivo', 'Tiene el pelo largo.', 'O cabelo dela é longo.', 'Corpo'],
    ['el brazo', 'braço', 'substantivo', 'Se rompió el brazo.', 'Ele quebrou o braço.', 'Corpo'],
    ['la pierna', 'perna', 'substantivo', 'Tengo la pierna cansada.', 'Minha perna está cansada.', 'Corpo'],
    ['el pan', 'pão', 'substantivo', 'Como pan todos los días.', 'Eu como pão todo dia.', 'Comida e bebida'],
    ['la leche', 'leite', 'substantivo', 'La leche está fría.', 'O leite está frio.', 'Comida e bebida'],
    ['el café', 'café', 'substantivo', 'Ella bebe café.', 'Ela bebe café.', 'Comida e bebida'],
    ['el arroz', 'arroz', 'substantivo', 'Comemos arroz al mediodía.', 'Comemos arroz no almoço.', 'Comida e bebida'],
    ['la carne', 'carne', 'substantivo', 'Él no come carne.', 'Ele não come carne.', 'Comida e bebida'],
    ['la fruta', 'fruta', 'substantivo', 'Compra fruta.', 'Compre frutas.', 'Comida e bebida'],
    ['el huevo', 'ovo', 'substantivo', 'Quiero un huevo.', 'Quero um ovo.', 'Comida e bebida'],
    ['el queso', 'queijo', 'substantivo', 'Este queso está bueno.', 'Este queijo é bom.', 'Comida e bebida'],
    ['el azúcar', 'açúcar', 'substantivo', 'Sin azúcar, por favor.', 'Sem açúcar, por favor.', 'Comida e bebida'],
    ['la sal', 'sal', 'substantivo', 'Pásame la sal.', 'Me passe o sal.', 'Comida e bebida'],
    ['la mañana', 'manhã', 'substantivo', 'Trabajo por la mañana.', 'Eu trabalho de manhã.', 'Tempo e rotina'],
    ['la tarde', 'tarde', 'substantivo', 'Nos vemos por la tarde.', 'Até a tarde.', 'Tempo e rotina'],
    ['la noche', 'noite', 'substantivo', 'La noche está tranquila.', 'A noite está calma.', 'Tempo e rotina'],
    ['la semana', 'semana', 'substantivo', 'La semana es larga.', 'A semana é longa.', 'Tempo e rotina'],
    ['el mes', 'mês', 'substantivo', 'Este mes está lleno.', 'Este mês está cheio.', 'Tempo e rotina'],
    ['hoy', 'hoje', 'advérbio', 'Hoy estoy cansado.', 'Estou cansado hoje.', 'Tempo e rotina'],
    ['ayer', 'ontem', 'advérbio', 'Ayer llovió.', 'Choveu ontem.', 'Tempo e rotina'],
    ['la hora', 'hora', 'substantivo', 'Espera una hora.', 'Espere uma hora.', 'Tempo e rotina'],
    ['el minuto', 'minuto', 'substantivo', 'Solo un minuto.', 'Só um minuto.', 'Tempo e rotina'],
    ['el fin de semana', 'fim de semana', 'substantivo', 'El fin de semana descanso.', 'No fim de semana eu descanso.', 'Tempo e rotina'],
  ],
  A2: [
    ['el vuelo', 'voo', 'substantivo', 'Nuestro vuelo sale a las seis.', 'Nosso voo sai às seis.', 'Viagem'],
    ['el pasaporte', 'passaporte', 'substantivo', 'Muéstrame tu pasaporte.', 'Me mostre seu passaporte.', 'Viagem'],
    ['el equipaje', 'bagagem', 'substantivo', 'Mi equipaje pesa mucho.', 'Minha bagagem está pesada.', 'Viagem'],
    ['el billete', 'passagem / bilhete', 'substantivo', 'Compré el billete por internet.', 'Comprei a passagem pela internet.', 'Viagem'],
    ['el retraso', 'atraso', 'substantivo', 'Hubo un retraso largo.', 'Houve um atraso longo.', 'Viagem'],
    ['el aeropuerto', 'aeroporto', 'substantivo', 'El aeropuerto está lejos.', 'O aeroporto é longe.', 'Viagem'],
    ['la maleta', 'mala', 'substantivo', 'Haz la maleta esta noche.', 'Faça sua mala hoje à noite.', 'Viagem'],
    ['la salida', 'partida / saída', 'substantivo', 'Mira la hora de salida.', 'Confira o horário de partida.', 'Viagem'],
    ['la llegada', 'chegada', 'substantivo', 'La llegada fue tranquila.', 'A chegada foi tranquila.', 'Viagem'],
    ['la tarjeta de embarque', 'cartão de embarque', 'substantivo', 'Guarda tu tarjeta de embarque.', 'Guarde seu cartão de embarque.', 'Viagem'],
    ['la carta', 'cardápio', 'substantivo', '¿Puedo ver la carta?', 'Posso ver o cardápio?', 'Restaurante'],
    ['el camarero', 'garçom', 'substantivo', 'El camarero ya viene.', 'O garçom está vindo.', 'Restaurante'],
    ['la propina', 'gorjeta', 'substantivo', 'Dejamos una buena propina.', 'Deixamos uma boa gorjeta.', 'Restaurante'],
    ['el postre', 'sobremesa', 'substantivo', 'Quiero postre.', 'Quero sobremesa.', 'Restaurante'],
    ['el entrante', 'entrada (prato)', 'substantivo', 'El entrante era pequeño.', 'A entrada era pequena.', 'Restaurante'],
    ['la reserva', 'reserva', 'substantivo', 'Hice una reserva.', 'Fiz uma reserva.', 'Restaurante'],
    ['la servilleta', 'guardanapo', 'substantivo', 'Pásame una servilleta.', 'Me passe um guardanapo.', 'Restaurante'],
    ['la bandeja', 'bandeja', 'substantivo', 'Ponlo en la bandeja.', 'Coloque na bandeja.', 'Restaurante'],
    ['el sabor', 'sabor', 'substantivo', 'El sabor es raro.', 'O sabor está estranho.', 'Restaurante'],
    ['picante', 'picante', 'adjetivo', 'Esta comida es picante.', 'Esta comida é picante.', 'Restaurante'],
    ['el efectivo', 'dinheiro (em espécie)', 'substantivo', 'Solo tengo efectivo.', 'Só tenho dinheiro em espécie.', 'Compras'],
    ['el cambio', 'troco', 'substantivo', 'Quédate con el cambio.', 'Fique com o troco.', 'Compras'],
    ['la talla', 'tamanho (roupa)', 'substantivo', '¿Tiene una talla más grande?', 'Tem um tamanho maior?', 'Compras'],
    ['la ganga', 'pechincha', 'substantivo', 'Ese abrigo fue una ganga.', 'Aquele casaco foi uma pechincha.', 'Compras'],
    ['el cajero', 'caixa (pessoa)', 'substantivo', 'Pregúntale al cajero.', 'Pergunte ao caixa.', 'Compras'],
    ['el pasillo', 'corredor (de loja)', 'substantivo', 'La leche está en el pasillo tres.', 'O leite está no corredor três.', 'Compras'],
    ['la estantería', 'prateleira', 'substantivo', 'La estantería está vacía.', 'A prateleira está vazia.', 'Compras'],
    ['las rebajas', 'liquidação', 'substantivo', 'Los zapatos están en rebajas.', 'Os sapatos estão em liquidação.', 'Compras'],
    ['la cartera', 'carteira', 'substantivo', 'Dejé la cartera en casa.', 'Deixei minha carteira em casa.', 'Compras'],
    ['la marca', 'marca', 'substantivo', 'Confío en esta marca.', 'Confio nesta marca.', 'Compras'],
    ['la tos', 'tosse', 'substantivo', 'Tiene mucha tos.', 'Ela está com muita tosse.', 'Saúde'],
    ['el dolor de cabeza', 'dor de cabeça', 'substantivo', 'Tengo dolor de cabeza.', 'Estou com dor de cabeça.', 'Saúde'],
    ['la pastilla', 'comprimido', 'substantivo', 'Toma una pastilla al día.', 'Tome um comprimido por dia.', 'Saúde'],
    ['el enfermero', 'enfermeiro', 'substantivo', 'El enfermero fue amable.', 'O enfermeiro foi gentil.', 'Saúde'],
    ['la lesión', 'lesão', 'substantivo', 'La lesión fue seria.', 'A lesão foi séria.', 'Saúde'],
    ['el descanso', 'descanso', 'substantivo', 'Necesitas descanso.', 'Você precisa de descanso.', 'Saúde'],
    ['la venda', 'curativo / bandagem', 'substantivo', 'Ponle una venda.', 'Coloque um curativo nisso.', 'Saúde'],
    ['mareado', 'tonto (com tontura)', 'adjetivo', 'Me siento mareado.', 'Estou me sentindo tonto.', 'Saúde'],
    ['la clínica', 'clínica', 'substantivo', 'La clínica abre a las ocho.', 'A clínica abre às oito.', 'Saúde'],
    ['la molestia', 'incômodo / dor leve', 'substantivo', 'Tengo una molestia en la espalda.', 'Tenho um incômodo nas costas.', 'Saúde'],
    ['el puente', 'ponte', 'substantivo', 'Cruza el puente.', 'Atravesse a ponte.', 'Cidade'],
    ['la plaza', 'praça', 'substantivo', 'Nos vimos en la plaza.', 'Nos encontramos na praça.', 'Cidade'],
    ['la esquina', 'esquina', 'substantivo', 'Gira en la esquina.', 'Vire na esquina.', 'Cidade'],
    ['el tráfico', 'trânsito', 'substantivo', 'El tráfico está fatal.', 'O trânsito está terrível.', 'Cidade'],
    ['el metro', 'metrô', 'substantivo', 'Coge el metro.', 'Pegue o metrô.', 'Cidade'],
    ['la parada', 'parada (ônibus)', 'substantivo', 'Bájate en la próxima parada.', 'Desça na próxima parada.', 'Cidade'],
    ['el mapa', 'mapa', 'substantivo', 'Mira el mapa.', 'Olhe o mapa.', 'Cidade'],
    ['el sendero', 'trilha', 'substantivo', 'Sigue este sendero.', 'Siga esta trilha.', 'Cidade'],
    ['la verja', 'portão', 'substantivo', 'La verja está cerrada.', 'O portão está trancado.', 'Cidade'],
    ['el paso de peatones', 'faixa de pedestres', 'substantivo', 'Usa el paso de peatones.', 'Use a faixa de pedestres.', 'Cidade'],
    ['la colada', 'roupa para lavar', 'substantivo', 'Hago la colada el domingo.', 'Eu lavo a roupa no domingo.', 'Casa e tarefas'],
    ['los platos', 'louça', 'substantivo', 'Él friega los platos.', 'Ele lava a louça.', 'Casa e tarefas'],
    ['la escoba', 'vassoura', 'substantivo', '¿Dónde está la escoba?', 'Onde está a vassoura?', 'Casa e tarefas'],
    ['la basura', 'lixo', 'substantivo', 'Saca la basura.', 'Leve o lixo para fora.', 'Casa e tarefas'],
    ['la toalla', 'toalha', 'substantivo', 'La toalla está mojada.', 'A toalha está molhada.', 'Casa e tarefas'],
    ['la manta', 'cobertor', 'substantivo', 'Necesito otra manta.', 'Preciso de outro cobertor.', 'Casa e tarefas'],
    ['el cajón', 'gaveta', 'substantivo', 'Está en el cajón.', 'Está na gaveta.', 'Casa e tarefas'],
    ['el armario', 'armário', 'substantivo', 'Cuélgalo en el armario.', 'Pendure no armário.', 'Casa e tarefas'],
    ['el fregadero', 'pia', 'substantivo', 'El fregadero está atascado.', 'A pia está entupida.', 'Casa e tarefas'],
    ['el espejo', 'espelho', 'substantivo', 'Mírate en el espejo.', 'Olhe no espelho.', 'Casa e tarefas'],
  ],
  B1: [
    ['la entrevista', 'entrevista', 'substantivo', 'La entrevista salió bien.', 'A entrevista correu bem.', 'Trabalho'],
    ['el currículum', 'currículo', 'substantivo', 'Mándame tu currículum.', 'Me mande seu currículo.', 'Trabalho'],
    ['el turno', 'turno', 'substantivo', 'Trabajo el turno de noche.', 'Eu trabalho no turno da noite.', 'Trabalho'],
    ['las horas extras', 'horas extras', 'substantivo', 'Hizo horas extras otra vez.', 'Ela fez hora extra de novo.', 'Trabalho'],
    ['las prácticas', 'estágio', 'substantivo', 'Consiguió unas prácticas.', 'Ele conseguiu um estágio.', 'Trabalho'],
    ['el supervisor', 'supervisor', 'substantivo', 'Habla con tu supervisor.', 'Fale com seu supervisor.', 'Trabalho'],
    ['la tarea', 'tarefa', 'substantivo', 'Esta tarea lleva dos horas.', 'Esta tarefa leva duas horas.', 'Trabalho'],
    ['la reunión', 'reunião', 'substantivo', 'Cancelaron la reunión.', 'A reunião foi cancelada.', 'Trabalho'],
    ['la plantilla', 'quadro de funcionários', 'substantivo', 'La plantilla es simpática.', 'A equipe é simpática.', 'Trabalho'],
    ['el contrato', 'contrato', 'substantivo', 'Lee el contrato primero.', 'Leia o contrato primeiro.', 'Trabalho'],
    ['la actualización', 'atualização', 'substantivo', 'Instala la actualización.', 'Instale a atualização.', 'Tecnologia'],
    ['la contraseña', 'senha', 'substantivo', 'Olvidé mi contraseña.', 'Esqueci minha senha.', 'Tecnologia'],
    ['la copia de seguridad', 'cópia de segurança', 'substantivo', 'Haz una copia de seguridad antes.', 'Faça uma cópia de segurança antes.', 'Tecnologia'],
    ['el dispositivo', 'dispositivo', 'substantivo', 'Este dispositivo es rápido.', 'Este dispositivo é rápido.', 'Tecnologia'],
    ['la pantalla', 'tela', 'substantivo', 'La pantalla está rota.', 'A tela está quebrada.', 'Tecnologia'],
    ['descargar', 'baixar', 'verbo', 'Descarga el archivo ahora.', 'Baixe o arquivo agora.', 'Tecnologia'],
    ['la red', 'rede', 'substantivo', 'La red está caída.', 'A rede está fora do ar.', 'Tecnologia'],
    ['el navegador', 'navegador', 'substantivo', 'Abre otra pestaña del navegador.', 'Abra outra aba do navegador.', 'Tecnologia'],
    ['la carpeta', 'pasta', 'substantivo', 'Guárdalo en esta carpeta.', 'Salve nesta pasta.', 'Tecnologia'],
    ['fallar', 'falhar / travar', 'verbo', 'La aplicación falló otra vez.', 'O aplicativo travou de novo.', 'Tecnologia'],
    ['reciclar', 'reciclar', 'verbo', 'Aquí reciclamos plástico.', 'Nós reciclamos plástico aqui.', 'Meio ambiente'],
    ['la contaminación', 'poluição', 'substantivo', 'La contaminación empeoró.', 'A poluição piorou.', 'Meio ambiente'],
    ['el residuo', 'resíduo', 'substantivo', 'El residuo alimentario es un problema.', 'O resíduo alimentar é um problema.', 'Meio ambiente'],
    ['el clima', 'clima', 'substantivo', 'El clima está cambiando.', 'O clima está mudando.', 'Meio ambiente'],
    ['la energía', 'energia', 'substantivo', 'La energía solar es más barata ahora.', 'A energia solar está mais barata agora.', 'Meio ambiente'],
    ['el bosque', 'floresta', 'substantivo', 'El bosque está protegido.', 'A floresta é protegida.', 'Meio ambiente'],
    ['la especie', 'espécie', 'substantivo', 'Esta especie es rara.', 'Esta espécie é rara.', 'Meio ambiente'],
    ['la sequía', 'seca', 'substantivo', 'La sequía duró meses.', 'A seca durou meses.', 'Meio ambiente'],
    ['la inundación', 'enchente', 'substantivo', 'La inundación dañó la carretera.', 'A enchente danificou a estrada.', 'Meio ambiente'],
    ['el vertido', 'despejo (poluente)', 'substantivo', 'El vertido llegó al río.', 'O despejo chegou ao rio.', 'Meio ambiente'],
    ['el árbitro', 'árbitro', 'substantivo', 'El árbitro paró el partido.', 'O árbitro parou o jogo.', 'Esportes'],
    ['el torneo', 'torneio', 'substantivo', 'Ganó el torneo.', 'Ela ganhou o torneio.', 'Esportes'],
    ['el rival', 'adversário', 'substantivo', 'Su rival era más rápido.', 'O adversário dele era mais rápido.', 'Esportes'],
    ['el compañero de equipo', 'companheiro de equipe', 'substantivo', 'Mi compañero de equipo marcó.', 'Meu companheiro de equipe marcou.', 'Esportes'],
    ['el entrenador', 'treinador', 'substantivo', 'El entrenador estaba enfadado.', 'O treinador estava bravo.', 'Esportes'],
    ['el marcador', 'placar', 'substantivo', '¿Cómo va el marcador?', 'Qual é o placar?', 'Esportes'],
    ['el partido', 'partida', 'substantivo', 'El partido empieza a las ocho.', 'A partida começa às oito.', 'Esportes'],
    ['el entrenamiento', 'treino', 'substantivo', 'El entrenamiento es cada mañana.', 'O treino é toda manhã.', 'Esportes'],
    ['la resistencia', 'resistência física', 'substantivo', 'Tiene mucha resistencia.', 'Ele tem muita resistência.', 'Esportes'],
    ['el campeonato', 'campeonato', 'substantivo', 'Perdieron el campeonato.', 'Eles perderam o campeonato.', 'Esportes'],
    ['discutir', 'discutir', 'verbo', 'Discuten por dinero.', 'Eles discutem por dinheiro.', 'Relacionamentos'],
    ['disculparse', 'pedir desculpas', 'verbo', 'Se disculpó rápido.', 'Ele pediu desculpas rápido.', 'Relacionamentos'],
    ['la confianza', 'confiança', 'substantivo', 'La confianza lleva tiempo.', 'Confiança leva tempo.', 'Relacionamentos'],
    ['celoso', 'ciumento', 'adjetivo', 'Se pone celosa fácilmente.', 'Ela fica com ciúmes fácil.', 'Relacionamentos'],
    ['leal', 'leal', 'adjetivo', 'Es un amigo leal.', 'Ele é um amigo leal.', 'Relacionamentos'],
    ['el chisme', 'fofoca', 'substantivo', 'Odio el chisme de oficina.', 'Odeio fofoca de escritório.', 'Relacionamentos'],
    ['el consejo', 'conselho', 'substantivo', 'Ese fue un buen consejo.', 'Aquilo foi um bom conselho.', 'Relacionamentos'],
    ['el favor', 'favor', 'substantivo', '¿Te puedo pedir un favor?', 'Posso pedir um favor?', 'Relacionamentos'],
    ['la riña', 'briga / desentendimento', 'substantivo', 'Tuvieron una riña tonta.', 'Eles tiveram uma briga boba.', 'Relacionamentos'],
    ['el acuerdo mutuo', 'acordo mútuo', 'substantivo', 'Llegamos a un acuerdo mutuo.', 'Chegamos a um acordo mútuo.', 'Relacionamentos'],
    ['el presupuesto', 'orçamento', 'substantivo', 'Cíñete al presupuesto.', 'Siga o orçamento.', 'Dinheiro'],
    ['los ahorros', 'poupança', 'substantivo', 'Usó sus ahorros.', 'Ela usou a poupança.', 'Dinheiro'],
    ['el préstamo', 'empréstimo', 'substantivo', 'Pidió un préstamo.', 'Ele fez um empréstimo.', 'Dinheiro'],
    ['la deuda', 'dívida', 'substantivo', 'Pagaron la deuda.', 'Eles quitaram a dívida.', 'Dinheiro'],
    ['el gasto', 'despesa', 'substantivo', 'El alquiler es mi mayor gasto.', 'O aluguel é minha maior despesa.', 'Dinheiro'],
    ['el interés', 'juros', 'substantivo', 'El interés es demasiado alto.', 'Os juros estão altos demais.', 'Dinheiro'],
    ['invertir', 'investir', 'verbo', 'Invierten en inmuebles.', 'Eles investem em imóveis.', 'Dinheiro'],
    ['la hipoteca', 'financiamento imobiliário', 'substantivo', 'Tenemos una hipoteca.', 'Nós temos um financiamento.', 'Dinheiro'],
    ['el seguro', 'seguro', 'substantivo', 'El seguro del coche es caro.', 'O seguro do carro é caro.', 'Dinheiro'],
    ['el salario mínimo', 'salário mínimo', 'substantivo', 'El salario mínimo subió.', 'O salário mínimo subiu.', 'Dinheiro'],
  ],
  B2: [
    ['la campaña', 'campanha', 'substantivo', 'La campaña duró seis semanas.', 'A campanha durou seis semanas.', 'Política'],
    ['el electorado', 'eleitorado', 'substantivo', 'El electorado está dividido.', 'O eleitorado está dividido.', 'Política'],
    ['la legislación', 'legislação', 'substantivo', 'Se aprobó una nueva legislación.', 'Uma nova legislação foi aprovada.', 'Política'],
    ['el cabildeo', 'lobby', 'substantivo', 'El cabildeo moldeó la ley.', 'O lobby moldou a lei.', 'Política'],
    ['la corrupción', 'corrupção', 'substantivo', 'La corrupción socava la confianza.', 'A corrupção corrói a confiança.', 'Política'],
    ['el referéndum', 'referendo', 'substantivo', 'Convocaron un referéndum.', 'Eles convocaram um referendo.', 'Política'],
    ['la coalición', 'coalizão', 'substantivo', 'La coalición se rompió.', 'A coalizão desmoronou.', 'Política'],
    ['la papeleta', 'cédula de votação', 'substantivo', 'Tu papeleta es secreta.', 'Seu voto é secreto.', 'Política'],
    ['la circunscripción', 'distrito eleitoral', 'substantivo', 'Visitó su circunscripción.', 'Ela visitou seu distrito eleitoral.', 'Política'],
    ['el mandato', 'mandato', 'substantivo', 'Alegan un mandato claro.', 'Eles alegam um mandato claro.', 'Política'],
    ['la inflación', 'inflação', 'substantivo', 'La inflación bajó el mes pasado.', 'A inflação desacelerou no mês passado.', 'Economia'],
    ['la recesión', 'recessão', 'substantivo', 'El país entró en recesión.', 'O país entrou em recessão.', 'Economia'],
    ['la subvención', 'subsídio', 'substantivo', 'Recortaron la subvención.', 'O subsídio foi cortado.', 'Economia'],
    ['el arancel', 'tarifa alfandegária', 'substantivo', 'Impusieron un arancel.', 'Impuseram uma tarifa.', 'Economia'],
    ['el superávit', 'superávit', 'substantivo', 'El presupuesto muestra superávit.', 'O orçamento mostra superávit.', 'Economia'],
    ['el déficit', 'déficit', 'substantivo', 'El déficit sigue creciendo.', 'O déficit continua crescendo.', 'Economia'],
    ['la oferta', 'oferta', 'substantivo', 'La oferta no cubre la demanda.', 'A oferta não atende à procura.', 'Economia'],
    ['la demanda', 'procura', 'substantivo', 'La demanda cayó bruscamente.', 'A procura caiu bruscamente.', 'Economia'],
    ['el monopolio', 'monopólio', 'substantivo', 'Tienen casi un monopolio.', 'Eles têm quase um monopólio.', 'Economia'],
    ['la austeridad', 'austeridade', 'substantivo', 'La austeridad dañó los servicios públicos.', 'A austeridade prejudicou os serviços públicos.', 'Economia'],
    ['el experimento', 'experimento', 'substantivo', 'El experimento falló dos veces.', 'O experimento falhou duas vezes.', 'Ciência'],
    ['la evidencia', 'evidência', 'substantivo', 'Hay evidencia sólida.', 'Há evidências sólidas.', 'Ciência'],
    ['la muestra', 'amostra', 'substantivo', 'La muestra era demasiado pequeña.', 'A amostra era pequena demais.', 'Ciência'],
    ['el laboratorio', 'laboratório', 'substantivo', 'Trabaja en un laboratorio.', 'Ela trabalha num laboratório.', 'Ciência'],
    ['la molécula', 'molécula', 'substantivo', 'El agua es una molécula simple.', 'A água é uma molécula simples.', 'Ciência'],
    ['el genoma', 'genoma', 'substantivo', 'Mapearon el genoma.', 'Eles mapearam o genoma.', 'Ciência'],
    ['la vacuna', 'vacina', 'substantivo', 'La vacuna funciona bien.', 'A vacina funciona bem.', 'Ciência'],
    ['el microbio', 'micróbio', 'substantivo', 'Este microbio es inofensivo.', 'Este micróbio é inofensivo.', 'Ciência'],
    ['la radiación', 'radiação', 'substantivo', 'Los niveles de radiación son normales.', 'Os níveis de radiação estão normais.', 'Ciência'],
    ['el telescopio', 'telescópio', 'substantivo', 'El telescopio halló un planeta.', 'O telescópio encontrou um planeta.', 'Ciência'],
    ['el titular', 'manchete', 'substantivo', 'El titular era engañoso.', 'A manchete era enganosa.', 'Mídia'],
    ['la cobertura', 'cobertura jornalística', 'substantivo', 'La cobertura fue sesgada.', 'A cobertura foi tendenciosa.', 'Mídia'],
    ['la censura', 'censura', 'substantivo', 'La censura aumentó el año pasado.', 'A censura aumentou no ano passado.', 'Mídia'],
    ['la propaganda', 'propaganda ideológica', 'substantivo', 'Esto es pura propaganda.', 'Isso é pura propaganda.', 'Mídia'],
    ['la emisión', 'transmissão', 'substantivo', 'La emisión llegó a millones.', 'A transmissão alcançou milhões.', 'Mídia'],
    ['el periodista', 'jornalista', 'substantivo', 'La periodista verificó sus fuentes.', 'A jornalista checou suas fontes.', 'Mídia'],
    ['el editorial', 'editorial', 'substantivo', 'El editorial criticó el plan.', 'O editorial criticou o plano.', 'Mídia'],
    ['el sensacionalismo', 'sensacionalismo', 'substantivo', 'El sensacionalismo vende más.', 'O sensacionalismo vende mais.', 'Mídia'],
    ['la audiencia', 'público', 'substantivo', 'La audiencia estaba hostil.', 'O público estava hostil.', 'Mídia'],
    ['la fuente', 'fonte', 'substantivo', 'Cita tu fuente.', 'Cite sua fonte.', 'Mídia'],
    ['la empatía', 'empatia', 'substantivo', 'La empatía se puede enseñar.', 'A empatia pode ser ensinada.', 'Psicologia'],
    ['la ansiedad', 'ansiedade', 'substantivo', 'La ansiedad afecta el sueño.', 'A ansiedade afeta o sono.', 'Psicologia'],
    ['el trauma', 'trauma', 'substantivo', 'El trauma duró años.', 'O trauma durou anos.', 'Psicologia'],
    ['la motivación', 'motivação', 'substantivo', 'La motivación se apaga sin resultados.', 'A motivação some sem resultados.', 'Psicologia'],
    ['la percepción', 'percepção', 'substantivo', 'La percepción moldea la memoria.', 'A percepção molda a memória.', 'Psicologia'],
    ['la conducta', 'comportamento', 'substantivo', 'Su conducta cambió de repente.', 'O comportamento dele mudou de repente.', 'Psicologia'],
    ['el instinto', 'instinto', 'substantivo', 'Confía en tu instinto aquí.', 'Confie no seu instinto aqui.', 'Psicologia'],
    ['el ánimo', 'ânimo / humor', 'substantivo', 'Su ánimo mejoró.', 'O humor dela melhorou.', 'Psicologia'],
    ['la autoestima', 'autoestima', 'substantivo', 'La baja autoestima es común.', 'Baixa autoestima é comum.', 'Psicologia'],
    ['el resentimiento', 'ressentimento', 'substantivo', 'El resentimiento creció despacio.', 'O ressentimento cresceu devagar.', 'Psicologia'],
    ['la demanda judicial', 'processo judicial', 'substantivo', 'Presentaron una demanda judicial.', 'Eles entraram com um processo.', 'Direito'],
    ['el veredicto', 'veredicto', 'substantivo', 'El veredicto sorprendió a todos.', 'O veredicto surpreendeu todos.', 'Direito'],
    ['el testimonio', 'depoimento', 'substantivo', 'Su testimonio fue decisivo.', 'O depoimento dela foi decisivo.', 'Direito'],
    ['el testigo', 'testemunha', 'substantivo', 'El testigo cambió su versión.', 'A testemunha mudou a versão.', 'Direito'],
    ['el acusado', 'réu', 'substantivo', 'El acusado guardó silencio.', 'O réu permaneceu calado.', 'Direito'],
    ['el abogado', 'advogado', 'substantivo', 'Llama a tu abogado.', 'Ligue para seu advogado.', 'Direito'],
    ['la culpabilidad declarada', 'confissão de culpa', 'substantivo', 'Optó por la culpabilidad declarada.', 'Ele optou por se declarar culpado.', 'Direito'],
    ['el recurso', 'recurso judicial', 'substantivo', 'Perdieron el recurso.', 'Eles perderam o recurso.', 'Direito'],
    ['la custodia', 'custódia', 'substantivo', 'Ella ganó la custodia.', 'Ela ganhou a custódia.', 'Direito'],
    ['el estatuto', 'estatuto', 'substantivo', 'El estatuto está anticuado.', 'O estatuto está ultrapassado.', 'Direito'],
  ],
  C1: [
    ['la hipótesis', 'hipótese', 'substantivo', 'La hipótesis no se sostuvo.', 'A hipótese não se sustentou.', 'Pesquisa acadêmica'],
    ['la metodología', 'metodologia', 'substantivo', 'Describe tu metodología con claridad.', 'Descreva sua metodologia com clareza.', 'Pesquisa acadêmica'],
    ['la correlación', 'correlação', 'substantivo', 'Correlación no es causalidad.', 'Correlação não é causalidade.', 'Pesquisa acadêmica'],
    ['la variable', 'variável', 'substantivo', 'Controla esa variable.', 'Controle essa variável.', 'Pesquisa acadêmica'],
    ['empírico', 'empírico', 'adjetivo', 'Necesitamos respaldo empírico.', 'Precisamos de respaldo empírico.', 'Pesquisa acadêmica'],
    ['la revisión por pares', 'revisão por pares', 'substantivo', 'La revisión por pares detectó el error.', 'A revisão por pares pegou o erro.', 'Pesquisa acadêmica'],
    ['longitudinal', 'longitudinal', 'adjetivo', 'Fue un estudio longitudinal.', 'Foi um estudo longitudinal.', 'Pesquisa acadêmica'],
    ['la replicación', 'replicação', 'substantivo', 'La replicación falló dos veces.', 'A replicação falhou duas vezes.', 'Pesquisa acadêmica'],
    ['la inferencia', 'inferência', 'substantivo', 'Esa inferencia es demasiado amplia.', 'Essa inferência é ampla demais.', 'Pesquisa acadêmica'],
    ['el paradigma', 'paradigma', 'substantivo', 'El paradigma cambió despacio.', 'O paradigma mudou devagar.', 'Pesquisa acadêmica'],
    ['el interesado', 'parte interessada', 'substantivo', 'Consulta a cada interesado.', 'Consulte cada parte interessada.', 'Negócios'],
    ['la adquisición', 'aquisição', 'substantivo', 'La adquisición se cerró en mayo.', 'A aquisição foi concluída em maio.', 'Negócios'],
    ['la fusión', 'fusão', 'substantivo', 'La fusión encontró resistencia.', 'A fusão enfrentou resistência.', 'Negócios'],
    ['la facturación', 'faturamento', 'substantivo', 'La facturación creció un doce por ciento.', 'O faturamento cresceu doze por cento.', 'Negócios'],
    ['la responsabilidad civil', 'responsabilidade civil', 'substantivo', 'Esa cláusula genera responsabilidad civil.', 'Aquela cláusula gera responsabilidade civil.', 'Negócios'],
    ['el arbitraje', 'arbitragem', 'substantivo', 'Fueron a arbitraje.', 'Eles foram para a arbitragem.', 'Negócios'],
    ['el referente', 'referência comparativa', 'substantivo', 'Fija un referente realista.', 'Defina uma referência realista.', 'Negócios'],
    ['la viabilidad', 'viabilidade', 'substantivo', 'Estudia la viabilidad primero.', 'Estude a viabilidade primeiro.', 'Negócios'],
    ['la diversificación', 'diversificação', 'substantivo', 'La diversificación redujo el riesgo.', 'A diversificação reduziu o risco.', 'Negócios'],
    ['la contratación pública', 'licitação pública', 'substantivo', 'La contratación pública tarda meses.', 'A licitação pública leva meses.', 'Negócios'],
    ['la ontología', 'ontologia', 'substantivo', 'Eso es una cuestión de ontología.', 'Isso é uma questão de ontologia.', 'Filosofia'],
    ['la epistemología', 'epistemologia', 'substantivo', 'La epistemología pregunta cómo sabemos.', 'A epistemologia pergunta como sabemos.', 'Filosofia'],
    ['el determinismo', 'determinismo', 'substantivo', 'El determinismo niega el libre albedrío.', 'O determinismo nega o livre-arbítrio.', 'Filosofia'],
    ['la dialéctica', 'dialética', 'substantivo', 'Argumentó por la dialéctica.', 'Ele argumentou pela dialética.', 'Filosofia'],
    ['la metafísica', 'metafísica', 'substantivo', 'La metafísica se resiste a la prueba.', 'A metafísica resiste à comprovação.', 'Filosofia'],
    ['existencial', 'existencial', 'adjetivo', 'Se volvió una amenaza existencial.', 'Virou uma ameaça existencial.', 'Filosofia'],
    ['la teleología', 'teleologia', 'substantivo', 'La teleología explica por la finalidad.', 'A teleologia explica pela finalidade.', 'Filosofia'],
    ['el nihilismo', 'niilismo', 'substantivo', 'El nihilismo niega el sentido inherente.', 'O niilismo nega sentido inerente.', 'Filosofia'],
    ['el axioma', 'axioma', 'substantivo', 'Parte de un axioma compartido.', 'Parta de um axioma comum.', 'Filosofia'],
    ['el silogismo', 'silogismo', 'substantivo', 'El silogismo es inválido.', 'O silogismo é inválido.', 'Filosofia'],
    ['la estratificación', 'estratificação', 'substantivo', 'La estratificación social persiste.', 'A estratificação social persiste.', 'Sociologia'],
    ['la asimilación', 'assimilação', 'substantivo', 'Se esperaba de ellos la asimilación.', 'Esperava-se deles a assimilação.', 'Sociologia'],
    ['demográfico', 'demográfico', 'adjetivo', 'El cambio demográfico es claro.', 'A mudança demográfica é clara.', 'Sociologia'],
    ['la urbanización', 'urbanização', 'substantivo', 'La urbanización se aceleró tras 1960.', 'A urbanização acelerou depois de 1960.', 'Sociologia'],
    ['la cohorte', 'coorte / geração', 'substantivo', 'Esa cohorte gana menos.', 'Essa geração ganha menos.', 'Sociologia'],
    ['la norma social', 'norma social', 'substantivo', 'La norma social cambió en silencio.', 'A norma social mudou silenciosamente.', 'Sociologia'],
    ['la desviación', 'desvio (social)', 'substantivo', 'La desviación se define por el contexto.', 'O desvio é definido pelo contexto.', 'Sociologia'],
    ['la movilidad social', 'mobilidade social', 'substantivo', 'La movilidad social se ha estancado.', 'A mobilidade social estagnou.', 'Sociologia'],
    ['el parentesco', 'parentesco', 'substantivo', 'Los lazos de parentesco siguen fuertes.', 'Os laços de parentesco seguem fortes.', 'Sociologia'],
    ['la secularización', 'secularização', 'substantivo', 'La secularización varía por región.', 'A secularização varia por região.', 'Sociologia'],
    ['el pronóstico', 'prognóstico', 'substantivo', 'El pronóstico es cautelosamente bueno.', 'O prognóstico é cautelosamente bom.', 'Medicina'],
    ['crónico', 'crônico', 'adjetivo', 'Se volvió una dolencia crónica.', 'Virou uma condição crônica.', 'Medicina'],
    ['benigno', 'benigno', 'adjetivo', 'El bulto era benigno.', 'O nódulo era benigno.', 'Medicina'],
    ['maligno', 'maligno', 'adjetivo', 'El tumor resultó maligno.', 'O tumor se revelou maligno.', 'Medicina'],
    ['la remisión', 'remissão', 'substantivo', 'Lleva un año en remisión.', 'Ela está em remissão há um ano.', 'Medicina'],
    ['la patología', 'patologia', 'substantivo', 'Llegó el informe de patología.', 'O laudo de patologia chegou.', 'Medicina'],
    ['la inmunidad', 'imunidade', 'substantivo', 'La inmunidad decae con el tiempo.', 'A imunidade diminui com o tempo.', 'Medicina'],
    ['la dosis', 'dosagem', 'substantivo', 'Ajusta la dosis con cuidado.', 'Ajuste a dosagem com cuidado.', 'Medicina'],
    ['la incisión', 'incisão', 'substantivo', 'La incisión cicatrizó bien.', 'A incisão cicatrizou bem.', 'Medicina'],
    ['la recaída', 'recaída', 'substantivo', 'Una recaída sigue siendo posible.', 'Uma recaída ainda é possível.', 'Medicina'],
    ['la retórica', 'retórica', 'substantivo', 'La retórica superó a la política.', 'A retórica passou à frente da política.', 'Retórica'],
    ['la persuasión', 'persuasão', 'substantivo', 'La persuasión vence a la coerción.', 'A persuasão vence a coerção.', 'Retórica'],
    ['la anécdota', 'anedota', 'substantivo', 'Una anécdota no es un dato.', 'Uma anedota não é dado.', 'Retórica'],
    ['la analogía', 'analogia', 'substantivo', 'La analogía falla aquí.', 'A analogia falha aqui.', 'Retórica'],
    ['la refutación', 'refutação', 'substantivo', 'Su refutación fue elegante.', 'A refutação dele foi elegante.', 'Retórica'],
    ['la connotación', 'conotação', 'substantivo', 'Esa palabra tiene una connotación.', 'Aquela palavra carrega uma conotação.', 'Retórica'],
    ['la réplica', 'réplica', 'substantivo', 'Preparó una réplica.', 'Ela preparou uma réplica.', 'Retórica'],
    ['la elocuencia', 'eloquência', 'substantivo', 'La elocuencia no tapa evidencia débil.', 'A eloquência não esconde evidência fraca.', 'Retórica'],
    ['el discurso público', 'discurso público', 'substantivo', 'El discurso público se ha degradado.', 'O discurso público se degradou.', 'Retórica'],
    ['la digresión', 'digressão', 'substantivo', 'Perdona la digresión.', 'Perdoe a digressão.', 'Retórica'],
  ],
  C2: [
    ['elegíaco', 'elegíaco', 'adjetivo', 'La novela tiene un tono elegíaco.', 'O romance tem um tom elegíaco.', 'Registro literário'],
    ['sepulcral', 'sepulcral', 'adjetivo', 'Habló con voz sepulcral.', 'Ele falou com uma voz sepulcral.', 'Registro literário'],
    ['idílico', 'idílico', 'adjetivo', 'Aquellos fueron días idílicos.', 'Aqueles eram dias idílicos.', 'Registro literário'],
    ['melifluo', 'melífluo', 'adjetivo', 'Su dicción meliflua cautivó a la sala.', 'A dicção melíflua dele prendeu a sala.', 'Registro literário'],
    ['quejumbroso', 'lamentoso', 'adjetivo', 'Entró una melodía quejumbrosa.', 'Uma melodia lamentosa entrou no ar.', 'Registro literário'],
    ['resplandeciente', 'resplandecente', 'adjetivo', 'Llegó resplandeciente de blanco.', 'Ela chegou resplandecente de branco.', 'Registro literário'],
    ['austero', 'austero', 'adjetivo', 'La prosa es austera y exacta.', 'A prosa é austera e exata.', 'Registro literário'],
    ['lánguido', 'lânguido', 'adjetivo', 'La tarde fue lánguida.', 'A tarde foi lânguida.', 'Registro literário'],
    ['etéreo', 'etéreo', 'adjetivo', 'La luz era casi etérea.', 'A luz era quase etérea.', 'Registro literário'],
    ['sonoro', 'sonoro', 'adjetivo', 'Su risa sonora llenó la sala.', 'A risada sonora dele encheu o salão.', 'Registro literário'],
    ['el litigio', 'litígio', 'substantivo', 'El caso acabó en litigio.', 'O caso terminou em litígio.', 'Jurídico avançado'],
    ['la jurisdicción', 'jurisdição', 'substantivo', 'El tribunal carece de jurisdicción.', 'O tribunal não tem jurisdição.', 'Jurídico avançado'],
    ['la imputación', 'imputação / denúncia formal', 'substantivo', 'La imputación tenía sesenta páginas.', 'A denúncia tinha sessenta páginas.', 'Jurídico avançado'],
    ['la culpabilidad', 'culpabilidade', 'substantivo', 'Nunca se estableció la culpabilidad.', 'A culpabilidade nunca foi estabelecida.', 'Jurídico avançado'],
    ['la presunción', 'presunção', 'substantivo', 'Rige la presunción de inocencia.', 'A presunção de inocência vale.', 'Jurídico avançado'],
    ['exculpatorio', 'excludente de culpa', 'adjetivo', 'Ocultaron pruebas exculpatorias.', 'Eles ocultaram provas excludentes de culpa.', 'Jurídico avançado'],
    ['el interdicto', 'liminar', 'substantivo', 'El juez dictó un interdicto.', 'O juiz concedeu uma liminar.', 'Jurídico avançado'],
    ['la declaración jurada', 'depoimento juramentado', 'substantivo', 'La declaración jurada duró todo el día.', 'O depoimento juramentado durou o dia todo.', 'Jurídico avançado'],
    ['dirimir', 'dirimir / julgar', 'verbo', 'Un panel dirimirá la disputa.', 'Um colegiado vai dirimir a disputa.', 'Jurídico avançado'],
    ['el ilícito civil', 'ilícito civil', 'substantivo', 'Eso configura un ilícito civil.', 'Isso configura um ilícito civil.', 'Jurídico avançado'],
    ['erudito', 'erudito', 'adjetivo', 'Las notas al pie son eruditas.', 'As notas de rodapé são eruditas.', 'Termos eruditos'],
    ['diáfano', 'diáfano / cristalino', 'adjetivo', 'Su explicación diáfana zanjó el asunto.', 'A explicação diáfana dele resolveu a questão.', 'Termos eruditos'],
    ['recóndito', 'recôndito', 'adjetivo', 'El argumento es innecesariamente recóndito.', 'O argumento é desnecessariamente recôndito.', 'Termos eruditos'],
    ['abstruso', 'abstruso', 'adjetivo', 'La teoría se volvió abstrusa.', 'A teoria ficou abstrusa.', 'Termos eruditos'],
    ['sagaz', 'sagaz', 'adjetivo', 'Fue una elección sagaz.', 'Foi uma escolha sagaz.', 'Termos eruditos'],
    ['perspicaz', 'perspicaz', 'adjetivo', 'Un lector perspicaz lo notará.', 'Um leitor perspicaz vai notar.', 'Termos eruditos'],
    ['lacónico', 'lacônico', 'adjetivo', 'Su respuesta fue lacónica.', 'A resposta dele foi lacônica.', 'Termos eruditos'],
    ['prolijo', 'prolixo', 'adjetivo', 'La introducción es prolija.', 'A introdução é prolixa.', 'Termos eruditos'],
    ['taciturno', 'taciturno', 'adjetivo', 'Permaneció taciturno todo el rato.', 'Ele permaneceu taciturno o tempo todo.', 'Termos eruditos'],
    ['locuaz', 'tagarela', 'adjetivo', 'Nuestro locuaz anfitrión no paraba.', 'Nosso anfitrião tagarela não parava.', 'Termos eruditos'],
    ['la ambivalencia', 'ambivalência', 'substantivo', 'Su ambivalencia era evidente.', 'A ambivalência dela era evidente.', 'Nuance psicológica'],
    ['el remordimiento', 'remorso', 'substantivo', 'Mintió sin remordimiento.', 'Ele mentiu sem nenhum remorso.', 'Nuance psicológica'],
    ['la aprensión', 'apreensão', 'substantivo', 'Lo abrió con aprensión.', 'Ela abriu com apreensão.', 'Nuance psicológica'],
    ['la ofensa', 'melindre / ofensa', 'substantivo', 'Se tomó el comentario como una ofensa.', 'Ele se ofendeu com o comentário.', 'Nuance psicológica'],
    ['el rencor', 'rancor', 'substantivo', 'Habló sin rencor.', 'Ela falou sem rancor.', 'Nuance psicológica'],
    ['la contrición', 'contrição', 'substantivo', 'Su contrición parecía genuina.', 'A contrição dele parecia genuína.', 'Nuance psicológica'],
    ['la soberbia', 'soberba / arrogância', 'substantivo', 'La soberbia precedió al derrumbe.', 'A soberba precedeu o colapso.', 'Nuance psicológica'],
    ['la indulgencia', 'tolerância / indulgência', 'substantivo', 'Gracias por su indulgencia.', 'Obrigado pela sua tolerância.', 'Nuance psicológica'],
    ['la magnanimidad', 'magnanimidade', 'substantivo', 'Mostró una magnanimidad inesperada.', 'Ele mostrou magnanimidade inesperada.', 'Nuance psicológica'],
    ['la timidez', 'timidez / insegurança', 'substantivo', 'Su timidez escondía talento real.', 'A timidez dela escondia talento real.', 'Nuance psicológica'],
    ['el corolario', 'corolário', 'substantivo', 'Más costes son un corolario de esa opción.', 'Custos maiores são um corolário dessa escolha.', 'Argumentação'],
    ['axiomático', 'axiomático', 'adjetivo', 'Es axiomático en este campo.', 'É axiomático nesta área.', 'Argumentação'],
    ['incontrovertible', 'incontestável', 'adjetivo', 'Los datos son incontrovertibles.', 'Os dados são incontestáveis.', 'Argumentação'],
    ['concluyente', 'conclusivo / cabal', 'adjetivo', 'Presentó un caso concluyente.', 'Ela apresentou um caso conclusivo.', 'Argumentação'],
    ['extrapolar', 'extrapolar', 'verbo', 'No extrapoles a partir de un caso.', 'Não extrapole a partir de um caso.', 'Argumentação'],
    ['el sofisma', 'sofisma', 'substantivo', 'Esa defensa es un sofisma.', 'Essa defesa é um sofisma.', 'Argumentação'],
    ['poco sincero', 'pouco sincero', 'adjetivo', 'Esa respuesta es poco sincera.', 'Essa resposta é pouco sincera.', 'Argumentação'],
    ['especioso', 'especioso', 'adjetivo', 'El razonamiento es especioso.', 'O raciocínio é especioso.', 'Argumentação'],
    ['pertinente', 'pertinente', 'adjetivo', 'Tu observación es pertinente.', 'Sua observação é pertinente.', 'Argumentação'],
    ['ipso facto', 'por isso mesmo', 'advérbio', 'No se sigue ipso facto.', 'Não decorre disso por isso mesmo.', 'Argumentação'],
    ['la verosimilitud', 'verossimilhança', 'substantivo', 'A la película le falta verosimilitud.', 'O filme carece de verossimilhança.', 'Crítica e estética'],
    ['el pastiche', 'pastiche', 'substantivo', 'El disco es un pastiche consciente.', 'O álbum é um pastiche consciente.', 'Crítica e estética'],
    ['el anticlímax', 'anticlímax', 'substantivo', 'El final cae en el anticlímax.', 'O final desaba no anticlímax.', 'Crítica e estética'],
    ['el desenlace', 'desfecho', 'substantivo', 'El desenlace pareció apresurado.', 'O desfecho pareceu apressado.', 'Crítica e estética'],
    ['la alegoría', 'alegoria', 'substantivo', 'Todo el libro es una alegoría.', 'O livro inteiro é uma alegoria.', 'Crítica e estética'],
    ['el motivo recurrente', 'motivo recorrente', 'substantivo', 'El agua es el motivo recurrente central.', 'A água é o motivo recorrente central.', 'Crítica e estética'],
    ['la hipérbole', 'hipérbole', 'substantivo', 'Eso es hipérbole, no análisis.', 'Isso é hipérbole, não análise.', 'Crítica e estética'],
    ['el patetismo', 'pathos / comoção', 'substantivo', 'La escena logra un patetismo real.', 'A cena alcança comoção verdadeira.', 'Crítica e estética'],
    ['la sátira', 'sátira', 'substantivo', 'Funciona mejor como sátira.', 'Funciona melhor como sátira.', 'Crítica e estética'],
    ['la obra completa', 'obra completa', 'substantivo', 'Esto es menor dentro de su obra completa.', 'Isto é menor dentro da obra completa dela.', 'Crítica e estética'],
  ],
};
