/** Francês — lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const FR_THEMATIC: LatinByLevel = {
  A1: [
    ['vert', 'verde', 'adjetivo', "L'herbe est verte.", 'A grama é verde.', 'Cores e formas'],
    ['jaune', 'amarelo', 'adjetivo', "J'aime les fleurs jaunes.", 'Gosto de flores amarelas.', 'Cores e formas'],
    ['noir', 'preto', 'adjetivo', 'Il porte un manteau noir.', 'Ele usa um casaco preto.', 'Cores e formas'],
    ['blanc', 'branco', 'adjetivo', 'Les murs sont blancs.', 'As paredes são brancas.', 'Cores e formas'],
    ['orange', 'laranja', 'adjetivo', 'Elle a un sac orange.', 'Ela tem uma bolsa laranja.', 'Cores e formas'],
    ['violet', 'roxo', 'adjetivo', 'Le ciel est devenu violet.', 'O céu ficou roxo.', 'Cores e formas'],
    ['marron', 'marrom', 'adjetivo', 'Mes chaussures sont marron.', 'Meus sapatos são marrons.', 'Cores e formas'],
    ['rose', 'rosa', 'adjetivo', 'Le bébé a une couverture rose.', 'O bebê tem um cobertor rosa.', 'Cores e formas'],
    ['le cercle', 'círculo', 'substantivo', 'Dessine un cercle ici.', 'Desenhe um círculo aqui.', 'Cores e formas'],
    ['le carré', 'quadrado', 'substantivo', 'La boîte est un carré.', 'A caixa é um quadrado.', 'Cores e formas'],
    ['la chemise', 'camisa', 'substantivo', 'Cette chemise est propre.', 'Esta camisa está limpa.', 'Roupas'],
    ['le pantalon', 'calça', 'substantivo', 'Ce pantalon est neuf.', 'Esta calça é nova.', 'Roupas'],
    ['les chaussures', 'sapatos', 'substantivo', 'Mes chaussures sont mouillées.', 'Meus sapatos estão molhados.', 'Roupas'],
    ['la robe', 'vestido', 'substantivo', 'Elle a acheté une robe.', 'Ela comprou um vestido.', 'Roupas'],
    ['la veste', 'jaqueta', 'substantivo', 'Prends ta veste.', 'Leve sua jaqueta.', 'Roupas'],
    ['le chapeau', 'chapéu', 'substantivo', 'Il a perdu son chapeau.', 'Ele perdeu o chapéu.', 'Roupas'],
    ['les chaussettes', 'meias', 'substantivo', "J'ai besoin de chaussettes propres.", 'Preciso de meias limpas.', 'Roupas'],
    ['le manteau', 'casaco', 'substantivo', 'Mets un manteau aujourd’hui.', 'Use um casaco hoje.', 'Roupas'],
    ['la jupe', 'saia', 'substantivo', 'Cette jupe est longue.', 'Aquela saia é longa.', 'Roupas'],
    ['les lunettes', 'óculos', 'substantivo', "J'ai oublié mes lunettes.", 'Esqueci meus óculos.', 'Roupas'],
    ['le soleil', 'sol', 'substantivo', 'Le soleil est fort.', 'O sol está forte.', 'Clima e natureza'],
    ['la pluie', 'chuva', 'substantivo', "La pluie s'est arrêtée.", 'A chuva parou.', 'Clima e natureza'],
    ['la neige', 'neve', 'substantivo', 'La neige est épaisse.', 'A neve está funda.', 'Clima e natureza'],
    ['le vent', 'vento', 'substantivo', 'Le vent est fort.', 'O vento está forte.', 'Clima e natureza'],
    ['le nuage', 'nuvem', 'substantivo', 'Il y a un nuage.', 'Há uma nuvem.', 'Clima e natureza'],
    ['l’arbre', 'árvore', 'substantivo', "L'arbre est vieux.", 'A árvore é velha.', 'Clima e natureza'],
    ['la fleur', 'flor', 'substantivo', 'Elle aime cette fleur.', 'Ela gosta desta flor.', 'Clima e natureza'],
    ['le ciel', 'céu', 'substantivo', 'Le ciel est dégagé.', 'O céu está limpo.', 'Clima e natureza'],
    ['la plage', 'praia', 'substantivo', 'Nous allons à la plage.', 'Nós vamos à praia.', 'Clima e natureza'],
    ['la montagne', 'montanha', 'substantivo', 'La montagne est haute.', 'A montanha é alta.', 'Clima e natureza'],
    ['la tête', 'cabeça', 'substantivo', "J'ai mal à la tête.", 'Minha cabeça dói.', 'Corpo'],
    ['la main', 'mão', 'substantivo', 'Donne-moi la main.', 'Me dê sua mão.', 'Corpo'],
    ['le pied', 'pé', 'substantivo', "J'ai froid au pied.", 'Meu pé está frio.', 'Corpo'],
    ['l’œil', 'olho', 'substantivo', 'Elle a un œil vert.', 'Ela tem um olho verde.', 'Corpo'],
    ['l’oreille', 'orelha / ouvido', 'substantivo', "J'ai mal à l'oreille.", 'Meu ouvido dói.', 'Corpo'],
    ['la bouche', 'boca', 'substantivo', 'Ouvre la bouche.', 'Abra a boca.', 'Corpo'],
    ['le nez', 'nariz', 'substantivo', 'Il a le nez rouge.', 'O nariz dele está vermelho.', 'Corpo'],
    ['les cheveux', 'cabelo', 'substantivo', 'Elle a les cheveux longs.', 'O cabelo dela é longo.', 'Corpo'],
    ['le bras', 'braço', 'substantivo', "Il s'est cassé le bras.", 'Ele quebrou o braço.', 'Corpo'],
    ['la jambe', 'perna', 'substantivo', "J'ai la jambe fatiguée.", 'Minha perna está cansada.', 'Corpo'],
    ['le pain', 'pão', 'substantivo', 'Je mange du pain tous les jours.', 'Eu como pão todo dia.', 'Comida e bebida'],
    ['le lait', 'leite', 'substantivo', 'Le lait est froid.', 'O leite está frio.', 'Comida e bebida'],
    ['le café', 'café', 'substantivo', 'Elle boit du café.', 'Ela bebe café.', 'Comida e bebida'],
    ['le riz', 'arroz', 'substantivo', 'Nous mangeons du riz à midi.', 'Comemos arroz no almoço.', 'Comida e bebida'],
    ['la viande', 'carne', 'substantivo', 'Il ne mange pas de viande.', 'Ele não come carne.', 'Comida e bebida'],
    ['le fruit', 'fruta', 'substantivo', 'Achète des fruits.', 'Compre frutas.', 'Comida e bebida'],
    ['l’œuf', 'ovo', 'substantivo', 'Je veux un œuf.', 'Quero um ovo.', 'Comida e bebida'],
    ['le fromage', 'queijo', 'substantivo', 'Ce fromage est bon.', 'Este queijo é bom.', 'Comida e bebida'],
    ['le sucre', 'açúcar', 'substantivo', 'Sans sucre, s’il vous plaît.', 'Sem açúcar, por favor.', 'Comida e bebida'],
    ['le sel', 'sal', 'substantivo', 'Passe-moi le sel.', 'Me passe o sal.', 'Comida e bebida'],
    ['le matin', 'manhã', 'substantivo', 'Je travaille le matin.', 'Eu trabalho de manhã.', 'Tempo e rotina'],
    ['l’après-midi', 'tarde', 'substantivo', 'À cet après-midi.', 'Até a tarde.', 'Tempo e rotina'],
    ['le soir', 'fim de tarde / noite', 'substantivo', 'Nous mangeons le soir.', 'Nós comemos à noite.', 'Tempo e rotina'],
    ['la nuit', 'noite', 'substantivo', 'La nuit est calme.', 'A noite está calma.', 'Tempo e rotina'],
    ['la semaine', 'semana', 'substantivo', 'La semaine est longue.', 'A semana é longa.', 'Tempo e rotina'],
    ['le mois', 'mês', 'substantivo', 'Ce mois est chargé.', 'Este mês está cheio.', 'Tempo e rotina'],
    ['aujourd’hui', 'hoje', 'advérbio', 'Je suis fatigué aujourd’hui.', 'Estou cansado hoje.', 'Tempo e rotina'],
    ['hier', 'ontem', 'advérbio', 'Il a plu hier.', 'Choveu ontem.', 'Tempo e rotina'],
    ['l’heure', 'hora', 'substantivo', 'Attends une heure.', 'Espere uma hora.', 'Tempo e rotina'],
    ['le week-end', 'fim de semana', 'substantivo', 'Je me repose le week-end.', 'Eu descanso no fim de semana.', 'Tempo e rotina'],
  ],
  A2: [
    ['le vol', 'voo', 'substantivo', 'Notre vol part à six heures.', 'Nosso voo sai às seis.', 'Viagem'],
    ['le passeport', 'passaporte', 'substantivo', 'Montrez-moi votre passeport.', 'Me mostre seu passaporte.', 'Viagem'],
    ['les bagages', 'bagagem', 'substantivo', 'Mes bagages sont lourds.', 'Minha bagagem está pesada.', 'Viagem'],
    ['le billet', 'passagem / bilhete', 'substantivo', "J'ai acheté le billet en ligne.", 'Comprei a passagem pela internet.', 'Viagem'],
    ['le retard', 'atraso', 'substantivo', 'Il y a eu un long retard.', 'Houve um atraso longo.', 'Viagem'],
    ['l’aéroport', 'aeroporto', 'substantivo', "L'aéroport est loin.", 'O aeroporto é longe.', 'Viagem'],
    ['la valise', 'mala', 'substantivo', 'Fais ta valise ce soir.', 'Faça sua mala hoje à noite.', 'Viagem'],
    ['le départ', 'partida', 'substantivo', "Vérifie l'heure de départ.", 'Confira o horário de partida.', 'Viagem'],
    ['l’arrivée', 'chegada', 'substantivo', "L'arrivée s'est bien passée.", 'A chegada foi tranquila.', 'Viagem'],
    ['la carte d’embarquement', 'cartão de embarque', 'substantivo', 'Garde ta carte d’embarquement.', 'Guarde seu cartão de embarque.', 'Viagem'],
    ['le menu', 'cardápio', 'substantivo', 'Je peux voir le menu ?', 'Posso ver o cardápio?', 'Restaurante'],
    ['le serveur', 'garçom', 'substantivo', 'Le serveur arrive.', 'O garçom está vindo.', 'Restaurante'],
    ['le pourboire', 'gorjeta', 'substantivo', 'Nous avons laissé un bon pourboire.', 'Deixamos uma boa gorjeta.', 'Restaurante'],
    ['le dessert', 'sobremesa', 'substantivo', 'Je veux un dessert.', 'Quero sobremesa.', 'Restaurante'],
    ['l’entrée', 'entrada (prato)', 'substantivo', "L'entrée était petite.", 'A entrada era pequena.', 'Restaurante'],
    ['la réservation', 'reserva', 'substantivo', "J'ai fait une réservation.", 'Fiz uma reserva.', 'Restaurante'],
    ['la serviette', 'guardanapo', 'substantivo', 'Passe-moi une serviette.', 'Me passe um guardanapo.', 'Restaurante'],
    ['le plateau', 'bandeja', 'substantivo', 'Mets-le sur le plateau.', 'Coloque na bandeja.', 'Restaurante'],
    ['le goût', 'sabor', 'substantivo', 'Le goût est étrange.', 'O sabor está estranho.', 'Restaurante'],
    ['épicé', 'picante', 'adjetivo', 'Ce plat est épicé.', 'Este prato é picante.', 'Restaurante'],
    ['les espèces', 'dinheiro (em espécie)', 'substantivo', "Je n'ai que des espèces.", 'Só tenho dinheiro em espécie.', 'Compras'],
    ['la monnaie', 'troco', 'substantivo', 'Gardez la monnaie.', 'Fique com o troco.', 'Compras'],
    ['la taille', 'tamanho (roupa)', 'substantivo', 'Vous avez une taille au-dessus ?', 'Tem um tamanho maior?', 'Compras'],
    ['la bonne affaire', 'pechincha', 'substantivo', 'Ce manteau était une bonne affaire.', 'Aquele casaco foi uma pechincha.', 'Compras'],
    ['le caissier', 'caixa (pessoa)', 'substantivo', 'Demande au caissier.', 'Pergunte ao caixa.', 'Compras'],
    ['le rayon', 'seção (de loja)', 'substantivo', 'Le lait est au rayon trois.', 'O leite está na seção três.', 'Compras'],
    ['l’étagère', 'prateleira', 'substantivo', "L'étagère est vide.", 'A prateleira está vazia.', 'Compras'],
    ['les soldes', 'liquidação', 'substantivo', 'Les chaussures sont en soldes.', 'Os sapatos estão em liquidação.', 'Compras'],
    ['le portefeuille', 'carteira', 'substantivo', "J'ai laissé mon portefeuille chez moi.", 'Deixei minha carteira em casa.', 'Compras'],
    ['la marque', 'marca', 'substantivo', 'Je fais confiance à cette marque.', 'Confio nesta marca.', 'Compras'],
    ['la toux', 'tosse', 'substantivo', 'Elle a une mauvaise toux.', 'Ela está com uma tosse feia.', 'Saúde'],
    ['le mal de tête', 'dor de cabeça', 'substantivo', "J'ai mal de tête.", 'Estou com dor de cabeça.', 'Saúde'],
    ['le comprimé', 'comprimido', 'substantivo', 'Prends un comprimé par jour.', 'Tome um comprimido por dia.', 'Saúde'],
    ['l’infirmier', 'enfermeiro', 'substantivo', "L'infirmier était gentil.", 'O enfermeiro foi gentil.', 'Saúde'],
    ['la blessure', 'lesão / ferimento', 'substantivo', 'La blessure était grave.', 'A lesão foi séria.', 'Saúde'],
    ['le repos', 'descanso', 'substantivo', 'Tu as besoin de repos.', 'Você precisa de descanso.', 'Saúde'],
    ['le pansement', 'curativo', 'substantivo', 'Mets un pansement dessus.', 'Coloque um curativo nisso.', 'Saúde'],
    ['étourdi', 'tonto', 'adjetivo', 'Je me sens étourdi.', 'Estou me sentindo tonto.', 'Saúde'],
    ['la clinique', 'clínica', 'substantivo', 'La clinique ouvre à huit heures.', 'A clínica abre às oito.', 'Saúde'],
    ['la douleur', 'dor', 'substantivo', "J'ai une douleur au dos.", 'Tenho uma dor nas costas.', 'Saúde'],
    ['le pont', 'ponte', 'substantivo', 'Traverse le pont.', 'Atravesse a ponte.', 'Cidade'],
    ['la place', 'praça', 'substantivo', 'On s’est vus sur la place.', 'Nos encontramos na praça.', 'Cidade'],
    ['le coin', 'esquina', 'substantivo', 'Tourne au coin.', 'Vire na esquina.', 'Cidade'],
    ['la circulation', 'trânsito', 'substantivo', 'La circulation est terrible.', 'O trânsito está terrível.', 'Cidade'],
    ['le métro', 'metrô', 'substantivo', 'Prends le métro.', 'Pegue o metrô.', 'Cidade'],
    ['l’arrêt', 'parada (ônibus)', 'substantivo', "Descends au prochain arrêt.", 'Desça na próxima parada.', 'Cidade'],
    ['la carte', 'mapa', 'substantivo', 'Regarde la carte.', 'Olhe o mapa.', 'Cidade'],
    ['le chemin', 'caminho', 'substantivo', 'Suis ce chemin.', 'Siga este caminho.', 'Cidade'],
    ['le portail', 'portão', 'substantivo', 'Le portail est fermé à clé.', 'O portão está trancado.', 'Cidade'],
    ['le passage piéton', 'faixa de pedestres', 'substantivo', 'Utilise le passage piéton.', 'Use a faixa de pedestres.', 'Cidade'],
    ['la lessive', 'roupa para lavar', 'substantivo', 'Je fais la lessive le dimanche.', 'Eu lavo a roupa no domingo.', 'Casa e tarefas'],
    ['la vaisselle', 'louça', 'substantivo', 'Il fait la vaisselle.', 'Ele lava a louça.', 'Casa e tarefas'],
    ['le balai', 'vassoura', 'substantivo', 'Où est le balai ?', 'Onde está a vassoura?', 'Casa e tarefas'],
    ['la poubelle', 'lixo / lixeira', 'substantivo', 'Sors la poubelle.', 'Leve o lixo para fora.', 'Casa e tarefas'],
    ['la serviette de bain', 'toalha de banho', 'substantivo', 'La serviette de bain est mouillée.', 'A toalha de banho está molhada.', 'Casa e tarefas'],
    ['la couverture', 'cobertor', 'substantivo', "J'ai besoin d'une autre couverture.", 'Preciso de outro cobertor.', 'Casa e tarefas'],
    ['le tiroir', 'gaveta', 'substantivo', "C'est dans le tiroir.", 'Está na gaveta.', 'Casa e tarefas'],
    ['le placard', 'armário', 'substantivo', 'Range-le dans le placard.', 'Guarde no armário.', 'Casa e tarefas'],
    ['l’évier', 'pia', 'substantivo', "L'évier est bouché.", 'A pia está entupida.', 'Casa e tarefas'],
    ['le miroir', 'espelho', 'substantivo', 'Regarde-toi dans le miroir.', 'Olhe no espelho.', 'Casa e tarefas'],
  ],
  B1: [
    ['l’entretien d’embauche', 'entrevista de emprego', 'substantivo', "L'entretien d'embauche s'est bien passé.", 'A entrevista de emprego correu bem.', 'Trabalho'],
    ['le CV', 'currículo', 'substantivo', 'Envoie-moi ton CV.', 'Me mande seu currículo.', 'Trabalho'],
    ['les heures supplémentaires', 'horas extras', 'substantivo', 'Elle a encore fait des heures supplémentaires.', 'Ela fez hora extra de novo.', 'Trabalho'],
    ['le stage', 'estágio', 'substantivo', 'Il a décroché un stage.', 'Ele conseguiu um estágio.', 'Trabalho'],
    ['le supérieur', 'superior / chefe', 'substantivo', 'Parle à ton supérieur.', 'Fale com seu chefe.', 'Trabalho'],
    ['la tâche', 'tarefa', 'substantivo', 'Cette tâche prend deux heures.', 'Esta tarefa leva duas horas.', 'Trabalho'],
    ['la réunion', 'reunião', 'substantivo', 'La réunion a été annulée.', 'A reunião foi cancelada.', 'Trabalho'],
    ['le personnel', 'quadro de funcionários', 'substantivo', 'Le personnel est sympathique.', 'A equipe é simpática.', 'Trabalho'],
    ['le contrat', 'contrato', 'substantivo', "Lis d'abord le contrat.", 'Leia o contrato primeiro.', 'Trabalho'],
    ['la mutation', 'transferência (de cargo)', 'substantivo', 'Il a demandé une mutation.', 'Ele pediu uma transferência.', 'Trabalho'],
    ['la mise à jour', 'atualização', 'substantivo', 'Installe la mise à jour.', 'Instale a atualização.', 'Tecnologia'],
    ['le mot de passe', 'senha', 'substantivo', "J'ai oublié mon mot de passe.", 'Esqueci minha senha.', 'Tecnologia'],
    ['la sauvegarde', 'cópia de segurança', 'substantivo', "Fais d'abord une sauvegarde.", 'Faça uma cópia de segurança antes.', 'Tecnologia'],
    ['l’appareil', 'aparelho / dispositivo', 'substantivo', 'Cet appareil est rapide.', 'Este aparelho é rápido.', 'Tecnologia'],
    ['l’écran', 'tela', 'substantivo', "L'écran est cassé.", 'A tela está quebrada.', 'Tecnologia'],
    ['télécharger', 'baixar', 'verbo', 'Télécharge le fichier maintenant.', 'Baixe o arquivo agora.', 'Tecnologia'],
    ['le réseau', 'rede', 'substantivo', 'Le réseau est en panne.', 'A rede está fora do ar.', 'Tecnologia'],
    ['le navigateur', 'navegador', 'substantivo', 'Ouvre un nouvel onglet du navigateur.', 'Abra uma nova aba do navegador.', 'Tecnologia'],
    ['le dossier', 'pasta', 'substantivo', 'Enregistre-le dans ce dossier.', 'Salve nesta pasta.', 'Tecnologia'],
    ['planter', 'travar (programa)', 'verbo', "L'application a encore planté.", 'O aplicativo travou de novo.', 'Tecnologia'],
    ['recycler', 'reciclar', 'verbo', 'Ici, on recycle le plastique.', 'Aqui nós reciclamos plástico.', 'Meio ambiente'],
    ['la pollution', 'poluição', 'substantivo', 'La pollution a empiré.', 'A poluição piorou.', 'Meio ambiente'],
    ['le déchet', 'resíduo', 'substantivo', 'Le déchet alimentaire est un problème.', 'O resíduo alimentar é um problema.', 'Meio ambiente'],
    ['le climat', 'clima', 'substantivo', 'Le climat change.', 'O clima está mudando.', 'Meio ambiente'],
    ['l’énergie', 'energia', 'substantivo', "L'énergie solaire est moins chère maintenant.", 'A energia solar está mais barata agora.', 'Meio ambiente'],
    ['la forêt', 'floresta', 'substantivo', 'La forêt est protégée.', 'A floresta é protegida.', 'Meio ambiente'],
    ['l’espèce', 'espécie', 'substantivo', 'Cette espèce est rare.', 'Esta espécie é rara.', 'Meio ambiente'],
    ['la sécheresse', 'seca', 'substantivo', 'La sécheresse a duré des mois.', 'A seca durou meses.', 'Meio ambiente'],
    ['l’inondation', 'enchente', 'substantivo', "L'inondation a abîmé la route.", 'A enchente danificou a estrada.', 'Meio ambiente'],
    ['le rejet', 'despejo (poluente)', 'substantivo', 'Le rejet a atteint la rivière.', 'O despejo chegou ao rio.', 'Meio ambiente'],
    ['l’arbitre', 'árbitro', 'substantivo', "L'arbitre a arrêté le match.", 'O árbitro parou o jogo.', 'Esportes'],
    ['le tournoi', 'torneio', 'substantivo', 'Elle a gagné le tournoi.', 'Ela ganhou o torneio.', 'Esportes'],
    ['l’adversaire', 'adversário', 'substantivo', 'Son adversaire était plus rapide.', 'O adversário dele era mais rápido.', 'Esportes'],
    ['le coéquipier', 'companheiro de equipe', 'substantivo', 'Mon coéquipier a marqué.', 'Meu companheiro de equipe marcou.', 'Esportes'],
    ['l’entraîneur', 'treinador', 'substantivo', "L'entraîneur était en colère.", 'O treinador estava bravo.', 'Esportes'],
    ['le score', 'placar', 'substantivo', 'Quel est le score ?', 'Qual é o placar?', 'Esportes'],
    ['le match', 'partida', 'substantivo', 'Le match commence à huit heures.', 'A partida começa às oito.', 'Esportes'],
    ['l’entraînement', 'treino', 'substantivo', "L'entraînement est tous les matins.", 'O treino é toda manhã.', 'Esportes'],
    ['l’endurance', 'resistência física', 'substantivo', 'Il a une grande endurance.', 'Ele tem muita resistência.', 'Esportes'],
    ['le championnat', 'campeonato', 'substantivo', 'Ils ont perdu le championnat.', 'Eles perderam o campeonato.', 'Esportes'],
    ['se disputer', 'discutir / brigar', 'verbo', 'Ils se disputent pour de l’argent.', 'Eles brigam por dinheiro.', 'Relacionamentos'],
    ['s’excuser', 'pedir desculpas', 'verbo', "Il s'est excusé rapidement.", 'Ele pediu desculpas rápido.', 'Relacionamentos'],
    ['la confiance', 'confiança', 'substantivo', 'La confiance prend du temps.', 'Confiança leva tempo.', 'Relacionamentos'],
    ['jaloux', 'ciumento', 'adjetivo', 'Elle devient jalouse facilement.', 'Ela fica com ciúmes fácil.', 'Relacionamentos'],
    ['loyal', 'leal', 'adjetivo', "C'est un ami loyal.", 'Ele é um amigo leal.', 'Relacionamentos'],
    ['les ragots', 'fofoca', 'substantivo', 'Je déteste les ragots de bureau.', 'Odeio fofoca de escritório.', 'Relacionamentos'],
    ['le conseil', 'conselho', 'substantivo', "C'était un bon conseil.", 'Aquilo foi um bom conselho.', 'Relacionamentos'],
    ['le coup de main', 'ajuda / força', 'substantivo', 'Tu peux me donner un coup de main ?', 'Você pode me dar uma força?', 'Relacionamentos'],
    ['la brouille', 'desentendimento', 'substantivo', 'Ils ont eu une brouille idiote.', 'Eles tiveram um desentendimento bobo.', 'Relacionamentos'],
    ['le compromis', 'acordo mútuo', 'substantivo', 'Nous avons trouvé un compromis.', 'Chegamos a um acordo.', 'Relacionamentos'],
    ['le budget', 'orçamento', 'substantivo', 'Respecte le budget.', 'Siga o orçamento.', 'Dinheiro'],
    ['l’épargne', 'poupança', 'substantivo', "Elle a utilisé son épargne.", 'Ela usou a poupança.', 'Dinheiro'],
    ['le prêt', 'empréstimo', 'substantivo', 'Il a pris un prêt.', 'Ele fez um empréstimo.', 'Dinheiro'],
    ['la dette', 'dívida', 'substantivo', 'Ils ont remboursé la dette.', 'Eles quitaram a dívida.', 'Dinheiro'],
    ['la dépense', 'despesa', 'substantivo', 'Le loyer est ma plus grosse dépense.', 'O aluguel é minha maior despesa.', 'Dinheiro'],
    ['les intérêts', 'juros', 'substantivo', 'Les intérêts sont trop élevés.', 'Os juros estão altos demais.', 'Dinheiro'],
    ['investir', 'investir', 'verbo', "Ils investissent dans l'immobilier.", 'Eles investem em imóveis.', 'Dinheiro'],
    ['le crédit immobilier', 'financiamento imobiliário', 'substantivo', 'Nous avons un crédit immobilier.', 'Nós temos um financiamento imobiliário.', 'Dinheiro'],
    ['l’assurance', 'seguro', 'substantivo', "L'assurance auto coûte cher.", 'O seguro do carro é caro.', 'Dinheiro'],
    ['le salaire minimum', 'salário mínimo', 'substantivo', 'Le salaire minimum a augmenté.', 'O salário mínimo subiu.', 'Dinheiro'],
  ],
  B2: [
    ['la campagne', 'campanha', 'substantivo', 'La campagne a duré six semaines.', 'A campanha durou seis semanas.', 'Política'],
    ['l’électorat', 'eleitorado', 'substantivo', "L'électorat est divisé.", 'O eleitorado está dividido.', 'Política'],
    ['la législation', 'legislação', 'substantivo', 'Une nouvelle législation est passée.', 'Uma nova legislação foi aprovada.', 'Política'],
    ['le lobbying', 'lobby', 'substantivo', 'Le lobbying a façonné la loi.', 'O lobby moldou a lei.', 'Política'],
    ['la corruption', 'corrupção', 'substantivo', 'La corruption sape la confiance.', 'A corrupção corrói a confiança.', 'Política'],
    ['le référendum', 'referendo', 'substantivo', 'Ils ont convoqué un référendum.', 'Eles convocaram um referendo.', 'Política'],
    ['la coalition', 'coalizão', 'substantivo', "La coalition s'est effondrée.", 'A coalizão desmoronou.', 'Política'],
    ['le bulletin de vote', 'cédula de votação', 'substantivo', 'Ton bulletin de vote est secret.', 'Seu voto é secreto.', 'Política'],
    ['la circonscription', 'distrito eleitoral', 'substantivo', 'Elle a visité sa circonscription.', 'Ela visitou seu distrito eleitoral.', 'Política'],
    ['le mandat', 'mandato', 'substantivo', 'Ils revendiquent un mandat clair.', 'Eles alegam um mandato claro.', 'Política'],
    ['l’inflation', 'inflação', 'substantivo', "L'inflation a ralenti le mois dernier.", 'A inflação desacelerou no mês passado.', 'Economia'],
    ['la récession', 'recessão', 'substantivo', 'Le pays est entré en récession.', 'O país entrou em recessão.', 'Economia'],
    ['la subvention', 'subsídio', 'substantivo', 'La subvention a été supprimée.', 'O subsídio foi cortado.', 'Economia'],
    ['le droit de douane', 'tarifa alfandegária', 'substantivo', 'Ils ont imposé un droit de douane.', 'Impuseram uma tarifa alfandegária.', 'Economia'],
    ['l’excédent', 'superávit', 'substantivo', 'Le budget affiche un excédent.', 'O orçamento mostra um superávit.', 'Economia'],
    ['le déficit', 'déficit', 'substantivo', 'Le déficit continue de croître.', 'O déficit continua crescendo.', 'Economia'],
    ['l’offre', 'oferta', 'substantivo', "L'offre ne suit pas la demande.", 'A oferta não atende à procura.', 'Economia'],
    ['la demande', 'procura', 'substantivo', 'La demande a chuté brutalement.', 'A procura caiu bruscamente.', 'Economia'],
    ['le monopole', 'monopólio', 'substantivo', 'Ils détiennent presque un monopole.', 'Eles têm quase um monopólio.', 'Economia'],
    ['l’austérité', 'austeridade', 'substantivo', "L'austérité a frappé les services publics.", 'A austeridade prejudicou os serviços públicos.', 'Economia'],
    ['l’expérience scientifique', 'experimento', 'substantivo', "L'expérience scientifique a échoué deux fois.", 'O experimento falhou duas vezes.', 'Ciência'],
    ['la preuve', 'prova / evidência', 'substantivo', 'Il y a des preuves solides.', 'Há evidências sólidas.', 'Ciência'],
    ['l’échantillon', 'amostra', 'substantivo', "L'échantillon était trop petit.", 'A amostra era pequena demais.', 'Ciência'],
    ['le laboratoire', 'laboratório', 'substantivo', 'Elle travaille dans un laboratoire.', 'Ela trabalha num laboratório.', 'Ciência'],
    ['la molécule', 'molécula', 'substantivo', "L'eau est une molécule simple.", 'A água é uma molécula simples.', 'Ciência'],
    ['le génome', 'genoma', 'substantivo', 'Ils ont cartographié le génome.', 'Eles mapearam o genoma.', 'Ciência'],
    ['le vaccin', 'vacina', 'substantivo', 'Le vaccin fonctionne bien.', 'A vacina funciona bem.', 'Ciência'],
    ['le microbe', 'micróbio', 'substantivo', 'Ce microbe est inoffensif.', 'Este micróbio é inofensivo.', 'Ciência'],
    ['le rayonnement', 'radiação', 'substantivo', 'Les niveaux de rayonnement sont normaux.', 'Os níveis de radiação estão normais.', 'Ciência'],
    ['le télescope', 'telescópio', 'substantivo', 'Le télescope a trouvé une planète.', 'O telescópio encontrou um planeta.', 'Ciência'],
    ['le titre', 'manchete', 'substantivo', 'Le titre était trompeur.', 'A manchete era enganosa.', 'Mídia'],
    ['la couverture médiatique', 'cobertura jornalística', 'substantivo', 'La couverture médiatique était biaisée.', 'A cobertura foi tendenciosa.', 'Mídia'],
    ['la censure', 'censura', 'substantivo', "La censure a augmenté l'an dernier.", 'A censura aumentou no ano passado.', 'Mídia'],
    ['la propagande', 'propaganda ideológica', 'substantivo', "C'est de la pure propagande.", 'Isso é pura propaganda.', 'Mídia'],
    ['la diffusion', 'transmissão', 'substantivo', 'La diffusion a touché des millions.', 'A transmissão alcançou milhões.', 'Mídia'],
    ['le journaliste', 'jornalista', 'substantivo', 'La journaliste a vérifié ses sources.', 'A jornalista checou suas fontes.', 'Mídia'],
    ['l’éditorial', 'editorial', 'substantivo', "L'éditorial a critiqué le plan.", 'O editorial criticou o plano.', 'Mídia'],
    ['la presse à sensation', 'imprensa sensacionalista', 'substantivo', 'Ne crois pas la presse à sensation.', 'Não acredite na imprensa sensacionalista.', 'Mídia'],
    ['le public', 'público', 'substantivo', 'Le public était hostile.', 'O público estava hostil.', 'Mídia'],
    ['la source', 'fonte', 'substantivo', 'Cite ta source.', 'Cite sua fonte.', 'Mídia'],
    ['l’empathie', 'empatia', 'substantivo', "L'empathie peut s'apprendre.", 'A empatia pode ser ensinada.', 'Psicologia'],
    ['l’anxiété', 'ansiedade', 'substantivo', "L'anxiété perturbe le sommeil.", 'A ansiedade afeta o sono.', 'Psicologia'],
    ['le traumatisme', 'trauma', 'substantivo', 'Le traumatisme a duré des années.', 'O trauma durou anos.', 'Psicologia'],
    ['la motivation', 'motivação', 'substantivo', 'La motivation s’éteint sans résultats.', 'A motivação some sem resultados.', 'Psicologia'],
    ['la perception', 'percepção', 'substantivo', 'La perception façonne la mémoire.', 'A percepção molda a memória.', 'Psicologia'],
    ['le comportement', 'comportamento', 'substantivo', 'Son comportement a changé brusquement.', 'O comportamento dele mudou de repente.', 'Psicologia'],
    ['l’instinct', 'instinto', 'substantivo', 'Fie-toi à ton instinct ici.', 'Confie no seu instinto aqui.', 'Psicologia'],
    ['l’humeur', 'humor / estado de espírito', 'substantivo', 'Son humeur s’est améliorée.', 'O humor dela melhorou.', 'Psicologia'],
    ['l’estime de soi', 'autoestima', 'substantivo', "Une faible estime de soi est courante.", 'Baixa autoestima é comum.', 'Psicologia'],
    ['le ressentiment', 'ressentimento', 'substantivo', 'Le ressentiment a grandi lentement.', 'O ressentimento cresceu devagar.', 'Psicologia'],
    ['le procès', 'processo judicial', 'substantivo', 'Ils ont intenté un procès.', 'Eles entraram com um processo.', 'Direito'],
    ['le verdict', 'veredicto', 'substantivo', 'Le verdict a surpris tout le monde.', 'O veredicto surpreendeu todos.', 'Direito'],
    ['le témoignage', 'depoimento', 'substantivo', 'Son témoignage a été décisif.', 'O depoimento dela foi decisivo.', 'Direito'],
    ['le témoin', 'testemunha', 'substantivo', 'Le témoin a changé de version.', 'A testemunha mudou a versão.', 'Direito'],
    ['le prévenu', 'réu', 'substantivo', 'Le prévenu est resté silencieux.', 'O réu permaneceu calado.', 'Direito'],
    ['l’avocat', 'advogado', 'substantivo', 'Appelle ton avocat.', 'Ligue para seu advogado.', 'Direito'],
    ['le plaidoyer', 'alegação de defesa', 'substantivo', 'Son plaidoyer a convaincu le jury.', 'A alegação de defesa dele convenceu o júri.', 'Direito'],
    ['l’appel', 'recurso judicial', 'substantivo', "Ils ont perdu l'appel.", 'Eles perderam o recurso.', 'Direito'],
    ['la garde', 'guarda (de filhos)', 'substantivo', 'Elle a obtenu la garde.', 'Ela ganhou a guarda.', 'Direito'],
    ['la loi écrite', 'lei escrita', 'substantivo', 'La loi écrite est dépassée.', 'A lei escrita está ultrapassada.', 'Direito'],
  ],
  C1: [
    ['l’hypothèse', 'hipótese', 'substantivo', "L'hypothèse n'a pas tenu.", 'A hipótese não se sustentou.', 'Pesquisa acadêmica'],
    ['la méthodologie', 'metodologia', 'substantivo', 'Décris clairement ta méthodologie.', 'Descreva sua metodologia com clareza.', 'Pesquisa acadêmica'],
    ['la corrélation', 'correlação', 'substantivo', "Corrélation n'est pas causalité.", 'Correlação não é causalidade.', 'Pesquisa acadêmica'],
    ['la variable', 'variável', 'substantivo', 'Contrôle cette variable.', 'Controle essa variável.', 'Pesquisa acadêmica'],
    ['empirique', 'empírico', 'adjetivo', "Il nous faut un appui empirique.", 'Precisamos de respaldo empírico.', 'Pesquisa acadêmica'],
    ['l’évaluation par les pairs', 'revisão por pares', 'substantivo', "L'évaluation par les pairs a repéré l'erreur.", 'A revisão por pares pegou o erro.', 'Pesquisa acadêmica'],
    ['longitudinal', 'longitudinal', 'adjetivo', "C'était une étude longitudinale.", 'Foi um estudo longitudinal.', 'Pesquisa acadêmica'],
    ['la réplication', 'replicação', 'substantivo', 'La réplication a échoué deux fois.', 'A replicação falhou duas vezes.', 'Pesquisa acadêmica'],
    ['l’inférence', 'inferência', 'substantivo', 'Cette inférence est trop large.', 'Essa inferência é ampla demais.', 'Pesquisa acadêmica'],
    ['le paradigme', 'paradigma', 'substantivo', 'Le paradigme a changé lentement.', 'O paradigma mudou devagar.', 'Pesquisa acadêmica'],
    ['la partie prenante', 'parte interessada', 'substantivo', 'Consulte chaque partie prenante.', 'Consulte cada parte interessada.', 'Negócios'],
    ['l’acquisition', 'aquisição', 'substantivo', "L'acquisition a été conclue en mai.", 'A aquisição foi concluída em maio.', 'Negócios'],
    ['la fusion', 'fusão', 'substantivo', 'La fusion a rencontré des résistances.', 'A fusão enfrentou resistência.', 'Negócios'],
    ['le chiffre d’affaires', 'faturamento', 'substantivo', "Le chiffre d'affaires a grimpé de douze pour cent.", 'O faturamento cresceu doze por cento.', 'Negócios'],
    ['la responsabilité civile', 'responsabilidade civil', 'substantivo', 'Cette clause crée une responsabilité civile.', 'Aquela cláusula cria responsabilidade civil.', 'Negócios'],
    ['l’arbitrage', 'arbitragem', 'substantivo', "Ils sont allés à l'arbitrage.", 'Eles foram para a arbitragem.', 'Negócios'],
    ['le point de référence', 'referência comparativa', 'substantivo', 'Fixe un point de référence réaliste.', 'Defina uma referência realista.', 'Negócios'],
    ['la faisabilité', 'viabilidade', 'substantivo', "Étudie d'abord la faisabilité.", 'Estude a viabilidade primeiro.', 'Negócios'],
    ['la diversification', 'diversificação', 'substantivo', 'La diversification a réduit le risque.', 'A diversificação reduziu o risco.', 'Negócios'],
    ['les marchés publics', 'licitações públicas', 'substantivo', 'Les marchés publics prennent des mois.', 'As licitações públicas levam meses.', 'Negócios'],
    ['l’ontologie', 'ontologia', 'substantivo', "C'est une question d'ontologie.", 'Isso é uma questão de ontologia.', 'Filosofia'],
    ['l’épistémologie', 'epistemologia', 'substantivo', "L'épistémologie demande comment on sait.", 'A epistemologia pergunta como sabemos.', 'Filosofia'],
    ['le déterminisme', 'determinismo', 'substantivo', 'Le déterminisme nie le libre arbitre.', 'O determinismo nega o livre-arbítrio.', 'Filosofia'],
    ['la dialectique', 'dialética', 'substantivo', 'Il a argumenté par la dialectique.', 'Ele argumentou pela dialética.', 'Filosofia'],
    ['la métaphysique', 'metafísica', 'substantivo', 'La métaphysique résiste à la preuve.', 'A metafísica resiste à comprovação.', 'Filosofia'],
    ['existentiel', 'existencial', 'adjetivo', "C'est devenu une menace existentielle.", 'Virou uma ameaça existencial.', 'Filosofia'],
    ['la téléologie', 'teleologia', 'substantivo', 'La téléologie explique par la finalité.', 'A teleologia explica pela finalidade.', 'Filosofia'],
    ['le nihilisme', 'niilismo', 'substantivo', 'Le nihilisme nie tout sens inhérent.', 'O niilismo nega sentido inerente.', 'Filosofia'],
    ['l’axiome', 'axioma', 'substantivo', "Pars d'un axiome partagé.", 'Parta de um axioma comum.', 'Filosofia'],
    ['le syllogisme', 'silogismo', 'substantivo', 'Le syllogisme est invalide.', 'O silogismo é inválido.', 'Filosofia'],
    ['la stratification', 'estratificação', 'substantivo', 'La stratification sociale persiste.', 'A estratificação social persiste.', 'Sociologia'],
    ['l’assimilation', 'assimilação', 'substantivo', "On attendait d'eux l'assimilation.", 'Esperava-se deles a assimilação.', 'Sociologia'],
    ['démographique', 'demográfico', 'adjetivo', 'Le changement démographique est net.', 'A mudança demográfica é clara.', 'Sociologia'],
    ['l’urbanisation', 'urbanização', 'substantivo', "L'urbanisation s'est accélérée après 1960.", 'A urbanização acelerou depois de 1960.', 'Sociologia'],
    ['la cohorte', 'coorte / geração', 'substantivo', 'Cette cohorte gagne moins.', 'Essa geração ganha menos.', 'Sociologia'],
    ['la norme sociale', 'norma social', 'substantivo', 'La norme sociale a changé sans bruit.', 'A norma social mudou silenciosamente.', 'Sociologia'],
    ['la déviance', 'desvio (social)', 'substantivo', 'La déviance se définit par le contexte.', 'O desvio é definido pelo contexto.', 'Sociologia'],
    ['la mobilité sociale', 'mobilidade social', 'substantivo', 'La mobilité sociale stagne.', 'A mobilidade social estagnou.', 'Sociologia'],
    ['la parenté', 'parentesco', 'substantivo', 'Les liens de parenté restent forts.', 'Os laços de parentesco seguem fortes.', 'Sociologia'],
    ['la sécularisation', 'secularização', 'substantivo', 'La sécularisation varie selon la région.', 'A secularização varia por região.', 'Sociologia'],
    ['le pronostic', 'prognóstico', 'substantivo', 'Le pronostic est prudemment bon.', 'O prognóstico é cautelosamente bom.', 'Medicina'],
    ['chronique', 'crônico', 'adjetivo', "C'est devenu une maladie chronique.", 'Virou uma doença crônica.', 'Medicina'],
    ['bénin', 'benigno', 'adjetivo', 'La tumeur était bénigne.', 'O tumor era benigno.', 'Medicina'],
    ['malin', 'maligno', 'adjetivo', "La tumeur s'est révélée maligne.", 'O tumor se revelou maligno.', 'Medicina'],
    ['la rémission', 'remissão', 'substantivo', 'Elle est en rémission depuis un an.', 'Ela está em remissão há um ano.', 'Medicina'],
    ['la pathologie', 'patologia', 'substantivo', 'Le rapport de pathologie est arrivé.', 'O laudo de patologia chegou.', 'Medicina'],
    ['l’immunité', 'imunidade', 'substantivo', "L'immunité diminue avec le temps.", 'A imunidade diminui com o tempo.', 'Medicina'],
    ['la posologie', 'posologia / dosagem', 'substantivo', 'Ajuste la posologie avec soin.', 'Ajuste a dosagem com cuidado.', 'Medicina'],
    ['l’incision', 'incisão', 'substantivo', "L'incision a bien cicatrisé.", 'A incisão cicatrizou bem.', 'Medicina'],
    ['la rechute', 'recaída', 'substantivo', 'Une rechute reste possible.', 'Uma recaída ainda é possível.', 'Medicina'],
    ['la rhétorique', 'retórica', 'substantivo', 'La rhétorique a dépassé la politique.', 'A retórica passou à frente da política.', 'Retórica'],
    ['la persuasion', 'persuasão', 'substantivo', 'La persuasion vaut mieux que la contrainte.', 'A persuasão vence a coerção.', 'Retórica'],
    ['l’anecdote', 'anedota', 'substantivo', "Une anecdote n'est pas une donnée.", 'Uma anedota não é dado.', 'Retórica'],
    ['l’analogie', 'analogia', 'substantivo', "L'analogie s'effondre ici.", 'A analogia falha aqui.', 'Retórica'],
    ['la réfutation', 'refutação', 'substantivo', 'Sa réfutation était élégante.', 'A refutação dele foi elegante.', 'Retórica'],
    ['la connotation', 'conotação', 'substantivo', 'Ce mot porte une connotation.', 'Aquela palavra carrega uma conotação.', 'Retórica'],
    ['la réplique', 'réplica', 'substantivo', 'Elle a préparé une réplique.', 'Ela preparou uma réplica.', 'Retórica'],
    ['l’éloquence', 'eloquência', 'substantivo', "L'éloquence ne cache pas une preuve faible.", 'A eloquência não esconde evidência fraca.', 'Retórica'],
    ['le discours public', 'discurso público', 'substantivo', "Le discours public s'est dégradé.", 'O discurso público se degradou.', 'Retórica'],
    ['la digression', 'digressão', 'substantivo', 'Pardonnez la digression.', 'Perdoe a digressão.', 'Retórica'],
  ],
  C2: [
    ['élégiaque', 'elegíaco', 'adjetivo', 'Le roman a un ton élégiaque.', 'O romance tem um tom elegíaco.', 'Registro literário'],
    ['sépulcral', 'sepulcral', 'adjetivo', "Il a parlé d'une voix sépulcrale.", 'Ele falou com uma voz sepulcral.', 'Registro literário'],
    ['idyllique', 'idílico', 'adjetivo', 'C’étaient des jours idylliques.', 'Aqueles eram dias idílicos.', 'Registro literário'],
    ['mélodieux', 'melodioso', 'adjetivo', 'Sa diction mélodieuse a captivé la salle.', 'A dicção melodiosa dele prendeu a sala.', 'Registro literário'],
    ['plaintif', 'lamentoso', 'adjetivo', 'Une mélodie plaintive est entrée.', 'Uma melodia lamentosa entrou no ar.', 'Registro literário'],
    ['resplendissant', 'resplandecente', 'adjetivo', 'Elle est arrivée resplendissante de blanc.', 'Ela chegou resplandecente de branco.', 'Registro literário'],
    ['austère', 'austero', 'adjetivo', 'La prose est austère et exacte.', 'A prosa é austera e exata.', 'Registro literário'],
    ['languissant', 'lânguido', 'adjetivo', "L'après-midi était languissant.", 'A tarde foi lânguida.', 'Registro literário'],
    ['éthéré', 'etéreo', 'adjetivo', 'La lumière était presque éthérée.', 'A luz era quase etérea.', 'Registro literário'],
    ['sonore', 'sonoro', 'adjetivo', 'Son rire sonore a rempli la salle.', 'A risada sonora dele encheu o salão.', 'Registro literário'],
    ['le litige', 'litígio', 'substantivo', "L'affaire s'est terminée en litige.", 'O caso terminou em litígio.', 'Jurídico avançado'],
    ['la juridiction', 'jurisdição', 'substantivo', 'Le tribunal n’a pas juridiction.', 'O tribunal não tem jurisdição.', 'Jurídico avançado'],
    ['la mise en accusation', 'denúncia formal', 'substantivo', 'La mise en accusation faisait soixante pages.', 'A denúncia tinha sessenta páginas.', 'Jurídico avançado'],
    ['la culpabilité', 'culpabilidade', 'substantivo', "La culpabilité n'a jamais été établie.", 'A culpabilidade nunca foi estabelecida.', 'Jurídico avançado'],
    ['la présomption', 'presunção', 'substantivo', "La présomption d'innocence s'applique.", 'A presunção de inocência vale.', 'Jurídico avançado'],
    ['disculpatoire', 'excludente de culpa', 'adjetivo', 'Ils ont caché des preuves disculpatoires.', 'Eles ocultaram provas excludentes de culpa.', 'Jurídico avançado'],
    ['l’injonction', 'liminar', 'substantivo', 'Le juge a prononcé une injonction.', 'O juiz concedeu uma liminar.', 'Jurídico avançado'],
    ['la déposition sous serment', 'depoimento juramentado', 'substantivo', 'La déposition sous serment a duré toute la journée.', 'O depoimento juramentado durou o dia todo.', 'Jurídico avançado'],
    ['trancher', 'decidir / julgar', 'verbo', 'Un comité va trancher le litige.', 'Um comitê vai julgar o litígio.', 'Jurídico avançado'],
    ['le délit civil', 'ilícito civil', 'substantivo', 'Cela constitue un délit civil.', 'Isso configura um ilícito civil.', 'Jurídico avançado'],
    ['érudit', 'erudito', 'adjetivo', 'Les notes de bas de page sont érudites.', 'As notas de rodapé são eruditas.', 'Termos eruditos'],
    ['limpide', 'límpido / cristalino', 'adjetivo', 'Son explication limpide a tout réglé.', 'A explicação límpida dele resolveu tudo.', 'Termos eruditos'],
    ['abscons', 'abstruso / obscuro', 'adjetivo', "L'argument est inutilement abscons.", 'O argumento é desnecessariamente obscuro.', 'Termos eruditos'],
    ['ésotérique', 'esotérico / hermético', 'adjetivo', 'La théorie est devenue ésotérique.', 'A teoria ficou hermética.', 'Termos eruditos'],
    ['sagace', 'sagaz', 'adjetivo', "C'était un choix sagace.", 'Foi uma escolha sagaz.', 'Termos eruditos'],
    ['perspicace', 'perspicaz', 'adjetivo', 'Un lecteur perspicace le remarquera.', 'Um leitor perspicaz vai notar.', 'Termos eruditos'],
    ['laconique', 'lacônico', 'adjetivo', 'Sa réponse fut laconique.', 'A resposta dele foi lacônica.', 'Termos eruditos'],
    ['prolixe', 'prolixo', 'adjetivo', "L'introduction est prolixe.", 'A introdução é prolixa.', 'Termos eruditos'],
    ['taciturne', 'taciturno', 'adjetivo', 'Il est resté taciturne tout du long.', 'Ele permaneceu taciturno o tempo todo.', 'Termos eruditos'],
    ['volubile', 'tagarela / loquaz', 'adjetivo', 'Notre hôte volubile ne s’arrêtait pas.', 'Nosso anfitrião tagarela não parava.', 'Termos eruditos'],
    ['l’ambivalence', 'ambivalência', 'substantivo', 'Son ambivalence était évidente.', 'A ambivalência dela era evidente.', 'Nuance psicológica'],
    ['le scrupule', 'escrúpulo', 'substantivo', 'Il a menti sans scrupule.', 'Ele mentiu sem nenhum escrúpulo.', 'Nuance psicológica'],
    ['l’appréhension', 'apreensão', 'substantivo', "Elle l'a ouvert avec appréhension.", 'Ela abriu com apreensão.', 'Nuance psicológica'],
    ['l’offense', 'ofensa / melindre', 'substantivo', 'Il a pris la remarque comme une offense.', 'Ele tomou o comentário como uma ofensa.', 'Nuance psicológica'],
    ['la rancune', 'rancor', 'substantivo', 'Elle a parlé sans rancune.', 'Ela falou sem rancor.', 'Nuance psicológica'],
    ['la contrition', 'contrição', 'substantivo', 'Sa contrition semblait sincère.', 'A contrição dele parecia genuína.', 'Nuance psicológica'],
    ['l’orgueil démesuré', 'arrogância desmedida', 'substantivo', "L'orgueil démesuré a précédé la chute.", 'A arrogância desmedida precedeu a queda.', 'Nuance psicológica'],
    ['l’indulgence', 'tolerância / indulgência', 'substantivo', 'Merci de votre indulgence.', 'Obrigado pela sua tolerância.', 'Nuance psicológica'],
    ['la magnanimité', 'magnanimidade', 'substantivo', 'Il a montré une magnanimité inattendue.', 'Ele mostrou magnanimidade inesperada.', 'Nuance psicológica'],
    ['la timidité', 'timidez', 'substantivo', 'Sa timidité cachait un vrai talent.', 'A timidez dela escondia talento real.', 'Nuance psicológica'],
    ['le corollaire', 'corolário', 'substantivo', 'Des coûts plus élevés sont un corollaire de ce choix.', 'Custos maiores são um corolário dessa escolha.', 'Argumentação'],
    ['axiomatique', 'axiomático', 'adjetivo', "C'est axiomatique dans ce domaine.", 'É axiomático nesta área.', 'Argumentação'],
    ['incontestable', 'incontestável', 'adjetivo', 'Les données sont incontestables.', 'Os dados são incontestáveis.', 'Argumentação'],
    ['probant', 'probatório / conclusivo', 'adjetivo', 'Elle a présenté un dossier probant.', 'Ela apresentou um caso conclusivo.', 'Argumentação'],
    ['extrapoler', 'extrapolar', 'verbo', "N'extrapole pas à partir d'un seul cas.", 'Não extrapole a partir de um caso.', 'Argumentação'],
    ['la casuistique', 'casuística / sofisma', 'substantivo', 'Cette défense relève de la casuistique.', 'Essa defesa é pura casuística.', 'Argumentação'],
    ['de mauvaise foi', 'de má-fé', 'adjetivo', 'Cette réponse est de mauvaise foi.', 'Essa resposta é de má-fé.', 'Argumentação'],
    ['spécieux', 'especioso', 'adjetivo', 'Le raisonnement est spécieux.', 'O raciocínio é especioso.', 'Argumentação'],
    ['pertinent', 'pertinente', 'adjetivo', 'Ta remarque est pertinente.', 'Sua observação é pertinente.', 'Argumentação'],
    ['ipso facto', 'por isso mesmo', 'advérbio', "Cela ne s'ensuit pas ipso facto.", 'Não decorre disso por isso mesmo.', 'Argumentação'],
    ['la vraisemblance', 'verossimilhança', 'substantivo', 'Le film manque de vraisemblance.', 'O filme carece de verossimilhança.', 'Crítica e estética'],
    ['le pastiche', 'pastiche', 'substantivo', "L'album est un pastiche assumé.", 'O álbum é um pastiche assumido.', 'Crítica e estética'],
    ['l’anticlimax', 'anticlímax', 'substantivo', "La fin sombre dans l'anticlimax.", 'O final desaba no anticlímax.', 'Crítica e estética'],
    ['le dénouement', 'desfecho', 'substantivo', 'Le dénouement a semblé précipité.', 'O desfecho pareceu apressado.', 'Crítica e estética'],
    ['l’allégorie', 'alegoria', 'substantivo', 'Tout le livre est une allégorie.', 'O livro inteiro é uma alegoria.', 'Crítica e estética'],
    ['le motif récurrent', 'motivo recorrente', 'substantivo', "L'eau est le motif récurrent central.", 'A água é o motivo recorrente central.', 'Crítica e estética'],
    ['l’hyperbole', 'hipérbole', 'substantivo', "C'est de l'hyperbole, pas de l'analyse.", 'Isso é hipérbole, não análise.', 'Crítica e estética'],
    ['le pathos', 'pathos / comoção', 'substantivo', 'La scène atteint un vrai pathos.', 'A cena alcança comoção verdadeira.', 'Crítica e estética'],
    ['la satire', 'sátira', 'substantivo', 'Cela fonctionne mieux comme satire.', 'Funciona melhor como sátira.', 'Crítica e estética'],
    ['l’œuvre', 'obra (conjunto)', 'substantivo', 'Ceci est mineur dans son œuvre.', 'Isto é menor dentro da obra dela.', 'Crítica e estética'],
  ],
};
