/** Italiano — lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const IT_THEMATIC: LatinByLevel = {
  A1: [
    ['verde', 'verde', 'adjetivo', "L'erba è verde.", 'A grama é verde.', 'Cores e formas'],
    ['giallo', 'amarelo', 'adjetivo', 'Mi piacciono i fiori gialli.', 'Gosto de flores amarelas.', 'Cores e formas'],
    ['nero', 'preto', 'adjetivo', 'Porta un cappotto nero.', 'Ele usa um casaco preto.', 'Cores e formas'],
    ['bianco', 'branco', 'adjetivo', 'Le pareti sono bianche.', 'As paredes são brancas.', 'Cores e formas'],
    ['arancione', 'laranja', 'adjetivo', 'Ha una borsa arancione.', 'Ela tem uma bolsa laranja.', 'Cores e formas'],
    ['viola', 'roxo', 'adjetivo', 'Il cielo è diventato viola.', 'O céu ficou roxo.', 'Cores e formas'],
    ['marrone', 'marrom', 'adjetivo', 'Le mie scarpe sono marroni.', 'Meus sapatos são marrons.', 'Cores e formas'],
    ['rosa', 'rosa', 'adjetivo', 'Il bambino ha una coperta rosa.', 'O bebê tem um cobertor rosa.', 'Cores e formas'],
    ['il cerchio', 'círculo', 'substantivo', 'Disegna un cerchio qui.', 'Desenhe um círculo aqui.', 'Cores e formas'],
    ['il quadrato', 'quadrado', 'substantivo', 'La scatola è un quadrato.', 'A caixa é um quadrado.', 'Cores e formas'],
    ['la camicia', 'camisa', 'substantivo', 'Questa camicia è pulita.', 'Esta camisa está limpa.', 'Roupas'],
    ['i pantaloni', 'calça', 'substantivo', 'Questi pantaloni sono nuovi.', 'Esta calça é nova.', 'Roupas'],
    ['le scarpe', 'sapatos', 'substantivo', 'Le mie scarpe sono bagnate.', 'Meus sapatos estão molhados.', 'Roupas'],
    ['il vestito', 'vestido', 'substantivo', 'Ha comprato un vestito.', 'Ela comprou um vestido.', 'Roupas'],
    ['la giacca', 'jaqueta', 'substantivo', 'Prendi la giacca.', 'Leve sua jaqueta.', 'Roupas'],
    ['il cappello', 'chapéu', 'substantivo', 'Ha perso il cappello.', 'Ele perdeu o chapéu.', 'Roupas'],
    ['i calzini', 'meias', 'substantivo', 'Mi servono calzini puliti.', 'Preciso de meias limpas.', 'Roupas'],
    ['il cappotto', 'casaco', 'substantivo', 'Metti il cappotto oggi.', 'Use um casaco hoje.', 'Roupas'],
    ['la gonna', 'saia', 'substantivo', 'Quella gonna è lunga.', 'Aquela saia é longa.', 'Roupas'],
    ['gli occhiali', 'óculos', 'substantivo', 'Ho dimenticato gli occhiali.', 'Esqueci meus óculos.', 'Roupas'],
    ['il sole', 'sol', 'substantivo', 'Il sole è forte.', 'O sol está forte.', 'Clima e natureza'],
    ['la pioggia', 'chuva', 'substantivo', 'La pioggia è finita.', 'A chuva parou.', 'Clima e natureza'],
    ['la neve', 'neve', 'substantivo', 'La neve è alta.', 'A neve está funda.', 'Clima e natureza'],
    ['il vento', 'vento', 'substantivo', 'Il vento è forte.', 'O vento está forte.', 'Clima e natureza'],
    ['la nuvola', 'nuvem', 'substantivo', "C'è una nuvola.", 'Há uma nuvem.', 'Clima e natureza'],
    ['l’albero', 'árvore', 'substantivo', "L'albero è vecchio.", 'A árvore é velha.', 'Clima e natureza'],
    ['il fiore', 'flor', 'substantivo', 'Le piace questo fiore.', 'Ela gosta desta flor.', 'Clima e natureza'],
    ['il cielo', 'céu', 'substantivo', 'Il cielo è sereno.', 'O céu está limpo.', 'Clima e natureza'],
    ['la spiaggia', 'praia', 'substantivo', 'Andiamo in spiaggia.', 'Nós vamos à praia.', 'Clima e natureza'],
    ['la montagna', 'montanha', 'substantivo', 'La montagna è alta.', 'A montanha é alta.', 'Clima e natureza'],
    ['la testa', 'cabeça', 'substantivo', 'Mi fa male la testa.', 'Minha cabeça dói.', 'Corpo'],
    ['la mano', 'mão', 'substantivo', 'Dammi la mano.', 'Me dê sua mão.', 'Corpo'],
    ['il piede', 'pé', 'substantivo', 'Ho il piede freddo.', 'Meu pé está frio.', 'Corpo'],
    ['l’occhio', 'olho', 'substantivo', 'Ha un occhio verde.', 'Ela tem um olho verde.', 'Corpo'],
    ['l’orecchio', 'orelha / ouvido', 'substantivo', "Mi fa male l'orecchio.", 'Meu ouvido dói.', 'Corpo'],
    ['la bocca', 'boca', 'substantivo', 'Apri la bocca.', 'Abra a boca.', 'Corpo'],
    ['il naso', 'nariz', 'substantivo', 'Ha il naso rosso.', 'O nariz dele está vermelho.', 'Corpo'],
    ['i capelli', 'cabelo', 'substantivo', 'Ha i capelli lunghi.', 'O cabelo dela é longo.', 'Corpo'],
    ['il braccio', 'braço', 'substantivo', 'Si è rotto il braccio.', 'Ele quebrou o braço.', 'Corpo'],
    ['la gamba', 'perna', 'substantivo', 'Ho la gamba stanca.', 'Minha perna está cansada.', 'Corpo'],
    ['il pane', 'pão', 'substantivo', 'Mangio pane ogni giorno.', 'Eu como pão todo dia.', 'Comida e bebida'],
    ['il latte', 'leite', 'substantivo', 'Il latte è freddo.', 'O leite está frio.', 'Comida e bebida'],
    ['il caffè', 'café', 'substantivo', 'Lei beve il caffè.', 'Ela bebe café.', 'Comida e bebida'],
    ['il riso', 'arroz', 'substantivo', 'Mangiamo riso a pranzo.', 'Comemos arroz no almoço.', 'Comida e bebida'],
    ['la carne', 'carne', 'substantivo', 'Lui non mangia carne.', 'Ele não come carne.', 'Comida e bebida'],
    ['la frutta', 'fruta', 'substantivo', 'Compra della frutta.', 'Compre frutas.', 'Comida e bebida'],
    ['l’uovo', 'ovo', 'substantivo', 'Voglio un uovo.', 'Quero um ovo.', 'Comida e bebida'],
    ['il formaggio', 'queijo', 'substantivo', 'Questo formaggio è buono.', 'Este queijo é bom.', 'Comida e bebida'],
    ['lo zucchero', 'açúcar', 'substantivo', 'Senza zucchero, per favore.', 'Sem açúcar, por favor.', 'Comida e bebida'],
    ['il sale', 'sal', 'substantivo', 'Passami il sale.', 'Me passe o sal.', 'Comida e bebida'],
    ['la mattina', 'manhã', 'substantivo', 'Lavoro la mattina.', 'Eu trabalho de manhã.', 'Tempo e rotina'],
    ['il pomeriggio', 'tarde', 'substantivo', 'Ci vediamo nel pomeriggio.', 'Nos vemos à tarde.', 'Tempo e rotina'],
    ['la sera', 'fim de tarde / noite', 'substantivo', 'Mangiamo la sera.', 'Nós comemos à noite.', 'Tempo e rotina'],
    ['la notte', 'noite', 'substantivo', 'La notte è tranquilla.', 'A noite está calma.', 'Tempo e rotina'],
    ['la settimana', 'semana', 'substantivo', 'La settimana è lunga.', 'A semana é longa.', 'Tempo e rotina'],
    ['il mese', 'mês', 'substantivo', 'Questo mese è pieno.', 'Este mês está cheio.', 'Tempo e rotina'],
    ['oggi', 'hoje', 'advérbio', 'Oggi sono stanco.', 'Estou cansado hoje.', 'Tempo e rotina'],
    ['ieri', 'ontem', 'advérbio', 'Ieri ha piovuto.', 'Choveu ontem.', 'Tempo e rotina'],
    ['l’ora', 'hora', 'substantivo', "Aspetta un'ora.", 'Espere uma hora.', 'Tempo e rotina'],
    ['il fine settimana', 'fim de semana', 'substantivo', 'Il fine settimana riposo.', 'No fim de semana eu descanso.', 'Tempo e rotina'],
  ],
  A2: [
    ['il volo', 'voo', 'substantivo', 'Il nostro volo parte alle sei.', 'Nosso voo sai às seis.', 'Viagem'],
    ['il passaporto', 'passaporte', 'substantivo', 'Mi mostri il passaporto.', 'Me mostre seu passaporte.', 'Viagem'],
    ['il bagaglio', 'bagagem', 'substantivo', 'Il mio bagaglio è pesante.', 'Minha bagagem está pesada.', 'Viagem'],
    ['il biglietto', 'passagem / bilhete', 'substantivo', 'Ho comprato il biglietto online.', 'Comprei a passagem pela internet.', 'Viagem'],
    ['il ritardo', 'atraso', 'substantivo', "C'è stato un lungo ritardo.", 'Houve um atraso longo.', 'Viagem'],
    ['l’aeroporto', 'aeroporto', 'substantivo', "L'aeroporto è lontano.", 'O aeroporto é longe.', 'Viagem'],
    ['la valigia', 'mala', 'substantivo', 'Prepara la valigia stasera.', 'Faça sua mala hoje à noite.', 'Viagem'],
    ['la partenza', 'partida', 'substantivo', "Controlla l'orario di partenza.", 'Confira o horário de partida.', 'Viagem'],
    ['l’arrivo', 'chegada', 'substantivo', "L'arrivo è andato bene.", 'A chegada foi tranquila.', 'Viagem'],
    ['la carta d’imbarco', 'cartão de embarque', 'substantivo', 'Conserva la carta d’imbarco.', 'Guarde seu cartão de embarque.', 'Viagem'],
    ['il menù', 'cardápio', 'substantivo', 'Posso vedere il menù?', 'Posso ver o cardápio?', 'Restaurante'],
    ['il cameriere', 'garçom', 'substantivo', 'Il cameriere sta arrivando.', 'O garçom está vindo.', 'Restaurante'],
    ['la mancia', 'gorjeta', 'substantivo', 'Abbiamo lasciato una buona mancia.', 'Deixamos uma boa gorjeta.', 'Restaurante'],
    ['il dolce', 'sobremesa', 'substantivo', 'Voglio un dolce.', 'Quero uma sobremesa.', 'Restaurante'],
    ['l’antipasto', 'entrada (prato)', 'substantivo', "L'antipasto era piccolo.", 'A entrada era pequena.', 'Restaurante'],
    ['la prenotazione', 'reserva', 'substantivo', 'Ho fatto una prenotazione.', 'Fiz uma reserva.', 'Restaurante'],
    ['il tovagliolo', 'guardanapo', 'substantivo', 'Passami un tovagliolo.', 'Me passe um guardanapo.', 'Restaurante'],
    ['il vassoio', 'bandeja', 'substantivo', 'Mettilo sul vassoio.', 'Coloque na bandeja.', 'Restaurante'],
    ['il sapore', 'sabor', 'substantivo', 'Il sapore è strano.', 'O sabor está estranho.', 'Restaurante'],
    ['piccante', 'picante', 'adjetivo', 'Questo piatto è piccante.', 'Este prato é picante.', 'Restaurante'],
    ['i contanti', 'dinheiro (em espécie)', 'substantivo', 'Ho solo contanti.', 'Só tenho dinheiro em espécie.', 'Compras'],
    ['il resto', 'troco', 'substantivo', 'Tenga il resto.', 'Fique com o troco.', 'Compras'],
    ['la taglia', 'tamanho (roupa)', 'substantivo', 'Avete una taglia più grande?', 'Tem um tamanho maior?', 'Compras'],
    ['l’affare', 'pechincha / bom negócio', 'substantivo', 'Quel cappotto è stato un affare.', 'Aquele casaco foi uma pechincha.', 'Compras'],
    ['il cassiere', 'caixa (pessoa)', 'substantivo', 'Chiedi al cassiere.', 'Pergunte ao caixa.', 'Compras'],
    ['la corsia', 'corredor (de loja)', 'substantivo', 'Il latte è nella corsia tre.', 'O leite está no corredor três.', 'Compras'],
    ['lo scaffale', 'prateleira', 'substantivo', 'Lo scaffale è vuoto.', 'A prateleira está vazia.', 'Compras'],
    ['i saldi', 'liquidação', 'substantivo', 'Le scarpe sono in saldi.', 'Os sapatos estão em liquidação.', 'Compras'],
    ['il portafoglio', 'carteira', 'substantivo', 'Ho lasciato il portafoglio a casa.', 'Deixei minha carteira em casa.', 'Compras'],
    ['la marca', 'marca', 'substantivo', 'Mi fido di questa marca.', 'Confio nesta marca.', 'Compras'],
    ['la tosse', 'tosse', 'substantivo', 'Ha una brutta tosse.', 'Ela está com uma tosse feia.', 'Saúde'],
    ['il mal di testa', 'dor de cabeça', 'substantivo', 'Ho mal di testa.', 'Estou com dor de cabeça.', 'Saúde'],
    ['la pastiglia', 'comprimido', 'substantivo', 'Prendi una pastiglia al giorno.', 'Tome um comprimido por dia.', 'Saúde'],
    ['l’infermiere', 'enfermeiro', 'substantivo', "L'infermiere è stato gentile.", 'O enfermeiro foi gentil.', 'Saúde'],
    ['la ferita', 'ferimento', 'substantivo', 'La ferita era seria.', 'O ferimento foi sério.', 'Saúde'],
    ['il riposo', 'descanso', 'substantivo', 'Hai bisogno di riposo.', 'Você precisa de descanso.', 'Saúde'],
    ['la benda', 'bandagem', 'substantivo', 'Mettici una benda.', 'Coloque uma bandagem nisso.', 'Saúde'],
    ['stordito', 'tonto', 'adjetivo', 'Mi sento stordito.', 'Estou me sentindo tonto.', 'Saúde'],
    ['la clinica', 'clínica', 'substantivo', 'La clinica apre alle otto.', 'A clínica abre às oito.', 'Saúde'],
    ['il dolore', 'dor', 'substantivo', 'Ho un dolore alla schiena.', 'Tenho uma dor nas costas.', 'Saúde'],
    ['il ponte', 'ponte', 'substantivo', 'Attraversa il ponte.', 'Atravesse a ponte.', 'Cidade'],
    ['la piazza', 'praça', 'substantivo', 'Ci siamo visti in piazza.', 'Nos encontramos na praça.', 'Cidade'],
    ['l’angolo', 'esquina', 'substantivo', "Gira all'angolo.", 'Vire na esquina.', 'Cidade'],
    ['il traffico', 'trânsito', 'substantivo', 'Il traffico è terribile.', 'O trânsito está terrível.', 'Cidade'],
    ['la metropolitana', 'metrô', 'substantivo', 'Prendi la metropolitana.', 'Pegue o metrô.', 'Cidade'],
    ['la fermata', 'parada (ônibus)', 'substantivo', 'Scendi alla prossima fermata.', 'Desça na próxima parada.', 'Cidade'],
    ['la mappa', 'mapa', 'substantivo', 'Guarda la mappa.', 'Olhe o mapa.', 'Cidade'],
    ['il sentiero', 'trilha', 'substantivo', 'Segui questo sentiero.', 'Siga esta trilha.', 'Cidade'],
    ['il cancello', 'portão', 'substantivo', 'Il cancello è chiuso a chiave.', 'O portão está trancado.', 'Cidade'],
    ['le strisce pedonali', 'faixa de pedestres', 'substantivo', 'Usa le strisce pedonali.', 'Use a faixa de pedestres.', 'Cidade'],
    ['il bucato', 'roupa para lavar', 'substantivo', 'Faccio il bucato la domenica.', 'Eu lavo a roupa no domingo.', 'Casa e tarefas'],
    ['i piatti', 'louça', 'substantivo', 'Lui lava i piatti.', 'Ele lava a louça.', 'Casa e tarefas'],
    ['la scopa', 'vassoura', 'substantivo', "Dov'è la scopa?", 'Onde está a vassoura?', 'Casa e tarefas'],
    ['la spazzatura', 'lixo', 'substantivo', 'Porta fuori la spazzatura.', 'Leve o lixo para fora.', 'Casa e tarefas'],
    ['l’asciugamano', 'toalha', 'substantivo', "L'asciugamano è bagnato.", 'A toalha está molhada.', 'Casa e tarefas'],
    ['la coperta', 'cobertor', 'substantivo', "Mi serve un'altra coperta.", 'Preciso de outro cobertor.', 'Casa e tarefas'],
    ['il cassetto', 'gaveta', 'substantivo', 'È nel cassetto.', 'Está na gaveta.', 'Casa e tarefas'],
    ['l’armadio', 'armário', 'substantivo', "Appendilo nell'armadio.", 'Pendure no armário.', 'Casa e tarefas'],
    ['il lavandino', 'pia', 'substantivo', 'Il lavandino è intasato.', 'A pia está entupida.', 'Casa e tarefas'],
    ['lo specchio', 'espelho', 'substantivo', 'Guardati allo specchio.', 'Olhe no espelho.', 'Casa e tarefas'],
  ],
  B1: [
    ['il colloquio', 'entrevista de emprego', 'substantivo', 'Il colloquio è andato bene.', 'A entrevista correu bem.', 'Trabalho'],
    ['il curriculum', 'currículo', 'substantivo', 'Mandami il tuo curriculum.', 'Me mande seu currículo.', 'Trabalho'],
    ['il turno', 'turno', 'substantivo', 'Faccio il turno di notte.', 'Eu trabalho no turno da noite.', 'Trabalho'],
    ['gli straordinari', 'horas extras', 'substantivo', 'Ha fatto di nuovo gli straordinari.', 'Ela fez hora extra de novo.', 'Trabalho'],
    ['il tirocinio', 'estágio', 'substantivo', 'Ha ottenuto un tirocinio.', 'Ele conseguiu um estágio.', 'Trabalho'],
    ['il responsabile', 'supervisor', 'substantivo', 'Parla con il tuo responsabile.', 'Fale com seu supervisor.', 'Trabalho'],
    ['il compito', 'tarefa', 'substantivo', 'Questo compito richiede due ore.', 'Esta tarefa leva duas horas.', 'Trabalho'],
    ['la riunione', 'reunião', 'substantivo', 'La riunione è stata annullata.', 'A reunião foi cancelada.', 'Trabalho'],
    ['il personale', 'quadro de funcionários', 'substantivo', 'Il personale è cordiale.', 'A equipe é simpática.', 'Trabalho'],
    ['il contratto', 'contrato', 'substantivo', 'Leggi prima il contratto.', 'Leia o contrato primeiro.', 'Trabalho'],
    ['l’aggiornamento', 'atualização', 'substantivo', "Installa l'aggiornamento.", 'Instale a atualização.', 'Tecnologia'],
    ['la password', 'senha', 'substantivo', 'Ho dimenticato la password.', 'Esqueci minha senha.', 'Tecnologia'],
    ['il backup', 'cópia de segurança', 'substantivo', 'Fai prima un backup.', 'Faça uma cópia de segurança antes.', 'Tecnologia'],
    ['il dispositivo', 'dispositivo', 'substantivo', 'Questo dispositivo è veloce.', 'Este dispositivo é rápido.', 'Tecnologia'],
    ['lo schermo', 'tela', 'substantivo', 'Lo schermo è rotto.', 'A tela está quebrada.', 'Tecnologia'],
    ['scaricare', 'baixar', 'verbo', 'Scarica il file adesso.', 'Baixe o arquivo agora.', 'Tecnologia'],
    ['la rete', 'rede', 'substantivo', 'La rete non funziona.', 'A rede está fora do ar.', 'Tecnologia'],
    ['il browser', 'navegador', 'substantivo', 'Apri una nuova scheda del browser.', 'Abra uma nova aba do navegador.', 'Tecnologia'],
    ['la cartella', 'pasta', 'substantivo', 'Salvalo in questa cartella.', 'Salve nesta pasta.', 'Tecnologia'],
    ['bloccarsi', 'travar (programa)', 'verbo', "L'applicazione si è bloccata di nuovo.", 'O aplicativo travou de novo.', 'Tecnologia'],
    ['riciclare', 'reciclar', 'verbo', 'Qui ricicliamo la plastica.', 'Aqui nós reciclamos plástico.', 'Meio ambiente'],
    ['l’inquinamento', 'poluição', 'substantivo', "L'inquinamento è peggiorato.", 'A poluição piorou.', 'Meio ambiente'],
    ['il rifiuto', 'resíduo', 'substantivo', 'Il rifiuto alimentare è un problema.', 'O resíduo alimentar é um problema.', 'Meio ambiente'],
    ['il clima', 'clima', 'substantivo', 'Il clima sta cambiando.', 'O clima está mudando.', 'Meio ambiente'],
    ['l’energia', 'energia', 'substantivo', "L'energia solare ora costa meno.", 'A energia solar está mais barata agora.', 'Meio ambiente'],
    ['il bosco', 'floresta', 'substantivo', 'Il bosco è protetto.', 'A floresta é protegida.', 'Meio ambiente'],
    ['la specie', 'espécie', 'substantivo', 'Questa specie è rara.', 'Esta espécie é rara.', 'Meio ambiente'],
    ['la siccità', 'seca', 'substantivo', 'La siccità è durata mesi.', 'A seca durou meses.', 'Meio ambiente'],
    ['l’alluvione', 'enchente', 'substantivo', "L'alluvione ha danneggiato la strada.", 'A enchente danificou a estrada.', 'Meio ambiente'],
    ['lo scarico', 'despejo (poluente)', 'substantivo', 'Lo scarico è arrivato al fiume.', 'O despejo chegou ao rio.', 'Meio ambiente'],
    ['l’arbitro', 'árbitro', 'substantivo', "L'arbitro ha fermato la partita.", 'O árbitro parou o jogo.', 'Esportes'],
    ['il torneo', 'torneio', 'substantivo', 'Ha vinto il torneo.', 'Ela ganhou o torneio.', 'Esportes'],
    ['l’avversario', 'adversário', 'substantivo', 'Il suo avversario era più veloce.', 'O adversário dele era mais rápido.', 'Esportes'],
    ['il compagno di squadra', 'companheiro de equipe', 'substantivo', 'Il mio compagno di squadra ha segnato.', 'Meu companheiro de equipe marcou.', 'Esportes'],
    ['l’allenatore', 'treinador', 'substantivo', "L'allenatore era arrabbiato.", 'O treinador estava bravo.', 'Esportes'],
    ['il punteggio', 'placar', 'substantivo', "Qual è il punteggio?", 'Qual é o placar?', 'Esportes'],
    ['la partita', 'partida', 'substantivo', 'La partita comincia alle otto.', 'A partida começa às oito.', 'Esportes'],
    ['l’allenamento', 'treino', 'substantivo', "L'allenamento è ogni mattina.", 'O treino é toda manhã.', 'Esportes'],
    ['la resistenza', 'resistência física', 'substantivo', 'Ha una grande resistenza.', 'Ele tem muita resistência.', 'Esportes'],
    ['il campionato', 'campeonato', 'substantivo', 'Hanno perso il campionato.', 'Eles perderam o campeonato.', 'Esportes'],
    ['litigare', 'brigar / discutir', 'verbo', 'Litigano per i soldi.', 'Eles brigam por dinheiro.', 'Relacionamentos'],
    ['scusarsi', 'pedir desculpas', 'verbo', 'Si è scusato subito.', 'Ele pediu desculpas rápido.', 'Relacionamentos'],
    ['la fiducia', 'confiança', 'substantivo', 'La fiducia richiede tempo.', 'Confiança leva tempo.', 'Relacionamentos'],
    ['geloso', 'ciumento', 'adjetivo', 'Diventa gelosa facilmente.', 'Ela fica com ciúmes fácil.', 'Relacionamentos'],
    ['leale', 'leal', 'adjetivo', 'È un amico leale.', 'Ele é um amigo leal.', 'Relacionamentos'],
    ['il pettegolezzo', 'fofoca', 'substantivo', 'Odio il pettegolezzo in ufficio.', 'Odeio fofoca de escritório.', 'Relacionamentos'],
    ['il consiglio', 'conselho', 'substantivo', 'Quello è stato un buon consiglio.', 'Aquilo foi um bom conselho.', 'Relacionamentos'],
    ['il piacere', 'favor', 'substantivo', 'Posso chiederti un piacere?', 'Posso te pedir um favor?', 'Relacionamentos'],
    ['il dissapore', 'desentendimento', 'substantivo', 'Hanno avuto un dissapore sciocco.', 'Eles tiveram um desentendimento bobo.', 'Relacionamentos'],
    ['il compromesso', 'acordo mútuo', 'substantivo', 'Siamo arrivati a un compromesso.', 'Chegamos a um acordo.', 'Relacionamentos'],
    ['il bilancio', 'orçamento', 'substantivo', 'Rispetta il bilancio.', 'Siga o orçamento.', 'Dinheiro'],
    ['i risparmi', 'poupança', 'substantivo', 'Ha usato i suoi risparmi.', 'Ela usou a poupança.', 'Dinheiro'],
    ['il prestito', 'empréstimo', 'substantivo', 'Ha chiesto un prestito.', 'Ele fez um empréstimo.', 'Dinheiro'],
    ['il debito', 'dívida', 'substantivo', 'Hanno estinto il debito.', 'Eles quitaram a dívida.', 'Dinheiro'],
    ['la spesa', 'despesa', 'substantivo', "L'affitto è la mia spesa maggiore.", 'O aluguel é minha maior despesa.', 'Dinheiro'],
    ['gli interessi', 'juros', 'substantivo', 'Gli interessi sono troppo alti.', 'Os juros estão altos demais.', 'Dinheiro'],
    ['investire', 'investir', 'verbo', 'Investono in immobili.', 'Eles investem em imóveis.', 'Dinheiro'],
    ['il mutuo', 'financiamento imobiliário', 'substantivo', 'Abbiamo un mutuo.', 'Nós temos um financiamento.', 'Dinheiro'],
    ['l’assicurazione', 'seguro', 'substantivo', "L'assicurazione auto è cara.", 'O seguro do carro é caro.', 'Dinheiro'],
    ['il salario minimo', 'salário mínimo', 'substantivo', 'Il salario minimo è aumentato.', 'O salário mínimo subiu.', 'Dinheiro'],
  ],
  B2: [
    ['la campagna elettorale', 'campanha eleitoral', 'substantivo', 'La campagna elettorale è durata sei settimane.', 'A campanha eleitoral durou seis semanas.', 'Política'],
    ['l’elettorato', 'eleitorado', 'substantivo', "L'elettorato è diviso.", 'O eleitorado está dividido.', 'Política'],
    ['la legislazione', 'legislação', 'substantivo', 'È passata una nuova legislazione.', 'Uma nova legislação foi aprovada.', 'Política'],
    ['le pressioni politiche', 'lobby', 'substantivo', 'Le pressioni politiche hanno plasmato la legge.', 'O lobby moldou a lei.', 'Política'],
    ['la corruzione', 'corrupção', 'substantivo', 'La corruzione mina la fiducia.', 'A corrupção corrói a confiança.', 'Política'],
    ['il referendum', 'referendo', 'substantivo', 'Hanno indetto un referendum.', 'Eles convocaram um referendo.', 'Política'],
    ['la coalizione', 'coalizão', 'substantivo', 'La coalizione è crollata.', 'A coalizão desmoronou.', 'Política'],
    ['la scheda elettorale', 'cédula de votação', 'substantivo', 'La tua scheda elettorale è segreta.', 'Seu voto é secreto.', 'Política'],
    ['il collegio elettorale', 'distrito eleitoral', 'substantivo', 'Ha visitato il suo collegio elettorale.', 'Ela visitou seu distrito eleitoral.', 'Política'],
    ['il mandato', 'mandato', 'substantivo', 'Rivendicano un mandato chiaro.', 'Eles alegam um mandato claro.', 'Política'],
    ['l’inflazione', 'inflação', 'substantivo', "L'inflazione è rallentata il mese scorso.", 'A inflação desacelerou no mês passado.', 'Economia'],
    ['la recessione', 'recessão', 'substantivo', 'Il paese è entrato in recessione.', 'O país entrou em recessão.', 'Economia'],
    ['il sussidio', 'subsídio', 'substantivo', 'Il sussidio è stato tagliato.', 'O subsídio foi cortado.', 'Economia'],
    ['il dazio', 'tarifa alfandegária', 'substantivo', 'Hanno imposto un dazio.', 'Impuseram uma tarifa.', 'Economia'],
    ['l’avanzo', 'superávit', 'substantivo', 'Il bilancio mostra un avanzo.', 'O orçamento mostra um superávit.', 'Economia'],
    ['il disavanzo', 'déficit', 'substantivo', 'Il disavanzo continua a crescere.', 'O déficit continua crescendo.', 'Economia'],
    ['l’offerta', 'oferta', 'substantivo', "L'offerta non copre la domanda.", 'A oferta não atende à procura.', 'Economia'],
    ['la domanda', 'procura', 'substantivo', 'La domanda è crollata.', 'A procura caiu bruscamente.', 'Economia'],
    ['il monopolio', 'monopólio', 'substantivo', 'Detengono quasi un monopolio.', 'Eles têm quase um monopólio.', 'Economia'],
    ['l’austerità', 'austeridade', 'substantivo', "L'austerità ha colpito i servizi pubblici.", 'A austeridade prejudicou os serviços públicos.', 'Economia'],
    ['l’esperimento', 'experimento', 'substantivo', "L'esperimento è fallito due volte.", 'O experimento falhou duas vezes.', 'Ciência'],
    ['la prova', 'prova / evidência', 'substantivo', 'Ci sono prove solide.', 'Há evidências sólidas.', 'Ciência'],
    ['il campione', 'amostra', 'substantivo', 'Il campione era troppo piccolo.', 'A amostra era pequena demais.', 'Ciência'],
    ['il laboratorio', 'laboratório', 'substantivo', 'Lavora in un laboratorio.', 'Ela trabalha num laboratório.', 'Ciência'],
    ['la molecola', 'molécula', 'substantivo', "L'acqua è una molecola semplice.", 'A água é uma molécula simples.', 'Ciência'],
    ['il genoma', 'genoma', 'substantivo', 'Hanno mappato il genoma.', 'Eles mapearam o genoma.', 'Ciência'],
    ['il vaccino', 'vacina', 'substantivo', 'Il vaccino funziona bene.', 'A vacina funciona bem.', 'Ciência'],
    ['il microbo', 'micróbio', 'substantivo', 'Questo microbo è innocuo.', 'Este micróbio é inofensivo.', 'Ciência'],
    ['la radiazione', 'radiação', 'substantivo', 'I livelli di radiazione sono normali.', 'Os níveis de radiação estão normais.', 'Ciência'],
    ['il telescopio', 'telescópio', 'substantivo', 'Il telescopio ha trovato un pianeta.', 'O telescópio encontrou um planeta.', 'Ciência'],
    ['il titolo', 'manchete', 'substantivo', 'Il titolo era fuorviante.', 'A manchete era enganosa.', 'Mídia'],
    ['la copertura mediatica', 'cobertura jornalística', 'substantivo', 'La copertura mediatica era di parte.', 'A cobertura foi tendenciosa.', 'Mídia'],
    ['la censura', 'censura', 'substantivo', "La censura è aumentata l'anno scorso.", 'A censura aumentou no ano passado.', 'Mídia'],
    ['la propaganda', 'propaganda ideológica', 'substantivo', 'Questa è pura propaganda.', 'Isso é pura propaganda.', 'Mídia'],
    ['la trasmissione', 'transmissão', 'substantivo', 'La trasmissione ha raggiunto milioni di persone.', 'A transmissão alcançou milhões.', 'Mídia'],
    ['il giornalista', 'jornalista', 'substantivo', 'La giornalista ha verificato le fonti.', 'A jornalista checou as fontes.', 'Mídia'],
    ['l’editoriale', 'editorial', 'substantivo', "L'editoriale ha criticato il piano.", 'O editorial criticou o plano.', 'Mídia'],
    ['la stampa scandalistica', 'imprensa sensacionalista', 'substantivo', 'Non fidarti della stampa scandalistica.', 'Não confie na imprensa sensacionalista.', 'Mídia'],
    ['il pubblico', 'público', 'substantivo', 'Il pubblico era ostile.', 'O público estava hostil.', 'Mídia'],
    ['la fonte', 'fonte', 'substantivo', 'Cita la tua fonte.', 'Cite sua fonte.', 'Mídia'],
    ['l’empatia', 'empatia', 'substantivo', "L'empatia si può insegnare.", 'A empatia pode ser ensinada.', 'Psicologia'],
    ['l’ansia', 'ansiedade', 'substantivo', "L'ansia disturba il sonno.", 'A ansiedade afeta o sono.', 'Psicologia'],
    ['il trauma', 'trauma', 'substantivo', 'Il trauma è durato anni.', 'O trauma durou anos.', 'Psicologia'],
    ['la motivazione', 'motivação', 'substantivo', 'La motivazione svanisce senza risultati.', 'A motivação some sem resultados.', 'Psicologia'],
    ['la percezione', 'percepção', 'substantivo', 'La percezione plasma la memoria.', 'A percepção molda a memória.', 'Psicologia'],
    ['il comportamento', 'comportamento', 'substantivo', 'Il suo comportamento è cambiato di colpo.', 'O comportamento dele mudou de repente.', 'Psicologia'],
    ['l’istinto', 'instinto', 'substantivo', 'Fidati del tuo istinto qui.', 'Confie no seu instinto aqui.', 'Psicologia'],
    ['l’umore', 'humor / estado de espírito', 'substantivo', 'Il suo umore è migliorato.', 'O humor dela melhorou.', 'Psicologia'],
    ['l’autostima', 'autoestima', 'substantivo', 'La bassa autostima è comune.', 'Baixa autoestima é comum.', 'Psicologia'],
    ['il risentimento', 'ressentimento', 'substantivo', 'Il risentimento è cresciuto lentamente.', 'O ressentimento cresceu devagar.', 'Psicologia'],
    ['la causa legale', 'processo judicial', 'substantivo', 'Hanno intentato una causa legale.', 'Eles entraram com um processo.', 'Direito'],
    ['il verdetto', 'veredicto', 'substantivo', 'Il verdetto ha sorpreso tutti.', 'O veredicto surpreendeu todos.', 'Direito'],
    ['la testimonianza', 'depoimento', 'substantivo', 'La sua testimonianza è stata decisiva.', 'O depoimento dela foi decisivo.', 'Direito'],
    ['il testimone', 'testemunha', 'substantivo', 'Il testimone ha cambiato versione.', 'A testemunha mudou a versão.', 'Direito'],
    ['l’imputato', 'réu', 'substantivo', "L'imputato è rimasto in silenzio.", 'O réu permaneceu calado.', 'Direito'],
    ['l’avvocato', 'advogado', 'substantivo', "Chiama il tuo avvocato.", 'Ligue para seu advogado.', 'Direito'],
    ['la dichiarazione di colpevolezza', 'confissão de culpa', 'substantivo', 'Ha optato per la dichiarazione di colpevolezza.', 'Ele optou pela confissão de culpa.', 'Direito'],
    ['l’appello', 'recurso judicial', 'substantivo', "Hanno perso l'appello.", 'Eles perderam o recurso.', 'Direito'],
    ['l’affidamento', 'guarda (de filhos)', 'substantivo', "Ha ottenuto l'affidamento.", 'Ela ganhou a guarda.', 'Direito'],
    ['la norma scritta', 'norma escrita', 'substantivo', 'La norma scritta è superata.', 'A norma escrita está ultrapassada.', 'Direito'],
  ],
  C1: [
    ['l’ipotesi', 'hipótese', 'substantivo', "L'ipotesi non ha retto.", 'A hipótese não se sustentou.', 'Pesquisa acadêmica'],
    ['la metodologia', 'metodologia', 'substantivo', 'Descrivi la tua metodologia con chiarezza.', 'Descreva sua metodologia com clareza.', 'Pesquisa acadêmica'],
    ['la correlazione', 'correlação', 'substantivo', 'Correlazione non è causalità.', 'Correlação não é causalidade.', 'Pesquisa acadêmica'],
    ['la variabile', 'variável', 'substantivo', 'Controlla quella variabile.', 'Controle essa variável.', 'Pesquisa acadêmica'],
    ['empirico', 'empírico', 'adjetivo', 'Serve un sostegno empirico.', 'Precisamos de respaldo empírico.', 'Pesquisa acadêmica'],
    ['la revisione tra pari', 'revisão por pares', 'substantivo', "La revisione tra pari ha scoperto l'errore.", 'A revisão por pares pegou o erro.', 'Pesquisa acadêmica'],
    ['longitudinale', 'longitudinal', 'adjetivo', 'È stato uno studio longitudinale.', 'Foi um estudo longitudinal.', 'Pesquisa acadêmica'],
    ['la replicazione', 'replicação', 'substantivo', 'La replicazione è fallita due volte.', 'A replicação falhou duas vezes.', 'Pesquisa acadêmica'],
    ['l’inferenza', 'inferência', 'substantivo', "Quell'inferenza è troppo ampia.", 'Essa inferência é ampla demais.', 'Pesquisa acadêmica'],
    ['il paradigma', 'paradigma', 'substantivo', 'Il paradigma è cambiato lentamente.', 'O paradigma mudou devagar.', 'Pesquisa acadêmica'],
    ['il portatore d’interesse', 'parte interessada', 'substantivo', 'Consulta ogni portatore d’interesse.', 'Consulte cada parte interessada.', 'Negócios'],
    ['l’acquisizione', 'aquisição', 'substantivo', "L'acquisizione si è chiusa a maggio.", 'A aquisição foi concluída em maio.', 'Negócios'],
    ['la fusione', 'fusão', 'substantivo', 'La fusione ha incontrato resistenze.', 'A fusão enfrentou resistência.', 'Negócios'],
    ['il fatturato', 'faturamento', 'substantivo', 'Il fatturato è cresciuto del dodici per cento.', 'O faturamento cresceu doze por cento.', 'Negócios'],
    ['la responsabilità civile', 'responsabilidade civil', 'substantivo', 'Quella clausola genera responsabilità civile.', 'Aquela cláusula gera responsabilidade civil.', 'Negócios'],
    ['l’arbitrato', 'arbitragem', 'substantivo', 'Sono andati in arbitrato.', 'Eles foram para a arbitragem.', 'Negócios'],
    ['il parametro di riferimento', 'referência comparativa', 'substantivo', 'Fissa un parametro di riferimento realistico.', 'Defina uma referência realista.', 'Negócios'],
    ['la fattibilità', 'viabilidade', 'substantivo', 'Studia prima la fattibilità.', 'Estude a viabilidade primeiro.', 'Negócios'],
    ['la diversificazione', 'diversificação', 'substantivo', 'La diversificazione ha ridotto il rischio.', 'A diversificação reduziu o risco.', 'Negócios'],
    ['gli appalti pubblici', 'licitações públicas', 'substantivo', 'Gli appalti pubblici richiedono mesi.', 'As licitações públicas levam meses.', 'Negócios'],
    ['l’ontologia', 'ontologia', 'substantivo', "È una questione di ontologia.", 'Isso é uma questão de ontologia.', 'Filosofia'],
    ['l’epistemologia', 'epistemologia', 'substantivo', "L'epistemologia chiede come sappiamo.", 'A epistemologia pergunta como sabemos.', 'Filosofia'],
    ['il determinismo', 'determinismo', 'substantivo', 'Il determinismo nega il libero arbitrio.', 'O determinismo nega o livre-arbítrio.', 'Filosofia'],
    ['la dialettica', 'dialética', 'substantivo', 'Ha argomentato per via dialettica.', 'Ele argumentou pela dialética.', 'Filosofia'],
    ['la metafisica', 'metafísica', 'substantivo', 'La metafisica resiste alla prova.', 'A metafísica resiste à comprovação.', 'Filosofia'],
    ['esistenziale', 'existencial', 'adjetivo', 'È diventata una minaccia esistenziale.', 'Virou uma ameaça existencial.', 'Filosofia'],
    ['la teleologia', 'teleologia', 'substantivo', 'La teleologia spiega attraverso il fine.', 'A teleologia explica pela finalidade.', 'Filosofia'],
    ['il nichilismo', 'niilismo', 'substantivo', 'Il nichilismo nega ogni senso intrinseco.', 'O niilismo nega sentido inerente.', 'Filosofia'],
    ['l’assioma', 'axioma', 'substantivo', 'Parti da un assioma condiviso.', 'Parta de um axioma comum.', 'Filosofia'],
    ['il sillogismo', 'silogismo', 'substantivo', 'Il sillogismo non è valido.', 'O silogismo é inválido.', 'Filosofia'],
    ['la stratificazione', 'estratificação', 'substantivo', 'La stratificazione sociale persiste.', 'A estratificação social persiste.', 'Sociologia'],
    ['l’assimilazione', 'assimilação', 'substantivo', "Da loro ci si aspettava l'assimilazione.", 'Esperava-se deles a assimilação.', 'Sociologia'],
    ['demografico', 'demográfico', 'adjetivo', 'Il mutamento demografico è netto.', 'A mudança demográfica é clara.', 'Sociologia'],
    ['l’urbanizzazione', 'urbanização', 'substantivo', "L'urbanizzazione è accelerata dopo il 1960.", 'A urbanização acelerou depois de 1960.', 'Sociologia'],
    ['la coorte', 'coorte / geração', 'substantivo', 'Quella coorte guadagna meno.', 'Essa geração ganha menos.', 'Sociologia'],
    ['la norma sociale', 'norma social', 'substantivo', 'La norma sociale è cambiata in silenzio.', 'A norma social mudou silenciosamente.', 'Sociologia'],
    ['la devianza', 'desvio (social)', 'substantivo', 'La devianza si definisce nel contesto.', 'O desvio é definido pelo contexto.', 'Sociologia'],
    ['la mobilità sociale', 'mobilidade social', 'substantivo', 'La mobilità sociale si è arrestata.', 'A mobilidade social estagnou.', 'Sociologia'],
    ['la parentela', 'parentesco', 'substantivo', 'I legami di parentela restano forti.', 'Os laços de parentesco seguem fortes.', 'Sociologia'],
    ['la secolarizzazione', 'secularização', 'substantivo', 'La secolarizzazione varia per regione.', 'A secularização varia por região.', 'Sociologia'],
    ['la prognosi', 'prognóstico', 'substantivo', 'La prognosi è cautamente buona.', 'O prognóstico é cautelosamente bom.', 'Medicina'],
    ['cronico', 'crônico', 'adjetivo', 'È diventata una malattia cronica.', 'Virou uma doença crônica.', 'Medicina'],
    ['benigno', 'benigno', 'adjetivo', 'La massa era benigna.', 'O nódulo era benigno.', 'Medicina'],
    ['maligno', 'maligno', 'adjetivo', 'Il tumore si è rivelato maligno.', 'O tumor se revelou maligno.', 'Medicina'],
    ['la remissione', 'remissão', 'substantivo', 'È in remissione da un anno.', 'Ela está em remissão há um ano.', 'Medicina'],
    ['la patologia', 'patologia', 'substantivo', 'È arrivato il referto di patologia.', 'O laudo de patologia chegou.', 'Medicina'],
    ['l’immunità', 'imunidade', 'substantivo', "L'immunità cala col tempo.", 'A imunidade diminui com o tempo.', 'Medicina'],
    ['il dosaggio', 'dosagem', 'substantivo', 'Regola il dosaggio con attenzione.', 'Ajuste a dosagem com cuidado.', 'Medicina'],
    ['l’incisione', 'incisão', 'substantivo', "L'incisione è guarita bene.", 'A incisão cicatrizou bem.', 'Medicina'],
    ['la ricaduta', 'recaída', 'substantivo', 'Una ricaduta resta possibile.', 'Uma recaída ainda é possível.', 'Medicina'],
    ['la retorica', 'retórica', 'substantivo', 'La retorica ha superato la politica.', 'A retórica passou à frente da política.', 'Retórica'],
    ['la persuasione', 'persuasão', 'substantivo', 'La persuasione batte la coercizione.', 'A persuasão vence a coerção.', 'Retórica'],
    ['l’aneddoto', 'anedota', 'substantivo', 'Un aneddoto non è un dato.', 'Uma anedota não é dado.', 'Retórica'],
    ['l’analogia', 'analogia', 'substantivo', "L'analogia qui non regge.", 'A analogia falha aqui.', 'Retórica'],
    ['la confutazione', 'refutação', 'substantivo', 'La sua confutazione è stata elegante.', 'A refutação dele foi elegante.', 'Retórica'],
    ['la connotazione', 'conotação', 'substantivo', 'Quella parola porta una connotazione.', 'Aquela palavra carrega uma conotação.', 'Retórica'],
    ['la replica', 'réplica', 'substantivo', 'Ha preparato una replica.', 'Ela preparou uma réplica.', 'Retórica'],
    ['l’eloquenza', 'eloquência', 'substantivo', "L'eloquenza non nasconde prove deboli.", 'A eloquência não esconde evidência fraca.', 'Retórica'],
    ['il discorso pubblico', 'discurso público', 'substantivo', 'Il discorso pubblico si è imbarbarito.', 'O discurso público se degradou.', 'Retórica'],
    ['la digressione', 'digressão', 'substantivo', 'Perdona la digressione.', 'Perdoe a digressão.', 'Retórica'],
  ],
  C2: [
    ['elegiaco', 'elegíaco', 'adjetivo', 'Il romanzo ha un tono elegiaco.', 'O romance tem um tom elegíaco.', 'Registro literário'],
    ['sepolcrale', 'sepulcral', 'adjetivo', 'Ha parlato con voce sepolcrale.', 'Ele falou com uma voz sepulcral.', 'Registro literário'],
    ['idilliaco', 'idílico', 'adjetivo', 'Quelli erano giorni idilliaci.', 'Aqueles eram dias idílicos.', 'Registro literário'],
    ['melodioso', 'melodioso', 'adjetivo', 'La sua dizione melodiosa ha incantato la sala.', 'A dicção melodiosa dele encantou a sala.', 'Registro literário'],
    ['lamentoso', 'lamentoso', 'adjetivo', 'Entrò una melodia lamentosa.', 'Uma melodia lamentosa entrou no ar.', 'Registro literário'],
    ['splendente', 'resplandecente', 'adjetivo', 'Arrivò splendente in bianco.', 'Ela chegou resplandecente de branco.', 'Registro literário'],
    ['austero', 'austero', 'adjetivo', 'La prosa è austera ed esatta.', 'A prosa é austera e exata.', 'Registro literário'],
    ['languido', 'lânguido', 'adjetivo', 'Il pomeriggio era languido.', 'A tarde foi lânguida.', 'Registro literário'],
    ['etereo', 'etéreo', 'adjetivo', 'La luce era quasi eterea.', 'A luz era quase etérea.', 'Registro literário'],
    ['sonoro', 'sonoro', 'adjetivo', 'La sua risata sonora riempì la sala.', 'A risada sonora dele encheu o salão.', 'Registro literário'],
    ['il contenzioso', 'litígio', 'substantivo', 'Il caso è finito in contenzioso.', 'O caso terminou em litígio.', 'Jurídico avançado'],
    ['la giurisdizione', 'jurisdição', 'substantivo', 'Il tribunale non ha giurisdizione.', 'O tribunal não tem jurisdição.', 'Jurídico avançado'],
    ['il rinvio a giudizio', 'denúncia formal', 'substantivo', 'Il rinvio a giudizio contava sessanta pagine.', 'A denúncia tinha sessenta páginas.', 'Jurídico avançado'],
    ['la colpevolezza', 'culpabilidade', 'substantivo', 'La colpevolezza non è mai stata accertata.', 'A culpabilidade nunca foi estabelecida.', 'Jurídico avançado'],
    ['la presunzione', 'presunção', 'substantivo', 'Vale la presunzione di innocenza.', 'A presunção de inocência vale.', 'Jurídico avançado'],
    ['scagionante', 'excludente de culpa', 'adjetivo', 'Hanno occultato prove scagionanti.', 'Eles ocultaram provas excludentes de culpa.', 'Jurídico avançado'],
    ['l’ingiunzione', 'liminar', 'substantivo', "Il giudice ha emesso un'ingiunzione.", 'O juiz concedeu uma liminar.', 'Jurídico avançado'],
    ['la deposizione giurata', 'depoimento juramentado', 'substantivo', 'La deposizione giurata è durata tutto il giorno.', 'O depoimento juramentado durou o dia todo.', 'Jurídico avançado'],
    ['dirimere', 'dirimir / julgar', 'verbo', 'Un collegio dirimerà la controversia.', 'Um colegiado vai dirimir a controvérsia.', 'Jurídico avançado'],
    ['l’illecito civile', 'ilícito civil', 'substantivo', 'Questo configura un illecito civile.', 'Isso configura um ilícito civil.', 'Jurídico avançado'],
    ['erudito', 'erudito', 'adjetivo', 'Le note a piè di pagina sono erudite.', 'As notas de rodapé são eruditas.', 'Termos eruditos'],
    ['limpido', 'límpido / cristalino', 'adjetivo', 'La sua spiegazione limpida ha chiuso la questione.', 'A explicação límpida dele encerrou a questão.', 'Termos eruditos'],
    ['recondito', 'recôndito', 'adjetivo', "L'argomento è inutilmente recondito.", 'O argumento é desnecessariamente recôndito.', 'Termos eruditos'],
    ['astruso', 'abstruso', 'adjetivo', 'La teoria è diventata astrusa.', 'A teoria ficou abstrusa.', 'Termos eruditos'],
    ['sagace', 'sagaz', 'adjetivo', 'È stata una scelta sagace.', 'Foi uma escolha sagaz.', 'Termos eruditos'],
    ['perspicace', 'perspicaz', 'adjetivo', 'Un lettore perspicace se ne accorgerà.', 'Um leitor perspicaz vai notar.', 'Termos eruditos'],
    ['laconico', 'lacônico', 'adjetivo', 'La sua risposta fu laconica.', 'A resposta dele foi lacônica.', 'Termos eruditos'],
    ['prolisso', 'prolixo', 'adjetivo', "L'introduzione è prolissa.", 'A introdução é prolixa.', 'Termos eruditos'],
    ['taciturno', 'taciturno', 'adjetivo', 'È rimasto taciturno per tutto il tempo.', 'Ele permaneceu taciturno o tempo todo.', 'Termos eruditos'],
    ['loquace', 'tagarela / loquaz', 'adjetivo', 'Il nostro loquace ospite non si fermava.', 'Nosso anfitrião tagarela não parava.', 'Termos eruditos'],
    ['l’ambivalenza', 'ambivalência', 'substantivo', 'La sua ambivalenza era evidente.', 'A ambivalência dela era evidente.', 'Nuance psicológica'],
    ['lo scrupolo', 'escrúpulo', 'substantivo', 'Ha mentito senza scrupolo.', 'Ele mentiu sem nenhum escrúpulo.', 'Nuance psicológica'],
    ['l’apprensione', 'apreensão', 'substantivo', "L'ha aperto con apprensione.", 'Ela abriu com apreensão.', 'Nuance psicológica'],
    ['l’offesa', 'ofensa / melindre', 'substantivo', "Ha preso il commento come un'offesa.", 'Ele tomou o comentário como uma ofensa.', 'Nuance psicológica'],
    ['il rancore', 'rancor', 'substantivo', 'Ha parlato senza rancore.', 'Ela falou sem rancor.', 'Nuance psicológica'],
    ['la contrizione', 'contrição', 'substantivo', 'La sua contrizione sembrava sincera.', 'A contrição dele parecia genuína.', 'Nuance psicológica'],
    ['la tracotanza', 'arrogância desmedida', 'substantivo', 'La tracotanza ha preceduto il crollo.', 'A arrogância desmedida precedeu o colapso.', 'Nuance psicológica'],
    ['l’indulgenza', 'indulgência / tolerância', 'substantivo', 'Grazie per la vostra indulgenza.', 'Obrigado pela sua tolerância.', 'Nuance psicológica'],
    ['la magnanimità', 'magnanimidade', 'substantivo', 'Ha mostrato una magnanimità inattesa.', 'Ele mostrou magnanimidade inesperada.', 'Nuance psicológica'],
    ['la ritrosia', 'retraimento / timidez', 'substantivo', 'La sua ritrosia nascondeva un vero talento.', 'O retraimento dela escondia talento real.', 'Nuance psicológica'],
    ['il corollario', 'corolário', 'substantivo', 'Costi maggiori sono un corollario di quella scelta.', 'Custos maiores são um corolário dessa escolha.', 'Argumentação'],
    ['assiomatico', 'axiomático', 'adjetivo', 'È assiomatico in questo campo.', 'É axiomático nesta área.', 'Argumentação'],
    ['incontrovertibile', 'incontestável', 'adjetivo', 'I dati sono incontrovertibili.', 'Os dados são incontestáveis.', 'Argumentação'],
    ['probante', 'probatório / conclusivo', 'adjetivo', 'Ha presentato un caso probante.', 'Ela apresentou um caso conclusivo.', 'Argumentação'],
    ['estrapolare', 'extrapolar', 'verbo', 'Non estrapolare da un solo caso.', 'Não extrapole a partir de um caso.', 'Argumentação'],
    ['la capziosità', 'capciosidade / sofisma', 'substantivo', 'Quella difesa è pura capziosità.', 'Essa defesa é pura capciosidade.', 'Argumentação'],
    ['in malafede', 'de má-fé', 'adjetivo', 'Quella risposta è in malafede.', 'Essa resposta é de má-fé.', 'Argumentação'],
    ['specioso', 'especioso', 'adjetivo', 'Il ragionamento è specioso.', 'O raciocínio é especioso.', 'Argumentação'],
    ['pertinente', 'pertinente', 'adjetivo', 'La tua osservazione è pertinente.', 'Sua observação é pertinente.', 'Argumentação'],
    ['ipso facto', 'por isso mesmo', 'advérbio', 'Non ne consegue ipso facto.', 'Não decorre disso por isso mesmo.', 'Argumentação'],
    ['la verosimiglianza', 'verossimilhança', 'substantivo', 'Al film manca verosimiglianza.', 'O filme carece de verossimilhança.', 'Crítica e estética'],
    ['il pastiche', 'pastiche', 'substantivo', "L'album è un pastiche consapevole.", 'O álbum é um pastiche consciente.', 'Crítica e estética'],
    ['l’anticlimax', 'anticlímax', 'substantivo', "Il finale sprofonda nell'anticlimax.", 'O final desaba no anticlímax.', 'Crítica e estética'],
    ['lo scioglimento', 'desfecho', 'substantivo', 'Lo scioglimento è parso frettoloso.', 'O desfecho pareceu apressado.', 'Crítica e estética'],
    ['l’allegoria', 'alegoria', 'substantivo', "L'intero libro è un'allegoria.", 'O livro inteiro é uma alegoria.', 'Crítica e estética'],
    ['il motivo ricorrente', 'motivo recorrente', 'substantivo', "L'acqua è il motivo ricorrente centrale.", 'A água é o motivo recorrente central.', 'Crítica e estética'],
    ['l’iperbole', 'hipérbole', 'substantivo', "Questa è iperbole, non analisi.", 'Isso é hipérbole, não análise.', 'Crítica e estética'],
    ['il pathos', 'pathos / comoção', 'substantivo', 'La scena raggiunge un vero pathos.', 'A cena alcança comoção verdadeira.', 'Crítica e estética'],
    ['la satira', 'sátira', 'substantivo', 'Funziona meglio come satira.', 'Funciona melhor como sátira.', 'Crítica e estética'],
    ['l’opera omnia', 'obra completa', 'substantivo', 'Questo è minore nella sua opera omnia.', 'Isto é menor dentro da obra completa dela.', 'Crítica e estética'],
  ],
};
