/** Japonês — lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { AsianByLevel } from '../entry';

export const JA_THEMATIC: AsianByLevel = {
  A1: [
    ['緑', 'midori', 'verde', 'substantivo', '草は緑です。', 'Kusa wa midori desu.', 'A grama é verde.', 'Cores e formas'],
    ['黄色', 'kiiro', 'amarelo', 'substantivo', '黄色い花が好きです。', 'Kiiroi hana ga suki desu.', 'Gosto de flores amarelas.', 'Cores e formas'],
    ['黒', 'kuro', 'preto', 'substantivo', '黒いコートを着ています。', 'Kuroi kōto o kite imasu.', 'Ele usa um casaco preto.', 'Cores e formas'],
    ['白', 'shiro', 'branco', 'substantivo', '壁は白いです。', 'Kabe wa shiroi desu.', 'As paredes são brancas.', 'Cores e formas'],
    ['オレンジ色', 'orenjiiro', 'laranja (cor)', 'substantivo', 'オレンジ色のかばんです。', 'Orenjiiro no kaban desu.', 'É uma bolsa laranja.', 'Cores e formas'],
    ['紫', 'murasaki', 'roxo', 'substantivo', '空が紫になりました。', 'Sora ga murasaki ni narimashita.', 'O céu ficou roxo.', 'Cores e formas'],
    ['茶色', 'chairo', 'marrom', 'substantivo', '私の靴は茶色です。', 'Watashi no kutsu wa chairo desu.', 'Meus sapatos são marrons.', 'Cores e formas'],
    ['ピンク', 'pinku', 'rosa', 'substantivo', 'ピンクの毛布です。', 'Pinku no mōfu desu.', 'É um cobertor rosa.', 'Cores e formas'],
    ['丸', 'maru', 'círculo', 'substantivo', 'ここに丸を書いてください。', 'Koko ni maru o kaite kudasai.', 'Desenhe um círculo aqui.', 'Cores e formas'],
    ['四角', 'shikaku', 'quadrado', 'substantivo', 'この箱は四角です。', 'Kono hako wa shikaku desu.', 'Esta caixa é um quadrado.', 'Cores e formas'],
    ['シャツ', 'shatsu', 'camisa', 'substantivo', 'このシャツはきれいです。', 'Kono shatsu wa kirei desu.', 'Esta camisa está limpa.', 'Roupas'],
    ['ズボン', 'zubon', 'calça', 'substantivo', 'このズボンは新しいです。', 'Kono zubon wa atarashii desu.', 'Esta calça é nova.', 'Roupas'],
    ['靴', 'kutsu', 'sapatos', 'substantivo', '靴がぬれています。', 'Kutsu ga nurete imasu.', 'Os sapatos estão molhados.', 'Roupas'],
    ['ワンピース', 'wanpiisu', 'vestido', 'substantivo', 'ワンピースを買いました。', 'Wanpiisu o kaimashita.', 'Ela comprou um vestido.', 'Roupas'],
    ['上着', 'uwagi', 'jaqueta / casaco leve', 'substantivo', '上着を持って行ってください。', 'Uwagi o motte itte kudasai.', 'Leve sua jaqueta.', 'Roupas'],
    ['帽子', 'boushi', 'chapéu', 'substantivo', '帽子をなくしました。', 'Bōshi o nakushimashita.', 'Ele perdeu o chapéu.', 'Roupas'],
    ['靴下', 'kutsushita', 'meias', 'substantivo', 'きれいな靴下が要ります。', 'Kirei na kutsushita ga irimasu.', 'Preciso de meias limpas.', 'Roupas'],
    ['コート', 'kooto', 'casaco', 'substantivo', '今日はコートを着てください。', 'Kyō wa kōto o kite kudasai.', 'Use um casaco hoje.', 'Roupas'],
    ['スカート', 'sukaato', 'saia', 'substantivo', 'そのスカートは長いです。', 'Sono sukāto wa nagai desu.', 'Aquela saia é longa.', 'Roupas'],
    ['眼鏡', 'megane', 'óculos', 'substantivo', '眼鏡を忘れました。', 'Megane o wasuremashita.', 'Esqueci meus óculos.', 'Roupas'],
    ['太陽', 'taiyou', 'sol', 'substantivo', '太陽が強いです。', 'Taiyō ga tsuyoi desu.', 'O sol está forte.', 'Clima e natureza'],
    ['雨', 'ame', 'chuva', 'substantivo', '雨が止みました。', 'Ame ga yamimashita.', 'A chuva parou.', 'Clima e natureza'],
    ['雪', 'yuki', 'neve', 'substantivo', '雪が深いです。', 'Yuki ga fukai desu.', 'A neve está funda.', 'Clima e natureza'],
    ['風', 'kaze', 'vento', 'substantivo', '風が強いです。', 'Kaze ga tsuyoi desu.', 'O vento está forte.', 'Clima e natureza'],
    ['雲', 'kumo', 'nuvem', 'substantivo', '雲が一つあります。', 'Kumo ga hitotsu arimasu.', 'Há uma nuvem.', 'Clima e natureza'],
    ['木', 'ki', 'árvore', 'substantivo', 'この木は古いです。', 'Kono ki wa furui desu.', 'Esta árvore é velha.', 'Clima e natureza'],
    ['桜', 'sakura', 'cerejeira', 'substantivo', '桜がきれいです。', 'Sakura ga kirei desu.', 'As cerejeiras estão lindas.', 'Clima e natureza'],
    ['空', 'sora', 'céu', 'substantivo', '空が晴れています。', 'Sora ga harete imasu.', 'O céu está limpo.', 'Clima e natureza'],
    ['海辺', 'umibe', 'praia / beira-mar', 'substantivo', '海辺へ行きます。', 'Umibe e ikimasu.', 'Nós vamos à praia.', 'Clima e natureza'],
    ['山', 'yama', 'montanha', 'substantivo', 'あの山は高いです。', 'Ano yama wa takai desu.', 'Aquela montanha é alta.', 'Clima e natureza'],
    ['頭', 'atama', 'cabeça', 'substantivo', '頭が痛いです。', 'Atama ga itai desu.', 'Minha cabeça dói.', 'Corpo'],
    ['手', 'te', 'mão', 'substantivo', '手を貸してください。', 'Te o kashite kudasai.', 'Me dê uma mão.', 'Corpo'],
    ['足', 'ashi', 'pé', 'substantivo', '足が冷たいです。', 'Ashi ga tsumetai desu.', 'Meu pé está frio.', 'Corpo'],
    ['目', 'me', 'olho', 'substantivo', '目が疲れました。', 'Me ga tsukaremashita.', 'Meus olhos cansaram.', 'Corpo'],
    ['耳', 'mimi', 'orelha / ouvido', 'substantivo', '耳が痛いです。', 'Mimi ga itai desu.', 'Meu ouvido dói.', 'Corpo'],
    ['口', 'kuchi', 'boca', 'substantivo', '口を開けてください。', 'Kuchi o akete kudasai.', 'Abra a boca.', 'Corpo'],
    ['鼻', 'hana', 'nariz', 'substantivo', '鼻が赤いです。', 'Hana ga akai desu.', 'O nariz está vermelho.', 'Corpo'],
    ['髪', 'kami', 'cabelo', 'substantivo', '髪が長いです。', 'Kami ga nagai desu.', 'O cabelo dela é longo.', 'Corpo'],
    ['腕', 'ude', 'braço', 'substantivo', '腕を折りました。', 'Ude o orimashita.', 'Ele quebrou o braço.', 'Corpo'],
    ['膝', 'hiza', 'joelho', 'substantivo', '膝が痛いです。', 'Hiza ga itai desu.', 'Meu joelho dói.', 'Corpo'],
    ['パン', 'pan', 'pão', 'substantivo', '毎日パンを食べます。', 'Mainichi pan o tabemasu.', 'Eu como pão todo dia.', 'Comida e bebida'],
    ['牛乳', 'gyuunyuu', 'leite', 'substantivo', '牛乳が冷たいです。', 'Gyūnyū ga tsumetai desu.', 'O leite está frio.', 'Comida e bebida'],
    ['コーヒー', 'koohii', 'café', 'substantivo', '彼女はコーヒーを飲みます。', 'Kanojo wa kōhī o nomimasu.', 'Ela bebe café.', 'Comida e bebida'],
    ['ご飯', 'gohan', 'arroz cozido / refeição', 'substantivo', '昼にご飯を食べます。', 'Hiru ni gohan o tabemasu.', 'Comemos arroz no almoço.', 'Comida e bebida'],
    ['肉', 'niku', 'carne', 'substantivo', '彼は肉を食べません。', 'Kare wa niku o tabemasen.', 'Ele não come carne.', 'Comida e bebida'],
    ['果物', 'kudamono', 'fruta', 'substantivo', '果物を買ってください。', 'Kudamono o katte kudasai.', 'Compre frutas.', 'Comida e bebida'],
    ['卵', 'tamago', 'ovo', 'substantivo', '卵が一つ欲しいです。', 'Tamago ga hitotsu hoshii desu.', 'Quero um ovo.', 'Comida e bebida'],
    ['チーズ', 'chiizu', 'queijo', 'substantivo', 'このチーズはおいしいです。', 'Kono chīzu wa oishii desu.', 'Este queijo é bom.', 'Comida e bebida'],
    ['砂糖', 'satou', 'açúcar', 'substantivo', '砂糖は要りません。', 'Satō wa irimasen.', 'Sem açúcar, por favor.', 'Comida e bebida'],
    ['塩', 'shio', 'sal', 'substantivo', '塩を取ってください。', 'Shio o totte kudasai.', 'Me passe o sal.', 'Comida e bebida'],
    ['朝', 'asa', 'manhã', 'substantivo', '朝に働きます。', 'Asa ni hatarakimasu.', 'Eu trabalho de manhã.', 'Tempo e rotina'],
    ['昼', 'hiru', 'meio-dia / tarde', 'substantivo', '昼に会いましょう。', 'Hiru ni aimashō.', 'Vamos nos encontrar ao meio-dia.', 'Tempo e rotina'],
    ['夕方', 'yuugata', 'fim de tarde', 'substantivo', '夕方に帰ります。', 'Yūgata ni kaerimasu.', 'Volto no fim da tarde.', 'Tempo e rotina'],
    ['夜', 'yoru', 'noite', 'substantivo', '夜は静かです。', 'Yoru wa shizuka desu.', 'A noite está calma.', 'Tempo e rotina'],
    ['今週', 'konshuu', 'esta semana', 'substantivo', '今週は長いです。', 'Konshū wa nagai desu.', 'Esta semana está longa.', 'Tempo e rotina'],
    ['今月', 'kongetsu', 'este mês', 'substantivo', '今月は忙しいです。', 'Kongetsu wa isogashii desu.', 'Este mês está cheio.', 'Tempo e rotina'],
    ['今日', 'kyou', 'hoje', 'substantivo', '今日は疲れました。', 'Kyō wa tsukaremashita.', 'Estou cansado hoje.', 'Tempo e rotina'],
    ['明日', 'ashita', 'amanhã', 'substantivo', '明日旅行します。', 'Ashita ryokō shimasu.', 'Nós viajamos amanhã.', 'Tempo e rotina'],
    ['昨日', 'kinou', 'ontem', 'substantivo', '昨日雨が降りました。', 'Kinō ame ga furimashita.', 'Choveu ontem.', 'Tempo e rotina'],
    ['週末', 'shuumatsu', 'fim de semana', 'substantivo', '週末は休みます。', 'Shūmatsu wa yasumimasu.', 'No fim de semana eu descanso.', 'Tempo e rotina'],
  ],
  A2: [
    ['飛行機', 'hikouki', 'avião', 'substantivo', '飛行機は六時に出ます。', 'Hikōki wa rokuji ni demasu.', 'O avião sai às seis.', 'Viagem'],
    ['パスポート', 'pasupooto', 'passaporte', 'substantivo', 'パスポートを見せてください。', 'Pasupōto o misete kudasai.', 'Me mostre seu passaporte.', 'Viagem'],
    ['荷物', 'nimotsu', 'bagagem', 'substantivo', '荷物が重いです。', 'Nimotsu ga omoi desu.', 'Minha bagagem está pesada.', 'Viagem'],
    ['切符', 'kippu', 'passagem / bilhete', 'substantivo', 'ネットで切符を買いました。', 'Netto de kippu o kaimashita.', 'Comprei a passagem pela internet.', 'Viagem'],
    ['遅れ', 'okure', 'atraso', 'substantivo', '長い遅れがありました。', 'Nagai okure ga arimashita.', 'Houve um atraso longo.', 'Viagem'],
    ['空港', 'kuukou', 'aeroporto', 'substantivo', '空港は遠いです。', 'Kūkō wa tōi desu.', 'O aeroporto é longe.', 'Viagem'],
    ['スーツケース', 'suutsukeesu', 'mala', 'substantivo', '今夜スーツケースを準備します。', 'Kon’ya sūtsukēsu o junbi shimasu.', 'Preparo a mala hoje à noite.', 'Viagem'],
    ['出発', 'shuppatsu', 'partida', 'substantivo', '出発の時間を確認してください。', 'Shuppatsu no jikan o kakunin shite kudasai.', 'Confira o horário de partida.', 'Viagem'],
    ['到着', 'touchaku', 'chegada', 'substantivo', '到着は順調でした。', 'Tōchaku wa junchō deshita.', 'A chegada foi tranquila.', 'Viagem'],
    ['搭乗券', 'toujouken', 'cartão de embarque', 'substantivo', '搭乗券を持っていてください。', 'Tōjōken o motte ite kudasai.', 'Guarde seu cartão de embarque.', 'Viagem'],
    ['メニュー', 'menyuu', 'cardápio', 'substantivo', 'メニューを見せてください。', 'Menyū o misete kudasai.', 'Posso ver o cardápio?', 'Restaurante'],
    ['店員', 'ten’in', 'atendente / garçom', 'substantivo', '店員が来ます。', 'Ten’in ga kimasu.', 'O atendente está vindo.', 'Restaurante'],
    ['チップ', 'chippu', 'gorjeta', 'substantivo', 'チップを置きました。', 'Chippu o okimashita.', 'Deixamos gorjeta.', 'Restaurante'],
    ['デザート', 'dezaato', 'sobremesa', 'substantivo', 'デザートが欲しいです。', 'Dezāto ga hoshii desu.', 'Quero sobremesa.', 'Restaurante'],
    ['前菜', 'zensai', 'entrada (prato)', 'substantivo', '前菜は小さかったです。', 'Zensai wa chiisakatta desu.', 'A entrada era pequena.', 'Restaurante'],
    ['席の予約', 'seki no yoyaku', 'reserva de mesa', 'substantivo', '席の予約をしました。', 'Seki no yoyaku o shimashita.', 'Fiz uma reserva de mesa.', 'Restaurante'],
    ['ナプキン', 'napukin', 'guardanapo', 'substantivo', 'ナプキンを取ってください。', 'Napukin o totte kudasai.', 'Me passe um guardanapo.', 'Restaurante'],
    ['お盆', 'obon', 'bandeja', 'substantivo', 'お盆に置いてください。', 'Obon ni oite kudasai.', 'Coloque na bandeja.', 'Restaurante'],
    ['味', 'aji', 'sabor', 'substantivo', '味が変です。', 'Aji ga hen desu.', 'O sabor está estranho.', 'Restaurante'],
    ['辛い', 'karai', 'picante', 'adjetivo', 'この料理は辛いです。', 'Kono ryōri wa karai desu.', 'Este prato é picante.', 'Restaurante'],
    ['現金', 'genkin', 'dinheiro (em espécie)', 'substantivo', '現金しかありません。', 'Genkin shika arimasen.', 'Só tenho dinheiro em espécie.', 'Compras'],
    ['おつり', 'otsuri', 'troco', 'substantivo', 'おつりは要りません。', 'Otsuri wa irimasen.', 'Fique com o troco.', 'Compras'],
    ['サイズ', 'saizu', 'tamanho', 'substantivo', '大きいサイズはありますか。', 'Ōkii saizu wa arimasu ka.', 'Tem um tamanho maior?', 'Compras'],
    ['お買い得', 'okaidoku', 'pechincha', 'substantivo', 'あのコートはお買い得でした。', 'Ano kōto wa okaidoku deshita.', 'Aquele casaco foi uma pechincha.', 'Compras'],
    ['レジ係', 'rejigakari', 'operador de caixa', 'substantivo', 'レジ係に聞いてください。', 'Rejigakari ni kiite kudasai.', 'Pergunte ao caixa.', 'Compras'],
    ['通路', 'tsuuro', 'corredor', 'substantivo', '牛乳は三番の通路です。', 'Gyūnyū wa sanban no tsūro desu.', 'O leite está no corredor três.', 'Compras'],
    ['棚', 'tana', 'prateleira', 'substantivo', '棚が空です。', 'Tana ga kara desu.', 'A prateleira está vazia.', 'Compras'],
    ['セール', 'seeru', 'liquidação', 'substantivo', '靴がセール中です。', 'Kutsu ga sēru chū desu.', 'Os sapatos estão em liquidação.', 'Compras'],
    ['財布', 'saifu', 'carteira', 'substantivo', '財布を家に忘れました。', 'Saifu o ie ni wasuremashita.', 'Deixei minha carteira em casa.', 'Compras'],
    ['ブランド', 'burando', 'marca', 'substantivo', 'このブランドを信じています。', 'Kono burando o shinjite imasu.', 'Confio nesta marca.', 'Compras'],
    ['咳', 'seki', 'tosse', 'substantivo', '咳がひどいです。', 'Seki ga hidoi desu.', 'A tosse está feia.', 'Saúde'],
    ['頭痛', 'zutsuu', 'dor de cabeça', 'substantivo', '頭痛がします。', 'Zutsū ga shimasu.', 'Estou com dor de cabeça.', 'Saúde'],
    ['錠剤', 'jouzai', 'comprimido', 'substantivo', '一日一錠剤を飲んでください。', 'Ichinichi ichi jōzai o nonde kudasai.', 'Tome um comprimido por dia.', 'Saúde'],
    ['看護師', 'kangoshi', 'enfermeiro', 'substantivo', '看護師は親切でした。', 'Kangoshi wa shinsetsu deshita.', 'O enfermeiro foi gentil.', 'Saúde'],
    ['けが', 'kega', 'ferimento', 'substantivo', 'けがは重かったです。', 'Kega wa omokatta desu.', 'O ferimento foi sério.', 'Saúde'],
    ['休養', 'kyuuyou', 'descanso', 'substantivo', '休養が必要です。', 'Kyūyō ga hitsuyō desu.', 'Você precisa de descanso.', 'Saúde'],
    ['包帯', 'houtai', 'bandagem', 'substantivo', '包帯を巻いてください。', 'Hōtai o maite kudasai.', 'Coloque uma bandagem.', 'Saúde'],
    ['めまい', 'memai', 'tontura', 'substantivo', 'めまいがします。', 'Memai ga shimasu.', 'Estou tonto.', 'Saúde'],
    ['診療所', 'shinryoujo', 'clínica', 'substantivo', '診療所は八時に開きます。', 'Shinryōjo wa hachiji ni akimasu.', 'A clínica abre às oito.', 'Saúde'],
    ['痛み', 'itami', 'dor', 'substantivo', '背中に痛みがあります。', 'Senaka ni itami ga arimasu.', 'Tenho dor nas costas.', 'Saúde'],
    ['橋', 'hashi', 'ponte', 'substantivo', '橋を渡ってください。', 'Hashi o watatte kudasai.', 'Atravesse a ponte.', 'Cidade'],
    ['広場', 'hiroba', 'praça', 'substantivo', '広場で会いました。', 'Hiroba de aimashita.', 'Nos encontramos na praça.', 'Cidade'],
    ['角', 'kado', 'esquina', 'substantivo', '角を曲がってください。', 'Kado o magatte kudasai.', 'Vire na esquina.', 'Cidade'],
    ['渋滞', 'juutai', 'congestionamento', 'substantivo', '渋滞がひどいです。', 'Jūtai ga hidoi desu.', 'O trânsito está terrível.', 'Cidade'],
    ['地下鉄', 'chikatetsu', 'metrô', 'substantivo', '地下鉄に乗ってください。', 'Chikatetsu ni notte kudasai.', 'Pegue o metrô.', 'Cidade'],
    ['停留所', 'teiryuujo', 'ponto de ônibus', 'substantivo', '次の停留所で降りてください。', 'Tsugi no teiryūjo de orite kudasai.', 'Desça na próxima parada.', 'Cidade'],
    ['地図', 'chizu', 'mapa', 'substantivo', '地図を見てください。', 'Chizu o mite kudasai.', 'Olhe o mapa.', 'Cidade'],
    ['道', 'michi', 'caminho / rua', 'substantivo', 'この道を行ってください。', 'Kono michi o itte kudasai.', 'Siga este caminho.', 'Cidade'],
    ['門', 'mon', 'portão', 'substantivo', '門が閉まっています。', 'Mon ga shimatte imasu.', 'O portão está fechado.', 'Cidade'],
    ['横断歩道', 'oudanhodou', 'faixa de pedestres', 'substantivo', '横断歩道を使ってください。', 'Ōdanhodō o tsukatte kudasai.', 'Use a faixa de pedestres.', 'Cidade'],
    ['洗濯', 'sentaku', 'lavagem de roupa', 'substantivo', '日曜日に洗濯します。', 'Nichiyōbi ni sentaku shimasu.', 'Eu lavo a roupa no domingo.', 'Casa e tarefas'],
    ['食器', 'shokki', 'louça', 'substantivo', '彼は食器を洗います。', 'Kare wa shokki o araimasu.', 'Ele lava a louça.', 'Casa e tarefas'],
    ['ほうき', 'houki', 'vassoura', 'substantivo', 'ほうきはどこですか。', 'Hōki wa doko desu ka.', 'Onde está a vassoura?', 'Casa e tarefas'],
    ['ごみ', 'gomi', 'lixo', 'substantivo', 'ごみを出してください。', 'Gomi o dashite kudasai.', 'Leve o lixo para fora.', 'Casa e tarefas'],
    ['タオル', 'taoru', 'toalha', 'substantivo', 'タオルがぬれています。', 'Taoru ga nurete imasu.', 'A toalha está molhada.', 'Casa e tarefas'],
    ['毛布', 'moufu', 'cobertor', 'substantivo', 'もう一枚毛布が要ります。', 'Mō ichimai mōfu ga irimasu.', 'Preciso de outro cobertor.', 'Casa e tarefas'],
    ['引き出し', 'hikidashi', 'gaveta', 'substantivo', '引き出しの中にあります。', 'Hikidashi no naka ni arimasu.', 'Está na gaveta.', 'Casa e tarefas'],
    ['押し入れ', 'oshiire', 'armário embutido', 'substantivo', '押し入れにしまってください。', 'Oshiire ni shimatte kudasai.', 'Guarde no armário.', 'Casa e tarefas'],
    ['流し', 'nagashi', 'pia', 'substantivo', '流しが詰まっています。', 'Nagashi ga tsumatte imasu.', 'A pia está entupida.', 'Casa e tarefas'],
    ['鏡', 'kagami', 'espelho', 'substantivo', '鏡を見てください。', 'Kagami o mite kudasai.', 'Olhe no espelho.', 'Casa e tarefas'],
  ],
  B1: [
    ['面接', 'mensetsu', 'entrevista de emprego', 'substantivo', '面接はうまくいきました。', 'Mensetsu wa umaku ikimashita.', 'A entrevista correu bem.', 'Trabalho'],
    ['履歴書', 'rirekisho', 'currículo', 'substantivo', '履歴書を送ってください。', 'Rirekisho o okutte kudasai.', 'Me mande seu currículo.', 'Trabalho'],
    ['シフト', 'shifuto', 'turno', 'substantivo', '夜のシフトで働きます。', 'Yoru no shifuto de hatarakimasu.', 'Eu trabalho no turno da noite.', 'Trabalho'],
    ['残業', 'zangyou', 'hora extra', 'substantivo', 'また残業しました。', 'Mata zangyō shimashita.', 'Ela fez hora extra de novo.', 'Trabalho'],
    ['インターン', 'intaan', 'estágio', 'substantivo', 'インターンに受かりました。', 'Intān ni ukarimashita.', 'Ele conseguiu um estágio.', 'Trabalho'],
    ['上司', 'joushi', 'chefe / superior', 'substantivo', '上司に相談してください。', 'Jōshi ni sōdan shite kudasai.', 'Fale com seu chefe.', 'Trabalho'],
    ['業務', 'gyoumu', 'trabalho / função', 'substantivo', 'この業務は二時間かかります。', 'Kono gyōmu wa nijikan kakarimasu.', 'Esta tarefa leva duas horas.', 'Trabalho'],
    ['打ち合わせ', 'uchiawase', 'reunião de trabalho', 'substantivo', '打ち合わせが中止になりました。', 'Uchiawase ga chūshi ni narimashita.', 'A reunião foi cancelada.', 'Trabalho'],
    ['従業員', 'juugyouin', 'funcionário', 'substantivo', '従業員は親切です。', 'Jūgyōin wa shinsetsu desu.', 'Os funcionários são simpáticos.', 'Trabalho'],
    ['契約', 'keiyaku', 'contrato', 'substantivo', 'まず契約を読んでください。', 'Mazu keiyaku o yonde kudasai.', 'Leia o contrato primeiro.', 'Trabalho'],
    ['更新', 'koushin', 'atualização', 'substantivo', '更新をインストールしてください。', 'Kōshin o insutōru shite kudasai.', 'Instale a atualização.', 'Tecnologia'],
    ['パスワード', 'pasuwaado', 'senha', 'substantivo', 'パスワードを忘れました。', 'Pasuwādo o wasuremashita.', 'Esqueci minha senha.', 'Tecnologia'],
    ['バックアップ', 'bakkuappu', 'cópia de segurança', 'substantivo', '先にバックアップを取ってください。', 'Saki ni bakkuappu o totte kudasai.', 'Faça uma cópia de segurança antes.', 'Tecnologia'],
    ['端末', 'tanmatsu', 'dispositivo', 'substantivo', 'この端末は速いです。', 'Kono tanmatsu wa hayai desu.', 'Este dispositivo é rápido.', 'Tecnologia'],
    ['画面', 'gamen', 'tela', 'substantivo', '画面が割れています。', 'Gamen ga warete imasu.', 'A tela está quebrada.', 'Tecnologia'],
    ['ダウンロード', 'daunroodo', 'download', 'substantivo', '今ダウンロードしてください。', 'Ima daunrōdo shite kudasai.', 'Baixe agora.', 'Tecnologia'],
    ['ネットワーク', 'nettowaaku', 'rede', 'substantivo', 'ネットワークが止まっています。', 'Nettowāku ga tomatte imasu.', 'A rede está fora do ar.', 'Tecnologia'],
    ['ブラウザ', 'burauza', 'navegador', 'substantivo', 'ブラウザで開いてください。', 'Burauza de hiraite kudasai.', 'Abra no navegador.', 'Tecnologia'],
    ['フォルダ', 'foruda', 'pasta', 'substantivo', 'このフォルダに保存してください。', 'Kono foruda ni hozon shite kudasai.', 'Salve nesta pasta.', 'Tecnologia'],
    ['落ちる', 'ochiru', 'travar / cair (sistema)', 'verbo', 'アプリがまた落ちました。', 'Apuri ga mata ochimashita.', 'O aplicativo travou de novo.', 'Tecnologia'],
    ['リサイクル', 'risaikuru', 'reciclagem', 'substantivo', 'ここでリサイクルします。', 'Koko de risaikuru shimasu.', 'Aqui nós reciclamos.', 'Meio ambiente'],
    ['汚染', 'osen', 'poluição', 'substantivo', '汚染がひどくなりました。', 'Osen ga hidoku narimashita.', 'A poluição piorou.', 'Meio ambiente'],
    ['廃棄物', 'haikibutsu', 'resíduo', 'substantivo', '廃棄物が問題です。', 'Haikibutsu ga mondai desu.', 'O resíduo é um problema.', 'Meio ambiente'],
    ['気候', 'kikou', 'clima', 'substantivo', '気候が変わっています。', 'Kikō ga kawatte imasu.', 'O clima está mudando.', 'Meio ambiente'],
    ['エネルギー', 'enerugii', 'energia', 'substantivo', '太陽エネルギーは安くなりました。', 'Taiyō enerugī wa yasuku narimashita.', 'A energia solar ficou mais barata.', 'Meio ambiente'],
    ['森', 'mori', 'floresta', 'substantivo', 'この森は守られています。', 'Kono mori wa mamorarete imasu.', 'Esta floresta é protegida.', 'Meio ambiente'],
    ['種', 'shu', 'espécie', 'substantivo', 'この種は珍しいです。', 'Kono shu wa mezurashii desu.', 'Esta espécie é rara.', 'Meio ambiente'],
    ['干ばつ', 'kanbatsu', 'seca', 'substantivo', '干ばつが何か月も続きました。', 'Kanbatsu ga nankagetsu mo tsuzukimashita.', 'A seca durou meses.', 'Meio ambiente'],
    ['洪水', 'kouzui', 'enchente', 'substantivo', '洪水が道路を壊しました。', 'Kōzui ga dōro o kowashimashita.', 'A enchente danificou a estrada.', 'Meio ambiente'],
    ['排水', 'haisui', 'efluente / descarga de água', 'substantivo', '排水が川に届きました。', 'Haisui ga kawa ni todokimashita.', 'O efluente chegou ao rio.', 'Meio ambiente'],
    ['審判', 'shinpan', 'árbitro', 'substantivo', '審判が試合を止めました。', 'Shinpan ga shiai o tomemashita.', 'O árbitro parou o jogo.', 'Esportes'],
    ['トーナメント', 'toonamento', 'torneio', 'substantivo', 'トーナメントで優勝しました。', 'Tōnamento de yūshō shimashita.', 'Ela venceu o torneio.', 'Esportes'],
    ['相手', 'aite', 'adversário', 'substantivo', '相手のほうが速かったです。', 'Aite no hō ga hayakatta desu.', 'O adversário era mais rápido.', 'Esportes'],
    ['チームメイト', 'chiimumeito', 'companheiro de equipe', 'substantivo', 'チームメイトが得点しました。', 'Chīmumeito ga tokuten shimashita.', 'Meu companheiro de equipe marcou.', 'Esportes'],
    ['監督', 'kantoku', 'treinador', 'substantivo', '監督は怒っていました。', 'Kantoku wa okotte imashita.', 'O treinador estava bravo.', 'Esportes'],
    ['得点', 'tokuten', 'pontuação', 'substantivo', '得点はいくつですか。', 'Tokuten wa ikutsu desu ka.', 'Qual é o placar?', 'Esportes'],
    ['試合', 'shiai', 'partida', 'substantivo', '試合は八時に始まります。', 'Shiai wa hachiji ni hajimarimasu.', 'A partida começa às oito.', 'Esportes'],
    ['練習', 'renshuu', 'treino', 'substantivo', '練習は毎朝あります。', 'Renshū wa maiasa arimasu.', 'O treino é toda manhã.', 'Esportes'],
    ['持久力', 'jikyuuryoku', 'resistência física', 'substantivo', '彼は持久力があります。', 'Kare wa jikyūryoku ga arimasu.', 'Ele tem muita resistência.', 'Esportes'],
    ['選手権', 'senshuken', 'campeonato', 'substantivo', '選手権で負けました。', 'Senshuken de makemashita.', 'Eles perderam o campeonato.', 'Esportes'],
    ['口論する', 'kouron suru', 'discutir / bater boca', 'verbo', 'お金のことで口論します。', 'Okane no koto de kōron shimasu.', 'Eles discutem por dinheiro.', 'Relacionamentos'],
    ['謝る', 'ayamaru', 'pedir desculpas', 'verbo', '彼はすぐに謝りました。', 'Kare wa sugu ni ayamarimashita.', 'Ele pediu desculpas rápido.', 'Relacionamentos'],
    ['信頼', 'shinrai', 'confiança', 'substantivo', '信頼には時間がかかります。', 'Shinrai ni wa jikan ga kakarimasu.', 'Confiança leva tempo.', 'Relacionamentos'],
    ['嫉妬深い', 'shittobukai', 'ciumento', 'adjetivo', '彼女は嫉妬深いです。', 'Kanojo wa shittobukai desu.', 'Ela é ciumenta.', 'Relacionamentos'],
    ['忠実な', 'chuujitsu na', 'leal', 'adjetivo', '彼は忠実な友達です。', 'Kare wa chūjitsu na tomodachi desu.', 'Ele é um amigo leal.', 'Relacionamentos'],
    ['噂話', 'uwasabanashi', 'fofoca', 'substantivo', '噂話が嫌いです。', 'Uwasabanashi ga kirai desu.', 'Odeio fofoca.', 'Relacionamentos'],
    ['助言', 'jogen', 'conselho', 'substantivo', 'いい助言でした。', 'Ii jogen deshita.', 'Foi um bom conselho.', 'Relacionamentos'],
    ['頼み', 'tanomi', 'pedido / favor', 'substantivo', '一つ頼みがあります。', 'Hitotsu tanomi ga arimasu.', 'Tenho um favor a pedir.', 'Relacionamentos'],
    ['仲たがい', 'nakatagai', 'desentendimento', 'substantivo', '小さな仲たがいがありました。', 'Chiisana nakatagai ga arimashita.', 'Houve um pequeno desentendimento.', 'Relacionamentos'],
    ['妥協', 'dakyou', 'acordo mútuo', 'substantivo', '妥協に達しました。', 'Dakyō ni tasshimashita.', 'Chegamos a um acordo.', 'Relacionamentos'],
    ['予算', 'yosan', 'orçamento', 'substantivo', '予算を守ってください。', 'Yosan o mamotte kudasai.', 'Siga o orçamento.', 'Dinheiro'],
    ['貯金', 'chokin', 'poupança', 'substantivo', '貯金を使いました。', 'Chokin o tsukaimashita.', 'Ela usou a poupança.', 'Dinheiro'],
    ['融資', 'yuushi', 'empréstimo (bancário)', 'substantivo', '融資を受けました。', 'Yūshi o ukemashita.', 'Ele fez um empréstimo.', 'Dinheiro'],
    ['借金', 'shakkin', 'dívida', 'substantivo', '借金を返しました。', 'Shakkin o kaeshimashita.', 'Eles quitaram a dívida.', 'Dinheiro'],
    ['出費', 'shuppi', 'despesa', 'substantivo', '家賃が一番の出費です。', 'Yachin ga ichiban no shuppi desu.', 'O aluguel é minha maior despesa.', 'Dinheiro'],
    ['利子', 'rishi', 'juros', 'substantivo', '利子が高すぎます。', 'Rishi ga takasugimasu.', 'Os juros estão altos demais.', 'Dinheiro'],
    ['投資する', 'toushi suru', 'investir', 'verbo', '不動産に投資します。', 'Fudōsan ni tōshi shimasu.', 'Eles investem em imóveis.', 'Dinheiro'],
    ['住宅ローン', 'juutaku roon', 'financiamento imobiliário', 'substantivo', '住宅ローンがあります。', 'Jūtaku rōn ga arimasu.', 'Nós temos um financiamento.', 'Dinheiro'],
    ['保険', 'hoken', 'seguro', 'substantivo', '車の保険は高いです。', 'Kuruma no hoken wa takai desu.', 'O seguro do carro é caro.', 'Dinheiro'],
    ['最低賃金', 'saitei chingin', 'salário mínimo', 'substantivo', '最低賃金が上がりました。', 'Saitei chingin ga agarimashita.', 'O salário mínimo subiu.', 'Dinheiro'],
  ],
  B2: [
    ['選挙運動', 'senkyo undou', 'campanha eleitoral', 'substantivo', '選挙運動は六週間続きました。', 'Senkyo undō wa rokushūkan tsuzukimashita.', 'A campanha durou seis semanas.', 'Política'],
    ['有権者', 'yuukensha', 'eleitor', 'substantivo', '有権者は分かれています。', 'Yūkensha wa wakarete imasu.', 'O eleitorado está dividido.', 'Política'],
    ['法制', 'housei', 'legislação', 'substantivo', '新しい法制が成立しました。', 'Atarashii hōsei ga seiritsu shimashita.', 'Uma nova legislação foi aprovada.', 'Política'],
    ['陳情', 'chinjou', 'lobby / petição', 'substantivo', '陳情が法案を変えました。', 'Chinjō ga hōan o kaemashita.', 'O lobby mudou o projeto de lei.', 'Política'],
    ['汚職', 'oshoku', 'corrupção', 'substantivo', '汚職が信頼を壊します。', 'Oshoku ga shinrai o kowashimasu.', 'A corrupção destrói a confiança.', 'Política'],
    ['国民投票', 'kokumin touhyou', 'referendo', 'substantivo', '国民投票を行いました。', 'Kokumin tōhyō o okonaimashita.', 'Eles realizaram um referendo.', 'Política'],
    ['連立', 'renritsu', 'coalizão', 'substantivo', '連立が崩れました。', 'Renritsu ga kuzuremashita.', 'A coalizão desmoronou.', 'Política'],
    ['投票用紙', 'touhyou youshi', 'cédula de votação', 'substantivo', '投票用紙は秘密です。', 'Tōhyō yōshi wa himitsu desu.', 'A cédula é secreta.', 'Política'],
    ['選挙区', 'senkyoku', 'distrito eleitoral', 'substantivo', '選挙区を訪ねました。', 'Senkyoku o tazunemashita.', 'Ela visitou seu distrito eleitoral.', 'Política'],
    ['負託', 'futaku', 'mandato confiado', 'substantivo', '国民の負託を受けました。', 'Kokumin no futaku o ukemashita.', 'Recebeu o mandato do povo.', 'Política'],
    ['インフレ', 'infure', 'inflação', 'substantivo', 'インフレが落ち着きました。', 'Infure ga ochitsukimashita.', 'A inflação desacelerou.', 'Economia'],
    ['不況', 'fukyou', 'recessão', 'substantivo', '国が不況に入りました。', 'Kuni ga fukyō ni hairimashita.', 'O país entrou em recessão.', 'Economia'],
    ['補助金', 'hojokin', 'subsídio', 'substantivo', '補助金が削られました。', 'Hojokin ga kezuraremashita.', 'O subsídio foi cortado.', 'Economia'],
    ['関税', 'kanzei', 'tarifa alfandegária', 'substantivo', '関税をかけました。', 'Kanzei o kakemashita.', 'Impuseram uma tarifa.', 'Economia'],
    ['黒字', 'kuroji', 'superávit', 'substantivo', '予算は黒字です。', 'Yosan wa kuroji desu.', 'O orçamento está em superávit.', 'Economia'],
    ['赤字', 'akaji', 'déficit', 'substantivo', '赤字が増えています。', 'Akaji ga fuete imasu.', 'O déficit continua crescendo.', 'Economia'],
    ['供給', 'kyoukyuu', 'oferta / fornecimento', 'substantivo', '供給が足りません。', 'Kyōkyū ga tarimasen.', 'A oferta não é suficiente.', 'Economia'],
    ['需要', 'juyou', 'procura / demanda', 'substantivo', '需要が急に下がりました。', 'Juyō ga kyū ni sagarimashita.', 'A procura caiu bruscamente.', 'Economia'],
    ['独占', 'dokusen', 'monopólio', 'substantivo', 'ほぼ独占状態です。', 'Hobo dokusen jōtai desu.', 'É quase um monopólio.', 'Economia'],
    ['緊縮', 'kinshuku', 'austeridade', 'substantivo', '緊縮が公共サービスを直撃しました。', 'Kinshuku ga kōkyō sābisu o chokugeki shimashita.', 'A austeridade atingiu os serviços públicos.', 'Economia'],
    ['実験', 'jikken', 'experimento', 'substantivo', '実験は二回失敗しました。', 'Jikken wa nikai shippai shimashita.', 'O experimento falhou duas vezes.', 'Ciência'],
    ['証拠', 'shouko', 'evidência', 'substantivo', '強い証拠があります。', 'Tsuyoi shōko ga arimasu.', 'Há evidências fortes.', 'Ciência'],
    ['標本', 'hyouhon', 'amostra', 'substantivo', '標本が小さすぎました。', 'Hyōhon ga chiisasugimashita.', 'A amostra era pequena demais.', 'Ciência'],
    ['研究室', 'kenkyuushitsu', 'laboratório', 'substantivo', '研究室で働いています。', 'Kenkyūshitsu de hataraite imasu.', 'Ela trabalha num laboratório.', 'Ciência'],
    ['分子', 'bunshi', 'molécula', 'substantivo', '水は簡単な分子です。', 'Mizu wa kantan na bunshi desu.', 'A água é uma molécula simples.', 'Ciência'],
    ['ゲノム', 'genomu', 'genoma', 'substantivo', 'ゲノムを解読しました。', 'Genomu o kaidoku shimashita.', 'Eles decifraram o genoma.', 'Ciência'],
    ['ワクチン', 'wakuchin', 'vacina', 'substantivo', 'ワクチンはよく効きます。', 'Wakuchin wa yoku kikimasu.', 'A vacina funciona bem.', 'Ciência'],
    ['微生物', 'biseibutsu', 'micróbio', 'substantivo', 'この微生物は無害です。', 'Kono biseibutsu wa mugai desu.', 'Este micróbio é inofensivo.', 'Ciência'],
    ['放射線', 'houshasen', 'radiação', 'substantivo', '放射線の値は正常です。', 'Hōshasen no atai wa seijō desu.', 'Os níveis de radiação estão normais.', 'Ciência'],
    ['望遠鏡', 'bouenkyou', 'telescópio', 'substantivo', '望遠鏡が惑星を見つけました。', 'Bōenkyō ga wakusei o mitsukemashita.', 'O telescópio encontrou um planeta.', 'Ciência'],
    ['見出し', 'midashi', 'manchete', 'substantivo', '見出しが誤解を招きました。', 'Midashi ga gokai o manekimashita.', 'A manchete induziu ao erro.', 'Mídia'],
    ['報道', 'houdou', 'cobertura jornalística', 'substantivo', '報道が偏っていました。', 'Hōdō ga katayotte imashita.', 'A cobertura foi tendenciosa.', 'Mídia'],
    ['検閲', 'ken’etsu', 'censura', 'substantivo', '検閲が去年増えました。', 'Ken’etsu ga kyonen fuemashita.', 'A censura aumentou no ano passado.', 'Mídia'],
    ['宣伝', 'senden', 'propaganda', 'substantivo', 'これはただの宣伝です。', 'Kore wa tada no senden desu.', 'Isso é pura propaganda.', 'Mídia'],
    ['放送', 'housou', 'transmissão', 'substantivo', '放送は何百万人に届きました。', 'Hōsō wa nanbyakuman-nin ni todokimashita.', 'A transmissão alcançou milhões.', 'Mídia'],
    ['記者', 'kisha', 'jornalista', 'substantivo', '記者が情報を確認しました。', 'Kisha ga jōhō o kakunin shimashita.', 'A jornalista checou a informação.', 'Mídia'],
    ['社説', 'shasetsu', 'editorial', 'substantivo', '社説が計画を批判しました。', 'Shasetsu ga keikaku o hihan shimashita.', 'O editorial criticou o plano.', 'Mídia'],
    ['大衆紙', 'taishuushi', 'imprensa sensacionalista', 'substantivo', '大衆紙は信用できません。', 'Taishūshi wa shin’yō dekimasen.', 'Não dá para confiar na imprensa sensacionalista.', 'Mídia'],
    ['聴衆', 'choushuu', 'público / plateia', 'substantivo', '聴衆は冷たかったです。', 'Chōshū wa tsumetakatta desu.', 'O público estava frio.', 'Mídia'],
    ['情報源', 'jouhougen', 'fonte de informação', 'substantivo', '情報源を明かしてください。', 'Jōhōgen o akashite kudasai.', 'Revele sua fonte.', 'Mídia'],
    ['共感', 'kyoukan', 'empatia', 'substantivo', '共感は学べます。', 'Kyōkan wa manabemasu.', 'A empatia pode ser aprendida.', 'Psicologia'],
    ['不安', 'fuan', 'ansiedade', 'substantivo', '不安が睡眠に影響します。', 'Fuan ga suimin ni eikyō shimasu.', 'A ansiedade afeta o sono.', 'Psicologia'],
    ['トラウマ', 'torauma', 'trauma', 'substantivo', 'トラウマが何年も続きました。', 'Torauma ga nannen mo tsuzukimashita.', 'O trauma durou anos.', 'Psicologia'],
    ['動機付け', 'doukizuke', 'motivação', 'substantivo', '結果がないと動機付けが消えます。', 'Kekka ga nai to dōkizuke ga kiemasu.', 'A motivação some sem resultados.', 'Psicologia'],
    ['知覚', 'chikaku', 'percepção', 'substantivo', '知覚が記憶を形作ります。', 'Chikaku ga kioku o katachizukurimasu.', 'A percepção molda a memória.', 'Psicologia'],
    ['行動', 'koudou', 'comportamento', 'substantivo', '彼の行動が急に変わりました。', 'Kare no kōdō ga kyū ni kawarimashita.', 'O comportamento dele mudou de repente.', 'Psicologia'],
    ['本能', 'honnou', 'instinto', 'substantivo', 'ここは本能を信じてください。', 'Koko wa honnō o shinjite kudasai.', 'Confie no seu instinto aqui.', 'Psicologia'],
    ['気分', 'kibun', 'humor / estado de espírito', 'substantivo', '気分がよくなりました。', 'Kibun ga yoku narimashita.', 'O humor melhorou.', 'Psicologia'],
    ['自尊心', 'jisonshin', 'autoestima', 'substantivo', '自尊心が低い人は多いです。', 'Jisonshin ga hikui hito wa ōi desu.', 'Baixa autoestima é comum.', 'Psicologia'],
    ['恨み', 'urami', 'ressentimento', 'substantivo', '恨みが少しずつ育ちました。', 'Urami ga sukoshi zutsu sodachimashita.', 'O ressentimento cresceu devagar.', 'Psicologia'],
    ['訴訟', 'soshou', 'processo judicial', 'substantivo', '訴訟を起こしました。', 'Soshō o okoshimashita.', 'Eles entraram com um processo.', 'Direito'],
    ['評決', 'hyouketsu', 'veredicto', 'substantivo', '評決が皆を驚かせました。', 'Hyōketsu ga mina o odorokasemashita.', 'O veredicto surpreendeu todos.', 'Direito'],
    ['証言', 'shougen', 'depoimento', 'substantivo', '彼女の証言が決め手でした。', 'Kanojo no shōgen ga kimete deshita.', 'O depoimento dela foi decisivo.', 'Direito'],
    ['証人', 'shounin', 'testemunha', 'substantivo', '証人が話を変えました。', 'Shōnin ga hanashi o kaemashita.', 'A testemunha mudou a versão.', 'Direito'],
    ['被告', 'hikoku', 'réu', 'substantivo', '被告は黙っていました。', 'Hikoku wa damatte imashita.', 'O réu permaneceu calado.', 'Direito'],
    ['弁護士', 'bengoshi', 'advogado', 'substantivo', '弁護士に電話してください。', 'Bengoshi ni denwa shite kudasai.', 'Ligue para seu advogado.', 'Direito'],
    ['答弁', 'touben', 'alegação / resposta formal', 'substantivo', '答弁が短すぎました。', 'Tōben ga mijikasugimashita.', 'A alegação foi curta demais.', 'Direito'],
    ['控訴', 'kouso', 'recurso judicial', 'substantivo', '控訴に負けました。', 'Kōso ni makemashita.', 'Eles perderam o recurso.', 'Direito'],
    ['親権', 'shinken', 'guarda (de filhos)', 'substantivo', '彼女が親権を得ました。', 'Kanojo ga shinken o emashita.', 'Ela ganhou a guarda.', 'Direito'],
    ['法令', 'hourei', 'lei / decreto', 'substantivo', 'この法令は古いです。', 'Kono hōrei wa furui desu.', 'Esta lei está ultrapassada.', 'Direito'],
  ],
  C1: [
    ['仮説', 'kasetsu', 'hipótese', 'substantivo', '仮説は支持されませんでした。', 'Kasetsu wa shiji saremasen deshita.', 'A hipótese não se sustentou.', 'Pesquisa acadêmica'],
    ['方法論', 'houhouron', 'metodologia', 'substantivo', '方法論を明確に書いてください。', 'Hōhōron o meikaku ni kaite kudasai.', 'Descreva sua metodologia com clareza.', 'Pesquisa acadêmica'],
    ['相関', 'soukan', 'correlação', 'substantivo', '相関は因果ではありません。', 'Sōkan wa inga de wa arimasen.', 'Correlação não é causalidade.', 'Pesquisa acadêmica'],
    ['変数', 'hensuu', 'variável', 'substantivo', 'その変数を統制してください。', 'Sono hensū o tōsei shite kudasai.', 'Controle essa variável.', 'Pesquisa acadêmica'],
    ['実証的な', 'jisshouteki na', 'empírico', 'adjetivo', '実証的な裏付けが必要です。', 'Jisshōteki na urazuke ga hitsuyō desu.', 'Precisamos de respaldo empírico.', 'Pesquisa acadêmica'],
    ['査読', 'sadoku', 'revisão por pares', 'substantivo', '査読が誤りを見つけました。', 'Sadoku ga ayamari o mitsukemashita.', 'A revisão por pares pegou o erro.', 'Pesquisa acadêmica'],
    ['縦断研究', 'juudan kenkyuu', 'estudo longitudinal', 'substantivo', 'それは縦断研究でした。', 'Sore wa jūdan kenkyū deshita.', 'Foi um estudo longitudinal.', 'Pesquisa acadêmica'],
    ['追試', 'tsuishi', 'replicação (de experimento)', 'substantivo', '追試は二回失敗しました。', 'Tsuishi wa nikai shippai shimashita.', 'A replicação falhou duas vezes.', 'Pesquisa acadêmica'],
    ['推論', 'suiron', 'inferência', 'substantivo', 'その推論は広すぎます。', 'Sono suiron wa hirosugimasu.', 'Essa inferência é ampla demais.', 'Pesquisa acadêmica'],
    ['枠組み', 'wakugumi', 'arcabouço / paradigma', 'substantivo', '枠組みがゆっくり変わりました。', 'Wakugumi ga yukkuri kawarimashita.', 'O arcabouço mudou devagar.', 'Pesquisa acadêmica'],
    ['利害関係者', 'rigai kankeisha', 'parte interessada', 'substantivo', '利害関係者に相談してください。', 'Rigai kankeisha ni sōdan shite kudasai.', 'Consulte cada parte interessada.', 'Negócios'],
    ['買収', 'baishuu', 'aquisição', 'substantivo', '買収は五月に完了しました。', 'Baishū wa gogatsu ni kanryō shimashita.', 'A aquisição foi concluída em maio.', 'Negócios'],
    ['合併', 'gappei', 'fusão', 'substantivo', '合併に反対がありました。', 'Gappei ni hantai ga arimashita.', 'A fusão enfrentou resistência.', 'Negócios'],
    ['売上高', 'uriagedaka', 'faturamento', 'substantivo', '売上高が十二パーセント伸びました。', 'Uriagedaka ga jūni pāsento nobimashita.', 'O faturamento cresceu doze por cento.', 'Negócios'],
    ['賠償責任', 'baishou sekinin', 'responsabilidade indenizatória', 'substantivo', 'その条項は賠償責任を生みます。', 'Sono jōkō wa baishō sekinin o umimasu.', 'Aquela cláusula gera responsabilidade indenizatória.', 'Negócios'],
    ['仲裁', 'chuusai', 'arbitragem', 'substantivo', '仲裁に持ち込みました。', 'Chūsai ni mochikomimashita.', 'Levaram à arbitragem.', 'Negócios'],
    ['基準値', 'kijunchi', 'valor de referência', 'substantivo', '現実的な基準値を決めてください。', 'Genjitsuteki na kijunchi o kimete kudasai.', 'Defina um valor de referência realista.', 'Negócios'],
    ['実現可能性', 'jitsugen kanousei', 'viabilidade', 'substantivo', 'まず実現可能性を調べてください。', 'Mazu jitsugen kanōsei o shirabete kudasai.', 'Estude a viabilidade primeiro.', 'Negócios'],
    ['多角化', 'takakuka', 'diversificação', 'substantivo', '多角化がリスクを下げました。', 'Takakuka ga risuku o sagemashita.', 'A diversificação reduziu o risco.', 'Negócios'],
    ['調達', 'choutatsu', 'aquisição institucional', 'substantivo', '調達には何か月もかかります。', 'Chōtatsu ni wa nankagetsu mo kakarimasu.', 'O processo de compras leva meses.', 'Negócios'],
    ['存在論', 'sonzairon', 'ontologia', 'substantivo', 'それは存在論の問題です。', 'Sore wa sonzairon no mondai desu.', 'Isso é uma questão de ontologia.', 'Filosofia'],
    ['認識論', 'ninshikiron', 'epistemologia', 'substantivo', '認識論は知の根拠を問います。', 'Ninshikiron wa chi no konkyo o toimasu.', 'A epistemologia questiona a base do saber.', 'Filosofia'],
    ['決定論', 'ketteiron', 'determinismo', 'substantivo', '決定論は自由意志を否定します。', 'Ketteiron wa jiyū ishi o hitei shimasu.', 'O determinismo nega o livre-arbítrio.', 'Filosofia'],
    ['弁証法', 'benshouhou', 'dialética', 'substantivo', '弁証法で議論しました。', 'Benshōhō de giron shimashita.', 'Ele argumentou pela dialética.', 'Filosofia'],
    ['形而上学', 'keijijougaku', 'metafísica', 'substantivo', '形而上学は証明を拒みます。', 'Keijijōgaku wa shōmei o kobamimasu.', 'A metafísica resiste à comprovação.', 'Filosofia'],
    ['実存的な', 'jitsuzonteki na', 'existencial', 'adjetivo', '実存的な脅威になりました。', 'Jitsuzonteki na kyōi ni narimashita.', 'Virou uma ameaça existencial.', 'Filosofia'],
    ['目的論', 'mokutekiron', 'teleologia', 'substantivo', '目的論は目的から説明します。', 'Mokutekiron wa mokuteki kara setsumei shimasu.', 'A teleologia explica pela finalidade.', 'Filosofia'],
    ['虚無主義', 'kyomushugi', 'niilismo', 'substantivo', '虚無主義は内在的な意味を否定します。', 'Kyomushugi wa naizaiteki na imi o hitei shimasu.', 'O niilismo nega sentido inerente.', 'Filosofia'],
    ['公理', 'kouri', 'axioma', 'substantivo', '共通の公理から始めてください。', 'Kyōtsū no kōri kara hajimete kudasai.', 'Parta de um axioma comum.', 'Filosofia'],
    ['三段論法', 'sandan ronpou', 'silogismo', 'substantivo', 'その三段論法は無効です。', 'Sono sandan ronpō wa mukō desu.', 'Esse silogismo é inválido.', 'Filosofia'],
    ['階層化', 'kaisouka', 'estratificação', 'substantivo', '社会の階層化は続いています。', 'Shakai no kaisōka wa tsuzuite imasu.', 'A estratificação social persiste.', 'Sociologia'],
    ['同化', 'douka', 'assimilação', 'substantivo', '同化が求められました。', 'Dōka ga motomeraremashita.', 'Esperava-se a assimilação.', 'Sociologia'],
    ['人口動態の', 'jinkou doutai no', 'demográfico', 'adjetivo', '人口動態の変化は明らかです。', 'Jinkō dōtai no henka wa akiraka desu.', 'A mudança demográfica é clara.', 'Sociologia'],
    ['都市化', 'toshika', 'urbanização', 'substantivo', '都市化が加速しました。', 'Toshika ga kasoku shimashita.', 'A urbanização acelerou.', 'Sociologia'],
    ['世代集団', 'sedai shuudan', 'coorte geracional', 'substantivo', 'その世代集団は収入が低いです。', 'Sono sedai shūdan wa shūnyū ga hikui desu.', 'Essa geração ganha menos.', 'Sociologia'],
    ['社会規範', 'shakai kihan', 'norma social', 'substantivo', '社会規範が静かに変わりました。', 'Shakai kihan ga shizuka ni kawarimashita.', 'A norma social mudou silenciosamente.', 'Sociologia'],
    ['逸脱', 'itsudatsu', 'desvio (social)', 'substantivo', '逸脱は文脈で決まります。', 'Itsudatsu wa bunmyaku de kimarimasu.', 'O desvio é definido pelo contexto.', 'Sociologia'],
    ['社会移動', 'shakai idou', 'mobilidade social', 'substantivo', '社会移動が止まっています。', 'Shakai idō ga tomatte imasu.', 'A mobilidade social estagnou.', 'Sociologia'],
    ['血縁', 'ketsuen', 'parentesco consanguíneo', 'substantivo', '血縁の絆は強いままです。', 'Ketsuen no kizuna wa tsuyoi mama desu.', 'Os laços de parentesco seguem fortes.', 'Sociologia'],
    ['世俗化', 'sezokuka', 'secularização', 'substantivo', '世俗化は地域で違います。', 'Sezokuka wa chiiki de chigaimasu.', 'A secularização varia por região.', 'Sociologia'],
    ['予後', 'yogo', 'prognóstico', 'substantivo', '予後は慎重ながら良好です。', 'Yogo wa shinchō nagara ryōkō desu.', 'O prognóstico é cautelosamente bom.', 'Medicina'],
    ['慢性の', 'mansei no', 'crônico', 'adjetivo', '慢性の病気になりました。', 'Mansei no byōki ni narimashita.', 'Virou uma doença crônica.', 'Medicina'],
    ['良性の', 'ryousei no', 'benigno', 'adjetivo', '腫瘍は良性のものでした。', 'Shuyō wa ryōsei no mono deshita.', 'O tumor era benigno.', 'Medicina'],
    ['悪性の', 'akusei no', 'maligno', 'adjetivo', '検査で悪性のものと分かりました。', 'Kensa de akusei no mono to wakarimashita.', 'O exame revelou que era maligno.', 'Medicina'],
    ['寛解', 'kankai', 'remissão', 'substantivo', '一年間寛解が続いています。', 'Ichinenkan kankai ga tsuzuite imasu.', 'Está em remissão há um ano.', 'Medicina'],
    ['病理', 'byouri', 'patologia', 'substantivo', '病理の報告が届きました。', 'Byōri no hōkoku ga todokimashita.', 'O laudo de patologia chegou.', 'Medicina'],
    ['免疫', 'men’eki', 'imunidade', 'substantivo', '免疫は時間とともに弱まります。', 'Men’eki wa jikan to tomo ni yowamarimasu.', 'A imunidade diminui com o tempo.', 'Medicina'],
    ['用量', 'youryou', 'dosagem', 'substantivo', '用量を慎重に調整してください。', 'Yōryō o shinchō ni chōsei shite kudasai.', 'Ajuste a dosagem com cuidado.', 'Medicina'],
    ['切開', 'sekkai', 'incisão', 'substantivo', '切開はよく治りました。', 'Sekkai wa yoku naorimashita.', 'A incisão cicatrizou bem.', 'Medicina'],
    ['再発', 'saihatsu', 'recaída', 'substantivo', '再発の可能性は残ります。', 'Saihatsu no kanōsei wa nokorimasu.', 'Uma recaída ainda é possível.', 'Medicina'],
    ['修辞', 'shuuji', 'retórica', 'substantivo', '修辞が政策を追い越しました。', 'Shūji ga seisaku o oikoshimashita.', 'A retórica passou à frente da política.', 'Retórica'],
    ['説得', 'settoku', 'persuasão', 'substantivo', '説得は強制に勝ちます。', 'Settoku wa kyōsei ni kachimasu.', 'A persuasão vence a coerção.', 'Retórica'],
    ['逸話', 'itsuwa', 'anedota', 'substantivo', '逸話はデータではありません。', 'Itsuwa wa dēta de wa arimasen.', 'Uma anedota não é dado.', 'Retórica'],
    ['類推', 'ruisui', 'analogia', 'substantivo', 'ここで類推は成り立ちません。', 'Koko de ruisui wa naritachimasen.', 'A analogia falha aqui.', 'Retórica'],
    ['反論', 'hanron', 'refutação', 'substantivo', '彼の反論は見事でした。', 'Kare no hanron wa migoto deshita.', 'A refutação dele foi elegante.', 'Retórica'],
    ['含意', 'gan’i', 'conotação / implicação', 'substantivo', 'その言葉には含意があります。', 'Sono kotoba ni wa gan’i ga arimasu.', 'Aquela palavra carrega uma conotação.', 'Retórica'],
    ['応酬', 'oushuu', 'réplica / troca de argumentos', 'substantivo', '激しい応酬になりました。', 'Hageshii ōshū ni narimashita.', 'Virou uma troca acalorada.', 'Retórica'],
    ['雄弁', 'yuuben', 'eloquência', 'substantivo', '雄弁は弱い証拠を隠せません。', 'Yūben wa yowai shōko o kakusemasen.', 'A eloquência não esconde evidência fraca.', 'Retórica'],
    ['言説', 'gensetsu', 'discurso (campo)', 'substantivo', '公共の言説が荒れています。', 'Kōkyō no gensetsu ga arete imasu.', 'O discurso público se degradou.', 'Retórica'],
    ['脱線', 'dassen', 'digressão', 'substantivo', '脱線をお許しください。', 'Dassen o oyurushi kudasai.', 'Perdoe a digressão.', 'Retórica'],
  ],
  C2: [
    ['哀切な', 'aisetsu na', 'pungente / elegíaco', 'adjetivo', 'この小説は哀切な調子です。', 'Kono shōsetsu wa aisetsu na chōshi desu.', 'Este romance tem um tom elegíaco.', 'Registro literário'],
    ['陰鬱な', 'in’utsu na', 'sombrio / lúgubre', 'adjetivo', '陰鬱な声で話しました。', 'In’utsu na koe de hanashimashita.', 'Ele falou com uma voz lúgubre.', 'Registro literário'],
    ['牧歌的な', 'bokkateki na', 'idílico', 'adjetivo', '牧歌的な日々でした。', 'Bokkateki na hibi deshita.', 'Eram dias idílicos.', 'Registro literário'],
    ['美しい響きの', 'utsukushii hibiki no', 'melodioso', 'adjetivo', '美しい響きの語りでした。', 'Utsukushii hibiki no katari deshita.', 'Era uma narração melodiosa.', 'Registro literário'],
    ['もの悲しい', 'monoganashii', 'lamentoso / melancólico', 'adjetivo', 'もの悲しい旋律が流れました。', 'Monoganashii senritsu ga nagaremashita.', 'Uma melodia melancólica soou.', 'Registro literário'],
    ['輝かしい', 'kagayakashii', 'resplandecente', 'adjetivo', '輝かしい経歴の持ち主です。', 'Kagayakashii keireki no mochinushi desu.', 'Tem uma trajetória resplandecente.', 'Registro literário'],
    ['簡素な', 'kanso na', 'austero / despojado', 'adjetivo', '文体は簡素で正確です。', 'Buntai wa kanso de seikaku desu.', 'O estilo é austero e exato.', 'Registro literário'],
    ['気だるい', 'kedarui', 'lânguido', 'adjetivo', '気だるい午後でした。', 'Kedarui gogo deshita.', 'Foi uma tarde lânguida.', 'Registro literário'],
    ['幽玄な', 'yuugen na', 'sutil e profundo (estético)', 'adjetivo', '幽玄な美しさがあります。', 'Yūgen na utsukushisa ga arimasu.', 'Há uma beleza sutil e profunda.', 'Registro literário'],
    ['朗々とした', 'rourou to shita', 'sonoro / ressonante', 'adjetivo', '朗々とした声が響きました。', 'Rōrō to shita koe ga hibikimashita.', 'Uma voz sonora ecoou.', 'Registro literário'],
    ['係争', 'keisou', 'litígio', 'substantivo', '事件は係争になりました。', 'Jiken wa keisō ni narimashita.', 'O caso virou litígio.', 'Jurídico avançado'],
    ['管轄', 'kankatsu', 'jurisdição', 'substantivo', '裁判所に管轄がありません。', 'Saibansho ni kankatsu ga arimasen.', 'O tribunal não tem jurisdição.', 'Jurídico avançado'],
    ['起訴状', 'kisojou', 'denúncia formal', 'substantivo', '起訴状は六十ページありました。', 'Kisojō wa rokujū pēji arimashita.', 'A denúncia tinha sessenta páginas.', 'Jurídico avançado'],
    ['責任能力', 'sekinin nouryoku', 'imputabilidade', 'substantivo', '責任能力は認められませんでした。', 'Sekinin nōryoku wa mitomeraremasen deshita.', 'A imputabilidade não foi reconhecida.', 'Jurídico avançado'],
    ['推定', 'suitei', 'presunção', 'substantivo', '無罪の推定が働きます。', 'Muzai no suitei ga hatarakimasu.', 'A presunção de inocência vale.', 'Jurídico avançado'],
    ['免責の', 'menseki no', 'excludente de responsabilidade', 'adjetivo', '免責の証拠を隠しました。', 'Menseki no shōko o kakushimashita.', 'Ocultaram provas excludentes.', 'Jurídico avançado'],
    ['差し止め命令', 'sashitome meirei', 'liminar', 'substantivo', '裁判官が差し止め命令を出しました。', 'Saibankan ga sashitome meirei o dashimashita.', 'O juiz concedeu uma liminar.', 'Jurídico avançado'],
    ['宣誓供述', 'sensei kyoujutsu', 'depoimento juramentado', 'substantivo', '宣誓供述は一日中続きました。', 'Sensei kyōjutsu wa ichinichijū tsuzukimashita.', 'O depoimento juramentado durou o dia todo.', 'Jurídico avançado'],
    ['裁定する', 'saitei suru', 'julgar / arbitrar', 'verbo', '委員会が紛争を裁定します。', 'Iinkai ga funsō o saitei shimasu.', 'A comissão vai julgar a disputa.', 'Jurídico avançado'],
    ['不法行為', 'fuhou koui', 'ilícito civil', 'substantivo', 'これは不法行為に当たります。', 'Kore wa fuhō kōi ni atarimasu.', 'Isso configura um ilícito civil.', 'Jurídico avançado'],
    ['博識な', 'hakushiki na', 'erudito', 'adjetivo', '博識な注釈が付いています。', 'Hakushiki na chūshaku ga tsuite imasu.', 'Vem com notas eruditas.', 'Termos eruditos'],
    ['明晰な', 'meiseki na', 'lúcido / cristalino', 'adjetivo', '明晰な説明で片付きました。', 'Meiseki na setsumei de katazukimashita.', 'A explicação lúcida resolveu tudo.', 'Termos eruditos'],
    ['難解な', 'nankai na', 'difícil / hermético', 'adjetivo', '議論が難解になりました。', 'Giron ga nankai ni narimashita.', 'O argumento ficou hermético.', 'Termos eruditos'],
    ['晦渋な', 'kaijuu na', 'obscuro / rebuscado', 'adjetivo', '晦渋な文章は避けてください。', 'Kaijū na bunshō wa sakete kudasai.', 'Evite um texto rebuscado.', 'Termos eruditos'],
    ['明敏な', 'meibin na', 'sagaz', 'adjetivo', '明敏な判断でした。', 'Meibin na handan deshita.', 'Foi uma decisão sagaz.', 'Termos eruditos'],
    ['洞察力のある', 'dousatsuryoku no aru', 'perspicaz', 'adjetivo', '洞察力のある読者は気づきます。', 'Dōsatsuryoku no aru dokusha wa kizukimasu.', 'Um leitor perspicaz vai notar.', 'Termos eruditos'],
    ['簡潔な', 'kanketsu na', 'lacônico / conciso', 'adjetivo', '返事は簡潔でした。', 'Henji wa kanketsu deshita.', 'A resposta foi lacônica.', 'Termos eruditos'],
    ['冗漫な', 'jouman na', 'prolixo', 'adjetivo', '序論が冗漫です。', 'Joron ga jōman desu.', 'A introdução é prolixa.', 'Termos eruditos'],
    ['無口な', 'mukuchi na', 'taciturno', 'adjetivo', '彼は終始無口でした。', 'Kare wa shūshi mukuchi deshita.', 'Ele permaneceu taciturno o tempo todo.', 'Termos eruditos'],
    ['饒舌な', 'jouzetsu na', 'tagarela / loquaz', 'adjetivo', '饒舌な主人が止まりません。', 'Jōzetsu na shujin ga tomarimasen.', 'O anfitrião tagarela não para.', 'Termos eruditos'],
    ['両価性', 'ryoukasei', 'ambivalência', 'substantivo', '彼女の両価性は明らかでした。', 'Kanojo no ryōkasei wa akiraka deshita.', 'A ambivalência dela era evidente.', 'Nuance psicológica'],
    ['良心の呵責', 'ryoushin no kashaku', 'peso na consciência', 'substantivo', '良心の呵責なく嘘をつきました。', 'Ryōshin no kashaku naku uso o tsukimashita.', 'Mentiu sem peso na consciência.', 'Nuance psicológica'],
    ['胸騒ぎ', 'munasawagi', 'pressentimento inquieto', 'substantivo', '胸騒ぎがして開けました。', 'Munasawagi ga shite akemashita.', 'Abriu com um pressentimento inquieto.', 'Nuance psicológica'],
    ['立腹', 'rippuku', 'irritação / ofensa', 'substantivo', 'その一言に立腹しました。', 'Sono hitokoto ni rippuku shimashita.', 'Ficou ofendido com aquele comentário.', 'Nuance psicológica'],
    ['遺恨', 'ikon', 'rancor antigo', 'substantivo', '遺恨なく話しました。', 'Ikon naku hanashimashita.', 'Falou sem rancor.', 'Nuance psicológica'],
    ['悔悟', 'kaigo', 'contrição', 'substantivo', '悔悟は本物に見えました。', 'Kaigo wa honmono ni miemashita.', 'A contrição parecia genuína.', 'Nuance psicológica'],
    ['傲慢', 'gouman', 'arrogância', 'substantivo', '傲慢が破綻を招きました。', 'Gōman ga hatan o manekimashita.', 'A arrogância levou ao colapso.', 'Nuance psicológica'],
    ['寛容', 'kanyou', 'tolerância', 'substantivo', 'ご寛容に感謝します。', 'Gokanyō ni kansha shimasu.', 'Agradeço pela sua tolerância.', 'Nuance psicológica'],
    ['度量の大きさ', 'doryou no ookisa', 'magnanimidade', 'substantivo', '度量の大きさに驚きました。', 'Doryō no ōkisa ni odorokimashita.', 'Surpreendeu pela magnanimidade.', 'Nuance psicológica'],
    ['内気', 'uchiki', 'timidez', 'substantivo', '内気が本当の実力を隠していました。', 'Uchiki ga hontō no jitsuryoku o kakushite imashita.', 'A timidez escondia talento real.', 'Nuance psicológica'],
    ['系論', 'keiron', 'corolário', 'substantivo', 'コスト増はその系論です。', 'Kosuto zō wa sono keiron desu.', 'O aumento de custo é um corolário disso.', 'Argumentação'],
    ['自明の', 'jimei no', 'axiomático / evidente', 'adjetivo', 'この分野では自明のことです。', 'Kono bun’ya de wa jimei no koto desu.', 'Nesta área isso é evidente.', 'Argumentação'],
    ['反駁不能な', 'hanbaku funou na', 'irrefutável', 'adjetivo', 'データは反駁不能なものです。', 'Dēta wa hanbaku funō na mono desu.', 'Os dados são irrefutáveis.', 'Argumentação'],
    ['首肯できる', 'shukou dekiru', 'aceitável / convincente', 'adjetivo', '首肯できる主張でした。', 'Shukō dekiru shuchō deshita.', 'Foi um argumento convincente.', 'Argumentação'],
    ['外挿する', 'gaisou suru', 'extrapolar', 'verbo', '一例から外挿しないでください。', 'Ichirei kara gaisō shinaide kudasai.', 'Não extrapole a partir de um caso.', 'Argumentação'],
    ['強弁', 'kyouben', 'argumentação forçada', 'substantivo', 'それは強弁にすぎません。', 'Sore wa kyōben ni sugimasen.', 'Isso não passa de argumentação forçada.', 'Argumentação'],
    ['不誠実な', 'fuseijitsu na', 'desonesto / de má-fé', 'adjetivo', '不誠実な答えです。', 'Fuseijitsu na kotae desu.', 'É uma resposta de má-fé.', 'Argumentação'],
    ['見せかけの', 'misekake no', 'aparente / especioso', 'adjetivo', '見せかけの論理です。', 'Misekake no ronri desu.', 'É uma lógica especiosa.', 'Argumentação'],
    ['適切な', 'tekisetsu na', 'pertinente / adequado', 'adjetivo', '適切な指摘だと思います。', 'Tekisetsu na shiteki da to omoimasu.', 'Acho uma observação pertinente.', 'Argumentação'],
    ['それ自体で', 'sore jitai de', 'por si só', 'advérbio', 'それ自体で結論にはなりません。', 'Sore jitai de ketsuron ni wa narimasen.', 'Por si só não é uma conclusão.', 'Argumentação'],
    ['迫真性', 'hakushinsei', 'verossimilhança', 'substantivo', 'この映画には迫真性が足りません。', 'Kono eiga ni wa hakushinsei ga tarimasen.', 'Este filme carece de verossimilhança.', 'Crítica e estética'],
    ['模倣作品', 'mohou sakuhin', 'pastiche', 'substantivo', 'これは意図的な模倣作品です。', 'Kore wa itoteki na mohō sakuhin desu.', 'Isto é um pastiche intencional.', 'Crítica e estética'],
    ['竜頭蛇尾', 'ryuutoudabi', 'começo grandioso e fim fraco', 'substantivo', '結末は竜頭蛇尾でした。', 'Ketsumatsu wa ryūtōdabi deshita.', 'O final foi um anticlímax.', 'Crítica e estética'],
    ['大団円', 'daidan’en', 'desfecho feliz', 'substantivo', '大団円が急ぎすぎでした。', 'Daidan’en ga isogisugi deshita.', 'O desfecho pareceu apressado.', 'Crítica e estética'],
    ['寓意', 'guui', 'alegoria', 'substantivo', 'この本全体が寓意です。', 'Kono hon zentai ga gūi desu.', 'O livro inteiro é uma alegoria.', 'Crítica e estética'],
    ['主題モチーフ', 'shudai mochiifu', 'motivo recorrente', 'substantivo', '水が中心の主題モチーフです。', 'Mizu ga chūshin no shudai mochīfu desu.', 'A água é o motivo recorrente central.', 'Crítica e estética'],
    ['誇張', 'kochou', 'hipérbole / exagero', 'substantivo', 'それは誇張であって分析ではありません。', 'Sore wa kochō de atte bunseki de wa arimasen.', 'Isso é exagero, não análise.', 'Crítica e estética'],
    ['哀感', 'aikan', 'pathos / comoção', 'substantivo', 'その場面には哀感があります。', 'Sono bamen ni wa aikan ga arimasu.', 'Aquela cena tem comoção verdadeira.', 'Crítica e estética'],
    ['風刺', 'fuushi', 'sátira', 'substantivo', '風刺として読むほうがいいです。', 'Fūshi to shite yomu hō ga ii desu.', 'Funciona melhor lido como sátira.', 'Crítica e estética'],
    ['全作品', 'zensakuhin', 'obra completa', 'substantivo', '全作品の中では小品です。', 'Zensakuhin no naka de wa shōhin desu.', 'Dentro da obra completa é uma peça menor.', 'Crítica e estética'],
  ],
};
