/** Coreano — lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { AsianByLevel } from '../entry';

export const KO_THEMATIC: AsianByLevel = {
  A1: [
    ['초록색', 'choroksaek', 'verde', 'substantivo', '풀은 초록색이에요.', 'Pureun choroksaegieyo.', 'A grama é verde.', 'Cores e formas'],
    ['노란색', 'noransaek', 'amarelo', 'substantivo', '노란색 꽃을 좋아해요.', 'Noransaek kkocheul joahaeyo.', 'Gosto de flores amarelas.', 'Cores e formas'],
    ['검은색', 'geomeunsaek', 'preto', 'substantivo', '검은색 외투를 입어요.', 'Geomeunsaek oetureul ibeoyo.', 'Ele usa um casaco preto.', 'Cores e formas'],
    ['흰색', 'huinsaek', 'branco', 'substantivo', '벽이 흰색이에요.', 'Byeogi huinsaegieyo.', 'As paredes são brancas.', 'Cores e formas'],
    ['주황색', 'juhwangsaek', 'laranja (cor)', 'substantivo', '주황색 가방이에요.', 'Juhwangsaek gabangieyo.', 'É uma bolsa laranja.', 'Cores e formas'],
    ['보라색', 'borasaek', 'roxo', 'substantivo', '하늘이 보라색이 됐어요.', 'Haneuri borasaegi dwaesseoyo.', 'O céu ficou roxo.', 'Cores e formas'],
    ['갈색', 'galsaek', 'marrom', 'substantivo', '제 신발은 갈색이에요.', 'Je sinbareun galsaegieyo.', 'Meus sapatos são marrons.', 'Cores e formas'],
    ['분홍색', 'bunhongsaek', 'rosa', 'substantivo', '분홍색 담요예요.', 'Bunhongsaek damyoyeyo.', 'É um cobertor rosa.', 'Cores e formas'],
    ['원', 'won', 'círculo', 'substantivo', '여기에 원을 그리세요.', 'Yeogie woneul geuriseyo.', 'Desenhe um círculo aqui.', 'Cores e formas'],
    ['네모', 'nemo', 'quadrado', 'substantivo', '상자가 네모예요.', 'Sangjaga nemoyeyo.', 'A caixa é um quadrado.', 'Cores e formas'],
    ['셔츠', 'syeocheu', 'camisa', 'substantivo', '이 셔츠는 깨끗해요.', 'I syeocheuneun kkaekkeutaeyo.', 'Esta camisa está limpa.', 'Roupas'],
    ['바지', 'baji', 'calça', 'substantivo', '이 바지는 새것이에요.', 'I bajineun saegeosieyo.', 'Esta calça é nova.', 'Roupas'],
    ['신발', 'sinbal', 'sapatos', 'substantivo', '신발이 젖었어요.', 'Sinbari jeojeosseoyo.', 'Os sapatos estão molhados.', 'Roupas'],
    ['원피스', 'wonpiseu', 'vestido', 'substantivo', '원피스를 샀어요.', 'Wonpiseureul sasseoyo.', 'Ela comprou um vestido.', 'Roupas'],
    ['재킷', 'jaekit', 'jaqueta', 'substantivo', '재킷을 가져가세요.', 'Jaekiseul gajyeogaseyo.', 'Leve sua jaqueta.', 'Roupas'],
    ['모자', 'moja', 'chapéu', 'substantivo', '모자를 잃어버렸어요.', 'Mojareul ireobeoryeosseoyo.', 'Ele perdeu o chapéu.', 'Roupas'],
    ['양말', 'yangmal', 'meias', 'substantivo', '깨끗한 양말이 필요해요.', 'Kkaekkeutan yangmari piryohaeyo.', 'Preciso de meias limpas.', 'Roupas'],
    ['외투', 'oetu', 'casaco', 'substantivo', '오늘은 외투를 입으세요.', 'Oneureun oetureul ibeuseyo.', 'Use um casaco hoje.', 'Roupas'],
    ['치마', 'chima', 'saia', 'substantivo', '그 치마는 길어요.', 'Geu chimaneun gireoyo.', 'Aquela saia é longa.', 'Roupas'],
    ['안경', 'angyeong', 'óculos', 'substantivo', '안경을 잊었어요.', 'Angyeongeul ijeosseoyo.', 'Esqueci meus óculos.', 'Roupas'],
    ['해', 'hae', 'sol', 'substantivo', '해가 강해요.', 'Haega ganghaeyo.', 'O sol está forte.', 'Clima e natureza'],
    ['비', 'bi', 'chuva', 'substantivo', '비가 그쳤어요.', 'Biga geuchyeosseoyo.', 'A chuva parou.', 'Clima e natureza'],
    ['폭설', 'pokseol', 'nevasca / neve forte', 'substantivo', '폭설이 내렸어요.', 'Pokseori naeryeosseoyo.', 'Caiu uma nevasca.', 'Clima e natureza'],
    ['바람', 'baram', 'vento', 'substantivo', '바람이 강해요.', 'Barami ganghaeyo.', 'O vento está forte.', 'Clima e natureza'],
    ['구름', 'gureum', 'nuvem', 'substantivo', '구름이 하나 있어요.', 'Gureumi hana isseoyo.', 'Há uma nuvem.', 'Clima e natureza'],
    ['나무', 'namu', 'árvore', 'substantivo', '이 나무는 오래됐어요.', 'I namuneun oraedwaesseoyo.', 'Esta árvore é velha.', 'Clima e natureza'],
    ['꽃', 'kkot', 'flor', 'substantivo', '이 꽃을 좋아해요.', 'I kkocheul joahaeyo.', 'Ela gosta desta flor.', 'Clima e natureza'],
    ['하늘', 'haneul', 'céu', 'substantivo', '하늘이 맑아요.', 'Haneuri malgayo.', 'O céu está limpo.', 'Clima e natureza'],
    ['바닷가', 'badatga', 'praia', 'substantivo', '바닷가에 가요.', 'Badatgae gayo.', 'Nós vamos à praia.', 'Clima e natureza'],
    ['산', 'san', 'montanha', 'substantivo', '저 산은 높아요.', 'Jeo saneun nopayo.', 'Aquela montanha é alta.', 'Clima e natureza'],
    ['머리', 'meori', 'cabeça', 'substantivo', '머리가 아파요.', 'Meoriga apayo.', 'Minha cabeça dói.', 'Corpo'],
    ['손', 'son', 'mão', 'substantivo', '손을 주세요.', 'Soneul juseyo.', 'Me dê sua mão.', 'Corpo'],
    ['발', 'bal', 'pé', 'substantivo', '발이 차가워요.', 'Bari chagawoyo.', 'Meu pé está frio.', 'Corpo'],
    ['눈', 'nun', 'olho', 'substantivo', '눈이 피곤해요.', 'Nuni pigonhaeyo.', 'Meus olhos estão cansados.', 'Corpo'],
    ['귀', 'gwi', 'orelha / ouvido', 'substantivo', '귀가 아파요.', 'Gwiga apayo.', 'Meu ouvido dói.', 'Corpo'],
    ['입', 'ip', 'boca', 'substantivo', '입을 벌리세요.', 'Ibeul beolliseyo.', 'Abra a boca.', 'Corpo'],
    ['코', 'ko', 'nariz', 'substantivo', '코가 빨개요.', 'Koga ppalgaeyo.', 'O nariz está vermelho.', 'Corpo'],
    ['머리카락', 'meorikarak', 'cabelo (fios)', 'substantivo', '머리카락이 길어요.', 'Meorikaragi gireoyo.', 'O cabelo dela é longo.', 'Corpo'],
    ['팔', 'pal', 'braço', 'substantivo', '팔이 부러졌어요.', 'Pari bureojyeosseoyo.', 'Ele quebrou o braço.', 'Corpo'],
    ['다리', 'dari', 'perna', 'substantivo', '다리가 피곤해요.', 'Dariga pigonhaeyo.', 'Minha perna está cansada.', 'Corpo'],
    ['빵', 'ppang', 'pão', 'substantivo', '매일 빵을 먹어요.', 'Maeil ppangeul meogeoyo.', 'Eu como pão todo dia.', 'Comida e bebida'],
    ['우유', 'uyu', 'leite', 'substantivo', '우유가 차가워요.', 'Uyuga chagawoyo.', 'O leite está frio.', 'Comida e bebida'],
    ['커피', 'keopi', 'café', 'substantivo', '그녀는 커피를 마셔요.', 'Geunyeoneun keopireul masyeoyo.', 'Ela bebe café.', 'Comida e bebida'],
    ['밥', 'bap', 'arroz cozido / refeição', 'substantivo', '점심에 밥을 먹어요.', 'Jeomsime babeul meogeoyo.', 'Comemos arroz no almoço.', 'Comida e bebida'],
    ['고기', 'gogi', 'carne', 'substantivo', '그는 고기를 안 먹어요.', 'Geuneun gogireul an meogeoyo.', 'Ele não come carne.', 'Comida e bebida'],
    ['과일', 'gwail', 'fruta', 'substantivo', '과일을 사세요.', 'Gwaireul saseyo.', 'Compre frutas.', 'Comida e bebida'],
    ['달걀', 'dalgyal', 'ovo', 'substantivo', '달걀 하나 주세요.', 'Dalgyal hana juseyo.', 'Quero um ovo.', 'Comida e bebida'],
    ['치즈', 'chijeu', 'queijo', 'substantivo', '이 치즈는 맛있어요.', 'I chijeuneun masisseoyo.', 'Este queijo é bom.', 'Comida e bebida'],
    ['설탕', 'seoltang', 'açúcar', 'substantivo', '설탕은 빼 주세요.', 'Seoltangeun ppae juseyo.', 'Sem açúcar, por favor.', 'Comida e bebida'],
    ['소금', 'sogeum', 'sal', 'substantivo', '소금 좀 주세요.', 'Sogeum jom juseyo.', 'Me passe o sal.', 'Comida e bebida'],
    ['아침', 'achim', 'manhã', 'substantivo', '아침에 일해요.', 'Achime ilhaeyo.', 'Eu trabalho de manhã.', 'Tempo e rotina'],
    ['오후', 'ohu', 'tarde', 'substantivo', '오후에 만나요.', 'Ohue mannayo.', 'Nos vemos à tarde.', 'Tempo e rotina'],
    ['저녁', 'jeonyeok', 'fim de tarde / jantar', 'substantivo', '저녁에 먹어요.', 'Jeonyeoge meogeoyo.', 'Nós comemos no fim da tarde.', 'Tempo e rotina'],
    ['밤', 'bam', 'noite', 'substantivo', '밤은 조용해요.', 'Bameun joyonghaeyo.', 'A noite está calma.', 'Tempo e rotina'],
    ['이번 주', 'ibeon ju', 'esta semana', 'substantivo', '이번 주는 길어요.', 'Ibeon juneun gireoyo.', 'Esta semana está longa.', 'Tempo e rotina'],
    ['이번 달', 'ibeon dal', 'este mês', 'substantivo', '이번 달은 바빠요.', 'Ibeon dareun bappayo.', 'Este mês está cheio.', 'Tempo e rotina'],
    ['오늘', 'oneul', 'hoje', 'substantivo', '오늘은 피곤해요.', 'Oneureun pigonhaeyo.', 'Estou cansado hoje.', 'Tempo e rotina'],
    ['내일', 'naeil', 'amanhã', 'substantivo', '내일 여행 가요.', 'Naeil yeohaeng gayo.', 'Nós viajamos amanhã.', 'Tempo e rotina'],
    ['어제', 'eoje', 'ontem', 'substantivo', '어제 비가 왔어요.', 'Eoje biga wasseoyo.', 'Choveu ontem.', 'Tempo e rotina'],
    ['주말', 'jumal', 'fim de semana', 'substantivo', '주말에 쉬어요.', 'Jumare swieoyo.', 'No fim de semana eu descanso.', 'Tempo e rotina'],
  ],
  A2: [
    ['비행기', 'bihaenggi', 'avião', 'substantivo', '비행기가 여섯 시에 떠나요.', 'Bihaenggiga yeoseot sie tteonayo.', 'O avião sai às seis.', 'Viagem'],
    ['여권', 'yeogwon', 'passaporte', 'substantivo', '여권을 보여 주세요.', 'Yeogwoneul boyeo juseyo.', 'Me mostre seu passaporte.', 'Viagem'],
    ['짐', 'jim', 'bagagem', 'substantivo', '짐이 무거워요.', 'Jimi mugeowoyo.', 'Minha bagagem está pesada.', 'Viagem'],
    ['표', 'pyo', 'passagem / bilhete', 'substantivo', '인터넷으로 표를 샀어요.', 'Inteoneseuro pyoreul sasseoyo.', 'Comprei a passagem pela internet.', 'Viagem'],
    ['지연', 'jiyeon', 'atraso', 'substantivo', '긴 지연이 있었어요.', 'Gin jiyeoni isseosseoyo.', 'Houve um atraso longo.', 'Viagem'],
    ['공항', 'gonghang', 'aeroporto', 'substantivo', '공항이 멀어요.', 'Gonghangi meoreoyo.', 'O aeroporto é longe.', 'Viagem'],
    ['여행 가방', 'yeohaeng gabang', 'mala de viagem', 'substantivo', '오늘 밤에 여행 가방을 싸요.', 'Oneul bame yeohaeng gabangeul ssayo.', 'Faço a mala hoje à noite.', 'Viagem'],
    ['출발', 'chulbal', 'partida', 'substantivo', '출발 시간을 확인하세요.', 'Chulbal siganeul hwaginhaseyo.', 'Confira o horário de partida.', 'Viagem'],
    ['도착', 'dochak', 'chegada', 'substantivo', '도착은 순조로웠어요.', 'Dochageun sunjorowosseoyo.', 'A chegada foi tranquila.', 'Viagem'],
    ['탑승권', 'tapseunggwon', 'cartão de embarque', 'substantivo', '탑승권을 가지고 계세요.', 'Tapseunggwoneul gajigo gyeseyo.', 'Guarde seu cartão de embarque.', 'Viagem'],
    ['메뉴', 'menyu', 'cardápio', 'substantivo', '메뉴 좀 볼 수 있을까요?', 'Menyu jom bol su isseulkkayo?', 'Posso ver o cardápio?', 'Restaurante'],
    ['종업원', 'jongeobwon', 'garçom / atendente', 'substantivo', '종업원이 와요.', 'Jongeobwoni wayo.', 'O garçom está vindo.', 'Restaurante'],
    ['팁', 'tip', 'gorjeta', 'substantivo', '팁을 놓고 왔어요.', 'Tibeul noko wasseoyo.', 'Deixamos gorjeta.', 'Restaurante'],
    ['후식', 'husik', 'sobremesa', 'substantivo', '후식을 먹고 싶어요.', 'Husigeul meokgo sipeoyo.', 'Quero sobremesa.', 'Restaurante'],
    ['전채', 'jeonchae', 'entrada (prato)', 'substantivo', '전채가 작았어요.', 'Jeonchaega jagasseoyo.', 'A entrada era pequena.', 'Restaurante'],
    ['자리 예약', 'jari yeyak', 'reserva de mesa', 'substantivo', '자리 예약을 했어요.', 'Jari yeyageul haesseoyo.', 'Fiz uma reserva de mesa.', 'Restaurante'],
    ['냅킨', 'naepkin', 'guardanapo', 'substantivo', '냅킨 좀 주세요.', 'Naepkin jom juseyo.', 'Me passe um guardanapo.', 'Restaurante'],
    ['쟁반', 'jaengban', 'bandeja', 'substantivo', '쟁반에 놓으세요.', 'Jaengbane noeuseyo.', 'Coloque na bandeja.', 'Restaurante'],
    ['맛', 'mat', 'sabor', 'substantivo', '맛이 이상해요.', 'Masi isanghaeyo.', 'O sabor está estranho.', 'Restaurante'],
    ['맵다', 'maepda', 'ser picante', 'adjetivo', '이 음식은 매워요.', 'I eumsigeun maewoyo.', 'Esta comida é picante.', 'Restaurante'],
    ['현금', 'hyeongeum', 'dinheiro (em espécie)', 'substantivo', '현금밖에 없어요.', 'Hyeongeumbakke eopseoyo.', 'Só tenho dinheiro em espécie.', 'Compras'],
    ['거스름돈', 'geoseureumdon', 'troco', 'substantivo', '거스름돈은 됐어요.', 'Geoseureumdoneun dwaesseoyo.', 'Fique com o troco.', 'Compras'],
    ['사이즈', 'saijeu', 'tamanho', 'substantivo', '더 큰 사이즈 있어요?', 'Deo keun saijeu isseoyo?', 'Tem um tamanho maior?', 'Compras'],
    ['특가', 'teukga', 'preço promocional', 'substantivo', '그 외투는 특가였어요.', 'Geu oetuneun teukgayeosseoyo.', 'Aquele casaco estava em promoção.', 'Compras'],
    ['계산원', 'gyesanwon', 'operador de caixa', 'substantivo', '계산원에게 물어보세요.', 'Gyesanwonege mureoboseyo.', 'Pergunte ao caixa.', 'Compras'],
    ['통로', 'tongno', 'corredor', 'substantivo', '우유는 삼 번 통로에 있어요.', 'Uyuneun sam beon tongnoe isseoyo.', 'O leite está no corredor três.', 'Compras'],
    ['선반', 'seonban', 'prateleira', 'substantivo', '선반이 비었어요.', 'Seonbani bieosseoyo.', 'A prateleira está vazia.', 'Compras'],
    ['세일', 'seil', 'liquidação', 'substantivo', '신발이 세일 중이에요.', 'Sinbari seil jungieyo.', 'Os sapatos estão em liquidação.', 'Compras'],
    ['지갑', 'jigap', 'carteira', 'substantivo', '지갑을 집에 두고 왔어요.', 'Jigabeul jibe dugo wasseoyo.', 'Deixei minha carteira em casa.', 'Compras'],
    ['상표', 'sangpyo', 'marca', 'substantivo', '이 상표를 믿어요.', 'I sangpyoreul mideoyo.', 'Confio nesta marca.', 'Compras'],
    ['기침', 'gichim', 'tosse', 'substantivo', '기침이 심해요.', 'Gichimi simhaeyo.', 'A tosse está feia.', 'Saúde'],
    ['두통', 'dutong', 'dor de cabeça', 'substantivo', '두통이 있어요.', 'Dutongi isseoyo.', 'Estou com dor de cabeça.', 'Saúde'],
    ['알약', 'alyak', 'comprimido', 'substantivo', '하루에 알약 하나 드세요.', 'Harue alyak hana deuseyo.', 'Tome um comprimido por dia.', 'Saúde'],
    ['간호사', 'ganhosa', 'enfermeiro', 'substantivo', '간호사가 친절했어요.', 'Ganhosaga chinjeolhaesseoyo.', 'O enfermeiro foi gentil.', 'Saúde'],
    ['부상', 'busang', 'lesão', 'substantivo', '부상이 심각했어요.', 'Busangi simgakaesseoyo.', 'A lesão foi séria.', 'Saúde'],
    ['휴식', 'hyusik', 'descanso', 'substantivo', '휴식이 필요해요.', 'Hyusigi piryohaeyo.', 'Você precisa de descanso.', 'Saúde'],
    ['붕대', 'bungdae', 'bandagem', 'substantivo', '붕대를 감으세요.', 'Bungdaereul gameuseyo.', 'Coloque uma bandagem.', 'Saúde'],
    ['어지럽다', 'eojireopda', 'estar tonto', 'adjetivo', '어지러워요.', 'Eojireowoyo.', 'Estou tonto.', 'Saúde'],
    ['진료소', 'jillyoso', 'clínica', 'substantivo', '진료소는 여덟 시에 열어요.', 'Jillyosoneun yeodeol sie yeoreoyo.', 'A clínica abre às oito.', 'Saúde'],
    ['통증', 'tongjeung', 'dor', 'substantivo', '등에 통증이 있어요.', 'Deunge tongjeungi isseoyo.', 'Tenho dor nas costas.', 'Saúde'],
    ['교량', 'gyoryang', 'ponte', 'substantivo', '교량을 건너세요.', 'Gyoryangeul geonneoseyo.', 'Atravesse a ponte.', 'Cidade'],
    ['광장', 'gwangjang', 'praça', 'substantivo', '광장에서 만났어요.', 'Gwangjangeseo mannasseoyo.', 'Nos encontramos na praça.', 'Cidade'],
    ['모퉁이', 'motungi', 'esquina', 'substantivo', '모퉁이에서 도세요.', 'Motungieseo doseyo.', 'Vire na esquina.', 'Cidade'],
    ['교통', 'gyotong', 'trânsito', 'substantivo', '교통이 아주 나빠요.', 'Gyotongi aju nappayo.', 'O trânsito está terrível.', 'Cidade'],
    ['지하철', 'jihacheol', 'metrô', 'substantivo', '지하철을 타세요.', 'Jihacheoreul taseyo.', 'Pegue o metrô.', 'Cidade'],
    ['정류장', 'jeongnyujang', 'ponto de ônibus', 'substantivo', '다음 정류장에서 내리세요.', 'Daeum jeongnyujangeseo naeriseyo.', 'Desça na próxima parada.', 'Cidade'],
    ['지도', 'jido', 'mapa', 'substantivo', '지도를 보세요.', 'Jidoreul boseyo.', 'Olhe o mapa.', 'Cidade'],
    ['길', 'gil', 'caminho / rua', 'substantivo', '이 길로 가세요.', 'I gillo gaseyo.', 'Siga este caminho.', 'Cidade'],
    ['대문', 'daemun', 'portão', 'substantivo', '대문이 잠겼어요.', 'Daemuni jamgyeosseoyo.', 'O portão está trancado.', 'Cidade'],
    ['횡단보도', 'hoengdanbodo', 'faixa de pedestres', 'substantivo', '횡단보도를 이용하세요.', 'Hoengdanbodoreul iyonghaseyo.', 'Use a faixa de pedestres.', 'Cidade'],
    ['빨래', 'ppallae', 'roupa para lavar', 'substantivo', '일요일에 빨래를 해요.', 'Iryoire ppallaereul haeyo.', 'Eu lavo a roupa no domingo.', 'Casa e tarefas'],
    ['설거지', 'seolgeoji', 'lavar louça', 'substantivo', '그가 설거지를 해요.', 'Geuga seolgeojireul haeyo.', 'Ele lava a louça.', 'Casa e tarefas'],
    ['빗자루', 'bitjaru', 'vassoura', 'substantivo', '빗자루가 어디 있어요?', 'Bitjaruga eodi isseoyo?', 'Onde está a vassoura?', 'Casa e tarefas'],
    ['쓰레기', 'sseuregi', 'lixo', 'substantivo', '쓰레기를 버리세요.', 'Sseuregireul beoriseyo.', 'Leve o lixo para fora.', 'Casa e tarefas'],
    ['수건', 'sugeon', 'toalha', 'substantivo', '수건이 젖었어요.', 'Sugeoni jeojeosseoyo.', 'A toalha está molhada.', 'Casa e tarefas'],
    ['담요', 'damyo', 'cobertor', 'substantivo', '담요가 하나 더 필요해요.', 'Damyoga hana deo piryohaeyo.', 'Preciso de outro cobertor.', 'Casa e tarefas'],
    ['서랍', 'seorap', 'gaveta', 'substantivo', '서랍 안에 있어요.', 'Seorap ane isseoyo.', 'Está na gaveta.', 'Casa e tarefas'],
    ['옷장', 'otjang', 'guarda-roupa', 'substantivo', '옷장에 거세요.', 'Otjange geoseyo.', 'Pendure no guarda-roupa.', 'Casa e tarefas'],
    ['싱크대', 'singkeudae', 'pia', 'substantivo', '싱크대가 막혔어요.', 'Singkeudaega makyeosseoyo.', 'A pia está entupida.', 'Casa e tarefas'],
    ['거울', 'geoul', 'espelho', 'substantivo', '거울을 보세요.', 'Geoureul boseyo.', 'Olhe no espelho.', 'Casa e tarefas'],
  ],
  B1: [
    ['면접', 'myeonjeop', 'entrevista de emprego', 'substantivo', '면접이 잘됐어요.', 'Myeonjeobi jaldwaesseoyo.', 'A entrevista correu bem.', 'Trabalho'],
    ['이력서', 'iryeokseo', 'currículo', 'substantivo', '이력서를 보내 주세요.', 'Iryeokseoreul bonae juseyo.', 'Me mande seu currículo.', 'Trabalho'],
    ['교대', 'gyodae', 'turno / revezamento', 'substantivo', '밤 교대로 일해요.', 'Bam gyodaero ilhaeyo.', 'Eu trabalho no turno da noite.', 'Trabalho'],
    ['야근', 'yageun', 'hora extra noturna', 'substantivo', '또 야근을 했어요.', 'Tto yageuneul haesseoyo.', 'Ela fez hora extra de novo.', 'Trabalho'],
    ['인턴', 'inteon', 'estágio', 'substantivo', '인턴 자리를 얻었어요.', 'Inteon jarireul eodeosseoyo.', 'Ele conseguiu um estágio.', 'Trabalho'],
    ['상사', 'sangsa', 'chefe / superior', 'substantivo', '상사와 이야기하세요.', 'Sangsawa iyagihaseyo.', 'Fale com seu chefe.', 'Trabalho'],
    ['업무', 'eommu', 'tarefa profissional', 'substantivo', '이 업무는 두 시간 걸려요.', 'I eommuneun du sigan geollyeoyo.', 'Esta tarefa leva duas horas.', 'Trabalho'],
    ['회의', 'hoeui', 'reunião', 'substantivo', '회의가 취소됐어요.', 'Hoeuiga chwisodwaesseoyo.', 'A reunião foi cancelada.', 'Trabalho'],
    ['직원', 'jigwon', 'funcionário', 'substantivo', '직원들이 친절해요.', 'Jigwondeuri chinjeolhaeyo.', 'Os funcionários são simpáticos.', 'Trabalho'],
    ['계약', 'gyeyak', 'contrato', 'substantivo', '먼저 계약을 읽으세요.', 'Meonjeo gyeyageul ilgeuseyo.', 'Leia o contrato primeiro.', 'Trabalho'],
    ['업데이트', 'eopdeiteu', 'atualização', 'substantivo', '업데이트를 설치하세요.', 'Eopdeiteureul seolchihaseyo.', 'Instale a atualização.', 'Tecnologia'],
    ['비밀번호', 'bimilbeonho', 'senha', 'substantivo', '비밀번호를 잊었어요.', 'Bimilbeonhoreul ijeosseoyo.', 'Esqueci minha senha.', 'Tecnologia'],
    ['백업', 'baegeop', 'cópia de segurança', 'substantivo', '먼저 백업을 하세요.', 'Meonjeo baegeobeul haseyo.', 'Faça uma cópia de segurança antes.', 'Tecnologia'],
    ['기기', 'gigi', 'dispositivo', 'substantivo', '이 기기는 빨라요.', 'I gigineun ppallayo.', 'Este dispositivo é rápido.', 'Tecnologia'],
    ['화면', 'hwamyeon', 'tela', 'substantivo', '화면이 깨졌어요.', 'Hwamyeoni kkaejyeosseoyo.', 'A tela está quebrada.', 'Tecnologia'],
    ['내려받다', 'naeryeobatda', 'baixar', 'verbo', '파일을 지금 내려받으세요.', 'Paireul jigeum naeryeobadeuseyo.', 'Baixe o arquivo agora.', 'Tecnologia'],
    ['네트워크', 'neteuwokeu', 'rede', 'substantivo', '네트워크가 끊겼어요.', 'Neteuwokeuga kkeunkyeosseoyo.', 'A rede caiu.', 'Tecnologia'],
    ['브라우저', 'beuraujeo', 'navegador', 'substantivo', '브라우저에서 여세요.', 'Beuraujeoeseo yeoseyo.', 'Abra no navegador.', 'Tecnologia'],
    ['폴더', 'poldeo', 'pasta', 'substantivo', '이 폴더에 저장하세요.', 'I poldeoe jeojanghaseyo.', 'Salve nesta pasta.', 'Tecnologia'],
    ['멈추다', 'meomchuda', 'travar / parar', 'verbo', '앱이 또 멈췄어요.', 'Aebi tto meomchwosseoyo.', 'O aplicativo travou de novo.', 'Tecnologia'],
    ['재활용', 'jaehwaryong', 'reciclagem', 'substantivo', '여기서 재활용을 해요.', 'Yeogiseo jaehwaryongeul haeyo.', 'Aqui nós reciclamos.', 'Meio ambiente'],
    ['오염', 'oyeom', 'poluição', 'substantivo', '오염이 심해졌어요.', 'Oyeomi simhaejyeosseoyo.', 'A poluição piorou.', 'Meio ambiente'],
    ['폐기물', 'pyegimul', 'resíduo', 'substantivo', '폐기물이 문제예요.', 'Pyegimuri munjeyeyo.', 'O resíduo é um problema.', 'Meio ambiente'],
    ['기후', 'gihu', 'clima', 'substantivo', '기후가 변하고 있어요.', 'Gihuga byeonhago isseoyo.', 'O clima está mudando.', 'Meio ambiente'],
    ['에너지', 'eneoji', 'energia', 'substantivo', '태양 에너지가 싸졌어요.', 'Taeyang eneojiga ssajyeosseoyo.', 'A energia solar ficou mais barata.', 'Meio ambiente'],
    ['숲', 'sup', 'floresta', 'substantivo', '이 숲은 보호받고 있어요.', 'I supeun bohobatgo isseoyo.', 'Esta floresta é protegida.', 'Meio ambiente'],
    ['종', 'jong', 'espécie', 'substantivo', '이 종은 희귀해요.', 'I jongeun huigwihaeyo.', 'Esta espécie é rara.', 'Meio ambiente'],
    ['가뭄', 'gamum', 'seca', 'substantivo', '가뭄이 몇 달 이어졌어요.', 'Gamumi myeot dal ieojyeosseoyo.', 'A seca durou meses.', 'Meio ambiente'],
    ['홍수', 'hongsu', 'enchente', 'substantivo', '홍수가 도로를 망가뜨렸어요.', 'Hongsuga dororeul manggatteuryeosseoyo.', 'A enchente danificou a estrada.', 'Meio ambiente'],
    ['배출수', 'baechulsu', 'efluente', 'substantivo', '배출수가 강에 닿았어요.', 'Baechulsuga gange dahasseoyo.', 'O efluente chegou ao rio.', 'Meio ambiente'],
    ['심판', 'simpan', 'árbitro', 'substantivo', '심판이 경기를 멈췄어요.', 'Simpani gyeonggireul meomchwosseoyo.', 'O árbitro parou o jogo.', 'Esportes'],
    ['토너먼트', 'toneomeonteu', 'torneio', 'substantivo', '토너먼트에서 우승했어요.', 'Toneomeonteueseo useunghaesseoyo.', 'Ela venceu o torneio.', 'Esportes'],
    ['상대', 'sangdae', 'adversário', 'substantivo', '상대가 더 빨랐어요.', 'Sangdaega deo ppallasseoyo.', 'O adversário era mais rápido.', 'Esportes'],
    ['팀 동료', 'tim dongryo', 'companheiro de equipe', 'substantivo', '팀 동료가 득점했어요.', 'Tim dongryoga deukjeomhaesseoyo.', 'Meu companheiro de equipe marcou.', 'Esportes'],
    ['감독', 'gamdok', 'treinador', 'substantivo', '감독이 화가 났어요.', 'Gamdogi hwaga nasseoyo.', 'O treinador ficou bravo.', 'Esportes'],
    ['점수', 'jeomsu', 'placar / pontuação', 'substantivo', '점수가 어떻게 돼요?', 'Jeomsuga eotteoke dwaeyo?', 'Qual é o placar?', 'Esportes'],
    ['경기', 'gyeonggi', 'partida', 'substantivo', '경기는 여덟 시에 시작해요.', 'Gyeonggineun yeodeol sie sijakaeyo.', 'A partida começa às oito.', 'Esportes'],
    ['훈련', 'hullyeon', 'treino', 'substantivo', '훈련은 매일 아침에 있어요.', 'Hullyeoneun maeil achime isseoyo.', 'O treino é toda manhã.', 'Esportes'],
    ['지구력', 'jiguryeok', 'resistência física', 'substantivo', '그는 지구력이 좋아요.', 'Geuneun jiguryeogi joayo.', 'Ele tem muita resistência.', 'Esportes'],
    ['선수권', 'seonsugwon', 'campeonato', 'substantivo', '선수권에서 졌어요.', 'Seonsugwoneseo jyeosseoyo.', 'Eles perderam o campeonato.', 'Esportes'],
    ['다투다', 'datuda', 'discutir / brigar', 'verbo', '돈 때문에 다퉈요.', 'Don ttaemune datwoyo.', 'Eles brigam por dinheiro.', 'Relacionamentos'],
    ['사과하다', 'sagwahada', 'pedir desculpas', 'verbo', '그가 바로 사과했어요.', 'Geuga baro sagwahaesseoyo.', 'Ele pediu desculpas rápido.', 'Relacionamentos'],
    ['신뢰', 'silloe', 'confiança', 'substantivo', '신뢰는 시간이 걸려요.', 'Silloeneun sigani geollyeoyo.', 'Confiança leva tempo.', 'Relacionamentos'],
    ['질투하다', 'jiltuhada', 'ter ciúmes', 'verbo', '그녀는 쉽게 질투해요.', 'Geunyeoneun swipge jiltuhaeyo.', 'Ela fica com ciúmes fácil.', 'Relacionamentos'],
    ['충실한', 'chungsilhan', 'leal / fiel', 'adjetivo', '그는 충실한 친구예요.', 'Geuneun chungsilhan chinguyeyo.', 'Ele é um amigo leal.', 'Relacionamentos'],
    ['뒷담화', 'dwitdamhwa', 'fofoca pelas costas', 'substantivo', '뒷담화를 싫어해요.', 'Dwitdamhwareul sirheohaeyo.', 'Odeio fofoca pelas costas.', 'Relacionamentos'],
    ['조언', 'joeon', 'conselho', 'substantivo', '좋은 조언이었어요.', 'Joeun joeonieosseoyo.', 'Foi um bom conselho.', 'Relacionamentos'],
    ['부탁', 'butak', 'pedido / favor', 'substantivo', '부탁 하나 해도 될까요?', 'Butak hana haedo doelkkayo?', 'Posso pedir um favor?', 'Relacionamentos'],
    ['불화', 'bulhwa', 'desavença', 'substantivo', '사소한 불화가 있었어요.', 'Sasohan bulhwaga isseosseoyo.', 'Houve uma desavença boba.', 'Relacionamentos'],
    ['타협', 'tahyeop', 'acordo mútuo', 'substantivo', '타협에 이르렀어요.', 'Tahyeobe ireureosseoyo.', 'Chegamos a um acordo.', 'Relacionamentos'],
    ['예산', 'yesan', 'orçamento', 'substantivo', '예산을 지키세요.', 'Yesaneul jikiseyo.', 'Siga o orçamento.', 'Dinheiro'],
    ['저축', 'jeochuk', 'poupança', 'substantivo', '저축을 썼어요.', 'Jeochugeul sseosseoyo.', 'Ela usou a poupança.', 'Dinheiro'],
    ['대출', 'daechul', 'empréstimo', 'substantivo', '대출을 받았어요.', 'Daechureul badasseoyo.', 'Ele fez um empréstimo.', 'Dinheiro'],
    ['빚', 'bit', 'dívida', 'substantivo', '빚을 다 갚았어요.', 'Bijeul da gapasseoyo.', 'Eles quitaram a dívida.', 'Dinheiro'],
    ['지출', 'jichul', 'despesa', 'substantivo', '월세가 가장 큰 지출이에요.', 'Wolsega gajang keun jichurieyo.', 'O aluguel é minha maior despesa.', 'Dinheiro'],
    ['이자', 'ija', 'juros', 'substantivo', '이자가 너무 높아요.', 'Ijaga neomu nopayo.', 'Os juros estão altos demais.', 'Dinheiro'],
    ['투자하다', 'tujahada', 'investir', 'verbo', '부동산에 투자해요.', 'Budongsane tujahaeyo.', 'Eles investem em imóveis.', 'Dinheiro'],
    ['주택 담보 대출', 'jutaek dambo daechul', 'financiamento imobiliário', 'substantivo', '주택 담보 대출이 있어요.', 'Jutaek dambo daechuri isseoyo.', 'Nós temos um financiamento.', 'Dinheiro'],
    ['보험', 'boheom', 'seguro', 'substantivo', '자동차 보험이 비싸요.', 'Jadongcha boheomi bissayo.', 'O seguro do carro é caro.', 'Dinheiro'],
    ['최저임금', 'choejeoimgeum', 'salário mínimo', 'substantivo', '최저임금이 올랐어요.', 'Choejeoimgeumi ollasseoyo.', 'O salário mínimo subiu.', 'Dinheiro'],
  ],
  B2: [
    ['선거 운동', 'seongeo undong', 'campanha eleitoral', 'substantivo', '선거 운동이 육 주 동안 이어졌어요.', 'Seongeo undongi yuk ju dongan ieojyeosseoyo.', 'A campanha durou seis semanas.', 'Política'],
    ['유권자', 'yugwonja', 'eleitor', 'substantivo', '유권자가 갈렸어요.', 'Yugwonjaga gallyeosseoyo.', 'O eleitorado está dividido.', 'Política'],
    ['입법', 'ipbeop', 'legislação', 'substantivo', '새 입법이 통과됐어요.', 'Sae ipbeobi tonggwadwaesseoyo.', 'Uma nova legislação foi aprovada.', 'Política'],
    ['로비', 'robi', 'lobby', 'substantivo', '로비가 법안을 바꿨어요.', 'Robiga beobaneul bakkwosseoyo.', 'O lobby mudou o projeto de lei.', 'Política'],
    ['부패', 'bupae', 'corrupção', 'substantivo', '부패가 신뢰를 무너뜨려요.', 'Bupaega silloereul muneotteuryeoyo.', 'A corrupção destrói a confiança.', 'Política'],
    ['국민투표', 'gungmintupyo', 'referendo', 'substantivo', '국민투표를 실시했어요.', 'Gungmintupyoreul silsihaesseoyo.', 'Realizaram um referendo.', 'Política'],
    ['연립', 'yeollip', 'coalizão', 'substantivo', '연립이 무너졌어요.', 'Yeollibi muneojyeosseoyo.', 'A coalizão desmoronou.', 'Política'],
    ['투표용지', 'tupyoyongji', 'cédula de votação', 'substantivo', '투표용지는 비밀이에요.', 'Tupyoyongjineun bimirieyo.', 'A cédula é secreta.', 'Política'],
    ['선거구', 'seongeogu', 'distrito eleitoral', 'substantivo', '선거구를 방문했어요.', 'Seongeogureul bangmunhaesseoyo.', 'Ela visitou seu distrito eleitoral.', 'Política'],
    ['위임', 'wiim', 'delegação / mandato', 'substantivo', '국민의 위임을 받았어요.', 'Gungminui wiimeul badasseoyo.', 'Recebeu o mandato do povo.', 'Política'],
    ['물가 상승', 'mulga sangseung', 'inflação', 'substantivo', '물가 상승이 둔화됐어요.', 'Mulga sangseungi dunhwadwaesseoyo.', 'A inflação desacelerou.', 'Economia'],
    ['불황', 'bulhwang', 'recessão', 'substantivo', '나라가 불황에 들어갔어요.', 'Naraga bulhwange deureogasseoyo.', 'O país entrou em recessão.', 'Economia'],
    ['보조금', 'bojogeum', 'subsídio', 'substantivo', '보조금이 삭감됐어요.', 'Bojogeumi sakgamdwaesseoyo.', 'O subsídio foi cortado.', 'Economia'],
    ['관세', 'gwanse', 'tarifa alfandegária', 'substantivo', '관세를 부과했어요.', 'Gwansereul bugwahaesseoyo.', 'Impuseram uma tarifa.', 'Economia'],
    ['흑자', 'heukja', 'superávit', 'substantivo', '예산이 흑자예요.', 'Yesani heukjayeyo.', 'O orçamento está em superávit.', 'Economia'],
    ['적자', 'jeokja', 'déficit', 'substantivo', '적자가 계속 늘어요.', 'Jeokjaga gyesok neureoyo.', 'O déficit continua crescendo.', 'Economia'],
    ['공급', 'gonggeup', 'oferta / fornecimento', 'substantivo', '공급이 부족해요.', 'Gonggeubi bujokaeyo.', 'A oferta é insuficiente.', 'Economia'],
    ['수요', 'suyo', 'procura / demanda', 'substantivo', '수요가 급락했어요.', 'Suyoga geumnakaesseoyo.', 'A procura caiu bruscamente.', 'Economia'],
    ['독점', 'dokjeom', 'monopólio', 'substantivo', '거의 독점 상태예요.', 'Geoui dokjeom sangtaeyeyo.', 'É quase um monopólio.', 'Economia'],
    ['긴축', 'ginchuk', 'austeridade', 'substantivo', '긴축이 공공 서비스를 덮쳤어요.', 'Ginchugi gonggong seobiseureul deopchyeosseoyo.', 'A austeridade atingiu os serviços públicos.', 'Economia'],
    ['실험', 'silheom', 'experimento', 'substantivo', '실험이 두 번 실패했어요.', 'Silheomi du beon silpaehaesseoyo.', 'O experimento falhou duas vezes.', 'Ciência'],
    ['증거', 'jeunggeo', 'evidência', 'substantivo', '강력한 증거가 있어요.', 'Gangryeokan jeunggeoga isseoyo.', 'Há evidências fortes.', 'Ciência'],
    ['표본', 'pyobon', 'amostra', 'substantivo', '표본이 너무 작았어요.', 'Pyoboni neomu jagasseoyo.', 'A amostra era pequena demais.', 'Ciência'],
    ['실험실', 'silheomsil', 'laboratório', 'substantivo', '실험실에서 일해요.', 'Silheomsireseo ilhaeyo.', 'Ela trabalha num laboratório.', 'Ciência'],
    ['분자', 'bunja', 'molécula', 'substantivo', '물은 단순한 분자예요.', 'Mureun dansunhan bunjayeyo.', 'A água é uma molécula simples.', 'Ciência'],
    ['유전체', 'yujeonche', 'genoma', 'substantivo', '유전체를 해독했어요.', 'Yujeoncheureul haedokaesseoyo.', 'Decifraram o genoma.', 'Ciência'],
    ['백신', 'baeksin', 'vacina', 'substantivo', '백신이 잘 들어요.', 'Baeksini jal deureoyo.', 'A vacina funciona bem.', 'Ciência'],
    ['미생물', 'misaengmul', 'micróbio', 'substantivo', '이 미생물은 무해해요.', 'I misaengmureun muhaehaeyo.', 'Este micróbio é inofensivo.', 'Ciência'],
    ['방사선', 'bangsaseon', 'radiação', 'substantivo', '방사선 수치가 정상이에요.', 'Bangsaseon suchiga jeongsangieyo.', 'Os níveis de radiação estão normais.', 'Ciência'],
    ['망원경', 'mangwongyeong', 'telescópio', 'substantivo', '망원경이 행성을 찾았어요.', 'Mangwongyeongi haengseongeul chajasseoyo.', 'O telescópio encontrou um planeta.', 'Ciência'],
    ['표제', 'pyoje', 'manchete', 'substantivo', '표제가 오해를 불렀어요.', 'Pyojega ohaereul bulleosseoyo.', 'A manchete induziu ao erro.', 'Mídia'],
    ['보도', 'bodo', 'cobertura jornalística', 'substantivo', '보도가 편향적이었어요.', 'Bodoga pyeonhyangjeogieosseoyo.', 'A cobertura foi tendenciosa.', 'Mídia'],
    ['검열', 'geomyeol', 'censura', 'substantivo', '작년에 검열이 늘었어요.', 'Jangnyeone geomyeori neureosseoyo.', 'A censura aumentou no ano passado.', 'Mídia'],
    ['선전', 'seonjeon', 'propaganda ideológica', 'substantivo', '이건 순전히 선전이에요.', 'Igeon sunjeonhi seonjeonieyo.', 'Isso é pura propaganda.', 'Mídia'],
    ['방송', 'bangsong', 'transmissão', 'substantivo', '방송이 수백만 명에게 닿았어요.', 'Bangsongi subaengman myeongege dahasseoyo.', 'A transmissão alcançou milhões.', 'Mídia'],
    ['기자', 'gija', 'jornalista', 'substantivo', '기자가 사실을 확인했어요.', 'Gijaga sasireul hwaginhaesseoyo.', 'A jornalista checou os fatos.', 'Mídia'],
    ['사설', 'saseol', 'editorial', 'substantivo', '사설이 계획을 비판했어요.', 'Saseori gyehoegeul bipanhaesseoyo.', 'O editorial criticou o plano.', 'Mídia'],
    ['황색 언론', 'hwangsaek eollon', 'imprensa sensacionalista', 'substantivo', '황색 언론을 믿지 마세요.', 'Hwangsaek eolloneul mitji maseyo.', 'Não confie na imprensa sensacionalista.', 'Mídia'],
    ['청중', 'cheongjung', 'plateia', 'substantivo', '청중이 냉담했어요.', 'Cheongjungi naengdamhaesseoyo.', 'A plateia estava fria.', 'Mídia'],
    ['출처', 'chulcheo', 'fonte', 'substantivo', '출처를 밝히세요.', 'Chulcheoreul balkiseyo.', 'Revele sua fonte.', 'Mídia'],
    ['공감', 'gonggam', 'empatia', 'substantivo', '공감은 배울 수 있어요.', 'Gonggameun baeul su isseoyo.', 'A empatia pode ser aprendida.', 'Psicologia'],
    ['불안', 'buran', 'ansiedade', 'substantivo', '불안이 잠을 방해해요.', 'Burani jameul banghaehaeyo.', 'A ansiedade atrapalha o sono.', 'Psicologia'],
    ['트라우마', 'teurauma', 'trauma', 'substantivo', '트라우마가 몇 년 갔어요.', 'Teuraumaga myeot nyeon gasseoyo.', 'O trauma durou anos.', 'Psicologia'],
    ['동기', 'donggi', 'motivação', 'substantivo', '결과가 없으면 동기가 사라져요.', 'Gyeolgwaga eopseumyeon donggiga sarajyeoyo.', 'A motivação some sem resultados.', 'Psicologia'],
    ['지각', 'jigak', 'percepção', 'substantivo', '지각이 기억을 만들어요.', 'Jigagi gieogeul mandeureoyo.', 'A percepção molda a memória.', 'Psicologia'],
    ['행동', 'haengdong', 'comportamento', 'substantivo', '그의 행동이 갑자기 변했어요.', 'Geuui haengdongi gapjagi byeonhaesseoyo.', 'O comportamento dele mudou de repente.', 'Psicologia'],
    ['본능', 'bonneung', 'instinto', 'substantivo', '여기서는 본능을 믿으세요.', 'Yeogiseoneun bonneungeul mideuseyo.', 'Confie no seu instinto aqui.', 'Psicologia'],
    ['기분', 'gibun', 'humor / estado de espírito', 'substantivo', '기분이 좋아졌어요.', 'Gibuni joajyeosseoyo.', 'O humor melhorou.', 'Psicologia'],
    ['자존감', 'jajongam', 'autoestima', 'substantivo', '낮은 자존감은 흔해요.', 'Najeun jajongameun heunhaeyo.', 'Baixa autoestima é comum.', 'Psicologia'],
    ['원망', 'wonmang', 'ressentimento', 'substantivo', '원망이 천천히 쌓였어요.', 'Wonmangi cheoncheonhi ssayeosseoyo.', 'O ressentimento cresceu devagar.', 'Psicologia'],
    ['소송', 'sosong', 'processo judicial', 'substantivo', '소송을 제기했어요.', 'Sosongeul jegihaesseoyo.', 'Eles entraram com um processo.', 'Direito'],
    ['평결', 'pyeonggyeol', 'veredicto', 'substantivo', '평결이 모두를 놀라게 했어요.', 'Pyeonggyeori modureul nollage haesseoyo.', 'O veredicto surpreendeu todos.', 'Direito'],
    ['증언', 'jeungeon', 'depoimento', 'substantivo', '그녀의 증언이 결정적이었어요.', 'Geunyeoui jeungeoni gyeoljeongjeogieosseoyo.', 'O depoimento dela foi decisivo.', 'Direito'],
    ['증인', 'jeungin', 'testemunha', 'substantivo', '증인이 말을 바꿨어요.', 'Jeungini mareul bakkwosseoyo.', 'A testemunha mudou a versão.', 'Direito'],
    ['피고', 'pigo', 'réu', 'substantivo', '피고는 침묵했어요.', 'Pigoneun chimmukaesseoyo.', 'O réu permaneceu calado.', 'Direito'],
    ['변호사', 'byeonhosa', 'advogado', 'substantivo', '변호사에게 전화하세요.', 'Byeonhosaege jeonhwahaseyo.', 'Ligue para seu advogado.', 'Direito'],
    ['답변', 'dapbyeon', 'resposta formal / alegação', 'substantivo', '답변이 너무 짧았어요.', 'Dapbyeoni neomu jjalbasseoyo.', 'A alegação foi curta demais.', 'Direito'],
    ['항소', 'hangso', 'recurso judicial', 'substantivo', '항소에서 졌어요.', 'Hangsoeseo jyeosseoyo.', 'Eles perderam o recurso.', 'Direito'],
    ['양육권', 'yangyukgwon', 'guarda de filhos', 'substantivo', '그녀가 양육권을 얻었어요.', 'Geunyeoga yangyukgwoneul eodeosseoyo.', 'Ela ganhou a guarda.', 'Direito'],
    ['법령', 'beomnyeong', 'lei / decreto', 'substantivo', '이 법령은 오래됐어요.', 'I beomnyeongeun oraedwaesseoyo.', 'Esta lei está ultrapassada.', 'Direito'],
  ],
  C1: [
    ['가설', 'gaseol', 'hipótese', 'substantivo', '가설이 지지받지 못했어요.', 'Gaseori jijibatji motaesseoyo.', 'A hipótese não se sustentou.', 'Pesquisa acadêmica'],
    ['방법론', 'bangbeomnon', 'metodologia', 'substantivo', '방법론을 명확히 쓰세요.', 'Bangbeomnoneul myeonghwakhi sseuseyo.', 'Descreva sua metodologia com clareza.', 'Pesquisa acadêmica'],
    ['상관관계', 'sanggwangwangye', 'correlação', 'substantivo', '상관관계는 인과가 아니에요.', 'Sanggwangwangyeneun ingwaga anieyo.', 'Correlação não é causalidade.', 'Pesquisa acadêmica'],
    ['변수', 'byeonsu', 'variável', 'substantivo', '그 변수를 통제하세요.', 'Geu byeonsureul tongjehaseyo.', 'Controle essa variável.', 'Pesquisa acadêmica'],
    ['실증적인', 'siljeungjeogin', 'empírico', 'adjetivo', '실증적인 근거가 필요해요.', 'Siljeungjeogin geun-geoga piryohaeyo.', 'Precisamos de base empírica.', 'Pesquisa acadêmica'],
    ['동료 심사', 'dongryo simsa', 'revisão por pares', 'substantivo', '동료 심사가 오류를 잡았어요.', 'Dongryo simsaga oryureul jabasseoyo.', 'A revisão por pares pegou o erro.', 'Pesquisa acadêmica'],
    ['종단 연구', 'jongdan yeongu', 'estudo longitudinal', 'substantivo', '그것은 종단 연구였어요.', 'Geugeoseun jongdan yeonguyeosseoyo.', 'Foi um estudo longitudinal.', 'Pesquisa acadêmica'],
    ['재현', 'jaehyeon', 'replicação', 'substantivo', '재현이 두 번 실패했어요.', 'Jaehyeoni du beon silpaehaesseoyo.', 'A replicação falhou duas vezes.', 'Pesquisa acadêmica'],
    ['추론', 'churon', 'inferência', 'substantivo', '그 추론은 너무 넓어요.', 'Geu churoneun neomu neolbeoyo.', 'Essa inferência é ampla demais.', 'Pesquisa acadêmica'],
    ['패러다임', 'paereodaim', 'paradigma', 'substantivo', '패러다임이 천천히 바뀌었어요.', 'Paereodaimi cheoncheonhi bakkwieosseoyo.', 'O paradigma mudou devagar.', 'Pesquisa acadêmica'],
    ['이해관계자', 'ihaegwangyeja', 'parte interessada', 'substantivo', '모든 이해관계자와 상의하세요.', 'Modeun ihaegwangyejawa sanguihaseyo.', 'Consulte cada parte interessada.', 'Negócios'],
    ['인수', 'insu', 'aquisição', 'substantivo', '인수가 오월에 끝났어요.', 'Insuga owore kkeutnasseoyo.', 'A aquisição foi concluída em maio.', 'Negócios'],
    ['합병', 'hapbyeong', 'fusão', 'substantivo', '합병이 반발에 부딪혔어요.', 'Hapbyeongi banbare budichyeosseoyo.', 'A fusão enfrentou resistência.', 'Negócios'],
    ['매출', 'maechul', 'faturamento', 'substantivo', '매출이 십이 퍼센트 늘었어요.', 'Maechuri sibi peosenteu neureosseoyo.', 'O faturamento cresceu doze por cento.', 'Negócios'],
    ['배상 책임', 'baesang chaegim', 'responsabilidade indenizatória', 'substantivo', '그 조항이 배상 책임을 만들어요.', 'Geu johangi baesang chaegimeul mandeureoyo.', 'Aquela cláusula gera responsabilidade indenizatória.', 'Negócios'],
    ['중재', 'jungjae', 'arbitragem', 'substantivo', '중재로 갔어요.', 'Jungjaero gasseoyo.', 'Levaram à arbitragem.', 'Negócios'],
    ['기준점', 'gijunjeom', 'referência comparativa', 'substantivo', '현실적인 기준점을 정하세요.', 'Hyeonsiljeogin gijunjeomeul jeonghaseyo.', 'Defina uma referência realista.', 'Negócios'],
    ['타당성', 'tadangseong', 'viabilidade', 'substantivo', '타당성을 먼저 검토하세요.', 'Tadangseongeul meonjeo geomtohaseyo.', 'Estude a viabilidade primeiro.', 'Negócios'],
    ['다각화', 'dagakhwa', 'diversificação', 'substantivo', '다각화가 위험을 줄였어요.', 'Dagakhwaga wiheomeul juryeosseoyo.', 'A diversificação reduziu o risco.', 'Negócios'],
    ['조달', 'jodal', 'aquisição institucional', 'substantivo', '조달에는 몇 달이 걸려요.', 'Jodareneun myeot dari geollyeoyo.', 'O processo de compras leva meses.', 'Negócios'],
    ['존재론', 'jonjaeron', 'ontologia', 'substantivo', '그것은 존재론의 문제예요.', 'Geugeoseun jonjaeronui munjeyeyo.', 'Isso é uma questão de ontologia.', 'Filosofia'],
    ['인식론', 'insingnon', 'epistemologia', 'substantivo', '인식론은 앎의 근거를 물어요.', 'Insingnoneun almui geun-georeul mureoyo.', 'A epistemologia questiona a base do saber.', 'Filosofia'],
    ['결정론', 'gyeoljeongnon', 'determinismo', 'substantivo', '결정론은 자유의지를 부정해요.', 'Gyeoljeongnoneun jayuuijireul bujeonghaeyo.', 'O determinismo nega o livre-arbítrio.', 'Filosofia'],
    ['변증법', 'byeonjeungbeop', 'dialética', 'substantivo', '변증법으로 논증했어요.', 'Byeonjeungbeobeuro nonjeunghaesseoyo.', 'Ele argumentou pela dialética.', 'Filosofia'],
    ['형이상학', 'hyeongisanghak', 'metafísica', 'substantivo', '형이상학은 증명을 거부해요.', 'Hyeongisanghageun jeungmyeongeul geobuhaeyo.', 'A metafísica resiste à comprovação.', 'Filosofia'],
    ['실존적인', 'siljonjeogin', 'existencial', 'adjetivo', '실존적인 위협이 됐어요.', 'Siljonjeogin wihyeobi dwaesseoyo.', 'Virou uma ameaça existencial.', 'Filosofia'],
    ['목적론', 'mokjeongnon', 'teleologia', 'substantivo', '목적론은 목적으로 설명해요.', 'Mokjeongnoneun mokjeogeuro seolmyeonghaeyo.', 'A teleologia explica pela finalidade.', 'Filosofia'],
    ['허무주의', 'heomujuui', 'niilismo', 'substantivo', '허무주의는 내재적 의미를 부정해요.', 'Heomujuuineun naejaejeok uimireul bujeonghaeyo.', 'O niilismo nega sentido inerente.', 'Filosofia'],
    ['공리', 'gongni', 'axioma', 'substantivo', '공통의 공리에서 출발하세요.', 'Gongtongui gongnieseo chulbalhaseyo.', 'Parta de um axioma comum.', 'Filosofia'],
    ['삼단논법', 'samdannonbeop', 'silogismo', 'substantivo', '그 삼단논법은 무효예요.', 'Geu samdannonbeobeun muhyoyeyo.', 'Esse silogismo é inválido.', 'Filosofia'],
    ['계층화', 'gyecheunghwa', 'estratificação', 'substantivo', '사회 계층화가 계속돼요.', 'Sahoe gyecheunghwaga gyesokdwaeyo.', 'A estratificação social persiste.', 'Sociologia'],
    ['동화', 'donghwa', 'assimilação', 'substantivo', '그들에게 동화가 요구됐어요.', 'Geudeurege donghwaga yogudwaesseoyo.', 'Esperava-se deles a assimilação.', 'Sociologia'],
    ['인구학적', 'ingu-hakjeok', 'demográfico', 'adjetivo', '인구학적 변화가 뚜렷해요.', 'Ingu-hakjeok byeonhwaga tturyeotaeyo.', 'A mudança demográfica é clara.', 'Sociologia'],
    ['도시화', 'dosihwa', 'urbanização', 'substantivo', '도시화가 빨라졌어요.', 'Dosihwaga ppallajyeosseoyo.', 'A urbanização acelerou.', 'Sociologia'],
    ['세대 집단', 'sedae jipdan', 'coorte geracional', 'substantivo', '그 세대 집단은 소득이 낮아요.', 'Geu sedae jipdaneun sodeugi najayo.', 'Essa geração ganha menos.', 'Sociologia'],
    ['사회 규범', 'sahoe gyubeom', 'norma social', 'substantivo', '사회 규범이 조용히 변했어요.', 'Sahoe gyubeomi joyonghi byeonhaesseoyo.', 'A norma social mudou silenciosamente.', 'Sociologia'],
    ['일탈', 'iltal', 'desvio (social)', 'substantivo', '일탈은 맥락이 정해요.', 'Iltareun maengnagi jeonghaeyo.', 'O desvio é definido pelo contexto.', 'Sociologia'],
    ['사회 이동', 'sahoe idong', 'mobilidade social', 'substantivo', '사회 이동이 멈췄어요.', 'Sahoe idongi meomchwosseoyo.', 'A mobilidade social estagnou.', 'Sociologia'],
    ['혈연', 'hyeoryeon', 'parentesco consanguíneo', 'substantivo', '혈연의 유대가 강해요.', 'Hyeoryeonui yudaega ganghaeyo.', 'Os laços de parentesco são fortes.', 'Sociologia'],
    ['세속화', 'sesokhwa', 'secularização', 'substantivo', '세속화는 지역마다 달라요.', 'Sesokhwaneun jiyeongmada dallayo.', 'A secularização varia por região.', 'Sociologia'],
    ['예후', 'yehu', 'prognóstico', 'substantivo', '예후는 조심스럽게 좋아요.', 'Yehuneun josimseureopge joayo.', 'O prognóstico é cautelosamente bom.', 'Medicina'],
    ['만성', 'manseong', 'crônico', 'substantivo', '만성 질환이 됐어요.', 'Manseong jilhwani dwaesseoyo.', 'Virou uma doença crônica.', 'Medicina'],
    ['양성', 'yangseong', 'benigno', 'substantivo', '종양이 양성이었어요.', 'Jongyangi yangseongieosseoyo.', 'O tumor era benigno.', 'Medicina'],
    ['악성', 'akseong', 'maligno', 'substantivo', '검사에서 악성으로 나왔어요.', 'Geomsaeseo akseongeuro nawasseoyo.', 'O exame apontou tumor maligno.', 'Medicina'],
    ['관해', 'gwanhae', 'remissão', 'substantivo', '일 년째 관해 상태예요.', 'Il nyeonjjae gwanhae sangtaeyeyo.', 'Está em remissão há um ano.', 'Medicina'],
    ['병리', 'byeongni', 'patologia', 'substantivo', '병리 보고서가 왔어요.', 'Byeongni bogoseoga wasseoyo.', 'O laudo de patologia chegou.', 'Medicina'],
    ['면역', 'myeonyeok', 'imunidade', 'substantivo', '면역은 시간이 지나면 약해져요.', 'Myeonyeogeun sigani jinamyeon yakaejyeoyo.', 'A imunidade diminui com o tempo.', 'Medicina'],
    ['용량', 'yongnyang', 'dosagem', 'substantivo', '용량을 신중히 조절하세요.', 'Yongnyangeul sinjunghi jojeolhaseyo.', 'Ajuste a dosagem com cuidado.', 'Medicina'],
    ['절개', 'jeolgae', 'incisão', 'substantivo', '절개 부위가 잘 아물었어요.', 'Jeolgae buwiga jal amureosseoyo.', 'A incisão cicatrizou bem.', 'Medicina'],
    ['재발', 'jaebal', 'recaída', 'substantivo', '재발 가능성은 남아 있어요.', 'Jaebal ganeungseongeun nama isseoyo.', 'Uma recaída ainda é possível.', 'Medicina'],
    ['수사학', 'susahak', 'retórica', 'substantivo', '수사학이 정책을 앞질렀어요.', 'Susahagi jeongchaegeul apjilleosseoyo.', 'A retórica passou à frente da política.', 'Retórica'],
    ['설득', 'seoldeuk', 'persuasão', 'substantivo', '설득이 강요를 이겨요.', 'Seoldeugi gangyoreul igyeoyo.', 'A persuasão vence a coerção.', 'Retórica'],
    ['일화', 'ilhwa', 'anedota', 'substantivo', '일화는 자료가 아니에요.', 'Ilhwaneun jaryoga anieyo.', 'Uma anedota não é dado.', 'Retórica'],
    ['유추', 'yuchu', 'analogia', 'substantivo', '여기서 유추가 깨져요.', 'Yeogiseo yuchuga kkaejyeoyo.', 'A analogia falha aqui.', 'Retórica'],
    ['반박', 'banbak', 'refutação', 'substantivo', '그의 반박이 훌륭했어요.', 'Geuui banbagi hullyunghaesseoyo.', 'A refutação dele foi elegante.', 'Retórica'],
    ['함의', 'hamui', 'conotação / implicação', 'substantivo', '그 말에는 함의가 있어요.', 'Geu mareneun hamuiga isseoyo.', 'Aquela palavra carrega uma conotação.', 'Retórica'],
    ['반론', 'ballon', 'réplica', 'substantivo', '반론을 준비했어요.', 'Balloneul junbihaesseoyo.', 'Ela preparou uma réplica.', 'Retórica'],
    ['웅변', 'ungbyeon', 'eloquência', 'substantivo', '웅변이 약한 증거를 못 가려요.', 'Ungbyeoni yakan jeunggeoreul mot garyeoyo.', 'A eloquência não esconde evidência fraca.', 'Retórica'],
    ['담론', 'damnon', 'discurso (campo)', 'substantivo', '공적 담론이 거칠어졌어요.', 'Gongjeok damnoni geochireojyeosseoyo.', 'O discurso público se degradou.', 'Retórica'],
    ['여담', 'yeodam', 'digressão', 'substantivo', '여담은 용서하세요.', 'Yeodameun yongseohaseyo.', 'Perdoe a digressão.', 'Retórica'],
  ],
  C2: [
    ['애가풍의', 'aegapungui', 'elegíaco', 'adjetivo', '이 소설은 애가풍의 어조예요.', 'I soseoreun aegapungui eojoyeyo.', 'Este romance tem um tom elegíaco.', 'Registro literário'],
    ['음울한', 'eumulhan', 'sombrio / lúgubre', 'adjetivo', '음울한 목소리로 말했어요.', 'Eumulhan moksoriro malhaesseoyo.', 'Ele falou com uma voz lúgubre.', 'Registro literário'],
    ['목가적인', 'mokgajeogin', 'idílico', 'adjetivo', '목가적인 나날이었어요.', 'Mokgajeogin nanarieosseoyo.', 'Eram dias idílicos.', 'Registro literário'],
    ['감미로운', 'gammiroun', 'melodioso / suave', 'adjetivo', '감미로운 낭독이었어요.', 'Gammiroun nangdogieosseoyo.', 'Foi uma leitura melodiosa.', 'Registro literário'],
    ['구슬픈', 'guseulpeun', 'lamentoso', 'adjetivo', '구슬픈 선율이 흘렀어요.', 'Guseulpeun seonyuri heulleosseoyo.', 'Uma melodia lamentosa soou.', 'Registro literário'],
    ['찬란한', 'challanhan', 'resplandecente', 'adjetivo', '찬란한 경력을 가졌어요.', 'Challanhan gyeongnyeogeul gajyeosseoyo.', 'Tem uma trajetória resplandecente.', 'Registro literário'],
    ['담백한', 'dambaekhan', 'sóbrio / despojado', 'adjetivo', '문체가 담백하고 정확해요.', 'Muncheega dambaekago jeonghwakaeyo.', 'O estilo é sóbrio e exato.', 'Registro literário'],
    ['나른한', 'nareunhan', 'lânguido', 'adjetivo', '나른한 오후였어요.', 'Nareunhan ohuyeosseoyo.', 'Foi uma tarde lânguida.', 'Registro literário'],
    ['몽환적인', 'monghwanjeogin', 'onírico / etéreo', 'adjetivo', '빛이 몽환적이었어요.', 'Bichi monghwanjeogieosseoyo.', 'A luz era etérea.', 'Registro literário'],
    ['낭랑한', 'nangnanghan', 'sonoro / claro', 'adjetivo', '낭랑한 목소리가 울렸어요.', 'Nangnanghan moksoriga ullyeosseoyo.', 'Uma voz sonora ecoou.', 'Registro literário'],
    ['소송 절차', 'sosong jeolcha', 'trâmite processual', 'substantivo', '소송 절차가 길어졌어요.', 'Sosong jeolchaga gireojyeosseoyo.', 'O trâmite processual se alongou.', 'Jurídico avançado'],
    ['관할권', 'gwanhalgwon', 'jurisdição', 'substantivo', '법원에 관할권이 없어요.', 'Beobwone gwanhalgwoni eopseoyo.', 'O tribunal não tem jurisdição.', 'Jurídico avançado'],
    ['공소장', 'gongsojang', 'denúncia formal', 'substantivo', '공소장이 육십 쪽이었어요.', 'Gongsojangi yuksip jjogieosseoyo.', 'A denúncia tinha sessenta páginas.', 'Jurídico avançado'],
    ['책임 능력', 'chaegim neungnyeok', 'imputabilidade', 'substantivo', '책임 능력이 인정되지 않았어요.', 'Chaegim neungnyeogi injeongdoeji anasseoyo.', 'A imputabilidade não foi reconhecida.', 'Jurídico avançado'],
    ['추정', 'chujeong', 'presunção', 'substantivo', '무죄 추정이 적용돼요.', 'Mujoe chujeongi jeogyongdwaeyo.', 'A presunção de inocência se aplica.', 'Jurídico avançado'],
    ['면책의', 'myeonchaegui', 'excludente de responsabilidade', 'adjetivo', '면책의 증거를 숨겼어요.', 'Myeonchaegui jeunggeoreul sumgyeosseoyo.', 'Ocultaram provas excludentes.', 'Jurídico avançado'],
    ['금지 명령', 'geumji myeongnyeong', 'liminar / medida proibitiva', 'substantivo', '판사가 금지 명령을 내렸어요.', 'Pansaga geumji myeongnyeongeul naeryeosseoyo.', 'O juiz concedeu uma liminar.', 'Jurídico avançado'],
    ['선서 진술', 'seonseo jinsul', 'depoimento juramentado', 'substantivo', '선서 진술이 하루 종일 이어졌어요.', 'Seonseo jinsuri haru jongil ieojyeosseoyo.', 'O depoimento juramentado durou o dia todo.', 'Jurídico avançado'],
    ['판결하다', 'pangyeolhada', 'julgar / sentenciar', 'verbo', '위원회가 분쟁을 판결해요.', 'Wiwonhoega bunjaengeul pangyeolhaeyo.', 'A comissão julga a disputa.', 'Jurídico avançado'],
    ['불법 행위', 'bulbeop haengwi', 'ilícito civil', 'substantivo', '이것은 불법 행위에 해당해요.', 'Igeoseun bulbeop haengwie haedanghaeyo.', 'Isso configura um ilícito civil.', 'Jurídico avançado'],
    ['박식한', 'baksikhan', 'erudito', 'adjetivo', '박식한 주석이 달렸어요.', 'Baksikan juseogi dallyeosseoyo.', 'Vem com notas eruditas.', 'Termos eruditos'],
    ['명료한', 'myeongnyohan', 'lúcido / claro', 'adjetivo', '명료한 설명이 논쟁을 끝냈어요.', 'Myeongnyohan seolmyeongi nonjaengeul kkeutnaesseoyo.', 'A explicação lúcida encerrou o debate.', 'Termos eruditos'],
    ['난해한', 'nanhaehan', 'hermético / difícil', 'adjetivo', '논의가 난해해졌어요.', 'Nonuiga nanhaehaejyeosseoyo.', 'O debate ficou hermético.', 'Termos eruditos'],
    ['심오한', 'simohan', 'profundo / recôndito', 'adjetivo', '심오한 주제를 다뤄요.', 'Simohan jujereul daryeoyo.', 'Trata de um tema profundo.', 'Termos eruditos'],
    ['명민한', 'myeongminhan', 'sagaz', 'adjetivo', '명민한 선택이었어요.', 'Myeongminhan seontaegieosseoyo.', 'Foi uma escolha sagaz.', 'Termos eruditos'],
    ['통찰력 있는', 'tongchallyeok inneun', 'perspicaz', 'adjetivo', '통찰력 있는 독자는 알아채요.', 'Tongchallyeok inneun dokjaneun arachaeyo.', 'Um leitor perspicaz percebe.', 'Termos eruditos'],
    ['간결한', 'gangyeolhan', 'lacônico / conciso', 'adjetivo', '대답이 간결했어요.', 'Daedabi gangyeolhaesseoyo.', 'A resposta foi lacônica.', 'Termos eruditos'],
    ['장황한', 'janghwanghan', 'prolixo', 'adjetivo', '서론이 장황해요.', 'Seoroni janghwanghaeyo.', 'A introdução é prolixa.', 'Termos eruditos'],
    ['과묵한', 'gwamukhan', 'taciturno', 'adjetivo', '그는 내내 과묵했어요.', 'Geuneun naenae gwamukaesseoyo.', 'Ele permaneceu taciturno o tempo todo.', 'Termos eruditos'],
    ['수다스러운', 'sudaseureoun', 'tagarela', 'adjetivo', '수다스러운 주인이 멈추지 않았어요.', 'Sudaseureoun juini meomchuji anasseoyo.', 'O anfitrião tagarela não parava.', 'Termos eruditos'],
    ['양가감정', 'yanggagamjeong', 'ambivalência', 'substantivo', '그녀의 양가감정이 뚜렷했어요.', 'Geunyeoui yanggagamjeongi tturyeotaesseoyo.', 'A ambivalência dela era evidente.', 'Nuance psicológica'],
    ['가책', 'gachaek', 'peso na consciência', 'substantivo', '가책 없이 거짓말했어요.', 'Gachaek eopsi geojinmalhaesseoyo.', 'Mentiu sem peso na consciência.', 'Nuance psicológica'],
    ['전율', 'jeonyul', 'arrepio / apreensão', 'substantivo', '전율을 느끼며 열었어요.', 'Jeonyureul neukkimyeo yeoreosseoyo.', 'Abriu sentindo um arrepio.', 'Nuance psicológica'],
    ['노여움', 'noyeoum', 'indignação / ofensa', 'substantivo', '그 말에 노여움을 느꼈어요.', 'Geu mare noyeoumeul neukkyeosseoyo.', 'Sentiu-se ofendido com aquele comentário.', 'Nuance psicológica'],
    ['앙금', 'anggeum', 'mágoa remanescente', 'substantivo', '앙금 없이 이야기했어요.', 'Anggeum eopsi iyagihaesseoyo.', 'Falou sem mágoa.', 'Nuance psicológica'],
    ['뉘우침', 'nwiuchim', 'contrição / arrependimento', 'substantivo', '뉘우침이 진심 같았어요.', 'Nwiuchimi jinsim gatasseoyo.', 'A contrição parecia genuína.', 'Nuance psicológica'],
    ['오만', 'oman', 'arrogância', 'substantivo', '오만이 몰락을 불렀어요.', 'Omani mollageul bulleosseoyo.', 'A arrogância levou ao colapso.', 'Nuance psicológica'],
    ['너그러움', 'neogeureoum', 'tolerância / clemência', 'substantivo', '너그러움에 감사드려요.', 'Neogeureoume gamsadeuryeoyo.', 'Agradeço pela sua tolerância.', 'Nuance psicológica'],
    ['아량', 'aryang', 'magnanimidade', 'substantivo', '뜻밖의 아량을 보였어요.', 'Tteutbakkui aryangeul boyeosseoyo.', 'Mostrou magnanimidade inesperada.', 'Nuance psicológica'],
    ['수줍음', 'sujueum', 'timidez', 'substantivo', '수줍음이 진짜 실력을 가렸어요.', 'Sujueumi jinjja sillyeogeul garyeosseoyo.', 'A timidez escondia talento real.', 'Nuance psicológica'],
    ['따름정리', 'ttareumjeongni', 'corolário', 'substantivo', '비용 증가는 그 따름정리예요.', 'Biyong jeungganeun geu ttareumjeongniyeyo.', 'O aumento de custo é um corolário disso.', 'Argumentação'],
    ['자명한', 'jamyeonghan', 'axiomático / evidente', 'adjetivo', '이 분야에서는 자명한 사실이에요.', 'I bunyaeseoneun jamyeonghan sasirieyo.', 'Nesta área isso é evidente.', 'Argumentação'],
    ['반박 불가능한', 'banbak bulganeunghan', 'irrefutável', 'adjetivo', '자료가 반박 불가능해요.', 'Jaryoga banbak bulganeunghaeyo.', 'Os dados são irrefutáveis.', 'Argumentação'],
    ['타당한', 'tadanghan', 'válido / bem fundamentado', 'adjetivo', '타당한 주장을 폈어요.', 'Tadanghan jujangeul pyeosseoyo.', 'Apresentou um argumento bem fundamentado.', 'Argumentação'],
    ['외삽하다', 'oesaphada', 'extrapolar', 'verbo', '한 사례에서 외삽하지 마세요.', 'Han saryeeseo oesaphaji maseyo.', 'Não extrapole a partir de um caso.', 'Argumentação'],
    ['궤변술', 'gwebyeonsul', 'sofística', 'substantivo', '그 변론은 궤변술이에요.', 'Geu byeonnoneun gwebyeonsurieyo.', 'Essa defesa é pura sofística.', 'Argumentação'],
    ['불성실한', 'bulseongsilhan', 'insincero / de má-fé', 'adjetivo', '불성실한 답변이에요.', 'Bulseongsilhan dapbyeonieyo.', 'É uma resposta de má-fé.', 'Argumentação'],
    ['그럴싸한', 'geureolssahan', 'aparentemente convincente', 'adjetivo', '그럴싸한 논리일 뿐이에요.', 'Geureolssahan nonriil ppunieyo.', 'É apenas uma lógica aparentemente convincente.', 'Argumentação'],
    ['적절한', 'jeokjeolhan', 'pertinente / adequado', 'adjetivo', '적절한 지적이에요.', 'Jeokjeolhan jijeogieyo.', 'É uma observação pertinente.', 'Argumentação'],
    ['그 자체로', 'geu jachero', 'por si só', 'advérbio', '그 자체로 결론이 되지는 않아요.', 'Geu jachero gyeolloni doejineun anayo.', 'Por si só não é uma conclusão.', 'Argumentação'],
    ['핍진성', 'pipjinseong', 'verossimilhança', 'substantivo', '이 영화는 핍진성이 부족해요.', 'I yeonghwaneun pipjinseongi bujokaeyo.', 'Este filme carece de verossimilhança.', 'Crítica e estética'],
    ['혼성모방', 'honseongmobang', 'pastiche', 'substantivo', '이건 의도적인 혼성모방이에요.', 'Igeon uidojeogin honseongmobangieyo.', 'Isto é um pastiche intencional.', 'Crítica e estética'],
    ['용두사미', 'yongdusami', 'começo grandioso e fim fraco', 'substantivo', '결말이 용두사미였어요.', 'Gyeolmari yongdusamiyeosseoyo.', 'O final foi um anticlímax.', 'Crítica e estética'],
    ['대단원', 'daedanwon', 'desfecho', 'substantivo', '대단원이 급했어요.', 'Daedanwoni geuphaesseoyo.', 'O desfecho pareceu apressado.', 'Crítica e estética'],
    ['우화', 'uhwa', 'fábula / alegoria', 'substantivo', '이 책 전체가 우화예요.', 'I chaek jeonchega uhwayeyo.', 'O livro inteiro é uma alegoria.', 'Crítica e estética'],
    ['반복 모티프', 'banbok motipeu', 'motivo recorrente', 'substantivo', '물이 중심 반복 모티프예요.', 'Muri jungsim banbok motipeuyeyo.', 'A água é o motivo recorrente central.', 'Crítica e estética'],
    ['과장', 'gwajang', 'hipérbole / exagero', 'substantivo', '그건 과장이지 분석이 아니에요.', 'Geugeon gwajangiji bunseogi anieyo.', 'Isso é exagero, não análise.', 'Crítica e estética'],
    ['비장미', 'bijangmi', 'beleza trágica / pathos', 'substantivo', '그 장면에 비장미가 있어요.', 'Geu jangmyeone bijangmiga isseoyo.', 'Aquela cena tem um pathos trágico.', 'Crítica e estética'],
    ['풍자', 'pungja', 'sátira', 'substantivo', '풍자로 읽는 편이 나아요.', 'Pungjaro ingneun pyeoni naayo.', 'Funciona melhor lido como sátira.', 'Crítica e estética'],
    ['전집', 'jeonjip', 'obra completa', 'substantivo', '전집 안에서는 소품이에요.', 'Jeonjip aneseoneun sopumieyo.', 'Dentro da obra completa é uma peça menor.', 'Crítica e estética'],
  ],
};
