/** Mandarim — lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { AsianByLevel } from '../entry';

export const ZH_THEMATIC: AsianByLevel = {
  A1: [
    ['绿色', 'lǜsè', 'verde', 'substantivo', '草是绿色的。', 'Cǎo shì lǜsè de.', 'A grama é verde.', 'Cores e formas'],
    ['黄色', 'huángsè', 'amarelo', 'substantivo', '我喜欢黄色的花。', 'Wǒ xǐhuān huángsè de huā.', 'Gosto de flores amarelas.', 'Cores e formas'],
    ['黑色', 'hēisè', 'preto', 'substantivo', '他穿黑色的大衣。', 'Tā chuān hēisè de dàyī.', 'Ele usa um casaco preto.', 'Cores e formas'],
    ['白色', 'báisè', 'branco', 'substantivo', '墙是白色的。', 'Qiáng shì báisè de.', 'As paredes são brancas.', 'Cores e formas'],
    ['橙色', 'chéngsè', 'laranja (cor)', 'substantivo', '她有橙色的包。', 'Tā yǒu chéngsè de bāo.', 'Ela tem uma bolsa laranja.', 'Cores e formas'],
    ['紫色', 'zǐsè', 'roxo', 'substantivo', '天空变成紫色了。', 'Tiānkōng biànchéng zǐsè le.', 'O céu ficou roxo.', 'Cores e formas'],
    ['棕色', 'zōngsè', 'marrom', 'substantivo', '我的鞋是棕色的。', 'Wǒ de xié shì zōngsè de.', 'Meus sapatos são marrons.', 'Cores e formas'],
    ['粉色', 'fěnsè', 'rosa', 'substantivo', '这是粉色的毯子。', 'Zhè shì fěnsè de tǎnzi.', 'Este é um cobertor rosa.', 'Cores e formas'],
    ['圆形', 'yuánxíng', 'círculo', 'substantivo', '请在这里画一个圆形。', 'Qǐng zài zhèlǐ huà yí gè yuánxíng.', 'Desenhe um círculo aqui.', 'Cores e formas'],
    ['方形', 'fāngxíng', 'quadrado', 'substantivo', '这个盒子是方形的。', 'Zhège hézi shì fāngxíng de.', 'Esta caixa é um quadrado.', 'Cores e formas'],
    ['衬衫', 'chènshān', 'camisa', 'substantivo', '这件衬衫很干净。', 'Zhè jiàn chènshān hěn gānjìng.', 'Esta camisa está limpa.', 'Roupas'],
    ['裤子', 'kùzi', 'calça', 'substantivo', '这条裤子是新的。', 'Zhè tiáo kùzi shì xīn de.', 'Esta calça é nova.', 'Roupas'],
    ['鞋', 'xié', 'sapatos', 'substantivo', '我的鞋湿了。', 'Wǒ de xié shī le.', 'Meus sapatos estão molhados.', 'Roupas'],
    ['连衣裙', 'liányīqún', 'vestido', 'substantivo', '她买了一条连衣裙。', 'Tā mǎi le yì tiáo liányīqún.', 'Ela comprou um vestido.', 'Roupas'],
    ['夹克', 'jiákè', 'jaqueta', 'substantivo', '带上你的夹克。', 'Dài shàng nǐ de jiákè.', 'Leve sua jaqueta.', 'Roupas'],
    ['帽子', 'màozi', 'chapéu', 'substantivo', '他丢了帽子。', 'Tā diū le màozi.', 'Ele perdeu o chapéu.', 'Roupas'],
    ['袜子', 'wàzi', 'meias', 'substantivo', '我需要干净的袜子。', 'Wǒ xūyào gānjìng de wàzi.', 'Preciso de meias limpas.', 'Roupas'],
    ['大衣', 'dàyī', 'sobretudo / casaco', 'substantivo', '今天穿大衣吧。', 'Jīntiān chuān dàyī ba.', 'Use um casaco hoje.', 'Roupas'],
    ['裙子', 'qúnzi', 'saia', 'substantivo', '那条裙子很长。', 'Nà tiáo qúnzi hěn cháng.', 'Aquela saia é longa.', 'Roupas'],
    ['眼镜', 'yǎnjìng', 'óculos', 'substantivo', '我忘了眼镜。', 'Wǒ wàng le yǎnjìng.', 'Esqueci meus óculos.', 'Roupas'],
    ['太阳', 'tàiyáng', 'sol', 'substantivo', '太阳很强。', 'Tàiyáng hěn qiáng.', 'O sol está forte.', 'Clima e natureza'],
    ['雨', 'yǔ', 'chuva', 'substantivo', '雨停了。', 'Yǔ tíng le.', 'A chuva parou.', 'Clima e natureza'],
    ['雪', 'xuě', 'neve', 'substantivo', '雪很深。', 'Xuě hěn shēn.', 'A neve está funda.', 'Clima e natureza'],
    ['风', 'fēng', 'vento', 'substantivo', '风很大。', 'Fēng hěn dà.', 'O vento está forte.', 'Clima e natureza'],
    ['云', 'yún', 'nuvem', 'substantivo', '天上有一朵云。', 'Tiān shàng yǒu yì duǒ yún.', 'Há uma nuvem no céu.', 'Clima e natureza'],
    ['树', 'shù', 'árvore', 'substantivo', '这棵树很老。', 'Zhè kē shù hěn lǎo.', 'Esta árvore é velha.', 'Clima e natureza'],
    ['花', 'huā', 'flor', 'substantivo', '她喜欢这朵花。', 'Tā xǐhuān zhè duǒ huā.', 'Ela gosta desta flor.', 'Clima e natureza'],
    ['天空', 'tiānkōng', 'céu', 'substantivo', '天空很晴朗。', 'Tiānkōng hěn qínglǎng.', 'O céu está limpo.', 'Clima e natureza'],
    ['海滩', 'hǎitān', 'praia', 'substantivo', '我们去海滩。', 'Wǒmen qù hǎitān.', 'Nós vamos à praia.', 'Clima e natureza'],
    ['山', 'shān', 'montanha', 'substantivo', '那座山很高。', 'Nà zuò shān hěn gāo.', 'Aquela montanha é alta.', 'Clima e natureza'],
    ['头', 'tóu', 'cabeça', 'substantivo', '我头疼。', 'Wǒ tóu téng.', 'Minha cabeça dói.', 'Corpo'],
    ['手', 'shǒu', 'mão', 'substantivo', '把手给我。', 'Bǎ shǒu gěi wǒ.', 'Me dê sua mão.', 'Corpo'],
    ['脚', 'jiǎo', 'pé', 'substantivo', '我的脚很冷。', 'Wǒ de jiǎo hěn lěng.', 'Meu pé está frio.', 'Corpo'],
    ['眼睛', 'yǎnjing', 'olho', 'substantivo', '我的眼睛累了。', 'Wǒ de yǎnjing lèi le.', 'Meus olhos estão cansados.', 'Corpo'],
    ['耳朵', 'ěrduo', 'orelha / ouvido', 'substantivo', '我的耳朵疼。', 'Wǒ de ěrduo téng.', 'Meu ouvido dói.', 'Corpo'],
    ['嘴', 'zuǐ', 'boca', 'substantivo', '请张开嘴。', 'Qǐng zhāngkāi zuǐ.', 'Abra a boca.', 'Corpo'],
    ['鼻子', 'bízi', 'nariz', 'substantivo', '他的鼻子红了。', 'Tā de bízi hóng le.', 'O nariz dele está vermelho.', 'Corpo'],
    ['头发', 'tóufa', 'cabelo', 'substantivo', '她的头发很长。', 'Tā de tóufa hěn cháng.', 'O cabelo dela é longo.', 'Corpo'],
    ['手臂', 'shǒubì', 'braço', 'substantivo', '他的手臂断了。', 'Tā de shǒubì duàn le.', 'Ele quebrou o braço.', 'Corpo'],
    ['腿', 'tuǐ', 'perna', 'substantivo', '我的腿累了。', 'Wǒ de tuǐ lèi le.', 'Minha perna está cansada.', 'Corpo'],
    ['面包', 'miànbāo', 'pão', 'substantivo', '我每天吃面包。', 'Wǒ měitiān chī miànbāo.', 'Eu como pão todo dia.', 'Comida e bebida'],
    ['牛奶', 'niúnǎi', 'leite', 'substantivo', '牛奶是凉的。', 'Niúnǎi shì liáng de.', 'O leite está frio.', 'Comida e bebida'],
    ['咖啡', 'kāfēi', 'café', 'substantivo', '她喝咖啡。', 'Tā hē kāfēi.', 'Ela bebe café.', 'Comida e bebida'],
    ['米饭', 'mǐfàn', 'arroz cozido', 'substantivo', '我们中午吃米饭。', 'Wǒmen zhōngwǔ chī mǐfàn.', 'Comemos arroz no almoço.', 'Comida e bebida'],
    ['肉', 'ròu', 'carne', 'substantivo', '他不吃肉。', 'Tā bù chī ròu.', 'Ele não come carne.', 'Comida e bebida'],
    ['水果', 'shuǐguǒ', 'fruta', 'substantivo', '请买一些水果。', 'Qǐng mǎi yìxiē shuǐguǒ.', 'Compre frutas.', 'Comida e bebida'],
    ['鸡蛋', 'jīdàn', 'ovo', 'substantivo', '我要一个鸡蛋。', 'Wǒ yào yí gè jīdàn.', 'Quero um ovo.', 'Comida e bebida'],
    ['奶酪', 'nǎilào', 'queijo', 'substantivo', '这种奶酪很好吃。', 'Zhè zhǒng nǎilào hěn hǎochī.', 'Este queijo é bom.', 'Comida e bebida'],
    ['糖', 'táng', 'açúcar', 'substantivo', '请不要放糖。', 'Qǐng búyào fàng táng.', 'Sem açúcar, por favor.', 'Comida e bebida'],
    ['盐', 'yán', 'sal', 'substantivo', '请把盐递给我。', 'Qǐng bǎ yán dì gěi wǒ.', 'Me passe o sal.', 'Comida e bebida'],
    ['早上', 'zǎoshang', 'manhã', 'substantivo', '我早上工作。', 'Wǒ zǎoshang gōngzuò.', 'Eu trabalho de manhã.', 'Tempo e rotina'],
    ['下午', 'xiàwǔ', 'tarde', 'substantivo', '下午见。', 'Xiàwǔ jiàn.', 'Até a tarde.', 'Tempo e rotina'],
    ['傍晚', 'bàngwǎn', 'fim de tarde', 'substantivo', '我们傍晚回来。', 'Wǒmen bàngwǎn huílái.', 'Voltamos no fim da tarde.', 'Tempo e rotina'],
    ['晚上', 'wǎnshang', 'noite', 'substantivo', '晚上很安静。', 'Wǎnshang hěn ānjìng.', 'A noite está calma.', 'Tempo e rotina'],
    ['这周', 'zhè zhōu', 'esta semana', 'substantivo', '这周很长。', 'Zhè zhōu hěn cháng.', 'Esta semana está longa.', 'Tempo e rotina'],
    ['这个月', 'zhège yuè', 'este mês', 'substantivo', '这个月很忙。', 'Zhège yuè hěn máng.', 'Este mês está cheio.', 'Tempo e rotina'],
    ['今天', 'jīntiān', 'hoje', 'substantivo', '我今天很累。', 'Wǒ jīntiān hěn lèi.', 'Estou cansado hoje.', 'Tempo e rotina'],
    ['明天', 'míngtiān', 'amanhã', 'substantivo', '我们明天出发。', 'Wǒmen míngtiān chūfā.', 'Nós viajamos amanhã.', 'Tempo e rotina'],
    ['昨天', 'zuótiān', 'ontem', 'substantivo', '昨天下雨了。', 'Zuótiān xià yǔ le.', 'Choveu ontem.', 'Tempo e rotina'],
    ['周末', 'zhōumò', 'fim de semana', 'substantivo', '周末我休息。', 'Zhōumò wǒ xiūxi.', 'No fim de semana eu descanso.', 'Tempo e rotina'],
  ],
  A2: [
    ['航班', 'hángbān', 'voo', 'substantivo', '我们的航班六点起飞。', 'Wǒmen de hángbān liù diǎn qǐfēi.', 'Nosso voo sai às seis.', 'Viagem'],
    ['护照', 'hùzhào', 'passaporte', 'substantivo', '请出示您的护照。', 'Qǐng chūshì nín de hùzhào.', 'Me mostre seu passaporte.', 'Viagem'],
    ['行李', 'xíngli', 'bagagem', 'substantivo', '我的行李很重。', 'Wǒ de xíngli hěn zhòng.', 'Minha bagagem está pesada.', 'Viagem'],
    ['车票', 'chēpiào', 'passagem / bilhete', 'substantivo', '我在网上买了车票。', 'Wǒ zài wǎngshàng mǎi le chēpiào.', 'Comprei a passagem pela internet.', 'Viagem'],
    ['延误', 'yánwù', 'atraso', 'substantivo', '有很长的延误。', 'Yǒu hěn cháng de yánwù.', 'Houve um atraso longo.', 'Viagem'],
    ['机场', 'jīchǎng', 'aeroporto', 'substantivo', '机场很远。', 'Jīchǎng hěn yuǎn.', 'O aeroporto é longe.', 'Viagem'],
    ['行李箱', 'xínglixiāng', 'mala', 'substantivo', '今晚收拾行李箱。', 'Jīnwǎn shōushi xínglixiāng.', 'Faça a mala hoje à noite.', 'Viagem'],
    ['出发', 'chūfā', 'partida', 'substantivo', '请确认出发时间。', 'Qǐng quèrèn chūfā shíjiān.', 'Confira o horário de partida.', 'Viagem'],
    ['到达', 'dàodá', 'chegada', 'substantivo', '到达很顺利。', 'Dàodá hěn shùnlì.', 'A chegada foi tranquila.', 'Viagem'],
    ['登机牌', 'dēngjīpái', 'cartão de embarque', 'substantivo', '请保管好登机牌。', 'Qǐng bǎoguǎn hǎo dēngjīpái.', 'Guarde seu cartão de embarque.', 'Viagem'],
    ['菜单', 'càidān', 'cardápio', 'substantivo', '可以看看菜单吗？', 'Kěyǐ kànkan càidān ma?', 'Posso ver o cardápio?', 'Restaurante'],
    ['服务员', 'fúwùyuán', 'garçom', 'substantivo', '服务员来了。', 'Fúwùyuán lái le.', 'O garçom está vindo.', 'Restaurante'],
    ['小费', 'xiǎofèi', 'gorjeta', 'substantivo', '我们留了小费。', 'Wǒmen liú le xiǎofèi.', 'Deixamos gorjeta.', 'Restaurante'],
    ['甜点', 'tiándiǎn', 'sobremesa', 'substantivo', '我想要甜点。', 'Wǒ xiǎng yào tiándiǎn.', 'Quero sobremesa.', 'Restaurante'],
    ['前菜', 'qiáncài', 'entrada (prato)', 'substantivo', '前菜很小。', 'Qiáncài hěn xiǎo.', 'A entrada era pequena.', 'Restaurante'],
    ['订位', 'dìngwèi', 'reserva de mesa', 'substantivo', '我订位了。', 'Wǒ dìngwèi le.', 'Fiz uma reserva.', 'Restaurante'],
    ['餐巾', 'cānjīn', 'guardanapo', 'substantivo', '请给我一张餐巾。', 'Qǐng gěi wǒ yì zhāng cānjīn.', 'Me passe um guardanapo.', 'Restaurante'],
    ['托盘', 'tuōpán', 'bandeja', 'substantivo', '请放在托盘上。', 'Qǐng fàng zài tuōpán shàng.', 'Coloque na bandeja.', 'Restaurante'],
    ['味道', 'wèidào', 'sabor', 'substantivo', '味道很奇怪。', 'Wèidào hěn qíguài.', 'O sabor está estranho.', 'Restaurante'],
    ['辣', 'là', 'picante', 'adjetivo', '这道菜很辣。', 'Zhè dào cài hěn là.', 'Este prato é picante.', 'Restaurante'],
    ['现金', 'xiànjīn', 'dinheiro (em espécie)', 'substantivo', '我只有现金。', 'Wǒ zhǐ yǒu xiànjīn.', 'Só tenho dinheiro em espécie.', 'Compras'],
    ['找零', 'zhǎolíng', 'troco', 'substantivo', '不用找零了。', 'Búyòng zhǎolíng le.', 'Fique com o troco.', 'Compras'],
    ['尺码', 'chǐmǎ', 'tamanho (roupa)', 'substantivo', '有更大的尺码吗？', 'Yǒu gèng dà de chǐmǎ ma?', 'Tem um tamanho maior?', 'Compras'],
    ['便宜货', 'piányihuò', 'pechincha', 'substantivo', '那件大衣是便宜货。', 'Nà jiàn dàyī shì piányihuò.', 'Aquele casaco foi uma pechincha.', 'Compras'],
    ['收银员', 'shōuyínyuán', 'operador de caixa', 'substantivo', '问一下收银员。', 'Wèn yíxià shōuyínyuán.', 'Pergunte ao caixa.', 'Compras'],
    ['通道', 'tōngdào', 'corredor', 'substantivo', '牛奶在三号通道。', 'Niúnǎi zài sān hào tōngdào.', 'O leite está no corredor três.', 'Compras'],
    ['架子', 'jiàzi', 'prateleira', 'substantivo', '架子空了。', 'Jiàzi kōng le.', 'A prateleira está vazia.', 'Compras'],
    ['促销', 'cùxiāo', 'promoção', 'substantivo', '鞋在促销。', 'Xié zài cùxiāo.', 'Os sapatos estão em promoção.', 'Compras'],
    ['钱包', 'qiánbāo', 'carteira', 'substantivo', '我把钱包忘在家里了。', 'Wǒ bǎ qiánbāo wàng zài jiā lǐ le.', 'Deixei minha carteira em casa.', 'Compras'],
    ['品牌', 'pǐnpái', 'marca', 'substantivo', '我信任这个品牌。', 'Wǒ xìnrèn zhège pǐnpái.', 'Confio nesta marca.', 'Compras'],
    ['咳嗽', 'késou', 'tosse', 'substantivo', '她咳嗽得厉害。', 'Tā késou de lìhai.', 'A tosse dela está feia.', 'Saúde'],
    ['头痛', 'tóutòng', 'dor de cabeça', 'substantivo', '我有点头痛。', 'Wǒ yǒudiǎn tóutòng.', 'Estou com dor de cabeça.', 'Saúde'],
    ['药片', 'yàopiàn', 'comprimido', 'substantivo', '每天吃一片药片。', 'Měitiān chī yí piàn yàopiàn.', 'Tome um comprimido por dia.', 'Saúde'],
    ['护士', 'hùshi', 'enfermeiro', 'substantivo', '护士很亲切。', 'Hùshi hěn qīnqiè.', 'O enfermeiro foi gentil.', 'Saúde'],
    ['受伤', 'shòushāng', 'ferir-se / lesão', 'verbo', '他受伤很严重。', 'Tā shòushāng hěn yánzhòng.', 'Ele se feriu gravemente.', 'Saúde'],
    ['休息', 'xiūxi', 'descanso', 'substantivo', '你需要休息。', 'Nǐ xūyào xiūxi.', 'Você precisa de descanso.', 'Saúde'],
    ['绷带', 'bēngdài', 'bandagem', 'substantivo', '请包上绷带。', 'Qǐng bāo shàng bēngdài.', 'Coloque uma bandagem.', 'Saúde'],
    ['头晕', 'tóuyūn', 'tontura', 'substantivo', '我有点头晕。', 'Wǒ yǒudiǎn tóuyūn.', 'Estou um pouco tonto.', 'Saúde'],
    ['诊所', 'zhěnsuǒ', 'clínica', 'substantivo', '诊所八点开门。', 'Zhěnsuǒ bā diǎn kāimén.', 'A clínica abre às oito.', 'Saúde'],
    ['疼痛', 'téngtòng', 'dor', 'substantivo', '我背部有疼痛。', 'Wǒ bèibù yǒu téngtòng.', 'Tenho dor nas costas.', 'Saúde'],
    ['桥', 'qiáo', 'ponte', 'substantivo', '请过桥。', 'Qǐng guò qiáo.', 'Atravesse a ponte.', 'Cidade'],
    ['广场', 'guǎngchǎng', 'praça', 'substantivo', '我们在广场见面。', 'Wǒmen zài guǎngchǎng jiànmiàn.', 'Nos encontramos na praça.', 'Cidade'],
    ['拐角', 'guǎijiǎo', 'esquina', 'substantivo', '在拐角处转弯。', 'Zài guǎijiǎo chù zhuǎnwān.', 'Vire na esquina.', 'Cidade'],
    ['交通', 'jiāotōng', 'trânsito', 'substantivo', '交通很糟糕。', 'Jiāotōng hěn zāogāo.', 'O trânsito está terrível.', 'Cidade'],
    ['地铁', 'dìtiě', 'metrô', 'substantivo', '坐地铁吧。', 'Zuò dìtiě ba.', 'Pegue o metrô.', 'Cidade'],
    ['车站', 'chēzhàn', 'estação / parada', 'substantivo', '在下一个车站下车。', 'Zài xià yí gè chēzhàn xià chē.', 'Desça na próxima parada.', 'Cidade'],
    ['地图', 'dìtú', 'mapa', 'substantivo', '看看地图。', 'Kànkan dìtú.', 'Olhe o mapa.', 'Cidade'],
    ['小路', 'xiǎolù', 'caminho / trilha', 'substantivo', '沿着这条小路走。', 'Yánzhe zhè tiáo xiǎolù zǒu.', 'Siga por este caminho.', 'Cidade'],
    ['大门', 'dàmén', 'portão', 'substantivo', '大门锁着。', 'Dàmén suǒ zhe.', 'O portão está trancado.', 'Cidade'],
    ['斑马线', 'bānmǎxiàn', 'faixa de pedestres', 'substantivo', '请走斑马线。', 'Qǐng zǒu bānmǎxiàn.', 'Use a faixa de pedestres.', 'Cidade'],
    ['洗衣', 'xǐyī', 'lavar roupa', 'verbo', '我星期天洗衣。', 'Wǒ xīngqītiān xǐyī.', 'Eu lavo roupa no domingo.', 'Casa e tarefas'],
    ['碗碟', 'wǎndié', 'louça', 'substantivo', '他洗碗碟。', 'Tā xǐ wǎndié.', 'Ele lava a louça.', 'Casa e tarefas'],
    ['扫把', 'sàobǎ', 'vassoura', 'substantivo', '扫把在哪里？', 'Sàobǎ zài nǎlǐ?', 'Onde está a vassoura?', 'Casa e tarefas'],
    ['垃圾', 'lājī', 'lixo', 'substantivo', '请把垃圾拿出去。', 'Qǐng bǎ lājī ná chūqù.', 'Leve o lixo para fora.', 'Casa e tarefas'],
    ['毛巾', 'máojīn', 'toalha', 'substantivo', '毛巾湿了。', 'Máojīn shī le.', 'A toalha está molhada.', 'Casa e tarefas'],
    ['毯子', 'tǎnzi', 'cobertor', 'substantivo', '我还需要一条毯子。', 'Wǒ hái xūyào yì tiáo tǎnzi.', 'Preciso de outro cobertor.', 'Casa e tarefas'],
    ['抽屉', 'chōuti', 'gaveta', 'substantivo', '在抽屉里。', 'Zài chōuti lǐ.', 'Está na gaveta.', 'Casa e tarefas'],
    ['衣柜', 'yīguì', 'guarda-roupa', 'substantivo', '挂在衣柜里。', 'Guà zài yīguì lǐ.', 'Pendure no guarda-roupa.', 'Casa e tarefas'],
    ['水槽', 'shuǐcáo', 'pia', 'substantivo', '水槽堵住了。', 'Shuǐcáo dǔ zhù le.', 'A pia está entupida.', 'Casa e tarefas'],
    ['镜子', 'jìngzi', 'espelho', 'substantivo', '照照镜子。', 'Zhào zhào jìngzi.', 'Olhe no espelho.', 'Casa e tarefas'],
  ],
  B1: [
    ['面试', 'miànshì', 'entrevista de emprego', 'substantivo', '面试很顺利。', 'Miànshì hěn shùnlì.', 'A entrevista correu bem.', 'Trabalho'],
    ['简历', 'jiǎnlì', 'currículo', 'substantivo', '请把简历发给我。', 'Qǐng bǎ jiǎnlì fā gěi wǒ.', 'Me mande seu currículo.', 'Trabalho'],
    ['班次', 'bāncì', 'turno', 'substantivo', '我上夜班次。', 'Wǒ shàng yèbāncì.', 'Eu trabalho no turno da noite.', 'Trabalho'],
    ['加班', 'jiābān', 'fazer hora extra', 'verbo', '她又加班了。', 'Tā yòu jiābān le.', 'Ela fez hora extra de novo.', 'Trabalho'],
    ['实习', 'shíxí', 'estágio', 'substantivo', '他得到了实习机会。', 'Tā dédào le shíxí jīhuì.', 'Ele conseguiu um estágio.', 'Trabalho'],
    ['主管', 'zhǔguǎn', 'supervisor', 'substantivo', '跟你的主管谈谈。', 'Gēn nǐ de zhǔguǎn tántan.', 'Fale com seu supervisor.', 'Trabalho'],
    ['任务', 'rènwù', 'tarefa', 'substantivo', '这个任务要两个小时。', 'Zhège rènwù yào liǎng gè xiǎoshí.', 'Esta tarefa leva duas horas.', 'Trabalho'],
    ['会议', 'huìyì', 'reunião', 'substantivo', '会议取消了。', 'Huìyì qǔxiāo le.', 'A reunião foi cancelada.', 'Trabalho'],
    ['员工', 'yuángōng', 'funcionário', 'substantivo', '员工很友好。', 'Yuángōng hěn yǒuhǎo.', 'Os funcionários são simpáticos.', 'Trabalho'],
    ['合同', 'hétong', 'contrato', 'substantivo', '先读合同。', 'Xiān dú hétong.', 'Leia o contrato primeiro.', 'Trabalho'],
    ['更新', 'gēngxīn', 'atualização', 'substantivo', '请安装更新。', 'Qǐng ānzhuāng gēngxīn.', 'Instale a atualização.', 'Tecnologia'],
    ['密码', 'mìmǎ', 'senha', 'substantivo', '我忘了密码。', 'Wǒ wàng le mìmǎ.', 'Esqueci minha senha.', 'Tecnologia'],
    ['备份', 'bèifèn', 'cópia de segurança', 'substantivo', '先做个备份。', 'Xiān zuò gè bèifèn.', 'Faça uma cópia de segurança antes.', 'Tecnologia'],
    ['设备', 'shèbèi', 'dispositivo', 'substantivo', '这个设备很快。', 'Zhège shèbèi hěn kuài.', 'Este dispositivo é rápido.', 'Tecnologia'],
    ['屏幕', 'píngmù', 'tela', 'substantivo', '屏幕碎了。', 'Píngmù suì le.', 'A tela está quebrada.', 'Tecnologia'],
    ['下载', 'xiàzài', 'baixar', 'verbo', '请现在下载文件。', 'Qǐng xiànzài xiàzài wénjiàn.', 'Baixe o arquivo agora.', 'Tecnologia'],
    ['网络', 'wǎngluò', 'rede', 'substantivo', '网络断了。', 'Wǎngluò duàn le.', 'A rede caiu.', 'Tecnologia'],
    ['浏览器', 'liúlǎnqì', 'navegador', 'substantivo', '在浏览器里打开。', 'Zài liúlǎnqì lǐ dǎkāi.', 'Abra no navegador.', 'Tecnologia'],
    ['文件夹', 'wénjiànjiā', 'pasta', 'substantivo', '存在这个文件夹里。', 'Cún zài zhège wénjiànjiā lǐ.', 'Salve nesta pasta.', 'Tecnologia'],
    ['崩溃', 'bēngkuì', 'travar (sistema)', 'verbo', '应用又崩溃了。', 'Yìngyòng yòu bēngkuì le.', 'O aplicativo travou de novo.', 'Tecnologia'],
    ['回收', 'huíshōu', 'reciclar', 'verbo', '我们这里回收塑料。', 'Wǒmen zhèlǐ huíshōu sùliào.', 'Aqui nós reciclamos plástico.', 'Meio ambiente'],
    ['污染', 'wūrǎn', 'poluição', 'substantivo', '污染变严重了。', 'Wūrǎn biàn yánzhòng le.', 'A poluição piorou.', 'Meio ambiente'],
    ['废物', 'fèiwù', 'resíduo', 'substantivo', '食物废物是个问题。', 'Shíwù fèiwù shì gè wèntí.', 'O resíduo alimentar é um problema.', 'Meio ambiente'],
    ['气候', 'qìhòu', 'clima', 'substantivo', '气候正在变化。', 'Qìhòu zhèngzài biànhuà.', 'O clima está mudando.', 'Meio ambiente'],
    ['能源', 'néngyuán', 'energia', 'substantivo', '太阳能源更便宜了。', 'Tàiyáng néngyuán gèng piányi le.', 'A energia solar ficou mais barata.', 'Meio ambiente'],
    ['森林', 'sēnlín', 'floresta', 'substantivo', '这片森林受保护。', 'Zhè piàn sēnlín shòu bǎohù.', 'Esta floresta é protegida.', 'Meio ambiente'],
    ['物种', 'wùzhǒng', 'espécie', 'substantivo', '这个物种很稀有。', 'Zhège wùzhǒng hěn xīyǒu.', 'Esta espécie é rara.', 'Meio ambiente'],
    ['干旱', 'gānhàn', 'seca', 'substantivo', '干旱持续了几个月。', 'Gānhàn chíxù le jǐ gè yuè.', 'A seca durou meses.', 'Meio ambiente'],
    ['洪水', 'hóngshuǐ', 'enchente', 'substantivo', '洪水冲坏了路。', 'Hóngshuǐ chōng huài le lù.', 'A enchente danificou a estrada.', 'Meio ambiente'],
    ['排放', 'páifàng', 'emissão / descarga', 'substantivo', '排放进了河里。', 'Páifàng jìn le hé lǐ.', 'A descarga foi para o rio.', 'Meio ambiente'],
    ['裁判', 'cáipàn', 'árbitro', 'substantivo', '裁判中止了比赛。', 'Cáipàn zhōngzhǐ le bǐsài.', 'O árbitro parou o jogo.', 'Esportes'],
    ['锦标赛', 'jǐnbiāosài', 'torneio', 'substantivo', '她赢了锦标赛。', 'Tā yíng le jǐnbiāosài.', 'Ela venceu o torneio.', 'Esportes'],
    ['对手', 'duìshǒu', 'adversário', 'substantivo', '他的对手更快。', 'Tā de duìshǒu gèng kuài.', 'O adversário dele era mais rápido.', 'Esportes'],
    ['队友', 'duìyǒu', 'companheiro de equipe', 'substantivo', '我的队友进球了。', 'Wǒ de duìyǒu jìnqiú le.', 'Meu companheiro de equipe marcou.', 'Esportes'],
    ['教练', 'jiàoliàn', 'treinador', 'substantivo', '教练很生气。', 'Jiàoliàn hěn shēngqì.', 'O treinador ficou bravo.', 'Esportes'],
    ['比分', 'bǐfēn', 'placar', 'substantivo', '比分是多少？', 'Bǐfēn shì duōshao?', 'Qual é o placar?', 'Esportes'],
    ['比赛', 'bǐsài', 'partida / competição', 'substantivo', '比赛八点开始。', 'Bǐsài bā diǎn kāishǐ.', 'A partida começa às oito.', 'Esportes'],
    ['训练', 'xùnliàn', 'treino', 'substantivo', '每天早上训练。', 'Měitiān zǎoshang xùnliàn.', 'O treino é toda manhã.', 'Esportes'],
    ['耐力', 'nàilì', 'resistência física', 'substantivo', '他的耐力很好。', 'Tā de nàilì hěn hǎo.', 'Ele tem muita resistência.', 'Esportes'],
    ['冠军赛', 'guànjūnsài', 'campeonato', 'substantivo', '他们输了冠军赛。', 'Tāmen shū le guànjūnsài.', 'Eles perderam o campeonato.', 'Esportes'],
    ['争吵', 'zhēngchǎo', 'brigar / discutir', 'verbo', '他们为钱争吵。', 'Tāmen wèi qián zhēngchǎo.', 'Eles brigam por dinheiro.', 'Relacionamentos'],
    ['道歉', 'dàoqiàn', 'pedir desculpas', 'verbo', '他很快道歉了。', 'Tā hěn kuài dàoqiàn le.', 'Ele pediu desculpas rápido.', 'Relacionamentos'],
    ['信任', 'xìnrèn', 'confiança', 'substantivo', '信任需要时间。', 'Xìnrèn xūyào shíjiān.', 'Confiança leva tempo.', 'Relacionamentos'],
    ['嫉妒', 'jídù', 'ciúme', 'substantivo', '她容易嫉妒。', 'Tā róngyì jídù.', 'Ela fica com ciúmes fácil.', 'Relacionamentos'],
    ['忠诚', 'zhōngchéng', 'lealdade', 'substantivo', '他很忠诚。', 'Tā hěn zhōngchéng.', 'Ele é muito leal.', 'Relacionamentos'],
    ['八卦', 'bāguà', 'fofoca', 'substantivo', '我讨厌办公室八卦。', 'Wǒ tǎoyàn bàngōngshì bāguà.', 'Odeio fofoca de escritório.', 'Relacionamentos'],
    ['建议', 'jiànyì', 'conselho / sugestão', 'substantivo', '那是个好建议。', 'Nà shì gè hǎo jiànyì.', 'Aquilo foi um bom conselho.', 'Relacionamentos'],
    ['帮忙', 'bāngmáng', 'ajudar / favor', 'verbo', '能帮个忙吗？', 'Néng bāng gè máng ma?', 'Pode me fazer um favor?', 'Relacionamentos'],
    ['不和', 'bùhé', 'desavença', 'substantivo', '他们有点不和。', 'Tāmen yǒudiǎn bùhé.', 'Eles tiveram uma desavença.', 'Relacionamentos'],
    ['妥协', 'tuǒxié', 'acordo mútuo', 'substantivo', '我们达成了妥协。', 'Wǒmen dáchéng le tuǒxié.', 'Chegamos a um acordo.', 'Relacionamentos'],
    ['预算', 'yùsuàn', 'orçamento', 'substantivo', '请遵守预算。', 'Qǐng zūnshǒu yùsuàn.', 'Siga o orçamento.', 'Dinheiro'],
    ['储蓄', 'chǔxù', 'poupança', 'substantivo', '她用了储蓄。', 'Tā yòng le chǔxù.', 'Ela usou a poupança.', 'Dinheiro'],
    ['贷款', 'dàikuǎn', 'empréstimo', 'substantivo', '他申请了贷款。', 'Tā shēnqǐng le dàikuǎn.', 'Ele fez um empréstimo.', 'Dinheiro'],
    ['债务', 'zhàiwù', 'dívida', 'substantivo', '他们还清了债务。', 'Tāmen huánqīng le zhàiwù.', 'Eles quitaram a dívida.', 'Dinheiro'],
    ['开支', 'kāizhī', 'despesa', 'substantivo', '房租是最大的开支。', 'Fángzū shì zuì dà de kāizhī.', 'O aluguel é a maior despesa.', 'Dinheiro'],
    ['利息', 'lìxī', 'juros', 'substantivo', '利息太高了。', 'Lìxī tài gāo le.', 'Os juros estão altos demais.', 'Dinheiro'],
    ['投资', 'tóuzī', 'investir', 'verbo', '他们投资房地产。', 'Tāmen tóuzī fángdìchǎn.', 'Eles investem em imóveis.', 'Dinheiro'],
    ['房贷', 'fángdài', 'financiamento imobiliário', 'substantivo', '我们有房贷。', 'Wǒmen yǒu fángdài.', 'Nós temos um financiamento.', 'Dinheiro'],
    ['保险', 'bǎoxiǎn', 'seguro', 'substantivo', '车险很贵。', 'Chēxiǎn hěn guì.', 'O seguro do carro é caro.', 'Dinheiro'],
    ['最低工资', 'zuìdī gōngzī', 'salário mínimo', 'substantivo', '最低工资涨了。', 'Zuìdī gōngzī zhǎng le.', 'O salário mínimo subiu.', 'Dinheiro'],
  ],
  B2: [
    ['竞选', 'jìngxuǎn', 'campanha eleitoral', 'substantivo', '竞选持续了六周。', 'Jìngxuǎn chíxù le liù zhōu.', 'A campanha durou seis semanas.', 'Política'],
    ['选民', 'xuǎnmín', 'eleitor', 'substantivo', '选民分裂了。', 'Xuǎnmín fēnliè le.', 'O eleitorado está dividido.', 'Política'],
    ['立法', 'lìfǎ', 'legislação', 'substantivo', '新的立法通过了。', 'Xīn de lìfǎ tōngguò le.', 'Uma nova legislação foi aprovada.', 'Política'],
    ['游说', 'yóushuì', 'lobby', 'substantivo', '游说改变了法案。', 'Yóushuì gǎibiàn le fǎ’àn.', 'O lobby mudou o projeto de lei.', 'Política'],
    ['腐败', 'fǔbài', 'corrupção', 'substantivo', '腐败破坏信任。', 'Fǔbài pòhuài xìnrèn.', 'A corrupção destrói a confiança.', 'Política'],
    ['公投', 'gōngtóu', 'referendo', 'substantivo', '他们举行了公投。', 'Tāmen jǔxíng le gōngtóu.', 'Eles realizaram um referendo.', 'Política'],
    ['联合政府', 'liánhé zhèngfǔ', 'governo de coalizão', 'substantivo', '联合政府垮了。', 'Liánhé zhèngfǔ kuǎ le.', 'O governo de coalizão caiu.', 'Política'],
    ['选票', 'xuǎnpiào', 'cédula de votação', 'substantivo', '选票是保密的。', 'Xuǎnpiào shì bǎomì de.', 'A cédula é secreta.', 'Política'],
    ['选区', 'xuǎnqū', 'distrito eleitoral', 'substantivo', '她访问了选区。', 'Tā fǎngwèn le xuǎnqū.', 'Ela visitou seu distrito eleitoral.', 'Política'],
    ['授权', 'shòuquán', 'mandato / autorização', 'substantivo', '他们获得了授权。', 'Tāmen huòdé le shòuquán.', 'Eles receberam o mandato.', 'Política'],
    ['通货膨胀', 'tōnghuò péngzhàng', 'inflação', 'substantivo', '通货膨胀放缓了。', 'Tōnghuò péngzhàng fànghuǎn le.', 'A inflação desacelerou.', 'Economia'],
    ['衰退', 'shuāituì', 'recessão', 'substantivo', '国家进入衰退。', 'Guójiā jìnrù shuāituì.', 'O país entrou em recessão.', 'Economia'],
    ['补贴', 'bǔtiē', 'subsídio', 'substantivo', '补贴被削减了。', 'Bǔtiē bèi xuējiǎn le.', 'O subsídio foi cortado.', 'Economia'],
    ['关税', 'guānshuì', 'tarifa alfandegária', 'substantivo', '他们征收了关税。', 'Tāmen zhēngshōu le guānshuì.', 'Impuseram uma tarifa.', 'Economia'],
    ['盈余', 'yíngyú', 'superávit', 'substantivo', '预算出现盈余。', 'Yùsuàn chūxiàn yíngyú.', 'O orçamento apresenta superávit.', 'Economia'],
    ['赤字', 'chìzì', 'déficit', 'substantivo', '赤字持续扩大。', 'Chìzì chíxù kuòdà.', 'O déficit continua crescendo.', 'Economia'],
    ['供给', 'gōngjǐ', 'oferta', 'substantivo', '供给跟不上需求。', 'Gōngjǐ gēn bú shàng xūqiú.', 'A oferta não acompanha a procura.', 'Economia'],
    ['需求', 'xūqiú', 'procura / demanda', 'substantivo', '需求急剧下降。', 'Xūqiú jíjù xiàjiàng.', 'A procura caiu bruscamente.', 'Economia'],
    ['垄断', 'lǒngduàn', 'monopólio', 'substantivo', '他们几乎垄断了市场。', 'Tāmen jīhū lǒngduàn le shìchǎng.', 'Eles quase monopolizam o mercado.', 'Economia'],
    ['紧缩', 'jǐnsuō', 'austeridade', 'substantivo', '紧缩影响了公共服务。', 'Jǐnsuō yǐngxiǎng le gōnggòng fúwù.', 'A austeridade atingiu os serviços públicos.', 'Economia'],
    ['实验', 'shíyàn', 'experimento', 'substantivo', '实验失败了两次。', 'Shíyàn shībài le liǎng cì.', 'O experimento falhou duas vezes.', 'Ciência'],
    ['证据', 'zhèngjù', 'evidência', 'substantivo', '有强有力的证据。', 'Yǒu qiáng yǒulì de zhèngjù.', 'Há evidências fortes.', 'Ciência'],
    ['样本', 'yàngběn', 'amostra', 'substantivo', '样本太小了。', 'Yàngběn tài xiǎo le.', 'A amostra era pequena demais.', 'Ciência'],
    ['实验室', 'shíyànshì', 'laboratório', 'substantivo', '她在实验室工作。', 'Tā zài shíyànshì gōngzuò.', 'Ela trabalha num laboratório.', 'Ciência'],
    ['分子', 'fēnzǐ', 'molécula', 'substantivo', '水是简单的分子。', 'Shuǐ shì jiǎndān de fēnzǐ.', 'A água é uma molécula simples.', 'Ciência'],
    ['基因组', 'jīyīnzǔ', 'genoma', 'substantivo', '他们绘制了基因组。', 'Tāmen huìzhì le jīyīnzǔ.', 'Eles mapearam o genoma.', 'Ciência'],
    ['疫苗', 'yìmiáo', 'vacina', 'substantivo', '疫苗效果很好。', 'Yìmiáo xiàoguǒ hěn hǎo.', 'A vacina funciona bem.', 'Ciência'],
    ['微生物', 'wēishēngwù', 'micróbio', 'substantivo', '这种微生物无害。', 'Zhè zhǒng wēishēngwù wúhài.', 'Este micróbio é inofensivo.', 'Ciência'],
    ['辐射', 'fúshè', 'radiação', 'substantivo', '辐射水平正常。', 'Fúshè shuǐpíng zhèngcháng.', 'Os níveis de radiação estão normais.', 'Ciência'],
    ['望远镜', 'wàngyuǎnjìng', 'telescópio', 'substantivo', '望远镜发现了一颗行星。', 'Wàngyuǎnjìng fāxiàn le yì kē xíngxīng.', 'O telescópio encontrou um planeta.', 'Ciência'],
    ['标题', 'biāotí', 'manchete / título', 'substantivo', '标题有误导性。', 'Biāotí yǒu wùdǎo xìng.', 'A manchete induzia ao erro.', 'Mídia'],
    ['报道', 'bàodào', 'cobertura jornalística', 'substantivo', '报道有偏向。', 'Bàodào yǒu piānxiàng.', 'A cobertura foi tendenciosa.', 'Mídia'],
    ['审查', 'shěnchá', 'censura / exame', 'substantivo', '去年审查加强了。', 'Qùnián shěnchá jiāqiáng le.', 'A censura aumentou no ano passado.', 'Mídia'],
    ['宣传', 'xuānchuán', 'propaganda ideológica', 'substantivo', '这纯粹是宣传。', 'Zhè chúncuì shì xuānchuán.', 'Isso é pura propaganda.', 'Mídia'],
    ['广播', 'guǎngbō', 'transmissão', 'substantivo', '广播覆盖了数百万人。', 'Guǎngbō fùgài le shù bǎi wàn rén.', 'A transmissão alcançou milhões.', 'Mídia'],
    ['记者', 'jìzhě', 'jornalista', 'substantivo', '记者核实了消息。', 'Jìzhě héshí le xiāoxi.', 'A jornalista checou a informação.', 'Mídia'],
    ['社论', 'shèlùn', 'editorial', 'substantivo', '社论批评了这个计划。', 'Shèlùn pīpíng le zhège jìhuà.', 'O editorial criticou o plano.', 'Mídia'],
    ['小报', 'xiǎobào', 'tabloide', 'substantivo', '别相信那份小报。', 'Bié xiāngxìn nà fèn xiǎobào.', 'Não acredite naquele tabloide.', 'Mídia'],
    ['观众', 'guānzhòng', 'público / plateia', 'substantivo', '观众很冷淡。', 'Guānzhòng hěn lěngdàn.', 'A plateia estava fria.', 'Mídia'],
    ['来源', 'láiyuán', 'fonte', 'substantivo', '请说明来源。', 'Qǐng shuōmíng láiyuán.', 'Indique sua fonte.', 'Mídia'],
    ['同理心', 'tónglǐxīn', 'empatia', 'substantivo', '同理心可以培养。', 'Tónglǐxīn kěyǐ péiyǎng.', 'A empatia pode ser cultivada.', 'Psicologia'],
    ['焦虑', 'jiāolǜ', 'ansiedade', 'substantivo', '焦虑影响睡眠。', 'Jiāolǜ yǐngxiǎng shuìmián.', 'A ansiedade afeta o sono.', 'Psicologia'],
    ['创伤', 'chuāngshāng', 'trauma', 'substantivo', '创伤持续了多年。', 'Chuāngshāng chíxù le duō nián.', 'O trauma durou anos.', 'Psicologia'],
    ['动力', 'dònglì', 'motivação / impulso', 'substantivo', '没有成果就没有动力。', 'Méiyǒu chéngguǒ jiù méiyǒu dònglì.', 'Sem resultados não há motivação.', 'Psicologia'],
    ['感知', 'gǎnzhī', 'percepção', 'substantivo', '感知塑造记忆。', 'Gǎnzhī sùzào jìyì.', 'A percepção molda a memória.', 'Psicologia'],
    ['行为', 'xíngwéi', 'comportamento', 'substantivo', '他的行为突然变了。', 'Tā de xíngwéi tūrán biàn le.', 'O comportamento dele mudou de repente.', 'Psicologia'],
    ['本能', 'běnnéng', 'instinto', 'substantivo', '这里要相信本能。', 'Zhèlǐ yào xiāngxìn běnnéng.', 'Aqui confie no instinto.', 'Psicologia'],
    ['心情', 'xīnqíng', 'humor / estado de espírito', 'substantivo', '她的心情好多了。', 'Tā de xīnqíng hǎo duō le.', 'O humor dela melhorou.', 'Psicologia'],
    ['自尊', 'zìzūn', 'autoestima', 'substantivo', '自尊低很常见。', 'Zìzūn dī hěn chángjiàn.', 'Baixa autoestima é comum.', 'Psicologia'],
    ['怨恨', 'yuànhèn', 'ressentimento', 'substantivo', '怨恨慢慢积累。', 'Yuànhèn mànman jīlěi.', 'O ressentimento cresceu devagar.', 'Psicologia'],
    ['诉讼', 'sùsòng', 'processo judicial', 'substantivo', '他们提起了诉讼。', 'Tāmen tíqǐ le sùsòng.', 'Eles entraram com um processo.', 'Direito'],
    ['裁决', 'cáijué', 'veredicto', 'substantivo', '裁决让所有人意外。', 'Cáijué ràng suǒyǒu rén yìwài.', 'O veredicto surpreendeu todos.', 'Direito'],
    ['证词', 'zhèngcí', 'depoimento', 'substantivo', '她的证词是决定性的。', 'Tā de zhèngcí shì juédìngxìng de.', 'O depoimento dela foi decisivo.', 'Direito'],
    ['证人', 'zhèngrén', 'testemunha', 'substantivo', '证人改了说法。', 'Zhèngrén gǎi le shuōfǎ.', 'A testemunha mudou a versão.', 'Direito'],
    ['被告', 'bèigào', 'réu', 'substantivo', '被告保持沉默。', 'Bèigào bǎochí chénmò.', 'O réu permaneceu calado.', 'Direito'],
    ['律师', 'lǜshī', 'advogado', 'substantivo', '给你的律师打电话。', 'Gěi nǐ de lǜshī dǎ diànhuà.', 'Ligue para seu advogado.', 'Direito'],
    ['辩护', 'biànhù', 'defesa (jurídica)', 'substantivo', '辩护很有说服力。', 'Biànhù hěn yǒu shuōfúlì.', 'A defesa foi convincente.', 'Direito'],
    ['上诉', 'shàngsù', 'recurso judicial', 'substantivo', '他们输了上诉。', 'Tāmen shū le shàngsù.', 'Eles perderam o recurso.', 'Direito'],
    ['抚养权', 'fǔyǎngquán', 'guarda de filhos', 'substantivo', '她获得了抚养权。', 'Tā huòdé le fǔyǎngquán.', 'Ela ganhou a guarda.', 'Direito'],
    ['法规', 'fǎguī', 'regulamento / lei', 'substantivo', '这项法规过时了。', 'Zhè xiàng fǎguī guòshí le.', 'Este regulamento está ultrapassado.', 'Direito'],
  ],
  C1: [
    ['假设', 'jiǎshè', 'hipótese', 'substantivo', '假设没有得到支持。', 'Jiǎshè méiyǒu dédào zhīchí.', 'A hipótese não se sustentou.', 'Pesquisa acadêmica'],
    ['方法论', 'fāngfǎlùn', 'metodologia', 'substantivo', '请清楚说明方法论。', 'Qǐng qīngchu shuōmíng fāngfǎlùn.', 'Descreva sua metodologia com clareza.', 'Pesquisa acadêmica'],
    ['相关性', 'xiāngguānxìng', 'correlação', 'substantivo', '相关性不是因果。', 'Xiāngguānxìng bú shì yīnguǒ.', 'Correlação não é causalidade.', 'Pesquisa acadêmica'],
    ['变量', 'biànliàng', 'variável', 'substantivo', '请控制那个变量。', 'Qǐng kòngzhì nàge biànliàng.', 'Controle essa variável.', 'Pesquisa acadêmica'],
    ['实证的', 'shízhèng de', 'empírico', 'adjetivo', '我们需要实证的支持。', 'Wǒmen xūyào shízhèng de zhīchí.', 'Precisamos de respaldo empírico.', 'Pesquisa acadêmica'],
    ['同行评审', 'tóngháng píngshěn', 'revisão por pares', 'substantivo', '同行评审发现了错误。', 'Tóngháng píngshěn fāxiàn le cuòwù.', 'A revisão por pares pegou o erro.', 'Pesquisa acadêmica'],
    ['纵向研究', 'zòngxiàng yánjiū', 'estudo longitudinal', 'substantivo', '那是一项纵向研究。', 'Nà shì yí xiàng zòngxiàng yánjiū.', 'Foi um estudo longitudinal.', 'Pesquisa acadêmica'],
    ['重复验证', 'chóngfù yànzhèng', 'replicação', 'substantivo', '重复验证失败了两次。', 'Chóngfù yànzhèng shībài le liǎng cì.', 'A replicação falhou duas vezes.', 'Pesquisa acadêmica'],
    ['推论', 'tuīlùn', 'inferência', 'substantivo', '那个推论太宽泛了。', 'Nàge tuīlùn tài kuānfàn le.', 'Essa inferência é ampla demais.', 'Pesquisa acadêmica'],
    ['范式', 'fànshì', 'paradigma', 'substantivo', '范式慢慢改变了。', 'Fànshì mànman gǎibiàn le.', 'O paradigma mudou devagar.', 'Pesquisa acadêmica'],
    ['利益相关者', 'lìyì xiāngguān zhě', 'parte interessada', 'substantivo', '请咨询每一位利益相关者。', 'Qǐng zīxún měi yí wèi lìyì xiāngguān zhě.', 'Consulte cada parte interessada.', 'Negócios'],
    ['收购', 'shōugòu', 'aquisição', 'substantivo', '收购在五月完成。', 'Shōugòu zài wǔyuè wánchéng.', 'A aquisição foi concluída em maio.', 'Negócios'],
    ['合并', 'hébìng', 'fusão', 'substantivo', '合并遇到了阻力。', 'Hébìng yùdào le zǔlì.', 'A fusão enfrentou resistência.', 'Negócios'],
    ['营收', 'yíngshōu', 'faturamento', 'substantivo', '营收增长了百分之十二。', 'Yíngshōu zēngzhǎng le bǎi fēn zhī shí’èr.', 'O faturamento cresceu doze por cento.', 'Negócios'],
    ['赔偿责任', 'péicháng zérèn', 'responsabilidade indenizatória', 'substantivo', '那条款产生赔偿责任。', 'Nà tiáokuǎn chǎnshēng péicháng zérèn.', 'Aquela cláusula gera responsabilidade indenizatória.', 'Negócios'],
    ['仲裁', 'zhòngcái', 'arbitragem', 'substantivo', '他们进入了仲裁。', 'Tāmen jìnrù le zhòngcái.', 'Eles foram para a arbitragem.', 'Negócios'],
    ['基准', 'jīzhǔn', 'referência comparativa', 'substantivo', '设定一个现实的基准。', 'Shèdìng yí gè xiànshí de jīzhǔn.', 'Defina uma referência realista.', 'Negócios'],
    ['可行性', 'kěxíngxìng', 'viabilidade', 'substantivo', '先研究可行性。', 'Xiān yánjiū kěxíngxìng.', 'Estude a viabilidade primeiro.', 'Negócios'],
    ['多元化', 'duōyuánhuà', 'diversificação', 'substantivo', '多元化降低了风险。', 'Duōyuánhuà jiàngdī le fēngxiǎn.', 'A diversificação reduziu o risco.', 'Negócios'],
    ['采购', 'cǎigòu', 'aquisição institucional', 'substantivo', '采购要花几个月。', 'Cǎigòu yào huā jǐ gè yuè.', 'O processo de compras leva meses.', 'Negócios'],
    ['本体论', 'běntǐlùn', 'ontologia', 'substantivo', '这是本体论的问题。', 'Zhè shì běntǐlùn de wèntí.', 'Isso é uma questão de ontologia.', 'Filosofia'],
    ['认识论', 'rènshílùn', 'epistemologia', 'substantivo', '认识论追问我们如何知道。', 'Rènshílùn zhuīwèn wǒmen rúhé zhīdào.', 'A epistemologia pergunta como sabemos.', 'Filosofia'],
    ['决定论', 'juédìnglùn', 'determinismo', 'substantivo', '决定论否认自由意志。', 'Juédìnglùn fǒurèn zìyóu yìzhì.', 'O determinismo nega o livre-arbítrio.', 'Filosofia'],
    ['辩证法', 'biànzhèngfǎ', 'dialética', 'substantivo', '他用辩证法论证。', 'Tā yòng biànzhèngfǎ lùnzhèng.', 'Ele argumentou pela dialética.', 'Filosofia'],
    ['形而上学', 'xíng’érshàngxué', 'metafísica', 'substantivo', '形而上学难以证明。', 'Xíng’érshàngxué nányǐ zhèngmíng.', 'A metafísica resiste à comprovação.', 'Filosofia'],
    ['存在主义的', 'cúnzài zhǔyì de', 'existencial', 'adjetivo', '这成了存在主义的威胁。', 'Zhè chéng le cúnzài zhǔyì de wēixié.', 'Virou uma ameaça existencial.', 'Filosofia'],
    ['目的论', 'mùdìlùn', 'teleologia', 'substantivo', '目的论用目的来解释。', 'Mùdìlùn yòng mùdì lái jiěshì.', 'A teleologia explica pela finalidade.', 'Filosofia'],
    ['虚无主义', 'xūwú zhǔyì', 'niilismo', 'substantivo', '虚无主义否认内在意义。', 'Xūwú zhǔyì fǒurèn nèizài yìyì.', 'O niilismo nega sentido inerente.', 'Filosofia'],
    ['公理', 'gōnglǐ', 'axioma', 'substantivo', '从共同的公理出发。', 'Cóng gòngtóng de gōnglǐ chūfā.', 'Parta de um axioma comum.', 'Filosofia'],
    ['三段论', 'sānduànlùn', 'silogismo', 'substantivo', '这个三段论无效。', 'Zhège sānduànlùn wúxiào.', 'Esse silogismo é inválido.', 'Filosofia'],
    ['阶层化', 'jiēcéng huà', 'estratificação', 'substantivo', '社会阶层化仍在持续。', 'Shèhuì jiēcéng huà réng zài chíxù.', 'A estratificação social persiste.', 'Sociologia'],
    ['同化', 'tónghuà', 'assimilação', 'substantivo', '当时要求他们同化。', 'Dāngshí yāoqiú tāmen tónghuà.', 'Esperava-se deles a assimilação.', 'Sociologia'],
    ['人口结构的', 'rénkǒu jiégòu de', 'demográfico', 'adjetivo', '人口结构的变化很明显。', 'Rénkǒu jiégòu de biànhuà hěn míngxiǎn.', 'A mudança demográfica é clara.', 'Sociologia'],
    ['城市化', 'chéngshìhuà', 'urbanização', 'substantivo', '城市化加快了。', 'Chéngshìhuà jiākuài le.', 'A urbanização acelerou.', 'Sociologia'],
    ['世代群体', 'shìdài qúntǐ', 'coorte geracional', 'substantivo', '那个世代群体收入更低。', 'Nàge shìdài qúntǐ shōurù gèng dī.', 'Essa geração ganha menos.', 'Sociologia'],
    ['社会规范', 'shèhuì guīfàn', 'norma social', 'substantivo', '社会规范悄悄改变了。', 'Shèhuì guīfàn qiāoqiāo gǎibiàn le.', 'A norma social mudou silenciosamente.', 'Sociologia'],
    ['越轨', 'yuèguǐ', 'desvio (social)', 'substantivo', '越轨由语境定义。', 'Yuèguǐ yóu yǔjìng dìngyì.', 'O desvio é definido pelo contexto.', 'Sociologia'],
    ['社会流动', 'shèhuì liúdòng', 'mobilidade social', 'substantivo', '社会流动停滞了。', 'Shèhuì liúdòng tíngzhì le.', 'A mobilidade social estagnou.', 'Sociologia'],
    ['血缘', 'xuèyuán', 'parentesco consanguíneo', 'substantivo', '血缘关系依然牢固。', 'Xuèyuán guānxì yīrán láogù.', 'Os laços de parentesco seguem fortes.', 'Sociologia'],
    ['世俗化', 'shìsúhuà', 'secularização', 'substantivo', '世俗化因地区而异。', 'Shìsúhuà yīn dìqū ér yì.', 'A secularização varia por região.', 'Sociologia'],
    ['预后', 'yùhòu', 'prognóstico', 'substantivo', '预后谨慎乐观。', 'Yùhòu jǐnshèn lèguān.', 'O prognóstico é cautelosamente bom.', 'Medicina'],
    ['慢性的', 'mànxìng de', 'crônico', 'adjetivo', '这成了慢性的疾病。', 'Zhè chéng le mànxìng de jíbìng.', 'Virou uma doença crônica.', 'Medicina'],
    ['良性的', 'liángxìng de', 'benigno', 'adjetivo', '肿块是良性的。', 'Zhǒngkuài shì liángxìng de.', 'O nódulo era benigno.', 'Medicina'],
    ['恶性的', 'èxìng de', 'maligno', 'adjetivo', '肿瘤是恶性的。', 'Zhǒngliú shì èxìng de.', 'O tumor era maligno.', 'Medicina'],
    ['缓解期', 'huǎnjiěqī', 'período de remissão', 'substantivo', '她已缓解期一年了。', 'Tā yǐ huǎnjiěqī yì nián le.', 'Ela está em remissão há um ano.', 'Medicina'],
    ['病理', 'bìnglǐ', 'patologia', 'substantivo', '病理报告到了。', 'Bìnglǐ bàogào dào le.', 'O laudo de patologia chegou.', 'Medicina'],
    ['免疫力', 'miǎnyìlì', 'imunidade', 'substantivo', '免疫力会随时间减弱。', 'Miǎnyìlì huì suí shíjiān jiǎnruò.', 'A imunidade diminui com o tempo.', 'Medicina'],
    ['剂量', 'jìliàng', 'dosagem', 'substantivo', '请谨慎调整剂量。', 'Qǐng jǐnshèn tiáozhěng jìliàng.', 'Ajuste a dosagem com cuidado.', 'Medicina'],
    ['切口', 'qiēkǒu', 'incisão', 'substantivo', '切口愈合得很好。', 'Qiēkǒu yùhé de hěn hǎo.', 'A incisão cicatrizou bem.', 'Medicina'],
    ['复发', 'fùfā', 'recaída', 'substantivo', '复发仍有可能。', 'Fùfā réng yǒu kěnéng.', 'Uma recaída ainda é possível.', 'Medicina'],
    ['修辞', 'xiūcí', 'retórica', 'substantivo', '修辞超过了政策。', 'Xiūcí chāoguò le zhèngcè.', 'A retórica passou à frente da política.', 'Retórica'],
    ['说服', 'shuōfú', 'persuadir', 'verbo', '说服胜过强迫。', 'Shuōfú shèngguò qiǎngpò.', 'A persuasão vence a coerção.', 'Retórica'],
    ['轶事', 'yìshì', 'anedota', 'substantivo', '轶事不是数据。', 'Yìshì bú shì shùjù.', 'Uma anedota não é dado.', 'Retórica'],
    ['类比', 'lèibǐ', 'analogia', 'substantivo', '这里类比不成立。', 'Zhèlǐ lèibǐ bù chénglì.', 'A analogia falha aqui.', 'Retórica'],
    ['反驳', 'fǎnbó', 'refutação', 'substantivo', '他的反驳很精彩。', 'Tā de fǎnbó hěn jīngcǎi.', 'A refutação dele foi elegante.', 'Retórica'],
    ['内涵', 'nèihán', 'conotação', 'substantivo', '那个词带有内涵。', 'Nàge cí dàiyǒu nèihán.', 'Aquela palavra carrega uma conotação.', 'Retórica'],
    ['回应', 'huíyìng', 'réplica / resposta', 'substantivo', '她准备了回应。', 'Tā zhǔnbèi le huíyìng.', 'Ela preparou uma réplica.', 'Retórica'],
    ['雄辩', 'xióngbiàn', 'eloquência', 'substantivo', '雄辩掩盖不了弱证据。', 'Xióngbiàn yǎngài bùliǎo ruò zhèngjù.', 'A eloquência não esconde evidência fraca.', 'Retórica'],
    ['公共话语', 'gōnggòng huàyǔ', 'discurso público', 'substantivo', '公共话语粗鄙化了。', 'Gōnggòng huàyǔ cūbǐ huà le.', 'O discurso público se degradou.', 'Retórica'],
    ['离题', 'lítí', 'digressão', 'substantivo', '请原谅我的离题。', 'Qǐng yuánliàng wǒ de lítí.', 'Perdoe a digressão.', 'Retórica'],
  ],
  C2: [
    ['挽歌式的', 'wǎngē shì de', 'elegíaco', 'adjetivo', '这部小说有挽歌式的语调。', 'Zhè bù xiǎoshuō yǒu wǎngē shì de yǔdiào.', 'Este romance tem um tom elegíaco.', 'Registro literário'],
    ['阴郁的', 'yīnyù de', 'sombrio / lúgubre', 'adjetivo', '他用阴郁的声音说话。', 'Tā yòng yīnyù de shēngyīn shuōhuà.', 'Ele falou com uma voz lúgubre.', 'Registro literário'],
    ['田园般的', 'tiányuán bān de', 'idílico', 'adjetivo', '那是田园般的日子。', 'Nà shì tiányuán bān de rìzi.', 'Eram dias idílicos.', 'Registro literário'],
    ['悦耳的', 'yuè’ěr de', 'melodioso', 'adjetivo', '她悦耳的朗读打动了全场。', 'Tā yuè’ěr de lǎngdú dǎdòng le quánchǎng.', 'A leitura melodiosa dela comoveu a sala.', 'Registro literário'],
    ['哀怨的', 'āiyuàn de', 'lamentoso', 'adjetivo', '哀怨的旋律传来。', 'Āiyuàn de xuánlǜ chuán lái.', 'Uma melodia lamentosa soou.', 'Registro literário'],
    ['灿烂的', 'cànlàn de', 'resplandecente', 'adjetivo', '她有灿烂的经历。', 'Tā yǒu cànlàn de jīnglì.', 'Ela tem uma trajetória resplandecente.', 'Registro literário'],
    ['简朴的', 'jiǎnpǔ de', 'austero / despojado', 'adjetivo', '文风简朴而准确。', 'Wénfēng jiǎnpǔ ér zhǔnquè.', 'O estilo é austero e exato.', 'Registro literário'],
    ['慵懒的', 'yōnglǎn de', 'lânguido', 'adjetivo', '那是个慵懒的下午。', 'Nà shì gè yōnglǎn de xiàwǔ.', 'Foi uma tarde lânguida.', 'Registro literário'],
    ['空灵的', 'kōnglíng de', 'etéreo', 'adjetivo', '光线几乎是空灵的。', 'Guāngxiàn jīhū shì kōnglíng de.', 'A luz era quase etérea.', 'Registro literário'],
    ['洪亮的', 'hóngliàng de', 'sonoro', 'adjetivo', '他洪亮的笑声传遍大厅。', 'Tā hóngliàng de xiàoshēng chuán biàn dàtīng.', 'A risada sonora dele encheu o salão.', 'Registro literário'],
    ['诉讼程序', 'sùsòng chéngxù', 'trâmite processual', 'substantivo', '诉讼程序拖了很久。', 'Sùsòng chéngxù tuō le hěn jiǔ.', 'O trâmite processual se arrastou.', 'Jurídico avançado'],
    ['管辖权', 'guǎnxiáquán', 'jurisdição', 'substantivo', '法院没有管辖权。', 'Fǎyuàn méiyǒu guǎnxiáquán.', 'O tribunal não tem jurisdição.', 'Jurídico avançado'],
    ['起诉书', 'qǐsùshū', 'denúncia formal', 'substantivo', '起诉书有六十页。', 'Qǐsùshū yǒu liùshí yè.', 'A denúncia tinha sessenta páginas.', 'Jurídico avançado'],
    ['罪责能力', 'zuìzé nénglì', 'imputabilidade', 'substantivo', '罪责能力从未确立。', 'Zuìzé nénglì cóngwèi quèlì.', 'A imputabilidade nunca foi estabelecida.', 'Jurídico avançado'],
    ['推定', 'tuīdìng', 'presunção', 'substantivo', '无罪推定依然适用。', 'Wúzuì tuīdìng yīrán shìyòng.', 'A presunção de inocência se aplica.', 'Jurídico avançado'],
    ['免责的', 'miǎnzé de', 'excludente de responsabilidade', 'adjetivo', '他们隐瞒了免责的证据。', 'Tāmen yǐnmán le miǎnzé de zhèngjù.', 'Ocultaram provas excludentes.', 'Jurídico avançado'],
    ['禁令', 'jìnlìng', 'liminar / medida proibitiva', 'substantivo', '法官下达了禁令。', 'Fǎguān xiàdá le jìnlìng.', 'O juiz concedeu uma liminar.', 'Jurídico avançado'],
    ['宣誓证词', 'xuānshì zhèngcí', 'depoimento juramentado', 'substantivo', '宣誓证词持续了一整天。', 'Xuānshì zhèngcí chíxù le yì zhěng tiān.', 'O depoimento juramentado durou o dia todo.', 'Jurídico avançado'],
    ['裁定', 'cáidìng', 'decidir / julgar', 'verbo', '委员会将裁定这起纠纷。', 'Wěiyuánhuì jiāng cáidìng zhè qǐ jiūfēn.', 'A comissão vai julgar a disputa.', 'Jurídico avançado'],
    ['民事侵权', 'mínshì qīnquán', 'ilícito civil', 'substantivo', '这构成民事侵权。', 'Zhè gòuchéng mínshì qīnquán.', 'Isso configura um ilícito civil.', 'Jurídico avançado'],
    ['博学的', 'bóxué de', 'erudito', 'adjetivo', '脚注非常博学。', 'Jiǎozhù fēicháng bóxué.', 'As notas de rodapé são eruditas.', 'Termos eruditos'],
    ['清澈的', 'qīngchè de', 'límpido / cristalino', 'adjetivo', '他清澈的解释结束了争论。', 'Tā qīngchè de jiěshì jiéshù le zhēnglùn.', 'A explicação límpida dele encerrou o debate.', 'Termos eruditos'],
    ['晦涩的', 'huìsè de', 'obscuro / hermético', 'adjetivo', '论证变得晦涩了。', 'Lùnzhèng biàn de huìsè le.', 'O argumento ficou hermético.', 'Termos eruditos'],
    ['深奥的', 'shēn’ào de', 'profundo / abstruso', 'adjetivo', '理论过于深奥。', 'Lǐlùn guòyú shēn’ào.', 'A teoria é abstrusa demais.', 'Termos eruditos'],
    ['睿智的', 'ruìzhì de', 'sagaz', 'adjetivo', '那是个睿智的选择。', 'Nà shì gè ruìzhì de xuǎnzé.', 'Foi uma escolha sagaz.', 'Termos eruditos'],
    ['敏锐的', 'mǐnruì de', 'perspicaz', 'adjetivo', '敏锐的读者会注意到。', 'Mǐnruì de dúzhě huì zhùyì dào.', 'Um leitor perspicaz vai notar.', 'Termos eruditos'],
    ['简练的', 'jiǎnliàn de', 'lacônico / conciso', 'adjetivo', '他的回答很简练。', 'Tā de huídá hěn jiǎnliàn.', 'A resposta dele foi lacônica.', 'Termos eruditos'],
    ['冗长的', 'rǒngcháng de', 'prolixo', 'adjetivo', '导言太冗长了。', 'Dǎoyán tài rǒngcháng le.', 'A introdução é prolixa.', 'Termos eruditos'],
    ['沉默寡言的', 'chénmò guǎyán de', 'taciturno', 'adjetivo', '他全程沉默寡言。', 'Tā quánchéng chénmò guǎyán.', 'Ele permaneceu taciturno o tempo todo.', 'Termos eruditos'],
    ['多话的', 'duōhuà de', 'tagarela', 'adjetivo', '多话的主人一直不停。', 'Duōhuà de zhǔrén yìzhí bù tíng.', 'O anfitrião tagarela não parava.', 'Termos eruditos'],
    ['矛盾心理', 'máodùn xīnlǐ', 'ambivalência', 'substantivo', '她的矛盾心理很明显。', 'Tā de máodùn xīnlǐ hěn míngxiǎn.', 'A ambivalência dela era evidente.', 'Nuance psicológica'],
    ['内疚', 'nèijiù', 'culpa / remorso', 'substantivo', '他毫无内疚地撒谎。', 'Tā háowú nèijiù de sāhuǎng.', 'Ele mentiu sem nenhum remorso.', 'Nuance psicológica'],
    ['忐忑', 'tǎntè', 'apreensivo / inquieto', 'adjetivo', '她忐忑地打开了信。', 'Tā tǎntè de dǎkāi le xìn.', 'Ela abriu a carta apreensiva.', 'Nuance psicológica'],
    ['恼怒', 'nǎonù', 'irritação / ofensa', 'substantivo', '那句话让他很恼怒。', 'Nà jù huà ràng tā hěn nǎonù.', 'Aquela frase o deixou ofendido.', 'Nuance psicológica'],
    ['积怨', 'jīyuàn', 'rancor acumulado', 'substantivo', '她说话没有积怨。', 'Tā shuōhuà méiyǒu jīyuàn.', 'Ela falou sem rancor.', 'Nuance psicológica'],
    ['悔意', 'huǐyì', 'contrição', 'substantivo', '他的悔意看来真诚。', 'Tā de huǐyì kànlái zhēnchéng.', 'A contrição dele parecia genuína.', 'Nuance psicológica'],
    ['傲慢', 'àomàn', 'arrogância', 'substantivo', '傲慢导致了崩塌。', 'Àomàn dǎozhì le bēngtā.', 'A arrogância levou ao colapso.', 'Nuance psicológica'],
    ['宽容', 'kuānróng', 'tolerância', 'substantivo', '感谢您的宽容。', 'Gǎnxiè nín de kuānróng.', 'Agradeço pela sua tolerância.', 'Nuance psicológica'],
    ['宽宏大量', 'kuānhóng dàliàng', 'magnanimidade', 'substantivo', '他表现得宽宏大量。', 'Tā biǎoxiàn de kuānhóng dàliàng.', 'Ele agiu com magnanimidade.', 'Nuance psicológica'],
    ['羞怯', 'xiūqiè', 'timidez', 'substantivo', '羞怯掩盖了真正的才华。', 'Xiūqiè yǎngài le zhēnzhèng de cáihuá.', 'A timidez escondia talento real.', 'Nuance psicológica'],
    ['必然结论', 'bìrán jiélùn', 'corolário', 'substantivo', '成本上升是必然结论。', 'Chéngběn shàngshēng shì bìrán jiélùn.', 'O aumento de custo é um corolário.', 'Argumentação'],
    ['不言自明的', 'bùyán zìmíng de', 'axiomático / evidente', 'adjetivo', '在这个领域这是不言自明的。', 'Zài zhège lǐngyù zhè shì bùyán zìmíng de.', 'Nesta área isso é evidente.', 'Argumentação'],
    ['无可辩驳的', 'wúkě biànbó de', 'irrefutável', 'adjetivo', '数据是无可辩驳的。', 'Shùjù shì wúkě biànbó de.', 'Os dados são irrefutáveis.', 'Argumentação'],
    ['有力的', 'yǒulì de', 'consistente / bem fundamentado', 'adjetivo', '她提出了有力的论证。', 'Tā tíchū le yǒulì de lùnzhèng.', 'Ela apresentou um argumento consistente.', 'Argumentação'],
    ['外推', 'wàituī', 'extrapolar', 'verbo', '不要从单个案例外推。', 'Búyào cóng dān gè ànlì wàituī.', 'Não extrapole a partir de um caso.', 'Argumentação'],
    ['诡辩术', 'guǐbiànshù', 'sofística', 'substantivo', '那种辩护是诡辩术。', 'Nà zhǒng biànhù shì guǐbiànshù.', 'Essa defesa é pura sofística.', 'Argumentação'],
    ['虚伪的', 'xūwěi de', 'hipócrita / de má-fé', 'adjetivo', '那个回答很虚伪。', 'Nàge huídá hěn xūwěi.', 'Aquela resposta é de má-fé.', 'Argumentação'],
    ['似是而非的', 'sìshì’érfēi de', 'especioso', 'adjetivo', '这个推理是似是而非的。', 'Zhège tuīlǐ shì sìshì’érfēi de.', 'Esse raciocínio é especioso.', 'Argumentação'],
    ['切题的', 'qiètí de', 'pertinente', 'adjetivo', '你的意见很切题。', 'Nǐ de yìjiàn hěn qiètí.', 'Sua observação é pertinente.', 'Argumentação'],
    ['就其本身而言', 'jiù qí běnshēn ér yán', 'por si só', 'advérbio', '就其本身而言并不成立。', 'Jiù qí běnshēn ér yán bìng bù chénglì.', 'Por si só não se sustenta.', 'Argumentação'],
    ['逼真感', 'bīzhēngǎn', 'verossimilhança', 'substantivo', '这部电影缺乏逼真感。', 'Zhè bù diànyǐng quēfá bīzhēngǎn.', 'Este filme carece de verossimilhança.', 'Crítica e estética'],
    ['拼贴之作', 'pīntiē zhī zuò', 'pastiche', 'substantivo', '这张专辑是有意的拼贴之作。', 'Zhè zhāng zhuānjí shì yǒuyì de pīntiē zhī zuò.', 'Este álbum é um pastiche intencional.', 'Crítica e estética'],
    ['虎头蛇尾', 'hǔtóu shéwěi', 'começo grandioso e fim fraco', 'substantivo', '结尾虎头蛇尾。', 'Jiéwěi hǔtóu shéwěi.', 'O final foi um anticlímax.', 'Crítica e estética'],
    ['结局', 'jiéjú', 'desfecho', 'substantivo', '结局显得仓促。', 'Jiéjú xiǎnde cāngcù.', 'O desfecho pareceu apressado.', 'Crítica e estética'],
    ['寓言', 'yùyán', 'alegoria / fábula', 'substantivo', '整本书就是一则寓言。', 'Zhěng běn shū jiùshì yì zé yùyán.', 'O livro inteiro é uma alegoria.', 'Crítica e estética'],
    ['反复出现的主题', 'fǎnfù chūxiàn de zhǔtí', 'motivo recorrente', 'substantivo', '水是反复出现的主题。', 'Shuǐ shì fǎnfù chūxiàn de zhǔtí.', 'A água é o motivo recorrente.', 'Crítica e estética'],
    ['夸张', 'kuāzhāng', 'hipérbole / exagero', 'substantivo', '那是夸张，不是分析。', 'Nà shì kuāzhāng, bú shì fēnxī.', 'Isso é exagero, não análise.', 'Crítica e estética'],
    ['悲怆', 'bēichuàng', 'pathos / comoção trágica', 'substantivo', '那一幕真有悲怆。', 'Nà yí mù zhēn yǒu bēichuàng.', 'Aquela cena tem comoção verdadeira.', 'Crítica e estética'],
    ['讽刺', 'fěngcì', 'sátira', 'substantivo', '当作讽刺来读更好。', 'Dàngzuò fěngcì lái dú gèng hǎo.', 'Funciona melhor lido como sátira.', 'Crítica e estética'],
    ['全集', 'quánjí', 'obra completa', 'substantivo', '在她的全集中这是小品。', 'Zài tā de quánjí zhōng zhè shì xiǎopǐn.', 'Dentro da obra completa dela isto é uma peça menor.', 'Crítica e estética'],
  ],
};
