/** Alemão — segundo lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const DE_THEMATIC2: LatinByLevel = {
  A1: [
    ['eins', 'um', 'numeral', 'Ich möchte einen Apfel.', 'Quero uma maçã.', 'Números e quantidade'],
    ['zwei', 'dois', 'numeral', 'Sie hat zwei Brüder.', 'Ela tem dois irmãos.', 'Números e quantidade'],
    ['drei', 'três', 'numeral', 'Wir haben drei Stunden gewartet.', 'Esperamos três horas.', 'Números e quantidade'],
    ['viele', 'muitos', 'determinante', 'Es sind viele Leute da.', 'Há muitas pessoas.', 'Números e quantidade'],
    ['wenige', 'poucos', 'determinante', 'Wenige Schüler kamen.', 'Poucos alunos vieram.', 'Números e quantidade'],
    ['die Hälfte', 'metade', 'substantivo', 'Ich habe die Hälfte gegessen.', 'Comi metade.', 'Números e quantidade'],
    ['leer', 'vazio', 'adjetivo', 'Die Flasche ist leer.', 'A garrafa está vazia.', 'Números e quantidade'],
    ['schwer', 'pesado', 'adjetivo', 'Diese Kiste ist schwer.', 'Esta caixa é pesada.', 'Números e quantidade'],
    ['leicht', 'leve', 'adjetivo', 'Die Tasche ist leicht.', 'A bolsa é leve.', 'Números e quantidade'],
    ['die Zahl', 'número', 'substantivo', 'Sag mir deine Zahl.', 'Me diga seu número.', 'Números e quantidade'],
    ['aufwachen', 'acordar', 'verbo', 'Ich wache um sechs auf.', 'Eu acordo às seis.', 'Ações do dia a dia'],
    ['schlafen', 'dormir', 'verbo', 'Ich schlafe acht Stunden.', 'Eu durmo oito horas.', 'Ações do dia a dia'],
    ['waschen', 'lavar', 'verbo', 'Wasch dir die Hände.', 'Lave as mãos.', 'Ações do dia a dia'],
    ['kochen', 'cozinhar', 'verbo', 'Sie kocht jeden Abend.', 'Ela cozinha toda noite.', 'Ações do dia a dia'],
    ['putzen', 'limpar', 'verbo', 'Ich putze die Wohnung.', 'Eu limpo o apartamento.', 'Ações do dia a dia'],
    ['kaufen', 'comprar', 'verbo', 'Ich kaufe hier Brot.', 'Eu compro pão aqui.', 'Ações do dia a dia'],
    ['verkaufen', 'vender', 'verbo', 'Sie verkaufen Obst.', 'Eles vendem fruta.', 'Ações do dia a dia'],
    ['laufen', 'caminhar / correr', 'verbo', 'Wir laufen zur Schule.', 'Nós vamos a pé até a escola.', 'Ações do dia a dia'],
    ['rennen', 'correr', 'verbo', 'Er rennt schnell.', 'Ele corre rápido.', 'Ações do dia a dia'],
    ['warten', 'esperar', 'verbo', 'Warten Sie bitte hier.', 'Espere aqui, por favor.', 'Ações do dia a dia'],
    ['der Lehrer', 'professor', 'substantivo', 'Der Lehrer ist nett.', 'O professor é gentil.', 'Escola'],
    ['der Schüler', 'aluno', 'substantivo', 'Sie ist eine gute Schülerin.', 'Ela é uma boa aluna.', 'Escola'],
    ['das Buch', 'livro', 'substantivo', 'Dieses Buch ist lang.', 'Este livro é longo.', 'Escola'],
    ['der Stift', 'caneta', 'substantivo', 'Ich brauche einen Stift.', 'Preciso de uma caneta.', 'Escola'],
    ['das Papier', 'papel', 'substantivo', 'Gib mir etwas Papier.', 'Me dê um papel.', 'Escola'],
    ['die Unterrichtsstunde', 'aula', 'substantivo', 'Die Unterrichtsstunde beginnt jetzt.', 'A aula começa agora.', 'Escola'],
    ['die Hausaufgaben', 'lição de casa', 'substantivo', 'Ich habe die Hausaufgaben fertig.', 'Terminei a lição de casa.', 'Escola'],
    ['die Prüfung', 'prova', 'substantivo', 'Die Prüfung war schwer.', 'A prova foi difícil.', 'Escola'],
    ['das Klassenzimmer', 'sala de aula', 'substantivo', 'Das Klassenzimmer ist groß.', 'A sala de aula é grande.', 'Escola'],
    ['die Frage', 'pergunta', 'substantivo', 'Ich habe eine Frage.', 'Tenho uma pergunta.', 'Escola'],
    ['der Vogel', 'pássaro', 'substantivo', 'Ein Vogel singt.', 'Um pássaro está cantando.', 'Animais'],
    ['der Fisch', 'peixe', 'substantivo', 'Der Fisch ist klein.', 'O peixe é pequeno.', 'Animais'],
    ['das Pferd', 'cavalo', 'substantivo', 'Das Pferd ist schnell.', 'O cavalo é rápido.', 'Animais'],
    ['die Kuh', 'vaca', 'substantivo', 'Die Kuh frisst Gras.', 'A vaca come grama.', 'Animais'],
    ['das Huhn', 'galinha', 'substantivo', 'Wir haben drei Hühner.', 'Temos três galinhas.', 'Animais'],
    ['die Maus', 'rato', 'substantivo', 'Hier ist eine Maus.', 'Tem um rato aqui.', 'Animais'],
    ['das Insekt', 'inseto', 'substantivo', 'Ein Insekt ist reingeflogen.', 'Um inseto entrou voando.', 'Animais'],
    ['das Schaf', 'ovelha', 'substantivo', 'Die Schafe sind weiß.', 'As ovelhas são brancas.', 'Animais'],
    ['das Schwein', 'porco', 'substantivo', 'Das Schwein ist schmutzig.', 'O porco está sujo.', 'Animais'],
    ['das Kaninchen', 'coelho', 'substantivo', 'Das Kaninchen ist schnell.', 'O coelho é rápido.', 'Animais'],
  ],
  A2: [
    ['der Bus', 'ônibus', 'substantivo', 'Der Bus hat Verspätung.', 'O ônibus está atrasado.', 'Transporte'],
    ['der Zug', 'trem', 'substantivo', 'Der Zug fährt um acht.', 'O trem sai às oito.', 'Transporte'],
    ['das Auto', 'carro', 'substantivo', 'Mein Auto ist alt.', 'Meu carro é velho.', 'Transporte'],
    ['das Fahrrad', 'bicicleta', 'substantivo', 'Ich fahre Fahrrad.', 'Eu ando de bicicleta.', 'Transporte'],
    ['das Taxi', 'táxi', 'substantivo', 'Nehmen wir ein Taxi.', 'Vamos pegar um táxi.', 'Transporte'],
    ['der Fahrer', 'motorista', 'substantivo', 'Der Fahrer war höflich.', 'O motorista foi educado.', 'Transporte'],
    ['der Fahrpreis', 'tarifa', 'substantivo', 'Der Fahrpreis ist gestiegen.', 'A tarifa subiu.', 'Transporte'],
    ['der Bahnsteig', 'plataforma', 'substantivo', 'Warte auf Bahnsteig zwei.', 'Espere na plataforma dois.', 'Transporte'],
    ['der Sitzplatz', 'assento', 'substantivo', 'Dieser Sitzplatz ist frei.', 'Este assento está livre.', 'Transporte'],
    ['die Fahrt', 'trajeto / viagem', 'substantivo', 'Die Fahrt dauert zwei Stunden.', 'O trajeto dura duas horas.', 'Transporte'],
    ['das Hobby', 'passatempo', 'substantivo', 'Lesen ist mein Hobby.', 'Ler é meu passatempo.', 'Lazer'],
    ['das Museum', 'museu', 'substantivo', 'Das Museum ist heute frei.', 'O museu está de graça hoje.', 'Lazer'],
    ['das Kino', 'cinema', 'substantivo', 'Wir waren im Kino.', 'Fomos ao cinema.', 'Lazer'],
    ['das Konzert', 'show / concerto', 'substantivo', 'Das Konzert war toll.', 'O show foi ótimo.', 'Lazer'],
    ['der Park', 'parque', 'substantivo', 'Der Park ist ganz nah.', 'O parque fica bem perto.', 'Lazer'],
    ['das Brettspiel', 'jogo de tabuleiro', 'substantivo', 'Dieses Brettspiel macht Spaß.', 'Este jogo de tabuleiro é divertido.', 'Lazer'],
    ['die Kamera', 'câmera', 'substantivo', 'Bring deine Kamera mit.', 'Traga sua câmera.', 'Lazer'],
    ['das Picknick', 'piquenique', 'substantivo', 'Wir haben ein Picknick gemacht.', 'Fizemos um piquenique.', 'Lazer'],
    ['schwimmen', 'nadar', 'verbo', 'Ich schwimme sonntags.', 'Eu nado aos domingos.', 'Lazer'],
    ['tanzen', 'dançar', 'verbo', 'Sie tanzen sehr gut.', 'Eles dançam muito bem.', 'Lazer'],
    ['glücklich', 'feliz', 'adjetivo', 'Sie sieht glücklich aus.', 'Ela parece feliz.', 'Emoções'],
    ['traurig', 'triste', 'adjetivo', 'Er war gestern traurig.', 'Ele estava triste ontem.', 'Emoções'],
    ['wütend', 'bravo', 'adjetivo', 'Sei nicht wütend.', 'Não fique bravo.', 'Emoções'],
    ['ängstlich', 'com medo', 'adjetivo', 'Ich bin ängstlich.', 'Estou com medo.', 'Emoções'],
    ['überrascht', 'surpreso', 'adjetivo', 'Wir waren überrascht.', 'Ficamos surpresos.', 'Emoções'],
    ['gelangweilt', 'entediado', 'adjetivo', 'Die Kinder sind gelangweilt.', 'As crianças estão entediadas.', 'Emoções'],
    ['besorgt', 'preocupado', 'adjetivo', 'Sie ist deswegen besorgt.', 'Ela está preocupada com isso.', 'Emoções'],
    ['stolz', 'orgulhoso', 'adjetivo', 'Ich bin stolz auf dich.', 'Estou orgulhoso de você.', 'Emoções'],
    ['ruhig', 'calmo', 'adjetivo', 'Versuch ruhig zu bleiben.', 'Tente ficar calmo.', 'Emoções'],
    ['einsam', 'solitário', 'adjetivo', 'Er fühlt sich einsam.', 'Ele se sente solitário.', 'Emoções'],
    ['jung', 'jovem', 'adjetivo', 'Sie ist sehr jung.', 'Ela é muito jovem.', 'Descrever pessoas'],
    ['alt', 'velho', 'adjetivo', 'Mein Großvater ist alt.', 'Meu avô é velho.', 'Descrever pessoas'],
    ['nett', 'gentil', 'adjetivo', 'Er ist ein netter Mann.', 'Ele é um homem gentil.', 'Descrever pessoas'],
    ['lustig', 'engraçado', 'adjetivo', 'Dein Freund ist lustig.', 'Seu amigo é engraçado.', 'Descrever pessoas'],
    ['still', 'quieto', 'adjetivo', 'Sie ist sehr still.', 'Ela é muito quieta.', 'Descrever pessoas'],
    ['klug', 'esperto / inteligente', 'adjetivo', 'Das war eine kluge Idee.', 'Foi uma ideia esperta.', 'Descrever pessoas'],
    ['faul', 'preguiçoso', 'adjetivo', 'Sei nicht faul.', 'Não seja preguiçoso.', 'Descrever pessoas'],
    ['ehrlich', 'honesto', 'adjetivo', 'Sie ist immer ehrlich.', 'Ela é sempre honesta.', 'Descrever pessoas'],
    ['freundlich', 'simpático', 'adjetivo', 'Das Personal ist freundlich.', 'A equipe é simpática.', 'Descrever pessoas'],
    ['stark', 'forte', 'adjetivo', 'Er ist sehr stark.', 'Ele é muito forte.', 'Descrever pessoas'],
  ],
  B1: [
    ['die Ernährung', 'alimentação', 'substantivo', 'Ihre Ernährung hat sich stark verändert.', 'A alimentação dela mudou muito.', 'Saúde e bem-estar'],
    ['die Bewegung', 'exercício físico', 'substantivo', 'Bewegung hilft beim Schlafen.', 'O exercício ajuda a dormir.', 'Saúde e bem-estar'],
    ['der Stress', 'estresse', 'substantivo', 'Stress wirkt auf den Körper.', 'O estresse afeta o corpo.', 'Saúde e bem-estar'],
    ['die Gewohnheit', 'hábito', 'substantivo', 'Es wurde zur Gewohnheit.', 'Virou um hábito.', 'Saúde e bem-estar'],
    ['die Therapie', 'terapia', 'substantivo', 'Die Therapie hat ihm sehr geholfen.', 'A terapia o ajudou muito.', 'Saúde e bem-estar'],
    ['die Genesung', 'recuperação', 'substantivo', 'Die Genesung braucht Zeit.', 'A recuperação leva tempo.', 'Saúde e bem-estar'],
    ['die Haltung', 'postura', 'substantivo', 'Korrigiere deine Haltung.', 'Corrija sua postura.', 'Saúde e bem-estar'],
    ['die Atmung', 'respiração', 'substantivo', 'Langsame Atmung beruhigt.', 'A respiração lenta acalma.', 'Saúde e bem-estar'],
    ['die Vorsorgeuntersuchung', 'check-up', 'substantivo', 'Ich hatte heute eine Vorsorgeuntersuchung.', 'Fiz um check-up hoje.', 'Saúde e bem-estar'],
    ['das Wohlbefinden', 'bem-estar', 'substantivo', 'Ihnen liegt das Wohlbefinden am Herzen.', 'Eles se importam com o bem-estar.', 'Saúde e bem-estar'],
    ['die Miete', 'aluguel', 'substantivo', 'Die Miete ist wieder gestiegen.', 'O aluguel subiu de novo.', 'Moradia'],
    ['der Mietvertrag', 'contrato de locação', 'substantivo', 'Der Mietvertrag endet im Juni.', 'O contrato acaba em junho.', 'Moradia'],
    ['die Kaution', 'caução', 'substantivo', 'Sie haben die Kaution behalten.', 'Ficaram com a caução.', 'Moradia'],
    ['der Mieter', 'inquilino', 'substantivo', 'Der Mieter hat sich beschwert.', 'O inquilino reclamou.', 'Moradia'],
    ['die Zimmerdecke', 'teto', 'substantivo', 'Die Zimmerdecke ist undicht.', 'O teto está vazando.', 'Moradia'],
    ['das Dach', 'telhado', 'substantivo', 'Das Dach muss repariert werden.', 'O telhado precisa de conserto.', 'Moradia'],
    ['der Keller', 'porão', 'substantivo', 'Der Keller ist feucht.', 'O porão está úmido.', 'Moradia'],
    ['der Balkon', 'varanda', 'substantivo', 'Wir essen auf dem Balkon.', 'Comemos na varanda.', 'Moradia'],
    ['die Rohrleitungen', 'encanamento', 'substantivo', 'Die Rohrleitungen sind alt.', 'O encanamento é velho.', 'Moradia'],
    ['die Vermieterin', 'senhoria', 'substantivo', 'Die Vermieterin hat mich angerufen.', 'A senhoria me ligou.', 'Moradia'],
    ['das Rezept', 'receita', 'substantivo', 'Schick mir das Rezept.', 'Me manda a receita.', 'Culinária'],
    ['die Zutat', 'ingrediente', 'substantivo', 'Eine Zutat fehlt.', 'Falta um ingrediente.', 'Culinária'],
    ['kochen lassen', 'ferver', 'verbo', 'Lass das Wasser zuerst kochen.', 'Ferva a água primeiro.', 'Culinária'],
    ['braten', 'fritar / grelhar', 'verbo', 'Brate die Zwiebeln langsam.', 'Frite a cebola devagar.', 'Culinária'],
    ['backen', 'assar (no forno)', 'verbo', 'Backe es eine Stunde.', 'Asse por uma hora.', 'Culinária'],
    ['hacken', 'picar', 'verbo', 'Hacke den Knoblauch fein.', 'Pique o alho bem fino.', 'Culinária'],
    ['würzen', 'temperar', 'verbo', 'Würze es mit Pfeffer.', 'Tempere com pimenta.', 'Culinária'],
    ['der Teig', 'massa (crua)', 'substantivo', 'Der Teig muss ruhen.', 'A massa precisa descansar.', 'Culinária'],
    ['schmoren', 'refogar / cozinhar lentamente', 'verbo', 'Wir schmoren das Fleisch langsam.', 'Cozinhamos a carne lentamente.', 'Culinária'],
    ['dämpfen', 'cozinhar no vapor', 'verbo', 'Dämpfe das Gemüse.', 'Cozinhe os legumes no vapor.', 'Culinária'],
    ['die Nachricht', 'mensagem', 'substantivo', 'Ich habe deine Nachricht bekommen.', 'Recebi sua mensagem.', 'Comunicação'],
    ['die Antwort', 'resposta', 'substantivo', 'Ich warte auf eine Antwort.', 'Estou esperando uma resposta.', 'Comunicação'],
    ['der Hinweis', 'aviso', 'substantivo', 'An der Tür hängt ein Hinweis.', 'Há um aviso na porta.', 'Comunicação'],
    ['die Bekanntmachung', 'comunicado', 'substantivo', 'Sie haben eine Bekanntmachung gemacht.', 'Fizeram um comunicado.', 'Comunicação'],
    ['das Gerücht', 'boato', 'substantivo', 'Das ist nur ein Gerücht.', 'É só um boato.', 'Comunicação'],
    ['die Erklärung', 'declaração', 'substantivo', 'Sie gab eine Erklärung ab.', 'Ela divulgou uma declaração.', 'Comunicação'],
    ['erklären', 'explicar', 'verbo', 'Erkläre es bitte noch einmal.', 'Explique de novo, por favor.', 'Comunicação'],
    ['beschreiben', 'descrever', 'verbo', 'Beschreibe, was du gesehen hast.', 'Descreva o que você viu.', 'Comunicação'],
    ['zusammenfassen', 'resumir', 'verbo', 'Fasse es in einem Satz zusammen.', 'Resuma em uma frase.', 'Comunicação'],
    ['das Missverständnis', 'mal-entendido', 'substantivo', 'Es war ein Missverständnis.', 'Foi um mal-entendido.', 'Comunicação'],
  ],
  B2: [
    ['die Skulptur', 'escultura', 'substantivo', 'Die Skulptur ist aus Bronze.', 'A escultura é de bronze.', 'Arte e cultura'],
    ['die Ausstellung', 'exposição', 'substantivo', 'Die Ausstellung öffnet am Freitag.', 'A exposição abre sexta.', 'Arte e cultura'],
    ['das Porträt', 'retrato', 'substantivo', 'Sie hat ein Porträt gemalt.', 'Ela pintou um retrato.', 'Arte e cultura'],
    ['die Leinwand', 'tela (de pintura)', 'substantivo', 'Die Leinwand war leer.', 'A tela estava em branco.', 'Arte e cultura'],
    ['das Orchester', 'orquestra', 'substantivo', 'Das Orchester hat geprobt.', 'A orquestra ensaiou.', 'Arte e cultura'],
    ['der Chor', 'coral', 'substantivo', 'Sie singt in einem Chor.', 'Ela canta num coral.', 'Arte e cultura'],
    ['der Dramatiker', 'dramaturgo', 'substantivo', 'Der Dramatiker ist berühmt.', 'O dramaturgo é famoso.', 'Arte e cultura'],
    ['der Romancier', 'romancista', 'substantivo', 'Sie ist eine junge Romancière.', 'Ela é uma jovem romancista.', 'Arte e cultura'],
    ['die Volkskunde', 'folclore', 'substantivo', 'Die örtliche Volkskunde ist reich.', 'O folclore local é rico.', 'Arte e cultura'],
    ['das Kulturerbe', 'patrimônio cultural', 'substantivo', 'Es ist eine Stätte des Kulturerbes.', 'É um sítio de patrimônio cultural.', 'Arte e cultura'],
    ['das Reich', 'império', 'substantivo', 'Das Reich brach zusammen.', 'O império ruiu.', 'História'],
    ['die Revolution', 'revolução', 'substantivo', 'Die Revolution veränderte alles.', 'A revolução mudou tudo.', 'História'],
    ['der Vertragsschluss', 'tratado', 'substantivo', 'Der Vertragsschluss beendete den Krieg.', 'O tratado encerrou a guerra.', 'História'],
    ['die Kolonie', 'colônia', 'substantivo', 'Es war einmal eine Kolonie.', 'Já foi uma colônia.', 'História'],
    ['die Dynastie', 'dinastia', 'substantivo', 'Die Dynastie hielt Jahrhunderte.', 'A dinastia durou séculos.', 'História'],
    ['der Aufstand', 'levante', 'substantivo', 'Der Aufstand wurde niedergeschlagen.', 'O levante foi esmagado.', 'História'],
    ['die Belagerung', 'cerco', 'substantivo', 'Die Belagerung dauerte ein Jahr.', 'O cerco durou um ano.', 'História'],
    ['das Archiv', 'arquivo histórico', 'substantivo', 'Das Archiv bewahrt die Briefe.', 'O arquivo guarda as cartas.', 'História'],
    ['die Chronik', 'crônica histórica', 'substantivo', 'Die Chronik nennt ihn.', 'A crônica o nomeia.', 'História'],
    ['das Artefakt', 'artefato', 'substantivo', 'Sie fanden ein Artefakt.', 'Encontraram um artefato.', 'História'],
    ['der Kontinent', 'continente', 'substantivo', 'Es ist der größte Kontinent.', 'É o maior continente.', 'Geografia'],
    ['die Halbinsel', 'península', 'substantivo', 'Die Halbinsel ist felsig.', 'A península é rochosa.', 'Geografia'],
    ['die Hochebene', 'planalto', 'substantivo', 'Die Hochebene ist trocken.', 'O planalto é seco.', 'Geografia'],
    ['der Gletscher', 'geleira', 'substantivo', 'Der Gletscher zieht sich zurück.', 'A geleira está recuando.', 'Geografia'],
    ['das Delta', 'delta (de rio)', 'substantivo', 'Das Delta ist fruchtbar.', 'O delta é fértil.', 'Geografia'],
    ['das Tal', 'vale', 'substantivo', 'Das Tal wird oft überflutet.', 'O vale alaga com frequência.', 'Geografia'],
    ['die Wüste', 'deserto', 'substantivo', 'Die Wüste breitet sich aus.', 'O deserto está avançando.', 'Geografia'],
    ['die Gezeiten', 'maré', 'substantivo', 'Die Gezeiten steigen.', 'A maré está subindo.', 'Geografia'],
    ['der Breitengrad', 'latitude', 'substantivo', 'Prüfe zuerst den Breitengrad.', 'Confira a latitude primeiro.', 'Geografia'],
    ['das Gelände', 'terreno', 'substantivo', 'Das Gelände ist schwierig.', 'O terreno é difícil.', 'Geografia'],
    ['die Integrität', 'integridade', 'substantivo', 'Seine Integrität steht außer Frage.', 'A integridade dele é inquestionável.', 'Ética'],
    ['die Tugend', 'virtude', 'substantivo', 'Geduld ist eine Tugend.', 'A paciência é uma virtude.', 'Ética'],
    ['die Pflicht', 'dever', 'substantivo', 'Es ist deine Pflicht, das zu melden.', 'É seu dever relatar isso.', 'Ética'],
    ['die Einwilligung', 'consentimento', 'substantivo', 'Sie handelten ohne Einwilligung.', 'Agiram sem consentimento.', 'Ética'],
    ['die Fairness', 'equidade', 'substantivo', 'Hier zählt Fairness.', 'Aqui a equidade importa.', 'Ética'],
    ['der Schaden', 'dano', 'substantivo', 'Die Maßnahme hat echten Schaden verursacht.', 'A medida causou dano real.', 'Ética'],
    ['die Würde', 'dignidade', 'substantivo', 'Behandelt sie mit Würde.', 'Trate-os com dignidade.', 'Ética'],
    ['die Verpflichtung', 'obrigação', 'substantivo', 'Wir haben eine Verpflichtung.', 'Temos uma obrigação.', 'Ética'],
    ['das Fehlverhalten', 'má conduta', 'substantivo', 'Er wurde wegen Fehlverhaltens entlassen.', 'Foi demitido por má conduta.', 'Ética'],
    ['der Hinweisgeber', 'denunciante', 'substantivo', 'Der Hinweisgeber wurde geschützt.', 'O denunciante foi protegido.', 'Ética'],
  ],
  C1: [
    ['die Bürokratie', 'burocracia', 'substantivo', 'Die Bürokratie hat alles verlangsamt.', 'A burocracia atrasou tudo.', 'Administração pública'],
    ['die Satzung', 'estatuto / decreto', 'substantivo', 'Eine neue Satzung wurde beschlossen.', 'Um novo estatuto foi aprovado.', 'Administração pública'],
    ['die Einhaltung', 'conformidade', 'substantivo', 'Die Einhaltung ist verpflichtend.', 'A conformidade é obrigatória.', 'Administração pública'],
    ['die Aufsicht', 'fiscalização', 'substantivo', 'Die Aufsicht war schwach.', 'A fiscalização era fraca.', 'Administração pública'],
    ['das Protokoll', 'protocolo', 'substantivo', 'Befolge das Protokoll genau.', 'Siga o protocolo à risca.', 'Administração pública'],
    ['die Richtlinie', 'diretriz', 'substantivo', 'Die Richtlinie gilt ab heute.', 'A diretriz vale a partir de hoje.', 'Administração pública'],
    ['das Quorum', 'quórum', 'substantivo', 'Wir haben das Quorum nicht erreicht.', 'Não atingimos o quórum.', 'Administração pública'],
    ['die Verbeamtung', 'efetivação no cargo', 'substantivo', 'Sie erhielt die Verbeamtung.', 'Ela foi efetivada no cargo.', 'Administração pública'],
    ['der Zuständigkeitsbereich', 'alçada / competência', 'substantivo', 'Das liegt außerhalb unseres Zuständigkeitsbereichs.', 'Isso está fora da nossa alçada.', 'Administração pública'],
    ['die Wiedergutmachung', 'reparação', 'substantivo', 'Sie forderten Wiedergutmachung.', 'Pediram reparação.', 'Administração pública'],
    ['der Median', 'mediana', 'substantivo', 'Hier ist der Median nützlicher.', 'Aqui a mediana é mais útil.', 'Estatística'],
    ['die Varianz', 'variância', 'substantivo', 'Die Varianz ist zu hoch.', 'A variância é alta demais.', 'Estatística'],
    ['die Standardabweichung', 'desvio padrão', 'substantivo', 'Gib die Standardabweichung an.', 'Informe o desvio padrão.', 'Estatística'],
    ['die Regression', 'regressão', 'substantivo', 'Die Regression erklärt wenig.', 'A regressão explica pouco.', 'Estatística'],
    ['die Wahrscheinlichkeit', 'probabilidade', 'substantivo', 'Die Wahrscheinlichkeit ist gering.', 'A probabilidade é baixa.', 'Estatística'],
    ['die Verteilung', 'distribuição', 'substantivo', 'Die Verteilung ist schief.', 'A distribuição é assimétrica.', 'Estatística'],
    ['der Ausreißer', 'ponto fora da curva', 'substantivo', 'Entferne diesen Ausreißer.', 'Remova esse ponto fora da curva.', 'Estatística'],
    ['die Signifikanz', 'significância', 'substantivo', 'Signifikanz ist nicht Bedeutung.', 'Significância não é importância.', 'Estatística'],
    ['der Schwellenwert', 'limiar', 'substantivo', 'Es fiel unter den Schwellenwert.', 'Ficou abaixo do limiar.', 'Estatística'],
    ['die Schätzung', 'estimativa', 'substantivo', 'Das ist eine grobe Schätzung.', 'É uma estimativa aproximada.', 'Estatística'],
    ['die Syntax', 'sintaxe', 'substantivo', 'Hier ändert sich die Syntax.', 'Aqui a sintaxe muda.', 'Linguística'],
    ['das Morphem', 'morfema', 'substantivo', 'Dieses Präfix ist ein Morphem.', 'Esse prefixo é um morfema.', 'Linguística'],
    ['das Phonem', 'fonema', 'substantivo', 'Die beiden Phoneme stehen im Kontrast.', 'Os dois fonemas contrastam.', 'Linguística'],
    ['die Semantik', 'semântica', 'substantivo', 'Der Streit dreht sich um Semantik.', 'A disputa é de semântica.', 'Linguística'],
    ['der Dialekt', 'dialeto', 'substantivo', 'Der Dialekt ändert sich je nach Region.', 'O dialeto varia por região.', 'Linguística'],
    ['die Sprachebene', 'registro de fala', 'substantivo', 'Passe die Sprachebene dem Kontext an.', 'Ajuste o registro de fala ao contexto.', 'Linguística'],
    ['die Etymologie', 'etimologia', 'substantivo', 'Die Etymologie ist umstritten.', 'A etimologia é contestada.', 'Linguística'],
    ['das verwandte Wort', 'cognato', 'substantivo', 'Diese beiden sind verwandte Wörter.', 'Estas duas são palavras cognatas.', 'Linguística'],
    ['die Flexion', 'flexão', 'substantivo', 'Die Flexion markiert den Fall.', 'A flexão marca o caso.', 'Linguística'],
    ['die Sprachgewandtheit', 'fluência / desenvoltura', 'substantivo', 'Sprachgewandtheit ist nicht Korrektheit.', 'A fluência não é correção.', 'Linguística'],
    ['die Fassade', 'fachada', 'substantivo', 'Die Fassade wurde restauriert.', 'A fachada foi restaurada.', 'Arquitetura'],
    ['das Fundament', 'fundação (de obra)', 'substantivo', 'Das Fundament hat Risse.', 'A fundação rachou.', 'Arquitetura'],
    ['der Bauplan', 'planta / projeto', 'substantivo', 'Prüfe den Bauplan noch einmal.', 'Confira a planta de novo.', 'Arquitetura'],
    ['das Gewölbe', 'abóbada', 'substantivo', 'Das Gewölbe ist mittelalterlich.', 'A abóbada é medieval.', 'Arquitetura'],
    ['das Gerüst', 'andaime', 'substantivo', 'Das Gerüst wurde heute aufgebaut.', 'O andaime subiu hoje.', 'Arquitetura'],
    ['die Bauleitplanung', 'zoneamento', 'substantivo', 'Die Bauleitplanung hat es verhindert.', 'O zoneamento impediu.', 'Arquitetura'],
    ['die Sanierung', 'reforma', 'substantivo', 'Die Sanierung dauerte ein Jahr.', 'A reforma levou um ano.', 'Arquitetura'],
    ['tragend', 'estrutural (que sustenta)', 'adjetivo', 'Das ist eine tragende Wand.', 'Aquela é uma parede estrutural.', 'Arquitetura'],
    ['die Zersiedelung', 'expansão urbana desordenada', 'substantivo', 'Die Zersiedelung nimmt zu.', 'A expansão urbana desordenada aumenta.', 'Arquitetura'],
    ['die Skyline', 'silhueta urbana', 'substantivo', 'Die Skyline hat sich völlig verändert.', 'A silhueta urbana mudou por completo.', 'Arquitetura'],
  ],
  C2: [
    ['die Entspannungspolitik', 'política de distensão', 'substantivo', 'Die Entspannungspolitik hielt nicht.', 'A política de distensão não durou.', 'Diplomacia'],
    ['die Annäherung', 'reaproximação', 'substantivo', 'Eine vorsichtige Annäherung begann.', 'Começou uma reaproximação cautelosa.', 'Diplomacia'],
    ['das Kommuniqué', 'comunicado oficial', 'substantivo', 'Das Kommuniqué sagte wenig.', 'O comunicado dizia pouco.', 'Diplomacia'],
    ['der Gesandte', 'emissário', 'substantivo', 'Ein Gesandter wurde entsandt.', 'Um emissário foi enviado.', 'Diplomacia'],
    ['das Abkommen', 'acordo formal', 'substantivo', 'Das Abkommen hält vorerst.', 'O acordo se mantém por ora.', 'Diplomacia'],
    ['die Sanktion', 'sanção', 'substantivo', 'Die Sanktionen wurden aufgehoben.', 'As sanções foram suspensas.', 'Diplomacia'],
    ['die Neutralität', 'neutralidade', 'substantivo', 'Sie erklärten die Neutralität.', 'Declararam neutralidade.', 'Diplomacia'],
    ['die Souveränität', 'soberania', 'substantivo', 'Die Souveränität war der Knackpunkt.', 'A soberania foi o impasse.', 'Diplomacia'],
    ['die Gegenseitigkeit', 'reciprocidade', 'substantivo', 'Der Pakt beruht auf Gegenseitigkeit.', 'O pacto se apoia na reciprocidade.', 'Diplomacia'],
    ['das Kräftemessen', 'queda de braço', 'substantivo', 'Das ist reines Kräftemessen.', 'Isso é pura queda de braço.', 'Diplomacia'],
    ['die Theodizee', 'teodiceia', 'substantivo', 'Die Theodizee fragt nach dem Bösen.', 'A teodiceia pergunta pelo mal.', 'Teologia e mito'],
    ['die Apotheose', 'apoteose', 'substantivo', 'Es war die Apotheose des Stils.', 'Foi a apoteose do estilo.', 'Teologia e mito'],
    ['die Eschatologie', 'escatologia', 'substantivo', 'Die Eschatologie handelt von den letzten Dingen.', 'A escatologia trata das coisas últimas.', 'Teologia e mito'],
    ['die Liturgie', 'liturgia', 'substantivo', 'Die Liturgie ist Jahrhunderte alt.', 'A liturgia tem séculos.', 'Teologia e mito'],
    ['die Ketzerei', 'heresia', 'substantivo', 'Es wurde als Ketzerei verurteilt.', 'Foi condenado como heresia.', 'Teologia e mito'],
    ['das Pantheon', 'panteão', 'substantivo', 'Sie trat ins Pantheon der Großen ein.', 'Ela entrou no panteão dos grandes.', 'Teologia e mito'],
    ['das Orakel', 'oráculo', 'substantivo', 'Das Orakel sprach in Rätseln.', 'O oráculo falava por enigmas.', 'Teologia e mito'],
    ['die Reliquie', 'relíquia', 'substantivo', 'Die Reliquie zog Pilger an.', 'A relíquia atraía peregrinos.', 'Teologia e mito'],
    ['das Schisma', 'cisma', 'substantivo', 'Das Schisma spaltete die Kirche.', 'O cisma dividiu a igreja.', 'Teologia e mito'],
    ['die Transzendenz', 'transcendência', 'substantivo', 'Das Gedicht strebt nach Transzendenz.', 'O poema busca a transcendência.', 'Teologia e mito'],
    ['a priori', 'a priori', 'advérbio', 'Das kann man nicht a priori wissen.', 'Isso não se sabe a priori.', 'Locuções cultas'],
    ['a fortiori', 'com mais razão ainda', 'advérbio', 'A fortiori scheitert der zweite Fall.', 'Com mais razão ainda, o segundo caso falha.', 'Locuções cultas'],
    ['conditio sine qua non', 'condição indispensável', 'substantivo', 'Vertrauen ist die conditio sine qua non.', 'A confiança é a condição indispensável.', 'Locuções cultas'],
    ['de facto', 'de fato', 'adjetivo', 'Sie ist die De-facto-Chefin.', 'Ela é a chefe de fato.', 'Locuções cultas'],
    ['ad hoc', 'ad hoc / improvisado', 'adjetivo', 'Es war ein Ad-hoc-Ausschuss.', 'Era um comitê ad hoc.', 'Locuções cultas'],
    ['mutatis mutandis', 'feitas as devidas adaptações', 'advérbio', 'Dasselbe gilt mutatis mutandis.', 'O mesmo vale, feitas as devidas adaptações.', 'Locuções cultas'],
    ['ceteris paribus', 'mantidas as demais condições', 'advérbio', 'Ceteris paribus sinkt die Nachfrage.', 'Mantidas as demais condições, a procura cai.', 'Locuções cultas'],
    ['prima facie', 'à primeira vista', 'adjetivo', 'Es gibt einen Prima-facie-Fall.', 'Há indício suficiente à primeira vista.', 'Locuções cultas'],
    ['an sich', 'em si mesmo', 'advérbio', 'Die Regel ist an sich nicht ungerecht.', 'A regra não é injusta em si mesma.', 'Locuções cultas'],
    ['in extremis', 'em situação extrema', 'advérbio', 'Der Deal wurde in extremis gerettet.', 'O acordo foi salvo in extremis.', 'Locuções cultas'],
    ['die Wehmut', 'saudade melancólica', 'substantivo', 'Sie sprach mit Wehmut davon.', 'Ela falava disso com saudade.', 'Emoções sutis'],
    ['die Melancholie', 'melancolia', 'substantivo', 'Eine stille Melancholie durchzieht es.', 'Uma melancolia discreta o atravessa.', 'Emoções sutis'],
    ['die Langeweile', 'tédio', 'substantivo', 'Die Langeweile langer Nachmittage.', 'O tédio das tardes longas.', 'Emoções sutis'],
    ['der Überschwang', 'euforia / entusiasmo', 'substantivo', 'Sein Überschwang war kurz.', 'A euforia dele durou pouco.', 'Emoções sutis'],
    ['die Beunruhigung', 'inquietação', 'substantivo', 'Die Nachricht sorgte für Beunruhigung.', 'A notícia causou inquietação.', 'Emoções sutis'],
    ['die Sehnsucht', 'anseio / saudade', 'substantivo', 'Eine Sehnsucht nach etwas Verlorenem.', 'Um anseio por algo perdido.', 'Emoções sutis'],
    ['die Gelassenheit im Sturm', 'serenidade diante da crise', 'substantivo', 'Sie zeigte Gelassenheit im Sturm.', 'Ela mostrou serenidade diante da crise.', 'Emoções sutis'],
    ['die Empörung', 'indignação', 'substantivo', 'Seine Empörung war berechtigt.', 'A indignação dele era justificada.', 'Emoções sutis'],
    ['die Träumerei', 'devaneio', 'substantivo', 'Sie versank in Träumerei.', 'Ela mergulhou num devaneio.', 'Emoções sutis'],
    ['der Trost', 'consolo', 'substantivo', 'Er fand Trost in der Musik.', 'Ele encontrou consolo na música.', 'Emoções sutis'],
  ],
};
