/** Inglês — segundo lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const EN_THEMATIC2: LatinByLevel = {
  A1: [
    ['one', 'um', 'numeral', 'I want one apple.', 'Quero uma maçã.', 'Números e quantidade'],
    ['two', 'dois', 'numeral', 'She has two brothers.', 'Ela tem dois irmãos.', 'Números e quantidade'],
    ['three', 'três', 'numeral', 'We waited three hours.', 'Esperamos três horas.', 'Números e quantidade'],
    ['many', 'muitos', 'determinante', 'There are many people.', 'Há muitas pessoas.', 'Números e quantidade'],
    ['few', 'poucos', 'determinante', 'Few students came.', 'Poucos alunos vieram.', 'Números e quantidade'],
    ['half', 'metade', 'substantivo', 'I ate half of it.', 'Comi metade.', 'Números e quantidade'],
    ['empty', 'vazio', 'adjetivo', 'The bottle is empty.', 'A garrafa está vazia.', 'Números e quantidade'],
    ['full', 'cheio', 'adjetivo', 'The glass is full.', 'O copo está cheio.', 'Números e quantidade'],
    ['heavy', 'pesado', 'adjetivo', 'This box is heavy.', 'Esta caixa é pesada.', 'Números e quantidade'],
    ['light', 'leve', 'adjetivo', 'The bag is light.', 'A bolsa é leve.', 'Números e quantidade'],
    ['wake up', 'acordar', 'verbo', 'I wake up at six.', 'Eu acordo às seis.', 'Ações do dia a dia'],
    ['sleep', 'dormir', 'verbo', 'I sleep eight hours.', 'Eu durmo oito horas.', 'Ações do dia a dia'],
    ['wash', 'lavar', 'verbo', 'Wash your hands.', 'Lave as mãos.', 'Ações do dia a dia'],
    ['cook', 'cozinhar', 'verbo', 'She cooks every night.', 'Ela cozinha toda noite.', 'Ações do dia a dia'],
    ['clean', 'limpar', 'verbo', 'I clean the house.', 'Eu limpo a casa.', 'Ações do dia a dia'],
    ['buy', 'comprar', 'verbo', 'I buy bread here.', 'Eu compro pão aqui.', 'Ações do dia a dia'],
    ['sell', 'vender', 'verbo', 'They sell fruit.', 'Eles vendem fruta.', 'Ações do dia a dia'],
    ['walk', 'caminhar', 'verbo', 'We walk to school.', 'Nós caminhamos até a escola.', 'Ações do dia a dia'],
    ['run', 'correr', 'verbo', 'He runs fast.', 'Ele corre rápido.', 'Ações do dia a dia'],
    ['wait', 'esperar', 'verbo', 'Please wait here.', 'Espere aqui, por favor.', 'Ações do dia a dia'],
    ['teacher', 'professor', 'substantivo', 'The teacher is kind.', 'O professor é gentil.', 'Escola'],
    ['student', 'aluno', 'substantivo', 'She is a good student.', 'Ela é uma boa aluna.', 'Escola'],
    ['book', 'livro', 'substantivo', 'This book is long.', 'Este livro é longo.', 'Escola'],
    ['pen', 'caneta', 'substantivo', 'I need a pen.', 'Preciso de uma caneta.', 'Escola'],
    ['paper', 'papel', 'substantivo', 'Give me some paper.', 'Me dê um papel.', 'Escola'],
    ['lesson', 'aula', 'substantivo', 'The lesson starts now.', 'A aula começa agora.', 'Escola'],
    ['homework', 'lição de casa', 'substantivo', 'I finished my homework.', 'Terminei minha lição de casa.', 'Escola'],
    ['test', 'prova', 'substantivo', 'The test was hard.', 'A prova foi difícil.', 'Escola'],
    ['classroom', 'sala de aula', 'substantivo', 'The classroom is big.', 'A sala de aula é grande.', 'Escola'],
    ['question', 'pergunta', 'substantivo', 'I have a question.', 'Tenho uma pergunta.', 'Escola'],
    ['bird', 'pássaro', 'substantivo', 'A bird is singing.', 'Um pássaro está cantando.', 'Animais'],
    ['fish', 'peixe', 'substantivo', 'The fish is small.', 'O peixe é pequeno.', 'Animais'],
    ['horse', 'cavalo', 'substantivo', 'The horse is fast.', 'O cavalo é rápido.', 'Animais'],
    ['cow', 'vaca', 'substantivo', 'The cow eats grass.', 'A vaca come grama.', 'Animais'],
    ['chicken', 'galinha', 'substantivo', 'We have three chickens.', 'Temos três galinhas.', 'Animais'],
    ['mouse', 'rato', 'substantivo', 'There is a mouse here.', 'Tem um rato aqui.', 'Animais'],
    ['insect', 'inseto', 'substantivo', 'An insect flew in.', 'Um inseto entrou voando.', 'Animais'],
    ['sheep', 'ovelha', 'substantivo', 'The sheep are white.', 'As ovelhas são brancas.', 'Animais'],
    ['pig', 'porco', 'substantivo', 'The pig is dirty.', 'O porco está sujo.', 'Animais'],
    ['rabbit', 'coelho', 'substantivo', 'The rabbit is fast.', 'O coelho é rápido.', 'Animais'],
  ],
  A2: [
    ['bus', 'ônibus', 'substantivo', 'The bus is late.', 'O ônibus está atrasado.', 'Transporte'],
    ['train', 'trem', 'substantivo', 'The train leaves at eight.', 'O trem sai às oito.', 'Transporte'],
    ['car', 'carro', 'substantivo', 'My car is old.', 'Meu carro é velho.', 'Transporte'],
    ['bicycle', 'bicicleta', 'substantivo', 'I ride a bicycle.', 'Eu ando de bicicleta.', 'Transporte'],
    ['taxi', 'táxi', 'substantivo', 'Let us take a taxi.', 'Vamos pegar um táxi.', 'Transporte'],
    ['driver', 'motorista', 'substantivo', 'The driver was polite.', 'O motorista foi educado.', 'Transporte'],
    ['fare', 'tarifa (de transporte)', 'substantivo', 'The fare went up.', 'A tarifa subiu.', 'Transporte'],
    ['platform', 'plataforma', 'substantivo', 'Wait on platform two.', 'Espere na plataforma dois.', 'Transporte'],
    ['seat', 'assento', 'substantivo', 'This seat is free.', 'Este assento está livre.', 'Transporte'],
    ['journey', 'trajeto / viagem', 'substantivo', 'The journey takes two hours.', 'O trajeto leva duas horas.', 'Transporte'],
    ['hobby', 'passatempo', 'substantivo', 'Reading is my hobby.', 'Ler é meu passatempo.', 'Lazer'],
    ['museum', 'museu', 'substantivo', 'The museum is free today.', 'O museu está de graça hoje.', 'Lazer'],
    ['cinema', 'cinema', 'substantivo', 'We went to the cinema.', 'Fomos ao cinema.', 'Lazer'],
    ['concert', 'show / concerto', 'substantivo', 'The concert was great.', 'O show foi ótimo.', 'Lazer'],
    ['park', 'parque', 'substantivo', 'The park is nearby.', 'O parque fica perto.', 'Lazer'],
    ['game', 'jogo', 'substantivo', 'This game is fun.', 'Este jogo é divertido.', 'Lazer'],
    ['camera', 'câmera', 'substantivo', 'Bring your camera.', 'Traga sua câmera.', 'Lazer'],
    ['picnic', 'piquenique', 'substantivo', 'We had a picnic.', 'Fizemos um piquenique.', 'Lazer'],
    ['swim', 'nadar', 'verbo', 'I swim on Sundays.', 'Eu nado aos domingos.', 'Lazer'],
    ['dance', 'dançar', 'verbo', 'They dance very well.', 'Eles dançam muito bem.', 'Lazer'],
    ['happy', 'feliz', 'adjetivo', 'She looks happy.', 'Ela parece feliz.', 'Emoções'],
    ['sad', 'triste', 'adjetivo', 'He was sad yesterday.', 'Ele estava triste ontem.', 'Emoções'],
    ['angry', 'bravo', 'adjetivo', 'Do not be angry.', 'Não fique bravo.', 'Emoções'],
    ['afraid', 'com medo', 'adjetivo', 'I am afraid of dogs.', 'Tenho medo de cachorro.', 'Emoções'],
    ['surprised', 'surpreso', 'adjetivo', 'We were surprised.', 'Ficamos surpresos.', 'Emoções'],
    ['bored', 'entediado', 'adjetivo', 'The children are bored.', 'As crianças estão entediadas.', 'Emoções'],
    ['worried', 'preocupado', 'adjetivo', 'She is worried about it.', 'Ela está preocupada com isso.', 'Emoções'],
    ['proud', 'orgulhoso', 'adjetivo', 'I am proud of you.', 'Estou orgulhoso de você.', 'Emoções'],
    ['calm', 'calmo', 'adjetivo', 'Try to stay calm.', 'Tente ficar calmo.', 'Emoções'],
    ['lonely', 'solitário', 'adjetivo', 'He feels lonely.', 'Ele se sente solitário.', 'Emoções'],
    ['young', 'jovem', 'adjetivo', 'She is very young.', 'Ela é muito jovem.', 'Descrever pessoas'],
    ['old', 'velho', 'adjetivo', 'My grandfather is old.', 'Meu avô é velho.', 'Descrever pessoas'],
    ['kind', 'gentil', 'adjetivo', 'He is a kind man.', 'Ele é um homem gentil.', 'Descrever pessoas'],
    ['funny', 'engraçado', 'adjetivo', 'Your friend is funny.', 'Seu amigo é engraçado.', 'Descrever pessoas'],
    ['quiet', 'quieto', 'adjetivo', 'She is very quiet.', 'Ela é muito quieta.', 'Descrever pessoas'],
    ['clever', 'esperto', 'adjetivo', 'That was a clever idea.', 'Foi uma ideia esperta.', 'Descrever pessoas'],
    ['lazy', 'preguiçoso', 'adjetivo', 'Do not be lazy.', 'Não seja preguiçoso.', 'Descrever pessoas'],
    ['honest', 'honesto', 'adjetivo', 'She is always honest.', 'Ela é sempre honesta.', 'Descrever pessoas'],
    ['friendly', 'simpático', 'adjetivo', 'The staff is friendly.', 'A equipe é simpática.', 'Descrever pessoas'],
    ['strong', 'forte', 'adjetivo', 'He is very strong.', 'Ele é muito forte.', 'Descrever pessoas'],
  ],
  B1: [
    ['diet', 'alimentação / dieta', 'substantivo', 'Her diet changed a lot.', 'A alimentação dela mudou muito.', 'Saúde e bem-estar'],
    ['exercise', 'exercício', 'substantivo', 'Exercise helps with sleep.', 'Exercício ajuda no sono.', 'Saúde e bem-estar'],
    ['stress', 'estresse', 'substantivo', 'Stress affects the body.', 'O estresse afeta o corpo.', 'Saúde e bem-estar'],
    ['habit', 'hábito', 'substantivo', 'It became a habit.', 'Virou um hábito.', 'Saúde e bem-estar'],
    ['therapy', 'terapia', 'substantivo', 'Therapy helped him a lot.', 'A terapia o ajudou muito.', 'Saúde e bem-estar'],
    ['recovery', 'recuperação', 'substantivo', 'Recovery takes time.', 'A recuperação leva tempo.', 'Saúde e bem-estar'],
    ['posture', 'postura', 'substantivo', 'Fix your posture.', 'Corrija sua postura.', 'Saúde e bem-estar'],
    ['breathing', 'respiração', 'substantivo', 'Slow breathing calms you.', 'Respiração lenta acalma.', 'Saúde e bem-estar'],
    ['checkup', 'check-up', 'substantivo', 'I had a checkup today.', 'Fiz um check-up hoje.', 'Saúde e bem-estar'],
    ['wellbeing', 'bem-estar', 'substantivo', 'They care about wellbeing.', 'Eles se importam com o bem-estar.', 'Saúde e bem-estar'],
    ['rent', 'aluguel', 'substantivo', 'The rent went up again.', 'O aluguel subiu de novo.', 'Moradia'],
    ['lease', 'contrato de locação', 'substantivo', 'The lease ends in June.', 'O contrato de locação acaba em junho.', 'Moradia'],
    ['deposit', 'caução', 'substantivo', 'They kept the deposit.', 'Eles ficaram com a caução.', 'Moradia'],
    ['tenant', 'inquilino', 'substantivo', 'The tenant complained.', 'O inquilino reclamou.', 'Moradia'],
    ['ceiling', 'teto', 'substantivo', 'The ceiling is leaking.', 'O teto está vazando.', 'Moradia'],
    ['roof', 'telhado', 'substantivo', 'The roof needs repair.', 'O telhado precisa de conserto.', 'Moradia'],
    ['basement', 'porão', 'substantivo', 'The basement is damp.', 'O porão está úmido.', 'Moradia'],
    ['balcony', 'varanda', 'substantivo', 'We eat on the balcony.', 'Comemos na varanda.', 'Moradia'],
    ['plumbing', 'encanamento', 'substantivo', 'The plumbing is old.', 'O encanamento é velho.', 'Moradia'],
    ['landlady', 'senhoria', 'substantivo', 'The landlady called me.', 'A senhoria me ligou.', 'Moradia'],
    ['recipe', 'receita', 'substantivo', 'Send me the recipe.', 'Me manda a receita.', 'Culinária'],
    ['ingredient', 'ingrediente', 'substantivo', 'One ingredient is missing.', 'Falta um ingrediente.', 'Culinária'],
    ['boil', 'ferver', 'verbo', 'Boil the water first.', 'Ferva a água primeiro.', 'Culinária'],
    ['fry', 'fritar', 'verbo', 'Fry the onions slowly.', 'Frite a cebola devagar.', 'Culinária'],
    ['bake', 'assar', 'verbo', 'Bake it for an hour.', 'Asse por uma hora.', 'Culinária'],
    ['chop', 'picar', 'verbo', 'Chop the garlic finely.', 'Pique o alho bem fino.', 'Culinária'],
    ['season', 'temperar', 'verbo', 'Season it with pepper.', 'Tempere com pimenta.', 'Culinária'],
    ['dough', 'massa (crua)', 'substantivo', 'The dough must rest.', 'A massa precisa descansar.', 'Culinária'],
    ['roast', 'assar (carne)', 'verbo', 'We roast the meat slowly.', 'Assamos a carne devagar.', 'Culinária'],
    ['steam', 'cozinhar no vapor', 'verbo', 'Steam the vegetables.', 'Cozinhe os legumes no vapor.', 'Culinária'],
    ['message', 'mensagem', 'substantivo', 'I got your message.', 'Recebi sua mensagem.', 'Comunicação'],
    ['reply', 'resposta', 'substantivo', 'I am waiting for a reply.', 'Estou esperando uma resposta.', 'Comunicação'],
    ['notice', 'aviso', 'substantivo', 'There is a notice on the door.', 'Há um aviso na porta.', 'Comunicação'],
    ['announcement', 'anúncio / comunicado', 'substantivo', 'They made an announcement.', 'Fizeram um comunicado.', 'Comunicação'],
    ['rumor', 'boato', 'substantivo', 'It is only a rumor.', 'É só um boato.', 'Comunicação'],
    ['statement', 'declaração', 'substantivo', 'She released a statement.', 'Ela divulgou uma declaração.', 'Comunicação'],
    ['explain', 'explicar', 'verbo', 'Explain it again, please.', 'Explique de novo, por favor.', 'Comunicação'],
    ['describe', 'descrever', 'verbo', 'Describe what you saw.', 'Descreva o que você viu.', 'Comunicação'],
    ['summarize', 'resumir', 'verbo', 'Summarize it in one line.', 'Resuma em uma linha.', 'Comunicação'],
    ['misunderstanding', 'mal-entendido', 'substantivo', 'It was a misunderstanding.', 'Foi um mal-entendido.', 'Comunicação'],
  ],
  B2: [
    ['sculpture', 'escultura', 'substantivo', 'The sculpture is bronze.', 'A escultura é de bronze.', 'Arte e cultura'],
    ['exhibition', 'exposição', 'substantivo', 'The exhibition opens Friday.', 'A exposição abre sexta.', 'Arte e cultura'],
    ['portrait', 'retrato', 'substantivo', 'She painted a portrait.', 'Ela pintou um retrato.', 'Arte e cultura'],
    ['canvas', 'tela (de pintura)', 'substantivo', 'The canvas was blank.', 'A tela estava em branco.', 'Arte e cultura'],
    ['orchestra', 'orquestra', 'substantivo', 'The orchestra rehearsed.', 'A orquestra ensaiou.', 'Arte e cultura'],
    ['choir', 'coral', 'substantivo', 'She sings in a choir.', 'Ela canta num coral.', 'Arte e cultura'],
    ['playwright', 'dramaturgo', 'substantivo', 'The playwright is famous.', 'O dramaturgo é famoso.', 'Arte e cultura'],
    ['novelist', 'romancista', 'substantivo', 'She is a young novelist.', 'Ela é uma jovem romancista.', 'Arte e cultura'],
    ['folklore', 'folclore', 'substantivo', 'Local folklore is rich.', 'O folclore local é rico.', 'Arte e cultura'],
    ['heritage', 'patrimônio', 'substantivo', 'It is a heritage site.', 'É um sítio de patrimônio.', 'Arte e cultura'],
    ['empire', 'império', 'substantivo', 'The empire collapsed.', 'O império ruiu.', 'História'],
    ['revolution', 'revolução', 'substantivo', 'The revolution changed everything.', 'A revolução mudou tudo.', 'História'],
    ['treaty', 'tratado', 'substantivo', 'They signed a treaty.', 'Assinaram um tratado.', 'História'],
    ['colony', 'colônia', 'substantivo', 'It was once a colony.', 'Já foi uma colônia.', 'História'],
    ['dynasty', 'dinastia', 'substantivo', 'The dynasty lasted centuries.', 'A dinastia durou séculos.', 'História'],
    ['uprising', 'levante', 'substantivo', 'The uprising was crushed.', 'O levante foi esmagado.', 'História'],
    ['siege', 'cerco', 'substantivo', 'The siege lasted a year.', 'O cerco durou um ano.', 'História'],
    ['archive', 'arquivo histórico', 'substantivo', 'The archive holds the letters.', 'O arquivo guarda as cartas.', 'História'],
    ['chronicle', 'crônica histórica', 'substantivo', 'The chronicle names him.', 'A crônica o nomeia.', 'História'],
    ['artifact', 'artefato', 'substantivo', 'They found an artifact.', 'Encontraram um artefato.', 'História'],
    ['continent', 'continente', 'substantivo', 'It is the largest continent.', 'É o maior continente.', 'Geografia'],
    ['peninsula', 'península', 'substantivo', 'The peninsula is rocky.', 'A península é rochosa.', 'Geografia'],
    ['plateau', 'planalto', 'substantivo', 'The plateau is dry.', 'O planalto é seco.', 'Geografia'],
    ['glacier', 'geleira', 'substantivo', 'The glacier is retreating.', 'A geleira está recuando.', 'Geografia'],
    ['delta', 'delta (de rio)', 'substantivo', 'The delta is fertile.', 'O delta é fértil.', 'Geografia'],
    ['valley', 'vale', 'substantivo', 'The valley floods often.', 'O vale alaga com frequência.', 'Geografia'],
    ['desert', 'deserto', 'substantivo', 'The desert is expanding.', 'O deserto está avançando.', 'Geografia'],
    ['tide', 'maré', 'substantivo', 'The tide is coming in.', 'A maré está subindo.', 'Geografia'],
    ['latitude', 'latitude', 'substantivo', 'Check the latitude first.', 'Confira a latitude primeiro.', 'Geografia'],
    ['terrain', 'terreno', 'substantivo', 'The terrain is difficult.', 'O terreno é difícil.', 'Geografia'],
    ['integrity', 'integridade', 'substantivo', 'His integrity is unquestioned.', 'A integridade dele é inquestionável.', 'Ética'],
    ['virtue', 'virtude', 'substantivo', 'Patience is a virtue.', 'A paciência é uma virtude.', 'Ética'],
    ['duty', 'dever', 'substantivo', 'It is your duty to report it.', 'É seu dever relatar isso.', 'Ética'],
    ['consent', 'consentimento', 'substantivo', 'They acted without consent.', 'Agiram sem consentimento.', 'Ética'],
    ['fairness', 'justiça / equidade', 'substantivo', 'Fairness matters here.', 'A equidade importa aqui.', 'Ética'],
    ['harm', 'dano', 'substantivo', 'The policy caused real harm.', 'A política causou dano real.', 'Ética'],
    ['dignity', 'dignidade', 'substantivo', 'Treat them with dignity.', 'Trate-os com dignidade.', 'Ética'],
    ['obligation', 'obrigação', 'substantivo', 'We have an obligation.', 'Temos uma obrigação.', 'Ética'],
    ['misconduct', 'má conduta', 'substantivo', 'He was fired for misconduct.', 'Foi demitido por má conduta.', 'Ética'],
    ['whistleblower', 'denunciante', 'substantivo', 'The whistleblower was protected.', 'O denunciante foi protegido.', 'Ética'],
  ],
  C1: [
    ['bureaucracy', 'burocracia', 'substantivo', 'Bureaucracy slowed everything.', 'A burocracia atrasou tudo.', 'Administração pública'],
    ['ordinance', 'decreto municipal', 'substantivo', 'A new ordinance passed.', 'Um novo decreto foi aprovado.', 'Administração pública'],
    ['compliance', 'conformidade', 'substantivo', 'Compliance is mandatory.', 'A conformidade é obrigatória.', 'Administração pública'],
    ['oversight', 'fiscalização', 'substantivo', 'Oversight was weak.', 'A fiscalização era fraca.', 'Administração pública'],
    ['protocol', 'protocolo', 'substantivo', 'Follow the protocol exactly.', 'Siga o protocolo à risca.', 'Administração pública'],
    ['directive', 'diretriz', 'substantivo', 'The directive takes effect today.', 'A diretriz entra em vigor hoje.', 'Administração pública'],
    ['quorum', 'quórum', 'substantivo', 'We did not reach a quorum.', 'Não atingimos o quórum.', 'Administração pública'],
    ['tenure', 'estabilidade no cargo', 'substantivo', 'She was granted tenure.', 'Ela obteve estabilidade no cargo.', 'Administração pública'],
    ['remit', 'alçada / competência', 'substantivo', 'That is outside our remit.', 'Isso está fora da nossa alçada.', 'Administração pública'],
    ['redress', 'reparação', 'substantivo', 'They sought legal redress.', 'Buscaram reparação judicial.', 'Administração pública'],
    ['median', 'mediana', 'substantivo', 'The median is more useful here.', 'A mediana é mais útil aqui.', 'Estatística'],
    ['variance', 'variância', 'substantivo', 'The variance is too high.', 'A variância é alta demais.', 'Estatística'],
    ['deviation', 'desvio', 'substantivo', 'Report the standard deviation.', 'Informe o desvio padrão.', 'Estatística'],
    ['regression', 'regressão', 'substantivo', 'The regression explains little.', 'A regressão explica pouco.', 'Estatística'],
    ['probability', 'probabilidade', 'substantivo', 'The probability is low.', 'A probabilidade é baixa.', 'Estatística'],
    ['distribution', 'distribuição', 'substantivo', 'The distribution is skewed.', 'A distribuição é assimétrica.', 'Estatística'],
    ['outlier', 'ponto fora da curva', 'substantivo', 'Remove that outlier.', 'Remova esse ponto fora da curva.', 'Estatística'],
    ['significance', 'significância', 'substantivo', 'Statistical significance is not importance.', 'Significância estatística não é importância.', 'Estatística'],
    ['threshold', 'limiar', 'substantivo', 'It fell below the threshold.', 'Ficou abaixo do limiar.', 'Estatística'],
    ['estimate', 'estimativa', 'substantivo', 'That is a rough estimate.', 'É uma estimativa aproximada.', 'Estatística'],
    ['syntax', 'sintaxe', 'substantivo', 'The syntax differs here.', 'A sintaxe difere aqui.', 'Linguística'],
    ['morpheme', 'morfema', 'substantivo', 'That prefix is one morpheme.', 'Esse prefixo é um morfema.', 'Linguística'],
    ['phoneme', 'fonema', 'substantivo', 'The two phonemes contrast.', 'Os dois fonemas contrastam.', 'Linguística'],
    ['semantics', 'semântica', 'substantivo', 'The dispute is about semantics.', 'A disputa é de semântica.', 'Linguística'],
    ['dialect', 'dialeto', 'substantivo', 'The dialect varies by region.', 'O dialeto varia por região.', 'Linguística'],
    ['register', 'registro (de fala)', 'substantivo', 'Match the register to the setting.', 'Ajuste o registro ao contexto.', 'Linguística'],
    ['etymology', 'etimologia', 'substantivo', 'The etymology is disputed.', 'A etimologia é contestada.', 'Linguística'],
    ['cognate', 'cognato', 'substantivo', 'These two words are cognates.', 'Estas duas palavras são cognatas.', 'Linguística'],
    ['inflection', 'flexão', 'substantivo', 'The inflection marks the case.', 'A flexão marca o caso.', 'Linguística'],
    ['fluency', 'fluência', 'substantivo', 'Fluency is not accuracy.', 'Fluência não é correção.', 'Linguística'],
    ['facade', 'fachada', 'substantivo', 'The facade was restored.', 'A fachada foi restaurada.', 'Arquitetura'],
    ['foundation', 'fundação (de obra)', 'substantivo', 'The foundation cracked.', 'A fundação rachou.', 'Arquitetura'],
    ['blueprint', 'planta / projeto', 'substantivo', 'Check the blueprint again.', 'Confira a planta de novo.', 'Arquitetura'],
    ['vault', 'abóbada', 'substantivo', 'The vault is medieval.', 'A abóbada é medieval.', 'Arquitetura'],
    ['scaffold', 'andaime', 'substantivo', 'The scaffold went up today.', 'O andaime subiu hoje.', 'Arquitetura'],
    ['zoning', 'zoneamento', 'substantivo', 'Zoning rules blocked it.', 'As regras de zoneamento impediram.', 'Arquitetura'],
    ['renovation', 'reforma', 'substantivo', 'The renovation took a year.', 'A reforma levou um ano.', 'Arquitetura'],
    ['load-bearing', 'estrutural (que sustenta)', 'adjetivo', 'That is a load-bearing wall.', 'Aquela é uma parede estrutural.', 'Arquitetura'],
    ['sprawl', 'expansão urbana desordenada', 'substantivo', 'Urban sprawl keeps growing.', 'A expansão urbana desordenada só cresce.', 'Arquitetura'],
    ['skyline', 'silhueta urbana', 'substantivo', 'The skyline changed completely.', 'A silhueta da cidade mudou por completo.', 'Arquitetura'],
  ],
  C2: [
    ['détente', 'distensão (diplomática)', 'substantivo', 'The détente did not last.', 'A distensão não durou.', 'Diplomacia'],
    ['rapprochement', 'reaproximação', 'substantivo', 'A cautious rapprochement began.', 'Começou uma reaproximação cautelosa.', 'Diplomacia'],
    ['communiqué', 'comunicado oficial', 'substantivo', 'The communiqué said little.', 'O comunicado dizia pouco.', 'Diplomacia'],
    ['envoy', 'emissário', 'substantivo', 'An envoy was dispatched.', 'Um emissário foi enviado.', 'Diplomacia'],
    ['accord', 'acordo formal', 'substantivo', 'The accord holds for now.', 'O acordo se mantém por ora.', 'Diplomacia'],
    ['sanction', 'sanção', 'substantivo', 'The sanctions were lifted.', 'As sanções foram suspensas.', 'Diplomacia'],
    ['neutrality', 'neutralidade', 'substantivo', 'They declared neutrality.', 'Declararam neutralidade.', 'Diplomacia'],
    ['sovereignty', 'soberania', 'substantivo', 'Sovereignty was the sticking point.', 'A soberania foi o ponto de impasse.', 'Diplomacia'],
    ['reciprocity', 'reciprocidade', 'substantivo', 'The deal rests on reciprocity.', 'O acordo se apoia na reciprocidade.', 'Diplomacia'],
    ['brinkmanship', 'política do abismo', 'substantivo', 'This is pure brinkmanship.', 'Isso é pura política do abismo.', 'Diplomacia'],
    ['theodicy', 'teodiceia', 'substantivo', 'Theodicy asks why evil exists.', 'A teodiceia pergunta por que o mal existe.', 'Teologia e mito'],
    ['apotheosis', 'apoteose', 'substantivo', 'It was the apotheosis of the style.', 'Foi a apoteose do estilo.', 'Teologia e mito'],
    ['eschatology', 'escatologia', 'substantivo', 'Eschatology deals with last things.', 'A escatologia trata das coisas últimas.', 'Teologia e mito'],
    ['liturgy', 'liturgia', 'substantivo', 'The liturgy is centuries old.', 'A liturgia tem séculos.', 'Teologia e mito'],
    ['heresy', 'heresia', 'substantivo', 'It was condemned as heresy.', 'Foi condenado como heresia.', 'Teologia e mito'],
    ['pantheon', 'panteão', 'substantivo', 'She entered the pantheon of greats.', 'Ela entrou no panteão dos grandes.', 'Teologia e mito'],
    ['oracle', 'oráculo', 'substantivo', 'The oracle spoke in riddles.', 'O oráculo falava por enigmas.', 'Teologia e mito'],
    ['relic', 'relíquia', 'substantivo', 'The relic drew pilgrims.', 'A relíquia atraía peregrinos.', 'Teologia e mito'],
    ['schism', 'cisma', 'substantivo', 'The schism split the church.', 'O cisma dividiu a igreja.', 'Teologia e mito'],
    ['transcendence', 'transcendência', 'substantivo', 'The poem reaches for transcendence.', 'O poema busca a transcendência.', 'Teologia e mito'],
    ['a priori', 'a priori', 'advérbio', 'You cannot know that a priori.', 'Isso não se sabe a priori.', 'Locuções cultas'],
    ['a fortiori', 'com mais razão ainda', 'advérbio', 'A fortiori, the second case fails.', 'Com mais razão ainda, o segundo caso não se sustenta.', 'Locuções cultas'],
    ['sine qua non', 'condição indispensável', 'substantivo', 'Trust is the sine qua non here.', 'Confiança é a condição indispensável aqui.', 'Locuções cultas'],
    ['de facto', 'de fato', 'adjetivo', 'She is the de facto leader.', 'Ela é a líder de fato.', 'Locuções cultas'],
    ['ad hoc', 'ad hoc / improvisado', 'adjetivo', 'It was an ad hoc committee.', 'Era um comitê ad hoc.', 'Locuções cultas'],
    ['mutatis mutandis', 'feitas as devidas adaptações', 'advérbio', 'The same applies, mutatis mutandis.', 'O mesmo vale, feitas as devidas adaptações.', 'Locuções cultas'],
    ['ceteris paribus', 'mantidas as demais condições', 'advérbio', 'Ceteris paribus, demand will fall.', 'Mantidas as demais condições, a procura vai cair.', 'Locuções cultas'],
    ['prima facie', 'à primeira vista', 'adjetivo', 'There is a prima facie case.', 'Há indício suficiente à primeira vista.', 'Locuções cultas'],
    ['per se', 'em si mesmo', 'advérbio', 'The rule is not unfair per se.', 'A regra não é injusta em si mesma.', 'Locuções cultas'],
    ['in extremis', 'em situação extrema', 'advérbio', 'The deal was saved in extremis.', 'O acordo foi salvo em situação extrema.', 'Locuções cultas'],
    ['wistfulness', 'saudade melancólica', 'substantivo', 'She spoke with wistfulness.', 'Ela falou com uma saudade melancólica.', 'Emoções sutis'],
    ['melancholy', 'melancolia', 'substantivo', 'A quiet melancholy runs through it.', 'Uma melancolia discreta o atravessa.', 'Emoções sutis'],
    ['ennui', 'tédio existencial', 'substantivo', 'The ennui of long afternoons.', 'O tédio existencial das tardes longas.', 'Emoções sutis'],
    ['elation', 'euforia', 'substantivo', 'His elation was short-lived.', 'A euforia dele durou pouco.', 'Emoções sutis'],
    ['disquiet', 'inquietação', 'substantivo', 'The news caused real disquiet.', 'A notícia causou verdadeira inquietação.', 'Emoções sutis'],
    ['yearning', 'anseio', 'substantivo', 'A yearning for something lost.', 'Um anseio por algo perdido.', 'Emoções sutis'],
    ['serenity', 'serenidade', 'substantivo', 'She faced it with serenity.', 'Ela encarou com serenidade.', 'Emoções sutis'],
    ['indignation', 'indignação', 'substantivo', 'His indignation was justified.', 'A indignação dele era justificada.', 'Emoções sutis'],
    ['reverie', 'devaneio', 'substantivo', 'She drifted into reverie.', 'Ela caiu num devaneio.', 'Emoções sutis'],
    ['solace', 'consolo', 'substantivo', 'He found solace in music.', 'Ele encontrou consolo na música.', 'Emoções sutis'],
  ],
};
