/** Espanhol — segundo lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const ES_THEMATIC2: LatinByLevel = {
  A1: [
    ['uno', 'um', 'numeral', 'Quiero una manzana.', 'Quero uma maçã.', 'Números e quantidade'],
    ['dos', 'dois', 'numeral', 'Tiene dos hermanos.', 'Ela tem dois irmãos.', 'Números e quantidade'],
    ['tres', 'três', 'numeral', 'Esperamos tres horas.', 'Esperamos três horas.', 'Números e quantidade'],
    ['muchos', 'muitos', 'determinante', 'Hay muchas personas.', 'Há muitas pessoas.', 'Números e quantidade'],
    ['pocos', 'poucos', 'determinante', 'Vinieron pocos alumnos.', 'Vieram poucos alunos.', 'Números e quantidade'],
    ['la mitad', 'metade', 'substantivo', 'Me comí la mitad.', 'Comi metade.', 'Números e quantidade'],
    ['vacío', 'vazio', 'adjetivo', 'La botella está vacía.', 'A garrafa está vazia.', 'Números e quantidade'],
    ['pesado', 'pesado', 'adjetivo', 'Esta caja es pesada.', 'Esta caixa é pesada.', 'Números e quantidade'],
    ['ligero', 'leve', 'adjetivo', 'El bolso es ligero.', 'A bolsa é leve.', 'Números e quantidade'],
    ['el número', 'número', 'substantivo', 'Dime tu número.', 'Me diga seu número.', 'Números e quantidade'],
    ['despertarse', 'acordar', 'verbo', 'Me despierto a las seis.', 'Eu acordo às seis.', 'Ações do dia a dia'],
    ['dormir', 'dormir', 'verbo', 'Duermo ocho horas.', 'Eu durmo oito horas.', 'Ações do dia a dia'],
    ['lavar', 'lavar', 'verbo', 'Lávate las manos.', 'Lave as mãos.', 'Ações do dia a dia'],
    ['cocinar', 'cozinhar', 'verbo', 'Ella cocina cada noche.', 'Ela cozinha toda noite.', 'Ações do dia a dia'],
    ['limpiar', 'limpar', 'verbo', 'Limpio la casa.', 'Eu limpo a casa.', 'Ações do dia a dia'],
    ['comprar', 'comprar', 'verbo', 'Compro pan aquí.', 'Eu compro pão aqui.', 'Ações do dia a dia'],
    ['vender', 'vender', 'verbo', 'Venden fruta.', 'Eles vendem fruta.', 'Ações do dia a dia'],
    ['caminar', 'caminhar', 'verbo', 'Caminamos a la escuela.', 'Nós caminhamos até a escola.', 'Ações do dia a dia'],
    ['correr', 'correr', 'verbo', 'Él corre rápido.', 'Ele corre rápido.', 'Ações do dia a dia'],
    ['esperar', 'esperar', 'verbo', 'Espera aquí, por favor.', 'Espere aqui, por favor.', 'Ações do dia a dia'],
    ['el profesor', 'professor', 'substantivo', 'El profesor es amable.', 'O professor é gentil.', 'Escola'],
    ['el alumno', 'aluno', 'substantivo', 'Es un buen alumno.', 'Ele é um bom aluno.', 'Escola'],
    ['el libro', 'livro', 'substantivo', 'Este libro es largo.', 'Este livro é longo.', 'Escola'],
    ['el bolígrafo', 'caneta', 'substantivo', 'Necesito un bolígrafo.', 'Preciso de uma caneta.', 'Escola'],
    ['el papel', 'papel', 'substantivo', 'Dame un papel.', 'Me dê um papel.', 'Escola'],
    ['la clase', 'aula', 'substantivo', 'La clase empieza ahora.', 'A aula começa agora.', 'Escola'],
    ['los deberes', 'lição de casa', 'substantivo', 'Terminé los deberes.', 'Terminei a lição de casa.', 'Escola'],
    ['el examen', 'prova', 'substantivo', 'El examen fue difícil.', 'A prova foi difícil.', 'Escola'],
    ['el aula', 'sala de aula', 'substantivo', 'El aula es grande.', 'A sala de aula é grande.', 'Escola'],
    ['la pregunta', 'pergunta', 'substantivo', 'Tengo una pregunta.', 'Tenho uma pergunta.', 'Escola'],
    ['el pájaro', 'pássaro', 'substantivo', 'Un pájaro está cantando.', 'Um pássaro está cantando.', 'Animais'],
    ['el pez', 'peixe', 'substantivo', 'El pez es pequeño.', 'O peixe é pequeno.', 'Animais'],
    ['el caballo', 'cavalo', 'substantivo', 'El caballo es rápido.', 'O cavalo é rápido.', 'Animais'],
    ['la vaca', 'vaca', 'substantivo', 'La vaca come hierba.', 'A vaca come grama.', 'Animais'],
    ['la gallina', 'galinha', 'substantivo', 'Tenemos tres gallinas.', 'Temos três galinhas.', 'Animais'],
    ['el ratón', 'rato', 'substantivo', 'Hay un ratón aquí.', 'Tem um rato aqui.', 'Animais'],
    ['el insecto', 'inseto', 'substantivo', 'Entró un insecto.', 'Entrou um inseto.', 'Animais'],
    ['la oveja', 'ovelha', 'substantivo', 'Las ovejas son blancas.', 'As ovelhas são brancas.', 'Animais'],
    ['el cerdo', 'porco', 'substantivo', 'El cerdo está sucio.', 'O porco está sujo.', 'Animais'],
    ['el conejo', 'coelho', 'substantivo', 'El conejo es rápido.', 'O coelho é rápido.', 'Animais'],
  ],
  A2: [
    ['el autobús', 'ônibus', 'substantivo', 'El autobús llega tarde.', 'O ônibus está atrasado.', 'Transporte'],
    ['el tren', 'trem', 'substantivo', 'El tren sale a las ocho.', 'O trem sai às oito.', 'Transporte'],
    ['el coche', 'carro', 'substantivo', 'Mi coche es viejo.', 'Meu carro é velho.', 'Transporte'],
    ['la bicicleta', 'bicicleta', 'substantivo', 'Voy en bicicleta.', 'Eu vou de bicicleta.', 'Transporte'],
    ['el taxi', 'táxi', 'substantivo', 'Cojamos un taxi.', 'Vamos pegar um táxi.', 'Transporte'],
    ['el conductor', 'motorista', 'substantivo', 'El conductor fue educado.', 'O motorista foi educado.', 'Transporte'],
    ['la tarifa', 'tarifa', 'substantivo', 'La tarifa subió.', 'A tarifa subiu.', 'Transporte'],
    ['el andén', 'plataforma', 'substantivo', 'Espera en el andén dos.', 'Espere na plataforma dois.', 'Transporte'],
    ['el asiento', 'assento', 'substantivo', 'Este asiento está libre.', 'Este assento está livre.', 'Transporte'],
    ['el recorrido', 'percurso', 'substantivo', 'El recorrido dura dos horas.', 'O percurso dura duas horas.', 'Transporte'],
    ['el pasatiempo', 'passatempo', 'substantivo', 'Leer es mi pasatiempo.', 'Ler é meu passatempo.', 'Lazer'],
    ['el museo', 'museu', 'substantivo', 'El museo es gratis hoy.', 'O museu está de graça hoje.', 'Lazer'],
    ['el cine', 'cinema', 'substantivo', 'Fuimos al cine.', 'Fomos ao cinema.', 'Lazer'],
    ['el concierto', 'show / concerto', 'substantivo', 'El concierto fue genial.', 'O show foi ótimo.', 'Lazer'],
    ['el parque', 'parque', 'substantivo', 'El parque está cerca.', 'O parque fica perto.', 'Lazer'],
    ['el juego', 'jogo', 'substantivo', 'Este juego es divertido.', 'Este jogo é divertido.', 'Lazer'],
    ['la cámara', 'câmera', 'substantivo', 'Trae tu cámara.', 'Traga sua câmera.', 'Lazer'],
    ['el picnic', 'piquenique', 'substantivo', 'Hicimos un picnic.', 'Fizemos um piquenique.', 'Lazer'],
    ['nadar', 'nadar', 'verbo', 'Nado los domingos.', 'Eu nado aos domingos.', 'Lazer'],
    ['bailar', 'dançar', 'verbo', 'Bailan muy bien.', 'Eles dançam muito bem.', 'Lazer'],
    ['feliz', 'feliz', 'adjetivo', 'Parece feliz.', 'Ela parece feliz.', 'Emoções'],
    ['triste', 'triste', 'adjetivo', 'Ayer estaba triste.', 'Ele estava triste ontem.', 'Emoções'],
    ['enfadado', 'bravo', 'adjetivo', 'No te pongas enfadado.', 'Não fique bravo.', 'Emoções'],
    ['asustado', 'com medo', 'adjetivo', 'Estoy asustado.', 'Estou com medo.', 'Emoções'],
    ['sorprendido', 'surpreso', 'adjetivo', 'Nos quedamos sorprendidos.', 'Ficamos surpresos.', 'Emoções'],
    ['aburrido', 'entediado', 'adjetivo', 'Los niños están aburridos.', 'As crianças estão entediadas.', 'Emoções'],
    ['preocupado', 'preocupado', 'adjetivo', 'Está preocupada por eso.', 'Ela está preocupada com isso.', 'Emoções'],
    ['orgulloso', 'orgulhoso', 'adjetivo', 'Estoy orgulloso de ti.', 'Estou orgulhoso de você.', 'Emoções'],
    ['tranquilo', 'calmo', 'adjetivo', 'Intenta estar tranquilo.', 'Tente ficar calmo.', 'Emoções'],
    ['solo', 'sozinho / solitário', 'adjetivo', 'Se siente muy solo.', 'Ele se sente muito sozinho.', 'Emoções'],
    ['joven', 'jovem', 'adjetivo', 'Ella es muy joven.', 'Ela é muito jovem.', 'Descrever pessoas'],
    ['viejo', 'velho', 'adjetivo', 'Mi abuelo es viejo.', 'Meu avô é velho.', 'Descrever pessoas'],
    ['amable', 'gentil', 'adjetivo', 'Es un hombre amable.', 'Ele é um homem gentil.', 'Descrever pessoas'],
    ['gracioso', 'engraçado', 'adjetivo', 'Tu amigo es gracioso.', 'Seu amigo é engraçado.', 'Descrever pessoas'],
    ['callado', 'quieto / calado', 'adjetivo', 'Es muy callada.', 'Ela é muito quieta.', 'Descrever pessoas'],
    ['listo', 'esperto', 'adjetivo', 'Fue una idea lista.', 'Foi uma ideia esperta.', 'Descrever pessoas'],
    ['perezoso', 'preguiçoso', 'adjetivo', 'No seas perezoso.', 'Não seja preguiçoso.', 'Descrever pessoas'],
    ['honesto', 'honesto', 'adjetivo', 'Siempre es honesta.', 'Ela é sempre honesta.', 'Descrever pessoas'],
    ['simpático', 'simpático', 'adjetivo', 'El equipo es simpático.', 'A equipe é simpática.', 'Descrever pessoas'],
    ['fuerte', 'forte', 'adjetivo', 'Es muy fuerte.', 'Ele é muito forte.', 'Descrever pessoas'],
  ],
  B1: [
    ['la alimentación', 'alimentação', 'substantivo', 'Su alimentación cambió mucho.', 'A alimentação dela mudou muito.', 'Saúde e bem-estar'],
    ['el ejercicio', 'exercício', 'substantivo', 'El ejercicio ayuda a dormir.', 'O exercício ajuda a dormir.', 'Saúde e bem-estar'],
    ['el estrés', 'estresse', 'substantivo', 'El estrés afecta al cuerpo.', 'O estresse afeta o corpo.', 'Saúde e bem-estar'],
    ['el hábito', 'hábito', 'substantivo', 'Se convirtió en un hábito.', 'Virou um hábito.', 'Saúde e bem-estar'],
    ['la terapia', 'terapia', 'substantivo', 'La terapia lo ayudó mucho.', 'A terapia o ajudou muito.', 'Saúde e bem-estar'],
    ['la recuperación', 'recuperação', 'substantivo', 'La recuperación lleva tiempo.', 'A recuperação leva tempo.', 'Saúde e bem-estar'],
    ['la postura', 'postura', 'substantivo', 'Corrige la postura.', 'Corrija a postura.', 'Saúde e bem-estar'],
    ['la respiración', 'respiração', 'substantivo', 'La respiración lenta calma.', 'A respiração lenta acalma.', 'Saúde e bem-estar'],
    ['la revisión médica', 'check-up', 'substantivo', 'Hoy tuve una revisión médica.', 'Hoje fiz um check-up.', 'Saúde e bem-estar'],
    ['el bienestar', 'bem-estar', 'substantivo', 'Les importa el bienestar.', 'Eles se importam com o bem-estar.', 'Saúde e bem-estar'],
    ['el alquiler', 'aluguel', 'substantivo', 'El alquiler subió otra vez.', 'O aluguel subiu de novo.', 'Moradia'],
    ['el contrato de arrendamiento', 'contrato de locação', 'substantivo', 'El contrato de arrendamiento acaba en junio.', 'O contrato de locação acaba em junho.', 'Moradia'],
    ['la fianza', 'caução', 'substantivo', 'Se quedaron con la fianza.', 'Ficaram com a caução.', 'Moradia'],
    ['el inquilino', 'inquilino', 'substantivo', 'El inquilino se quejó.', 'O inquilino reclamou.', 'Moradia'],
    ['el techo', 'teto', 'substantivo', 'El techo tiene goteras.', 'O teto está vazando.', 'Moradia'],
    ['el tejado', 'telhado', 'substantivo', 'El tejado necesita arreglo.', 'O telhado precisa de conserto.', 'Moradia'],
    ['el sótano', 'porão', 'substantivo', 'El sótano está húmedo.', 'O porão está úmido.', 'Moradia'],
    ['el balcón', 'varanda', 'substantivo', 'Comemos en el balcón.', 'Comemos na varanda.', 'Moradia'],
    ['la fontanería', 'encanamento', 'substantivo', 'La fontanería es antigua.', 'O encanamento é antigo.', 'Moradia'],
    ['la casera', 'senhoria', 'substantivo', 'La casera me llamó.', 'A senhoria me ligou.', 'Moradia'],
    ['la receta', 'receita', 'substantivo', 'Mándame la receta.', 'Me manda a receita.', 'Culinária'],
    ['el ingrediente', 'ingrediente', 'substantivo', 'Falta un ingrediente.', 'Falta um ingrediente.', 'Culinária'],
    ['hervir', 'ferver', 'verbo', 'Hierve el agua primero.', 'Ferva a água primeiro.', 'Culinária'],
    ['freír', 'fritar', 'verbo', 'Fríe la cebolla despacio.', 'Frite a cebola devagar.', 'Culinária'],
    ['hornear', 'assar (no forno)', 'verbo', 'Hornéalo una hora.', 'Asse por uma hora.', 'Culinária'],
    ['picar', 'picar', 'verbo', 'Pica el ajo muy fino.', 'Pique o alho bem fino.', 'Culinária'],
    ['sazonar', 'temperar', 'verbo', 'Sazona con pimienta.', 'Tempere com pimenta.', 'Culinária'],
    ['la masa', 'massa (crua)', 'substantivo', 'La masa debe reposar.', 'A massa precisa descansar.', 'Culinária'],
    ['asar', 'assar (carne)', 'verbo', 'Asamos la carne despacio.', 'Assamos a carne devagar.', 'Culinária'],
    ['cocer al vapor', 'cozinhar no vapor', 'verbo', 'Cuece las verduras al vapor.', 'Cozinhe os legumes no vapor.', 'Culinária'],
    ['el mensaje', 'mensagem', 'substantivo', 'Recibí tu mensaje.', 'Recebi sua mensagem.', 'Comunicação'],
    ['la respuesta', 'resposta', 'substantivo', 'Espero una respuesta.', 'Estou esperando uma resposta.', 'Comunicação'],
    ['el aviso', 'aviso', 'substantivo', 'Hay un aviso en la puerta.', 'Há um aviso na porta.', 'Comunicação'],
    ['el comunicado', 'comunicado', 'substantivo', 'Hicieron un comunicado.', 'Fizeram um comunicado.', 'Comunicação'],
    ['el rumor', 'boato', 'substantivo', 'Es solo un rumor.', 'É só um boato.', 'Comunicação'],
    ['la declaración', 'declaração', 'substantivo', 'Publicó una declaración.', 'Ela divulgou uma declaração.', 'Comunicação'],
    ['explicar', 'explicar', 'verbo', 'Explícalo otra vez, por favor.', 'Explique de novo, por favor.', 'Comunicação'],
    ['describir', 'descrever', 'verbo', 'Describe lo que viste.', 'Descreva o que você viu.', 'Comunicação'],
    ['resumir', 'resumir', 'verbo', 'Resúmelo en una línea.', 'Resuma em uma linha.', 'Comunicação'],
    ['el malentendido', 'mal-entendido', 'substantivo', 'Fue un malentendido.', 'Foi um mal-entendido.', 'Comunicação'],
  ],
  B2: [
    ['la escultura', 'escultura', 'substantivo', 'La escultura es de bronce.', 'A escultura é de bronze.', 'Arte e cultura'],
    ['la exposición', 'exposição', 'substantivo', 'La exposición abre el viernes.', 'A exposição abre sexta.', 'Arte e cultura'],
    ['el retrato', 'retrato', 'substantivo', 'Pintó un retrato.', 'Ela pintou um retrato.', 'Arte e cultura'],
    ['el lienzo', 'tela (de pintura)', 'substantivo', 'El lienzo estaba en blanco.', 'A tela estava em branco.', 'Arte e cultura'],
    ['la orquesta', 'orquestra', 'substantivo', 'La orquesta ensayó.', 'A orquestra ensaiou.', 'Arte e cultura'],
    ['el coro', 'coral', 'substantivo', 'Canta en un coro.', 'Ela canta num coral.', 'Arte e cultura'],
    ['el dramaturgo', 'dramaturgo', 'substantivo', 'El dramaturgo es famoso.', 'O dramaturgo é famoso.', 'Arte e cultura'],
    ['el novelista', 'romancista', 'substantivo', 'Es una novelista joven.', 'Ela é uma jovem romancista.', 'Arte e cultura'],
    ['el folclore', 'folclore', 'substantivo', 'El folclore local es rico.', 'O folclore local é rico.', 'Arte e cultura'],
    ['el patrimonio', 'patrimônio', 'substantivo', 'Es un sitio de patrimonio.', 'É um sítio de patrimônio.', 'Arte e cultura'],
    ['el imperio', 'império', 'substantivo', 'El imperio se derrumbó.', 'O império ruiu.', 'História'],
    ['la revolución', 'revolução', 'substantivo', 'La revolución lo cambió todo.', 'A revolução mudou tudo.', 'História'],
    ['el tratado', 'tratado', 'substantivo', 'Firmaron un tratado.', 'Assinaram um tratado.', 'História'],
    ['la colonia', 'colônia', 'substantivo', 'Antes fue una colonia.', 'Já foi uma colônia.', 'História'],
    ['la dinastía', 'dinastia', 'substantivo', 'La dinastía duró siglos.', 'A dinastia durou séculos.', 'História'],
    ['el levantamiento', 'levante', 'substantivo', 'El levantamiento fue aplastado.', 'O levante foi esmagado.', 'História'],
    ['el asedio', 'cerco', 'substantivo', 'El asedio duró un año.', 'O cerco durou um ano.', 'História'],
    ['el archivo histórico', 'arquivo histórico', 'substantivo', 'El archivo histórico guarda las cartas.', 'O arquivo histórico guarda as cartas.', 'História'],
    ['la crónica', 'crônica histórica', 'substantivo', 'La crónica lo menciona.', 'A crônica o menciona.', 'História'],
    ['el artefacto', 'artefato', 'substantivo', 'Encontraron un artefacto.', 'Encontraram um artefato.', 'História'],
    ['el continente', 'continente', 'substantivo', 'Es el continente más grande.', 'É o maior continente.', 'Geografia'],
    ['la península', 'península', 'substantivo', 'La península es rocosa.', 'A península é rochosa.', 'Geografia'],
    ['la meseta', 'planalto', 'substantivo', 'La meseta es seca.', 'O planalto é seco.', 'Geografia'],
    ['el glaciar', 'geleira', 'substantivo', 'El glaciar retrocede.', 'A geleira está recuando.', 'Geografia'],
    ['el delta', 'delta (de rio)', 'substantivo', 'El delta es fértil.', 'O delta é fértil.', 'Geografia'],
    ['el valle', 'vale', 'substantivo', 'El valle se inunda a menudo.', 'O vale alaga com frequência.', 'Geografia'],
    ['el desierto', 'deserto', 'substantivo', 'El desierto está avanzando.', 'O deserto está avançando.', 'Geografia'],
    ['la marea', 'maré', 'substantivo', 'La marea está subiendo.', 'A maré está subindo.', 'Geografia'],
    ['la latitud', 'latitude', 'substantivo', 'Comprueba la latitud primero.', 'Confira a latitude primeiro.', 'Geografia'],
    ['el terreno', 'terreno', 'substantivo', 'El terreno es difícil.', 'O terreno é difícil.', 'Geografia'],
    ['la integridad', 'integridade', 'substantivo', 'Su integridad es indiscutible.', 'A integridade dele é indiscutível.', 'Ética'],
    ['la virtud', 'virtude', 'substantivo', 'La paciencia es una virtud.', 'A paciência é uma virtude.', 'Ética'],
    ['el deber', 'dever', 'substantivo', 'Es tu deber informarlo.', 'É seu dever relatar isso.', 'Ética'],
    ['el consentimiento', 'consentimento', 'substantivo', 'Actuaron sin consentimiento.', 'Agiram sem consentimento.', 'Ética'],
    ['la equidad', 'equidade', 'substantivo', 'Aquí importa la equidad.', 'Aqui a equidade importa.', 'Ética'],
    ['el daño', 'dano', 'substantivo', 'La política causó un daño real.', 'A política causou dano real.', 'Ética'],
    ['la dignidad', 'dignidade', 'substantivo', 'Trátalos con dignidad.', 'Trate-os com dignidade.', 'Ética'],
    ['la obligación', 'obrigação', 'substantivo', 'Tenemos una obligación.', 'Temos uma obrigação.', 'Ética'],
    ['la mala conducta', 'má conduta', 'substantivo', 'Lo despidieron por mala conducta.', 'Foi demitido por má conduta.', 'Ética'],
    ['el denunciante', 'denunciante', 'substantivo', 'Protegieron al denunciante.', 'Protegeram o denunciante.', 'Ética'],
  ],
  C1: [
    ['la burocracia', 'burocracia', 'substantivo', 'La burocracia lo retrasó todo.', 'A burocracia atrasou tudo.', 'Administração pública'],
    ['la ordenanza', 'decreto municipal', 'substantivo', 'Aprobaron una nueva ordenanza.', 'Aprovaram um novo decreto.', 'Administração pública'],
    ['el cumplimiento', 'conformidade', 'substantivo', 'El cumplimiento es obligatorio.', 'A conformidade é obrigatória.', 'Administração pública'],
    ['la supervisión', 'fiscalização', 'substantivo', 'La supervisión era débil.', 'A fiscalização era fraca.', 'Administração pública'],
    ['el protocolo', 'protocolo', 'substantivo', 'Sigue el protocolo al pie de la letra.', 'Siga o protocolo à risca.', 'Administração pública'],
    ['la directriz', 'diretriz', 'substantivo', 'La directriz entra en vigor hoy.', 'A diretriz entra em vigor hoje.', 'Administração pública'],
    ['el quórum', 'quórum', 'substantivo', 'No alcanzamos el quórum.', 'Não atingimos o quórum.', 'Administração pública'],
    ['la titularidad', 'estabilidade no cargo', 'substantivo', 'Obtuvo la titularidad.', 'Ela obteve estabilidade no cargo.', 'Administração pública'],
    ['la competencia', 'alçada / competência', 'substantivo', 'Eso excede nuestra competencia.', 'Isso excede nossa alçada.', 'Administração pública'],
    ['la reparación', 'reparação', 'substantivo', 'Buscaron reparación judicial.', 'Buscaram reparação judicial.', 'Administração pública'],
    ['la mediana', 'mediana', 'substantivo', 'Aquí la mediana es más útil.', 'Aqui a mediana é mais útil.', 'Estatística'],
    ['la varianza', 'variância', 'substantivo', 'La varianza es demasiado alta.', 'A variância é alta demais.', 'Estatística'],
    ['la desviación estándar', 'desvio padrão', 'substantivo', 'Informa la desviación estándar.', 'Informe o desvio padrão.', 'Estatística'],
    ['la regresión', 'regressão', 'substantivo', 'La regresión explica poco.', 'A regressão explica pouco.', 'Estatística'],
    ['la probabilidad', 'probabilidade', 'substantivo', 'La probabilidad es baja.', 'A probabilidade é baixa.', 'Estatística'],
    ['la distribución', 'distribuição', 'substantivo', 'La distribución es asimétrica.', 'A distribuição é assimétrica.', 'Estatística'],
    ['el valor atípico', 'ponto fora da curva', 'substantivo', 'Elimina ese valor atípico.', 'Remova esse ponto fora da curva.', 'Estatística'],
    ['la significación', 'significância', 'substantivo', 'La significación no es importancia.', 'Significância não é importância.', 'Estatística'],
    ['el umbral', 'limiar', 'substantivo', 'Quedó por debajo del umbral.', 'Ficou abaixo do limiar.', 'Estatística'],
    ['la estimación', 'estimativa', 'substantivo', 'Es una estimación aproximada.', 'É uma estimativa aproximada.', 'Estatística'],
    ['la sintaxis', 'sintaxe', 'substantivo', 'Aquí la sintaxis cambia.', 'Aqui a sintaxe muda.', 'Linguística'],
    ['el morfema', 'morfema', 'substantivo', 'Ese prefijo es un morfema.', 'Esse prefixo é um morfema.', 'Linguística'],
    ['el fonema', 'fonema', 'substantivo', 'Los dos fonemas contrastan.', 'Os dois fonemas contrastam.', 'Linguística'],
    ['la semántica', 'semântica', 'substantivo', 'La disputa es de semántica.', 'A disputa é de semântica.', 'Linguística'],
    ['el dialecto', 'dialeto', 'substantivo', 'El dialecto varía por región.', 'O dialeto varia por região.', 'Linguística'],
    ['el registro lingüístico', 'registro de fala', 'substantivo', 'Ajusta el registro lingüístico al contexto.', 'Ajuste o registro de fala ao contexto.', 'Linguística'],
    ['la etimología', 'etimologia', 'substantivo', 'La etimología está en disputa.', 'A etimologia é contestada.', 'Linguística'],
    ['el cognado', 'cognato', 'substantivo', 'Estas palabras son cognados.', 'Estas palavras são cognatas.', 'Linguística'],
    ['la flexión', 'flexão', 'substantivo', 'La flexión marca el caso.', 'A flexão marca o caso.', 'Linguística'],
    ['la fluidez', 'fluência', 'substantivo', 'La fluidez no es corrección.', 'Fluência não é correção.', 'Linguística'],
    ['la fachada', 'fachada', 'substantivo', 'Restauraron la fachada.', 'A fachada foi restaurada.', 'Arquitetura'],
    ['los cimientos', 'fundação (de obra)', 'substantivo', 'Los cimientos se agrietaron.', 'A fundação rachou.', 'Arquitetura'],
    ['el plano', 'planta / projeto', 'substantivo', 'Revisa el plano otra vez.', 'Confira a planta de novo.', 'Arquitetura'],
    ['la bóveda', 'abóbada', 'substantivo', 'La bóveda es medieval.', 'A abóbada é medieval.', 'Arquitetura'],
    ['el andamio', 'andaime', 'substantivo', 'Hoy montaron el andamio.', 'O andaime subiu hoje.', 'Arquitetura'],
    ['la zonificación', 'zoneamento', 'substantivo', 'La zonificación lo impidió.', 'O zoneamento impediu.', 'Arquitetura'],
    ['la reforma', 'reforma (de obra)', 'substantivo', 'La reforma duró un año.', 'A reforma levou um ano.', 'Arquitetura'],
    ['de carga', 'estrutural (que sustenta)', 'adjetivo', 'Es una pared de carga.', 'É uma parede estrutural.', 'Arquitetura'],
    ['la expansión urbana', 'expansão urbana', 'substantivo', 'La expansión urbana no para.', 'A expansão urbana não para.', 'Arquitetura'],
    ['el perfil urbano', 'silhueta urbana', 'substantivo', 'El perfil urbano cambió del todo.', 'A silhueta urbana mudou por completo.', 'Arquitetura'],
  ],
  C2: [
    ['la distensión', 'distensão (diplomática)', 'substantivo', 'La distensión no duró.', 'A distensão não durou.', 'Diplomacia'],
    ['el acercamiento', 'reaproximação', 'substantivo', 'Empezó un acercamiento cauteloso.', 'Começou uma reaproximação cautelosa.', 'Diplomacia'],
    ['el comunicado oficial', 'comunicado oficial', 'substantivo', 'El comunicado oficial decía poco.', 'O comunicado oficial dizia pouco.', 'Diplomacia'],
    ['el enviado', 'emissário', 'substantivo', 'Enviaron a un enviado.', 'Enviaram um emissário.', 'Diplomacia'],
    ['el acuerdo formal', 'acordo formal', 'substantivo', 'El acuerdo formal se sostiene.', 'O acordo formal se mantém.', 'Diplomacia'],
    ['la sanción', 'sanção', 'substantivo', 'Levantaron las sanciones.', 'Suspenderam as sanções.', 'Diplomacia'],
    ['la neutralidad', 'neutralidade', 'substantivo', 'Declararon la neutralidad.', 'Declararam neutralidade.', 'Diplomacia'],
    ['la soberanía', 'soberania', 'substantivo', 'La soberanía fue el punto muerto.', 'A soberania foi o impasse.', 'Diplomacia'],
    ['la reciprocidad', 'reciprocidade', 'substantivo', 'El pacto se basa en la reciprocidad.', 'O pacto se baseia na reciprocidade.', 'Diplomacia'],
    ['el pulso diplomático', 'queda de braço diplomática', 'substantivo', 'Esto es un puro pulso diplomático.', 'Isso é pura queda de braço diplomática.', 'Diplomacia'],
    ['la teodicea', 'teodiceia', 'substantivo', 'La teodicea pregunta por el mal.', 'A teodiceia pergunta pelo mal.', 'Teologia e mito'],
    ['la apoteosis', 'apoteose', 'substantivo', 'Fue la apoteosis del estilo.', 'Foi a apoteose do estilo.', 'Teologia e mito'],
    ['la escatología', 'escatologia', 'substantivo', 'La escatología trata del fin.', 'A escatologia trata do fim.', 'Teologia e mito'],
    ['la liturgia', 'liturgia', 'substantivo', 'La liturgia tiene siglos.', 'A liturgia tem séculos.', 'Teologia e mito'],
    ['la herejía', 'heresia', 'substantivo', 'Fue condenado como herejía.', 'Foi condenado como heresia.', 'Teologia e mito'],
    ['el panteón', 'panteão', 'substantivo', 'Entró en el panteón de los grandes.', 'Entrou no panteão dos grandes.', 'Teologia e mito'],
    ['el oráculo', 'oráculo', 'substantivo', 'El oráculo hablaba en enigmas.', 'O oráculo falava por enigmas.', 'Teologia e mito'],
    ['la reliquia', 'relíquia', 'substantivo', 'La reliquia atraía peregrinos.', 'A relíquia atraía peregrinos.', 'Teologia e mito'],
    ['el cisma', 'cisma', 'substantivo', 'El cisma dividió la iglesia.', 'O cisma dividiu a igreja.', 'Teologia e mito'],
    ['la trascendencia', 'transcendência', 'substantivo', 'El poema busca la trascendencia.', 'O poema busca a transcendência.', 'Teologia e mito'],
    ['a priori', 'a priori', 'advérbio', 'Eso no se sabe a priori.', 'Isso não se sabe a priori.', 'Locuções cultas'],
    ['a fortiori', 'com mais razão ainda', 'advérbio', 'A fortiori, el segundo caso falla.', 'Com mais razão ainda, o segundo caso não se sustenta.', 'Locuções cultas'],
    ['sine qua non', 'condição indispensável', 'substantivo', 'La confianza es la condición sine qua non.', 'A confiança é a condição indispensável.', 'Locuções cultas'],
    ['de facto', 'de fato', 'adjetivo', 'Es la líder de facto.', 'Ela é a líder de fato.', 'Locuções cultas'],
    ['ad hoc', 'ad hoc / improvisado', 'adjetivo', 'Era un comité ad hoc.', 'Era um comitê ad hoc.', 'Locuções cultas'],
    ['mutatis mutandis', 'feitas as devidas adaptações', 'advérbio', 'Lo mismo vale, mutatis mutandis.', 'O mesmo vale, feitas as devidas adaptações.', 'Locuções cultas'],
    ['ceteris paribus', 'mantidas as demais condições', 'advérbio', 'Ceteris paribus, la demanda caerá.', 'Mantidas as demais condições, a procura vai cair.', 'Locuções cultas'],
    ['prima facie', 'à primeira vista', 'adjetivo', 'Hay indicios prima facie.', 'Há indícios à primeira vista.', 'Locuções cultas'],
    ['per se', 'em si mesmo', 'advérbio', 'La norma no es injusta per se.', 'A norma não é injusta em si mesma.', 'Locuções cultas'],
    ['in extremis', 'em situação extrema', 'advérbio', 'El acuerdo se salvó in extremis.', 'O acordo foi salvo in extremis.', 'Locuções cultas'],
    ['la añoranza', 'saudade melancólica', 'substantivo', 'Habló con añoranza.', 'Ela falou com saudade melancólica.', 'Emoções sutis'],
    ['la melancolía', 'melancolia', 'substantivo', 'Lo atraviesa una melancolía callada.', 'Uma melancolia discreta o atravessa.', 'Emoções sutis'],
    ['el hastío', 'tédio existencial', 'substantivo', 'El hastío de las tardes largas.', 'O tédio das tardes longas.', 'Emoções sutis'],
    ['el júbilo', 'júbilo / euforia', 'substantivo', 'Su júbilo duró poco.', 'A euforia dele durou pouco.', 'Emoções sutis'],
    ['el desasosiego', 'inquietação', 'substantivo', 'La noticia causó desasosiego.', 'A notícia causou inquietação.', 'Emoções sutis'],
    ['el anhelo', 'anseio', 'substantivo', 'Un anhelo por algo perdido.', 'Um anseio por algo perdido.', 'Emoções sutis'],
    ['la serenidad', 'serenidade', 'substantivo', 'Lo afrontó con serenidad.', 'Ela encarou com serenidade.', 'Emoções sutis'],
    ['la indignación', 'indignação', 'substantivo', 'Su indignación estaba justificada.', 'A indignação dele era justificada.', 'Emoções sutis'],
    ['el ensimismamiento', 'devaneio / absorção', 'substantivo', 'Cayó en el ensimismamiento.', 'Ela caiu num devaneio.', 'Emoções sutis'],
    ['el consuelo', 'consolo', 'substantivo', 'Halló consuelo en la música.', 'Ele encontrou consolo na música.', 'Emoções sutis'],
  ],
};
