/** Francês — segundo lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const FR_THEMATIC2: LatinByLevel = {
  A1: [
    ['un', 'um', 'numeral', 'Je veux une pomme.', 'Quero uma maçã.', 'Números e quantidade'],
    ['deux', 'dois', 'numeral', 'Elle a deux frères.', 'Ela tem dois irmãos.', 'Números e quantidade'],
    ['trois', 'três', 'numeral', 'Nous avons attendu trois heures.', 'Esperamos três horas.', 'Números e quantidade'],
    ['beaucoup', 'muitos', 'advérbio', 'Il y a beaucoup de gens.', 'Há muitas pessoas.', 'Números e quantidade'],
    ['peu', 'poucos', 'advérbio', 'Peu d’élèves sont venus.', 'Poucos alunos vieram.', 'Números e quantidade'],
    ['la moitié', 'metade', 'substantivo', "J'en ai mangé la moitié.", 'Comi metade.', 'Números e quantidade'],
    ['vide', 'vazio', 'adjetivo', 'La bouteille est vide.', 'A garrafa está vazia.', 'Números e quantidade'],
    ['plein', 'cheio', 'adjetivo', 'Le verre est plein.', 'O copo está cheio.', 'Números e quantidade'],
    ['lourd', 'pesado', 'adjetivo', 'Cette boîte est lourde.', 'Esta caixa é pesada.', 'Números e quantidade'],
    ['léger', 'leve', 'adjetivo', 'Le sac est léger.', 'A bolsa é leve.', 'Números e quantidade'],
    ['se réveiller', 'acordar', 'verbo', 'Je me réveille à six heures.', 'Eu acordo às seis.', 'Ações do dia a dia'],
    ['dormir', 'dormir', 'verbo', 'Je dors huit heures.', 'Eu durmo oito horas.', 'Ações do dia a dia'],
    ['laver', 'lavar', 'verbo', 'Lave-toi les mains.', 'Lave as mãos.', 'Ações do dia a dia'],
    ['cuisiner', 'cozinhar', 'verbo', 'Elle cuisine chaque soir.', 'Ela cozinha toda noite.', 'Ações do dia a dia'],
    ['nettoyer', 'limpar', 'verbo', 'Je nettoie la maison.', 'Eu limpo a casa.', 'Ações do dia a dia'],
    ['acheter', 'comprar', 'verbo', "J'achète du pain ici.", 'Eu compro pão aqui.', 'Ações do dia a dia'],
    ['vendre', 'vender', 'verbo', 'Ils vendent des fruits.', 'Eles vendem frutas.', 'Ações do dia a dia'],
    ['marcher', 'caminhar', 'verbo', 'Nous marchons jusqu’à l’école.', 'Nós caminhamos até a escola.', 'Ações do dia a dia'],
    ['courir', 'correr', 'verbo', 'Il court vite.', 'Ele corre rápido.', 'Ações do dia a dia'],
    ['attendre', 'esperar', 'verbo', 'Attendez ici, s’il vous plaît.', 'Espere aqui, por favor.', 'Ações do dia a dia'],
    ['le professeur', 'professor', 'substantivo', 'Le professeur est gentil.', 'O professor é gentil.', 'Escola'],
    ['l’élève', 'aluno', 'substantivo', "C'est une bonne élève.", 'Ela é uma boa aluna.', 'Escola'],
    ['le livre', 'livro', 'substantivo', 'Ce livre est long.', 'Este livro é longo.', 'Escola'],
    ['le stylo', 'caneta', 'substantivo', "J'ai besoin d'un stylo.", 'Preciso de uma caneta.', 'Escola'],
    ['le papier', 'papel', 'substantivo', 'Donne-moi du papier.', 'Me dê um papel.', 'Escola'],
    ['le cours', 'aula', 'substantivo', 'Le cours commence maintenant.', 'A aula começa agora.', 'Escola'],
    ['les devoirs', 'lição de casa', 'substantivo', "J'ai fini mes devoirs.", 'Terminei minha lição de casa.', 'Escola'],
    ['l’examen', 'prova', 'substantivo', "L'examen était difficile.", 'A prova foi difícil.', 'Escola'],
    ['la salle de classe', 'sala de aula', 'substantivo', 'La salle de classe est grande.', 'A sala de aula é grande.', 'Escola'],
    ['le cahier', 'caderno', 'substantivo', "J'ai oublié mon cahier.", 'Esqueci meu caderno.', 'Escola'],
    ['l’oiseau', 'pássaro', 'substantivo', 'Un oiseau chante.', 'Um pássaro está cantando.', 'Animais'],
    ['le poisson', 'peixe', 'substantivo', 'Le poisson est petit.', 'O peixe é pequeno.', 'Animais'],
    ['le cheval', 'cavalo', 'substantivo', 'Le cheval est rapide.', 'O cavalo é rápido.', 'Animais'],
    ['la vache', 'vaca', 'substantivo', "La vache mange de l'herbe.", 'A vaca come grama.', 'Animais'],
    ['la poule', 'galinha', 'substantivo', 'Nous avons trois poules.', 'Temos três galinhas.', 'Animais'],
    ['la souris', 'rato', 'substantivo', 'Il y a une souris ici.', 'Tem um rato aqui.', 'Animais'],
    ['l’insecte', 'inseto', 'substantivo', 'Un insecte est entré.', 'Um inseto entrou.', 'Animais'],
    ['le mouton', 'ovelha', 'substantivo', 'Les moutons sont blancs.', 'As ovelhas são brancas.', 'Animais'],
    ['le cochon', 'porco', 'substantivo', 'Le cochon est sale.', 'O porco está sujo.', 'Animais'],
    ['le lapin', 'coelho', 'substantivo', 'Le lapin est rapide.', 'O coelho é rápido.', 'Animais'],
  ],
  A2: [
    ['le bus', 'ônibus', 'substantivo', 'Le bus est en retard.', 'O ônibus está atrasado.', 'Transporte'],
    ['le train', 'trem', 'substantivo', 'Le train part à huit heures.', 'O trem sai às oito.', 'Transporte'],
    ['la voiture', 'carro', 'substantivo', 'Ma voiture est vieille.', 'Meu carro é velho.', 'Transporte'],
    ['le vélo', 'bicicleta', 'substantivo', 'Je vais à vélo.', 'Eu vou de bicicleta.', 'Transporte'],
    ['le taxi', 'táxi', 'substantivo', 'Prenons un taxi.', 'Vamos pegar um táxi.', 'Transporte'],
    ['le chauffeur', 'motorista', 'substantivo', 'Le chauffeur était poli.', 'O motorista foi educado.', 'Transporte'],
    ['le tarif', 'tarifa', 'substantivo', 'Le tarif a augmenté.', 'A tarifa subiu.', 'Transporte'],
    ['le quai', 'plataforma', 'substantivo', 'Attends sur le quai deux.', 'Espere na plataforma dois.', 'Transporte'],
    ['la place assise', 'assento', 'substantivo', 'Cette place assise est libre.', 'Este assento está livre.', 'Transporte'],
    ['le voyage', 'viagem / trajeto', 'substantivo', 'Le voyage dure deux heures.', 'A viagem dura duas horas.', 'Transporte'],
    ['le loisir', 'passatempo', 'substantivo', 'La lecture est mon loisir.', 'Ler é meu passatempo.', 'Lazer'],
    ['le musée', 'museu', 'substantivo', 'Le musée est gratuit aujourd’hui.', 'O museu está de graça hoje.', 'Lazer'],
    ['le cinéma', 'cinema', 'substantivo', 'Nous sommes allés au cinéma.', 'Fomos ao cinema.', 'Lazer'],
    ['le concert', 'show / concerto', 'substantivo', 'Le concert était génial.', 'O show foi ótimo.', 'Lazer'],
    ['le parc', 'parque', 'substantivo', 'Le parc est tout près.', 'O parque fica bem perto.', 'Lazer'],
    ['le jeu', 'jogo', 'substantivo', 'Ce jeu est amusant.', 'Este jogo é divertido.', 'Lazer'],
    ['l’appareil photo', 'câmera', 'substantivo', 'Apporte ton appareil photo.', 'Traga sua câmera.', 'Lazer'],
    ['le pique-nique', 'piquenique', 'substantivo', 'Nous avons fait un pique-nique.', 'Fizemos um piquenique.', 'Lazer'],
    ['nager', 'nadar', 'verbo', 'Je nage le dimanche.', 'Eu nado aos domingos.', 'Lazer'],
    ['danser', 'dançar', 'verbo', 'Ils dansent très bien.', 'Eles dançam muito bem.', 'Lazer'],
    ['heureux', 'feliz', 'adjetivo', 'Elle a l’air heureuse.', 'Ela parece feliz.', 'Emoções'],
    ['triste', 'triste', 'adjetivo', 'Il était triste hier.', 'Ele estava triste ontem.', 'Emoções'],
    ['fâché', 'bravo', 'adjetivo', 'Ne sois pas fâché.', 'Não fique bravo.', 'Emoções'],
    ['effrayé', 'com medo', 'adjetivo', 'Je suis effrayé.', 'Estou com medo.', 'Emoções'],
    ['surpris', 'surpreso', 'adjetivo', 'Nous étions surpris.', 'Ficamos surpresos.', 'Emoções'],
    ['ennuyé', 'entediado', 'adjetivo', 'Les enfants sont ennuyés.', 'As crianças estão entediadas.', 'Emoções'],
    ['inquiet', 'preocupado', 'adjetivo', 'Elle est inquiète pour ça.', 'Ela está preocupada com isso.', 'Emoções'],
    ['fier', 'orgulhoso', 'adjetivo', 'Je suis fier de toi.', 'Estou orgulhoso de você.', 'Emoções'],
    ['calme', 'calmo', 'adjetivo', 'Essaie de rester calme.', 'Tente ficar calmo.', 'Emoções'],
    ['seul', 'sozinho / solitário', 'adjetivo', 'Il se sent très seul.', 'Ele se sente muito sozinho.', 'Emoções'],
    ['jeune', 'jovem', 'adjetivo', 'Elle est très jeune.', 'Ela é muito jovem.', 'Descrever pessoas'],
    ['vieux', 'velho', 'adjetivo', 'Mon grand-père est vieux.', 'Meu avô é velho.', 'Descrever pessoas'],
    ['gentil', 'gentil', 'adjetivo', "C'est un homme gentil.", 'Ele é um homem gentil.', 'Descrever pessoas'],
    ['drôle', 'engraçado', 'adjetivo', 'Ton ami est drôle.', 'Seu amigo é engraçado.', 'Descrever pessoas'],
    ['discret', 'discreto / reservado', 'adjetivo', 'Elle est très discrète.', 'Ela é muito reservada.', 'Descrever pessoas'],
    ['astucieux', 'astuto / esperto', 'adjetivo', "C'était une idée astucieuse.", 'Foi uma ideia astuta.', 'Descrever pessoas'],
    ['paresseux', 'preguiçoso', 'adjetivo', 'Ne sois pas paresseux.', 'Não seja preguiçoso.', 'Descrever pessoas'],
    ['honnête', 'honesto', 'adjetivo', 'Elle est toujours honnête.', 'Ela é sempre honesta.', 'Descrever pessoas'],
    ['sympathique', 'simpático', 'adjetivo', "L'équipe est sympathique.", 'A equipe é simpática.', 'Descrever pessoas'],
    ['fort', 'forte', 'adjetivo', 'Il est très fort.', 'Ele é muito forte.', 'Descrever pessoas'],
  ],
  B1: [
    ['l’alimentation', 'alimentação', 'substantivo', 'Son alimentation a beaucoup changé.', 'A alimentação dela mudou muito.', 'Saúde e bem-estar'],
    ['l’exercice', 'exercício', 'substantivo', "L'exercice aide à dormir.", 'O exercício ajuda a dormir.', 'Saúde e bem-estar'],
    ['le stress', 'estresse', 'substantivo', 'Le stress affecte le corps.', 'O estresse afeta o corpo.', 'Saúde e bem-estar'],
    ['l’habitude', 'hábito', 'substantivo', "C'est devenu une habitude.", 'Virou um hábito.', 'Saúde e bem-estar'],
    ['la thérapie', 'terapia', 'substantivo', 'La thérapie l’a beaucoup aidé.', 'A terapia o ajudou muito.', 'Saúde e bem-estar'],
    ['la guérison', 'recuperação', 'substantivo', 'La guérison prend du temps.', 'A recuperação leva tempo.', 'Saúde e bem-estar'],
    ['la posture', 'postura', 'substantivo', 'Corrige ta posture.', 'Corrija sua postura.', 'Saúde e bem-estar'],
    ['la respiration', 'respiração', 'substantivo', 'Une respiration lente calme.', 'A respiração lenta acalma.', 'Saúde e bem-estar'],
    ['le bilan de santé', 'check-up', 'substantivo', "J'ai fait un bilan de santé.", 'Fiz um check-up.', 'Saúde e bem-estar'],
    ['le bien-être', 'bem-estar', 'substantivo', 'Ils tiennent au bien-être.', 'Eles se importam com o bem-estar.', 'Saúde e bem-estar'],
    ['le loyer', 'aluguel', 'substantivo', 'Le loyer a encore augmenté.', 'O aluguel subiu de novo.', 'Moradia'],
    ['le bail', 'contrato de locação', 'substantivo', 'Le bail se termine en juin.', 'O contrato acaba em junho.', 'Moradia'],
    ['la caution', 'caução', 'substantivo', 'Ils ont gardé la caution.', 'Ficaram com a caução.', 'Moradia'],
    ['le locataire', 'inquilino', 'substantivo', 'Le locataire s’est plaint.', 'O inquilino reclamou.', 'Moradia'],
    ['le plafond', 'teto', 'substantivo', 'Le plafond fuit.', 'O teto está vazando.', 'Moradia'],
    ['le toit', 'telhado', 'substantivo', 'Le toit doit être réparé.', 'O telhado precisa de conserto.', 'Moradia'],
    ['la cave', 'porão', 'substantivo', 'La cave est humide.', 'O porão está úmido.', 'Moradia'],
    ['le balcon', 'varanda', 'substantivo', 'Nous mangeons sur le balcon.', 'Comemos na varanda.', 'Moradia'],
    ['la plomberie', 'encanamento', 'substantivo', 'La plomberie est ancienne.', 'O encanamento é antigo.', 'Moradia'],
    ['la propriétaire', 'senhoria', 'substantivo', 'La propriétaire m’a appelé.', 'A senhoria me ligou.', 'Moradia'],
    ['la recette', 'receita', 'substantivo', 'Envoie-moi la recette.', 'Me manda a receita.', 'Culinária'],
    ['l’ingrédient', 'ingrediente', 'substantivo', 'Il manque un ingrédient.', 'Falta um ingrediente.', 'Culinária'],
    ['bouillir', 'ferver', 'verbo', "Fais bouillir l'eau d'abord.", 'Ferva a água primeiro.', 'Culinária'],
    ['frire', 'fritar', 'verbo', 'Fais frire les oignons doucement.', 'Frite a cebola devagar.', 'Culinária'],
    ['cuire au four', 'assar no forno', 'verbo', 'Fais-le cuire au four une heure.', 'Asse por uma hora.', 'Culinária'],
    ['hacher', 'picar', 'verbo', "Hache l'ail très finement.", 'Pique o alho bem fino.', 'Culinária'],
    ['assaisonner', 'temperar', 'verbo', 'Assaisonne avec du poivre.', 'Tempere com pimenta.', 'Culinária'],
    ['la pâte', 'massa (crua)', 'substantivo', 'La pâte doit reposer.', 'A massa precisa descansar.', 'Culinária'],
    ['rôtir', 'assar (carne)', 'verbo', 'Nous rôtissons la viande lentement.', 'Assamos a carne devagar.', 'Culinária'],
    ['cuire à la vapeur', 'cozinhar no vapor', 'verbo', 'Fais cuire les légumes à la vapeur.', 'Cozinhe os legumes no vapor.', 'Culinária'],
    ['le message', 'mensagem', 'substantivo', "J'ai reçu ton message.", 'Recebi sua mensagem.', 'Comunicação'],
    ['la réponse', 'resposta', 'substantivo', "J'attends une réponse.", 'Estou esperando uma resposta.', 'Comunicação'],
    ['l’avis', 'aviso', 'substantivo', 'Il y a un avis sur la porte.', 'Há um aviso na porta.', 'Comunicação'],
    ['l’annonce', 'anúncio / comunicado', 'substantivo', 'Ils ont fait une annonce.', 'Fizeram um comunicado.', 'Comunicação'],
    ['la rumeur', 'boato', 'substantivo', "Ce n'est qu'une rumeur.", 'É só um boato.', 'Comunicação'],
    ['la déclaration', 'declaração', 'substantivo', 'Elle a publié une déclaration.', 'Ela divulgou uma declaração.', 'Comunicação'],
    ['expliquer', 'explicar', 'verbo', 'Explique-le encore, s’il te plaît.', 'Explique de novo, por favor.', 'Comunicação'],
    ['décrire', 'descrever', 'verbo', 'Décris ce que tu as vu.', 'Descreva o que você viu.', 'Comunicação'],
    ['résumer', 'resumir', 'verbo', 'Résume-le en une ligne.', 'Resuma em uma linha.', 'Comunicação'],
    ['le malentendu', 'mal-entendido', 'substantivo', "C'était un malentendu.", 'Foi um mal-entendido.', 'Comunicação'],
  ],
  B2: [
    ['la sculpture', 'escultura', 'substantivo', 'La sculpture est en bronze.', 'A escultura é de bronze.', 'Arte e cultura'],
    ['l’exposition', 'exposição', 'substantivo', "L'exposition ouvre vendredi.", 'A exposição abre sexta.', 'Arte e cultura'],
    ['le portrait', 'retrato', 'substantivo', 'Elle a peint un portrait.', 'Ela pintou um retrato.', 'Arte e cultura'],
    ['la toile', 'tela (de pintura)', 'substantivo', 'La toile était vierge.', 'A tela estava em branco.', 'Arte e cultura'],
    ['l’orchestre', 'orquestra', 'substantivo', "L'orchestre a répété.", 'A orquestra ensaiou.', 'Arte e cultura'],
    ['la chorale', 'coral', 'substantivo', 'Elle chante dans une chorale.', 'Ela canta num coral.', 'Arte e cultura'],
    ['le dramaturge', 'dramaturgo', 'substantivo', 'Le dramaturge est célèbre.', 'O dramaturgo é famoso.', 'Arte e cultura'],
    ['le romancier', 'romancista', 'substantivo', "C'est une jeune romancière.", 'Ela é uma jovem romancista.', 'Arte e cultura'],
    ['le folklore', 'folclore', 'substantivo', 'Le folklore local est riche.', 'O folclore local é rico.', 'Arte e cultura'],
    ['le patrimoine', 'patrimônio', 'substantivo', "C'est un site du patrimoine.", 'É um sítio de patrimônio.', 'Arte e cultura'],
    ['l’empire', 'império', 'substantivo', "L'empire s'est effondré.", 'O império ruiu.', 'História'],
    ['la révolution', 'revolução', 'substantivo', 'La révolution a tout changé.', 'A revolução mudou tudo.', 'História'],
    ['le traité', 'tratado', 'substantivo', 'Ils ont signé un traité.', 'Assinaram um tratado.', 'História'],
    ['la colonie', 'colônia', 'substantivo', "C'était autrefois une colonie.", 'Já foi uma colônia.', 'História'],
    ['la dynastie', 'dinastia', 'substantivo', 'La dynastie a duré des siècles.', 'A dinastia durou séculos.', 'História'],
    ['le soulèvement', 'levante', 'substantivo', 'Le soulèvement a été écrasé.', 'O levante foi esmagado.', 'História'],
    ['le siège', 'cerco', 'substantivo', 'Le siège a duré un an.', 'O cerco durou um ano.', 'História'],
    ['les archives', 'arquivo histórico', 'substantivo', 'Les archives gardent les lettres.', 'O arquivo guarda as cartas.', 'História'],
    ['la chronique', 'crônica histórica', 'substantivo', 'La chronique le mentionne.', 'A crônica o menciona.', 'História'],
    ['l’artefact', 'artefato', 'substantivo', 'Ils ont trouvé un artefact.', 'Encontraram um artefato.', 'História'],
    ['le continent', 'continente', 'substantivo', "C'est le plus grand continent.", 'É o maior continente.', 'Geografia'],
    ['la péninsule', 'península', 'substantivo', 'La péninsule est rocheuse.', 'A península é rochosa.', 'Geografia'],
    ['le plateau montagneux', 'planalto', 'substantivo', 'Le plateau montagneux est sec.', 'O planalto é seco.', 'Geografia'],
    ['le glacier', 'geleira', 'substantivo', 'Le glacier recule.', 'A geleira está recuando.', 'Geografia'],
    ['le delta', 'delta (de rio)', 'substantivo', 'Le delta est fertile.', 'O delta é fértil.', 'Geografia'],
    ['la vallée', 'vale', 'substantivo', 'La vallée est souvent inondée.', 'O vale alaga com frequência.', 'Geografia'],
    ['le désert', 'deserto', 'substantivo', 'Le désert avance.', 'O deserto está avançando.', 'Geografia'],
    ['la marée', 'maré', 'substantivo', 'La marée monte.', 'A maré está subindo.', 'Geografia'],
    ['la latitude', 'latitude', 'substantivo', "Vérifie d'abord la latitude.", 'Confira a latitude primeiro.', 'Geografia'],
    ['le terrain', 'terreno', 'substantivo', 'Le terrain est difficile.', 'O terreno é difícil.', 'Geografia'],
    ['l’intégrité', 'integridade', 'substantivo', 'Son intégrité ne fait aucun doute.', 'A integridade dele é inquestionável.', 'Ética'],
    ['la vertu', 'virtude', 'substantivo', 'La patience est une vertu.', 'A paciência é uma virtude.', 'Ética'],
    ['le devoir', 'dever', 'substantivo', "C'est ton devoir de le signaler.", 'É seu dever relatar isso.', 'Ética'],
    ['le consentement', 'consentimento', 'substantivo', 'Ils ont agi sans consentement.', 'Agiram sem consentimento.', 'Ética'],
    ['l’équité', 'equidade', 'substantivo', "L'équité compte ici.", 'A equidade importa aqui.', 'Ética'],
    ['le préjudice', 'dano / prejuízo', 'substantivo', 'La mesure a causé un vrai préjudice.', 'A medida causou dano real.', 'Ética'],
    ['la dignité', 'dignidade', 'substantivo', 'Traitez-les avec dignité.', 'Trate-os com dignidade.', 'Ética'],
    ['l’obligation', 'obrigação', 'substantivo', 'Nous avons une obligation.', 'Temos uma obrigação.', 'Ética'],
    ['la faute professionnelle', 'má conduta', 'substantivo', 'Il a été licencié pour faute professionnelle.', 'Foi demitido por má conduta.', 'Ética'],
    ['le lanceur d’alerte', 'denunciante', 'substantivo', 'Le lanceur d’alerte a été protégé.', 'O denunciante foi protegido.', 'Ética'],
  ],
  C1: [
    ['la bureaucratie', 'burocracia', 'substantivo', 'La bureaucratie a tout ralenti.', 'A burocracia atrasou tudo.', 'Administração pública'],
    ['l’arrêté municipal', 'decreto municipal', 'substantivo', 'Un nouvel arrêté municipal est passé.', 'Um novo decreto foi aprovado.', 'Administração pública'],
    ['la conformité', 'conformidade', 'substantivo', 'La conformité est obligatoire.', 'A conformidade é obrigatória.', 'Administração pública'],
    ['le contrôle', 'fiscalização', 'substantivo', 'Le contrôle était faible.', 'A fiscalização era fraca.', 'Administração pública'],
    ['le protocole', 'protocolo', 'substantivo', 'Suivez le protocole à la lettre.', 'Siga o protocolo à risca.', 'Administração pública'],
    ['la directive', 'diretriz', 'substantivo', 'La directive entre en vigueur aujourd’hui.', 'A diretriz entra em vigor hoje.', 'Administração pública'],
    ['le quorum', 'quórum', 'substantivo', "Nous n'avons pas atteint le quorum.", 'Não atingimos o quórum.', 'Administração pública'],
    ['la titularisation', 'estabilidade no cargo', 'substantivo', 'Elle a obtenu la titularisation.', 'Ela obteve estabilidade no cargo.', 'Administração pública'],
    ['le ressort', 'alçada / competência', 'substantivo', 'Cela dépasse notre ressort.', 'Isso excede nossa alçada.', 'Administração pública'],
    ['la réparation', 'reparação', 'substantivo', 'Ils ont demandé réparation.', 'Pediram reparação.', 'Administração pública'],
    ['la médiane', 'mediana', 'substantivo', 'La médiane est plus utile ici.', 'A mediana é mais útil aqui.', 'Estatística'],
    ['la variance', 'variância', 'substantivo', 'La variance est trop élevée.', 'A variância é alta demais.', 'Estatística'],
    ['l’écart type', 'desvio padrão', 'substantivo', "Indiquez l'écart type.", 'Informe o desvio padrão.', 'Estatística'],
    ['la régression', 'regressão', 'substantivo', 'La régression explique peu.', 'A regressão explica pouco.', 'Estatística'],
    ['la probabilité', 'probabilidade', 'substantivo', 'La probabilité est faible.', 'A probabilidade é baixa.', 'Estatística'],
    ['la distribution', 'distribuição', 'substantivo', 'La distribution est asymétrique.', 'A distribuição é assimétrica.', 'Estatística'],
    ['la valeur aberrante', 'ponto fora da curva', 'substantivo', 'Retire cette valeur aberrante.', 'Remova esse ponto fora da curva.', 'Estatística'],
    ['la significativité', 'significância', 'substantivo', 'La significativité n’est pas l’importance.', 'A significância não é a importância.', 'Estatística'],
    ['le seuil', 'limiar', 'substantivo', 'Il est passé sous le seuil.', 'Ficou abaixo do limiar.', 'Estatística'],
    ['l’estimation', 'estimativa', 'substantivo', "C'est une estimation approximative.", 'É uma estimativa aproximada.', 'Estatística'],
    ['la syntaxe', 'sintaxe', 'substantivo', 'La syntaxe change ici.', 'A sintaxe muda aqui.', 'Linguística'],
    ['le morphème', 'morfema', 'substantivo', 'Ce préfixe est un morphème.', 'Esse prefixo é um morfema.', 'Linguística'],
    ['le phonème', 'fonema', 'substantivo', 'Les deux phonèmes s’opposent.', 'Os dois fonemas se opõem.', 'Linguística'],
    ['la sémantique', 'semântica', 'substantivo', 'Le débat porte sur la sémantique.', 'O debate é de semântica.', 'Linguística'],
    ['le dialecte', 'dialeto', 'substantivo', 'Le dialecte varie selon la région.', 'O dialeto varia por região.', 'Linguística'],
    ['le registre de langue', 'registro de fala', 'substantivo', 'Adapte le registre de langue au contexte.', 'Ajuste o registro de fala ao contexto.', 'Linguística'],
    ['l’étymologie', 'etimologia', 'substantivo', "L'étymologie est contestée.", 'A etimologia é contestada.', 'Linguística'],
    ['le mot apparenté', 'cognato', 'substantivo', 'Ces deux mots sont apparentés.', 'Estas duas palavras são cognatas.', 'Linguística'],
    ['la flexion', 'flexão', 'substantivo', 'La flexion marque le cas.', 'A flexão marca o caso.', 'Linguística'],
    ['l’aisance', 'fluência / desenvoltura', 'substantivo', "L'aisance n'est pas la correction.", 'A fluência não é a correção.', 'Linguística'],
    ['la façade', 'fachada', 'substantivo', 'La façade a été restaurée.', 'A fachada foi restaurada.', 'Arquitetura'],
    ['les fondations', 'fundação (de obra)', 'substantivo', 'Les fondations se sont fissurées.', 'A fundação rachou.', 'Arquitetura'],
    ['le plan d’architecte', 'planta / projeto', 'substantivo', 'Revois le plan d’architecte.', 'Confira a planta de novo.', 'Arquitetura'],
    ['la voûte', 'abóbada', 'substantivo', 'La voûte est médiévale.', 'A abóbada é medieval.', 'Arquitetura'],
    ['l’échafaudage', 'andaime', 'substantivo', "L'échafaudage a été monté aujourd'hui.", 'O andaime subiu hoje.', 'Arquitetura'],
    ['le zonage', 'zoneamento', 'substantivo', 'Le zonage l’a empêché.', 'O zoneamento impediu.', 'Arquitetura'],
    ['la rénovation', 'reforma', 'substantivo', 'La rénovation a duré un an.', 'A reforma levou um ano.', 'Arquitetura'],
    ['porteur', 'estrutural (que sustenta)', 'adjetivo', "C'est un mur porteur.", 'É uma parede estrutural.', 'Arquitetura'],
    ['l’étalement urbain', 'expansão urbana', 'substantivo', "L'étalement urbain continue.", 'A expansão urbana continua.', 'Arquitetura'],
    ['la silhouette urbaine', 'silhueta urbana', 'substantivo', 'La silhouette urbaine a changé.', 'A silhueta urbana mudou.', 'Arquitetura'],
  ],
  C2: [
    ['la détente diplomatique', 'distensão diplomática', 'substantivo', 'La détente diplomatique n’a pas duré.', 'A distensão diplomática não durou.', 'Diplomacia'],
    ['le rapprochement', 'reaproximação', 'substantivo', 'Un rapprochement prudent a commencé.', 'Começou uma reaproximação cautelosa.', 'Diplomacia'],
    ['le communiqué', 'comunicado oficial', 'substantivo', 'Le communiqué disait peu.', 'O comunicado dizia pouco.', 'Diplomacia'],
    ['l’émissaire', 'emissário', 'substantivo', 'Un émissaire a été envoyé.', 'Um emissário foi enviado.', 'Diplomacia'],
    ['l’accord formel', 'acordo formal', 'substantivo', "L'accord formel tient pour l'instant.", 'O acordo formal se mantém por ora.', 'Diplomacia'],
    ['la sanction internationale', 'sanção internacional', 'substantivo', 'Les sanctions internationales ont été levées.', 'As sanções internacionais foram suspensas.', 'Diplomacia'],
    ['la neutralité', 'neutralidade', 'substantivo', 'Ils ont déclaré la neutralité.', 'Declararam neutralidade.', 'Diplomacia'],
    ['la souveraineté', 'soberania', 'substantivo', 'La souveraineté a bloqué les discussions.', 'A soberania travou as conversas.', 'Diplomacia'],
    ['la réciprocité', 'reciprocidade', 'substantivo', "L'accord repose sur la réciprocité.", 'O acordo se apoia na reciprocidade.', 'Diplomacia'],
    ['la politique du pire', 'política do abismo', 'substantivo', "C'est de la pure politique du pire.", 'Isso é pura política do abismo.', 'Diplomacia'],
    ['la théodicée', 'teodiceia', 'substantivo', 'La théodicée interroge le mal.', 'A teodiceia interroga o mal.', 'Teologia e mito'],
    ['l’apothéose', 'apoteose', 'substantivo', "C'était l'apothéose du style.", 'Foi a apoteose do estilo.', 'Teologia e mito'],
    ['l’eschatologie', 'escatologia', 'substantivo', "L'eschatologie traite des fins dernières.", 'A escatologia trata das coisas últimas.', 'Teologia e mito'],
    ['la liturgie', 'liturgia', 'substantivo', 'La liturgie a des siècles.', 'A liturgia tem séculos.', 'Teologia e mito'],
    ['l’hérésie', 'heresia', 'substantivo', 'Ce fut condamné comme hérésie.', 'Foi condenado como heresia.', 'Teologia e mito'],
    ['le panthéon', 'panteão', 'substantivo', 'Elle est entrée au panthéon des grands.', 'Ela entrou no panteão dos grandes.', 'Teologia e mito'],
    ['l’oracle', 'oráculo', 'substantivo', "L'oracle parlait par énigmes.", 'O oráculo falava por enigmas.', 'Teologia e mito'],
    ['la relique', 'relíquia', 'substantivo', 'La relique attirait les pèlerins.', 'A relíquia atraía peregrinos.', 'Teologia e mito'],
    ['le schisme', 'cisma', 'substantivo', "Le schisme a divisé l'Église.", 'O cisma dividiu a igreja.', 'Teologia e mito'],
    ['la transcendance', 'transcendência', 'substantivo', 'Le poème vise la transcendance.', 'O poema busca a transcendência.', 'Teologia e mito'],
    ['a priori', 'a priori', 'advérbio', 'On ne peut pas le savoir a priori.', 'Isso não se sabe a priori.', 'Locuções cultas'],
    ['a fortiori', 'com mais razão ainda', 'advérbio', 'A fortiori, le second cas échoue.', 'Com mais razão ainda, o segundo caso falha.', 'Locuções cultas'],
    ['sine qua non', 'condição indispensável', 'adjetivo', "La confiance est la condition sine qua non.", 'A confiança é a condição indispensável.', 'Locuções cultas'],
    ['de facto', 'de fato', 'adjetivo', "Elle est la dirigeante de facto.", 'Ela é a líder de fato.', 'Locuções cultas'],
    ['ad hoc', 'ad hoc / improvisado', 'adjetivo', "C'était un comité ad hoc.", 'Era um comitê ad hoc.', 'Locuções cultas'],
    ['mutatis mutandis', 'feitas as devidas adaptações', 'advérbio', 'Cela vaut, mutatis mutandis.', 'Vale o mesmo, feitas as devidas adaptações.', 'Locuções cultas'],
    ['toutes choses égales par ailleurs', 'mantidas as demais condições', 'advérbio', 'Toutes choses égales par ailleurs, la demande baissera.', 'Mantidas as demais condições, a procura vai cair.', 'Locuções cultas'],
    ['prima facie', 'à primeira vista', 'adjetivo', 'Il y a un cas prima facie.', 'Há indício suficiente à primeira vista.', 'Locuções cultas'],
    ['en soi', 'em si mesmo', 'advérbio', "La règle n'est pas injuste en soi.", 'A regra não é injusta em si mesma.', 'Locuções cultas'],
    ['in extremis', 'em situação extrema', 'advérbio', "L'accord a été sauvé in extremis.", 'O acordo foi salvo in extremis.', 'Locuções cultas'],
    ['la nostalgie', 'saudade melancólica', 'substantivo', 'Elle en parlait avec nostalgie.', 'Ela falava disso com saudade.', 'Emoções sutis'],
    ['la mélancolie', 'melancolia', 'substantivo', 'Une mélancolie discrète le traverse.', 'Uma melancolia discreta o atravessa.', 'Emoções sutis'],
    ['l’ennui', 'tédio existencial', 'substantivo', "L'ennui des longs après-midis.", 'O tédio das tardes longas.', 'Emoções sutis'],
    ['l’exaltation', 'euforia', 'substantivo', 'Son exaltation fut brève.', 'A euforia dele durou pouco.', 'Emoções sutis'],
    ['l’inquiétude', 'inquietação', 'substantivo', "La nouvelle a causé une vraie inquiétude.", 'A notícia causou verdadeira inquietação.', 'Emoções sutis'],
    ['l’aspiration', 'anseio', 'substantivo', 'Une aspiration vers quelque chose de perdu.', 'Um anseio por algo perdido.', 'Emoções sutis'],
    ['la sérénité', 'serenidade', 'substantivo', 'Elle y a fait face avec sérénité.', 'Ela encarou com serenidade.', 'Emoções sutis'],
    ['l’indignation', 'indignação', 'substantivo', 'Son indignation était justifiée.', 'A indignação dele era justificada.', 'Emoções sutis'],
    ['la rêverie', 'devaneio', 'substantivo', 'Elle a sombré dans la rêverie.', 'Ela caiu num devaneio.', 'Emoções sutis'],
    ['le réconfort', 'consolo', 'substantivo', 'Il a trouvé du réconfort dans la musique.', 'Ele encontrou consolo na música.', 'Emoções sutis'],
  ],
};
