/** Italiano — segundo lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { LatinByLevel } from '../entry';

export const IT_THEMATIC2: LatinByLevel = {
  A1: [
    ['uno', 'um', 'numeral', 'Voglio una mela.', 'Quero uma maçã.', 'Números e quantidade'],
    ['due', 'dois', 'numeral', 'Ha due fratelli.', 'Ela tem dois irmãos.', 'Números e quantidade'],
    ['tre', 'três', 'numeral', 'Abbiamo aspettato tre ore.', 'Esperamos três horas.', 'Números e quantidade'],
    ['molti', 'muitos', 'determinante', 'Ci sono molte persone.', 'Há muitas pessoas.', 'Números e quantidade'],
    ['pochi', 'poucos', 'determinante', 'Sono venuti pochi studenti.', 'Vieram poucos alunos.', 'Números e quantidade'],
    ['la metà', 'metade', 'substantivo', 'Ne ho mangiato la metà.', 'Comi metade.', 'Números e quantidade'],
    ['vuoto', 'vazio', 'adjetivo', 'La bottiglia è vuota.', 'A garrafa está vazia.', 'Números e quantidade'],
    ['pieno', 'cheio', 'adjetivo', 'Il bicchiere è pieno.', 'O copo está cheio.', 'Números e quantidade'],
    ['pesante', 'pesado', 'adjetivo', 'Questa scatola è pesante.', 'Esta caixa é pesada.', 'Números e quantidade'],
    ['leggero', 'leve', 'adjetivo', 'La borsa è leggera.', 'A bolsa é leve.', 'Números e quantidade'],
    ['svegliarsi', 'acordar', 'verbo', 'Mi sveglio alle sei.', 'Eu acordo às seis.', 'Ações do dia a dia'],
    ['dormire', 'dormir', 'verbo', 'Dormo otto ore.', 'Eu durmo oito horas.', 'Ações do dia a dia'],
    ['lavare', 'lavar', 'verbo', 'Lavati le mani.', 'Lave as mãos.', 'Ações do dia a dia'],
    ['cucinare', 'cozinhar', 'verbo', 'Lei cucina ogni sera.', 'Ela cozinha toda noite.', 'Ações do dia a dia'],
    ['pulire', 'limpar', 'verbo', 'Pulisco la casa.', 'Eu limpo a casa.', 'Ações do dia a dia'],
    ['comprare', 'comprar', 'verbo', 'Compro il pane qui.', 'Eu compro pão aqui.', 'Ações do dia a dia'],
    ['vendere', 'vender', 'verbo', 'Vendono frutta.', 'Eles vendem fruta.', 'Ações do dia a dia'],
    ['camminare', 'caminhar', 'verbo', 'Camminiamo fino a scuola.', 'Nós caminhamos até a escola.', 'Ações do dia a dia'],
    ['correre', 'correr', 'verbo', 'Lui corre veloce.', 'Ele corre rápido.', 'Ações do dia a dia'],
    ['aspettare', 'esperar', 'verbo', 'Aspetta qui, per favore.', 'Espere aqui, por favor.', 'Ações do dia a dia'],
    ['l’insegnante', 'professor', 'substantivo', "L'insegnante è gentile.", 'O professor é gentil.', 'Escola'],
    ['lo studente', 'aluno', 'substantivo', 'È una brava studentessa.', 'Ela é uma boa aluna.', 'Escola'],
    ['il libro', 'livro', 'substantivo', 'Questo libro è lungo.', 'Este livro é longo.', 'Escola'],
    ['la penna', 'caneta', 'substantivo', 'Mi serve una penna.', 'Preciso de uma caneta.', 'Escola'],
    ['la carta', 'papel', 'substantivo', 'Dammi un foglio di carta.', 'Me dê uma folha de papel.', 'Escola'],
    ['la lezione', 'aula', 'substantivo', 'La lezione comincia adesso.', 'A aula começa agora.', 'Escola'],
    ['i compiti', 'lição de casa', 'substantivo', 'Ho finito i compiti.', 'Terminei a lição de casa.', 'Escola'],
    ['la verifica', 'prova', 'substantivo', 'La verifica era difficile.', 'A prova foi difícil.', 'Escola'],
    ['l’aula', 'sala de aula', 'substantivo', "L'aula è grande.", 'A sala de aula é grande.', 'Escola'],
    ['il quesito', 'pergunta / questão', 'substantivo', 'Ho un quesito.', 'Tenho uma pergunta.', 'Escola'],
    ['l’uccello', 'pássaro', 'substantivo', 'Un uccello sta cantando.', 'Um pássaro está cantando.', 'Animais'],
    ['il pesce', 'peixe', 'substantivo', 'Il pesce è piccolo.', 'O peixe é pequeno.', 'Animais'],
    ['il cavallo', 'cavalo', 'substantivo', 'Il cavallo è veloce.', 'O cavalo é rápido.', 'Animais'],
    ['la mucca', 'vaca', 'substantivo', "La mucca mangia l'erba.", 'A vaca come grama.', 'Animais'],
    ['la gallina', 'galinha', 'substantivo', 'Abbiamo tre galline.', 'Temos três galinhas.', 'Animais'],
    ['il topo', 'rato', 'substantivo', "C'è un topo qui.", 'Tem um rato aqui.', 'Animais'],
    ['l’insetto', 'inseto', 'substantivo', 'È entrato un insetto.', 'Entrou um inseto.', 'Animais'],
    ['la pecora', 'ovelha', 'substantivo', 'Le pecore sono bianche.', 'As ovelhas são brancas.', 'Animais'],
    ['il maiale', 'porco', 'substantivo', 'Il maiale è sporco.', 'O porco está sujo.', 'Animais'],
    ['il coniglio', 'coelho', 'substantivo', 'Il coniglio è veloce.', 'O coelho é rápido.', 'Animais'],
  ],
  A2: [
    ['l’autobus', 'ônibus', 'substantivo', "L'autobus è in ritardo.", 'O ônibus está atrasado.', 'Transporte'],
    ['il treno', 'trem', 'substantivo', 'Il treno parte alle otto.', 'O trem sai às oito.', 'Transporte'],
    ['la macchina', 'carro', 'substantivo', 'La mia macchina è vecchia.', 'Meu carro é velho.', 'Transporte'],
    ['la bicicletta', 'bicicleta', 'substantivo', 'Vado in bicicletta.', 'Eu vou de bicicleta.', 'Transporte'],
    ['il taxi', 'táxi', 'substantivo', 'Prendiamo un taxi.', 'Vamos pegar um táxi.', 'Transporte'],
    ['l’autista', 'motorista', 'substantivo', "L'autista è stato gentile.", 'O motorista foi gentil.', 'Transporte'],
    ['la tariffa', 'tarifa', 'substantivo', 'La tariffa è aumentata.', 'A tarifa subiu.', 'Transporte'],
    ['il binario', 'plataforma', 'substantivo', 'Aspetta al binario due.', 'Espere na plataforma dois.', 'Transporte'],
    ['il posto a sedere', 'assento', 'substantivo', 'Questo posto a sedere è libero.', 'Este assento está livre.', 'Transporte'],
    ['il viaggio', 'viagem', 'substantivo', 'Il viaggio dura due ore.', 'A viagem dura duas horas.', 'Transporte'],
    ['il passatempo', 'passatempo', 'substantivo', 'Leggere è il mio passatempo.', 'Ler é meu passatempo.', 'Lazer'],
    ['il museo', 'museu', 'substantivo', 'Il museo oggi è gratis.', 'O museu está de graça hoje.', 'Lazer'],
    ['il cinema', 'cinema', 'substantivo', 'Siamo andati al cinema.', 'Fomos ao cinema.', 'Lazer'],
    ['il concerto', 'show / concerto', 'substantivo', 'Il concerto è stato bellissimo.', 'O show foi ótimo.', 'Lazer'],
    ['il parco', 'parque', 'substantivo', 'Il parco è qui vicino.', 'O parque fica aqui perto.', 'Lazer'],
    ['il gioco', 'jogo', 'substantivo', 'Questo gioco è divertente.', 'Este jogo é divertido.', 'Lazer'],
    ['la macchina fotografica', 'câmera', 'substantivo', 'Porta la macchina fotografica.', 'Traga sua câmera.', 'Lazer'],
    ['il picnic', 'piquenique', 'substantivo', 'Abbiamo fatto un picnic.', 'Fizemos um piquenique.', 'Lazer'],
    ['nuotare', 'nadar', 'verbo', 'Nuoto la domenica.', 'Eu nado aos domingos.', 'Lazer'],
    ['ballare', 'dançar', 'verbo', 'Ballano molto bene.', 'Eles dançam muito bem.', 'Lazer'],
    ['felice', 'feliz', 'adjetivo', 'Sembra felice.', 'Ela parece feliz.', 'Emoções'],
    ['triste', 'triste', 'adjetivo', 'Ieri era triste.', 'Ele estava triste ontem.', 'Emoções'],
    ['arrabbiato', 'bravo', 'adjetivo', 'Non essere arrabbiato.', 'Não fique bravo.', 'Emoções'],
    ['spaventato', 'com medo', 'adjetivo', 'Sono spaventato.', 'Estou com medo.', 'Emoções'],
    ['sorpreso', 'surpreso', 'adjetivo', 'Siamo rimasti sorpresi.', 'Ficamos surpresos.', 'Emoções'],
    ['annoiato', 'entediado', 'adjetivo', 'I bambini sono annoiati.', 'As crianças estão entediadas.', 'Emoções'],
    ['preoccupato', 'preocupado', 'adjetivo', 'È preoccupata per questo.', 'Ela está preocupada com isso.', 'Emoções'],
    ['orgoglioso', 'orgulhoso', 'adjetivo', 'Sono orgoglioso di te.', 'Estou orgulhoso de você.', 'Emoções'],
    ['calmo', 'calmo', 'adjetivo', 'Cerca di restare calmo.', 'Tente ficar calmo.', 'Emoções'],
    ['solo', 'sozinho / solitário', 'adjetivo', 'Si sente molto solo.', 'Ele se sente muito sozinho.', 'Emoções'],
    ['giovane', 'jovem', 'adjetivo', 'È molto giovane.', 'Ela é muito jovem.', 'Descrever pessoas'],
    ['vecchio', 'velho', 'adjetivo', 'Mio nonno è vecchio.', 'Meu avô é velho.', 'Descrever pessoas'],
    ['gentile', 'gentil', 'adjetivo', 'È un uomo gentile.', 'Ele é um homem gentil.', 'Descrever pessoas'],
    ['divertente', 'engraçado', 'adjetivo', 'Il tuo amico è divertente.', 'Seu amigo é engraçado.', 'Descrever pessoas'],
    ['silenzioso', 'quieto', 'adjetivo', 'È molto silenziosa.', 'Ela é muito quieta.', 'Descrever pessoas'],
    ['furbo', 'esperto', 'adjetivo', 'È stata un’idea furba.', 'Foi uma ideia esperta.', 'Descrever pessoas'],
    ['pigro', 'preguiçoso', 'adjetivo', 'Non essere pigro.', 'Não seja preguiçoso.', 'Descrever pessoas'],
    ['onesto', 'honesto', 'adjetivo', 'È sempre onesta.', 'Ela é sempre honesta.', 'Descrever pessoas'],
    ['simpatico', 'simpático', 'adjetivo', 'Lo staff è simpatico.', 'A equipe é simpática.', 'Descrever pessoas'],
    ['forte', 'forte', 'adjetivo', 'È molto forte.', 'Ele é muito forte.', 'Descrever pessoas'],
  ],
  B1: [
    ['l’alimentazione', 'alimentação', 'substantivo', "La sua alimentazione è cambiata molto.", 'A alimentação dela mudou muito.', 'Saúde e bem-estar'],
    ['l’esercizio fisico', 'exercício físico', 'substantivo', "L'esercizio fisico aiuta a dormire.", 'O exercício físico ajuda a dormir.', 'Saúde e bem-estar'],
    ['lo stress', 'estresse', 'substantivo', 'Lo stress colpisce il corpo.', 'O estresse afeta o corpo.', 'Saúde e bem-estar'],
    ['l’abitudine', 'hábito', 'substantivo', 'È diventata un’abitudine.', 'Virou um hábito.', 'Saúde e bem-estar'],
    ['la terapia', 'terapia', 'substantivo', "La terapia l'ha aiutato molto.", 'A terapia o ajudou muito.', 'Saúde e bem-estar'],
    ['la guarigione', 'recuperação', 'substantivo', 'La guarigione richiede tempo.', 'A recuperação leva tempo.', 'Saúde e bem-estar'],
    ['la postura', 'postura', 'substantivo', 'Correggi la postura.', 'Corrija a postura.', 'Saúde e bem-estar'],
    ['la respirazione', 'respiração', 'substantivo', 'La respirazione lenta calma.', 'A respiração lenta acalma.', 'Saúde e bem-estar'],
    ['il controllo medico', 'check-up', 'substantivo', 'Oggi ho fatto un controllo medico.', 'Hoje fiz um check-up.', 'Saúde e bem-estar'],
    ['il benessere', 'bem-estar', 'substantivo', 'Tengono al benessere.', 'Eles se importam com o bem-estar.', 'Saúde e bem-estar'],
    ['l’affitto', 'aluguel', 'substantivo', "L'affitto è aumentato di nuovo.", 'O aluguel subiu de novo.', 'Moradia'],
    ['il contratto di locazione', 'contrato de locação', 'substantivo', 'Il contratto di locazione scade a giugno.', 'O contrato acaba em junho.', 'Moradia'],
    ['la caparra', 'caução', 'substantivo', 'Si sono tenuti la caparra.', 'Ficaram com a caução.', 'Moradia'],
    ['l’inquilino', 'inquilino', 'substantivo', "L'inquilino si è lamentato.", 'O inquilino reclamou.', 'Moradia'],
    ['il soffitto', 'teto', 'substantivo', 'Il soffitto perde acqua.', 'O teto está vazando.', 'Moradia'],
    ['il tetto', 'telhado', 'substantivo', 'Il tetto va riparato.', 'O telhado precisa de conserto.', 'Moradia'],
    ['la cantina', 'porão', 'substantivo', 'La cantina è umida.', 'O porão está úmido.', 'Moradia'],
    ['il balcone', 'varanda', 'substantivo', 'Mangiamo sul balcone.', 'Comemos na varanda.', 'Moradia'],
    ['l’impianto idraulico', 'encanamento', 'substantivo', "L'impianto idraulico è vecchio.", 'O encanamento é velho.', 'Moradia'],
    ['la padrona di casa', 'senhoria', 'substantivo', 'La padrona di casa mi ha chiamato.', 'A senhoria me ligou.', 'Moradia'],
    ['la ricetta', 'receita', 'substantivo', 'Mandami la ricetta.', 'Me manda a receita.', 'Culinária'],
    ['l’ingrediente', 'ingrediente', 'substantivo', 'Manca un ingrediente.', 'Falta um ingrediente.', 'Culinária'],
    ['bollire', 'ferver', 'verbo', "Fai bollire prima l'acqua.", 'Ferva a água primeiro.', 'Culinária'],
    ['friggere', 'fritar', 'verbo', 'Friggi la cipolla piano.', 'Frite a cebola devagar.', 'Culinária'],
    ['infornare', 'levar ao forno', 'verbo', 'Infornalo per un’ora.', 'Leve ao forno por uma hora.', 'Culinária'],
    ['tritare', 'picar', 'verbo', "Trita l'aglio molto fine.", 'Pique o alho bem fino.', 'Culinária'],
    ['condire', 'temperar', 'verbo', 'Condisci con il pepe.', 'Tempere com pimenta.', 'Culinária'],
    ['l’impasto', 'massa (crua)', 'substantivo', "L'impasto deve riposare.", 'A massa precisa descansar.', 'Culinária'],
    ['arrostire', 'assar (carne)', 'verbo', 'Arrostiamo la carne lentamente.', 'Assamos a carne devagar.', 'Culinária'],
    ['cuocere a vapore', 'cozinhar no vapor', 'verbo', 'Cuoci le verdure a vapore.', 'Cozinhe os legumes no vapor.', 'Culinária'],
    ['il messaggio', 'mensagem', 'substantivo', 'Ho ricevuto il tuo messaggio.', 'Recebi sua mensagem.', 'Comunicação'],
    ['la risposta', 'resposta', 'substantivo', 'Aspetto una risposta.', 'Estou esperando uma resposta.', 'Comunicação'],
    ['l’avviso', 'aviso', 'substantivo', "C'è un avviso sulla porta.", 'Há um aviso na porta.', 'Comunicação'],
    ['il comunicato', 'comunicado', 'substantivo', 'Hanno fatto un comunicato.', 'Fizeram um comunicado.', 'Comunicação'],
    ['la voce di corridoio', 'boato', 'substantivo', 'È solo una voce di corridoio.', 'É só um boato.', 'Comunicação'],
    ['la dichiarazione', 'declaração', 'substantivo', 'Ha rilasciato una dichiarazione.', 'Ela divulgou uma declaração.', 'Comunicação'],
    ['spiegare', 'explicar', 'verbo', 'Spiegalo di nuovo, per favore.', 'Explique de novo, por favor.', 'Comunicação'],
    ['descrivere', 'descrever', 'verbo', 'Descrivi quello che hai visto.', 'Descreva o que você viu.', 'Comunicação'],
    ['riassumere', 'resumir', 'verbo', 'Riassumilo in una riga.', 'Resuma em uma linha.', 'Comunicação'],
    ['il malinteso', 'mal-entendido', 'substantivo', 'È stato un malinteso.', 'Foi um mal-entendido.', 'Comunicação'],
  ],
  B2: [
    ['la scultura', 'escultura', 'substantivo', 'La scultura è di bronzo.', 'A escultura é de bronze.', 'Arte e cultura'],
    ['la mostra', 'exposição', 'substantivo', 'La mostra apre venerdì.', 'A exposição abre sexta.', 'Arte e cultura'],
    ['il ritratto', 'retrato', 'substantivo', 'Ha dipinto un ritratto.', 'Ela pintou um retrato.', 'Arte e cultura'],
    ['la tela', 'tela (de pintura)', 'substantivo', 'La tela era bianca.', 'A tela estava em branco.', 'Arte e cultura'],
    ['l’orchestra', 'orquestra', 'substantivo', "L'orchestra ha provato.", 'A orquestra ensaiou.', 'Arte e cultura'],
    ['il coro', 'coral', 'substantivo', 'Canta in un coro.', 'Ela canta num coral.', 'Arte e cultura'],
    ['il drammaturgo', 'dramaturgo', 'substantivo', 'Il drammaturgo è famoso.', 'O dramaturgo é famoso.', 'Arte e cultura'],
    ['il romanziere', 'romancista', 'substantivo', 'È una giovane romanziera.', 'Ela é uma jovem romancista.', 'Arte e cultura'],
    ['il folclore', 'folclore', 'substantivo', 'Il folclore locale è ricco.', 'O folclore local é rico.', 'Arte e cultura'],
    ['il patrimonio culturale', 'patrimônio cultural', 'substantivo', 'È un sito del patrimonio culturale.', 'É um sítio de patrimônio cultural.', 'Arte e cultura'],
    ['l’impero', 'império', 'substantivo', "L'impero è crollato.", 'O império ruiu.', 'História'],
    ['la rivoluzione', 'revolução', 'substantivo', 'La rivoluzione ha cambiato tutto.', 'A revolução mudou tudo.', 'História'],
    ['il trattato', 'tratado', 'substantivo', 'Hanno firmato un trattato.', 'Assinaram um tratado.', 'História'],
    ['la colonia', 'colônia', 'substantivo', 'Un tempo era una colonia.', 'Já foi uma colônia.', 'História'],
    ['la dinastia', 'dinastia', 'substantivo', 'La dinastia durò secoli.', 'A dinastia durou séculos.', 'História'],
    ['la rivolta', 'levante', 'substantivo', 'La rivolta fu repressa.', 'O levante foi reprimido.', 'História'],
    ['l’assedio', 'cerco', 'substantivo', "L'assedio durò un anno.", 'O cerco durou um ano.', 'História'],
    ['l’archivio storico', 'arquivo histórico', 'substantivo', "L'archivio storico conserva le lettere.", 'O arquivo histórico guarda as cartas.', 'História'],
    ['la cronaca storica', 'crônica histórica', 'substantivo', 'La cronaca storica lo nomina.', 'A crônica histórica o nomeia.', 'História'],
    ['il reperto', 'artefato', 'substantivo', 'Hanno trovato un reperto.', 'Encontraram um artefato.', 'História'],
    ['il continente', 'continente', 'substantivo', 'È il continente più grande.', 'É o maior continente.', 'Geografia'],
    ['la penisola', 'península', 'substantivo', 'La penisola è rocciosa.', 'A península é rochosa.', 'Geografia'],
    ['l’altopiano', 'planalto', 'substantivo', "L'altopiano è secco.", 'O planalto é seco.', 'Geografia'],
    ['il ghiacciaio', 'geleira', 'substantivo', 'Il ghiacciaio si ritira.', 'A geleira está recuando.', 'Geografia'],
    ['il delta', 'delta (de rio)', 'substantivo', 'Il delta è fertile.', 'O delta é fértil.', 'Geografia'],
    ['la valle', 'vale', 'substantivo', 'La valle si allaga spesso.', 'O vale alaga com frequência.', 'Geografia'],
    ['il deserto', 'deserto', 'substantivo', 'Il deserto avanza.', 'O deserto está avançando.', 'Geografia'],
    ['la marea', 'maré', 'substantivo', 'La marea sta salendo.', 'A maré está subindo.', 'Geografia'],
    ['la latitudine', 'latitude', 'substantivo', 'Controlla prima la latitudine.', 'Confira a latitude primeiro.', 'Geografia'],
    ['il terreno', 'terreno', 'substantivo', 'Il terreno è difficile.', 'O terreno é difícil.', 'Geografia'],
    ['l’integrità', 'integridade', 'substantivo', 'La sua integrità è fuori discussione.', 'A integridade dele é inquestionável.', 'Ética'],
    ['la virtù', 'virtude', 'substantivo', 'La pazienza è una virtù.', 'A paciência é uma virtude.', 'Ética'],
    ['il dovere', 'dever', 'substantivo', 'È tuo dovere segnalarlo.', 'É seu dever relatar isso.', 'Ética'],
    ['il consenso informato', 'consentimento', 'substantivo', 'Hanno agito senza consenso informato.', 'Agiram sem consentimento.', 'Ética'],
    ['l’equità', 'equidade', 'substantivo', "Qui conta l'equità.", 'Aqui a equidade importa.', 'Ética'],
    ['il danno', 'dano', 'substantivo', 'La misura ha causato un danno reale.', 'A medida causou dano real.', 'Ética'],
    ['la dignità', 'dignidade', 'substantivo', 'Trattali con dignità.', 'Trate-os com dignidade.', 'Ética'],
    ['l’obbligo', 'obrigação', 'substantivo', 'Abbiamo un obbligo.', 'Temos uma obrigação.', 'Ética'],
    ['la condotta scorretta', 'má conduta', 'substantivo', 'È stato licenziato per condotta scorretta.', 'Foi demitido por má conduta.', 'Ética'],
    ['il segnalante', 'denunciante', 'substantivo', 'Il segnalante è stato protetto.', 'O denunciante foi protegido.', 'Ética'],
  ],
  C1: [
    ['la burocrazia', 'burocracia', 'substantivo', 'La burocrazia ha rallentato tutto.', 'A burocracia atrasou tudo.', 'Administração pública'],
    ['l’ordinanza', 'decreto municipal', 'substantivo', 'È passata una nuova ordinanza.', 'Um novo decreto foi aprovado.', 'Administração pública'],
    ['la conformità', 'conformidade', 'substantivo', 'La conformità è obbligatoria.', 'A conformidade é obrigatória.', 'Administração pública'],
    ['la vigilanza', 'fiscalização', 'substantivo', 'La vigilanza era debole.', 'A fiscalização era fraca.', 'Administração pública'],
    ['il protocollo', 'protocolo', 'substantivo', 'Segui il protocollo alla lettera.', 'Siga o protocolo à risca.', 'Administração pública'],
    ['la direttiva', 'diretriz', 'substantivo', 'La direttiva entra in vigore oggi.', 'A diretriz entra em vigor hoje.', 'Administração pública'],
    ['il quorum', 'quórum', 'substantivo', 'Non abbiamo raggiunto il quorum.', 'Não atingimos o quórum.', 'Administração pública'],
    ['il ruolo di ruolo', 'estabilidade no cargo', 'substantivo', 'Ha ottenuto il posto di ruolo.', 'Ela obteve estabilidade no cargo.', 'Administração pública'],
    ['la competenza', 'alçada / competência', 'substantivo', 'Questo esula dalla nostra competenza.', 'Isso foge da nossa alçada.', 'Administração pública'],
    ['il risarcimento', 'reparação', 'substantivo', 'Hanno chiesto un risarcimento.', 'Pediram reparação.', 'Administração pública'],
    ['la mediana', 'mediana', 'substantivo', 'Qui la mediana è più utile.', 'Aqui a mediana é mais útil.', 'Estatística'],
    ['la varianza', 'variância', 'substantivo', 'La varianza è troppo alta.', 'A variância é alta demais.', 'Estatística'],
    ['la deviazione standard', 'desvio padrão', 'substantivo', 'Riporta la deviazione standard.', 'Informe o desvio padrão.', 'Estatística'],
    ['la regressione', 'regressão', 'substantivo', 'La regressione spiega poco.', 'A regressão explica pouco.', 'Estatística'],
    ['la probabilità', 'probabilidade', 'substantivo', 'La probabilità è bassa.', 'A probabilidade é baixa.', 'Estatística'],
    ['la distribuzione', 'distribuição', 'substantivo', 'La distribuzione è asimmetrica.', 'A distribuição é assimétrica.', 'Estatística'],
    ['il valore anomalo', 'ponto fora da curva', 'substantivo', 'Togli quel valore anomalo.', 'Remova esse ponto fora da curva.', 'Estatística'],
    ['la significatività', 'significância', 'substantivo', 'La significatività non è importanza.', 'A significância não é importância.', 'Estatística'],
    ['la soglia', 'limiar', 'substantivo', 'È sceso sotto la soglia.', 'Ficou abaixo do limiar.', 'Estatística'],
    ['la stima', 'estimativa', 'substantivo', 'È una stima approssimativa.', 'É uma estimativa aproximada.', 'Estatística'],
    ['la sintassi', 'sintaxe', 'substantivo', 'Qui la sintassi cambia.', 'Aqui a sintaxe muda.', 'Linguística'],
    ['il morfema', 'morfema', 'substantivo', 'Quel prefisso è un morfema.', 'Esse prefixo é um morfema.', 'Linguística'],
    ['il fonema', 'fonema', 'substantivo', 'I due fonemi si oppongono.', 'Os dois fonemas se opõem.', 'Linguística'],
    ['la semantica', 'semântica', 'substantivo', 'La disputa è di semantica.', 'A disputa é de semântica.', 'Linguística'],
    ['il dialetto', 'dialeto', 'substantivo', 'Il dialetto varia per regione.', 'O dialeto varia por região.', 'Linguística'],
    ['il registro linguistico', 'registro de fala', 'substantivo', 'Adatta il registro linguistico al contesto.', 'Ajuste o registro de fala ao contexto.', 'Linguística'],
    ['l’etimologia', 'etimologia', 'substantivo', "L'etimologia è discussa.", 'A etimologia é contestada.', 'Linguística'],
    ['il cognato', 'cognato', 'substantivo', 'Queste due parole sono cognate.', 'Estas duas palavras são cognatas.', 'Linguística'],
    ['la flessione', 'flexão', 'substantivo', 'La flessione marca il caso.', 'A flexão marca o caso.', 'Linguística'],
    ['la scioltezza', 'fluência / desenvoltura', 'substantivo', 'La scioltezza non è correttezza.', 'A fluência não é correção.', 'Linguística'],
    ['la facciata', 'fachada', 'substantivo', 'La facciata è stata restaurata.', 'A fachada foi restaurada.', 'Arquitetura'],
    ['le fondamenta', 'fundação (de obra)', 'substantivo', 'Le fondamenta si sono crepate.', 'A fundação rachou.', 'Arquitetura'],
    ['il progetto architettonico', 'planta / projeto', 'substantivo', 'Ricontrolla il progetto architettonico.', 'Confira a planta de novo.', 'Arquitetura'],
    ['la volta', 'abóbada', 'substantivo', 'La volta è medievale.', 'A abóbada é medieval.', 'Arquitetura'],
    ['il ponteggio', 'andaime', 'substantivo', 'Oggi hanno montato il ponteggio.', 'O andaime subiu hoje.', 'Arquitetura'],
    ['la zonizzazione', 'zoneamento', 'substantivo', 'La zonizzazione lo ha impedito.', 'O zoneamento impediu.', 'Arquitetura'],
    ['la ristrutturazione', 'reforma', 'substantivo', 'La ristrutturazione è durata un anno.', 'A reforma levou um ano.', 'Arquitetura'],
    ['portante', 'estrutural (que sustenta)', 'adjetivo', 'Quello è un muro portante.', 'Aquela é uma parede estrutural.', 'Arquitetura'],
    ['l’espansione urbana', 'expansão urbana', 'substantivo', "L'espansione urbana non si ferma.", 'A expansão urbana não para.', 'Arquitetura'],
    ['il profilo urbano', 'silhueta urbana', 'substantivo', 'Il profilo urbano è cambiato del tutto.', 'A silhueta urbana mudou por completo.', 'Arquitetura'],
  ],
  C2: [
    ['la distensione', 'distensão (diplomática)', 'substantivo', 'La distensione non è durata.', 'A distensão não durou.', 'Diplomacia'],
    ['il riavvicinamento', 'reaproximação', 'substantivo', 'È iniziato un cauto riavvicinamento.', 'Começou uma reaproximação cautelosa.', 'Diplomacia'],
    ['il comunicato ufficiale', 'comunicado oficial', 'substantivo', 'Il comunicato ufficiale diceva poco.', 'O comunicado oficial dizia pouco.', 'Diplomacia'],
    ['l’inviato', 'emissário', 'substantivo', 'È stato mandato un inviato.', 'Um emissário foi enviado.', 'Diplomacia'],
    ['l’intesa', 'acordo formal', 'substantivo', "L'intesa per ora regge.", 'O acordo se mantém por ora.', 'Diplomacia'],
    ['la sanzione', 'sanção', 'substantivo', 'Le sanzioni sono state revocate.', 'As sanções foram suspensas.', 'Diplomacia'],
    ['la neutralità', 'neutralidade', 'substantivo', 'Hanno dichiarato la neutralità.', 'Declararam neutralidade.', 'Diplomacia'],
    ['la sovranità', 'soberania', 'substantivo', 'La sovranità è stata il nodo.', 'A soberania foi o impasse.', 'Diplomacia'],
    ['la reciprocità', 'reciprocidade', 'substantivo', "L'accordo si regge sulla reciprocità.", 'O acordo se apoia na reciprocidade.', 'Diplomacia'],
    ['il braccio di ferro', 'queda de braço', 'substantivo', 'È un puro braccio di ferro.', 'É pura queda de braço.', 'Diplomacia'],
    ['la teodicea', 'teodiceia', 'substantivo', 'La teodicea interroga il male.', 'A teodiceia interroga o mal.', 'Teologia e mito'],
    ['l’apoteosi', 'apoteose', 'substantivo', "Fu l'apoteosi dello stile.", 'Foi a apoteose do estilo.', 'Teologia e mito'],
    ['l’escatologia', 'escatologia', 'substantivo', "L'escatologia tratta delle cose ultime.", 'A escatologia trata das coisas últimas.', 'Teologia e mito'],
    ['la liturgia', 'liturgia', 'substantivo', 'La liturgia ha secoli.', 'A liturgia tem séculos.', 'Teologia e mito'],
    ['l’eresia', 'heresia', 'substantivo', 'Fu condannato come eresia.', 'Foi condenado como heresia.', 'Teologia e mito'],
    ['il pantheon', 'panteão', 'substantivo', 'È entrata nel pantheon dei grandi.', 'Ela entrou no panteão dos grandes.', 'Teologia e mito'],
    ['l’oracolo', 'oráculo', 'substantivo', "L'oracolo parlava per enigmi.", 'O oráculo falava por enigmas.', 'Teologia e mito'],
    ['la reliquia', 'relíquia', 'substantivo', 'La reliquia attirava pellegrini.', 'A relíquia atraía peregrinos.', 'Teologia e mito'],
    ['lo scisma', 'cisma', 'substantivo', 'Lo scisma divise la chiesa.', 'O cisma dividiu a igreja.', 'Teologia e mito'],
    ['la trascendenza', 'transcendência', 'substantivo', 'La poesia tende alla trascendenza.', 'A poesia busca a transcendência.', 'Teologia e mito'],
    ['a priori', 'a priori', 'advérbio', 'Non lo si può sapere a priori.', 'Isso não se sabe a priori.', 'Locuções cultas'],
    ['a fortiori', 'com mais razão ainda', 'advérbio', 'A fortiori, il secondo caso cade.', 'Com mais razão ainda, o segundo caso cai.', 'Locuções cultas'],
    ['sine qua non', 'condição indispensável', 'adjetivo', 'La fiducia è la condizione sine qua non.', 'A confiança é a condição indispensável.', 'Locuções cultas'],
    ['de facto', 'de fato', 'adjetivo', 'È la leader de facto.', 'Ela é a líder de fato.', 'Locuções cultas'],
    ['ad hoc', 'ad hoc / improvisado', 'adjetivo', 'Era un comitato ad hoc.', 'Era um comitê ad hoc.', 'Locuções cultas'],
    ['mutatis mutandis', 'feitas as devidas adaptações', 'advérbio', 'Vale lo stesso, mutatis mutandis.', 'Vale o mesmo, feitas as devidas adaptações.', 'Locuções cultas'],
    ['ceteris paribus', 'mantidas as demais condições', 'advérbio', 'Ceteris paribus, la domanda calerà.', 'Mantidas as demais condições, a procura vai cair.', 'Locuções cultas'],
    ['prima facie', 'à primeira vista', 'adjetivo', "C'è un caso prima facie.", 'Há indício suficiente à primeira vista.', 'Locuções cultas'],
    ['di per sé', 'em si mesmo', 'advérbio', 'La norma non è ingiusta di per sé.', 'A norma não é injusta em si mesma.', 'Locuções cultas'],
    ['in extremis', 'em situação extrema', 'advérbio', "L'accordo fu salvato in extremis.", 'O acordo foi salvo in extremis.', 'Locuções cultas'],
    ['la nostalgia', 'saudade melancólica', 'substantivo', 'Ne parlava con nostalgia.', 'Ela falava disso com saudade.', 'Emoções sutis'],
    ['la malinconia', 'melancolia', 'substantivo', 'Una malinconia discreta lo attraversa.', 'Uma melancolia discreta o atravessa.', 'Emoções sutis'],
    ['la noia esistenziale', 'tédio existencial', 'substantivo', 'La noia esistenziale dei pomeriggi lunghi.', 'O tédio existencial das tardes longas.', 'Emoções sutis'],
    ['l’euforia', 'euforia', 'substantivo', 'La sua euforia durò poco.', 'A euforia dele durou pouco.', 'Emoções sutis'],
    ['l’inquietudine', 'inquietação', 'substantivo', 'La notizia ha causato inquietudine.', 'A notícia causou inquietação.', 'Emoções sutis'],
    ['l’anelito', 'anseio', 'substantivo', 'Un anelito verso qualcosa di perduto.', 'Um anseio por algo perdido.', 'Emoções sutis'],
    ['la serenità', 'serenidade', 'substantivo', "L'ha affrontato con serenità.", 'Ela encarou com serenidade.', 'Emoções sutis'],
    ['l’indignazione', 'indignação', 'substantivo', 'La sua indignazione era giustificata.', 'A indignação dele era justificada.', 'Emoções sutis'],
    ['la fantasticheria', 'devaneio', 'substantivo', 'Si perse in una fantasticheria.', 'Ela se perdeu num devaneio.', 'Emoções sutis'],
    ['il conforto', 'consolo', 'substantivo', 'Trovò conforto nella musica.', 'Ele encontrou consolo na música.', 'Emoções sutis'],
  ],
};
