/** Japonês — segundo lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { AsianByLevel } from '../entry';

export const JA_THEMATIC2: AsianByLevel = {
  A1: [
    ['一つ', 'hitotsu', 'um (contagem)', 'numeral', 'りんごを一つください。', 'Ringo o hitotsu kudasai.', 'Uma maçã, por favor.', 'Números e quantidade'],
    ['二つ', 'futatsu', 'dois (contagem)', 'numeral', '二つ買いました。', 'Futatsu kaimashita.', 'Comprei dois.', 'Números e quantidade'],
    ['三つ', 'mittsu', 'três (contagem)', 'numeral', '三つ残っています。', 'Mittsu nokotte imasu.', 'Restam três.', 'Números e quantidade'],
    ['たくさん', 'takusan', 'muito / muitos', 'advérbio', '人がたくさんいます。', 'Hito ga takusan imasu.', 'Há muitas pessoas.', 'Números e quantidade'],
    ['少し', 'sukoshi', 'um pouco', 'advérbio', '少しだけ食べました。', 'Sukoshi dake tabemashita.', 'Comi só um pouco.', 'Números e quantidade'],
    ['半分', 'hanbun', 'metade', 'substantivo', '半分食べました。', 'Hanbun tabemashita.', 'Comi metade.', 'Números e quantidade'],
    ['空の', 'kara no', 'vazio', 'adjetivo', 'びんは空です。', 'Bin wa kara desu.', 'A garrafa está vazia.', 'Números e quantidade'],
    ['満杯', 'manpai', 'lotado / cheio', 'substantivo', '店は満杯です。', 'Mise wa manpai desu.', 'A loja está lotada.', 'Números e quantidade'],
    ['重い', 'omoi', 'pesado', 'adjetivo', 'この箱は重いです。', 'Kono hako wa omoi desu.', 'Esta caixa é pesada.', 'Números e quantidade'],
    ['軽い', 'karui', 'leve', 'adjetivo', 'かばんは軽いです。', 'Kaban wa karui desu.', 'A bolsa é leve.', 'Números e quantidade'],
    ['起きる', 'okiru', 'acordar / levantar', 'verbo', '六時に起きます。', 'Rokuji ni okimasu.', 'Eu acordo às seis.', 'Ações do dia a dia'],
    ['寝る', 'neru', 'dormir / deitar', 'verbo', '十時に寝ます。', 'Jūji ni nemasu.', 'Eu durmo às dez.', 'Ações do dia a dia'],
    ['洗う', 'arau', 'lavar', 'verbo', '手を洗ってください。', 'Te o aratte kudasai.', 'Lave as mãos.', 'Ações do dia a dia'],
    ['作る', 'tsukuru', 'fazer / preparar', 'verbo', '毎晩料理を作ります。', 'Maiban ryōri o tsukurimasu.', 'Preparo comida toda noite.', 'Ações do dia a dia'],
    ['掃除する', 'souji suru', 'limpar', 'verbo', '部屋を掃除します。', 'Heya o sōji shimasu.', 'Eu limpo o quarto.', 'Ações do dia a dia'],
    ['買う', 'kau', 'comprar', 'verbo', 'ここでパンを買います。', 'Koko de pan o kaimasu.', 'Eu compro pão aqui.', 'Ações do dia a dia'],
    ['売る', 'uru', 'vender', 'verbo', '果物を売っています。', 'Kudamono o utte imasu.', 'Eles vendem frutas.', 'Ações do dia a dia'],
    ['歩く', 'aruku', 'caminhar', 'verbo', '学校まで歩きます。', 'Gakkō made arukimasu.', 'Eu caminho até a escola.', 'Ações do dia a dia'],
    ['走る', 'hashiru', 'correr', 'verbo', '彼は速く走ります。', 'Kare wa hayaku hashirimasu.', 'Ele corre rápido.', 'Ações do dia a dia'],
    ['待つ', 'matsu', 'esperar', 'verbo', 'ここで待ってください。', 'Koko de matte kudasai.', 'Espere aqui, por favor.', 'Ações do dia a dia'],
    ['先生', 'sensei', 'professor', 'substantivo', '先生は親切です。', 'Sensei wa shinsetsu desu.', 'O professor é gentil.', 'Escola'],
    ['学生', 'gakusei', 'aluno', 'substantivo', '彼女はいい学生です。', 'Kanojo wa ii gakusei desu.', 'Ela é uma boa aluna.', 'Escola'],
    ['本', 'hon', 'livro', 'substantivo', 'この本は長いです。', 'Kono hon wa nagai desu.', 'Este livro é longo.', 'Escola'],
    ['ペン', 'pen', 'caneta', 'substantivo', 'ペンが要ります。', 'Pen ga irimasu.', 'Preciso de uma caneta.', 'Escola'],
    ['ノート', 'nooto', 'caderno', 'substantivo', 'ノートを開いてください。', 'Nōto o hiraite kudasai.', 'Abra o caderno.', 'Escola'],
    ['授業', 'jugyou', 'aula', 'substantivo', '授業が始まります。', 'Jugyō ga hajimarimasu.', 'A aula vai começar.', 'Escola'],
    ['宿題', 'shukudai', 'lição de casa', 'substantivo', '宿題を終えました。', 'Shukudai o oemashita.', 'Terminei a lição de casa.', 'Escola'],
    ['テスト', 'tesuto', 'prova', 'substantivo', 'テストは難しかったです。', 'Tesuto wa muzukashikatta desu.', 'A prova foi difícil.', 'Escola'],
    ['教室', 'kyoushitsu', 'sala de aula', 'substantivo', '教室は広いです。', 'Kyōshitsu wa hiroi desu.', 'A sala de aula é grande.', 'Escola'],
    ['質問', 'shitsumon', 'pergunta', 'substantivo', '質問があります。', 'Shitsumon ga arimasu.', 'Tenho uma pergunta.', 'Escola'],
    ['鳥', 'tori', 'pássaro', 'substantivo', '鳥が鳴いています。', 'Tori ga naite imasu.', 'Um pássaro está cantando.', 'Animais'],
    ['魚', 'sakana', 'peixe', 'substantivo', 'この魚は小さいです。', 'Kono sakana wa chiisai desu.', 'Este peixe é pequeno.', 'Animais'],
    ['馬', 'uma', 'cavalo', 'substantivo', '馬は速いです。', 'Uma wa hayai desu.', 'O cavalo é rápido.', 'Animais'],
    ['牛', 'ushi', 'vaca / boi', 'substantivo', '牛が草を食べています。', 'Ushi ga kusa o tabete imasu.', 'A vaca está comendo grama.', 'Animais'],
    ['鶏', 'niwatori', 'galinha', 'substantivo', '鶏が三羽います。', 'Niwatori ga sanba imasu.', 'Temos três galinhas.', 'Animais'],
    ['ねずみ', 'nezumi', 'rato', 'substantivo', 'ねずみがいます。', 'Nezumi ga imasu.', 'Tem um rato.', 'Animais'],
    ['虫', 'mushi', 'inseto', 'substantivo', '虫が入りました。', 'Mushi ga hairimashita.', 'Entrou um inseto.', 'Animais'],
    ['羊', 'hitsuji', 'ovelha', 'substantivo', '羊は白いです。', 'Hitsuji wa shiroi desu.', 'As ovelhas são brancas.', 'Animais'],
    ['豚', 'buta', 'porco', 'substantivo', '豚は汚れています。', 'Buta wa yogorete imasu.', 'O porco está sujo.', 'Animais'],
    ['うさぎ', 'usagi', 'coelho', 'substantivo', 'うさぎは速いです。', 'Usagi wa hayai desu.', 'O coelho é rápido.', 'Animais'],
  ],
  A2: [
    ['バス', 'basu', 'ônibus', 'substantivo', 'バスが遅れています。', 'Basu ga okurete imasu.', 'O ônibus está atrasado.', 'Transporte'],
    ['電車', 'densha', 'trem', 'substantivo', '電車は八時に出ます。', 'Densha wa hachiji ni demasu.', 'O trem sai às oito.', 'Transporte'],
    ['車', 'kuruma', 'carro', 'substantivo', '私の車は古いです。', 'Watashi no kuruma wa furui desu.', 'Meu carro é velho.', 'Transporte'],
    ['自転車', 'jitensha', 'bicicleta', 'substantivo', '自転車で行きます。', 'Jitensha de ikimasu.', 'Eu vou de bicicleta.', 'Transporte'],
    ['タクシー', 'takushii', 'táxi', 'substantivo', 'タクシーに乗りましょう。', 'Takushī ni norimashō.', 'Vamos pegar um táxi.', 'Transporte'],
    ['運転手', 'untenshu', 'motorista', 'substantivo', '運転手は丁寧でした。', 'Untenshu wa teinei deshita.', 'O motorista foi educado.', 'Transporte'],
    ['運賃', 'unchin', 'tarifa', 'substantivo', '運賃が上がりました。', 'Unchin ga agarimashita.', 'A tarifa subiu.', 'Transporte'],
    ['ホーム', 'hoomu', 'plataforma', 'substantivo', '二番ホームで待ってください。', 'Niban hōmu de matte kudasai.', 'Espere na plataforma dois.', 'Transporte'],
    ['座席', 'zaseki', 'assento', 'substantivo', 'この座席は空いています。', 'Kono zaseki wa aite imasu.', 'Este assento está livre.', 'Transporte'],
    ['移動', 'idou', 'deslocamento', 'substantivo', '移動に二時間かかります。', 'Idō ni nijikan kakarimasu.', 'O deslocamento leva duas horas.', 'Transporte'],
    ['趣味', 'shumi', 'passatempo', 'substantivo', '読書が趣味です。', 'Dokusho ga shumi desu.', 'Ler é meu passatempo.', 'Lazer'],
    ['博物館', 'hakubutsukan', 'museu', 'substantivo', '今日は博物館が無料です。', 'Kyō wa hakubutsukan ga muryō desu.', 'Hoje o museu está de graça.', 'Lazer'],
    ['映画館', 'eigakan', 'cinema', 'substantivo', '映画館へ行きました。', 'Eigakan e ikimashita.', 'Fomos ao cinema.', 'Lazer'],
    ['コンサート', 'konsaato', 'show / concerto', 'substantivo', 'コンサートはよかったです。', 'Konsāto wa yokatta desu.', 'O show foi ótimo.', 'Lazer'],
    ['公園', 'kouen', 'parque', 'substantivo', '公園は近いです。', 'Kōen wa chikai desu.', 'O parque fica perto.', 'Lazer'],
    ['ゲーム', 'geemu', 'jogo', 'substantivo', 'このゲームは面白いです。', 'Kono gēmu wa omoshiroi desu.', 'Este jogo é divertido.', 'Lazer'],
    ['カメラ', 'kamera', 'câmera', 'substantivo', 'カメラを持って来てください。', 'Kamera o motte kite kudasai.', 'Traga sua câmera.', 'Lazer'],
    ['ピクニック', 'pikunikku', 'piquenique', 'substantivo', 'ピクニックをしました。', 'Pikunikku o shimashita.', 'Fizemos um piquenique.', 'Lazer'],
    ['泳ぐ', 'oyogu', 'nadar', 'verbo', '日曜日に泳ぎます。', 'Nichiyōbi ni oyogimasu.', 'Eu nado aos domingos.', 'Lazer'],
    ['踊る', 'odoru', 'dançar', 'verbo', '彼らは上手に踊ります。', 'Karera wa jōzu ni odorimasu.', 'Eles dançam muito bem.', 'Lazer'],
    ['嬉しい', 'ureshii', 'contente', 'adjetivo', '彼女は嬉しそうです。', 'Kanojo wa ureshisō desu.', 'Ela parece contente.', 'Emoções'],
    ['悲しい', 'kanashii', 'triste', 'adjetivo', '昨日は悲しかったです。', 'Kinō wa kanashikatta desu.', 'Ontem eu estava triste.', 'Emoções'],
    ['怒った', 'okotta', 'bravo', 'adjetivo', '彼は怒った顔をしています。', 'Kare wa okotta kao o shite imasu.', 'Ele está com cara de bravo.', 'Emoções'],
    ['怖い', 'kowai', 'assustador / com medo', 'adjetivo', '犬が怖いです。', 'Inu ga kowai desu.', 'Tenho medo de cachorro.', 'Emoções'],
    ['驚いた', 'odoroita', 'surpreso', 'adjetivo', 'とても驚きました。', 'Totemo odorokimashita.', 'Fiquei muito surpreso.', 'Emoções'],
    ['退屈な', 'taikutsu na', 'entediante', 'adjetivo', '子どもは退屈そうです。', 'Kodomo wa taikutsu sō desu.', 'As crianças parecem entediadas.', 'Emoções'],
    ['心配な', 'shinpai na', 'preocupado', 'adjetivo', 'それが心配です。', 'Sore ga shinpai desu.', 'Estou preocupado com isso.', 'Emoções'],
    ['誇らしい', 'hokorashii', 'orgulhoso', 'adjetivo', '君が誇らしいです。', 'Kimi ga hokorashii desu.', 'Estou orgulhoso de você.', 'Emoções'],
    ['落ち着いた', 'ochitsuita', 'calmo', 'adjetivo', '落ち着いた声で話しました。', 'Ochitsuita koe de hanashimashita.', 'Falou com voz calma.', 'Emoções'],
    ['寂しい', 'sabishii', 'solitário', 'adjetivo', '一人で寂しいです。', 'Hitori de sabishii desu.', 'Me sinto solitário sozinho.', 'Emoções'],
    ['若い', 'wakai', 'jovem', 'adjetivo', '彼女はとても若いです。', 'Kanojo wa totemo wakai desu.', 'Ela é muito jovem.', 'Descrever pessoas'],
    ['年配の', 'nenpai no', 'idoso', 'adjetivo', '年配の方が来ました。', 'Nenpai no kata ga kimashita.', 'Um senhor idoso veio.', 'Descrever pessoas'],
    ['優しい', 'yasashii', 'gentil', 'adjetivo', '彼は優しい人です。', 'Kare wa yasashii hito desu.', 'Ele é uma pessoa gentil.', 'Descrever pessoas'],
    ['面白い', 'omoshiroi', 'engraçado / interessante', 'adjetivo', '君の友達は面白いです。', 'Kimi no tomodachi wa omoshiroi desu.', 'Seu amigo é engraçado.', 'Descrever pessoas'],
    ['静かな', 'shizuka na', 'quieto', 'adjetivo', '彼女はとても静かです。', 'Kanojo wa totemo shizuka desu.', 'Ela é muito quieta.', 'Descrever pessoas'],
    ['賢い', 'kashikoi', 'esperto', 'adjetivo', '賢い考えでした。', 'Kashikoi kangae deshita.', 'Foi uma ideia esperta.', 'Descrever pessoas'],
    ['怠惰な', 'taida na', 'preguiçoso', 'adjetivo', '怠惰にならないでください。', 'Taida ni naranaide kudasai.', 'Não seja preguiçoso.', 'Descrever pessoas'],
    ['正直な', 'shoujiki na', 'honesto', 'adjetivo', '彼女はいつも正直です。', 'Kanojo wa itsumo shōjiki desu.', 'Ela é sempre honesta.', 'Descrever pessoas'],
    ['親切な', 'shinsetsu na', 'atencioso', 'adjetivo', 'スタッフは親切です。', 'Sutaffu wa shinsetsu desu.', 'A equipe é atenciosa.', 'Descrever pessoas'],
    ['強い', 'tsuyoi', 'forte', 'adjetivo', '彼はとても強いです。', 'Kare wa totemo tsuyoi desu.', 'Ele é muito forte.', 'Descrever pessoas'],
  ],
  B1: [
    ['食生活', 'shokuseikatsu', 'hábitos alimentares', 'substantivo', '食生活が変わりました。', 'Shokuseikatsu ga kawarimashita.', 'Os hábitos alimentares mudaram.', 'Saúde e bem-estar'],
    ['運動', 'undou', 'exercício físico', 'substantivo', '運動は睡眠に効きます。', 'Undō wa suimin ni kikimasu.', 'O exercício ajuda no sono.', 'Saúde e bem-estar'],
    ['ストレス', 'sutoresu', 'estresse', 'substantivo', 'ストレスは体に響きます。', 'Sutoresu wa karada ni hibikimasu.', 'O estresse afeta o corpo.', 'Saúde e bem-estar'],
    ['習慣', 'shuukan', 'hábito', 'substantivo', 'それが習慣になりました。', 'Sore ga shūkan ni narimashita.', 'Isso virou um hábito.', 'Saúde e bem-estar'],
    ['治療', 'chiryou', 'tratamento', 'substantivo', '治療がとても効きました。', 'Chiryō ga totemo kikimashita.', 'O tratamento funcionou muito bem.', 'Saúde e bem-estar'],
    ['回復', 'kaifuku', 'recuperação', 'substantivo', '回復には時間がかかります。', 'Kaifuku ni wa jikan ga kakarimasu.', 'A recuperação leva tempo.', 'Saúde e bem-estar'],
    ['姿勢', 'shisei', 'postura', 'substantivo', '姿勢を直してください。', 'Shisei o naoshite kudasai.', 'Corrija sua postura.', 'Saúde e bem-estar'],
    ['呼吸', 'kokyuu', 'respiração', 'substantivo', 'ゆっくりした呼吸は落ち着きます。', 'Yukkuri shita kokyū wa ochitsukimasu.', 'A respiração lenta acalma.', 'Saúde e bem-estar'],
    ['健康診断', 'kenkou shindan', 'check-up médico', 'substantivo', '今日健康診断を受けました。', 'Kyō kenkō shindan o ukemashita.', 'Fiz um check-up hoje.', 'Saúde e bem-estar'],
    ['健やかさ', 'sukoyakasa', 'bem-estar / saúde plena', 'substantivo', '健やかさを大事にしています。', 'Sukoyakasa o daiji ni shite imasu.', 'Damos valor ao bem-estar.', 'Saúde e bem-estar'],
    ['家賃', 'yachin', 'aluguel', 'substantivo', '家賃がまた上がりました。', 'Yachin ga mata agarimashita.', 'O aluguel subiu de novo.', 'Moradia'],
    ['賃貸契約', 'chintai keiyaku', 'contrato de locação', 'substantivo', '賃貸契約は六月までです。', 'Chintai keiyaku wa rokugatsu made desu.', 'O contrato vai até junho.', 'Moradia'],
    ['敷金', 'shikikin', 'caução', 'substantivo', '敷金は返りませんでした。', 'Shikikin wa kaerimasen deshita.', 'A caução não foi devolvida.', 'Moradia'],
    ['借り手', 'karite', 'inquilino', 'substantivo', '借り手が苦情を言いました。', 'Karite ga kujō o iimashita.', 'O inquilino reclamou.', 'Moradia'],
    ['天井', 'tenjou', 'teto', 'substantivo', '天井から水が漏れています。', 'Tenjō kara mizu ga morete imasu.', 'O teto está vazando.', 'Moradia'],
    ['屋根', 'yane', 'telhado', 'substantivo', '屋根の修理が必要です。', 'Yane no shūri ga hitsuyō desu.', 'O telhado precisa de conserto.', 'Moradia'],
    ['地下室', 'chikashitsu', 'porão', 'substantivo', '地下室は湿っています。', 'Chikashitsu wa shimette imasu.', 'O porão está úmido.', 'Moradia'],
    ['ベランダ', 'beranda', 'varanda', 'substantivo', 'ベランダで食べます。', 'Beranda de tabemasu.', 'Comemos na varanda.', 'Moradia'],
    ['配管', 'haikan', 'encanamento', 'substantivo', '配管が古いです。', 'Haikan ga furui desu.', 'O encanamento é velho.', 'Moradia'],
    ['家主', 'yanushi', 'proprietário do imóvel', 'substantivo', '家主から電話がありました。', 'Yanushi kara denwa ga arimashita.', 'O proprietário ligou.', 'Moradia'],
    ['レシピ', 'reshipi', 'receita', 'substantivo', 'レシピを送ってください。', 'Reshipi o okutte kudasai.', 'Me manda a receita.', 'Culinária'],
    ['材料', 'zairyou', 'ingrediente', 'substantivo', '材料が一つ足りません。', 'Zairyō ga hitotsu tarimasen.', 'Falta um ingrediente.', 'Culinária'],
    ['沸かす', 'wakasu', 'ferver (água)', 'verbo', '先にお湯を沸かします。', 'Saki ni oyu o wakashimasu.', 'Primeiro fervo a água.', 'Culinária'],
    ['揚げる', 'ageru', 'fritar', 'verbo', '玉ねぎをゆっくり揚げます。', 'Tamanegi o yukkuri agemasu.', 'Frito a cebola devagar.', 'Culinária'],
    ['焼く', 'yaku', 'assar / grelhar', 'verbo', '一時間焼いてください。', 'Ichijikan yaite kudasai.', 'Asse por uma hora.', 'Culinária'],
    ['刻む', 'kizamu', 'picar', 'verbo', 'にんにくを細かく刻みます。', 'Ninniku o komakaku kizamimasu.', 'Pico o alho bem fino.', 'Culinária'],
    ['味付けする', 'ajitsuke suru', 'temperar', 'verbo', 'こしょうで味付けします。', 'Koshō de ajitsuke shimasu.', 'Tempero com pimenta.', 'Culinária'],
    ['生地', 'kiji', 'massa (crua)', 'substantivo', '生地を休ませてください。', 'Kiji o yasumasete kudasai.', 'Deixe a massa descansar.', 'Culinária'],
    ['煮込む', 'nikomu', 'cozinhar em fogo baixo', 'verbo', '肉をゆっくり煮込みます。', 'Niku o yukkuri nikomimasu.', 'Cozinho a carne devagar.', 'Culinária'],
    ['蒸す', 'musu', 'cozinhar no vapor', 'verbo', '野菜を蒸してください。', 'Yasai o mushite kudasai.', 'Cozinhe os legumes no vapor.', 'Culinária'],
    ['メッセージ', 'messeeji', 'mensagem', 'substantivo', 'メッセージを受け取りました。', 'Messēji o uketorimashita.', 'Recebi a mensagem.', 'Comunicação'],
    ['返信', 'henshin', 'resposta', 'substantivo', '返信を待っています。', 'Henshin o matte imasu.', 'Estou esperando resposta.', 'Comunicação'],
    ['お知らせ', 'oshirase', 'aviso', 'substantivo', 'ドアにお知らせがあります。', 'Doa ni oshirase ga arimasu.', 'Há um aviso na porta.', 'Comunicação'],
    ['発表', 'happyou', 'anúncio / apresentação', 'substantivo', '発表がありました。', 'Happyō ga arimashita.', 'Houve um anúncio.', 'Comunicação'],
    ['噂', 'uwasa', 'boato', 'substantivo', 'ただの噂です。', 'Tada no uwasa desu.', 'É só um boato.', 'Comunicação'],
    ['声明', 'seimei', 'declaração pública', 'substantivo', '声明を出しました。', 'Seimei o dashimashita.', 'Divulgou uma declaração.', 'Comunicação'],
    ['説明する', 'setsumei suru', 'explicar', 'verbo', 'もう一度説明してください。', 'Mō ichido setsumei shite kudasai.', 'Explique de novo, por favor.', 'Comunicação'],
    ['描写する', 'byousha suru', 'descrever', 'verbo', '見たものを描写してください。', 'Mita mono o byōsha shite kudasai.', 'Descreva o que você viu.', 'Comunicação'],
    ['要約する', 'youyaku suru', 'resumir', 'verbo', '一行で要約してください。', 'Ichigyō de yōyaku shite kudasai.', 'Resuma em uma linha.', 'Comunicação'],
    ['誤解', 'gokai', 'mal-entendido', 'substantivo', 'それは誤解でした。', 'Sore wa gokai deshita.', 'Foi um mal-entendido.', 'Comunicação'],
  ],
  B2: [
    ['彫刻', 'choukoku', 'escultura', 'substantivo', 'この彫刻は青銅製です。', 'Kono chōkoku wa seidōsei desu.', 'Esta escultura é de bronze.', 'Arte e cultura'],
    ['展覧会', 'tenrankai', 'exposição', 'substantivo', '展覧会は金曜に始まります。', 'Tenrankai wa kin’yō ni hajimarimasu.', 'A exposição abre sexta.', 'Arte e cultura'],
    ['肖像画', 'shouzouga', 'retrato', 'substantivo', '肖像画を描きました。', 'Shōzōga o kakimashita.', 'Pintou um retrato.', 'Arte e cultura'],
    ['キャンバス', 'kyanbasu', 'tela (de pintura)', 'substantivo', 'キャンバスは白いままでした。', 'Kyanbasu wa shiroi mama deshita.', 'A tela ficou em branco.', 'Arte e cultura'],
    ['管弦楽団', 'kangengakudan', 'orquestra', 'substantivo', '管弦楽団が練習しました。', 'Kangengakudan ga renshū shimashita.', 'A orquestra ensaiou.', 'Arte e cultura'],
    ['合唱団', 'gasshoudan', 'coral', 'substantivo', '合唱団で歌っています。', 'Gasshōdan de utatte imasu.', 'Ela canta num coral.', 'Arte e cultura'],
    ['劇作家', 'gekisakka', 'dramaturgo', 'substantivo', 'その劇作家は有名です。', 'Sono gekisakka wa yūmei desu.', 'Aquele dramaturgo é famoso.', 'Arte e cultura'],
    ['小説家', 'shousetsuka', 'romancista', 'substantivo', '若い小説家です。', 'Wakai shōsetsuka desu.', 'É uma jovem romancista.', 'Arte e cultura'],
    ['民間伝承', 'minkan denshou', 'folclore', 'substantivo', '地元の民間伝承は豊かです。', 'Jimoto no minkan denshō wa yutaka desu.', 'O folclore local é rico.', 'Arte e cultura'],
    ['文化遺産', 'bunka isan', 'patrimônio cultural', 'substantivo', 'ここは文化遺産です。', 'Koko wa bunka isan desu.', 'Aqui é patrimônio cultural.', 'Arte e cultura'],
    ['帝国', 'teikoku', 'império', 'substantivo', '帝国は崩れました。', 'Teikoku wa kuzuremashita.', 'O império ruiu.', 'História'],
    ['革命', 'kakumei', 'revolução', 'substantivo', '革命がすべてを変えました。', 'Kakumei ga subete o kaemashita.', 'A revolução mudou tudo.', 'História'],
    ['条約', 'jouyaku', 'tratado', 'substantivo', '条約に調印しました。', 'Jōyaku ni chōin shimashita.', 'Assinaram um tratado.', 'História'],
    ['植民地', 'shokuminchi', 'colônia', 'substantivo', 'かつて植民地でした。', 'Katsute shokuminchi deshita.', 'Já foi uma colônia.', 'História'],
    ['王朝', 'ouchou', 'dinastia', 'substantivo', 'その王朝は何世紀も続きました。', 'Sono ōchō wa nanseiki mo tsuzukimashita.', 'A dinastia durou séculos.', 'História'],
    ['反乱', 'hanran', 'rebelião / levante', 'substantivo', '反乱は鎮圧されました。', 'Hanran wa chin’atsu saremashita.', 'A rebelião foi reprimida.', 'História'],
    ['包囲', 'houi', 'cerco', 'substantivo', '包囲は一年続きました。', 'Hōi wa ichinen tsuzukimashita.', 'O cerco durou um ano.', 'História'],
    ['文書館', 'bunshokan', 'arquivo histórico', 'substantivo', '文書館が手紙を保管しています。', 'Bunshokan ga tegami o hokan shite imasu.', 'O arquivo guarda as cartas.', 'História'],
    ['年代記', 'nendaiki', 'crônica histórica', 'substantivo', '年代記に彼の名があります。', 'Nendaiki ni kare no na ga arimasu.', 'A crônica traz o nome dele.', 'História'],
    ['遺物', 'ibutsu', 'artefato antigo', 'substantivo', '遺物が見つかりました。', 'Ibutsu ga mitsukarimashita.', 'Encontraram um artefato.', 'História'],
    ['大陸', 'tairiku', 'continente', 'substantivo', '最も大きな大陸です。', 'Mottomo ōkina tairiku desu.', 'É o maior continente.', 'Geografia'],
    ['半島', 'hantou', 'península', 'substantivo', 'この半島は岩がちです。', 'Kono hantō wa iwagachi desu.', 'Esta península é rochosa.', 'Geografia'],
    ['高原', 'kougen', 'planalto', 'substantivo', '高原は乾燥しています。', 'Kōgen wa kansō shite imasu.', 'O planalto é seco.', 'Geografia'],
    ['氷河', 'hyouga', 'geleira', 'substantivo', '氷河が後退しています。', 'Hyōga ga kōtai shite imasu.', 'A geleira está recuando.', 'Geografia'],
    ['三角州', 'sankakusu', 'delta (de rio)', 'substantivo', '三角州は肥沃です。', 'Sankakusu wa hiyoku desu.', 'O delta é fértil.', 'Geografia'],
    ['谷', 'tani', 'vale', 'substantivo', '谷はよく浸水します。', 'Tani wa yoku shinsui shimasu.', 'O vale alaga com frequência.', 'Geografia'],
    ['砂漠', 'sabaku', 'deserto', 'substantivo', '砂漠が広がっています。', 'Sabaku ga hirogatte imasu.', 'O deserto está avançando.', 'Geografia'],
    ['干満', 'kanman', 'maré (fluxo e refluxo)', 'substantivo', '干満の差が大きいです。', 'Kanman no sa ga ōkii desu.', 'A variação da maré é grande.', 'Geografia'],
    ['緯度', 'ido', 'latitude', 'substantivo', 'まず緯度を確認してください。', 'Mazu ido o kakunin shite kudasai.', 'Confira a latitude primeiro.', 'Geografia'],
    ['地形', 'chikei', 'relevo / terreno', 'substantivo', '地形が険しいです。', 'Chikei ga kewashii desu.', 'O terreno é acidentado.', 'Geografia'],
    ['誠実さ', 'seijitsusa', 'integridade', 'substantivo', '彼の誠実さは疑いません。', 'Kare no seijitsusa wa utagaimasen.', 'Não duvido da integridade dele.', 'Ética'],
    ['美徳', 'bitoku', 'virtude', 'substantivo', '忍耐は美徳です。', 'Nintai wa bitoku desu.', 'A paciência é uma virtude.', 'Ética'],
    ['義務', 'gimu', 'dever', 'substantivo', '報告するのが義務です。', 'Hōkoku suru no ga gimu desu.', 'É um dever relatar.', 'Ética'],
    ['同意', 'doui', 'consentimento', 'substantivo', '同意なしに進めました。', 'Dōi nashi ni susumemashita.', 'Prosseguiram sem consentimento.', 'Ética'],
    ['公平さ', 'kouheisa', 'equidade', 'substantivo', 'ここでは公平さが大事です。', 'Koko de wa kōheisa ga daiji desu.', 'Aqui a equidade importa.', 'Ética'],
    ['危害', 'kigai', 'dano / prejuízo', 'substantivo', '実際に危害が出ました。', 'Jissai ni kigai ga demashita.', 'Houve dano real.', 'Ética'],
    ['尊厳', 'songen', 'dignidade', 'substantivo', '尊厳をもって扱ってください。', 'Songen o motte atsukatte kudasai.', 'Trate com dignidade.', 'Ética'],
    ['責務', 'sekimu', 'obrigação / incumbência', 'substantivo', '私たちには責務があります。', 'Watashitachi ni wa sekimu ga arimasu.', 'Temos uma obrigação.', 'Ética'],
    ['不正行為', 'fusei koui', 'má conduta', 'substantivo', '不正行為で解雇されました。', 'Fusei kōi de kaiko saremashita.', 'Foi demitido por má conduta.', 'Ética'],
    ['内部告発者', 'naibu kokuhatsusha', 'denunciante interno', 'substantivo', '内部告発者は守られました。', 'Naibu kokuhatsusha wa mamoraremashita.', 'O denunciante foi protegido.', 'Ética'],
  ],
  C1: [
    ['官僚制', 'kanryousei', 'burocracia', 'substantivo', '官僚制がすべてを遅らせました。', 'Kanryōsei ga subete o okurasemashita.', 'A burocracia atrasou tudo.', 'Administração pública'],
    ['条例', 'jourei', 'decreto municipal', 'substantivo', '新しい条例が成立しました。', 'Atarashii jōrei ga seiritsu shimashita.', 'Um novo decreto foi aprovado.', 'Administração pública'],
    ['遵守', 'junshu', 'conformidade', 'substantivo', '遵守は義務です。', 'Junshu wa gimu desu.', 'A conformidade é obrigatória.', 'Administração pública'],
    ['監視', 'kanshi', 'fiscalização / vigilância', 'substantivo', '監視が甘かったです。', 'Kanshi ga amakatta desu.', 'A fiscalização era frouxa.', 'Administração pública'],
    ['手順書', 'tejunsho', 'protocolo escrito', 'substantivo', '手順書どおりに進めてください。', 'Tejunsho dōri ni susumete kudasai.', 'Siga o protocolo à risca.', 'Administração pública'],
    ['指令', 'shirei', 'diretriz', 'substantivo', '指令は本日施行されます。', 'Shirei wa honjitsu shikō saremasu.', 'A diretriz entra em vigor hoje.', 'Administração pública'],
    ['定足数', 'teisokusuu', 'quórum', 'substantivo', '定足数に達しませんでした。', 'Teisokusū ni tasshimasen deshita.', 'Não atingimos o quórum.', 'Administração pública'],
    ['終身在職権', 'shuushin zaishokuken', 'estabilidade vitalícia no cargo', 'substantivo', '終身在職権を得ました。', 'Shūshin zaishokuken o emashita.', 'Obteve estabilidade no cargo.', 'Administração pública'],
    ['所管', 'shokan', 'alçada / jurisdição administrativa', 'substantivo', 'それは所管外です。', 'Sore wa shokangai desu.', 'Isso está fora da nossa alçada.', 'Administração pública'],
    ['救済', 'kyuusai', 'reparação / amparo', 'substantivo', '法的救済を求めました。', 'Hōteki kyūsai o motomemashita.', 'Buscaram reparação judicial.', 'Administração pública'],
    ['中央値', 'chuuouchi', 'mediana', 'substantivo', 'ここでは中央値が有効です。', 'Koko de wa chūōchi ga yūkō desu.', 'Aqui a mediana é mais útil.', 'Estatística'],
    ['分散', 'bunsan', 'variância', 'substantivo', '分散が大きすぎます。', 'Bunsan ga ōkisugimasu.', 'A variância é alta demais.', 'Estatística'],
    ['標準偏差', 'hyoujun hensa', 'desvio padrão', 'substantivo', '標準偏差を示してください。', 'Hyōjun hensa o shimeshite kudasai.', 'Informe o desvio padrão.', 'Estatística'],
    ['回帰', 'kaiki', 'regressão', 'substantivo', 'この回帰は説明力が低いです。', 'Kono kaiki wa setsumeiryoku ga hikui desu.', 'Esta regressão explica pouco.', 'Estatística'],
    ['確率', 'kakuritsu', 'probabilidade', 'substantivo', '確率は低いです。', 'Kakuritsu wa hikui desu.', 'A probabilidade é baixa.', 'Estatística'],
    ['分布', 'bunpu', 'distribuição', 'substantivo', '分布が偏っています。', 'Bunpu ga katayotte imasu.', 'A distribuição é assimétrica.', 'Estatística'],
    ['外れ値', 'hazurechi', 'ponto fora da curva', 'substantivo', 'その外れ値を除いてください。', 'Sono hazurechi o nozoite kudasai.', 'Remova esse ponto fora da curva.', 'Estatística'],
    ['有意性', 'yuuisei', 'significância', 'substantivo', '有意性は重要性ではありません。', 'Yūisei wa jūyōsei de wa arimasen.', 'Significância não é importância.', 'Estatística'],
    ['閾値', 'shikiichi', 'limiar', 'substantivo', '閾値を下回りました。', 'Shikiichi o shitamawarimashita.', 'Ficou abaixo do limiar.', 'Estatística'],
    ['推定値', 'suiteichi', 'valor estimado', 'substantivo', 'これは大まかな推定値です。', 'Kore wa ōmaka na suiteichi desu.', 'É uma estimativa aproximada.', 'Estatística'],
    ['統語論', 'tougoron', 'sintaxe (estudo)', 'substantivo', 'ここで統語論が変わります。', 'Koko de tōgoron ga kawarimasu.', 'Aqui a sintaxe muda.', 'Linguística'],
    ['形態素', 'keitaiso', 'morfema', 'substantivo', 'この接頭辞は形態素です。', 'Kono settōji wa keitaiso desu.', 'Este prefixo é um morfema.', 'Linguística'],
    ['音素', 'onso', 'fonema', 'substantivo', '二つの音素が対立します。', 'Futatsu no onso ga tairitsu shimasu.', 'Os dois fonemas contrastam.', 'Linguística'],
    ['意味論', 'imiron', 'semântica', 'substantivo', '争点は意味論です。', 'Sōten wa imiron desu.', 'A disputa é de semântica.', 'Linguística'],
    ['方言', 'hougen', 'dialeto', 'substantivo', '方言は地域で違います。', 'Hōgen wa chiiki de chigaimasu.', 'O dialeto varia por região.', 'Linguística'],
    ['言語使用域', 'gengo shiyouiki', 'registro de fala', 'substantivo', '場面に合う言語使用域を選んでください。', 'Bamen ni au gengo shiyōiki o erande kudasai.', 'Escolha o registro adequado ao contexto.', 'Linguística'],
    ['語源', 'gogen', 'etimologia', 'substantivo', 'この語源には異説があります。', 'Kono gogen ni wa isetsu ga arimasu.', 'Esta etimologia é contestada.', 'Linguística'],
    ['同根語', 'doukongo', 'cognato', 'substantivo', 'この二語は同根語です。', 'Kono nigo wa dōkongo desu.', 'Estas duas palavras são cognatas.', 'Linguística'],
    ['屈折', 'kussetsu', 'flexão', 'substantivo', '屈折が格を示します。', 'Kussetsu ga kaku o shimeshimasu.', 'A flexão marca o caso.', 'Linguística'],
    ['流暢さ', 'ryuuchousa', 'fluência', 'substantivo', '流暢さは正確さではありません。', 'Ryūchōsa wa seikakusa de wa arimasen.', 'Fluência não é correção.', 'Linguística'],
    ['正面', 'shoumen', 'fachada / frente', 'substantivo', '正面が修復されました。', 'Shōmen ga shūfuku saremashita.', 'A fachada foi restaurada.', 'Arquitetura'],
    ['基礎', 'kiso', 'fundação (de obra)', 'substantivo', '基礎にひびが入りました。', 'Kiso ni hibi ga hairimashita.', 'A fundação rachou.', 'Arquitetura'],
    ['設計図', 'sekkeizu', 'planta / projeto', 'substantivo', '設計図をもう一度確認してください。', 'Sekkeizu o mō ichido kakunin shite kudasai.', 'Confira a planta de novo.', 'Arquitetura'],
    ['丸天井', 'marutenjou', 'abóbada', 'substantivo', 'この丸天井は中世のものです。', 'Kono marutenjō wa chūsei no mono desu.', 'Esta abóbada é medieval.', 'Arquitetura'],
    ['足場', 'ashiba', 'andaime', 'substantivo', '今日足場が組まれました。', 'Kyō ashiba ga kumaremashita.', 'O andaime subiu hoje.', 'Arquitetura'],
    ['用途地域', 'youto chiiki', 'zoneamento', 'substantivo', '用途地域の規制で止まりました。', 'Yōto chiiki no kisei de tomarimashita.', 'O zoneamento barrou a obra.', 'Arquitetura'],
    ['改修', 'kaishuu', 'reforma', 'substantivo', '改修に一年かかりました。', 'Kaishū ni ichinen kakarimashita.', 'A reforma levou um ano.', 'Arquitetura'],
    ['耐力壁', 'tairyokuheki', 'parede estrutural', 'substantivo', 'それは耐力壁です。', 'Sore wa tairyokuheki desu.', 'Aquela é uma parede estrutural.', 'Arquitetura'],
    ['都市の膨張', 'toshi no bouchou', 'expansão urbana', 'substantivo', '都市の膨張が続いています。', 'Toshi no bōchō ga tsuzuite imasu.', 'A expansão urbana continua.', 'Arquitetura'],
    ['街並み', 'machinami', 'paisagem urbana', 'substantivo', '街並みがすっかり変わりました。', 'Machinami ga sukkari kawarimashita.', 'A paisagem urbana mudou por completo.', 'Arquitetura'],
  ],
  C2: [
    ['緊張緩和', 'kinchou kanwa', 'distensão (diplomática)', 'substantivo', '緊張緩和は長続きしませんでした。', 'Kinchō kanwa wa nagatsuzuki shimasen deshita.', 'A distensão não durou.', 'Diplomacia'],
    ['関係改善', 'kankei kaizen', 'reaproximação', 'substantivo', '慎重な関係改善が始まりました。', 'Shinchō na kankei kaizen ga hajimarimashita.', 'Começou uma reaproximação cautelosa.', 'Diplomacia'],
    ['公式声明', 'koushiki seimei', 'comunicado oficial', 'substantivo', '公式声明はほとんど語りませんでした。', 'Kōshiki seimei wa hotondo katarimasen deshita.', 'O comunicado oficial dizia pouco.', 'Diplomacia'],
    ['特使', 'tokushi', 'emissário especial', 'substantivo', '特使が派遣されました。', 'Tokushi ga haken saremashita.', 'Um emissário foi enviado.', 'Diplomacia'],
    ['協定', 'kyoutei', 'acordo formal', 'substantivo', '協定は今のところ保たれています。', 'Kyōtei wa ima no tokoro tamotarete imasu.', 'O acordo se mantém por ora.', 'Diplomacia'],
    ['制裁', 'seisai', 'sanção', 'substantivo', '制裁が解除されました。', 'Seisai ga kaijo saremashita.', 'As sanções foram suspensas.', 'Diplomacia'],
    ['中立', 'chuuritsu', 'neutralidade', 'substantivo', '中立を宣言しました。', 'Chūritsu o sengen shimashita.', 'Declararam neutralidade.', 'Diplomacia'],
    ['主権', 'shuken', 'soberania', 'substantivo', '主権が争点になりました。', 'Shuken ga sōten ni narimashita.', 'A soberania virou o impasse.', 'Diplomacia'],
    ['相互主義', 'sougo shugi', 'reciprocidade', 'substantivo', '合意は相互主義に基づきます。', 'Gōi wa sōgo shugi ni motozukimasu.', 'O acordo se baseia na reciprocidade.', 'Diplomacia'],
    ['瀬戸際政策', 'setogiwa seisaku', 'política do abismo', 'substantivo', 'これは瀬戸際政策にすぎません。', 'Kore wa setogiwa seisaku ni sugimasen.', 'Isso não passa de política do abismo.', 'Diplomacia'],
    ['神義論', 'shingiron', 'teodiceia', 'substantivo', '神義論は悪の由来を問います。', 'Shingiron wa aku no yurai o toimasu.', 'A teodiceia questiona a origem do mal.', 'Teologia e mito'],
    ['神格化', 'shinkakuka', 'apoteose / divinização', 'substantivo', 'それは様式の神格化でした。', 'Sore wa yōshiki no shinkakuka deshita.', 'Foi a apoteose do estilo.', 'Teologia e mito'],
    ['終末論', 'shuumatsuron', 'escatologia', 'substantivo', '終末論は最後の事柄を扱います。', 'Shūmatsuron wa saigo no kotogara o atsukaimasu.', 'A escatologia trata das coisas últimas.', 'Teologia e mito'],
    ['典礼', 'tenrei', 'liturgia', 'substantivo', 'この典礼は何世紀も前のものです。', 'Kono tenrei wa nanseiki mo mae no mono desu.', 'Esta liturgia tem séculos.', 'Teologia e mito'],
    ['異端', 'itan', 'heresia', 'substantivo', '異端として断罪されました。', 'Itan to shite danzai saremashita.', 'Foi condenado como heresia.', 'Teologia e mito'],
    ['万神殿', 'banshinden', 'panteão', 'substantivo', '偉人の万神殿に加わりました。', 'Ijin no banshinden ni kuwawarimashita.', 'Entrou no panteão dos grandes.', 'Teologia e mito'],
    ['神託', 'shintaku', 'oráculo', 'substantivo', '神託は謎めいていました。', 'Shintaku wa nazomeite imashita.', 'O oráculo era enigmático.', 'Teologia e mito'],
    ['聖遺物', 'seiibutsu', 'relíquia sagrada', 'substantivo', '聖遺物が巡礼者を集めました。', 'Seiibutsu ga junreisha o atsumemashita.', 'A relíquia atraía peregrinos.', 'Teologia e mito'],
    ['教会分裂', 'kyoukai bunretsu', 'cisma', 'substantivo', '教会分裂が信徒を分けました。', 'Kyōkai bunretsu ga shinto o wakemashita.', 'O cisma dividiu os fiéis.', 'Teologia e mito'],
    ['超越', 'chouetsu', 'transcendência', 'substantivo', 'この詩は超越を目指します。', 'Kono shi wa chōetsu o mezashimasu.', 'Este poema busca a transcendência.', 'Teologia e mito'],
    ['先験的に', 'senkenteki ni', 'a priori', 'advérbio', 'それは先験的には分かりません。', 'Sore wa senkenteki ni wa wakarimasen.', 'Isso não se sabe a priori.', 'Locuções cultas'],
    ['なおさら', 'naosara', 'com mais razão ainda', 'advérbio', 'なおさら第二の例は成り立ちません。', 'Naosara daini no rei wa naritachimasen.', 'Com mais razão ainda, o segundo caso não se sustenta.', 'Locuções cultas'],
    ['必須条件', 'hissu jouken', 'condição indispensável', 'substantivo', '信頼が必須条件です。', 'Shinrai ga hissu jōken desu.', 'A confiança é a condição indispensável.', 'Locuções cultas'],
    ['事実上の', 'jijitsujou no', 'de fato', 'adjetivo', '彼女が事実上の責任者です。', 'Kanojo ga jijitsujō no sekininsha desu.', 'Ela é a responsável de fato.', 'Locuções cultas'],
    ['臨時の', 'rinji no', 'provisório / ad hoc', 'adjetivo', '臨時の委員会でした。', 'Rinji no iinkai deshita.', 'Era um comitê provisório.', 'Locuções cultas'],
    ['準用して', 'jun’you shite', 'aplicando-se com as devidas adaptações', 'advérbio', '同じ規定を準用してください。', 'Onaji kitei o jun’yō shite kudasai.', 'Aplique a mesma norma com as devidas adaptações.', 'Locuções cultas'],
    ['他の条件が同じなら', 'hoka no jouken ga onaji nara', 'mantidas as demais condições', 'advérbio', '他の条件が同じなら需要は落ちます。', 'Hoka no jōken ga onaji nara juyō wa ochimasu.', 'Mantidas as demais condições, a procura cai.', 'Locuções cultas'],
    ['一応の', 'ichiou no', 'preliminar / à primeira vista', 'adjetivo', '一応の根拠はあります。', 'Ichiō no konkyo wa arimasu.', 'Há fundamento à primeira vista.', 'Locuções cultas'],
    ['それ自体としては', 'sore jitai to shite wa', 'em si mesmo considerado', 'advérbio', '規則はそれ自体としては不当ではありません。', 'Kisoku wa sore jitai to shite wa futō de wa arimasen.', 'A regra, em si mesma, não é injusta.', 'Locuções cultas'],
    ['土壇場で', 'dotanba de', 'no último instante', 'advérbio', '合意は土壇場で救われました。', 'Gōi wa dotanba de sukuwaremashita.', 'O acordo foi salvo no último instante.', 'Locuções cultas'],
    ['郷愁', 'kyoushuu', 'saudade da terra / nostalgia', 'substantivo', '郷愁を込めて語りました。', 'Kyōshū o komete katarimashita.', 'Falou com nostalgia.', 'Emoções sutis'],
    ['憂愁', 'yuushuu', 'melancolia', 'substantivo', '静かな憂愁が流れています。', 'Shizuka na yūshū ga nagarete imasu.', 'Corre por ali uma melancolia discreta.', 'Emoções sutis'],
    ['倦怠', 'kentai', 'tédio / lassidão', 'substantivo', '長い午後の倦怠。', 'Nagai gogo no kentai.', 'O tédio das tardes longas.', 'Emoções sutis'],
    ['高揚', 'kouyou', 'exaltação / euforia', 'substantivo', '高揚は長続きしませんでした。', 'Kōyō wa nagatsuzuki shimasen deshita.', 'A euforia durou pouco.', 'Emoções sutis'],
    ['不穏', 'fuon', 'inquietação / tensão latente', 'substantivo', 'その報せは不穏を生みました。', 'Sono shirase wa fuon o umimashita.', 'A notícia gerou inquietação.', 'Emoções sutis'],
    ['憧憬', 'shoukei', 'anseio / aspiração', 'substantivo', '失われたものへの憧憬。', 'Ushinawareta mono e no shōkei.', 'Um anseio pelo que se perdeu.', 'Emoções sutis'],
    ['静謐', 'seihitsu', 'serenidade profunda', 'substantivo', '静謐をもって受け止めました。', 'Seihitsu o motte uketomemashita.', 'Recebeu com serenidade.', 'Emoções sutis'],
    ['義憤', 'gifun', 'indignação justa', 'substantivo', '彼の義憤はもっともでした。', 'Kare no gifun wa mottomo deshita.', 'A indignação dele era justa.', 'Emoções sutis'],
    ['夢想', 'musou', 'devaneio', 'substantivo', '夢想にふけっていました。', 'Musō ni fukette imashita.', 'Estava mergulhado num devaneio.', 'Emoções sutis'],
    ['慰め', 'nagusame', 'consolo', 'substantivo', '音楽に慰めを見いだしました。', 'Ongaku ni nagusame o miidashimashita.', 'Encontrou consolo na música.', 'Emoções sutis'],
  ],
};
