/** Coreano — segundo lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { AsianByLevel } from '../entry';

export const KO_THEMATIC2: AsianByLevel = {
  A1: [
    ['하나', 'hana', 'um (contagem)', 'numeral', '사과 하나 주세요.', 'Sagwa hana juseyo.', 'Uma maçã, por favor.', 'Números e quantidade'],
    ['둘', 'dul', 'dois (contagem)', 'numeral', '둘 샀어요.', 'Dul sasseoyo.', 'Comprei dois.', 'Números e quantidade'],
    ['셋', 'set', 'três (contagem)', 'numeral', '셋 남았어요.', 'Set namasseoyo.', 'Restam três.', 'Números e quantidade'],
    ['많이', 'mani', 'muito', 'advérbio', '사람이 많이 있어요.', 'Sarami mani isseoyo.', 'Há muitas pessoas.', 'Números e quantidade'],
    ['조금', 'jogeum', 'um pouco', 'advérbio', '조금만 먹었어요.', 'Jogeumman meogeosseoyo.', 'Comi só um pouco.', 'Números e quantidade'],
    ['절반', 'jeolban', 'metade', 'substantivo', '절반을 먹었어요.', 'Jeolbaneul meogeosseoyo.', 'Comi metade.', 'Números e quantidade'],
    ['비다', 'bida', 'estar vazio', 'verbo', '병이 비었어요.', 'Byeongi bieosseoyo.', 'A garrafa está vazia.', 'Números e quantidade'],
    ['가득하다', 'gadeukhada', 'estar cheio', 'adjetivo', '잔이 가득해요.', 'Jani gadeukaeyo.', 'O copo está cheio.', 'Números e quantidade'],
    ['무겁다', 'mugeopda', 'ser pesado', 'adjetivo', '이 상자는 무거워요.', 'I sangjaneun mugeowoyo.', 'Esta caixa é pesada.', 'Números e quantidade'],
    ['가볍다', 'gabyeopda', 'ser leve', 'adjetivo', '가방이 가벼워요.', 'Gabangi gabyeowoyo.', 'A bolsa é leve.', 'Números e quantidade'],
    ['일어나다', 'ireonada', 'acordar / levantar', 'verbo', '여섯 시에 일어나요.', 'Yeoseot sie ireonayo.', 'Eu acordo às seis.', 'Ações do dia a dia'],
    ['자다', 'jada', 'dormir', 'verbo', '여덟 시간 자요.', 'Yeodeol sigan jayo.', 'Eu durmo oito horas.', 'Ações do dia a dia'],
    ['씻다', 'ssitda', 'lavar', 'verbo', '손을 씻으세요.', 'Soneul ssiseuseyo.', 'Lave as mãos.', 'Ações do dia a dia'],
    ['요리하다', 'yorihada', 'cozinhar', 'verbo', '그녀는 매일 저녁 요리해요.', 'Geunyeoneun maeil jeonyeok yorihaeyo.', 'Ela cozinha toda noite.', 'Ações do dia a dia'],
    ['청소하다', 'cheongsohada', 'limpar', 'verbo', '집을 청소해요.', 'Jibeul cheongsohaeyo.', 'Eu limpo a casa.', 'Ações do dia a dia'],
    ['사다', 'sada', 'comprar', 'verbo', '여기서 빵을 사요.', 'Yeogiseo ppangeul sayo.', 'Eu compro pão aqui.', 'Ações do dia a dia'],
    ['팔다', 'palda', 'vender', 'verbo', '과일을 팔아요.', 'Gwaireul parayo.', 'Eles vendem frutas.', 'Ações do dia a dia'],
    ['걷다', 'geotda', 'caminhar', 'verbo', '학교까지 걸어요.', 'Hakgyokkaji georeoyo.', 'Eu caminho até a escola.', 'Ações do dia a dia'],
    ['달리다', 'dallida', 'correr', 'verbo', '그는 빨리 달려요.', 'Geuneun ppalli dallyeoyo.', 'Ele corre rápido.', 'Ações do dia a dia'],
    ['기다리다', 'gidarida', 'esperar', 'verbo', '여기서 기다리세요.', 'Yeogiseo gidariseyo.', 'Espere aqui.', 'Ações do dia a dia'],
    ['선생님', 'seonsaengnim', 'professor', 'substantivo', '선생님은 친절해요.', 'Seonsaengnimeun chinjeolhaeyo.', 'O professor é gentil.', 'Escola'],
    ['학생', 'haksaeng', 'aluno', 'substantivo', '그녀는 좋은 학생이에요.', 'Geunyeoneun joeun haksaengieyo.', 'Ela é uma boa aluna.', 'Escola'],
    ['책', 'chaek', 'livro', 'substantivo', '이 책은 길어요.', 'I chaegeun gireoyo.', 'Este livro é longo.', 'Escola'],
    ['펜', 'pen', 'caneta', 'substantivo', '펜이 필요해요.', 'Peni piryohaeyo.', 'Preciso de uma caneta.', 'Escola'],
    ['공책', 'gongchaek', 'caderno', 'substantivo', '공책을 펴세요.', 'Gongchaegeul pyeoseyo.', 'Abra o caderno.', 'Escola'],
    ['수업', 'sueop', 'aula', 'substantivo', '수업이 시작해요.', 'Sueobi sijakaeyo.', 'A aula começa.', 'Escola'],
    ['숙제', 'sukje', 'lição de casa', 'substantivo', '숙제를 다 했어요.', 'Sukjereul da haesseoyo.', 'Terminei a lição de casa.', 'Escola'],
    ['시험', 'siheom', 'prova', 'substantivo', '시험이 어려웠어요.', 'Siheomi eoryeowosseoyo.', 'A prova foi difícil.', 'Escola'],
    ['교실', 'gyosil', 'sala de aula', 'substantivo', '교실이 넓어요.', 'Gyosiri neolbeoyo.', 'A sala de aula é grande.', 'Escola'],
    ['질문', 'jilmun', 'pergunta', 'substantivo', '질문이 있어요.', 'Jilmuni isseoyo.', 'Tenho uma pergunta.', 'Escola'],
    ['새', 'sae', 'pássaro', 'substantivo', '새가 노래해요.', 'Saega noraehaeyo.', 'Um pássaro canta.', 'Animais'],
    ['물고기', 'mulgogi', 'peixe', 'substantivo', '물고기가 작아요.', 'Mulgogiga jagayo.', 'O peixe é pequeno.', 'Animais'],
    ['말', 'mal', 'cavalo', 'substantivo', '말이 빨라요.', 'Mari ppallayo.', 'O cavalo é rápido.', 'Animais'],
    ['소', 'so', 'vaca / boi', 'substantivo', '소가 풀을 먹어요.', 'Soga pureul meogeoyo.', 'A vaca come grama.', 'Animais'],
    ['닭', 'dak', 'galinha', 'substantivo', '닭이 세 마리 있어요.', 'Dalgi se mari isseoyo.', 'Temos três galinhas.', 'Animais'],
    ['쥐', 'jwi', 'rato', 'substantivo', '여기 쥐가 있어요.', 'Yeogi jwiga isseoyo.', 'Tem um rato aqui.', 'Animais'],
    ['곤충', 'gonchung', 'inseto', 'substantivo', '곤충이 들어왔어요.', 'Gonchungi deureowasseoyo.', 'Entrou um inseto.', 'Animais'],
    ['양', 'yang', 'ovelha', 'substantivo', '양은 하얘요.', 'Yangeun hayaeyo.', 'As ovelhas são brancas.', 'Animais'],
    ['돼지', 'dwaeji', 'porco', 'substantivo', '돼지가 더러워요.', 'Dwaejiga deoreowoyo.', 'O porco está sujo.', 'Animais'],
    ['토끼', 'tokki', 'coelho', 'substantivo', '토끼가 빨라요.', 'Tokkiga ppallayo.', 'O coelho é rápido.', 'Animais'],
  ],
  A2: [
    ['버스', 'beoseu', 'ônibus', 'substantivo', '버스가 늦었어요.', 'Beoseuga neujeosseoyo.', 'O ônibus está atrasado.', 'Transporte'],
    ['기차', 'gicha', 'trem', 'substantivo', '기차가 여덟 시에 떠나요.', 'Gichaga yeodeol sie tteonayo.', 'O trem sai às oito.', 'Transporte'],
    ['자동차', 'jadongcha', 'carro', 'substantivo', '제 자동차는 낡았어요.', 'Je jadongchaneun nalgasseoyo.', 'Meu carro é velho.', 'Transporte'],
    ['자전거', 'jajeongeo', 'bicicleta', 'substantivo', '자전거를 타요.', 'Jajeongeoreul tayo.', 'Eu ando de bicicleta.', 'Transporte'],
    ['택시', 'taeksi', 'táxi', 'substantivo', '택시를 탑시다.', 'Taeksireul tapsida.', 'Vamos pegar um táxi.', 'Transporte'],
    ['운전사', 'unjeonsa', 'motorista', 'substantivo', '운전사가 친절했어요.', 'Unjeonsaga chinjeolhaesseoyo.', 'O motorista foi gentil.', 'Transporte'],
    ['요금', 'yogeum', 'tarifa', 'substantivo', '요금이 올랐어요.', 'Yogeumi ollasseoyo.', 'A tarifa subiu.', 'Transporte'],
    ['승강장', 'seunggangjang', 'plataforma', 'substantivo', '이 번 승강장에서 기다리세요.', 'I beon seunggangjangeseo gidariseyo.', 'Espere na plataforma dois.', 'Transporte'],
    ['좌석', 'jwaseok', 'assento', 'substantivo', '이 좌석은 비었어요.', 'I jwaseogeun bieosseoyo.', 'Este assento está livre.', 'Transporte'],
    ['이동', 'idong', 'deslocamento', 'substantivo', '이동에 두 시간 걸려요.', 'Idonge du sigan geollyeoyo.', 'O deslocamento leva duas horas.', 'Transporte'],
    ['취미', 'chwimi', 'passatempo', 'substantivo', '독서가 제 취미예요.', 'Dokseoga je chwimiyeyo.', 'Ler é meu passatempo.', 'Lazer'],
    ['박물관', 'bangmulgwan', 'museu', 'substantivo', '오늘 박물관은 무료예요.', 'Oneul bangmulgwaneun muryoyeyo.', 'Hoje o museu é de graça.', 'Lazer'],
    ['영화관', 'yeonghwagwan', 'cinema', 'substantivo', '영화관에 갔어요.', 'Yeonghwagwane gasseoyo.', 'Fomos ao cinema.', 'Lazer'],
    ['공연', 'gongyeon', 'espetáculo / show', 'substantivo', '공연이 훌륭했어요.', 'Gongyeoni hullyunghaesseoyo.', 'O espetáculo foi ótimo.', 'Lazer'],
    ['공원', 'gongwon', 'parque', 'substantivo', '공원이 가까워요.', 'Gongwoni gakkawoyo.', 'O parque fica perto.', 'Lazer'],
    ['놀이', 'nori', 'brincadeira / jogo', 'substantivo', '이 놀이는 재미있어요.', 'I norineun jaemiisseoyo.', 'Esta brincadeira é divertida.', 'Lazer'],
    ['카메라', 'kamera', 'câmera', 'substantivo', '카메라를 가져오세요.', 'Kamerareul gajyeooseyo.', 'Traga sua câmera.', 'Lazer'],
    ['소풍', 'sopung', 'piquenique / passeio', 'substantivo', '소풍을 갔어요.', 'Sopungeul gasseoyo.', 'Fomos a um piquenique.', 'Lazer'],
    ['수영하다', 'suyeonghada', 'nadar', 'verbo', '일요일에 수영해요.', 'Iryoire suyeonghaeyo.', 'Eu nado aos domingos.', 'Lazer'],
    ['춤추다', 'chumchuda', 'dançar', 'verbo', '그들은 아주 잘 춤춰요.', 'Geudeureun aju jal chumchwoyo.', 'Eles dançam muito bem.', 'Lazer'],
    ['기쁘다', 'gippeuda', 'estar contente', 'adjetivo', '그녀는 기뻐 보여요.', 'Geunyeoneun gippeo boyeoyo.', 'Ela parece contente.', 'Emoções'],
    ['슬프다', 'seulpeuda', 'estar triste', 'adjetivo', '어제는 슬펐어요.', 'Eojeneun seulpeosseoyo.', 'Ontem eu estava triste.', 'Emoções'],
    ['화나다', 'hwanada', 'ficar bravo', 'verbo', '화내지 마세요.', 'Hwanaeji maseyo.', 'Não fique bravo.', 'Emoções'],
    ['무섭다', 'museopda', 'ter medo / ser assustador', 'adjetivo', '개가 무서워요.', 'Gaega museowoyo.', 'Tenho medo de cachorro.', 'Emoções'],
    ['놀라다', 'nollada', 'surpreender-se', 'verbo', '우리는 놀랐어요.', 'Urineun nollasseoyo.', 'Ficamos surpresos.', 'Emoções'],
    ['지루하다', 'jiruhada', 'ser entediante', 'adjetivo', '아이들이 지루해해요.', 'Aideuri jiruhaehaeyo.', 'As crianças estão entediadas.', 'Emoções'],
    ['걱정하다', 'geokjeonghada', 'preocupar-se', 'verbo', '그녀는 그걸 걱정해요.', 'Geunyeoneun geugeol geokjeonghaeyo.', 'Ela se preocupa com isso.', 'Emoções'],
    ['자랑스럽다', 'jarangseureopda', 'sentir orgulho', 'adjetivo', '네가 자랑스러워요.', 'Nega jarangseureowoyo.', 'Estou orgulhoso de você.', 'Emoções'],
    ['침착하다', 'chimchakhada', 'ser calmo', 'adjetivo', '침착하려고 하세요.', 'Chimchakaryeogo haseyo.', 'Tente ficar calmo.', 'Emoções'],
    ['외롭다', 'oeropda', 'sentir-se só', 'adjetivo', '그는 외로워해요.', 'Geuneun oerowohaeyo.', 'Ele se sente sozinho.', 'Emoções'],
    ['젊다', 'jeomda', 'ser jovem', 'adjetivo', '그녀는 아주 젊어요.', 'Geunyeoneun aju jeolmeoyo.', 'Ela é muito jovem.', 'Descrever pessoas'],
    ['늙다', 'neukda', 'envelhecer', 'verbo', '할아버지는 늙으셨어요.', 'Harabeojineun neulgeusyeosseoyo.', 'Meu avô está velho.', 'Descrever pessoas'],
    ['다정하다', 'dajeonghada', 'ser afetuoso', 'adjetivo', '그는 다정한 사람이에요.', 'Geuneun dajeonghan saramieyo.', 'Ele é uma pessoa afetuosa.', 'Descrever pessoas'],
    ['웃기다', 'utgida', 'ser engraçado', 'adjetivo', '네 친구는 웃겨요.', 'Ne chinguneun utgyeoyo.', 'Seu amigo é engraçado.', 'Descrever pessoas'],
    ['조용하다', 'joyonghada', 'ser quieto', 'adjetivo', '그녀는 아주 조용해요.', 'Geunyeoneun aju joyonghaeyo.', 'Ela é muito quieta.', 'Descrever pessoas'],
    ['똑똑하다', 'ttokttokhada', 'ser inteligente', 'adjetivo', '똑똑한 생각이었어요.', 'Ttokttokan saenggagieosseoyo.', 'Foi uma ideia inteligente.', 'Descrever pessoas'],
    ['게으르다', 'geeureuda', 'ser preguiçoso', 'adjetivo', '게으르지 마세요.', 'Geeureuji maseyo.', 'Não seja preguiçoso.', 'Descrever pessoas'],
    ['정직하다', 'jeongjikhada', 'ser honesto', 'adjetivo', '그녀는 늘 정직해요.', 'Geunyeoneun neul jeongjikaeyo.', 'Ela é sempre honesta.', 'Descrever pessoas'],
    ['상냥하다', 'sangnyanghada', 'ser cordial', 'adjetivo', '직원들이 상냥해요.', 'Jigwondeuri sangnyanghaeyo.', 'Os funcionários são cordiais.', 'Descrever pessoas'],
    ['힘세다', 'himseda', 'ser forte', 'adjetivo', '그는 아주 힘세요.', 'Geuneun aju himseyo.', 'Ele é muito forte.', 'Descrever pessoas'],
  ],
  B1: [
    ['식습관', 'siksseupgwan', 'hábitos alimentares', 'substantivo', '식습관이 많이 바뀌었어요.', 'Siksseupgwani mani bakkwieosseoyo.', 'Os hábitos alimentares mudaram muito.', 'Saúde e bem-estar'],
    ['운동', 'undong', 'exercício físico', 'substantivo', '운동은 잠에 도움이 돼요.', 'Undongeun jame doumi dwaeyo.', 'O exercício ajuda no sono.', 'Saúde e bem-estar'],
    ['스트레스', 'seuteureseu', 'estresse', 'substantivo', '스트레스는 몸에 영향을 줘요.', 'Seuteureseuneun mome yeonghyangeul jwoyo.', 'O estresse afeta o corpo.', 'Saúde e bem-estar'],
    ['습관', 'seupgwan', 'hábito', 'substantivo', '그게 습관이 됐어요.', 'Geuge seupgwani dwaesseoyo.', 'Isso virou um hábito.', 'Saúde e bem-estar'],
    ['치료', 'chiryo', 'tratamento', 'substantivo', '치료가 큰 도움이 됐어요.', 'Chiryoga keun doumi dwaesseoyo.', 'O tratamento ajudou muito.', 'Saúde e bem-estar'],
    ['회복', 'hoebok', 'recuperação', 'substantivo', '회복에는 시간이 걸려요.', 'Hoebogeneun sigani geollyeoyo.', 'A recuperação leva tempo.', 'Saúde e bem-estar'],
    ['자세', 'jase', 'postura', 'substantivo', '자세를 바로잡으세요.', 'Jasereul barojabeuseyo.', 'Corrija sua postura.', 'Saúde e bem-estar'],
    ['호흡', 'hoheup', 'respiração', 'substantivo', '느린 호흡이 진정시켜요.', 'Neurin hoheubi jinjeongsikyeoyo.', 'A respiração lenta acalma.', 'Saúde e bem-estar'],
    ['건강검진', 'geongangeomjin', 'check-up médico', 'substantivo', '오늘 건강검진을 받았어요.', 'Oneul geongangeomjineul badasseoyo.', 'Fiz um check-up hoje.', 'Saúde e bem-estar'],
    ['안녕과 행복', 'annyeonggwa haengbok', 'bem-estar', 'substantivo', '안녕과 행복을 중시해요.', 'Annyeonggwa haengbogeul jungsihaeyo.', 'Valorizam o bem-estar.', 'Saúde e bem-estar'],
    ['월세', 'wolse', 'aluguel mensal', 'substantivo', '월세가 또 올랐어요.', 'Wolsega tto ollasseoyo.', 'O aluguel subiu de novo.', 'Moradia'],
    ['임대차 계약', 'imdaecha gyeyak', 'contrato de locação', 'substantivo', '임대차 계약이 유월에 끝나요.', 'Imdaecha gyeyagi yuwore kkeutnayo.', 'O contrato acaba em junho.', 'Moradia'],
    ['보증금', 'bojeunggeum', 'caução', 'substantivo', '보증금을 돌려받지 못했어요.', 'Bojeunggeumeul dollyebatji motaesseoyo.', 'Não recebi a caução de volta.', 'Moradia'],
    ['세입자', 'seipja', 'inquilino', 'substantivo', '세입자가 항의했어요.', 'Seipjaga hanguihaesseoyo.', 'O inquilino reclamou.', 'Moradia'],
    ['천장', 'cheonjang', 'teto', 'substantivo', '천장에서 물이 새요.', 'Cheonjangeseo muri saeyo.', 'O teto está vazando.', 'Moradia'],
    ['지붕', 'jibung', 'telhado', 'substantivo', '지붕을 고쳐야 해요.', 'Jibungeul gochyeoya haeyo.', 'O telhado precisa de conserto.', 'Moradia'],
    ['지하실', 'jihasil', 'porão', 'substantivo', '지하실이 습해요.', 'Jihasiri seuphaeyo.', 'O porão está úmido.', 'Moradia'],
    ['발코니', 'balkoni', 'varanda', 'substantivo', '발코니에서 밥을 먹어요.', 'Balkonieseo babeul meogeoyo.', 'Comemos na varanda.', 'Moradia'],
    ['배관', 'baegwan', 'encanamento', 'substantivo', '배관이 오래됐어요.', 'Baegwani oraedwaesseoyo.', 'O encanamento é velho.', 'Moradia'],
    ['임대인', 'imdaein', 'locador / proprietário', 'substantivo', '임대인이 전화했어요.', 'Imdaeini jeonhwahaesseoyo.', 'O proprietário ligou.', 'Moradia'],
    ['조리법', 'joribeop', 'receita culinária', 'substantivo', '조리법을 보내 주세요.', 'Joribeobeul bonae juseyo.', 'Me manda a receita.', 'Culinária'],
    ['재료', 'jaeryo', 'ingrediente', 'substantivo', '재료 하나가 없어요.', 'Jaeryo hanaga eopseoyo.', 'Falta um ingrediente.', 'Culinária'],
    ['끓이다', 'kkeurida', 'ferver', 'verbo', '먼저 물을 끓이세요.', 'Meonjeo mureul kkeuriseyo.', 'Ferva a água primeiro.', 'Culinária'],
    ['튀기다', 'twigida', 'fritar', 'verbo', '양파를 천천히 튀기세요.', 'Yangpareul cheoncheonhi twigiseyo.', 'Frite a cebola devagar.', 'Culinária'],
    ['굽다', 'gupda', 'assar / grelhar', 'verbo', '한 시간 구우세요.', 'Han sigan guuseyo.', 'Asse por uma hora.', 'Culinária'],
    ['다지다', 'dajida', 'picar bem fino', 'verbo', '마늘을 곱게 다지세요.', 'Maneureul gopge dajiseyo.', 'Pique o alho bem fino.', 'Culinária'],
    ['양념하다', 'yangnyeomhada', 'temperar', 'verbo', '후추로 양념하세요.', 'Huchuro yangnyeomhaseyo.', 'Tempere com pimenta.', 'Culinária'],
    ['반죽', 'banjuk', 'massa (crua)', 'substantivo', '반죽을 쉬게 하세요.', 'Banjugeul swige haseyo.', 'Deixe a massa descansar.', 'Culinária'],
    ['조리다', 'jorida', 'cozinhar reduzindo o caldo', 'verbo', '고기를 천천히 조려요.', 'Gogireul cheoncheonhi joryeoyo.', 'Cozinho a carne devagar.', 'Culinária'],
    ['찌다', 'jjida', 'cozinhar no vapor', 'verbo', '채소를 찌세요.', 'Chaesoreul jjiseyo.', 'Cozinhe os legumes no vapor.', 'Culinária'],
    ['메시지', 'mesiji', 'mensagem', 'substantivo', '메시지를 받았어요.', 'Mesijireul badasseoyo.', 'Recebi a mensagem.', 'Comunicação'],
    ['답장', 'dapjang', 'resposta (a mensagem)', 'substantivo', '답장을 기다려요.', 'Dapjangeul gidaryeoyo.', 'Estou esperando resposta.', 'Comunicação'],
    ['안내문', 'annaemun', 'aviso escrito', 'substantivo', '문에 안내문이 있어요.', 'Mune annaemuni isseoyo.', 'Há um aviso na porta.', 'Comunicação'],
    ['발표', 'balpyo', 'anúncio / apresentação', 'substantivo', '발표가 있었어요.', 'Balpyoga isseosseoyo.', 'Houve um anúncio.', 'Comunicação'],
    ['소문', 'somun', 'boato', 'substantivo', '그냥 소문이에요.', 'Geunyang somunieyo.', 'É só um boato.', 'Comunicação'],
    ['성명', 'seongmyeong', 'declaração pública', 'substantivo', '성명을 냈어요.', 'Seongmyeongeul naesseoyo.', 'Divulgou uma declaração.', 'Comunicação'],
    ['설명하다', 'seolmyeonghada', 'explicar', 'verbo', '다시 설명해 주세요.', 'Dasi seolmyeonghae juseyo.', 'Explique de novo.', 'Comunicação'],
    ['묘사하다', 'myosahada', 'descrever', 'verbo', '본 것을 묘사하세요.', 'Bon geoseul myosahaseyo.', 'Descreva o que você viu.', 'Comunicação'],
    ['요약하다', 'yoyakhada', 'resumir', 'verbo', '한 줄로 요약하세요.', 'Han jullo yoyakaseyo.', 'Resuma em uma linha.', 'Comunicação'],
    ['오해', 'ohae', 'mal-entendido', 'substantivo', '그건 오해였어요.', 'Geugeon ohaeyeosseoyo.', 'Foi um mal-entendido.', 'Comunicação'],
  ],
  B2: [
    ['조각', 'jogak', 'escultura', 'substantivo', '이 조각은 청동이에요.', 'I jogageun cheongdongieyo.', 'Esta escultura é de bronze.', 'Arte e cultura'],
    ['전시회', 'jeonsihoe', 'exposição', 'substantivo', '전시회가 금요일에 열려요.', 'Jeonsihoega geumyoire yeollyeoyo.', 'A exposição abre sexta.', 'Arte e cultura'],
    ['초상화', 'chosanghwa', 'retrato', 'substantivo', '초상화를 그렸어요.', 'Chosanghwareul geuryeosseoyo.', 'Pintou um retrato.', 'Arte e cultura'],
    ['캔버스', 'kaenbeoseu', 'tela (de pintura)', 'substantivo', '캔버스가 비어 있었어요.', 'Kaenbeoseuga bieo isseosseoyo.', 'A tela estava em branco.', 'Arte e cultura'],
    ['관현악단', 'gwanhyeonakdan', 'orquestra', 'substantivo', '관현악단이 연습했어요.', 'Gwanhyeonakdani yeonseupaesseoyo.', 'A orquestra ensaiou.', 'Arte e cultura'],
    ['합창단', 'hapchangdan', 'coral', 'substantivo', '합창단에서 노래해요.', 'Hapchangdaneseo noraehaeyo.', 'Ela canta num coral.', 'Arte e cultura'],
    ['극작가', 'geukjakga', 'dramaturgo', 'substantivo', '그 극작가는 유명해요.', 'Geu geukjakganeun yumyeonghaeyo.', 'Aquele dramaturgo é famoso.', 'Arte e cultura'],
    ['소설가', 'soseolga', 'romancista', 'substantivo', '젊은 소설가예요.', 'Jeolmeun soseolgayeyo.', 'É uma jovem romancista.', 'Arte e cultura'],
    ['민속', 'minsok', 'folclore', 'substantivo', '지역 민속이 풍부해요.', 'Jiyeok minsogi pungbuhaeyo.', 'O folclore local é rico.', 'Arte e cultura'],
    ['문화유산', 'munhwayusan', 'patrimônio cultural', 'substantivo', '여기는 문화유산이에요.', 'Yeogineun munhwayusanieyo.', 'Aqui é patrimônio cultural.', 'Arte e cultura'],
    ['제국', 'jeguk', 'império', 'substantivo', '제국이 무너졌어요.', 'Jegugi muneojyeosseoyo.', 'O império ruiu.', 'História'],
    ['혁명', 'hyeongmyeong', 'revolução', 'substantivo', '혁명이 모든 걸 바꿨어요.', 'Hyeongmyeongi modeun geol bakkwosseoyo.', 'A revolução mudou tudo.', 'História'],
    ['조약', 'joyak', 'tratado', 'substantivo', '조약에 서명했어요.', 'Joyage seomyeonghaesseoyo.', 'Assinaram um tratado.', 'História'],
    ['식민지', 'singminji', 'colônia', 'substantivo', '한때 식민지였어요.', 'Hanttae singminjiyeosseoyo.', 'Já foi uma colônia.', 'História'],
    ['왕조', 'wangjo', 'dinastia', 'substantivo', '그 왕조는 몇 세기 이어졌어요.', 'Geu wangjoneun myeot segi ieojyeosseoyo.', 'A dinastia durou séculos.', 'História'],
    ['봉기', 'bonggi', 'levante', 'substantivo', '봉기가 진압됐어요.', 'Bonggiga jinapdwaesseoyo.', 'O levante foi reprimido.', 'História'],
    ['포위', 'powi', 'cerco', 'substantivo', '포위가 일 년 이어졌어요.', 'Powiga il nyeon ieojyeosseoyo.', 'O cerco durou um ano.', 'História'],
    ['기록보관소', 'girokbogwanso', 'arquivo histórico', 'substantivo', '기록보관소가 편지를 보관해요.', 'Girokbogwansoga pyeonjireul bogwanhaeyo.', 'O arquivo guarda as cartas.', 'História'],
    ['연대기', 'yeondaegi', 'crônica histórica', 'substantivo', '연대기에 그의 이름이 있어요.', 'Yeondaegie geuui ireumi isseoyo.', 'A crônica traz o nome dele.', 'História'],
    ['유물', 'yumul', 'artefato antigo', 'substantivo', '유물을 발견했어요.', 'Yumureul balgyeonhaesseoyo.', 'Encontraram um artefato.', 'História'],
    ['대륙', 'daeryuk', 'continente', 'substantivo', '가장 큰 대륙이에요.', 'Gajang keun daeryugieyo.', 'É o maior continente.', 'Geografia'],
    ['반도', 'bando', 'península', 'substantivo', '이 반도는 바위가 많아요.', 'I bandoneun bawiga manayo.', 'Esta península é rochosa.', 'Geografia'],
    ['고원', 'gowon', 'planalto', 'substantivo', '고원은 건조해요.', 'Gowoneun geonjohaeyo.', 'O planalto é seco.', 'Geografia'],
    ['빙하', 'bingha', 'geleira', 'substantivo', '빙하가 물러나고 있어요.', 'Binghaga mulleonago isseoyo.', 'A geleira está recuando.', 'Geografia'],
    ['삼각주', 'samgakju', 'delta (de rio)', 'substantivo', '삼각주는 비옥해요.', 'Samgakjuneun biokhaeyo.', 'O delta é fértil.', 'Geografia'],
    ['계곡', 'gyegok', 'vale', 'substantivo', '계곡이 자주 잠겨요.', 'Gyegogi jaju jamgyeoyo.', 'O vale alaga com frequência.', 'Geografia'],
    ['사막', 'samak', 'deserto', 'substantivo', '사막이 넓어지고 있어요.', 'Samagi neolbeojigo isseoyo.', 'O deserto está avançando.', 'Geografia'],
    ['조수', 'josu', 'maré', 'substantivo', '조수가 밀려와요.', 'Josuga millyeowayo.', 'A maré está subindo.', 'Geografia'],
    ['위도', 'wido', 'latitude', 'substantivo', '위도를 먼저 확인하세요.', 'Widoreul meonjeo hwaginhaseyo.', 'Confira a latitude primeiro.', 'Geografia'],
    ['지형', 'jihyeong', 'relevo / terreno', 'substantivo', '지형이 험해요.', 'Jihyeongi heomhaeyo.', 'O terreno é acidentado.', 'Geografia'],
    ['성실성', 'seongsilseong', 'integridade', 'substantivo', '그의 성실성은 의심할 바 없어요.', 'Geuui seongsilseongeun uisimhal ba eopseoyo.', 'A integridade dele é inquestionável.', 'Ética'],
    ['미덕', 'mideok', 'virtude', 'substantivo', '인내는 미덕이에요.', 'Innaeneun mideogieyo.', 'A paciência é uma virtude.', 'Ética'],
    ['의무', 'uimu', 'dever', 'substantivo', '신고하는 게 의무예요.', 'Singohaneun ge uimuyeyo.', 'É um dever relatar.', 'Ética'],
    ['동의', 'dongui', 'consentimento', 'substantivo', '동의 없이 진행했어요.', 'Dongui eopsi jinhaenghaesseoyo.', 'Prosseguiram sem consentimento.', 'Ética'],
    ['공정성', 'gongjeongseong', 'equidade', 'substantivo', '여기선 공정성이 중요해요.', 'Yeogiseon gongjeongseongi jungyohaeyo.', 'Aqui a equidade importa.', 'Ética'],
    ['피해', 'pihae', 'dano', 'substantivo', '실제 피해가 생겼어요.', 'Silje pihaega saenggyeosseoyo.', 'Houve dano real.', 'Ética'],
    ['존엄', 'joneom', 'dignidade', 'substantivo', '존엄을 지켜 대하세요.', 'Joneomeul jikyeo daehaseyo.', 'Trate com dignidade.', 'Ética'],
    ['책무', 'chaengmu', 'obrigação / incumbência', 'substantivo', '우리에게 책무가 있어요.', 'Uriege chaengmuga isseoyo.', 'Temos uma obrigação.', 'Ética'],
    ['부정행위', 'bujeonghaengwi', 'má conduta', 'substantivo', '부정행위로 해고됐어요.', 'Bujeonghaengwiro haegodwaesseoyo.', 'Foi demitido por má conduta.', 'Ética'],
    ['내부고발자', 'naebugobalja', 'denunciante interno', 'substantivo', '내부고발자를 보호했어요.', 'Naebugobaljareul bohohaesseoyo.', 'O denunciante foi protegido.', 'Ética'],
  ],
  C1: [
    ['관료제', 'gwallyoje', 'burocracia', 'substantivo', '관료제가 모든 걸 늦췄어요.', 'Gwallyojega modeun geol neutchwosseoyo.', 'A burocracia atrasou tudo.', 'Administração pública'],
    ['조례', 'jorye', 'decreto municipal', 'substantivo', '새 조례가 통과됐어요.', 'Sae joryega tonggwadwaesseoyo.', 'Um novo decreto foi aprovado.', 'Administração pública'],
    ['준수', 'junsu', 'conformidade', 'substantivo', '준수는 의무예요.', 'Junsuneun uimuyeyo.', 'A conformidade é obrigatória.', 'Administração pública'],
    ['감독 기능', 'gamdok gineung', 'função de fiscalização', 'substantivo', '감독 기능이 약했어요.', 'Gamdok gineungi yakaesseoyo.', 'A fiscalização era fraca.', 'Administração pública'],
    ['절차서', 'jeolchaseo', 'protocolo escrito', 'substantivo', '절차서를 그대로 따르세요.', 'Jeolchaseoreul geudaero ttareuseyo.', 'Siga o protocolo à risca.', 'Administração pública'],
    ['지침', 'jichim', 'diretriz', 'substantivo', '지침이 오늘부터 시행돼요.', 'Jichimi oneulbuteo sihaengdwaeyo.', 'A diretriz vale a partir de hoje.', 'Administração pública'],
    ['의결정족수', 'uigyeoljeongjoksu', 'quórum', 'substantivo', '의결정족수를 못 채웠어요.', 'Uigyeoljeongjoksureul mot chaewosseoyo.', 'Não atingimos o quórum.', 'Administração pública'],
    ['정년보장', 'jeongnyeonbojang', 'estabilidade no cargo', 'substantivo', '정년보장을 받았어요.', 'Jeongnyeonbojangeul badasseoyo.', 'Obteve estabilidade no cargo.', 'Administração pública'],
    ['소관', 'sogwan', 'alçada / competência', 'substantivo', '그건 우리 소관이 아니에요.', 'Geugeon uri sogwani anieyo.', 'Isso não é da nossa alçada.', 'Administração pública'],
    ['구제', 'guje', 'reparação / amparo', 'substantivo', '법적 구제를 구했어요.', 'Beopjeok gujereul guhaesseoyo.', 'Buscaram reparação judicial.', 'Administração pública'],
    ['중앙값', 'junganggap', 'mediana', 'substantivo', '여기선 중앙값이 더 유용해요.', 'Yeogiseon jungganggabi deo yuyonghaeyo.', 'Aqui a mediana é mais útil.', 'Estatística'],
    ['분산도', 'bunsando', 'variância', 'substantivo', '분산도가 너무 커요.', 'Bunsandoga neomu keoyo.', 'A variância é grande demais.', 'Estatística'],
    ['표준편차', 'pyojunpyeoncha', 'desvio padrão', 'substantivo', '표준편차를 밝히세요.', 'Pyojunpyeonchareul balkiseyo.', 'Informe o desvio padrão.', 'Estatística'],
    ['회귀', 'hoegwi', 'regressão', 'substantivo', '이 회귀는 설명력이 낮아요.', 'I hoegwineun seolmyeongnyeogi najayo.', 'Esta regressão explica pouco.', 'Estatística'],
    ['확률', 'hwangnyul', 'probabilidade', 'substantivo', '확률이 낮아요.', 'Hwangnyuri najayo.', 'A probabilidade é baixa.', 'Estatística'],
    ['분포', 'bunpo', 'distribuição', 'substantivo', '분포가 치우쳐 있어요.', 'Bunpoga chiuchyeo isseoyo.', 'A distribuição é assimétrica.', 'Estatística'],
    ['이상치', 'isangchi', 'ponto fora da curva', 'substantivo', '그 이상치를 빼세요.', 'Geu isangchireul ppaeseyo.', 'Remova esse ponto fora da curva.', 'Estatística'],
    ['유의성', 'yuuiseong', 'significância', 'substantivo', '유의성은 중요성이 아니에요.', 'Yuuiseongeun jungyoseongi anieyo.', 'Significância não é importância.', 'Estatística'],
    ['임계값', 'imgyegap', 'limiar', 'substantivo', '임계값 아래로 떨어졌어요.', 'Imgyegap araero tteoreojyeosseoyo.', 'Ficou abaixo do limiar.', 'Estatística'],
    ['추정치', 'chujeongchi', 'valor estimado', 'substantivo', '대략적인 추정치예요.', 'Daeryakjeogin chujeongchiyeyo.', 'É uma estimativa aproximada.', 'Estatística'],
    ['통사론', 'tongsaron', 'sintaxe (estudo)', 'substantivo', '여기서 통사론이 달라져요.', 'Yeogiseo tongsaroni dallajyeoyo.', 'Aqui a sintaxe muda.', 'Linguística'],
    ['형태소', 'hyeongtaeso', 'morfema', 'substantivo', '이 접두사는 형태소예요.', 'I jeopdusaneun hyeongtaesoyeyo.', 'Este prefixo é um morfema.', 'Linguística'],
    ['음소', 'eumso', 'fonema', 'substantivo', '두 음소가 대립해요.', 'Du eumsoga daeriphaeyo.', 'Os dois fonemas contrastam.', 'Linguística'],
    ['의미론', 'uimiron', 'semântica', 'substantivo', '쟁점은 의미론이에요.', 'Jaengjeomeun uimironieyo.', 'A disputa é de semântica.', 'Linguística'],
    ['방언', 'bangeon', 'dialeto', 'substantivo', '방언은 지역마다 달라요.', 'Bangeoneun jiyeongmada dallayo.', 'O dialeto varia por região.', 'Linguística'],
    ['말투 수준', 'maltu sujun', 'registro de fala', 'substantivo', '상황에 맞는 말투 수준을 고르세요.', 'Sanghwange manneun maltu sujuneul goreuseyo.', 'Escolha o registro adequado ao contexto.', 'Linguística'],
    ['어원', 'eowon', 'etimologia', 'substantivo', '이 어원은 논쟁 중이에요.', 'I eowoneun nonjaeng jungieyo.', 'Esta etimologia é contestada.', 'Linguística'],
    ['동계어', 'donggyeeo', 'cognato', 'substantivo', '이 두 단어는 동계어예요.', 'I du daneoneun donggyeeoyeyo.', 'Estas duas palavras são cognatas.', 'Linguística'],
    ['굴절', 'guljeol', 'flexão', 'substantivo', '굴절이 격을 표시해요.', 'Guljeori gyeogeul pyosihaeyo.', 'A flexão marca o caso.', 'Linguística'],
    ['유창성', 'yuchangseong', 'fluência', 'substantivo', '유창성은 정확성이 아니에요.', 'Yuchangseongeun jeonghwakseongi anieyo.', 'Fluência não é correção.', 'Linguística'],
    ['정면', 'jeongmyeon', 'fachada / frente', 'substantivo', '정면이 복원됐어요.', 'Jeongmyeoni bogwondwaesseoyo.', 'A fachada foi restaurada.', 'Arquitetura'],
    ['기초', 'gicho', 'fundação (de obra)', 'substantivo', '기초에 금이 갔어요.', 'Gichoe geumi gasseoyo.', 'A fundação rachou.', 'Arquitetura'],
    ['설계도', 'seolgyedo', 'planta / projeto', 'substantivo', '설계도를 다시 확인하세요.', 'Seolgyedoreul dasi hwaginhaseyo.', 'Confira a planta de novo.', 'Arquitetura'],
    ['둥근 천장', 'dunggeun cheonjang', 'abóbada', 'substantivo', '둥근 천장이 중세 것이에요.', 'Dunggeun cheonjangi jungse geosieyo.', 'A abóbada é medieval.', 'Arquitetura'],
    ['비계', 'bigye', 'andaime', 'substantivo', '오늘 비계를 세웠어요.', 'Oneul bigyereul sewosseoyo.', 'O andaime subiu hoje.', 'Arquitetura'],
    ['용도지역', 'yongdojiyeok', 'zoneamento', 'substantivo', '용도지역 규제로 막혔어요.', 'Yongdojiyeok gyujero makyeosseoyo.', 'O zoneamento barrou a obra.', 'Arquitetura'],
    ['개보수', 'gaebosu', 'reforma', 'substantivo', '개보수에 일 년이 걸렸어요.', 'Gaebosue il nyeoni geollyeosseoyo.', 'A reforma levou um ano.', 'Arquitetura'],
    ['내력벽', 'naeryeokbyeok', 'parede estrutural', 'substantivo', '그건 내력벽이에요.', 'Geugeon naeryeokbyeogieyo.', 'Aquela é uma parede estrutural.', 'Arquitetura'],
    ['도시 팽창', 'dosi paengchang', 'expansão urbana', 'substantivo', '도시 팽창이 계속돼요.', 'Dosi paengchangi gyesokdwaeyo.', 'A expansão urbana continua.', 'Arquitetura'],
    ['도시 경관', 'dosi gyeonggwan', 'paisagem urbana', 'substantivo', '도시 경관이 완전히 바뀌었어요.', 'Dosi gyeonggwani wanjeonhi bakkwieosseoyo.', 'A paisagem urbana mudou por completo.', 'Arquitetura'],
  ],
  C2: [
    ['긴장 완화', 'ginjang wanhwa', 'distensão (diplomática)', 'substantivo', '긴장 완화는 오래가지 못했어요.', 'Ginjang wanhwaneun oraegaji motaesseoyo.', 'A distensão não durou.', 'Diplomacia'],
    ['관계 개선', 'gwangye gaeseon', 'reaproximação', 'substantivo', '조심스러운 관계 개선이 시작됐어요.', 'Josimseureoun gwangye gaeseoni sijakdwaesseoyo.', 'Começou uma reaproximação cautelosa.', 'Diplomacia'],
    ['공식 성명', 'gongsik seongmyeong', 'comunicado oficial', 'substantivo', '공식 성명은 별말이 없었어요.', 'Gongsik seongmyeongeun byeolmari eopseosseoyo.', 'O comunicado oficial dizia pouco.', 'Diplomacia'],
    ['특사', 'teuksa', 'emissário especial', 'substantivo', '특사가 파견됐어요.', 'Teuksaga pagyeondwaesseoyo.', 'Um emissário foi enviado.', 'Diplomacia'],
    ['협정', 'hyeopjeong', 'acordo formal', 'substantivo', '협정은 아직 유지돼요.', 'Hyeopjeongeun ajik yujidwaeyo.', 'O acordo ainda se mantém.', 'Diplomacia'],
    ['제재', 'jejae', 'sanção', 'substantivo', '제재가 해제됐어요.', 'Jejaega haejedwaesseoyo.', 'As sanções foram suspensas.', 'Diplomacia'],
    ['중립', 'jungnip', 'neutralidade', 'substantivo', '중립을 선언했어요.', 'Jungnibeul seoneonhaesseoyo.', 'Declararam neutralidade.', 'Diplomacia'],
    ['주권', 'jugwon', 'soberania', 'substantivo', '주권이 쟁점이 됐어요.', 'Jugwoni jaengjeomi dwaesseoyo.', 'A soberania virou o impasse.', 'Diplomacia'],
    ['상호주의', 'sanghojuui', 'reciprocidade', 'substantivo', '합의는 상호주의에 근거해요.', 'Habuineun sanghojuuie geun-geohaeyo.', 'O acordo se baseia na reciprocidade.', 'Diplomacia'],
    ['벼랑끝 전술', 'byeorangkkeut jeonsul', 'política do abismo', 'substantivo', '이건 벼랑끝 전술일 뿐이에요.', 'Igeon byeorangkkeut jeonsuril ppunieyo.', 'Isso é apenas política do abismo.', 'Diplomacia'],
    ['신정론', 'sinjeongnon', 'teodiceia', 'substantivo', '신정론은 악의 문제를 물어요.', 'Sinjeongnoneun agui munjereul mureoyo.', 'A teodiceia questiona o problema do mal.', 'Teologia e mito'],
    ['신격화', 'singyeokhwa', 'apoteose / divinização', 'substantivo', '그것은 양식의 신격화였어요.', 'Geugeoseun yangsigui singyeokhwayeosseoyo.', 'Foi a apoteose do estilo.', 'Teologia e mito'],
    ['종말론', 'jongmallon', 'escatologia', 'substantivo', '종말론은 마지막 일을 다뤄요.', 'Jongmalloneun majimak ireul daryeoyo.', 'A escatologia trata das coisas últimas.', 'Teologia e mito'],
    ['전례', 'jeollye', 'liturgia', 'substantivo', '이 전례는 수 세기 됐어요.', 'I jeollyeneun su segi dwaesseoyo.', 'Esta liturgia tem séculos.', 'Teologia e mito'],
    ['이단', 'idan', 'heresia', 'substantivo', '이단으로 단죄됐어요.', 'Idaneuro danjoedwaesseoyo.', 'Foi condenado como heresia.', 'Teologia e mito'],
    ['만신전', 'mansinjeon', 'panteão', 'substantivo', '위인들의 만신전에 들었어요.', 'Wiindeurui mansinjeone deureosseoyo.', 'Entrou no panteão dos grandes.', 'Teologia e mito'],
    ['신탁', 'sintak', 'oráculo', 'substantivo', '신탁은 수수께끼 같았어요.', 'Sintageun susukkekki gatasseoyo.', 'O oráculo era enigmático.', 'Teologia e mito'],
    ['성유물', 'seongyumul', 'relíquia sagrada', 'substantivo', '성유물이 순례자를 모았어요.', 'Seongyumuri sullyejareul moasseoyo.', 'A relíquia atraía peregrinos.', 'Teologia e mito'],
    ['교회 분열', 'gyohoe bunyeol', 'cisma', 'substantivo', '교회 분열이 신자를 갈랐어요.', 'Gyohoe bunyeori sinjareul gallasseoyo.', 'O cisma dividiu os fiéis.', 'Teologia e mito'],
    ['초월', 'chowol', 'transcendência', 'substantivo', '이 시는 초월을 지향해요.', 'I sineun choworeul jihyanghaeyo.', 'Este poema busca a transcendência.', 'Teologia e mito'],
    ['선험적으로', 'seonheomjeogeuro', 'a priori', 'advérbio', '그건 선험적으로 알 수 없어요.', 'Geugeon seonheomjeogeuro al su eopseoyo.', 'Isso não se sabe a priori.', 'Locuções cultas'],
    ['더욱이', 'deougi', 'com mais razão ainda', 'advérbio', '더욱이 두 번째 경우는 성립하지 않아요.', 'Deougi du beonjjae gyeong-uneun seongniphaji anayo.', 'Com mais razão ainda, o segundo caso não se sustenta.', 'Locuções cultas'],
    ['필수 조건', 'pilsu jogeon', 'condição indispensável', 'substantivo', '신뢰가 필수 조건이에요.', 'Silloega pilsu jogeonieyo.', 'A confiança é a condição indispensável.', 'Locuções cultas'],
    ['사실상의', 'sasilsangui', 'de fato', 'adjetivo', '그녀가 사실상의 책임자예요.', 'Geunyeoga sasilsangui chaegimjayeyo.', 'Ela é a responsável de fato.', 'Locuções cultas'],
    ['임시의', 'imsiui', 'provisório / ad hoc', 'adjetivo', '임시의 위원회였어요.', 'Imsiui wiwonhoeyeosseoyo.', 'Era um comitê provisório.', 'Locuções cultas'],
    ['준용하여', 'junyonghayeo', 'aplicando-se com as devidas adaptações', 'advérbio', '같은 규정을 준용하여 적용해요.', 'Gateun gyujeongeul junyonghayeo jeogyonghaeyo.', 'Aplica-se a mesma norma com as devidas adaptações.', 'Locuções cultas'],
    ['다른 조건이 같다면', 'dareun jogeoni gatdamyeon', 'mantidas as demais condições', 'advérbio', '다른 조건이 같다면 수요가 줄어요.', 'Dareun jogeoni gatdamyeon suyoga jureoyo.', 'Mantidas as demais condições, a procura cai.', 'Locuções cultas'],
    ['일응', 'ireung', 'à primeira vista (jurídico)', 'advérbio', '일응 근거가 있어요.', 'Ireung geun-geoga isseoyo.', 'Há fundamento à primeira vista.', 'Locuções cultas'],
    ['그 자체만으로는', 'geu jachemaneuroneun', 'em si mesmo considerado', 'advérbio', '규칙은 그 자체만으로는 부당하지 않아요.', 'Gyuchigeun geu jachemaneuroneun budanghaji anayo.', 'A regra, em si mesma, não é injusta.', 'Locuções cultas'],
    ['막판에', 'makpane', 'no último instante', 'advérbio', '합의는 막판에 살아났어요.', 'Habuineun makpane saranasseoyo.', 'O acordo foi salvo no último instante.', 'Locuções cultas'],
    ['향수', 'hyangsu', 'nostalgia / saudade', 'substantivo', '향수에 젖어 말했어요.', 'Hyangsue jeojeo malhaesseoyo.', 'Falou tomado de nostalgia.', 'Emoções sutis'],
    ['우수', 'usu', 'melancolia', 'substantivo', '조용한 우수가 흘러요.', 'Joyonghan usuga heulleoyo.', 'Corre por ali uma melancolia discreta.', 'Emoções sutis'],
    ['권태', 'gwontae', 'tédio / lassidão', 'substantivo', '긴 오후의 권태.', 'Gin ohuui gwontae.', 'O tédio das tardes longas.', 'Emoções sutis'],
    ['고양감', 'goyanggam', 'exaltação / euforia', 'substantivo', '고양감은 오래가지 않았어요.', 'Goyanggameun oraegaji anasseoyo.', 'A euforia durou pouco.', 'Emoções sutis'],
    ['불안감', 'buran-gam', 'inquietação', 'substantivo', '그 소식이 불안감을 낳았어요.', 'Geu sosigi buran-gameul nanasseoyo.', 'A notícia gerou inquietação.', 'Emoções sutis'],
    ['갈망', 'galmang', 'anseio', 'substantivo', '잃어버린 것에 대한 갈망.', 'Ireobeorin geose daehan galmang.', 'Um anseio pelo que se perdeu.', 'Emoções sutis'],
    ['평온', 'pyeongon', 'serenidade', 'substantivo', '평온하게 받아들였어요.', 'Pyeongonhage badadeuryeosseoyo.', 'Recebeu com serenidade.', 'Emoções sutis'],
    ['의분', 'uibun', 'indignação justa', 'substantivo', '그의 의분은 정당했어요.', 'Geuui uibuneun jeongdanghaesseoyo.', 'A indignação dele era justa.', 'Emoções sutis'],
    ['몽상', 'mongsang', 'devaneio', 'substantivo', '몽상에 잠겼어요.', 'Mongsange jamgyeosseoyo.', 'Mergulhou num devaneio.', 'Emoções sutis'],
    ['위안', 'wian', 'consolo', 'substantivo', '음악에서 위안을 찾았어요.', 'Eumageseo wianeul chajasseoyo.', 'Encontrou consolo na música.', 'Emoções sutis'],
  ],
};
