/** Mandarim — segundo lote temático. Nenhuma palavra repete os lotes anteriores. */

import type { AsianByLevel } from '../entry';

export const ZH_THEMATIC2: AsianByLevel = {
  A1: [
    ['一', 'yī', 'um', 'numeral', '我要一个苹果。', 'Wǒ yào yí gè píngguǒ.', 'Quero uma maçã.', 'Números e quantidade'],
    ['二', 'èr', 'dois', 'numeral', '她有二个哥哥。', 'Tā yǒu èr gè gēge.', 'Ela tem dois irmãos.', 'Números e quantidade'],
    ['三', 'sān', 'três', 'numeral', '我们等了三个小时。', 'Wǒmen děng le sān gè xiǎoshí.', 'Esperamos três horas.', 'Números e quantidade'],
    ['很多', 'hěn duō', 'muitos', 'determinante', '这里有很多人。', 'Zhèlǐ yǒu hěn duō rén.', 'Há muitas pessoas aqui.', 'Números e quantidade'],
    ['一点', 'yìdiǎn', 'um pouco', 'advérbio', '我只吃了一点。', 'Wǒ zhǐ chī le yìdiǎn.', 'Comi só um pouco.', 'Números e quantidade'],
    ['一半', 'yíbàn', 'metade', 'substantivo', '我吃了一半。', 'Wǒ chī le yíbàn.', 'Comi metade.', 'Números e quantidade'],
    ['空', 'kōng', 'vazio', 'adjetivo', '瓶子是空的。', 'Píngzi shì kōng de.', 'A garrafa está vazia.', 'Números e quantidade'],
    ['满', 'mǎn', 'cheio', 'adjetivo', '杯子是满的。', 'Bēizi shì mǎn de.', 'O copo está cheio.', 'Números e quantidade'],
    ['重', 'zhòng', 'pesado', 'adjetivo', '这个箱子很重。', 'Zhège xiāngzi hěn zhòng.', 'Esta caixa é pesada.', 'Números e quantidade'],
    ['轻', 'qīng', 'leve', 'adjetivo', '包很轻。', 'Bāo hěn qīng.', 'A bolsa é leve.', 'Números e quantidade'],
    ['起床', 'qǐchuáng', 'levantar da cama', 'verbo', '我六点起床。', 'Wǒ liù diǎn qǐchuáng.', 'Eu me levanto às seis.', 'Ações do dia a dia'],
    ['睡觉', 'shuìjiào', 'dormir', 'verbo', '我睡八个小时。', 'Wǒ shuì bā gè xiǎoshí.', 'Eu durmo oito horas.', 'Ações do dia a dia'],
    ['洗', 'xǐ', 'lavar', 'verbo', '请洗手。', 'Qǐng xǐ shǒu.', 'Lave as mãos.', 'Ações do dia a dia'],
    ['做饭', 'zuò fàn', 'cozinhar', 'verbo', '她每天晚上做饭。', 'Tā měitiān wǎnshang zuò fàn.', 'Ela cozinha toda noite.', 'Ações do dia a dia'],
    ['打扫', 'dǎsǎo', 'limpar', 'verbo', '我打扫房子。', 'Wǒ dǎsǎo fángzi.', 'Eu limpo a casa.', 'Ações do dia a dia'],
    ['买', 'mǎi', 'comprar', 'verbo', '我在这里买面包。', 'Wǒ zài zhèlǐ mǎi miànbāo.', 'Eu compro pão aqui.', 'Ações do dia a dia'],
    ['卖', 'mài', 'vender', 'verbo', '他们卖水果。', 'Tāmen mài shuǐguǒ.', 'Eles vendem frutas.', 'Ações do dia a dia'],
    ['走', 'zǒu', 'caminhar / ir embora', 'verbo', '我们走路去学校。', 'Wǒmen zǒulù qù xuéxiào.', 'Nós vamos a pé para a escola.', 'Ações do dia a dia'],
    ['跑', 'pǎo', 'correr', 'verbo', '他跑得很快。', 'Tā pǎo de hěn kuài.', 'Ele corre muito rápido.', 'Ações do dia a dia'],
    ['等', 'děng', 'esperar', 'verbo', '请在这里等。', 'Qǐng zài zhèlǐ děng.', 'Espere aqui, por favor.', 'Ações do dia a dia'],
    ['老师', 'lǎoshī', 'professor', 'substantivo', '老师很亲切。', 'Lǎoshī hěn qīnqiè.', 'O professor é gentil.', 'Escola'],
    ['学生', 'xuésheng', 'aluno', 'substantivo', '她是好学生。', 'Tā shì hǎo xuésheng.', 'Ela é uma boa aluna.', 'Escola'],
    ['书', 'shū', 'livro', 'substantivo', '这本书很长。', 'Zhè běn shū hěn cháng.', 'Este livro é longo.', 'Escola'],
    ['笔', 'bǐ', 'caneta', 'substantivo', '我需要一支笔。', 'Wǒ xūyào yì zhī bǐ.', 'Preciso de uma caneta.', 'Escola'],
    ['本子', 'běnzi', 'caderno', 'substantivo', '请打开本子。', 'Qǐng dǎkāi běnzi.', 'Abra o caderno.', 'Escola'],
    ['课', 'kè', 'aula', 'substantivo', '课现在开始。', 'Kè xiànzài kāishǐ.', 'A aula começa agora.', 'Escola'],
    ['作业', 'zuòyè', 'lição de casa', 'substantivo', '我做完作业了。', 'Wǒ zuò wán zuòyè le.', 'Terminei a lição de casa.', 'Escola'],
    ['考试', 'kǎoshì', 'prova', 'substantivo', '考试很难。', 'Kǎoshì hěn nán.', 'A prova foi difícil.', 'Escola'],
    ['教室', 'jiàoshì', 'sala de aula', 'substantivo', '教室很大。', 'Jiàoshì hěn dà.', 'A sala de aula é grande.', 'Escola'],
    ['黑板', 'hēibǎn', 'quadro-negro', 'substantivo', '请看黑板。', 'Qǐng kàn hēibǎn.', 'Olhe para o quadro.', 'Escola'],
    ['鸟', 'niǎo', 'pássaro', 'substantivo', '一只鸟在唱歌。', 'Yì zhī niǎo zài chànggē.', 'Um pássaro está cantando.', 'Animais'],
    ['鱼', 'yú', 'peixe', 'substantivo', '这条鱼很小。', 'Zhè tiáo yú hěn xiǎo.', 'Este peixe é pequeno.', 'Animais'],
    ['马', 'mǎ', 'cavalo', 'substantivo', '马跑得很快。', 'Mǎ pǎo de hěn kuài.', 'O cavalo corre rápido.', 'Animais'],
    ['牛', 'niú', 'vaca / boi', 'substantivo', '牛在吃草。', 'Niú zài chī cǎo.', 'A vaca está comendo grama.', 'Animais'],
    ['鸡', 'jī', 'galinha', 'substantivo', '我们有三只鸡。', 'Wǒmen yǒu sān zhī jī.', 'Temos três galinhas.', 'Animais'],
    ['老鼠', 'lǎoshǔ', 'rato', 'substantivo', '这里有一只老鼠。', 'Zhèlǐ yǒu yì zhī lǎoshǔ.', 'Tem um rato aqui.', 'Animais'],
    ['昆虫', 'kūnchóng', 'inseto', 'substantivo', '一只昆虫飞进来了。', 'Yì zhī kūnchóng fēi jìnlái le.', 'Um inseto entrou voando.', 'Animais'],
    ['羊', 'yáng', 'ovelha', 'substantivo', '羊是白色的。', 'Yáng shì báisè de.', 'As ovelhas são brancas.', 'Animais'],
    ['猪', 'zhū', 'porco', 'substantivo', '猪很脏。', 'Zhū hěn zāng.', 'O porco está sujo.', 'Animais'],
    ['兔子', 'tùzi', 'coelho', 'substantivo', '兔子跑得快。', 'Tùzi pǎo de kuài.', 'O coelho corre rápido.', 'Animais'],
  ],
  A2: [
    ['公交车', 'gōngjiāochē', 'ônibus', 'substantivo', '公交车晚点了。', 'Gōngjiāochē wǎndiǎn le.', 'O ônibus está atrasado.', 'Transporte'],
    ['火车', 'huǒchē', 'trem', 'substantivo', '火车八点开。', 'Huǒchē bā diǎn kāi.', 'O trem sai às oito.', 'Transporte'],
    ['汽车', 'qìchē', 'carro', 'substantivo', '我的汽车很旧。', 'Wǒ de qìchē hěn jiù.', 'Meu carro é velho.', 'Transporte'],
    ['自行车', 'zìxíngchē', 'bicicleta', 'substantivo', '我骑自行车。', 'Wǒ qí zìxíngchē.', 'Eu ando de bicicleta.', 'Transporte'],
    ['出租车', 'chūzūchē', 'táxi', 'substantivo', '我们打出租车吧。', 'Wǒmen dǎ chūzūchē ba.', 'Vamos pegar um táxi.', 'Transporte'],
    ['司机', 'sījī', 'motorista', 'substantivo', '司机很有礼貌。', 'Sījī hěn yǒu lǐmào.', 'O motorista foi educado.', 'Transporte'],
    ['票价', 'piàojià', 'tarifa', 'substantivo', '票价涨了。', 'Piàojià zhǎng le.', 'A tarifa subiu.', 'Transporte'],
    ['站台', 'zhàntái', 'plataforma', 'substantivo', '请在二号站台等。', 'Qǐng zài èr hào zhàntái děng.', 'Espere na plataforma dois.', 'Transporte'],
    ['座位', 'zuòwèi', 'assento', 'substantivo', '这个座位是空的。', 'Zhège zuòwèi shì kōng de.', 'Este assento está livre.', 'Transporte'],
    ['路程', 'lùchéng', 'trajeto', 'substantivo', '路程要两个小时。', 'Lùchéng yào liǎng gè xiǎoshí.', 'O trajeto leva duas horas.', 'Transporte'],
    ['爱好', 'àihào', 'passatempo', 'substantivo', '看书是我的爱好。', 'Kànshū shì wǒ de àihào.', 'Ler é meu passatempo.', 'Lazer'],
    ['博物馆', 'bówùguǎn', 'museu', 'substantivo', '博物馆今天免费。', 'Bówùguǎn jīntiān miǎnfèi.', 'O museu está de graça hoje.', 'Lazer'],
    ['电影院', 'diànyǐngyuàn', 'cinema', 'substantivo', '我们去了电影院。', 'Wǒmen qù le diànyǐngyuàn.', 'Fomos ao cinema.', 'Lazer'],
    ['音乐会', 'yīnyuèhuì', 'concerto', 'substantivo', '音乐会很棒。', 'Yīnyuèhuì hěn bàng.', 'O concerto foi ótimo.', 'Lazer'],
    ['公园', 'gōngyuán', 'parque', 'substantivo', '公园很近。', 'Gōngyuán hěn jìn.', 'O parque fica perto.', 'Lazer'],
    ['游戏', 'yóuxì', 'jogo', 'substantivo', '这个游戏很好玩。', 'Zhège yóuxì hěn hǎowán.', 'Este jogo é divertido.', 'Lazer'],
    ['相机', 'xiàngjī', 'câmera', 'substantivo', '把相机带来。', 'Bǎ xiàngjī dài lái.', 'Traga sua câmera.', 'Lazer'],
    ['野餐', 'yěcān', 'piquenique', 'substantivo', '我们去野餐了。', 'Wǒmen qù yěcān le.', 'Fomos a um piquenique.', 'Lazer'],
    ['游泳', 'yóuyǒng', 'nadar', 'verbo', '我星期天游泳。', 'Wǒ xīngqītiān yóuyǒng.', 'Eu nado aos domingos.', 'Lazer'],
    ['跳舞', 'tiàowǔ', 'dançar', 'verbo', '他们跳舞跳得很好。', 'Tāmen tiàowǔ tiào de hěn hǎo.', 'Eles dançam muito bem.', 'Lazer'],
    ['开心', 'kāixīn', 'contente', 'adjetivo', '她看起来很开心。', 'Tā kàn qǐlái hěn kāixīn.', 'Ela parece contente.', 'Emoções'],
    ['难过', 'nánguò', 'triste', 'adjetivo', '他昨天很难过。', 'Tā zuótiān hěn nánguò.', 'Ele estava triste ontem.', 'Emoções'],
    ['生气', 'shēngqì', 'ficar bravo', 'verbo', '别生气。', 'Bié shēngqì.', 'Não fique bravo.', 'Emoções'],
    ['害怕', 'hàipà', 'ter medo', 'verbo', '我害怕狗。', 'Wǒ hàipà gǒu.', 'Tenho medo de cachorro.', 'Emoções'],
    ['惊讶', 'jīngyà', 'surpreso', 'adjetivo', '我们很惊讶。', 'Wǒmen hěn jīngyà.', 'Ficamos surpresos.', 'Emoções'],
    ['无聊', 'wúliáo', 'entediado / sem graça', 'adjetivo', '孩子们很无聊。', 'Háizimen hěn wúliáo.', 'As crianças estão entediadas.', 'Emoções'],
    ['担心', 'dānxīn', 'preocupar-se', 'verbo', '她很担心这件事。', 'Tā hěn dānxīn zhè jiàn shì.', 'Ela está preocupada com isso.', 'Emoções'],
    ['骄傲', 'jiāo’ào', 'orgulhoso', 'adjetivo', '我为你骄傲。', 'Wǒ wèi nǐ jiāo’ào.', 'Estou orgulhoso de você.', 'Emoções'],
    ['冷静', 'lěngjìng', 'calmo', 'adjetivo', '请保持冷静。', 'Qǐng bǎochí lěngjìng.', 'Mantenha a calma.', 'Emoções'],
    ['孤单', 'gūdān', 'solitário', 'adjetivo', '他觉得很孤单。', 'Tā juéde hěn gūdān.', 'Ele se sente muito solitário.', 'Emoções'],
    ['年轻', 'niánqīng', 'jovem', 'adjetivo', '她很年轻。', 'Tā hěn niánqīng.', 'Ela é muito jovem.', 'Descrever pessoas'],
    ['年老', 'niánlǎo', 'idoso', 'adjetivo', '我爷爷年老了。', 'Wǒ yéye niánlǎo le.', 'Meu avô está idoso.', 'Descrever pessoas'],
    ['善良', 'shànliáng', 'bondoso', 'adjetivo', '他是个善良的人。', 'Tā shì gè shànliáng de rén.', 'Ele é uma pessoa bondosa.', 'Descrever pessoas'],
    ['幽默', 'yōumò', 'bem-humorado', 'adjetivo', '你的朋友很幽默。', 'Nǐ de péngyou hěn yōumò.', 'Seu amigo é bem-humorado.', 'Descrever pessoas'],
    ['安静', 'ānjìng', 'quieto', 'adjetivo', '她很安静。', 'Tā hěn ānjìng.', 'Ela é muito quieta.', 'Descrever pessoas'],
    ['聪明', 'cōngming', 'inteligente', 'adjetivo', '那是个聪明的主意。', 'Nà shì gè cōngming de zhǔyi.', 'Foi uma ideia inteligente.', 'Descrever pessoas'],
    ['懒', 'lǎn', 'preguiçoso', 'adjetivo', '别懒。', 'Bié lǎn.', 'Não seja preguiçoso.', 'Descrever pessoas'],
    ['诚实', 'chéngshí', 'honesto', 'adjetivo', '她一直很诚实。', 'Tā yìzhí hěn chéngshí.', 'Ela é sempre honesta.', 'Descrever pessoas'],
    ['友好', 'yǒuhǎo', 'amigável', 'adjetivo', '员工很友好。', 'Yuángōng hěn yǒuhǎo.', 'Os funcionários são amigáveis.', 'Descrever pessoas'],
    ['强壮', 'qiángzhuàng', 'forte (fisicamente)', 'adjetivo', '他很强壮。', 'Tā hěn qiángzhuàng.', 'Ele é muito forte.', 'Descrever pessoas'],
  ],
  B1: [
    ['饮食', 'yǐnshí', 'alimentação', 'substantivo', '她的饮食变了很多。', 'Tā de yǐnshí biàn le hěn duō.', 'A alimentação dela mudou muito.', 'Saúde e bem-estar'],
    ['锻炼', 'duànliàn', 'exercitar-se', 'verbo', '锻炼有助于睡眠。', 'Duànliàn yǒuzhùyú shuìmián.', 'Exercitar-se ajuda no sono.', 'Saúde e bem-estar'],
    ['压力', 'yālì', 'estresse / pressão', 'substantivo', '压力会影响身体。', 'Yālì huì yǐngxiǎng shēntǐ.', 'O estresse afeta o corpo.', 'Saúde e bem-estar'],
    ['习惯', 'xíguàn', 'hábito', 'substantivo', '这成了一个习惯。', 'Zhè chéng le yí gè xíguàn.', 'Isso virou um hábito.', 'Saúde e bem-estar'],
    ['治疗', 'zhìliáo', 'tratamento', 'substantivo', '治疗帮了他很多。', 'Zhìliáo bāng le tā hěn duō.', 'O tratamento o ajudou muito.', 'Saúde e bem-estar'],
    ['康复', 'kāngfù', 'recuperação', 'substantivo', '康复需要时间。', 'Kāngfù xūyào shíjiān.', 'A recuperação leva tempo.', 'Saúde e bem-estar'],
    ['姿势', 'zīshì', 'postura', 'substantivo', '请纠正姿势。', 'Qǐng jiūzhèng zīshì.', 'Corrija sua postura.', 'Saúde e bem-estar'],
    ['呼吸', 'hūxī', 'respiração', 'substantivo', '缓慢的呼吸让人平静。', 'Huǎnmàn de hūxī ràng rén píngjìng.', 'A respiração lenta acalma.', 'Saúde e bem-estar'],
    ['体检', 'tǐjiǎn', 'check-up médico', 'substantivo', '我今天做了体检。', 'Wǒ jīntiān zuò le tǐjiǎn.', 'Fiz um check-up hoje.', 'Saúde e bem-estar'],
    ['安康', 'ānkāng', 'bem-estar', 'substantivo', '他们重视员工的安康。', 'Tāmen zhòngshì yuángōng de ānkāng.', 'Valorizam o bem-estar dos funcionários.', 'Saúde e bem-estar'],
    ['租金', 'zūjīn', 'aluguel', 'substantivo', '租金又涨了。', 'Zūjīn yòu zhǎng le.', 'O aluguel subiu de novo.', 'Moradia'],
    ['租约', 'zūyuē', 'contrato de locação', 'substantivo', '租约六月到期。', 'Zūyuē liùyuè dàoqī.', 'O contrato vence em junho.', 'Moradia'],
    ['押金', 'yājīn', 'caução', 'substantivo', '押金没退还。', 'Yājīn méi tuìhuán.', 'A caução não foi devolvida.', 'Moradia'],
    ['租客', 'zūkè', 'inquilino', 'substantivo', '租客投诉了。', 'Zūkè tóusù le.', 'O inquilino reclamou.', 'Moradia'],
    ['天花板', 'tiānhuābǎn', 'teto', 'substantivo', '天花板漏水。', 'Tiānhuābǎn lòushuǐ.', 'O teto está vazando.', 'Moradia'],
    ['屋顶', 'wūdǐng', 'telhado', 'substantivo', '屋顶要修了。', 'Wūdǐng yào xiū le.', 'O telhado precisa de conserto.', 'Moradia'],
    ['地下室', 'dìxiàshì', 'porão', 'substantivo', '地下室很潮湿。', 'Dìxiàshì hěn cháoshī.', 'O porão está úmido.', 'Moradia'],
    ['阳台', 'yángtái', 'varanda', 'substantivo', '我们在阳台吃饭。', 'Wǒmen zài yángtái chīfàn.', 'Comemos na varanda.', 'Moradia'],
    ['管道', 'guǎndào', 'encanamento', 'substantivo', '管道很旧了。', 'Guǎndào hěn jiù le.', 'O encanamento é velho.', 'Moradia'],
    ['房主', 'fángzhǔ', 'proprietário do imóvel', 'substantivo', '房主给我打电话了。', 'Fángzhǔ gěi wǒ dǎ diànhuà le.', 'O proprietário me ligou.', 'Moradia'],
    ['食谱', 'shípǔ', 'receita culinária', 'substantivo', '把食谱发给我。', 'Bǎ shípǔ fā gěi wǒ.', 'Me manda a receita.', 'Culinária'],
    ['配料', 'pèiliào', 'ingrediente', 'substantivo', '少了一样配料。', 'Shǎo le yí yàng pèiliào.', 'Falta um ingrediente.', 'Culinária'],
    ['煮沸', 'zhǔfèi', 'ferver', 'verbo', '先把水煮沸。', 'Xiān bǎ shuǐ zhǔfèi.', 'Ferva a água primeiro.', 'Culinária'],
    ['炸', 'zhá', 'fritar em óleo', 'verbo', '慢慢把洋葱炸一下。', 'Mànman bǎ yángcōng zhá yíxià.', 'Frite a cebola devagar.', 'Culinária'],
    ['烤', 'kǎo', 'assar', 'verbo', '烤一个小时。', 'Kǎo yí gè xiǎoshí.', 'Asse por uma hora.', 'Culinária'],
    ['切碎', 'qiēsuì', 'picar', 'verbo', '把蒜切碎。', 'Bǎ suàn qiēsuì.', 'Pique o alho.', 'Culinária'],
    ['调味', 'tiáowèi', 'temperar', 'verbo', '用胡椒调味。', 'Yòng hújiāo tiáowèi.', 'Tempere com pimenta.', 'Culinária'],
    ['面团', 'miàntuán', 'massa (crua)', 'substantivo', '面团要醒一会儿。', 'Miàntuán yào xǐng yíhuìr.', 'A massa precisa descansar.', 'Culinária'],
    ['炖', 'dùn', 'cozinhar em fogo baixo', 'verbo', '我们慢慢炖肉。', 'Wǒmen mànman dùn ròu.', 'Cozinhamos a carne devagar.', 'Culinária'],
    ['蒸', 'zhēng', 'cozinhar no vapor', 'verbo', '把蔬菜蒸一下。', 'Bǎ shūcài zhēng yíxià.', 'Cozinhe os legumes no vapor.', 'Culinária'],
    ['消息', 'xiāoxi', 'mensagem / notícia', 'substantivo', '我收到你的消息了。', 'Wǒ shōudào nǐ de xiāoxi le.', 'Recebi sua mensagem.', 'Comunicação'],
    ['回复', 'huífù', 'resposta', 'substantivo', '我在等回复。', 'Wǒ zài děng huífù.', 'Estou esperando resposta.', 'Comunicação'],
    ['通知', 'tōngzhī', 'aviso', 'substantivo', '门上有一张通知。', 'Mén shàng yǒu yì zhāng tōngzhī.', 'Há um aviso na porta.', 'Comunicação'],
    ['公告', 'gōnggào', 'comunicado', 'substantivo', '他们发了公告。', 'Tāmen fā le gōnggào.', 'Fizeram um comunicado.', 'Comunicação'],
    ['传闻', 'chuánwén', 'boato', 'substantivo', '那只是传闻。', 'Nà zhǐshì chuánwén.', 'Isso é só um boato.', 'Comunicação'],
    ['声明', 'shēngmíng', 'declaração pública', 'substantivo', '她发表了声明。', 'Tā fābiǎo le shēngmíng.', 'Ela divulgou uma declaração.', 'Comunicação'],
    ['解释', 'jiěshì', 'explicar', 'verbo', '请再解释一遍。', 'Qǐng zài jiěshì yí biàn.', 'Explique de novo, por favor.', 'Comunicação'],
    ['描述', 'miáoshù', 'descrever', 'verbo', '描述一下你看到的。', 'Miáoshù yíxià nǐ kàndào de.', 'Descreva o que você viu.', 'Comunicação'],
    ['总结', 'zǒngjié', 'resumir', 'verbo', '用一句话总结。', 'Yòng yí jù huà zǒngjié.', 'Resuma em uma frase.', 'Comunicação'],
    ['误会', 'wùhuì', 'mal-entendido', 'substantivo', '那是个误会。', 'Nà shì gè wùhuì.', 'Foi um mal-entendido.', 'Comunicação'],
  ],
  B2: [
    ['雕塑', 'diāosù', 'escultura', 'substantivo', '这座雕塑是青铜的。', 'Zhè zuò diāosù shì qīngtóng de.', 'Esta escultura é de bronze.', 'Arte e cultura'],
    ['展览', 'zhǎnlǎn', 'exposição', 'substantivo', '展览周五开幕。', 'Zhǎnlǎn zhōuwǔ kāimù.', 'A exposição abre sexta.', 'Arte e cultura'],
    ['肖像', 'xiàoxiàng', 'retrato', 'substantivo', '她画了一幅肖像。', 'Tā huà le yì fú xiàoxiàng.', 'Ela pintou um retrato.', 'Arte e cultura'],
    ['画布', 'huàbù', 'tela (de pintura)', 'substantivo', '画布还是空白的。', 'Huàbù háishì kòngbái de.', 'A tela ainda está em branco.', 'Arte e cultura'],
    ['管弦乐队', 'guǎnxián yuèduì', 'orquestra', 'substantivo', '管弦乐队排练了。', 'Guǎnxián yuèduì páiliàn le.', 'A orquestra ensaiou.', 'Arte e cultura'],
    ['合唱团', 'héchàngtuán', 'coral', 'substantivo', '她在合唱团唱歌。', 'Tā zài héchàngtuán chànggē.', 'Ela canta num coral.', 'Arte e cultura'],
    ['剧作家', 'jùzuòjiā', 'dramaturgo', 'substantivo', '那位剧作家很有名。', 'Nà wèi jùzuòjiā hěn yǒumíng.', 'Aquele dramaturgo é famoso.', 'Arte e cultura'],
    ['小说家', 'xiǎoshuōjiā', 'romancista', 'substantivo', '她是年轻的小说家。', 'Tā shì niánqīng de xiǎoshuōjiā.', 'Ela é uma jovem romancista.', 'Arte e cultura'],
    ['民俗', 'mínsú', 'folclore', 'substantivo', '当地民俗很丰富。', 'Dāngdì mínsú hěn fēngfù.', 'O folclore local é rico.', 'Arte e cultura'],
    ['文化遗产', 'wénhuà yíchǎn', 'patrimônio cultural', 'substantivo', '这里是文化遗产。', 'Zhèlǐ shì wénhuà yíchǎn.', 'Aqui é patrimônio cultural.', 'Arte e cultura'],
    ['帝国', 'dìguó', 'império', 'substantivo', '帝国崩溃了。', 'Dìguó bēngkuì le.', 'O império ruiu.', 'História'],
    ['革命', 'gémìng', 'revolução', 'substantivo', '革命改变了一切。', 'Gémìng gǎibiàn le yíqiè.', 'A revolução mudou tudo.', 'História'],
    ['条约', 'tiáoyuē', 'tratado', 'substantivo', '他们签了条约。', 'Tāmen qiān le tiáoyuē.', 'Assinaram um tratado.', 'História'],
    ['殖民地', 'zhímíndì', 'colônia', 'substantivo', '这里曾是殖民地。', 'Zhèlǐ céng shì zhímíndì.', 'Aqui já foi uma colônia.', 'História'],
    ['王朝', 'wángcháo', 'dinastia', 'substantivo', '那个王朝延续了几个世纪。', 'Nàge wángcháo yánxù le jǐ gè shìjì.', 'Aquela dinastia durou séculos.', 'História'],
    ['起义', 'qǐyì', 'levante', 'substantivo', '起义被镇压了。', 'Qǐyì bèi zhènyā le.', 'O levante foi reprimido.', 'História'],
    ['围城', 'wéichéng', 'cerco', 'substantivo', '围城持续了一年。', 'Wéichéng chíxù le yì nián.', 'O cerco durou um ano.', 'História'],
    ['档案馆', 'dàng’ànguǎn', 'arquivo histórico', 'substantivo', '档案馆保存着这些信。', 'Dàng’ànguǎn bǎocún zhe zhèxiē xìn.', 'O arquivo guarda essas cartas.', 'História'],
    ['编年史', 'biānniánshǐ', 'crônica histórica', 'substantivo', '编年史提到了他。', 'Biānniánshǐ tídào le tā.', 'A crônica o menciona.', 'História'],
    ['文物', 'wénwù', 'artefato histórico', 'substantivo', '他们发现了一件文物。', 'Tāmen fāxiàn le yí jiàn wénwù.', 'Encontraram um artefato.', 'História'],
    ['大陆', 'dàlù', 'continente', 'substantivo', '这是最大的大陆。', 'Zhè shì zuì dà de dàlù.', 'É o maior continente.', 'Geografia'],
    ['半岛', 'bàndǎo', 'península', 'substantivo', '这个半岛多岩石。', 'Zhège bàndǎo duō yánshí.', 'Esta península é rochosa.', 'Geografia'],
    ['高原', 'gāoyuán', 'planalto', 'substantivo', '高原很干燥。', 'Gāoyuán hěn gānzào.', 'O planalto é seco.', 'Geografia'],
    ['冰川', 'bīngchuān', 'geleira', 'substantivo', '冰川在退缩。', 'Bīngchuān zài tuìsuō.', 'A geleira está recuando.', 'Geografia'],
    ['三角洲', 'sānjiǎozhōu', 'delta (de rio)', 'substantivo', '三角洲很肥沃。', 'Sānjiǎozhōu hěn féiwò.', 'O delta é fértil.', 'Geografia'],
    ['山谷', 'shāngǔ', 'vale', 'substantivo', '山谷经常被淹。', 'Shāngǔ jīngcháng bèi yān.', 'O vale alaga com frequência.', 'Geografia'],
    ['沙漠', 'shāmò', 'deserto', 'substantivo', '沙漠在扩大。', 'Shāmò zài kuòdà.', 'O deserto está avançando.', 'Geografia'],
    ['潮汐', 'cháoxī', 'maré', 'substantivo', '潮汐正在上涨。', 'Cháoxī zhèngzài shàngzhǎng.', 'A maré está subindo.', 'Geografia'],
    ['纬度', 'wěidù', 'latitude', 'substantivo', '先确认纬度。', 'Xiān quèrèn wěidù.', 'Confira a latitude primeiro.', 'Geografia'],
    ['地势', 'dìshì', 'relevo / terreno', 'substantivo', '地势很险峻。', 'Dìshì hěn xiǎnjùn.', 'O terreno é acidentado.', 'Geografia'],
    ['正直', 'zhèngzhí', 'integridade', 'substantivo', '他的正直毋庸置疑。', 'Tā de zhèngzhí wúyōng zhìyí.', 'A integridade dele é inquestionável.', 'Ética'],
    ['美德', 'měidé', 'virtude', 'substantivo', '耐心是一种美德。', 'Nàixīn shì yì zhǒng měidé.', 'A paciência é uma virtude.', 'Ética'],
    ['责任', 'zérèn', 'dever / responsabilidade', 'substantivo', '举报是你的责任。', 'Jǔbào shì nǐ de zérèn.', 'Relatar é seu dever.', 'Ética'],
    ['同意', 'tóngyì', 'consentimento', 'substantivo', '他们未经同意就行动了。', 'Tāmen wèijīng tóngyì jiù xíngdòng le.', 'Agiram sem consentimento.', 'Ética'],
    ['公平', 'gōngpíng', 'equidade / justiça', 'substantivo', '这里公平很重要。', 'Zhèlǐ gōngpíng hěn zhòngyào.', 'Aqui a equidade importa.', 'Ética'],
    ['伤害', 'shānghài', 'dano', 'substantivo', '这项政策造成了真实伤害。', 'Zhè xiàng zhèngcè zàochéng le zhēnshí shānghài.', 'Essa política causou dano real.', 'Ética'],
    ['尊严', 'zūnyán', 'dignidade', 'substantivo', '请以尊严对待他们。', 'Qǐng yǐ zūnyán duìdài tāmen.', 'Trate-os com dignidade.', 'Ética'],
    ['义务', 'yìwù', 'obrigação', 'substantivo', '我们有义务。', 'Wǒmen yǒu yìwù.', 'Temos uma obrigação.', 'Ética'],
    ['不当行为', 'bùdàng xíngwéi', 'má conduta', 'substantivo', '他因不当行为被解雇。', 'Tā yīn bùdàng xíngwéi bèi jiěgù.', 'Foi demitido por má conduta.', 'Ética'],
    ['举报人', 'jǔbàorén', 'denunciante', 'substantivo', '举报人受到了保护。', 'Jǔbàorén shòudào le bǎohù.', 'O denunciante foi protegido.', 'Ética'],
  ],
  C1: [
    ['官僚主义', 'guānliáo zhǔyì', 'burocracia', 'substantivo', '官僚主义拖慢了一切。', 'Guānliáo zhǔyì tuō màn le yíqiè.', 'A burocracia atrasou tudo.', 'Administração pública'],
    ['条例', 'tiáolì', 'regulamento / decreto', 'substantivo', '新条例通过了。', 'Xīn tiáolì tōngguò le.', 'Um novo decreto foi aprovado.', 'Administração pública'],
    ['合规', 'héguī', 'conformidade', 'substantivo', '合规是强制的。', 'Héguī shì qiángzhì de.', 'A conformidade é obrigatória.', 'Administração pública'],
    ['监管', 'jiānguǎn', 'fiscalização', 'substantivo', '监管很薄弱。', 'Jiānguǎn hěn bóruò.', 'A fiscalização era fraca.', 'Administração pública'],
    ['规程', 'guīchéng', 'protocolo', 'substantivo', '请严格遵守规程。', 'Qǐng yángé zūnshǒu guīchéng.', 'Siga o protocolo à risca.', 'Administração pública'],
    ['指令', 'zhǐlìng', 'diretriz', 'substantivo', '指令今天生效。', 'Zhǐlìng jīntiān shēngxiào.', 'A diretriz entra em vigor hoje.', 'Administração pública'],
    ['法定人数', 'fǎdìng rénshù', 'quórum', 'substantivo', '没有达到法定人数。', 'Méiyǒu dádào fǎdìng rénshù.', 'Não atingimos o quórum.', 'Administração pública'],
    ['终身职位', 'zhōngshēn zhíwèi', 'estabilidade vitalícia no cargo', 'substantivo', '她获得了终身职位。', 'Tā huòdé le zhōngshēn zhíwèi.', 'Ela obteve estabilidade no cargo.', 'Administração pública'],
    ['职权范围', 'zhíquán fànwéi', 'alçada / competência', 'substantivo', '这超出我们的职权范围。', 'Zhè chāochū wǒmen de zhíquán fànwéi.', 'Isso excede nossa alçada.', 'Administração pública'],
    ['救济措施', 'jiùjì cuòshī', 'medida reparatória', 'substantivo', '他们寻求法律救济措施。', 'Tāmen xúnqiú fǎlǜ jiùjì cuòshī.', 'Buscaram reparação legal.', 'Administração pública'],
    ['中位数', 'zhōngwèishù', 'mediana', 'substantivo', '这里中位数更有用。', 'Zhèlǐ zhōngwèishù gèng yǒuyòng.', 'Aqui a mediana é mais útil.', 'Estatística'],
    ['方差', 'fāngchā', 'variância', 'substantivo', '方差太大了。', 'Fāngchā tài dà le.', 'A variância é grande demais.', 'Estatística'],
    ['标准差', 'biāozhǔnchā', 'desvio padrão', 'substantivo', '请报告标准差。', 'Qǐng bàogào biāozhǔnchā.', 'Informe o desvio padrão.', 'Estatística'],
    ['回归分析', 'huíguī fēnxī', 'análise de regressão', 'substantivo', '回归分析解释力有限。', 'Huíguī fēnxī jiěshìlì yǒuxiàn.', 'A análise de regressão explica pouco.', 'Estatística'],
    ['概率', 'gàilǜ', 'probabilidade', 'substantivo', '概率很低。', 'Gàilǜ hěn dī.', 'A probabilidade é baixa.', 'Estatística'],
    ['分布', 'fēnbù', 'distribuição', 'substantivo', '分布是偏斜的。', 'Fēnbù shì piānxié de.', 'A distribuição é assimétrica.', 'Estatística'],
    ['异常值', 'yìcháng zhí', 'ponto fora da curva', 'substantivo', '请去掉那个异常值。', 'Qǐng qùdiào nàge yìcháng zhí.', 'Remova esse ponto fora da curva.', 'Estatística'],
    ['显著性', 'xiǎnzhùxìng', 'significância', 'substantivo', '显著性不等于重要性。', 'Xiǎnzhùxìng bù děngyú zhòngyàoxìng.', 'Significância não é importância.', 'Estatística'],
    ['阈值', 'yùzhí', 'limiar', 'substantivo', '它低于阈值。', 'Tā dīyú yùzhí.', 'Ficou abaixo do limiar.', 'Estatística'],
    ['估计值', 'gūjì zhí', 'valor estimado', 'substantivo', '这是个粗略的估计值。', 'Zhè shì gè cūlüè de gūjì zhí.', 'É uma estimativa aproximada.', 'Estatística'],
    ['句法', 'jùfǎ', 'sintaxe', 'substantivo', '这里句法不一样。', 'Zhèlǐ jùfǎ bù yíyàng.', 'Aqui a sintaxe é diferente.', 'Linguística'],
    ['语素', 'yǔsù', 'morfema', 'substantivo', '这个前缀是一个语素。', 'Zhège qiánzhuì shì yí gè yǔsù.', 'Este prefixo é um morfema.', 'Linguística'],
    ['音位', 'yīnwèi', 'fonema', 'substantivo', '这两个音位形成对立。', 'Zhè liǎng gè yīnwèi xíngchéng duìlì.', 'Estes dois fonemas contrastam.', 'Linguística'],
    ['语义学', 'yǔyìxué', 'semântica', 'substantivo', '争论在于语义学。', 'Zhēnglùn zàiyú yǔyìxué.', 'A disputa é de semântica.', 'Linguística'],
    ['方言', 'fāngyán', 'dialeto', 'substantivo', '方言因地区而异。', 'Fāngyán yīn dìqū ér yì.', 'O dialeto varia por região.', 'Linguística'],
    ['语体', 'yǔtǐ', 'registro de fala', 'substantivo', '请根据场合选择语体。', 'Qǐng gēnjù chǎnghé xuǎnzé yǔtǐ.', 'Escolha o registro conforme o contexto.', 'Linguística'],
    ['词源', 'cíyuán', 'etimologia', 'substantivo', '这个词源有争议。', 'Zhège cíyuán yǒu zhēngyì.', 'Esta etimologia é contestada.', 'Linguística'],
    ['同源词', 'tóngyuáncí', 'cognato', 'substantivo', '这两个是同源词。', 'Zhè liǎng gè shì tóngyuáncí.', 'Estas duas são palavras cognatas.', 'Linguística'],
    ['屈折变化', 'qūzhé biànhuà', 'flexão', 'substantivo', '屈折变化标示格。', 'Qūzhé biànhuà biāoshì gé.', 'A flexão marca o caso.', 'Linguística'],
    ['流利度', 'liúlìdù', 'fluência', 'substantivo', '流利度不等于准确度。', 'Liúlìdù bù děngyú zhǔnquèdù.', 'Fluência não é correção.', 'Linguística'],
    ['正立面', 'zhènglìmiàn', 'fachada', 'substantivo', '正立面已经修复。', 'Zhènglìmiàn yǐjīng xiūfù.', 'A fachada já foi restaurada.', 'Arquitetura'],
    ['地基', 'dìjī', 'fundação (de obra)', 'substantivo', '地基裂了。', 'Dìjī liè le.', 'A fundação rachou.', 'Arquitetura'],
    ['施工图', 'shīgōngtú', 'planta / projeto executivo', 'substantivo', '再核对一下施工图。', 'Zài héduì yíxià shīgōngtú.', 'Confira a planta de novo.', 'Arquitetura'],
    ['拱顶', 'gǒngdǐng', 'abóbada', 'substantivo', '这个拱顶是中世纪的。', 'Zhège gǒngdǐng shì zhōngshìjì de.', 'Esta abóbada é medieval.', 'Arquitetura'],
    ['脚手架', 'jiǎoshǒujià', 'andaime', 'substantivo', '今天搭了脚手架。', 'Jīntiān dā le jiǎoshǒujià.', 'O andaime subiu hoje.', 'Arquitetura'],
    ['分区规划', 'fēnqū guīhuà', 'zoneamento', 'substantivo', '分区规划挡住了这个项目。', 'Fēnqū guīhuà dǎngzhù le zhège xiàngmù.', 'O zoneamento barrou o projeto.', 'Arquitetura'],
    ['翻修', 'fānxiū', 'reforma', 'substantivo', '翻修花了一年。', 'Fānxiū huā le yì nián.', 'A reforma levou um ano.', 'Arquitetura'],
    ['承重墙', 'chéngzhòngqiáng', 'parede estrutural', 'substantivo', '那是一堵承重墙。', 'Nà shì yì dǔ chéngzhòngqiáng.', 'Aquela é uma parede estrutural.', 'Arquitetura'],
    ['城市扩张', 'chéngshì kuòzhāng', 'expansão urbana', 'substantivo', '城市扩张还在继续。', 'Chéngshì kuòzhāng hái zài jìxù.', 'A expansão urbana continua.', 'Arquitetura'],
    ['城市天际线', 'chéngshì tiānjìxiàn', 'silhueta urbana', 'substantivo', '城市天际线完全变了。', 'Chéngshì tiānjìxiàn wánquán biàn le.', 'A silhueta urbana mudou por completo.', 'Arquitetura'],
  ],
  C2: [
    ['缓和政策', 'huǎnhé zhèngcè', 'política de distensão', 'substantivo', '缓和政策没有持续。', 'Huǎnhé zhèngcè méiyǒu chíxù.', 'A política de distensão não durou.', 'Diplomacia'],
    ['关系改善', 'guānxì gǎishàn', 'reaproximação', 'substantivo', '谨慎的关系改善开始了。', 'Jǐnshèn de guānxì gǎishàn kāishǐ le.', 'Começou uma reaproximação cautelosa.', 'Diplomacia'],
    ['官方公报', 'guānfāng gōngbào', 'comunicado oficial', 'substantivo', '官方公报几乎没说什么。', 'Guānfāng gōngbào jīhū méi shuō shénme.', 'O comunicado oficial dizia pouco.', 'Diplomacia'],
    ['特使', 'tèshǐ', 'emissário especial', 'substantivo', '派出了一位特使。', 'Pàichū le yí wèi tèshǐ.', 'Um emissário foi enviado.', 'Diplomacia'],
    ['协定', 'xiédìng', 'acordo formal', 'substantivo', '协定目前还有效。', 'Xiédìng mùqián hái yǒuxiào.', 'O acordo ainda está em vigor.', 'Diplomacia'],
    ['制裁', 'zhìcái', 'sanção', 'substantivo', '制裁被解除了。', 'Zhìcái bèi jiěchú le.', 'As sanções foram suspensas.', 'Diplomacia'],
    ['中立', 'zhōnglì', 'neutralidade', 'substantivo', '他们宣布中立。', 'Tāmen xuānbù zhōnglì.', 'Declararam neutralidade.', 'Diplomacia'],
    ['主权', 'zhǔquán', 'soberania', 'substantivo', '主权成了症结。', 'Zhǔquán chéng le zhēngjié.', 'A soberania virou o impasse.', 'Diplomacia'],
    ['对等原则', 'duìděng yuánzé', 'princípio da reciprocidade', 'substantivo', '协议基于对等原则。', 'Xiéyì jīyú duìděng yuánzé.', 'O acordo se baseia na reciprocidade.', 'Diplomacia'],
    ['边缘政策', 'biānyuán zhèngcè', 'política do abismo', 'substantivo', '这不过是边缘政策。', 'Zhè búguò shì biānyuán zhèngcè.', 'Isso não passa de política do abismo.', 'Diplomacia'],
    ['神义论', 'shényìlùn', 'teodiceia', 'substantivo', '神义论追问恶的由来。', 'Shényìlùn zhuīwèn è de yóulái.', 'A teodiceia questiona a origem do mal.', 'Teologia e mito'],
    ['神化', 'shénhuà', 'apoteose / divinização', 'substantivo', '那是这种风格的神化。', 'Nà shì zhè zhǒng fēnggé de shénhuà.', 'Foi a apoteose desse estilo.', 'Teologia e mito'],
    ['末世论', 'mòshìlùn', 'escatologia', 'substantivo', '末世论讨论最终之事。', 'Mòshìlùn tǎolùn zuìzhōng zhī shì.', 'A escatologia trata das coisas últimas.', 'Teologia e mito'],
    ['礼仪规程', 'lǐyí guīchéng', 'liturgia', 'substantivo', '这套礼仪规程有几百年了。', 'Zhè tào lǐyí guīchéng yǒu jǐ bǎi nián le.', 'Esta liturgia tem séculos.', 'Teologia e mito'],
    ['异端', 'yìduān', 'heresia', 'substantivo', '它被定为异端。', 'Tā bèi dìng wéi yìduān.', 'Foi condenado como heresia.', 'Teologia e mito'],
    ['万神殿', 'wànshéndiàn', 'panteão', 'substantivo', '她进入了伟人的万神殿。', 'Tā jìnrù le wěirén de wànshéndiàn.', 'Ela entrou no panteão dos grandes.', 'Teologia e mito'],
    ['神谕', 'shényù', 'oráculo', 'substantivo', '神谕说得很隐晦。', 'Shényù shuō de hěn yǐnhuì.', 'O oráculo falava de forma enigmática.', 'Teologia e mito'],
    ['圣物', 'shèngwù', 'relíquia sagrada', 'substantivo', '圣物吸引了朝圣者。', 'Shèngwù xīyǐn le cháoshèngzhě.', 'A relíquia atraía peregrinos.', 'Teologia e mito'],
    ['教会分裂', 'jiàohuì fēnliè', 'cisma', 'substantivo', '教会分裂让信众分道扬镳。', 'Jiàohuì fēnliè ràng xìnzhòng fēndào yángbiāo.', 'O cisma separou os fiéis.', 'Teologia e mito'],
    ['超越性', 'chāoyuèxìng', 'transcendência', 'substantivo', '这首诗追求超越性。', 'Zhè shǒu shī zhuīqiú chāoyuèxìng.', 'Este poema busca a transcendência.', 'Teologia e mito'],
    ['先验地', 'xiānyàn de', 'a priori', 'advérbio', '那不能先验地知道。', 'Nà bùnéng xiānyàn de zhīdào.', 'Isso não se sabe a priori.', 'Locuções cultas'],
    ['更何况', 'gèng hékuàng', 'com mais razão ainda', 'advérbio', '更何况第二种情况不成立。', 'Gèng hékuàng dì èr zhǒng qíngkuàng bù chénglì.', 'Com mais razão ainda, o segundo caso não se sustenta.', 'Locuções cultas'],
    ['必要条件', 'bìyào tiáojiàn', 'condição indispensável', 'substantivo', '信任是必要条件。', 'Xìnrèn shì bìyào tiáojiàn.', 'A confiança é a condição indispensável.', 'Locuções cultas'],
    ['事实上的', 'shìshí shàng de', 'de fato', 'adjetivo', '她是事实上的负责人。', 'Tā shì shìshí shàng de fùzérén.', 'Ela é a responsável de fato.', 'Locuções cultas'],
    ['临时的', 'línshí de', 'provisório / ad hoc', 'adjetivo', '那是个临时的委员会。', 'Nà shì gè línshí de wěiyuánhuì.', 'Era um comitê provisório.', 'Locuções cultas'],
    ['比照适用', 'bǐzhào shìyòng', 'aplicar-se por analogia', 'verbo', '同样的规定比照适用。', 'Tóngyàng de guīdìng bǐzhào shìyòng.', 'A mesma norma se aplica por analogia.', 'Locuções cultas'],
    ['其他条件不变', 'qítā tiáojiàn búbiàn', 'mantidas as demais condições', 'advérbio', '其他条件不变，需求会下降。', 'Qítā tiáojiàn búbiàn, xūqiú huì xiàjiàng.', 'Mantidas as demais condições, a procura cai.', 'Locuções cultas'],
    ['初步看来', 'chūbù kànlái', 'à primeira vista', 'advérbio', '初步看来是有依据的。', 'Chūbù kànlái shì yǒu yījù de.', 'À primeira vista há fundamento.', 'Locuções cultas'],
    ['本身而论', 'běnshēn ér lùn', 'em si mesmo considerado', 'advérbio', '就本身而论这条规则并不不公。', 'Jiù běnshēn ér lùn zhè tiáo guīzé bìng bù bùgōng.', 'Em si mesma, esta regra não é injusta.', 'Locuções cultas'],
    ['最后关头', 'zuìhòu guāntóu', 'no último instante', 'substantivo', '协议在最后关头保住了。', 'Xiéyì zài zuìhòu guāntóu bǎozhù le.', 'O acordo foi salvo no último instante.', 'Locuções cultas'],
    ['乡愁', 'xiāngchóu', 'saudade da terra natal', 'substantivo', '她带着乡愁讲述。', 'Tā dài zhe xiāngchóu jiǎngshù.', 'Ela narrava com saudade da terra.', 'Emoções sutis'],
    ['忧郁', 'yōuyù', 'melancolia', 'substantivo', '一种安静的忧郁贯穿全书。', 'Yì zhǒng ānjìng de yōuyù guànchuān quán shū.', 'Uma melancolia discreta atravessa o livro.', 'Emoções sutis'],
    ['倦怠', 'juàndài', 'tédio / lassidão', 'substantivo', '漫长午后的倦怠。', 'Màncháng wǔhòu de juàndài.', 'O tédio das tardes longas.', 'Emoções sutis'],
    ['振奋', 'zhènfèn', 'exaltação / entusiasmo', 'substantivo', '那份振奋很短暂。', 'Nà fèn zhènfèn hěn duǎnzàn.', 'Aquela euforia foi breve.', 'Emoções sutis'],
    ['不安', 'bù’ān', 'inquietação', 'substantivo', '这消息引起了不安。', 'Zhè xiāoxi yǐnqǐ le bù’ān.', 'A notícia gerou inquietação.', 'Emoções sutis'],
    ['渴望', 'kěwàng', 'anseio', 'substantivo', '对逝去之物的渴望。', 'Duì shìqù zhī wù de kěwàng.', 'Um anseio pelo que se perdeu.', 'Emoções sutis'],
    ['宁静', 'níngjìng', 'serenidade', 'substantivo', '她以宁静面对此事。', 'Tā yǐ níngjìng miànduì cǐ shì.', 'Ela encarou aquilo com serenidade.', 'Emoções sutis'],
    ['义愤', 'yìfèn', 'indignação justa', 'substantivo', '他的义愤是有道理的。', 'Tā de yìfèn shì yǒu dàolǐ de.', 'A indignação dele era justa.', 'Emoções sutis'],
    ['遐想', 'xiáxiǎng', 'devaneio', 'substantivo', '她陷入了遐想。', 'Tā xiànrù le xiáxiǎng.', 'Ela mergulhou num devaneio.', 'Emoções sutis'],
    ['慰藉', 'wèijiè', 'consolo', 'substantivo', '他在音乐中找到慰藉。', 'Tā zài yīnyuè zhōng zhǎodào wèijiè.', 'Ele encontrou consolo na música.', 'Emoções sutis'],
  ],
};
